lightdash/lightdash

- .env
- docker-compose.gcloud.yml
- docker-compose.yml
- docker/dockerfile-dbt-server
- dockerfile
- docs/docusaurus.config.js
- packages/backend/src/index.ts
Running dbt in a separate docker container makes it very difficult to force dbt to recompile (needs SIGHUP).
Allow dbt to run as child process in production image.
> run dbt process in production docker image

- CHANGELOG.md
- packages/frontend/src/components/ChartConfigPanel.tsx
Close: #117 
Bug where we could group the only dimension available making the chart inaccessible  
Fix: 
- disable group button if there is only 1 dimension available
> Fix group the only dimension 

- CHANGELOG.md
- packages/frontend/src/components/ExploreSideBar.tsx
Now the scrollbar will not show only when the table-content overflows,
> Fix : Broken padding on sidebar #120

- CHANGELOG.md
- packages/frontend/src/App.tsx
- packages/frontend/src/components/ExploreSideBar.tsx
Now the sidebar will show at the very left side even 'UI becomes scrollable'
> Fix: #96 Side bar fixed at 100vh in UI

- README.md
- docs/docs/get-started/setup-an-existing-dbt-project.md
Updates to docs:
* Use `docker run -it` in all docs - closes #122 
* Update getting started guide for users with a local db. This documents the workaround in #91 but does not fix the underlying issues
> update docs docker run

- CHANGELOG.md
- packages/frontend/src/filters/FiltersForm.tsx
Ui fix input fields overlapping at  filterblock if used more than one
----------
> Ui fix input fields overlapping at  filterblock if used more than one

- CHANGELOG.md
- packages/frontend/src/index.css
#140, #142
(dimensions vs. measures) will not show any background: on hover
and all the items in it which are selectable are only toggle with pointer cursor
>  ui fix : Improved sidebar #142 + small scroll-x flicker while configure charts

- CHANGELOG.md
- docs/docs/references/metrics.md
- packages/backend/src/dbt/translator.ts
- packages/backend/src/exploreCompiler.mock.ts
- packages/backend/src/exploreCompiler.test.ts
- packages/backend/src/exploreCompiler.ts
- packages/backend/src/schema.json
- packages/common/src/index.ts
Closes: #58 
Preview:
Preview YAML:
```
meta:
metrics:
my_total_customers:
type: count_distinct
my_total_customers_plus:
type: number
sql: 2 + ${my_total_customers}
```
> Add non-aggregate metric types and support metric references

- packages/backend/src/queryBuilder.ts
- packages/common/package.json
- packages/common/src/index.ts
- packages/frontend/src/filters/DateFilterForm.tsx
- packages/frontend/src/filters/FiltersForm.tsx
- yarn.lock
Closes: #204 
Since date and timestamp are so identical I tried to use the same code as possible. 
It's still not ideal but there is a ticket in the backlog to refactor the entire filters components and logic.
Preview:
[<img src="https://cdn.loom.com/sessions/thumbnails/51f742a535594fb3b75f489b4fc9fd13-with-play.gif" />](https://www.loom.com/share/51f742a535594fb3b75f489b4fc9fd13)
> add timestamp filters

- CHANGELOG.md
- packages/backend/package.json
- packages/backend/src/config/parseConfig.ts
- packages/backend/src/dbt/dbtRpcClientBase.ts
- packages/backend/src/errors.ts
- packages/backend/src/jsonSchemas/lightdashConfig/v1.json
- packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts
- packages/backend/src/projectAdapters/dbtGithubProjectAdapter.ts
- packages/backend/src/projectAdapters/projectAdapter.ts
- yarn.lock
Closes #272
Also run `dbt deps` when recompiling projects. It's essential now that we pull raw project files from GitHub. The user doesn't have a chance to run `dbt deps` themselves in that case. So we run it for you
Closes #305
> Users are able to link a project to a Github repo with a dbt project

- CHANGELOG.md
- packages/frontend/src/providers/ExplorerProvider.tsx
> fix: remove sorts when field is toggled in explorer

- CHANGELOG.md
- packages/frontend/src/hooks/useQueryResults.tsx
Closes: #384
Each commit represents an improvement: 
- only show error when runs the query
- ~remove prop drilling and improve state management by having the results query in the main explorer provider~
- ~update explorer url params on query run~
@silentninja since you were working on the same problem in #388, would you like to review these changes? Is easier to review by checking each commit.
Update: 
Updated PR to only fix the error drawer
> Explorer provider improvements

- CHANGELOG.md
- packages/backend/src/@types/knex-tables.d.ts
- packages/backend/src/database/entities/savedQueries.ts
- packages/backend/src/database/migrations/20210831103040_add_table_calculations_table.ts
- packages/frontend/src/components/Explorer.tsx
- packages/frontend/src/pages/SavedExplorer.tsx
Closes #377
Closes #266 
Table calculations are now saved with a saved chart
Note that this will only save “selected” table calculations, any table calculations you have in the explorer but don’t include in the chart, will not be saved.
@ZeRego this makes me wonder if we should have the table dimensions as selectable
> Saved table calculations to db

- dockerfile
- dockerfile-demo
- packages/backend/src/database/migrations/20210831103040_add_table_calculations_table.ts
Seems like there is a bug in the python+nodejs docker image
https://github.com/nikolaik/docker-python-nodejs/issues/31
Until then we need to pin the docker image to the last version that worked.
> fix: pin docker image

- packages/backend/src/queryBuilder.mock.ts
- packages/backend/src/queryBuilder.ts
Closes #396
* Moves `LIMIT` clause out of CTE for table calculations
* Moves `ORDER BY ` clause out of CTE for table calculations
> Ordering is lost with table calculations

- packages/backend/src/dbt/dbtRpcClientBase.ts
- packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts
- packages/common/src/index.ts
Thanks to @jtcohen6 on https://github.com/dbt-labs/dbt/issues/3702 we're actually able to get the entire `manifest.json` from the dbt rpc server.
> use get-manifest method rather than compile in dbt rpc

- CHANGELOG.md
- packages/frontend/src/components/Explorer.tsx
- packages/frontend/src/components/RefreshButton.tsx
- packages/frontend/src/components/ResultsTable.tsx
- packages/frontend/src/hooks/useChartConfig.tsx
- packages/frontend/src/hooks/useExplorerRoute.ts
- packages/frontend/src/hooks/useQueryResults.tsx
- packages/frontend/src/pages/SavedExplorer.tsx
- packages/frontend/src/providers/ExplorerProvider.tsx
This PR adds local state tracking for the Explore data. This should provide a clear separation of concern between actions/data that are displaying the current query(displaying charts) vs the ones dealing with the next query(filters). 
This should help clear up few bugs and makes way for new possibilities. As a bonus writing an integration test should be easier since the queryResults prop has been removed.
Fixes #77
https://www.loom.com/share/a356c6d446e941b7a6bb30d5b3909c98
> Add State tracking and replace queryResult prop drill with hooks

- CHANGELOG.md
- packages/backend/src/queryBuilder.mock.ts
- packages/backend/src/queryBuilder.ts
Fixes error in snowfalke, which assumes all identifiers are uppercase if not quoted
—
> Add quotes to aliases in order by clause

- docker/docker-compose.dev.yml
This adds a volume to docker compose to cache node_modules. This makes it substantially faster to refresh the dev environment when changing `lightdash.yml`, dependencies, or compiling common.
> Node modules volume

- docs/docs/get-started/setup-a-github-project.md
Improve Heroku docs since we now have the `target` field when deploying to Heroku with a github repo.
> Explain target field in heroku deployment

- CHANGELOG.md
- packages/frontend/src/components/RefreshButton.tsx
- packages/frontend/src/hooks/useQueryResults.tsx
- packages/frontend/src/pages/SavedExplorer.tsx
Closes: #133 
Now that we have a pristine state we can use useQuery without workarounds. 
The 'run query' button syncs the pristine state and the useQueryResults hook handles the rest.
> fix(#133): sync state on run query button click

- packages/e2e/cypress/integration/explore.spec.ts
- packages/e2e/cypress/support/commands.ts
Make sure we pre compile the project before running the tests to avoid timeouts in the test.
> fix: pre compile project before running e2e tests

- packages/frontend/src/components/ResultsTable.tsx
Not a life threatening issue, but getting a lot stuff in the console because of those missing keys in `ResultsTable`
```
index.js:1 Warning: Each child in a list should have a unique "key" prop.
Check the render method of `ResultsTable`. See https://reactjs.org/link/warning-keys for more information.
at DragDropContext (http://localhost:3000/static/js/vendors~main.chunk.js:250755:19)
at ResultsTable (http://localhost:3000/static/js/main.chunk.js:10501:91)
at div
at div
```
> missing keys in results table

- CHANGELOG.md
- packages/backend/src/config/parseConfig.mock.ts
- packages/backend/src/config/parseConfig.test.ts
- packages/backend/src/config/parseConfig.ts
- packages/backend/src/dbt/profiles.ts
- packages/backend/src/jsonSchemas/lightdashConfig/v1.json
- packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts
- packages/backend/src/projectAdapters/dbtCloudIdeProjectAdapter.ts
- packages/backend/src/projectAdapters/dbtGitProjectAdapter.ts
- packages/backend/src/projectAdapters/dbtGithubProjectAdapter.ts
- packages/backend/src/projectAdapters/dbtGitlabProjectAdapter.ts
- packages/backend/src/projectAdapters/dbtLocalCredentialsProjectAdapter.ts
- packages/backend/src/projectAdapters/dbtLocalProjectAdapter.ts
- packages/backend/src/projectAdapters/dbtRemoteProjectAdapter.ts
- packages/backend/src/projectAdapters/projectAdapter.ts
- packages/backend/src/services/ProjectService.ts
- packages/backend/src/types.ts
- packages/common/src/index.ts
- packages/frontend/src/components/ProjectConnection/DbtForms/DbtCloudForm.tsx
* Fix bug where project adapter attempted to start before credentials were available
* Added new adapter type dedicated to handling dbt projects with custom credentials
* Added destroy method to clean up adapter resources
* Fix field name typo in dbt cloud form
* Remove unused project config fields (`port, target,profiles_dir` on git adapters and `port` on local adapters)
> Fix adapter for local credentials

- CHANGELOG.md
- packages/frontend/src/App.tsx
- packages/frontend/src/components/ExploreSideBar.tsx
- packages/frontend/src/hooks/useCompiledSql.tsx
- packages/frontend/src/hooks/useExplore.tsx
- packages/frontend/src/hooks/useExplores.tsx
- packages/frontend/src/hooks/useOrganizationUsers.ts
- packages/frontend/src/hooks/useProject.ts
- packages/frontend/src/hooks/useProjects.ts
- packages/frontend/src/hooks/useQueryError.ts
- packages/frontend/src/hooks/useQueryResults.tsx
- packages/frontend/src/hooks/useRefreshServer.tsx
- packages/frontend/src/hooks/useServerStatus.tsx
When query response returns 401, the user must be redirected to login page
I've seen some redundant code in the hooks that fetch data and deal with issues.
So I created a common hook that deal with 401 and other errors:
```
const useQueryError = () => {
const queryClient = useQueryClient();
const [errorResponse, setErrorResponse] = useState<any>(null);
const {
errorLogs: { showError },
} = useApp();
useEffect(() => {
(async function doIfError() {
if (errorResponse) {
// @ts-ignore
const { statusCode } = errorResponse;
if (statusCode === 401) {
await queryClient.invalidateQueries('health');
} else {
const { message } = errorResponse;
const [first, ...rest] = message.split('\n');
showError({ title: first, body: rest.join('\n') });
}
}
})();
}, [errorResponse]);
return [errorResponse, …
```
> redirect to login page if unauthorized 401

- docs/docs/guides/how-to-join-tables.md
The indenting in the docs for joining tables was incorrect.
> fix indenting in join example

- render.yaml
Don't run rudderstack events on PR previews
> fix sync to render pr previews

- CHANGELOG.md
- packages/frontend/src/components/ChartConfigPanel.tsx
- packages/frontend/src/components/SimpleChart.tsx
- packages/frontend/src/hooks/useChartConfig.tsx
Closes: #487 
When we have multiple metrics + grouped dimension the labels are formatted like `[group_dimension_value] metric name`
Preview:
FYI: I opened a separate bug for the legend overlap #541
> fix(#487): support multiple metrics with a grouped dimension

- packages/backend/src/dbt/dbtCliClient.ts
- packages/backend/src/index.ts
These only show in traces when an GET request triggers a recompile. When hitting the "refresh" button, the work happens async and traces don't render.
> chore: instrument dbt cli calls

- CHANGELOG.md
- dockerfile
- dockerfile-demo
- docs/docs/faqs/faqs.md
- docs/docs/get-started/setup-lightdash/connect-project.mdx
- packages/backend/src/schema.json
Closes #726
No major changes to `manifest.json`. `meta` can now be used in the `config` block of a dbt model but I've decided not to support that yet.
I've tested this with manifests from `0.20.0` and `0.21.0` without errors
> build(#726): update dbt to 0.21.0

- docker-compose.oauth.yml
- docker-compose.service-account.yml
- dockerfile
- dockerfile-demo
- docs/docs/faqs/faqs.md
- packages/backend/src/dbt/dbtRpcClientBase.ts
Since we only accept credentials through the UI with a service account, we no longer need to support oauth.
Improvements:
* slimmer docker image
* no more scanning dbt logs
—
> build: remove gcloud oauth mode for bigquery

- packages/frontend/src/components/SimpleChart.tsx
- packages/frontend/src/hooks/useChartConfig.tsx
This PR sets the xAxis on a chart to an [echarts 'time' type](https://echarts.apache.org/en/option.html#xAxis.type).
**Before**
* Points are equally spaced even though timestamps have very irregular spacing
* Labels are ISO timestamp strings
* Chart is in wrong order with most recent on the left (because of the sort direction)
**After**
* Points are correctly spaced in time
* Labels are human friendly
* Chart is always in increasing time order from left to right
**Considerations** 
* For bar style (where the axes are flipped) - it didn't render with `time` types, so it defaults to categorical as before.
* The chart uses linear interpolation. e.g. in the second image above, there is a huge gap between the peak value of 50 and the next value of 2 (row above 50). This is rendered as a long …
> fix: use time-series layout for time-like dimensions in charts

- docker/docker-compose.dev.yml
When using a Docker-compose config, the main codespace container needs to remain running indefinitely. Since the Dockerfile has an entrypoint script which ends up exiting, the devcontainer config for the codespace needs to override the entrypoint and command to provide a simple script which runs forever. This allows the main codespace container to stay running and connectable.
I verified that running a codespace on this branch remains available.
Note that Codespaces does not yet support the `workspaceFolder` property in devcontainer.json, but the codespace itself does launch with this configuration. The source code is mounted to `/workspaces/lightdash`.
> Fix codespace startup

- packages/frontend/src/components/SimpleChart.tsx
Closes #752
When showing multiple series, echarts was showing some strange behaviour for time-series plots.
This seemed to be fixed by providing explicit encoding from the data to each series.
This change also adds:
* More reliable series labels
* Better tooltips
—
> fix(#752): encode echarts dimensions explicitly

- packages/frontend/src/components/Explorer.tsx
- packages/frontend/src/components/UserSettingsModal/ProjectManagementPanel.tsx
Closes: #543 
Changes: 
- access project page from explore 
- rename button from 'Edit' to 'Settings' and changed icon
Preview:
> fix: make it easier to find the project settings page

- docs/docs/get-started/setup-lightdash/add-metrics.mdx
There was a broken link in the documentation that was blocking deployment to docs.lightdash.com
Discovered by @drernie on #803
—
> docs: fix broken link

- packages/backend/src/dbt/profiles.ts
Many dbt projects customise the destinations of materialized tables depending on the value of the `target` name in `profiles.yml` 
Since we generate a `profiles.yml` under-the-hood, the name we choose for the `target` will influence the destinations of dbt models, meaning we could look for tables in the wrong places in the warehouse if we don’t set `target` correctly. 
Currently we use `lightdash_target` but many dbt projects use [`generate_schema_name_for_env`](https://docs.getdbt.com/docs/guides/debugging-schema-names#4-put-the-two-together) that rely on the target name being `prod`
I suggest we use `prod` by default and I’ve opened #801 to make more permanent change.
—
> fix: use prod as default dbt target

- packages/frontend/src/components/SimpleChart.tsx
- packages/frontend/src/pages/Dashboard.tsx
Attempting to improve #781 
This does 80% of the job by forcing tooltips to stay inside the chart. However if the tooltip is much larger than the chart then it still overflows and hides behind others.
@ZeRego I couldn't find an option to increase the `z-index` in e-charts. Maybe there's something simpler I can do
> fix: confine tooltips to charts

- packages/backend/src/config/parseConfig.ts
- packages/backend/src/dbt/dbtCliClient.ts
- packages/backend/src/health.ts
- packages/backend/src/models/ProjectModel/ProjectModel.mock.ts
- packages/common/src/index.ts
- packages/frontend/package.json
- packages/frontend/src/App.tsx
- packages/frontend/src/components/ChatWidget.tsx
- yarn.lock
After having Lightdash open for 10seconds after login, the chat widget appears.
It suggests messaging the team and signing up for Lightdash Cloud.
This is off by default and enabled by providing `PAPERCUPS_TOKEN` to the backend.
* @hamzahc1 we can change the styling, obviously the purple is jarring haha
> feat: add papercups chat widget

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/analytics/client.ts
- packages/backend/src/models/User.ts
@ZeRego since we don't add opted-in to the database, we only capture this on register. 
This means the `identify` command just has an additional argument. It's not as clean as adding it to the db (which would also enable us to later opt-out).
> chore: send opted-in with identify

- packages/frontend/src/pages/Dashboard.tsx
Closes: #874 Closes: #873 
@owlas I wasn't able to reproduce these bugs locally but from my investigation they seem to relate to unnecessary re-renders in the dashboard page.
> fix: prevent unnecessary renders in dashboard page

- packages/backend/src/database/migrations/20211118105119_add_markdown_and_loom_dashboard_tiles.ts
> fix: delete tiles with types markdown or loom during rollback

- packages/backend/src/config/parseConfig.ts
- packages/backend/src/projectAdapters/dbtGitlabProjectAdapter.ts
- packages/backend/src/projectAdapters/projectAdapter.ts
- packages/common/src/index.ts
- packages/frontend/src/components/ProjectConnection/DbtForms/GitlabForm.tsx
Allows users to specify a domain host for gitlab. This is useful if user's are self-hosting a gitlab instance on their own domain.
> feat: self hosted gitlab

- packages/frontend/src/components/Home/LatestCard.tsx
- packages/frontend/src/components/Home/LatestDashboards.tsx
- packages/frontend/src/components/Home/LatestSavedCharts.tsx
n/a
- Add skeleton loading to latest cards
> style: add skeleton loading to latest cards

- packages/frontend/src/components/Home/LatestSavedCharts.tsx
> fix: make latest saved charts full width

- packages/frontend/src/hooks/useChartConfig.tsx
Closes: #864
The chart was erroring when there was a dimension with a boolean value as a name. We now force the dimension name to be a string.
> fix: handle grouping by boolean dimension

- docker-compose.yml
- docker/docker-compose.dev.yml
- examples/full-jaffle-shop-demo/docker-compose.yml
First Line of Code is wrong
version: "3.9"  #does not exist, docker compose correct latest version at the time of this writing is 
version: "3.8"
Closes:
> ci: fix docker compose yml version 

- .github/CONTRIBUTING.md
This PR adds the `demo login details` to the instructions to run Lightdash locally.
> Add demo login details to run instructions

- .github/CONTRIBUTING.md
This PR updates the contributing instructions with docker to mention the memory needed for Lightdash to run locally
> docs: make a note of the memory docker requires to run the container

- packages/backend/src/services/warehouseClients/SnowflakeWarehouseClient.ts
Closes: #1123
Closes: #1127 
The snowflake client is passed a default database (the value provided by the user in the warehouse settings page). This means that `SHOW COLUMNS` defaults to showing columns only in that default database. 
To get columns across all databases we need to run `SHOW COLUMNS IN ACCOUNT` which gets all columns across all databases. [Snowflake docs on `SHOW COLUMNS`](https://docs.snowflake.com/en/sql-reference/sql/show-columns.html)
> fix(#1223,#1127): get columns from all snowflake databases and schemas

- packages/backend/src/services/warehouseClients/RedshiftWarehouseClient.ts
- packages/frontend/src/components/ProjectConnection/WarehouseForms/PostgresForm.tsx
- packages/frontend/src/components/ProjectConnection/WarehouseForms/RedshiftForm.tsx
Closes: 
Adds support for setting SSL mode to `no-verify` via the UI for postgres connections. This is especially helpful for connecting to postgres databases on heroku
> feat: support no-verify for postgres connections

- packages/frontend/src/components/TableTree.tsx
- packages/frontend/src/hooks/useFilters.ts
Closes: #922 
@ZeRego @nathaliabj - I need some help
1. How can I prevent the dimension from being toggled when hitting the filter button? i.e. when I click the filter button it toggles the dimension state
2. Anyone have a better idea for showing active/not-active state for the filter icon? When active, it can't be clicked again. And it must render both when the dimension is active and not. See screenshot below for the four cases:
In order from top to bottom:
* dimension selected, filter active
* dimension not selected, filter active
* dimension selected, filter not active
* dimension not selected, filter not active
> feat(#922): add filters from sidebar

- packages/frontend/src/components/SimpleChart/index.tsx
Closes #571 
For **categorical x-axes only** rotate labels and force them to render for every value on the chart.
> fix(#571): add axis tooltip for categorical plots

- .github/workflows/release-on-merge.yml
- release.config.js
Closes: #1286
Merge to `main` to publish a release. 
Requires using[Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) in order to categorize the appropriate release type:
```
fix: a commit of the type fix patches a bug in your codebase (this correlates with [PATCH](http://semver.org/#summary) in Semantic Versioning).
feat: a commit of the type feat introduces a new feature to the codebase (this correlates with [MINOR](http://semver.org/#summary) in Semantic Versioning).
BREAKING CHANGE: a commit that has a footer BREAKING CHANGE:, or appends a ! after the type/scope, introduces a breaking API change (correlating with [MAJOR](http://semver.org/#summary) in Semantic Versioning). A BREAKING CHANGE can be part of commits of any type.
```
Publishing a release will:
- update …
> ci: add semantic release workflow

- .github/workflows/main.yml
Ignores alpha and beta tags. 
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
> ci: ignore alpha tags for docker build workflow

- packages/common/src/index.ts
- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
- packages/frontend/src/components/common/MonthAndYearInput.tsx
- packages/frontend/src/components/common/WeekPicker.tsx
- packages/frontend/src/components/common/YearInput.tsx
Closes: 
For dimensions that have the time interval 'week' it should display a week picker
<a href="https://www.loom.com/share/9b7e9dda4a624737b5968e885666b409">
<p>Lightdash - week picker - Watch Video</p>
</a>
<a href="https://www.loom.com/share/5b74cd099a6a4abb96aeffa7121543bc">
<p>Lightdash - Month and Year pickers</p>
</a>
> feat(filters): add week, month and year pickers [skip ci]

- packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilters.styles.ts
- packages/frontend/src/components/DashboardFilter/DashboardFilter.styles.tsx
Closes: #1335 
This PR aligns and adds space to the active filter tags in the dashboard
> style(dashboard): alignment and space between tags

- packages/frontend/src/components/DashboardFilter/index.tsx
- packages/frontend/src/pages/Dashboard.tsx
Closes: #1334 
This PR disables the filter button when there are no tiles in the dashboard
> fix(dashboards): filter button is disabled when there are no tiles in the dashboard

- packages/common/src/index.ts
- packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilter.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
- packages/frontend/src/components/common/Filters/FieldAutoComplete.tsx
- packages/frontend/src/components/common/Filters/FilterGroupForm.tsx
- packages/frontend/src/components/common/Filters/FilterRuleForm.tsx
- packages/frontend/src/components/common/Filters/configs.ts
- packages/frontend/src/components/common/Filters/index.tsx
- packages/frontend/src/hooks/useFilters.ts
Closes: 
When we added a filter to the dashboard or changed the operator, without changing the value it would create a filter sql with an empty value. the UI would show a default value but it wasn't being applied.
> fix(filters): set default filter values

- packages/common/src/index.ts
- packages/common/src/types/dashboard.ts
- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/DashboardTiles/TileForms/TileModal.tsx
- packages/frontend/src/components/Explorer.tsx
- packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx
Closes: #1327 
Default uses smaller tiles for big number charts.
**Todo**
- Get it working for "add tile" button on edit dashboard view
> style: bignumber charts have smaller tiles by default

- packages/frontend/src/pages/Dashboard.tsx
- packages/frontend/src/providers/DashboardProvider.tsx
Closes: #1356
- Hide filters section
- Don't apply filters to charts
- Reset filters when going back to view mode
<a href="https://www.loom.com/share/d318a1f4b0ee4fdc8c59b4684b6ba5cc">
<p>Lightdash - 15 February 2022 - Watch Video</p>
</a>
> fix(dashboards): hide+disable dashboard filters when in edit mode

- packages/frontend/src/components/RefreshButton.tsx
Closes: #1392 
Whenever the "Run query" (`RefreshButton.tsx`) is visible, the user can use `cmd+enter` to execute the query in place of pressing the button.
This is also true whenever there is a modal open, even if the "Run query" button is in the background. This won't be a problem since the "Run query" button only exists on the explorer and the settings modal over the explorer is planned to be moved.
> feat: add cmd+enter hotkey to RefreshButton

- packages/common/src/index.ts
- packages/e2e/cypress/integration/explore.spec.ts
- packages/frontend/src/components/ResultsTable/CellContextMenu.tsx
- packages/frontend/src/components/ResultsTable/ColumnHeaderContextMenu.tsx
- packages/frontend/src/components/ResultsTable/ResultsTable.tsx
- packages/frontend/src/components/TableCalculationModal.tsx
- packages/frontend/src/components/TableTree.tsx
- packages/frontend/src/components/common/Filters/index.tsx
- packages/frontend/src/hooks/useColumns.tsx
- packages/frontend/src/hooks/useFilters.ts
- packages/frontend/src/providers/ExplorerProvider.tsx
- packages/frontend/src/types/react-table-config.d.ts
Closes: #86 
Right-click a table cell and you can filter to values including that value. Right-click a column header and create an empty filter for that column.
**Todo**
- Get data to refresh after filter added via cell
- Get data to not refresh after filter added via column header
- Improve right-click target for column headers (only on text currently)
- Show filter indicator in column headers?
- Show icon suggesting right-click on cell/column header hover? Similar to the sidebar
https://www.loom.com/share/9851baae02ad469ba43071d0691ddac1
> feat: add filter from table cells and headers

- packages/backend/src/exploreCompiler.test.ts
- packages/common/src/index.ts
Closes: #1346
Fixed regex in friendlyName to allow for purely numeric words in a field name whether at the start or otherwise
> fix: numbers are no longer removed from column name #1346

- packages/frontend/src/components/Explorer.tsx
- packages/frontend/src/components/LightdashVisualization/index.tsx
- packages/frontend/src/components/SimpleTable/index.tsx
Closes: 
Data in table visualisation can no longer be grouped/pivoted.
> fix(charts): disable chart configuration for table visualization

- packages/backend/src/queryBuilder.ts
- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
closes: #1452, closes: #1466
In: https://github.com/lightdash/lightdash/blob/5e742cb32c761a805c32c491bd188f5b6834997e/packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx#L111-L123
whenever the field is empty, it defaults to 1, so even if you hit backspace, you can only add the number to 1 as explained in #1452 
By adding a minimum value of 1, it allows you to enter any numeric value and not get default to 1.
<a href="https://www.loom.com/share/fa859128d8ae49918b4f1356386b65ea">
<p>Lightdash - fix-numeric-input - Watch Video</p>
</a>
> fix(filters): add min value to input instead of 'or' operator

- packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
- packages/frontend/src/hooks/useCartesianChartConfig.ts
- packages/frontend/src/hooks/useEcharts.ts
- packages/frontend/src/hooks/usePivotDimensions.ts
Closes: #531
- allow dimensions/metrics/table calculations to be used in both axis
- allow dimensions/metrics/table calculations to be used to pivot data
<a href="https://www.loom.com/share/f89a56c05ff84cdeb538a30826947b19">
<p>Lightdash - axis independent from field type - Watch Video</p>
</a>
> feat(charts): allow all field types to be applied to both axis and pivoting

- .github/workflows/release-on-merge.yml
After release, trigger a helm chart update. 
There are prerequisites for adding this trigger:
> fix: trigger helm chart update upon release

- packages/frontend/src/components/Home/LatestSavedCharts/LatestSavedCharts.style.tsx
- packages/frontend/src/components/Home/LatestSavedCharts/index.tsx
Quick update in the view all button and title of the saved charts panel in the home page
> style: update view all button on the charts panel in home page

- packages/common/src/openapi/schemas/UpdateDashboard.json
- packages/common/src/openapibundle.json
- packages/frontend/src/components/common/EditableHeader.tsx
- packages/frontend/src/pages/Dashboard.tsx
Closes: #1514 
This PR updates the logic to edit a dashboard title only when on edit mode and after clicking save.
The component we are currently using from blueprint does not allow for this functionality to happen, this PR work around that and forces the update.
https://www.loom.com/share/e7590b3665ce4536b96a24f540589339
> fix: save to be active when title changes and send request on save

- dockerfile
Fixes python3 Header filer error when running docker-compose build
> fix: add python3-dev to dockerfile

- packages/frontend/package.json
- packages/frontend/src/components/AddColumnButton.tsx
- packages/frontend/src/components/ReactHookForm/Form.tsx
- packages/frontend/src/components/TableCalculationHeaderButton.tsx
- packages/frontend/src/components/TableCalculationModal.tsx
- packages/frontend/src/components/TableCalculationModels/CreateTableCalculationModal.tsx
- packages/frontend/src/components/TableCalculationModels/DeleteTableCalculationModal.tsx
- packages/frontend/src/components/TableCalculationModels/TableCalculationModal.styles.ts
- packages/frontend/src/components/TableCalculationModels/TableCalculationModal.tsx
- packages/frontend/src/components/TableCalculationModels/UpdateTableCalculationModal.tsx
- packages/frontend/src/components/TableCalculationModels/index.tsx
- packages/frontend/src/components/common/modal/BaseModal.tsx
Closes: #492 
- Wrap sql into multiple lines.
- Expand modal to edit really big sql queries. The library we use for edit sql doesn't have responsive feature :'(  so I couldn't have the input height match the modal height.
<a href="https://www.loom.com/share/4364f461e8bd436db2e919e5cb98a068">
<p>Lightdash - expand table calculation modal - Watch Video</p>
</a>
> fix: wrap table calculation sql + expand modal

- packages/frontend/src/components/Explorer.tsx
Closes: #1226
When a chart is saved (and there are no charts, so `save as` is not affected) it collapses the chart. 
Because it refreshes the `Explorer` componen, initializing the `vizIsOpen` state variable again
> fix: dont collapse chart on save

- packages/frontend/src/components/Explorer/VisualizationCardOptions/VisualizationCardOptions.style.tsx
- packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
Closes: #1445 
This PR groups the chart types in a dropdown
> feat: group chart types in a dropdown

- packages/frontend/src/components/ChartConfigPanel/ChartConfigPanel.styles.ts
- packages/frontend/src/components/ChartConfigPanel/FieldLayoutOptions.tsx
- packages/frontend/src/components/ChartConfigPanel/Series/BasicSeriesConfiguration.tsx
- packages/frontend/src/components/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
- packages/frontend/src/components/ChartConfigPanel/Series/Series.styles.ts
- packages/frontend/src/components/ChartConfigPanel/Series/SingleSeriesConfiguration.tsx
- packages/frontend/src/components/common/Filters/FieldAutoComplete.tsx
Closes: #1591 
This PR updates the styling for all the chart config tabs to mirror designs
https://www.loom.com/share/066acae274a548f9bc1f7b2c5136ea34
> style: apply final styling to chart config

- packages/backend/src/database/entities/organizations.ts
- packages/backend/src/database/migrations/20220330140655_alter_organisation_add_chart_colours.ts
- packages/backend/src/models/OrganizationModel.ts
- packages/common/src/index.ts
Closes: #1572
Add backend, db migration for storing chart_colors inside organization table
GET
PATCH
> feat: add colour palette on organization settings

- packages/frontend/src/hooks/useEcharts.ts
**Explore view (left before, right after)**
**Narrow tile (top before, bottom after)**
We take a small hit here because now long labels reduce the chart area greatly in very narrow tiles, we need to be smarter to conditionally truncate the text or something. I think this is a good solution for now.
** Wide tile (top before, bottom after)**
Closes #1622
> fix: show whole tick label on charts (no truncate)

- packages/frontend/src/components/ChartConfigPanel/Series/SeriesColorPicker.tsx
Closes: #1531
Don't close the popup on change (see related bug)
> fix: do not close color picker on change

- packages/frontend/src/components/Explorer.tsx
Closes: #1653
Show `save changes` instead of `save chart` when applies. Disable save button if no changes have been made.
> feat: save changes button on charts + disabled button

- packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
- packages/frontend/src/components/DashboardFilter/index.tsx
- packages/frontend/src/hooks/dashboard/useDashboard.tsx
- packages/frontend/src/pages/Dashboard.tsx
- packages/frontend/src/providers/DashboardProvider.tsx
Closes: #1637 
This PR fixes filters labels not displaying properly when dashboard has not saved tiles, and filters are being added on edit mode.
For this i have added a state context in the dashboard provider that will only be used in this situation.
> fix: dashboard cross filtering cause an error

- packages/backend/src/models/DashboardModel/DashboardModel.ts
- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/services/DashboardService/DashboardService.test.ts
- packages/backend/src/services/DashboardService/DashboardService.ts
- packages/common/src/openapi/paths/projectDashboards.json
- packages/common/src/openapibundle.json
- packages/frontend/src/components/Explorer.tsx
- packages/frontend/src/hooks/dashboard/useDashboards.tsx
Closes: #1631
Adds optional parameter chartId ? to `/projects/uuid/dashboards` endpoint for doing the filtering 
> http://localhost:8080/api/v1/projects/3675b69e-8324-4110-bdca-059031aa8da3/dashboards?chartId=12
> http://localhost:8080/api/v1/projects/3675b69e-8324-4110-bdca-059031aa8da3/dashboards
> feat: confirm user wants to delete chart with linked dashboards

- packages/frontend/src/pages/Dashboard.tsx
Closes: #1209
Show browser confirm popup when trying to leave / refresh the page with unsaved changes 
Capturing navigation using `history.block`
Capturing refresh using `beforeunload` (chromium on linux) 
capturing refresh using `before unload` (chrome on mac)
> feat: warn leaving dashboards

- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
Closes: 
Prevents creating a history entry when entering edit mode.
Without this, the back button in the browser takes you out edit mode back to view mode but doesn't actually save your changes.
> fix: replace history on enter dashboard edit mode

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/services/SavedChartsService/SavedChartService.ts
- packages/common/src/openapi/paths/projectSavedCharts.json
- packages/common/src/openapibundle.json
Closes: #1717
Take optional parameter `duplicateFrom` on the save endpoint to save new chart using existing chartUuid
```
curl 'http://localhost:3000/api/v1/projects/3675b69e-8324-4110-bdca-059031aa8da3/saved?duplicateFrom=b14c8165-3874-4076-8258-e599398e9d35' -H 'Content-Type: application/json' 
```
```
{"status":"ok","results":{"uuid":"8b2e39b3-dbe8-4059-aa7f-1eae1459a12a","projectUuid":"3675b69e-8324-4110-bdca-059031aa8da3","name":"test","tableName":"customers","updatedAt":"2022-04-08T14:49:00.042Z","metricQuery":{"dimensions":["customers_customer_id"],"metrics":["customers_unique_customer_count"],"filters":{},"sorts":[{"fieldId":"customers_unique_customer_count","descending":true}],"limit":500,"tableCalculations":[]},"chartConfig":{"type":"cartesian","config":{"layout":{"xField":"custo …
```
> feat: duplicate chart endpoint

- packages/frontend/src/components/Explorer.tsx
closes #1706
Fixes a bug on save chages button for table and bigint
This is why it happens. For table and bignuberm, the config is set to `undefined` but data comes with `null` 
I'm updating the default
> fix: fix save changes disabled button for bigint and tables

- packages/frontend/src/components/Explorer.tsx
- packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.styles.tsx
- packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx
Closes: #1665
New modal for adding charts to dashboards (add new + add to existing dashboard) 
Edge case: adding with no dashboards (will always show the "add new" first)
> feat: add-new-chart-to-dashboard

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/Explorer.tsx
- packages/frontend/src/pages/Dashboard.tsx
Closes: #1732
Explore from here on dashboards
This time I'm loadign a savedChart and don't allow overrides .
See this other PR for more details https://github.com/lightdash/lightdash/pull/1747#issuecomment-1096280877
> feat: explore from here saved

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/services/DashboardService/DashboardService.ts
- packages/common/src/openapi/paths/projectDashboards.json
- packages/common/src/openapi/schemas/CreateDashboard.json
- packages/common/src/openapibundle.json
Closes: #1753
Add endpoint to duplicate dashboard
> feat: endpoint duplicate dashboard

- packages/frontend/src/components/Explorer.tsx
- packages/frontend/src/components/SimpleChart/index.tsx
- packages/frontend/src/components/SimpleStatistic/index.tsx
- packages/frontend/src/components/SimpleTable/index.tsx
Closes: #1687
Saved charts should be open by default 
I initially started adding `from` arguments to history.state on all components pointing to Explorer, but then I realized that the  behaviour we really  want is to open the chart when is `/saved/` , I confirmed this with @PriPatel
> feat: saved charts should be open by default

- packages/common/src/index.ts
Closes: #1751
Fixes JS rounding issue with `percent` format
Raw
With format
> fix: fix format decimals

- packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
- packages/frontend/src/hooks/useCartesianChartConfig.ts
Closes: #1765
fix bignumber and table saved charts
This was because we try to load the default chart, we should only do that if the chart doesn't have chartConfig -> is not saved
> fix: fix bignumber and table saved charts

- packages/frontend/src/components/Explorer.tsx
- packages/frontend/src/components/Home/LatestSavedCharts/index.tsx
- packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx
- packages/frontend/src/components/common/ActionCardList.tsx
- packages/frontend/src/components/common/ActionCardList/ActionCardList.style.tsx
- packages/frontend/src/components/common/ActionCardList/index.tsx
- packages/frontend/src/components/common/modal/ActionModal.tsx
- packages/frontend/src/components/common/modal/ModalActionButtons.tsx
Closes: #1667 
This PR brings more consistency in the copy of the option menu across the site.
It also adds the possibility to add a chart to a dashboard from within the saved queries page.
> feat: bring consistency around chart ations 2

- packages/frontend/src/components/Explorer.tsx
- packages/frontend/src/components/common/modal/ModalActionButtons.tsx
- packages/frontend/src/hooks/dashboard/useDashboard.tsx
- packages/frontend/src/hooks/useSavedQuery.ts
Closes: #1767 
This PR adds a link to the new duplicated chart/dashboard in the success message when it is duplicated from a dashboard/chart saved list.
However the user will be automatically redirected to the new duplicated chart when one is duplicated from within the explorer.
https://www.loom.com/share/2dab4eaa887b4d8caac7b3b01c40f049
> feat: navigate to chart when duplicated 2

- packages/backend/src/models/SavedChartModel.ts
- packages/frontend/src/components/NavBar/HelpMenu/HelpMenu.styles.tsx
Closes: #1779 
Update styling on the notifications icon:
- Remove grey icons when there are no notifications to see
- Reduced margin between help and notification icon
- Added hover state to the notifications button
> style: give hover state and update notification widget

- packages/frontend/src/components/Explorer.tsx
Closes: #[1805](https://github.com/lightdash/lightdash/issues/1805)
Remove overrideQueryUuid condition on save changes 
This hasUnsavedChanges has changed recently, causing this special case to break the "disabled" property on the button 
This could potentially cause that a saved chart from Explore can't be saved without changes, but the comparison is a bit broken at the moment because of chartConfig being overwritten.
> fix: remove overridequeryuuid condition on save changes

- packages/frontend/src/components/NavBar/HelpMenu/index.tsx
- packages/frontend/src/providers/TrackingProvider.tsx
- packages/frontend/src/types/Events.ts
Closes: #1775 
this PR adds tracking events to the new notifications headway for when the notifications button is clicked, when the user clicks in one of the items, and when the user clicks on the _Lightdash updates_ button
> feat: add tracking to notifications button

- packages/frontend/src/hooks/useEcharts.ts
fix format undefined on frontend
https://sentry.io/organizations/lightdash/issues/3210581843/?referrer=digest-slack
This error happened when the chart had table calculations, and we were shoing labels
Fixed:
> fix: fix format undefined on frontend

- packages/frontend/src/components/Explorer.tsx
- packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
- packages/frontend/src/components/RefreshButton.tsx
- packages/frontend/src/components/common/Filters/index.tsx
- packages/frontend/src/hooks/useCartesianChartConfig.ts
- packages/frontend/src/hooks/useExplorerRoute.ts
- packages/frontend/src/hooks/useFilters.ts
- packages/frontend/src/hooks/useQueryResults.tsx
- packages/frontend/src/pages/SavedExplorer.tsx
- packages/frontend/src/providers/ExplorerProvider.tsx
Closes: 
- remove logic around pristine state in explorer provider
- any provider action can now set `shouldFetchResults` to `true` so the query results are fetched after the reducer calculates the state
- there is also a direct way to fetch the query results ( previously we had to sync the pristine state )
- explorer url params now update based on the MetricQuery returned by the query results 
- move states from component into provider
- removed big number callback which was causing unwanted behaviour
> refactor: remove pristine state from explorer provider

- packages/frontend/src/App.tsx
- packages/frontend/src/components/Explorer.tsx
- packages/frontend/src/hooks/useExplorerRoute.ts
- packages/frontend/src/pages/Explorer.styles.ts
- packages/frontend/src/pages/Explorer.tsx
- packages/frontend/src/pages/SavedExplorer.tsx
- packages/frontend/src/providers/ExplorerProvider.tsx
Closes: 
- explorer initial state is now set via a prop in the provider. This means both `saved chart` and `state via url` is set in the same way in the respective page component
- remove hook that set the saved chart type since it is now done in the initial state
- remove setState action since we should use the initial state
- add loading and error UI in the saved chart page
- split useExplorerRouter into 2 hooks: 1 updates the url params based on the explorer provider, 1 reads the explore state from the url params ( which is applied as the initial state on the explorer provider )
> refactor: explorer initial state

- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/ChartDownload.tsx
- packages/frontend/src/components/Explorer.tsx
- packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
- packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
- packages/frontend/src/components/Explorer/ExplorerResults.tsx
- packages/frontend/src/components/LineageButton.tsx
- packages/frontend/src/components/RefreshButton.tsx
- packages/frontend/src/components/TableCalculationModels/TableCalculationModal.tsx
- packages/frontend/src/hooks/useColumns.tsx
- packages/frontend/src/hooks/useCompiledSql.tsx
- packages/frontend/src/hooks/useDefaultSortField.tsx
- packages/frontend/src/hooks/useExplore.tsx
- packages/frontend/src/hooks/useExplorerAceEditorCompleter.tsx
- packages/frontend/src/hooks/useExplorerRoute.ts
- packages/frontend/src/hooks/useField.ts
- packages/frontend/src/hooks/useFilters.ts
- packages/frontend/src/hooks/useQueryResults.tsx
- packages/frontend/src/pages/SavedExplorer.tsx
- packages/frontend/src/providers/ExplorerProvider.tsx
Closes: 
- make the explorer provider state as close as possible as the saved chart version
> refactor: change explorer provider state into saved chart version

- packages/common/src/index.ts
- packages/frontend/src/components/Explorer.tsx
- packages/frontend/src/hooks/useExplorerRoute.ts
- packages/frontend/src/pages/SavedExplorer.tsx
- packages/frontend/src/providers/ExplorerProvider.tsx
Closes: #1782 #1737
- pass saved chart object into explorer provider ( is also going to be useful for future PRs )
- move logic to detect unsaved changes into explorer provider
- unsaved logic now compares all necessary properties
> fix: compare all chart properies to detect unsaved changes

- packages/frontend/src/components/Explorer.tsx
- packages/frontend/src/pages/SavedExplorer.tsx
- packages/frontend/src/providers/ExplorerProvider.tsx
Closes: 
- expose the saved chart in explorer provider
- clean explorer component props/state related to saved chart
> refactor: expose saved chart in explorer provider

- packages/e2e/cypress/integration/savedDashboards.spec.ts
Closes: [
](https://github.com/lightdash/lightdash-internal-work/issues/291#issuecomment-1109487860)
Allow multiple test runs by deleting a previously created dashbaord, instead of deleting `jaffle shop` dashboard
> chore: new delete dashboard

- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
- packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
- packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
- packages/frontend/src/hooks/useCartesianChartConfig.ts
Closes: #1821
<a href="https://www.loom.com/share/91080fe0b1dc487488b99b904aa21024">
<p>Lightdash - fix changing chart type - Watch Video</p>
</a>
> fix: updating saved visualization type no longer breaks UI

- packages/frontend/src/components/SimpleTable/index.tsx
Closes: #1926 
Table visualization no longer uses plotted data.
> fix: table visualization shows pivoted data

- packages/frontend/src/components/common/ActionCardList/ActionCardList.style.tsx
- packages/frontend/src/components/common/ActionCardList/index.tsx
Closes: #1312 
This PR adds search to the saved queries pages when there are 5 or more saved charts.
> feat: add search to saved charts

- packages/frontend/src/providers/TrackingProvider.tsx
Closes: #1931 
This was a hard one to find. 
The menu would disappear because the menuitems array was being rebuild when it shouldn't so the element references would change and the menu would close.
I found out that the problem was in the `<TrackSection />` since it was always marking the section as changed when it wasn't. The menuitems `useMemo` was dependent on the `track` method which was constantly being changed, triggering the hook.
> fix: unstable table tree menus

- packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx
Closes: #1783
There was a bug on this previous code, so I'm rolling back. But ideally we should fix this . I've tried with KeepValues, and a few other things in this  `reset` but that doesn't work https://react-hook-form.com/api/useform/reset
> fix: rollback dbt form reset

- packages/frontend/src/components/UserSettingsModal/AppearancePanel/AppearancePanel.styles.ts
- packages/frontend/src/components/UserSettingsModal/AppearancePanel/index.tsx
Closes: #1885 
Had a chat with @PriPatel and we decided to make some UX changes here since we were fixing bugs.
Changes: 
- no more tooltip color picker. We know we need to pick a new color picket library but for now this doesn't seem useful in this page
- re-style elements to be similar to the rest of the app
- make sure we use the org colors after loading
<a href="https://www.loom.com/share/502b6d3fc38e485197bb80c8e20a9093">
<p>Lightdash - default chart colors - Watch Video</p>
</a>
> fix: default chart colors

- packages/backend/src/clients/DockerHub/DockerHub.ts
- packages/backend/src/services/HealthService/HealthService.ts
Closes: #1553
Store version and refretch it every 10 mins in the background, making /health not blocking
> fix: health dockerhub call

- packages/frontend/src/components/TableCalculationHeaderButton.tsx
- packages/frontend/src/components/TableCalculationModels/TableCalculationModal.tsx
Closes: #1905
This is only affecting `updated table calculations` not on `create`
The problem is that on each click we make new queries to RunSQL , the popup is reloaded here https://github.com/lightdash/lightdash/blob/main/packages/frontend/src/components/ResultsTable/ResultsTable.tsx#L154
I simply stopped event propagation on the popup 
Before: 
After:
> fix: table calculation reload

- packages/frontend/src/components/DashboardTiles/EmptyStateNoTiles/index.tsx
- packages/frontend/src/components/Home/LatestSavedCharts/index.tsx
- packages/frontend/src/components/SavedQueries/EmptySavedChartsState/EmptySavedChartsState.styles.tsx
- packages/frontend/src/components/SavedQueries/EmptySavedChartsState/index.tsx
- packages/frontend/src/components/common/ActionCardList/index.tsx
- packages/frontend/src/pages/Dashboard.tsx
Closes: #1674 
This PR adds a message and run a query button when there are no available charts in the saved charts section
> feat: add message and button to create new charts when none are saved

- packages/frontend/src/components/TableCalculationModels/TableCalculationModal.styles.ts
- packages/frontend/src/components/TableCalculationModels/TableCalculationModal.tsx
Closes: #1961 
This PR fixes the creating table calculations not being able to exit full screen, the problem was that the sql input was taking full width which was pushing the modal's footer down.
> style: update max height of sql input on full screen

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
- packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
- packages/frontend/src/hooks/useCartesianChartConfig.ts
- packages/frontend/src/hooks/usePivotDimensions.ts
Closes: 
- Rename args to have accurate meaning
- The visualization provider and its internal hooks are responsible for managing the visualization state, after the initial load, so they shouldn't update their internal state based on arguments change. This removes the possibility of an infinite loop.
> chore: refactor visualization provider to handle initial values

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/DashboardTiles/TileBase/TileBase.styles.tsx
- packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
Closes: #1941 
this PR adds description tooltips to the charts in the dashboard tiles
> feat: add description tooltip to charts in a dashboard

- packages/frontend/src/components/DashboardFilter/index.tsx
- packages/frontend/src/pages/Dashboard.tsx
Closes: #1677
Allow adding filter before dashboard is saved
Also, remove the filter button when there are no `chart` tiles (eg: markdown)
> fix: disabled add filter button on dashboard with tiles

- packages/e2e/cypress/integration/explore.spec.ts
- packages/frontend/src/hooks/useSavedQuery.ts
Closes: #1809 
This PR now displays the correct messages for when saving a new chart it now says `chart was saved` and on save changes it says `chart was updated`
> fix: update success messages to the correct ones

- packages/backend/src/dbt/translator.ts
We currently include models, seeds, and sources in our lineage graph.
However, the current implementation uses the model/seed/source **name** not the model/seed/source **unique_id** for each node in the lineage graph. Although dbt models must have unique names, a model and a seed may have the same name. That means that our lineage graph can end up with a circular dependency:
```
{ name: 'node1', type: 'model'} -> { name: 'node2', type: 'model' } -> { name: 'node1', type: 'seed'}
```
^ if you build a graph of the names, you end up with a loop (from `node1` back to `node1`
**quick fix** - remove seeds and sources from the graph. Long term we should use the `unique_id` to build the graph.
Closes:
> fix: remove unsupported dbt nodes from from lineage graphs

- packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
- packages/frontend/src/pages/SavedExplorer.tsx
Closes: #979 
This PR makes the back button on the explorer to always redirect to the referrer page.
> fix: back button to always point to the tables page

- packages/backend/src/index.ts
Closes: 
Removes http logs from dockerhub 
https://sentry.io/organizations/lightdash/issues/?project=5959292&query=&statsPeriod=1h
Before: 
AFter:
> chore: remove http dockerhub breadcrumb

- packages/backend/src/models/DashboardModel/DashboardModel.ts
- packages/frontend/src/hooks/dashboard/useDashboard.tsx
Closes: #1894 
In our select we a combination of all dashboards and versions order by latest created version and then have a `distinct on` that makes sure the final results are just the latest dashboard versions.
But the new ‘where’ clause that filters by chart uuid ( so we can detect where the chart is being used ) happens at the start so it filters out the latest versions before the `distinct on`.
We want to get the latest dashboard versions and then do the filtering by chart id. 
<a href="https://www.loom.com/share/4b14b1533ee04e3795a89ebbb10d351f">
<p>Lightdash - fix related dashboards - Watch Video</p>
</a>
> fix: related dashboards

- packages/backend/src/services/ProjectService/ProjectService.test.ts
- packages/common/src/index.ts
- packages/common/src/types/field.ts
- packages/common/src/utils/formatting.ts
- packages/frontend/src/hooks/useBigNumberConfig.ts
Closes: #1722 
Blocked by: https://github.com/lightdash/lightdash/pull/2033
This is one of many PR's to move all the value formatting logic from `packages/frontend/src/utils/resultFormatter.tsx` to this util function. The FE should use the formatted values, that BE returns, where possible.
Both the big number and table visualizations should now show formatted values independently of their type.
Changes:
- formatted value is always a string
- format all value types ( undefined, null, string, number, boolean, date, timestamp )
- fix big number to use formatted value when selected field isn't of type number
TODO: 
- add tests
<a href="https://www.loom.com/share/06f66ca2d6974732bfbe0063e488de88">
<p>Lightdash - formatted values in big number and table - Watch Video</p>
</a>
> fix: show formatted values in big number and table

- packages/frontend/src/hooks/useEcharts.ts
Closes: #2032
Unify tooltip config, do not show multiple tooltips 
Before: 
After:
> fix: tooltips on scattered charts, unify tooltip config

- packages/frontend/src/providers/AppProvider.tsx
Closes: #2069
Close toaster on error
Create
Refresh
> fix: close apptoaster on error

- packages/common/src/types/savedCharts.ts
Closes: #1049 
Switches the second default colour from green --> orange.
> fix: updates default colours to be colourblind friendly

- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
…en updated
Closes: #2090 
This PR adds an alert when a chart has been changed and the user is navigating away from the page.
> feat: Chart unsaved changes alert

- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx
- packages/frontend/src/components/ProjectConnection/ProjectStatusCallout.tsx
- packages/frontend/src/components/ProjectConnection/WarehouseForms/BigQueryForm.tsx
- packages/frontend/src/components/ProjectConnection/WarehouseForms/PostgresForm.tsx
- packages/frontend/src/components/ProjectConnection/WarehouseForms/RedshiftForm.tsx
- packages/frontend/src/components/ProjectConnection/WarehouseForms/SnowflakeForm.tsx
- packages/frontend/src/components/ProjectConnection/index.tsx
- packages/frontend/src/hooks/useProject.ts
Closes: #2084
Updates explores and cache after project update 
Fixes compileExplores
> fix: refresh explores after project update

- packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx
Closes: #2113 
This PR adds a tooltip to the disabled filters panel on view mode, to instruct the user that to view it they will need to go to edit mode
> chore: add tooltip to filter panel chevron on view mode

- packages/frontend/src/components/TableTree.styles.ts
- packages/frontend/src/components/TableTree.tsx
Closes: #1984 
This PR fixes the items from being cut off when the sidebar item is not hovered and not filters have been added
> fix: update component so it does not cut test

- docs/docs/guides/visualizing-your-results.mdx
- packages/e2e/cypress/integration/explore.spec.ts
- packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
Closes: #1870 
This PR updates the `bar chart` name to `horizontal bar chart` all across the docs and app
> feat: update bar chart with horizontal bar chart

- packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
- packages/frontend/src/hooks/useCartesianChartConfig.ts
Closes: #1927 
- avoid visualization provider from recalculating all the configuration when results are refreshed ( since `resultsData` is undefined while is loading )
- avoid setting multiple times the chart configuration by using `else if` 
- allow the chart configuration to set fallback axes when results data changes
> fix: handle invalid chart configuration

- packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts
- packages/backend/src/services/ProjectService/ProjectService.mock.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/backend/src/types.ts
- packages/common/src/index.ts
- packages/frontend/src/components/ChartDownload.tsx
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
- packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
- packages/frontend/src/hooks/useSqlQueryVisualization.ts
- packages/frontend/src/pages/SqlRunner.styles.ts
- packages/frontend/src/pages/SqlRunner.tsx
- packages/warehouses/src/types.ts
- packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.test.ts
- packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
- packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts
- packages/warehouses/src/warehouseClients/PostgresWarehouseClient.mock.ts
- packages/warehouses/src/warehouseClients/PostgresWarehouseClient.test.ts
- packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
- packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.mock.ts
- packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.test.ts
- packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
- packages/warehouses/src/warehouseClients/WarehouseClient.mock.ts
Closes: #1135
- create a mock explore and metric query based on the sql runner results
- Display chart visualization in sql runner
Out of scope functionality: 
- be able to share the url with the chart configuration
> feat: add chart vizualization to sql runner

- packages/backend/src/dbt/translator.mock.ts
- packages/backend/src/dbt/translator.test.ts
- packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts
- packages/common/src/compiler/translator.ts
- packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.mock.ts
- packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.test.ts
- packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
- packages/warehouses/src/warehouseClients/WarehouseClient.mock.ts
We were implicitly running case-insensitive matches for database/schema/table/column names for the Snowflake adapter (inside the `getCatalog` function).
This makes it explicit during `attachTypesToModels` 
The snowflake schema also returns the raw catalog without changing case for columns, so columns are likely to always be returned upper case.
User experience:
* If I'm on any database except snowflake, the case of the column names in my `schema.yml` file matter!
* If I'm on snowflake, the case of the column names in my `schema.yml` file don't matter
Closes:
> fix: case insensitive behaviour for snowflake

- packages/cli/src/dbt/targets/postgres.ts
`profiles.yml` for a postgres target supports both `database` and `dbname` interchangeably. Adds support for `database`
**before**
**after**
Closes: #2228
> fix: database field name in profiles.yml

- packages/cli/.eslintrc.json
- packages/cli/src/dbt/models.ts
- packages/cli/src/dbt/schema.ts
- packages/cli/src/handlers/generate.ts
Closes: #2219 
The CLI should generate new `.yml` files for undocumented models and update `.yml` files for models with existing documentation.
However if the user deletes a `.yml` file **after** running `dbt compile` - then `lightdash generate` will expect a documented model but not find anything.
This PR alters the `lightdash generate` command to fallback to generating a new `.yml` file if it expected but failed to find an existing `.yml` file.
Example with jaffle:
```
$ tree models
models
├── customers.sql
├── docs.md
├── orders.sql
├── overview.md
├── payments.sql
├── schema.yml
└── staging
├── schema.yml
├── stg_customers.sql
├── stg_orders.sql
└── stg_payments.sql
$ dbt compile
$ lightdash generate
Generated .yml files:
✔   payments ➡️  models/schema.yml
✔   customers ➡️ …
```
> feat: handle deleted schema.yml files on cli

- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/common/src/authorization/organizationMemberAbility.ts
- packages/frontend/src/components/RefreshDbtButton/index.tsx
Closes: #2128
Remove ability to 'refresh dbt' for those with project view-only access
admin vs viewer
> feat: job manage permission

- packages/frontend/src/components/ProjectConnection/WarehouseForms/DatabricksForm.tsx
Closes: 
Fixes error when creating a new Databricks connection:
> DbtError: Failed to run "dbt parse" 11:12:18 Encountered an error while reading profiles: 11:12:18 ERROR: Runtime Error Credentials in profile "lightdash_profile", target "prod" invalid: 'schema' is a required property 
Introduced recently when updating the Databricks form
> fix: database field for databricks form

- packages/common/src/compiler/translator.ts
Closes:  #2224  
When a user compiles their project, we automatically determine dimension types by looking for column types in the database (unless the user explicitly provides the `meta.dimension.type` property in their `schema.yml`).
If we can't find the column at the time of compiling we throw an error and it's extremely common that uses hit this error.
This PR changes behaviour to default to a string type dimension, even if we can't find the column in the database. If the column still doesn't exist when the user goes to query the dimension, then they'll get an error that the column doesn't exist.
This is a better flow for two reasons:
* We separate the idea of the database state from the compiled project state (we can never guarantee that any dimension/model is available in the db at …
> feat: default to string dimensions

- .github/CONTRIBUTING.md
Closes: 
In the contribution guide Step 3, default branch to set upstream is mentioned as 'master'.
GitHub changed the default branch name to 'main'
> docs: Contribution guide step 3- default branch name changed to main

- .github/CONTRIBUTING.md
- packages/frontend/src/components/ProjectConnection/WarehouseForms/BigQueryForm.tsx
Closes: 
Documentation prompt in the Create Project form for BigQuery -> Project name pointed to dbt Project name in docs. 
Added the correct link to point to Project name of BigQuery
> fix: Change docs link in big query form - project name to point to correct anchor

- packages/common/src/index.ts
- packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx
- packages/frontend/src/components/ResultsTable/ResultsTable.styles.tsx
- packages/frontend/src/components/ResultsTable/ResultsTable.tsx
- packages/frontend/src/components/SqlRunner/SqlRunnerResultsTable.tsx
- packages/frontend/src/hooks/useColumns.tsx
- packages/frontend/src/hooks/useSqlQueryVisualization.ts
- packages/frontend/src/pages/SqlRunner.tsx
Closes: #1527 
Note that I didn't add column totals to the table visualization since it only shows the first 25 results which is a problem already so I suggest we add the totals when we improve the table visualization UX
> feat: column totals

- packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilter.tsx
- packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
- packages/frontend/src/components/DashboardFilter/FilterSearch/index.tsx
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/pages/Dashboard.tsx
- packages/frontend/src/providers/DashboardProvider.tsx
Closes: #2399 
I had to split the code to track the temporary filters that are in the url in a separate state as the ones that are saved in the dashboard.
> fix: dashboard temporary filters

- packages/common/src/openapi/schemas/SavedChart/ChartConfig/ChartSeries.json
- packages/common/src/openapi/schemas/SavedChart/CreateSavedChart.json
- packages/common/src/openapibundle.json
- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/ChartConfigPanel/FieldLayoutOptions.tsx
- packages/frontend/src/components/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
- packages/frontend/src/components/ChartConfigPanel/Series/SingleSeriesConfiguration.tsx
- packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
- packages/frontend/src/hooks/useCartesianChartConfig.ts
Closes: #2284
Add area charts as new chart. Unlike other charts, this is not a type, but an AreaStyle property (empty for now) on the series
Stacking is enabled for area charts, but the result looks weird...
> feat: area charts

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
Before: 
only saved filters were being applied to the charts
After: 
all filters are applied to charts
> fix: apply dashboard filter

- packages/frontend/src/components/TableTree.styles.ts
- packages/frontend/src/components/TableTree.tsx
When a saved chart is using a dimension that has been hidden in the dbt project ( `hidden: true` ) we used to keep the saved chart working but we wouldn't display the dimension in the sidebar. 
With this fix we now show the dimension in the sidebar as long as being used but with a warning.
> fix: warn about hidden dimensions being used

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/DashboardTiles/DashboardMarkdownTile.styles.ts
- packages/frontend/src/components/DashboardTiles/DashboardMarkdownTile.tsx
- packages/frontend/src/components/DashboardTiles/TileBase/TileBase.styles.tsx
- packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
Closes: #2410 
This PR updates the markdown tiles styling, and removes the divider from the markdown and the rest of the tiles
> fix: remove divider and update markdown tile styling

- packages/frontend/src/components/SqlRunner/RunSqlQueryButton.tsx
Closes: #1619 
This PR fixes the `Run query` button tooltip from staying active when the button is clicked
> fix: tooltip to be disabled on click

- packages/backend/src/models/DashboardModel/DashboardModel.mock.ts
- packages/backend/src/models/UserModel.ts
- packages/backend/src/services/DashboardService/DashboardService.mock.ts
- packages/backend/src/services/DashboardService/DashboardService.test.ts
- packages/backend/src/services/OrganizationService/OrganizationService.mock.ts
- packages/backend/src/services/ProjectService/ProjectService.mock.ts
- packages/backend/src/services/ProjectService/ProjectService.test.ts
- packages/common/src/authorization/index.mock.ts
- packages/common/src/authorization/index.test.ts
- packages/common/src/authorization/index.ts
- packages/common/src/authorization/organizationMemberAbility.test.ts
- packages/common/src/authorization/organizationMemberAbility.ts
- packages/common/src/authorization/projectMemberAbility.test.ts
- packages/common/src/authorization/projectMemberAbility.ts
- packages/common/src/authorization/types.ts
- packages/common/src/index.ts
- packages/common/src/openapi/schemas/LightdashUser.json
- packages/common/src/openapibundle.json
- packages/common/src/types/user.ts
- packages/frontend/package.json
- packages/frontend/src/App.tsx
- packages/frontend/src/components/AppRoute.tsx
- packages/frontend/src/components/ForbiddenPanel.tsx
- packages/frontend/src/components/PrivateRoute.tsx
- packages/frontend/src/components/ProjectRoute.tsx
- packages/frontend/src/components/common/Authorization/index.tsx
- packages/frontend/src/pages/ProjectSettings.tsx
- packages/frontend/src/providers/AppProvider.tsx
- packages/frontend/src/types/Events.ts
- yarn.lock
> feat: access project permissions in the UI

- packages/backend/src/database/migrations/20220622093921_remove-user-cascade-deletion.ts
Fixing the bug where deleting the user cascades to what the user created/edited. Meaning all the chart and dashboard versions that user created are deleted. 
This changes the behaviour so when the user is deleted we just change the `updated_by_user_uuid` to `null` + deletes all the invalid dashboards and saved charts.
> fix: user cascade deletion

- packages/frontend/src/components/TableTree.styles.ts
- packages/frontend/src/components/TableTree.tsx
Closes: #2493 
This PR adds icons to the dimension types in the explorer sidebar
> feat: add dimension type icons to the explorer sidebar

- packages/backend/src/models/JobModel/JobModel.ts
- packages/backend/src/services/DashboardService/DashboardService.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/backend/src/services/SavedChartsService/SavedChartService.ts
- packages/e2e/cypress/e2e/createProjects.cy.ts
- packages/e2e/cypress/e2e/projectPermission.cy.ts
- packages/frontend/src/components/ProjectAccess/ProjectAccess.tsx
- packages/frontend/src/components/ProjectConnection/index.tsx
- packages/frontend/src/components/ProjectTablesConfiguration/ProjectTablesConfiguration.tsx
- packages/frontend/src/components/UserSettings/AppearancePanel/index.tsx
- packages/frontend/src/components/UserSettings/ProjectManagementPanel/index.tsx
- packages/frontend/src/pages/ProjectSettings.tsx
- packages/frontend/src/pages/Settings.tsx
- apply permission check to all ProjectService methods
- update permission checks in saved chart and dashboard services
- apply permission check in org appearance form
- apply permission check in all project setting forms
- some other small fixes around permissions
> fix: project access permissions

- packages/frontend/src/components/TableTree.styles.ts
- packages/frontend/src/components/TableTree.tsx
Closes: #2493 
This PR updates the icons on the explorer sidebar
- Removes icons from headings (metrics / dimensions / custom metrics)
- Adds icons to metrics / custom metrics
- Updates the icons color
- Adds icons to items with subitems as well so the hierarchy is clear
- removes table names from sub items
> feat: remove heading icons and add icons to metrics

- packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
- packages/frontend/src/hooks/useCartesianChartConfig.ts
Closes: #2526 
Area chart when stacking 2 y axis with no grouping:
Area chart when stacking 2 y axis with grouping:
Note that we have in place some restrictions on what is possible to do with stacked charts. There is a [separate ticket to improve stacking configuration](https://github.com/lightdash/lightdash/issues/2524).
> fix: stack area chart when not grouping

- packages/cli/src/handlers/compile.ts
Closes: #2552 
Closes: #2538 
Changes the compile process on the CLI to behave similarly to compiling in the UI
* Compiling Lightdash does not require all referenced tables/columns to exist (we can never guarantee that)
* If the user doesn't specify a dimension type, we'll still try and find the type in the warehouse, if we can't we default to string
> feat: default string dimensions on cli

- packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx
- packages/frontend/src/components/Explorer/ResultsCard/ResultsCard.tsx
- packages/frontend/src/components/Explorer/SqlCard/SqlCard.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.styles.ts
- packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
- packages/frontend/src/providers/ExplorerProvider.tsx
Closes:[#2607](https://github.com/lightdash/lightdash/issues/2607)
- reset chart config
- reset results data
- disable sections when no table is selected
> fix: explore reset

- packages/frontend/src/hooks/useTableConfig.ts
Totals in the table viz weren't formatted like the values in the column.
Closes: #2695
> fix: format table viz totals

- docs/docs/get-started/setup-lightdash/connect-project.mdx
- docs/docs/get-started/setup-lightdash/lightdash-cli.mdx
We're looking to simplify onboarding. Previously, we had some vital steps only available in the onboarding email.
> 1. Open up our [getting started guide](https://docs.lightdash.com/get-started/setup-lightdash/intro/).
> 2. Make sure your dbt project is compatible with dbt version 1.0.0 - we can help upgrade if you have issues).
> 2. If you need to add our IP address to your database’s allow-list, you should use: 35.245.81.252
> 3. Ensure you have access to a dbt project on github/gitlab/bitbucket/etc along with the credentials for your data warehouse.
> 4. One person from your org should [sign up here using your work email](https://app.lightdash.cloud/register). You will be provisioned with a cloud instance.
> 5. Once you’re in, you can go into the Settings menu to invite the rest of …
> docs: add vital steps to deprecate onboarding email

- packages/backend/src/database/entities/dashboards.ts
- packages/backend/src/database/migrations/20220804115530_tile_hide_title_property.ts
- packages/backend/src/models/DashboardModel/DashboardModel.ts
- packages/common/src/types/dashboard.ts
- packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
Closes: #1848
Only applies to Charts and Looms, we should move title from markdowns into their content , see more https://github.com/lightdash/lightdash/issues/1848#issuecomment-1109737276
But that requires a new spec, what happens to everyone’s Markdown tiles that already have titles? do we just make them into H1?
> feat: hide title toggle on dashboards

- packages/frontend/src/components/common/Table/TableProvider.tsx
- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes: #2737
- add `useMemo` to useEcharts hook
- amend column order logic so it doesn't trigger onChange callback when the component mounts
> fix: chart flicker

- packages/backend/package.json
- packages/backend/src/queryBuilder.mock.ts
- packages/backend/src/queryBuilder.ts
Closes: 2793 
@owlas @TuringLovesDeathMetal  In the ticket I mentioned the end of the current day but that would still include future values so I used the current time.
eg: In the last 1 day filter 
`((customers.created) >= ('2020-04-03') AND (customers.created) < ('2020-04-04 01:12:00'))`
> fix: in the last filter

- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes: #2874 
Fixes table calculation line chart label overlap
before:
after:
> fix: table calculation overlapping labels

- packages/common/src/types/field.ts
Closes: #2903
fixes string, date and boolean metric types
before:
after:
> fix: string, date and boolean metric types

- packages/frontend/src/providers/ExplorerProvider.tsx
> fix: fix table calculation renaming sort

- packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx
- packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx
- packages/frontend/src/components/common/Table/types.ts
- packages/frontend/src/hooks/useColumns.tsx
- packages/frontend/src/providers/ExplorerProvider.tsx
Closes: #2924 
We need to show in the results table all fields that are active but can't be found in the table fields.
Since I don't know if the field is a dimension or metrics I had to introduce an agnostic function to remove any active field from the metric query.
> fix: option to remove invalid fields

- docs/docs/get-started/intro.mdx
1 character change to fix a broken [link](https://docs.lightdash.com/get-started/intro/get-started/develop-in-lightdash/intro) in the docs.
> docs: amend broken "developing in lightdash" link in docs

- packages/frontend/src/components/Explorer/SpaceBrowser/index.tsx
Closes: #2936 
renaming or removing spaces always renamed/removed the last item because all edit/delete modals popped at once (last always on top)
https://user-images.githubusercontent.com/962095/184309043-7df52ab7-1f2e-4be9-bfd3-595d4f5c392c.mp4
> fix: renaming and removing spaces always renamed/removed the last item

- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
Closes: #2932 
removed "last refresh at" from the dashboard header
spaces were already added here #2929
> chore: remove "last refreshed at" from the dashboard header

- packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
Closes: #2826 
We alter the snowflake query session to use UTC as the default, this controls the assumed timezone for `TIMESTAMP_TZ` (timestamps with no time zones).
Ideally we should be able to set this parameter as a connection setting but we're blocked by a feature request on the node sdk for snowflake: https://github.com/snowflakedb/snowflake-connector-nodejs/issues/61
For now we prepend every query with an additional query to set the session timezone. I'm sure we take a performance hit but nothing substantial:
**Without** `ALTER SESSION` pre-query
1. `select 1` - 2.128s
2. `select 1` - 0.682s
3. `show parameters like 'timezone'` - 8.588s
4. `show parameters like 'timezone'` - 0.730s
**With** `ALTER SESSION` pre-query
1. `select 1` - 0.908s
2. `select 1` - 1.091s
3. `show parameters …
> fix: use default utc timezone for snowflake queries

- packages/frontend/src/components/common/Table/ScrollableTable/HeaderDnD.tsx
- packages/frontend/src/components/common/Table/TableProvider.tsx
- packages/frontend/src/providers/ExplorerProvider.tsx
The explore components are constantly re-rendering when ordering the columns. Causing the app to be less responsive. 
This is really noticeable in the open PR #2942 where it's constantly recalculating the pivot data.
Now we only re-render the explore when the ordering finishes. 
Before:
After:
> fix: performance when ordering columns

- .github/workflows/release-on-merge.yml
Closes: 
I could have used the latest LTS version `ubuntu-22.04` but we already use `20.04` in someo other workflows, so we better use the same version, and update all flows when needed.
> chore: bump ubuntu version 20.04

- packages/frontend/src/components/ChartConfigPanel/index.tsx
- packages/frontend/src/components/ChartDownload.tsx
- packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/2652
- Disable chart options when there is empty chart display
> fix: disable charts options for empty chart

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/services/OrganizationService/OrganizationService.ts
- packages/backend/src/services/UserService.ts
Closes: #2980
I added 2 extra args: 
- newUser : it is true if the invitation is created for a new user
- generatedInvite: false if only the role was updated, true if a new invitation is created (for a new or existing user) 
I added some info to org properties that was easily accessible (org name) , the rest requires a bit of refactoring
> feat: analytics permission updated

- packages/backend/src/models/UserModel.ts
- packages/backend/src/services/UserService.ts
Closes: #2846
We don't expose if the user has a password or not , so we can't simply hide the menu if the user has no password (or even if he has social login) 
Instead we change the error message
See full thread https://lightdash.slack.com/archives/C02NPFHF4F6/p1661410782856119
> fix: show different error reset password for social login

- packages/frontend/src/components/DashboardFilter/FilterSearch/FilterSearch.styles.tsx
- packages/frontend/src/components/DashboardTiles/AddTileButton.tsx
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
- packages/frontend/src/components/ExploreMenuItem.tsx
- packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
- packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
- packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx
- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
- packages/frontend/src/components/Explorer/SpaceBrowser/SpaceBrowserMenu.tsx
- packages/frontend/src/components/Explorer/SpaceBrowser/index.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/SeriesContextMenu.tsx
- packages/frontend/src/components/NavBar/BrowseMenu/index.tsx
- packages/frontend/src/components/NavBar/ExploreMenu/index.tsx
- packages/frontend/src/components/NavBar/GlobalSearch/index.tsx
- packages/frontend/src/components/NavBar/NavBar.styles.tsx
- packages/frontend/src/components/NavBar/index.tsx
- packages/frontend/src/components/ProjectAccess/ProjectAccessCreation/index.tsx
- packages/frontend/src/components/ReactHookForm/MultiSelect.tsx
- packages/frontend/src/components/SavedQueries/SavedQueriesMenu.tsx
- packages/frontend/src/components/SimpleStatistic/BigNumberContextMenu.tsx
- packages/frontend/src/components/TableCalculationHeaderButton.tsx
- packages/frontend/src/components/UnderlyingData/UnderlyingDataModal.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/StringAutoComplete.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/UnitOfTimeAutoComplete.tsx
- packages/frontend/src/components/common/RouterMenuItem.tsx
- packages/frontend/src/components/common/SideBarLoadingState.tsx
- packages/frontend/src/components/common/Table/ScrollableTable/TableHeader.tsx
- packages/frontend/src/components/common/modal/ModalActionButtons.tsx
> chore: add missing keys / migrate MenuItem deprecations / menu appearance

- packages/frontend/src/components/Explorer/ResultsCard/CellContextMenu.tsx
- packages/frontend/src/components/SimpleTable/CellContextMenu.tsx
- packages/frontend/src/components/common/Table/BodyCell.tsx
- packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
- packages/frontend/src/components/common/Table/ScrollableTable/index.tsx
- packages/frontend/src/components/common/Table/Table.styles.ts
- packages/frontend/src/components/common/Table/TableProvider.tsx
- packages/frontend/src/components/common/Table/types.ts
related to #2997 
- makes rendering tables fast by wrapping cell with popover menu only after the click.
- keeps the existing UX untouched
- cleans up `TableBody` to be relatively simple by extracting `BodyCell`
- simplifies `CellContextMenu`
- removes blocking scroll when the context menu is open
> chore: cell context menu perf improvement

- packages/e2e/cypress/e2e/explore.cy.ts
Fixes flaky tests that I've added recently.
Tests were not waiting for the chart to load. Because of that Chart Type menu button was disabled and caused timeouts sometime
> test: fix flaky table tests

- packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
Closes: #3070
We were missing an initial chart config combination: (3 metrics, 1 dimension)
> fix: fix empty chart sqlrunner 1+ metrics 1 dimension

- packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
- packages/frontend/src/components/UnderlyingData/UnderlyingDataModal.tsx
- packages/frontend/src/components/UnderlyingData/UnderlyingDataModalContent.tsx
- packages/frontend/src/components/UnderlyingData/UnderlyingDataProvider.tsx
- packages/frontend/src/components/UnderlyingData/UnderlyingDataResultsTable.tsx
- packages/frontend/src/hooks/useColumns.tsx
- packages/frontend/src/hooks/useExplore.tsx
- packages/frontend/src/hooks/useQueryResults.tsx
Related to: #2997
Changes:
- move all the logic in the underlying data provider to the model content component `UnderlyingDataModalContent.tsx`. So it only calculates once the model opens.
- stop using the same hook as the explore page to fetch results. Now, it has a dedicated hook `useUnderlyingDataResults()` with a unique queryKey.
- and stop refetch the explore when component mounts.
Before:
After:
> chore: refactor underlying data provider

- packages/frontend/src/components/BigNumberConfig/index.tsx
- packages/frontend/src/components/ChartConfigPanel/index.tsx
- packages/frontend/src/components/ChartDownload.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCardHeader.tsx
- packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
- packages/frontend/src/components/TableConfigPanel/index.tsx
- packages/frontend/src/pages/SqlRunner.tsx
Closes:  https://github.com/lightdash/lightdash/issues/3122
-  Visualisation ( Chart -> table -> Number ) : Free to choose even if there is no data available
- Chart Configure: Disable if it is chart type and no data available
- Chart export: Disable if chart type and no data available
> fix: disable visualization buttons

- packages/common/src/types/field.ts
- packages/e2e/cypress/e2e/explore.cy.ts
- packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx
- packages/frontend/src/components/SortButton/SortButton.styles.ts
- packages/frontend/src/components/SortButton/SortItem.tsx
- packages/frontend/src/utils/sortUtils.ts
Closes: #3140 
adds proper sort indicators based on field type
> feat: proper sort indicators based on field type

- packages/backend/src/database/migrations/20220907161709_multiply-dashboard-tile-size.ts
- packages/backend/src/database/seeds/development/03_saved_dashboards.ts
- packages/common/src/types/dashboard.ts
- packages/frontend/src/pages/Dashboard.tsx
Closes: #2954 
- Increased grid points by 3x.
- Height increases by 50px ( before 150px )
- Width has 36 points relative to window width ( before 12 ) 
- Set min width and height with sane values
- Height 100px
- Width 6 points 
- migrate all tiles to match the new scale
> feat: increase dashboard tile grid points

- packages/backend/src/database/migrations/20220615070629_add_member_role.ts
Closes: #3187 
Make sure we update all users role from `member` to `viewer` before deleting the `member` role.
> fix: member role migration rollback

- packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx
- packages/frontend/src/components/SortButton/SortButton.styles.ts
- packages/frontend/src/components/SortButton/SortItem.tsx
- packages/frontend/src/utils/sortUtils.ts
previously: 
- Flips sort order for boolean fields. (because false is Ascending and true is Descending)
- Changes boolean labels from First-Last to Yes-No
> feat: multisort for booleans

- packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx
originally reported by @rephus → https://github.com/lightdash/lightdash/pull/3218#issuecomment-1243485708
fixes ascending sort in header cell context menu
https://user-images.githubusercontent.com/962095/189705591-eeee05a8-6383-4b06-972f-b2e17ebba4a2.mp4
> fix: ascending sort in header cell context menu

- packages/frontend/src/components/NavBar/GlobalSearch/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/3265
fixes reload when navigating from global search
> fix: explore page not reloading when navigating

- packages/frontend/src/components/common/ResourceList/ResourceList.styles.ts
- packages/frontend/src/components/common/ResourceList/ResourceTable/ResourceTable.styles.ts
- packages/frontend/src/components/common/ResourceList/ResourceTable/index.tsx
makes full row clickable instead of resource name
https://user-images.githubusercontent.com/962095/191202464-505ff46f-c5a0-4f50-bdd8-7831643cb755.mp4
> feat: resource table full row link

- packages/e2e/cypress/e2e/dashboard.cy.ts
- packages/e2e/cypress/e2e/savedDashboards.cy.ts
- packages/frontend/src/components/Explorer/SpaceBrowser/index.tsx
- packages/frontend/src/components/Home/LandingPanel/LandingPanel.styles.tsx
- packages/frontend/src/components/Home/LandingPanel/index.tsx
- packages/frontend/src/components/Home/LatestDashboards/index.tsx
- packages/frontend/src/components/Home/LatestSavedCharts/index.tsx
- packages/frontend/src/components/SpacePanel/index.tsx
- packages/frontend/src/components/common/ResourceList/ResourceEmptyState.styles.ts
- packages/frontend/src/components/common/ResourceList/ResourceEmptyState.tsx
- packages/frontend/src/components/common/ResourceList/ResourceList.styles.ts
- packages/frontend/src/components/common/ResourceList/ResourceTable/ResourceTable.styles.ts
- packages/frontend/src/components/common/ResourceList/ResourceTable/index.tsx
- packages/frontend/src/components/common/ResourceList/index.tsx
- packages/frontend/src/pages/Home.tsx
- packages/frontend/src/pages/SavedDashboards.tsx
- packages/frontend/src/pages/SavedQueries.tsx
- normalises empty states for resource lists.
> ⚠️ spaces resource does not have an icon, any suggestions what to use? @PriPatel
> feat: resource list empty states

- packages/frontend/src/components/ChartConfigPanel/ChartConfigPanel.styles.ts
- packages/frontend/src/components/ChartConfigPanel/FieldLayoutOptions.tsx
Closes:  https://github.com/lightdash/lightdash/issues/2829
- Disable group option in configure chart if no metrics in chart
<details>
<summary>Screenshot</summary>
<br />
</details>
> fix(2829): `group` should be unavailable if you only have dimensions in your chart

- docs/docs/guides/exploring-your-content.mdx
- docs/docs/guides/how-to-create-metrics.mdx
- docs/docs/references/dimensions.mdx
- docs/docs/references/metrics.mdx
We included `show_underlying_values` as a parameter in the dimensions reference doc, but it's only actually availble for metrics. 
This removes teh reference.
> docs: removes show underlying values from dim reference doc

- packages/common/src/utils/timeFrames.ts
- packages/frontend/src/hooks/echarts/useEcharts.ts
When using big time intervals ( MONTH, QUARTER, YEAR ) the chart axis should adapt to use the same time interval and labels.
Before:
After (month, quarter, year):
> fix: adapt axis interval to dimension time interval

- packages/cli/src/handlers/deploy.ts
- packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectSuccess.tsx
Closes: https://github.com/lightdash/lightdash/issues/3376
- redirect to project home instead of an explorer from the CLI
> fix: do not skip onboarding screens from the cli

- packages/cli/src/dbt/targets/Bigquery/index.ts
Closes:#3355
With location:
WIthout location with server eu1.lightdash.cloud: 
Unknown cloud server:
> fix: get default bigquery location if missing in profiles

- packages/frontend/src/components/Home/LatestDashboards/index.tsx
- packages/frontend/src/components/Home/LatestSavedCharts/index.tsx
- packages/frontend/src/components/SpacePanel/index.tsx
- packages/frontend/src/components/common/ResourceList/ResourceEmptyState.tsx
- packages/frontend/src/components/common/ResourceList/ResourceTable/index.tsx
- packages/frontend/src/components/common/ResourceList/index.tsx
- packages/frontend/src/pages/SavedDashboards.tsx
- packages/frontend/src/pages/SavedQueries.tsx
Closes: https://github.com/lightdash/lightdash/issues/3334
- add default sort for resource list
- add default column visibility for resource list
- improve component API
- sort order [desc (down arrow), asc (up arrow), none]
- hide sort icon if table is not interactive
> sort disabled for 1 item
> another is interactive with icon
> sorted but its not interactive (hiding icon) if I still should show the icon
> feat: resource list default sort

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/SeriesContextMenu.tsx
- packages/frontend/src/components/UnderlyingData/UnderlyingDataProvider.tsx
Closes: #3318 
Changes:
- Use selected metric to show chart underlying data ( so it shows the same results as viewing metric underlying data from results table )
- User correct field when using pivot
Applying metric show_underlying_values
``` 
metrics:
count_users:
type: count_distinct
show_underlying_values:
- first_name
- last_name
```
With pivot
> fix: chart underlying data

- packages/frontend/src/pages/Login.tsx
> fix: hide recover password button when email client isnt configured

- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/common/src/index.ts
- packages/frontend/src/components/common/Filters/FilterInputs/AutoComplete/autoCompleteUtils.ts
- packages/frontend/src/hooks/useFieldValues.ts
Code assumed the values for the auto complete were strings. 
When the values weren't strings there was a blank page with the error: 
TypeError
t.toLowerCase is not a function. (In 't.toLowerCase()', 't.toLowerCase' is undefined)
Changes:
- improve type safety by changing the type from `any` to `unknown` 
- filter values that aren't strings
> fix: filter auto complete values

- .github/CONTRIBUTING.md
Closes:  NA
The earlier url pointed to label `good first issue` while the actual label is `🙋 good first issue`
> docs: Fix link for good first issue in contributing doc

- packages/e2e/cypress/e2e/dashboard.cy.ts
- packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx
Closes: https://github.com/lightdash/lightdash/issues/3268
before:
after:
> feat: space label in add chart to dashboard modal

- docs/docs/references/dimensions.mdx
The difference is that we reference the table and then have the column name as a string instead of a reference. When there is a reference, we will copy the SQL from that reference, that’s why it causes issues when referencing itself.
> docs: fix self reference example

- packages/common/src/utils/timeFrames.ts
- packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNode.tsx
- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes: #3444
Closes: #3443
For users that haven't synced their repo recently, their cached explores might have unsupported time intervals. 
Since this is a temporary problem I don't want to change the type to support `string`.
Instead I'm just validating the value is a valid time interval
> fix: time interval backwards compatibility

- packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
- packages/frontend/src/components/DashboardFilter/index.tsx
- packages/frontend/src/hooks/dashboard/useDashboard.tsx
- packages/frontend/src/providers/DashboardProvider.tsx
Closes: #3390
Fields for filters was extracted for saved dashboard (if tiles > 0) . I updated it to always take the files from the `unsaved` tiles 
https://user-images.githubusercontent.com/1983672/195590815-442f972a-9a21-45c2-9d35-5e567fa9e687.mov
> fix: show fields to filter from new tiles

- docs/docs/references/dimensions.mdx
- packages/common/src/index.ts
- packages/common/src/templating/template.mock.ts
- packages/common/src/templating/template.test.ts
- packages/common/src/templating/template.ts
- packages/common/src/types/results.ts
- packages/frontend/src/components/Explorer/ResultsCard/CellContextMenu.tsx
- packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx
- packages/frontend/src/components/Explorer/ResultsCard/UrlMenuItems.tsx
- packages/frontend/src/components/ProjectRoute.tsx
- packages/frontend/src/components/SimpleTable/CellContextMenu.tsx
- packages/frontend/src/components/UnderlyingData/CellContextMenu.tsx
Closes: #3465 
Changes:
- create component to render urls, so it can be reused in results table, simple table, underlying data table
- disable url menu when url can't be parsed and display error in tooltip for easy debug
- allow template to access row values
Error messages:
Example yml referencing a value from the row:
Reference column `customer_id` from table `customers` 
```
- label: "Open company"
url: "https://example.com/company/${row.customers.customer_id.raw | url_encode }"
```
> feat: url can reference any value in the row

- packages/frontend/src/components/NavBar/BrowseMenu/index.tsx
removes divider if spaces does not exist
before
after
> style: remove divider if spaces does not exist

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/SeriesContextMenu.tsx
- packages/frontend/src/components/SimpleTable/CellContextMenu.tsx
- packages/frontend/src/components/UnderlyingData/UnderlyingDataModalContent.tsx
- packages/frontend/src/components/UnderlyingData/UnderlyingDataProvider.tsx
Closes: 
Before it was only filtering by the first pivot value.
Now is filtering by all pivot values.
Filter underlying data for all pivot values
> fix: underlying data of multi pivot table

- packages/frontend/src/App.tsx
- packages/frontend/src/components/DbtCloudSettings/index.tsx
- packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
- packages/frontend/src/components/NavBar/SettingsMenu/index.tsx
- packages/frontend/src/components/ProjectAccess/ProjectAccess.tsx
- packages/frontend/src/components/ProjectAccess/ProjectAccessCreation/index.tsx
- packages/frontend/src/components/ProjectAccess/index.tsx
- packages/frontend/src/components/ProjectConnection/ProjectConnection.styles.tsx
- packages/frontend/src/components/ProjectConnection/index.tsx
- packages/frontend/src/components/ProjectTablesConfiguration/ProjectTablesConfiguration.tsx
- packages/frontend/src/components/UserSettings/ProjectManagementPanel/index.tsx
- packages/frontend/src/hooks/dbtCloud/useProjectDbtCloudSettings.ts
- packages/frontend/src/hooks/useExplores.tsx
- packages/frontend/src/pages/ProjectSettings.styles.tsx
- packages/frontend/src/pages/ProjectSettings.tsx
- packages/frontend/src/pages/Settings.tsx
Closes: https://github.com/lightdash/lightdash/issues/3429
**Table configuration tab**
https://user-images.githubusercontent.com/962095/198115089-14352489-3e1d-42d8-afb5-d849dfa301bb.mp4
> feat: project settings breadcrumbs

- dockerfile
- dockerfile-prs
- packages/backend/package.json
- yarn.lock
why: 
I was looking into this: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1666927757498709
but I was not able to reproduce.
I found out few mentions of pg / node 14 issues. here are some links:
https://github.com/knex/knex/issues/4075
https://stackoverflow.com/questions/40435315/knex-timeout-acquiring-a-connection-the-pool-is-probably-full-are-you-missing#comment108851590_61482183
- upgrades node from 14 to 16
- upgrades pg/knex (no breaking changes, only patch version changes)
> chore: upgrade pg and node to 16

- scripts/reset-db.sh
```bash
﹩ ./scripts/reset-db.sh
./scripts/reset-db.sh: line 4: [: -v: unary operator expected
```
fixes error above ^
> fix: check for env variable in reset-db script

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/database/seeds/development/01_initial_user.ts
- packages/backend/src/routers/jobsRouter.ts
- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/cli/src/analytics/analytics.ts
- packages/cli/src/handlers/dbt/apiClient.ts
- packages/cli/src/handlers/dbt/refresh.ts
- packages/cli/src/index.ts
- packages/common/src/types/api.ts
Closes: #3615 
Changes:
- enable token authentication on 3 endpoints: get project, get token, refresh project
- add `refresh` CLI command 
- track from where the refresh was triggered from
Github action to refresh the Lightdash project can be simplified over the existing `deploy` command:
```
name: refresh-lightdash
on:
push:
branches: [ "main", "master" ]
jobs:
deploy:
runs-on: ubuntu-latest
steps:
- uses: actions/setup-node@v3.4.1
- name: Get lightdash version 
uses: sergeysova/jq-action@v2
id: version 
env:
LIGHTDASH_URL: ${{ secrets.LIGHTDASH_URL }}   
with: 
cmd: curl -s "${LIGHTDASH_URL}/api/v1/health" | jq -r '.results.version'
- name: Install lightdash CLI
run: npm install -g "@lightdash/cli@${{ steps.version.outputs.value }}" || npm install -g @lightdash/cli@latest
- name: …
```
> feat: refresh command

- packages/cli/src/dbt/models.ts
Reverts lightdash/lightdash#3540
Closes: https://github.com/lightdash/lightdash/issues/3543
Ok so the previous alias implementation was replacing too much stuff. So I am reverting back that change, and just fixing the bug mentioned on the original ticket
If I add  an alias to my model : 
Before:
After:
> fix: Revert previous alias on CLI and fix error

- packages/frontend/src/components/Explorer/ExplorerHeader/ExplorerHeader.styles.tsx
- packages/frontend/src/components/Explorer/ExplorerHeader/index.tsx
- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
- packages/frontend/src/components/common/ShareShortLinkButton/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/3609
- removes share button from the edit mode header for saved charts
- adds button for explore/charts next to a run query button (always)
- always copies minified URL
https://user-images.githubusercontent.com/962095/199081267-6dedaba7-9254-4e71-85b0-a77025d19622.mp4
> feat: leave only one share button for explores and charts

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
Closes: #3655 
Fix wrong amount of arguments that was throwing a silent error and preventing users to see underlying data of dashboard charts.
Before: 
After:
> fix: dashboard chart underlying data

- packages/common/src/compiler/exploreCompiler.ts
Closes: #3664
Include table reference from metric filters
Example:
```
total_completed_order_amount:
type: sum
format: usd
round: 2
filters:
- customers.first_name: "Paul"
```
> fix: missing FROM clause from metric filter reference

- packages/backend/src/models/SearchModel/index.ts
- packages/e2e/cypress/e2e/globalSearch.cy.ts
Closes: #3637
Example with `orders` hidden metric and table configuration only has `orders` visible.
```
- name: gift_card_amount
description: Amount of the order (AUD) paid for by gift card
tests:
- not_null
meta:
dimension:
hidden: true
```
> fix: exclude hidden tables and fields from global search

- packages/frontend/src/components/TableConfigPanel/ColumnConfiguration.tsx
Show/hide button was not available when no pivot was applied.
> fix: table column hide button

- packages/common/src/index.test.ts
- packages/common/src/utils/formatting.ts
- packages/frontend/src/hooks/echarts/useEcharts.ts
- packages/frontend/src/hooks/useBigNumberConfig.ts
Closes: #3703 
Changes:
- change `value: any` to `value: number` or `value: unknown`
- change function args to have value as the first arg and then an options object
- add function that confirms value as a number type
> chore: refactor formatting function args

- packages/backend/src/database/entities/savedCharts.ts
- packages/common/src/index.test.ts
- packages/common/src/types/dbt.ts
- packages/common/src/types/field.ts
- packages/common/src/types/metricQuery.ts
- packages/common/src/types/savedCharts.ts
- packages/common/src/utils/formatting.ts
- packages/frontend/src/components/BigNumberConfig/index.tsx
- packages/frontend/src/hooks/echarts/useEcharts.ts
- packages/frontend/src/hooks/useBigNumberConfig.ts
Closes: #3702 
Refactor common package **numberStyle** types, utils and vars to **compact**
> chore: rename numberStyle types, utils and vars to compact

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/LightdashVisualization/index.tsx
- packages/frontend/src/components/SimpleTable/index.tsx
- packages/frontend/src/components/common/Table/ScrollableTable/index.tsx
- packages/frontend/src/components/common/Table/Table.styles.ts
- packages/frontend/src/components/common/Table/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/3705
removes extra padding from the dashboard table viz
> fix: dashboard table padding

- packages/backend/src/@types/knex-tables.d.ts
- packages/backend/src/controllers/authenticationRoles.ts
- packages/backend/src/database/entities/spaces.ts
- packages/backend/src/database/migrations/20210728093219_saved_queries.ts
- packages/backend/src/database/migrations/20221109083433_space_permission.ts
- packages/backend/src/database/seeds/development/01_initial_user.ts
- packages/backend/src/models/DashboardModel/DashboardModel.mock.ts
- packages/backend/src/models/ProjectModel/ProjectModel.ts
- packages/backend/src/models/SpaceModel.ts
- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/services/DashboardService/DashboardService.mock.ts
- packages/backend/src/services/ProjectService/ProjectService.mock.ts
- packages/backend/src/services/SpaceService/SpaceService.ts
- packages/common/src/types/projectMemberProfile.ts
- packages/common/src/types/space.ts
Closes: #3202
> Existing charts will have `isPrivate: false`
> New created charts will have `isPrivate: true` and the user will be added to the list of `access` 
> Built required endpoints
> You can use `patch space` endpoint to change isPrivate 
>  Built a new endpoint 
>  Built a new endpoint 
> Added a limitation: there must be at least 1 user on the access list 
`Jaffle shop` is public (is_private=false) and `private space` is private but I'm in the access list as admin (from org) 
`Jaffle shop` becomes private (and I'm not in the access list) 
To change `isPrivate` call existing endpoint ` patch /spaces/:spaceUuid with `isPrivate` in body
```
POST {{base_url}}/projects/3675b69e-8324-4110-bdca-059031aa8da3/spaces/f99afb8b-07e0-4025-b797-92961248ebb2/share
Content-Type: …
```
> feat: backend space share

- packages/frontend/src/components/ReactHookForm/MultiSelect.tsx
Closes: https://github.com/lightdash/lightdash/issues/3751
deprecated MultiSelect does not support `disabled` prop
> fix: disable table configuration settings for the viewer

- packages/e2e/cypress/e2e/explore.cy.ts
- packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
- packages/frontend/src/components/ChartConfigPanel/Legend/index.tsx
- packages/frontend/src/components/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
- packages/frontend/src/components/ChartConfigPanel/Series/SingleSeriesConfiguration.tsx
- packages/frontend/src/components/TableConfigPanel/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/3673
@PriPatel there are a lot of inconsistencies in the viz config in general. I have not touched anything else but let's tackle that as a separate issue.
**Table viz panel**
**Series tab for line charts and area charts**
**Axes tab:** 
(we already say 'show grid' so the checkboxes make sense here)
Legend tab
https://user-images.githubusercontent.com/962095/201729131-d5db135c-5f1f-40bd-9902-c8d15e903901.mp4
> feat: viz config switch to checkbox

- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes: #3749  
Changes:
- add dimensions in y-axis to `nonPivotedKeys` when pivoting data
> fix: pivot with dimensions in y axis

- packages/frontend/src/components/DashboardFilter/index.tsx
- packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FiltersProvider.tsx
- packages/frontend/src/components/common/WeekPicker.tsx
Closes: #3804
Changes:
- day picker 
- week picker 
Note that when a user picks a week from the week picker we only store the starting day of that week. This might cause problems when the user changes the start of the week configuration.
<a href="https://www.loom.com/share/ddcfc6a2ada346b99804c3b87c50e032">
<p>Lightdash - date picker start of week - Watch Video</p>
</a>
> feat: date picker use start of week configuration

- packages/frontend/src/components/SpacePanel/index.tsx
Closes: #3825
Without  `manage` space permissions
With `manage` space permissions
> feat: hide share space button if user does not have space permissions

- packages/frontend/src/App.tsx
Closes: https://github.com/lightdash/lightdash/issues/3829
removes focus outline and only enables it when using TABs
> style: focus state on tabs only

- packages/frontend/src/App.styles.tsx
- packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceAccessType.tsx
- packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceAddUser.tsx
- packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceModal.style.ts
- packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceSelect.tsx
- packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceUserList.tsx
- packages/frontend/src/components/common/ShareSpaceModal/index.tsx
- packages/frontend/src/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/3817
https://user-images.githubusercontent.com/962095/203865970-c7ef3836-531e-4c52-87ad-3f7688f0cdf2.mp4
> style: permissions modal

- packages/frontend/src/index.tsx
> chore: add svgr type ref

- packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts
- packages/cli/src/handlers/compile.ts
- packages/cli/src/handlers/createProject.ts
- packages/cli/src/handlers/deploy.ts
- packages/cli/src/handlers/preview.ts
- packages/cli/src/index.ts
Closes: #3803
Add `--start-of-week` option for commands `deploy` `preview` `start-preview` 
<a href="https://www.loom.com/share/68cdb585512445afb45b3d4e2ad622de">
<p>Lightdash - start of week preview command - Watch Video</p>
</a>
<a href="https://www.loom.com/share/563989d39ff54b2384ea588f36dba9e7">
<p>Lightdash - start of week deploy command - Watch Video</p>
</a>
> feat: configure start of week in CLI commands

- packages/frontend/src/components/ChartConfigPanel/Grid/index.tsx
- packages/frontend/src/components/ChartConfigPanel/Legend/Legend.styles.tsx
- packages/frontend/src/components/ChartConfigPanel/Legend/index.tsx
- packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ProjectConnectFlow.styles.tsx
- packages/frontend/src/components/ReactHookForm/UnitInput.tsx
- packages/frontend/src/components/common/UnitInput/UnitInput.style.ts
- packages/frontend/src/components/common/UnitInput/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/3871
demo video / user testing:
https://cln.sh/wAlIMC
> feat: chart config unit input improvements

- .github/CONTRIBUTING.md
Closes: no related issue
Added a command `PUPPETEER_SKIP_DOWNLOAD=true` before running build script to fix this error
> docs: add dev set up command to fix error when running build script

- packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
Closes: #3886 
Changes: 
- we always remove the pivot value when changing to table visualization
Changing from chart to table:
Defining a pivot in table and then changing to chart and back to table ( resets pivot )
> fix: remove pivot when changing to table vizualisation

- docs/docs/guides/cli/cli-authentication.mdx
- packages/cli/src/config.ts
- packages/cli/src/handlers/dbt/apiClient.ts
- packages/cli/src/handlers/login.ts
Closes: #3580 
I'm adding support for the [`Proxy-Authorization`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Proxy-Authorization) header. In many production deployments, we want to hide Lightdash behind an authorization proxy like: [Cloud IAP](https://cloud.google.com/iap). Now, you can easily authorize by setting `LIGHTDASH_PROXY_AUTHORIZATION` environment variable. It enable scenarios, when we want to deploy changes to secured Lightdash instance using CLI or generating previews of local changes on remote, secured Lightdash instance
> feat: add Proxy-Authorization header support

- packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilters.styles.ts
- packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
- packages/frontend/src/components/DashboardFilter/DashboardFilter.styles.tsx
Closes: https://github.com/lightdash/lightdash/issues/3980
> fix: dashboard filters wrapping

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/DrillDownMenuItem/index.tsx
- packages/frontend/src/components/Explorer/ResultsCard/CellContextMenu.tsx
- packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/SeriesContextMenu.tsx
- packages/frontend/src/components/SimpleStatistic/BigNumberContextMenu.tsx
- packages/frontend/src/components/SimpleTable/CellContextMenu.tsx
- packages/frontend/src/components/SimpleTable/DashboardCellContextMenu.tsx
- packages/frontend/src/components/SimpleTable/index.tsx
- packages/frontend/src/components/UnderlyingData/DrillDownMenuItem.tsx
- packages/frontend/src/components/UnderlyingData/UnderlyingDataProvider.tsx
Closes: #3891 
This feature is available on both explore and dashboards:
- results table - only on metric cell
- charts - only on series with metric
- big number - only on metric values
- table viz - only on metric cell
When drilling down the query should contain:
- dimension selected in the menu
- metric clicked/selected
- explore filters + dashboard filters + one filter per pivot value + dimension value from selected chart series
<a href="https://www.loom.com/share/13ba56a4abc9475b9314684b86321d49">
<p>Lightdash - drill by dimension ( chart ) - Watch Video</p>
</a>
<a href="https://www.loom.com/share/262ab30f65d9429698f9cb3bc90a6976">
<p>Lightdash - drill by dimension ( big number ) - Watch Video</p>
</a>
<a href="https://www.loom.com/share/31cc8f25f0e7421b822b4de3272b9b8b"> …
> feat: drill by dimension

- packages/cli/package.json
Closes: [3813](https://github.com/lightdash/lightdash/issues/3813)
Before:
After:
Published and tested with `npm i -g @lightdash/cli@0.346.1-rc1`
> fix: script bash preinstall script if fails on windows

- packages/frontend/src/components/UserSettings/UserManagementPanel/InviteSuccess.tsx
Closes:  [3909](https://github.com/lightdash/lightdash/issues/3909)
When I invite a new user, it says "invite successful" but then it also tells me to copy a link. 
This made me think that the user didn't get an email sent to them as well.
Instead, the copy should say:
`We've just sent xxxx an email with their invite! You can also share their invite link with them to join your organization. This link will expire in 3 days.`
> fix: message on invite user success is confusing

- packages/backend/src/models/ShareModel.ts
Remove accidental database fields returned during creation of share links.
(orginally part of https://github.com/lightdash/lightdash/pull/3937)
> fix: remove extra fields from ShareModel

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/DashboardTiles/TileBase/TileBase.styles.tsx
- packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
Closes:  #3696
**In edit mode**
- Add hover state to dashboard tile (suggestion : drop shadow)
- Add selected state to dashboard tile (suggestion : blue border)
- Grab cursor when hovering over tile header
- Grabbing cursor when selecting tile to drag
**In view mode**
- The context menu and info icon should only show on hover.
> fix: clean up dashboard tiles

- packages/frontend/src/components/NavBar/HelpMenu/HelpMenu.styles.tsx
- packages/frontend/src/components/NavBar/HelpMenu/index.tsx
Closes:  [3918](https://github.com/lightdash/lightdash/issues/3918)
The bell is a different colour compared to the help and settings icon. It should match them!
#abb3bf
> fix: notifications icon styles

- packages/frontend/src/components/NavLink.styles.tsx
- packages/frontend/src/components/NavLink.tsx
Closes:  [3966](https://github.com/lightdash/lightdash/issues/3966)
All items under the `Browse` menu are underlined. They shouldn't be (for consistency!)
> fix: browse menu items should not be underlined

- packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterConfiguration.styled.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterSettings.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/TileFilterConfiguration.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/4008
**Settings tab**
**Tiles tab**
https://user-images.githubusercontent.com/962095/208907180-c005a1c4-0cba-4754-a812-f622e17e7cfe.mp4
> style: dashboard filters popover

- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/ChartConfigPanel/Legend/ReferenceLines.tsx
- packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
Closes: #3957
[Screencast from 22-12-22 13:48:32.webm](https://user-images.githubusercontent.com/1983672/209140380-6b0fca9b-1d62-4239-adb7-fd6d718e9d3b.webm)
> feat: add label to markline

- packages/frontend/src/components/MetricQueryData/DrillDownMenuItem.tsx
- packages/frontend/src/components/MetricQueryData/DrillDownModal.tsx
Closes:  #4034
The modal that pops up should say
> feat: update drill down  copy

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/DashboardTiles/TileBase/TileBase.styles.tsx
- packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
Closes: [#3986](https://github.com/lightdash/lightdash/issues/3986)
> feat: dashboard filters should be an icon and description should appear on title hover

- packages/frontend/src/components/TableCalculationModels/TableCalculationModal.tsx
Closes: [614](https://github.com/lightdash/lightdash/issues/614) 
Currently, we show the following warning to all postgres/redshift users.
The warning takes up a lot of screen space in the modal. It would be much better to show this conditional on whether a divide / has actually been used in the table calculation. The warning is not informative if you're not actually dividing.
> fix: show divide warning only when dividing

- docs/docs/guides/cli/cli-authentication.mdx
Closes: 
I was trying to authenticate lightdash, but the link is wrong for Europe. I get this error:
```
FetchError: request to https://eu1.lightdash.com/api/v1/login failed, reason: getaddrinfo ENOTFOUND eu1.lightdash.com
at ClientRequest.<anonymous> (/Users/annebelleolminkhof/.nvm/versions/node/v18.12.1/lib/node_modules/@lightdash/cli/node_modules/node-fetch/lib/index.js:1491:11)
at ClientRequest.emit (node:events:513:28)
at ClientRequest.emit (node:domain:489:12)
at TLSSocket.socketErrorListener (node:_http_client:494:9)
at TLSSocket.emit (node:events:513:28)
at TLSSocket.emit (node:domain:489:12)
at emitErrorNT (node:internal/streams/destroy:151:8)
at emitErrorCloseNT (node:internal/streams/destroy:116:3)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { …
```
> docs: amend CLI login example 

- packages/frontend/src/components/common/ShareSpaceModal/index.tsx
Closes: #3865 
Show generic footer message if "Full access" is selected
> chore: show generic footer message when space has full access

- packages/common/src/compiler/filtersCompiler.mock.ts
- packages/common/src/compiler/filtersCompiler.test.ts
- packages/common/src/compiler/filtersCompiler.ts
Closes: #4092 
```
metrics:
in_gbp:
type: sum
format: 'gbp'
filters:
- event_id: '>= 4'
```
> fix: ">=" and "<=" metric number filters

- docs/docs/references/filters.md
- packages/common/src/compiler/filtersCompiler.mock.ts
- packages/common/src/compiler/filtersCompiler.test.ts
- packages/common/src/compiler/filtersCompiler.ts
- packages/common/src/types/filter.ts
- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/FilterInputs.styles.tsx
- packages/frontend/src/components/common/Filters/configs.ts
Closes: [#3599](https://github.com/lightdash/lightdash/issues/3599)
We have the option to filter `is on or after` and then include `is on or before`, but right now, because we don't have nested filtering options, this means I'm forced to have any other filters I might choose have the `all filters apply` logic to them. 
Also, it's a bit annoying that I need to apply `is on or after` and `is on or before` as two separate filters (a user actually didn't know how to do this...they were looking for a `range` option - that's how unintuitive it was)
We should add an option for `is between` for date + timestamp filters.
> feat: `is between` date filter

- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes: #4117
Things in scope: 
Things out of scope:
It kind of works despite of the bug, but it is not reliable
> feat: adjust axis limits when using reference lines outside of the chart

- packages/backend/src/index.ts
Removes three endpoints from sentry traces:
- /api/v1/livez
- /robots.txt
- /favicon.ico
The livez produces about 99% of traces in production (due to polling for live state), which contain no performance information.
> fix: remove livez,robots,favicon from sentry traces

- packages/frontend/src/components/ChartConfigPanel/Legend/ReferenceLine.tsx
Closes: #4191
Before, the key was either xAxis or yAxis, now both axis keys can exist in data, but they can be undefined. I fixed the method that gets the right axis. 
[Screencast from 19-01-23 10:42:34.webm](https://user-images.githubusercontent.com/1983672/213409166-10c39a1c-d70b-4114-85b8-98b8803f6e27.webm)
> fix: reference line missing value

- packages/common/src/types/filter.ts
- packages/common/src/utils/conditionalFormatting.ts
- packages/common/src/utils/formatting.ts
- packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilter.tsx
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx
- packages/frontend/src/components/common/Filters/configs.ts
- packages/frontend/src/components/common/Table/BodyCell.tsx
- packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
Closes: https://github.com/lightdash/lightdash/issues/4197
Rule 1:
- product_value is greater than 5 (and condition 2:) is less than 10
- on hover, it would show: is greater than 5 and is less than 10
> feat: conditional formatting show applied rules on hover

- packages/backend/src/index.ts
All asset files in the `/build/assets` dir generated by vite are appended with a hash, which changes if the content changes. This PR marks those as immutable and `max-age: 1yr` for the `cache-control` header. Enabling CDNs to cache these.
All other build files (index.html, robots.txt, and icons) have a no cache policy (as before).
```
curl -s -D - -o /dev/null http://localhost:8080/
curl -s -D - -o /dev/null http://localhost:8080/favicon.ico
curl -s -D - -o /dev/null http://localhost:8080/assets/blueprint-icons-vendor.27956899.js
> chore: set asset headers to immutable

- packages/backend/src/index.ts
Fixing headers for index.html
Use `no-cache` to make sure every request checks for a new version of `index.html`. To be safe I'm also adding `private` which turns off public caching entirely (e.g. CDNs) but allows browsers to continue caching. In future for performance we may want to replace `private` with `public`. But in this case I'll take the performance hit to prevent errors loading `.js` assets in production behind a CDN
```
// private - browsers can cache but not CDNs
// no-cache - caches must revalidate with the origin server before using a cached copy
```
> fix: force no public cache on index.html

- packages/common/src/compiler/exploreCompiler.mock.ts
- packages/common/src/compiler/exploreCompiler.test.ts
- packages/common/src/compiler/exploreCompiler.ts
- packages/common/src/compiler/translator.ts
- packages/common/src/types/dbt.ts
- packages/common/src/types/explore.ts
Closes: #1034 
This allows the user to join the same table multiple times under an alias. Example in dbt config:
```yaml
models:
- name: pull_requests
meta:
joins:
- join: users
sql_on: ${pull_requests.user_id} = ${users.user_id}
- join: users
alias: closed_by
sql_on: ${closed_by} = ${created_by.user_id}
- join: users
alias: reviewed_by
sql_on: ${pull_requests.reviewed_by} = ${reviewed_by.user_id}
label: An optional new label for the join
```
Need to pull `tableLabel` out of `translator.ts` into `exploreCompiler.ts` but blocked by `tableLabel` being on the base `Field` type
> feat: add table alias

- packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts
- packages/backend/src/queryBuilder.mock.ts
- packages/backend/src/queryBuilder.test.ts
- packages/backend/src/queryBuilder.ts
- packages/backend/src/queryCompiler.mock.ts
- packages/backend/src/queryCompiler.test.ts
- packages/backend/src/queryCompiler.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/cli/src/handlers/compile.ts
- packages/common/src/compiler/exploreCompiler.mock.ts
- packages/common/src/compiler/exploreCompiler.test.ts
- packages/common/src/compiler/exploreCompiler.ts
- packages/common/src/compiler/translator.ts
- packages/common/src/index.ts
- packages/common/src/types/warehouse.ts
- packages/warehouses/.eslintrc.js
- packages/warehouses/src/types.ts
- packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
- packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts
- packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
- packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
- packages/warehouses/src/warehouseClients/TrinoWarehouseClient.ts
Closes: 
Move the configuration around quote chars to the warehouse client. 
This work is a preparation to convert the explore compiler functions into a class. 
Changes:
- move warehouse client types to common since we need to use it there
- move warehouse config to warehouse clients 
- amend mocks/tests
> chore: warehouse client config methods

- packages/backend/src/services/ProjectService/ProjectService.ts
Adds a span to `/availableFilters` (our slowest endpoint in prod) to get better performance measurements. 
Related to: https://github.com/lightdash/lightdash/issues/4259
Example in dev:
> chore: instrument getAvailableFilters

- packages/frontend/src/components/ChartConfigPanel/FieldLayoutOptions.tsx
- packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes: #3553
I tried to implement this with minimal changes and side effects , so instead of setting `xField` to undefined, I'm giving it an special state that I can check when setting `category` axis and values. 
[Screencast from 25-01-23 16:15:43.webm](https://user-images.githubusercontent.com/1983672/214601997-8e500f24-faac-4480-b9d4-317031ca1fa4.webm)
Also works with groups
> feat: chart with empty x axis

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/DashboardTiles/DashboardLoomTile.tsx
- packages/frontend/src/components/DashboardTiles/DashboardMarkdownTile.tsx
- packages/frontend/src/components/DashboardTiles/TileBase/TileBase.styles.tsx
- packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
> fix: hover state for clickable dashboard chart titles

- packages/common/src/compiler/exploreCompiler.mock.ts
- packages/common/src/compiler/exploreCompiler.test.ts
- packages/common/src/compiler/exploreCompiler.ts
- packages/common/src/compiler/translator.ts
- packages/common/src/types/dbt.ts
- packages/common/src/types/explore.ts
Closes: #2009
Allows the user to specify a subset of fields (dimensions/metrics) to pull through on a joined model. This must include the join key to successfully compile the join sql.
> feat: support join fields

- packages/warehouses/package.json
- yarn.lock
Closes: https://github.com/lightdash/lightdash/issues/4304
error occurring when opening a databricks connection.
after package upgrade we should expect a descriptive error why databricks did not accept the connection
```
TypeError: Converting circular structure to JSON
--> starting at object with constructor 'TLSSocket'
|     property 'parser' -> object with constructor 'HTTPParser'
--- property 'socket' closes the circle
```
> chore: upgrade databricks client from 1.0 to 1.1

- packages/backend/package.json
- packages/backend/src/models/DashboardModel/DashboardModel.ts
- packages/backend/src/models/ProjectModel/ProjectModel.ts
- packages/backend/src/models/SavedChartModel.ts
- packages/backend/src/models/UserModel.ts
- yarn.lock
Also fixes new warnings with double rollbacks in transaction blocks
2.4.0 contains a bug when inserting arrays: https://github.com/knex/knex/issues/5365
The diff looks big but I've only made two changes:
- upgrading to 2.4.2
- Removing the `try {} except {trx.rollback(e); throw e;}` from a bunch of transacting blocks
> fix: upgrade knex from 2.4.0 to 2.4.2

- packages/common/src/index.ts
Closes: #4234 
`privateKey` and `privateKeyPass` are sensitive Snowflake credentials that shouldn’t be send to browser in plain text.
This change also fixes issues with updating Snowflake setting in UI as sensitive credentials are automatically copied to updates configs.
> fix: Add Snowflake private key credentials to sensitive credentials list

- packages/backend/src/manifestv7.json
- packages/cli/src/dbt/models.ts
- packages/cli/src/handlers/generate.ts
- packages/cli/src/manifestv7.json
- packages/common/src/compiler/translator.mock.ts
- packages/common/src/types/dbtFromSchema.ts
removes dependencies on root path to support dbt 1.4.1 projects: https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.4
Closes: #4920
- I removed `"root_path"` from all nodes in the `manifest`
- I added `additionalProperties: true` to `CompiledModelNode` and `ParsedMetric` (the only two we validate in the CLI/backend) to allow manifests with and without `root_path`
- I refactored the CLI logic that depended on `root_path`
```
(dbt1-3) ➜  jaffle_shop git:(feat/add-url) ✗ lightdash deploy 
10:55:15  Running with dbt=1.3.1
10:55:18  Found 7 models, 20 tests, 0 snapshots, 0 analyses, 289 macros, 0 operations, 4 seed files, 0 sources, 0 exposures, 2 metrics
10:55:18  
10:55:18  Concurrency: 4 threads (target='prod')
10:55:18  
10:55:19  Done.
- SUCCESS> payments 
- SUCCESS> …
```
> feat: remove `root_path` dependency

- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/common/ResourceList/ResourceIcon.tsx
- packages/frontend/src/components/common/ResourceList/ResourceType.tsx
- packages/frontend/src/components/common/ResourceList/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/4342
before:
after:
I am labeling unknown chart type as "Chart" with "Bar icon"
but might be better to claim unknown chart type as "Bar Chart"
open to suggestion
> fix: unknown chart type appearing as dashboard

- packages/backend/src/schema.json
- packages/cli/src/schema.json
- packages/common/src/compiler/translator.mock.ts
- packages/common/src/compiler/translator.ts
- packages/common/src/schemas/json/lightdash-dbt-2.0.json
- packages/common/src/types/dbt.ts
- packages/common/src/types/field.ts
- packages/common/src/types/metricQuery.ts
- packages/common/src/types/table.ts
- packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx
- packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeNodes.tsx
- packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeProvider.tsx
Closes: #4000 
Example yml:
```
models:
- name: customers
meta:
order_fields_by: index // or 'label'
```
We went with `index` and `label` instead of `yml` and `alphabetically` because this opens the possibilities for future order options. eg: `type`, `name` 
Notes on the order logic:
- since metrics can be declared in multiple places we forced the following order: `dbt metrics > metrics in model metadata > metrics in dimension metadata`
- group labels inherit the index of the first dimension that uses it
- fields order defaults to `label` 
The code is also 90% ready to support the `index` in the dimension/metric metadata, in case the user wants to override the order mentioned above. We can add this in a future PR if users ask for it. 
Preview: …
> feat: order fields by index

- packages/backend/src/models/ProjectModel/ProjectModel.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
Reduce amount of IO from the database by only loading a single explore from the cache (currently we load all of them to get a single explore)
This is a large part of the time spent during `/availableFilters` (see: #4259)
> refactor: filter explores in cache

- packages/backend/src/database/migrations/20230202114455_add_index_to_analytics_tables.ts
Fetching a chart definition now includes views and the database is query is very slow. This is because counting views involves a full table scan. I've added an index to make it much faster to search for chart views and dashboard views by uuid.
> fix: add indices to analytics tables

- packages/frontend/src/components/common/ResourceList/ResourceTable.styles.ts
Closes: https://github.com/lightdash/lightdash/issues/4347
old: 
new:
@PriPatel I also increased font-size from 13 to 14 px for titles... is it too much? wdyt?
> style: tweak resource list

- packages/backend/src/services/DashboardService/DashboardService.ts
- packages/backend/src/services/SavedChartsService/SavedChartService.ts
- packages/frontend/src/components/PinnedItemsPanel/index.tsx
- packages/frontend/src/components/common/ResourceList/ResourceActionHandlers.tsx
- packages/frontend/src/components/common/ResourceList/ResourceActionMenu.tsx
- packages/frontend/src/components/common/ResourceList/index.tsx
- packages/frontend/src/hooks/pinning/useChartPinningMutation.ts
- packages/frontend/src/hooks/pinning/useDashboardPinningMutation.ts
- packages/frontend/src/pages/Home.tsx
Closes: #3043 
MVP for pinning - This ticket covers the basic functionality. The rest in this milestone will cover a better user experience and frontend improvements. 
**You can pin **charts** and **dashboards** to your homepage.** (no limit) 
**Where can you pin from?**
**Permissions**
> feat: pinned charts and dashboards component added to homepage

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/database/entities/pinnedList.ts
- packages/backend/src/models/PinnedListModel.ts
- packages/backend/src/services/DashboardService/DashboardService.ts
- packages/backend/src/services/SavedChartsService/SavedChartService.ts
- packages/backend/src/utils.ts
- packages/common/src/types/pinning.ts
Closes: #4128 
analytics event `pinned_list.updated`
triggered when a pinned list is updated (has an item added or removed from the list)
parameters include:
- user_id (user who updated the list)
- source (`homepage` if homepage, otherwise `space.the_space_name` when we create pinned lists in spaces)
- project_id (where the pinned list exists)
- organization_id (where the pinned list exists)
- timestamp
- pinned_list_id (unique identifier for a pinned list)
- pinned_items (this is a JSON blob which has the pinned items as a list.
> chore: pinned_list.updated event added

- packages/backend/src/clients/Aws/s3.ts
- packages/backend/src/routers/projectRouter.ts
- packages/common/src/index.ts
- packages/frontend/src/components/DownloadCsvPopup/index.tsx
- packages/frontend/src/components/Explorer/ResultsCard/ResultsCard.tsx
- packages/frontend/src/hooks/useDownloadCsv.tsx
Closes:   #4411
This feature will allow users to download a  csv directly from the browser, without processing all the data in the frontend
If the server has S3 enabled, it will store it on S3 and return its url, otherwise it will store it locally (/tmp) and return the file using a new lightdash endpoint
Sample CSV on s3: https://lightdash-slack-screenshots.storage.googleapis.com/csv-gOvCpyyvTB_qXUDC0pLfo.csv
> feat: csv full download

- packages/frontend/src/hooks/useQueryResults.tsx
- packages/frontend/src/providers/ExplorerProvider.tsx
Closes: #4393 
Reduced the scope of the hook dependencies to the essential. Any significant change in the chart config was causing the query to run. eg: pivoting
Before:
https://user-images.githubusercontent.com/9117144/217612526-93f85ef3-270d-4b45-ac49-313e7c00f8f4.mp4
Now: 
https://user-images.githubusercontent.com/9117144/217612640-ddb6ff47-4c22-4237-8281-c4e8160a13c2.mp4
> fix: multiple run queries on page load

- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
- packages/frontend/src/pages/Dashboard.tsx
- packages/frontend/src/providers/DashboardProvider.tsx
Closes: 
- only request the dashboard in the provider and reuse it in the page component
- only render the update modal when needed
> fix: multiple dashboard requests on page load

- packages/backend/package.json
- packages/backend/src/routers/projectRouter.ts
- yarn.lock
> fix: corrupt csv files because of commas and semicolons

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
- packages/frontend/src/pages/Dashboard.tsx
Changes:
- adds proper loading state
- await for explore to load before fetching chart results
Before:
https://user-images.githubusercontent.com/9117144/217873529-852ed6d0-a995-4344-92a2-8307f372954f.mp4
After:
https://user-images.githubusercontent.com/9117144/217873339-69cb95f0-c28a-4a52-baab-ca32d52f6a1a.mp4
> fix: chart tile loading state and duplicated requests

- packages/frontend/src/components/PinnedItemsPanel/index.tsx
- packages/frontend/src/hooks/pinning/useChartPinningMutation.ts
- packages/frontend/src/hooks/pinning/useDashboardPinningMutation.ts
Closes: #4433 
When pinning or unpinning a chart or dashboard, if you select the action menu again, the copy won't have updated and will be suggesting the opposite, incorrect action. 
e.g. when you've just pinned a dashbord, the action menu still has the item "Pin to homepage" instead of "Unpin from homepage". Likewise (but inverse) with unpinning.
> fix: spaces page action menu doesnt update pinning status

- packages/backend/src/controllers/schedulerController.ts
- packages/backend/src/controllers/shareController.ts
- packages/backend/src/routers/dashboardRouter.ts
- packages/backend/src/routers/organizationRouter.ts
- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/routers/savedChartRouter.ts
Closes: #3358 
Make most endpoints support authentication with Personal Access Token. 
Excludes endpoints to create/edit/delete:
- user
- organisation
- integrations ( slack/dbt )
Also fixes some endpoints that should not be available in the demo.
> feat: support personal access tokens across endpoints

- packages/frontend/src/components/NavBar/ExploreMenu/index.tsx
- packages/frontend/src/components/SpacePanel/index.tsx
Closes: #4454 
Space panels (image below) were using the old `Create a new dashboard` flow i.e. a dashboard named `Untitled` is created by default and the user is redirected to it. 
New flow: popover to choose `name` and `description`, on `create` button click, user is redirected to new dashboard in `edit mode`.
I thoroughly tested all other places in the app from which we can `Create a dashboard` and the new flow is now implemented throughout the app. This was the only miss.
> fix: create a new dashboard flow should be uniform

- packages/common/src/index.ts
- packages/common/src/utils/item.ts
- packages/e2e/cypress/e2e/createProjects.cy.ts
- packages/e2e/cypress/e2e/explore.cy.ts
- packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
- packages/frontend/src/components/ChartConfigPanel/Series/BasicSeriesConfiguration.tsx
- packages/frontend/src/components/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes: #4391 
Table names can make labels and legends confusing, even when joining other tables it might be unhelpful. 
They should be hidden. Based on user research, there have been no real convincing cases that have come up to suggest that table names are useful in axes.
> feat: hide table names from chart labels

- packages/frontend/src/components/PinnedItemsPanel/index.tsx
- packages/frontend/src/components/common/ResourceList/ResourceList.styles.ts
- packages/frontend/src/components/common/ResourceList/ResourceListWrapper.tsx
- packages/frontend/src/components/common/ResourceList/index.tsx
- packages/frontend/src/pages/Home.tsx
Closes: #4444 
`Pin Spaces, Dashboards and Charts to the top of the homepage to guide your business users to the right content.`
`Your data team have pinned these items to help guide you towards the most relevant content!`
> feat: info icon to give different users context on pinned items

- packages/frontend/src/components/RefreshDbtButton/index.tsx
Closes: #2063 
When the user hovers over the refresh dbt, it would be useful to have a couple of lines explaining when this action should be carried out. 
```
If you've updated your YAML files, you can sync your changes to Lightdash by clicking this button.
```
> feat: tooltip on refresh dbt button added

- docs/docs/references/metrics.mdx
- packages/common/src/types/filterGrammar.test.ts
Closes: 
@rephus do we support underscore as an operator? It's not in the docs but in the grammar it looks like it has a special meaning
> docs: add docs + test for underscores in filters

- packages/frontend/src/components/Explorer/SpaceBrowser/AddResourceToSpaceMenu.styles.ts
- packages/frontend/src/components/Explorer/SpaceBrowser/AddResourceToSpaceMenu.tsx
- packages/frontend/src/components/Explorer/SpaceBrowser/SpaceBrowser.styles.tsx
- packages/frontend/src/components/Home/RecentlyUpdatedPanel/index.tsx
- packages/frontend/src/components/PinnedItemsPanel/index.tsx
- packages/frontend/src/components/SpacePanel/index.tsx
- packages/frontend/src/components/common/ResourceList/ResourceTable.tsx
> feat: updates to spaces page

- packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
- packages/frontend/src/components/PinnedItemsPanel/index.tsx
- packages/frontend/src/components/ReactHookForm/PasswordInput.tsx
- packages/frontend/src/components/UserSettings/CreateTokenPanel/index.tsx
- packages/frontend/src/components/UserSettings/UserManagementPanel/InviteSuccess.tsx
- packages/frontend/src/components/common/Table/index.tsx
- packages/frontend/src/hooks/thirdPartyServices/useSentry.ts
- packages/frontend/src/pages/SqlRunner.tsx
As requested by @rephus - this only sends replays when there is an error (60s buffer of user activity). It doesn't capture anything otherwise
> chore: add sentry replays

- packages/frontend/src/pages/SavedDashboards.tsx
- packages/frontend/src/pages/SavedQueries.tsx
> fix: hide type column from all charts and all dashboards tables

- packages/frontend/src/pages/Dashboard.tsx
- packages/frontend/src/pages/Home.tsx
- packages/frontend/src/pages/Projects.tsx
> fix: improving loading states

- packages/frontend/src/components/SettingsUsageAnalytics/SettingsUsageAnalytics.styles.ts
- packages/frontend/src/components/SettingsUsageAnalytics/index.tsx
> fix: updating styling on usage analytics tab

- .github/workflows/cli-test.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/manual-trigger-e2e-tests.yml
- .github/workflows/security.yml
- .github/workflows/timezone-tests.yml
- packages/e2e/cypress/e2e/api/api.cy.ts
- packages/e2e/cypress/e2e/api/pinning.cy.ts
- packages/e2e/cypress/e2e/api/scheduler.cy.ts
- packages/e2e/cypress/e2e/createProjects.cy.ts
- packages/e2e/cypress/e2e/dashboard.cy.ts
- packages/e2e/cypress/e2e/dates.cy.ts
- packages/e2e/cypress/e2e/explore.cy.ts
- packages/e2e/cypress/e2e/formats.cy.ts
- packages/e2e/cypress/e2e/globalSearch.cy.ts
- packages/e2e/cypress/e2e/savedDashboards.cy.ts
- packages/e2e/cypress/e2e/settings/profile.cy.ts
- packages/e2e/cypress/e2e/sqlrunner.cy.ts
- packages/e2e/cypress/support/commands.ts
- packages/e2e/cypress/support/e2e.ts
- packages/e2e/package.json
- yarn.lock
Closes: 
Update GitHub action versions:
- actions/checkout@v2 -> actions/checkout@v3
- actions/setup-python@v1 -> actions/setup-python@v4
- cypress-io/github-action@v4 -> cypress-io/github-action@v5
- actions/upload-artifact@v2 -> actions/upload-artifact@v3
Update cypress container:
- cypress/browsers:node14.19.0-chrome100-ff99-edge -> cypress/browsers:node18.12.0-chrome107 
It only installs chrome, instead of chrome + firefox+edge, so it should be much faster 🙏 
Cypress:
- Update to latest version
- Update how cypress stores and reuses the session cookies
- Fix some typing issues
Creates and then reuses
Recreates after we logout
> chore: update cypress and github actions versions

- packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
- packages/frontend/src/components/DashboardTiles/TileForms/TileUpdateModal.tsx
Closes: #4312 
before
https://user-images.githubusercontent.com/67699259/220104899-4548b63e-90d8-4a28-b724-a7b09f668fb2.mov
after
https://user-images.githubusercontent.com/67699259/220104917-b094c338-56f5-4dd2-a0b8-7176e6c07ff5.mov
> fix: when editing tile click affects elements behind modal

- packages/frontend/src/components/ExploreFromHereButton/index.tsx
> fix: explore from here button is too big

- packages/backend/src/projectAdapters/dbtNoneCredentialsProjectAdapter.ts
- packages/backend/src/projectAdapters/projectAdapter.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/frontend/src/components/ProjectConnection/DbtForms/DbtNoneForm.tsx
- packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx
- packages/frontend/src/components/ProjectConnection/index.tsx
Closes: #4356
Temporary fix until we refactor the settings page and endpoints to decouple compiling from updating warehouse settings.
* Simplify the none project adapter by removing unneeded logic
* Add error if trying to compile a project with a none adapter (possible on the `/refresh` endpoint and `/create` endpoint for projects)
* Remove extra fields from the dbt form in the UI for CLI projects
* Switch the `PATCH /project/{projectUuid}` endpoint to skip compilation for CLI projects
* Switch UI copy on th dbt form for CLI projects
> fix: skip compile on project update

- packages/frontend/src/components/NavBar/NavBar.styles.tsx
> feat: icons shouldnt have white fill when active

- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
> fix: show dashboard header without action buttons to viewers

- packages/e2e/cypress/e2e/settings/invites.cy.ts
Closes: 
When we enable email on PRs, a e2e test fails because the text of the `generate invite` button changes. 
This PR allows both buttons
> chore: fix invite email e2e test

- packages/frontend/src/components/Explorer/ResultsCard/CellContextMenu.tsx
- packages/frontend/src/components/SimpleTable/CellContextMenu.tsx
- packages/frontend/src/components/SimpleTable/DashboardCellContextMenu.tsx
Closes: #4493
before (screenshots from dashboard)
after
> feat: hide `View underlying data` for dimensions

- packages/frontend/src/components/Home/RecentlyUpdatedPanel/index.tsx
- packages/frontend/src/components/common/ResourceView/index.tsx
> fix: most popular items

- packages/cli/package.json
- packages/cli/src/index.ts
- yarn.lock
Closes: #4552 
Our CLI is optimized for node v16 even though it might work with other versions. We are now showing a warning when the user is running with a different major version.
> chore: show warning when node version is not v16

- packages/frontend/src/components/common/Filters/FieldAutoComplete.tsx
it looks like the icons for selected fields aren't vertically centered.
> fix: vertically center icons in selected fields

- packages/backend/src/index.ts
Fixes error where accessing the root still returned a caching policy. The root is being overridden somewhere in the `index.ts` so adding an explicit route for `/` with a higher priority fixed the headers.
* ❌ `/` is cacheable
* ✅ every other path (e.g. `/login`) returned no-cache
```
➜  ~ curl -s -o /dev/null -D - http://localhost:8080/login
HTTP/1.1 200 OK
X-Powered-By: Express
Cache-Control: no-cache, private
...
➜  ~ curl -s -o /dev/null -D - http://localhost:8080
HTTP/1.1 200 OK
X-Powered-By: Express
Cache-Control: public, max-age=0
...
```
* ✅ all routes including `/` returns no-cache
```
➜  ~ curl -s -o /dev/null -D - http://localhost:8080/login
HTTP/1.1 200 OK
X-Powered-By: Express
Cache-Control: no-cache, private
...
➜  ~ curl -s -o /dev/null -D - http://localhost:8080 …
```
> fix: override cache-control on express root

- packages/backend/src/services/ShareService/ShareService.mock.ts
- packages/backend/src/services/ShareService/ShareService.test.ts
- packages/backend/src/services/ShareService/ShareService.ts
Closes: #4623
Converting a shared URL to a full URL needed at least view access to the whole org. Now we just check that they can access a member profile in the org (effectively, whether they are a member).
Before: https://www.loom.com/share/582d7ee21e2c40dfab8b46e7d7f1d47a
After: https://www.loom.com/share/769d0b7ffc3540e29be50a19dde2c653
I'm not sure why we track organizationUuid on the share URLs at all, from what I can see I'm 80% sure we could delete that relationship, since we always enforce all checks on access after getting the full URL. I suppose this stops people from outside the org being able to see the full URL. Is that necessary?
> fix: org members can get share urls

- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulerModalBase.styles.ts
- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/index.tsx
> fix: styling changes for scheduled deliveries

- packages/backend/src/index.ts
- packages/backend/src/scheduler.ts
- packages/backend/src/scheduler/SchedulerClient.ts
- packages/backend/src/scheduler/SchedulerWorker.ts
- packages/e2e/cypress/e2e/api/scheduler.cy.ts
Closes: 
Fix error:
```[Lightdash] error: Unable to schedule job for scheduler 53852685-84f6-4c95-96ab-ea45dbadbec4 duplicate key value violates unique constraint "pg_namespace_nspname_index"```
We should have more logs about the schedule worker. eg:
```
2023-03-02 12:07:03 [Lightdash] info: Worker connected and looking for jobs... (task names: 'generateDailyJobs', 'handleScheduledDelivery', 'sendSlackNotification', 'sendEmailNotification')
2023-03-02 12:07:03 [Lightdash] debug: Found task 1345 (handleScheduledDelivery)
2023-03-02 12:07:38 [Lightdash] info: Completed task 1345 (handleScheduledDelivery) with success (35377.41ms)
```
> fix: scheduler migration

- packages/backend/src/database/entities/emails.ts
- packages/backend/src/database/migrations/20230301085912_add_verified_column_to_email_table.ts
- packages/backend/src/models/EmailModel.ts
- packages/backend/src/models/UserModel.ts
- packages/backend/src/services/UserService.ts
Closes #4633 
Closes #4632 
- Adds a verified flag to emails
- Whenever an SSO user logs/in registers, we verify any emails that user has in Lightdash if it matches the email on their SSO profile
- Renamed a function in `userService`
- Enforced that emails received from OIDC signups are lower-cased before inserting into the DB, since lower case is not guaranteed from OIDC issuers (we already do this with emails on the password login endpoints)
**Testing**
Tested locally with Google SSO configured
- Verifies on login ✅ 
- Verifies on new account creation with new org ✅ 
- Verifies on new account creation from invite ✅ 
- Verifies from adding new social login to existing account ✅ 
- Cannot verify another users email ✅ (even if your SSO email is already in use by another Lightdash user as …
> feat: verify emails for SSO users

- packages/backend/src/clients/Aws/s3.ts
Closes: #4656 
- Makes the `S3_ACCESS_KEY` and `S3_SECRET_KEY` environment variables optional for S3 storage in order to allow more secure IAM role authentication for AWS users.
> feat: allow iam role authentication for s3 storage

- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/ResourceViewGridChartItem.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/ResourceViewGridDashboardItem.tsx
Closes: #4657 
this issue is a combination of:
- bug with Safari rendering < only addressing this bug in the PR.
- DIV inside A tag (kinda an anti-pattern)
> fix: safari mantine divider issue

- packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx
Closes: #4663 
Metrics
Custom Metrics
> feat: move empty state metrics text to pop over

- examples/api/verify-emails.http
- packages/backend/src/@types/knex-tables.d.ts
- packages/backend/src/clients/EmailClient/EmailClient.ts
- packages/backend/src/clients/EmailClient/templates/oneTimePasscode.html
- packages/backend/src/controllers/userController.ts
- packages/backend/src/database/entities/email_one_time_passcodes.ts
- packages/backend/src/database/entities/emails.ts
- packages/backend/src/database/migrations/20230301161351_add_email_otp_table.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/models/EmailModel.ts
- packages/backend/src/models/UserModel.ts
- packages/backend/src/services/UserService.ts
- packages/common/src/index.ts
- packages/common/src/types/email.ts
Closes: #4635 
Blocked by: #4648 
- Adds OTP table to db
- Adds models manage OTPs
- New endpoint to trigger OTP emails
See `examples/api/verify-emails.http` to:
- login
- check your verification status
- trigger a new top
- check verification status again
- try and verify with a passcode
> feat: add OTP flow for email verification

- packages/cli/src/dbt/templating.ts
Closes: #4679
Add's parser for `var` jinja blocks in `profiles.yml`
Example Usage:
```bash
$ node ./packages/cli/dist/index.js deploy --create --profiles-dir . --vars '{"branch": "develop"}' --target ci
```
> feat: add jinja parser for var from cli

- CHANGELOG.md
- examples/api/org-allowed-email-domains.http
- package.json
- packages/backend/package.json
- packages/backend/src/@types/knex-tables.d.ts
- packages/backend/src/controllers/organizationController.ts
- packages/backend/src/database/entities/organizations.ts
- packages/backend/src/database/entities/organizationsAllowedEmailDomains.ts
- packages/backend/src/database/migrations/20230309122217_create_org_allowed_email_domains_table.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/models/OrganizationAllowedEmailDomainsModel.ts
- packages/backend/src/models/models.ts
- packages/backend/src/services/OrganizationService/OrganizationService.test.ts
- packages/backend/src/services/OrganizationService/OrganizationService.ts
- packages/backend/src/services/services.ts
- packages/cli/package.json
- packages/common/package.json
- packages/common/src/types/organization.ts
- packages/e2e/package.json
- packages/frontend/package.json
- packages/warehouses/package.json
Related to: #4716 
Changes:
- new table, entity, model ( added a new table in case we want to have multiple settings for each organisation )
- new methods in organisation service to manage allowed email domains
- new endpoints
Endpoints:
```
GET http://localhost:8080/api/v1/org/allowedEmailDomains
PATCH http://localhost:8080/api/v1/org/allowedEmailDomains
Content-Type: application/json
{
"organizationUuid": "172a2270-000f-42be-9c68-c4752c23ae51",
"emailDomains": ["lightdash.com"],
"role": "viewer",
"projectUuids": []
}
```
https://user-images.githubusercontent.com/9117144/224058113-ddf49073-8149-4949-b288-c3016368272b.mp4
> feat: endpoints for organisation allowed email domains

- packages/backend/src/database/migrations/20230309224308_fix_email_id_on_delete.ts
- packages/backend/src/services/UserService.ts
- packages/frontend/src/App.tsx
- packages/frontend/src/components/AppRoute.tsx
- packages/frontend/src/components/PrivateRoute.tsx
- packages/frontend/src/hooks/useEmailVerification.tsx
- packages/frontend/src/pages/SignUp.styles.tsx
- packages/frontend/src/pages/Signup.tsx
- packages/frontend/src/pages/VerifyEmail.tsx
- packages/frontend/src/types/Events.ts
Closes: #3650 
If the email server is configured, the user needs to verify their email during onboarding. 
Note that we had to **disable verification for PR environments** so the e2e tests could pass. **All tests need to be done locally.** 
https://user-images.githubusercontent.com/9117144/224180602-7bdebe52-9c44-4037-8b28-393aaa5548b8.mp4
https://user-images.githubusercontent.com/9117144/224180661-9fc8b682-5892-4e0f-a71c-79c2caf210c2.mp4
https://user-images.githubusercontent.com/9117144/224182635-96e27471-c0e4-4754-95ae-904a91d2eec0.mp4
https://user-images.githubusercontent.com/9117144/224182894-0f8a3111-fbb3-400e-8604-5f449e32e300.mp4
https://user-images.githubusercontent.com/9117144/224185392-6e75801b-81e0-4486-ab9d-544d272ae77a.mp4 …
> feat: verify email when user signs up or is invited

- .github/workflows/cli-test.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/timezone-tests.yml
Closes: #4744 
this was not working because workflows have a check that automatically generated render env can't pass.
standard PR services have following names:
automatically generated render blueprint services have different names:
> chore: don't skip external PR tests

- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulerForm.tsx
The tooltip on hover for adding a scheduled delivery via email references "a slack scheduled delivery" where it should instead say "an email scheduled delivery"
> fix: typo in email scheduled delivery tooltip

- .github/workflows/release-on-merge.yml
Uses a personal access token in the repository secrets to push to main without branch protection rules
> fix: add GitHub token on release workflow

- packages/backend/src/services/CsvService/CsvService.ts
Closes: #4723 
Force formatting when the type of the value is date or timestamp.
Before:
After:
> fix: csv date export format

- packages/frontend/src/components/NavBar/BrowseMenu/index.tsx
> fix: sorting spaces alphabetically in browse menu

- packages/frontend/src/components/SpacePanel/index.tsx
Closes: #4802 
Removed the add button on the space page in case the user cannot manage dashboards or charts.
https://www.loom.com/share/8a9a560abec44526b847ac29b4f84b5a
> fix: disable add button for viewer on space page

- packages/frontend/src/components/Home/LandingPanel/LandingPanel.styles.tsx
- packages/frontend/src/components/Home/LandingPanel/index.tsx
> feat: migrate landing panel to Mantine

- .github/workflows/test-and-build.yml
- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/clients/Aws/s3.ts
- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/services/CsvService/CsvService.mock.ts
- packages/backend/src/services/CsvService/CsvService.test.ts
- packages/backend/src/services/CsvService/CsvService.ts
- packages/backend/src/services/CsvService/convertRowsToCsv.js
- packages/backend/src/services/ProjectService/ProjectService.ts
Closes: #4737
List of changes: 
- instead of using APItoCSv, I created a RowToCsv, which takes the raw results form the warehouse, and format the row and convert to CSV in chunks. 
- We still need the worker to not lock the thread and  keep the API responsive
- I always write into a file using a stream, if S3 is enabled, then I read the file and push into S3, otherwise I serve the same file locally
- Added CSV unit tests ! 
- Updated both /downloadCsv endpoint and scheduler job 
Before: 
1M cells CSVs was taking about 1.5Gb memory, and crashing with 2M
500k
1M 
Now 1M:
> feat: csv performance tweaks

- packages/frontend/src/pages/SavedQueries.tsx
> feat: `All Saved Charts` page components migrated to Mantine

- packages/frontend/src/pages/SavedDashboards.tsx
> feat: `All Dashboards` page migrated to Mantine

- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/frontend/src/hooks/useQueryResults.tsx
Closes: #4569
Move underlying data to a separte backeend endpoint. 
I added some permission check placeholder (same as runQuery)
> feat: run underlying data query on separate endpoint

- packages/frontend/src/components/SpacePanel/index.tsx
- packages/frontend/src/components/common/ShareSpaceModal/index.tsx
- packages/frontend/src/pages/Space.tsx
Closes: 
migrated to Mantine
```
wrappers
breadcrumbs
Share button
Three dots button
```
refactored
```
Page header components (i.e. breadcrumbs, share button, three dots button) 
previously in SpacePanel are now in SpacePage
```
> feat: migrating space page buttons and wrappers to Mantine

- packages/e2e/cypress/e2e/createProjects.cy.ts
- packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
- packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts
- packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
- packages/warehouses/src/warehouseClients/RedshiftWarehouseClient.ts
- packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
- packages/warehouses/src/warehouseClients/TrinoWarehouseClient.ts
- packages/warehouses/src/warehouseClients/WarehouseBaseClient.ts
Closes: 
**Add a base client that all warehouse clients extend from.** 
This is necessary so we can move all the SQL generation from the common package into the warehouse clients. 
The base client should have the default logic/SQL. And each warehouse client should be able to override/intercept that logic/SQL.  You can see we already do it with `getMetricSql` 
Motivation: https://lightdash-community.slack.com/archives/C03MG2VTR08/p1678734136416819
> chore: warehouse base client

- packages/e2e/cypress/e2e/login.cy.ts
- packages/frontend/package.json
- packages/frontend/src/pages/Login.tsx
Closes: #4812 
what this POC revealed
```
- we can use Mantine useForm hook to replace react-use-form
- it's fairly straightforward to migrate forms, given they are well built
- in order to completely migrate the Sign in Page, we need to migrate: 
SSO login buttons, AboutFooter, Page component
```
> feat: migrate `login` form to Mantine

- packages/frontend/package.json
- packages/frontend/src/components/AboutFooter.tsx
- packages/frontend/src/components/common/ResourceView/index.tsx
Closes: #4894 
1. modals with/without update
2. footer on pages
3. footer on sidebar (SQL runner)
> feat: about footer migrated to Mantine

- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/e2e/cypress/e2e/dashboard.cy.ts
Closes: #4968
Changes: 
- Added new e2e dashboard filter 
- updated the backend to `append` filters from request to existing chart filters. 
There is no need to update the frontend to change its logic. 
[Screencast from 31-03-23 10:08:15.webm](https://user-images.githubusercontent.com/1983672/229068269-00a8a827-8fa1-48f8-bebf-213c9f834938.webm)
How I tested it: 
- I created a chart with filter orderId = 5 
- I added that chart to the dashboard
- As a viewer, I can add filters, they will be appended to the orderId = 5 (the frontend stills sends the chart filter anyway) 
- I tried to hack the request using CURL by replacing orderId = 5 with orderId = 1
- I can see in the backend that the filters are appended
- On the CURL response, I get 0 results now
> fix: append dashboard filters

- packages/common/src/types/pivot.ts
- packages/frontend/src/components/SimpleTable/index.tsx
- packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
- packages/frontend/src/pages/PivotingPOC/HeaderCell.tsx
- packages/frontend/src/pages/PivotingPOC/IndexCell.tsx
- packages/frontend/src/pages/PivotingPOC/PivotTable.tsx
- packages/frontend/src/pages/PivotingPOC/UseStyles.tsx
Metric labels are formatted correctly:
> fix: metric labels pivot table

- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/ResourceViewGridSpaceItem.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewList/index.tsx
Closes: 
found this bug
fixed it
> fix: single word long space names overflows

- packages/frontend/src/components/Home/RecentlyUpdatedPanel/index.tsx
- packages/frontend/src/components/NavBar/ExploreMenu/index.tsx
- packages/frontend/src/components/PinnedItemsPanel/index.tsx
- packages/frontend/src/components/common/MantineIcon/index.tsx
- packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx
- packages/frontend/src/pages/Home.tsx
Closes: #4979 
- passing data to `RecentlyUpdatedPanel` and `PinnedItemsPanel` as props, making them dumb components
- all loading states are now in `Home.tsx`
- migrated to Mantine `RecentlyUpdatedPanel`'s empty state (now EVERYTHING on home page is Mantified 🎉 )
- the page shows the `PageSpinner` until all data on the home page is retrieved
https://user-images.githubusercontent.com/67699259/230393088-a381c1ac-da16-4884-9a2e-34d6c51f7da5.mov
`-`
- empty state for viewers updated to make sense 😅 here's a before/after
> fix: unify loading states for home page

- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
- packages/frontend/src/components/common/PageHeader/index.tsx
Closes: #4997 
https://user-images.githubusercontent.com/74011196/231140365-79d1f42a-cb53-43f7-8657-e84a50a75bea.mov
> style: improve visuals of dashboard and chart headers

- packages/backend/src/models/ResourceViewItemModel.ts
- packages/common/src/index.ts
- packages/common/src/types/resourceViewItem.ts
- packages/frontend/src/components/Explorer/SpaceBrowser/index.tsx
- packages/frontend/src/components/Home/RecentlyUpdatedPanel/index.tsx
- packages/frontend/src/components/PinnedItemsPanel/index.tsx
- packages/frontend/src/components/common/ResourceView/ResourceActionHandlers.tsx
- packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx
- packages/frontend/src/components/common/ResourceView/ResourceIcon.tsx
- packages/frontend/src/components/common/ResourceView/ResourceLastEdited.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/ResourceViewGridChartItem.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/ResourceViewGridDashboardItem.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/ResourceViewGridSpaceItem.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/index.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewList/index.tsx
- packages/frontend/src/components/common/ResourceView/index.tsx
- packages/frontend/src/components/common/ResourceView/resourceTypeUtils.ts
- packages/frontend/src/components/common/ResourceView/resourceUtils.ts
- packages/frontend/src/pages/SavedDashboards.tsx
- packages/frontend/src/pages/SavedQueries.tsx
- packages/frontend/src/pages/Space.tsx
- packages/frontend/src/pages/Spaces.tsx
Part of a group of PRs to make a new API endpoint to get ResourceViewItems used by the frontend. Need for pinning.
* Moves `resourceViewUtils` to `@lightdash/common` (most file changes are import updates)
* Updates the `ResourceViewItemSpace` type to only include required fields
* Adds a new db query to get `ResourceViewItemSpaces` by a pinned list uuid (not used yet)
> chore: add db query for ResourceViewItemSpace

- packages/backend/src/database/seeds/development/02_saved_queries.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/e2e/cypress/e2e/dates.cy.ts
- packages/frontend/src/hooks/useQueryResults.tsx
Closes: #4983
TL;DR the chart query with dashboard filters was missing the timezone fix. 
Before:
After:
+ Bonus: I added and fixed some tests
> fix: month filter chart

- packages/frontend/src/components/ExploreFromHereButton/index.tsx
- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
- packages/frontend/src/components/ShareLinkButton/index.tsx
- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
- packages/frontend/src/components/common/ShareShortLinkButton/index.tsx
Closes: #5053 
- changed the edit, link, and more icons to Tabler icons
- Did not change the series-search icon near the "Explore from here" text, bcoz I could not find one in tabler icon.
Dashboard:
Chart:
> style: improve visuals by changing icons to tabler icons in dashboard and chart

- .github/CONTRIBUTING.md
Add demo login credentials to local dev setup instructions without Docker (they were mentioned on the with-Docker guide but not on the non-Docker one)
> docs: add demo login creds to local dev setup instructions w/o Docker

- packages/frontend/src/pages/Projects.tsx
Currently, users who join an org for the first time get redirected to the first project that's available (independently of its Project type: `Default` or `Preview`).
https://user-images.githubusercontent.com/7611706/232542404-7f34839c-6e48-4ab9-a77c-9a063c43ace7.mov
Users who join an org for the first time get redirected to the first `default` Project - if it exists.
https://user-images.githubusercontent.com/7611706/232542665-cc22c90b-1ff0-4b82-894f-04287b5eb42c.mov
> fix: redirect new user to first default project

- packages/backend/src/scheduler/SchedulerTask.ts
- packages/frontend/src/components/ExportCSV/index.tsx
adds logger to `downloadCsv` job since it's not propagating catching errors
> fix: add logger to `downloadCsv` job

- packages/backend/src/clients/Slack/Slackbot.ts
- packages/backend/src/scheduler/SchedulerTask.ts
- packages/backend/src/services/UnfurlService/UnfurlService.ts
Closes: 
I think this retry could be blocking the worker when an error happens..
> fix: disable browser retries

- packages/backend/src/controllers/userController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/services/UserService.ts
- packages/frontend/src/hooks/user/useUserDeleteMutation.ts
- packages/frontend/src/pages/JoinOrganization.tsx
Closes: #5114 
Users get stuck when registering without an invite link - since the `createOrg` mutation error doesn't get handled, the page displays an intermittent page spinner + infinite calls to `createOrg` mutation through an useEffect.
Current behaviour is registered in issue #5114.
- User tries to register (with /register)
- Create Org mutation throws `403`
- Stop flow, allow user to discard current journey 
- Redirect to /login and start over
https://user-images.githubusercontent.com/7611706/233031286-25e98376-554b-4fba-8127-fa3d2c0ebbc3.mov
https://user-images.githubusercontent.com/7611706/233032322-d1a1328f-5bc8-4f4d-b8df-d105e3ed116d.mov
https://user-images.githubusercontent.com/7611706/233031375-b49270f4-414a-4d6f-8249-ad6fe06b80e0.mov
Thanks @ZeRego for pairing on this 🎉
> fix: handle error for multiple orgs registration when it's not allowed

- packages/frontend/src/components/UserSettings/UserManagementPanel/index.tsx
- packages/frontend/src/hooks/useOrganizationUsers.ts
Closes: #5139 
Increase detail of `useDeleteUserMutation` for an organization by renaming it to `useDeleteOrganizationUserMutation`. This is necessary to avoid confusion between this hook and the newly-added hook `useUserDeleteMutation` added on #5141
> chore: rename useDeleteUserMutation hook to useDeleteOrganizationUserMutation

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/database/migrations/20220125142122_add_organisation_allowed_domains_column.ts
- packages/backend/src/database/migrations/20230308100040_remove_org_allowed_email_domains.ts
- packages/backend/src/models/OrganizationModel.ts
- packages/backend/src/services/OrganizationService/OrganizationService.mock.ts
- packages/backend/src/services/OrganizationService/OrganizationService.test.ts
- packages/backend/src/services/OrganizationService/OrganizationService.ts
Relates to: #5143 (doesn't fully close it as it's a fraction of the work that needs to be done)
Similar to: https://github.com/lightdash/lightdash/pull/5145
Rename `organisation` references to `organization` in backend package
> chore: rename organization spelling in backend

- packages/backend/src/clients/Slack/SlackMessageBlocks.ts
- packages/backend/src/scheduler/SchedulerTask.ts
Closes: #5118 
Send Slack message when there are no results from query and therefore no CSV URL. 
Example of query with no results:
Slack message example:
> feat: send slack message for empty csv results

- packages/frontend/src/App.tsx
Closes: #5022 
Before:
After: there is some space now around the image. You can notice it between the label and the top of the image (grey line)
> fix: minimal chart padding

- packages/backend/src/generated/routes.ts
- packages/backend/src/models/InviteLinkModel.ts
- packages/backend/src/models/OrganizationModel.ts
- packages/backend/src/services/OrganizationService/OrganizationService.mock.ts
- packages/backend/src/services/OrganizationService/OrganizationService.ts
- packages/common/src/index.ts
- packages/common/src/types/organization.ts
- packages/frontend/src/components/UserSettings/OrganizationPanel/index.tsx
- packages/frontend/src/hooks/organization/useOrganization.ts
Finalises work done on: 
* https://github.com/lightdash/lightdash/pull/5142
* https://github.com/lightdash/lightdash/pull/5145
* https://github.com/lightdash/lightdash/pull/5147
Closes: #5143 
Rename all instances of `organisation` to `organization` in `packages/common` and update references in `packages/backend` and `packages/frontend`. 
We now only have 3 files that reference the word `organisation` which don't need to be changed 🎉
> chore: rename organization spelling in common package

- packages/frontend/src/components/SimpleStatistic/index.tsx
- packages/frontend/src/hooks/useResizeObserver/index.ts
Closes: #4921 
Fix /minimal page Big Number chart size when capturing a screenshot to be sent on a Scheduled Delivery. Tested with Render-deployed environment. 
Thanks @IrakliJani for pairing with me on this and identifying the underlying issue with Mantine's `useResizeObserver` hook that didn't track `ref` changes and therefore didn't allow us to do the necessary calculations.
Before
After
> fix: minimal page big number chart font sizes

- packages/frontend/src/hooks/useQueryResults.tsx
Closes: https://github.com/lightdash/lightdash/issues/5085
Fixes sentry error "Non-Error promise rejection captured"
This happened for two reasons:
- `lightdashApi` throws raw objects instead of errors (but refactoring this will change 200 usages around the app)
- `useQueryResults` used `mutate` without awaiting, so when it rejected it was uncaught and the resulting response (a non-error from `lightdashApi`) was thrown to sentry. 
This only happened for errors when the user got an error when hitting the `runQuery` button
Side effects:
- `await` means that the errors will now propagate up, but this is fine because the only usage is in `ExploreProvider` and is wrapped in a `try{} catch{console.error()}` so behaviour in the app is unchanged
> fix: uncaught rejection in useQueryResults.tsx

- packages/backend/src/database/migrations/20230421072202_scheduler_log_index.ts
- packages/backend/src/models/SchedulerModel/index.ts
Closes: #5176
currently on analytics it takes 2 seconds to get the data from the backend
We load 13624 rows 
and takes 10+ seconds to render. 
I think limiting results will fix the issue. 1500 results means more than 1 every minute in a day (60*24=1440) 
I added also an index on scheduler_uuid to make it scale better. 
Another harder improvements we could implement : 
- lazy loading
- Pagination
If you have a scheduled delivery that runs once a week , and you have another delivery that runs every hour. It is possibl ethat all the logs are about the noisy scheduler. So on the scheduler dashboard it will look like it never run
This should be fixed here https://github.com/lightdash/lightdash/issues/5175
Or The fix for this would be to make a separate request per schedulerUuid... so I guess …
> fix: limit and index scheduler logs

- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulerForm.tsx
- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulerModalContent.tsx
Closes: #4890 
Currently if headless browser is disabled (no screenshot functionality available) and user creates a scheduled delivery it will ignore the `image` format field being disabled and still set it as the `format` value for the Scheduled Delivery, when it should actually be `csv`.
This PR ensures the `format` is set to `csv` when the `image` option is disabled
Current behaviour:
https://user-images.githubusercontent.com/7611706/233314288-bd141ff7-548c-4cf6-a443-992db7e889ea.mov
Solution: 
https://user-images.githubusercontent.com/7611706/233314344-f363dd60-7574-42ba-a118-012a0a8ad763.mov
> fix: handle default scheduler when headless browser is disabled

- packages/backend/src/models/SavedChartModel.ts
Investigating #5074 
- adds a transaction around `SavedChartModel.get`, which contains our slowest db calls. 
- reduces an extra table scan on `analytics_chart_views` using a CTE, this is the most expensive part of the call
(check the commits individually for a cleaner diff)
> chore: improve get chart query

- docs/docs/self-host/self-host-lightdash-docker-compose.mdx
Closes: (just fixing minor typo in docs - i did not create an issue for it)
Hi, during playing around with lightdash, I discovered following minor issue in docs (```bash): 
Here is the simple fix for it. :)
> docs: minor typo in self host lightdash docs (docker-compose)

- packages/backend/src/models/SchedulerModel/index.ts
Closes: #4861
Linked issue already explains this, but essentially this PR handles a potential `scheduler_uuid` value missing  when handling the logging of a Scheduled Job. 
(Thanks @ZeRego for pairing with me on this 🎉 )
> fix: handle undefined scheduler_uuid when logging

- packages/common/src/compiler/exploreCompiler.ts
Closes:  #5077
What happened: 
When we select fields on `sql_on` join, we basically filter the fields that are not in the list, that includes `_DAY, _MONTH` etc.
I now include groups too. 
Before: 
Now:
> fix: keep date group on joined tables

- packages/backend/src/clients/Aws/s3.ts
- packages/backend/src/services/CsvService/CsvService.test.ts
- packages/backend/src/services/CsvService/CsvService.ts
- packages/backend/src/services/services.ts
Closes: #5161
I found some errors on gcloud logs (not in sentry though) 
S3 does not have any retry method, so I don't know how to make it more resilient without knowing what the error is. 
I removed the fallback 
and I configured LightdashConfig properly. I think it was not picking up the right SITE_URL
> fix: remove local storage fallback and use lightdashconfig

- packages/backend/src/models/SchedulerModel/index.ts
Related to: https://github.com/lightdash/lightdash/pull/5184
Closes: #4861 
After discussing with @owlas & @rephus, I've added another check for the `scheduler_uuid` FK error. Not only we check for the `code` but also the `constraint` to specifically target that.
> fix: check for fk constraint on error for scheduler_uuid

- packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNodeActions.tsx
Closes: https://github.com/lightdash/lightdash/issues/5333
stops propagation of menu item events
https://user-images.githubusercontent.com/962095/235843657-4ca2a955-890f-4257-97a3-d5403e0dcecd.mp4
> fix: explore tree menu event propagation

- packages/frontend/src/components/Explorer/ResultsCard/ExplorerResultsNonIdealStates.tsx
- packages/frontend/src/components/common/EmptyState/index.tsx
Extract `EmptyState` component so it can be used as an alternative to `NonIdealState` when migrating to mantine
(cc @yasmin-e )
Thanks @IrakliJani for pointing this out!
> refactor: create common EmptyState component

- .husky/pre-commit
- package.json
follow up for: #5339 
lint-staged passes only changed pathes to the unused-exports while it should run on entire frontend project
moved `unused-exports` check directly to git hooks
> chore: unused exports git hook

- packages/frontend/src/components/UserSettings/AccessTokensPanel/AccessTokens.styles.ts
- packages/frontend/src/components/UserSettings/AccessTokensPanel/index.tsx
Closes: #5344  
before:
after:
incoming: moving `EmptyState` to common components!
> feat: migrate no tokens view to mantine

- packages/backend/src/dbt/dbtCliClient.ts
- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/scheduler/SchedulerClient.ts
- packages/backend/src/scheduler/SchedulerTask.ts
- packages/backend/src/scheduler/SchedulerWorker.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/common/src/types/scheduler.ts
Closes: #5165
Note: I haven't updated the logic for any of these methods, I'm just moving the async stuff inside scheduler. But these methods are still using the old Job table method , we'll have to refactor the backend and frontend to move this to the new sheduler log details (like csv) . I created separated tickets for this 
Moves both : 
- "Dbt refresh" -> Compile project 
- "Test and compile " (settings) -> TestAndCOmpile project
IMO these 2 functions could be merged together . But I have added a separate ticket for that . 
```
2023-05-02 14:12:34 [Lightdash] info: Worker worker-05e44e4151677f91f2 was created
2023-05-02 14:12:34 [Lightdash] debug: Spawned
2023-05-02 14:12:34 [Lightdash] debug: Worker connected and looking for jobs... (task names: 'generateDailyJobs', …
```
> feat: move compile project to scheduler

- packages/frontend/src/hooks/useBigNumberConfig.ts
Closes: #5357
Fix big number chart when `resultsData?.rows?.[0]?.[selectedField]` is undefined. 
Before: we were getting a blank screen
Now:
> fix: broken big number chart

- packages/backend/src/services/SavedChartsService/SavedChartService.ts
Adds missing access checks for Charts API. Before this it allowed users in the same project to alter charts in each other's private spaces. 
```
GET http://localhost:8080/api/v1/saved/227f0171-308c-44b3-8fcf-26f5dd2d388b
Authorization: ApiKey xx
PATCH http://localhost:8080/api/v1/saved/227f0171-308c-44b3-8fcf-26f5dd2d388b
Authorization: ApiKey xx
Content-Type: application/json
{
"name": "new name"
}
GET http://localhost:8080/api/v1/saved/227f0171-308c-44b3-8fcf-26f5dd2d388b
Authorization: ApiKey xx
PATCH http://localhost:8080/api/v1/saved/227f0171-308c-44b3-8fcf-26f5dd2d388b
Authorization: ApiKey xx
Content-Type: application/json
{
"name": "attack name"
}
```
> fix: check space access in charts api

- packages/frontend/src/components/UserSettings/AccessTokensPanel/AccessTokens.styles.ts
- packages/frontend/src/components/UserSettings/AccessTokensPanel/TokensTable.tsx
- packages/frontend/src/components/UserSettings/AccessTokensPanel/index.tsx
- packages/frontend/src/components/UserSettings/ProjectManagementPanel/ProjectManagementPanel.styles.ts
- packages/frontend/src/components/UserSettings/ProjectManagementPanel/index.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewList/index.tsx
- packages/frontend/src/hooks/styles/useTableStyles.tsx
Closes: #5329 
Change PATs List view to a `<Table>`
Create styles hook `useTableStyles` to be shared across the app. This hook also allows overrides with CSS selectors+styling
NOTE: this work does not include `Delete token` modal layout
before: 
after:
Resource List component still looks as it did before:
> feat: migrate access tokens list to mantine table

- packages/frontend/src/components/common/PageBreadcrumbs.tsx
Closes: https://github.com/lightdash/lightdash/issues/5363
> fix: mantine breadcrumb overflow

- packages/frontend/src/components/Explorer/ResultsCard/CellContextMenu.tsx
- packages/frontend/src/components/common/Table/BodyCell.tsx
- packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
- packages/frontend/src/components/common/Table/Table.styles.ts
Closes: #5121 
To avoid issues with virtualization, where the rows have different heights, we now truncate large texts.
We consider large text if there are more than 35 chars. ( an arbitrary number that is usually close to 300px )
We set those cells to have 300px width and expand them on hover or when the cell is selected.
Preview:
Preview in PR: 
https://lightdash-pr-5388.onrender.com/projects/3675b69e-8324-4110-bdca-059031aa8da3/saved/1db7e2c3-8f73-489d-a145-d30ff0043b1c/view
Note that our demo data doesn't have large text so I had to use a table calculation (table calculation values are always aligned to the right).
- Words longer that 300px won't be fully visible.
- We force the cell to be 300px when the text is longer than 35 chars, even if the text isn't truncated. This problem …
> feat: truncate large text in table cell

- packages/frontend/src/components/ProjectConnection/ProjectConnection.styles.tsx
Closes: https://github.com/lightdash/lightdash/issues/5364
not sure why but this is not present locally (fixes prod if we add 100% width to it)
> fix: settings page layout issue

- packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNode.tsx
> fix: overflow with mantine tooltips in explore panel

- packages/frontend/src/components/common/ResourceView/resourceUtils.ts
- packages/frontend/src/pages/Spaces.tsx
Closes: #5401 
When viewing All Spaces, each Link has an empty string for `projectUuid`. 
This only happens on spaces. 
Before
(see issue)
After
> fix: get correct link for a space in all spaces grid

- packages/frontend/src/components/MetricQueryData/MetricQueryDataProvider.tsx
Closes: #5356 
Haven't been able to reproduce ( it might be an edge case where a column was removed from the query or yml ) but the error report points to this line of code. The code assumes the `selectedFields` is not empty and selectedField can't be undefined, which is not true.
> fix: undefined item on chart click

- packages/frontend/src/components/common/PivotTable/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/5426
fixes bug with `getItemFromAxis` method which did not properly select a fields based on metricsAsRows enabled/disabled state
> fix: conditional formatting in new pivot table

- packages/common/src/types/pivot.ts
- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/Explorer/VisualizationCard/ShowTotalsToggle.tsx
- packages/frontend/src/components/TableConfigPanel/GeneralSettings.tsx
- packages/frontend/src/components/common/PivotTable/HeaderCell.tsx
- packages/frontend/src/components/common/PivotTable/TotalCell.tsx
- packages/frontend/src/components/common/PivotTable/ValueCellMenu.tsx
- packages/frontend/src/components/common/PivotTable/index.tsx
- packages/frontend/src/hooks/pivotTable/pivotQueryResults.test.ts
- packages/frontend/src/hooks/pivotTable/pivotQueryResults.ts
- packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
Closes: https://github.com/lightdash/lightdash/issues/4934
Closes: #5383 
row totals and column totals for pivot tables with metrics as rows
⚠️ ⚠️ ⚠️ 
**this only implements both row totals and column totals for metrics as rows**
⚠️ ⚠️ ⚠️
> feat: pivot table row totals

- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/BigNumberConfig/index.tsx
- packages/frontend/src/components/SimpleStatistic/index.tsx
- packages/frontend/src/hooks/useBigNumberConfig.ts
Closes: #2045 
**Big Number Chart config panel**:
**Big Number tile**:
> feat: big number comparison

- packages/frontend/src/components/SimpleStatistic/index.tsx
- packages/frontend/src/hooks/useBigNumberConfig.ts
Closes: #5454 
Update the styling of the Big Number comparison when it shows `n/a` (in the case where there is no previous row to compare to or the table calculation is a string).
> feat: updated styling when comparison is n/a

- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/BigNumberConfig/index.tsx
- packages/frontend/src/components/SimpleStatistic/index.tsx
- packages/frontend/src/hooks/useBigNumberConfig.ts
Closes: #4884 
For cases where an increase in a KPI metric is not a good thing, the user should be able to switch what 'green' represents. By default, red = bad and green = good. 
https://github.com/lightdash/lightdash/assets/67699259/e9991323-ceac-4fd0-a939-33accb74e899
> feat: big number comp color switch

- packages/backend/src/models/AnalyticsModel.ts
- packages/backend/src/models/SavedChartModel.ts
- packages/backend/src/routers/savedChartRouter.ts
- packages/backend/src/services/AnalyticsService/AnalyticsService.ts
- packages/backend/src/services/SavedChartsService/SavedChartService.ts
- packages/common/src/index.ts
- packages/common/src/types/analytics.ts
- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
- packages/frontend/src/components/common/PageHeader/ViewInfo.tsx
- packages/frontend/src/hooks/chart/useChartViewStats.ts
Closes: #5367 
Changes:
- remove view stats from the chart type
- in the chart page, get the chart view stats from a separate endpoint
> fix: get chart view stats in a separate endpoint

- packages/frontend/src/hooks/useResizeObserver/index.ts
Closes: #5433 
Return if no `entries` to fix `resizeObserver` loop error.
Unfortunately, I can't replicate this locally :/
Reference: https://github.com/adazzle/react-data-grid/pull/2933/files
> fix: return if no entries on resizeObserver

- packages/cli/src/index.ts
Attempting to suppress this warning but I can't reproduce the warning message with any local build. So let's try publishing with this flag and see if it takes effect
```
(node:22848) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
```
> fix: suppress aws sdk warning in cli

- packages/frontend/src/components/UserSettings/AccessTokensPanel/index.tsx
Rendering logic wasn't correct for empty PATs list. 
Before
https://github.com/lightdash/lightdash/assets/7611706/02636e59-3c5c-49f3-8625-29aa6af15acf
After
https://github.com/lightdash/lightdash/assets/7611706/4345c1de-761f-4f8d-8a6a-c4732a2a3cdf
> fix: add correct rendering logic for empty pats list

- packages/frontend/src/components/DashboardTiles/EmptyStateNoTiles/index.tsx
- packages/frontend/src/components/Explorer/SpaceBrowser/AddResourceToSpaceModal.tsx
- packages/frontend/src/hooks/useSpaces.ts
- packages/frontend/src/pages/Home.tsx
- packages/frontend/src/pages/Space.tsx
Just noticed there are still `/spaces-and-content` queries happening on the dashboard page.
Went and cleared up more usages.
> fix: use space summaries where possible in frontend

- packages/frontend/src/components/NavBar/HeadwayMenuItem.tsx
- packages/frontend/src/components/NavBar/index.tsx
Relates to: #5324 
Ahead of new notifications (for validation errors) tab:
* change bell icon to sparkles
* move that icon to the end
Before
After
> feat: change and move headway icon

- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/common/src/types/conditionalRule.ts
- packages/common/src/types/filter.ts
- packages/common/src/utils/conditionalFormatting.ts
- packages/frontend/src/components/DashboardFilter/index.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/AutoComplete/MultiAutoComplete.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FiltersProvider.tsx
- packages/frontend/src/hooks/useFieldValues.ts
- packages/frontend/src/providers/DashboardProvider.tsx
Closes: #3651 
Changes:
- FE sends dashboard filters to "auto complete" endpoint
- BE adds the relevant filters to the search SQL. relevant filters = the filter table is the same
Example: ( on the right you can see the SQL query with the relevant filters )
https://github.com/lightdash/lightdash/assets/9117144/ac0c39e7-fb6d-4dae-920e-8f938cd64958
> feat: apply relevant dashboard filters to autocomplete search

- packages/frontend/src/hooks/useSavedQuery.ts
Closes: #5515 
Remove timezone from filter dates, right before making the API request.
Related to fix in this recent PR https://github.com/lightdash/lightdash/commit/cf1c4765f1fe128979bb2067148afa3dc1572fb1
> fix: filter timezone when saving chart

- packages/frontend/src/components/SettingsValidator/index.tsx
Closes: 
Add `word-break: break-all` to validation errors 
before
after
> fix: add break-all to validation erros

- packages/frontend/src/components/SettingsValidator/index.tsx
Relates to: #5324 
Change `key` to be index instead of `name` so that we avoid `Table` errors to have the same key in table.
> fix: change key to be index

- packages/common/src/types/pivot.ts
- packages/frontend/src/components/Explorer/VisualizationCard/ShowTotalsToggle.tsx
- packages/frontend/src/components/TableConfigPanel/GeneralSettings.tsx
- packages/frontend/src/components/common/PivotTable/index.tsx
- packages/frontend/src/hooks/pivotTable/pivotQueryResults.ts
- packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
Closes: #3245 
Changes:
- add row totals option ( column totals when metrics as rows )
- take into account hidden metrics and metrics that can't have a total ( eg: average )
Row totals
Column totals ( metric as rows )
The option is available when there is a group ( the same way we have for "metric as rows" ):
> feat: row totals

- packages/frontend/src/components/NavBar/HeadwayMenuItem.tsx
- packages/frontend/src/components/NavBar/NotificationsMenu/index.tsx
Relates to: #5324 
- Move Headway icon to top right
- Make sure both indicators/badges are matching in size and color (notifications vs headway )
- Remove some broken animations from Headway's widget badge: `bounce`, `shake`, and `wobble`
Recording: 
https://github.com/lightdash/lightdash/assets/7611706/15f6e85c-20a7-4ea0-aebc-eaca7ae6cab4
> feat: move headway badge to top right

- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/e2e/cypress/e2e/api/projectPermissions.cy.ts
Closes: #5545 
Changes:
- check user permission when updating explores
- check user permission on methods that are triggered via scheduler jobs
- add e2e tests
> fix: check permission on explores update

- packages/backend/src/database/entities/validation.ts
- packages/backend/src/models/SpaceModel.ts
- packages/common/src/types/dashboard.ts
- packages/common/src/types/savedCharts.ts
- packages/common/src/types/space.ts
- packages/common/src/types/validation.ts
Related to: https://github.com/lightdash/lightdash/issues/5325 and a consequence of: https://github.com/lightdash/lightdash/pull/5570#issuecomment-1557352109
* Add `validationError` property (if found) to charts and dashboards queried in the SpaceModel. 
There will be more work done after this PR on: 
* Saved Charts model
* Dashboards Model 
And wherever we might need.
> feat: add validation status to spaceModel

- packages/backend/src/models/SpaceModel.ts
Closes: 
Changes: 
- exclude null values from access array
Before: `[null]`
After: `[]`
> fix: get space summary sql to exclude null values from access array

- packages/backend/src/models/ValidationModel/ValidationModel.ts
Closes: #5587
Get all errors per chart and dashboard by removing the `distinctOn`.
> fix: get all errors per chart and dashboard

- packages/backend/src/models/ProjectModel/ProjectModel.ts
Closes: 
The tile_uuids behave a bit different to other uuids, i tis important we keep the same uuid between dashboard versions, as they need to match version + tile uuid
> fix: duplicated tile uuids

- packages/frontend/src/components/SimpleStatistic/index.tsx
> fix: big number comp arrow margin

- packages/frontend/src/components/Explorer/ExploreTree/TableTree/index.tsx
Closes: #5368 #5483 
before
after
> fix: hide collapsed tables pill

- packages/backend/src/models/DashboardModel/DashboardModel.ts
- packages/backend/src/models/SpaceModel.ts
- packages/common/src/types/resourceViewItem.ts
- packages/common/src/types/validation.ts
- packages/frontend/src/components/SettingsValidator/ValidatorTable.tsx
- packages/frontend/src/components/SettingsValidator/hooks/useScrollAndHighlight.ts
- packages/frontend/src/components/common/ResourceView/ResourceIcon.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewList/index.tsx
- packages/frontend/src/components/common/ResourceView/resourceUtils.ts
Closes: #5325
Add warning icon to `ResourceIcon`s in case there are validation errors for that chart/dashboard
The tooltip is different between admins/developers and the rest of the org. 
For Admins/Developers:
https://github.com/lightdash/lightdash/assets/7611706/b558d907-117b-43f7-8528-f231c5a59eef
on click of link in tooltip, the user gets redirected to the validator page and scrolled to the first error and it gets highlighted. 
For Non-admins/developers:
https://github.com/lightdash/lightdash/assets/7611706/76f3a96e-dc3e-4a21-bf6b-fd88450e0cda
More scenarios:
https://github.com/lightdash/lightdash/assets/7611706/5e8c351c-4ed2-4431-a328-c4d95b390271
NB: Had to control the `Tooltip` component so we can interact with its content on hover. Hopefully, the comments make sense.
> feat: add validation error indicator for resource items

- packages/cli/src/index.ts
Closes: #4678
- Show Node version warning only on error
- Show dbt install link when error shows dbt is missing
```
⚠️ You are using Node.js version v18.11.0. Lightdash CLI is optimized for v16 so you might experience issues.
Failed to get dbt --version:
Command failed with ENOENT: dbt --version
spawn dbt ENOENT
```
```
Failed to get dbt --version:
Command failed with ENOENT: dbt --version
spawn dbt ENOENT
You must have dbt installed to use this command. See https://docs.getdbt.com/docs/core/installation for installation instructions
⚠️ You are using Node.js version v18.11.0. Lightdash CLI is optimized for v16 so you might experience issues.
```
> feat: show dbt install link on cli

- packages/common/src/types/projects.ts
- packages/warehouses/src/warehouseClients/PostgresWarehouseClient.test.ts
- packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
Stacked PR1 for #2650 (original big PR: https://github.com/lightdash/lightdash/pull/5612)
Needed for SSH Tunnels because the pool must be killed before we close an SSH tunnel.
> chore: end pg pool after query (stacked 1)

- packages/frontend/src/components/NavBar/index.tsx
Closes: #5366 
Increased the width to match the global search width `200px` > `250px`
> fix: project dropdown styling

- packages/common/src/types/savedCharts.ts
- packages/e2e/cypress/e2e/sqlrunner.cy.ts
- packages/frontend/src/components/SimpleTable/index.tsx
- packages/frontend/src/components/TableConfigPanel/GeneralSettings.tsx
- packages/frontend/src/components/common/Table/TablePagination/index.tsx
- packages/frontend/src/components/common/Table/TableProvider.tsx
- packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
Closes: #5360 
https://github.com/lightdash/lightdash/assets/67699259/e977cdce-06e0-42be-ba4f-c53c8ab4d64e
> fix: toggle tables results total

- packages/frontend/src/components/NavBar/ProjectSwitcher.tsx
- packages/frontend/src/components/NavBar/SettingsMenu.tsx
- packages/frontend/src/components/NavBar/index.tsx
- packages/frontend/src/components/SettingsUsageAnalytics/SettingsUsageAnalytics.styles.ts
- packages/frontend/src/components/UserSettings/ProjectManagementPanel/index.tsx
- packages/frontend/src/hooks/useActiveProject.ts
- packages/frontend/src/hooks/useProject.ts
- packages/frontend/src/hooks/useProjects.ts
- packages/frontend/src/pages/Projects.tsx
Closes: #5457 
I’m viewing Project X.
I am on the Usage Analytics page.
I use the project switcher to go to Project Y
I am redirected to the Usage Analytics page for Project Y.
I see the toast confirming this.
> feat: settings restructure - project switcher

- packages/backend/src/otel.ts
filesystem and database operations that happen outside of express routes are not captured
This is to clean up traces, they included a lot of filesystem reads that were not part of user requests
> fix: remove fs, pg root spans

- packages/frontend/src/pages/Settings.tsx
> fix: settings restructure collapsible navbar

- packages/backend/src/database/entities/validation.ts
- packages/backend/src/database/migrations/20230530130533_validations_update_table.ts
- packages/backend/src/models/ValidationModel/ValidationModel.ts
- packages/backend/src/scheduler/SchedulerTask.ts
- packages/backend/src/services/ValidationService/ValidationService.mock.ts
- packages/backend/src/services/ValidationService/ValidationService.test.ts
- packages/backend/src/services/ValidationService/ValidationService.ts
- packages/cli/src/handlers/validate.ts
- packages/common/src/types/validation.ts
- packages/frontend/src/components/SettingsValidator/ValidatorTable.tsx
Relates to: #5653 
Add the following new columns: 
* 'error_type' (see enum)
* 'chart_name (for dashboard errors)
* 'field_name' (for any type of error except tables)
* 'model_name' (for table/explore errors)
* 'dimension_name' (for table/explore errors)
Keep the `error` message for now
Improve types and add type guards
Will then make changes to the UI - no current properties have changes, so it will not break the UI)
> feat: update validation model and table

- packages/backend/src/otel.ts
We're not exporting metrics with otel because the node sdk isn't picking up the environment variables
> fix: workaround otel metrics env vars

- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/models/SchedulerModel/SchedulerModel.test.ts
- packages/backend/src/models/SchedulerModel/index.ts
- packages/backend/src/services/SchedulerService/SchedulerService.ts
- packages/common/src/types/scheduler.ts
Related to: #5369
No changes in the UI yet, those will be done in #5369
Changes:
- return relevant chart and dashboard names
- return log created date
- only show logs where delivery scheduled date is between 7 days ago and current time
> feat: limit scheduler logs and include chart and dashboard names

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/pages/MinimalDashboard.tsx
Closes: #5726 
We don't need to drill down the dashboard filters anymore since they are applied in `useSavedQueryWithDashboardFilters`.
https://github.com/lightdash/lightdash/assets/9117144/5e2cef1f-f14a-4086-b95f-b5da8c78b4cf
> fix: apply dashboard filters in scheduled deliveries

- packages/backend/src/database/entities/validation.ts
- packages/backend/src/database/migrations/20230602131116_validation-reset-current.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/models/ValidationModel/ValidationModel.ts
- packages/common/src/types/validation.ts
- packages/frontend/src/components/SettingsValidator/index.tsx
Relates to: #5653 
* add migration file that deletes entries where `error_type` is `null`
* change `error_type` and `errorType` to required
* remove _stale_ validation results message. 
* remove `dimension_name` - not used anymore
> feat: reset current validations and improve types

- packages/backend/src/otel.ts
These spans tell us about timings about filesystem IO, they're very noisy and not that useful
> chore: disable fs instrumentation with opentelemetry

- docs/docs/self-host/customize-deployment/configure-logging-for-lightdash.mdx
- docs/docs/self-host/customize-deployment/environment-variables.mdx
- docs/docs/self-host/self-host-lightdash.mdx
- packages/backend/setupJest.ts
- packages/backend/src/config/parseConfig.ts
- packages/backend/src/logger.ts
- packages/backend/src/models/ProjectModel/ProjectModel.mock.ts
Closes: #4291
Allows the user to configure Lightdash logging behaviour using the following environment variables:
- `LIGHTDASH_LOG_LEVEL`: The minimum level of log messages to display. Defaults to `INFO`.
- `LIGHTDASH_LOG_FORMAT`: The format of log messages. Defaults to `pretty`. Can be `plain`, `pretty`, or `json`.
- `LIGHTDASH_LOG_OUTPUTS`: The outputs to send log messages to. Defaults to `console`.
- `LIGHTDASH_LOG_CONSOLE_LEVEL`: The minimum level of log messages to display on the console. Defaults to `LIGHTDAH_LOG_LEVEL`.
- `LIGHTDASH_LOG_CONSOLE_FORMAT`: The format of log messages on the console. Defaults to `LIGHTDASH_LOG_FORMAT`.
- `LIGHTDASH_LOG_FILE_LEVEL`: The minimum level of log messages to write to the log file. Defaults to `LIGHTDASH_LOG_LEVEL`.
- …
> feat: configure logs with environment variables

- packages/frontend/src/mantineTheme.ts
Closes: #5777
Add `z-index` `20` to root `Indicator`, similar to the `Tooltip` root styling approach. 
Example with it working: 
Previously, without the overriding, the Indicator had a `z-index` set to `100`, which we don't need. 
Once we fully migrate to using Mantine UI then we can set our own `z-index` scale, if necessary.
> feat: add z-index 20 to Indicator in theme

- packages/frontend/src/hooks/useColumnTotals.ts
Closes: https://github.com/lightdash/lightdash/issues/5540
Closes: https://github.com/lightdash/lightdash/issues/5547
> fix: total exclusions for certain types

- packages/common/src/types/filterGrammar.ts
Closes:  #5791
I was forcing operator.lowercase() to compare `null` and `NULL`, but that was affecting other operators that require specific case like `startsWith`
> fix: fix operator starts with lowercase

- packages/frontend/src/components/SchedulersView/SchedulersViewUtils.tsx
- packages/frontend/src/pages/MinimalSavedExplorer.tsx
> fix: scheduled deliveries charts bg should be white

- packages/frontend/src/components/SchedulersView/SchedulersView.tsx
Closes: #5801
The problem:  We store the channel Ids , not the names in the database. 
Solution: Make a request to slack channels in the FE and get the name from the matching ID 
Alternative solutions and why I didn't do it: 
- Use slack names instead of ids : this works when sending emails, but it is not compatible with the JoinConversation slack API, so we can't use it 
- store channel_name in db: a bit messy, and it might get out of sync, so I didn't like it.
> fix: fix slack channel names on schedulers

- packages/frontend/src/hooks/useColumnTotals.ts
Closes: #5819 
there's an issue in table viz where field is expected but undefined is passed to `isSummable` https://lightdash.sentry.io/issues/4237389485/?project=5959292
> fix: summable field is undefined

- packages/backend/src/generated/routes.ts
- packages/backend/src/models/SearchModel/index.ts
- packages/common/src/types/search.ts
- packages/frontend/src/components/NavBar/GlobalSearch/SearchIcon.tsx
- packages/frontend/src/components/NavBar/GlobalSearch/hooks.ts
- packages/frontend/src/components/NavBar/GlobalSearch/index.tsx
- packages/frontend/src/mantineTheme.ts
Closes: #5639
Add visual indicator for model/table errors. 
Previously, we filtered out the explore errors from the table search results. 
Now, we do 2 things: 
- Get the explores (without errors) 
- Get the explores with errors and compare against the validation table (if they're there, get them)
At the end, we concat the errors to the tables and let the rest of the FE do its work. 
https://github.com/lightdash/lightdash/assets/7611706/acaff509-b7f3-45f7-893e-3ed42589191b
> feat: add visual indicator for model errors

- packages/backend/src/database/entities/validation.ts
- packages/backend/src/database/migrations/20230609111307_validation_set_null.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/models/ValidationModel/ValidationModel.ts
- packages/backend/src/services/ValidationService/ValidationService.test.ts
- packages/backend/src/services/ValidationService/ValidationService.ts
- packages/common/src/types/validation.ts
- packages/frontend/src/components/SettingsValidator/ValidatorTable/index.tsx
Closes: #5816
- we can't link to the chart because we no longer have the uuid, instead we don't link to anything
> feat: keep validation if content deleted

- packages/frontend/src/components/SchedulersView/SchedulersView.tsx
- packages/frontend/src/components/SchedulersView/SchedulersViewUtils.tsx
> fix: time format for scheduled deliveries dashboard

- .github/workflows/main.yml
Closes: #522 
Skip `docker` job on forked repositories `pull_request`
Unfortunately it seems that GitHub Actions does not support a similar verification on `workflow` level, only at `job` or `step`, so the workflow will start and end with a `Skipped` status
References:
- https://github.com/orgs/community/discussions/9098
- https://github.com/orgs/community/discussions/26829
> chore: skip deploy to docker hub on fork PR

- packages/frontend/src/components/SimpleTable/index.tsx
Closes: -
adds third-party block classes to pivot table viz.
> fix: prevent showing pivot table in third parties

- packages/backend/src/controllers/spaceController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/routers/projectRouter.ts
- packages/common/src/types/space.ts
Enhances: https://github.com/lightdash/lightdash/issues/5666
Added methods.
- `POST /projects/{projectUuid}/spaces/{spaceUuid}/share`
- `DELETE /projects/{projectUuid}/spaces/{spacesUuid}/share/{userUuid}`
> feat: Add APIs to add and revoke space-level access

- packages/cli/src/dbt/templating.test.ts
- packages/cli/src/dbt/templating.ts
Closes: #5926 
Changes:
Don't escape jinja templates values when parsing local dbt profile.
> fix: dont escape env_var values

- packages/frontend/src/providers/DashboardProvider.tsx
Closes: #5817 
```
In the params,
- temporary filters are 'tempFilters'
- saved filters are 'filters'
```
https://www.loom.com/share/8eaf9a23e2924c9cb7821f72254c3872?sid=2fd2ac4e-7436-42f8-8e2c-a850b7835ce8
> fix: dashboard URL should have filters (temporary and saved)

- packages/frontend/src/components/common/ResourceView/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/5912
there was a mistake in the logic where it was hiding the tab bar when there was only 1 item.
> fix: resource view tabs not visible when there is one item

- docs/package.json
When writing documentation while delivering a feature in the same PR, it's quicker to get some screenshots on local development. 
`docusaurus`'s default port is `3000` which conflicts when running dev environment.
> chore: update docusaurus port to 3002

- packages/frontend/index.html
- packages/frontend/src/components/common/PivotTable/Cell.tsx
- packages/frontend/src/components/common/PivotTable/ValueCell.tsx
- packages/frontend/src/components/common/PivotTable/tableStyles.tsx
- packages/frontend/src/providers/MantineProvider.tsx
Closes: https://github.com/lightdash/lightdash/issues/5694
> feat: inter font for tabular data

- packages/frontend/src/components/TableConfigPanel/GeneralSettings.tsx
> fix: remove unexpected columns field in chart config

- packages/frontend/src/components/common/Filters/renderFilterList.tsx
> fix: add table icon in front of table names

- packages/backend/src/controllers/organizationController.ts
Closes: https://github.com/lightdash/lightdash/issues/5987
UpdateOrganizationMember isn't available with the API key authentication due to the lack of allowApiKeyAuthentication.
> feat: allow API key authentication on `UpdateOrganizationMember`

- packages/frontend/src/components/PinnedItemsPanel/index.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/index.tsx
- packages/frontend/src/components/common/ResourceView/index.tsx
- packages/frontend/src/pages/Home.tsx
- packages/frontend/src/pages/Spaces.tsx
- packages/frontend/src/providers/PinnedItemsProvider.tsx
Closes: #5470
I'm not sure if I implemented the way the issue envisioned.
One downside I noticed is that every time a `ResourceView` type `Grid` is used, it must be wrapped by `PinnedItemsProvider` even if reordering is not enabled. (it happens on `Spaces` page)
Maybe #5847 could solve the prop drilling problem and bring more bonus. I'm opening this PR as draft to discuss it
> refactor: add pinned items context

- packages/common/src/compiler/exploreCompiler.ts
Relates to: https://github.com/lightdash/lightdash/pull/5973#pullrequestreview-1490373217
Caused by: #5998 
Get correct key for date filters. 
Currently, the cached explores return the time format uppercased (e.g. `order_date_DAY`) so the code was breaking for date filters applied to custom metrics due to ref names not matching (`order_date_day` vs `order_date_DAY`). 
Since we can assume that dimensions in an explore `table` are all unique, we can also find the one that matches the lowercased ref.
> fix: get correct key for date filters

- packages/backend/src/services/ValidationService/ValidationService.mock.ts
- packages/backend/src/services/ValidationService/ValidationService.test.ts
- packages/backend/src/services/ValidationService/ValidationService.ts
Closes: #5942
I introduce an error on payments table that was appearing on validation.
When  selected customers/orders (not payments): 
Before:
AFter:
Logs: 
I added a tag to orders
I selected that tag
No "payment errors":
> fix: only show selected tables on validation

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/services/DashboardService/DashboardService.ts
Closes: #5962 5962
Add the following new properties to `dashboard.updated` events: 
```ts
tilesCount: number;
chartTilesCount: number;
markdownTilesCount: number;
loomTilesCount: number;
filtersCount: number;
```
Also, separated the `deleted` from the `updated` events, now we have: 
* DeletedDashboardEvent
* UpdatedDashboardEvent
> chore: update dashboard_updated event 

- packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx
- packages/frontend/src/components/UserSettings/UserManagementPanel/index.tsx
Closes: #5155 
Technical changes:
```
- Migrated form to Mantine use-form
- Migrated all components to Mantine
- Added grouping by Space to Select dash dropdown
```
> feat: migrate `Move chart to dashboard` modal

- packages/e2e/cypress/e2e/explore.cy.ts
- packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
- packages/frontend/src/hooks/useExplorerRoute.ts
- packages/frontend/src/pages/Explorer.tsx
- packages/frontend/src/providers/ExplorerProvider.tsx
Closes: #5892
If someone with a MacOS could confirm for me that `mod + alt + k` is equivalent as `command + option + k` in MacOS I'd appreciate!
- `Edit`: confirmed, thanks @ZeRego!
I think it would also be interesting to communicate for the user in some way that this shortcut exists 🤔 
`Edit`: Updated video showing that selected table is persisted
https://github.com/lightdash/lightdash/assets/24387035/a21f4130-9a1c-4a1c-85e5-f618ef7bd5ec
> feat: add clear query shortcut

- packages/frontend/src/hooks/useExplorerRoute.ts
- packages/frontend/src/providers/ExplorerProvider.tsx
Closes: 
- only update explore url params where there is a pristine state ( aka: when a use runs a query )
- clear the url params when user hits `command + option + k`
> fix: only set url params with pristine state

- packages/frontend/src/components/Explorer/CustomMetricModal/index.tsx
- packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx
Closes: #5972
Users can edit and add filters to a custom metric when viewing it on the table results of an explore. 
https://github.com/lightdash/lightdash/assets/7611706/388c22cf-093c-4245-8051-ffd4495e6581
> feat: can edit filters in table results

- packages/e2e/cypress/e2e/dashboard.cy.ts
Closes: 
Problem:
e2e test was failing because the `Add` button was behind the dropdown. 
Added command to close it.
> chore: amend dashboard test

- packages/backend/src/models/SavedChartModel.ts
- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx
- packages/frontend/src/components/common/ResourceIcon/index.tsx
Closes: #5767 
Make modal bigger;
Get chart `config` from chart summaries so that we get the chart kind to render the icon
Grey out icon if chart is already in dashboard. 
https://github.com/lightdash/lightdash/assets/7611706/5a663aab-e6e7-4351-ac3b-5d29067d82c9
> feat: add chart type icon when adding to dashboard

- docs/docs/references/roles.mdx
- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/database/entities/organizations.ts
- packages/backend/src/database/migrations/20230623082425_add-prg-default-project.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/models/OrganizationModel.ts
- packages/backend/src/services/OrganizationService/OrganizationService.ts
- packages/backend/src/services/UserService.ts
- packages/common/src/types/organization.ts
- packages/frontend/src/components/UserSettings/DefaultProjectPanel/index.tsx
- packages/frontend/src/hooks/useActiveProject.ts
- packages/frontend/src/hooks/useProjects.ts
- packages/frontend/src/pages/Settings.tsx
Closes: #5869 
Default state:
Setting default project + new users joining:
https://github.com/lightdash/lightdash/assets/9117144/21f16486-0e96-4042-aedd-797a8f9436fd
> feat: organization default project

- packages/frontend/src/components/common/ResourceView/index.tsx
- packages/frontend/src/pages/Space.tsx
Closes: #5891 
If no dashboards, the default tab will be Charts
Default tab is Charts,
> fix: land on charts if dashboards are empty

- packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx
Closes: #6056 
add `searchable` prop.
https://github.com/lightdash/lightdash/assets/7611706/4a7ec38d-412c-47c4-94dd-8f9cdfbc405f
> fix: make chart dropdown searchable when adding to dashboard

- packages/frontend/src/components/common/PivotTable/index.tsx
> fix: pivot table align totals to right

- packages/backend/src/services/ValidationService/ValidationService.ts
- packages/frontend/src/hooks/validation/useValidation.ts
Closes: N/A
We were seeing too many `403` logs when users were on any page where there's a nav bar. The nav bar would get validation results (`GET` /validate), which would then retrieve the results **if** the user could manage `validation` - only admins and developers. If they didn't have the ability to do so, it would throw a 403. However, this endpoint is retried 3 times, which is unnecessary. 
Only retry the hook if it's !== 403
Also, we were pulling the project from memory when checking if the user could manage validation of a project. We can achieve the same by just getting the `user.organizationUuid` from the `get` args.
> fix: reduce retry and get org id from param when validating 

- packages/frontend/src/components/common/ResourceView/index.tsx
Re-introduces the reverted commit: https://github.com/lightdash/lightdash/commit/bcaf4b7fcc26ec374cb454382998c466e668d4bd
That was previously reverted on: 
https://github.com/lightdash/lightdash/commit/bcaf4b7fcc26ec374cb454382998c466e668d4bd
> fix: land on charts if dashboards are empty (#5931)

- packages/e2e/cypress/e2e/downloadCsv.cy.ts
- packages/frontend/src/components/BigNumberConfig/BigNumberConfigTabs.tsx
- packages/frontend/src/components/BigNumberConfig/index.tsx
- packages/frontend/src/components/ChartConfigPanel/ChartConfigPanel.styles.ts
- packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
- packages/frontend/src/components/ChartConfigPanel/index.tsx
- packages/frontend/src/components/ChartDownload.tsx
- packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
- packages/frontend/src/components/TableConfigPanel/TableConfig.styles.ts
- packages/frontend/src/components/TableConfigPanel/index.tsx
- reverts reverted mantine migration changes
- reverts back to popover2 (from mantine to blueprint popover) for table config and chart config
skip revert and only review this commit: https://github.com/lightdash/lightdash/pull/6067/commits/26e91a45c8adac8660a0573100c404b7c8dbdacb
> fix: revert of mantine config panels

- packages/backend/src/scheduler/SchedulerClient.ts
- Remove double migration (`makeWorkerUtils` already runs migrations [see source](https://github.com/graphile/worker/blob/4d05832a1712f456d92001514c9474da73b56901/src/lib.ts#L223) we don't need an extra call).
- Crash if migrations fail
`makeWorkerUtils` tries to run migrations before creating the graphile utils client. This can error for a couple of reasons:
- if multiple workers try to run migrations some, none, or all can fail
- if the database connection isn't ready it'll fail 
The problem is that the current code will cache the rejected promise on `this.graphileUtils` so the scheduler will never work but also will never exit (meaning no restarts in k8s or docker etc.). 
After this change if we can't start the migrations we catch the error, log it out, and exit the scheduler process. …
> fix: exit process when makeWorkerUtils fails

- packages/frontend/src/components/common/Filters/renderFilterItem.tsx
Closes: #5977
Add `Tooltip` of description on hover of fields in `FieldAutocomplete`
ForwardRef to `MenuItem2`: https://mantine.dev/core/tooltip/#custom-components-with-tooltip
Screenrecording: 
https://github.com/lightdash/lightdash/assets/7611706/35c29ef8-043a-449f-8c29-79bccd301b3b
> feat: display item description popover on renderFilterItem

- packages/frontend/src/hooks/dashboard/useDashboard.tsx
Closes: 
After a user creates a chart and clicks `Add to dashboard` there is an edge case that triggers an error message, even though there is no real impact to the user experience.
This is because we are trying to request a dashboard without a uuid. ( last request )
> fix: prevent dashboard request when uuid is empty

- packages/backend/src/models/ProjectModel/ProjectModel.ts
If the project content uses custom metrics, none of the content is copied to the preview project.
It errors because the custom metric table has a unique column `uuid` and we are copying its value to the preview.
> fix: preview content where charts have custom metrics

- packages/frontend/src/components/RefreshButton.tsx
- packages/frontend/src/components/common/Table/TableProvider.tsx
- packages/frontend/src/providers/BlueprintProvider.tsx
Closes:  https://github.com/lightdash/lightdash/issues/6024
- Migrate `useHotkeys` hook to mantine
**Note to reviewers: 
- I haven't checked on non-mac system, can take a look if it fails on windows**
> feat: Migrate hotkeys hooks to mantine

- packages/frontend/package.json
- packages/frontend/vite.config.ts
- yarn.lock
Users that use a browser that does not support the `.at(` method have a broken experience when adding filters to a saved chart. 
This adds `vite`'s own polyfill package: https://github.com/vitejs/vite/tree/main/packages/plugin-legacy#readme
Add `modernPolyfills` attribute with specific polyfill for the `at()` method: https://unpkg.com/browse/core-js@3.31.0/modules/ - this avoids importing the whole polyfill package and instead only imports the file in this list just for `es.array.at`
> fix: add array.at polyfill

- packages/e2e/cypress/e2e/dates.cy.ts
- packages/frontend/src/components/common/Filters/index.tsx
Closes: N/A
Add `hasGrouping` to filters in explore
Screen recordings
before
https://github.com/lightdash/lightdash/assets/7611706/3ab2abeb-56c8-4a70-b039-bec13acd5061
after
https://github.com/lightdash/lightdash/assets/7611706/24500be2-0097-4ffc-bc20-5e25fa2a28b6
> fix: add hasGrouping to filters in explore

- packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
Closes: #6065 
Tooltips apprear to the right of table name
> fix: tooltip appear to the right of table name

- packages/common/src/utils/item.ts
- packages/frontend/src/components/common/Filters/FieldAutoComplete.tsx
- packages/frontend/src/components/common/Filters/renderFilterItem.tsx
- packages/frontend/src/components/common/Filters/renderFilterList.tsx
Closes: #5977
- Removes show tooltip on hover of field (in pr #6077) - so changes to `renderFilterItem` are what's reverted
- Instead, adds tooltip on hover of table name (if there's a `description`)
- Changed a util name and added another one to get the `name` and `tableLabel` for a `field`.
https://github.com/lightdash/lightdash/assets/7611706/d6bcd774-428a-45c6-8603-09be8029097a
> feat: add description tooltip to table names when adding filters

- .github/workflows/cli-test-1.5.yml
- packages/backend/src/dbt/dbtCliClient.test.ts
- packages/backend/src/dbt/dbtCliClient.ts
- packages/cli/src/dbt/manifest.ts
- packages/cli/src/handlers/compile.ts
Closes:  https://github.com/lightdash/lightdash/issues/6104
There was a bug between dbt>=1.5.0 and <1.5.2 where the manifest was not being generated in the dir when using project-dir 
https://github.com/dbt-labs/dbt-core/releases/tag/v1.5.2
https://github.com/dbt-labs/dbt-core/issues/7819
This is affecting both the CLi and backend, where a user can use 1.5.0 and get the bug, or use 1.5.2 where the bug is no more
On cloud, we install on docker ~1.5.0 which always gets the last minor version available (1.5.2 right now) 
Backend with 1.5.0
Backend with 1.5.2
> fix: target dbt 1.5.2

- .github/workflows/count-blueprint.yml
This github action always fails for external PRs since it doesnt have access to `secrets.CI_GITHUB_TOKEN`
> chore: skip blueprint action for external PRs

- packages/e2e/cypress/e2e/settings/profile.cy.ts
Changing the email had an impact on other e2e tests that run in parallel.
> chore: dont update user email in e2e tests

- packages/backend/src/controllers/projectController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/models/SpaceModel.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/common/src/types/resourceViewItem.ts
- packages/common/src/types/space.ts
- packages/e2e/cypress/e2e/api/spacePermissions.cy.ts
- packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx
- packages/frontend/src/components/common/modal/ChartCreateModal.tsx
- packages/frontend/src/components/common/modal/DashboardCreateModal.tsx
- packages/frontend/src/hooks/useSpaces.ts
- packages/frontend/src/pages/Spaces.tsx
Closes: https://github.com/lightdash/lightdash/issues/6038
Changes:
- stop using `spaces-and-content` endpoint since it queries all dashboards and charts
- update chart summary endpoint to have all the necessary information
- allow users that can manage projects to see all private spaces
https://github.com/lightdash/lightdash/assets/9117144/4b659fb0-7fa1-4767-acfa-9be915989885
> feat: allow admins to list all private spaces

- .github/workflows/release-on-merge.yml
Pin the plugin to the last working version.
Open issue: https://github.com/jpoehnelt/semantic-release-replace-plugin/issues/221
> chore: pin plugin to last working version

- packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
Closes: #6166
I was able to replicate this by adding ssl verification to the connection ,
Before : 
And backend breaks :fire: 
After: 
Returns error and backend keeps working :+1:
> fix: postgres query error

- packages/backend/src/models/SchedulerModel/index.ts
- packages/frontend/src/components/SchedulersView/LogsView.tsx
Closes: #6070
Before:
After:
About the missaligned issue: 
This is happening because we use collapsible groups inside a cell , this means we can't align the job name with the timestamps. 
However, I was not able to replicate this locally, (see screenshots) 
A solution would be to incrase the job name size to avoid text on  2 lines , or use ellipsis... but we can do this on a separate PR.
> feat: remove duplicated job scheduler

- packages/frontend/src/components/common/ResourceView/index.tsx
- packages/frontend/src/pages/Spaces.tsx
Closes: #6170 
Change the name of the Admin all spaces tab and add a tooltip. Note that I had to add the ability to add info-tooltips to tabs.
> feat: rename admin spaces tab. Add tooltip.

- packages/e2e/cypress/e2e/api/api.cy.ts
- packages/e2e/cypress/e2e/api/organizationPermissions.cy.ts
- packages/e2e/cypress/e2e/api/projectPermissions.cy.ts
Reduce/remove flakiness from api tests. 
Since we started e2e test parallelisation the server is taking more than 500 ms to respond to some requests.
> chore: remove 500 timeout from api e2e tests

- packages/frontend/src/components/common/ResourceView/ResourceViewList/index.tsx
Closes: #6203 
Stops the info icon from wrapping when resource names are too long
> fix: stop info icon from wrapping on resource list

- .github/workflows/e2e-tests.yml
Avoid check error in `main` commits
> chore: skip e2e action on main branch

- .github/workflows/cli-tests.yml
- .github/workflows/count-blueprint.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/release-on-merge.yml
- .github/workflows/test-and-build.yml
Changes:
- cache yarn dependencies
- use `--frozen-lockfile` option 
This should reduce the time of most of github actions since we install all our dependencies multiple times.
Note: 
Still getting a few `cache not found` and I'm not sure why. Would still merge it and keep checking it during the next week.
> chore: cache yarn in github actions

- packages/e2e/cypress/e2e/createProjects.cy.ts
Changes:
- refactor part of the test that was testing results
- replaced UI tests with API tests
- improve selectors
Results when creating postgres project locally:
Before - 1min
After - 30sec
Results when creating projects in github action:
Before - 5min 28sec
After - 3min 48sec
> chore: refactor "create project" e2e tests

- .github/CONTRIBUTING.md
Adds more information to the contributing doc about PR tags. I could have used this info 😄 . 
Note that I did not open a ticket for this since it is very small and docs-only. But I can if we think that's better.
> docs: add branch prefix explanation

- packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx
- packages/frontend/src/components/Explorer/CustomMetricModal/index.tsx
- packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx
- packages/frontend/src/components/UserSettings/AccessTokensPanel/CreateTokenModal.tsx
- packages/frontend/src/components/UserSettings/AccessTokensPanel/TokensTable.tsx
- packages/frontend/src/components/UserSettings/DeleteOrganizationPanel/DeleteOrganizationModal.tsx
- packages/frontend/src/components/UserSettings/DeleteProjectPanel/DeleteProjectModal.tsx
- packages/frontend/src/components/UserSettings/InvitesModal/index.tsx
- packages/frontend/src/components/UserSettings/UserManagementPanel/index.tsx
- packages/frontend/src/mantineTheme.ts
Closes: #6082 
Defaults the Mantine modals' y-position to match the Blueprint ones. Removes centering from the Mantine modals.
> style: move mantine modals up to match blueprint's

- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/PieChartConfig/PieChartLayoutConfig.tsx
- packages/frontend/src/components/PieChartConfig/PieChartSeriesConfig.tsx
- packages/frontend/src/hooks/echarts/useEchartsPieChart.ts
- packages/frontend/src/hooks/usePieChartConfig.ts
Closes: https://github.com/lightdash/lightdash/issues/6007
⚠️ ⚠️ ⚠️  TESTING VIDEO WITH UI QUESTION: https://cln.sh/r1zJRgK4
items left:
> feat: pie charts value formatting options

- packages/frontend/src/hooks/echarts/useEcharts.ts
This reverts commit 6cf9580d47a8ce8b8d41d764b88d9957fa7db920.
Closes:
> revert: echarts show tooltip only on hovered lines/bars (#6195)

- packages/frontend/src/components/common/ResourceInfoPopup/DashboardList.tsx
- packages/frontend/src/components/common/ResourceInfoPopup/ResourceInfoPopup.tsx
Closes: #6188 
- Make link to open in new tab
> fix: make dashboard link to open in new tab for saved charts

- packages/frontend/src/components/DashboardFilter/FilterConfiguration/TileFilterConfiguration.tsx
- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes: #6301
I think this is the best way to fix it without introducing extra attributes to the chart ChartTile, but le tme know if you prefer a different approach.
Before:
After:
> fix: filter empty chart title

- packages/common/src/types/field.test.ts
- packages/common/src/types/field.ts
Closes: #4097 
**Changes:**
When generating a field ID, replace all the `.` in the field name to `__` ( double underscore )
I'm using double underscore to avoid conflicts
eg: the fields `dimension.column` and `dimension_column` in the same table would both end up as `table_dimension_column` 
**Note 1:** Even with a double underscore is possible to cause this conflict but less likely. 
**Note 2:** This PR doesn't handle the necessary SQL to access json fields in each warehouse. The developer will have to define it in their yml.  
YML:
Manifest:
Query:
> fix: handle dotted field names when generating field id

- packages/backend/src/controllers/projectController.ts
- packages/backend/src/controllers/runQueryController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/routers/projectRouter.ts
Closes: https://github.com/lightdash/lightdash/discussions/6181
Breaking change for api consumers using auto-generated clients is renaming `postRunQuery` to `runMetricQuery`
> feat: use tsoa for sql query api

- packages/backend/src/services/SchedulerService/SchedulerService.ts
- packages/frontend/src/components/NavBar/SettingsMenu.tsx
- packages/frontend/src/components/UserSettings/ProjectManagementPanel/index.tsx
- packages/frontend/src/pages/Settings.tsx
Closes: #6362 
Changes:
- amend permission in scheduled deliveries logs API
- hide "project/organization settings" navbar link if user doesn't have `update` permission
- hide "settings" button from projects list if user doesn't have `update` permission
- hide sidebar menu options if user doesn't have `update` permission
Viewer:
Interactive viewer:
Editor:
> feat: hide setting pages if user cant update

- packages/frontend/src/pages/Dashboard.tsx
Closes: #6031 
Uses Sentry's `useProfiler` to track the following React components: 
* `Dashboard`
* `Dashboard tiles per type`
Followed this guide: https://docs.sentry.io/platforms/javascript/guides/react/features/component-tracking/
example: https://lightdash.sentry.io/performance/summary/spans/?environment=development&project=5959292&query=&statsPeriod=30d&transaction=%2Fprojects%2F%3AprojectUuid%2Fdashboards%2F%3AdashboardUuid%2F%3Amode%3F
Can see it being added to the transaction _waterfall_ here: https://lightdash.sentry.io/performance/lightdash:94f33550c0d946e78b124063648ee0f8/?environment=development&project=5959292&query=&statsPeriod=1h&transaction=%2Fprojects%2F%3AprojectUuid%2Fdashboards%2F%3AdashboardUuid%2F%3Amode%3F#span-b46dfb3131718207
^ You will see duplicate `.mount`s, …
> chore: profile mounting times in dashboard and tiles

- dockerfile
- dockerfile-prs
Closes: N/A
After this release: https://github.com/starburstdata/dbt-trino/blob/master/CHANGELOG.md
our Docker build started failing. First instance: https://github.com/lightdash/lightdash/actions/runs/5579941834/jobs/10196171946
Pinning `dbt-trino` to its previous version works, but this is a temporary solution - we need to figure out which deps are clashing and how to handle it: on the code and/or by reporting a bug
> chore: pin dbt-trino to 1.5.0

- packages/common/src/types/conditionalFormatting.ts
- packages/common/src/utils/conditionalFormatting.ts
- packages/frontend/package.json
- packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormatting.tsx
- packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingList.tsx
- packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingRule.tsx
- packages/frontend/src/components/common/PivotTable/ValueCell.tsx
- packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
- packages/frontend/src/utils/colorUtils.ts
- yarn.lock
Closes: #3936 
acceptance criteria:
persisted configuration:
```js
conditionalFormattings: [
// for single color range and conditional operator
{
"color": "#fac858",
"rules": [
{
"id": "90f8b88a-b623-4853-9a9b-9ba460e7de4b",
"values": [
30
],
"operator": "greaterThan"
}
],
"target": {
"fieldId": "orders_total_order_amount"
}
},
// for multi color range and min/max values
{
"rule": {
"max": 40,
"min": 30
},
"color": {
"end": "#73c0de",
"start": "#b39e6f",
"steps": 5 // <--------- hardcoding `5` for now (generates 5 colors between `start` and `end`
},
"target": {
"fieldId": "orders_customer_id"
}
}
]
```
video demo:
https://github.com/lightdash/lightdash/assets/962095/e83a4502-1e1e-469f-9711-bc412ea4a55b
in results table:
in pivot tables:
> feat: conditional formatting color range

- packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/GeneralSettings.tsx
- packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/index.tsx
Closes: #6258 
Moves the table config popup, tabs and checkboxes to Mantine.
> chore: table config popup in Mantine

- packages/frontend/src/components/Explorer/CustomMetricModal/index.tsx
- packages/frontend/src/components/NavBar/GlobalSearch/SearchIcon.tsx
- packages/frontend/src/components/NavBar/GlobalSearch/index.tsx
- packages/frontend/src/components/NavBar/index.tsx
- packages/frontend/src/components/common/Table/Table.styles.ts
- packages/frontend/src/mantineTheme.ts
- packages/frontend/src/providers/BlueprintProvider.tsx
- packages/frontend/src/styles/blueprint-core.css
- packages/frontend/src/styles/blueprint-popover2.css
Closes: #6273
- alters blueprint-core.css with new z-indexes that is aligned with mantine
- clones blueprint-popover2.css
- alters blueprint-popover2.css with new z-indexes
- cleans up mantine z-index patches
tested:
- homepage / content pages / action modals and menus
- settings + project settings
- dashboards with modals and menus + dashboard filters
- explore:
- all chart configs
- custom filters
- filters
- sorting
- limits
- export csv
- table / viz context menus and underlying data + etc..
> chore: mantine and blueprint z indices

- packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilter.tsx
- packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilters.styles.ts
- packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
Closes: #6358 
Remove active filter if not targeting any field id
https://github.com/lightdash/lightdash/assets/7611706/bc086d5d-4ffe-4f80-8939-10a32616bb51
> fix: address ux after only chart with filter applied to is removed from dashboard

- packages/frontend/src/mantineTheme.ts
For some reason Mantine doesn't apply cursor: pointer to checkboxes and radios by default. This sets the setting to do so. 
More here:
https://mantine.dev/theming/theme-object/#cursortype
> fix: add cursor: pointer to checkboxes and radios

- packages/frontend/src/components/common/PivotTable/ValueCell.tsx
- packages/frontend/src/components/common/Table/TableProvider.tsx
Closes: #6193 
When visualising tables, the `ValueCell` component that currently uses `useHotKeys` would allow the copy of the `Cell` value if user pressed `mod + c`. However, this is blocking the copy-to-clipboard functionality everywhere else that is not a `ValueCell`. 
I believe the usage of the `useHotKeys` is affecting the other elements due to the way we're implementing the `ValueCellMenu`+`ValueCell`. 
Instead of adding the `onKeyDown` events to the `td` elements, we listen to: 
* is isMenuOpen truthy
* if user presses the copy keyboard shortcut (we now use `getHotkeyHandler`  https://mantine.dev/hooks/use-hotkeys/#targeting-elements )
NOTE: `td` elements aren't focusable by nature, so this addresses that
Don't have a screen-recording bc Quicktime player + keyboard shortcuts aren't …
> fix: unlock clipboard copy when visualising tables

- packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingList.tsx
- packages/frontend/src/hooks/echarts/useEchartsPieChart.ts
Closes: https://github.com/lightdash/lightdash/issues/6354
⚠️ it seems like echarts or echarts react wrapper has a bug rendering "label lines" when changing configuration and happens when changing from "value label" between "Inside" and "Outside"
> fix: pie charts tooltip and label configuration

- packages/backend/package.json
- packages/backend/src/@types/knex-tables.d.ts
- packages/backend/src/database/entities/savedCharts.ts
- packages/backend/src/database/migrations/20230718093901_add_dashbord_uuid_to_chart_table.ts
- packages/backend/src/models/DashboardModel/DashboardModel.mock.ts
- packages/backend/src/models/DashboardModel/DashboardModel.ts
- packages/backend/src/models/ProjectModel/ProjectModel.ts
- packages/backend/src/models/SavedChartModel.ts
- packages/backend/src/services/ValidationService/ValidationService.mock.ts
- packages/common/src/types/savedCharts.ts
- packages/e2e/cypress/e2e/api/dashboard.cy.ts
Relates to: #6133 
Closes: #6227 
Changes:
- amend knex table typing
- update chart table to have a dashboard uuid column and space id column be nullable
Table before:
```
create table saved_queries
(
saved_query_id                    integer generated always as identity
primary key,
saved_query_uuid                  uuid         default uuid_generate_v4() not null
constraint saved_queries_saved_query_uuid_unique
unique,
created_at                        timestamp    default CURRENT_TIMESTAMP  not null,
name                              text                                    not null,
space_id                          integer                                 not null
constraint saved_queries_space_id_foreign
references spaces
on delete cascade,
description                       text, …
```
> feat: save chart in dashboard

- packages/frontend/src/components/DashboardFilter/FilterConfiguration/TileFilterConfiguration.tsx
> fix: titles not showing on filters panel

- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/ResourceViewGridChartItem.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/ResourceViewGridDashboardItem.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/ResourceViewGridSpaceItem.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/index.tsx
Closes: #6278 
Drag-and-drop enhancements:
- Add drag icon to corner of Resource Item that can be dragged. 
- Pass the drag handler props to the `DragIcon` instead
- Only show icon on hover
- Cursor should only be in _drag_ mode if the `DragIcon` is clicked
https://github.com/lightdash/lightdash/assets/7611706/33a7f6df-21ad-481a-8901-9ad054f72b83
Tooltip changes:
- only display tooltip on hover of the item `name`
- changed `Space`'s `Popover`->`Tooltip`, seems to be working fine!
https://github.com/lightdash/lightdash/assets/7611706/6a6ec937-cc2e-43f1-b613-8384369cdc02
NOTE: when viewing `All Spaces`, the drag and drop icon does not get displayed because draggability is disabled in that context.
> fix: address ux on pinned items drag-and-drop

- packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/index.tsx
Closes: #6417 
When viewing a chart, and when there's grouped series and we hide them all, the `Configure` button gets disabled. 
Reason for this is that the usage of `useEcharts` does not give enough granularity for this scenario: when `series` is a `[]` but `rows`/results data has length > 0.
Instead, use `useVisualisationProvider` like on other config panels to disable the button correctly. 
https://github.com/lightdash/lightdash/assets/7611706/93ba69ac-b8b1-4b24-b5bf-2d03facdcb46
> fix: check if configure is disabled with visualisation context

- packages/backend/src/models/DashboardModel/DashboardModel.ts
- packages/backend/src/services/DashboardService/DashboardService.test.ts
- packages/backend/src/services/DashboardService/DashboardService.ts
- packages/backend/src/services/services.ts
Closes: #6394 
https://github.com/lightdash/lightdash/assets/9117144/49895ef5-292b-4b59-a5af-769ec4a1d46f
> feat: delete orphan charts when updating dashboard

- packages/frontend/src/styles/blueprint-core.css
Closes: #6421 
Padding isn't applied to date picker caption on production bundles: 
locally: 
Add style with higher specificity to override the padding not being set.
> style: add padding to datepicker caption select

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/services/DashboardService/DashboardService.mock.ts
- packages/backend/src/services/DashboardService/DashboardService.test.ts
- packages/backend/src/services/DashboardService/DashboardService.ts
- packages/backend/src/services/SavedChartsService/SavedChartService.ts
- packages/common/src/types/dashboard.ts
Closes: #6388 
Requirements:
Chart created in dashboard:
Chart that belongs to dashboard updated:
Chart created in space ( doesn't have dashboard id ):
> chore: add chart in dashboard events

- package.json
- yarn.lock
Closes: N/A
Currently we use `npm-run-all` that hasn't been updated since 2018. 
Replaced it with `concurrently` and set colors and names for processes to easily see to which process the log belongs to. 
Since we have some scripts using `run-s` (https://github.com/mysticatea/npm-run-all/blob/master/docs/run-s.md), which basically runs a set of scripts sequentially, I added `npm-run-all2` to keep the current behaviour on those scripts (`concurrently` does not provide a command to run a set of scripts sequentially).
We could do the `dev` command with `npm-run-all2` as well but `concurrently` allows for better customisation/labelling of the processes that are being run so figured it would add more value to our devx. But happy to remove and just have 1 package for all instead!
Screen …
> chore: add `concurrently` to improve dev step and introduce `npm-run-all2`

- packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLine.tsx
Date picker popups in the chart config were causing the config popover to close. This sets the (blueprint-based) date pickers to open in portals and fixes them closing the popup. Here's a video of it working:
https://github.com/lightdash/lightdash/assets/1864179/6403c356-39f6-4b11-b0a7-86443447c28b
> fix: date pickers in chart config close popup

- packages/backend/src/models/DashboardModel/DashboardModel.ts
- packages/common/src/types/dashboard.ts
- packages/frontend/src/components/common/ResourceView/ResourceActionHandlers.tsx
- packages/frontend/src/components/common/modal/DashboardDeleteModal.tsx
- packages/frontend/src/pages/Dashboard.tsx
Closes: #6239 
Closes: #6495 
- out of scope bonus: migrated modal to Mantine
- modal added to dashboard too
no charts in dashboard
with charts in dashboard
> feat: delete dashboard modal updated

- packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
- packages/frontend/src/components/common/modal/DeleteChartTileThatBelongsToDashboardModal.tsx
Closes: #6241 
Changes for tiles where the chart belongs to dashboard:
> feat: update delete chart tile modal and options

- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes: #6493 
We were not applying most of the legend settings in to charts. This cleans up the merging of the legend config with the in-chart legend settings and now all of the setting should work.
> fix: legend settings not working

- packages/frontend/src/components/NavBar/HeadwayMenuItem.tsx
Closes: #5781
Change headway icon to 16px:16px
screenshot:
> style: change headway sparkles icon size to 16px

- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
Closes: #6336
`Tooltip`s from `blueprint` + `disabled` buttons don't work as expected. 
Instead, wrap the button with `mantine`'s `Tooltip` and wrap the button with a `Box` component so the `ref` is forwarded. 
https://github.com/lightdash/lightdash/assets/7611706/8a5ff7d7-9df3-4a29-9125-32e856f2adf6
> fix: correct hover tooltip ux when no changes to save in dashboard button

- packages/frontend/src/components/UserSettings/AppearancePanel/index.tsx
Closes: #6514
Disabled `Save changes` button if form isn't dirty
Add button to cancel changes if form is dirty. If clicked, reset to initial values
https://github.com/lightdash/lightdash/assets/7611706/6659290a-44f9-43a8-ba7c-7b36a4f74f93
> feat: add way to reset form state on appearance settings

- packages/frontend/src/components/DashboardTiles/TileBase/TileBase.styles.tsx
- packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
Closes: #3174 #5773
If Dashboard title `MARKDOWN` has an empty `title`(`''`), then remove the height reserved for the header, but still make sure that the 3-dot-vertical icon actions are styled and working correctly. 
https://github.com/lightdash/lightdash/assets/7611706/1c0a53c3-e4ff-4ad7-b4a5-82ee47352edd
> fix: check if markdown tile title is empty and reduce height

- docs/docs/references/metrics.mdx
link not recognised because `sql` has to be lowercase
> docs: fix lowercase broken link in metric docs

- packages/backend/src/queryBuilder.mock.ts
- packages/backend/src/queryBuilder.test.ts
- packages/backend/src/queryBuilder.ts
- packages/common/src/utils/filters.ts
- packages/e2e/cypress/e2e/dates.cy.ts
- packages/frontend/src/components/common/Filters/FieldAutoComplete.styles.tsx
- packages/frontend/src/components/common/Filters/FilterGroupForm.styles.tsx
- packages/frontend/src/components/common/Filters/FilterGroupForm.tsx
- packages/frontend/src/components/common/Filters/FilterRuleForm.tsx
- packages/frontend/src/components/common/Filters/index.tsx
Closes: #3700 
Functionality was already there, we just had to add the option in the UI.
Changes:
- allow for users to convert filter rules into a group ( only 1 level deep )
- refactor button components to Mantine
- small UI changes: lines, button position
note: not worth cleaning up too much the UI/code since we are going to do a complete revamp of the filters. 
https://github.com/lightdash/lightdash/assets/9117144/554d0310-f951-4bc6-8f97-8009f3884491
> feat: nested filters

- packages/common/src/utils/filters.ts
- packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilter.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterSettings.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/BooleanFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/UnitOfTimeAutoComplete.tsx
- packages/frontend/src/hooks/dashboard/useDashboardFiltersForExplore.ts
**changes in popover:**
---
**default is disabled:**
---
**changes in active dashboard filters:**
---
**changes in dashboard chart tile:**
> feat: dashboard filters default value

- packages/frontend/src/components/common/Filters/FilterInputs/BooleanFilterInputs.tsx
- packages/frontend/src/components/common/Filters/utils/getPlaceholderByFilterTypeAndOperator.ts
Closes: N/A
On dashboard: 
1. Edit
2. Add boolean filter (disabled/no default value) 
3. Save
4. Click on `disabled`/no-value filter
5. See `any` option
6. Click on `True` or `False`
7. See `Any` option disabled
Also checked on the chart filters and this option is disabled, so all good
https://github.com/lightdash/lightdash/assets/7611706/953f9570-8825-4253-a921-ba7d3189f58b
charts still ok: 
https://github.com/lightdash/lightdash/assets/7611706/f5b38042-f23a-4bc4-9cb3-e8c52717444b
> fix: add any option to boolean filter

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation.md
Unicode emojis do not get URL encoded properly when we try to create quicklinks to create GitHub issues.
> fix: use raw emojis in github template

- packages/backend/src/database/seeds/development/02_saved_queries.ts
- packages/backend/src/models/DashboardModel/DashboardModel.ts
- packages/backend/src/models/SavedChartModel.ts
- packages/backend/src/services/DashboardService/DashboardService.mock.ts
- packages/backend/src/services/DashboardService/DashboardService.test.ts
- packages/backend/src/services/DashboardService/DashboardService.ts
- packages/backend/src/services/SavedChartsService/SavedChartService.ts
- packages/common/src/types/dashboard.ts
- packages/common/src/types/savedCharts.ts
- packages/e2e/cypress/e2e/api/dashboard.cy.ts
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/common/modal/ChartCreateModal.tsx
Closes: [Create chart in dashboard before creating dashboard tile #6510](https://github.com/lightdash/lightdash/issues/6510)
We had to rollback changes from the initial implementation. 
Before: 
- we would send the chart data in the dashboard tile ( `newChartData` ) 
- the DashboardModel would create the chart and save the uuid in the new tile
- the DashboardService would figure out which charts were created and record a `saved_chart.created` event
Now:
- we create a chart with dashboardUuid ( this triggers the `saved_chart.created` event )
- we update the dashboard with the new chart uuid ( the same way we add other chart tiles )
Pros:
The newly created chart shows up while editing the dashboard.
Cons: 
We track `saved_chart.created` before it is saved in the dashboard. 
There is an edge …
> feat: create chart before updating dashboard

- docs/docs/get-started/setup-lightdash/get-project-lightdash-ready.mdx
- docs/docs/guides/cli/cli-authentication.mdx
- docs/docs/snippets/github-secrets.mdx
This confused some users with custom domains: https://lightdash.slack.com/archives/C05B9N87JPR/p1690997457011219?thread_ts=1690368212.693799&cid=C05B9N87JPR
> docs: remove hardcoded cloud urls

- packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/ChartConfigTabs.tsx
Closes: #6272 
Move the chart config tabs to mantine. Note that this required making the chart config a little wider than the others to keep the tabs from wrapping. I think it still looks fine. It covers more of the chart, but not by much. And we are planning on making that experience better anyway.
> feat: chart config tabs in mantine

- packages/frontend/src/components/common/ResourceView/ResourceActionHandlers.tsx
- packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx
- packages/frontend/src/components/common/ResourceView/index.tsx
A customer is seeing a silent failure when trying to move dashboards between spaces from the resource list. We can't repro it and can't seem to get enough data. This adds some temporary logging around this to gather more data. We will remove it when we have enough info. 
Many details in this thread:
https://lightdash.slack.com/archives/C02KDBTN9RV/p1690872099600449
> chore: debug logs for moving dashboards

- packages/backend/src/services/CsvService/CsvService.test.ts
- packages/backend/src/services/CsvService/CsvService.ts
Closes: #6502
Fixes a bug in `convertRowToCsv` that tried to convert `null` values with `moment()` leading to `Invalid Date` appearing in csvs.
Note this is a breaking change:
- Existing `null` strings returned `'∅'`
- Existing `undefined` strings returned `'-'`
- Now `null` and `undefined` both return `null` and `undefined` respectively
Nulls and undefined are handled by `csv-stringify` and print `,,`
> fix: write null dates to csvs

- packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilter.tsx
- packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterConfiguration.styled.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterSettings.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/utils/index.ts
- packages/frontend/src/components/DashboardFilter/FilterSearch/index.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
- packages/frontend/src/components/common/MonthAndYearInput.tsx
- packages/frontend/src/components/common/YearInput.tsx
Closes: https://github.com/lightdash/lightdash/issues/6478
reset to original value:
> feat: dashboard filters simplified view mode

- packages/frontend/src/components/VisualizationConfigs/BigNumberConfig/BigNumberConfigTabs.tsx
- packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/FieldLayoutOptions.tsx
- packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLine.tsx
- packages/frontend/src/components/VisualizationConfigs/PieChartConfig/PieChartLayoutConfig.tsx
- packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormatting.tsx
- packages/frontend/src/components/common/FieldSelect/FieldSelect.tsx
- packages/frontend/src/components/common/FieldSelect/FieldSelectItem.tsx
Moves the FieldSelect and FieldItem components from chart config to common. We are going to use the select in filters as well. Also updates its props.
> refactor: move field selector to common

- packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
Closes: N/A
Steps to reproduce bug: 
* Go to dashboard
* enable edit mode
* click on saved filter
* go to tiles tab
* click 'apply'
* save dashboard
* (now on view mode)
* click on same filter
* can only view tiles tab (not the correct view mode tab) 
When applying/saving a filter, reset tab to be the default - `FilterTabs.SETTINGS`. This fixes the issue. 
current bug
https://github.com/lightdash/lightdash/assets/7611706/de253354-1b59-4a44-b72b-2186255d7aa4
fixed with this pr:
https://github.com/lightdash/lightdash/assets/7611706/3ce3f477-85eb-4f90-b24b-a019e1bc3a02
> fix: set to default tab filter tab when saving

- packages/frontend/src/components/DashboardFilter/FilterConfiguration/TileFilterConfiguration.tsx
Closes half of #6072
left to do: ` Show the chart icon type next to the chart name `
Refactor current implementation in `TileFilterConfiguration`;
Use `useListState` from `mantine hooks` to control group of checkboxes: example https://mantine.dev/core/checkbox/#indeterminate-state
Ensure there's always a defined field when checking a checkbox 
**in View mode**
https://github.com/lightdash/lightdash/assets/7611706/0e408219-49b7-4db9-b001-a12dddb9e68d
**in Edit mode**
https://github.com/lightdash/lightdash/assets/7611706/e8e4b438-22f0-4bbb-ba76-4697de5f6af0
> feat: update dashboard filters tiles tab

- packages/frontend/src/components/DashboardTiles/TileBase/TileBase.styles.tsx
Closes: N/A
When viewing or editing a dashboard, it's hard to visually distinguish which state the user is in. 
Added a dashed border to the tiles when in edit mode. 
https://github.com/lightdash/lightdash/assets/7611706/b64af742-fb82-46b8-8b0d-1e550b3bf2de
> feat: add dashed border to tiles on edit mode

- packages/frontend/src/components/DashboardTiles/TileBase/TileBase.styles.tsx
Closes: N/A
make dashboard tile borders a bit lighter in view mode
before
after
> feat: make dashboard tiles borders lighter on view mode

- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
- packages/frontend/src/components/common/Page/PageHeader.tsx
Closes: N/A
Lighten `pageheader`'s shadow.
before: 
after:
> feat: lighten dashboard-header's shadow

- packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
Closes: #6702
Adds a tooltip explaining why the apply button is disabled. 
Note that the original bug here is mostly fixed elsewhere -- this is the final part, making it clear why you are in this state.
> fix: add a tooltip when apply button is disabled

- packages/frontend/src/components/NavBar/GlobalSearch/SearchIcon.tsx
- packages/frontend/src/components/SettingsValidator/ValidatorTable/index.tsx
- packages/frontend/src/components/common/ResourceIcon/index.tsx
Closes: N/A
When starting work on https://github.com/lightdash/lightdash/issues/6072, more specifically on adding the icon next to the checkbox, I realised that the `getChartIcon` util would apply default styles. 
With this in mind:
* `getChartIcon` returns only the Icon for each type
* `ChartIcon` component is a shared, styled `IconBox` with the correct Icon from `getChartIcon`, utilised in many places.
> refactor: create ChartIcon component

- packages/frontend/src/components/Explorer/ResultsCard/UrlMenuItems.tsx
When there is an error with a URL in the results table, the tooltip showing the error is covered (z-index issue). This moves it and updates the component to use mantine. Before and after below.
Before:
After fix:
> fix: error for broken urls in tables is covered up

- packages/backend/src/models/DashboardModel/DashboardModel.ts
- packages/common/src/types/dashboard.ts
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/TileFilterConfiguration.tsx
- packages/frontend/src/components/common/ResourceIcon/index.tsx
Closes: #6072
* Get last-version-chart kind 
* Update type
* Get correct icon
* Display next to checkbox
> feat: add chart icon next to tile target checkbox

- packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterSettings.tsx
Closes: #6709
hide disabled input when:
* filter is `any value` 
* filter operator is of type `null` and `not null`
https://github.com/lightdash/lightdash/assets/7611706/a6e564cf-94d5-4db0-90fb-57e7443b03d6
> feat: hide any value input when null/not null

- packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilter.tsx
Closes: #6719 
Change the filter close button color. I did this by just using the built-in mantine CloseButton
Before:
After:
> fix: filter close icon color

- packages/frontend/src/components/NavBar/HelpMenu.tsx
Closes: N/A
Hide intercom for non-cloud customers
For example, on local you can't see it:
> feat: only show intercom to cloud customers

- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
Closes: #6752
When editing a chart from a dashboard: 
* See `Save changes`
* See `Cancel changes` **only** when there are unsaved changes
* Add go-back (Icon arrow back) button that goes back only, displays a prompt if the user has unsaved changes, before going back to the og dashboard. 
* Display tooltip on hover of new go-back button
https://github.com/lightdash/lightdash/assets/7611706/5c30fc41-29c5-4438-b6c2-e4d7f57cd20d
> feat: improve chart from dashboard edit ux

- package.json
- packages/backend/src/scheduler/SchedulerWorker.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/common/src/types/scheduler.ts
- yarn.lock
Closes: N/A
When running tasks on the scheduler, if there is an `organizationUuid`, pass it and set it as a span attribute.
This increases our traceability when looking at grafana logs
NOTE: upgraded `TypeScript` because narrowing down of types on an `unknown` object wasn't working on the type checker. This was fixed after 4.9  ref: https://www.reddit.com/r/typescript/comments/yv9tnk/narrowing_unknown_in_type_guard/iwew6ru/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
> feat: add organization_id attribute to schedule worker task

- packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
> fix: dashboard filters should not show reset in edit mode

- packages/frontend/src/components/DashboardTiles/AddTileButton.tsx
- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
Closes: N/A
Found this while working on #6798;
Disabled `add tile` button when dashboard is saving
Add loading state when dashboard is saving 
https://github.com/lightdash/lightdash/assets/7611706/5deb0d0e-abab-4f8a-b520-0d99e72ff01f
> fix: improve saving state on dashboards

- packages/frontend/src/components/common/Filters/FieldAutoComplete.tsx
- packages/frontend/src/components/common/Filters/renderFilterList.tsx
Relates to #6798 
Users have reported that when they click to find a field to filter a dashboard by, it takes more than 1s to get the list of grouped fields. 
This is because of an expensive method to group items by their table to then provide a better experience to our users. 
This PR covers the following: 
* converting tables.find((t) => t.name === item.table to a JS `Map` which ensures lookup is O(n), instead of O(n^2)
* memoization of `groupedItems` with React's own `useMemo` and `useCallback`
* Creation of `useGroupedItems` hook - only specific to this component, so it stays on same file
Screen-recording: 
https://github.com/lightdash/lightdash/assets/7611706/b9a634a6-40d0-4cfd-90bb-fc7e75e35423
> feat: improve render filter list performance

- packages/frontend/src/components/common/ResourceIcon/index.tsx
Closes: N/A
remove extra quotes when transform-rotating `bar chart` icon for horizontal bar charts
screenshot
> fix: remove extra quotes on rotate transform

- packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterSettings.tsx
Closes: #6761 
Move the default value switch below the filters. And change copy.
> fix: move dashboard filter default value switch

- packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx
Closes: #6781 
As part of this PR, have made the dashboard list searchable when adding a chart to a dashboard.
Have attached video for reference. 
Please let me know in case of any feedback.
https://github.com/lightdash/lightdash/assets/20976813/dc8f072d-4d02-4913-8652-9993a91af3c3
> feat: add searchable dashboard list when adding chart to dashboard

- .github/workflows/cli-tests.yml
- .github/workflows/e2e-tests.yml
Github action `AsasInnab/regex-action@v1` is no longer maintained and will soon stop working. 
The deployment url is already available in the github event so we don't need a regex.
> chore: remove deprecated github action

- .github/workflows/e2e-tests.yml
Current github warning
Latest version of the github action uses node16
> chore: update create-json github action

- packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
- packages/frontend/src/components/DashboardFilter/Filter.tsx
- packages/frontend/src/components/DashboardFilter/index.tsx
- packages/frontend/src/providers/DashboardProvider.tsx
Closes: #6681
Add loading state to the following: 
* `Add filter` button - should be in `loading` state if dashboard filters are loading
* Add `Skeleton`s to Dashboard filter pills list whilst dashboard filters are loading
Other improvements:
* Do not show anything related to Dashboard Filters if there are no chart tiles in dashboard (added `hasChartTiles` to DashboardContext)
https://github.com/lightdash/lightdash/assets/7611706/49453016-72c9-4419-9b38-f683669f4be0
> fix: loading state for dashboard filters

- packages/frontend/src/pages/Dashboard.tsx
Closes: N/A
Remove footer from Dashboard page.
`Home` is the only page with Footer.
> feat: remove footer from Dashboard page

- packages/common/src/utils/formatting.test.ts
- packages/common/src/utils/formatting.ts
Closes: #6101
Users were confused that boolean values in results were formatted as Yes/No. This changes booleans in tables and filters to be 'True' or 'False'. 
Before:
After:
> fix: format boolean values as true/false

- docs/docs/references/user-attributes.mdx
Fixes the attribute definition in the docs (adding a space before `lightdash` causes an error at query time)
> docs: removes spaces in front of attribute definition

- packages/frontend/src/components/common/modal/DashboardCreateModal.tsx
Closes: #6870 
The cancel button on the create dashboard dialog was a no-op. Fixed callback.
> fix: create dashboard cancel button doesnt work

- packages/e2e/cypress/e2e/dashboard.cy.ts
- packages/frontend/src/components/DashboardTiles/AddTileButton.tsx
We are having a lot of issues with create chart in dashboard. This hides the feature behind a feature flag for now. We will remove this when it's ready. 
To enable the feature in the mean time:
`localStorage.setItem('enable-create-chart-in-dashboard', true)`
> fix: hide create chart in dashboard

- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/common/src/types/field.ts
- packages/common/src/types/metricQuery.ts
- packages/frontend/src/components/Explorer/CustomMetricModal/index.tsx
- packages/frontend/src/components/Explorer/CustomMetricModal/utils/index.ts
Closes: #6773 
Custom metric for percentile didn't have anywhere to choose the percentile. This adds an input box to choose what you want the percentile to be and plumbs that through. 
I hadn't interacted with these things much -- if anyone sees something I didn't think of or should have done differently, I'm very open to changing this.
> fix: add an input for percentile in metrics

- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
Closes: N/A
Move details underneath dashboard title to popover;
https://github.com/lightdash/lightdash/assets/7611706/4e1d3684-c22d-42f9-9971-cd7bc31d6720
Next, I'll reduce the vertical padding in that container.
> feat: move dashboard details to popover

- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
- packages/frontend/src/components/common/Page/PageHeader.tsx
Closes: N/A
decrease dashboard header height by passing `h` `auto` to page header
before:
after
> style: decrease dashboard header height

- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
Closes: N/A
add a `Pencil icon` on the left of the dashboard popover last-updated section that doesn't make sense 
this is without:
> chore: remove small dashboard header icon

- packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
- packages/frontend/src/components/DashboardFilter/Filter.tsx
- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
- packages/frontend/src/hooks/dashboard/useDashboardRefresh.tsx
- packages/frontend/src/hooks/dashboard/useSavedQueryWithDashboardFilters.ts
- packages/frontend/src/providers/DashboardProvider.tsx
Closes: #6796 
Add Refresh button to trigger the invalidation of the following queries: 
```
{ queryKey: ['queryResults'] },
{ queryKey: ['saved_query'] },
{ queryKey: ['saved_dashboard_query', dashboardUuid] },
{ queryKey: ['dashboards', 'availableFilters'] },
```
A Chart tile is also considered to be in loading state when data is being fetched;
Invalidate filters as well so this depending data refreshes as well;
https://github.com/lightdash/lightdash/assets/7611706/b6f8ba6d-806f-4253-8d09-11ee1c4ffbbe
> feat: add refresh button to dashboard

- packages/frontend/src/components/DashboardTiles/AddTileButton.tsx
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/hooks/dashboard/useDashboardStorage.tsx
Closes: #6853 
NOTE to reviewers: There are a number of issues with charts in dashboards and I am starting with a targeted fix for this one. Things won't work perfectly with just this review but they will be better. This introduces a hook for managing these temp charts which will have more functionality with in next few reviews. 
Editing a chart in a dashboard was causing the chart to be lost. This was happening when the dashboard hadn't been saved yet. The draft state of the dashboard wasn't getting passed back to the edit experience. 
In this review I created a hook for storing the dashboard between pages and reused that hook where necessary. In the next few reviews I plan to move more of the interaction with session storage into the hook. 
Also note if you want to test it out, there is …
> fix: editing an in-dashboard chart loses the chart

- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
- packages/frontend/src/hooks/dashboard/useDashboardRefresh.tsx
Closes: #6905 
There was an issue with the refresh button setup where it was calling `useQueries` on the default client with existing query strings and no query functions, essentially creating a new cache for those functions. There was a race condition that caused the page to break with an unknown error when one of those was called.
This changes the pattern to just invalidate those queries in the existing client. 
This also changes the `queryResults` key to `savedChartResults`. `queryResults` doesn't exist. 
One caveat here is that the loading state on the button will now show whenever something is getting fetched on the page, not just from the refresh button. We could potentially pare that down, but I didn't figure out how to scope `isFetching` to just these queries. It will take a …
> fix: dashboard crash on refresh

- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
- packages/frontend/src/components/common/MonthAndYearInput.tsx
Closes: https://github.com/lightdash/lightdash/issues/6902
I was able to reproduce this with selecting timezone that is ahead of local timezone
my locale: gmt+4:00
overriden: gmt+5:30
> fix: filter input year and year month timezone issue

- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulerForm.tsx
Closes: #6893 
In add schedule delivery modal, it was not possible to click on the hyperlinks in the tooltip. Have added hoverDelay of 500ms so the tooltip stays there for some time and we are able to click on the hyperlinks. Have also made it so the links open in a new tab which felt a better UX to me. Please let me know in case of feedback. Have attached video for reference.
https://github.com/lightdash/lightdash/assets/20976813/ba7141ef-e7bf-44de-ac7b-e5d76d671646
> fix: tooltip hover effect on add email and add slack

- packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx
Keep the add chart dialog open on click outside. 
The dashboard add charts dialog is currently set to close on click outside. But the dropdown to choose charts stays open even after you select one, covering the 'Add' button. The result is a kind of frustrating experience where you have to pick a chart, then be careful to click on a small exposed part of the dialog to close the dropdown so you can click Add. If you click outside the dialog, it closes without adding your selected charts. 
This just keeps the dialog open on click outside, giving the user more space to click the dropdown closed and also making them make an explicit choice whether to add or cancel.
> fix: keep add charts dialog open on click outside

- docs/docs/guides/how-to-create-scheduled-deliveries.mdx
Most content will be used in separate section
Relates to: #6945 & #6946
> docs: remove google sheets related info from scheduled deliveries

- packages/frontend/src/components/NavBar/BrowseMenu.tsx
- packages/frontend/src/components/NavBar/ExploreMenu.tsx
Closes: #6952 
As part of this PR, have fixed the size of icons on navbar to 16x16 in new and browse tab. Attached video for reference.
https://github.com/lightdash/lightdash/assets/20976813/2aaed9e6-cce6-4d3e-8481-7277d90dfb87
> fix: size of icons in new and browse tab in navbar to 16x16

- docs/docs/references/metrics.mdx
Include information about max metrics only working with `numeric` types
> docs: update max metrics

- packages/frontend/src/components/Explorer/ExplorerHeader/index.tsx
- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
- packages/frontend/src/components/NavBar/index.tsx
- packages/frontend/src/hooks/dashboard/useDashboardStorage.tsx
- packages/frontend/src/pages/Dashboard.tsx
- packages/frontend/src/pages/Explorer.tsx
Closes: #6865 
Going back to a dashboard from editing a chart in that dashboard was breaking the header. The special header for editing charts would stay around forever. This change moves more of the interaction with sessionStorage into a hook, then uses that hook to read and clear storage items used for the header. The clear now happens in a useEffect on the dashboard page instead of before the re-direct. 
There is more to be done as far as moving things into the hook, but this fixes the header problem.
> fix: header breaks returning from chart edit

- packages/frontend/src/api/MetricFlowAPI.ts
Closes: 
Context: the dimension 'metric_time' is special and is available to all metrics.
Problem:
Dbt API throws an error when we filter metrics with the dimension `metric_time`. 
I'm introducing a workaround in the API request by excluding that dimension from the filters.
> fix: dbt error workaround for metric_time dimension

- packages/frontend/src/hooks/pivotTable/pivotQueryResults.ts
Closes: https://github.com/lightdash/lightdash/issues/6813
⚠️ ⚠️ ⚠️ holding release till monday!
see headway update: https://changelog.lightdash.com/breaking-change-pivot-tables-with-60-columns-will-no-longer-be-supported-273072
re-introduces column limit to the pivot table
> feat: pivot table max column size

- packages/frontend/src/features/metricFlow/utils/convertMetricFlowFieldsToExplore.ts
Closes: #6971 
**Problem:**
If we group by a time dimension without specifying a grain we expected the results columns to match but that's not the case.
eg: for the following query
```
mutation {
createQuery(
environmentId: "204496"
metrics: [{ name: "revenue"}]
groupBy: [{ name: "order_id__ordered_at"}]
) {
queryId
}
}
```
I expect the columns:  ‘revenue’ and ‘order_id__ordered_at’  but we get:  ‘revenue’ and ‘order_id__ordered_at__day’ ( note the grain suffix )
This causes problems because there is a mismatch between the dimension name (aka ID ) the user selected and what was returned.
We had to implement a workaround by renaming all the time dimensions we receive from dbt.
`isTimeDimension ? `${name}__day` : name`
This works well because the API accepts the name with the grain suffix. …
> fix: add default suffix to metricflow time dimensions

- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes: #6588
[Screencast from 04-09-23 11:44:39.webm](https://github.com/lightdash/lightdash/assets/1983672/cd0dfd2f-4a63-4763-b631-e37511e1cdc1)
What was happening: 
Before we were simply checking the `group/pivot` of the series (eg: shipped, completed) but when you have multiple sries, the pivot appears multiple times. so that didn't work. 
Now I'm checking the  full serie display name against the selected legend
> fix: fix total legend with multiple series

- packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx
Closes: https://github.com/lightdash/lightdash/issues/6876
> fix: admins should see all spaces when moving items

- packages/frontend/src/components/common/Table/TableProvider.tsx
- packages/frontend/src/components/common/Table/types.ts
- packages/frontend/src/hooks/tableVisualization/getDataAndColumns.tsx
- packages/frontend/src/types/table-core.d.ts
Closes: #7009
We currently filter out hidden columns from `getDataAndColumns` util. The result of this util is then utilised in `TableProvider`. 
However, some cells might require information about other columns, regardless of their visibility. 
(read bug 7009)
This ensures all columns are provided, but then looped through to set if visible or not on `TableProvider` using `setColumnVisibility`
on explorer
https://github.com/lightdash/lightdash/assets/7611706/6019389b-0533-470b-b815-4d7ad4088fc7
on dashboards
https://github.com/lightdash/lightdash/assets/7611706/ddcd7b7b-364e-4890-82f0-7cefdaf4b348
> fix: avoid filtering out hidden columns and set visibility on table provider

- packages/frontend/src/components/common/Filters/FilterInputs/AutoComplete/MultiAutoComplete.tsx
Closes: #7022
Currently, users: 
* add filter to a dashboard of type string
* add operator that will trigger the MultiAutoComplete (for example `includes`)
* add value
* remove that value
* add another one. If that click happened outside of the popover, it would close the whole popover.
This was because of the `popoverProps` being spread.
Now, we only pass the necessary ones: 
`onClosing` and `onOpening`
> fix: only pass onOpening and onClosing props to MultiAutoComplete

- packages/backend/src/models/ProjectModel/ProjectModel.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
Closes: #7007 
Note: There is an edge case where we return the wrong explore because join table aliases are not unique
eg:
```
- name: payments
meta:
joins:
- join: users
alias: users_alias
sql_on: ${users.user_id} = ${payments.order_id}
- name: orders
meta:
joins:
- join: customer
alias: users_alias
sql_on: ${users_alias.customer_id} = ${payments.order_id}
```
In this case, autocomplete for the field `users_alias.name` will always get results from table `users` and never from `customers`.
Preview autocomplete working with joined tables with alias:
```
- name: payments
meta:
joins:
- join: orders
sql_on: ${orders.order_id} = ${payments.order_id}
- join: customers
alias: customers_payments_limited
sql_on: ${customers_payments_limited.customer_id} = ${orders.customer_id}
fields: …
```
> fix: autocomplete for joined tables with alias

- docs/docs/references/joins.md
> docs: join table type docs

- packages/backend/package.json
- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/clients/EmailClient/EmailClient.ts
- packages/backend/src/clients/Slack/Slackbot.ts
- packages/backend/src/scheduler/SchedulerTask.ts
- packages/backend/src/services/UnfurlService/UnfurlService.ts
- packages/common/src/types/scheduler.ts
- yarn.lock
Closes: partially closes 6678 (Requires frontend)
Sample pdf 
[scale-to-fit.pdf](https://github.com/lightdash/lightdash/files/12524497/scale-to-fit.pdf)
> feat: send pdf attachemnt with image

- packages/backend/src/services/CsvService/CsvService.test.ts
- packages/backend/src/services/CsvService/CsvService.ts
Closes: #4758
Exporting `Which customers have not recently ordered an item?` chart : 
> csv-which_customers_have_not_recently_ordered_an_item_-2023-09-06-11-36-24-6970.csv
Exporting `payments` unsaved chart or results:
> csv-payments-2023-09-06-11-36-24-6970.csv
> feat: rename CSV files

- packages/frontend/src/components/common/ResourceInfoPopup/DashboardList.tsx
Closes: #6735 
There is a slight lag when we hover on the information icon in dashboard list item (specially if we have a very slow network). Have added a loader on this so the user don't get confused.
Attaching video for reference.
https://github.com/lightdash/lightdash/assets/20976813/77341cb0-6893-40f9-b506-9a21fc414dc6
> fix: add loader on hover of information icon on chart list item

- packages/frontend/src/components/common/ResourceInfoPopup/DashboardList.tsx
Closes: [#7023](https://github.com/lightdash/lightdash/issues/7023)
The dashboard link was bubbling out the click event to the chart link, which was making the chart open in the same tab. 
I added a stop propagation to the event, so that the dashboard link opens up in a new tab
[Screencast from 2023-09-07 01-47-11.webm](https://github.com/lightdash/lightdash/assets/37402791/5b8a4745-8ef5-476e-bb3b-86625164bc0e)
> fix: opening dashboard links in popup in a new tab

- packages/e2e/cypress/e2e/settings/invites.cy.ts
- packages/frontend/src/components/ProjectAccess/ProjectAccess.tsx
- packages/frontend/src/components/UserSettings/AccessTokensPanel/TokensTable.tsx
- packages/frontend/src/components/UserSettings/ProjectManagementPanel/index.tsx
- packages/frontend/src/components/UserSettings/SlackSettingsPanel/index.tsx
- packages/frontend/src/components/UserSettings/UserManagementPanel/index.tsx
Closes: #6515 
This PR makes the delete icon consistent across the tabs specified in the issue. Attached screenshot for the same. Have also made couple of additional fixes not part of the original issue.
- There seemed to be a typo in the Revoke project access modal. The word 'for' seemed to be missing. Have added that. 
- In the same file, to add the trash icon I used the mantine button. There were already button being used from blueprint. So migrated the buttons to mantine. This broke the UI of the modal using these buttons, so migrated it to mantine as well. (I saw in some issues that there was a plan to migrate to mantine so made this change. Apologies if this is not needed).
Attaching screenshots:
User management panel:
All projects panel:
Slack Integration:
Personal access token: …
> fix: make delete action consistent on settings page

- packages/backend/src/queryBuilder.test.ts
- packages/backend/src/queryBuilder.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/backend/src/services/SearchService/SearchService.ts
- packages/backend/src/services/UserAttributesService/UserAttributeUtil.test.ts
- packages/backend/src/services/UserAttributesService/UserAttributeUtils.ts
Closes: #7049
Motivation: 
when checking user attributes, we filter from db user attributes by `userUuid` which means attributes we were passing to the `hasUserAttribute` only contain the user.
But this is confusing, not very untuitive, and could cause bugs in the future. So I refactored to also check the uuid on the `hasUserAttribute` method. 
This means we'll have to cascade the userUuid in some methods like `buidlQuery`
> chore: refactor auser attribute method

- packages/cli/src/handlers/preview.ts
First, GitHub changed the manner to set output in GitHub Actions. So, we have to follow the current one.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Second, it would be good to give another way to get the project UUID deployed by the Lightdash CLI, because GitHub Actions might disallow us to put files in `${HOME}/.config/lightdash`. I haven't identified the root cause of failures on GitHub Actions to validate a preview project which was launched just before executing a `lightdash validate` command. The preview project was created. However, a `lightdash validate` command sequencially executed just after the creation was failed due to the lack of informatio of a project UUID.
```
- id: validate-lightdash-project
name: "Validate …
```
> fix: the deprecated GitHub Actions' outputs manner

- packages/cli/src/handlers/compile.ts
I have an issue to compile a dbt project with the Lightdash CLI. I am still investigating the root cause. But, I would like to make sure the CLI uses the passed dbt profile and target by showing the logs.
> feat: Show the dbt profile and target when compiling with the CLI

- packages/common/src/compiler/filtersCompiler.ts
Closes: #7064 
When using string filters and not having any value in the criteria, the query generated used to have a where clause (false) as mentioned in the referenced issue. Have changed it to have a where clause as (true) so it does not impact rest of the query. Have made similar change for number type filters as the issue was also persistent in that case as well (not mentioned on the original issue). Please let me know in case this was not needed.
Attached video for reference.
https://github.com/lightdash/lightdash/assets/20976813/497ef34e-4275-416e-8f1d-1d54263a29f5
> fix: query generation with empty value on string and number filters

- packages/backend/src/services/UnfurlService/UnfurlService.ts
Closes: #7041
While debugging
Now: 
To complete the rest of the acceptance criteria we'll have to release and test these metrics first.
> chore: add metrics to screenshot method

- packages/common/src/utils/scheduler.test.ts
- packages/common/src/utils/scheduler.ts
- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulersListItem.tsx
Closes: #6848
Acceptance criteria:
Before:
Now:
Before:
Now: 
Before: 
Now:
Before:
Now:
Does not apply
> fix: add utc to cron expressions

- packages/frontend/src/components/LightdashVisualization/index.tsx
- packages/frontend/src/components/SimpleChart/index.tsx
- packages/frontend/src/components/SimplePieChart/index.tsx
- packages/frontend/src/hooks/echarts/useEcharts.ts
- packages/frontend/src/hooks/echarts/useEchartsPieChart.ts
Closes: #7093 
Disable `animation` for echarts in dashboards.
https://github.com/lightdash/lightdash/assets/7611706/4269c893-9161-4ed3-9da4-19edb3f8dd92
Screen recording with pie chart:
https://github.com/lightdash/lightdash/assets/7611706/8feda3c7-c75d-4bdf-a56e-40b40d23a9f2
Screen recording for minimal:
https://github.com/lightdash/lightdash/assets/7611706/acd40b2b-2e56-4f9f-8377-9050fd27907a
Screen recording of individual chart animation still working:
https://github.com/lightdash/lightdash/assets/7611706/acbe1ab9-fe80-4f95-96d1-bee1f9dd8b25
NOTE: animation still works when viewing individual charts
> chore: disable echarts animation if on a dashboard

- docs/docs/references/metrics.mdx
Updates filters docs to include double quotes around the examples (otherwise, some of hte examples actually fail on compile e.g. `user_name: %katie%` needs double quotes)
> docs: update metrics.mdx filters

- packages/frontend/src/pages/Dashboard.tsx
Closes: #7124 
Changed history.push() to history.replace() to avoid going back to edit mode
[Screencast from 2023-09-19 23-16-40.webm](https://github.com/lightdash/lightdash/assets/37402791/8ed16591-25ca-453c-aec0-4812834b3e71)
> fix: should not go to editing a dashboard after saving or cancelling

- .github/workflows/cli-tests.yml
Github action that runs CLI tests is failing with following error:
```
Running:  cli.cy.ts                                                                       (1 of 1)
read ECONNRESET
Error: read ECONNRESET
at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
Test run failed, code 1
More information might be available above
Cypress module has returned the following error message:
Could not find Cypress test run results
Error: Could not find Cypress test run results
```
Error seems related to chrome so I'm removing that config since it shouldn't matter for CLI tests.
> chore: runs tests in default browser

- docs/docs/references/sql-variables.mdx
- docs/docs/references/user-attributes.mdx
The attribute is not properly interpreted when calling it with a space before the `}`. Fixing the user attribute references in the docs
> chore(docs): fix typo in user attributes

- packages/frontend/src/components/RefreshButton.tsx
- packages/frontend/src/providers/ExplorerProvider.tsx
Closes:  #7161 
As per the issue description, we have to keep the run query button enabled in explore view even when underlying metrics/dimensions have not been modified. Have made the suggested change.
> feat: Keep run query enabled in explore even when underlying metrics/dimensions have not been modified

- packages/backend/src/services/ProjectService/ProjectService.ts
Closes: #7106 
Adds 2 Sentry Transactions: 
`getResultsForChartWithWarehouseQuery`: The total time for a saved chart result
`runWarehouseQuery`: The total time for a warehouse query
This would benefit observability, specially when encapsulating multiple warehouse requests at a time into one Sentry transaction so it's easier to calculate how much time between Lightdash DB and Warehouse client operations
> chore: add sentry logging for getting chart results and warehouse query

- packages/backend/src/generated/swagger.json
- packages/backend/src/models/SavedChartModel.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
Relates to: #7058 
`availableFilters` was getting the whole chart from the chart model when all info that is necessary is:
```
uuid: string;
name: string;
spaceUuid: string;
tableName: string;
projectUuid: string;
```
Sentry `/availableFilters` duration:  https://lightdash.sentry.io/performance/summary/spans/projectService.getAvailableFiltersForSavedQuery:ca6069760127bd19/?project=5959292&statsPeriod=30d&transaction=POST+%2Fapi%2Fv1%2Fdashboards%2FavailableFilters
> chore: reduce query to get available filters

- packages/backend/package.json
- packages/backend/src/index.ts
- packages/frontend/package.json
- packages/frontend/vite.config.ts
- yarn.lock
Closes: #7097 
Gzips `js` and `css` assets and serves them if they exist.
Utilises `vite-plugin-compression2` a package that is currently being maintained: https://github.com/nonzzz/vite-plugin-compression
Uses `express-static-gzip` to serve pre-compressed files
When this gets merged, we should test if it works on our instance first. It works locally (by running the BE + a FE build) and also in Render, but had to clear the cache on Render for it to work.
> chore: compress vite assets and serve them if they exist

- packages/backend/src/models/SavedChartModel.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
Closes: #7163 
Query all charts in batches so we can get the necessary information to get the available filters per chart.
With this: 
https://lightdash-pr-7186.onrender.com/projects/3675b69e-8324-4110-bdca-059031aa8da3/dashboards/43cfa66c-f99b-4d1c-82c6-5d03b6f332e7/view?filters=%7B%22dimensions%22%3A%5B%7B%22id%22%3A%22e7df7c5a-1070-439a-8300-125fe5f9b1af%22%2C%22target%22%3A%7B%22fieldId%22%3A%22orders_is_completed%22%2C%22tableName%22%3A%22orders%22%7D%2C%22values%22%3A%5Btrue%5D%2C%22operator%22%3A%22equals%22%7D%2C%7B%22id%22%3A%226d28a3a5-c01f-46d8-9f6b-74a9ab1efd99%22%2C%22target%22%3A%7B%22fieldId%22%3A%22orders_order_date_year%22%2C%22tableName%22%3A%22orders%22%7D%2C%22values%22%3A%5B5%5D%2C%22operator%22%3A%22inThePast%22%2C%22settings%22%3A%7B%22completed%22%3Atrue%2C%22unitOf …
> chore: batch-query charts to then get available filters

- packages/frontend/src/components/LimitButton/LimitForm.tsx
Closes: #7199 
The 'total rows' input had buttons that made it easy to put it in a negative state, causing a validation error. This makes the min value for the input 1.
> fix: dont allow row limit to go below 1

- packages/backend/package.json
- packages/backend/src/index.ts
- packages/frontend/package.json
- packages/frontend/vite.config.ts
- yarn.lock
Closes: #7097
After work done on: https://github.com/lightdash/lightdash/pull/7200, I've noticed that some assets were randomly not being served with the gzipped file generated with vite compression plugin. 
This is because some of these asset response headers were missing 2 headers:
```
- `Vary: Accept-Encoding`
- `Content-Encoding: gzip`
```
For example: 
in here ^ only the first asset is served gzipped, and the others aren't, even though these are available. 
This could be related to: https://github.com/tkoenig89/express-static-gzip/issues/22 where there are multiple assets being requested at once. 
Since this could be a config issue (with google cloud CDN), I would like to test one thing instead: compressing the assets with the `express`'s `compression` middleware. 
**NOTE**
THis …
> fix: compress in express server instead

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
Viewers and Interactive viewers were seeing the 'Move to space' button on charts in dashboards. It errored out when they tried, but this makes it so they won't see the button.
> fix: disable move-to-space option for viewers

- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/VisualizationConfigs/PieChartConfig/PieChartDisplayConfig.tsx
- packages/frontend/src/hooks/echarts/useEchartsPieChart.ts
- packages/frontend/src/hooks/usePieChartConfig.ts
Closes: #7091 
Implemented a new feature allowing users to toggle between horizontal and vertical legend positions in pie chart configurations. Additionally, introduced input fields to enable precise customization of legend positions within the charts.
> feat: vertical legend option for pie charts

- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
- packages/frontend/src/pages/Dashboard.tsx
Closes: #7196
Allows interactive viewers to export dashboards. As well as see the refresh and link buttons. 
Note: we don't have a super-clear way of describing in code the difference between and interactive viewer and a viewer. I'm using whether or not they can export csv as a proxy for being an interactive viewer. Tested with viewer, interactive viewer, and editor permissions.
> fix: allow interactive viewers to export dashboard

- .github/workflows/cli-tests.yml
- .github/workflows/e2e-tests.yml
For some reason there is a test that never ends and cypress doesn't kill it. Adding a timeout to the github action job.
test-frontend
> chore: timeout e2e tests

- packages/e2e/cypress/e2e/app/dashboard.cy.ts
Closes: N/A
Adds e2e test coverage for dashboards when the user:
* Adds a saved chart
* Creates charts within dashboards
* Adds a filter
* Customises the tile targets
* Adds a field from another explore in the tile target
> test: add more coverage to dashboard test on filters

- packages/backend/src/index.ts
- packages/frontend/vite.config.ts
Closes: #7097 
* gzip js, jsmap and css files
* look for these .gzip files
THis has already been tested in an alpha release, these should be the only changes required to serve all gzipped assets. 
No changes have been made to the disabling of CDN caching - only the browser can cache these assets
summary on cache + revalidation + origin server + google cloud cdn + browser caching and **with** these changes:
for example: `blueprint-vendor-xxx.js` has a `cache-control` response header of `public, max-age=0` - the  CDN sees this, holds the asset, but will revalidate it with the origin server every time it's requested because of the `max-age=0`
Since the request header also has `Cache-control: no-cache` the CDN will respect this directive and fetch a fresh copy from the origin server
Besides …
> chore: enable js jsmap and css to be gzipped

- packages/frontend/package.json
- yarn.lock
Closes: N/A
Vite wasn't transpiling `static` class methods correctly
fixed here: https://github.com/vitejs/vite/commit/4ca7c13
> chore: upgrade vite to 4.4.9

- packages/backend/src/models/UserAttributesModel.ts
- packages/backend/src/queryBuilder.test.ts
- packages/backend/src/queryBuilder.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/backend/src/services/SearchService/SearchService.ts
- packages/backend/src/services/UserAttributesService/UserAttributeUtil.test.ts
- packages/backend/src/services/UserAttributesService/UserAttributeUtils.ts
Closes: #7227 
**Wrong sql filters**
The following code intended to fetch values for specific user uuids and for attributes with default values.
```javascript
// packages/backend/src/models/UserAttributesModel.ts
if (filters.userUuid) {
query
.where(`users.user_uuid`, filters.userUuid)
.orWhereNotNull(`attribute_default`); 
}
```
The problem is that it is a `OR` condition so it was returning values for all users where the attribute had a default value.
**Assumptions** 
The logic that builds the query assumed the user attributes argument only had information for 1 user.
```
const userValue =
userAttribute.users.length > 0
? userAttribute.users[0].value
: userAttribute.attributeDefault;
```
The problem is that argument had more users values ( see first problem above ).
- New method to fetch …
> fix: user attribute default value

- packages/e2e/cypress/e2e/app/dashboard.cy.ts
- packages/frontend/src/Routes.tsx
- packages/frontend/src/components/NavBar/ExploreMenu.tsx
Closes: #7116 
The problem was:
- When creating a new dashboard from an existing dashboard, the page never remounted, leaving all of the state from the  dashboard context.
This fix:
- Forces a re-mount of the dashboard by keying the page to the dashboard uuid. This clears the filters, but is also probably the right thing to do for other state.
> fix: clear filters when creating new dashboard

- packages/backend/src/services/CsvService/CsvService.ts
- packages/common/src/utils/filters.ts
- packages/frontend/src/hooks/dashboard/useDashboardFiltersForExplore.ts
Closes: #7068 
OG chart:
dashboard with chart + dashboard filter:
old buggy csv:
new fixed csv:
> fix: csv export dashboard filters

- packages/common/src/utils/formatting.ts
Closes: #6852 
Note that this formatting is applied at the cell level. 
We are not inferring the table calculation overall type as each value can be different. The app still assumes table calculation is of type `number`.
> fix: format table calculation dates

- docs/docs/guides/cli/cli-authentication.mdx
Fixes a typo in the documentation when running Lightdash behind an authenticating proxy (https://docs.lightdash.com/guides/cli/cli-authentication/, option 3).
The variable used in [packages/cli/src/handlers/login.ts](https://github.com/lightdash/lightdash/blob/main/packages/cli/src/handlers/login.ts#L126) is `LIGHTDASH_PROXY_AUTHORIZATION`.
> docs: fix typo in CLI authentication behind proxy

- packages/backend/src/models/SlackAuthenticationModel.ts
- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulerForm.tsx
Closes: #7050  
It was wrongly marking everything as a private channel.
Preview fix:
> fix: slack channel label

- packages/e2e/cypress/e2e/app/dashboard.cy.ts
- packages/frontend/src/providers/DashboardProvider.tsx
Closes: #6564 
Don't put saved filters in the dashboard URL. Temp filters still get stored there. 
I'm going to follow this up with a bit of a cleanup of the context file.
> feat: 6564 dashboard links should more generically include saved filters and this should be dynamic

- packages/common/src/types/pivot.ts
- packages/frontend/src/components/Explorer/ResultsCard/ResultsCard.tsx
- packages/frontend/src/components/SimpleTable/index.tsx
- packages/frontend/src/components/common/Table/TablePagination/index.tsx
- packages/frontend/src/hooks/pivotTable/pivotQueryResults.test.ts
- packages/frontend/src/hooks/pivotTable/pivotQueryResults.ts
Closes: #7149 
Check if `show number of results` is set on the config for a pivot table and display its results
With it turned on
With it turned off
> fix: show pivot table results

- packages/frontend/src/pages/Dashboard.tsx
- packages/frontend/src/pages/MinimalDashboard.tsx
this PR work is related to: https://github.com/lightdash/lightdash/issues/6932
As it's been impossible for me to reproduce this issue, I am not going to close the original ticket and will continue investigating on it today.
From the latest image in the customer thread, I can see a tile positioned over another tile, in the middle of an animation.
That makes me suspicious that headless browser resources are not enough to do a complex layout animations. React Grid Layout does a lot of calculations and mounts with an animation, which is unnecessary for minimal web pages (screenshot pages) and consumes a lot of resources.
See the before-and-after in the video:
https://github.com/lightdash/lightdash/assets/962095/34806a44-9d88-4c45-b67d-f131d2bf42ae
> fix: disable animations in minimal dashboards

- packages/frontend/src/components/SimpleChart/index.tsx
- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes: #7285 
in: https://github.com/apache/echarts/issues/14563 we can see that there's issues when triggering the tooltip with `trigger: 'item'` + `showSymbol: false`
This PRs checks if the hovered item has that property set to `false` and then will not set the option to change the trigger to `item` if that matches.
https://github.com/lightdash/lightdash/assets/7611706/1574f73e-38cc-4b0b-a84a-87a6d1b293d9
> fix: keep tooltip trigger axis if line series with no symbol

- packages/frontend/src/components/ReactHookForm/AutoComplete.tsx
Closes: #7287
When `activeItem` is `undefined` on the Autocomplete, we should return `null` to indicate no item is active: https://blueprintjs.com/docs/#select/suggest
https://github.com/lightdash/lightdash/assets/7611706/5660de79-1911-49d5-924a-6616fd7e9a2a
> fix: set activeItem null if undefined

- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes: #7076
It took me a while to understand this issue, but it was really easy to replicate: 
- If you select a chart and select a date as X axis
- But then you sort by "another" dimension
- Then in the code we check if fthe `field` matches the sort : `alreadySorted` 
- If not, then we run a  `results.sort` 
- This method was messing with the results, the series was not matching the results
- This was causing that all results were displayed in the wrong place. 
Before:
X: axis Month
Sort by: quarter
After:
> fix: fix total label on stacked chart

- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes:  #3979
This fix also applies formatting to non-dates (eg: currency) 
Before
After
> fix: fix tootlip header format

- packages/frontend/src/components/RenderedSql.tsx
Closes: #7323
Similar to how SQL code is rendered in MetricFlow, let's also use `Prism` to render the generated SQL in explore:
> feat: use prism to render sql code

- packages/frontend/src/features/scheduler/components/SchedulerModal2.tsx
- packages/frontend/src/features/scheduler/components/SchedulerModalContent.tsx
- packages/frontend/src/features/scheduler/components/SchedulerModalContent2.tsx
Closes: #7324 
> **NOTE**: to test these changes, turn the feature flag on by pasting and running this in the console: `localStorage.setItem('scheduler-modal-2', true)`
Moves the modal for scheduled deliveries and the scheduled deliveries list to mantine. Not the list items. A couple notes for reviewers:
- SchedulerModalContent2 is a partial re-implementation of SchedulerModalContent. In coming reviews I will move the rest of the content over
- The CSS for making a sticky footer in Mantine isn't great and it's inline. I will move it somewhere shared when I need it again. Also, I was having trouble with it, so I time-boxed it and this is what I got. If someone has a better idea or pattern I'm all ears 😄 
Here's the new view:
With nothing in the list:
> chore: scheduled deliveries modal in mantine

- packages/e2e/cypress/e2e/app/dates.cy.ts
- packages/e2e/cypress/e2e/app/explore.cy.ts
Closes: N/A
With the introduction of a new component to render the compile SQL in explore we also need to update the E2E Cypress selectors.
> test: fix sql runner query compare between prism and ace

- packages/frontend/src/components/DashboardTiles/TileBase/TileBase.styles.tsx
- packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
- packages/frontend/src/components/SimpleStatistic/index.tsx
Closes: #7283
Remove height of a Tile's header block if this is set as hidden -> similar approach to the way we hide the header block if the Markdown Tile's Header is empty: https://github.com/lightdash/lightdash/pull/6535
Example of a tile with hidden title that doesn't have cropped-data issues anymore:
> style: center and hide header if hidden title

- packages/backend/src/services/UnfurlService/UnfurlService.ts
Closes: https://github.com/lightdash/lightdash/issues/7363
Previously we were filtering the element on `explore` by .echarts-for-react, this doesn't work for table viz or big value.
I also added some extra span details like orgUuid
> fix: fix unfurl data visualization on tables

- packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
Closes: #7229
Turn off stacking if moving from chart type AREA to something else, with no pivot dimensions.
Example:
* Create bar chart
* Change to Area
* Change back to bar
Screen recording with fix:
https://github.com/lightdash/lightdash/assets/7611706/a0f9d3a2-89cd-4824-b851-e6921a8be296
> fix: turn off stacking if no pivot dimensions

- packages/backend/src/services/SpaceService/SpaceService.ts
- packages/common/src/types/space.ts
- packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceAddUser.tsx
- packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceUserList.tsx
- packages/frontend/src/components/common/SpaceActionModal/index.tsx
Closes: N/A
Found Sentry error: https://lightdash.sentry.io/issues/4535709279/events/d4a562e0e27b464c96e8d6aaf8fc8936/?project=5959292&referrer=replay-errors
This improves the type of `access` and adds optional chaining where needed
> fix: make access possibly undefined

- packages/frontend/src/features/metricFlow/components/MetricFlowFieldList.tsx
- packages/frontend/src/features/metricFlow/utils/convertDimensionNameToLabels.ts
- packages/frontend/src/features/metricFlow/utils/convertMetricFlowFieldsToExplore.ts
Closes: #7329
The initial idea was to group them by "table" and have a tree. 
This will involve quite a bit of work and needs design. 
I opted to make the labels cleaner for now.
Before:
After:
> style: render semantic layer table label from dimension label

- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes:  #7405
> I think this might be have been a side effect of fixing https://github.com/lightdash/lightdash/issues/7076 , we removed the automatic sorting, that was causing a bug on totals. We could keep the sorting only if there are line charts, or no totals
Before:
Now:
However, this could still cause issues if there is a total on bar chart axis, the sorting is wrong and one of the axis is a line chart (edge case)
> fix: auto sorting line charts without totals

- packages/frontend/src/components/ChartDownload.tsx
Closes: #7352
This PR will not fix the issue when downloading (that requires a bit more of investigation) , this is just preventing the user from getting a white page when trying to download an image 
I believe this error might be happening on echarts library (I couldn't find an issue about this). But only happens when the label is `inside`, not when it is `outside`. This error doesn't happen even if we select outside first, and then outside. I'll create a separate PR 
[Screencast from 10-10-23 16:59:38.webm](https://github.com/lightdash/lightdash/assets/1983672/f87695cf-39c5-416b-8e40-99f7266ad4e0)
Try to download an image from the new pie chat on jaffle shop, you should see the error on console, previously that was throwing a white page
> fix: try-catch error when downloading jpeg image from pie chart

- packages/frontend/src/hooks/dashboard/useSavedQueryWithDashboardFilters.ts
Closes: #7400 
We were showing a loading state when there was no data for a chart. The result was a chart that had been deleted would show the loading state forever and the tile was un-deletable. 
To test:
1. Create a chart 
2. Add it to a dashboard
3. Delete the chart 
4. Go back to the dashboard
> fix: dead tiles when charts are deleted

- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLines.tsx
Closes:  #7421
Instead of using `name` to store the `uuid` we use echarts' value: 
I kept some .name filtering for backwards compatibility (so you can edit or remove "old" reference lines) 
Before: 
Now: 
Without label 
With label
> fix: reference lines uuid

- examples/full-jaffle-shop-demo/dbt/models/schema.yml
- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes: https://github.com/lightdash/lightdash/issues/7422
This fix https://github.com/lightdash/lightdash/pull/7307 introduced a new issue on `non-formatted` timestamps 
I am only formatting if the time interval is quarter (original issue) or the field is formatted 
Before
Now:
> fix: fix default tooltip format

- packages/frontend/src/pages/UserActivity.tsx
Closes: 
Fixes layout issue with posthog
<PosthogFeature> creates a `div`, that breaks the layout on analytics page. 
Before:
https://lightdash.slack.com/archives/C053ESBT36V/p1697186588749739?thread_ts=1696937066.677159&cid=C053ESBT36V
After:
> fix: posthog analytics feature layout

- packages/e2e/cypress/e2e/app/dates.cy.ts
- packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingRule.tsx
- packages/frontend/src/components/common/Filters/FilterRuleForm.tsx
Closes: #7338 
migrates operator inputs from blueprint to mantine
in explore:
explore filters with disabled state:
in conditional formatting:
> feat: filter inputs - operator inputs to mantine

- packages/cli/src/handlers/preview.ts
- packages/cli/src/index.ts
Closes: #5041 
- Added custom preview name through `--name`
- Enforced a single `lightdash preview` with the same name running at the same time
Creating preview - 
Creating preview with the same name as existing preview -
Aside - It seems that `preview` and `start-preview` can be merged into a single command with a `--live` option that runs `preview`
> feat: add --name to preview

- packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
Closes: #7408 
Showing the total toggle only for BAR charts.
> fix: Disables total toggle for line/area/scatter charts, only show for bar charts.

- packages/frontend/src/hooks/useSpaces.ts
Closes: #7461 
- fixed incorrect `queryKey` which was being used to invalidate queries 
Before :
https://www.loom.com/share/baa0453b02bd496b90ffccaf30dfef05
After : 
https://www.loom.com/share/53c00d26c66b4fb883c9a6b1adb3acd2
> fix: spaces delete not updating

- packages/frontend/src/components/common/modal/DashboardCreateModal.tsx
Closes: #7278
Click on the input, see a list of available spaces
Start typing to enter a new space name
It doesn't show up in the list, but I see an option to Create new space instead
https://github.com/lightdash/lightdash/assets/113882904/17badea1-a548-4026-a073-c1e96eb6f932
> feat: Replace 'Create new space' button in modals with a more efficient pattern

- packages/e2e/cypress/e2e/app/dashboard.cy.ts
- packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
- packages/frontend/src/components/common/TagInput/DefaultValue/DefaultValue.styles.ts
- packages/frontend/src/components/common/TagInput/DefaultValue/DefaultValue.tsx
- packages/frontend/src/components/common/TagInput/TagInput.styles.ts
- packages/frontend/src/components/common/TagInput/TagInput.tsx
- packages/frontend/src/components/common/TagInput/TagInputRightSection/TagInputRightSection.tsx
- packages/frontend/src/components/common/TagInput/TagInputRightSection/get-taginput-right-section-props.tsx
Closes: #7317 
This is a TagInput component that I am introducing to mantine v6 since we are stuck on v6.
Why are we stuck on mantine v6:
- mantine v7 depends on react 18
- upgrading to react 18 breaks blueprint
- blueprint is the problem
- but we should also migrate v6 mantine to v7 because of the breaking changes
---
TagInput Code comes from three sources but **it must be removed with Mantine v7!!!**
- PR that was going to introduce TagInput to Mantine v6.1 https://github.com/mantinedev/mantine/pull/3674
- TagInput from v7 https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/components/TagsInput/TagsInput.tsx#L93
- me
new tag input:
overflow:
> feat: filter inputs tag input to mantine

- packages/frontend/src/hooks/useSpaces.ts
Closes: #7491 
Updating the space name did not auto refresh on spaces page. Please see attached video for the fix:
https://github.com/lightdash/lightdash/assets/20976813/62167e96-99b2-4a42-a2aa-3fce330ed96a
> fix: auto refresh on renaming a space from spaces page

- packages/frontend/src/components/common/Page/Page.tsx
Closes: #6430 
- Changed `hasBanner` so that it takes the `PreviewBanner` into account and sizes appropriately
**Before** - 
https://www.loom.com/share/839674af27d948b7893684b64d82acb7
https://www.loom.com/share/e98e78d70c65479c991c77af627af8f0
**After** -
https://www.loom.com/share/526a55bb817549c2bdd65833c2c14bfd
https://www.loom.com/share/ea6a3dd4fe544232a6207ac498771b37
**Aside** - According to the [README](https://github.com/lightdash/lightdash/blob/main/packages/frontend/README.md) we're supposed to be following the Atomic Design Structure, but the components folder (presumably containing only molecules and organisms) contains lots of components that access files outside components ([e.g.](https://github.com/lightdash/lightdash/tree/main/packages/frontend/src/components/common/modal) …
> fix: scrolling issue

- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/warehouses/src/ssh/sshTunnel.ts
Closes: #7444
This will test connection before running a query, makes the server responsive in case one or more requests fail because of the tunnel. 
The tunnel object: 
With active connection
Without active connection
I was hoping this ssh library was using the event emitter interface, so I was expecting to do a `tunnel.on('close')`  to keep track of its state, but I couldn't find anything in the docs
> fix: ssh test connection before run query

- packages/frontend/src/components/common/Filters/FilterGroupForm.tsx
Closes: #7500 
Only show `Add Filter` if in Edit mode
Before: in issue ^
After:
> fix: hide add filter button if not in edit mode

- packages/common/src/compiler/exploreCompiler.test.ts
- packages/common/src/compiler/exploreCompiler.ts
Fix necessary for #7434
Problem, we didn't remove the final `}` from the reference name.
> fix: parsing all references

- packages/frontend/src/components/common/TagInput/TagInput.tsx
Add a validationFunction to TagInput. It already has a way to pass a regex, but it's a common pattern to pass a function for validation. For example, we use validateEmail and others in a number of places. 
- If neither validationRegex nor validationFunction is set, any value is allowed
- If only one of them is set, rejections are based on that one
- If both are set, new values must pass both tests
> feat: add a validation function to TagInput

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
Closes: #7435 
Disables links out on chart-in-dashboard titles. Editing a chart in a dashboard on a different browser tab causes bad state issues with the current design.
> fix: disable redirect for charts in dashboards

- packages/frontend/src/components/SimpleStatistic/index.tsx
Closes: #6608 
Good morning :)
Added a vertical scaling factor. Currently taking the minimum of both for scaling and it seems to me that it works, but let me know if a different behavior is required.
> Resize the viz to a reasonable extent when the panel shrinks. The other charts do this.
Done.
> Indicate when there is a viz that is hidden by the panel being too small.
Requires some design decisions. 
Let me know what you all think :)
Before :
https://www.loom.com/share/316e17f69b40447fb78fdd649a52ba7a
After : 
https://www.loom.com/share/d95ada8f5cc345d399bb71a426926fa3
> fix: allow vertical big number resizing

- packages/frontend/src/features/scheduler/components/SchedulerForm2.tsx
- packages/frontend/src/features/scheduler/components/SchedulerModalContent2.tsx
- packages/frontend/src/features/scheduler/components/SchedulerModalFooter.tsx
Closes: #7386 
> **NOTE**: to test these changes, turn the feature flag on by pasting and running this in the console: `localStorage.setItem('scheduler-modal-2', true)`
Add 'Send now' to the new scheduled deliveries form. This also includes moving footer code to its own file. The footer doesn't change, the main changes here are:
- Add the send now handler
- Validate before sending
- Add types to form transformation
> chore: scheduler send now

- packages/common/src/compiler/exploreCompiler.mock.ts
- packages/common/src/compiler/exploreCompiler.test.ts
- packages/common/src/compiler/exploreCompiler.ts
Closes: #7434
example yml
```
- name: orders
meta:
joins:
- join: customers
sql_on: ${customers.customer_id} = ${orders.customer_id}
fields: [first_name, last_name] # we don't need to include 'customer_id' anymore
```
Query using join table, customer id is used in the join but not available in the sidebar.
> feat: joined table fields can now omit fields used in the SQL

- packages/frontend/src/features/scheduler/components/SchedulerForm2.tsx
Closes: #7390 
> **NOTE**: to test these changes, turn the feature flag on by pasting and running this in the console: `localStorage.setItem('scheduler-modal-2', true)`
Add customization tab to scheduled deliveries. The new tab has the markdown input.
> chore: add customization tab to scheduler modal

- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
Dashboard action menu was staying open when clicked. It shouldn't. And it was causing a bad interaction with the modals.
Before (with bug):
After (fixed):
> fix: close dashboard action menu on click

- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/models/DashboardModel/DashboardModel.ts
- packages/backend/src/models/SpaceModel.ts
- packages/backend/src/services/DashboardService/DashboardService.ts
Closes: N/A
After merging this: #7370, I noticed I did the ordering of latest dashboard version outside of the subquery, making it not work as expected. 
This addresses that + removes an unused function
> fix: order on dashboards subquery first

- packages/frontend/src/components/DashboardTiles/AddTileButton.tsx
Related to what this PR https://github.com/lightdash/lightdash/pull/7539 fixed
On `add`  
We also should click on menu item click
> chore: close on add tile menu item click

- packages/frontend/src/features/scheduler/components/SchedulerForm2.tsx
- packages/frontend/src/features/scheduler/components/SchedulerModalContent.tsx
- packages/frontend/src/features/scheduler/components/SchedulerModalContent2.tsx
- packages/frontend/src/features/scheduler/components/SchedulerModalFooter.tsx
Closes: #7387 
> **NOTE**: to test these changes, turn the feature flag on by pasting and running this in the console: `localStorage.setItem('scheduler-modal-2', true)`
Adds edit mode for the new scheduled deliveries UI. You can now edit an existing schedule, save it, and send now.
> chore: edit mode for schedulers

- packages/frontend/src/components/common/SpaceActionModal/index.tsx
Closes: #7475
- Reset value of form when clicking the 'Back' button
Before - 
https://www.loom.com/share/5f899005f3da435483ec2c8fbaeb331c
After - 
https://www.loom.com/share/1ea55c65f28f4d998d24fdc77fd8af51
> fix: incorrectly created shared space when private selected

- packages/frontend/src/components/DashboardTiles/AddTileButton.tsx
Closes: N/A
Remove `Divider`s when adding tile on dashboards
> style: remove dividers on add tile menu

- packages/backend/src/services/ProjectService/ProjectService.ts
Closes: N/A
After work done on: https://github.com/lightdash/lightdash/pull/7370, one thing I missed was the:
`hasSpaceAccess` that was including private items for Admins' homepages. 
Before, we used to get:
* `charts` from `spaces-and-content` query: which has: `hasSpaceAccess(user, space, false),` -> does not include private spaces for admins (ref: https://github.com/lightdash/lightdash/blob/main/packages/backend/src/services/SpaceService/SpaceService.ts#L74)
* `dashboards` from `/projects/${projectUuid}/dashboards?includePrivate=false`, which also did the same: `hasSpaceAccess(user, space, false)` https://github.com/lightdash/lightdash/blob/main/packages/backend/src/services/DashboardService/DashboardService.ts#L172 where the hook defaults to false when no param is passed: …
> fix: do not include private resources if admin when on home page

- packages/backend/src/database/migrations/20231019161823_add_missing_index_to_saved_queries.ts
Add indices on our slowest queries in production. 
- saved_queries_versions (missing index on foreign key to parent)
- saved_queries_version_fields (missing index on foreign key to parent)
- saved_queries_version_additional_metrics (missing index on foreign key to parent)
- saved_queries_version_table_calculations (missing index on foreign key to parent)
- validations (missing index for scans by dashboard_uuid or saved_chart_uuid)
> fix: add indices to saved chart tables

- packages/frontend/src/hooks/useExplore.tsx
Closes: N/A
Add `staleTime` and `cacheTime` to `useExplore` query to reduce queries to the backend. 
`staleTime` will tell `react-query` that the data is fresh for `15` minutes; 
`cacheTime` will tell `react-query` to store the data in-memory (for `20` minutes)in order to avoid having to request the server for data that won't change that often. 
Why higher cacheTime? 
followed this article: https://www.codemzy.com/blog/react-query-cachetime-staletime
> feat: add stale time and cacheTime to useExplore

- packages/backend/src/controllers/authentication.ts
- packages/backend/src/routers/apiV1Router.ts
- packages/frontend/src/components/common/ThirdPartySignInButton/index.tsx
- packages/frontend/src/pages/Invite.tsx
- packages/frontend/src/pages/Login.tsx
- packages/frontend/src/pages/Register.tsx
Closes: #7571 
Things to tidy up:
- Refactor redirect code in Login, Register, Invite components - so that all methods use the same redirectURL
- Session data is cleared on `.authenticate` in passport: https://medium.com/passportjs/fixing-session-fixation-b2b68619c51d - are we accounting for this?
- Apply redirect logic consistently across all OIDC providers
Cases to test (common across password and all SSO providers):
- After logging in, I'm redirected to the homepage or `from` if it exists
- After registering via `/register` I'm redirected to the homepage or `from` if it exists
- After registering via `/login` with SSO I'm redirected to the homepage or `from` if it exists
- After registering via an invite link I'm redirected to the hompage or `from` if it exists
> fix: redirect on register

- packages/frontend/src/components/Explorer/ExploreSideBar/ExploreNavLink.tsx
Closes: #7579 
adds multiline prop to the tooltip avoid overflow
> fix: explore models tooltip

- packages/frontend/src/hooks/useExplore.tsx
This reverts commit 478d936cbe4c429bc72e2f23e51521737aae4b5a. - from PR: #7567 
Closes: N/A
When users update the `explores` through the CLI, the browser isn't aware that the cache needs to be invalidated; The user could refresh and that would clear the in-memory cache set by `react-query`, but that can lead to frustration and UX shouldn't be hindered by this change. 
We should find a way to trigger a job from the CLI to the browser, so it knows that it needs to invalidate - can we trigger a page refresh from the CLI?
> fix: revert "feat: add stale time and cacheTime to useExplore (#7567)"

- packages/e2e/cypress/e2e/app/explore.cy.ts
- packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx
- packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderSortMenuOptions.tsx
Closes: N/A
Replace `Popover` with `Menu` on results table columns; 
This was triggered by working on: https://github.com/lightdash/lightdash/pull/7590
> feat: replace popover with menu on results table

- packages/backend/src/models/ProjectModel/ProjectModel.ts
- packages/backend/src/services/PinningService/PinningService.ts
- packages/backend/src/services/ProjectService/ProjectService.mock.ts
- packages/backend/src/services/ProjectService/ProjectService.test.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/backend/src/services/SavedChartsService/SavedChartService.ts
- packages/backend/src/services/SearchService/SearchService.ts
- packages/backend/src/services/SpaceService/SpaceService.ts
- packages/backend/src/services/UnfurlService/UnfurlService.ts
- packages/backend/src/services/ValidationService/ValidationService.ts
- packages/common/src/types/projects.ts
Closes: #7598 
Problem:
I noticed that we were requesting the entire project information from the DB when we just needed the organisation uuid. 
Changes:
- Added type ProjectSummary
- Added new DB query to just fetch the project uuid, name and org uuid
- Update all the services to use new method when possible
- Update mocks
- My IDE also auto formatted some raw SQL in the model
Force tests:
test-frontend
> fix: optimize get project summary

- packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/FieldLayoutOptions.tsx
- packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLine.tsx
- packages/frontend/src/components/VisualizationConfigs/PieChartConfig/PieChartLayoutConfig.tsx
- packages/frontend/src/components/VisualizationConfigs/PieChartConfig/PieChartSeriesConfig.tsx
- packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ColumnConfiguration.tsx
- packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormatting.tsx
- packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingRule.tsx
- packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/GeneralSettings.tsx
Fixes tooltips getting cut off in the chart config sidebar. Mostly by putting them in a portal. 
🤔 is there a downside to setting `withinPortal` as the default? We can think about it.
> fix: tooltips in config sidebar

- packages/frontend/src/utils/dashboardSavedFiltersOverride.test.ts
- packages/frontend/src/utils/dashboardSavedFiltersOverride.ts
Relates to: #7547
When users view a dashboard, and alter its **saved** filters, they want to share a URL for that dashboard with the results they've customised. This PR covers the encoding of a difference between a saved filter and the override the user set; This string will then be added to the URL as part of an `overrides` search param. This util will then be used when a user updates a dimension/metric **saved** filter - however, we should agree on the format of these overrides. 
These overrides should: 
* include the `fieldId`
* include the `operator` (original or updated, if changed)
* include the `values` (if there's a change)
* include the `settings` (if need/changed)
**NOTE**: no logic for duplicate filters has been added yet. This PR isolates the scenario where the user updates a …
> chore: create util to construct dashboard saved filter override subparam

- packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
Closes: N/A
`BIGNUMERIC` values should be parsed so when the rows are formatted in the worker https://github.com/lightdash/lightdash/blob/fix/parse-big-numeric-big-query-cells/packages/backend/src/services/ProjectService/ProjectService.ts#L973 couldn't clone, leading to this error: 
```
DataCloneError: function Big2(n){var x=this;if(!(x instanceof Big2))return n===UNDEFINED?Big():new Big2(n);if(n instanceof Bi......2} could not be cloned.
```
Then, the values are parsed here: https://github.com/lightdash/lightdash/blob/fix/parse-big-numeric-big-query-cells/packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts#L44
(Note: I tried to reference `big.js` and do `x instaceof Big` but that was never truthy... 🤔 )
ref: https://github.com/MikeMcl/big.js
How to replicate:
* query a …
> fix: parse bignumeric in bigquery

- packages/frontend/src/features/scheduler/components/SchedulerModalBase.styles.ts
- packages/frontend/src/features/scheduler/components/SchedulerModalContent2.tsx
- packages/frontend/src/features/scheduler/components/SchedulersList.tsx
- packages/frontend/src/features/scheduler/components/SchedulersListItem.tsx
Closes: #7645 
Port scheduled deliveries list to mantine.
Before:
After:
> feat: scheduled deliveries list in mantine

- packages/backend/src/database/migrations/20231026185236_add-index-space-id-to-saved-queries.ts
Closes: N/A
Similar to: https://github.com/lightdash/lightdash/pull/7556/files - add index `space_id` to the `saved_queries` table
This will help on
`SpaceModel.find` - https://github.com/lightdash/lightdash/blob/chore/add-index-spaceid-to-saved-queries/packages/backend/src/models/SpaceModel.ts#L63
getting info for availableFilters -  https://github.com/lightdash/lightdash/blob/chore/add-index-spaceid-to-saved-queries/packages/backend/src/models/SavedChartModel.ts#L912
test-frontend
> chore: add space_id index to saved_queries table

- packages/e2e/cypress/e2e/app/dates.cy.ts
- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/DatePicker.tsx
closes: #7314 
migrates DateInput2 to mantine (this one is without time picker)
https://github.com/lightdash/lightdash/assets/962095/505fe414-c8e3-4ada-b112-7b4d4f3745cb
> feat: filter inputs - date picker input to mantine

- packages/frontend/src/hooks/useSavedDashboardFiltersOverrides.tsx
- packages/frontend/src/providers/DashboardProvider.tsx
Closes: #7696
Add JSON.stringified overrides of saved filters to the dashboard url as `filters` search param; 
Reintroduces changes reverted in #7261 (which were effectively fixing an issue with URLs being too long and unprocessable by the browser), but also **only** adds these overrides if they're actually overriding the **saved** filter. 
This ensures that when users share dashboard urls + if there are overrides to **saved** filters, the URL will include these; 
This also ensures that when users override **saved** dashboard filters, these will also be reflected on `Export Dashboard` functionality.
> fix: readd saved filter overrides

- packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.test.ts
- packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
- packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.mock.ts
- packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.test.ts
- packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
- packages/warehouses/src/warehouseClients/TrinoWarehouseClient.mock.ts
- packages/warehouses/src/warehouseClients/WarehouseClient.mock.ts
Closes: #7715 
Reverts: https://github.com/lightdash/lightdash/pull/7680 & https://github.com/lightdash/lightdash/pull/7624, so that later we can optimise column parsing once the caching strategy becomes more robust.
test-frontend
> fix: revert column parsing optimisation

- packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/FilterNumberInput.tsx
Closes: https://github.com/lightdash/lightdash/issues/7583
**Mantine V6 does not support decimal values without precision in NumberInput. I've added a note to remove this component once we move to Mantine v7**
> fix: filter inputs numeric input decimals

- packages/frontend/src/components/SchedulersView/SchedulersViewActionMenu.tsx
- packages/frontend/src/features/scheduler/components/SchedulerDeleteModal.tsx
- packages/frontend/src/features/scheduler/components/SchedulersList.tsx
Closes: #7646 
Migrate the scheduled deliveries delete dialog to mantine.
Old:
New!
> feat: use mantine for schedule delete dialog

- packages/e2e/cypress/support/commands.ts
- render.yaml
The cypress tests are failing a wide range of PRs because of unhandled exceptions from the resize observer. This is an experiment to ignore those errors. Is there a downside to this? If it passes we could merge it if we are ok ignoring these errors. 
test-frontend
> chore: ignore resize observer exceptions in e2e tests

- packages/frontend/src/components/common/Filters/FilterInputs/FilterDateRangePicker.tsx
Closes: #7767
When selecting a new date (non-timestamp) filter + `is between` operator, and there's no value set yet, set `maxDate` as undefined like we do already on `timestamp` date filters in: https://github.com/lightdash/lightdash/blob/fix/default-to-new-date-instance-on-is-between/packages/frontend/src/components/common/Filters/FilterInputs/FilterDateTimeRangePicker.tsx#L34
https://github.com/lightdash/lightdash/assets/7611706/29133a9d-cf77-499f-83d1-fa64d60664c6
> fix: set undefined maxDate when creating isbetween date filter

- packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
The Postgres client connection error detection order often prevents helpful information from bubbling up to the end user. I suspect many error conditions will have an undefined client and a defined error.
Prior to this PR this is what I see on the command line when an error occurs:
```
22:21:13  Done. PASS=7 WARN=0 ERROR=0 SKIP=0 TOTAL=7
Generated .yml files:
✖   Failed to generate ld__historical_organization_user.yml
Error running postgres query: Error: client undefined
```
After this PR this is what I see:
```
22:21:53  Done. PASS=7 WARN=0 ERROR=0 SKIP=0 TOTAL=7
Generated .yml files:
✖   Failed to generate ld__historical_organization_user.yml
Error running postgres query: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: [redacted] is not in …
```
> fix: expose correct Postgres error notification 

- packages/frontend/src/components/Explorer/CustomMetricModal/index.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/FilterStringAutoComplete.tsx
- packages/frontend/src/components/common/Filters/FilterRuleForm.tsx
- packages/frontend/src/components/common/Filters/FiltersProvider.tsx
Closes: #7744
Closes: https://github.com/lightdash/lightdash/issues/7337
Add `inModal` context to `FiltersProvider` so that inputs get correct `withinPortal` if so
> issue in mantine: https://github.com/mantinedev/mantine/issues/211
https://github.com/lightdash/lightdash/assets/7611706/e8113784-6b08-4a05-906f-fe17c921b0a2
> fix: filters + z indices on custom metric modal

- packages/backend/src/scheduler/SchedulerTask.ts
Closes: #7784 
Pass `schedulerUuid` to minimal dashboard params on scheduled deliveries if it exists;
We then can use the scheduler context on Minimal dashboards like so:
```tsx
const { search } = useLocation();
const searchParams = new URLSearchParams(search);
const schedulerUuid = searchParams.get('schedulerUuid');
const { data: scheduler, isLoading } = useScheduler(schedulerUuid ?? '');
```
> chore: pass schedulerUuid param to minimal dashboard if it exists

- packages/backend/src/database/migrations/20231101164443_add_cache_explores_foreign_key.ts
- packages/backend/src/models/ProjectModel/ProjectModel.ts
Closes: #7274 
- delete all cached explores for projects that no longer exist ( eg: preview projects ) 
- add foreign key to project table so the rows are deleted when a project is deleted
Force tests:
test-frontend
test-cli
> fix: add missing foreign key to cached explores table

- packages/frontend/src/components/SimpleStatistic/index.tsx
Closes: #7790 
Big number tooltip was getting cut off by adjacent tiles
> fix: big number tooltip gets cut off

- packages/backend/src/controllers/schedulerController.ts
- packages/backend/src/database/entities/scheduler.ts
- packages/backend/src/database/migrations/20231102135932_add-filters-to-scheduler-table.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/models/SchedulerModel/index.ts
- packages/common/src/types/scheduler.ts
Relates to: #4425
Adds migration file to add `filters` column to a scheduler
Updates scheduler DB with `filters` type and adds type guard `isDashboardScheduler`
> feat: add filters to schedulers

- packages/frontend/package.json
- packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLine.tsx
- packages/frontend/src/providers/BlueprintProvider.tsx
- yarn.lock
- gets rid of last blueprint date picker from reference lines
- adjusts spaces for other date inputs in reference lines
- removes npm dependencies and imports
day picker:
week picker:
month picker:
quarter:
year:
🎉 🎉 🎉
> feat: migrate last date picker to mantine

- packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLine.tsx
Closes: https://github.com/lightdash/lightdash/issues/7662
We previously used a `debounce` to mitigate this issue, because re-render makes it quite slow. That was a bit of a hack, instead I moved the render logic to `onblur` for label. 
[Screencast from 03-11-23 09:07:05.webm](https://github.com/lightdash/lightdash/assets/1983672/34d84b7b-61a2-4640-9bb5-4b246e9bcd5c)
> fix: update reference line label on blur

- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
- packages/frontend/src/components/common/Dashboard/DashboardRefreshButton.tsx
Closes: #3693 
Adds feature flag check `dashboard-auto-refresh`
Adds client-only auto-refresh functionality - if the user refreshes the page, the auto-refresh settings are reset and back to `Manual`.
Once an interval is created, it will run: 
```ts
clearCacheAndFetch();
invalidateDashboardRelatedQueries();
```
Screen-recording
Refresh-every-1-minute 
https://github.com/lightdash/lightdash/assets/7611706/e2f49caf-e68e-44d9-8964-b3f96d96ab4c
> feat: add dashboard auto refresh behind feature flag

- packages/frontend/src/features/scheduler/components/SchedulerForm.tsx
Closes: #7805 
Removes the 'no destination' text from scheduled deliveries. It wasn't necessary wasn't really following an existing validation pattern.
> fix: remove no destination text from scheduler

- packages/frontend/src/components/common/Filters/FilterInputs/FilterStringAutoComplete.tsx
Closes: #7812 
Initially, the last item you hovered over before the dropdown closed, was selected causing unexpected behavior. Disabling selectonblur property fixes that.
[Screencast from 04-11-23 13:20:20.webm](https://github.com/lightdash/lightdash/assets/76876702/f07f407a-6ec9-45f4-9e8f-33fda89e2bcf)
> fix: persist selected tags in multiselect

- packages/frontend/src/components/ReactHookForm/CronInput/CustomInputs.tsx
- packages/frontend/src/components/ReactHookForm/CronInput/DailyInputs.tsx
- packages/frontend/src/components/ReactHookForm/CronInput/FrequencySelect.tsx
- packages/frontend/src/components/ReactHookForm/CronInput/HourlyInputs.tsx
- packages/frontend/src/components/ReactHookForm/CronInput/MonthlyInputs.tsx
- packages/frontend/src/components/ReactHookForm/CronInput/WeekDaySelect.tsx
- packages/frontend/src/components/ReactHookForm/CronInput/WeeklyInputs.tsx
- packages/frontend/src/components/ReactHookForm/CronInput/index.tsx
Closes: #7804 
Updates scheduler form layout so that the time inputs are mostly on one line. Google sheets dialog gets the updates too -- it could probably use a design pass, but it doesn't look worse than it did before. 
Here's an example
> fix: make scheduler time inputs more compact

- packages/frontend/src/components/DashboardFilter/Filter.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterSettings.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/TileFilterConfiguration.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/Explorer/CustomMetricModal/index.tsx
- packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx
- packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLine.tsx
- packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingRule.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/BooleanFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/FilterDatePicker.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/FilterDateTimePicker.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/FilterMonthAndYearPicker.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/FilterStringAutoComplete.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/FilterUnitOfTimeAutoComplete.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/FilterWeekPicker.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/FilterYearPicker.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/index.tsx
- packages/frontend/src/components/common/Filters/FilterRuleForm.tsx
- packages/frontend/src/components/common/Filters/FiltersProvider.tsx
- packages/frontend/src/components/common/PivotTable/index.tsx
- packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
- packages/frontend/src/features/scheduler/components/SchedulerFilters.tsx
> chore: filter feature tidyup

- packages/backend/src/controllers/authentication.ts
Closes: [](https://lightdash.sentry.io/issues/4597992817/events/fdd2fb2daae54543a093e35ddc05ec46/?environment=cloud_beta&project=5959292&query=is%3Aunresolved&referrer=previous-event&statsPeriod=7d&stream_index=6)
Users were getting this error: `Cannot set headers after they are sent to the client` because it was trying to do both redirects;
> fix: return redirect on OIDC

- packages/backend/src/controllers/savedChartController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/services/CsvService/CsvService.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/common/src/utils/filters.ts
- packages/e2e/cypress/e2e/api/projectPermissions.cy.ts
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/hooks/dashboard/useDashboardFiltersForExplore.ts
- packages/frontend/src/hooks/dashboard/useDashboardFiltersForTile.ts
- packages/frontend/src/hooks/useQueryResults.tsx
- packages/frontend/src/utils/dateFilter.ts
Closes: 
At the moment, the logic to find what dashboard filters are applied to each chart is in the frontend. 
This PR is moving that logic to the BE. The FE sends all filters based on the tileUuid and the BE filters those based on the explore tables for that chart. 
The following PR is going to merge a few of the requests from the frontend and some of this code ( frontend/common) is going to be removed.
> feat: apply dashboard filter to chart in server

- .github/workflows/release-on-merge.yml
this should mean github triggers a tag-pushed action to trigger `main.yml` jobs
> chore: not persist credentials for release action

- packages/backend/src/clients/Google/GoogleDriveClient.ts
- packages/backend/src/scheduler/SchedulerTask.ts
Closes: 
Before: 
After: 
When downloading from chart or results (uploadGsheetFromQuery)
From google sync (uploadGsheet)  we can hide table names and use custom label s
> fix: google sheet column names

- packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLine.tsx
Closes:  #7875
What happened: I recently moved from using `name` to `value` to set a label instead of an uuid (but kept the name for backwards compatibility) , however, the update method was not updated to use the new id field, this was causing that all the lines were updated at the same time because it was sending name (reference line).
> fix: multiple reference lines

- packages/frontend/src/components/DashboardFilter/Filter.tsx
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx
- packages/frontend/src/hooks/dashboard/useDashboard.tsx
- packages/frontend/src/hooks/dashboard/useDashboardStorage.tsx
- packages/frontend/src/pages/Dashboard.tsx
- packages/frontend/src/providers/DashboardProvider.tsx
Closes: N/A
Make `dashboardTiles` initial value `undefined` so that, when loading a dashboard that we know has `tiles`, we can avoid calling `/charts` endpoint in `EmptyStateNoTiles`.
> fix: make dashboard tiles initially undefined to avoid extra call

- packages/backend/src/services/ProjectService/ProjectService.ts
Closes: N/A
Avoid making 2 extra calls to get `getExplore` by passing `explore` to relevant methods so that's reused until the end of getting results
Also, parallelise 2 db queries: to get the space summary + get explore to speed things up.
> fix: optimise chart results endpoint

- packages/frontend/src/components/DashboardFilter/Filter.tsx
- packages/frontend/src/providers/DashboardProvider.tsx
I was analyzing performance related to 'filter pills,' and it appears that we were recalculating all the functions I memoized in the PR after every minor action, such as drag-and-drop, opening menus, and hovering over buttons. This is likely due to the heavy Dashboard provider state and not 'slicing' useDashboardContext anywhere.
Not memoizing the variables in the filter pill component leads to significant rerendering of child components. This happens because all recalculated variables are references (not value types), and React only performs shallow diffing.
> fix: dashboard filters performance (Part 1)
