lightdash/lightdash

packages/backend/src/services/ProjectService/ProjectService.ts
Closes: 
Allow to create a preview without an upstream project.
If there is an upstream project, check access to that project.
test-cli
test-backend
test-frontend
=> fix: create preview permission

packages/backend/src/database/entities/projects.ts, packages/backend/src/database/migrations/20241101095115_add_created_by_user_uuid_to_projects.ts, packages/backend/src/database/seeds/development/01_initial_user.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/models/ProjectModel/ProjectModel.mock.ts, packages/backend/src/models/ProjectModel/ProjectModel.ts, packages/backend/src/services/ProjectService/ProjectService.mock.ts, packages/backend/src/services/ProjectService/ProjectService.ts, packages/common/src/authorization/organizationMemberAbility.test.ts, packages/common/src/authorization/organizationMemberAbility.ts, packages/common/src/authorization/projectMemberAbility.test.ts, packages/common/src/authorization/projectMemberAbility.ts, packages/common/src/index.ts, packages/common/src/types/organization.ts, packages/common/src/types/projects.ts, packages/frontend/src/components/UserSettings/ProjectManagementPanel/index.tsx, packages/frontend/src/pages/Settings.tsx
Closes: https://github.com/lightdash/lightdash/issues/12044
test-backend
test-frontend
test-cli
=> feat: developers should be able to delete previews 

packages/backend/src/controllers/projectController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/models/TagsModel.ts, packages/backend/src/services/ProjectService/ProjectService.ts, packages/common/src/index.ts, packages/common/src/types/tags.ts, packages/frontend/src/features/metricsCatalog/components/CatalogTag.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogTagForm.tsx, packages/frontend/src/features/metricsCatalog/hooks/useCatalogTags.tsx, packages/frontend/src/features/metricsCatalog/utils/getRandomTagColor.tsx
Relates to: https://github.com/lightdash/lightdash/issues/10330
> [!NOTE]
> Next PR will focus on tagging and displaying tags in the column for the catalog field
Creates form to create tag
Uses util to get a random color from a mantine color palette (we utilise hex codes tho)
Creates Tag component that generates a tag styling depending on the base color.
Demo
https://github.com/user-attachments/assets/69bd6b0c-d1e9-405d-9433-ac00b86b4187
=> feat: allow creating tag for project and get tags

examples/api/catalog.http, packages/backend/src/controllers/projectController.ts, packages/backend/src/database/entities/tags.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/models/TagsModel.ts, packages/backend/src/services/ProjectService/ProjectService.ts
Closes: #12271 
- Adds `PATCH {project_uuid}/tags/{tag_uuid}`
=> feat: add tag update endpoint

packages/backend/src/controllers/projectController.ts, packages/backend/src/generated/swagger.json, packages/frontend/src/features/metricsCatalog/components/MetricCatalogTagFormItem.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogTagForm.tsx, packages/frontend/src/features/metricsCatalog/hooks/useCatalogTags.tsx
Relates to: #10330
Adds trash icon to delete tag
invalidates on deletion
makes small styling change to the save button as requested by @PriPatel 
https://github.com/user-attachments/assets/9e2c22e9-fbd5-4614-8f76-195fee8fdb2d
=> feat: allow deleting tags

packages/frontend/package.json, packages/frontend/src/components/NavBar/CreatePreviewProjectModal.tsx, packages/frontend/src/components/NavBar/ProjectSwitcher.tsx, yarn.lock
Closes: https://github.com/lightdash/lightdash/issues/12170
=> feat: project list in create preview modal

packages/backend/src/models/ProjectModel/ProjectModel.ts, packages/backend/src/services/ProjectService/ProjectService.mock.ts, packages/common/src/types/organization.ts, packages/frontend/src/components/UserSettings/DeleteProjectPanel/ProjectDeleteInBulkModal.tsx, packages/frontend/src/components/UserSettings/ProjectManagementPanel/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/8077
https://github.com/user-attachments/assets/8a092119-c429-4d2a-bb92-96ae9e18d6ba
=> feat: project list UX and bulk actions

packages/backend/src/controllers/projectController.ts, packages/backend/src/generated/swagger.json, packages/frontend/src/features/metricsCatalog/components/MetricCatalogTagFormItem.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogTagForm.tsx, packages/frontend/src/features/metricsCatalog/hooks/useCatalogTags.tsx
Relates to: #10330
Adds hook to update tag
creates shared component to allow edit of label or color (and adds a small preview on color refresh)
Demo
https://github.com/user-attachments/assets/977cc0c0-20bf-41e6-bf33-181b6f05145c
=> feat: enable editing a tag/category's label or color

packages/common/src/compiler/translator.ts
Closes: https://github.com/lightdash/lightdash/issues/12257
Before
After
=> fix: additional dimension timestamp description

packages/backend/src/database/entities/catalog.ts, packages/backend/src/models/CatalogModel/CatalogModel.ts, packages/backend/src/models/ProjectModel/ProjectModel.ts, packages/backend/src/scheduler/SchedulerTask.ts, packages/backend/src/services/CatalogService/CatalogService.ts, packages/backend/src/services/CsvService/CsvService.test.ts, packages/backend/src/services/ProjectService/ProjectService.test.ts, packages/backend/src/services/ProjectService/ProjectService.ts, packages/backend/src/services/ServiceRepository.ts, packages/common/src/types/catalog.ts
Closes: #12269 
https://github.com/user-attachments/assets/c63cc783-df10-40ff-8954-49e0e4f9ad54
=> feat: migrate tags from previous catalog to newly indexed catalog

packages/backend/src/models/CatalogModel/CatalogModel.ts
- Fixes the search function after https://github.com/lightdash/lightdash/pull/12130/files#diff-ae15d8bab3decc0dd34758f1a560b0cd1905d6f6153161bff4efed171a0a5084
=> fix: make search query default empty string

packages/backend/src/models/CatalogModel/CatalogModel.ts, packages/backend/src/models/ModelRepository.ts
=> chore: add lightdashconfig to catalog model

packages/backend/src/models/CatalogModel/CatalogModel.ts
=> chore: export catalog args

packages/cli/src/dbt/models.ts, packages/cli/src/handlers/generate.ts
Closes: https://github.com/lightdash/lightdash/issues/12215
how I was able to reproduce this: https://github.com/lightdash/lightdash/issues/12215
=> fix: cli generate when passing project dir

packages/frontend/src/components/common/Table/Table.styles.ts
Closes:  https://github.com/lightdash/lightdash/issues/12029
See thread: https://lightdash.slack.com/archives/C075JNX28GG/p1730976164813749?thread_ts=1729328955.618789&cid=C075JNX28GG
Before:
[Screencast from 07-11-24 11:31:09.webm](https://github.com/user-attachments/assets/e6954d88-763b-4301-9fcb-ffc2dccf50fd)
After:
[Screencast from 07-11-24 11:31:23.webm](https://github.com/user-attachments/assets/d49d7664-776d-4d78-9633-99c518c3d239)
=> fix: show all content for pinned columns

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx, packages/frontend/src/features/metricsCatalog/store/metricsCatalogSlice.ts
Closes: N/A
`>= editor`
`< editor`
=> fix: hide add tag button if no permissions to manage

packages/backend/src/clients/Google/GoogleDriveClient.ts
Closes:  https://github.com/lightdash/lightdash/issues/12191
Before
After:
These dates can be formatted  correctly later using gsheets
=> fix: date format gsheets

packages/backend/src/services/ProjectService/ProjectService.ts
Closes:  https://github.com/lightdash/lightdash/issues/12199
Before:
=> fix: remove virtual explore from exposure

packages/common/src/types/filter.ts, packages/frontend/src/features/scheduler/components/SchedulerFilters.tsx
This reverts commit d370bcd92646318be8714b02989efdaa98597797.
This PR seems to have caused problems for users. Reverting for now.
=> fix: Revert "fix: time-based filters in scheduled deliveries  (#12272)"

packages/backend/src/models/GroupsModel.ts, packages/backend/src/models/OrganizationMemberProfileModel.ts, packages/backend/src/services/OrganizationService/OrganizationService.ts
Commercial Repo: https://github.com/lightdash/lightdash-commercial/pull/374 
- This adds a function that allows search to search by exact instead of a fuzzy search
- This will be used by SCIM `eq` filter when looking for specific users
=> feat: added ability to list users within org and groups by exact match

packages/backend/src/analytics/LightdashAnalytics.ts, packages/backend/src/services/OrganizationService/OrganizationService.ts, packages/backend/src/services/UserService.ts
Relates to: [#352](https://github.com/lightdash/lightdash-commercial/issues/352)
Changes:
- delete duplicate 'user.deleted' event
- add `context` property to user events
- enforce user events to have the user id from who performed the action
- added consistent properties for the affected user and organization
- exported types as they will be overridden the commercial repo
- fix a `user.delete` event that was tracking the wrong user id.
=> fix(analytics): user create/update/delete analytics event

packages/backend/src/analytics/LightdashAnalytics.ts, packages/backend/src/services/GroupService.ts, packages/backend/src/services/OrganizationService/OrganizationService.ts, packages/backend/src/services/UserService.ts
Relates to: https://github.com/lightdash/lightdash-commercial/issues/352
Changes:
- Add context to group events
=> fix(analytics): group create/update/delete analytics

packages/backend/src/analytics/LightdashAnalytics.ts
Related to: [#352](https://github.com/lightdash/lightdash-commercial/issues/352)
Allow user and group events to be anonymous. This is necessary as commercial can't override events from OSS yet.
=> chore(analytics): allow anonymous user and group events

packages/backend/src/controllers/sqlRunnerController.ts, packages/backend/src/generated/swagger.json, packages/frontend/src/components/UserSettings/GithubSettingsPanel/index.tsx, packages/frontend/src/features/sqlRunner/store/thunks.ts
Closes:  https://github.com/lightdash/lightdash/issues/12169
**Before:**
The entire sql runner page was empty, no tables, and github was throwing errors
**Now:**
YOu can select tables, write sql, but you can't run queries.
=> fix: fix sql runner page in demo

packages/frontend/src/features/metricsCatalog/hooks/useCatalogCategories.tsx, packages/frontend/src/features/metricsCatalog/hooks/useProjectTags.tsx, packages/frontend/src/features/metricsCatalog/utils/updateMetricsCatalogQuery.ts
Closes: N/A
Relates to: https://github.com/lightdash/lightdash/pull/12329
Creates shared util to set query data for `metrics-catalog` query with a callback for data transformation. 
Also, introduced `immer`
=> refactor: use shared util to set queryData for metrics catalog

packages/frontend/src/features/metricsCatalog/components/MetricCatalogCategoryFormItem.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogCategoryForm.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar.tsx
Closes: #12319 #12311
- Opens categories popover on cell click
- Changes category row to be the target area
- Shows category 3 dot menu on hover
- Applies category filters on select instead of on popover close
=> chore: metrics catalog ux improvements

packages/frontend/src/features/metricsCatalog/components/MetricCatalogCategoryFormItem.tsx
Closes: [#12309](https://github.com/lightdash/lightdash/issues/12309)
Remove
Refresh
=> chore: add tooltips to catalog form item actions

packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar.tsx
=> fix: add clear button to search component

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
Closes: [#12299](https://github.com/lightdash/lightdash/issues/12299)
=> chore: change table loading indicator to spinner

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar.tsx
Closes: #12301 
https://github.com/user-attachments/assets/93af3a6d-801a-4348-9fb6-1b17d5e48d0f
=> chore: add total results indicator

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx, packages/frontend/src/features/metricsCatalog/store/metricsCatalogSlice.ts
Closes: #12346 
https://github.com/user-attachments/assets/dc70f992-13f2-4252-b703-869b0a8b2849
=> fix: click on category cell only closes the popover

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumnName.tsx, packages/frontend/src/providers/TrackingProvider.tsx, packages/frontend/src/types/Events.ts
Closes: [#12369](https://github.com/lightdash/lightdash/issues/12369)
=> chore: track when a metric icon is applied

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumnName.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx
=> chore: add table name as tooltip

docs/docs/self-host/customize-deployment/recommended-resources.mdx, docs/docs/self-host/self-host-lightdash.mdx
Add basic docs for recommended resources. This has been asked about a few times. I got these values from our help setup.
=> docs: add resource recommendations

packages/backend/src/projectAdapters/dbtAzureDevOpsProjectAdapter.ts, packages/backend/src/projectAdapters/dbtBitBucketProjectAdapter.ts, packages/backend/src/projectAdapters/dbtGitProjectAdapter.ts, packages/backend/src/projectAdapters/dbtGithubProjectAdapter.ts, packages/backend/src/projectAdapters/dbtGitlabProjectAdapter.ts
Closes:  #12150
Before: 
> Something went wrong
or 
After:
=> fix: better git errors

packages/backend/src/database/entities/groups.ts, packages/backend/src/database/migrations/20241108145015_group-names-unique.ts, packages/backend/src/database/migrations/20241112140014_add-updated-columns-to-groups-table.ts, packages/backend/src/database/seeds/development/04_groups.ts, packages/backend/src/models/GroupsModel.ts, packages/backend/src/services/GroupService.ts, packages/backend/src/services/OrganizationService/OrganizationService.ts, packages/common/src/types/groups.ts, packages/e2e/cypress/e2e/api/groups.cy.ts
Relates to: [#357](https://github.com/lightdash/lightdash-commercial/issues/357)
Changes:
- update groups table to store information of when/who created and updated the group
- adjust queries to insert and get that information
- fix e2e tests to generate unique names on each run
=> feat: add group created and updated metadata

docs/src/components/PlanPills.jsx
=> docs: add pill components for plans

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogCategoryForm.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumnName.tsx, packages/frontend/src/styles/emoji-picker-react.css
Closes: N/A
- resized emojis and some padding, font sizes etc (had to use `!important`)
- enabled search
- disabled preview
**Before**
**After**
=> style: resize `emoji-picker-react`

docs/docs/references/scim-integration.mdx
Merge this first: https://github.com/lightdash/lightdash/pull/12395
- Adds Enterprise Cloud pill for SCIM docs
=> docs: added cloud enterprise pill to SCIM docs

docs/docs/references/scim-integration.mdx
Closes: https://github.com/lightdash/lightdash-commercial/issues/380
- Added note explaining that active status is synced from providers
=> docs: added note about active status syncing from provider

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar.tsx
=> chore: metrics catalog table container

packages/frontend/src/features/metricsCatalog/components/CatalogCategory.tsx, packages/frontend/src/features/metricsCatalog/components/MetricCatalogCategoryFormItem.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogCategoryForm.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumnName.tsx, packages/frontend/src/features/metricsCatalog/utils/getRandomTagColor.tsx, packages/frontend/src/styles/emoji-picker-react.css
Closes: [#12365](https://github.com/lightdash/lightdash/issues/12365)
This PR moves the category form item to a subpopover and handles the opening and closing depending on the click events etc. 
Changes the refresh-color-behaviour to a predefined color palette.
https://github.com/user-attachments/assets/36b1bccd-c72a-4e9e-832c-eb5588ae6aac
=> feat: display color swatch picker

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar.tsx, packages/frontend/src/mantineTheme.ts
=> chore: table header improvements

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
=> chore: table footer improvements

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumnName.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx, packages/frontend/src/features/metricsCatalog/hooks/useCatalogCategories.tsx, packages/frontend/src/features/metricsCatalog/hooks/useCatalogItemIcon.tsx, packages/frontend/src/features/metricsCatalog/hooks/useProjectTags.tsx
Closes: #12394
Improves loading experience
increases page size to `50`
> [!NOTE]
> on the ticket it says to show the spinner on scroll for next page, but I can't seem to be able to show it. I still think that these changes are better than what we have now.
demo:
https://github.com/user-attachments/assets/9eb68259-e5a3-4624-a467-1d3e9eb4a7a0
=> chore: improve loading ux and increase page size to 50

.env
=> fix: update port for site_url in .env

docs/docs/references/scim-integration.mdx
- added small note mentioning user needs to have administrative permissions for Okta and Azure
=> docs: made note for admin permissions in scim docs

packages/frontend/src/features/metricsCatalog/components/CatalogCategory.tsx, packages/frontend/src/features/metricsCatalog/components/CatalogCategorySwatch.tsx, packages/frontend/src/features/metricsCatalog/components/MetricCatalogCategoryFormItem.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx, packages/frontend/src/features/metricsCatalog/styles/useCategoryStyles.ts, packages/frontend/src/features/metricsCatalog/utils/getRandomTagColor.tsx
Relates to: [#12277](https://github.com/lightdash/lightdash/issues/12277)
Added reusable hook
Updated palette
Added separate swatch-like component
=> style: apply more styling to categories

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
=> chore: add table cell styles

.github/CONTRIBUTING.md, docs/docs/self-host/customize-deployment/enable-headless-browser-for-lightdash.mdx, examples/full-jaffle-shop-demo/dbt/models/events.yml
=> chore: remove puppeteer in docs

packages/frontend/src/features/metricsCatalog/components/ExploreMetricButton.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
=> chore: metrics catalog show explore on row hover

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumnName.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx
Relates to: [#12277](https://github.com/lightdash/lightdash/issues/12277)
demo:
=> style: apply fw and lh to metric name & description

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
=> fix: metrics catalog table height

packages/frontend/src/features/metricsCatalog/components/MetricCatalogCategoryFormItem.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar.tsx, packages/frontend/src/features/metricsCatalog/styles/useCategoryStyles.ts, packages/frontend/src/mantineTheme.ts
Closes: [#12436](https://github.com/lightdash/lightdash/issues/12436)
Hover over row - maybe this needs to be 200.
Hover over pills ( just feels a bit clunky right now),,,
Hover over categories filter button 
hover over category form item (when applying)
hover on row to show explore
=> style: add transition duration of 200ms to hover interactions

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
=> fix: column sizes to match figma & table head border

packages/frontend/src/features/metricsCatalog/components/ExploreMetricButton.tsx, packages/frontend/src/features/metricsCatalog/components/MetricChartUsageButton.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumnName.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar.tsx, packages/frontend/src/pages/MetricsCatalog.tsx
Closes: https://github.com/lightdash/lightdash/issues/12247
> [!NOTE]
> This doesn't fix the persisting tooltips when clicking on any sort action icon. Ref: https://github.com/KevinVandy/mantine-react-table/issues/186
=> style: theme tooltips

packages/frontend/src/features/metricsCatalog/components/CatalogCategory.tsx, packages/frontend/src/features/metricsCatalog/components/CatalogCategorySwatch.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar.tsx, packages/frontend/src/features/metricsCatalog/styles/useCategoryStyles.ts
Closes: [#12474](https://github.com/lightdash/lightdash/issues/12474)
- Removed hover interaction on categories (but kept on swatches)
- Changes inset pixel 
- Reduced gap
- Change icon color and size
=> style: apply misc UI changes to categories

packages/backend/src/App.ts
Closes: https://github.com/lightdash/lightdash-internal-work/issues/2227
On render:
=> chore: add policy express demo

packages/backend/src/postHog.ts, packages/backend/src/services/CommentService/CommentService.ts
Closes:  https://github.com/lightdash/lightdash/issues/12480
=> fix: enable by default comments feature

packages/frontend/src/features/metricsCatalog/components/MetricCatalogCategoryFormItem.tsx, packages/frontend/src/features/metricsCatalog/components/MetricChartUsageModal.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogCategoryForm.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar.tsx, packages/frontend/src/pages/MetricsCatalog.tsx
=> style: final changes to tag form input and popover

packages/e2e/cypress/e2e/api/sqlRunner.cy.ts, packages/e2e/cypress/support/warehouses.ts
=> fix: disable databricks sqlrunner

docs/docs/references/scim-integration.mdx
Closes: https://github.com/lightdash/lightdash-commercial/issues/403
=> docs(scim): document how to rotate a SCIM token

packages/warehouses/package.json, yarn.lock
Closes: 
Bump trino client version.
test-cli
=> fix: trino client dependency

packages/frontend/src/components/NavBar/ProjectSwitcher.tsx
=> fix: project menu empty list

packages/common/src/types/filter.ts, packages/e2e/cypress/e2e/api/dashboard.cy.ts, packages/frontend/src/components/UserSettings/MyWarehouseConnectionsPanel/index.tsx, packages/frontend/src/hooks/useExplorerRoute.ts
Closes: https://github.com/lightdash/lightdash/issues/12518
=> feat: metrics explorer default filters

packages/frontend/src/components/ChartDownload.tsx, packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx, packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
Closes:  https://github.com/lightdash/lightdash/issues/12521
=> feat: export image tile dashboard

docs/docs/references/user-attributes.mdx
=> docs: clarify column filtering and how it impacts metrics

packages/backend/package.json, packages/backend/src/logging/winston.ts, packages/backend/src/scheduler/SchedulerWorker.ts, packages/backend/src/scheduler/SchedulerWorkerEventEmitter.ts, yarn.lock
Closes: [#12420](https://github.com/lightdash/lightdash/issues/12420)
Add worker and job metadata to all logs to allow developers to filter all logs related to a worker, job, task.
All pretty logs now contain the worker and job id
Example:
```Sentry:bd4cd79458a6e9b8a4c7bc8207b9eff7 Worker:worker-c24d396d6dcbfeec27 Job:93```
All json logs now contain the following properties:
```
{
...
worker?: {
id: string | null;
};
job?: {
id: string;
queue_name: string | null;
task_identifier: string;
priority: number;
attempts: number;
};
}
```
```
[backend] 2024-11-19 17:53:35 [Lightdash] http: POST /api/v1/projects/3675b69e-8324-4110-bdca-059031aa8da3/explores/payments/downloadCsv 200 - 16 ms
[backend] 2024-11-19 17:53:35 [Lightdash] info: Worker worker-c24d396d6dcbfeec27 started job 93 …
```
=> chore: add worker and job metadata to logs

docs/docs/guides/metrics-catalog.mdx, docs/sidebars.js
Relates to: [#12544](https://github.com/lightdash/lightdash/issues/12544)
=> docs: add metrics catalog guide

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx, packages/frontend/src/features/metricsCatalog/store/metricsCatalogSlice.ts
Closes: [#12544](https://github.com/lightdash/lightdash/issues/12544)
demo:
=> chore: add popover info to metric catalog instructions

packages/frontend/src/components/NavBar/BrowseMenu.tsx
Closes: [#12543](https://github.com/lightdash/lightdash/issues/12543)
Demo
=> feat: add metrics catalog browse menu item

packages/frontend/src/components/DashboardTabs/index.tsx, packages/frontend/src/pages/Dashboard.tsx, packages/frontend/src/styles/react-grid.css
Closes: #12528 
- makes dashboard spacing consistent with headers
=> fix: dashboard X spacing to be consistent with headers

packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/routers/organizationRouter.ts, packages/backend/src/scheduler/SchedulerClient.ts, packages/backend/src/scheduler/SchedulerTask.ts, packages/backend/src/scheduler/SchedulerWorker.ts, packages/backend/src/services/ProjectService/ProjectService.ts, packages/cli/src/handlers/createProject.ts, packages/common/src/index.ts, packages/common/src/types/projects.ts, packages/common/src/types/scheduler.ts, packages/e2e/cypress/support/commands.ts
…(#12491)"
Closes: 
This reverts commit 71fb811c2a7604817edd5d4024aa2107eac28774.
[feat: project creation in scheduler] https://github.com/lightdash/lightdash/commit/71fb811c2a7604817edd5d4024aa2107eac28774
That commit caused a breaking change in our API and is affecting all previous CLI versions. 
Once this is merged, all versions between [chore(release): 0.1375.0](https://github.com/lightdash/lightdash/commit/b2bb4fbd0e5dd60449ba8cebdda69422cc6b9ed1) until this fix will be broken, which is a much smaller number than all previous CLI versions.
=> fix: create project and preview with older CLI versions  

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
Closes:  https://github.com/lightdash/lightdash/issues/12576
=> fix: remove export image from bignumber charts

packages/frontend/src/features/sqlRunner/components/TablesPanel.tsx
Closes: https://github.com/lightdash/lightdash/issues/12282
Before
After
=> fix: adjust size panel

packages/backend/src/controllers/catalogController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/CatalogService/CatalogService.ts, packages/common/src/types/catalog.ts, packages/frontend/src/features/metricsCatalog/components/MetricPeekDatePicker.tsx, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/features/metricsCatalog/hooks/useDateRangePicker.tsx, packages/frontend/src/features/metricsCatalog/hooks/useMetricsCatalog.tsx, packages/frontend/src/features/metricsCatalog/utils/metricPeekDate.tsx
Closes: https://github.com/lightdash/lightdash/issues/12598
- gets default time dimension from endpoint so that the default time range is applied.
- Adds util to generate date ranges (based on default time dimension) and presets (as described in ticket)
- Introduces hook to generate utils and values for date range picker 
> [!NOTE]
> No BE queries yet
> [!NOTE]
> Styling changes should be done separately - the base UI/UX has been reviewed by @PriPatel already.
DEMO
https://github.com/user-attachments/assets/3fea6a24-c334-4066-99d4-47cb12f766e5
=> feat: display date-range picker and allow preset selection [UI]

packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceUserList.tsx
Closes: #12488 
- Adds deduplication logic to not show the same user more than once in space permissions. This is caused when the user belongs to more than one group.
=> fix: user list in space permissions shows duplicates

packages/backend/src/routers/organizationRouter.ts, packages/backend/src/scheduler/SchedulerClient.ts, packages/backend/src/scheduler/SchedulerTask.ts, packages/backend/src/scheduler/SchedulerWorker.ts, packages/backend/src/services/ProjectService/ProjectService.ts, packages/common/src/types/scheduler.ts
Closes: [#11405](https://github.com/lightdash/lightdash/issues/11405)
We don't need to update other endpoints as the project creation is the last one to still compile a project in the main server instead of the worker.
Changes:
- move the async work to a scheduled task
- update all project tasks to have 1 max attempts
=> chore: move project creation to scheduler

packages/backend/src/queryBuilder.ts, packages/backend/src/services/ProjectService/ProjectService.ts, packages/common/src/types/filter.ts, packages/common/src/utils/formatting.ts
Closes: https://github.com/lightdash/lightdash/issues/12615
Reverts lightdash/lightdash#12515
See thread: https://lightdash.slack.com/archives/C03MCQ08UKS/p1732633555162649?thread_ts=1732564947.022949&cid=C03MCQ08UKS
Reopen: https://github.com/lightdash/lightdash/issues/12448
=> fix: Revert "fix: apply date granularity to filters"

packages/backend/src/services/ProjectService/ProjectService.ts
Relates to: https://github.com/lightdash/lightdash/pull/12616/files
- Re-adds missing import
=> fix: add missing import

packages/backend/src/controllers/metricsExplorerController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts, packages/backend/src/services/ServiceRepository.ts, packages/common/src/types/catalog.ts, packages/common/src/types/metricsExplorer.ts, packages/frontend/package.json, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsVisualization.tsx, packages/frontend/src/features/metricsCatalog/hooks/useRunMetricExplorerQuery.ts, yarn.lock
Closes: [#12609](https://github.com/lightdash/lightdash/issues/12609)
=> feat: metrics explorer visualization 

packages/backend/src/services/PromoteService/PromoteService.ts, packages/common/src/authorization/organizationMemberAbility.test.ts, packages/common/src/authorization/organizationMemberAbility.ts, packages/common/src/authorization/projectMemberAbility.test.ts, packages/common/src/authorization/projectMemberAbility.ts, packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
Closes:  https://github.com/lightdash/lightdash/issues/12525
This PR will fix a bug for p ublic spaces and add the `disabled` option if the user does not have permissions.
=> fix: promote content for developers

packages/backend/src/services/CoderService/CoderService.ts
=> fix:  dependency coder

packages/frontend/src/features/metricsCatalog/components/MetricPeekDatePicker.tsx
Closes: N/A
button looks similar to the radio group below
small changes throughout the calendar component
Demo
=> style: update metric peek date picker styles

packages/frontend/src/features/metricsCatalog/components/MetricPeekDatePicker.tsx, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/mantineTheme.ts
Closes: N/A
Adds new Offwhite color - there's a theory that we could add an _off_ color pallette (thank you @PriPatel for the suggestion)
but just one color is ok for now. 
Fixed a layout issue where the _sidebar_ of the modal wasn't taking full height
=> style: add new offWhite color & fix layout issue

packages/frontend/src/features/metricsCatalog/components/MetricPeekDatePicker.tsx, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx
=> style: amend spacing and colors in date picker

packages/backend/src/controllers/metricsExplorerController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts, packages/common/src/types/metricsExplorer.ts, packages/common/src/utils/metricsExplorer.ts, packages/frontend/src/features/metricsCatalog/components/MetricPeekDatePicker.tsx, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/features/metricsCatalog/hooks/useDateRangePicker.tsx, packages/frontend/src/features/metricsCatalog/hooks/useRunMetricExplorerQuery.ts, packages/frontend/src/features/metricsCatalog/utils/metricPeekDate.tsx, packages/frontend/src/hooks/useExplorerRoute.ts
Closes: [#12650](https://github.com/lightdash/lightdash/issues/12650)
=> feat: metrics explorer filters

packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ColumnConfiguration.tsx
fixes copy on pivoted tables hidden dimensions
=> chore: fixes copy on pivoted tables

packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
Closes: N/A
- modal height responsiveness
- chart vis: spacing, hiding y axis label, some changes to the grid appearance, colors, and font sizes
=> style: apply responsiveness to modal height | vis styling

packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/CoderService/CoderService.ts, packages/backend/src/services/PromoteService/PromoteService.ts, packages/backend/src/services/ServiceRepository.ts, packages/cli/src/handlers/download.ts, packages/common/src/types/coder.ts
Closes: 
List of changes: 
- reusing promote logic on chart update
- log created/updated changes in CLI 
- do not update if not needed (CLI logic + promote logic) 
- bugfixes
=> fix: Promote chart as code

docs/docs/references/metrics.mdx
Adds .yml formatting example for metrics to reference docs.
=> docs: adds formatting yaml example for metrics

packages/backend/src/controllers/catalogController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/CatalogService/CatalogService.ts, packages/common/src/index.ts, packages/common/src/types/catalog.ts, packages/frontend/src/features/metricsCatalog/components/MetricTree/index.tsx, packages/frontend/src/features/metricsCatalog/hooks/useMetricsTree.tsx
Closes: #12641
⚠️ Based on: https://github.com/lightdash/lightdash/pull/12639
- Creates edges on connect
- Deletes edges on backspace
https://github.com/user-attachments/assets/45578ac8-f1f9-4d7e-bc92-c3405fdaa005
=> feat: metric trees frontend save edges

packages/frontend/src/components/RegisterForms/VerifyEmailForm.tsx, packages/frontend/src/components/UserSettings/ProfilePanel/index.tsx, packages/frontend/src/hooks/useEmailVerification.tsx, packages/frontend/src/pages/VerifyEmail.tsx
Closes: [#12678](https://github.com/lightdash/lightdash/issues/12678) 
Accessing page `/verify-email` without being authenticated would cause an infinite loop.
Replicate locally:
- make sure you are not authenticated
- access http://localhost:3000/verify-email
=> fix: check email status if user is authenticated

examples/full-jaffle-shop-demo/dbt/models/schema.yml, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/models/CatalogModel/CatalogModel.ts, packages/backend/src/scheduler/SchedulerTask.ts, packages/backend/src/services/CatalogService/CatalogService.ts, packages/backend/src/services/ProjectService/ProjectService.ts, packages/common/src/types/catalog.ts
Closes: [#12691](https://github.com/lightdash/lightdash/issues/12691)
https://github.com/user-attachments/assets/2b9680c5-f61a-40eb-8798-703d160e449a
=> feat: add best effort migration of edges

packages/backend/src/controllers/metricsExplorerController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts, packages/common/src/types/metricsExplorer.ts, packages/common/src/utils/metricsExplorer.ts, packages/frontend/src/features/metricsCatalog/components/ExploreMetricButton.tsx, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/types.ts, packages/frontend/src/features/metricsCatalog/components/visualization/useChartZoom.tsx, packages/frontend/src/features/metricsCatalog/hooks/useDateRangePicker.tsx, packages/frontend/src/features/metricsCatalog/hooks/useRunMetricExplorerQuery.ts, packages/frontend/src/features/metricsCatalog/utils/metricPeekDate.tsx, packages/frontend/src/hooks/useExplorerRoute.ts
=> feat: metrics explorer filter improvements

packages/backend/src/controllers/metricsExplorerController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts, packages/common/src/types/metricsExplorer.ts, packages/common/src/utils/metricsExplorer.ts, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx, packages/frontend/src/features/metricsCatalog/hooks/useRunMetricExplorerQuery.ts
=> feat: metric explorer compare with other metric - part 1

package.json, packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx, packages/frontend/src/components/Explorer/ExplorePanel/index.tsx, packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx, packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx, packages/frontend/src/pages/CreateProject.tsx, yarn.lock
Closes: N/A
Upgrades prettier to `2.8.1` so that we can use typescript's `satisfies` without format issues
Reference: https://github.com/prettier/prettier/issues/13516
=> chore: upgrade prettier to 2.8.1

packages/backend/src/services/CatalogService/CatalogService.ts, packages/common/src/authorization/organizationMemberAbility.ts, packages/common/src/authorization/projectMemberAbility.ts, packages/common/src/authorization/types.ts
Closes: #12690 
Requirements: Editors and above will be able to edit the canvas
=> feat: add permission checks and validation for trees backend

packages/frontend/src/features/metricsCatalog/components/MetricTree/MetricTreeConnectedNode.tsx, packages/frontend/src/features/metricsCatalog/components/MetricTree/MetricTreeUnconnectedNode.tsx, packages/frontend/src/features/metricsCatalog/components/MetricTree/index.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx, packages/frontend/src/features/metricsCatalog/store/metricsCatalogSlice.ts
Closes: #12692 
- Adds view mode when user doesn't have permission to change the tree
https://github.com/user-attachments/assets/c419c306-96da-4573-a28d-3befda61f4fd
=> feat: add view mode

packages/backend/src/controllers/catalogController.ts, packages/backend/src/controllers/metricsExplorerController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/models/CatalogModel/CatalogModel.ts, packages/backend/src/services/CatalogService/CatalogService.ts, packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts, packages/common/src/types/catalog.ts, packages/common/src/types/metricsExplorer.ts, packages/common/src/utils/metricsExplorer.ts, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx, packages/frontend/src/features/metricsCatalog/hooks/useCatalogMetricsWithTimeDimensions.ts, packages/frontend/src/features/metricsCatalog/hooks/useRunMetricExplorerQuery.ts
=> feat: metrics explorer compare with other metric part 2

packages/backend/src/scheduler/SchedulerWorker.ts
Closes: #12753 
- Increases attempts to 3
- Logs all graphile errors by default as `error` level so we can see the stack
=> chore: add explicit error for generateDailyJobs and increate attempts

packages/common/src/utils/metricsExplorer.ts, packages/frontend/src/features/metricsCatalog/components/MetricPeekDatePicker.tsx, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/TimeDimensionIntervalPicker.tsx, packages/frontend/src/features/metricsCatalog/hooks/useDateRangePicker.tsx, packages/frontend/src/features/metricsCatalog/hooks/useRunMetricExplorerQuery.ts, packages/frontend/src/features/metricsCatalog/utils/metricPeekDate.tsx
Closes: [#12717](https://github.com/lightdash/lightdash/issues/12717)
- date filter is a segmented control
- presets reference a main util to get the default date range for an interval/granularity
- all controls are above the viz
https://github.com/user-attachments/assets/430e98fc-b799-4489-af61-8daa1647de67
=> feat: change layout of date picker, granularity and data zoom

packages/frontend/src/features/metricsCatalog/components/MetricPeekDatePicker.tsx, packages/frontend/src/features/metricsCatalog/hooks/useDateRangePicker.tsx
Closes: #12755
**DAY**
**WEEKLY**
**MONTHLY**
**YEARLY**
=> style: amend pickers' styles

packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
=> style: make metrics explorer visualization straight lines

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx
Closes: [#12771](https://github.com/lightdash/lightdash/issues/12771)
=> chore: add alpha badge next to metrics catalog header

packages/backend/src/config/parseConfig.ts, packages/backend/src/routers/projectRouter.ts, packages/backend/src/services/HealthService/HealthService.mock.ts, packages/backend/src/services/HealthService/HealthService.ts, packages/backend/src/services/ProjectService/ProjectService.ts, packages/common/src/index.ts, packages/common/src/types/fieldMatch.ts, packages/frontend/src/components/common/Filters/FilterInputs/FilterStringAutoComplete.tsx, packages/frontend/src/hooks/useFieldValues.ts, packages/frontend/src/testing/__mocks__/api/healthResponse.mock.ts
Closes:  https://github.com/lightdash/lightdash/issues/10514
[Screencast from 2024-12-09 13-21-55.webm](https://github.com/user-attachments/assets/8ee4c493-8e44-443f-ba61-f1e2b60759a4)
=> feat: cache results in filters

packages/backend/src/controllers/metricsExplorerController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts, packages/common/src/types/metricsExplorer.ts, packages/common/src/utils/metricsExplorer.ts, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/useChartZoom.tsx, packages/frontend/src/features/metricsCatalog/hooks/useRunMetricExplorerQuery.ts, packages/frontend/src/features/metricsCatalog/utils/metricPeekDate.tsx
Closes: https://github.com/lightdash/lightdash/issues/12760
=> chore: metrics explore visualization results in the backend

packages/frontend/src/features/metricsCatalog/hooks/useDateRangePicker.tsx
=> style: border style on hover of this month selected

packages/backend/src/controllers/metricsExplorerController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts, packages/common/src/index.ts, packages/common/src/types/metricsExplorer.ts, packages/common/src/utils/metricsExplorer.ts, packages/frontend/src/features/metricsCatalog/components/MetricTree/MetricTreeConnectedNode.tsx, packages/frontend/src/features/metricsCatalog/components/MetricTree/MetricTreeUnconnectedNode.tsx, packages/frontend/src/features/metricsCatalog/components/MetricTree/index.tsx, packages/frontend/src/features/metricsCatalog/hooks/useRunMetricExplorerQuery.ts, packages/frontend/src/hooks/useBigNumberConfig.ts
Closes: #12693 
- Adds new endpoint to fetch metric big number value
=> feat: fetch big number data for metrics tree

packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
=> style: update legends, axes and tooltips

packages/frontend/src/features/metricsCatalog/components/MetricPeekComparison.tsx, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/TimeDimensionIntervalPicker.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/TimeDimensionPicker.tsx, packages/frontend/src/features/metricsCatalog/styles/useSelectStyles.ts
=> style: update overall metrics explorer's styles

packages/backend/src/models/SearchModel/utils/search.ts, packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
Closes: #12712
- Fixes searching by label and metric name
**Before**
**After**
Special characters in search queries are ignored by full text search (vectors don't include those) but when using reserved characters part of the FTS syntax it would error, this fixes the error
**Before**
**After**
=> fix: set filtering to manual since it is performed on the backend

packages/frontend/src/features/metricsCatalog/components/ExploreMetricButton.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar.tsx
Relates to: #12719
Just on metrics catalog
=> feat: revise metrics catalog tooltips

packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts, packages/common/src/types/metricsExplorer.ts, packages/common/src/utils/metricsExplorer.ts, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
Closes: N/A
none
previous period
another metric
> [!NOTE]
> Designs reviewing by @PriPatel already
=> style: show labels on chart tooltip

packages/frontend/src/features/metricsCatalog/components/MetricPeekComparison.tsx, packages/frontend/src/features/metricsCatalog/components/MetricPeekDatePicker.tsx, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsVisualizationEmptyState.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
Closes: [#12719](https://github.com/lightdash/lightdash/issues/12719)
Only on metrics explorer
=> chore: review metrics explorer tooltips

packages/backend/src/controllers/catalogController.ts, packages/backend/src/controllers/metricsExplorerController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/CatalogService/CatalogService.ts, packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts, packages/common/src/types/catalog.ts, packages/common/src/types/metricsExplorer.ts, packages/common/src/utils/metricsExplorer.ts, packages/frontend/src/features/metricsCatalog/components/MetricPeekComparison.tsx, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx, packages/frontend/src/features/metricsCatalog/hooks/useCatalogSegmentDimensions.ts, packages/frontend/src/features/metricsCatalog/hooks/useRunMetricExplorerQuery.ts, packages/frontend/src/hooks/useExplorerRoute.ts
=> feat: metrics explorer segment by

packages/backend/src/services/CatalogService/CatalogService.ts, packages/frontend/src/features/metricsCatalog/components/MetricPeekComparison.tsx, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx
=> fix: metrics explorer available metrics query

packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
Closes: [#12843](https://github.com/lightdash/lightdash/issues/12843)
=> feat: metrics explorer visualization colors

packages/backend/src/services/CatalogService/CatalogService.ts, packages/common/src/utils/metricsExplorer.ts
Closes: [#12840](https://github.com/lightdash/lightdash/issues/12840)
=> fix: metrics explorer filter segment dimension

packages/backend/src/config/lightdashConfig.mock.ts, packages/backend/src/config/parseConfig.ts, packages/backend/src/services/HealthService/HealthService.ts, packages/backend/src/services/ProjectService/ProjectService.ts, packages/frontend/src/components/common/Filters/FilterInputs/FilterStringAutoComplete.tsx
Closes:  https://github.com/lightdash/lightdash/issues/12789
- cache entire hashed query, this includes user attributes (if any) . Note, this is secure, but less efficient,s ince we need to get all metadata from explore and metricquery to compute the query to get the cache key to know if it is cached or not;
- use s3cacheClient to store results in s3, rather than in memory
- change in env variables  
Same UI: 
[Screencast from 2024-12-11 10-04-29.webm](https://github.com/user-attachments/assets/fdbf3eaa-9837-4844-8755-db19237d5651)
=> fix: improve backend autocomplete

packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts, packages/common/src/types/metricsExplorer.ts, packages/common/src/utils/metricsExplorer.ts, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx
Closes: [#12836](https://github.com/lightdash/lightdash/issues/12836)
=> feat: metrics explorer segment by max 10 series

packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/useChartZoom.tsx
Closes: [#12845](https://github.com/lightdash/lightdash/issues/12845)
I preserved the code and usecase
=> fix: metrics explorer disable data zoom

packages/backend/src/services/UserService.ts
Closes: 
- Adds logging to `loginWithOpenId` within `userService`. Will assist in an investigation with some OIDC requests failing
=> chore: added logging within loginWithOpenId()

packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/common/src/types/metricsExplorer.ts, packages/common/src/utils/metricsExplorer.ts, packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx, packages/frontend/src/features/metricsCatalog/hooks/useDynamicYAxisWidth.tsx, packages/frontend/src/features/metricsCatalog/hooks/useRunMetricExplorerQuery.ts
Closes: #12742 
- Fixes tooltip props type
- Adds formatted value to response
- Adds y axis tick format depending on value
=> chore: add formatted value and fix tooltip types

packages/frontend/src/components/NavBar/BrowseMenu.tsx, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/providers/TrackingProvider.tsx, packages/frontend/src/types/Events.ts
=> chore: add analytics events

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx
Closes: #12884 
- Updates the state if the project uuid or organization uuid have changed
=> fix: check if projectUuid in state is different from current projectUuid in the params

packages/backend/src/services/CoderService/CoderService.ts, packages/backend/src/services/PromoteService/PromoteService.ts
Closes: https://github.com/lightdash/lightdash/issues/12880
New space slugs can be used when creating new charts/dashboards or when updating
=> fix: space change on promote content

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumnName.tsx, packages/frontend/src/hooks/useExplorerRoute.ts
Closes: [#12886](https://github.com/lightdash/lightdash/issues/12886)
- Deletes the code for opening the old explore on metric name click, not sure if we will bring it back at some point
=> chore: disable opening old explore on metric name click (temp)

packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
Closes: [#12867](https://github.com/lightdash/lightdash/issues/12867)
functionality has been approved by Pri
=> feat: metrics explorer interactive legends

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumnName.tsx
Closes: [#12909](https://github.com/lightdash/lightdash/issues/12909)
=> fix: re-add css import to override emoji picker style

packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
Closes: #12908 
https://github.com/user-attachments/assets/ba0104e1-02a3-4354-aeaa-e9570f682d69
=> fix: hovering on the right side of datapoint not showing correct segments in tooltip

packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx
Closes: #12890 
https://github.com/user-attachments/assets/86ba685d-b82c-41c9-9fd4-c8a0c8c9aca1
=> chore: show error when no dims to segment by

packages/frontend/src/features/metricsCatalog/components/MetricPeekDatePicker.tsx, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/providers/TrackingProvider.tsx
=> chore: track change of date filter only on user action

packages/frontend/src/features/metricsCatalog/components/MetricPeekComparison.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
=> chore: copy link changes metrics explorer

packages/e2e/cypress/e2e/app/space.cy.ts, packages/frontend/src/components/common/ResourceIcon/index.tsx, packages/frontend/src/components/common/ResourceView/ContentTypeMultiSelect.tsx, packages/frontend/src/components/common/ResourceView/InfiniteResourceTable.tsx, packages/frontend/src/pages/SavedDashboards.tsx, packages/frontend/src/pages/SavedQueries.tsx, packages/frontend/src/pages/Space.tsx
Closes: 
Changes:
- update table and page styles
- allow to click on row
- add multi select when table has multiple types
- refactor dashboards and space page to use the new table
=> feat: space and dashboard page new table

packages/frontend/src/pages/Space.tsx
Closes: https://github.com/lightdash/lightdash/issues/12928
Before:
After:
=> fix: space content filtered by space uuid

packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
=> fix: y axis scale on metrics catalog

packages/frontend/src/components/common/ResourceView/ContentTypeMultiSelect.tsx
Closes: 
Fix typo to fix missing color in multi select
=> chore: content type multiselect color typo

packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
Closes: #12933 
**Before**
https://github.com/user-attachments/assets/7ee5a0cd-4e97-46f2-a62a-f48bf23e3f5b
**After**
https://github.com/user-attachments/assets/05786401-3a22-4420-a34c-553e630e8240
=> chore: fix overflow of x-axis label

packages/cli/src/analytics/analytics.ts, packages/cli/src/config.ts, packages/cli/src/handlers/download.ts, packages/cli/src/handlers/login.ts
Closes:  https://github.com/lightdash/lightdash/issues/12855
individual chart error
=> chore: content as code analytics

packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx
Closes: 
navigate up and down to navigate between metrics
=> feat: allow keyboard shortcuts to navigate to other metrics

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx, packages/frontend/src/components/UserSettings/GithubSettingsPanel/index.tsx, packages/frontend/src/features/sqlRunner/components/Header/HeaderCreate.tsx, packages/frontend/src/features/virtualView/components/CreateVirtualViewModal.tsx, packages/frontend/src/hooks/gitIntegration/useGitIntegration.ts
Closes: [#12744](https://github.com/lightdash/lightdash/issues/12744)
Changes:
- extract endpoint hook that knows if git integration is enabled
- replace hook in SQL runner
- enable github integration ( find dev github app secrets )
- go to org settings -> integrations -> install github -> on success manually change URL from dev proxy to `http://localhost:3000` 
- change the seeded project to connect to a github repo rather than local files
- add member to org
- make member a project developer
- login as new member -> go to SQL runner
create virtual view info label:
write back to dbt available
=> fix: org member & project developer write back to dbt

packages/common/src/utils/metricsExplorer.ts, packages/frontend/src/features/metricsCatalog/utils/metricPeekDate.tsx
Closes: #12937 
- Changes month default to be 3M
- Changes year default to be "this year"
- Adjusts defaults to match the descriptions in the comments above the code
=> chore: spotlight default date ranges

packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreLegend.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreTooltip.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
Closes: N/A
Was getting harder to manage the tooltip component - clarified a few things, added some variants of tooltips depending on the comparison, and documented small utils.
=> refactor: metric explorer tooltip component

packages/cli/src/handlers/download.ts
=> fix: throw warning if folder does not exist , chart as code

packages/frontend/src/features/metricsCatalog/components/MetricPeekComparison.tsx, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/features/metricsCatalog/components/SelectItem.tsx, packages/frontend/src/features/metricsCatalog/styles/useSelectStyles.ts
Closes: #12946 
- When metric/dimension name is big:
https://github.com/user-attachments/assets/fa02ac95-7516-4257-b2cf-ea70ac974ac0
=> chore: make segment by and metric select searchable

packages/backend/src/models/FeatureFlagModel/FeatureFlagModel.ts, packages/backend/src/models/ModelRepository.ts, packages/frontend/src/hooks/useFeatureFlagEnabled.ts
Closes: 
Improves devx and extend feature flag usage.
=> chore: feature flag extendability

packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/MetricPeekComparison.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/MetricPeekDatePicker.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/MetricPeekSegmentationPicker.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
Closes: N/A
Move some components around
ℹ️ Open to changes on naming, structure, etc
=> refactor: move peek-related components to vis folder

.github/workflows/cli-tests.yml, dockerfile, dockerfile-prs, packages/backend/src/dbt/dbtCliClient.ts, packages/cli/src/dbt/manifest.ts, packages/cli/src/handlers/compile.ts, packages/cli/src/handlers/dbt/getDbtVersion.ts, packages/common/src/types/projects.ts
Closes:  https://github.com/lightdash/lightdash/issues/12207
Before:
After:
=> feat: support dbt 1.9

packages/backend/src/services/ProjectService/ProjectService.ts
Relates to: #12958, #12981 
Wraps format rows to measure duration
test-frontend
test-backend
=> chore: wrap format rows to measure duration

packages/warehouses/package.json, packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts, yarn.lock
Closes: 
test-frontend
test-backend
test-cli
log:
ui:
=> fix: postgres+redshift query default timeout

packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts, packages/backend/src/services/ProjectService/ProjectService.ts
Reverts lightdash/lightdash#12995
=> chore: revert "chore: force avoid worker when formatting for metrics catalog"

packages/frontend/src/components/DashboardTabs/DeleteTabModal.tsx, packages/frontend/src/components/Explorer/SpaceBrowser/AddResourceToSpaceModal.tsx
I found two errors and fixed them.
=> chore: fix typos in modals

packages/frontend/src/components/ReactHookForm/Form.tsx
Remove deprecated `defaultProps`. I checked the codebase, this is the last one of these.
=> chore: remove deprecated defaultProps

packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/common/src/types/projects.ts, packages/frontend/src/components/ProjectConnection/WarehouseForms/PostgresForm.tsx, packages/frontend/src/components/ProjectConnection/WarehouseForms/RedshiftForm.tsx, packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
related to: [#12965](https://github.com/lightdash/lightdash/issues/12965)
=> feat: warehouses postgres+redshift timeout in the ui settings

packages/backend/src/services/SavedSqlService/SavedSqlService.ts
Related to: [#13005](https://github.com/lightdash/lightdash/issues/13005)
Enforce saved chart SQL and limit when pivoting results instead of the values in the request body.
We need a bigger refactor to stop passing the SQL and request the unpivoted results in the FE.
Original request selecting everything from orders
Modified request select everything from customers.
=> fix: pivot results sql

packages/frontend/src/features/sqlRunner/components/SaveSqlChartModal.tsx
Fix an error from setting at text area value to null
=> fix: null error in SQL runner save dialog

packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/UsersView.tsx
Closes: #13003 
https://github.com/user-attachments/assets/af857a50-97d0-4292-8ba7-cdf400193641
=> fix: use loading inside table

packages/backend/src/App.ts, packages/backend/src/backendApp.ts, packages/backend/src/index.ts
Relates to: https://github.com/lightdash/lightdash-internal-work/issues/2343
- Instantiates the app on a separate file and exports it so it can be imported, see related issue
- Adds getters to services, models and database
=> chore: export app instance

packages/frontend/src/features/metricsCatalog/components/MetricTree/MetricTreeConnectedNode.tsx, packages/frontend/src/features/metricsCatalog/components/MetricTree/MetricTreeUnconnectedNode.tsx, packages/frontend/src/features/metricsCatalog/components/MetricTree/index.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar.tsx, packages/frontend/src/features/metricsCatalog/store/metricsCatalogSlice.ts
Closes: #12815
Refetch when going from tree -> list view (refetch will use previous data/cached)
Handle view change in slice
Small style changes 
https://github.com/user-attachments/assets/34e55559-65fd-411e-be29-a3d4ccfc421e
=> fix: refetch when tree to list view and style changes

packages/e2e/cypress/e2e/app/dashboard.cy.ts, packages/frontend/package.json, packages/frontend/src/App.tsx, packages/frontend/src/Routes.tsx, packages/frontend/src/hooks/dashboard/useDashboardStorage.ts, yarn.lock
Relate to: [#13014](https://github.com/lightdash/lightdash/issues/13014)
There is going to be a series of PRs as the migration is quite big and likely to break.
First one adds backwards compatibility between v5 and v6 and tackes points 1 & 2  in https://github.com/remix-run/react-router/discussions/8753
=> chore: react router v6 part1

packages/frontend/src/App.tsx, packages/frontend/src/MobileRoutes.tsx, packages/frontend/src/Routes.tsx, packages/frontend/src/components/AppRoute.tsx, packages/frontend/src/components/Explorer/CustomMetricModal/hooks/useDataForFiltersProvider.ts, packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx, packages/frontend/src/components/NavBar/ProjectSwitcher.tsx, packages/frontend/src/components/NavBar/UserCredentialsSwitcher.tsx, packages/frontend/src/components/PrivateRoute.tsx, packages/frontend/src/components/ProjectRoute.tsx, packages/frontend/src/features/comments/hooks/useScrollToDashboardCommentViaSearchParam.ts, packages/frontend/src/hooks/dashboard/useDashboard.ts, packages/frontend/src/hooks/useActiveProject.ts, packages/frontend/src/hooks/useCalculateTotal.ts, packages/frontend/src/hooks/useExplorerRoute.ts, packages/frontend/src/hooks/useProjectCatalog.ts, packages/frontend/src/hooks/useSavedQuery.ts, packages/frontend/src/hooks/useSearchParams.ts, packages/frontend/src/hooks/useSqlQuery.ts, packages/frontend/src/hooks/useSqlRunnerRoute.ts, packages/frontend/src/pages/Dashboard.tsx, packages/frontend/src/pages/MobileHome.tsx, packages/frontend/src/pages/ProjectSettings.tsx, packages/frontend/src/pages/SemanticViewerEdit.tsx, packages/frontend/src/pages/Settings.tsx, yarn.lock
Closes: [#13014](https://github.com/lightdash/lightdash/issues/13014)
Changes:
- refactor route elements to route objects  (App.tsx, Routes.tsx, MobileRoutes.tsx, Settings.tsx, ProjectSettings.tsx)
- refactor navigation blocker in chart/dashboard pages
- move remaining v5 imports to the compatibility lib
=> chore: react router v6

packages/frontend/src/components/SettingsValidator/index.tsx
=> fix: add loader on validator page

packages/frontend/src/components/common/LightTable/styles.ts, packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
Closes: https://github.com/lightdash/lightdash/issues/12602
Non pivot table 
Before:
After:
=> fix: fix hover style pivot table

packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx
Closes: #13058 
**Before**
https://github.com/user-attachments/assets/fe9303e9-92dd-4875-9e9b-cb50544ae8bb
**After**
https://github.com/user-attachments/assets/897dacf2-6a19-4788-983a-4769cab27d88
=> fix: remove duplicate loading overlay

packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx
=> style: add keyboard shortcut on hover

packages/backend/src/clients/Slack/SlackClient.ts, packages/backend/src/scheduler/SchedulerTask.ts
Closes:  https://github.com/lightdash/lightdash/issues/13076
=> feat: upload images to slack on scheduled deliveries

packages/frontend/src/features/metricsCatalog/components/MetricCatalogCategoryFormItem.tsx
Relates to: #13099 
**Before**
**After**
=> fix: removes width from transparent category button so there's no horizontal scroll bar

packages/common/src/types/dashboard.ts, packages/frontend/src/MobileRoutes.tsx, packages/frontend/src/components/MinimalDashboardTabs/index.tsx, packages/frontend/src/pages/MinimalDashboard.tsx
Closes: #12380 
Added dashboard tabs on mobile view
Recording uploaded here: https://github.com/lightdash/lightdash/issues/12380#issuecomment-2571421564
=> feat: add dashboard tabs on mobile

packages/backend/src/scheduler/SchedulerClient.ts, packages/backend/src/scheduler/SchedulerTask.ts, packages/backend/src/services/DashboardService/DashboardService.ts, packages/backend/src/services/SavedChartsService/SavedChartService.ts, packages/backend/src/services/SchedulerService/SchedulerService.ts, packages/common/src/utils/scheduler.ts, packages/frontend/src/features/scheduler/components/SchedulerForm.tsx
Closes: https://github.com/lightdash/lightdash/issues/13117
=> fix: scheduler empty string timezones

packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx
Closes: https://github.com/lightdash/lightdash/issues/12114
=> fix: missing field name does not truncate

packages/cli/src/handlers/generate.ts, packages/cli/src/index.ts
Closes: #13038
No skipping:
skipping:
=> feat: skip existing generate cli

packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/useChartZoom.tsx
Closes: #13054 
- Re-enables and fixes drag to zoom
https://github.com/user-attachments/assets/18cdf34e-06ba-4b74-8e4e-4deecb907687
=> feat: metrics explorer chart zoom

packages/frontend/src/features/sync/components/SyncModalForm.tsx
=> fix: google sheets sync timezone empty string

packages/frontend/src/features/metricsCatalog/components/MetricTree/index.tsx, packages/frontend/src/features/metricsCatalog/hooks/useTreeNodePosition.tsx
Closes: #13051 
**Before**
https://github.com/user-attachments/assets/301e2bf6-e7c2-4837-82e1-5632eb06424a
**After**
https://github.com/user-attachments/assets/8f1c69eb-66d7-4999-becb-4319df7b2676
=> feat: show expanded node when dragging out

packages/frontend/src/features/sync/components/SyncModalForm.tsx
=> fix: google sheets sync form bug

.github/workflows/_setup_node_pnpm_cypress/action.yml, .github/workflows/release-on-merge.yml, .github/workflows/test-and-build.yml, dockerfile, dockerfile-prs, package.json
Closes: 
test-cli
test-frontend
=> chore: add pnpm package manager to package.json

packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts, packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx, packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreFilter.tsx, packages/frontend/src/features/metricsCatalog/styles/useFilterStyles.ts, packages/frontend/src/features/metricsCatalog/utils/metricExploreFilter.tsx
Closes: https://github.com/lightdash/lightdash/issues/12962
Moves some logic/utils to its own file
Enables filtering by boolean
Ensures that layout is different between dimension types
demo
https://github.com/user-attachments/assets/4514651c-4d94-4c41-b8e7-7fbf42b3608e
=> feat: allow filtering by boolean dim in metrics explorer

.github/workflows/release-on-merge.yml, release.config.js
=> fix: release workflow pnpm workspaces

release.config.js
=> fix: release workflow pnpm workspaces file order

.github/workflows/release-on-merge.yml, release.config.mjs
=> fix: release action

.github/workflows/release-on-merge.yml, release.config.mjs
=> fix: release workflow npm audit

packages/backend/src/services/CoderService/CoderService.ts, packages/common/src/types/coder.ts
Closes:  https://github.com/lightdash/lightdash/issues/13187
Functionality was already there, but the type was not correctly supported.
=> fix: support markdown updates dashboard as code

packages/frontend/src/features/metricsCatalog/components/MetricTree/MetricTreeConnectedNode.tsx
Closes: #13041 
Adds spinner while waiting for result
=> chore: add loader when waiting for total query

packages/backend/src/database/entities/catalog.ts, packages/backend/src/database/migrations/20250110160817_add_label_to_search_vector.ts, packages/backend/src/models/CatalogModel/CatalogModel.ts, packages/backend/src/models/CatalogModel/utils/index.ts, packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx
Closes: https://github.com/lightdash/lightdash/issues/13191
- adds label to the search 
- allows sorting by label (it was being sorted by name previously)
- updates search_vector include label, with same weight as name
=> fix: store label in catalog search to be searchable

packages/frontend/src/components/Home/LandingPanel/index.tsx, packages/frontend/src/providers/Tracking/types.ts, packages/frontend/src/types/Events.ts
=> chore: track home page run query click

packages/frontend/src/components/common/Filters/FilterInputs/BooleanFilterInputs.tsx, packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx, packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
Closes: 
Fixes: #12291 
[Screencast from 10-01-25 05:51:23 AM IST.webm](https://github.com/user-attachments/assets/e2b31ba4-85bf-4687-9e8e-6aa34ddc6f56)
=> fix: auto-focus filter value input

packages/cli/src/handlers/dbt/getWarehouseClient.ts
Closes: #13219
1. install dbt cloud cli
```
python -m venv dbt-cloud
source dbt-cloud/bin/activate
pip install --upgrade pip
pip install dbt
dbt --version
deactivate
source dbt-cloud/bin/activate
```
2. create new user+org
3. follow CLI steps to create project. eg:
```
node ../../../packages/cli/dist/index.js login http://localhost:3000/ --token 1234-abcd
node ../../../packages/cli/dist/index.js deploy --create
```
Before:
After:
=> fix: create first project using dbt cloud cli

packages/common/src/types/resourceViewItem.ts, packages/frontend/src/components/common/ResourceView/InfiniteResourceTable.tsx, packages/frontend/src/hooks/useContent.ts, packages/frontend/src/pages/Space.tsx, yarn.lock
Closes: [#13148](https://github.com/lightdash/lightdash/issues/13148)
=> fix: dashboard content appearing blank

yarn.lock
=> chore: out of sync yarn lock

packages/cli/src/handlers/download.ts, packages/cli/src/index.ts
=> feat(cli): support argument `--project` on lightdash download/upload.

packages/backend/src/App.ts, packages/backend/src/SchedulerApp.ts, packages/backend/src/database/migrations/20250113135824_redact-graphile-job-data.ts, packages/backend/src/scheduler/SchedulerTask.ts, packages/backend/src/services/CsvService/CsvService.test.ts, packages/backend/src/services/ProjectService/ProjectService.test.ts, packages/backend/src/services/ProjectService/ProjectService.ts, packages/backend/src/services/ServiceRepository.ts, packages/common/src/types/scheduler.ts
Closes: 
Update schedule job data that creates a project + test & compile.
=> fix: create project with compile

packages/frontend/src/features/metricsCatalog/components/MetricTree/MetricTreeCollapsedNode.tsx, packages/frontend/src/features/metricsCatalog/components/MetricTree/MetricTreeExpandedNode.tsx
=> chore: add table to info tooltip

packages/frontend/src/features/metricsCatalog/components/MetricTree/index.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar/CategoriesFilter.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar/SegmentedControlHoverCard.tsx, packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar/index.tsx, packages/frontend/src/mantineTheme.ts
Closes: #13241 
- Adds new tooltip to segmented control
- Adds title to canvas
=> chore: canvas header updates

packages/backend/src/@types/rudder-sdk-node.d.ts, packages/backend/src/analytics/LightdashAnalytics.ts
Closes: 
I forgot to update our custom type for rudderstack, I'm surprised it didn't fail 
test-cli test-frontend test-backend
=> fix: fix rudderstack custom type

packages/frontend/src/features/metricsCatalog/components/MetricTree/MetricTreeCollapsedNode.tsx, packages/frontend/src/features/metricsCatalog/components/MetricTree/MetricTreeDefaultEdge.tsx, packages/frontend/src/features/metricsCatalog/components/MetricTree/MetricTreeExpandedNode.tsx, packages/frontend/src/features/metricsCatalog/components/MetricTree/index.tsx, packages/frontend/src/features/metricsCatalog/styles/useChangeIndicatorStyles.ts
Closes: #13248 
Updates collapsed/expanded node styles + edge
=> chore: canvas node UI changes

packages/backend/src/services/UserAttributesService/UserAttributeUtil.mocks.ts
Closes: 
Added strict undefined check for userAttributeUtil
Goal: Enable noUncheckedIndexedAccess  all over backend.
=> fix: --noUncheckedIndexedAccess on userAttributeUtil

packages/backend/src/services/ValidationService/ValidationService.mock.ts, packages/backend/src/services/ValidationService/ValidationService.test.ts, packages/common/src/types/explore.ts
Closes: 
Added strict `undefined` check for validationService
Goal: Enable `noUncheckedIndexedAccess ` all over backend.
=> fix: --noUncheckedIndexedAccess on validationService

packages/backend/src/projectAdapters/dbtNoneCredentialsProjectAdapter.ts, packages/backend/src/scheduler/SchedulerTask.ts, packages/backend/src/services/CsvService/CsvService.ts, packages/backend/src/services/ProjectService/ProjectService.ts
=> Feat: Added explore_name to query metadata

packages/frontend/src/components/DashboardTiles/TileBase/TileBase.styles.tsx, packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
Closes: 
Fixes #13143 
Before:
[Screencast from 09-01-25 01:23:34 PM IST.webm](https://github.com/user-attachments/assets/37e4c26e-97fd-4b80-a9a8-0be3081ca4ff)
After:
[Screencast from 09-01-25 01:22:26 PM IST.webm](https://github.com/user-attachments/assets/790e1020-4772-4319-828a-0aa858ee4a7b)
=> fix: title move position

packages/common/src/types/featureFlags.ts, packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar/index.tsx
Closes: [#2697](https://github.com/lightdash/lightdash-internal-work/issues/2697)
- Removes metric-trees feature flag
=> chore: remove metric-trees feature flag

packages/backend/src/dbt/DbtMetadataApiClient.ts
Closes: [#13201](https://github.com/lightdash/lightdash/issues/13201)
Reproduce locally:
1. enable flag 'show-dbt-cloud-project-option'
2. change page size to 50 https://github.com/lightdash/lightdash/blob/10e2edf0676ce38255f6413c1d36780d954a1052/packages/backend/src/dbt/DbtMetadataApiClient.ts#L22
3. add a console log in `getModels` to see it making multiple requests
4. connect to dbt cloud (reach out to me for credentials)
=> fix: get all models from dbt cloud api

CHANGELOG.md, package.json, packages/backend/package.json, packages/cli/package.json, packages/common/package.json, packages/e2e/package.json, packages/frontend/package.json, packages/warehouses/package.json
=> fix: release pipeline

packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreComparison.tsx
Relates to first checkbox in: #13209
Demo
=> style: apply same padding to comparison box

packages/backend/src/controllers/catalogController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/models/CatalogModel/CatalogModel.ts, packages/backend/src/services/CatalogService/CatalogService.ts, packages/frontend/src/components/NavBar/BrowseMenu.tsx, packages/frontend/src/components/NavBar/MainNavBarContent.tsx, packages/frontend/src/components/NavBar/MetricsLink.tsx, packages/frontend/src/features/metricsCatalog/hooks/useMetricsCatalog.tsx
Closes: https://github.com/lightdash/lightdash/issues/13279
Ignore my comment on the issue and just focus on the main ticket's AC
when no metrics
when metrics
=> feat: render metrics link depending on metrics count

packages/frontend/src/components/AboutFooter.tsx, packages/frontend/src/components/common/Page/Page.tsx
Closes: https://github.com/lightdash/lightdash/issues/13233
before:
after:
=> fix: sidebar and fixed page scrollbars

packages/backend/src/models/CatalogModel/CatalogModel.ts, packages/common/src/types/catalog.ts, packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar/CategoriesFilter.tsx
Closes: #13161
Demo:
https://github.com/user-attachments/assets/7c17768c-8dcd-4c89-88fd-a39c750f43fa
=> feat: allow filtering by uncategorized items

.github/workflows/release-on-merge.yml, package.json, packages/cli/package.json, packages/common/package.json, packages/warehouses/package.json, release.config.js
=> fix: pnpm release

.github/workflows/release-on-merge.yml, release.config.js
=> fix: pnpm release 2

.github/workflows/release-on-merge.yml
=> fix: NODE_AUTH_TOKEN for PNPM

.github/workflows/release-on-merge.yml, release.config.js
=> fix: pnpm auth token

packages/backend/src/controllers/catalogController.ts
Closes: N/A
On metric trees/canvas changes
=> chore: unauthorize metric tree changes in demo

packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
Closes:  https://github.com/lightdash/lightdash/issues/13328
Before:
After:
:+1:
=> fix: invalid tag bigquery

packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
Closes:  https://github.com/lightdash/lightdash/issues/13328
Before:
AFter:
:+1:
=> fix: long querytag biquery

packages/frontend/src/hooks/useColumns.tsx
Closes: [#13308](https://github.com/lightdash/lightdash/issues/13308)
Before:
Fix:
=> fix: results table warning for unfetched columns

packages/backend/src/dbt/dbtCliClient.test.ts, packages/backend/src/dbt/dbtCliClient.ts
Closes: 
Support select `*` and `@` 
https://docs.getdbt.com/reference/node-selection/yaml-selectors#cli-style
=> fix: support dbt selectors * and @

packages/backend/src/models/ProjectModel/ProjectModel.ts, packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts, packages/backend/src/services/ProjectService/ProjectService.ts
Closes: 
Deploying a project with no models would not expose the error message.
Before:
After:
=> fix: show error when no models are found

packages/backend/src/services/ProjectService/ProjectService.ts
Closes:  https://github.com/lightdash/lightdash-internal-work/issues/2730
Before:
AFter:
=> fix: add logs to failed warehouse queries

packages/backend/src/clients/Slack/SlackMessageBlocks.ts, packages/backend/src/scheduler/SchedulerTask.ts
Closes:  https://github.com/lightdash/lightdash/issues/13242
Gsyncs
Deliveries:
=> feat: error delivery add link

packages/frontend/src/components/Explorer/FormatForm/index.tsx, packages/frontend/src/components/Explorer/FormatModal/index.tsx, packages/frontend/src/components/Explorer/ResultsCard/FormatMenuOptions.tsx, packages/frontend/src/features/tableCalculation/components/TableCalculationModal.tsx
Closes: https://github.com/lightdash/lightdash/issues/13316
https://github.com/user-attachments/assets/ca8ab226-d1e4-42ec-b496-b72f1c6f2a11
=> feat: field custom formatting improvements

packages/backend/src/models/ProjectModel/ProjectModel.ts, packages/backend/src/services/CatalogService/CatalogService.ts, packages/backend/src/services/ProjectService/ProjectService.test.ts, packages/backend/src/services/ProjectService/ProjectService.ts, packages/backend/src/services/ValidationService/ValidationService.test.ts, packages/backend/src/services/ValidationService/ValidationService.ts
Closes: #10384 
This PR provides a partial fix for issue #10384
Changes in this PR include:
- refactor getExploreFromCache, findExploreByTableName, getExploresFromCache
=> chore: fix legacy methods

packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
=> fix: max update depth after react 19

packages/common/src/dbt/schemas/lightdashMetadata.json
=> fix: missing id format in lightdash metadata

packages/backend/src/analytics/LightdashAnalytics.ts, packages/backend/src/clients/EmailClient/EmailClient.ts, packages/backend/src/models/AnalyticsModel.ts, packages/backend/src/models/PinnedListModel.ts, packages/backend/src/services/AnalyticsService/AnalyticsService.ts, packages/backend/src/services/GitIntegrationService/GitIntegrationService.ts, packages/backend/src/utils.ts
Related: https://github.com/lightdash/lightdash-internal-work/issues/2758
I timeboxed this task, this is the first batch of fixes.
=> fix: fix some ANyTypes across our codebase

packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
Closes:  https://github.com/lightdash/lightdash/issues/13419
Before
After
=> fix: parse errors bigquery

packages/backend/src/clients/Google/GoogleDriveClient.ts, packages/backend/src/scheduler/SchedulerTask.ts, packages/common/src/types/scheduler.ts, packages/frontend/src/features/sync/components/SyncModalForm.tsx
Closes: https://github.com/lightdash/lightdash/issues/6744
with weird charts
=> feat: gsync save in tab name

packages/frontend/src/features/sync/components/SyncModalForm.tsx
=> fix: metadata tab name on gsync

.github/workflows/gcp-build-and-push.yml, .github/workflows/release-on-merge.yml, scripts/gcp-build-and-push.sh
Closes: 
Changes:
- amend sentry step 
- add GCP build and push workflow
=> chore: GCP build and push workflow

packages/backend/src/models/TagsModel.ts
- Only delete tags that have a reference
=> fix: deleting non project tags

packages/backend/src/services/ProjectService/ProjectService.ts
Closes: N/A
Relates to [#2809](https://github.com/lightdash/lightdash-internal-work/issues/2809)
- logs on pivot query failure
- related to snowflake query generation when doing a pivot. Users should ensure the casing matches the standards applied by their warehouses but we can assist them better if we have the right logging.
=> chore: log errored sql when pivotting fails in runner

packages/backend/src/dbt/DbtMetadataApiClient.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts, packages/backend/src/projectAdapters/dbtCloudIdeProjectAdapter.ts, packages/backend/src/projectAdapters/projectAdapter.ts, packages/common/src/types/projects.ts, packages/frontend/src/components/ProjectConnection/DbtForms/DbtCloudForm.tsx
Closes: [#13332](https://github.com/lightdash/lightdash/issues/13332)
New input:
Logs without tag filter:
Logs with tag filter:
=> feat: allow to filter dbt cloud models by tags

.github/CONTRIBUTING.md
=> docs: pgvector docs

packages/backend/src/ee/repl/index.ts, packages/backend/src/ee/repl/scripts/fixDuplicateSlugs.test.ts, packages/backend/src/ee/repl/scripts/fixDuplicateSlugs.ts, packages/backend/src/ee/repl/scripts/listProjects.test.ts, packages/backend/src/ee/repl/scripts/listProjects.ts, packages/backend/src/ee/repl/scripts/testUtils/index.ts, packages/backend/src/utils/SlugUtils.ts
- Adds script to fix duplicate slugs for charts
=> feat: add script to fix duplicate slugs for charts

packages/backend/src/ee/analytics/index.ts, packages/backend/src/ee/controllers/embedController.ts, packages/backend/src/ee/services/EmbedService/EmbedService.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/common/src/ee/embed/index.ts, packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx, packages/frontend/src/ee/features/embed/SettingsEmbed/EmbedCodeSnippet.tsx, packages/frontend/src/ee/features/embed/SettingsEmbed/EmbedUrlForm.tsx, packages/frontend/src/ee/pages/EmbedDashboard.tsx
Closes:  https://github.com/lightdash/lightdash/issues/13371
New settings
I added export to pdf as a new settings, since it was a feature that was not customizable. It is enabled  by default
New header, combinations:
No miniheader, the print button has some extra padding so it doesn't overlap the chart options 
[Screencast from 2025-01-29 09-51-23.webm](https://github.com/user-attachments/assets/a4da55c7-e794-4c08-957c-c6e9bbf2aae3)
=> feat: add data zoom to embed dashboards

.github/CONTRIBUTING.md, docker-compose.yml, docker/Dockerfile.headless-browser, docker/docker-compose.dev.yml, packages/backend/src/services/UnfurlService/UnfurlService.ts
Closes: 
Changes:
- update browserless image
- adjust timeout (necessary for new image)
- add logger
https://lightdash-pr-13386.onrender.com/api/v1/slack/image/D2OeuJ_nYaoUq4xeCyuMp
New logs:
Force test:
test-frontend
test-backend
=> feat: browserless chromium latest version from ghcr

packages/backend/src/controllers/sqlRunnerController.ts, packages/backend/src/projectAdapters/dbtNoneCredentialsProjectAdapter.ts, packages/backend/src/scheduler/SchedulerTask.ts, packages/backend/src/services/CsvService/CsvService.ts, packages/backend/src/services/ProjectService/ProjectService.ts, packages/common/src/types/analytics.ts, packages/common/src/types/warehouse.ts
Closes: #13457
- Enforces `query_context` query tag
- Single export for `RunQueryTags`
=> feat: enforce query context in query tags

packages/backend/src/clients/EmailClient/EmailClient.ts, packages/backend/src/clients/EmailClient/templates/googleSheetsSyncDisabledNotification.html, packages/backend/src/clients/Google/GoogleDriveClient.ts, packages/backend/src/scheduler/SchedulerTask.ts, packages/common/src/types/errors.ts
Closes: [#13398](https://github.com/lightdash/lightdash/issues/13398)
If the error is 500, we can retry the scheduled delivery, considered a Transient error
If the scheduler is disabled, we will notify the user that created the google sheets sync
we're disabling google sheets syncs even if the error is to do with google api. We should retry 
let's also monitor how this goes.
=> feat: handle sheets transient err and send email if disabled

packages/backend/src/models/DashboardModel/DashboardModel.ts, packages/backend/src/models/SavedChartModel.ts, packages/backend/src/services/ValidationService/ValidationService.mock.ts
Closes:  https://github.com/lightdash/lightdash/issues/13410
Before:
After:
=> fix: only validate charts saved in space or latest dashboard version

.github/workflows/gcp-build-and-push.yml
Closes: 
Remove the concurrency check as it was causing issues since `release-on-merge` also has the check. 
We shouldn't need the that check since we check for `chore(release):` commits.
=> chore: remove-gc-action-concurrency-check

packages/e2e/cypress/e2e/app/embed.cy.ts
Closes: [#2622](https://github.com/lightdash/lightdash-internal-work/issues/2622)
=> chore: embed e2e test

dockerfile, dockerfile-prs
Closes: #13488
- Pins `pnpm` version in docker file
=> fix: pin pnpm corepack installation

packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts
Closes: N/A
Removes unnecessary lightdash  project config logs
=> chore: remove unnecessary config logs

packages/backend/src/projectAdapters/dbtGitProjectAdapter.ts, packages/backend/src/projectAdapters/dbtNoneCredentialsProjectAdapter.ts
=> fix: remove unsafe destruct on projectAdapter

dockerfile, dockerfile-prs, package.json
Closes: N/A
Relates to: https://github.com/nodejs/corepack/issues/616
Detailed description of solution: https://github.com/SSWConsulting/SSW.Website/pull/3571#issue-2826448565
=> fix: install latest corepack before pnpm & pin pnpm@9.15.5

packages/backend/src/logging/winston.ts
=> chore: fix winston warning log

packages/common/src/dbt/schemas/manifestV12.json
Closes: N/A
From: https://schemas.getdbt.com/
test-backend
test-cli
=> fix: update manifestV12.json 

packages/frontend/src/components/ProjectAccess/CreateProjectAccessModal.tsx
Closes:  https://github.com/lightdash/lightdash/issues/13383
Before:
After:
=> fix: project admin cant invite new users

scripts/gcp-build-and-push.sh
Closes: [#13530](https://github.com/lightdash/lightdash/issues/13530)
=> chore: update GCP image repository

packages/backend/src/clients/Aws/S3CacheClient.ts
Closes: https://github.com/lightdash/lightdash-commercial/issues/434
Sanitizes metadata before caching results
Sentry error: https://lightdash.sentry.io/issues/6013865457/events/b512d29212134895a133ca6733d10efa/?project=5959292
=> fix: sanitize metadata before sending request to s3

packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/common/src/types/scheduler.ts
- Fix type that was conflicting with TSOA
=> fix: replaceCustomFields type

scripts/gcp-build-and-push.sh
Closes: 
Fix error;
```denied: Unauthenticated request. Unauthenticated requests do not have permission "artifactregistry.repositories.uploadArtifacts" on resource "projects/lightdash-containers/locations/us/repositories/lightdash" (or it may not exist)```
=> chore: add missing gcp config

packages/frontend/src/ee/features/embed/SettingsEmbed/EmbedCodeSnippet.tsx
Closes: 
A couple small syntax fixes in the embed code snippets.
=> fix: syntax errors in embed snippets

packages/frontend/src/components/Explorer/CustomMetricModal/index.tsx, packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx, packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeProvider.tsx, packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNode.tsx, packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/types.ts, packages/frontend/src/components/Explorer/SaveChartButton/index.tsx
Closes: [#13527](https://github.com/lightdash/lightdash/issues/13527) 
Show error when there is a metric with the same ID, independently if the rest(sql, etc) is a match.
=> feat: custom metric duplicate id error

packages/backend/src/models/UserModel.ts, packages/backend/src/services/UserService.ts, packages/common/src/utils/accessors.test.ts, packages/common/src/utils/accessors.ts
Related:  https://github.com/lightdash/lightdash-internal-work/issues/2758
=> fix: any type in UserService

packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/13523
Added missing padding between searchbar and title in 'Tables' sidebar.
=> style: add padding between searchbar and title in 'Tables' sidebar

packages/backend/src/clients/github/Github.ts, packages/backend/src/services/GitIntegrationService/GitIntegrationService.ts
Closes:  https://github.com/lightdash/lightdash/issues/13569
Before:
After:
Better error handling: 
"Unknown error": 
Not found error :
=> fix: fix path on custom metric PR

packages/backend/src/services/UserService.ts
Closes: https://github.com/lightdash/lightdash/issues/13596
Relates to: https://github.com/lightdash/lightdash/commit/5b72d20399209a45ca72b84c0ae2169c0f1fda1d#diff-2bf009692ddaa991e3267d9e2531e09172bfa4c622cfcc4270d550dc127d9fa5
- Changing how the function was imported made requesting a new token stop working
=> fix: request new access token

packages/backend/src/App.ts
=> fix: cors include same domain in the check

packages/e2e/cypress/e2e/app/pivotTables.cy.ts, packages/e2e/cypress/support/drag.ts
Closes:  https://github.com/lightdash/lightdash/issues/13514
[Screencast from 2025-02-05 10-41-43.webm](https://github.com/user-attachments/assets/091474ae-76d4-4e88-9709-1d92cb2200d4)
=> chore: pivot table e2e tests

packages/backend/src/App.ts
=> fix: cors allowed headers

packages/backend/src/App.ts
=> feat: cors enable regex domains

packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/common/src/ee/embed/index.ts, packages/frontend/src/ee/features/embed/SettingsEmbed/EmbedCodeSnippet.tsx, packages/frontend/src/ee/features/embed/SettingsEmbed/EmbedUrlForm.tsx, packages/sdk-test-app/src/App.tsx, packages/sdk/src/Lightdash.tsx
=> feat: react sdk decode project uuid from token

packages/frontend/src/components/Explorer/ExploreTree/TableTree/ItemDetailPreview.tsx, packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNode.tsx
Closes: [#13508](https://github.com/lightdash/lightdash/issues/13508)
=> feat: display sql & type on metric hover

packages/backend/src/services/GitIntegrationService/GitIntegrationService.ts, packages/common/src/types/field.ts, packages/common/src/utils/convertToDbt.ts, packages/common/src/utils/fields.test.ts, packages/common/src/utils/fields.ts, packages/common/src/utils/formatting.test.ts, packages/common/src/utils/formatting.ts, packages/frontend/src/components/Explorer/FormatForm/index.tsx
Closes: [#13619](https://github.com/lightdash/lightdash/issues/13619)
Changes:
- fix issue when creating PR where the project path is `/` 
- convert format objects to format expression
- replace YML metric with Custom metric if format is a match
- add unit tests
Known limitation:
- We don't support dot and white space separators. Format expression separators are based on the locale.
Demo:
https://github.com/user-attachments/assets/31dfe21f-9e6e-49b2-95c0-a025e6a82b9b
=> feat: write custom metric to dbt with format expression

packages/frontend/src/components/common/LightTable/styles.ts, packages/frontend/src/components/common/Table/Table.styles.ts, packages/frontend/src/components/common/Table/index.tsx, packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts, packages/frontend/src/hooks/echarts/useEchartsFunnelConfig.ts, packages/frontend/src/hooks/echarts/useEchartsPieConfig.ts, packages/sdk-test-app/src/App.tsx, packages/sdk/src/Lightdash.tsx
Closes: #13517 
Enable override of fonts and background in sdk
=> feat: enable overriding fonts and bg in sdk

packages/common/src/utils/formatting.ts, packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts
Closes: 
Replicate:
- add legacy percent format on a metric
- add to bar chart
- go to series -> show value labels
Before:
After:
=> fix: format series values

packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts, packages/frontend/src/hooks/echarts/useEchartsFunnelConfig.ts, packages/frontend/src/hooks/echarts/useEchartsPieConfig.ts
=> fix: cast font family to string

packages/backend/src/services/CoderService/CoderService.ts
Closes: 
fix: we need to `filter` content before the `slice`
=> fix: content as code offset

packages/frontend/src/ee/pages/EmbedDashboard.tsx, packages/frontend/src/sdk/index.tsx, packages/sdk/src/Lightdash.tsx, packages/sdk/src/index.ts
=> feat: react sdk filters

packages/backend/src/ee/services/EmbedService/EmbedService.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/common/src/ee/embed/index.ts, packages/frontend/src/ee/features/embed/SettingsEmbed/EmbedCodeSnippet.tsx
Closes: #13641
Content of jwt for embedding above: 
```json
{
"content": {
"type": "dashboard",
"projectUuid": "3675b69e-8324-4110-bdca-059031aa8da3",
"dashboardSlug": "jaffle-dashboard",
"dashboardFiltersInteractivity": {
"enabled": "none"
},
"canExportCsv": false,
"canExportImages": false,
"isPreview": false,
"canDateZoom": false,
"canExportPagePdf": true
},
"userAttributes": {
"": ""
},
"user": {
"email": "demo@lightdash.com"
},
"iat": 1739362193,
"exp": 1739365793
}
```
=> feat: reference dashboard via slug in embed

packages/backend/src/services/GitIntegrationService/GitIntegrationService.ts
Closes #13575
I added some formatting so that it's more readable
Without formatting: https://github.com/notgiorgi/jaffle_shop/pull/1
With formatting: https://github.com/notgiorgi/jaffle_shop/pull/3
=> feat(backend): Update message in Pull Request for write back to say "don't change stuff"

packages/frontend/src/components/Explorer/CustomMetricWriteBackModal/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/13638
=> fix: disable write back on error

packages/common/src/utils/fields.test.ts, packages/common/src/utils/fields.ts
Closes: 
ERROR: https://lightdash.sentry.io/issues/6296261992/?alert_rule_id=15154466&alert_type=issue&environment=cloud_beta&notification_uuid=3e1b9397-9fc5-435f-95cb-ef9a61f0df10&project=4507168845529088&referrer=issue_alert-slack
before:
after:
=> fix: assert filter type

packages/backend/src/services/UnfurlService/UnfurlService.ts, packages/frontend/src/components/DashboardTiles/DashboardMarkdownTile.tsx
Closes: [#13458](https://github.com/lightdash/lightdash/issues/13458)
wait for markdown tiles to be attached to dom before screenshotting.
=> fix: wait for markdown tiles before screenshot

packages/frontend/src/components/DashboardTiles/DashboardMarkdownTile.tsx
Closes: https://github.com/lightdash/lightdash/issues/13671
Allows duplicating markdown tiles 
Tested: 
- duplicated a bunch, added a saved chart + created a chart within dashboard and checked draft state throughout the stages 
- cancelled duplicating by going back to view mode
=> feat: allow duplicating markdown tiles

examples/api/organization-members.http, packages/backend/src/controllers/organizationController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/models/OrganizationMemberProfileModel.ts, packages/backend/src/services/OrganizationService/OrganizationService.ts, packages/e2e/cypress/e2e/api/api.cy.ts
=> feat: add get org member by email endpoint

packages/backend/src/analytics/LightdashAnalytics.ts, packages/backend/src/services/GitIntegrationService/GitIntegrationService.ts, packages/frontend/src/components/Explorer/ExplorePanel/index.tsx, packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx, packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNodeActions.tsx, packages/frontend/src/providers/Tracking/types.ts, packages/frontend/src/types/Events.ts
Closes: [#13636](https://github.com/lightdash/lightdash/issues/13636)
=> chore(analytics): events for write custom metrics back to dbt

packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNodeActions.tsx
=> fix: formatting in treesinglenodeactions

packages/backend/src/models/ValidationModel/ValidationModel.ts
Closes: N/A
`batchInsert` validation errors, to fix this issue: 
```
insert into "validations" ("chart_name", "dashboard_uuid", "error", "error_type", "field_name", "job_id", "model_name", "project_uuid", "saved_chart_uuid", "source") values ($1, DEFAULT, $2, $3, $4, $5, DEFAULT, $6, $7, $8), ($9, DEFAULT, $10, $11, $12, $13, DEFAULT, $14, $15, $16), ($17, DEFAULT, $18, $19, $20, $21, DEFAULT, $22, $23, $24), ($25, DEFAULT, $26, $27, $28, $29, DEFAULT, $30, $31, $32), ($33, DEFAULT, $34, $35, $36, $37, DEFAULT, $38, $39, $40), ($41, DEFAULT, $42, $43, $44, $45, DEFAULT, $46, $47, $48), ($49, DEFAULT, $50, $51, $52, $53, DEFAULT, $54, $55, $56), ($57, DEFAULT, $58, $59, $60, $61, DEFAULT, $62, $63, $64), ($65, DEFAULT, $66, $67, $68, $69, DEFAULT, $70, $71, $72), ($73, DEFAULT, $74, $75, …
```
=> fix: batch insert when running validator

packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx, packages/frontend/src/components/common/PageHeader/SpaceAndDashboardInfo.tsx, packages/frontend/src/components/common/TextCopy.tsx
=> feat: add way to copy slug from dashboard page

packages/e2e/cypress/e2e/app/userAttributes.cy.ts
- Relates to: https://github.com/lightdash/lightdash/pull/13663
=> fix: user attribute error on e2e

packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx
=> fix(frontend): added contrast text color for selected tiles.

packages/backend/src/clients/github/Github.ts, packages/backend/src/controllers/gitIntegrationController.ts, packages/backend/src/controllers/githubController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/projectAdapters/dbtGithubProjectAdapter.ts, packages/backend/src/projectAdapters/projectAdapter.ts, packages/backend/src/services/GitIntegrationService/GitIntegrationService.ts, packages/common/src/index.ts, packages/common/src/types/gitIntegration.ts, packages/common/src/types/projects.ts, packages/common/src/utils/github.ts, packages/frontend/src/MobileRoutes.tsx, packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx, packages/frontend/src/components/ProjectConnection/DbtForms/AzureDevOpsForm.tsx, packages/frontend/src/components/ProjectConnection/DbtForms/BitBucketForm.tsx, packages/frontend/src/components/ProjectConnection/DbtForms/DbtCloudForm.tsx, packages/frontend/src/components/ProjectConnection/DbtForms/DbtLocalForm.tsx, packages/frontend/src/components/ProjectConnection/DbtForms/GithubForm.tsx, packages/frontend/src/components/ProjectConnection/DbtForms/GitlabForm.tsx, packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx, packages/frontend/src/components/ProjectConnection/WarehouseForms/Inputs/DbtVersion.tsx, packages/frontend/src/components/UserSettings/GithubSettingsPanel/index.tsx, packages/frontend/src/components/common/GithubIntegration/hooks/useGithubIntegration.tsx, packages/frontend/src/features/sqlRunner/components/Header/HeaderCreate.tsx, packages/frontend/src/features/virtualView/components/CreateVirtualViewModal.tsx, packages/frontend/src/hooks/gitIntegration/useGitIntegration.ts, packages/frontend/src/pages/AuthPopupResult.tsx
Closes: https://github.com/lightdash/lightdash/issues/13687
[Screencast from 2025-02-14 15-56-06.webm](https://github.com/user-attachments/assets/fe0c15b5-dbfb-4408-906b-fa6590508afd)
things I tested: 
- create new project using github installation_id
- after being created, go to settings, and save again
- after being created with installation id, switch to PAT
=> feat: GitHub login full flow

packages/frontend/src/components/common/PivotTable/index.tsx, packages/frontend/src/components/common/Table/TableProvider.tsx, packages/frontend/src/hooks/useColumns.tsx
Closes: [#13491](https://github.com/lightdash/lightdash/issues/13491)
To test, changed `raw_events` to include new lines in event name
=> fix: process new lines in results

packages/backend/src/analytics/LightdashAnalytics.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/ProjectService/ProjectService.ts, packages/common/src/types/field.ts, packages/common/src/utils/formatting.ts, packages/frontend/src/components/Explorer/FormatForm/index.tsx, packages/frontend/src/features/tableCalculation/components/TableCalculationModal.tsx
Closes: [#13586](https://github.com/lightdash/lightdash/issues/13586) 
Closes: [#3778](https://github.com/lightdash/lightdash/issues/3778)
Changes:
- add "custom" option to metric/custom metric/table calculation format modals
- update query executed event
=> feat: allow custom format metrics and table calculations in the UI

packages/cli/src/dbt/models.ts
Closes: 
Questions (prompts) are asked concurrently, so they're hard to read and impossible to answer one-by-one. This change makes sure they're asked sequentially 
before: https://cln.sh/pT1TThMw
after: https://cln.sh/RYqHpYs4
=> fix(cli): "do you want to overwrite column description?" question formatting

packages/backend/src/models/SavedChartModel.ts, packages/backend/src/services/ValidationService/ValidationService.mock.ts, packages/backend/src/services/ValidationService/ValidationService.test.ts, packages/backend/src/services/ValidationService/ValidationService.ts
Closes: #13681
Updates validator to check for dimensions that filters of a custom metric depend on
https://cln.sh/qdXtJXS9
=> fix(backend): Validate custom metrics' filters

packages/backend/src/analytics/LightdashAnalytics.ts, packages/backend/src/generated/swagger.json, packages/backend/src/models/SearchModel/index.ts, packages/backend/src/services/SearchService/SearchService.ts, packages/common/src/types/search.ts, packages/frontend/src/features/omnibar/components/Omnibar.tsx, packages/frontend/src/features/omnibar/components/OmnibarFilters.tsx, packages/frontend/src/features/omnibar/components/utils.ts, packages/frontend/src/features/omnibar/utils/getSearchItemLabel.ts, packages/frontend/src/features/omnibar/utils/getSearchItemMap.ts, packages/frontend/src/providers/Tracking/types.ts
Closes: https://github.com/lightdash/lightdash/issues/13734
=> feat: filter dashboard tabs search

packages/backend/src/ee/services/AiService/tools/generateQueryFilters.ts, packages/common/src/ee/Ai/schemas.ts, packages/frontend/vite.config.ts
=> fix(ai): date filtering

.eslintrc.js, packages/backend/.eslintrc.js, packages/common/.eslintrc.js, packages/e2e/.eslintrc.js
=> chore: disable any warning eslint

packages/common/src/types/conditionalFormatting.ts, packages/common/src/utils/conditionalFormatting.ts, packages/common/src/utils/item.ts, packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingItem.tsx, packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingList.tsx, packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingRule.tsx, packages/frontend/src/components/common/Filters/FilterInputs/utils.ts
Closes: #5058
Allowed operators: 
- equals
- includes
Conditional formatting now supports string dimensions for a single color - no range option 
Main changes include: 
- better handling of draft updates 
- better util usage
- errors thrown on no-implementation operators
Demo
https://github.com/user-attachments/assets/e47012ac-4451-4f8b-832c-7bf95ee97ebd
=> feat: allow conditional formatting for string dimensions

packages/backend/src/models/SearchModel/index.ts
Closes:  #13762
Before:
AFter:
=> fix: fix tabs search multiple results

packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json
=> chore: generate api (conditional formatting)

packages/sdk-test-app/src/App.tsx
Closes: 
This just keeps the URL between reloads. It's very helpful when testing.
=> chore: persist url for test app

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx, packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/index.tsx
Closes: #13753, references: #13510
Series disappear when manually sorting them
https://github.com/user-attachments/assets/d7f12be0-3259-4e15-90a0-ebe17f010eef
https://github.com/user-attachments/assets/86afb59f-6e10-4adc-acd0-0fc10cd971bb
=> fix(frontend): Series disappear when manually sorting them

packages/backend/src/services/ProjectService/ProjectService.ts, packages/common/src/types/results.ts
=> fix: fix formatted undefined and log query results

packages/frontend/src/components/DataOps/index.tsx
=> fix: add placeholder and add '(current)' to current project

packages/frontend/src/components/Explorer/ExploreTree/TableTree/index.tsx
Closes: #12110 
Fix "Add dimension" button overlap with accordion on scroll issue
=> fix: add dimension button overlap issue

packages/e2e/cypress/e2e/api/projectPermissions.cy.ts
Related to: https://github.com/lightdash/lightdash/pull/13767
=> chore: amend project permission API tests

packages/backend/src/services/CsvService/CsvService.ts
Closes: 
Add logs for dashboard export csv. 
Related to: [#2939](https://github.com/lightdash/lightdash-internal-work/issues/2939)
=> chore: add info logs for dashboard CSV export

packages/cli/src/dbt/targets/postgres.ts, packages/cli/src/handlers/compile.ts, packages/cli/src/handlers/dbt/getWarehouseClient.ts
Closes: #7939
Support for postgres `sslmode: verify-full` and `sslmode: verify-ca` from CLI
Error messages:
=> fix(cli): create Postgres project with certificates via CLI

package.json, packages/backend/package.json
add a script to run backend tests sequentially, useful for docker and low-end machines
=> chore(backend): add a script to run backend tests sequentially

packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/UsersView.tsx
`useDebouncedValue` hook was causing page to re-render infinitely, which caused `TrackPage` component to re-render and track `invite_management_settings` events nonstop
Before: https://cln.sh/TF3QMrH2
=> fix(frontend): infinite re-renders in user settings

packages/backend/package.json, packages/backend/src/scripts/create-migration.ts
Closes: N/A
Can set OSS or EE migration
for EE there needs to be a license key
=> chore: let dev choose which directory to create migration

packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/CoderService/CoderService.ts, packages/common/src/types/coder.ts
Closes: https://github.com/lightdash/lightdash/issues/13822
in yaml:
after upload:
=> fix: chart as code pivot config

.github/workflows/release-on-merge.yml
=> fix: git secrets release action

.github/workflows/release-on-merge.yml
=> fix: git secrets release action disable husky env var

package.json
=> fix: husky prepare fallback

packages/frontend/src/ee/features/embed/EmbedDashboard/components/EmbedDashboard.tsx, packages/frontend/src/ee/features/embed/EmbedDashboard/components/EmbedMarkdownTile.tsx
Closes: #13840 
Translate MD tiles correclty
=> chore: translate markdown tiles correctly

packages/backend/src/ee/authentication/middlewares.ts
=> chore: improve scim token errors

packages/common/src/authorization/projectMemberAbility.test.ts
=> chore: fix semantic viewer test

packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
Closes:  #13882
Before
[Screencast from 2025-03-04 09-11-11.webm](https://github.com/user-attachments/assets/dc866a41-2e4b-4fed-8085-9b2ece9aadd8)
After
[Screencast from 2025-03-04 09-34-29.webm](https://github.com/user-attachments/assets/23c1f20e-f860-4e3c-9da0-834b220aed22)
=> fix: fix dynamic height virtual table

packages/warehouses/package.json, pnpm-lock.yaml
Relates to: https://github.com/lightdash/lightdash/pull/13892
- New types add the ability to `asyncExec`
=> chore: remove @types/snowflake-sdk

packages/backend/src/projectAdapters/projectAdapter.ts, packages/frontend/src/components/ProjectConnection/DbtForms/GithubForm.tsx
Closes:  #13898
Closes: https://github.com/lightdash/lightdash/issues/13899
Before
[Screencast from 2025-03-04 11-00-58.webm](https://github.com/user-attachments/assets/1fbf8186-3a4d-472d-ba13-add48be66d97)
After
=> fix: force github login on project form

packages/frontend/src/App.tsx, packages/frontend/src/hooks/thirdPartyServices/useSentry.ts
Closes: N/A
Followed docs here: https://docs.sentry.io/platforms/javascript/guides/react/features/react-router/v7/#usage-with-createbrowserrouter-or-creatememoryrouter
=> chore: update react router v7 with sentry instrumentation

packages/backend/src/controllers/gitIntegrationController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/queryBuilder.ts, packages/backend/src/services/GitIntegrationService/GitIntegrationService.ts, packages/common/src/dbt/DbtSchemaEditor/DbtSchemaEditor.mock.ts, packages/common/src/dbt/DbtSchemaEditor/DbtSchemaEditor.test.ts, packages/common/src/dbt/DbtSchemaEditor/DbtSchemaEditor.ts, packages/common/src/index.ts, packages/common/src/types/dbt.ts, packages/common/src/utils/convertCustomDimensionsToYaml.ts, packages/common/src/utils/customDimensions.ts
Related to: [#13802](https://github.com/lightdash/lightdash/issues/13802)
Request:
PR:
Query with new dimensions:
=> feat(API): write back bin dimensions

packages/backend/src/services/UnfurlService/UnfurlService.ts, packages/common/src/types/errors.ts
Closes: N/A
Better grouping of errors since now there is a ScreenshotError class
Set tags correctly and remove some unnecessary ones
=> chore: set correct sentry tags on saveScreenshot errors

packages/backend/src/sentry.ts, packages/common/src/types/errors.ts, packages/warehouses/src/ssh/sshTunnel.ts
Closes: 
#13883
Adds SshTunnelError for SshTunnel.connect method and ignores it, while keeping all other `WarehouseConnectionError`s intact
=> chore: Add SshTunnelError for improved SSH tunnel error handling

packages/frontend/src/components/common/Table/ScrollableTable/BodyCell.tsx
Closes: 
before:
after:
preserving newline breaks:
=> fix: table cell rendering for strings that does not have a newline

packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx
=> fix: fix import common

packages/backend/src/services/CsvService/CsvService.ts, packages/common/src/index.ts, packages/common/src/utils/promises.ts
=> fix: download valid chart csv

packages/backend/src/routers/dashboardRouter.ts, packages/backend/src/scheduler/SchedulerClient.ts, packages/backend/src/scheduler/SchedulerTask.ts, packages/backend/src/scheduler/SchedulerTaskTracer.ts, packages/backend/src/scheduler/SchedulerWorker.ts, packages/backend/src/services/CsvService/CsvService.ts, packages/common/src/types/scheduler.ts, packages/common/src/types/schedulerTaskList.ts, packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx, packages/frontend/src/features/scheduler/hooks/useScheduler.ts, packages/frontend/src/hooks/dashboard/useDashboard.ts
Closes: https://github.com/lightdash/lightdash/issues/13825
Migrate endpoint to scheduler
Process documented: https://www.notion.so/lightdash/Create-a-scheduler-method-1aea63207a7a8046ad24f68c24a7f308
=> fix: migrate dashboard csv zip to scheduler

packages/common/src/types/results.ts, packages/frontend/src/components/common/PivotTable/index.tsx, packages/frontend/src/components/common/Table/ScrollableTable/BodyCell.tsx, packages/frontend/src/hooks/useColumns.tsx
Closes: https://github.com/lightdash/lightdash/pull/13948
=> fix: formatting cell value regression

packages/common/src/utils/conditionalFormatting.ts
=> fix: conditional formatting null comparison regression

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx, packages/frontend/src/components/DashboardTiles/TileBase/TileBase.styles.tsx, packages/frontend/src/components/DashboardTiles/TileBase/index.tsx, packages/frontend/src/features/dateZoom/components/DateZoomInfoOnTile.tsx
Closes: https://github.com/lightdash/lightdash/issues/13949
https://github.com/user-attachments/assets/dfcd305f-713c-420b-a891-7b8aff0ec657
=> fix: chart descriptions not showing up

packages/backend/src/ee/scheduler/SchedulerClient.ts, packages/backend/src/ee/scheduler/SchedulerWorker.ts, packages/backend/src/scheduler/SchedulerTaskTracer.ts, packages/backend/src/scheduler/types.ts, packages/common/src/types/schedulerTaskList.ts
Closes: #13977 
before:
https://lightdash.slack.com/archives/C04DUJH6BNZ/p1741358817301089
after:
https://lightdash.slack.com/archives/C04DUJH6BNZ/p1741358926146649
=> fix: ai service getTagsForTask

packages/frontend/src/components/common/PivotTable/index.tsx, packages/frontend/src/hooks/tableVisualization/getDataAndColumns.tsx
Fixes: https://lightdash.sentry.io/issues/6363892358/?project=4507168845529088&referrer=github-pr-bot
Related PR: https://github.com/lightdash/lightdash/pull/13847#issuecomment-2704200370
=> fix: subtotals check if null or undefined

packages/backend/src/services/OrganizationService/OrganizationService.ts, packages/backend/src/services/UserService.ts, packages/common/src/index.ts, packages/common/src/utils/organization.ts, packages/frontend/package.json, packages/frontend/src/components/UserCompletionModal/UserCompletionModal.tsx, packages/frontend/src/components/UserSettings/OrganizationPanel/index.tsx, pnpm-lock.yaml
Closes: [#2975](https://github.com/lightdash/lightdash-internal-work/issues/2975)
Improves organization name validation
https://cln.sh/s23pjJzh
=> fix: improve organization name validation

.github/workflows/create-sentry-release.yml
Closes: N/A
I suspect that the frontend source maps aren't being properly set on the UI - examples here: https://lightdash.sentry.io/issues/?environment=cloud_beta&project=4507168845529088&query=is%3Aunresolved&referrer=issue-list&sort=freq&statsPeriod=14d&viewId=150308
didn't set `inject: false` - I want to see how this goes https://github.com/getsentry/action-release/releases/tag/v3.0.0
=> fix: upgrade to getsentry/action-release@v3

packages/backend/src/middlewares/sentry.ts
Closes: 
Fixes
```
packages/backend lint: /home/runner/work/lightdash/lightdash/packages/backend/src/middlewares/sentry.ts
packages/backend lint:   15:13  error  Unsafe assignment of an `any` value  @typescript-eslint/no-unsafe-assignment
packages/backend lint:   16:13  error  Unsafe assignment of an `any` value  @typescript-eslint/no-unsafe-assignment
```
=> chore: fix lint error sentry middleware

packages/backend/src/ee/services/ScimService/ScimService.ts, packages/common/src/ee/scim/errors.ts
Closes: N/A
Added name ScimError to scim error constructor 
example: https://lightdash.sentry.io/issues/6381467485/?environment=development&query=is%3Aunresolved&referrer=issue-stream&sort=date&statsPeriod=1h&stream_index=0
=> chore: capture sentry exception as ScimError

packages/frontend/src/components/common/Table/ScrollableTable/BodyCell.tsx, packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx, packages/frontend/src/components/common/Table/Table.styles.ts
Closes: https://github.com/lightdash/lightdash/issues/13985
https://github.com/user-attachments/assets/565704ed-f1a5-4205-84da-0ae959b802bc
=> fix: table body cell should expand if text is too long

packages/backend/src/controllers/v2/ProjectController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/ProjectService/ProjectService.test.ts, packages/backend/src/services/ProjectService/ProjectService.ts, packages/backend/src/services/ProjectService/types.ts, packages/common/src/types/api/paginatedQuery.ts, packages/common/src/types/featureFlags.ts, packages/frontend/src/hooks/useQueryResults.ts
Relates to:  [#13988](https://github.com/lightdash/lightdash/issues/13988)
Changes:
- Fetch results for the explore using the new paginated endpoint. This behaviour is behind a feature flag for now.
- Remove unused/legacy properties from new endpoint
Demo with pageSize = 20
https://github.com/user-attachments/assets/5d7426c2-4388-412b-872f-f2339c6c7e56
=> feat(explore): request results with new endpoint

packages/backend/src/models/SlackAuthenticationModel.ts
Follow up on #13980 and #13958
Categorizes slack errors
https://lightdash.sentry.io/issues/6367524063/?query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=14d&stream_index=8
=> chore: categorize not found errors in SlackAuthenticationModel

packages/backend/src/services/ProjectService/ProjectService.ts
Closes: 
chore: set warehouse type tag for Sentry
=> chore: set warehouse type tag for Sentry

packages/frontend/src/features/sqlRunner/components/Header/HeaderCreate.tsx
Closes:  https://github.com/lightdash/lightdash/issues/14003
This will help with customers who don't know why write back doesn't show up on sql runner.
=> fix: show write back on sql runner

packages/backend/src/services/ProjectService/ProjectService.ts, packages/common/src/types/queryHistory.ts, packages/common/src/types/warehouse.ts, packages/warehouses/package.json, packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts, packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.test.ts, pnpm-lock.yaml
Closes: [#13911](https://github.com/lightdash/lightdash/issues/13911)
test-frontend
=> feat(API): Bigquery pagination

packages/backend/src/scheduler/SchedulerJobTimeout.ts, packages/common/src/types/errors.ts
Closes: #14043 
Related to: https://lightdash.sentry.io/issues/6365741605/?environment=cloud_beta&query=is%3Aunresolved%20tryJobOrTimeout&referrer=issue-stream&sort=date&statsPeriod=14d&stream_index=0
=> chore: categorise job timeout as TimeoutError

.github/workflows/gcp-build-and-push.yml
Closes: N/A
Followed: https://github.com/getsentry/sentry-cli/issues/792#issuecomment-1014956104
Ad there are no commits set in Release
=> fix: add fetch depth 0 to checkout action (sentry release)

packages/backend/src/config/parseConfig.ts, packages/frontend/src/hooks/tableVisualization/getDataAndColumns.tsx
=> fix: common imports from src

packages/common/src/types/errors.ts, packages/common/src/utils/conditionalFormatting.ts, packages/frontend/src/components/common/Filters/utils/getPlaceholderByFilterTypeAndOperator.ts
Categorizes some not-implemented errors for better filtering
not very common but does fall through the cracks: 
- https://lightdash.sentry.io/issues/6321787447/?query=Not%20implemented&referrer=issue-stream&sort=date&stream_index=1
- https://lightdash.sentry.io/issues/6396730160/?project=4507168845529088&query=Not%20implemented&referrer=issue-stream&sort=date&stream_index=0
=> chore: categorize not-implemented-errors

packages/backend/src/analytics/LightdashAnalytics.ts, packages/backend/src/services/ProjectService/ProjectService.ts
Closes: [#14013](https://github.com/lightdash/lightdash/issues/14013)
Add analytic events to paginated query:
`query.executed` - this one already existed but extended properties
`query.ready` - when the warehouse query is completed/ready
`query.error` - when the warehouse throws an error
`query_page.fetched` - when we fetch a results page
**Note:** since these screenshots I added a few more properties to the events: `columnsCount`, `totalRowCount`, `totalPageCount`.
=> chore(analytics): paginated query events

packages/backend/src/controllers/v2/ProjectController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/ProjectService/ProjectService.ts, packages/backend/src/services/UnfurlService/UnfurlService.ts, packages/common/src/types/analytics.ts, packages/frontend/src/hooks/dashboard/useDashboardChart.ts, packages/frontend/src/hooks/useExplore.tsx, packages/frontend/src/hooks/useQueryResults.ts, packages/frontend/src/hooks/useSavedQuery.ts, packages/frontend/vite.config.ts
Closes: [#13988](https://github.com/lightdash/lightdash/issues/13988)
Note: this is behind a feature flag 
Load paginated results in:
- chart view
- chart history
- dashboard
=> feat: load paginated results for charts and dashboards

.cursor/rules/backend.mdc, .cursor/rules/frontend.mdc
Closes: N/A
Adds BE and FE cursor rules
Auto attaches based on the file being in frontend or backend
=> chore: add cursor rules for FE and BE

packages/cli/src/dbt/targets/snowflake.ts
Partially closes: #6424
credentials in 1password
Before:
After:
=> feat: add private_key to snowflake CLI

.gitignore, packages/frontend/.eslintrc.js, packages/frontend/.storybook/main.ts, packages/frontend/.storybook/preview.tsx, packages/frontend/package.json, packages/frontend/src/stories/Button.stories.tsx, packages/frontend/src/stories/FormCard.mdx, packages/frontend/src/stories/FormCard.stories.tsx, packages/frontend/tsconfig.json, pnpm-lock.yaml
Closes: 
Followed these tutorials: 
https://storybook.js.org/docs/get-started/install
https://v6.mantine.dev/guides/storybook/
Highlights: 
- Controls for components
- ability to add autodocs
- ability to copy sourcecode of templates
Just run:
`pnpm -F frontend storybook`
=> chore: add initial storybook structure

packages/backend/package.json, packages/backend/src/App.ts, packages/backend/src/config/parseConfig.test.ts, packages/backend/src/config/parseConfig.ts, pnpm-lock.yaml
Closes: [#2974](https://github.com/lightdash/lightdash-internal-work/issues/2974)
Modify helmet config for `/embeds/*` routes
Demo: https://jsbin.com/pibenebiqe/edit?html,output (I set `LIGHTDASH_CSP_REPORT_ONLY=false` on staging env)
=> feat: adjust helmet config for embed subroutes

packages/backend/src/services/ProjectService/ProjectService.ts, packages/backend/src/services/ProjectService/resultsPagination.ts, packages/frontend/src/hooks/useQueryError.ts
- Validates if requested page is over last page taking into account total results from queryHistory
=> fix: validate page against total pages

packages/backend/src/services/UnfurlService/UnfurlService.ts
Closes: N/A
If this helps, I will update env vars accordingly
=> chore: increase playwright response wait timeout to 90000

packages/backend/src/controllers/v2/ProjectController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/ProjectService/ProjectService.ts, packages/backend/src/services/ProjectService/types.ts, packages/common/src/types/api/paginatedQuery.ts, packages/frontend/src/components/MetricQueryData/UnderlyingDataModalContent.tsx, packages/frontend/src/hooks/useQueryResults.ts
Closes: #14041 
- Adds underlying data query to paginated query endpoints
- Modifies hook to request paginated results when paginated results are enabled and query uuid exists
=> feat: add paginated underlying data query

packages/common/src/utils/formatting.ts, packages/warehouses/src/warehouseClients/TrinoWarehouseClient.mock.ts, packages/warehouses/src/warehouseClients/TrinoWarehouseClient.test.ts, packages/warehouses/src/warehouseClients/TrinoWarehouseClient.ts
Closes: https://github.com/lightdash/lightdash/issues/14097
Before
After
=> fix: uppercase column trino

packages/cli/src/handlers/preview.ts
=> feat(preview): display parent project name in output when creating a preview project

packages/backend/src/services/SchedulerService/SchedulerService.ts, packages/frontend/src/features/sync/components/SyncModalView.tsx
Closes: #8365 and #13307
Sync Now button for Google Sheet Sync
Demo: https://cln.sh/1rdDPvsR
=> feat: Sync Now button for Google Sheet Sync

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx, packages/frontend/src/components/Explorer/index.tsx, packages/frontend/src/components/MetricQueryData/MetricQueryDataProvider.tsx, packages/frontend/src/components/MetricQueryData/UnderlyingDataModalContent.tsx, packages/frontend/src/components/MetricQueryData/context.ts, packages/frontend/src/hooks/dashboard/useDashboardChart.ts
Closes: #14146 
AC:
- should still work for chart view
- explorer
**Before:**
https://github.com/user-attachments/assets/1579feee-b5fc-4cd7-b999-53d3a23c9144
**After:**
https://github.com/user-attachments/assets/3eafe811-4093-4a1f-a94c-c3481b058d24
=> fix: dashboard chart underlying data queryUuid

packages/backend/src/analytics/LightdashAnalytics.ts, packages/backend/src/controllers/authentication/middlewares.ts, packages/backend/src/controllers/runQueryController.ts, packages/backend/src/controllers/savedChartController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/LightdashAnalyticsService/LightdashAnalyticsService.ts, packages/backend/src/services/ServiceRepository.ts
Closes: #14095 
- Adds deprecation notice header
- Adds deprecated decorator
- Tracks analytics event for legacy routes
=> chore: add deprecation notice to legacy results endpoints

packages/frontend/src/components/UserCompletionModal/UserCompletionModal.tsx
Related to: ##13997
Do not validate organization name when user is joining existing organization
=> fix: User completion modal blocking people from completing sign up

packages/backend/src/controllers/schedulerController.ts, packages/backend/src/models/SchedulerModel/SchedulerModel.test.ts, packages/backend/src/models/SchedulerModel/index.ts, packages/backend/src/scheduler/SchedulerClient.ts, packages/backend/src/scheduler/SchedulerTask.ts, packages/backend/src/scheduler/SchedulerWorker.ts, packages/backend/src/services/SchedulerService/SchedulerService.ts, packages/common/src/authorization/organizationMemberAbility.test.ts, packages/common/src/authorization/organizationMemberAbility.ts, packages/common/src/authorization/projectMemberAbility.test.ts, packages/common/src/authorization/projectMemberAbility.ts, packages/common/src/authorization/types.ts, packages/common/src/types/schedulerLog.ts, packages/frontend/src/testing/__mocks__/api/userResponse.mock.ts
=> fix: fix job status

packages/frontend/src/components/Explorer/CustomMetricModal/hooks/useDataForFiltersProvider.ts, packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx, packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx, packages/frontend/src/components/Explorer/ResultsCard/ResultsCard.tsx, packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx, packages/frontend/src/hooks/useQueryResults.ts, packages/frontend/src/pages/MinimalSavedExplorer.tsx
Closes: 
Fix error where pivoted charts cause an infinite loop.
Before:
After:
=> fix: infinite loop error on pivotted charts

packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
Closes: 
Switching from user/pass to snowflake with private key with a different user , doesn't remove the old password, so it was still trying to apply the old password with the new user
=> fix: snowflake private key swap

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx, packages/frontend/src/components/Explorer/ResultsCard/ResultsCard.tsx, packages/frontend/src/components/ExportCSV/ExportCSVModal.tsx, packages/frontend/src/components/ExportCSV/index.tsx, packages/frontend/src/components/ExportSelector/index.tsx, packages/frontend/src/components/MetricQueryData/UnderlyingDataModalContent.tsx, packages/frontend/src/components/common/ChartDownload/ChartDownloadMenu.tsx
Closes: 
Clean up csv export modal/button to not depend on the rows.
=> chore: remove rows dependency from export csv modal

packages/frontend/src/components/ProjectConnection/WarehouseForms/SnowflakeForm.tsx
Closes: https://github.com/lightdash/lightdash/issues/14183
=> fix: default password snowflake

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
=> fix: invisible colors embed dashboard

packages/backend/src/models/ProjectModel/ProjectModel.ts
Closes:  https://github.com/lightdash/lightdash/issues/14189
Before: 
After:
=> fix: batch copy content for preview

packages/cli/src/dbt/targets/snowflake.ts
Closes: 
Thread: https://lightdash.slack.com/archives/C04NZSMM9LZ/p1743177550893329?thread_ts=1742810076.366889&cid=C04NZSMM9LZ
=> fix: snowflake auth cli

packages/backend/src/services/UnfurlService/UnfurlService.ts
Closes: N/A
doubles the timeout wait
=> chore: double timeout of response wait screenshot

packages/frontend/src/components/DashboardFilter/Filter.tsx
Closes: #6035
Adds a button to reset all Dashboard saved filters
Demo: https://cln.sh/PjXmtHqw
=> feat: button to reset all Dashboard saved filters

packages/backend/src/clients/github/Github.ts, packages/backend/src/controllers/gitIntegrationController.ts, packages/backend/src/controllers/projectController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/CsvService/CsvService.test.ts, packages/backend/src/services/GitIntegrationService/GitIntegrationService.ts, packages/backend/src/services/ProjectService/ProjectService.test.ts, packages/backend/src/services/ProjectService/ProjectService.ts, packages/backend/src/services/ServiceRepository.ts, packages/common/src/types/projects.ts, packages/frontend/src/components/NavBar/CreatePreviewProjectModal.tsx, packages/frontend/src/components/ProjectConnection/DbtForms/DbtCloudForm.tsx, packages/frontend/src/components/ProjectConnection/index.tsx, packages/frontend/src/components/RefreshDbtButton/index.tsx, packages/frontend/src/hooks/useProjectPreview.ts
Closes:  https://github.com/lightdash/lightdash/issues/14237
Branch Jose and Oli made during the offiste. 
I reviewed the code , remove code and made some small UI changes. 
This currently works for Github users, UI can still be improved for the rest. I'll create a separate ticket for the changes we need.
=> feat: preview branch

packages/backend/src/services/ProjectService/ProjectService.ts
Improve Table Selection handling for explorer
=> fix: improve Table Selection handling for explorer

packages/backend/src/services/ProjectService/ProjectService.ts
Reverts lightdash/lightdash#14255
=> fix: revert "fix: improve Table Selection handling for explorer"

packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/CreateGroupModal.tsx
Closes: #14279
**Before**
https://github.com/user-attachments/assets/9c860be0-ed83-4453-97e8-453a55032288
**After**
https://github.com/user-attachments/assets/f8d3077a-dbaf-419d-9db6-93735b8fa3d8
=> fix: scroll inside select

packages/common/src/types/projects.ts
=> fix: bigquery preview dataset

packages/backend/src/App.ts, packages/backend/src/controllers/authentication/middlewares.ts
Closes:  #14284
Demo: https://cln.sh/Mq8yQPYs
=> fix: invite links dont work when invites are deleted and recreated

packages/backend/src/analytics/LightdashAnalytics.ts, packages/backend/src/services/ProjectService/ProjectService.ts
Closes: #14300 
Add status to page fetched event
=> chore: add status to page fetched event

packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx, packages/frontend/src/components/DashboardFilter/Filter.tsx, packages/frontend/src/components/DashboardFilter/index.tsx, packages/frontend/src/ee/features/embed/EmbedDashboard/components/EmbedDashboardFilters.tsx, packages/frontend/src/providers/Dashboard/DashboardProvider.tsx
Closes: #14278 
Reset filters button for embedded dashboards
Demo: https://cln.sh/Vg0DntY7
=> feat: Reset filters button for embedded dashboards

packages/frontend/src/hooks/useQueryResults.ts
Closes: #14299
- Implements a simple backoff strategy when polling for ready state. Goes from 250ms -> 500ms -> 1000ms, and then stays at 1s
=> fix: implement pending query polling backoff strategy

packages/frontend/src/components/common/Filters/FilterInputs/BooleanFilterInputs.tsx, packages/frontend/src/components/common/Filters/FilterInputs/utils.ts, packages/frontend/src/components/common/Filters/utils/getPlaceholderByFilterTypeAndOperator.ts
Closes: https://github.com/lightdash/lightdash/issues/14151
=> feat: boolean filter `is not` operator

packages/frontend/src/components/ProjectConnection/WarehouseForms/PostgresForm.tsx, packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
Closes: https://github.com/lightdash/lightdash/issues/14291
Made changes to allow SSL protected postgres warehouses on GCP 
If you want to test, search for `Postgres staging database SSL protected` on 1password
=> fix: postgres certificates

packages/frontend/src/components/common/ChartDownload/ChartDownloadOptions.tsx
Closes: [#14179](https://github.com/lightdash/lightdash/issues/14179)
We have opened 2 tickets in echarts repo related to this work:
- [Bug] getDataURL throws TypeError: Cannot read properties of null (reading 'length') [#20904](https://github.com/apache/echarts/issues/20904)
- [Bug] Pie label position doesn't update correctly when switching between outside and inside [#20905](https://github.com/apache/echarts/issues/20905)
While we wait for the library fixes, to avoid errors, we hide the labels during image export.
Before:
After (download):
=> fix: add workaround to export pie chart with inside label

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/TooltipConfig.tsx, packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/index.tsx, packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts
=> fix: autocomplete no pivot for tooltip

packages/backend/src/database/seeds/development/01_initial_user.ts, packages/backend/src/database/seeds/development/05_nested_spaces.ts, packages/common/src/index.ts
Closes: N/A
Adds seed script for nested spaces.
- Seeds `demo2@lightdash.com` user for default org 
- Generates three top level directories: shared, private and one with `access` (w/ demo2 user)
=> chore: seeder for nested spaces

packages/e2e/cypress/e2e/api/async-query.cy.ts
Closes: 
Add API tests for paginated query endpoints. 
There is more we could add here, but this is a good basis. 
test-frontend
test-backend
=> chore: e2e tests for paginated query handling

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/TooltipConfig.tsx, packages/frontend/src/styles/monaco.css
=> fix: monaco custom tooltip UI issues

packages/frontend/src/components/ProjectConnection/WarehouseForms/PostgresForm.tsx
=> fix: remove certificates from require SSL

packages/backend/src/generated/swagger.json
Related PR: https://github.com/lightdash/lightdash/pull/14155, https://github.com/lightdash/lightdash/issues/13920
- Runs `generate-api` and release results caching for pagination
=> feat: release results caching and update swagger

packages/frontend/src/features/scheduler/components/SchedulerForm.tsx
=> fix: reduce msteams webhook badges

packages/frontend/vite.config.ts
Closes: N/A
chore: add allowed host for cloudflared tunnels in Vite config
=> chore: add allowed host for cloudflared tunnels in Vite config

packages/frontend/src/hooks/useContent.ts, packages/frontend/src/pages/Space.tsx
Relates to: https://github.com/lightdash/lightdash/issues/14319#issuecomment-2786973638
Removes add-existing-content from Space view
=> chore: remove add-existing-content from Space view

packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/models/SpaceModel.ts, packages/backend/src/services/CoderService/CoderService.ts, packages/backend/src/services/PromoteService/PromoteService.mock.ts, packages/common/src/types/featureFlags.ts, packages/common/src/types/resourceViewItem.ts, packages/common/src/types/space.ts, packages/frontend/src/components/common/ResourceView/ResourceActionHandlers.tsx, packages/frontend/src/components/common/ShareSpaceModal/index.tsx, packages/frontend/src/components/common/SpaceActionModal/CreateSpaceModalContent.tsx, packages/frontend/src/components/common/SpaceActionModal/index.tsx, packages/frontend/src/hooks/useContent.ts, packages/frontend/src/pages/Space.tsx
Closes: #14319 
Added feature flag to `common` - `NestedSpaces` -> "nested-spaces"
Hide permissions change if it's a nested space.
When creating a root space
When creating a nested space
When updating a nested space
=> feat: handle creation/update of nested spaces

packages/backend/src/analytics/LightdashAnalytics.ts, packages/backend/src/services/SavedChartsService/SavedChartService.ts
Closes: https://github.com/lightdash/lightdash/issues/14360
=> chore: Analytic event for custom tooltip

packages/backend/package.json, packages/backend/src/models/UserModel.ts, packages/backend/src/services/UserService.ts, pnpm-lock.yaml
Relates to: [#14373](https://github.com/lightdash/lightdash/issues/14373)
Getting the session user on each API request is flooding the DB with requests. 
This PR caches the session user for 30 seconds reducing greatly the queries to the DB.
=> fix: cache user session

packages/frontend/src/components/NavBar/BrowseMenu.tsx
Closes: #14330
Only show root spaces in navbar
=> feat: Only show root spaces in navbar

packages/backend/src/ee/controllers/embedController.ts, packages/backend/src/ee/index.ts, packages/backend/src/ee/services/EmbedService/EmbedService.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/ProjectService/ProjectService.ts, packages/frontend/src/ee/features/embed/EmbedDashboard/api.ts, packages/frontend/src/hooks/tableVisualization/useTableConfig.ts, packages/frontend/src/hooks/useCalculateTotal.ts, packages/frontend/src/hooks/useColumns.tsx
Closes: https://github.com/lightdash/lightdash/issues/14186
=> feat: embedding table totals

packages/frontend/src/components/common/modal/ChartCreateModal/SaveToSpaceOrDashboard.tsx
Closes: [#14387](https://github.com/lightdash/lightdash/issues/14387)
Allow org admins to save to private dashboards
=> fix: Allow org admins to save to private dashboards

packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
Closes: [#14157](https://github.com/lightdash/lightdash/issues/14157)
Related to: https://github.com/lightdash/lightdash/pull/13510
Before:
After:
=> fix: reference line for pivot series

packages/backend/src/models/ContentModel/ContentConfigurations/SpaceContentConfiguration.ts, packages/frontend/src/components/common/ResourceView/InfiniteResourceTable.tsx, packages/frontend/src/components/common/ResourceView/types.ts, packages/frontend/src/hooks/useContent.ts, packages/frontend/src/hooks/useSpaces.ts, packages/frontend/src/pages/Space.tsx
Closes: #14322 
Displays a nested space in a space
Uses work in #14399 to filter by parent space uuid
Hides "Space" column for this view - redundant
Demo
https://github.com/user-attachments/assets/098f6f07-e341-4449-95b6-370dc96a4ce1
=> feat: display nested spaces in space

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- Fixes loading states for dashboard charts
**Before**
https://github.com/user-attachments/assets/abaaa4dd-b6ed-484f-94e2-15f7da425075
**After**
https://github.com/user-attachments/assets/290db622-36a3-4fa8-bd0f-866b0cf9e812
=> fix: dashboard loading states

packages/backend/src/config/lightdashConfig.mock.ts, packages/backend/src/config/parseConfig.ts, packages/backend/src/logging/winston.ts
Closes: 
https://cloud.google.com/logging/docs/view/correlate-logs
=> chore: add gcp trace field to winston

packages/backend/src/ee/services/EmbedService/EmbedService.ts, packages/backend/src/services/CoderService/CoderService.ts, packages/backend/src/services/DashboardService/DashboardService.ts, packages/backend/src/services/PromoteService/PromoteService.ts, packages/common/src/types/dashboard.ts, packages/frontend/src/components/DashboardTabs/DeleteTabModal.tsx, packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx, packages/frontend/src/components/DashboardTiles/TileBase/index.tsx, packages/frontend/src/components/common/modal/DashboardDeleteModal.tsx
removes duplicate function
was discussed here: https://github.com/lightdash/lightdash/pull/14335#discussion_r2039615885
=> chore: remove duplicated is chart tile function

packages/backend/src/models/UserModel.ts, packages/backend/src/services/UserService.ts
Relates to: https://github.com/lightdash/lightdash/issues/14373, https://github.com/lightdash/lightdash/pull/14381
- Re-adds user session in memory cache with awaited promise
=> fix: re-add session user in memory cache

packages/backend/src/prometheus.ts
Closes: 
Track query wait and execution time above
=> chore: increase prometheus histogram buckets

packages/backend/src/models/ProjectModel/ExploreCache.ts, packages/backend/src/models/ProjectModel/ProjectModel.ts, packages/backend/src/models/UserModel.ts
Closes: #14425 
- Adds in memory cache to `findExploresFromCache`
=> feat: cache explores in memory

packages/backend/src/models/SpaceModel.ts
Closes: 
uses single transaction when creating an upstream space
=> fix: use single transaction when creating an upstream space

packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/models/SpaceModel.ts, packages/backend/src/services/DashboardService/DashboardService.mock.ts, packages/backend/src/services/ProjectService/ProjectService.mock.ts, packages/backend/src/services/PromoteService/PromoteService.mock.ts, packages/common/src/types/space.ts, packages/frontend/src/components/common/MantineModal/index.tsx, packages/frontend/src/components/common/SpaceActionModal/DeleteSpaceModalContent.tsx, packages/frontend/src/components/common/SpaceActionModal/index.tsx, packages/frontend/src/hooks/useSpaces.ts
=> feat: refreshed delete space modal

packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/models/ContentModel/ContentConfigurations/SpaceContentConfiguration.ts, packages/backend/src/models/ResourceViewItemModel.ts, packages/backend/src/models/SpaceModel.ts, packages/backend/src/services/CoderService/CoderService.ts, packages/backend/src/services/DashboardService/DashboardService.mock.ts, packages/backend/src/services/ProjectService/ProjectService.mock.ts, packages/backend/src/services/PromoteService/PromoteService.mock.ts, packages/backend/src/services/PromoteService/PromoteService.ts, packages/common/src/types/content.ts, packages/common/src/types/promotion.ts, packages/common/src/types/resourceViewItem.ts, packages/common/src/types/space.ts, packages/frontend/src/components/NavBar/ExploreMenu.tsx, packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx, packages/frontend/src/components/common/ResourceView/ResourceActionHandlers.tsx, packages/frontend/src/components/common/SpaceActionModal/index.tsx, packages/frontend/src/pages/Space.tsx, packages/frontend/src/pages/SpacesV2.tsx
=> feat: expose path for space resource in the api

packages/frontend/.eslintrc.js, packages/frontend/src/stories/Tree.module.css, packages/frontend/src/stories/Tree.stories.tsx, packages/frontend/src/stories/Tree.tsx, packages/frontend/src/stories/test.json.ts
=> feat: add tree component in storybook

packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceAccessType.tsx, packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceAddUser.tsx, packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceUserList.tsx, packages/frontend/src/components/common/ShareSpaceModal/index.tsx
=> feat: show callout for nested spaces and disable share

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx, packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx, packages/frontend/src/pages/Dashboard.tsx, packages/frontend/src/pages/SavedExplorer.tsx
Closes: [#14449](https://github.com/lightdash/lightdash/issues/14449)
Changes:
- use chart/dashboard pinnedListUuid property instead of fetching all pinned items
- move pin logic closer to button
=> fix: remove pinned items request from chart and dashboard page

packages/frontend/src/components/common/Tree/Tree.tsx, packages/frontend/src/components/common/Tree/utils.ts, packages/frontend/src/stories/Tree.stories.tsx
=> feat: tree component add value and onChange props

packages/backend/src/clients/Aws/S3Client.ts, packages/backend/src/clients/Slack/SlackClient.ts, packages/backend/src/scheduler/SchedulerTask.ts, packages/backend/src/services/UnfurlService/UnfurlService.ts, packages/common/src/types/scheduler.ts
Closes: #14465
Test steps in linked issue.
**Before**
Internal thread: https://lightdash.slack.com/archives/C04DUJH6BNZ/p1744973402825889 (notice no pdf message in thread)
**After**
Internal thread: https://lightdash.slack.com/archives/C04DUJH6BNZ/p1744975337309979 (notice pdf message in thread)
=> fix: slack upload PDF attachment in thread

packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts
Closes:  https://github.com/lightdash/lightdash/issues/14431
Works with pivot results too
=> fix: formatted value custom tooltip

packages/frontend/src/components/common/ResourceView/InfiniteResourceTable.tsx, packages/frontend/src/components/common/ResourceView/InfiniteResourceTableColumnName.tsx, packages/frontend/src/components/common/ResourceView/ResourceAccessInfo.tsx
=> feat: display access and contents information for nested spaces

docker/docker-compose.dev.yml, packages/frontend/package.json
=> chore: expose storybook port on dev docker-compose

packages/frontend/src/stories/Modal.stories.tsx
Closes: N/A
Showcases new MantineModal component that conforms to the new UI guidelines
=> chore: add MantineModal to storybook

packages/frontend/src/components/common/MantineModal/index.tsx
Closes: N/A
Fixes scroll behavior of modal component
=> fix: MantineModal scroll behavior

packages/backend/src/models/ResourceViewItemModel.ts
Closes: https://github.com/lightdash/lightdash/issues/14447
With a production example, the execution time dropped from 4 seconds to 40ms.
See more details in slack thread
Changes:
- move chart/dashboard counting to cte
- simplify joins + where condition
=> fix: get all spaces query

packages/backend/src/services/ProjectService/ProjectService.ts
Closes: #14480
Related PR: https://github.com/lightdash/lightdash/pull/14444
Reproduction steps in issue to be closed
**Before**
**After**
=> fix: add quotes wraping row_index

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/TooltipConfig.tsx
=> chore: update custom tooltip docs url

packages/frontend/src/components/common/MantineModal/index.tsx, packages/frontend/src/components/common/ResourceView/ResourceActionHandlers.tsx, packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx, packages/frontend/src/components/common/ResourceView/index.tsx, packages/frontend/src/components/common/ResourceView/types.ts, packages/frontend/src/components/common/TransferItemsModal/TransferItemsModal.tsx
Partially implements: https://github.com/lightdash/lightdash/issues/14420
[CleanShot 2025-04-22 at 16.12.13.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/cOL6QbQzyaUdOs5psinD/e140beef-6f91-4737-bd72-41253f90bef1.mp4" />](https://app.graphite.dev/media/video/cOL6QbQzyaUdOs5psinD/e140beef-6f91-4737-bd72-41253f90bef1.mp4)
=> feat: transfer to modal

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx, packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx, packages/frontend/src/components/common/ResourceView/ResourceActionHandlers.tsx, packages/frontend/src/components/common/TransferItemsModal/TransferItemsModal.tsx
Partially implements: #14420
[CleanShot 2025-04-22 at 17.52.56.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/cOL6QbQzyaUdOs5psinD/cd679c90-51b8-4f5e-a259-86bdfa8f127a.mp4" />](https://app.graphite.dev/media/video/cOL6QbQzyaUdOs5psinD/cd679c90-51b8-4f5e-a259-86bdfa8f127a.mp4)
=> feat: create space within transfer modal (only nested)

.gitignore
Ignores prometheus configuration when running locally
=> chore: add prometheus files to gitignore

packages/backend/src/knexfile.ts
Simple docs explaining the parameters for the knex connection pool, we may use this for tuning in future.
=> docs: add knex config docs to knefile.ts

packages/backend/src/services/ProjectService/ProjectService.ts
Closes: #14510
**Before**
With 1 y-axis field
With 2 y-axis fields
**After**
With 1 y-axis field
With 2 y-axis fields
=> fix: enforce limit on pivoted columns

packages/backend/src/queryBuilder.test.ts
Closes: N/A
fixes backend build
test-backend
=> fix: backend build

package.json, scripts/build.sh
=> chore: add mantine v7 build in build.sh

packages/e2e/cypress/e2e/app/savedDashboards.cy.ts, packages/frontend/src/components/common/modal/DashboardUpdateModal.tsx, packages/frontend/src/stories/Modal.stories.tsx
Closes: N/A
Updated this component to use MantineModal
Added a storybook example with dev notes - lmk if this is not the right place to do this.
=> style: make DashboardUpdateModal a MantineModal

packages/backend/src/models/SavedChartModel.ts
Closes: [#14445](https://github.com/lightdash/lightdash/issues/14445)
Fetching 3700 rows.
Before: > 10 seconds
After: < 1second
More in slack thread https://lightdash.slack.com/archives/C08N5JUL57V/p1744818106153039
=> fix: get project charts last version CTE

packages/backend/src/services/UserService.ts
Closes: 
Missing code from https://github.com/lightdash/lightdash/pull/14429/files
=> fix: get cached user

packages/frontend/src/components/common/modal/DashboardCreateModal.tsx
=> style: turn DashboardCreateModal into a MantineModal

packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/models/ContentModel/ContentConfigurations/DashboardContentConfiguration.ts, packages/backend/src/models/ContentModel/ContentConfigurations/DbtExploreChartContentConfiguration.ts, packages/backend/src/models/ContentModel/ContentConfigurations/SemanticViewerChartContentConfiguration.ts, packages/backend/src/models/ContentModel/ContentConfigurations/SpaceContentConfiguration.ts, packages/backend/src/models/ContentModel/ContentConfigurations/SqlChartContentConfiguration.ts, packages/backend/src/models/ContentModel/ContentModel.ts, packages/backend/src/models/ContentModel/ContentModelTypes.ts, packages/frontend/src/components/common/ResourceView/InfiniteResourceTable.tsx
Closes: N/A
Sets up a ranking system between content types
Brings back sorting on columns that was removed accidentally here https://github.com/lightdash/lightdash/pull/14428/files#diff-9ac1d71c2b519de99e4cdeae397a203a4a61e846671ed240c68be0e483f2fde4
=> feat: order content by rank

packages/frontend/src/components/DashboardFilter/FilterConfiguration/TileFilterConfiguration.tsx, packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx, packages/frontend/src/components/DashboardTiles/TileForms/TileAddModal.tsx, packages/frontend/src/components/common/ResourceIcon/index.tsx, packages/frontend/src/components/common/ResourceView/ContentTypeFilter.tsx, packages/frontend/src/components/common/ResourceView/InfiniteResourceTable.tsx, packages/frontend/src/features/omnibar/components/OmnibarItemIcon.tsx, packages/frontend/src/features/omnibar/components/utils.ts, packages/frontend/src/pages/Space.tsx, packages/frontend/src/pages/SpacesV2.tsx
Relates to: #14402
Done the below:
**Table**
**Space Row**
=> style: apply some changes to Space UI

packages/frontend/src/components/common/SpaceSelector/SpaceSelector.tsx, packages/frontend/src/components/common/TransferItemsModal/TransferItemsModal.tsx, packages/frontend/src/components/common/Tree/Tree.tsx, packages/frontend/src/components/common/Tree/TreeItem.tsx
Closes: 
explanation:
[CleanShot 2025-04-24 at 19.33.14.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/cOL6QbQzyaUdOs5psinD/568e9e42-6a1c-4a94-8504-9768468f80cc.mp4" />](https://app.graphite.dev/media/video/cOL6QbQzyaUdOs5psinD/568e9e42-6a1c-4a94-8504-9768468f80cc.mp4)
=> style: tree component visual improvements

packages/frontend/src/components/common/SpaceSelector/SpaceCreationForm.tsx, packages/frontend/src/components/common/TransferItemsModal/TransferItemsModal.tsx
Closes: 
video explanation:
[CleanShot 2025-04-24 at 19.46.44.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/cOL6QbQzyaUdOs5psinD/6a600999-e5fe-4ebc-bbb6-8d52032061bf.mp4" />](https://app.graphite.dev/media/video/cOL6QbQzyaUdOs5psinD/6a600999-e5fe-4ebc-bbb6-8d52032061bf.mp4)
=> feat: allow creating of root level spaces from the transfer to modal

packages/frontend/src/hooks/analytics/useUserActivity.tsx, packages/frontend/src/pages/UserActivity.tsx
=> fix: improve UI export CSV analytics

packages/frontend/src/components/common/ResourceView/AdminContentViewFilter.tsx, packages/frontend/src/components/common/SpaceSelector/SpaceSelector.tsx, packages/frontend/src/components/common/TransferItemsModal/TransferItemsModal.tsx, packages/frontend/src/components/common/modal/ChartCreateModal/SaveToSpaceForm.tsx
Closes: https://github.com/lightdash/lightdash/issues/14500
[CleanShot 2025-04-24 at 20.18.36.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/cOL6QbQzyaUdOs5psinD/e02edb25-b1c1-49b7-b37a-b9e16c05c438.mp4" />](https://app.graphite.dev/media/video/cOL6QbQzyaUdOs5psinD/e02edb25-b1c1-49b7-b37a-b9e16c05c438.mp4)
=> feat: admin content view for space tree selector

packages/frontend/src/components/common/Tree/TreeItem.tsx
Closes: 
[CleanShot 2025-04-25 at 11.55.07.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/cOL6QbQzyaUdOs5psinD/e17ffb02-c436-42f8-8256-da41ba468fa5.mp4" />](https://app.graphite.dev/media/video/cOL6QbQzyaUdOs5psinD/e17ffb02-c436-42f8-8256-da41ba468fa5.mp4)
=> style: tree component item should expand to 100%

packages/frontend/src/components/common/SpaceSelector/SpaceSelector.tsx, packages/frontend/src/components/common/TransferItemsModal/TransferItemsModal.tsx
=> style: tree component height

packages/e2e/cypress/e2e/app/dashboard.cy.ts, packages/frontend/src/components/common/modal/DashboardCreateModal.tsx
- Fixes e2e test taking into account new spaces modal
test-frontend
=> fix: e2e dashboard export tests

packages/common/src/types/featureFlags.ts, packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx, packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx, packages/frontend/src/components/common/ResourceView/ResourceActionHandlers.tsx, packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx, packages/frontend/src/components/common/ResourceView/types.ts, packages/frontend/src/components/common/SpaceSelector/SpaceSelector.tsx, packages/frontend/src/components/common/modal/ChartCreateModal/SaveToSpaceForm.tsx, packages/frontend/src/components/common/modal/ChartCreateModal/SaveToSpaceOrDashboard.tsx, packages/frontend/src/components/common/modal/DashboardCreateModal.tsx, packages/frontend/src/features/sqlRunner/components/SaveSqlChartModal.tsx, packages/frontend/src/features/sqlRunner/components/UpdateSqlChartModal.tsx, packages/frontend/src/pages/Space.tsx
Closes: #14564
Removes feature-flag checks for `nested-spaces`
=> chore: remove nested-spaces feature flag checks

packages/e2e/cypress/e2e/app/space.cy.ts, packages/frontend/src/pages/Space.tsx
Closes: #N/A
Added a data-testid attribute to the Space add button and updated the E2E test to use this attribute for more reliable test selection. Also improved the navigation in the test by using direct URL visit and more specific space name selection.
=> chore: fix e2e test for spaces

packages/backend/src/controllers/v2/ProjectController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/models/QueryHistoryModel.ts, packages/backend/src/services/ProjectService/ProjectService.ts, packages/frontend/src/hooks/useQueryResults.ts, packages/frontend/src/providers/Explorer/ExplorerProvider.tsx
Relates to: [1406](https://github.com/lightdash/lightdash/issues/1406)
Mark query as cancelled in our DB.
=> feat: cancel query endpoint

render.yaml
Closes: 
Increase preview environment database resources so e2e tests can run faster and without errors.
Changes:
- increase max database connections
- increase database cpu & memory
=> chore(devx): increase preview database resources

packages/backend/src/controllers/v2/ProjectController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/ProjectService/ProjectService.ts, packages/common/src/types/api/paginatedQuery.ts, packages/e2e/cypress/e2e/api/async-query.cy.ts, packages/frontend/src/components/MetricQueryData/UnderlyingDataModalContent.tsx, packages/frontend/src/hooks/dashboard/useDashboardChartReadyQuery.ts, packages/frontend/src/hooks/useQueryResults.ts, packages/frontend/src/hooks/useUnderlyingDataResults.ts
Closes: #14394
**Old endpoints**
- `POST /api/v2/projects/{projectUuid}/query`
**New endpoints**
- `POST /api/v2/projects/{projectUuid}/query/metric-query`
- `POST /api/v2/projects/{projectUuid}/query/chart`
- `POST /api/v2/projects/{projectUuid}/query/dashboard-chart`
- `POST /api/v2/projects/{projectUuid}/query/underlying-data`
Note: scheduled deliveries should still work
test-frontend
=> fix: split query execute endpoint

packages/frontend/src/components/common/ResourceView/AdminContentViewFilter.tsx, packages/frontend/src/components/common/SpaceSelector/SpaceSelector.tsx, packages/frontend/src/components/common/TransferItemsModal/TransferItemsModal.tsx
Closes: 
[CleanShot 2025-04-29 at 17.20.13.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/cOL6QbQzyaUdOs5psinD/46c45ce1-720f-4184-b194-76261f0cdaba.mp4" />](https://app.graphite.dev/media/video/cOL6QbQzyaUdOs5psinD/46c45ce1-720f-4184-b194-76261f0cdaba.mp4)
=> style: polish space selector

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/CustomVis/utils/vegaTemplates.tsx
Closes: 
These marks will not be used on the chart, but it is useful for us to track the "template" the user is using on analytics
=> chore: add custom mark to vega templates for analytics

packages/frontend/src/hooks/useQueryResults.ts
=> fix: query refetch after cancelation

packages/backend/src/clients/Slack/SlackClient.ts
Closes: #14597 
DM channel now has pdf attachment
> [!IMPORTANT]
> This requires updating scope of slack app to also have "im:write"
=> fix: slack upload pdf on dm channel

packages/frontend/src/hooks/useQueryResults.ts
Related PR: https://github.com/lightdash/lightdash/pull/14603/files
**Before**
https://github.com/user-attachments/assets/e30e301e-87c0-4782-b586-69f6eac4eb66
**After**
https://github.com/user-attachments/assets/2f05e972-dce6-42af-9e0b-6c788c88ff58
=> fix: query key invalidation in paginated queries

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx, packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
- Fixes argument types for `TransferItemsModal` component
=> fix: transfer items modal props

packages/frontend/src/components/common/SpaceSelector/SpaceSelector.tsx, packages/frontend/src/components/common/Tree/Tree.tsx, packages/frontend/src/components/common/Tree/useFuzzyTreeSearch.ts, packages/frontend/src/hooks/useFuzzySearch.ts
related to: #14550
part 1 of tree search.
=> feat: add fuzzy search and fuzzy tree search hooks

packages/cli/src/index.ts
Closes:  https://github.com/lightdash/lightdash/issues/14641
Before
After
=> fix: add defer to cli compile

packages/common/src/utils/formatting.test.ts
Closes: N/A
formatting.test.ts wasn't running all tests.
=> test: remove .only in formatting.test.ts

packages/backend/src/controllers/v2/ProjectController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/ProjectService/ProjectService.ts, packages/backend/src/services/ProjectService/types.ts, packages/common/src/types/api/paginatedQuery.ts
Relates to: #14588 
Adds an endpoint for running SQL asynchronously using the paginated endpoints.
=> chore: add async, paged sql endpoint

packages/backend/src/database/seeds/development/05_nested_spaces.ts, packages/backend/src/models/ProjectModel/ProjectModel.ts, packages/backend/src/models/SpaceModel.ts, packages/backend/src/services/CoderService/CoderService.ts, packages/backend/src/services/PromoteService/PromoteService.mock.ts, packages/backend/src/services/PromoteService/PromoteService.test.ts, packages/backend/src/services/PromoteService/PromoteService.ts, packages/backend/src/services/SpaceService/SpaceService.ts, packages/backend/src/utils/SlugUtils.ts, packages/common/src/types/promotion.ts, packages/common/src/utils/slug.test.ts, packages/common/src/utils/slugs.ts, packages/e2e/cypress/e2e/api/nestedSpaces.cy.ts
Closes: #14642
test-backend
test-frontend
test-cli
=> fix: generate unique space slugs and use ltree paths

packages/backend/src/services/PromoteService/PromoteService.mock.ts, packages/backend/src/services/PromoteService/PromoteService.test.ts, packages/backend/src/services/PromoteService/PromoteService.ts
Closes: N/A
Related to: #14643
This PR fixes the `PromoteService` tests
=> fix: PromoteService tests

packages/backend/src/models/SpaceModel.ts, packages/backend/src/services/CoderService/CoderService.ts, packages/common/src/utils/slug.test.ts, packages/common/src/utils/slugs.ts
=> fix: content as code with space path

packages/backend/src/services/CoderService/CoderService.ts, packages/backend/src/services/PromoteService/PromoteService.ts
=> chore: remove all todos and fixmes

packages/e2e/package.json, pnpm-lock.yaml
Closes: 
Update e2e dependencies
Force test:
test-frontend
=> chore(devx): update e2e dependencies

packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
Closes: #14628 
- Adds ability to apply dashboard filters and sorts to sql charts
https://github.com/user-attachments/assets/ede62acf-4845-414a-a304-3bece8af89d9
=> feat: add dashboard filters to dashboard sql chart endpoint

packages/frontend/package.json, packages/frontend/src/index.tsx, pnpm-lock.yaml
Closes: N/A
https://github.com/aidenybai/react-scan/blob/main/docs/installation/vite.md
Added React Scan to the frontend package to help with component debugging and performance optimization in development mode. React Scan provides insights into component rendering behavior and helps identify potential performance bottlenecks.
Configured to only run in development environments
=> chore: add react-scan for dev

packages/frontend/src/providers/App/AppProvider.tsx
Closes: N/A
This isn't used anywhere
=> chore: remove unused drawer in AppProvider

packages/backend/src/ee/services/EmbedService/EmbedService.ts
=> fix: 403 error when embedding dashboards with "Allow all dashboards" option

packages/backend/src/controllers/spaceController.ts, packages/backend/src/controllers/v2/ContentController.ts, packages/backend/src/database/entities/dashboards.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/models/ContentModel/ContentModel.ts, packages/backend/src/models/DashboardModel/DashboardModel.ts, packages/backend/src/models/SavedChartModel.ts, packages/backend/src/models/SavedSemanticViewerChartModel.ts, packages/backend/src/models/SavedSqlModel.ts, packages/backend/src/models/SpaceModel.ts, packages/backend/src/services/ContentService/ContentService.ts, packages/backend/src/services/DashboardService/DashboardService.ts, packages/backend/src/services/SavedChartsService/SavedChartService.ts, packages/backend/src/services/SavedSemanticViewerChartService/SavedSemanticViewerChartService.ts, packages/backend/src/services/SavedSqlService/SavedSqlService.ts, packages/backend/src/services/SemanticLayerService/SemanticLayerService.ts, packages/backend/src/services/ServiceRepository.ts, packages/backend/src/services/SpaceService/SpaceService.ts, packages/common/src/types/content.ts, packages/common/src/types/resourceViewItem.ts, packages/frontend/src/Routes.tsx, packages/frontend/src/components/common/ResourceView/InfiniteResourceTable.tsx, packages/frontend/src/hooks/useContent.ts, packages/frontend/src/pages/Space.tsx, packages/frontend/src/pages/Spaces.tsx, packages/frontend/src/pages/SpacesV2.tsx
Closes: https://github.com/lightdash/lightdash/issues/14323
=> feat: resource bulk actions - move to another space

packages/frontend/src/components/common/ResourceView/InfiniteResourceTable.tsx, packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx
=> feat: ui/ux improvements for bulk selection actions

packages/frontend/src/components/common/SpaceSelector/SpaceSelector.tsx, packages/frontend/src/components/common/TransferItemsModal/TransferItemsModal.tsx
=> feat: adjust transfer items modal size

packages/frontend/src/components/common/SpaceSelector/SpaceSelector.tsx
=> fix: <admins should see all content in tree selector

packages/backend/src/controllers/spaceController.ts, packages/backend/src/controllers/v2/ContentController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/models/SavedChartModel.ts, packages/backend/src/services/ContentService/ContentService.ts, packages/backend/src/services/SavedChartsService/SavedChartService.ts, packages/common/src/types/content.ts, packages/common/src/types/space.ts, packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx, packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx, packages/frontend/src/components/common/ResourceView/InfiniteResourceTable.tsx, packages/frontend/src/components/common/ResourceView/ResourceActionHandlers.tsx, packages/frontend/src/components/common/modal/MoveChartThatBelongsToDashboardModal.tsx, packages/frontend/src/hooks/dashboard/useDashboard.ts, packages/frontend/src/hooks/useContent.ts, packages/frontend/src/hooks/useSavedQuery.ts, packages/frontend/src/hooks/useSpaces.ts, packages/frontend/src/pages/Dashboard.tsx, packages/frontend/src/pages/Space.tsx
=> feat: unify all content item actions (only move so far) bulk or single

packages/backend/src/analytics/LightdashAnalytics.ts, packages/backend/src/controllers/renameController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/RenameService/RenameService.ts, packages/backend/src/services/RenameService/rename.mock.ts, packages/backend/src/services/RenameService/rename.test.ts, packages/backend/src/services/RenameService/rename.ts, packages/backend/src/services/ServiceRepository.ts, packages/backend/src/services/ValidationService/ValidationService.ts, packages/cli/src/handlers/dbt/refresh.ts, packages/cli/src/handlers/renameHandler.ts, packages/cli/src/index.ts, packages/common/src/types/rename.ts, packages/frontend/src/components/SettingsValidator/ValidatorTable/hooks/useRenameResource.ts, packages/frontend/src/components/SettingsValidator/ValidatorTable/index.tsx, packages/frontend/src/components/SettingsValidator/index.tsx, packages/frontend/src/components/SettingsValidator/utils/utils.ts, packages/frontend/src/hooks/validation/useValidation.ts
=> feat: rename UI

packages/backend/src/App.ts, packages/backend/src/SchedulerApp.ts, packages/backend/src/analytics/LightdashAnalytics.ts, packages/backend/src/controllers/renameController.ts, packages/backend/src/ee/index.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/models/DashboardModel/DashboardModel.ts, packages/backend/src/models/SavedChartModel.ts, packages/backend/src/scheduler/SchedulerTask.ts, packages/backend/src/scheduler/SchedulerTaskTracer.ts, packages/backend/src/scheduler/SchedulerWorker.ts, packages/backend/src/services/RenameService/RenameService.ts, packages/backend/src/services/RenameService/rename.mock.ts, packages/backend/src/services/RenameService/rename.test.ts, packages/backend/src/services/RenameService/rename.ts, packages/backend/src/services/ServiceRepository.ts, packages/backend/src/services/ValidationService/ValidationService.ts, packages/cli/src/handlers/dbt/refresh.ts, packages/cli/src/handlers/renameHandler.ts, packages/cli/src/handlers/validate.ts, packages/cli/src/index.ts, packages/common/src/index.ts, packages/common/src/types/rename.ts, packages/common/src/types/schedulerTaskList.ts, packages/e2e/cypress/e2e/api/rename.cy.ts, packages/frontend/src/components/SettingsValidator/ValidatorTable/hooks/useRenameResource.ts, packages/frontend/src/components/SettingsValidator/ValidatorTable/index.tsx, packages/frontend/src/components/SettingsValidator/index.tsx, packages/frontend/src/components/SettingsValidator/utils/utils.ts
Closes:  https://github.com/lightdash/lightdash/issues/5264
[Screencast from 2025-05-09 15-53-25.webm](https://github.com/user-attachments/assets/9f8b563d-d3ec-4be5-b6d4-4b0c70ef6460)
=> feat: rename models and fields in CLI and UI 

.github/CONTRIBUTING.md
Relates to: https://github.com/lightdash/lightdash/pull/14746
=> chore: add docs about /etc/hosts/ for minio file download

packages/backend/src/@types/knex-tables.d.ts
=> chore: amend import

dockerfile, dockerfile-prs
Closes: #14777 
Uncommenting the installation of dbt-trino 1.9.0 because it got available.
=> fix: uncomment dbt-trino 1.9.0 installation

packages/backend/src/ee/index.ts, packages/backend/src/ee/services/CommercialCacheService.ts, packages/backend/src/models/ResultsFileModel/ResultsFileModel.ts, packages/backend/src/services/AsyncQueryService/AsyncQueryService.test.ts, packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts, packages/backend/src/services/CacheService/ICacheService.ts, packages/backend/src/services/ServiceRepository.ts
Related to: #14730
Closes: [#14731](https://github.com/lightdash/lightdash/issues/14731)
Moves results file logic from cache service to async query service. 
Keeps results file & cache logic intact.
=> chore: move results file logic from cache service

packages/frontend/src/components/common/Table/Table.styles.ts, packages/frontend/src/components/common/Table/TableProvider.tsx, packages/frontend/src/hooks/useColumns.tsx
Closes: #14683 
This PR fixes the frozen columns for Table Chart. 
https://github.com/user-attachments/assets/8642131b-4647-4937-9b56-f52794bead37
=> fix: frozen columns not working in Table Chart

packages/backend/src/database/seeds/development/04_groups.ts, packages/backend/src/database/seeds/development/05_nested_spaces.ts, packages/common/src/index.ts, packages/e2e/cypress/e2e/app/space.cy.ts, packages/e2e/cypress/screenshots/.gitignore, packages/e2e/cypress/videos/.gitignore, packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx, packages/frontend/src/components/common/modal/DashboardCreateModal.tsx, packages/frontend/src/hooks/dashboard/useDashboard.ts
Closes: N/A
- Added a new seed group for editors and associated the editor user with this group
- Added a new parent space (Parent Space 5) with group access for the editor group
=> chore: improve seeder and e2e tests for spaces

packages/e2e/cypress/e2e/app/space.cy.ts
Closes: n/a
test-e2e
improved e2e tests for spaces
=> chore: improved e2e tests for spaces

packages/backend/src/services/AsyncQueryService/AsyncQueryService.test.ts, packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts, packages/backend/src/services/AsyncQueryService/types.ts
Relates to: [#14709](https://github.com/lightdash/lightdash/issues/14709)
Extract SQL generation and Field overrides from the `executeAsyncQuery()`.
=> chore: remove query compilation from executeAsyncQuery

release.config.js
=> fix: unterminated quoted string in the release action

packages/backend/src/database/migrations/20250514072535_increase_scheduler_log_target_size.ts
Closes: 
Thread: https://lightdash.slack.com/archives/C03MCQ08UKS/p1747153095873909
MS teams webhooks can be larger than 255
=> fix: increase scheduler log target migration

packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
Relates to: https://github.com/lightdash/lightdash/pull/14758
- Return the error before checking for results file existence.
**Before**
**After**
=> fix: return query error before checking if theres a results file

packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/RenameService/rename.ts, packages/backend/src/services/ValidationService/ValidationService.ts, packages/common/src/types/filter.ts, packages/common/src/utils/filters.ts, packages/frontend/src/components/DashboardFilter/FilterConfiguration/TileFilterConfiguration.tsx, packages/frontend/src/components/common/Filters/FilterInputs/utils.ts
Closes: 
New type in preparation for dashboard filter tile target to work on SQL charts.
=> fix: support reference target for dashboard filters

packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
=> fix: pivot table loading state in explorer

packages/backend/src/ee/services/AiService/utils/aiCopilot/validators.ts, packages/backend/src/queryBuilder.ts, packages/common/src/compiler/exploreCompiler.ts, packages/common/src/compiler/filtersCompiler.mock.ts, packages/common/src/compiler/filtersCompiler.test.ts, packages/common/src/compiler/filtersCompiler.ts
=> chore: abstract filter util function to not require compiled field

packages/backend/src/App.ts, packages/backend/src/config/parseConfig.ts, packages/backend/src/models/ProjectModel/ProjectModel.ts, packages/backend/src/services/OrganizationService/OrganizationService.ts, packages/common/src/types/api.ts
This PR refactors the instance initialization process with several improvements:
1. Renamed `initializeProject()` to `initializeInstance()` to better reflect its purpose
2. Added prefix `LD_` to all setup environment variables for consistency
3. Enhanced API key configuration to support expiration time settings
- Added support for setting API key expiration days via `LD_SETUP_API_KEY_EXPIRATION`
- Setting this to 0 creates a non-expiring API key
4. Improved error handling and validation for enum values
5. Added support for configuring start of week via `LD_SETUP_START_OF_WEEK`
6. Optimized database query in `hasAnyProjects()` to use COUNT instead of fetching all projects
7. Restructured initialization flow to perform optional steps at the end
8. Added more detailed …
=> fix: review changes for initialize instance

packages/backend/src/App.ts, packages/backend/src/config/parseConfig.ts, packages/backend/src/models/DashboardModel/PersonalAccessTokenModel.ts, packages/backend/src/models/ProjectModel/ProjectModel.ts, packages/backend/src/models/UserModel.ts, packages/backend/src/services/OrganizationService/OrganizationService.test.ts, packages/backend/src/services/OrganizationService/OrganizationService.ts, packages/backend/src/services/ServiceRepository.ts, packages/common/src/types/api.ts
Closes: https://github.com/lightdash/lightdash-internal-work/issues/3338
New variables 
```
export SETUP_ADMIN_EMAIL='javier@lightdash.com'
export SETUP_ADMIN_NAME='Javier Rengel' # optional, default: Admin User
export SETUP_ORGANIZATION_NAME='Setup test org'
export SETUP_ORGANIZATION_EMAIL_DOMAIN='lightdash.com' # optional
export SETUP_ORGANIZATION_DEFAULT_ROLE='VIEWER' # optional
export SETUP_ADMIN_API_KEY='user provided api key'  # optional
export SETUP_PROJECT_NAME='Setup test project'
export SETUP_PROJECT_SCHEMA='jaffle'
export SETUP_PROJECT_HOST="dbc-....databricks.com"
export SETUP_PROJECT_HTTP_PATH="/sql/1.0/warehouses/..."
export SETUP_PROJECT_PAT="..."
export SETUP_GITHUB_PAT="ghp_..." 
export SETUP_GITHUB_REPOSITORY="rephus/jaffle_shop"
export SETUP_GITHUB_BRANCH="main"
export …
```
=> feat: initial setup with env variables

packages/frontend/src/ee/CommercialRoutes.tsx
=> fix: debug ai chat ui

examples/api/ai-agents.http, packages/backend/src/ee/controllers/aiAgentController.ts, packages/backend/src/ee/controllers/aiController.ts, packages/backend/src/ee/index.ts, packages/backend/src/ee/services/AiAgentService.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/services/ServiceRepository.ts, packages/common/src/ee/AiAgent/index.ts, packages/common/src/ee/index.ts
Closes: #14830
This PR adds the initial structure for AI Agents feature by:
1. Creating a new `AiAgentController` with endpoints for listing, getting, creating, and updating agents
2. Adding a new `AiAgentService` class to handle agent-related business logic
3. Defining TypeScript types for AI agents, threads, and messages in the common package
4. Adding HTTP examples for testing the new API endpoints
=> feat: Agent API v1 Spec

packages/backend/src/controllers/v2/QueryController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/queryBuilder.class.mocks.ts, packages/backend/src/queryBuilder.class.test.ts, packages/backend/src/queryBuilder.ts, packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts, packages/backend/src/services/AsyncQueryService/types.ts, packages/common/src/types/api/paginatedQuery.ts, packages/common/src/types/filter.ts, packages/common/src/utils/filters.ts, packages/frontend/src/features/queryRunner/sqlRunnerPivotQueries.ts, packages/frontend/src/features/sqlRunner/hooks/useSavedSqlChartResults.tsx, packages/frontend/src/features/sqlRunner/runners/SqlRunnerResultsRunnerFrontend.ts
Closes: [#14709](https://github.com/lightdash/lightdash/issues/14709)
=> feat(api): support dashboard filters with column references in sql charts

packages/common/src/types/featureFlags.ts, packages/frontend/src/components/DashboardFilter/FilterConfiguration/TileFilterConfiguration.tsx, packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx, packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx, packages/frontend/src/features/sqlRunner/hooks/useSavedSqlChartResults.tsx, packages/frontend/src/features/sqlRunner/runners/SqlRunnerResultsRunnerFrontend.ts, packages/frontend/src/providers/Dashboard/DashboardProvider.tsx, packages/frontend/src/providers/Dashboard/types.ts
Closes: [#14629](https://github.com/lightdash/lightdash/issues/14629)
Note: Table viz is not supported atm
=> feat: filter sql charts in dashboard

packages/frontend/src/components/SettingsValidator/index.tsx
Improves the UI of the validation error modal by:
1. Setting `maxHeight: 'fit-content !important'` for the modal content to ensure proper sizing
2. Changing the Group component's display property to 'inline-block' for better checkbox alignment
=> fix: validation rename tooltip

packages/frontend/src/components/MetricQueryData/DrillDownModal.tsx
Closes: #14196 
**Before**
https://github.com/user-attachments/assets/e4f2de4a-7083-457e-95b6-950af3ef8db5
**After**
https://github.com/user-attachments/assets/308a1b0c-365f-4dcb-9f0e-d3f5c57e6042
=> fix: drill down with custom dimensions

packages/backend/src/controllers/projectController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/routers/projectRouter.ts
Closes: #14905 
Refresh should still work:
test-frontend
=> chore: move refresh route into project controller

packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx, packages/frontend/src/ee/features/aiCopilot/components/ConversationsList.tsx, packages/frontend/src/ee/features/aiCopilot/components/ThreadDetailsModal.tsx, packages/frontend/src/ee/features/aiCopilot/hooks/useAiAgents.ts
=> chore: introduce conversations list

packages/common/src/ee/AiAgent/index.ts, packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx, packages/frontend/src/ee/features/aiCopilot/components/ConversationsList.tsx, packages/frontend/src/ee/features/aiCopilot/components/ThreadDetailsModal.tsx, packages/frontend/src/ee/features/aiCopilot/hooks/useAiAgents.ts
=> chore: formalise form schema for ai agent customisation

packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeGroupNode.tsx
Relates to: #14638
Updates Tree group node rendering:
- Takes out some inline handlers
- Memoizes some things that might help
- Tries to make the display names better for React Scan
=> chore: optimize Explore group tree node

examples/api/ai-agents.http, packages/backend/src/@types/knex-tables.d.ts, packages/backend/src/ee/controllers/aiAgentController.ts, packages/backend/src/ee/database/entities/aiAgent.ts, packages/backend/src/ee/models/AiAgentModel.ts, packages/backend/src/ee/services/AiAgentService.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/common/src/ee/AiAgent/index.ts, packages/common/src/index.ts, packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx, packages/frontend/src/ee/features/aiCopilot/components/AiAgents.tsx, packages/frontend/src/ee/features/aiCopilot/components/ConversationsList.tsx, packages/frontend/src/ee/features/aiCopilot/components/ThreadDetailsModal.tsx, packages/frontend/src/ee/features/aiCopilot/hooks/useAiAgents.ts
Implements React Query hooks for AI Agents functionality. The implementation includes:
- Query hooks for fetching agent lists, individual agents, threads, and thread details
- Mutation hooks for creating and updating agents
- Enhanced agent details UI with tabs for general settings and conversations
- Added conversation history view with thread details modal
- Updated AiAgent type to include name field
- Added projectUuid and name to ApiUpdateAiAgent interface
=> feat: ai agents

packages/backend/src/ee/controllers/aiAgentController.ts, packages/backend/src/ee/models/AiAgentModel.ts, packages/backend/src/ee/services/AiAgentService.ts, packages/backend/src/generated/routes.ts, packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx, packages/frontend/src/ee/features/aiCopilot/components/AiAgents.tsx, packages/frontend/src/ee/features/aiCopilot/hooks/useAiAgents.ts
Implements the "Get Agent" API endpoint and fixes the agent details view in the frontend. 
- Implementing the `getAgent` controller method that was previously throwing a `NotImplementedError`
- Fixing the SQL query in `AiAgentModel` to properly handle null integrations with `COALESCE` and `FILTER`
- Updating the frontend to correctly consume the agent data from the API
- Removing debug console.log statements from the agent form submission
=> feat: get ai agent (api+ui)

packages/backend/src/ee/controllers/aiAgentController.ts, packages/backend/src/ee/database/entities/aiAgent.ts, packages/backend/src/ee/models/AiAgentModel.ts, packages/backend/src/ee/services/AiAgentService.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/common/src/ee/AiAgent/index.ts, packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx, packages/frontend/src/ee/features/aiCopilot/components/AiAgents.tsx, packages/frontend/src/ee/features/aiCopilot/hooks/useAiAgents.ts
Implements the create agent functionality for AI Copilot. This PR:
- Implements the `createAgent` endpoint in the backend controller
- Adds the necessary model and service methods to create an AI agent
- Updates the database entity to make description and image_url nullable
- Adds the name field to the ApiCreateAiAgent type
- Connects the frontend form submission to the new API endpoint
=> feat: create/update ai agent (api+ui)

examples/api/ai-agents.http, packages/backend/src/@types/knex-tables.d.ts, packages/backend/src/ee/controllers/aiAgentController.ts, packages/backend/src/ee/database/entities/aiAgent.ts, packages/backend/src/ee/models/AiAgentModel.ts, packages/backend/src/ee/services/AiAgentService.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/common/src/ee/AiAgent/index.ts, packages/common/src/index.ts, packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx, packages/frontend/src/ee/features/aiCopilot/components/AiAgents.tsx, packages/frontend/src/ee/features/aiCopilot/components/ConversationsList.tsx, packages/frontend/src/ee/features/aiCopilot/components/ThreadDetailsModal.tsx, packages/frontend/src/ee/features/aiCopilot/hooks/useAiAgents.ts
Closes: https://github.com/lightdash/lightdash/issues/14916
=> feat: list ai agents

packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx
=> style: fix form spacing in agent detail view

packages/frontend/src/ee/features/aiCopilot/components/AgentAvatar.tsx, packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx, packages/frontend/src/ee/features/aiCopilot/components/AiAgents.tsx, packages/frontend/src/ee/features/aiCopilot/components/ThreadDetailsModal.tsx
=> style: make agent avatar consistent

packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx, packages/frontend/src/ee/features/aiCopilot/components/AiAgents.tsx
Closes: #14932
Added "Last modified" timestamps: 
- In the agent details view, showing when the agent was last updated
- As a new column in the agents table, making it easier to track recent changes
=> feat(frontend): display last modified timestamp for AI agents

packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx
Closes: #14945
Disables already-in-use channels from the multiselect
We can improve ux/messaging later
=> fix: disable slack channels already in use

packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx, packages/frontend/src/ee/features/aiCopilot/hooks/useAiAgents.ts
Closes: #14935
1. Simplified query key structure by using array format consistently
2. Fixed the return type of `updateAgent` to correctly use `ApiAiAgentResponse['results']`
3. Removed unnecessary navigation callback from `useUpdateAiAgentMutation` in AgentDetails component
=> fix: simplify query keys on useAiAgents hooks

docker-compose.yml
Closes: #14971 
- Adds MinIO container setup to `docker-compose.yml`
=> fix: add minio to oss docker compose

packages/frontend/src/hooks/useSpaceManagement.ts
Closes: #14930 
Before (check issue)
**After**
https://github.com/user-attachments/assets/873af19d-c8f5-4ec6-a829-c70a7d1882bf
=> fix: space management not updating the space uuid when reloading edit page

packages/backend/src/models/ResultsFileModel/ResultsFileModel.ts
=> feat: use version for results file model query cache key

packages/frontend/src/components/SettingsValidator/index.tsx
=> fix: rename UI default values

packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx, packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx, packages/frontend/src/components/common/Filters/FilterInputs/index.tsx
Related to: [#14969](https://github.com/lightdash/lightdash/issues/14969)
Allow filter input components to be rendered without a field.
=> chore: optional field in filter inputs

packages/backend/src/ee/services/CommercialSlackIntegrationService.ts, packages/backend/src/services/SlackIntegrationService/SlackIntegrationService.ts
Added permission checks to Slack integration methods to ensure users have appropriate access rights
=> fix: Slack integration api improvements

packages/backend/src/clients/Slack/SlackClient.ts, packages/backend/src/controllers/slackController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/frontend/src/components/SchedulersView/SchedulersView.tsx, packages/frontend/src/components/UserSettings/SlackSettingsPanel/index.tsx, packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx, packages/frontend/src/ee/features/aiCopilot/components/AiAgents.tsx, packages/frontend/src/features/scheduler/components/SchedulerForm.tsx, packages/frontend/src/hooks/slack/useSlack.ts
Closes: https://github.com/lightdash/lightdash/issues/14979
- adds extra options to slack channel backend
- refactors useSlackChannels
- updates UI for AI Agents page
=> feat: add options to exclude DMs and groups from Slack channels

packages/backend/src/@types/knex-tables.d.ts, packages/backend/src/ee/database/entities/aiAgent.ts, packages/backend/src/ee/database/migrations/20250523140213_add_ai_agent_instruction_versions_table.ts, packages/backend/src/ee/models/AiAgentModel.ts, packages/backend/src/ee/services/AiAgentService.ts, packages/backend/src/ee/services/AiService/AiService.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/common/src/ee/AiAgent/index.ts, packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx
Closes: #14876 
Added support for AI agent instructions/system prompts to configure agent behavior.
<details><summary>Preview 📸</summary>
</details> 
<details><summary>Instruction history</summary>
</details>
=> feat: introduce system prompts

packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx, packages/frontend/src/hooks/slack/useSlack.ts
Closes: #14975
Improved the Slack integration UI in agent details page by:
- Wrapping Slack channels selection in a Fieldset component for better organization
- Moved the "Refresh Channels" button into the channels label area for a cleaner layout
- Added loading state indicator during channel refresh operations
- Improved the refresh functionality to properly show loading state while fetching channels
[Screen Recording 2025-05-26 at 19.00.44.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/HorFj8gm8QUuuIDE2vgk/62c7f758-160d-4f3f-a626-b3e55c716baa.mov" />](https://app.graphite.dev/media/video/HorFj8gm8QUuuIDE2vgk/62c7f758-160d-4f3f-a626-b3e55c716baa.mov)
=> feat: Improve Slack integration UI in Agent details

packages/backend/src/ee/services/ScimService/ScimService.ts
Closes: [#15035](https://github.com/lightdash/lightdash/issues/15035)
Fixed a bug in the SCIM service where updating a group's name would fail if the group already had that name. The fix ensures that when checking for name uniqueness, we exclude the current group from the check to allow groups to keep their existing name during updates.
Also improved the code flow by checking if the group exists in the organization before performing other validations.
=> fix: enhance group update validation in ScimService

packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx, packages/frontend/src/features/queryRunner/executeQuery.ts, packages/frontend/src/features/queryRunner/sqlRunnerPivotQueries.ts, packages/frontend/src/features/sqlRunner/hooks/useSavedSqlChartResults.tsx, packages/frontend/src/features/sqlRunner/runners/SqlRunnerResultsRunnerFrontend.ts
Closes: 
Changes:
- stop requesting unpivoted results in dashboard tiles
- apply filters to table viz
=> feat: filter SQL chart with table viz

packages/backend/src/ee/database/entities/ai.ts, packages/backend/src/ee/models/AiAgentModel.ts, packages/backend/src/ee/services/AiAgentService.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/common/src/ee/AiAgent/index.ts
fix: display correct slack user names in Agent conversation history
=> fix: display correct slack user names in Agent conversation history

packages/backend/src/ee/clients/Slack/SlackBot.ts, packages/backend/src/ee/index.ts, packages/backend/src/ee/services/AiService/AiService.ts
Closes: https://github.com/lightdash/lightdash/issues/14977
=> feat: display agent name in Slack responses

packages/frontend/src/components/DashboardFilter/Filter.tsx, packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
Closes: [#15056](https://github.com/lightdash/lightdash/issues/15056)
**Before**
https://github.com/user-attachments/assets/70982bf8-efb4-40b8-91ed-1bee9a809cc5
**After**
https://github.com/user-attachments/assets/8fafbc3b-a66e-418e-bbaf-c57eaaf010d1
=> fix: set the correct table name when editing tile targets

packages/backend/src/ee/services/AiService/AiService.ts, packages/backend/src/ee/services/AiService/utils/aiCopilot/prompts.ts
=> feat: move agent name and instructions to prompt template

packages/frontend/src/ee/CommercialRoutes.tsx, packages/frontend/src/ee/pages/AiAgents/AgentsListPage.tsx, packages/frontend/src/mantine8Theme.ts, packages/frontend/src/mantineTheme.ts
Closes: 
Enhances the AI Agents UI with improved styling and theme consistency. I've created a new `getMantine8ThemeOverride` function to apply consistent styling to Mantine 8 components for this page.
<details> 
<summary>Screenshots</summary>
</details>
=> feat: Improved Agents UI

packages/backend/src/services/AsyncQueryService/AsyncQueryService.test.ts
Fixes AsyncQueryService.test.ts `should include original columns in pivotDetails for pivoted queries` test.
=> fix: increase resultsExpiresAt

packages/frontend/sdk/package.json
=> chore: frontend sdk version bump

packages/frontend/src/components/ProjectConnection/WarehouseForms/BigQueryForm.tsx
copy improvements for the bigquery form and new authentication types
=> fix: copy on bigquery form

packages/frontend/src/components/NavBar/AiAgentsButton.tsx, packages/frontend/src/components/NavBar/BrowseMenu.tsx, packages/frontend/src/components/NavBar/MainNavBarContent.tsx
Closes: #15141
Moving AI Agent navigation button from Explore menu to top navigation
I tried the brain icon to match the orgs settings, but looks like a nut?
wdyt?
=> feat: Make analyst top level navigation

packages/backend/src/ee/services/AiService/AiService.ts, packages/backend/src/ee/services/ai/agent.ts, packages/backend/src/ee/services/ai/types/aiAgent.ts, packages/backend/src/ee/services/ai/utils/getChatHistoryFromThreadMessages.ts, packages/common/src/ee/Ai/types.ts
=> refactor: replace AiChatMessage with CoreMessage from AI SDK

packages/backend/src/ee/services/AiService/AiService.ts, packages/backend/src/ee/services/ai/agent.ts, packages/backend/src/ee/services/ai/prompts/conversationHistory.ts, packages/backend/src/ee/services/ai/prompts/system.ts
Closes: [#15203](https://github.com/lightdash/lightdash/issues/15203)
=> refactor: move and improve AI agent system prompts

packages/backend/package.json, packages/backend/src/ee/services/AiService/AiService.ts, packages/backend/src/ee/services/ai/agents/agent.ts, packages/common/package.json, pnpm-lock.yaml
Closes: https://github.com/lightdash/lightdash/pull/15207
=> feat: add experimental tool call repair to AI agent

packages/backend/src/controllers/authentication/strategies/snowflakeStrategy.ts, packages/backend/src/services/ProjectService/ProjectService.ts, packages/backend/src/services/UserService.ts, packages/common/src/types/userWarehouseCredentials.ts, packages/frontend/src/components/ProjectConnection/WarehouseForms/SnowflakeForm.tsx, packages/frontend/src/components/UserSettings/MyWarehouseConnectionsPanel/CreateCredentialsModal.tsx, packages/frontend/src/components/UserSettings/MyWarehouseConnectionsPanel/WarehouseFormInputs.tsx
Closes:  https://github.com/lightdash/lightdash/issues/15173
Works for both explorer and sql runner 
[Screencast from 2025-06-05 15-35-06.webm](https://github.com/user-attachments/assets/e9fcbd02-4b2e-4e90-aad2-20b966e3b6aa)
=> feat: snowflake user specific credentials

packages/common/src/types/featureFlags.ts, packages/frontend/src/components/DashboardTabs/Tab.tsx, packages/frontend/src/components/DashboardTiles/AddTileButton.tsx, packages/frontend/src/components/common/modal/DashboardExportModal.tsx, packages/frontend/src/features/scheduler/components/SchedulerForm.tsx
Closes: #15198
Removes dashboard_tabs feature flag from the repo. Tabs will now be available to all customers. 
Depends on:
=> feat: productize dashboard for general availability

packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
Closes: #[issue number]
Fixed an issue with downloading pivoted query results by generating appropriate dimension fields from the query columns when pivot configuration is present. This ensures that pivoted data is correctly formatted when downloaded as CSV or Excel files.
```
curl --location 'http://localhost:3000/api/v2/projects/3675b69e-8324-4110-bdca-059031aa8da3/query/<query uuid>/download' \
--header 'Content-Type: application/json' \
--header 'Authorization: ApiKey <personal access token>' \
--data '{
"type": "csv",
"customLabels": {
"order_date": "date"
},
"columnOrder": ["order_date", "amount_sum"]
}'
```
=> fix: generate pivot fields for SQL query downloads

packages/backend/src/config/parseConfig.ts, packages/backend/src/ee/services/AiAgentService.ts
This PR adds support for configuring the OpenAI API key through the Lightdash configuration system rather than directly accessing it from environment variables. The changes include:
1. Extending the `LightdashConfig` type to include OpenAI provider configuration
2. Updating the config parser to read the OpenAI API key from environment variables
3. Adding a `getOpenAiApiKey()` method to the `AiAgentService` class
4. Refactoring the AI agent code to use the new method instead of directly accessing environment variables
This change improves the configuration management for AI features and removes TODO comments related to configuration.
=> feat: add OpenAI API key to config for AI Copilot

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatBubbles.tsx, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatInput.tsx
Closes: #15186, #15187
This PR enhances the AI Copilot chat interface with several UX improvements:
1. Hides the user's own name in chat bubbles when they are the sender
2. Adds a tooltip to the thumbs-up button that appears when feedback has been sent
3. Replaces the user avatar and name in the chat input with a disclaimer about agent accuracy
4. Improves date formatting in message timestamps
=> fix: Agent UI fixes from feedback

packages/backend/src/models/SpaceModel.ts
=> fix: improve filtering

packages/backend/src/models/SpaceModel.ts
test-backend
test-frontend
test-cli
=> fix: improve space movement with project scoping and cycle detection

packages/backend/src/controllers/exploreController.ts, packages/backend/src/controllers/savedChartController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/middlewares/deprecation.ts
Closes: #15013
Added deprecation middleware that adds the `warning` header:
=> chore: deprecate /downloadCsv

packages/backend/src/App.ts, packages/backend/src/SchedulerApp.ts, packages/backend/src/analytics/LightdashAnalytics.ts, packages/backend/src/clients/EmailClient/templates/dashboardCsvNotification.html, packages/backend/src/ee/index.ts, packages/backend/src/scheduler/SchedulerTask.ts, packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts, packages/backend/src/services/CsvService/CsvService.ts, packages/common/src/types/scheduler.ts, packages/frontend/src/components/SchedulersView/SchedulersView.tsx, packages/frontend/src/components/SchedulersView/SchedulersViewUtils.tsx, packages/frontend/src/features/scheduler/components/SchedulerForm.tsx
Closes: #15205 
Added support for XLSX format in scheduled deliveries. Users can now export data to Excel files in addition to CSV and Google Sheets. The implementation leverages the AsyncQueryService to handle large datasets efficiently and includes proper analytics tracking for the new format.
The XLSX option is now available in the scheduler form UI alongside the existing CSV, Image, and Google Sheets options.
Email:
Slack message:
=> feat: add XLSX format option for scheduled deliveries

packages/backend/src/ee/controllers/aiAgentController.ts, packages/backend/src/ee/index.ts, packages/backend/src/ee/services/AiAgentService.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/common/src/ee/AiAgent/index.ts, packages/common/src/index.ts
- Enable "View Underlying Data" for AI-generated visualizations
- Use paginated query api for fetching chart data
=> feat: stream query results for AI Agent charts

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatBubbles.tsx, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AiChartVisualization.tsx, packages/frontend/src/ee/features/aiCopilot/utils/echarts.ts, packages/frontend/src/ee/features/aiCopilot/utils/getAiAgentChartConfig.ts, packages/frontend/src/ee/features/aiCopilot/utils/getOpenInExploreUrl.ts
This change enables users to create more complex visualizations directly from AI Copilot conversations and seamlessly transition to the Explore view with the pivot configuration preserved.
=> feat: continue exploring pivoted bar chart from AI Agent

packages/frontend/src/components/NavBar/AiAgentsButton.tsx
Refactored `AiAgentsButton` so it only fetches information if feature flags are enabled
=> fix: trying to pull AI Agents without FF

packages/backend/src/scheduler/SchedulerTask.ts, packages/common/src/utils/charts.ts, packages/frontend/src/features/sqlRunner/components/Download/ResultsDownloadButton.tsx
Closes: #15342
- Support for custom labels, hidden files and column order support.
- Extracted helpers to be re-used in BE & FE
=> feat: add custom labels, hidden files and column order support for SQL chart scheduled delivery

packages/backend/src/scheduler/SchedulerTask.ts, packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts, packages/backend/src/services/AsyncQueryService/types.ts, packages/common/src/types/api/paginatedQuery.ts
Closes: #15341
Support limits for scheduled deliveries
=> feat: support limits for scheduled deliveries

packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts
- Adds info logs to compileAllExplores
=> fix: add info logs to compile all explores

packages/backend/src/controllers/v2/QueryController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx, packages/frontend/src/components/ExportResults/index.tsx, packages/frontend/src/hooks/dashboard/useDashboardChartDownload.ts
Closes: #15408
Bringing back dashboard tile download limits, fully supported by streaming!
=> feat: dashboard chart tile download limit (is back!)

packages/backend/src/ee/index.ts, packages/backend/src/models/ModelRepository.ts
=> fix: service account model no license

packages/backend/src/clients/EmailClient/EmailClient.mock.ts, packages/backend/src/clients/EmailClient/EmailClient.test.ts, packages/backend/src/clients/EmailClient/EmailClient.ts, packages/backend/src/scheduler/SchedulerClient.ts
Closes: #15364
Implemented a retry mechanism (3×2 in total), as well as increased timeout config aligned with Nodemailer defaults and RFC 5321
=> feat: retry mechanism and increased timeouts for the email client

packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx, packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeProvider.tsx, packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/types.ts, packages/frontend/src/components/Explorer/ExploreTree/TableTree/index.tsx, packages/frontend/src/components/Explorer/ExploreTree/index.tsx
Closes: #15337 
**Before**
https://github.com/user-attachments/assets/f5ce30f8-753a-4811-85ee-d70770a5e2a2
**After**
https://github.com/user-attachments/assets/ea3ebdf6-6f18-4264-9b9e-99fb946878d1
=> fix: improve search performance for sidebars with a lot of content

packages/frontend/src/pages/Dashboard.tsx
Closes: #15461
See ticket for clarification
=> fix: get private spaces when moving dashboard - admin view

.github/CONTRIBUTING.md, packages/backend/src/database/seeds/development/01_initial_user.ts
we still use dbt 1.4 in dev, which is not commonly used. this makes the dev environment up to date with newer dbt features
=> chore: use dbt1.7 in dev environment

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatInput.tsx
Closes: https://github.com/lightdash/lightdash/issues/15483
Fixed an issue with the AgentChatInput component where pressing Enter would submit the form while users were still composing characters in languages that use Input Method Editors (IME), such as Chinese, Japanese, or Korean.
Added event listeners for composition events to track when a user is in the middle of composing a character, and prevent form submission during this state. Also updated the submit button to be disabled during composition and changed its radius from "md" to "xl" for better visual appearance.
[CleanShot 2025-06-23 at 20.31.54.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/cOL6QbQzyaUdOs5psinD/8618954b-28 …
=> fix: prevent Enter key submission during character composition

packages/frontend/src/ee/features/aiCopilot/hooks/useProjectAiAgents.ts, packages/frontend/src/ee/features/aiCopilot/hooks/useUserAgentPreferences.ts, packages/frontend/src/ee/pages/AiAgents/AgentsWelcome.tsx
Closes: https://github.com/lightdash/lightdash/issues/15457
Enhanced AI Agent feature with improved loading states and feature flag checks. The PR adds proper loading indicators and redirects when AI features are not enabled. It also extends the query hooks to accept additional options, allowing for more flexible control over query behavior, including custom error handling and conditional execution.
=> feat: add feature flag checks and loading states to AI agents page

packages/frontend/package.json, packages/frontend/src/api.ts, packages/frontend/src/ee/features/aiCopilot/streaming/AiAgentThreadStreamAbortControllerContext.tsx, packages/frontend/src/ee/features/aiCopilot/streaming/AiAgentThreadStreamAbortControllerContextProvider.tsx, packages/frontend/src/ee/features/aiCopilot/streaming/AiAgentThreadStreamStore.ts, packages/frontend/src/ee/features/aiCopilot/streaming/AiAgentThreadStreamStoreProvider.tsx, packages/frontend/src/ee/features/aiCopilot/streaming/useAiAgentThreadStreamMutation.ts, packages/frontend/src/ee/features/aiCopilot/streaming/useAiAgentThreadStreamQuery.ts, pnpm-lock.yaml
Related: #15360
Frontend state management for streaming AI agent thread responses.
- Adds the `ai` package for processing data streams
- Creates a new `lightdashApiStream` function to handle streaming API responses
- Implements a Redux store for managing streaming state with actions for starting, appending, stopping, and handling errors
- Adds an abort controller context to manage cancellation of streaming requests
- Creates custom hooks for streaming mutations and queries
=> feat: AI Agent stream state management

packages/frontend/src/ee/CommercialRoutes.tsx, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatBubbles.tsx, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatDisplay.tsx, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ScrollToBottom.tsx, packages/frontend/src/ee/features/aiCopilot/components/ThreadDetailsModal.tsx, packages/frontend/src/ee/features/aiCopilot/hooks/useOrganizationAiAgents.ts, packages/frontend/src/ee/features/aiCopilot/utils/thinkingMessageStub.ts, packages/frontend/src/ee/pages/AiAgents/AgentThreadPage.tsx, packages/frontend/src/ee/pages/AiAgents/AiAgentNewThreadPage.tsx
Closes: #15360
Implemented real-time streaming for AI agent responses in the chat interface. This enhancement replaces the static "Thinking..." message with a live-updating response that shows the AI's output as it's being generated.
Key improvements:
- Added a streaming store provider to manage streaming state across components
- Created a dedicated ScrollToBottom component that intelligently handles auto-scrolling during streaming
- Refactored API calls to support streaming responses
- Implemented optimistic UI updates with proper loading states
- Improved the user experience by showing real-time typing feedback instead of a static loading indicator
=> feat(frontend): streaming support for AI Agent thread responses

packages/backend/src/utils/QueryBuilder/queryBuilder.mock.ts, packages/backend/src/utils/QueryBuilder/queryBuilder.test.ts
Closes: #XXX
This PR enhances the query builder with several new features:
1. Added support for required filters on joined tables, allowing constraints to be applied across table relationships
2. Implemented proper sorting for time-based dimensions:
- Month name sorting (January, February, etc.)
- Day of week name sorting (Sunday, Monday, etc.)
3. Added support for custom SQL dimensions in metric queries
The changes include new test cases and mock data to verify these features work correctly across different query scenarios.
=> chore: add MetricQueryBuilder tests to cover required filters, time based sorting and custom SQL dimension

packages/backend/src/utils/QueryBuilder/queryBuilder.ts
Closes: 
Refactored the query builder to move the GROUP BY SQL generation logic into the dimensions SQL generation method. This improves code organization by keeping related functionality together and ensures consistent GROUP BY clause generation across different query paths.
=> refactor: move GROUP BY generation to dimensionsSQL in MetricQueryBuilder

packages/backend/src/utils/QueryBuilder/queryBuilder.ts
Closes: 
Refactored the MetricQueryBuilder class to improve code organization and maintainability. Created dedicated methods for handling dimension and metric filters, moving the filter logic from the buildQuery method into separate helper methods. This change makes the code more modular and easier to understand by encapsulating filter-related functionality in dedicated methods.
=> refactor: extract filter SQL generation into separate methods in MetricQueryBuilder

packages/frontend/src/ee/features/aiCopilot/components/AiAgentPageLayout.tsx, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatDisplay.tsx, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatInput.module.css, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatInput.tsx, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AiChartQuickOptions.tsx, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AiChartVisualization.tsx, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ScrollToBottom.tsx, packages/frontend/src/ee/features/aiCopilot/components/ThreadDetailsModal.tsx, packages/frontend/src/ee/pages/AiAgents/AgentThreadPage.tsx
Improved the chat UI by redesigning the chat input component with a blurred backdrop and better visual hierarchy. The chat display now includes the input as a child component, making the layout more cohesive. Added sticky positioning to keep the input at the bottom of the chat area, and improved scrolling behavior for a better user experience.
[CleanShot 2025-06-25 at 19.27.18.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/cOL6QbQzyaUdOs5psinD/b10de4d6-5ef4-434a-ac40-fe3b0fc9aa57.mp4" />](https://app.graphite.dev/media/video/cOL6QbQzyaUdOs5psinD/b10de4d6-5ef4-434a-ac40-fe3b0fc9aa57.mp4)
=> feat: redesign chat UI with sticky input and improved scrolling

packages/backend/src/utils/QueryBuilder/queryBuilder.ts
Closes: 
Refactored the table calculation SQL generation into a dedicated method `getTableCalculationsSQL()` to improve code organization and maintainability. This method now handles both the SELECT statements for table calculations and their associated filters, making the main query building logic cleaner and more consistent with how dimensions and metrics are processed.
=> refactor: extract table calculations SQL into separate method

packages/backend/src/utils/QueryBuilder/queryBuilder.ts
Closes: 
Refactored the `MetricQueryBuilder` class by extracting join SQL generation into a separate method `getJoinsSQL`. This improves code organization and readability by isolating the join-related logic from the main `compileQuery` method.
The new method accepts tables referenced in dimensions and metrics as parameters and returns both the generated join SQL and the set of tables used in the joins, maintaining the same functionality while making the code more modular.
=> refactor: extract join SQL generation into separate method in MetricQueryBuilder

packages/backend/src/utils/QueryBuilder/queryBuilder.ts
Closes: 
Refactored the MetricQueryBuilder class to improve SQL assembly logic by introducing two new static methods:
- `buildCtesSQL`: Handles the construction of Common Table Expressions (CTEs)
- `assembleSqlParts`: Filters out undefined parts and joins SQL fragments
These methods reduce code duplication and make the SQL assembly process more consistent throughout the class, improving maintainability and readability.
=> refactor: extract SQL assembly logic into static methods

packages/frontend/src/components/UserSettings/AccessTokensPanel/CreateTokenModal.tsx, packages/frontend/src/components/UserSettings/AccessTokensPanel/TokensTable.tsx, packages/frontend/src/components/UserSettings/AccessTokensPanel/useExpireOptions.ts, packages/frontend/src/hooks/useAccessToken.ts
Closes: #15554
Improved the Personal Access Token UI by replacing the UUID column with a more user-friendly menu interface. Added a dedicated modal for copying token UUIDs that includes helpful context about what a token UUID is used for and a link to documentation about token rotation.
=> fix: improve access token UI with dropdown menu and UUID copy modal

packages/backend/src/utils/QueryBuilder/queryBuilder.ts
Closes: 
Refactored the MetricQueryBuilder class to simplify SQL query construction logic. The changes consolidate the query building process by using a common `finalSelectParts` array that gets modified based on conditions, rather than duplicating SQL assembly code. This approach makes the code more maintainable by reducing repetition and improving readability while maintaining the same functionality.
=> refactor: simplify SQL query construction in MetricQueryBuilder

packages/backend/src/services/ProjectService/ProjectService.ts, packages/backend/src/services/UserService.ts
=> fix: improve error logs sso

packages/cli/src/handlers/validate.ts
Closes: #15638
Reproduction steps:
1. create chart from payments explore with metric from joined table
2. remove payments joins from schema.yml
3. run validate command 
```
pnpm cli-build
node ./packages/cli/dist/index.js login http://localhost:3000
node ./packages/cli/dist/index.js validate --project-dir ./examples/full-jaffle-shop-demo/dbt --profiles-dir ./examples/full-jaffle-shop-demo/profiles
```
Enhances the validation output in the CLI by:
- Adding color coding to error counts (red for errors, green for no errors)
- Including "last updated by" and "last updated at" information for charts and dashboards
- Improving the formatting of the validation results with aligned columns
This makes it easier to identify who last modified a resource with validation errors and when the change …
=> feat: improve validation output with color-coded errors and last updated info

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ScrollToBottom.tsx
Closes: #15432
Enhanced the auto-scroll functionality in AI Copilot chat to properly handle chart visualizations. The PR introduces a separate scroll threshold for charts (500px) versus streaming content (200px), and adds auto-scrolling when a chart visualization is added to the last message. This ensures users can see newly generated charts without having to manually scroll down.
Demo:
[CleanShot 2025-07-01 at 19.45.46.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/SRLEqMEevAzoFwvhnfeq/252cdad2-4168-4282-873c-d2c8acad9468.mp4" />](https://app.graphite.dev/media/video/SRLEqMEevAzoFwvhnfeq/252cdad2-4168-4282-873c-d2c8acad9468.mp4)
=> fix: scroll-to-bottom behavior when a new visualization is generated

packages/common/src/ee/AiAgent/schemas/visualizations/tableViz.ts
Closes: #15691
Update the schema validation for table visualizations to allow queries without metrics
=> fix: remove minimum requirement for metrics in tableViz schema

examples/full-jaffle-shop-demo/dbt/models/fanouts_examples/fanouts_addresses.yml, examples/full-jaffle-shop-demo/dbt/models/fanouts_examples/fanouts_countries.yml, examples/full-jaffle-shop-demo/dbt/models/fanouts_examples/fanouts_sales_targets.yml
=> fix: add missing version on jaffle fanout models

packages/backend/src/ee/services/EmbedService/EmbedService.ts
Closes: [#15667](https://github.com/lightdash/lightdash/issues/15667)
Reproduce steps:
1. update project to use staging snowflake
2. load embed dashboard
3. login to snowflake
4. go to query history
5. see query tags for latest query
Examples:
```
{
"embed":"true",
"external_id":"1751463609",
"project_uuid":"3675b69e-8324-4110-bdca-059031aa8da3",
"organization_uuid":"172a2270-000f-42be-9c68-c4752c23ae51",
"chart_uuid":"4d420512-f1e2-40a0-a6b2-3fa989f30b76",
"dashboard_uuid":"25d76208-0d10-4098-b046-ad8686c2c13b",
"explore_name":"payments",
"query_context":"calculateTotal"
}
{
"embed":"true",
"external_id":"1751463609",
"project_uuid":"3675b69e-8324-4110-bdca-059031aa8da3",
"organization_uuid":"172a2270-000f-42be-9c68-c4752c23ae51",
"chart_uuid":"4d420512-f1e2-40a0-a6b2-3fa989f30b76", …
```
=> feat: enhance query tags for embed service with detailed context

packages/backend/src/ee/services/ai/agents/agent.ts, packages/backend/src/sentry.ts
Always trace AI streams on Sentry. No need to record inputs and outputs.
=> feat: always trace AI streams on Sentry

packages/frontend/src/features/sqlRunner/components/SqlEditor.tsx, packages/frontend/src/features/sqlRunner/components/Tables.tsx, packages/frontend/src/features/sqlRunner/hooks/useMultipleTableFields.tsx, packages/frontend/src/features/sqlRunner/hooks/useTableFields.tsx
Improved SQL editor table data handling to prevent errors when data is empty or not available. Added validation to ensure database keys exist before accessing them, and filtered out empty field names in table fields.
=> fix: Prevent autocompletion errors when no table names are available

examples/full-jaffle-shop-demo/dbt/macros/quarter_end_date.sql, packages/e2e/cypress/e2e/app/createProjects.cy.ts, packages/e2e/cypress/e2e/app/customDimensions.cy.ts
- Fixes dbt project macro to support `redshift`
- Updates assertion for 20 models instead of 11
- Updates custom dimension result assertions to take into account new values after fanout fix
test-frontend
=> fix(test): create project tests were failing on redshift

packages/common/src/types/featureFlags.ts, packages/frontend/src/components/ProjectConnection/WarehouseForms/BigQueryForm.tsx, packages/frontend/src/components/ProjectConnection/WarehouseForms/PostgresForm.tsx, packages/frontend/src/components/ProjectConnection/WarehouseForms/RedshiftForm.tsx, packages/frontend/src/components/ProjectConnection/WarehouseForms/SnowflakeForm.tsx, packages/frontend/src/components/ProjectConnection/WarehouseForms/TrinoForm.tsx, packages/frontend/src/pages/Settings.tsx
- Remove PassthroughLogin feature flag - already deployed to all users
=> refactor: remove PassthroughLogin feature flag

examples/full-jaffle-shop-demo/dbt/models/customers.yml, examples/full-jaffle-shop-demo/dbt/models/orders.yml
- Reverts `jaffle-shop` changes from https://github.com/lightdash/lightdash/pull/15718 which were causing tests to fail
test-frontend
test-cli
=> fix(test): remove explores from meta tags

packages/backend/src/ee/controllers/embedController.ts, packages/backend/src/ee/models/EmbedModel.ts, packages/backend/src/ee/services/EmbedService/EmbedService.ts, packages/backend/src/middlewares/jwtAuthMiddleware/hydrateEmbeddedAccount.ts, packages/backend/src/middlewares/jwtAuthMiddleware/jwtAuthMiddleware.test.ts, packages/backend/src/middlewares/jwtAuthMiddleware/jwtAuthMiddleware.ts, packages/common/src/ee/embed/index.ts, packages/common/src/types/auth.ts, packages/e2e/cypress/e2e/app/savedDashboards.cy.ts
Closes: #15622
Refactored the JWT authentication middleware for embedded dashboards to improve security and maintainability. Key changes include:
1. Restructured the account access controls to properly separate user attributes and filtering permissions
2. Fixed the organization join in the EmbedModel to correctly retrieve organization data
3. Improved the dashboard permissions checking with a more consistent method
4. Extracted JWT verification logic to use the proper decodeLightdashJwt function
5. Added better error handling for missing dashboard UUIDs in embed tokens
6. Simplified the external ID handling by using consistent user identifiers
=> feat: use filters and userAttributes from req.account in EmbedService

.github/workflows/cli-tests.yml, dockerfile, dockerfile-prs, packages/backend/src/dbt/dbtCliClient.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/cli/src/handlers/dbt/getDbtVersion.ts, packages/common/src/dbt/schemas/manifestV12.json, packages/common/src/types/projects.ts
Closes: https://github.com/lightdash/lightdash/issues/15708
Add support for dbt 1.10 by updating the Docker images to install dbt 1.10 alongside existing versions. This PR also updates the CI workflow to test against dbt 1.4, 1.9, and 1.10 (removing 1.8), and adds the necessary code changes to recognize and handle dbt 1.10 in the application.
=> feat: add support for dbt 1.10

packages/backend/src/controllers/authentication/strategies/oidcStrategy.ts
Improves error handling in OpenID authentication by providing more specific error messages when email or subject (user ID) is missing from the profile. Previously, a generic error message was shown for both cases. Now, detailed error logs include the profile data and user-facing messages clearly indicate which field is missing.
=> fix: improve OpenID authentication error messages

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatAssistantBubble.tsx, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatDisplay.tsx, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatUserBubble.tsx
Refactored chat bubble components to improve organization into two components
1. `AgentChatAssistantBubble.tsx`
2. `AgentChatUserBubble.tsx`
=> chore: Split AI Copilot chat bubbles into separate components

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/AiChartGenerationToolCallDescription.tsx
Improved the UI for AI chart generation tool call descriptions by:
1. Adding proper spacing between badges with `mx={rem(2)}`
2. Consolidating dimensions and metrics into a single array for cleaner rendering
3. Adding a conditional check to only show "with fields" when there are fields to display
4. Maintaining consistent styling across all badges
=> refactor: improve chart generation tool call UI with better field display

packages/frontend/src/ee/features/aiCopilot/components/SlackIntegrationSteps.tsx, packages/frontend/src/ee/pages/AiAgents/ProjectAiAgentEditPage.tsx, packages/frontend/src/mantine8Theme.ts
Redesigned AI Agent edit page:
- Improved page structure with defined sections
- Simplified the Slack integration instructions text
- Moved action buttons to the top of the page for better accessibility
- Enhanced typography and spacing for improved readability
=> feat: Restructure Agent edit page

packages/backend/src/ee/index.ts, packages/backend/src/ee/models/AiAgentModel.ts, packages/backend/src/ee/services/AiAgentService.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/models/GroupsModel.ts, packages/common/src/ee/AiAgent/index.ts, packages/frontend/src/components/NavBar/AiAgentsButton.tsx, packages/frontend/src/ee/features/aiCopilot/hooks/useOrganizationAiAgents.ts, packages/frontend/src/ee/features/aiCopilot/hooks/useProjectAiAgents.ts, packages/frontend/src/ee/pages/AiAgents/ProjectAiAgentEditPage.tsx
Reverts lightdash/lightdash#15706
=> fix: revert add group access to ai agents

.github/workflows/test-and-build.yml
This PR enhances our GitHub workflow by:
1. Expanding pull request triggers to include stacked prs
2. Adding manual workflow dispatch capability
3. Adding a type checking step with `pnpm typecheck`
4. Adding a frontend build step with `pnpm frontend-build`
=> feat: run build and tests on stacked prs

packages/frontend/src/features/parameters/components/Parameters.tsx, packages/frontend/src/features/parameters/index.ts, packages/frontend/src/hooks/parameters/useParameters.ts, packages/frontend/src/pages/Dashboard.tsx
=> feat: parameters menu button in dashboard and hook

packages/frontend/src/components/Explorer/ParametersCard/ParametersCard.tsx, packages/frontend/src/features/parameters/components/ParameterSelection.tsx, packages/frontend/src/features/parameters/components/Parameters.tsx, packages/frontend/src/features/parameters/index.ts, packages/frontend/src/hooks/parameters/useParameterState.ts
=> feat: use parameters in both dashboard & explorer

packages/backend/src/@types/express-session.d.ts, packages/backend/src/controllers/authentication/middlewares.ts, packages/backend/src/ee/clients/Slack/SlackClient.ts, packages/backend/src/routers/apiV1Router.ts, packages/frontend/src/ee/pages/SlackAuthSuccess.tsx
Enhances Slack authentication flow by preserving context when users connect their Slack account to Lightdash. When a user clicks the "Connect your Slack account" button in Slack, the system now captures and passes along team ID, channel ID, message timestamp, and thread timestamp through the authentication process. After successful authentication, users are automatically redirected back to the relevant Slack conversation.
=> feat: deep-link to Slack message during AI Agent Slack OAuth flow

package.json, packages/backend/src/App.ts, packages/e2e/cypress.config.ts, packages/e2e/cypress/e2e/app/createProjects.cy.ts, packages/e2e/cypress/e2e/app/explore.cy.ts, packages/e2e/cypress/support/commands.ts, packages/e2e/cypress/support/warehouses.ts, packages/e2e/package.json
Closes: #15848
This PR improves the E2E testing infrastructure with several enhancements:
1. Added a new `e2e-open-native` script that allows running Cypress tests using the host machine's environment variables
2. Enhanced error logging in the backend to include stack traces in development mode
3. Added a new `getJwtToken` Cypress command to generate JWT tokens for testing embedded dashboards
4. Improved type safety in Cypress commands by adding TypeScript type annotations
5. Made database connection parameters configurable via environment variables (PGUSER, PGPASSWORD, etc.)
6. Added support for specifying a custom dbt project directory via environment variables
These changes make it easier to run E2E tests natively and sets up functionality for the changes coming to AsyncQuery Service …
=> feat: setup Cypress for JWT async-queries

CLAUDE.md
Added documentation to CLAUDE.md with:
1. Package-specific commands for faster targeted operations (lint, typecheck, test)
2. Instructions for checking the local database with psql examples
3. API debugging examples using curl
Assumes:
- postgres related environment variables are setup
- `LDPAT` (personal access token) environment variable is setup
=> docs: add instructions for extending the agent loop

package.json, packages/backend/INTEGRATION_TESTS.md, packages/backend/jest.config.js, packages/backend/package.json, packages/backend/src/ee/services/AiAgentService.ts, packages/backend/src/ee/services/ai/agents/tests/agent.integration.test.ts, packages/backend/src/vitest.setup.integration.ts, packages/backend/vitest.config.integration.ts, pnpm-lock.yaml
Relates to: #15829 
> [!NOTE]
> This integration set up + tests do **not** run yet on the CI - that will be a separate PR 
- Added Vitest configuration for integration tests (`vitest.config.integration.ts`)
- Created comprehensive test setup with automatic database management (`vitest.setup.integration.ts`)
- Added new pnpm script: `pnpm backend-test-integration` (needs to be run in a python virtual env)
- Migration and seed execution for clean test environment
- Proper cleanup and rollback after tests complete
- Initial integration test for AI agent functionality (`agent.integration.test.ts`)
- Tests agent creation, thread management, and response generation
- Validates tool calls and AI model interactions
=> test: add ai agent integration test

packages/backend/package.json, packages/backend/src/ee/services/ai/agents/tests/agent.integration.test.ts, packages/backend/src/ee/services/ai/agents/tests/utils/llmAsAJudge.ts, pnpm-lock.yaml
Relates to: #15829 
`llmAsAJudge.ts` utility uses `autoevals` prompt for `factuality` scoring and `JSONDiff` as another scorer
=> test: score find explores response with llm-as-a-judge

packages/backend/src/auth/account/account.test.ts, packages/backend/src/auth/account/account.ts, packages/backend/src/controllers/exploreController.ts, packages/backend/src/controllers/projectController.ts, packages/backend/src/controllers/runQueryController.ts, packages/backend/src/controllers/savedChartController.ts, packages/backend/src/controllers/sqlRunnerController.ts, packages/backend/src/controllers/v2/QueryController.ts, packages/backend/src/ee/services/AiAgentService.ts, packages/backend/src/ee/services/AiService/AiService.ts, packages/backend/src/ee/services/SupportService/SupportService.ts, packages/backend/src/models/QueryHistoryModel/QueryHistoryModel.ts, packages/backend/src/routers/dashboardRouter.ts, packages/backend/src/routers/savedChartRouter.ts, packages/backend/src/scheduler/SchedulerTask.ts, packages/backend/src/services/AsyncQueryService/AsyncQueryService.test.ts, packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts, packages/backend/src/services/AsyncQueryService/types.ts, packages/backend/src/services/CsvService/CsvService.ts, packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts, packages/backend/src/services/ProjectService/ProjectService.mock.ts, packages/backend/src/services/ProjectService/ProjectService.test.ts, packages/backend/src/services/ProjectService/ProjectService.ts, packages/common/src/authorization/jwtAbility.ts, packages/common/src/types/auth.ts, packages/common/src/types/queryHistory.ts, packages/common/src/types/scheduler.ts, packages/e2e/cypress/e2e/api/async-query.cy.ts, packages/e2e/cypress/e2e/app/explore.cy.ts, packages/e2e/cypress/support/commands.ts
This reverts commit 74a26ec0a3554c6ae3b8e6f6d42234f1b067cf40.
Closes: 
@almeidabbm found that PATs are busted because of changes we made with req.account. Reverting for now and will re-introduce these changes after updating all auth mechanisms.
=> fix: Revert "feat: refactor AsyncQuery and Project service to use account where needed for Embedded Explores (#15893)"

packages/backend/src/models/SavedChartModel.ts, packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts, packages/backend/src/utils/QueryBuilder/queryBuilder.test.ts, packages/backend/src/utils/QueryBuilder/queryBuilder.ts, packages/common/src/index.ts, packages/frontend/src/components/Explorer/ParametersCard/ParametersCard.tsx, packages/frontend/src/ee/features/embed/EmbedDashboard/components/EmbedDashboardChartTile.tsx, packages/frontend/src/hooks/useCompiledSql.ts, packages/frontend/src/hooks/useSavedQuery.ts, packages/frontend/src/pages/ChartHistory.tsx, packages/frontend/src/pages/MinimalSavedExplorer.tsx, packages/frontend/src/pages/SavedExplorer.tsx, packages/frontend/src/providers/Explorer/ExplorerProvider.tsx, packages/frontend/src/providers/Explorer/defaultState.ts, packages/frontend/src/providers/Explorer/types.ts
Closes: #15927 
- Create&update chart with params
- Apply saved & default param values on query run
https://github.com/user-attachments/assets/4571423f-4217-488a-b961-ac5ed90b2dee
=> feat: save chart parameter values

packages/backend/src/services/CLAUDE.md
Closes: 
Added documentation for the services directory in the backend with a new CLAUDE.md file. The documentation includes:
- Overview of the services directory's purpose and responsibilities
- Instructions on how to use services with the dependency injection pattern
- Code examples showing how to use existing services and create new ones
- Important information about service architecture and best practices
- Links to key service-related files for further reference
This documentation will help developers understand the service layer architecture and follow consistent patterns when working with or creating services.
=> docs: add CLAUDE.md guide for backend services

packages/frontend/src/features/parameters/components/Parameters.tsx
=> chore: update parameter icon

packages/backend/src/models/DashboardModel/DashboardModel.ts, packages/backend/src/services/DashboardService/DashboardService.ts
Relates to: #16021 
- Send parameters on dashboard update. 
- Don't update them if no values are sent.
=> chore: accept parameter values on dashboard update

packages/backend/src/models/DashboardModel/DashboardModel.ts, packages/backend/src/services/DashboardService/DashboardService.ts, packages/e2e/cypress/e2e/api/dashboard.cy.ts
Add an API test to create a dashbaord with parameters, update it, and check parameters values
=> chore: add api test for dashboard parameter values

packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/InvitesModal.tsx
Use mantine 8 on `InvitesModal`
=> fix: upgrade InvitesModal.tsx to mantine 8

packages/backend/src/utils/QueryBuilder/parameters.test.ts, packages/backend/src/utils/QueryBuilder/parameters.ts, packages/backend/src/utils/QueryBuilder/queryBuilder.ts
Closes: #N/A
Escape parameter values.
=> fix: escape parameter values

packages/backend/src/services/RenameService/RenameService.ts
Updated the `RenameService` to allow model renaming when new name is not live yet.
The updated logic is consistent with the `runScheduledRenameResources` validation, but we were throwing before reaching that step.
=> fix: Allow chart model renames before changes are applied

.claude/commands/apply-style-guide.md
=> docs: style guide command

packages/backend/src/ee/services/ai/agents/tests/agent.integration.test.ts
Closes: 
Adds multi-turn conversation support to AI agents, allowing them to maintain context across multiple prompts in the same thread. This enables more natural interactions where users can ask follow-up questions without repeating context.
The PR also adds a new test for the agent's ability to explain its capabilities and adds support for vertical bar charts in agent responses.
=> test: add generic and long-context message assertion

packages/warehouses/package.json, pnpm-lock.yaml
Upgrade snowflake-sdk from version 2.0.4 to 2.1.3 to leverage the latest features and bug fixes, mainly the update to axios.
This update includes several new dependencies and updates to existing ones, enhancing the Snowflake integration capabilities.
test-frontend
test-backend
test-cli
=> fix: bump snowflake-sdk version

packages/backend/src/controllers/v2/QueryController.ts, packages/backend/src/generated/swagger.json, packages/backend/tsoa.yml
Closes: #1234
This PR improves the API documentation for the Query Controller endpoints by adding detailed descriptions for each endpoint and parameter. It also:
1. Updates the Query Controller tag from `v2, Query` to just `Query` for better organization
2. Adds a proper description for the Query tag in the API documentation
3. Sets `yaml: false` in tsoa.yml to ensure consistent output format
These changes make the API more self-documenting and improve the developer experience when using our API endpoints.
=> docs: add descriptions for Query controller endpoints

packages/frontend/STYLE_GUIDE.md
Updates the style guide with a few rules I found helpful to get Claude to upgrade components a little better.
=> chore: update style guide with m8 suggestions

.github/CONTRIBUTING.md
This PR updates our contribution guidelines, removing contradictory instructions and ensuring that contributors understand the contribution and review process. 
Relevant Slack conversations: 
- https://lightdash.slack.com/archives/C02GQKJK84Q/p1754396749307349
- https://lightdash.slack.com/archives/C02GQKJK84Q/p1754304560084289
- Not sure that the link to style guidelines is a good one to reference as it just points to running prettier etc. Let me know if I should remove entirely or replace with a different link.
=> chore: update contribution guide

packages/frontend/src/features/sqlRunner/components/SqlEditor.tsx
Closes: ###
https://github.com/user-attachments/assets/fda1bdb8-89bf-4310-be2b-f64033e261cb
Monaco editor autocomplete for parameters. Features:
- Wraps with `${}` automatically
- Priority sorting
- Substitute properties without duplication
=> feat: sql editor parameters autocomplete

packages/frontend/src/components/Explorer/ResultsCard/ResultsCard.tsx, packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx, packages/frontend/src/components/ExportResults/index.tsx, packages/frontend/src/components/ExportSelector/index.tsx, packages/frontend/src/components/common/ChartDownload/ChartDownloadMenu.tsx, packages/frontend/src/components/common/ChartDownload/ChartDownloadOptions.tsx
before:
after:
[CleanShot 2025-08-05 at 18.13.32.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/cOL6QbQzyaUdOs5psinD/8618b118-b12e-4856-bded-a31ac28d77e6.mp4" />](https://app.graphite.dev/media/video/cOL6QbQzyaUdOs5psinD/8618b118-b12e-4856-bded-a31ac28d77e6.mp4)
=> style: ensure consistency of chart and result table buttons across the Explore page

packages/frontend/sdk/index.tsx, packages/frontend/src/providers/MantineProvider.tsx
Closes: #N/A
fixes missing mantine 8 style import
=> fix: missing mantine 8 style import

packages/backend/src/ee/services/EmbedService/EmbedService.ts, packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts, packages/backend/src/services/ProjectService/ProjectService.ts, packages/backend/src/services/ProjectService/getDashboardParametersValuesMap.ts
Refactored dashboard parameter handling to use a consistent approach across the application. Created a new utility function `getDashboardParametersValuesMap` that extracts parameter values from a dashboard and converts them to the required format. This function is now used in both the EmbedService and AsyncQueryService to ensure dashboard parameters are properly applied to queries.
The PR also simplifies the `combineParameters` method by reducing the number of parameters it accepts, making the parameter priority clearer: request parameters take precedence over saved parameters (from charts or dashboards), which take precedence over default values.
=> chore: remove combination of multiple saved charts and fix embedded dashboard

packages/backend/src/controllers/v2/ParametersController.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/models/ProjectParametersModel.ts, packages/backend/src/services/ProjectParametersService.ts, packages/backend/src/services/ServiceRepository.ts, packages/common/src/index.ts, packages/common/src/types/api/parameters.ts
Closes: #16303
Added a new API endpoint to list project parameters with pagination, search, and sorting capabilities. The endpoint `/api/v2/projects/:projectUuid/parameters/list` supports:
- Searching parameters by name, label, and description
- Sorting by name or creation date
- Pagination with customizable page size (limited to 100 items per page)
- Consistent secondary sorting by name when primary sort is by creation date
This endpoint returns parameter summaries including name, creation date, and configuration, making it easier to display and manage parameters in the UI.
<details>
<summary>
Example response
</summary>
```json
{
"status": "ok",
"results": {
"data": [
{
"name": "metric_type",
"createdAt": "2025-08-13T04:08:08.480Z",
"config": {
"label": "Metric Type",
"default": …
```
=> feat: project parameters api

packages/backend/src/ee/services/ai/agents/tests/agent.integration.test.ts, packages/backend/src/ee/services/ai/prompts/system.ts, packages/common/src/ee/AiAgent/schemas/visualizations/index.ts
Closes: #16250
(it was pretty ok)
=> feat: AI Agent limitations transparency

packages/backend/src/App.ts, packages/backend/src/clients/Slack/SlackClient.ts, packages/backend/src/clients/Slack/SlackMessageBlocks.ts, packages/backend/src/config/parseConfig.ts, packages/backend/src/ee/clients/Slack/SlackClient.ts, packages/backend/src/ee/index.ts, packages/backend/src/ee/services/AiAgentService.ts, packages/backend/src/generated/routes.ts, packages/backend/src/generated/swagger.json, packages/backend/src/models/SlackAuthenticationModel.ts, packages/backend/src/services/ServiceRepository.ts, packages/backend/src/services/UnfurlService/UnfurlService.ts
This reverts PR #16254 and fixes slack initialization for OSS
=> fix: Revert "refactor: move Slack client functionality to service layer"

.github/workflows/ai-agent-integration-tests.yml
Closes: #16256
Add new workflow for running AI Agent integration tests.
This workflow runs on weekdays at 8:00 UTC and can be triggered manually. At the end of run, it uploads results as artifacts and sends a summary to a [dedicated slack channel](https://lightdash.slack.com/archives/C099V56GEV9)
=> chore: AI Agent integration test CI

packages/backend/src/utils/QueryBuilder/MetricQueryBuilder.test.ts
Added support for `NULLS FIRST` and `NULLS LAST` sorting in SQL queries. This implementation allows users to control how NULL values are ordered in query results by adding a `nullsFirst` property to sort configurations.
The PR includes:
- A new static method `getNullsFirstLast` to generate the appropriate SQL clause
- Comprehensive test coverage for various sorting scenarios
- Support for both ascending and descending sorts
- Compatibility with custom bin dimensions
This enhancement gives users more control over how NULL values are positioned in sorted query results.
=> test: add nulls first last support

packages/backend/src/ee/services/ai/tools/findCharts.ts, packages/backend/src/ee/services/ai/tools/findDashboards.ts, packages/backend/src/models/SearchModel/index.ts, packages/common/src/types/search.ts
Closes: #16458
Added `lastUpdatedBy` information to search results for charts and dashboards. This enhancement provides more context about who last modified a resource, complementing the existing `createdBy` information. The changes include:
1. Updated SQL queries to join with user tables for both creation and update information
2. Added `lastUpdatedBy` fields to search result types
3. Enhanced the XML output in AI tools to include the last updated user information
This improvement helps users better understand the history and ownership of charts and dashboards when searching.
=> feat: add lastUpdatedBy to chart and dashboard search results

packages/backend/README.md, packages/backend/package.json, packages/backend/src/migrateOrRollbackDatabase.ts
Closes: https://github.com/lightdash/lightdash/issues/9188
Added utility scripts with documentation:
1. **[new] Database Migration and Rollback Tool** - A script that automates database migrations and rollbacks, handling missing migration files by downloading them from GitHub when needed.
2. **[documented] User Password Override Tool** - A command-line utility for administrators to reset user passwords. 
Both tools include important disclaimers about data safety and proper usage. The README has been updated with comprehensive documentation for each script, including usage examples and warnings.
=> chore(devx): add database migration/rollback utility script

packages/frontend/src/ee/features/aiCopilot/components/AiAgentPageLayout/AiAgentPageLayout.tsx, packages/frontend/src/ee/features/aiCopilot/components/AiAgentPageLayout/aiAgentPageLayout.module.css, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatAssistantBubble.tsx, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatUserBubble.tsx, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ArtifactButton/AiArtifactButton.module.css
Closes: #16457
Wrap up Artifacts work by making UI improvements
=> feat: Improve Artifacts UI styles

packages/backend/src/routers/mcpRouter.ts
Implements Server-Sent Events (SSE) transport method for MCP endpoints. The implementation:
- Adds proper SSE headers to the response
- Sets up a heartbeat mechanism to keep connections alive
- Handles connection cleanup when clients disconnect
- Sends an initial connection event to clients
- Returns appropriate responses for different HTTP methods
This allows clients to establish persistent connections with the MCP server for real-time updates.
before:
after:
=> feat: implement SSE transport method for MCP

.github/workflows/gcp-build-and-push.yml, scripts/gcp-build-and-push.sh
=> feat: add multi-region Docker image replication to GCP build

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatUserBubble.tsx, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ArtifactButton/AiArtifactButton.module.css, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ArtifactButton/AiArtifactButton.tsx, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/AiChartToolCalls.tsx
Improved the visual design of AI Copilot chat elements with the following changes:
- Updated the user bubble background color from white to gray.0
- Completely redesigned the artifact button with a new modern style:
- Added hover, active, and focus states
- Improved color scheme with indigo accents
- Enhanced typography and spacing
- Added loading state styling
- Refined the tool calls UI:
- Updated the timeline appearance with dashed lines
- Improved icon styling with subtle backgrounds
- Adjusted spacing, typography, and colors for better readability
- Changed the "How it is calculated" section header styling
=> style: make styling improvements to chat interface

packages/frontend/src/hooks/useExplorerAceEditorCompleter.ts
Adds custom dimensions to the auto complete for table calculations.
=> feat: add custom dims to table calc auto complete

packages/frontend/src/components/DashboardTabs/gridUtils.ts, packages/frontend/src/pages/MinimalDashboard.tsx
This reverts commit 91d7dcd23e78981e099c0be7b532371f1b1611eb.
Closes: 
Reverting a change that broke scheduled deliveries
=> fix: revert "fix: mobile dashbaord layout (#16666)"

packages/backend/src/config/parseConfig.test.ts, packages/backend/src/config/parseConfig.ts
`LD_SETUP_PROJECT_PAT` which is used for databricks PAT was incorrectly being checked for being prefixed with `ldpat_`
=> fix: simplify personal access token handling in setup config

packages/frontend/src/hooks/useQueryResults.ts
`useInfiniteQueryResults` seems to return stale data when `queryUuid` changes
This PR adds dependency change detection during render to prevent displaying outdated data when project or query UUIDs change. The implementation:
1. Adds a `dependenciesChanged` flag to detect when project or query UUIDs change
2. Uses this flag to properly reset loading states when switching queries
=> fix: detect stale data when using useInfiniteQueryResults hook

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatAssistantBubble.tsx, packages/frontend/src/ee/features/aiCopilot/hooks/useAiAgentThreadArtifact.ts, packages/frontend/src/ee/pages/AiAgents/AgentThreadPage.tsx
- Automatically select artifact when a new artifact is generated in thread
- Automatically select last artifact in a thread when threads are switched
- User can close an artifact or switch between them in a thread
=> fix: automatic artifact switching logic between threads

packages/frontend/src/ee/features/aiCopilot/components/AiAgentPageLayout/AiAgentPageLayout.tsx
Added `onCollapse` and `onExpand` event handlers to the AI Agent sidebar to properly update the sidebar collapsed state when these events occur. This ensures the `isAgentSidebarCollapsed` state is synchronized with the actual sidebar UI state.
=> feat: add collapse/expand handlers to AI agent sidebar

packages/frontend/src/components/JobDetailsDrawer/index.tsx
Closes: #XXX
Enhances the Job Details Drawer UI with improved error display and new features:
- Added support for "SKIPPED" job status with appropriate styling
- Improved error display with a dedicated error box and better formatting
- Added copy button functionality to easily copy error messages
- Enhanced error message readability with proper spacing and styling
- Implemented scrollable error container with max height to handle large error logs
before
after
=> style: improve job drawer error logs

packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
Closes: #N/A
Fixed a bug in the Snowflake warehouse client where `getColumns()` could potentially return undefined. Added proper type annotation and reused the existing `getFieldsFromStatement` method to avoid code duplication in the query execution logic.
=> fix: handle undefined columns in Snowflake query results

packages/frontend/src/ee/features/aiCopilot/streaming/useAiAgentThreadStreamMutation.ts
=> fix: add console log for jsonLine in AI agent thread stream processing

packages/frontend/src/ee/features/aiCopilot/streaming/useAiAgentThreadStreamMutation.ts
Refactored the AI agent thread streaming implementation to use the `DefaultChatTransport` class from the 'ai' library instead of a custom `processResponseStream` function. This simplifies the code by leveraging the library's built-in stream processing capabilities, making it more maintainable and potentially more robust.
`DefaultChatTransport` is the class being used by `useChat` hook ai-sdk exposes, under the hood it uses this helper that handles SSE stream parsing properly: https://github.com/vercel/ai/blob/main/packages/provider-utils/src/parse-json-event-stream.ts
=> fix: replace custom stream processing with ChatStreamParser in AI agent thread

packages/backend/src/ee/services/ai/tools/generateTableVizConfig.ts
Improved table visualization handling in AI tools with better empty result handling. The PR:
- Removes the `isOneRow` flag and replaces it with a more descriptive `rowCount` variable
- Adds explicit handling for queries that return no results
- Only sends CSV files to Slack when there are actual results to show
- Simplifies the error message for table visualization generation
=> fix: improve table visualization handling for empty results in AI tools

packages/backend/src/ee/services/ai/models/openai-gpt.ts
Adds todo to address OPENAI_RESPONSES_API config to later be able to override .responses api or not
=> chore: add todo to address OPENAI_RESPONSES_API

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AiChartVisualization.tsx
=> feat: Improve artifact error UI

package.json, pnpm-lock.yaml
Closes: https://github.com/lightdash/lightdash/security/dependabot
test-frontend test-backend test-cli
=> chore: upgrade hono library

packages/backend/src/ee/services/ai/agents/agent.ts
Refactored AI agent logging by introducing a `createAiAgentLogger` function that centralizes debug logging logic. This improves code readability and maintainability by replacing repetitive logging patterns with a consistent, context-aware logging approach. The function takes a boolean flag to enable/disable logging and a context string to identify the source of log messages.
=> refactor: create centralized logger for AI agent debugging

packages/frontend/src/ee/features/aiCopilot/components/AiAgentEditPageLayout/AiAgentEditPageLayout.tsx
Adjusted the container styling in the AI Agent Edit Page header to match content
=> fix: Fix header size in agent settings

packages/backend/src/ee/models/AiAgentModel.ts, packages/backend/src/ee/scheduler/SchedulerWorker.ts, packages/backend/src/ee/services/AiAgentService.ts
This PR fixes several issues with AI agent evaluations:
1. Adds error handling for evaluation task timeouts by updating the eval run result with a failure status and error message.
2. Creates a new `updateEvalRunResult` method to handle updating evaluation results when errors occur.
3. Prevents database errors by adding checks before inserting empty arrays into database tables:
- Only inserts tool call updates when there are items to insert
- Only inserts tool result updates when there are items to insert
- Only inserts artifact version updates when there are items to insert
These changes improve the robustness of the AI agent evaluation system by properly handling timeouts and preventing potential database errors.
=> fix: handle empty arrays in AI agent database operations and add timeout handling

packages/backend/src/clients/EmailClient/EmailClient.ts, packages/backend/src/services/UnfurlService/UnfurlService.ts
Closes: 
Improved error handling in email sending and screenshot capture processes:
1. In EmailClient:
- Added better error messages for file-related errors (ENOENT)
- Used the getErrorMessage helper for more consistent error formatting
2. In UnfurlService:
- Added detection for ECONNREFUSED errors as retryable errors
- Improved user-facing error messages for connection errors
- Added more specific error handling for 500 Internal Server Error responses
These changes provide more user-friendly error messages while preserving the original errors in logs for debugging.
=> fix: improve error messages for email sending and screenshot failures

packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
Closes: #17042
Implemented infinite scrolling for non-virtualized tables by adding scroll event listeners to the table container. This enhancement allows users to load more data when scrolling to the bottom of the table in both virtualized and non-virtualized modes.
Key improvements:
- Added a constant `SCROLL_THRESHOLD` (100px) to standardize when to trigger loading more data
- Enhanced the `NormalTableBody` component to support infinite scrolling
- Added loading indicator at the bottom of the table when fetching more rows
- Added detailed comments explaining the scrolling math and logic for better maintainability
1. Create a dashboard that has a table with limit > 500 rows
2. Embed this dashboard and try to scroll
3. It should fetch more rows as you scroll
**Before** …
=> fix: table visualizations rendered on minimal dashboards should also scroll to fetch more results

packages/backend/src/models/ProjectModel/ProjectModel.test.ts, packages/backend/src/models/ProjectModel/ProjectModel.ts
Closes: 
Tests `applyChange` static method
=> test: add cases for applyChange in ProjectModel.test.ts

packages/backend/src/models/ChangesetModel.ts
Closes: N/A
Added a `createChange` method to the `ChangesetModel` class that creates a change in the database. If no active changeset exists for the project, it automatically creates one before adding the change. The method handles transaction management to ensure data consistency and validates input parameters using the existing schema validation.
=> chore: add createChange method in model

packages/backend/src/models/ProjectModel/ProjectModel.ts
Closes: 
Previews are erroring with
=> chore: import ChangesetUtils from @lightdash/common

packages/backend/src/ee/services/McpService/McpService.ts, packages/backend/src/ee/services/ai/agents/agent.ts, packages/backend/src/ee/services/ai/tools/findCharts.ts, packages/backend/src/ee/services/ai/tools/findDashboards.ts, packages/backend/src/ee/services/ai/tools/findExplores.tsx, packages/backend/src/ee/services/ai/tools/findFields.ts, packages/backend/src/ee/services/ai/tools/generateBarVizConfig.ts, packages/backend/src/ee/services/ai/tools/generateDashboard.ts, packages/backend/src/ee/services/ai/tools/generateTableVizConfig.ts, packages/backend/src/ee/services/ai/tools/generateTimeSeriesVizConfig.ts, packages/backend/src/ee/services/ai/tools/improveContext.ts, packages/backend/src/ee/services/ai/tools/proposeChange.ts, packages/backend/src/ee/services/ai/tools/runMetricQuery.ts, packages/backend/src/ee/services/ai/tools/searchFieldValues.ts, packages/backend/src/ee/services/ai/utils/toModelOutput.ts, packages/common/src/ee/AiAgent/schemas/index.ts, packages/common/src/ee/AiAgent/schemas/outputMetadata.ts, packages/common/src/ee/AiAgent/schemas/tools/toolDashboardArgs.ts, packages/common/src/ee/AiAgent/schemas/tools/toolFindChartsArgs.ts, packages/common/src/ee/AiAgent/schemas/tools/toolFindDashboardsArgs.ts, packages/common/src/ee/AiAgent/schemas/tools/toolFindExploresArgs.ts, packages/common/src/ee/AiAgent/schemas/tools/toolFindFieldsArgs.ts, packages/common/src/ee/AiAgent/schemas/tools/toolImproveContext.ts, packages/common/src/ee/AiAgent/schemas/tools/toolProposeChange.ts, packages/common/src/ee/AiAgent/schemas/tools/toolRunMetricQueryArgs.ts, packages/common/src/ee/AiAgent/schemas/tools/toolSearchFieldValuesArgs.ts, packages/common/src/ee/AiAgent/schemas/tools/toolTableVizArgs.ts, packages/common/src/ee/AiAgent/schemas/tools/toolTimeSeriesArgs.ts, packages/common/src/ee/AiAgent/schemas/tools/toolVerticalBarArgs.ts, packages/frontend/src/ee/features/aiCopilot/hooks/useProjectAiAgents.ts
Implements structured tool outputs for AI agent tools to improve error handling and response formatting. This change adds output schemas for all tools and introduces a standardized output format with metadata that includes success/error status. The new `toModelOutput` utility function properly formats tool responses for the AI model, ensuring errors are correctly identified and handled.
=> feat: add structured output schema for AI agent tools and support metadata

packages/frontend/src/features/changesets/components/ProjectChangesets.tsx
=> fix: truncate changes correctly

packages/frontend/src/features/changesets/components/ProjectChangesets.tsx
=> style: keep create action sublabel empty

packages/backend/src/models/CatalogModel/CatalogModel.ts
Closes: N/A
Added support for table entity updates in the CatalogModel. Previously, the model only handled dimension and metric updates, but now it can also process table-level changes. This includes:
1. Adding `CompiledTable` as a possible field type to update
2. Adding a check for table entity type
3. Restructuring the update logic to handle tables separately from dimensions and metrics
4. Adding a type filter to the database query to distinguish between table and field updates
This enhancement allows the catalog to properly update table metadata such as labels and descriptions.
=> feat: handle table label & description updates

packages/frontend/src/components/NavBar/ProjectSwitcher.tsx
Closes: #XXX
Added project filtering functionality to the ProjectSwitcher component. Users can now filter projects by "All Projects", "Production", or "Preview" using a new SegmentedControl. The filter persists during the session and displays appropriate messaging when no projects match the selected filter criteria. Also improved the dropdown UI with better spacing and minimum width.
[demo-switcher.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/user-attachments/thumbnails/11bdd778-bfd0-4b97-b980-945680afa86d.mov" />](https://app.graphite.dev/user-attachments/video/11bdd778-bfd0-4b97-b980-945680afa86d.mov)
=> feat: add filters to project switcher

packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx
Fixes an issue where changes to filters were not being saved correctly.
=> fix: save filters in context as well as redux

packages/backend/src/ee/services/ai/tools/generateDashboard.ts
Improves the dashboard generation tool by tracking valid visualizations using a Set instead of relying on array transformations. This approach maintains the original visualization indices and ensures that only valid visualizations are included in the dashboard while preserving the original configuration structure.
The PR replaces the previous approach of creating a new object with filtered visualizations with a more direct filtering method that references the original toolArgs, improving code clarity and maintainability.
=> fix: dashboard generation with valid visualization tracking

packages/backend/src/services/AsyncQueryService/AsyncQueryService.test.ts, packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts, packages/backend/src/services/AsyncQueryService/types.ts, packages/backend/src/services/ProjectService/ProjectService.ts
Closes: #17280
See issue's description - all is covered there
=> fix: check if registered user when user creds required

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/AiProposeChangeToolCall/index.tsx, packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/ToolCallPaper.tsx
Improved error handling in AI Propose Change Tool Call
=> feat: improve error handling for propose change tools ui

packages/backend/src/services/ProjectService/ProjectService.ts
Closes: #N/A
Improves Snowflake SSO token handling by properly distinguishing between refresh tokens and access tokens. The PR adds validation to detect invalid token formats and throws a specific error when an access token is incorrectly used as a refresh token. This fixes issues with older projects that weren't storing refresh tokens correctly and ensures proper token regeneration.
The changes also improve error handling by preserving LightdashErrors and explicitly storing the refresh token in the warehouse connection for future access token generation.
=> fix: validate snowflake refresh token format

packages/frontend/src/ee/features/aiCopilot/components/Evals/EvalDetail.tsx, packages/frontend/src/ee/features/aiCopilot/components/Evals/EvalSectionLayout.tsx
Closes: #N/A
Improved the UI for evaluation details in the AI Copilot feature:
1. Redesigned the evaluation details layout with a cleaner structure
2. Added a scrollable area with a maximum height for test prompts to prevent long lists from taking up too much space
3. Reorganized the header section to better display evaluation information
4. Fixed navigation to properly direct users to the evaluations tab when navigating back from evaluation details
5. Improved tooltip styling and information display
[CleanShot 2025-10-08 at 14.21.41.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/user-attachments/thumbnails/67a02ccb-904a-40d3-99db-4fff30f44bf4.mp4" />](https://app.graphite.dev/user-attachments/video/67a02ccb-904 …
=> fix: get correct breadcrumb & prompt list is scrollable
