lightdash/lightdash

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/ExploreFromHereButton/index.tsx
packages/frontend/src/hooks/useExplorerRoute.ts

Closes: #12367 
NOTE: that this is a pretty targeted fix to make sure Explore From Here doesn't lose chart configuration. We could make our URL params and shared/shortened URL interaction better. 
The Explore from here button was using `getExplorerUrlFromCreateSavedChartVersion` to generate an in-memory URL, then using the share URL generator to produce a redirect url from that. But since `getExplorerUrlFromCreateSavedChartVersion` would truncate the url by removing chart config, chart configs were lost in Exploring. This just adds an option to preserve long urls and uses that option for Explore From Here. 
To test:
- go to an explore
- select dimensions and columns
- add a big pivot value (eg: orders day)
- set stacking to 'stack'
- save to a dashboard
- explore from here on that chart
- …

fix: dont shorten urls before creating EFH share link

---

packages/backend/src/models/CatalogModel/CatalogModel.ts

Closes: [#12391](https://github.com/lightdash/lightdash/issues/12391)
Now it returns the catalog item will all tags if one of them is included in the filtering query
demo: 
https://github.com/user-attachments/assets/3c331329-156d-46a6-a959-19e00dcb5ca5

fix: get all tags when filtering

---

packages/backend/package.json
packages/backend/src/routers/headlessBrowser.ts
yarn.lock

Closes:  #12418
We already use playwright for getting images (unfurlService) , this were some leftover endpoints, only used in E2E tests. 
BY removing this library, we fix a vulnerability

chore: remove puppeteer

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/visualizations/CartesianChartDataModel.ts
packages/frontend/src/components/DataViz/config/CartesianChartStyling.tsx
packages/frontend/src/components/DataViz/config/CartesianChartValueLabelConfig.tsx
packages/frontend/src/components/DataViz/store/cartesianChartBaseSlice.ts

Closes: #11924 
Adds options for value labels in SQL runner charts. For now this is only enabled in chart with one series. Multiple series is blocked on fixing multi-series settings, the main ticket for which is: #11925

feat: value label options for sql runner charts

---

packages/frontend/src/components/DashboardFilter/Filter.tsx

Closes: https://github.com/lightdash/lightdash/issues/12435
Changes:
- inactive filter border styles
- inactive filter backend opacity
- removed icon for inactive filter
- moved tooltip for inactive filter to apply to entire component
- update tooltip text for inactive filter
- added a delay to the tables tooltip
Before:
Now: ( note: second filter was disabled for all tabs )
Tooltips:

fix(dashboard): inactive filter styles

---

docs/docs/references/groups.mdx
docs/docs/self-host/customize-deployment/use-sso-login-for-self-hosted-lightdash.mdx
packages/backend/src/config/parseConfig.ts
packages/backend/src/services/UserService.ts

Closes: [#384](https://github.com/lightdash/lightdash-commercial/issues/384)
This is just marking the feature as deprecated. There is a separate ticket to remove the code after some time https://github.com/lightdash/lightdash/issues/12430

chore: mark group sync as deprecated

---

packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceAddUser.tsx

Closes: https://github.com/lightdash/lightdash/issues/12316
this bug happens because of react query caching + infinite pagination combination. I can discuss this further but the short story is, react query produces different cache spaces for search queries because search query is in the cache key.
https://github.com/user-attachments/assets/da43b4f2-25fa-4cf6-98cf-e9cd132e3631

fix: cant invite project users to space

---

packages/backend/src/models/DashboardModel/DashboardModel.mock.ts
packages/backend/src/models/OrganizationMemberProfileModel.ts
packages/backend/src/models/UserModel.ts
packages/backend/src/services/DashboardService/DashboardService.mock.ts
packages/backend/src/services/OrganizationService/OrganizationService.mock.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/backend/src/services/PromoteService/PromoteService.mock.ts
packages/backend/src/services/ShareService/ShareService.mock.ts
packages/backend/src/services/UserService.mock.ts
packages/backend/src/services/ValidationService/ValidationService.mock.ts
packages/common/src/authorization/index.mock.ts
packages/common/src/authorization/organizationMemberAbility.mock.ts
packages/common/src/types/organizationMemberProfile.ts
packages/common/src/types/user.ts
packages/frontend/src/testing/__mocks__/api/userResponse.mock.ts

Dependant Commercial PR: https://github.com/lightdash/lightdash-commercial/pull/396 
- This adds `updated_at` and `created_at` from the users table to both `LightdashUser` and `OrganizationMeMberProfile` 
- These values are grabbed by the SCIM service when returning user metadata back to the identity requester in the form of `created` and `lastModified`

feat: added created_at and updated_at to user and organization member objects

---

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumnName.tsx
packages/frontend/src/styles/emoji-picker-react.css

Relates to: [#12277](https://github.com/lightdash/lightdash/issues/12277)
label color
emoji size
emoji picker input

style: apply changes to metric name label and emojipicker

---

packages/common/src/visualizations/CartesianChartDataModel.ts

Closes: #12485 
When there are too many value labels in a chart, they overlap heavily. This makes echarts elide some of them. This could be better, but it's gives us parity with our existing chart config. 
Without this change:
With this change:

fix: overlapping value labels in sql runner

---

packages/frontend/src/components/common/Table/ScrollableTable/CellMenu.tsx

Closes:  https://github.com/lightdash/lightdash/issues/12496
I think the issue is only happening on embedding because other dashboards/pages are wrapped by perhaps a scrollable component , with relative position, where `window.scrollY` is always 0. We could use the same wrapper on embedding to fix the issue, however, I'm not sure exactly how this is done, or if that will cause other issues (eg: when printing the page) 
I belive this solution (given we are already hacking the position using absolute) it is more reusable, since it doesn't depend on the wrapper. 
Added scroll to absolute position of the menu
Before
After
I also tessted this on `dashboard tables` , `explore table` and `results`

fix: fix cell context menu embedding

---

examples/full-jaffle-shop-demo/dbt/models/schema.yml
packages/common/src/compiler/translator.ts
packages/common/src/schemas/json/lightdash-dbt-2.0.json
packages/common/src/types/dbt.ts
packages/common/src/types/field.ts
packages/common/src/types/table.ts

Relates to: #12392
allow this definition on the table/model-level:
```yml
default_time_dimension:
field: timestamp_tz
interval: MONTH
```
- demo
test-cli
test-frontend
test-backend

chore: allow default time dimension for tables

---

packages/common/src/visualizations/CartesianChartDataModel.ts

Closes: #12484 
Apply formatting to value labels in SQL runner. It was missing. 
To test:
- Make a chart in SQL runner
- Add percentage formatting
- Add value labels formatting
- You should see the value label formatted with percent

fix: apply formatting to value labels

---

packages/warehouses/package.json

Closes: 
Multiple developers get the error about missing certificate because it was only copied on `build` and not on `dev` command.
Two recent threads: 
- https://lightdash-community.slack.com/archives/C03MG2VTR08/p1730713172417309
- https://lightdash-community.slack.com/archives/C03MG2VTR08/p1731741092008529

chore: copy warehouse certificates on dev command

---

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumnName.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx

Closes: N/A
Demo for < editor
https://github.com/user-attachments/assets/1ab1d2a9-cb33-4806-be94-62936d893844
Demo for >= editor
https://github.com/user-attachments/assets/201c19c6-9244-430a-8500-6d1f66307711
> [!NOTE]
> The backend already checks for permissions, so even though the user with insufficient perms could change some stuff on the ui, it would error on the BE, reverting back to the original state.

fix: change ui feedback when no perms to manage catalog

---

packages/warehouses/package.json
yarn.lock

Upgrades databricks -> `1.8.4` which sets `lz4` as an optional dependency. So if building `lz4` fails, yarn will continue. 
Note that yarn will still try to install lz4 with every `yarn install` unless you specify explicitly `yarn install --ignore-optional`

chore: update databricks-sql to 1.8.4

---

packages/common/src/visualizations/CartesianChartDataModel.ts
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/store/thunks.ts

Closes: #12501 
The SQL color picker wasn't matching the colors displayed on the chart by default. We were passing an empty array instead of undefined, which was causing the colors to default incorrectly
To repro:
- Run a query
- Make a bar chart with multiple series
- Notice that the color picker is a different color than the second series by default 
Before:
With this fix:

fix: color picker not matching colors in sql runner

---

packages/frontend/src/hooks/useExplorerRoute.ts

Relates to: #12392
- does only metric selection if no default dimension in table.
- goes to explorer and displays a big number chart.
demo:
https://github.com/user-attachments/assets/1acf836b-b50a-4cc9-8eca-4157a8b686ab

feat: open big number if no default dim on metric explore

---

packages/backend/src/queryBuilder.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/filter.ts
packages/common/src/utils/formatting.ts

Closes: https://github.com/lightdash/lightdash/issues/12448
No date zoom 
With month date zoom 
Before
After

fix: apply date granularity to filters

---

packages/e2e/cypress/e2e/app/dashboard.cy.ts
packages/frontend/src/components/DashboardFilter/Filter.tsx
packages/frontend/src/pages/Dashboard.tsx

Closes: N/A
After this merge: https://github.com/lightdash/lightdash/pull/12439, filter pills are scrollable if no space left/too long, but that included a change to the parent box of these where there's an overflow applied, leading to cypress issues like: 
```
This element <input#mantine-0nhrxw6dt.mantine-Input-input.mantine-Select-input.mantine-gcbe4a> is not visible because its content is being clipped by one of its parent elements, which has a CSS property of overflow: hidden, scroll or auto
```
even though a real user could interact with the popovers, cypress couldn't because it was classified as not visible. 
1. Simplified styles
2. added withinPortal prop to filter popover.

fix: open dashboard filter popover within portal

---

packages/common/src/visualizations/CartesianChartDataModel.ts

Closes: #12527 
In the SQL runner, the x-axis will now be sorted by default.

feat: sort x-axis by default in SQL runner

---

packages/frontend/src/features/tableCalculation/components/SqlForm.tsx
packages/frontend/src/features/tableCalculation/components/TableCalculationModal.tsx

Closes: #12552 
- When adding a table calculation the editor is focused on load
- CMD/Crtl + Enter will attempt to submit the form

fix: focus editor on load & cmd + enter to submit for table calculation

---

packages/frontend/src/components/DataViz/visualizations/ChartDataTable.tsx
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx

Closes: 
Disable sorting on grouped cols in SQL runner. Repro: make a chart in SQL runner, add a group, check that you can't click on the pivoted columns in the chart table.

fix: I shouldnt be able to sort by a pivoted column

---

packages/backend/src/controllers/csvController.ts
packages/backend/src/scheduler/SchedulerTask.ts
packages/backend/src/services/SchedulerService/SchedulerService.ts

Closes: [#12561](https://github.com/lightdash/lightdash/issues/12561)
Changes:
- amend all scheduled jobs to store the error message in the log
- amend the csv service to throw an error when there is an error log
Before the FE would not detect an error and kept pulling the request resulting in a infinite spinner.
Now it shows the error message
To reproduce:
- create a chart from "customers" add last name in x axis, a metric in y axis and pivot by first name
- add chart to dashboard
- go to dashboard
- click export CSV from chart tile

fix: show error when downloading CSV

---

packages/backend/src/controllers/catalogController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/CatalogService/CatalogService.ts
packages/common/src/types/catalog.ts
packages/frontend/src/Routes.tsx
packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumnName.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx
packages/frontend/src/features/metricsCatalog/hooks/useMetricsCatalog.tsx
packages/frontend/src/features/metricsCatalog/store/metricsCatalogSlice.ts

Closes: [#12591](https://github.com/lightdash/lightdash/issues/12591)
- adds new endpoint to get a metric through /dataCatalog/metrics/{tableName}/{metricName}
- it gets the filtered explore, which accounts for user attributes 
- gets metric with hook
on the UI:
- when the user clicks on a metric name, it will open the modal (tooltips and improvements in interaction shall be done separately)
- when the modal opens, the url changes as well to: `/metrics/peek/orders/average_order_size`
- if the user visits this url, the modal will open 
demo: 
https://github.com/user-attachments/assets/682fff88-dc14-417f-80a5-6b06291ca321

feat: display metric peek modal on click of metric column name

---

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx
packages/frontend/src/features/metricsCatalog/store/metricsCatalogSlice.ts

Relates to: #12542
- Hides explore button in metrics catalog when user doesn't have access to the explore

fix: hide explore button when user doesn't have access to explore

---

packages/frontend/src/features/metricsCatalog/components/ExploreMetricButton.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx

Relates to: #12542
Before:
After:

fix: allow metric name to use the whole width of the cell and cta to overlay

---

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx

Relates to: #12542 
- Removes bottom border when there are no results
- Fixes misc double borders on right and bottom (last row and last column)
Before:
After:

fix: remove divider when no results and double borders

---

docs/docs/references/tables.mdx

Adds references to row-level filtering in the `tables` reference docs (because I couldn't find the docs and went looking here)

docs: add row level filtering to tables

---

packages/backend/src/models/UserModel.ts

Dependant Commercial PR: https://github.com/lightdash/lightdash-commercial/pull/407
- on user create conflict in userModel it now throws a more appropriate `AlreadyExistsError` instead of `ParameterError`

fix: duplicate user on create throws correct error

---

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar.tsx

…ser is viewer/interactive_viewer
Relates to: #12542
- Hides categories column & filters when data has no categories and user is viewer/interactive viewer

chore: hide categories and filters when there are no categories and user is viewer

---

packages/backend/src/App.ts
packages/backend/src/logging/winston.ts

Relates to: [#2276](https://github.com/lightdash/lightdash-internal-work/issues/2276)
Log HTTP requests with and without response so allow us to detect which requests crash the server.
Logs without response are disabled in dev environment.
Example

chore: log http requests with and without response metadata

---

packages/common/src/types/filter.ts
packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
packages/frontend/src/components/common/Filters/FilterInputs/FilterUnitOfTimeAutoComplete.tsx

Closes: #12604
- when adding querying from tables and adding filters, it will now only show relevant values. Previously when `Date years` was selected along with `in the last` it will list `days` which is not intuitive

fix: show only relevant date filters for year, month, etc..

---

packages/backend/src/models/ProjectModel/ProjectModel.ts

Closes: #2273
- fixes issue with space group permissions not being copied on preview.

fix: space group permissions gets duplicated over on preview create

---

scripts/clean-repo.sh

Closes: 
- Adds a helper script for clearing out all build files and node_modules. Helpful for when a breaking dependancy is updated and causes run issues in the development environment

chore: added script for cleaning repository

---

packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsVisualization.tsx
packages/frontend/src/pages/MetricsCatalog.tsx

Closes: N/A
- Some spacing updates, borders, sizes etc
- Added default props to `Paper`, which update the border, shadow used, etc
- Removed usage of `AspectRatio`
Screenshot

style: update metric modal peek styles

---

packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx

Closes:  N/A
Apply border indigo and radio button to comparison box
screenshot

style: apply border to selected comparison

---

packages/backend/src/services/CoderService/CoderService.ts

Closes: 
I was not filtering by project, so it was getting the chart from another project with the same slug (likely production rather than preview)

fix: filter project on charts as code

---

packages/frontend/src/features/metricsCatalog/components/MetricsVisualization.tsx

Closes: #12653 
Adds simply-styled tooltip on hover and also shows comparison when that is selected

feat: show tooltip on hover of metric peek viz

---

examples/full-jaffle-shop-demo/dbt/models/schema.yml
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/CatalogService/CatalogService.ts
packages/common/src/schemas/json/lightdash-dbt-2.0.json
packages/common/src/types/dbt.ts
packages/common/src/types/field.ts
packages/common/src/types/table.ts
packages/common/src/types/timeFrames.ts

Closes: [#12585](https://github.com/lightdash/lightdash/issues/12585)
Similar to work done on: https://github.com/lightdash/lightdash/pull/12505
- can specify metric-level `default_time_dimension`
- if both are given, the metric level will take precedence, otherwise, fallback to the table-level defined default time dimension
demo: 
**metric-level: DAY**
**table-level: MONTH** for another metric that has no metric-level info set

feat: allow default time dimension on a metric-level

---

packages/backend/src/controllers/catalogController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/services/CatalogService/CatalogService.ts
packages/common/src/utils/catalogMetricsTree.ts
packages/frontend/src/features/metricsCatalog/components/MetricTree/index.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar.tsx
packages/frontend/src/features/metricsCatalog/hooks/useMetricsTree.tsx
packages/frontend/src/features/metricsCatalog/store/metricsCatalogSlice.ts

Closes: #12679 
⚠️ Depends on https://github.com/lightdash/lightdash/pull/12643
- Adds limit of 30 metrics to display on the tree
- When there are more than 30 metrics (by changing filters) and user is on the tree, show suboptimal state
https://github.com/user-attachments/assets/64f8258e-5739-4439-9f79-27607403d138

feat: limit metric node count

---

packages/backend/src/database/entities/savedCharts.ts
packages/backend/src/models/SavedChartModel.ts

Closes: 
Fix issue where results table would not show column totals.
Before:
Save chart returns `timezone: null` when it expects `string | undefined` 
Total request fails because `timezone: null` is not a valid value.
Validation error in BE
After:
Save chart doesn't return a timezone if there isn't one.
Total request works.

fix: saved chart with null timezone

---

packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/ProjectService/ProjectService.ts

Relates to: https://github.com/lightdash/lightdash-internal-work/issues/2312
**Note:** this doesn't fix all the issues related to using join alias. There is a separate ticket for that:https://github.com/lightdash/lightdash/issues/12680
Update autocomplete logic to find the original explore for join alias instead of using the explore where the join belongs to.
Needs to be tested locally and update payments joins to have an alias:
```
- name: payments
description: This table has information about individual payments
meta:
joins:
- join: orders
sql_on: ${orders.order_id} = ${payments.order_id}
- join: customers
alias: customer_alias
sql_on: ${customer_alias.customer_id} = ${orders.customer_id}
```
Before it would use the "payments" explore and join "customer alias".
Now it uses the …

fix(dashboards): autocomplete for joined tables using alias

---

packages/frontend/package.json
packages/frontend/src/features/metricsCatalog/components/MetricTree/index.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
yarn.lock

Closes: #12665 
Basic layout for the metric tree including:
- A tree layout of connected nodes
- A grid of unconnected nodes
This is pretty basic and will have to be iterated on, but it will give us something to try. Some obvious missing things:
- Style for the group so it can have a name like "Unconnected nodes". The default group doesn't have a lable
- A spinner or a better await while the tree is building
- Experiments with other data. I only tested locally

chore: metric tree layout

---

docs/docs/references/dimensions.mdx
docs/docs/references/metrics.mdx

Update time intervals docs to have more clear examples. (removes a bunch of unnecessary middle sections). 
Adds model-level metrics example to metrics.yml example

docs: update time intervals

---

packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts

Closes: [#12699](https://github.com/lightdash/lightdash/issues/12699)
pg client doesn't support native BitInt values ([ref](https://github.com/brianc/node-pg-types/issues/78)) so we have to implement the workaround suggested [here](https://github.com/brianc/node-pg-types/issues/78#issuecomment-538632724)
Type parser was introduced in https://github.com/lightdash/lightdash/commit/e8a4ea1eb7dcdd488d9786b6e0e157fa6d530495
Data:
Before:
After:
Update raw_plan.csv
```
id,plan_name,metadata,big_number
1,free,{"created_by":"John Miller"},9223358433259708591
2,silver,{"created_by":"Elliot Stone"},9223358433259708592
3,gold,{"created_by":"John Miller"},9223358433259708593
4,platinum,{"created_by":"Elliot Stone"},9223358433259708594
5,diamond,{"created_by":"John Miller"},9223358433259708595
``` …

fix: big numbers in Postgres

---

packages/backend/src/controllers/metricsExplorerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/CatalogService/CatalogService.ts
packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts
packages/common/src/types/catalog.ts
packages/common/src/types/metricsExplorer.ts
packages/common/src/utils/metricsExplorer.ts
packages/frontend/src/features/metricsCatalog/components/MetricPeekDatePicker.tsx
packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/TimeDimensionIntervalPicker.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/TimeDimensionPicker.tsx
packages/frontend/src/features/metricsCatalog/hooks/useDateRangePicker.tsx
packages/frontend/src/features/metricsCatalog/hooks/useRunMetricExplorerQuery.ts
packages/frontend/src/hooks/useExplorerRoute.ts

Closes: [#12667](https://github.com/lightdash/lightdash/issues/12667)
- Generates a default time dimension for a metric if defined on table yml - test with `Average order size`
- metric yml - test with `Total order amount`
- if the table only has ONE date dim - test with `Unique customer count`
If no defaults available ⬆️ , we then get the available time dimensions for that metric and allow the changing of the field and/or interval - you can test this with anything in `payments` table, `events` table etc
demo:
https://github.com/user-attachments/assets/d5c669d7-30ef-417d-af62-41eb61e22769
> [!IMPORTANT]
> The granularity/interval changes the chart as it should, as well as the filtered range - however, the filter component is not in sync with the change. I want to tackle this on this …

feat: render metric visualization even if no default & config

---

packages/frontend/src/features/metricsCatalog/components/MetricTree/MetricTreeConnectedNode.tsx
packages/frontend/src/features/metricsCatalog/components/MetricTree/MetricTreeUnconnectedNode.tsx
packages/frontend/src/features/metricsCatalog/components/MetricTree/index.tsx

relates to: #12693 
First round of styles for metric tree nodes. The numeric data is faked at the moment, but this sets up custom tree nodes.

chore: metric tree nodes styles

---

packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Closes: #12574 
- modifies the `applyLimitToSqlQuery` function to strip out limits and semicolons from subqueries and applies limit to end of query
- It also looks for the smallest outer limit applied and will use the smaller one
// keyword to include frontend tests
test-frontend

fix: strip subquery query limits and append to end

---

packages/frontend/src/features/metricsCatalog/components/ExploreMetricButton.tsx
packages/frontend/src/features/metricsCatalog/hooks/useMetricsCatalog.tsx

Closes: N/A
Only enable query on click of explore:
currently, all metrics present on the catalog will trigger api requests. this is unnecessary.

fix: only enable metric query on click of explore

---

packages/backend/src/SchedulerApp.ts

Closes: [#12735](https://github.com/lightdash/lightdash/issues/12735) 
Apply the same BigInt.toJson() method we have in App.ts to SchedulerApp.ts. 
Before:
After:
--- 
To reproduce this, you have to run the scheduled app in a different container. 
Edit your `docker/docker-compose.dev.yml` to have:
```
scheduler:
build:
context: ..
dockerfile: dockerfile
target: dev
depends_on:
- db-dev
environment:
- PGHOST=${PGHOST}
- PGPORT=${PGPORT}
- PGUSER=${PGUSER}
- PGPASSWORD=${PGPASSWORD}
- PGDATABASE=${PGDATABASE}
- SECURE_COOKIES=${SECURE_COOKIES}
- LIGHTDASH_SECRET=${LIGHTDASH_SECRET}
- LIGHTDASH_LOG_LEVEL=${LIGHTDASH_LOG_LEVEL}
- NODE_ENV=${NODE_ENV}
- DBT_DEMO_DIR=${DBT_DEMO_DIR}
- SITE_URL=${SITE_URL}
- LIGHTDASH_QUERY_MAX_LIMIT=${LIGHTDASH_QUERY_MAX_LIMIT}
- …
```

fix: stringify BigInt in scheduler worker

---

packages/frontend/src/features/metricsCatalog/components/ExploreMetricButton.tsx

Relats to: https://github.com/lightdash/lightdash/pull/12732
After https://github.com/lightdash/lightdash/pull/12732, the metrics explorer and standard explorer were opening at the same time. 
This PR fixes that and skips the opening on a new tab if the button hasn't been clicked.

fix: dont open url if shouldFetch is false

---

packages/common/src/utils/metricsExplorer.ts
packages/frontend/src/features/metricsCatalog/components/MetricPeekDatePicker.tsx
packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/TimeDimensionIntervalPicker.tsx
packages/frontend/src/features/metricsCatalog/hooks/useDateRangePicker.tsx
packages/frontend/src/features/metricsCatalog/utils/metricPeekDate.tsx

Closes: [#12659](https://github.com/lightdash/lightdash/issues/12659)
> [!IMPORTANT]
> See Miro attached to ticket on all the rules
This PR:
- adds presets per each time frame/interval
- adds week-range picker
- has different pickers depending on the interval chosen
DAY
https://github.com/user-attachments/assets/b668f828-093f-4305-8c59-a3f54dc88b74
MONTH
https://github.com/user-attachments/assets/d85177ce-b6e5-40a0-915c-244deb1cca55
YEAR
https://github.com/user-attachments/assets/aeaabde2-e686-402e-a332-9f7ff02053b6

feat: tune date zoom when metric-exploring

---

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar.tsx

Closes: #12752 
- Disables metric tree for viewers when there are no edges between the selected metrics
- Editors and up can still access the tree in that case and only have access disabled when the metric count is invalid
https://github.com/user-attachments/assets/ecc8121f-650e-4e4a-923a-5c4cd6b84d1b

fix: disable tree for viewer when invalid edge count

---

packages/backend/src/controllers/v2/ContentController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/ContentModel/ContentConfigurations/DashboardContentConfiguration.ts
packages/backend/src/models/ContentModel/ContentConfigurations/DbtExploreChartContentConfiguration.ts
packages/backend/src/models/ContentModel/ContentConfigurations/SemanticViewerChartContentConfiguration.ts
packages/backend/src/models/ContentModel/ContentConfigurations/SqlChartContentConfiguration.ts
packages/backend/src/models/ContentModel/ContentModelTypes.ts
packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx
packages/frontend/src/components/DashboardTiles/TileForms/ChartUpdateModal.tsx
packages/frontend/src/hooks/useChartSummariesV2.ts

Relates to: [#12759](https://github.com/lightdash/lightdash/issues/12759) 
Changes:
- update content endpoint to search by name
- replace useChartSummaries for `useChartSummariesV2` in dashboard modals

fix: paginate charts in dashboard modals

---

packages/backend/src/services/CatalogService/CatalogService.ts
packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts
packages/common/src/utils/metricsExplorer.ts
packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
packages/frontend/src/features/metricsCatalog/hooks/useRunMetricExplorerQuery.ts

Closes: N/A
After this merge: https://github.com/lightdash/lightdash/pull/12748, I found some issues when interacting with the Date zoom + metric comparison. This PR addresses that.
This PR ensures that Date zoom works ok when comparing metric A with another metric. 
Granularity is respected. 
Values are parsed so that the y axis range is correct - can revert this change if we want to tackle this differently.

fix: address time interval overrride on comparison of metrics

---

packages/frontend/src/features/metricsCatalog/components/MetricPeekDatePicker.tsx
packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/TimeDimensionPicker.tsx

Closes: https://github.com/lightdash/lightdash/issues/12739
- Show time dimension picker below chart if there are available dimensions (no default)
- If not, hide it
- Always keep picker visible if its supposed to be visible - resize window
- Do **not** keep Modal mounted - it causes issues between metric peeks - sometimes the chart takes the whole height and it hides the picker, so this was the fix. 
- Moves legend to above the chart
Demo
https://github.com/user-attachments/assets/c1bdfb84-767b-4faa-af8c-4950dc08937b

style: move time dimension picker to below viz

---

packages/backend/src/routers/projectRouter.ts
packages/backend/src/routers/slackRouter.ts

Closes:  https://github.com/lightdash/lightdash-internal-work/issues/2438
These 2 endpoints are only used when s3 is not available

chore: improve file path

---

packages/backend/src/models/GroupsModel.ts

Related to: https://github.com/lightdash/lightdash-commercial/pull/411 
- fixes an issue where newMembers of a group throws an error if it doesn't match the length of what is in the DB. this causes issues for SCIM where the list may contain users that don't exist yet.

chore: fixed group update so it doesn't throw on empty list

---

packages/backend/src/services/CatalogService/CatalogService.ts

Closes: #12772
Adds `getMetrics` service method to get all metrics in batch - allows receiving user attributes to fix a n+1 query
`getMetric` calls `getMetrics` with just one metric in the array

perf: get metrics with batched attribute-filter

---

packages/backend/src/generated/swagger.json
packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/models/CatalogModel/utils/index.ts
packages/backend/src/services/CatalogService/CatalogService.ts
packages/backend/src/services/DashboardService/DashboardService.ts
packages/backend/src/services/SavedChartsService/SavedChartService.ts
packages/common/src/types/catalog.ts

Closes: 
- Updates the chart usage taking into account field type
- Improves the chart usage update query so that it only performs at most 2 queries, one for increments and one for decrements

chore: improve chart usage update query

---

packages/common/src/utils/metricsExplorer.ts

Closes: N/A
get year forward instead of back - after merging this: https://github.com/lightdash/lightdash/pull/12793/files#diff-3618c7b719361cc6c12376a7ebfefc923784745ff035551f32ecd3150011f687
before
after

fix: get year forward on PoP comparison

---

packages/backend/src/models/GroupsModel.ts
packages/e2e/cypress/e2e/api/groups.cy.ts
pnpm-workspace.yaml

- Adds more specific error types thrown if there are errors in `GroupModel.updateGroup()` for use downstream

chore: updated types of errors thrown on updateGroup

---

packages/backend/src/clients/EmailClient/EmailClient.mock.ts
packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/services/HealthService/HealthService.mock.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/common/src/index.ts
packages/frontend/src/pages/Explorer.tsx
packages/frontend/src/pages/MinimalSavedExplorer.tsx
packages/frontend/src/pages/SavedExplorer.tsx
packages/frontend/src/providers/ExplorerProvider.tsx
packages/frontend/src/testing/__mocks__/api/healthResponse.mock.ts

Closes: #5082 
Adds an environment variable to make the default limit configurable. I believe this is the first explore default param that is set in the env config, so there is a little plumbing to make that work. 
Note that this is *not* currently plumbed into the SQL runner or Semantic viewer, but that could be added here or in a follow up. 
To test: 
- set `LIGHTDASH_QUERY_DEFAULT_LIMIT` 
- check that the new default is used in explores

feat: make default limit configurable

---

packages/frontend/src/components/Explorer/ExplorerHeader/index.tsx
packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/components/common/ShareShortLinkButton/index.tsx

Closes: [#12810](https://github.com/lightdash/lightdash/issues/12810)
Generate URL with entire chart config rather than using current URL which removes chart config to keep URL valid.
Same fix as https://github.com/lightdash/lightdash/pull/12400
Sharing from explore
https://github.com/user-attachments/assets/86e6e9bd-cc0c-45f6-9e59-748c0979f78c

fix: share unsaved chart config

---

packages/frontend/src/features/metricsCatalog/components/ExploreMetricButton.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumnName.tsx
packages/frontend/src/providers/TrackingProvider.tsx
packages/frontend/src/types/Events.ts

Closes: [#12713](https://github.com/lightdash/lightdash/issues/12713)
- Opens metric explorer on explore button click
- Adds new event `METRICS_CATALOG_METRIC_NAME_CLICKED`

chore: cta of explore button opens metrics explorer

---

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx

Closes: #12715 
- Removes double borders on bottom last row and left last column

fix: metrics catalog double border

---

packages/frontend/src/components/Explorer/SpaceBrowser/AddResourceToSpaceModal.tsx
packages/frontend/src/components/common/ResourceView/InfiniteResourceTable.tsx
packages/frontend/src/hooks/useContent.ts
packages/frontend/src/pages/Space.tsx

Closes: 
Charts page is showing charts from all projects the user has access to.
Space page was working well because it was filtering by space uuid.
Change:
- fix URL param, it was `projectUuid` instead of `projectUuids`
Steps to replicate:
- create preview
- go to charts page
before:
after:

fix: chart page showing charts from all projects the user has access to

---

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx
packages/frontend/src/hooks/useRefreshServer.tsx

Closes: #12822
- listen to changes of project uuid param - it now will trigger a new query if we change the project from the project switcher on the nav bar
- reset metrics-catalog query on refresh of catalog
demo
https://github.com/user-attachments/assets/8b2c4e1c-d356-4494-a603-e1fba1c4abc7

fix: listen to project uuid changes and reset on refresh

---

packages/frontend/src/components/common/Filters/FilterInputs/FilterStringAutoComplete.tsx

Closes:  https://github.com/lightdash/lightdash/issues/12790
- pinned to the bottom
- change tooltip copy 
[Screencast from 2024-12-11 11-17-13.webm](https://github.com/user-attachments/assets/52e46f46-2002-4432-845f-3a92dcb3f331)
In dashboards:

fix: improve cache autocomplete UI

---

packages/backend/src/scheduler/SchedulerClient.ts
packages/backend/src/scheduler/SchedulerWorker.test.ts
packages/backend/src/scheduler/SchedulerWorker.ts

Closes: 
Jobs scheduled for midnight were not running when the job creating task happened after the first minute of the day. The method which finds which jobs to run rounds down to the beginning of the minute, so when it runs at 00:00:30, it catches jobs at midnight, but if it runs at 00:01:30, it misses jobs in the first minute.
This fix makes it so `generateDailyJobsForScheduler` takes an optional starting time after which to generate jobs. When we are creating the daily jobs, we now pass the start of the day `00:00:00`. So all jobs in that minute and after get added. 
Note that other calls to `generateDailyJobsForScheduler` from `create` and `update` methods DO NOT pass a start time since we want them to create jobs starting from when they are called.

fix: generate jobs starting at midnight, even when scheduler is delayed

---

packages/frontend/src/features/metricsCatalog/components/MetricPeekComparison.tsx
packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx

Closes: [#12844](https://github.com/lightdash/lightdash/issues/12844)
mantine's disabled prop hides the right section
and
data-disabled prop does not get forwarded to the input
this is fixed in mantine 7 but have not found a way to make it work with mantine 6, thus I removed disabled state completely and left a comment

fix: metrics explorer segment compare select loading states

---

packages/frontend/src/features/metricsCatalog/components/MetricPeekModal.tsx

Closes: [#12862](https://github.com/lightdash/lightdash/issues/12862)
sets comparison as none if its comparing a different metric but that is still empty

fix: set comparison as none if empty metric

---

packages/backend/src/clients/Google/GoogleDriveClient.ts
packages/backend/src/scheduler/SchedulerTask.ts
packages/common/src/types/errors.ts

Closes:  https://github.com/lightdash/lightdash/issues/12825
We were already disabling some google sheet schedulers on specific errors 
- invalid_grant : integration with gsheets was removed https://myaccount.google.com/connections
- request entity: file was removed from gdrive 
Now I'm throwing a new error type, and capturing all errorrs to disable schedulers. 
And sending a notification to slack 
Disabling gsheets
slack notification:

fix: capture all errors from gsheet, disable scheduler and notify

---

packages/backend/src/services/CoderService/CoderService.ts
packages/common/src/types/coder.ts

Thread: https://lightdash.slack.com/archives/C07UA0AC2G2/p1734084141684769?thread_ts=1734029192.374489&cid=C07UA0AC2G2
Removes tile uuid from dashboard as code, it was not used, but it was causing confusion to users.

fix: remove tile uuid from dashboard as code

---

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx

Closes: 
- when there's no scroll it means that there won't be overlap with footer, so we don't set border bottom to `none`
- when there's scroll, we set it to `none` so there's no double borders

fix: only set border bottom to none when theres scroll and is last row

---

packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx

Closes: #12888 
https://github.com/user-attachments/assets/5063e9e4-8ea4-4557-be9a-9384dbb1a861

fix: metrics explorer y label align center

---

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
packages/frontend/src/features/metricsCatalog/hooks/useMetricsCatalog.tsx
packages/frontend/src/providers/TrackingProvider.tsx
packages/frontend/src/types/Events.ts

Closes: N/A
Tracks when user searches the metrics catalog

chore: track when searching metrics catalog

---

packages/frontend/src/features/metricsCatalog/components/MetricPeekComparison.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
packages/frontend/src/features/metricsCatalog/styles/useSelectStyles.ts

Closes: 
transitions on metrics explorer
disables tooltip animation (recharts)

style: add transition animations to metrics explorer clickables

---

packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts
packages/common/src/utils/metricsExplorer.ts
packages/frontend/src/features/metricsCatalog/hooks/useDateRangePicker.tsx
packages/frontend/src/features/metricsCatalog/utils/metricPeekDate.tsx

Closes: [#12893](https://github.com/lightdash/lightdash/issues/12893)
When comparing to previous year, on a week granularity, there was no offset applied to the start of the week, now we address that and values align with the previous year's relative week. 
Also, have used isoWeek plugin so that the it matches the isoString usage we have - thoughts?
Demo:

fix: use isoWeek and offset weeks correctly on PoP

---

packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/controllers/projectController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/CoderService/CoderService.ts
packages/cli/src/handlers/download.ts
packages/common/src/types/coder.ts

Closes: #12856
[Screencast from 2024-12-17 09-23-58.webm](https://github.com/user-attachments/assets/96a20ce6-c8a4-473e-a7b1-18765778fe87)
I tried stress loading this a bit, it seems to be working as expected 
We can increase the max concurrent charts if we like. 
178 charts + 39 dashboards takes 2 seconds to download in batches 
I created thousand of charts and dashboards, some charts were charts within dashboards
I allowed 1000 simultaneous charts (aka 1000 queries to the database) 
The old listing of charts and dashboards in the UI breaks with a few hundreds
Some charts were as big as 119kb (4351 lines) 
Memory increased  a small amount per call 
Command took 12 seconds 
Conclusion: 1000 simultaneous requests are manageable, however, I think having a limit of 100 charts per query makes …

fix: content as code download in batches

---

packages/frontend/src/features/sqlRunner/components/Header/HeaderCreate.tsx
packages/frontend/src/features/sqlRunner/hooks/useSqlRunnerShareUrl.ts
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts
packages/frontend/src/pages/SqlRunnerNew.tsx

Closes: [#12829](https://github.com/lightdash/lightdash/issues/12829) 
Problems:
- we were storing results and other state properties that should not be part of a share url
- we had to rerun the query on load
- we were not storing the viz config in the share url
Changes:
- move all logic around share URL to hooks
- only save relevant properties in share url
- save viz config in share url
- handle legacy URLs
https://github.com/user-attachments/assets/3ccb5ea1-7678-427b-bb86-b8f94c8b6234

fix: SQL runner share url

---

packages/common/src/types/savedCharts.ts
packages/frontend/src/components/VisualizationConfigs/PieChartConfig/PieChartDisplayConfig.tsx
packages/frontend/src/hooks/echarts/useEchartsPieConfig.ts
packages/frontend/src/hooks/usePieChartConfig.ts

Closes: [#12801](https://github.com/lightdash/lightdash/issues/12801)
Problem: large series labels would cause the legend to overlap the chart and the tooltip to be partially hidden.
Changes:
- truncate legend labels by default
- truncate tooltip labels by default
- allow to change legend label max length ( no option to change tooltip for now )
---
---
g

feat: pie chart legend max length

---

packages/frontend/src/components/VisualizationConfigs/ColorSelector.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingItem.tsx
packages/frontend/src/components/VisualizationConfigs/common/AccordionControl.tsx

Closes: #12657 
Shows the color and the column name in conditional formatting list (before it was a rule number).
Now:
Before:

feat: show conditional format field name and color in list

---

packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreLegend.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx

Closes: #12911
Adds custom Legend wrapper 
Calculates widths of text, truncates, shows tooltip 
Ensures that 2 rows max per page if too large of a set of legends
Demo:
https://github.com/user-attachments/assets/77c004f7-eaad-42ec-bc8f-ab4a43cb3619

feat: add new custom legend wrapper and handle pagination

---

packages/backend/src/controllers/v2/FeatureFlagController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/FeatureFlagModel/FeatureFlagModel.ts
packages/backend/src/models/ModelRepository.ts
packages/backend/src/services/FeatureFlag/FeatureFlagService.ts
packages/backend/src/services/HealthService/HealthService.mock.ts
packages/backend/src/services/HealthService/HealthService.ts
packages/backend/src/services/ServiceRepository.ts
packages/common/src/index.ts
packages/common/src/types/featureFlags.ts
packages/frontend/src/components/ProjectAccess/index.tsx
packages/frontend/src/components/UserSettings/UserAttributesPanel/UserAttributeModal.tsx
packages/frontend/src/components/UserSettings/UserAttributesPanel/index.tsx
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/UsersView.tsx
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/index.tsx
packages/frontend/src/hooks/useFeatureFlagEnabled.ts
packages/frontend/src/pages/Settings.tsx
packages/frontend/src/testing/__mocks__/api/healthResponse.mock.ts

Closes: [#12939](https://github.com/lightdash/lightdash/issues/12939) 
Centralize feature flag source logic in the Model so it can be used by all services. In the near future, we will also have a table in the DB to control feature flags at the org/user level.
Changes:
- create feature flag controller/service/model
- move user groups feature flag logic to new model
- remove users group flag from health endpoint
- update frontend to use new hook/endpoint
`GROUPS_ENABLED=false` + false Posthog feature flag
`GROUPS_ENABLED=true` + false Posthog feature flag
OR
`GROUPS_ENABLED=false` + true Posthog feature flag

chore: feature flag endpoint

---

packages/common/src/utils/timeFrames.ts
packages/frontend/package.json
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts
yarn.lock

Closes: [#4431](https://github.com/lightdash/lightdash/issues/4431)
⚠️ this required an upgrade to the latest version of echarts
⚠️ I tried to hide the ticks for the hidden labels but could not succeed.
ℹ️ for better readability, when the granularity is `day` I make the year and month labels bold to distinguish it easily for days when they are close.
---

fix: echarts overlapping labels

---

packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts
packages/backend/src/services/ProjectService/ProjectService.ts

This reverts commit 0338c1db15f1e0be315abbe2f52ce02c542da633.
This is causing an issue for some customers in the SQL runner. Reverting for now while I figure out what was missing from test coverage.

fix: revert "fix: add support for double slash SQL comments (#12942)"

---

packages/backend/src/logging/measureTime.ts
packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts
packages/backend/src/services/ProjectService/ProjectService.ts

Relates to: https://github.com/lightdash/lightdash/issues/12970
- logs operation duration of main function calls to render a chart on the metrics explorer
- same for metric trees' nodes metric total 
- this also includes logs for the metric query against the warehouse, format rows logic, and getting results from cache

chore: log and measure operations for metrics explorer/trees

---

packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreLegend.tsx

fix: have legend icon variants on metrics explorer

---

packages/cli/src/handlers/download.ts

Closes:  https://github.com/lightdash/lightdash/issues/12903
Another example (creating folders) 
i’d expect that the dashboard selector would always download charts linked to the dashboard (even if I added a chart selector as well).

fix: downloading a specific dashboard also downloads all associated charts

---

packages/frontend/src/features/metricsCatalog/components/visualization/TimeDimensionIntervalPicker.tsx

fix: reset grain dropdown picker width

---

packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreTooltip.tsx

fix: get correct key on previous period

---

packages/common/src/index.ts

Closes: #12981 
Biggest performance gain came from not using spread!
Code used to test
```typscript
import { formatRows, formatRowsOld } from './index';
import { DimensionType, FieldType, type ItemsMap } from './types/field';
// Mock data and types needed for testing
const createMockItemsMap = (columnCount: number): ItemsMap => {
const itemsMap: ItemsMap = {};
for (let i = 0; i < columnCount; i += 1) {
const columnName = `column${i}`;
itemsMap[columnName] = {
name: columnName,
label: columnName,
type: DimensionType.STRING,
table: 'test_table',
tableLabel: 'Test Table',
description: 'Test column',
hidden: false,
round: 2,
index: i,
fieldType: FieldType.DIMENSION,
sql: '',
};
}
return itemsMap;
};
const createMockRows = (rowCount: number, columnCount: number) =>
Array.from({ length: …
```

fix(perf): improve format rows perf

---

packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts
packages/backend/src/services/ProjectService/ProjectService.ts

Closes: #12981 
Avoids using the worker for metrics catalog as this is impacting the duration of the `formatRows` execution, testing

chore: force avoid worker when formatting for metrics catalog

---

packages/backend/src/controllers/metricsExplorerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/metricsExplorer.ts
packages/common/src/utils/metricsExplorer.ts
packages/frontend/src/features/metricsCatalog/components/MetricTree/MetricTreeConnectedNode.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreTooltip.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/types.ts
packages/frontend/src/features/metricsCatalog/hooks/useRunMetricExplorerQuery.ts

Closes: #12997 
- Formats result values on the frontend instead of backend
- Fix tree total query to use data range query params, previously they were being ignored

feat: format metric explorer and tree values on the frontend instead of backend

---

packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts
packages/common/src/utils/metricsExplorer.ts

Fetches top `MAX_SEGMENT_DIMENSION_UNIQUE_VALUES` segments by metric before running the query so that a filter can be applied to reduce amount of results.

fix: fetch segments to prevent long running query when segmenting

---

packages/frontend/src/features/metricsCatalog/components/visualization/MetricPeekDatePicker.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/TimeDimensionIntervalPicker.tsx

Closes: N/A
Optimistically-update set interval in dropdown and let the query take care of the rest
Ensure we keep a stable previous ref to the chosen date range/label so that the segmented control doesnt jump to custom date ranges when changing the interval. 
https://github.com/user-attachments/assets/c9cc6ee5-c3fa-4fb7-ba76-a96f649bd95a

fix: optimistically set time dimension interval picker

---

packages/frontend/src/features/sqlRunner/components/Sidebar.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts
packages/frontend/src/pages/SqlRunnerNew.tsx

Relates to: #11518 
This does two things:
- Moves sidebar state to the slice, making it possible to control it in other parts of the page
- Opens the sidebar (if it was closed) when switching to the viz tab. This mitigates the issue mentioned in the linked ticket (#11518) where it's confusing to switch to the viz tab and see no cahrt config. We could potentially improve this behavior in the future, but this seems better than what we have. And moving sidebar state to the slice will be necessary for whatever else we do there.

fix: show the sidebar when switching to the viz tab

---

packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx

Closes: N/A
In metrics explorer, run 2 queries that return no results and show empty state. Go between date ranges and see the loading spinner. Before this PR, we weren't showing the spinner at all, which for longer queries, wouldn't be sufficient feedback to the user.

fix: show loading spinner in between empty states

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx

Closes: #11894 
I saw this ticket when looking for something else in the SQL runner and it was easy enough to pick up. 
Removes the orange warning color from unrun SQL as the linked ticket calls for. 
Before
After

fix: remove orange state from SQL runner

---

packages/e2e/cypress/e2e/app/sqlRunnerNew.cy.ts
packages/frontend/src/components/DataViz/store/selectors.ts
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/SaveSqlChartModal.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerListeners.ts
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

Closes: #13013 
This fixes a bug and makes a behavior change:
- **bug:** sql runner cant save when there is only one column
- **change:** when saving from the SQL tab, the viz will be saved as a table, the current view
The implementation does the following
- Populates both table and chart config when data loads (it used to be just the chart config)
- If the user saves while viewing the results table, the table viz will be saved
To test:
- Run a query with one column
- Save from the SQL tab
- A table is saved

feat: enable SQL runner to save to a table when no viz is selected

---

packages/frontend/src/components/DashboardFilter/Filter.tsx
packages/frontend/src/components/DashboardTabs/AddTabModal.tsx
packages/frontend/src/components/DashboardTabs/EditTabModal.tsx
packages/frontend/src/components/DashboardTabs/Tab.tsx

Closes: https://github.com/lightdash/lightdash/issues/12053
**1. Inactive filter dashed border color now slightly darker to avoid optical illusion of dashed line being lighter than solid line**
**2. Tooltip singular/plural tab(s) as appropriate** 
**3. Auto-focus add and edit tab modal text fields**
**4. Reduce width of dashboard tab menu**

feat: dashboard tab ux and style tweaks

---

packages/backend/src/database/migrations/20241226133341_alter-available-tables-column-type.ts
packages/frontend/src/features/sqlRunner/hooks/useTables.tsx
packages/frontend/src/hooks/useProject.ts

Closes: [#2573](https://github.com/lightdash/lightdash-internal-work/issues/2573)
- Fixes column type which lead to errors when inserting
- Fixes hook requesting tables/projects with undefined `projectUuid`
When testing make sure that migration doesn't delete data already existing in table

fix: alter available tables column types

---

packages/frontend/src/components/DashboardTabs/Tab.tsx
packages/frontend/src/components/DashboardTabs/index.tsx

Closes: https://github.com/lightdash/lightdash/issues/11220
Restrict dashboard tabs to one line. Maximum tab width is `1 / num_tabs`. Overflowing tab titles are truncated with and ellipsis, and a tooltip displays on mouseover for these. Gray scrollbar appears below tabs if parent container width exceeded.

feat: restrict dashboard tabs to one line

---

packages/frontend/src/features/sqlRunner/components/TableFields.tsx
packages/frontend/src/pages/ViewSqlChart.tsx

Closes: #11468, #11966 
A couple small changes from tidying up the SQL Runner backlog:
- Remove bottom padding on the fields list
- Make the view page segmented control style match the edit page

fix: remove fields bottom padding, change sql viewer tab style

---

packages/backend/src/services/ProjectService/ProjectService.ts

Closes:  https://github.com/lightdash/lightdash/issues/12697
Simply skip cache if query comes from explore: `{explore}/runQuery`
- view chart uses `/saved/{uuid}/results`
- dashboard uses `/saved/{uuid}/chart-and-results`
- calculate total from explore does not have any cache  (calculateTotalFromSavedChart does) 
- scheduler doesn't rely on this explore method 
We could add a new argument `skipCache` that will also skip the step of uploading results to cloud storage. 
This can be done on this PR, or on a separate PR ( I can make a ticket for it) . 
We'll have to add this argument to multiple methods, and cascade the value from the explore results method until getResultsFromCacheOrWarehouse

fix: skip cache for explore queries

---

packages/cli/src/index.ts

Closes: NA
Please let me know if I should open the issue.
It would be great to boost local development by adding the `--skip-dbt-compile` and `--skip-warehouse-catalog` options to `lightdash compile` as some other commands do. Those options may be for advanced developers who understand the internal behavior of Lightdash CLI. However, they would be very useful to quickly check dimensions and metrics, though the result with the options isn't 100% reliable due to the lack of required information. 
- The `--skip-dbt-compile` option enable us to use the existing `manifest.json`. Sometimes, we don't need to re-generate `manifest.json` every time when running `lightdash compile` in local development.
- The `--skip-warehouse-catalog` option enables us to skip fetching warehouse catalog. If we …

feat: `--skip-dbt-compile` and `--skip-warehouse-catalog` to `compile`

---

packages/frontend/src/components/DataViz/FieldReferenceSelect.tsx

Closes: #11896 
Make the field select style match other dropdowns. 
The selected element is now gray.

fix: [SQL runner] make field select style match other dropdowns

---

packages/frontend/src/features/sqlRunner/components/Header/HeaderCreate.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts
packages/frontend/src/features/virtualView/components/CreateVirtualViewModal.tsx

Closes: #11895 
Use correct name placeholders for virtual view
- Untitled placeholder when no name is entered 
- Default to the name entered on the page in the virtual view dialog (it was empty)

fix: use correct placeholder for virtual views

---

packages/frontend/src/features/metricsCatalog/components/MetricCatalogCellOverlay.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumnDescription.tsx

Closes: #13057 
- Adds ability to preview clamped markdown
**Note:** Removed ability to display highlight for description when searching 
**Before**
**After**

fix: render markdown on clamped description

---

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx

Closes: #12991 
Shows an empty state with link to the metrics docs when no metrics are present. The empty state for 'No results found' when searching is unchanged. 
To test, you have to have no metrics. Locally you can reset the db or return no data in some other way. 
The ticket didn't specify copy, but I made a guess.

feat: empty state links to docs when there are no metrics

---

packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx

Closes: #13081 
- Adds month and year in date range when years are different
**Before**
**After**

fix: adds month to prev period comparison legend when years in date range are different

---

packages/backend/src/database/seeds/development/01_initial_user.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/projectAdapters/projectAdapter.ts
packages/common/src/types/projects.ts
packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx
packages/frontend/src/components/ProjectConnection/index.tsx

Closes: [#10848](https://github.com/lightdash/lightdash/issues/10848)
We save 'latest' in the database and when we need to execute a dbt command we find the latest supported version.

feat: option to use latest dbt version

---

packages/frontend/src/Routes.tsx
packages/frontend/src/pages/Dashboard.tsx
packages/frontend/src/providers/Dashboard/DashboardProvider.tsx

Closes: #13095 
To replicate see issue ^ 
Underlying issue: 
- When we save a dashboard, we navigate back to /view
- The use Effect in dashboard provider for temp filters was running unnecessarily bc the reference was not stable (dashboardTempFilters). I introduced the useDeepCompareEffect to avoid unnecessary re-renders. Before, it would not wait for the navigate in Dashboard.tsx to update the pathname, and a redirect to back to previous pathname (edit mode) would happen.

fix: redirect to view mode when dashboard is saved

---

packages/backend/src/dbt/DbtMetadataApiClient.ts
packages/common/src/types/dbt.ts

Closes: [#13104](https://github.com/lightdash/lightdash/issues/13104)
Problem introduced by: https://github.com/lightdash/lightdash/commit/f5700418f719faf53ed2fd0db696fb6ee273274d
We need to simulate/mock the manifest version when fetching the model data via the dbt cloud graphql API. 
Before:
After:

fix: dbt cloud manifest version

---

packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreLegend.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
packages/frontend/src/features/metricsCatalog/utils/metricPeekDate.tsx

Closes: #12959 
- Adds dashed line for incomplete period
- Calculate uniq legend payload since now we duplicate the line name for the incomplete period to keep legend interactions
https://github.com/user-attachments/assets/62f590a4-afa5-4cd8-b6bb-dc47e934e41f

feat: show different color for incomplete period

---

packages/frontend/src/features/sqlRunner/components/SqlEditor.tsx

Closes: #11805 
Tab will now indent by 2 spaces instead of 4 in the SQL runner. Working through some SQL runner UX tickets.

fix: use 2 space tabs instead of 4 in sql runner

---

packages/frontend/src/components/SchedulersView/SchedulersView.tsx
packages/frontend/src/features/scheduler/components/SchedulersListItem.tsx
packages/frontend/src/features/sync/components/SyncModalView.tsx

Fixes an issue where saved empty strings in Scheduled deliveries timezones cause the list page to crash

fix: handle empty string timezone in FE

---

packages/cli/src/globalState.ts
packages/cli/src/handlers/compile.ts
packages/cli/src/handlers/createProject.ts
packages/cli/src/handlers/dbt/compile.ts
packages/cli/src/handlers/dbt/getDbtVersion.mocks.ts
packages/cli/src/handlers/dbt/getDbtVersion.test.ts
packages/cli/src/handlers/dbt/getDbtVersion.ts

Changes:
- Refactor logic on getting dbt version and fallback
- Show warning/prompt consistently across all Lightdash commands
- Only show prompt once
```
python -m venv dbt-1-3
source dbt-1-3/bin/activate
pip install --upgrade pip
pip install dbt-postgres~=1.3.0
dbt --version
deactivate
source dbt-1-3/bin/activate
```

fix: dbt version fallback prompt

---

packages/frontend/src/components/common/Page/Sidebar.tsx
packages/frontend/src/components/common/Page/constants.ts
packages/frontend/src/hooks/useSidebarResize.ts

Closes: https://github.com/lightdash/lightdash/issues/13124
allows resizing sidebar half the screen size. taking into account window resize as well - when you resize the window the sidebar sizes down too
https://github.com/user-attachments/assets/fe3f939a-0ae2-4a68-b17b-66c71b0c9b27

fix: sidebar resizing to allow showing long field labels

---

packages/frontend/src/features/metricsCatalog/components/MetricTree/index.tsx

Closes: #13050 
**Before**
https://github.com/user-attachments/assets/49611e29-efcc-4f4e-937d-7de343428fdc
**After**
https://github.com/user-attachments/assets/d0c8a8a1-189a-4384-a282-9d603eefd22f

fix: metric tree nodes not loading edges when changing filters

---

packages/backend/src/models/SavedChartModel.ts
packages/backend/src/services/CatalogService/CatalogService.ts

Relates to: [#2647](https://github.com/lightdash/lightdash-internal-work/issues/2647)
- Splits `getChartUsageByFieldId` into:
- `getChartSummariesForFieldId` - gets all summaries for a single field, used in the explorer when clicking usage
- `getChartCountForFieldIds` - count query for multiple fields, used when backfilling chart usage count
- SQL when backfilling usage:
```sql
select "saved_queries_version_fields"."name" as "fieldId", count("saved_queries"."saved_query_uuid") from "saved_queries" left join "dashboards" on "dashboards"."dashboard_uuid" = "saved_queries"."dashboard_uuid" inner join "spaces" on "spaces"."space_id" = "dashboards"."space_id" or "spaces"."space_id" = "saved_queries"."space_id" left join "projects" on "spaces"."project_id" = "projects"."project_id" left join …
```

fix: split chart usage query into count and select for single chart

---

packages/cli/src/handlers/download.ts
packages/cli/src/index.ts

Closes: https://github.com/lightdash/lightdash/issues/13157
I want to add the `--path` option to `lightdash download` and `lightdash upload` respectively so that we can specify the path to manage Lightdash charts and dashboards. If we don't pass the `--path` option, Lightdash CLI manage charts and dashboards in the default directory `lightdash` as today.
```shell
$ node /Users/yu/local/src/github/lightdash/packages/cli/dist/index.js download 
⠙ Downloading charts
Created new folder: /Users/yu/local/src/github/jaffle_shop/lightdash/charts 
✔ Downloaded 5 charts
⠇ Downloading dashboards
Created new folder: /Users/yu/local/src/github/jaffle_shop/lightdash/dashboards 
✔ Downloaded 2 dashboards
Done 🕶
$ tree lightdash/
lightdash/
├── charts
│   ├── -orders-day.yml
│   ├── -orders-month.yml
│ …
```

feat: Enable to specify path of `lightdasah {download,upload}`

---

packages/frontend/src/components/common/GSheetsIcon/index.tsx

Removing styled components to reduce our reliance on them. 
Here are screenshots of everywhere these icons are used I took with this change applied
**Explorer table sync**
**Sync dialog**
**Deliveries list**

chore: remove styled components from gsheets icons

---

packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx

Closes: #12115
The spacing in the sidebar was different between saved and unsaved Explores. The components return fragments which were being wrapped in a stack in unsaved explores and not in saved ones. This just moves the stack to the imported component.

fix: different sidebar spacing between saved and unsaved explores

---

packages/frontend/src/features/metricsCatalog/components/ExploreMetricButton.tsx
packages/frontend/src/features/metricsCatalog/components/MetricExploreModal.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreComparison.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreDatePicker.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreSegmentationPicker.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreTooltip.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
packages/frontend/src/features/metricsCatalog/hooks/useDateRangePicker.tsx
packages/frontend/src/features/metricsCatalog/store/metricsCatalogSlice.ts
packages/frontend/src/features/metricsCatalog/utils/metricExploreDate.tsx

Closes: N/A
Keep /peek url path
Keep peek word references in backend - thats fine
Rename occurrences of "peek" on the frontend bc it was getting confusing - there was a mix of "peek" and "explore"

refactor: replace peek references with explore

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/cli/src/dbt/models.ts
packages/cli/src/globalState.ts
packages/cli/src/handlers/compile.ts
packages/cli/src/handlers/createProject.ts
packages/cli/src/handlers/dbt/compile.ts
packages/cli/src/handlers/dbt/getDbtProfileTargetName.ts
packages/cli/src/handlers/dbt/getDbtVersion.mocks.ts
packages/cli/src/handlers/dbt/getDbtVersion.test.ts
packages/cli/src/handlers/dbt/getDbtVersion.ts
packages/cli/src/handlers/dbt/getWarehouseClient.ts
packages/cli/src/handlers/dbt/run.ts
packages/cli/src/handlers/deploy.ts
packages/cli/src/handlers/generate.ts
packages/common/src/index.ts

Closes: [#9025](https://github.com/lightdash/lightdash/issues/9025)
Adding experimental support for dbt cloud CLI in the Lightdash CLI.
**Known limitation:**
1. dbt cloud doesn't expose credentials to the warehouse so for some commands we rely on the warehouse credentials from the active project. That means the credentials from the project should have access to all development/staging schemas.
Affected commands: `lightdash generate`, `lightdash preview` and `lightdash start-preview` 
2. Warehouse credentials will be empty when creating a new project that is not a preview. Upon creation, the user needs to update the project settings.
- Move logic on how to get the warehouse client and target/profile data to separate functions which now handles the dbt cloud scenario.
- Adjust dbt commands …

feat: dbt cloud CLI

---

packages/backend/src/database/migrations/20250108140928_create-project-uuid-catalog-search-uuid-index.ts
packages/backend/src/models/CatalogModel/CatalogModel.ts

Relates to: [#2647](https://github.com/lightdash/lightdash-internal-work/issues/2647)
- Adds composite index to `project_uuid` and `catalog_search_uuid` to the `catalog_search` table to help with metric tree edges query.
- Filters by project UUID on join instead of after
```typescript
await this.database(MetricsTreeEdgesTableName)
.select<
(DbMetricsTreeEdge & {
source_metric_name: string;
source_metric_table_name: string;
target_metric_name: string;
target_metric_table_name: string;
})[]
>({
source_metric_catalog_search_uuid: `${MetricsTreeEdgesTableName}.source_metric_catalog_search_uuid`,
target_metric_catalog_search_uuid: `${MetricsTreeEdgesTableName}.target_metric_catalog_search_uuid`,
created_at: `${MetricsTreeEdgesTableName}.created_at`,
created_by_user_uuid: …
```

chore: add composite index for project_uuid and catalog_search_uuid

---

packages/frontend/src/Routes.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar.tsx
packages/frontend/src/features/metricsCatalog/store/metricsCatalogSlice.ts
packages/frontend/src/pages/MetricsCatalog.tsx

Closes: #13049 
- Keeps full state of catalog query in URL
- Adds `/tree` to route to the tree view

feat: allow tree urls to be shared

---

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx

Closes: #12993 
Sets the min height of the tree container to the same value as the table

fix: make tree container min height same as the table

---

packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreFilter.tsx
packages/frontend/src/features/metricsCatalog/styles/useFilterStyles.ts

Closes: [#13177](https://github.com/lightdash/lightdash/issues/13177)
Operator is on the same row as the dimension to filter by
type values / tag input component is on its own row and grows vertically
demo

style: let tag input grow vertically in metric filter

---

packages/frontend/src/features/metricsCatalog/components/MetricExploreModal.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreComparison.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreFilter.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreSegmentationPicker.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/TimeDimensionPicker.tsx

Closes: #13149
just adding "group" does it

feat: group fields by table label in metric catalog

---

packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreLegend.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreTooltip.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/MetricsVisualization.tsx
packages/frontend/src/features/metricsCatalog/components/visualization/types.ts

Closes: #13227
Reviewed by @PriPatel 
(btw, there's definitely room for improvement and consistency throughout, but will do that in a separate PR)
alm

style: get accurate styles for comparison types of metrics exploration

---

packages/frontend/src/components/DataViz/store/cartesianChartBaseSlice.ts

Closes: #13260
To replicate
- Create sql runner chart
- Select 2 y axis fields
- Go "Series" and set 2nd y axis as "right"  axis position
- go to "Display" and **only** update the right y axis - the left y axis should remain _untouched_
- hit save and see validation error
This is because the yAxis[0] is set to `null` - default to empty object so that the default are applied nicely
with this change the above error doesn't happen.

fix: set left yaxis display if not set when theres 2

---

packages/frontend/src/features/metricsCatalog/components/MetricTree/index.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar/index.tsx

Relates to: #12912 
- Resets initial layout when reloading tree page

fix: reset layout when initial edges or nodes change

---

packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts

Closes: #13237 
- Sets the explore of the compare metric query to the same as the base query so it finds the filter field
- Select a metric
- Filter on a field from that explore
- Compare to a metric on a separate explore

fix: use base query explore name when running comparison

---

packages/frontend/src/components/common/Page/Page.tsx

Closes: #13141 
Check https://github.com/lightdash/lightdash/issues/2395 for titles
**Before**
**After**
React docs: https://react.dev/reference/react-dom/components/title#use-variables-in-the-title

fix: interpolate string for page title

---

packages/common/src/utils/metricsExplorer.ts
packages/frontend/src/features/metricsCatalog/utils/metricExploreDate.tsx

Closes: #13193
reverts: https://github.com/lightdash/lightdash/pull/12944/files
demo

chore: revert back to original metric explore date ranges

---

packages/frontend/src/features/metricsCatalog/components/visualization/MetricExploreDatePicker.tsx

Closes: N/A
After selecting a custom date range the segmented control shouldn't be disabled. 
This fixes that
before
https://github.com/user-attachments/assets/6f59ff92-7e30-4a33-abfd-cb84cc71eb94
after
https://github.com/user-attachments/assets/a232eb45-4ee8-4484-875c-e53c6151c20b

fix: only disable date range selection when fetching

---

packages/frontend/src/components/common/BackgroundSvg.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsVisualizationEmptyState.tsx

Closes: #13156
Creates common component `BackgroundSvg` - mantine's one (BackgroundImage) doesn't work with svgs
demo:

style: correctly load svg background image

---

packages/backend/src/database/migrations/20250115094940_fix_missing_slugs.ts

Closes:  https://github.com/lightdash/lightdash-internal-work/issues/2704
This migration fixes missing slugs caused by weird invalid characters (eg: japanese chars) during hte initial migration when we introduce slugs. 
There is an edge case that is not covered here, if the same chart was duplicated on a preview, and the slug is missing, this change will assign different slugs, making promotion break. But that promotion was likely broken anyway given the slugs were missing. 
Before
After

fix: missing slugs

---

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx

Closes: https://github.com/lightdash/lightdash/issues/13223
Change:
- clear the entire dashboard storage when a chart is moved to space.
Before:
https://github.com/user-attachments/assets/5a1f1980-d2c5-488a-80fe-241d0ee7c1c9
After:
https://github.com/user-attachments/assets/1147a764-9852-42e4-9418-d39d0895e224

fix: clear dashboard storage after moving chart to space

---

packages/frontend/src/components/NavBar/BrowseMenu.tsx

Closes: 
space list had weird bounds on its right and bottom designated for scrollbars, even though the scrollbars were not always visible.
before:
after:
https://github.com/user-attachments/assets/c8e1dd31-45e7-4089-b46a-3dffaaa9b568

fix: browse menu spaces list scroll

---

packages/frontend/src/components/LimitButton/LimitForm.tsx
packages/frontend/src/features/semanticViewer/components/ContentResults.tsx
packages/frontend/src/features/sqlRunner/components/Download/ResultsDownloadFromUrl.tsx

Closes: 
Makes the row limit forms more consistent. Explore, SQL Runner, and the sql runner results downloads forms now have more consistent styling:
- Label is now "Row limit"
- Inputs are the same size
- 'required' asterisk is there
**SQL Runner**
**Explorer**
**Results download**
Note the that SQL runner table doesn't respect the limit correctly, there is a ticket: #13310

fix: make row-limit forms consistent

---

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx
packages/frontend/src/features/metricsCatalog/store/metricsCatalogSlice.ts

Closes: N/A
After this merge: #13275, the slice was storing unserializable data in redux
This only stores `userUuid` - if we need more info, we can get it from the endpoint response later.
events sent properly still:

chore: store just the userUuid in catalog slice

---

packages/backend/src/clients/Aws/s3.ts
packages/backend/src/services/UnfurlService/UnfurlService.ts

Closes: [#2723](https://github.com/lightdash/lightdash-internal-work/issues/2723)
Problem: There was a change where generated pdf files were not available in the machine that was sending the email.
Solution: Save generated pdfs in S3 and use S3 URL for the email attachment. 
Before: 
Email with pdf attachment could fail because pdf could not be found.
```
Failed task 927252 (sendEmailNotification) with error Failed to send email. Error: ENOENT: no such file or directory, open '/tmp/slack-image-notification-1234_abcd.pdf' (281.63ms):
SmptError: Failed to send email. Error: ENOENT: no such file or directory, open '/tmp/slack-image-notification-1234_abcd.pdf'
at EmailClient.sendEmail (/usr/app/packages/backend/dist/clients/EmailClient/EmailClient.js:66:23)
at …
```

fix: email with pdf attachments

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx

Fixes a couple issues with SQL runner table styles.
1. Cleans up result table and drag handle borders. The drag handle had no left border and the table had double borders. To repro: run a query and look at the results table and drag handle at the bottom of the page.
**Before**
**Now**
2. Remove the resize handle when only the table is showing. To repro: run a query, switch to the chart tab, select table viz. Before, there was a resize handle that didn't do anything, now it is hidden. 
**Before**

fix: sql runner table borders

---

packages/frontend/src/features/metricsCatalog/components/Canvas/index.tsx

fix: prevent canvas infinite loop when calling setLayout on useEffect

---

packages/backend/src/controllers/projectController.ts
packages/backend/src/controllers/spotlightController.ts

GET for tags and config are unauthorized in demo

fix: get spotlight config and tags authorized in demo

---

packages/frontend/src/features/metricsCatalog/components/CatalogCategory.tsx
packages/frontend/src/features/metricsCatalog/components/MetricCatalogCategoryFormItem.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogCategoryForm.tsx

Closes: #13394
See AC. Visually approved by @PriPatel 
only show code icon on TagInput, dont show on dropdown
can't use yml-categories to categorise other metrics - this makes things more complex and could be very confusing to users! They will probably only define categories on the yml or on the ui, not both. Let's see!

feat: handle yml-vs-ui catagories on spotlight

---

packages/backend/src/models/CatalogModel/CatalogModel.ts

Closes: #13407
When indexing the catalog with a large number of items, we hit PostgreSQL's parameter limit (65,535) due to bulk inserting all records at once. Each catalog record has 11 columns, so inserting more than ~5,957 records at once would exceed this limit.
Use Knex's batchInsert utility to automatically split the inserts into smaller batches. We've set the batch size to 3,000 records, which means each batch will use at most 33,000 parameters (3,000 records × 11 columns), staying under PostgreSQL's limit while maintaining good performance.

fix: batch insert catalog search entries

---

.github/workflows/gcp-build-and-push.yml
.github/workflows/release-on-merge.yml

Closes: 
Change how we trigger the GCP workflow so we can see its state in the commit status.
At the moment, even if you open to see all the checks, GCP workflow is not part of it.

chore: trigger GCP workflow on chore(release) commit

---

packages/frontend/src/components/DataViz/config/CartesianChartSeries.tsx
packages/frontend/src/components/DataViz/config/CartesianChartTypeConfig.tsx
packages/frontend/src/components/DataViz/config/CartesianChartValueLabelConfig.tsx
packages/frontend/src/components/DataViz/config/SingleSeriesConfiguration.tsx
packages/frontend/src/components/VisualizationConfigs/common/Config.tsx

Make the sql runner series config form have uniform inputs. 
**With this change**
**Before**

feat: sql runner consistent style for series config form

---

packages/backend/src/ee/database/migrations/20240522101742_add_embedding_vector_to_catalog.ts
packages/backend/src/ee/database/migrations/20240617193700_changes_to_project_to_slack_channel_mapping.ts
packages/e2e/cypress/e2e/api/embedManagement.cy.ts

Relates to: [#2622](https://github.com/lightdash/lightdash-internal-work/issues/2622)
Changes:
- amend 2 EE migration rollbacks
- add API tests for embed management features: manage embed token/config, create embed url.
- add license to staging env ( will make it available in all render PRS after merge )
Next PR:
- add e2e test for embed page
test-frontend
test-cli
test-backend

fix: EE migration rollbacks + add embed management API tests

---

packages/backend/src/App.ts
packages/common/src/index.ts
packages/frontend/src/components/common/ErrorState/index.tsx
packages/frontend/src/hooks/toaster/ApiErrorDisplay.tsx

Closes: [#2801](https://github.com/lightdash/lightdash-internal-work/issues/2801)
Changes:
- add trace ID to error metadata
- adjust UI to show both ids and easy copy
Replicate:
- add `SENTRY_DSN` env var
- throw a 500 error in a service (example: list projects)
- see error in UI (example project home page)

fix: add trace id to api response

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/database/seeds/development/01_initial_user.ts
packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/models/CatalogModel/utils/index.ts
packages/backend/src/models/TagsModel.ts
packages/backend/src/projectAdapters/dbtAzureDevOpsProjectAdapter.ts
packages/backend/src/projectAdapters/dbtBaseProjectAdapter.test.ts
packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts
packages/backend/src/projectAdapters/dbtBitBucketProjectAdapter.ts
packages/backend/src/projectAdapters/dbtCloudIdeProjectAdapter.ts
packages/backend/src/projectAdapters/dbtGitProjectAdapter.ts
packages/backend/src/projectAdapters/dbtGithubProjectAdapter.ts
packages/backend/src/projectAdapters/dbtGitlabProjectAdapter.ts
packages/backend/src/projectAdapters/dbtLocalCredentialsProjectAdapter.ts
packages/backend/src/projectAdapters/dbtLocalProjectAdapter.ts
packages/backend/src/projectAdapters/dbtNoneCredentialsProjectAdapter.ts
packages/backend/src/projectAdapters/projectAdapter.ts
packages/backend/src/services/CatalogService/CatalogService.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/types.ts
packages/cli/src/analytics/analytics.ts
packages/cli/src/handlers/deploy.ts
packages/cli/src/lightdash-config/index.ts
packages/cli/src/lightdash-config/lightdash-config.test.ts
packages/common/src/utils/loadLightdashProjectConfig.ts

Closes: [#13309](https://github.com/lightdash/lightdash/issues/13309)
> [!IMPORTANT]
> Didn't add code to track "default_time_dimension" as there is no context of tracking when converting Explores (see translator.ts and dbt.ts)
lightdash config loaded
⚠️ if no yml file, this event won't be sent
category applied (yml)
category applied (ui) - always 1 (for now, bc there is no way to do a batch assign on the ui)

chore: track spotlight curation analytics events

---

packages/backend/src/ee/models/CommercialCatalogModel.ts
packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/scheduler/SchedulerTask.ts
packages/backend/src/services/CatalogService/CatalogService.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/catalog.ts

Related to: https://github.com/lightdash/lightdash-internal-work/issues/2777
- Uses batch insert when inserting new cached explores instead single insert
- Logs amount of individual cached explores inserted
- Don't pass explores as an argument to `indexCatalog` since it is logged

fix: use batch insert and don't pass full explores as index catalog job payload

---

packages/frontend/src/components/SimpleChart/index.tsx

Closes: N/A
We have 2 tooltip trigger behaviours: on region of series and on a isolated series. 
When moving away from a chart too quickly, this can leave an undesired state: the series is emphasised and the rest isn't.
This PR toggles the emphasis state on mouse in and out (same way as with the tooltip). 
NOTE: I tried `dispatchAction` but nothing worked. Setting the spec like this did. 
before
https://github.com/user-attachments/assets/0d0fe079-060f-4511-8332-752d0b2b5df7
after
https://github.com/user-attachments/assets/9fed7574-f55a-458d-8b85-d454c95cf0be

fix: disable emphasis on echarts mouseout

---

packages/backend/src/ee/index.ts
packages/backend/src/ee/services/ScimService/ScimService.mock.ts
packages/backend/src/ee/services/ScimService/ScimService.ts

Closes: N/A
If posthog is not enabled, then also check if the SCIM feature flag is turned on via env var. This reuses the commercial feature flag model. 
To reproduce on `main`:
```
remove post hog api key env var, or taint it
turn on SCIM_ENABLED=true
```
To test on this branch:
```
remove post hog api key env var, or taint it
turn on SCIM_ENABLED=true
```
Go to the scim access tokens and see the list and you're able to generate

fix: check if scim flag is on via posthog or env

---

packages/cli/src/handlers/dbt/run.ts
packages/cli/src/index.ts

Closes:  #13542
- Adds `--assume-no` option to `dbt run` to skip all prompts to update yaml files
AC:
- `--assume-yes` should still work as is (write all files without prompting)
- default should still ask for files
- `--assume-no` should not prompt and not write files
Related docs PR: https://github.com/lightdash/lightdash-docs/pull/40

feat: add --assume-no option

---

packages/frontend/src/components/UserSettings/UserAttributesPanel/UserAttributeModal.tsx

Closes: N/A
Adds a tooltip explaining what it means when setting a default value

chore: improve messaging on user attribute default value

---

packages/frontend/src/components/ProjectAccess/ProjectAccess.tsx

Closes: 
This issue is likely to be a race condition, 
I was able to replicat ethis by running e2e permission tests while refreshing this page. 
Perhaps the reques tto get the user orgs is out of sync when we access this page. Refreshing the page fixes the issue

fix: undefined role project settings

---

packages/frontend/src/components/ProjectAccess/ProjectAccess.tsx
packages/frontend/src/components/ProjectAccess/ProjectAccessRow.tsx
packages/frontend/src/hooks/useProjectAccess.tsx

Closes: https://github.com/lightdash/lightdash/issues/13551
- Go to /projectAccess
- The util convertOrganizationRoleToProjectRole was expecting the role from orgRoles to always be defined. this is now addressed
(made small style improvements)

fix: get inherited roles if org roles exist

---

packages/common/src/utils/conditionalFormatting.ts

Closes: 
Checks if column is visible/added when checking conditional formatting configurations
**before**
https://github.com/user-attachments/assets/238c70df-33d3-4eff-8e8d-3e5af141e503
**after**
https://github.com/user-attachments/assets/8a518817-40d0-4344-aea6-fa7c0feaa519

fix: handle hidden column if conditional format

---

packages/common/src/visualizations/CartesianChartDataModel.ts
packages/frontend/src/components/DataViz/config/CartesianChartSeries.tsx

Closes: #12861
Checks if groupedSeries' values (by reference) have more than one series so that we enable stacking.
https://github.com/user-attachments/assets/8e5e8f53-dbb5-4ec0-89ac-c38038a2eda5

fix: can stack if grouped series ref has more than one

---

packages/common/src/utils/fields.mock.ts
packages/common/src/utils/fields.test.ts
packages/common/src/utils/fields.ts

Closes: [#13560](https://github.com/lightdash/lightdash/issues/13560)
Compare filter unit of time when matching custom metrics with metrics.

fix: compare filter unit of time

---

packages/frontend/src/components/DashboardTabs/EditTabModal.tsx

Closes: #13250 
This PR adjusts the width of the 'Edit Your Tab' modal to match the width of the 'Add New Tab' modal.

fix: resize edit tab to match Add New tab width

---

packages/e2e/cypress/e2e/app/createProjects.cy.ts

Closes: N/A
error:
```
1) Create projects
Should create a Snowflake project:
AssertionError: expected '2,000' to equal '1,999'
+ expected - actual
-'2,000'
+'1,999'
at testPercentile/ (webpack://e2e/./cypress/e2e/app/createProjects.cy.ts:233:0)
at testPercentile (webpack://e2e/./cypress/e2e/app/createProjects.cy.ts:231:0)
```
test-frontend
test-backend

test: update expected snowflake e2e value

---

packages/frontend/src/components/SimpleChart/index.tsx
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: #13613
before  (see ticket)
after:

fix: get formatted value when tooltip in isolation

---

packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Closes: #13615 
- When `database`, `schema` and `table` exist, we can use `getCatalog` to get the table fields using a fully qualified name that will not fail because of casing - query with where clauses fails because of that.

fix: use getCatalog to get columns information when all arguments of get fields are available

---

packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/components/common/ResourceInfoPopup/ResourceInfoPopup.tsx

Closes:   https://github.com/lightdash/lightdash/issues/13436
I found this solution was the most consistent with our style style={{ whiteSpace: 'pre-line' }}
using "box" broke the font , and using component="pre" added some unexpected margins. 
Related: https://github.com/orgs/mantinedev/discussions/7127
Before
After

fix: multiline descriptions

---

packages/sdk/src/Lightdash.tsx

Closes: 
Adds a slash to lightdash url when not present. Both of our initial uses had this problem.

fix: add slash to lightdash URL when not present

---

packages/frontend/src/hooks/toaster/ApiErrorDisplay.tsx

Closes: 
This error toast was a little bit broken. 
**Before**
**After**

fix: error toast layout

---

packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts
packages/frontend/src/hooks/echarts/useEchartsFunnelConfig.ts
packages/frontend/src/hooks/echarts/useEchartsPieConfig.ts
packages/sdk/src/Lightdash.tsx

Closes: 
Don't use theme-based fonts in internal Lightdash charts. Charts will pick up the styles only when passed to the SDK.

fix: don't use theme fonts in lightdash charts

---

packages/common/src/utils/timeFrames.ts

Closes: #13441 
NOTE: start of week is set to `tuesday`
Tested with:
- Trino
- Bigquery
- Databricks
- Postgres
- Snowflake (was already working because it uses the WEEK_START session var)
Before:
After:
test-backend
test-cli

fix: week num values

---

packages/frontend/src/pages/MinimalDashboard.tsx

Closes: #13650
To test on main
- create dashboard with 2 tabs
- select "send now" or scheduled delivery for tab 2 (just has to be other than the first)
- see error
This fixes: 
- when `schedulerTabs` is set in the search params, then aggregate all tabs in one view.
- if viewing in mobile mode, allow navigation between tabs.

fix: aggregate tabs into one view when sending now/scheduling

---

packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx

Closes: 
Until we add this modal for not github projects, keep it consistent, disable the mulitple modal , like we do already for single custom metrics

fix: disable custom metric write back if not github

---

packages/frontend/src/components/common/Filters/FilterInputs/utils.ts

Closes: https://github.com/lightdash/lightdash/issues/13697
before (see how timezone-based **but** date fields had the hh:mm when doing "in between") 
after (fixed for in between operator, the other operators had already the correct formatting)

chore: format date when in_between and type date

---

packages/frontend/src/components/common/TagInput/TagInput.tsx
packages/frontend/src/features/metricsCatalog/components/CatalogCategory.tsx
packages/frontend/src/features/metricsCatalog/components/MetricCatalogCategoryFormItem.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogCategoryForm.tsx
packages/frontend/src/features/metricsCatalog/styles/useCategoryStyles.ts

Closes: #13350 
This pull request introduces several enhancements across multiple components in the `metricsCatalog` feature. The changes focus on improving keyboard accessibility, error handling, and user experience with the metrics catalog form.
* [`packages/frontend/src/components/common/TagInput/TagInput.tsx`](diffhunk://#diff-7c7e43cee6b2ff2e9542c03f7cce078a542599fa8cde01af373dfc044e7c01d6R464): Added `data-autofocus` attribute to ensure the input is still focused when the Popover's dropdown is initially rendered. This complements the removal of `useFocusTrap` and `inputFocusTrapRef` from `packages/frontend/src/features/metricsCatalog/components/MetricCatalogCategoryForm.tsx`.
* [`packages/frontend/src/features/metricsCatalog/components/CatalogCategory.tsx`](diffhunk://#diff-5fb364cbd …

feat: allow tab and enter to navigate/apply categories

---

packages/backend/src/ee/services/EmbedService/EmbedService.ts
packages/backend/src/services/ProjectService/ProjectService.ts

Closes: [#2720](https://github.com/lightdash/lightdash-internal-work/issues/2720)
Reuse autocomplete metric query in OSS/EE endpoints.
OSS
EE

chore: reuse autocomplete metric query

---

packages/backend/src/services/PromoteService/PromoteService.ts

Closes: #13705 
- Always force slugs when creating charts and dashboard while promoting like we do for space upsert.
To test:
1. Create project (not preview)
2. Set new project as upstream of existing project
3. Promote dashboard/chart
4. Make changes to dashboard/chart
5. Promote again
6. Make sure dashboard/chart is updated and a new one is not created

fix: always force slug when creating chart or dashboard

---

packages/frontend/src/api.ts
packages/sdk/src/Lightdash.tsx

Closes: 
Use sessionStorage for SDK instead of localStorage. Session storage will get set every time the SDK mounts, so it will work. But it won't be persisted in the domain when new tabs are opened.

fix: use sessionStorage instead of localStorage for SDK routes

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/job.ts
packages/frontend/src/components/ProjectConnection/index.tsx
packages/frontend/src/features/catalog/hooks/useIndexCatalogJob.ts
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx
packages/frontend/src/hooks/useRefreshServer.ts

Closes: [#13403](https://github.com/lightdash/lightdash/issues/13403)
Changes:
- update compile project job to store index catalog job id
- FE checks index catalog job each 2 seconds
- show new loading button instead of refresh dbt button
- reload table once it is complete
Demo:
https://github.com/user-attachments/assets/ffdad5a3-af0b-48a8-8ba1-8a04541eedbd

fix: reload metrics catalog on index catalog complete

---

packages/common/src/authorization/organizationMemberAbility.ts
packages/common/src/authorization/projectMemberAbility.ts

Closes: 
Editors should not be able to update project settings. There was a misinterpretation of the docs on "updating a project" and "updating content in a project" that originated this bug.
We have updated the [roles documentation](https://docs.lightdash.com/references/roles#organization-roles) to distinguish between those two
Demo editor user:

fix: editor project access

---

packages/cli/src/dbt/schema.ts
packages/common/src/schemas/json/lightdash-dbt-2.0.json

Closes: #13770 
Allow YML models without `version: 2` field

fix: CLI commands fail when `version: 2` is missing in model YAML

---

packages/frontend/src/ee/features/embed/EmbedDashboard/components/EmbedDashboard.tsx
packages/frontend/src/ee/pages/EmbedDashboard.tsx
packages/sdk-test-app/src/App.tsx
packages/sdk/src/Lightdash.tsx

Closes: #13666 
Fix a double scroll in embedding. We had two nested containers handling sizing differently. Now we have one container with different styles.

fix: bad double scroll in sdk dashboards

---

packages/frontend/src/providers/MantineProvider.tsx
packages/sdk/src/Lightdash.tsx

Closes: 
The SDK was showing toasts overlaying the containing app like this:
This PR hides all toasts from the SDK. I don't imagine anyone will want these as toasts in their app, but we could make it an option in the future. Or find another place to put the information that's within the container.

fix: hide toasts in SDK

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/ProjectModel/ProjectModel.mock.ts
packages/backend/src/models/ProjectModel/ProjectModel.test.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/common/src/types/projects.ts
packages/frontend/src/components/ProjectConnection/WarehouseForms/PostgresForm.tsx
packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts

Closes: [#1816](https://github.com/lightdash/lightdash/issues/1816)
Allow to upload client certificate, private key, root certificate for Postgres connections in the UI.
CLI support will be done under: https://github.com/lightdash/lightdash/issues/7939 
https://www.notion.so/lightdash/How-to-develop-debug-Postgres-with-certificates-1a1a63207a7a8052b644e589a13c6e58
https://github.com/user-attachments/assets/c4e8ff21-0957-4143-b95e-a13e3980ebe0
https://github.com/user-attachments/assets/025594aa-dce9-45e4-80ce-eb5a5b09e47e

feat: support Postgres client and root certificates

---

packages/frontend/src/Routes.tsx
packages/frontend/src/pages/LegacySqlRunner.tsx

Closes: [#2918](https://github.com/lightdash/lightdash-internal-work/issues/2918) 
Redirect legacy SQL Runner URLs to new page.
Copies over the SQL but no chart config.
Reproduce locally by inserting the following data in `postgres.public.share` and disable `React.StrictMode` in `packages/frontend/src/index.tsx`
```
{
"share_id": 1,
"nanoid": "GZ-OqNIzkTWFlHkHzJqoh",
"path": "/projects/3675b69e-8324-4110-bdca-059031aa8da3/sqlRunner",
"params": "?create_saved_chart_version=%7B%22tableName%22%3A%22sql_runner%22%2C%22metricQuery%22%3A%7B%22exploreName%22%3A%22sql_runner%22%2C%22dimensions%22%3A%5B%22sql_runner_order_date%22%2C%22sql_runner_status%22%2C%22sql_runner_is_completed%22%5D%2C%22metrics%22%3A%5B%22sql_runner_order_id%22%2C%22sql_runner_customer_id%22%2C%22sql_runner_credit_card_amou …
```

feat: redirect legacy SQL Runner URLs to new page

---

packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx

Closes: #13760 
Closes: #13291
This PR fixes an issue where attempting to interact with a filter popover (e.g., selecting text inside an input field) would unintentionally trigger the drag behavior.
- Updated the disabled condition in the `DraggableItem` component to include `!!openPopoverId`.
- Now, dragging is disabled when a filter popover is open, ensuring a smoother user experience.

fix: Selecting dashboard filter label text results in dragging the filter rather than selecting text

---

packages/backend/src/ee/services/EmbedService/EmbedService.ts
packages/backend/src/services/CsvService/CsvService.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/filter.test.ts
packages/common/src/types/filter.ts
packages/common/src/utils/filters.test.ts
packages/common/src/utils/filters.ts
packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx

Closes: https://github.com/lightdash/lightdash/issues/13576
Automatically override chart filters when dashboard filters use:
- Same dimension (e.g., dashboard filter on status overrides chart's status filter)
- Different granularity of same time dimension (e.g., dashboard order_date_year overrides chart's order_date_month)
- Add tracking of overridden filters using new fieldsToChange property
- Maintain existing AND/OR logic for unrelated filters
New filter resolution logic in filters.ts:
- trackWhichTimeBasedMetricFiltersToOverride identifies override candidates
- Enhanced findAndOverrideChartFilter handles granularity overrides
Time based dimension:
- Create dashboard 
- Create chart (with filter `order_date_month` = march 2018)
- Add dashboard filter `order_date_day` = 2018-03-24
- …

feat: override tiles' filters if dashboard ones target similar

---

packages/frontend/src/components/common/Table/TableProvider.tsx

Closes: #13828
Relates to: https://github.com/lightdash/lightdash/pull/13703
- Fixes row numbers not showing, introduced by [new lines in results PR](https://github.com/lightdash/lightdash/pull/13703)
To test:
- Follow steps in related PR to make sure new lines are still being processed
- Check row numbers in both pivot table and results table

fix: row numbers not appearing

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/types/savedCharts.ts
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Axes/index.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Layout/index.tsx
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: [#5564](https://github.com/lightdash/lightdash/issues/5564)
- Added ability to sort bar charts by total bar values
- Implemented two new sorting options: Bars Ascending, Bars Descending
- Added UI controls in chart configuration panel
1. Create a bar chart (with or without grouping)
2. Open chart configuration and check Sort dropdown in Axes section
3. Test each sorting option:
- Default: Maintains original results order
- Inverted: Reverses original results order
- Bars Ascending: Sorts by total bar values (smallest to largest)
- Bars Descending: Sorts by total bar values (largest to smallest)
- Bar total sorting only works with categorical x-axis
**AC:**
- Works for horizontal/vertical bar charts, for other cartesian chart types it shows as disabled
- Backwards compatible with …

feat: sort stacked bar charts

---

packages/backend/src/App.ts
packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/config/parseConfig.test.ts
packages/backend/src/config/parseConfig.ts

Closes: #13821 
This PR adds support for securely embedding the Lightdash application within iframes on third-party websites
Required env vars:
```
LIGHTDASH_IFRAME_EMBEDDING_DOMAINS=https://example.com,https://www.example.com
SECURE_COOKIES=true
```
Optional relevant env vars:
```
TRUST_PROXY=true #in cases where server might be behind a proxy (e.g. locally)
```
How to run locally:
- Tunnel locally running app so that it's accessible with https
- e.g. `claudflared --tunnel  http://localhost:3000`
- Setup all of the above env variables
- Embed into iframe:
```tsx
<iframe
width="1280px"
height="720px"
src="<YOUR_TUNNELED_URL>"
allow="fullscreen"
title="Lightdash Dashboard"
/>
```

feat: allow accessing Lightdash from an iframe

---

packages/frontend/src/hooks/useColumns.tsx

Closes: https://github.com/lightdash/lightdash/issues/13491
This PR fixes an issue with how newlines are displayed in table visualizations when using PostgreSQL as the database backend.
Different warehouses handle string escaping differently, e.g.
- **Snowflake** interprets `\n` directly as a newline character
- **PostgreSQL** treats `\n` as literal characters (backslash + n) unless using the `E` prefix for C-style escapes - https://www.postgresql.org/docs/16/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS-ESCAPE
When data containing newlines is returned from PostgreSQL to the frontend, the newlines appear as literal `\n` strings rather than actual newline characters. Our previous fix in PR #13703 incorrectly attempted to split on `\\n` instead of the correct `\n` pattern.
- Updated the string …

fix: new line processing in results

---

packages/backend/src/SchedulerApp.ts
packages/backend/src/sentry.ts

Closes: N/A
Ignore more errors on Scheduler/Worker section. 
Now the errors-to-be-ignored are shared between backend apps.

chore: share errors to ignore in sentry on BE and worker

---

packages/backend/src/models/ProjectModel/ProjectModel.test.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts

A customer reported losing virtual views after a recompile of the project. It seems very likely that this happened in the `saveExploresToCache` function where we were keeping the virtual views in memory, then deleting them and adding them back. Between loading them in memory and saving them back to the database, we were doing this expensive spread operation.
```
const uniqueExplores = uniqWith(
[...explores, ...virtualViews.map((e) => e.explore)],
(a, b) => a.name === b.name,
);
```
Which could blow up memory. I couldn't find an OOM in the logs, but this seems like it will improve things by at least rolling back if something fails. 
This does two things:
1. Puts the logic in this function into a transaction so that if it fails, the database will rollback and not lose the original state. …

fix: save explores to cache in a transaction

---

packages/backend/src/services/ValidationService/ValidationService.ts

Closes: #13872
custom metric filter could be `null`.

fix: check if custom metric filter exists before validating

---

packages/backend/src/config/parseConfig.ts
packages/common/src/index.ts

Closes:  https://github.com/lightdash/lightdash/issues/13845
We don't have an official way to disable rudderstack. When customers ask we have told them to use a space `' '`. This adds a flag to disable rudderstack. 
If this looks good I can add it to the docs.

feat: add a flag to disable telemetry

---

packages/frontend/src/components/common/Filters/FilterInputs/FilterMultiStringInput.tsx
packages/frontend/src/components/common/Filters/FilterInputs/FilterStringAutoComplete.tsx
packages/frontend/src/components/common/Filters/FilterInputs/utils.ts

Closes: #8341 
Replaces whitespace with '·' and new line '↵'
A few more solutions are proposed in the comments for issue: #8341 
Final solution with a few edge cases:

fix: whitespace handling

---

packages/common/src/authorization/projectMemberAbility.ts
packages/frontend/src/components/DashboardTiles/DashboardSemanticViewerChartTile.tsx
packages/frontend/src/components/NavBar/ExploreMenu.tsx
packages/frontend/src/features/semanticViewer/components/Header/HeaderView.tsx
packages/frontend/src/pages/SemanticViewerEdit.tsx

`'manage', 'SemanticViewer'` permissions were not used for enforcing any permission checks

chore: unused semantic viewer permission checks

---

packages/backend/.eslintrc.js
packages/common/src/authorization/projectMemberAbility.ts

Promote permissions are already enforced because editors have the ability to `'manage', '...'` and manage allows all actions (including promote). 
This removes the permissions, which doesn't change app behaviour. However we could rewrite the permissions for editors so it doesn't include promoting (not use 'manage')

chore: remove unused promote permissions

---

packages/backend/src/services/GitIntegrationService/GitIntegrationService.mock.ts
packages/backend/src/services/GitIntegrationService/GitIntegrationService.test.ts
packages/backend/src/services/GitIntegrationService/GitIntegrationService.ts
packages/cli/src/dbt/models.ts
packages/cli/src/dbt/schema.ts
packages/cli/src/handlers/generate.ts
packages/common/src/dbt/DbtSchemaEditor/DbtSchemaEditor.mock.ts
packages/common/src/dbt/DbtSchemaEditor/DbtSchemaEditor.test.ts
packages/common/src/dbt/DbtSchemaEditor/DbtSchemaEditor.ts
packages/common/src/types/deepPartial.ts

Closes: #5422 
Closes: [#13896](https://github.com/lightdash/lightdash/issues/13896)
Changes:
- move schema validation to class constructor (+ test)
- refactor `lightdash generate` command to use the new class. Preserves YAML formatting and comments.
Update meta:
https://github.com/user-attachments/assets/fb53d90d-092d-4b25-ae87-0b296df6b4d5
Generate columns:
https://github.com/user-attachments/assets/635209e9-5e7d-430b-a490-3550dd8d26ac

feat: preserve YAML formatting and comments when running `lightdash generate` command

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/controllers/projectController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/index.ts
packages/common/src/pivotTable/pivotQueryResults.test.ts
packages/common/src/pivotTable/pivotQueryResults.ts
packages/common/src/types/analytics.ts
packages/common/src/types/pivot.ts
packages/common/src/types/savedCharts.ts
packages/common/src/utils/subtotals.ts
packages/frontend/src/components/common/PivotTable/index.tsx
packages/frontend/src/components/common/Table/ScrollableTable/TableHeader.tsx
packages/frontend/src/hooks/tableVisualization/getDataAndColumns.tsx
packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
packages/frontend/src/hooks/useCalculateSubtotals.ts
packages/frontend/src/providers/Explorer/ExplorerProvider.tsx

Closes: [#11348](https://github.com/lightdash/lightdash/issues/11348)
This PR moves the subtotal calculation logic from the frontend to the backend so that they are calculated by a warehouse query and thus supporting all metric types
- Added new `/calculate-subtotals` endpoint in the backend to handle subtotal computations
- This endpoint returns the calculations for all subtotal groupings
- Updated frontend table visualization to use the new backend endpoint
- Can now calculate subtotals when having custom dimensions (bin/sql) in the subtotal dimension groups
- Disabled for embedding scenarios like `/calculate-totals` hook
- The way the subtotals are being calculated is by running a metric query with a subgroup of dimensions, e.g.
- my query has `status`, `date_month`, `date_week`, we …

feat: calculate subtotals in the backend

---

packages/common/src/types/featureFlags.ts
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx

Closes:  https://github.com/lightdash/lightdash/issues/13831
Closes: https://github.com/lightdash/lightdash/issues/13464
I was able to replicate by removing the color on the groups (after looking at the chartconfig form the customer) . I even copied their org palette
THe colors were a bit random, when `calculateSeriesColorAssignment` was enabled. 
The good colors: 
Random colors: 
Sometimes even the color in series were reversed:

fix:  disable calculate series color

---

packages/common/src/types/featureFlags.ts
packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNodeActions.tsx

Closes: 
Hiding option to write back bin dimensions until known limitations are addressed or mitigated.
This bin type cannot be moved to dbt as it requires a CTE to pre-calculate the values.
We recommend users moving the bin logic to dbt and creating a new dimension in dbt.
When writing back a bin dimension, the SQL shown in the preview may not have the correct column references and syntax.
Please ensure the SQL is correct before merging the pull request.
Example preview:
```
order_id_test_bin:
label: Test bin
type: string
sql: >-
/* This is a preview! Replace column references and confirm SQL before using in production. */
CONCAT(FLOOR(${reference_column} / 10) * 10, ' - ',
(FLOOR(${reference_column} / 10) + 1) * 10 - 1)
```
This is not possible at the moment. If you have a custom …

feat: feature flag write back for bin dimensions

---

packages/backend/src/scheduler/SchedulerTask.ts
packages/backend/src/sentry.ts
packages/common/src/types/errors.ts

Closes: N/A
Ignore ReadFileError's in Sentry when a pdf is being added as an attachment to a scheduled delivery. 
Example: 
https://lightdash.sentry.io/issues/6363169049/events/e7584f5750f74c92a49a82e3ff0e88de?environment=cloud_beta&project=5959292&referrer=alert-rule-issue-list

chore: throw ReadFileError on pdf image buffer read

---

packages/backend/src/models/SlackAuthenticationModel.ts

Closes: #13957
`getAuthenticationToken` function was receiving `null` as an argument and failing
https://github.com/lightdash/lightdash/blob/85bc1adad69b46070f8dd7976cf6ffde7b1780dc/packages/backend/src/routers/headlessBrowser.ts#L15
The only way for this to happen is for `getUserUuid` function to return null https://github.com/lightdash/lightdash/blob/3d04a286ff909d5a27fa734bf8775354bb33fc6d/packages/backend/src/clients/Slack/Slackbot.ts#L193
This could happen in cases when user which installed the slack integration got deleted, row got cascaded and `user_uuid` points to `NULL`

fix: Address `getAuthenticationToken` error when unfurling urls in Slackbot

---

packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx

Closes: 
Reverts a change to ungrouped color picking

fix: revert check for groups in series coloring

---

packages/backend/src/clients/Google/GoogleDriveClient.ts

Closes: #13884
The problem was that:
1.  [`GoogleDriveClient#getCredentials` method](https://github.com/lightdash/lightdash/blob/eeb6b20382a475c8ee27d2e949640353d46c5a5f/packages/backend/src/clients/Google/GoogleDriveClient.ts#L39-L55) is not actually checking wether existing credentials are valid, only checks if they exist
2. Each different request to google could throw an 401/400 error
3. The errors thrown were not `ForbiddenError`s  thus they weren't caught by [`shouldDisableSync`](https://github.com/lightdash/lightdash/blob/ab042358d45223ef15492715417ab47d6c19cb4c/packages/backend/src/scheduler/SchedulerTask.ts#L1992-L1995) and sync was not disabled
As a solution I wrapped each google api call in a try/catch that properly handles the errors
Before:
After:
To reproduce:
1. Setup …

fix: handle unauthorized and invalid_grant errors from google

---

packages/backend/src/clients/Slack/SlackClient.ts
packages/backend/src/clients/Slack/Slackbot.ts
packages/backend/src/errors.ts
packages/common/src/types/errors.ts

Relates to: https://lightdash.sentry.io/issues/6367790428/?environment=cloud_beta&query=missing_scope&referrer=issue-stream&sort=date&statsPeriod=30d&stream_index=0
Followed suggestion here: https://github.com/slackapi/node-slack-sdk/blob/039bd050cd736d666d063397067cb014adf23711/packages/web-api/README.md?plain=1#L142
I would like to group first, then figure out which SlackError's to filter out on the UI and alerting in Sentry

chore: add SlackError class

---

packages/frontend/src/components/NavBar/ExploreMenu.tsx

Closes: https://github.com/lightdash/lightdash/issues/13975

fix: new dashboard menu item is missing for developers and editors

---

packages/frontend/src/components/UserSettings/AppearanceSettingsPanel/index.tsx

The color palette form can be closed with invalid values, which remain when you re-open it. This confused me a little, so I made it clear values on close. 
Another option: we could block closing with invalid values, but then it's a little annoying to have to fix them to bail out of the dialog. 
Here's the issue *without* this change

fix: clear values on close palette

---

packages/backend/src/services/ProjectService/ProjectService.ts

- We were returning the page size sent in the request instead of the actual page size

fix: returns actual page size in response

---

packages/common/src/utils/formatting.test.ts
packages/common/src/utils/formatting.ts
packages/frontend/src/features/sqlRunner/hooks/useDownloadResults.tsx

Closes: #14018 
SQL runner was rendering all falsey values as `-`. This makes it render 0, null, false and undefined consistently with other places we download csvs.

fix: don't treat all falsey values as undefined in sql-runner

---

packages/frontend/src/pages/Dashboard.tsx

This makes it so that dashboards stay on the selected tab when entering edit more. Before, if you clicked edit, it put you on the first tab, losing context.
**Before:**
**After:**

fix: keep the selected tab on dashbaord edit

---

packages/backend/src/controllers/userController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json

Closes: NA
Please let me know if I should open an issue.
Currently, we can not call the APIs for workflow credentials as `getWarehouseCredentials`. But if the APIs are available, we can implement the seamlesslly integrate Lightdash with the warehouse service.
For instance, we can create service account key with terraform. If the `updateWarehouseCredentials` API is available, we can seamlessly register the credentials in Lightdash. We won't need manual operations any more.

feat: Enable API call to operate warehouse credentials

---

packages/backend/src/services/CoderService/CoderService.test.ts
packages/backend/src/services/CoderService/CoderService.ts
packages/common/src/types/coder.ts

Closes: https://github.com/lightdash/lightdash/issues/13830
Fixed by replacing the tile uuid with a chart slug on `download`, then matching the filter back on `upload`
If there are multiple charts with the same slug, we assign them an index based on their position in the tile list. 
Before:
After:
Dashboard UI after upload on a different project: 
dashboard filters (uploaded vs original) 
Note: There is an edge case where this will not work , since we are relying on the position of the tiles when they are saved. 
Edge case not covered (replication steps) : 
- Have a dashboard with the same `chart` duplicated in different tiles
- Add a dashboard filter
- Deselect one of the filters on one of the duplicated tiles 
- Download code 
- Update the code, and remove one of the duplicated charts …

fix: filters on dashboards as code

---

packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNode.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/types.ts
packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/utils.ts
packages/frontend/src/components/Explorer/ExploreTree/index.tsx

Closes: [#14032](https://github.com/lightdash/lightdash/issues/14032)
this PR tries to eliminate react max depth error by
- removing forEach and mutations from tree components
- changing search result Set to be array of strings instead of a set
```
React ErrorBoundary Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
at div (<anonymous>)
at div (<anonymous>)
at div (<anonymous>)
at ExploreTree (../../src/components/Explorer/ExploreTree/index.tsx:34:5)
at ItemDetailProvider (../../src/components/Explorer/ExploreTree/TableTree/ItemDetailProvider.tsx:11:65)
...
(45 additional frame(s) were not displayed)
Error: Maximum update …
```

fix: sidebar search react max depth error

---

packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/models/ModelRepository.ts
packages/backend/src/models/OrganizationModel.ts
packages/common/src/index.ts
packages/common/src/utils/colors.test.ts
packages/common/src/utils/colors.ts
packages/frontend/src/components/VisualizationConfigs/ColorSelector.tsx
packages/frontend/src/components/common/PivotTable/index.tsx
packages/frontend/src/hooks/usePieChartConfig.ts
packages/frontend/src/utils/colorUtils.ts

Closes: #14007
env vars to test locally
```
export ALLOW_MULTIPLE_ORGS=true
export DEFAULT_COLOR_PALETTE_NAME="Rainbow Spectrum"
export DEFAULT_COLOR_PALETTE_COLORS=#FF0000,#FF3300,#FF6600,#FF9900,#FFCC00,#FFFF00,#CCFF00,#99FF00,#66FF00,#33FF00,#00FF00,#00FF33,#00FF66,#00FF99,#00FFCC,#00FFFF,#0099FF,#0066FF,#0033FF,#0000FF
```
how to test
- logout
- go to /register
- set up quick postgres project
- go to Settings > Appearance
- see color palette set as default
demo

feat: allow default color palette on org creation

---

dockerfile

Closes: #14075
Now that the command to run `build-sourcemaps` is a different name form `build` we have to run `postbuild` explicitly to copy over the html assets (related to email templates)
And checked that the docker image contains the html files
(can provide a test script and env vars to test locally)

fix: run postbuild after BE sourcemaps build

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/index.ts

Relates to: [#14072](https://github.com/lightdash/lightdash/issues/14072)
- Returns applied dashboard filters to execute query response. Returning `null` shows intent that this is not dashboard chart async query

feat: add applied dashboard filters to response

---

packages/common/src/types/field.ts
packages/common/src/utils/filters.ts
packages/frontend/src/components/Explorer/ExploreTree/TableTree/ItemDetailPreview.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNode.tsx
packages/frontend/src/hooks/tableVisualization/getDataAndColumns.tsx

Closes: #13709 
Closes: #14061
This PR does a few things
Fixes on-hover of metric-model-level it not showing the metric info 
Test with field  `completion_percentage` metric in orders
On **main**, if you hover, you can't see the metric info
On this **branch**, you can.
Displays yml reference on the dropdown up top
Users can now see the sql + the compiled sql if they click on it
Moved description above the sql
You can test this with many filters. Try it out with the following yml in `schema.yml` > compled_order_count
```yml
completed_order_count:
label: Completed order count
description: Total number of completed orders
type: count_distinct
filters:
- is_completed: "true"
- order_date_day: "2018-02-10"
- order_date_week: "inThePast 14 months"
- customers.customer_id: "1"
- status: "!false" …
```

feat: improve on-hover of metric detail 

---

packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.test.ts
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Closes: [#14072](https://github.com/lightdash/lightdash/issues/14072)
- Uses on complete for Bigquery job completion
- Runs warehouse prepare statement in multi statement call for snowflake
Note: checked again snowflake for different ways of getting total rows, and the current way was the only where this was possible

fix: warehouse wait for query completion

---

packages/frontend/src/Routes.tsx
packages/frontend/src/components/DashboardTabs/index.tsx
packages/frontend/src/components/NavBar/DashboardExplorerBanner.tsx
packages/frontend/src/components/common/modal/ChartCreateModal/SaveToDashboard.tsx
packages/frontend/src/hooks/dashboard/useDashboardStorage.ts

Closes: #13990 
Primarily this makes it so that when you edit a chart on a dashboard tab and go back to the dashboard, you'll be in the tab you were editing. This part is pretty straightforward. 
This required a change to the way the dashboard gets mounted. We were unmounting and remounting the whole dashboard on tab change, when the URL changed. But this meant the context was lost every time you switched tabs, so we couldn't support proper editing across tabs. This 'worked' before because in edit mode we didn't look at the URL for tabs. But it made it impossible to deep link to the tabs during edit. 
This PR changes the router to NOT unmount and remount the dashboard on tab change. This will help perf, and also fixes a couple bugs I saw when editing across tabs, but is definitely a …

fix: saving new chart redirects to first tab

---

packages/backend/src/dbt/profiles.ts
packages/cli/src/dbt/targets/snowflake.ts
packages/common/src/types/projects.ts
packages/e2e/cypress/e2e/app/createProjects.cy.ts
packages/frontend/src/components/ProjectConnection/WarehouseForms/SnowflakeForm.tsx
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Closes: https://github.com/lightdash/lightdash/issues/6424
This change is also backwards compatible with `private_key_path` from CLI and passwords in the UI

feat: Add private key snowflake UI

---

packages/backend/src/dbt/profiles.ts

Closes: #14131
Related to:  #14084
Backwards compatibility reasons treat empty `authenticationType` field as `authenticationType: 'password'`

fix: handle missing authentication type in snowflake credentials check

---

packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx

Fixes the loading state for SQL chart tiles. Before they were showing an error during loading. Now they just show the loading state. 
Before:
After

fix: sql chart tile loading state

---

packages/frontend/src/ee/features/embed/SettingsEmbed/EmbedDashboardsForm.tsx

Closes: #14107  
A user reported not being able to interact with the allowed dashboards dropdown. One way this could happen is if they have not access to any dashboards. This PR disables the allowed dashboards dropdown when the user has not dashboards available. And shows a message that should make it clear what's wrong.

feat: indicate when there are no dashboards avialable for embedding

---

packages/frontend/src/pages/Settings.tsx

Currently users with Viewer, Interactive viewer, and Editor permissions have the project settings links hidden from them BUT they can still access the routes. Some of the pages on those routes show sensitive information like the embedding token or who has what access on the project. This disables access to those routes for users who can't see the links. 
We could add more fine-grained access to those pages if there is a need for it, but setting up access such that the available links match the available routes makes more sense than what we currently have.

fix: block access to settings routes hidden because of permissions

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/types/filter.ts
packages/common/src/utils/filters.ts
packages/e2e/cypress/e2e/app/tableCalculation.cy.ts
packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterSettings.tsx
packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
packages/frontend/src/components/common/Filters/FilterInputs/FilterStringAutoComplete.tsx
packages/frontend/src/components/common/Filters/utils/getPlaceholderByFilterTypeAndOperator.ts

Closes: [#8138](https://github.com/lightdash/lightdash/issues/8138)
Allows the user setting single-select filters when creating them in edit mode so that they're saved permanently on the dashboard (the value can still be overriden, but they won't be able to select multiple)
demo

feat: add single-select dashboard filters

---

packages/common/jest.config.dev.js
packages/common/package.json

Makes test skip compile and uses the watch plugin when running tests in dev. Much faster!

chore: make common tests fast + watchable in dev

---

packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Add `privateKeyPass` support for Snowflake authentication

fix:  Snowflake warehouse authentication using private key with a passphrase

---

packages/common/src/index.ts
packages/frontend/src/components/Explorer/CustomMetricModal/hooks/useDataForFiltersProvider.ts
packages/frontend/src/components/Explorer/ExplorerHeader/index.tsx
packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx
packages/frontend/src/components/Explorer/FiltersCard/useFieldsWithSuggestions.ts
packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx
packages/frontend/src/components/Explorer/ResultsCard/ResultsCard.tsx
packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
packages/frontend/src/components/Explorer/index.tsx
packages/frontend/src/components/MetricQueryData/UnderlyingDataResultsTable.tsx
packages/frontend/src/components/RefreshButton.tsx
packages/frontend/src/components/SimpleTable/index.tsx
packages/frontend/src/components/common/PaginateControl.tsx
packages/frontend/src/components/common/Table/TableProvider.tsx
packages/frontend/src/components/common/Table/types.ts
packages/frontend/src/features/sqlRunner/hooks/useSqlRunnerShareUrl.ts
packages/frontend/src/hooks/useColumns.tsx
packages/frontend/src/hooks/useQueryResults.ts
packages/frontend/src/pages/MinimalSavedExplorer.tsx
packages/frontend/src/providers/Explorer/ExplorerProvider.tsx
packages/frontend/src/providers/Explorer/types.ts

Related to: [#13916](https://github.com/lightdash/lightdash/issues/13916)
What components display results:
- viz (charts/table/etc)
- results table
- underlying data table
What pages/endpoints use those components but don't support pagination yet:
- embed dashboard
- underlying data ( waiting for [#14041](https://github.com/lightdash/lightdash/issues/14041))
What warehouses ignore `pageSize` endpoint param and return a single page with all the rows:
- trino
- postgres
- databricks
Challenges/Goals:
- keep UI pagination pagination decoupled from API+warehouse pagination
- How to incrementally add lazy load support since the explorer provider, dashboard, viz and table components are all expecting all the rows.
For this PR I'm focusing on the results table in the explorer page:
- refactor …

feat: lazy load rows for results table

---

packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Closes:  https://github.com/lightdash/lightdash/issues/14205
What the issue was: 
It is possible to have a private key already, and if that exists, we prioritize private_key over password, even if password authentication type was selected 
Before
After

fix: fix snowflake password and encryption override

---

packages/frontend/src/hooks/useChartColorConfig/utils.ts

Closes: 
For calculate color method, make logic consistent for barchars and pie charts for the same groups
Before
AFter
The first thing I noticed, is that the method that was calculating the color (based on the serie/pivot) was different for pie charts and bar charts 
Pie charts
Bar charts 
This is because we were using on barcharts pivot field, rather than pivotValue[].field. After updating this, the logic was a lot simpler. 
It even works for charts with multigropus

fix: simplify color on pivots, unify logic with pie charts

---

packages/backend/src/database/migrations/20250328163817_change_query_history_error_column_type.ts

Closes: #14209 
- Changes `error` column type to be text instead of string
Before:
After:

fix: make query history error column text type

---

packages/frontend/src/hooks/useChartColorConfig/utils.ts

Reverts lightdash/lightdash#14152
Was initially working well for stacked charts, but some edge cases require the previous logic
before
after

fix: revert "fix: simplify color on pivots, unify logic with pie charts"

---

packages/frontend/src/Routes.tsx

Closes: [#14175](https://github.com/lightdash/lightdash/issues/14175)
Passes `key` with dashboardUuid in `Routes` so that the component remounts with new data
This seems like the cleanest solution (instead of manipulating the way that `setDashboardTiles` is called in `Dashboard.tsx)
Follow steps from ticket to see that the dashboard changes based on the param.

fix: unmount dashboard if uuid changes

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx

Closes: #14206
Relates to: https://github.com/lightdash/lightdash/issues/13950
- After fixing series with transparent colors, we were passing pivot dimensions before sanitization by the usePivotDimensions hook which caused a bug when a chart was saved with a pivot dimension but didn't have it in the results.
1. Create cartesian chart with grouped dimension
2. Remove the dimension in the group and save chart (don't run query) - this will cause the config to have a pivot dimension but no matching selected dimension
3. Add chart to dashboard
4. Open dashboard
**Before**
**After**

fix: use only valid pivot dimensions when computing chart series

---

packages/backend/src/routers/dashboardRouter.ts
packages/backend/src/services/UnfurlService/UnfurlService.ts
packages/frontend/src/components/common/modal/DashboardExportModal.tsx
packages/frontend/src/features/preview/components/PreviewAndCustomizeScreenshot.tsx
packages/frontend/src/features/scheduler/components/SchedulerPreview.tsx
packages/frontend/src/hooks/dashboard/useDashboard.ts

Closes: https://github.com/lightdash/lightdash/issues/13738
- redid the modal layout to be the same as the color palette ones. Modals will look like this one from now on - will implement something in storybook later 
- users can select tab 1, tab 2.
- If they select multiple tabs, it will include them all in one page. 
- Added a bit more logging to a few parts of the screenshot experience
Demo

feat: allow exporting a dashboard tab

---

packages/frontend/src/components/CustomVisualization/index.tsx
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer/ResultsCard/ResultsCard.tsx
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
packages/frontend/src/components/FunnelChart/index.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/LightdashVisualization/context.ts
packages/frontend/src/components/LightdashVisualization/types.ts
packages/frontend/src/components/SimpleChart/index.tsx
packages/frontend/src/components/SimplePieChart/index.tsx
packages/frontend/src/components/SimpleTable/index.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingList.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/GeneralSettings.tsx
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.mock.ts
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
packages/frontend/src/hooks/cartesianChartConfig/utils.ts
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts
packages/frontend/src/hooks/tableVisualization/getDataAndColumns.tsx
packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
packages/frontend/src/hooks/useBigNumberConfig.ts
packages/frontend/src/hooks/useCustomVisualizationConfig.ts
packages/frontend/src/hooks/useFunnelChartConfig.ts
packages/frontend/src/hooks/usePieChartConfig.ts
packages/frontend/src/hooks/usePivotDimensions.ts
packages/frontend/src/hooks/useQueryResults.ts
packages/frontend/src/pages/MinimalSavedExplorer.tsx

Relates to: [#13916](https://github.com/lightdash/lightdash/issues/13916)
Move fetch call to viz components. At the moment they all fetch all rows beside the big number viz. 
Dashboard tiles are still loading all rows and mocking pagination methods(eg: fetchAll, fetchMoreRows)
Following PRs:
- add virtualization to table viz + load more pages as it scrolls
- lazy load viz in dashboard tiles

feat: lazy load explore visualization

---

packages/e2e/cypress/e2e/app/tableCalculation.cy.ts
packages/frontend/src/components/Explorer/CustomDimensionModal/CustomSqlDimensionModal.tsx
packages/frontend/src/features/tableCalculation/components/SqlForm.tsx
packages/frontend/src/features/tableCalculation/components/TableCalculationModal.tsx

Closes: [#14172](https://github.com/lightdash/lightdash/issues/14172)
Changed Modals to be similar to the standard ones - a good example is PaletteModalBase
Renamed wording "isFullscreen" to "isExpanded" to match what is actually happening

feat: allow expanding Custom SQL modal

---

packages/common/src/pivotTable/pivotQueryResults.ts
packages/common/src/types/pivot.ts
packages/frontend/src/hooks/tableVisualization/useTableConfig.ts

Closes: [#14001](https://github.com/lightdash/lightdash/issues/14001)
**Example 1**
[metrics as rows.csv](https://github.com/user-attachments/files/19533498/metrics.as.rows.csv)
**Example 2**
[simple table.csv](https://github.com/user-attachments/files/19533499/simple.table.csv)
**Example 3**
[row totals table.csv](https://github.com/user-attachments/files/19533500/row.totals.table.csv)

feat: include row totals on pivot csv

---

packages/backend/src/controllers/metricsExplorerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/CatalogService/CatalogService.ts
packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts
packages/common/src/utils/metricsExplorer.ts
packages/frontend/src/features/metricsCatalog/components/Canvas/TreeComponents/nodes/ExpandedNode.tsx
packages/frontend/src/features/metricsCatalog/components/Canvas/index.tsx
packages/frontend/src/features/metricsCatalog/hooks/useRunMetricExplorerQuery.ts

Closes: #14110
Canvas nodes in spotlight weren't comparing periods correctly.
Whole this month (effectively month to date)  would get compared to whole previous month. So say it was Apr 5, 5 days would get compared to whole March.
Example of metric queries run _before_:
```sql
-- Previous period
SELECT
COUNT(DISTINCT "orders".order_id) AS "orders_unique_order_count"
FROM "postgres"."jaffle"."orders" AS "orders"
WHERE ((
((DATE_TRUNC('MONTH', "orders".order_date)) >= ('2025-03-01') AND (DATE_TRUNC('MONTH', "orders".order_date)) <= ('2025-03-05'))
))
LIMIT 1;
-- Current period
SELECT
COUNT(DISTINCT "orders".order_id) AS "orders_unique_order_count"
FROM "postgres"."jaffle"."orders" AS "orders"
WHERE ((
((DATE_TRUNC('MONTH', "orders".order_date)) >= ('2025-04-01') AND (DATE_TRUNC('MONTH', …
```

fix: Spotlight canvas nodes comparing to previous month incorrectly

---

packages/frontend/src/features/export/hooks/useExportToGoogleSheet.tsx

- Whenever clicking on the export gsheets button for the second time, it would fire the mutation creating a new job but wouldn't poll for the completion of the new job
**Before**
**After**
**Steps to test**:
1. Go to explore
2. Export gsheets
3. Export gsheets again, look at network tab - you will see infinite loading spinner and no requests polling for the second attempt of exporting

fix: add job id to key when getting gsheets job results

---

packages/frontend/src/components/RegisterForms/VerifyEmailForm.tsx

Nice to have auto-focus on OTP input so that you can just type in your pin as soon as you land on the page
Demo: https://cln.sh/b7bxS4DD

feat: auto focus OTP pin input

---

packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
packages/frontend/src/components/common/Filters/FilterRuleForm.tsx

Closes: #14256 
- Only autofocus select when there's no value selected. This is because there are multiple components with autofocus and there are conflicts
**After**
https://github.com/user-attachments/assets/9a9f9ac3-d992-4e78-9e5d-c5f96ef8a3ec

fix: in the current filter stop autofocus when there's a value

---

packages/frontend/src/components/common/CollapsableCard/CollapsableCard.tsx

Super minor style fix. It's been bugging me 😄. Card action icons/buttons were not aligned with the header. 
**Before**
**After**

fix: card action alignment

---

packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.mock.ts
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts

… map for cartesian
Closes: #14281 
Introduced by: https://github.com/lightdash/lightdash/pull/14166/files#diff-b03fcc24642214a50cfe6ba2a9b7033fa210d120b9ef872f3da83f325c0de636
- `getExpectedSeriesMap` needs rows to exist to produce appropriate series for merging. Uses `hasFetchedAllRows` to run the logic
**Before**
https://github.com/user-attachments/assets/b71b1660-bc9f-4422-a2cd-0666c11ca91a
**After**
https://github.com/user-attachments/assets/8788a372-3a4b-4d7e-9e3b-4ee9c9f178f6

fix: wait for all rows to be fetched before getting expected series map for cartesian

---

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Grid/constants.ts
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: #14062
- Calculates correct grid taking into account the default gap of the y axis names
**Before**
**After**

fix: calculate correct grid taking into account default gap

---

packages/backend/src/services/ProjectService/ProjectService.ts

- When running the subtotals queries on the backend we were still passing sorts, this meant that if we were sorting by the last dimension (which gets removed from the subtotal groups) the query would fail: see known limitations in: https://github.com/lightdash/lightdash/pull/13847
**Before**
**After**

fix: remove sorts from subtotals queries

---

packages/frontend/src/hooks/dashboard/useDashboardChart.ts

Relates to: https://github.com/lightdash/lightdash/pull/14224, [Decrease amount of requests while waiting for paginated results](https://github.com/lightdash/lightdash/issues/14299)
- While hook was loading, data from feature flag hook was undefined therefore it was requesting `chart-and-results`. When it was successful it changed the key and refetched using pagination query. Now it waits for it to be fetched (also works with errors, which will have fetched true and data: undefined)

fix: wait for pagination feature flag to be fetched before running the hook

---

packages/backend/src/models/SpaceModel.ts
packages/backend/src/services/PromoteService/PromoteService.ts

Closes: N/A
Fixes the bug with promoting charts in nested spaces leading to only the last space being created on top level

fix: nested space promotions

---

packages/backend/src/models/SavedChartModel.ts
packages/backend/src/services/CatalogService/CatalogService.ts

Closes: [#3142](https://github.com/lightdash/lightdash-internal-work/issues/3142)
Optimize query that counts charts for each catalog field:
- remove unnecessary joins
- remove seq scans
- filter by fields available in the catalog
Before:
After:

fix: optimize query that counts charts per catalog field

---

examples/api/nested-spaces.http
packages/backend/src/database/entities/spaces.ts
packages/backend/src/database/migrations/20250404110407_nested_spaces.ts
packages/backend/src/database/seeds/development/01_initial_user.ts
packages/backend/src/database/seeds/development/05_nested_spaces.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/DashboardModel/DashboardModel.mock.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/models/ResourceViewItemModel.ts
packages/backend/src/models/SpaceModel.ts
packages/backend/src/services/CoderService/CoderService.ts
packages/backend/src/services/DashboardService/DashboardService.mock.ts
packages/backend/src/services/PromoteService/PromoteService.mock.ts
packages/backend/src/services/PromoteService/PromoteService.test.ts
packages/backend/src/services/PromoteService/PromoteService.ts
packages/backend/src/services/SpaceService/SpaceService.test.ts
packages/backend/src/services/SpaceService/SpaceService.ts
packages/common/src/index.ts
packages/common/src/types/promotion.ts
packages/common/src/types/space.ts
packages/common/src/utils/slug.test.ts
packages/common/src/utils/slugs.ts
packages/frontend/src/components/common/ShareSpaceModal/index.tsx

Closes: N/A
- Adds DB migration to support nested spaces
This PR adds 2 columns to `spaces` table
- `parent_space_uuid` that contains the direct parent of a space
- `path`, and `ltree` containing the hierarchy of spaces. `parent-slug.child-slug.grandchild-slug`

feat: nested spaces (backend)

---

packages/backend/src/database/entities/resultsCache.ts
packages/backend/src/database/migrations/20250411110948_add_updated_at_column_to_results_cache.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/ResultsCacheModel/ResultsCacheModel.test.ts
packages/backend/src/models/ResultsCacheModel/ResultsCacheModel.ts
packages/backend/src/models/ResultsCacheModel/types.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/ProjectService/types.ts
packages/common/src/index.ts
packages/frontend/src/hooks/useQueryResults.ts

Closes: [#14375](https://github.com/lightdash/lightdash/issues/14375)
- Adds `updated_at` column to `results_cache` table
- Returns cache metadata in `executeAsyncQuery`
https://github.com/user-attachments/assets/e4381746-28ef-4eb8-aa08-c81de300faa9

feat: add updated_at column to results cache and return in cache metadata

---

packages/backend/src/App.ts
packages/backend/src/SchedulerApp.ts
packages/backend/src/prometheus.ts

Relates to: [#14373](https://github.com/lightdash/lightdash/issues/14373)
Add prometheus metrics for database. Helps track if there is a bottleneck in the database connections.
Metrics example:
```
pg_pool_max_size 10
pg_pool_size 10
pg_active_connections 1
pg_idle_connections 9
pg_queued_queries 0
pg_connection_acquire_time_bucket{le="1"} 552
pg_connection_acquire_time_bucket{le="5"} 621
pg_connection_acquire_time_bucket{le="10"} 631
pg_connection_acquire_time_bucket{le="25"} 634
pg_connection_acquire_time_bucket{le="50"} 634
pg_connection_acquire_time_bucket{le="100"} 635
pg_connection_acquire_time_bucket{le="250"} 635
pg_connection_acquire_time_bucket{le="500"} 635
pg_connection_acquire_time_bucket{le="1000"} 635
pg_connection_acquire_time_bucket{le="2500"} 635 …
```

chore: prometheus metrics for database

---

packages/backend/src/database/migrations/20250411142258_add_user_id_index_to_project_memberships.ts

Relates to: https://github.com/lightdash/lightdash/issues/14373
When getting the session user, we fetch all the projects roles.
```
SELECT
*
FROM
"project_memberships"
LEFT JOIN
"projects"
ON
"project_memberships"."project_id" = "projects"."project_id"
WHERE
"user_id" = $1
```
Since project_memberships doesn't have an index for `user_id` it does a seq scan:
Explain plan: ( now uses index scan )
```
Nested Loop Left Join  (cost=0.26..17.06 rows=1 width=2820) (actual time=0.036..0.038 rows=1 loops=1)
->  Index Scan using project_memberships_project_id_index on project_memberships  (cost=0.12..8.14 rows=1 width=48) (actual time=0.022..0.024 rows=1 loops=1)
Filter: (user_id = 1)
->  Index Scan using projects_pkey on projects  (cost=0.14..8.15 rows=1 width=2772) (actual time=0.010..0.011 …
```

fix: add user_id index to project_memberships table

---

packages/common/src/types/featureFlags.ts
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/hooks/dashboard/useDashboardChart.ts
packages/frontend/src/hooks/useQueryResults.ts

Closes: #14349 
Shows the warehouse execution time and total time for tiles on dashboards. 
Feature flag is created and enabled for dev and analytics

feat: show tile query execution timing

---

packages/frontend/src/providers/Dashboard/DashboardProvider.tsx

Closes: 
Adds a guard for accessing cacheMetadata. There is a crash report in sentry from this. 
https://lightdash.sentry.io/issues/6536834014/events/dbfc780c5d104c93a5e6a584930a8515?environment=cloud_beta&project=4507168845529088
I don't know how this can get undefined. I'm looking into that and we need to clean up the types here, but this should be safe and avoid the crash.

fix: error when cacheMetadata is undefined

---

packages/frontend/src/hooks/dashboard/useDashboardChart.ts
packages/frontend/src/hooks/useExplore.tsx
packages/frontend/src/hooks/useSavedQuery.ts

Relates to: https://github.com/lightdash/lightdash/issues/14299, https://github.com/lightdash/lightdash/issues/14373, 
- Improves `useDashboardChart` hook so it doesn't request for the same explore multiple times by using the hooks
**Before**
- dashboard containing multiple duplicate charts ((uses same explore)
**After**
- dashboard containing multiple duplicate charts (uses same explore)

fix: only fetch explore once

---

packages/frontend/src/ee/features/embed/SettingsEmbed/index.tsx

Closes: #14385
Gets dashboards from private spaces **if** the user has ability to see them **or** has direct access to them. A similar PR was done here: https://github.com/lightdash/lightdash/pull/14409/files
To test
create public and private space and insert a dashboard in each
for another user, create a private space and add a dashboard
you should see all dashboards as an admin on the embed configuration 
Also test the dashboards-as-code
1. download a dashboard (as another user)
2. and upload it to a private space with a different slug/filename to test it out
3. you should see that one as well in the embed configuration

fix: get dashboards from allowed private space when embedding

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/models/ResultsCacheModel/ResultsCacheModel.test.ts
packages/backend/src/models/ResultsCacheModel/ResultsCacheModel.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/index.ts

Add analytics events for caching.
Adds events for
- results_cache.create
- results_cache.write
- results_cache.read
- results_cache.delete
And adds cache metadata these events when available
- query.executed
- query_page.fetched
Note: I wasn't sure about tracking 2 events in sequence, but this code does that sometimes. For example, it sends a `results_cache.read`, then a `query_page.fetched` one after the other when a page is fetched. It seems like it will be useful to have these types separated for when actually doing analytics, but if there is a reason not to do this, we can adjust it.

chore: add analytics events for results cache

---

packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
packages/frontend/src/providers/Dashboard/DashboardProvider.tsx

Closes: https://github.com/lightdash/lightdash/issues/14353

fix: show reset filters if url overrides dashboard filters

---

packages/backend/src/logging/winston.ts

Logging to `trace` ends up nesting the trace field in `.jsonPayload.trace` (this is where GCP puts all fields by default)
If we want `trace` to actually appear at the root of a GCP log object, we need to use the special metadata field: https://cloud.google.com/logging/docs/structured-logging#structured_logging_special_field

fix: google trace metadata field

---

packages/e2e/cypress/e2e/app/dashboard.cy.ts
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/components/common/modal/DashboardCreateModal.tsx

- Fixes dashboard charts loading state which wasn't showing loading while doing the post to execute query + get first page other than on the initial load
**Before**
https://github.com/user-attachments/assets/0e109f93-fe4b-463d-a875-f85ebea107a3
**After**
https://github.com/user-attachments/assets/88a00b86-b290-4d71-8f19-beda95625e86

fix: loading state on dashboard charts refresh

---

packages/backend/src/models/AnalyticsModel.ts
packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/models/DashboardModel/DashboardModel.ts
packages/backend/src/models/OpenIdIdentitiesModel.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/models/UserModel.ts
packages/backend/src/models/WarehouseAvailableTablesModel/WarehouseAvailableTablesModel.ts

- Reduce number of connections checked out from knex by properly using transaction objects (`trx`) in database queries instead of the main database connection (in other words these were checking out one connection for trx and _another_ connection for each this.database use)
- Removed redundant `.transacting(trx)` calls when the transaction is already being used (no biggy but just cleaning)

fix: no new sessions in trx blocks

---

packages/e2e/cypress/e2e/app/explore.cy.ts
packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderSortMenuOptions.tsx
packages/frontend/src/components/SortButton/Sorting.tsx
packages/frontend/src/components/SortButton/index.tsx

Closes: #9533 
When a sort is applied to from the column header, then replace the sorting
When the user wants to multisort, then they have to click on the badge to add more
Ticket above includes mockups and relevant thread is here: https://lightdash.slack.com/archives/C03MCQ08UKS/p1744369704613779?thread_ts=1744369543.999679&cid=C03MCQ08UKS
https://github.com/user-attachments/assets/b55f52db-f6ad-4596-961b-13803d94d111

feat: improve sorting behaviour ux

---

packages/backend/src/services/UnfurlService/UnfurlService.ts
packages/frontend/src/components/DashboardTiles/TileBase/index.tsx

Closes: #14411 
- `chart-and-results` is no longer used or behind a feature flag, remove it from unfurl service
test-frontend

fix: remove legacy endpoints from unfurl service

---

packages/frontend/src/components/Explorer/ExploreSideBar/ExploreNavLink.tsx

Closes: N/A
Noticed this when I broke an explore:
https://github.com/user-attachments/assets/4aac2e27-d559-455c-ba57-976a5d0ca05d
Improved on-hover experience of an explore error (matches metric detail component)
Got ✅ from @PriPatel 
https://github.com/user-attachments/assets/2aa47a14-0456-43dc-95f4-a93b376615a4

style: improve explore error hovercard

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/providers/Tracking/types.ts
packages/frontend/src/types/Events.ts

Add an event to track dashboard query return time in the frontend. 
To test:
- Check that one `track` is sent per dashboard chart containing the load time

chore: add a frontend event for query performance

---

packages/backend/src/services/UnfurlService/UnfurlService.ts

Closes: #14462
- Timeout to wait for charts was still running even when expected responses was 0
1. Create dashboard with just markdown tiles ( don't add any saved charts )
2. Trigger `Generate preview`
**Before**
**After**

fix: don't trigger unfurl timeout when there are 0 expected responses

---

packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx

Closes: #14468
This happens when calculated series colors is disabled. Calculated series colors introduces other issues related to chart render order, but fixes this.
This approach will sort the `fallback` colors so that colors always match if 2 charts contain the same series and are using fallback colors
Related PR: https://github.com/lightdash/lightdash/pull/13923 
**Before**
**After**

fix: sort series for fallback colors

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/services/SpaceService/SpaceService.ts
packages/frontend/src/pages/Space.tsx
packages/frontend/src/providers/Tracking/types.ts
packages/frontend/src/types/Events.ts

Closes: #14396
**server events - create/update/delete**
**UI - click on space breadcrumb**

chore: add analytics events to nested spaces' feature

---

packages/frontend/package.json
pnpm-lock.yaml

Closes: #14494
- Bump echarts version to 5.6.0 which fixes `undefined` access
Haven't been able to reproduce the issue locally
https://github.com/apache/echarts/issues/20532 - fix released in https://github.com/apache/echarts/releases/tag/5.6.0

fix: bump echarts to 5.6.0

---

packages/common/src/types/conditionalFormatting.ts
packages/common/src/utils/conditionalFormatting.ts
packages/frontend/src/utils/colorUtils.ts

Closes: #12557 and fixes bug with small (close to 1) numbers
Instead of using discrete fixed number of steps, smoothly interpolate numbers

fix: conditional formatting for small numbers and smooth color range

---

packages/backend/src/config/parseConfig.ts
packages/backend/src/logging/auditLog.ts
packages/backend/src/logging/caslAuditWrapper.test.ts
packages/backend/src/logging/caslAuditWrapper.ts
packages/backend/src/logging/winston.ts
packages/backend/src/services/DashboardService/DashboardService.ts
packages/common/src/authorization/types.ts

Logs out permission checks for auditing. This doesn't actually enable the wrapper yet.
- Adds CASL wrapper to enable logging
- Adds winston log levels for auditing
- Adds tests for CASL formatting
Example check from the dashboard (not included in this PR)
```
{
"action": "view",
"actor": {
"email": "demo@lightdash.com",
"firstName": "David",
"groupMemberships": [],
"lastName": "Attenborough",
"organizationRole": "admin",
"organizationUuid": "172a2270-000f-42be-9c68-c4752c23ae51",
"uuid": "b264d83a-9000-426a-85ec-3f9c20f368ce"
},
"context": {},
"id": "fbd1f07a-df3f-4d40-8005-62e48339c34b",
"level": "audit",
"message": "view Dashboard 747c7e64-cffb-4e72-b92c-9b035c8e17d5 by b264d83a-9000-426a-85ec-3f9c20f368ce (allowed)",
"resource": {
"name": "Jaffle dashboard",
"organizationUuid": …
```

feat: add audit logging for casl checks

---

.cursor/rules/backend-code-style.mdc
.cursor/rules/backend-service-authorization-permissions.mdc

Adds cursor rules for writing permission checks. Frequently it uses CASL incorrectly

docs: update cusor rules with auth info

---

.cursor/rules/backend.mdc

Stops cursor writing ridiculous unit tests

docs: add cursor rules for backend unit tests

---

packages/backend/src/utils.ts

I want to wrap a span around a sync function

chore: sentryWrapTransaction accepts sync functions

---

packages/frontend/src/components/common/ResourceView/InfiniteResourceTable.tsx

Closes: #14486
Allows clicking on a space row besides its name

fix: allow clicking on space row in InfiniteResourceTable

---

packages/frontend/src/components/common/modal/DashboardCreateModal.tsx
packages/frontend/src/features/sqlRunner/components/SaveSqlChartModal.tsx
packages/frontend/src/features/sqlRunner/components/UpdateSqlChartModal.tsx
packages/frontend/src/hooks/useSpaceManagement.ts

Relates to: https://github.com/lightdash/lightdash/issues/14329
When creating a dashboard from: 
Also hides "create space" from modals when the feature is not enabled

feat: allow saving/creating spaces in dashboard create

---

packages/e2e/cypress/e2e/app/dashboard.cy.ts
packages/e2e/cypress/e2e/app/explore.cy.ts
packages/e2e/cypress/e2e/app/pivotTables.cy.ts
packages/e2e/cypress/e2e/app/savedDashboards.cy.ts
packages/e2e/cypress/e2e/app/space.cy.ts
packages/e2e/cypress/e2e/app/sqlRunner.cy.ts
packages/frontend/src/components/common/SpaceSelector/SpaceCreationForm.tsx
packages/frontend/src/components/common/SpaceSelector/SpaceSelector.tsx
packages/frontend/src/components/common/TransferItemsModal/TransferItemsModal.tsx
packages/frontend/src/components/common/modal/ChartCreateModal/SaveToDashboardForm.tsx
packages/frontend/src/components/common/modal/ChartCreateModal/SaveToSpaceForm.tsx
packages/frontend/src/components/common/modal/ChartCreateModal/SaveToSpaceOrDashboard.tsx
packages/frontend/src/components/common/modal/DashboardCreateModal.tsx
packages/frontend/src/features/semanticViewer/components/Modals/SaveSemanticViewerChartModal.tsx
packages/frontend/src/features/sqlRunner/components/SaveSqlChartModal.tsx
packages/frontend/src/features/sqlRunner/components/UpdateSqlChartModal.tsx
packages/frontend/src/hooks/useModalSteps.ts
packages/frontend/src/hooks/useSpaceManagement.ts

Relates to: #14329
Adds multi-step modal when saving a chart

feat: allow saving content to any space (tree view)

---

packages/frontend/src/components/common/modal/ChartCreateModal/SaveToSpaceOrDashboard.tsx

Closes: N/A
Fix max update depth issue when de-selecting a _default space_ - this happens when creating a chart when in the space detail view
before
[before-max.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/DJhzIQbRJqTJiKN3mUjT/53ff3834-c1c5-4ea1-852a-e3b9b4902dc3.mov" />](https://app.graphite.dev/media/video/DJhzIQbRJqTJiKN3mUjT/53ff3834-c1c5-4ea1-852a-e3b9b4902dc3.mov)
after
[fixed-max.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/DJhzIQbRJqTJiKN3mUjT/d1223c51-ca3d-4972-b882-e4d952aa83ea.mov" />](https://app.graphite.dev/media/video/DJhzIQbRJqTJiKN3mUjT/d1223c51-ca3d- …

fix: only set default space if form not initialised

---

packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts
packages/backend/src/utils.ts

Adds a sync version of `wrapSentryTransaction` so that `buildQuery` remains a sync function

fix: revert queryBuilder to sync function

---

packages/common/src/utils/timeFrames.ts

Closes: #14534
- Updates `time_intervals` defaults for `date` types to match docs
docs: https://docs.lightdash.com/references/dimensions#by-default-the-time-intervals-we-use-are
Before:
After:
test-frontend

fix: default time intervals for date

---

packages/backend/src/dbt/dbtCliClient.ts

Closes: N/A
Added a new `ensureDbtProjectDir` method to the `DbtCliClient` class that checks if the dbt project directory exists before running commands. This method is now called before installing dependencies in the `test` method, which will throw a more descriptive error when the project directory is missing.
[CleanShot 2025-04-25 at 16.58.14.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/SRLEqMEevAzoFwvhnfeq/83209ea3-05d8-4158-8421-5e54af834214.mp4" />](https://app.graphite.dev/media/video/SRLEqMEevAzoFwvhnfeq/83209ea3-05d8-4158-8421-5e54af834214.mp4)

fix: check dbt project directory exists before running commands

---

packages/backend/src/ee/controllers/embedController.ts
packages/backend/src/ee/database/migrations/20250424123216_add_allow_all_dashboards_column_to_embeddings.ts
packages/backend/src/ee/models/EmbedModel.ts
packages/backend/src/ee/services/EmbedService/EmbedService.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/ee/embed/index.ts
packages/e2e/cypress/e2e/api/embedManagement.cy.ts
packages/frontend/src/ee/features/embed/SettingsEmbed/EmbedDashboardsForm.tsx
packages/frontend/src/ee/features/embed/SettingsEmbed/index.tsx

Closes: #14361
Added a new "Allow all dashboards" option to the embed settings, which allows users to embed any dashboard without having to explicitly select each one.
- Added a new `allow_all_dashboards` column to the `embedding` table
- Updated the embed model, service, and controller to support the new option
- Added a switch in the UI to toggle between allowing all dashboards or selecting specific ones
- Updated permission checks to respect the new setting
Demo: https://cln.sh/DL4qwBxr

feat: admins can allow all dashboards to be embedded

---

packages/common/src/utils/slug.test.ts
packages/common/src/utils/slugs.ts

Closes: https://github.com/lightdash/lightdash/issues/14559
for space slugs that still contain leading and trailing hyphens, ignore the trimming of them when creating a nested space. 
This is related to #[this PR](https://github.com/lightdash/lightdash/pull/9875) where sanitization when generating removed leading and trailing but the migration did not account for that

fix: ltree path generation for slugs with emojis

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/metricQuery.ts
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer/ResultsCard/CellContextMenu.tsx
packages/frontend/src/components/Explorer/VisualizationCard/SeriesContextMenu.tsx
packages/frontend/src/components/FunnelChart/FunnelChartContextMenu.tsx
packages/frontend/src/components/MetricQueryData/UnderlyingDataModalContent.tsx
packages/frontend/src/components/SimplePieChart/PieChartContextMenu.tsx
packages/frontend/src/components/SimpleStatistic/BigNumberContextMenu.tsx
packages/frontend/src/components/SimpleTable/CellContextMenu.tsx
packages/frontend/src/components/SimpleTable/DashboardCellContextMenu.tsx
packages/frontend/src/components/common/PivotTable/ValueCellMenu.tsx

Closes: #10023 
**Before**
- Underlying data option didn't show for any metric
**After**
https://github.com/user-attachments/assets/d5772ab7-49ca-4b1b-ac36-3a91776f13ac

feat: enable underlying data for charts with sql custom dimensions

---

packages/backend/src/controllers/v2/ProjectController.ts
packages/e2e/cypress/e2e/app/tableCalculation.cy.ts
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer/ExplorerHeader/index.tsx
packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx
packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/components/Explorer/index.tsx
packages/frontend/src/components/RefreshButton.tsx
packages/frontend/src/ee/features/embed/EmbedDashboard/components/EmbedDashboardChartTile.tsx
packages/frontend/src/hooks/dashboard/useDashboardChartReadyQuery.ts
packages/frontend/src/hooks/useColumns.tsx
packages/frontend/src/hooks/useQueryResults.ts
packages/frontend/src/providers/Explorer/ExplorerProvider.tsx

Related to: [#1406](https://github.com/lightdash/lightdash/issues/1406)
Stop loading the first page of results on query creation. 
This will allow us to cancel a query while it's pending.
Changes:
- update dashboard hook to not fetch first page
- update infinite results hook to refetct query while in pending state
- update loading states condition
- refactor firstPage usage to use resultsData

fix: stop waiting for first results page

---

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/components/common/ResourceView/ResourceActionHandlers.tsx
packages/frontend/src/components/common/TransferItemsModal/TransferItemsModal.tsx
packages/frontend/src/components/common/modal/DashboardCreateModal.tsx
packages/frontend/src/features/semanticViewer/components/Modals/SaveSemanticViewerChartModal.tsx
packages/frontend/src/features/sqlRunner/components/SaveSqlChartModal.tsx
packages/frontend/src/features/sqlRunner/components/UpdateSqlChartModal.tsx
packages/frontend/src/pages/Dashboard.tsx

Closes: n/A
Improves loading states with loading overlays/loading states when
saving sql runner chart
[state loadin sql runner.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/DJhzIQbRJqTJiKN3mUjT/951c3dbf-ba46-45ae-b59f-2445921098c4.mov" />](https://app.graphite.dev/media/video/DJhzIQbRJqTJiKN3mUjT/951c3dbf-ba46-45ae-b59f-2445921098c4.mov)
transferring dashboard
[saved-dashboard-tranfer.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/DJhzIQbRJqTJiKN3mUjT/2c87eb58-ad87-4182-aa49-1324f4f37bcc.mov" />](https://app.graphite.dev/media/video/DJhzIQbRJqTJiKN3mUjT/2c87eb58-ad87-418 …

fix: add loading states/overlays when moving

---

packages/e2e/cypress/e2e/app/dates.cy.ts
packages/frontend/src/api.ts
packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx
packages/frontend/src/components/RefreshButton.tsx
packages/frontend/src/ee/features/embed/EmbedDashboard/components/EmbedDashboardChartTile.tsx
packages/frontend/src/hooks/useQueryResults.ts
packages/frontend/src/providers/Explorer/ExplorerProvider.tsx
packages/frontend/src/providers/Explorer/types.ts

Closes: #1406 
Note this only cancels the query in the frontend. 
A separate PR is necessary to cancel the query in the warehouse.
Changes:
- support signal in fetch calls and query execution hook
- show cancel button when query is being created or pending
- on cancel, cancel query creation and set the previous queryUuid. (loads cached pages)

feat: cancel explore query

---

packages/frontend/src/features/queryRunner/BaseResultsRunner.ts
packages/frontend/src/providers/ReactQuery/createQueryClient.ts

Related issues: https://github.com/lightdash/lightdash/issues/13292#issuecomment-2701083940, https://github.com/TanStack/query/discussions/4753#discussioncomment-4592410
Docs: https://tanstack.com/query/v4/docs/framework/react/guides/network-mode
**How to test**
1. Turn off your wifi
2. Try to run lightdash locally, without this change you will see an infinite loading spinner in the login page

fix: use networkMode always for tanstack queries and mutations

---

packages/frontend/src/providers/Explorer/ExplorerProvider.tsx

Removes duplicate declaration of `queryClient`

fix: duplicate use query client

---

packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx

Closes: #14345
Clicking "Remove" from the results table should remove the field from the active fields, not actually "deleting" it from the explore. 
[bug-custom-dimension.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/DJhzIQbRJqTJiKN3mUjT/246bf392-2a6b-469e-8eba-ac3afaccb340.mov" />](https://app.graphite.dev/media/video/DJhzIQbRJqTJiKN3mUjT/246bf392-2a6b-469e-8eba-ac3afaccb340.mov)

fix: remove active field custom dim instead of deleting

---

packages/frontend/src/components/FunnelChart/index.tsx
packages/frontend/src/components/SimpleChart/index.tsx
packages/frontend/src/components/SimplePieChart/index.tsx
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts
packages/frontend/src/hooks/echarts/useEchartsFunnelConfig.ts
packages/frontend/src/hooks/echarts/useEchartsPieConfig.ts
packages/frontend/src/hooks/echarts/useLegendDoubleClickSelection.ts
packages/frontend/src/hooks/echarts/useLegendDoubleClickTooltip.ts

Closes: [#13780](https://github.com/lightdash/lightdash/issues/13780)
- Use double click to select series, echarts doesn't provide a way to handle right clicks: https://github.com/apache/echarts/issues/20288
**Cartesian charts**
https://github.com/user-attachments/assets/04c50a38-1511-49a4-8167-bb049130ad04
**Pie charts**
https://github.com/user-attachments/assets/f02ad7b3-b4bf-4e59-af1b-cee6acd9d4b5
**Funnel charts**
https://github.com/user-attachments/assets/fdb4e5a9-577d-496b-a8f1-3eab30f84e73

feat: add double legend click handlers

---

packages/cli/src/handlers/dbt/compile.ts
packages/cli/src/index.ts

Closes: #14464
Added support for the `--defer` flag in dbt commands. This allows users to resolve unselected nodes by deferring to the manifest within the `--state` directory.
- Added `defer` option to `DbtCompileOptions` type
- Added `defer` to the list of dbt compile arguments
- Added proper CLI options with descriptions for `--defer` and `--no-defer` flags in multiple commands
Before
After

feat: support --defer dbt on CLi preview

---

packages/frontend/src/hooks/dashboard/useDashboardChartReadyQuery.ts

- Invalidate cache in query key was causing the first refresh of a dashboard to trigger 2 queries
**Before**
https://github.com/user-attachments/assets/f40fb113-4426-4be3-b6aa-cf65b5d1fce1
**After**
https://github.com/user-attachments/assets/719cd176-4b63-420f-a524-fb27e7d78385

fix: remove invalidate cache from query key

---

packages/backend/src/database/entities/resultsCache.ts
packages/backend/src/database/migrations/20250501102249_add_status_column_to_results_cache.ts
packages/backend/src/models/ResultsCacheModel/ResultsCacheModel.test.ts
packages/backend/src/models/ResultsCacheModel/ResultsCacheModel.ts
packages/backend/src/models/ResultsCacheModel/types.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts

Closes: #14620 
- Fixes race condition where if 2 charts were loaded at the same time (with caching enabled) the first one would still be writing to cache while the second would render a cache hit and try to request the results from the file while it was still being written
- Adding column to `results_cache` table which tracks whether the cache is `READY` or `PENDING`
- Sets the `queryHistory` status depending on this when it is a cache hit
- On get results, updates the `queryHistory` status to `READY`

fix: race condition cache being written while another execute query was called

---

packages/backend/src/ee/repl/index.ts
packages/backend/src/ee/repl/scripts/fixDuplicateSlugs.test.ts
packages/backend/src/ee/repl/scripts/fixDuplicateSlugs.ts
packages/backend/src/utils/SlugUtils.ts

Related to: [#14584](https://github.com/lightdash/lightdash/issues/14584)
Execution plan:
- add REPL scripts that fix chart&dashboards slug uniqueness across all projects
- test scripts in production, with dryRun:true option
- move the script's logic to a migration + enforce unique index
- delete REPL scripts
Update script to work across all projects.

chore(repl): update script to fix chart slugs across all projects

---

packages/backend/src/database/entities/dashboards.ts
packages/backend/src/ee/repl/scripts/fixDuplicateSlugs.ts
packages/backend/src/utils/SlugUtils.ts

Related to: [#14584](https://github.com/lightdash/lightdash/issues/14584)
Execution plan:
- add REPL scripts that fix chart&dashboards slug uniqueness across all projects
- test scripts in production, with dryRun:true option
- move the script's logic to a migration + enforce unique index
- delete REPL scripts
- 
Add script to fix duplicate dashboard slugs across all projects. 90% copy paste from chart script

chore(repl): script to fix duplicate dashboard slugs

---

packages/backend/src/ee/services/CommercialCacheService.ts
packages/frontend/src/hooks/dashboard/useDashboardChartReadyQuery.ts

Relates to: https://github.com/lightdash/lightdash/pull/14624
- Sets cache back to pending when invalidating

fix: set cache status to pending when invalidating

---

packages/frontend/src/hooks/useQueryResults.ts

- Takes into account `warehouseExecutionTime` when calculating total fetch time

fix: add query execution time to total time

---

packages/frontend/src/components/common/Dashboard/DashboardRefreshButton.tsx
packages/frontend/src/hooks/dashboard/useDashboardRefresh.ts

Closes: [#14659](https://github.com/lightdash/lightdash/issues/14659)
- We were updating `invalidateQueries` state + invalidating manually the query. This caused double fetch on first refresh because `invalidateQueries` went from `false` to `true` which invalidates the query itself, but then it was also getting invalidated by the refresh button.
- This PR fixes this by splitting queries into invalidate between related queries (which always get fetched and are not dependent on `invalidateCache`) and results queries (dependent on `invalidateCache`). Then we only manually invalidate the results manually when `invalidateCache` is true and the button is clicked, otherwise the `invalidateCache` state change invalidates the query by itself
**Before** …

fix: dashboard double fetch on first refresh

---

packages/frontend/src/components/common/modal/ChartCreateModal/SaveToSpaceOrDashboard.tsx

Hitting "Enter" when saving a chart caused the page to reload (form submit), loosing any progress on the chart. This prevents the reload in the case of early submission of the form. 
Before:
To test:
- Make a chart
- Click "Save Chart"
- Git it a name
- Hit Enter 
- Before: page reload
- With this fix: nothing happens

fix: don't reload page on early submit from chart save

---

packages/backend/src/controllers/v2/ProjectController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/ProjectService/types.ts
packages/common/src/types/api/paginatedQuery.ts
packages/common/src/types/sqlRunner.ts

Closes: #14627 
Add an optional pivot config to the paginated SQL endpoint. 
`POST /api/v2/projects/:projectId/query/sql`
The POST body I've been using for initial tests looks like
```
{
"context": "dashboardView",
"invalidateCache": false,
"sql": "SELECT * FROM \"postgres\".\"jaffle\".\"customers\" ",
"pivotConfiguration": {
"indexColumn": {
"reference": "created",
"type": "time"
},
"valuesColumns": [
{
"reference": "customer_id",
"aggregation": "sum"
}
],
"groupByColumns": [],
"sortBy": [
{
"direction": "ASC",
"reference": "created"
}
]
}
}
```
test-frontend

chore: add pivot option to sql endpoint

---

packages/frontend/src/components/Explorer/ResultsCard/QuickCalculations.tsx

Closes: #13521
Trino does not have a `FLOAT` type, so this fixes the quick calculations

fix: QuickCalculations for `trino`

---

packages/backend/src/services/CoderService/CoderService.ts
packages/backend/src/services/PromoteService/PromoteService.ts
packages/common/src/utils/slug.test.ts
packages/common/src/utils/slugs.ts

Closes: N/A
This PR improves space creation during promotion by:
1. Removing debug console.log statements from CoderService
2. Enhancing the PromoteService to handle multiple space hierarchies correctly:
- Added a `getDeepestPaths` utility function to identify leaf nodes in space hierarchies
- Modified space creation logic to process each hierarchy independently
- Prevented duplicate space creation by tracking created spaces in a Map
3. Added comprehensive tests for the new `getDeepestPaths` utility function
This change ensures that when promoting content with complex space hierarchies, all spaces are created correctly and efficiently.

fix: neighbor spaces when promoting

---

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/components/Explorer/SpaceBrowser/SpaceBrowserMenu.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/components/common/ResourceView/ResourceActionHandlers.tsx
packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx
packages/frontend/src/components/common/ResourceView/types.ts
packages/frontend/src/components/common/SpaceSelector/SpaceSelector.tsx
packages/frontend/src/components/common/TransferItemsModal/TransferItemsModal.tsx
packages/frontend/src/components/common/Tree/Tree.tsx
packages/frontend/src/components/common/Tree/TreeItem.module.css
packages/frontend/src/components/common/Tree/TreeItem.tsx
packages/frontend/src/components/common/modal/ChartCreateModal/SaveToSpaceForm.tsx
packages/frontend/src/hooks/useSpaces.ts
packages/frontend/src/pages/Space.tsx

Closes: #14326
Adds the ability to transfer spaces to other spaces, allowing users to organize their space hierarchy. This feature enables moving spaces between parent spaces or to the root level.

feat(frontend): Move space to another space

---

packages/frontend/src/components/common/SpaceActionModal/index.tsx

Closes: #14673
Fix form initialization in SpaceActionModal to only use provided data when editing an existing space. When creating a new space, the form should start with undefined values rather than potentially using stale data.

fix: initialize form values only when editing a space

---

packages/backend/src/models/ProjectModel/ProjectModel.ts

Closes: #14692
Skip creating a "Shared" space for preview projects.

fix: skip default space creation for preview projects

---

packages/backend/src/controllers/runQueryController.ts
packages/backend/src/controllers/savedChartController.ts
packages/backend/src/controllers/v2/ProjectController.ts
packages/backend/src/ee/services/EmbedService/EmbedService.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/AsyncQueryService/AsyncQueryService.test.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/backend/src/services/AsyncQueryService/types.ts
packages/backend/src/services/CsvService/CsvService.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/api/paginatedQuery.ts
packages/common/src/types/metricQuery.ts
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/MetricQueryData/UnderlyingDataModalContent.tsx
packages/frontend/src/components/MetricQueryData/types.ts
packages/frontend/src/hooks/dashboard/useDashboardChartReadyQuery.ts
packages/frontend/src/hooks/useQueryResults.ts
packages/frontend/src/hooks/useUnderlyingDataResults.ts

Closes: #14615
Gets x axis field from cartesian configs, otherwise, the first date dim from metric query
Overrides correct x axis ID
Passes `DateZoom` to underlying data query
Also renames `granularity` to a `dateZoom` property with a few properties
[datezoomwithunderlyingdata.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/DJhzIQbRJqTJiKN3mUjT/77b318af-aade-4003-bf2b-3bdf30c67e48.mov" />](https://app.graphite.dev/media/video/DJhzIQbRJqTJiKN3mUjT/77b318af-aade-4003-bf2b-3bdf30c67e48.mov)

fix: filter date zoom when viewing underlying data

---

packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts

Relates to: https://github.com/lightdash/lightdash/pull/14688
**Before**
**After**

fix: sql queries causing explore not found error when not cached

---

packages/frontend/src/components/common/ResourceView/InfiniteResourceTable.tsx
packages/frontend/src/pages/Space.tsx

Closes: #14699
In the Space page, we now automatically set the initial view to 'all' for project admins who don't have direct access to the space, making it easier for them to see all content they can manage.
[CleanShot 2025-05-07 at 18.26.28.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/SRLEqMEevAzoFwvhnfeq/e0fa5807-d6bb-4202-8406-91aa22018315.mp4" />](https://app.graphite.dev/media/video/SRLEqMEevAzoFwvhnfeq/e0fa5807-d6bb-4202-8406-91aa22018315.mp4)

fix: admins should be able to see private spaces on every level

---

packages/common/src/compiler/filtersCompiler.ts
packages/common/src/utils/filters.ts
packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
packages/frontend/src/components/common/Filters/FilterInputs/FilterQuarterPicker.tsx

Closes: #14176 
- Created a new `FilterQuarterPicker` component that allows users to select quarters (Q1, Q2, Q3, Q4) for a given year
- Updated date filter handling to properly format and process quarterly date selections (see filters.ts)
- Added quarter support to the date filter rendering logic
- Replaced string literals with `FilterOperator` enum constants in the date filter SQL renderer
This change enables users to filter data by quarters, rather than using specific dates. Dates are stored in the same format as DAY as the truncation will work this way. 
https://github.com/user-attachments/assets/c3cfb15f-9da2-4b7b-94ef-6d504b2f0c38

feat: handle quarter filter with new picker

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx
packages/frontend/src/components/Explorer/ResultsCard/ExplorerResultsNonIdealStates.tsx
packages/frontend/src/components/RefreshButton.tsx
packages/frontend/src/components/SimpleChart/index.tsx
packages/frontend/src/components/common/Table/index.tsx
packages/frontend/src/ee/features/embed/EmbedDashboard/components/EmbedDashboardChartTile.tsx
packages/frontend/src/hooks/useQueryResults.ts

Closes: #14672 
This fixes an issue where charts with errors in the query never got out of the loading state. We weren't handling the error status on paginated queries completely. This was especially problematic on dashbaords, because the edit controls were hidden.
To repro the issue, you can add a bad table calculation on the Explore page. You'll see it loads forever:
If you save that chart it will also load forever. 
Now, it shows an error:

fix: show error for visualizations on paginated query error

---

packages/backend/src/controllers/v2/ProjectController.ts
packages/backend/src/ee/index.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/AsyncQueryService/AsyncQueryService.test.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/backend/src/services/AsyncQueryService/types.ts
packages/backend/src/services/ServiceRepository.ts
packages/common/src/types/api/paginatedQuery.ts

Closes: #14626 
- Adds `POST /api/v2/projects/{projectUuid}/query/dashboard-sql-chart` endpoint that returns just the pivoted results of a sql chart (when not table viz)
**Example body**
```json
{
"context": "dashboardView",
"invalidateCache": false,
"savedSqlUuid": "d0cda854-6b6c-41e7-b3d2-dc5cd46ebe42",
"dashboardUuid": "e9d95a07-e5c8-4ea9-8365-e45bc4b47898",
"dashboardFilters": {
"dimensions": [],
"metrics": [],
"tableCalculations": []
},
"dashboardSorts": []
}
```
https://github.com/user-attachments/assets/af826c10-fa93-45ae-b0b7-e712e02be466
test-frontend

feat: add dashboard-sql-chart endpoint that just uses pivoted results

---

packages/backend/src/models/SpaceModel.ts
packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/components/Explorer/SpaceBrowser/SpaceBrowserMenu.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx
packages/frontend/src/components/common/ShareSpaceModal/index.tsx
packages/frontend/src/components/common/SpaceSelector/SpaceCreationForm.tsx
packages/frontend/src/components/common/TransferItemsModal/TransferItemsModal.tsx

Closes: #14719
Improves the UX for moving resources between spaces by:
1. Updating button and menu labels from "Transfer to space" to more intuitive "Move" or "Move [resource type]"
2. Enhancing the transfer modal with clearer messaging that shows resource names in quotes
3. Improving error message when attempting to move a space into one of its own nested spaces
4. Adding proper formatting for space names in quotes throughout the UI

fix: improve UI text for moving resources between spaces

---

packages/backend/src/models/SpaceModel.ts

Closes: 
fix: SpaceModel getUserSpacesAccess method for non-root spaces. non-admin users were not able to see any content in a nested space

fix: SpaceModel getUserSpacesAccess method for non-root spaces

---

packages/frontend/src/hooks/useQueryResults.ts

- Fixes chart stuck in loading when going back to previous query uuid
**Before**
https://github.com/user-attachments/assets/958d1cfd-151a-46c7-9ce4-1794a12a163a
**After**
https://github.com/user-attachments/assets/ca132a0c-4783-4208-af25-b36c09bc6f31

fix: charts stuck in loading when going back to previous useQuery state

---

packages/frontend/src/features/tableCalculation/components/TableCalculationModal.tsx

Closes: #14174 
The issue in this ticket was that downloading a chart with a table calculation with no format included `currency: USD`. It turns out we were always saving table calculations with currency USD if nothing else was specified. 
This makes is so currency is undefined if unspecified. 
To test:
- Create a chart with a table calc an no format
- Save it
- CLI download the chart
- There should be no USD

fix: save table calcs with no currency by default

---

.env.development
docker/docker-compose.dev.yml
packages/backend/src/clients/Aws/S3CacheClient.ts
packages/backend/src/clients/Aws/S3Client.ts
packages/backend/src/config/parseConfig.ts

Closes: #14739 
- Adds MinIO to local dev setup
- Adds `S3_FORCE_PATH_STYLE` setting which is needed by MinIO
- Uses `bitnami/minio` so we can create default buckets: `default` and `results` (official minio doesn't let us do this)
- Minio admin page: `localhost:9001`
SQL Runner results being saved with current config

feat: add minio for local development

---

packages/frontend/src/components/DashboardTabs/Tab.tsx

Uses consistent copy for tab deleting
https://github.com/user-attachments/assets/e2257dd7-ec07-491d-87a7-6dbe24fe1bc8

fix: update copy on dashboard tab delete

---

packages/frontend/src/components/DashboardTabs/index.tsx

Fixes a bug where tiles were not deleted on tab removal

fix: delete tiles on deleted tabs in frontend

---

packages/frontend/src/components/common/SpaceActionModal/DeleteSpaceModal.tsx
packages/frontend/src/components/common/SpaceActionModal/index.tsx

Closes #14770
This feature updates the DeleteSpaceModal component with a new isLoading prop. It also updates the SpaceModal component with a new prop `isLoading`. All children component are going to use this instead of `isDisabled` to display the loading state

feat: Display loading state when deleting a Space

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/Download/ResultsDownloadFromUrl.tsx
packages/frontend/src/features/sqlRunner/components/Header/HeaderEdit.tsx
packages/frontend/src/features/sqlRunner/components/SaveSqlChartModal.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

Closes: #14407 
There are still some limit-related UX questions in the SQL runner, but this is an improvement that specifically solves the stated issue that the SQL runner ALWAYS sends limit=500. 
On the initial SQL page (where limit can't be changed), we now use the `LIGHTDASH_QUERY_DEFAULT_LIMIT` for the query limit and the default results download. 
On the chart page, we now respect the user-input limit
What this *doesn't* address:
- Limits entered in the SQL are still overridden if they are higher than the limit
To test:
- Set `LIGHTDASH_QUERY_DEFAULT_LIMIT` to something other than 500
- Check that the initial query page uses that limit
- Set the limit manually on the chart page and check that that limit is used.

fix: SQL Runner always sends limit 500

---

packages/frontend/src/components/common/ResourceView/InfiniteResourceTable.tsx

Closes: #14782
This PR fixes a bug where the context menu remains active when selecting all rows from a table. This implementation is a temporary workaround (see code comments for details). I'll report this issue to the table library later.

fix: Context menu is active during item selection

---

packages/backend/src/queryBuilder.mock.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/common/src/compiler/exploreCompiler.mock.ts
packages/common/src/types/warehouse.ts
packages/common/src/utils/virtualView.ts
packages/warehouses/src/warehouseClients/WarehouseBaseClient.ts

Relates to: https://github.com/lightdash/lightdash/pull/14758
- After enforcing saving results on all warehouses so that all support async queries, we no longer need the codepath that didn't fetch results on `warehouseClient.executeAsyncQuery`
- Enforce `resultsStreamCallback` since now that will always exist when running an async query
- Always return duration ms and row count

chore: delete code path for not executing the query in warehouse client

---

packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/common/src/types/sqlRunner.ts

Relates to: https://github.com/lightdash/lightdash/pull/14788
- We're using the `sql` directly in `runAsyncQuery` now which means that for sql runner charts and queries we don't need to prefix the pivot configuration anymore
**Before**
**After**

fix: column not exists for sql chart queries

---

packages/backend/src/services/RenameService/RenameService.ts
packages/backend/src/services/RenameService/rename.test.ts
packages/backend/src/services/RenameService/rename.ts

Closes: #XXXX
Small bugfixes for CLI and better validation logs after testing on analytics . UI renaming works as expected
Improves the explore rename functionality by:
1. Fixing how charts are filtered when renaming an explore:
- Now properly handles explore errors during filtering
- Correctly identifies charts that use the explore in joins
- Adds better logging for explore and join filtering
2. Enhances validation for renamed resources:
- Adds resource type ('chart', 'dashboard', 'alert', 'dashboard scheduler') to validation messages
- Makes validation optional for dashboard, alert, and dashboard scheduler renames
- Improves error logging by removing unnecessary formatting that made logs harder to read in GCP
3. Adds a test case for renaming subscriptions in saved chart models

fix: explore rename chart

---

packages/frontend/src/hooks/dashboard/useDashboardChartReadyQuery.ts

The error from the chart query was overwriting the error from the results. I have no repro, but to verify, make sure charts load and charts with errors show errors.

fix: capture either error on use dashboard chart query

---

packages/frontend/src/components/common/ResourceView/InfiniteResourceTable.tsx
packages/frontend/src/components/common/SpaceSelector/SpaceSelector.tsx
packages/frontend/src/components/common/TransferItemsModal/TransferItemsModal.tsx

Closes: #14781  
- Allow bulk move of Spaces into Root Space
- Move to Root Space is disabled when trying to move other items (dashboards and charts)

fix: Cannot bulk move Spaces into top level Space

---

packages/cli/src/dbt/models.ts
packages/cli/src/handlers/dbt/run.ts
packages/cli/src/handlers/generate.ts
packages/cli/src/index.ts

Closes: #14798
Added a new `--preserve-column-case` flag to the `dbt run` and `generate` commands that allows users to maintain the original casing of column names in generated schema files. By default, column names are converted to lowercase, but with this flag enabled, the original case will be preserved.

feat(cli): flag to preserve original casing of column names in generated schema files

---

packages/frontend/src/components/common/ResourceView/InfiniteResourceTable.tsx

Closes: #14784 
- `InfiniteResourceTable`: Disable item navigation when selecting rows in table
- Navigation is still enabled in the item title

fix: Navigation enabled when selecting rows

---

packages/frontend/src/components/UserSettings/AiAgentsPanel/index.tsx
packages/frontend/src/components/UserSettings/SlackSettingsPanel/index.tsx
packages/frontend/src/ee/features/aiCopilot/components/AiAgents.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChannelProjectMappings.tsx
packages/frontend/src/pages/Settings.tsx

Relates to: #14827
- Move Slack channel mappings to /aiAgents route
- Move that form to that section (it will change anyway)
- Only show save changes button if the form is dirty.
**Screenshots with the ai copilot enabled**
**without**

feat: add initial AI agents page

---

packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts

Related to: #14709
Changes:
- move dashboard filter and sort to prepare function
- refactor prepare function arguments so it can be used in `executeAsyncSqlQuery` 
This will allow us to generate/modify the SQL based on dashboard filters in a single place.

chore: refactor and reuse prepareSqlChartAsyncQueryArgs

---

packages/backend/src/clients/Aws/S3CacheClient.ts
packages/backend/src/clients/ResultsFileStorageClients/S3ResultsFileStorageClient.ts
packages/backend/src/controllers/v2/QueryController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/backend/src/services/AsyncQueryService/types.ts
packages/common/src/index.ts

Relates to: [Endpoint to download CSV from query uuid](https://github.com/lightdash/lightdash/issues/14702)
- Adds endpoint to get the results file URL. This is useful for sql runner download since it uses the raw results file and then generates the csv in the frontend: `packages/frontend/src/features/sqlRunner/hooks/useDownloadResults.tsx`
Note: missing columns from the return type, should be available after [Save results columns to query_history table on execution](https://github.com/lightdash/lightdash/issues/14815)

feat: add download results file endpoint

---

packages/backend/src/config/parseConfig.ts

Closes: #N/A
Makes `emailDomain` and `apiKey` optional in the initial setup configuration. Previously, these fields were required, but now they can be undefined if the corresponding environment variables are not set.

fix: required initialize project vars

---

packages/common/src/index.ts
packages/e2e/cypress/e2e/app/sqlRunner.cy.ts
packages/frontend/src/features/queryRunner/pollQueryResults.ts
packages/frontend/src/features/sqlRunner/hooks/useSqlQueryRun.tsx
packages/frontend/src/features/sqlRunner/store/thunks.ts

Relates to: [Update FE Sql tiles to use the new paginated endpoints](https://github.com/lightdash/lightdash/issues/14633)
- Uses new `POST /api/v2/projects/{projectUuid}/query/sql` to fetch results for the sql runner results table
https://github.com/user-attachments/assets/dfe5c80f-3a51-4ae7-91d8-88663a7d9836

chore: fetch sql runner results from new endpoint

---

packages/backend/src/clients/ResultsFileStorageClients/S3ResultsFileStorageClient.ts
packages/common/src/types/warehouse.ts
packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Closes: #14820 
- This was happening because of attempts at handling back pressure which closed the write stream too soon
Removing back pressure handling in favor of letting node handle it fixes the issue
Steps to reproduce:
1. use databricks cluster (this bug shouldn't be tied to it, but we could only reproduce there)
2. Query events, event_id, count
3. Set limit to 500
4. Notice that pagesize will be around 400 when it should be 500 for the first page so the chart doesn't load
test-frontend

fix: results page smaller than actual results

---

packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/backend/src/services/ProjectService/ProjectService.ts

Closes: 
Optimise backend services to only fetch the project summary instead of the entire project.
This should improve the API response time.

chore: get project summary instead of entire project

---

packages/backend/src/queryBuilder.ts
packages/common/src/compiler/translator.ts
packages/common/src/types/filter.ts
packages/common/src/types/filterGrammar.ts
packages/common/src/types/table.ts
packages/common/src/utils/filters.mock.ts
packages/common/src/utils/filters.test.ts
packages/common/src/utils/filters.ts
packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx

Closes: #14807 
- Adds the ability of adding required filters to joined tables fields
On "orders" model add
```yaml
meta:
required_filters:
- status: "completed"
- customers.first_name: "Jane"
```
Recompile project

feat: add required filters for joined tables

---

packages/frontend/src/components/SimpleTable/index.tsx

Closes: #8806
Closes: #8216
Improve error handling when pivot table fails to fetch pivot script. 
Explain problem and provide action to fix it.
Before:
After:

fix: request user to refresh page when worker cant load old pivot script

---

packages/backend/src/ee/clients/Slack/SlackBot.ts
packages/backend/src/ee/database/entities/ai.ts
packages/backend/src/ee/database/entities/aiAgent.ts
packages/backend/src/ee/database/migrations/20250516162139_add_ai_agents_table.ts
packages/backend/src/ee/database/migrations/20250516162927_add_ai_agent_integrations_table.ts
packages/backend/src/ee/database/migrations/20250516163327_add_ai_agent_uuid_to_ai_thread.ts
packages/backend/src/ee/index.ts
packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/ee/models/AiModel.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/ee/services/AiService/AiService.ts
packages/backend/src/ee/services/AiService/utils/errors.ts
packages/backend/src/models/ModelRepository.ts
packages/common/src/ee/Ai/types.ts
packages/common/src/ee/AiAgent/index.ts

Closes: #14847
Add database schema for AI Agents, migrate old slack-first schema
- Creates `ai_agent` table to store agent configurations with name, description, and data sources
- Creates `ai_agent_integration` table to manage integrations (currently supporting Slack)
- Adds `agent_uuid` column to the existing `ai_thread` table
- Includes a migration to convert existing Slack channel mappings to the new agent structure
- Migrations are revertable and do not delete any data
- All the existing features work as expected
Before:
After:

feat: add AI agents database schema and migration

---

packages/frontend/src/features/metricsCatalog/utils/metricExploreFilter.ts

Closes: #14924
For boolean filters we can't just send the operator with empty results, to fix this I kept the logic for operators the same but am overriding them when creating the filter
Before (see ticket)
**After**
Metrics explorer filtering by false
Metrics explorer filtering by true

fix: spotlight inverse boolean

---

packages/backend/src/ee/controllers/aiAgentController.ts
packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/generated/routes.ts
packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx
packages/frontend/src/ee/features/aiCopilot/hooks/useAiAgents.ts

Closes: #XXXX
Added the ability to delete AI agents through a new API endpoint and UI integration. This PR includes:
- New DELETE endpoint for AI agents in the backend controller
- Implementation of the delete functionality in the AI agent model and service
- Frontend mutation hook for deleting agents
- Integration of the delete functionality in the agent details component

feat: allow deleting agents

---

examples/api/ai-agents.http
packages/backend/src/ee/controllers/aiAgentController.ts
packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/common/src/index.ts
packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx
packages/frontend/src/ee/features/aiCopilot/components/ConversationsList.tsx
packages/frontend/src/ee/features/aiCopilot/components/ThreadDetailsModal.tsx
packages/frontend/src/ee/features/aiCopilot/hooks/useAiAgents.ts

Closes: #14831
Implements the AI agent thread endpoints to allow users to view their conversation history with AI agents. This PR adds functionality to:
1. List all threads for a specific AI agent
2. View a specific thread with all messages between the user and the AI agent
- Database queries to retrieve thread summaries and messages
- API endpoints for accessing thread data
- HTTP examples for testing the new endpoints

feat(backend): implement AI agent threads API endpoints

---

packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx

Hide the Conversations tab when creating a new agent.

fix: dont render conversations tab in create mode

---

packages/backend/src/ee/database/entities/aiAgent.ts
packages/backend/src/ee/database/migrations/20250521173353_add_ai_agent_modified_at_column.ts
packages/backend/src/ee/models/AiAgentModel.ts
packages/common/src/ee/AiAgent/index.ts

Related: #14932
- Created a new migration to add the `updated_at` column to the `ai_agent` table
- Updated the `DbAiAgent` type to include the new field
- Modified the `AiAgentTable` type to properly handle the new column in updates
- Updated the agent model to return the timestamps in API responses
- Ensured the `updated_at` field is set when updating an agent
- Added timestamp fields to the agent schema with proper date coercion

feat(backend): updatedAt column for agents

---

packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx

Closes: N/A
Added a TagsInput component to the Agent Details form that allows users to select tags when a project is selected. The component only appears when a project UUID is provided. Updated the form handling to properly manage tag values, setting them to null when empty.

fix: allow tags when project selected

---

packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/index.tsx
packages/frontend/src/components/Explorer/ExploreTree/index.tsx

Relates to: #14638
Removes inlined handlers from some more tree components. This is a code clean-up with along the path to improving perf in the explores page. 
To test it:
- Interact with the tables sidebar
- Select and deselect various dimensions and metrics
- Fitler
- Add custom dimensions and table calcs
- Search
- Creat, edit, delete Virtual View
- Etc. 
- Does everything work
Note that this is a step to improve perf -- it won't be fixed.

chore: remove inline handlers in Explore tree

---

packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/frontend/src/hooks/useBigNumberConfig.ts

Closes: https://github.com/lightdash/lightdash/issues/14696
- Overrides `format` expression instead of adding `formatOptions` from metric query overrides. In formatting logic, `format` expression always takes precedence over `formatOptions` hence why formatting overrides weren't being applied
https://github.com/user-attachments/assets/70ea517c-35f5-464e-933b-351ce04b1893

fix: format overrides for bignumber and results

---

packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/index.tsx
packages/frontend/src/components/Explorer/ExploreTree/index.tsx
packages/frontend/src/providers/Explorer/ExplorerProvider.test.tsx
packages/frontend/src/providers/Explorer/ExplorerProvider.tsx
packages/frontend/src/providers/Explorer/defaultState.ts
packages/frontend/src/providers/__mocks__/explorerTypeMocks.ts

Relates to: #14638 
Add tests for explorer provider reducers. In anticipation of refactoring the reducers, this is meant to make sure they work the same. 
This is largely AI generated and probably not worth deep thought, but let me know if there are concerns.

chore: add tests for ExplorerProvider

---

packages/backend/src/ee/index.ts
packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/ee/services/CommercialSlackIntegrationService.ts
packages/backend/src/services/SlackIntegrationService/SlackIntegrationService.ts

Closes: #14934
Added functionality to delete AI agent Slack integrations when a Slack installation is removed from an organization. This ensures that when a user disconnects Slack from their organization, all related AI agent Slack integrations are properly cleaned up as well.

feat: delete AI agent slack integrations when removing Slack installation

---

packages/frontend/src/providers/Explorer/ExplorerProvider.tsx

Relates to: https://github.com/lightdash/lightdash/issues/14638
Uses immer for Explore Provider reducers. This is necessary to optimize this provider so that it's not creating new objects all the time. 
There are a lot of tests for these reducers now. 
To test manually:
Use the explore as much as possible

chore: use immer for explorer reducers

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/ValidationService/ValidationService.ts
packages/common/src/types/filter.ts
packages/common/src/utils/filters.test.ts
packages/common/src/utils/filters.ts
packages/frontend/src/components/DashboardFilter/FilterConfiguration/TileFilterConfiguration.tsx
packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx

Closes: #14892
Issue one: 
Filters for explorer charts were applied to SQL charts if they have a column name that matched the filter fieldId (eg: orders_status).
Issue two:
Project validation was showing errors when dashboard has filters for SQL charts.
Before
After

fix: project validation when dashboard has filters for SQL charts

---

packages/common/src/index.test.ts
packages/common/src/utils/filters.ts
packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterSettings.tsx
packages/frontend/src/components/DashboardFilter/FilterConfiguration/TileFilterConfiguration.tsx
packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx
packages/frontend/src/components/common/Filters/FilterRuleForm.tsx
packages/frontend/src/features/metricsCatalog/utils/metricExploreFilter.ts
packages/frontend/src/providers/Dashboard/types.ts

Related to: https://github.com/lightdash/lightdash/issues/14969
This PR updates the SQL chart tile metadata to include column type information. Previously, only column references were stored, but now we're storing both the reference and type for each column. This change ensures that dashboard filters have access to the correct column type information when configuring filters.
Key changes:
- Updated `SqlChartTileMetadata` type to store `ResultColumn` objects (with reference and type) instead of just strings
- Modified `DashboardSqlChartTile` to extract both reference and type from query dimensions
- Updated filter configuration components to properly access column references from the new metadata structure

chore: update SQL chart column metadata to include type information

---

packages/frontend/src/components/DashboardFilter/Filter.tsx
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx
packages/frontend/src/components/common/Filters/FilterInputs/utils.test.ts
packages/frontend/src/components/common/Filters/FilterInputs/utils.ts
packages/frontend/src/components/common/PivotTable/index.tsx
packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
packages/frontend/src/ee/features/embed/SettingsEmbed/EmbedFiltersInteractivity.tsx
packages/frontend/src/features/scheduler/components/SchedulerFilters.tsx
packages/frontend/src/providers/Dashboard/DashboardProvider.tsx

Related to: https://github.com/lightdash/lightdash/issues/14969
Refactored the filter label utility functions to improve code organization and testability:
1. Renamed `getConditionalRuleLabel` to `getConditionalRuleLabelFromItem` for clarity
2. Created a new base function `getConditionalRuleLabel` that accepts primitive parameters instead of a field item
3. Added comprehensive unit tests for both functions to ensure correct behavior
This change makes the filter label generation more flexible and easier to test, while maintaining backward compatibility through the renamed function.

refactor: rename getConditionalRuleLabel to getConditionalRuleLabelFromItem and add tests

---

packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx

Fixes a `key` warning in the virtual table. I saw this and thought I should investigate. 
It was harmless--just in the loading state, but I thought I'd fix it to reduce warnings.

chore: fix key warning in virtual table

---

packages/common/src/utils/filters.ts
packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
packages/frontend/src/components/DashboardFilter/Filter.tsx
packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterSettings.tsx
packages/frontend/src/components/DashboardFilter/FilterConfiguration/TileFilterConfiguration.tsx
packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx

Closes: [#14969](https://github.com/lightdash/lightdash/issues/14969)
Note: feature is behind feature flag for now
Main changes:
- Adapt filter components to not expect a `field`
- Show columns dropdown
- Show active SQL filters
- Support temporary SQL filters

feat: filter by SQL column

---

packages/backend/src/services/SavedChartsService/SavedChartService.ts

Closes: 
Fix chart type tracking for complex mark types in saved charts. Previously, when a chart's mark was an object rather than a simple string, it would be displayed as "[object Object]". Now, complex mark types are properly stringified to capture their full structure in analytics.

fix: handle object mark type in chart config

---

packages/backend/src/clients/Slack/SlackClient.ts
packages/backend/src/ee/index.ts
packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/common/src/ee/AiAgent/index.ts
packages/frontend/src/ee/features/aiCopilot/components/ThreadDetailsModal.tsx

Closes: #14978
Added Slack user profile information to AI Copilot threads. This enhancement retrieves user profile details (name and image) from Slack when displaying thread messages, ensuring that messages from Slack users show their actual names rather than generic identifiers.

feat: For slack based agent threads correctly show message author name

---

packages/frontend/src/components/Explorer/CustomMetricModal/index.tsx

Memo-ize internal props in create custom metric modal. Especially `getFilterableDimensionsFromItemsMap`, which is really heavy. 
This doesn't have a big impact on page perf, but it makes a big difference for that dialog being sluggish. 
Also just moves some hooks to group related ones.

chore: memoize custom metric modal props

---

examples/full-jaffle-shop-demo/dbt/models/events.yml
packages/backend/src/ee/services/AiAgentService.test.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/ee/services/AiService/AiService.ts
packages/backend/src/ee/services/AiService/tools/findFieldsTool.ts
packages/backend/src/ee/services/AiService/tools/generateQueryFilters.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/ContentService/ContentService.ts
packages/backend/src/services/SemanticLayerService/SemanticLayerService.ts
packages/backend/src/services/ServiceRepository.ts
packages/common/src/ee/AiAgent/filterExploreByTags.test.ts
packages/common/src/ee/AiAgent/filterExploreByTags.ts
packages/common/src/ee/AiAgent/index.ts

Closes: https://github.com/lightdash/lightdash/issues/14879
No tags are configured in settings UI:
| Tagging Scenario                  | AI Visibility                    |
|-----------------------------------|----------------------------------|
| No tags configured in settings UI | Everything is visible by default |
---
Tags are configured in settings UI:
| Tagging Scenario                     | AI Visibility               |
|--------------------------------------|-----------------------------|
| Explore only (with matching tag)     | All fields in the Explore   |
| Some fields only (with matching tag) | Only those tagged fields    |
| Explore + some fields (with match)   | Only those tagged fields    |
| No matching tags                     | Nothing is visible          |

feat: implement AI tag filtering for explore visibility

---

examples/api/ai-agents.http
packages/backend/src/ee/controllers/aiAgentController.ts
packages/backend/src/ee/index.ts
packages/backend/src/ee/scheduler/SchedulerClient.ts
packages/backend/src/ee/scheduler/SchedulerWorker.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/ee/services/AiService/AiService.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/scheduler/SchedulerTaskTracer.ts
packages/common/src/ee/Ai/types.ts
packages/common/src/ee/AiAgent/index.ts
packages/common/src/types/schedulerTaskList.ts

Closes: #15041
This PR adds new API endpoints to support AI agent thread generation. It introduces two new endpoints:
- `POST /api/v1/aiAgents/{agentUuid}/generate` to start a new agent thread with an initial prompt
- `POST /api/v1/aiAgents/{agentUuid}/threads/{threadUuid}/generate` to generate a response in an existing thread

feat(backend): add AI agent thread generation endpoints

---

packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts

Closes: #15076
We were not picking up the limit for saved SQL charts, so the results could look wildly different than in edit mode. This uses the saved limit. 
To test:
- Make a new SQL chart from the `events` table
- group by 'event'
- Save the chart
- The saved version should look the same
- Before this fix the saved version was very different (see the ticket)
Here's an example of the fixed version working with different limits

fix: use the correct limit for SQL-charts

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/frontend/src/components/common/LinkButton.tsx
packages/frontend/src/ee/CommercialRoutes.tsx
packages/frontend/src/ee/pages/AiAgents/AgentConversationListPage.tsx
packages/frontend/src/ee/pages/AiAgents/AgentConversationPage.tsx
packages/frontend/src/ee/pages/AiAgents/AgentPage.tsx
packages/frontend/src/ee/pages/AiAgents/AgentsListPage.tsx

Closes: #15051
Added AI Agents UI with new routes and pages for viewing agents and their threads.
- New route structure for AI agents under `/projects/:projectUuid/ai/agents/`
- Agent list page showing all available agents 
- Agent details page with information
- Thread listing page for each agent
- Individual thread view page

feat: New Agents page structure

---

packages/backend/src/ee/services/AiService/AiService.ts

Fixed agent settings retrieval when handling Slack or web app prompts. Before we were only getting agent settings from Slack channel prompts.

fix: system prompts not working for web ui

---

packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx
packages/frontend/src/ee/features/aiCopilot/components/SlackIntegrationSteps.tsx

Closes: #14976
Added a Slack integration stepper component to improve the user experience when connecting AI agents to Slack:
1. Allow Integration access - Prompts users to connect their Slack account to Lightdash
2. Select Channels - Guides users to select channels for the agent
3. Start Using Agent - Instructs users on how to interact with the agent in Slack
Responsiveness is not good 😬 as you can see the steps move around to make space to fit in one line

feat: Add Slack integration steps UI for AI agents

---

packages/backend/src/database/migrations/20250529000000_make_cache_key_non_nullable.ts

Reordered the migration steps for the `cache_key` column in the `query_history` table to ensure proper execution:
1. First create the index on the `cache_key` column
2. Then update null values to 'n/a'
3. Finally make the column non-nullable
This ordering prevents potential issues that could occur if we tried to create an index after making the column non-nullable.

fix: reorder migration steps to index cache_key before making it non-nullable

---

packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/common/src/authorization/organizationMemberAbility.ts
packages/common/src/authorization/types.ts

- Added permission checks in `AiAgentService` for viewing and creating threads
- Defined CASL abilities for AI agent threads in organization member roles

feat: add user permissions for AI agent threads

---

examples/api/ai-agents.http
packages/backend/src/ee/services/AiAgentService.ts
packages/common/src/authorization/organizationMemberAbility.ts
packages/common/src/authorization/types.ts
packages/frontend/src/ee/pages/AiAgents/AgentPage.tsx
packages/frontend/src/ee/pages/AiAgents/AgentsListPage.tsx
packages/frontend/src/pages/Settings.tsx

Closes: #15136
Added permission checks for AI Agent management. Now only users with the appropriate permissions can create, update, or delete AI agents. The permissions are enforced both on the backend and frontend:
- Added 'AiAgent' to CASL subject names and rules
- Implemented permission checks in AiAgentService for create, update, and delete operations

feat: add permission checks for AI Agent management

---

packages/backend/src/ee/index.ts
packages/backend/src/ee/services/EmbedService/EmbedService.ts

Added organization model to the EmbedService dependencies to properly check if embedding feature is enabled. The `isFeatureEnabled` method now retrieves the organization details to include the organization name when checking feature flags

fix: embed feature flag check

---

packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/ee/AiAgent/index.ts
packages/frontend/src/ee/features/aiCopilot/components/AgentDetails.tsx
packages/frontend/src/ee/features/aiCopilot/components/AiAgents.tsx
packages/frontend/src/ee/pages/AiAgents/AgentPage.tsx
packages/frontend/src/ee/pages/AiAgents/AgentsListPage.tsx

Closes: #15149
Users can provide an image URL when creating or updating an agent, which will be displayed in the agent list, agent details page, and in conversations. If no image URL is provided, the system will continue to use the default avatar based on the agent's name.
- Adding `imageUrl` field to the AI agent model and database
- Updating the agent creation and editing forms with a new image URL input field
- Displaying the custom images in all relevant UI components
- Adding validation to ensure the image URL is properly formatted

feat: allow changing agents avatar

---

packages/frontend/src/components/NavBar/BrowseMenu.tsx
packages/frontend/src/ee/CommercialRoutes.tsx
packages/frontend/src/ee/features/aiCopilot/hooks/useAiAgents.ts
packages/frontend/src/ee/pages/AiAgents/AgentPage.tsx
packages/frontend/src/ee/pages/AiAgents/AgentsListPage.tsx

Closes: #15137
Updated URL paths for AI Agents from `/aiAgents` to `/ai-agents` to follow kebab-case convention. This includes:
- Updated navigation links in the BrowseMenu component
- Added a redirect from `/aiAgents` to `/ai-agents` in CommercialRoutes (temporary)
- Updated all internal navigation paths in useAiAgents hook, AgentPage, and AgentsListPage

chore: change /aiAgents to /ai-agents

---

packages/frontend/src/components/Explorer/CustomMetricModal/index.tsx

Closes: #15097
Fix custom metric format options by creating a new object when setting the format field value. This prevents potential reference issues by ensuring we're not directly modifying the original object.

fix: clone formatOptions when setting field value

---

packages/e2e/cypress/e2e/app/createProjects.cy.ts

Closes:  
Fixes bigquery e2e 
before:
after
Updated the BigQuery warehouse authentication type selection in the E2E tests from "Private Key" to "Service Account (JSON key file)" to match the current UI options.

fix: update BigQuery authentication type label

---

packages/backend/src/controllers/v2/QueryController.ts
packages/backend/src/ee/index.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/AsyncQueryService/AsyncQueryService.test.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/backend/src/services/AsyncQueryService/types.ts
packages/backend/src/services/CsvService/CsvService.ts
packages/backend/src/services/ExcelService/ExcelService.ts
packages/backend/src/services/ServiceRepository.ts
packages/common/src/index.ts
packages/common/src/types/api/paginatedQuery.ts
packages/common/src/types/downloadFile.ts
packages/common/src/utils/fileDownloadLimit.ts
packages/e2e/cypress/e2e/app/downloadCsv.cy.ts
packages/frontend/src/components/Explorer/ResultsCard/ResultsCard.tsx
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
packages/frontend/src/components/ExportResults/index.tsx
packages/frontend/src/components/ExportSelector/index.tsx
packages/frontend/src/components/common/ChartDownload/ChartDownloadMenu.tsx
packages/frontend/src/components/common/ChartDownload/chartDownloadUtils.ts
packages/frontend/src/components/common/Page/Sidebar.tsx
packages/frontend/src/features/queryRunner/executeQuery.ts
packages/frontend/src/hooks/useQueryResults.ts
packages/frontend/src/providers/Explorer/ExplorerProvider.tsx
packages/frontend/src/providers/Explorer/types.ts

Closes: #15012 
Closes: [#15014](https://github.com/lightdash/lightdash/issues/15014)
Refactored the export functionality to improve the user experience and code organization. This PR:
- Created a new `ExportResults` component that replaces the old `ExportCSV` component
- Added support for XLSX file exports alongside CSV
- Improved the UI with better segmented controls for export options
- Centralized the download logic through a new `getDownloadQueryUuid` method
- Removed duplicate code for CSV generation across different components
- Enhanced error handling and user feedback during the export process
- Updated the download button label to be more descriptive ("Download data" instead of "csv")
The new export UI provides clearer options for users to select file format, value formatting, …

feat: add XLSX download option in explores page

---

packages/backend/src/ee/models/AiModel.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/ee/services/AiService/AiService.ts

Closes: #15190
Added a dedicated `updateHumanScore` method to properly handle scores without the need to update the whole response (including dates).

fix: Giving feedback updates the response time

---

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatBubbles.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/DotsLoader/DotsLoader.module.css
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/DotsLoader/DotsLoader.tsx
packages/frontend/src/ee/pages/AiAgents/AgentPage.tsx
packages/frontend/src/ee/pages/AiAgents/AgentThreadPage.tsx
packages/frontend/src/mantine8Theme.ts

Closes: #15133
Improved loading states in AI Agent chat with a new dots loader component + other small improvements:
- Added new Loader type: `dots` using Mantine theme
- The component allows passing a custom 'delayedMessage' that will render if the loader is for running for longer than 8s
- Improved error states for visualization generation failures
- Improved Assistant bubble action button styling and layout
<details><summary>Screenshots</summary>
[Screen Recording 2025-06-05 at 16.55.57.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/HorFj8gm8QUuuIDE2vgk/b83b6330-259e-4626-887b-87c79c2c4036.mov" />](https://app.graphite.dev/media/video/HorFj8gm8QUuuIDE2vgk/b83b6330-259e-4626-887 …

feat: Improve AI Agent loading states

---

packages/frontend/src/components/DashboardTabs/index.tsx
packages/frontend/src/components/DashboardTiles/TileBase/index.tsx

Closes: #13111
Some simple styling changes to dashboard tabs:
1. Adds space between tabs by default—this is similar to the spacing in editMode
2. Reduces space between top charts and tab bottom
3. Remove the stroke under the active tab, although...
4. Sets the canvas background to gray (the default for no tabs) which creates a separation with the active tab

feat: improve dashboard tab styling (spacing and colors)

---

packages/frontend/src/components/DashboardTabs/index.tsx
packages/frontend/src/pages/Dashboard.tsx

Closes: #15200
This is a UX improvement where we only show tabs if there is more than one. There's no reason to have a single tab, since we have just one dashboard.
When exiting tab mode from having one tab, we keep that tab in the database. For now that means a user cannot delete the final tab so that we keep the tab name. Maybe this isn't all that important and we can revist later.

feat: exit tab mode if we're down to a single tab

---

packages/backend/src/ee/models/CommercialFeatureFlagModel.ts
packages/common/src/ee/commercialFeatureFlags.ts
packages/frontend/src/components/NavBar/AiAgentsButton.tsx
packages/frontend/src/components/NavBar/MainNavBarContent.tsx

Added a new AI Agent feature flag and implemented proper permission checks for the AI Agents button in the navigation bar. The button will now only be displayed if:
1. The user has the ability to view AI Agents
2. The AI Copilot feature flag is enabled
3. The new AI Agent feature flag is enabled
This ensures the AI Agents functionality is only accessible to users with appropriate permissions and when the required features are enabled.

fix: Show `Ask AI` button only to users who can manage Agents

---

packages/backend/src/services/CsvService/CsvService.ts

Closes: #15222
Automatic pipeline management would choke, so we've introduced a bit of control.
```
pipeline(readStream, rowTransformer, stringifier, writeStream, callback)
```
```
stringifier.pipe(writeStream)  // Simple direct pipe
pipeline(readStream, rowTransformer, callback)  // Simple 2-stream pipeline
stringifier.write(csvRow)  // Direct calls from transform
stringifier.end()  // Explicit control
```
The main issue was `stringifier.end()` not being called, assuming because of backpressure, so now we do it manually [here](https://github.com/lightdash/lightdash/pull/15225/files#diff-43e0d90f35a0e1c918ae55ecee8fbd5cdef887ffd35e40ec0d2248b374c854e7R313) and [here](https://github.com/lightdash/lightdash/pull/15225/files#diff-43e0d90f35a0e1c918ae55ecee8fbd5cdef887ffd35e40ec0d2248b374c854e …

fix: csv streaming pipeline simplification

---

packages/frontend/src/components/Explorer/CustomDimensionModal/CustomBinDimensionModal.tsx

Closes: #15232
Reproduction of the bug: https://cln.sh/XznG4TYv
Fixed a bug in the CustomBinDimensionModal component by using lodash's cloneDeep when setting the binConfig.customRange field value.

fix: custom range breaking custom dimension form

---

packages/backend/src/ee/services/AiAgentService.ts
packages/frontend/src/ee/features/aiCopilot/utils/getChartVisualizationFromAiQuery.ts

Closes: #15219
tldr;
mismatch between the `xAxis.data` 
```
"2018-01-01T00:00:00Z"
"2018-03-26T00:00:00Z"
```
and the `dataset.source` date formats:
```
"2018-01-01T00:00:00.000Z"  
"2018-03-25T23:00:00.000Z"
```
Refactored AI agent query execution to use `runExploreQuery` instead of `runMetricQuery` in the backend service. This simplifies the API call by passing parameters directly rather than using a complex object structure.
In the frontend, improved the chart visualization generation from AI queries by:
- Using default state for metric query properties
- Simplifying results data handling
- Properly passing fields to the visualization provider
- Adding itemsMap to the returned props

fix: get explore query rows on ai agent service

---

packages/common/src/types/featureFlags.ts
packages/e2e/cypress/e2e/app/createProjects.cy.ts
packages/frontend/src/components/ProjectConnection/WarehouseForms/BigQueryForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/defaultValues.ts

Closes: #XXXX
Added a feature flag `BigquerySSO` to control the availability of SSO authentication for BigQuery connections. When the flag is disabled, the UI will only show the service account authentication option and set it as the default. This allows for controlled rollout of the SSO functionality.
- Added a new feature flag `BigquerySSO` in featureFlags.ts
- Modified BigQueryForm to conditionally render SSO-related UI components based on the flag
- Changed the default authentication type to PRIVATE_KEY in defaultValues.ts
- Added flag checks before making BigQuery dataset API calls

fix: add BigQuery SSO feature flag

---

packages/backend/src/controllers/authentication/strategies/snowflakeStrategy.ts
packages/backend/src/ee/controllers/snowflakeController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/HealthService/HealthService.ts

Closes:  https://github.com/lightdash/lightdash-internal-work/issues/3448
This PR moves the Snowflake controller to the Enterprise Edition (EE) directory and adds license validation for Snowflake authentication. The changes include:
1. Moving `snowflakeController.ts` from `controllers/` to `ee/controllers/`
2. Adding license validation checks in both the Snowflake controller and strategy
3. Updating the health service to only show Snowflake as enabled when both client ID and license key are present
These changes ensure that Snowflake authentication is properly gated behind an Enterprise license.

chore: move snowflake controller to enterprise edition

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/services/ProjectService/ProjectService.ts

[Screencast from 2025-06-10 08-46-06.webm](https://github.com/user-attachments/assets/c6011530-1e14-4743-ac56-4a1b8d4676e9)
[Screencast from 2025-06-10 08-49-57.webm](https://github.com/user-attachments/assets/15ac57ca-f654-4abc-b57c-37c569701500)
Closes:  https://github.com/lightdash/lightdash-internal-work/issues/3444
Added authentication type and user credentials tracking to project analytics events. Created a reusable `getAnalyticProperties` method to standardize analytics data collection across project creation and update flows. This ensures consistent tracking of warehouse authentication methods and user credential requirements.

chore: add authentication tracking to project analytics

---

packages/e2e/cypress/e2e/app/downloadCsv.cy.ts
packages/e2e/cypress/e2e/app/embed.cy.ts
packages/frontend/src/api/csv.ts
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/DashboardTiles/DashboardMinimalDownloadCsv.tsx
packages/frontend/src/components/ExportResults/index.tsx
packages/frontend/src/hooks/dashboard/useDashboardChartReadyQuery.ts

Closes: #15015
Extending the new /download endpoint onto dashboard chart tiles.
| menu | download option  |
|:-:|:-:|
| ![Screenshot 2025-06-09 at 21.20.02.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/yF4RSYW2o5tuXO8E416G/fbaede4a-94f0-4c67-9e22-19e4a0fff9ae.png)  | ![Screenshot 2025-06-09 at 21.20.07.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/yF4RSYW2o5tuXO8E416G/a62e89c0-0053-4ff3-9366-46350737a0a1.png) |
| menu | download option  |
|:-:|:-:|
| ![Screenshot 2025-06-09 at 21.20.15.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/yF4RSYW2o5tuXO8E416G/48ae323f-a64e-47ef-9ef9-e2a8ce848754.png) | ![Screenshot 2025-06-09 at 21.20.19.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/yF4RSYW2o5tuXO8E416G/dac021c2-39d4-4e02- …

feat: dashboard chart tile data download

---

packages/backend/src/ee/controllers/aiAgentController.ts
packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/frontend/src/components/NavBar/AiAgentsButton.tsx
packages/frontend/src/components/UserSettings/AiAgentsPanel/index.tsx
packages/frontend/src/ee/CommercialRoutes.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatBubbles.tsx
packages/frontend/src/ee/features/aiCopilot/components/ConversationsList.tsx
packages/frontend/src/ee/features/aiCopilot/components/OrganizationAiAgent.tsx
packages/frontend/src/ee/features/aiCopilot/components/OrganizationAiAgents.tsx
packages/frontend/src/ee/features/aiCopilot/components/ThreadDetailsModal.tsx
packages/frontend/src/ee/features/aiCopilot/hooks/useOrganizationAiAgents.ts
packages/frontend/src/ee/features/aiCopilot/hooks/useProjectAiAgents.ts
packages/frontend/src/ee/pages/AiAgents/AgentPage.tsx
packages/frontend/src/ee/pages/AiAgents/AgentThreadPage.tsx
packages/frontend/src/ee/pages/AiAgents/AgentsListPage.tsx
packages/frontend/src/ee/pages/AiAgents/AiAgentNewThreadPage.tsx
packages/frontend/src/pages/Settings.tsx

Closes: #15246
This PR adds project-specific AI agents endpoints and UI. It introduces a new endpoints in `AiAgentController` to fetch AI agents scoped to a specific project. The UI has been updated to use project-specific routes for AI agents, changing from `/ai-agents` to `/projects/{projectUuid}/ai-agents`.
- New API endpoints for listing and getting project-specific AI agents
- Updated model and service layers to support filtering agents by project UUID
- Refactored frontend hooks to separate organization-wide and project-specific AI agent operations
- Updated navigation and routing to use project-scoped paths for AI agents

feat: show agents only in project

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/types/filter.ts
packages/common/src/utils/filters.ts
packages/frontend/src/components/DashboardFilter/ActiveFilters/Filter.tsx
packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx

Closes: #15161
Before:
After:
Added support for fallback type in dashboard filter targets to improve filter handling when fields or columns are not immediately available. This allows filters to function properly even when the underlying data structure is still loading or when using SQL columns.
Key changes:
- Added `fallbackType` property to `DashboardFieldTarget` to infer filter types when fields/columns aren't available
- Improved filter display logic to use fallback types when needed
- Fixed filter configuration to properly handle cases where field data is still loading
- Reordered some type definitions for better organization

fix: required dashboard filters for SQL charts

---

packages/frontend/src/ee/features/aiCopilot/hooks/useOrganizationAiAgents.ts

Optimistically track user feedback on Agent responses.
I was testing this in production today and seemed quite slow
Before:
After:

feat: optimistically track user feedback on Agent responses

---

packages/backend/src/services/CsvService/CsvService.ts

Closes: #10214 
For the new /download endpoint, we're using `stringify` from csv-stringify package, which supported `bom: true` param in order to fix the UTF-8 BOM issue.

fix: pass bom: true to stringify

---

packages/backend/src/services/CsvService/CsvService.ts

Closes: an issue with memory leak while stringifying the CSV.
There was an error like `MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [PassThrough]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit` -- potentially causing:
- Multiple identical listeners executing the same resume() call
- Wasted CPU cycles processing redundant event handlers
- Memory pressure from accumulated closures
This was also observed on the backend memory usage monitor.
With this fix we ensure:
- Only 1 drain listener exists at any time per stream
- Listeners are properly cleaned up after use
- Memory usage remains constant regardless of file size

fix: waiting for drain

---

packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/common/src/constants/sqlRunner.ts
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/hooks/useSavedSqlChartResults.tsx
packages/frontend/src/hooks/useQueryResults.ts

Closes: an issue for client with Redshift, trying to execute an "all results" query and fails -- most likely due to the limit being set to `Number.MAX_SAFE_INTEGER`, which is too high for Redshift.
Using max 32-bit signed integer instead - 2_147_483_647.

fix: use a max 32-bit signed integer for all results queries

---

packages/frontend/src/hooks/dashboard/useDashboardChartReadyQuery.ts

Closes: #15272
Dashboard refresh button wasn't sending the right invalidateCache value, so charts weren't being updated. 
There were a couple issues with refetching charts lately and we had, then removed this from the query key. Putting it back there fixes this issue and I have verified that both other issues are still fixed too. 1) Charts don't double fetch, 2) SQL charts do refetch. Here's some videos. 
Here is the point of this ticket -- the refresh button refreshes the cache:
An explore chart does not double fetch:
A sql chart fetches once as well:

fix: correctly send invalidate cache on refresh

---

packages/backend/src/services/OrganizationService/OrganizationService.ts

Closes:  https://github.com/lightdash/lightdash/issues/15268
> export LD_SETUP_DBT_VERSION='v1.8'
Use the dbt version specified in the project setup configuration instead of always defaulting to the latest version when creating a new project. This ensures that projects are created with the intended dbt version rather than automatically using the latest.

fix: use project's dbtVersion instead of hardcoded latest

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/ExportCSV/index.tsx
packages/frontend/src/components/ExportResults/index.tsx

Closes: #15265
If we wrap ExportResults in a modal, we can pass `renderDialogActions` to render appropriate footer:

feat: make ExportResults component wrappable in a modal

---

packages/backend/src/services/CsvService/CsvService.ts
packages/frontend/src/components/DashboardTiles/DashboardMinimalDownloadCsv.tsx

Closes: #10214 
This PR updates the CSV export functionality to include a UTF-8 BOM at the beginning of exported files. This ensures proper character rendering—especially for non-Latin scripts like Japanese—when opening CSVs in Microsoft Excel, which otherwise fails to correctly interpret UTF-8 encoding.
Before:
After:

feat: add UTF-8 BOM support to CSV exports

---

packages/backend/src/App.ts
packages/backend/src/clients/EmailClient/EmailClient.ts
packages/backend/src/clients/EmailClient/templates/genericNotification.html
packages/backend/src/ee/repl/index.ts
packages/backend/src/ee/repl/scripts/fixDuplicateSlugs.ts

This PR adds a generic notification email template and functionality to support sending email reports with CSV attachments. It includes:
1. A new `getClients()` method in the App class to access client instances
2. A `canSendEmail()` method to check if the email client is properly configured
3. A new `sendGenericNotificationEmail()` method in EmailClient to send customizable notifications
4. A generic HTML email template that supports markdown content and tables
5. Enhanced the `fixDuplicateChartSlugs` script to generate CSV reports and send email notifications
These changes enable administrators to receive detailed reports when chart slugs are updated, with the option to include CSV attachments containing the changes made.

feat: add generic notification email and email reporting for slug fixes

---

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatDisplay.tsx

Added an ErrorBoundary component around the AssistantBubble in the AgentChatDisplay component to prevent the entire chat interface from crashing if there's an error rendering an assistant message.

fix: Add ErrorBoundary to AssistantBubble component

---

packages/backend/src/services/UnfurlService/UnfurlService.ts

Closes: #15102
Fix a bug in the UnfurlService where the expected number of paginated responses for dashboard screenshots was incorrectly using `chartTileUuids` instead of `nonNullChartTileUuids`. This ensures that the service correctly tracks the expected number of responses when generating dashboard screenshots.
relevant logs that confirm this theory
> INFO ... Dashboard screenshot: 14 non-null chart tiles out of 16 total tiles
> INFO ... Dashboard screenshot: Expecting 16 paginated responses
> INFO ... Waiting for 16 paginated responses with timeout 2880000ms
☝️ should be waiting for 14

fix: wait for non-null charts' responses

---

packages/frontend/src/hooks/toaster/useToaster.tsx

I hit the edge case where the apiError is undefined, added null checks for apiError properties in ApiErrorDisplay component to prevent potential runtime errors when accessing properties of undefined objects.

fix: add null checks to apiError properties in ApiErrorDisplay

---

packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Closes: 
Fix Snowflake authentication logic to allow private key authentication when password is not provided. This change ensures that private key authentication works correctly even when the authenticationType is not explicitly set to 'private_key', as long as a privateKey is provided and no password is specified.

fix: allow Snowflake private key auth without password

---

packages/backend/src/queryBuilder.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts

Closes: #15414 
- Applies same limits as the chart view, previously it was just passing undefined
- Changes the order in which comments and semi-colons are stripped out from the sql since it was causing a semi-colon to remain if there was a comment after it
**Before**
```sql
WITH original_query AS (SELECT
"event_id" AS "event_id",
"timestamp_tz" AS "timestamp_tz",
"timestamp_ntz" AS "timestamp_ntz",
"timestamp_ltz" AS "timestamp_ltz",
"date" AS "date",
"event" AS "event"
FROM (
SELECT * FROM "postgres"."jaffle"."events";
) AS "sql_query"), group_by_query AS (SELECT "event", sum("event_id") AS "event_id_sum" FROM original_query group by "event")
SELECT * FROM group_by_query  LIMIT 500 
```
**After**
```sql
WITH original_query AS (SELECT
"event_id" AS "event_id",
"timestamp_tz" AS …
```

fix: apply chart limit to dashboard sql chart and fix remove comments and strip semi-colons when there's no limit

---

packages/frontend/src/ee/CommercialRoutes.tsx
packages/frontend/src/ee/pages/AiAgents/AgentsRedirect.tsx

This change makes it easier to create direct links to the AI Agents feature without requiring a specific project UUID in the URL.
Added a redirect page for AI Agents to improve navigation. This change makes it easier to create direct links to the AI Agents without the need of knowing project uuid.
When users access `/ai-agents/`, they will now be automatically redirected to their default project's AI agents page if they have the necessary permissions. If they lack permissions, they'll be redirected to the projects page with a toast

feat: New  ai-agents redirect route

---

packages/backend/src/clients/ResultsFileStorageClients/S3ResultsFileStorageClient.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/backend/src/services/CsvService/CsvService.ts
packages/backend/src/services/ExcelService/ExcelService.ts
packages/backend/src/utils/FileDownloadUtils.ts

Closes: potential memory leak & heap overflow, as we were re-using a static method meant for pivot table export for non-pivot one. For both CSV and XLSX.
- Rethink the streaming approach
- Eliminate manual handling of the stream
- Use proper streaming for non-pivot CSV tables
- Use proper streaming for non-pivot XLSX tables, bridging with a temp file, otherwise the automatic pipeline cannot evenly handle the backpressure between reading JSONL, generating XLSX and streaming upload to s3.
Supports millions of rows for CSV and at least 1 million for XLSX, no matter the amount of columns (to an extend with current `--max-old-space-size=1024`).

feat: proper streaming for csv & xlsx

---

packages/backend/src/ee/controllers/aiAgentUserPreferencesController.ts
packages/backend/src/ee/database/entities/aiAgentUserPreferences.ts
packages/backend/src/ee/database/migrations/20250617135333_add_ai_agent_user_project_preferences_table.ts
packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/ee/AiAgent/index.ts

This PR adds user preferences for AI agents. This will be used to allow users to set and retrieve their default agent for a project. I decided to introduce a specialized agent user preferences table as this is an EE feature, and didn't want to expose that configuration table to other users/customers
- New database table `ai_agent_user_preferences` to store user preferences
- API endpoints to get and set the default agent:
- GET `/api/v1/projects/:projectUuid/aiAgents/preferences`
- POST `/api/v1/projects/:projectUuid/aiAgents/preferences` with `{ defaultAgentUuid: string }` body
I'll use these methods in a follow up PR to update the current logic relying on LocalStorage (to fix #15386)

feat: Introduce ai agent user project preferences table

---

packages/backend/src/ee/controllers/scimOrganizationAccessTokenController.ts
packages/backend/src/ee/controllers/serviceAccountsController.ts
packages/backend/src/ee/models/ServiceAccountModel.ts
packages/backend/src/ee/services/ServiceAccountService/ServiceAccountService.ts
packages/backend/src/models/DashboardModel/PersonalAccessTokenModel.ts
packages/cli/package.json
packages/cli/src/config.ts
packages/cli/src/handlers/dbt/apiClient.ts
packages/cli/src/handlers/login.ts
packages/cli/src/handlers/utils.ts
packages/cli/src/index.ts
packages/common/src/index.ts
packages/common/src/types/auth.ts
pnpm-lock.yaml

Closes: #N/A
Adds prefixes to Service Account tokens and Personal Access tokens.
Introduces an `AuthTokenPrefix` enum to standardize token prefixes across the application. This replaces hardcoded string prefixes with the enum values for SCIM tokens (`scim_`), service account tokens (`ldsvc_`), and personal access tokens (`ldpat_`).

feat: add prefixes for PATs and ServiceAccount tokens

---

packages/frontend/src/features/sqlRunner/components/SqlEditor.tsx
packages/frontend/src/features/sqlRunner/hooks/useDetectedTableFields.tsx
packages/frontend/src/features/sqlRunner/hooks/useMultipleTableFields.tsx
packages/frontend/src/features/sqlRunner/hooks/useTableFields.tsx

Closes: #15437
Enhanced SQL editor autocomplete with column suggestions. The editor now detects tables in the SQL query and provides intelligent field suggestions with type information alongside table suggestions.
Key improvements:
- Added column autocomplete with data types in the SQL editor
- Implemented detection of table references in SQL queries
- Created new hooks to fetch and manage field data for multiple tables
- Prioritized field suggestions over table suggestions in the autocomplete dropdown
- Added context information to show which table/schema a field belongs to
> [!IMPORTANT]
> we never had field suggestions 
To try it out: 
type `e` or `o` to get autocomplete of the orders and/or events table
then whenever you type another character you get the fields both tables have, …

feat: improve sql runner completion

---

packages/warehouses/src/utils/processPromisesInBatches.ts
packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
packages/warehouses/src/warehouseClients/TrinoWarehouseClient.ts

Performs catalog requests in batches instead of using `Promise.all`
Internal thread: https://lightdash.slack.com/archives/C03MCQ08UKS/p1749567281085269
test-frontend
test-backend
test-cli

fix: perform getCatalog requests in batches

---

packages/backend/src/ee/models/CommercialFeatureFlagModel.ts

Closes: N/A
Similar to: https://github.com/lightdash/lightdash/pull/15148
Added `organizationName` to the user context in `CommercialFeatureFlagModel` when tracking feature flag usage. This ensures that organization name data is properly passed along when tracking feature flag usage events.

fix: pass org name to ai feature flags

---

packages/backend/src/services/ExcelService/ExcelService.test.ts
packages/backend/src/services/ExcelService/ExcelService.ts

Closes: #15430
Support formats defined in Yaml when exporting formatted Excels.

feat: use yml format prop for excel data export & unit tests

---

packages/frontend/src/hooks/useQueryResults.ts

Closes: #15449
Added `keepPreviousData: true` to the query configuration in `useGetReadyQueryResults` hook to preserve the last metric query data. This prevents potential breakage in cartesian chart configuration during data transitions.
https://github.com/user-attachments/assets/058cef68-884c-4cb2-9aa5-e6e3ccadb09b

fix: running query breaking series axis configuration for cartesian charts

---

packages/backend/src/ee/index.ts
packages/backend/src/models/ModelRepository.ts
packages/backend/src/services/OrganizationService/OrganizationService.ts
packages/backend/src/services/ServiceRepository.ts

Closes: 
I think this is a better approach than https://github.com/lightdash/lightdash/pull/15450
Another option would be to create a separate EE service for the initialize environment, which is where this serviceAccountModel is used. 
Another option, is not move serviceAccountModel to non ee (along with the migration!) since this might be something that we use a lot in the future. 
Makes the `serviceAccountModel` parameter optional in the `OrganizationService` to support the open-source version of Lightdash. This change allows the service to function properly without requiring service account functionality, which is an enterprise feature.
The PR adds the `organizationService` to the enterprise app arguments and updates the service to handle cases where the service account model is not …

fix: make serviceAccountModel optional in OrganizationService

---

docker/docker-compose.dev.mini.yml

This PR replaces the `node_modules` volume (which is not required anymore) with a `postgres_data` volume in the development Docker Compose configuration. The new volume is properly mounted to the PostgreSQL container at `/var/lib/postgresql/data`, ensuring data persistence between container restarts.

chore: add persistent volume for postgres in `docker-compose.dev.mini.yml`

---

.env.development
docker/docker-compose.dev.mini.yml
docker/docker-compose.dev.yml

Enable MinIO browser in development environment by adding `MINIO_BROWSER=on` to `.env.development` and passing this environment variable to MinIO containers in Docker Compose files. Also added persistent storage for MinIO by creating a new volume `minio_data` in the mini development setup.

chore: enable MinIO browser in development environment

---

packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingItem.tsx

Closes: [#14671](https://github.com/lightdash/lightdash/issues/14671)
This brings back the ability of using range conditional formatting to when there's no field selected - check comment below
**Before**
**After**

fix: bring back table wide conditional formatting

---

packages/backend/src/clients/ResultsFileStorageClients/S3ResultsFileStorageClient.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/backend/src/services/CsvService/CsvService.test.ts
packages/backend/src/services/CsvService/CsvService.ts
packages/backend/src/services/ExcelService/ExcelService.test.ts
packages/backend/src/services/ExcelService/ExcelService.ts
packages/backend/src/utils/FileDownloadUtils/FileDownloadUtils.test.ts
packages/backend/src/utils/FileDownloadUtils/FileDownloadUtils.ts

Closes: #15475
We resolved the "Invalid character in header content" issue for Japanese users by implementing RFC 5987-compliant Content-Disposition headers that properly encode Unicode filenames. The solution replaces aggressive ASCII-only sanitization with smart character handling that preserves Unicode characters (like Japanese text) while safely removing only filesystem-unsafe characters, then creates dual-format headers with both an ASCII fallback (`filename="fallback.csv"`) and a properly URL-encoded Unicode version (`filename*=UTF-8''%E7%BE%8E%E3%81%97%E3%81%84.csv`) to ensure browser compatibility.

feat: use filename*=UTF-8 for content-disposition & utils tests

---

.claude/commands/cs-bugs.md
CLAUDE.md
packages/cli/CLAUDE.md

Some quick initial context for claude - let's improve it over time
- Adds a root claude.md for project level context
- Adds a CLI claude.md that's pulled in for changes to `/packages/cli` files
- Adds a claude command to fetch open customer suppport issues

chore: add init claude context

---

packages/backend/src/config/aiConfigSchema.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/ee/services/ai/agents/agent.ts
packages/backend/src/ee/services/ai/models/openai-gpt.ts

Closes: #15548
Added support for custom OpenAI base URL in AI Copilot configuration. This allows users to specify an alternative OpenAI API endpoint through the `OPENAI_BASE_URL` environment variable. The implementation includes schema validation for the new `baseUrl` parameter and updates the OpenAI client configuration to use the custom endpoint when provided.

feat: add OpenAI base URL configuration option

---

packages/backend/src/controllers/organizationController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/routers/organizationRouter.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/cli/src/handlers/createProject.ts
packages/cli/src/handlers/preview.ts
packages/cli/src/index.ts
packages/common/src/index.ts
packages/e2e/cypress/e2e/api/organizationPermissions.cy.ts

Closes: #15514
Moved project creation endpoint to `OrganizationsController` so it uses TSOA.
The CLI has been updated with a `--skip-copy-content` option for the `preview` and `start-preview` commands, giving users more control over the project creation process.
**Tests to perform**
- Run `lightdash <preview|start-preview>` with and without `--skip-copy-content`
- All other project creation sources should work as they have been, project creation via UI should still copy content
**`start-preview` without `--skip-copy-content`**
**`start-preview` with `--skip-copy-content`**
**`preview` without `--skip-copy-content`**
**`preview` with `--skip-copy-content`**

feat: add --skip-copy-content option to preview and start-preview commands

---

packages/common/src/types/warehouse.ts
packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts
packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
packages/warehouses/src/warehouseClients/RedshiftWarehouseClient.ts
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
packages/warehouses/src/warehouseClients/TrinoWarehouseClient.ts
packages/warehouses/src/warehouseClients/WarehouseBaseClient.ts
packages/warehouses/src/warehouseClients/WarehouseBaseSqlBuilder.ts

This separates all the sql building logic of warehouses from the query execution.
Benefit is that you can use the sql building functions without needing a set of valid/fake credentials.
Questions:

chore: extract warehouse sql builder methods

---

packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/ee/Ai/schemas.ts
packages/common/src/ee/AiAgent/index.ts
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/LightdashVisualization/context.ts
packages/frontend/src/components/common/MantineModal/index.tsx
packages/frontend/src/components/common/modal/ChartCreateModal/SaveToDashboard.tsx
packages/frontend/src/components/common/modal/ChartCreateModal/SaveToSpaceOrDashboard.tsx
packages/frontend/src/components/common/modal/ChartCreateModal/index.tsx
packages/frontend/src/components/common/modal/ChartCreateModal/types.ts
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatBubbles.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AiChartQuickOptions.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AiChartVisualization.tsx
packages/frontend/src/ee/features/aiCopilot/utils/getOpenInExploreUrl.ts
packages/frontend/src/hooks/useSavedQuery.ts

Closes: #15276
Added the ability to save charts generated by AI Agents in chats.
This PR also adds a new `description` field to chart configuration schemas so agents can create them to simplify saving charts
<details><summary>Screenshots 📸</summary>
Following video is not up to date with UI
[Screen Recording 2025-06-19 at 19.03.35.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/HorFj8gm8QUuuIDE2vgk/11aa34e4-a643-43b4-be0f-1fa81fb2e04f.mov" />](https://app.graphite.dev/media/video/HorFj8gm8QUuuIDE2vgk/11aa34e4-a643-43b4-be0f-1fa81fb2e04f.mov)
_pls ignore the amount of times I added this chart in the dashboard, I promise it was all testing and the tool only saves the chart once 😭_ …

feat: Save generated viz from agent chat

---

packages/frontend/src/ee/pages/AiAgents/AgentThreadPage.tsx

Closes: https://github.com/lightdash/lightdash/issues/15446
Changed the padding in the AgentThreadPage component from `py="xl"` to `pb="md"`, removing the top padding and reducing the bottom padding. This adjustment improves the layout of the AI agent thread page.

fix: change paddings on a chat conversation container

---

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatBubbles.tsx

Only show agent tool calls when streaming is active in the Agent. This prevents tool calls from being displayed when they're no longer relevant in non-streaming contexts.

fix: only show agent tool calls during streaming

---

packages/backend/src/ee/services/ai/tools/generateBarVizConfig.ts
packages/backend/src/ee/services/ai/tools/generateCsv.ts
packages/backend/src/ee/services/ai/tools/generateQueryFilters.ts
packages/backend/src/ee/services/ai/tools/generateTimeSeriesVizConfigTool.ts
packages/backend/src/ee/services/ai/tools/getOneLineResult.ts
packages/backend/src/ee/services/ai/visualizations/csvFile.ts
packages/backend/src/ee/services/ai/visualizations/timeSeriesChart.ts
packages/backend/src/ee/services/ai/visualizations/verticalBarChart.ts
packages/common/src/ee/Ai/schemas.ts

Relates to: #15361
This PR adds filter transformation to ensure proper format for queries while maintaining the original format for tool call arguments. It introduces a new `filtersSchemaTransformed` schema that properly transforms filter rules into the format expected by the query engine.
The changes apply this transformation in multiple visualization tools:
- Bar chart visualization
- CSV generation
- Query filters
- Time series visualization
This ensures consistent filter handling across all AI-powered visualization tools while maintaining backward compatibility with the existing API.

fix: transform filters on tool call

---

packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/ee/AiAgent/index.ts
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/AiChartToolCalls.tsx

Closes: N/A
Unblocked `pnpm generate-api` command by removing zod schema infer on `AiAgentToolCall`.`toolArgs`
error was
```
There was a problem resolving type of 'FindFieldsToolArgs'.
There was a problem resolving type of 'AiAgentToolCall'.
There was a problem resolving type of 'AiAgentMessageAssistant'.
There was a problem resolving type of 'AiAgentMessage<AiAgentUser>'.
There was a problem resolving type of 'AiAgentThread'.
There was a problem resolving type of 'ApiAiAgentThreadResponse'.
Generate routes error.
GenerateMetadataError: No matching model found for referenced type aiFindFieldsToolSchema.
```

fix: remove zod schema to unblock tsoa generate

---

packages/frontend/src/components/UserCompletionModal/UserCompletionModal.tsx

Closes: #N/A
Remove UI when `RUDDERSTACK_ANALYTICS_DISABLED=true`
Auto-complete user setup when tracking is disabled. When Rudder tracking is not configured (writeKey is undefined), the user completion modal will automatically submit with default values instead of showing the modal to the user.

fix: auto-complete user setup when tracking is disabled

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/index.ts
packages/common/src/types/organization.ts
packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/utils.tsx
packages/frontend/src/components/ProjectConnection/ProjectForm.tsx
packages/frontend/src/components/ProjectConnection/UpdateProjectConnection.tsx

Working towards https://github.com/lightdash/lightdash/issues/15347
This makes it possible to create a project without any warehouse credentials. This is only available on the "precompiled" endpoint, which expects a bunch of already constructed explorers.
The `Project` variable already had the warehouse credentials as optional and it appears to be well handled.
Changes:
- LightdashAnalytics - now warehouse type is optional so will be missing sometimes
- `OrganizationProject` had warehouse credentials as required but I've made it optional (only needed for user specific credentials flow in the UI)
- Added defaults to the `ProjectConnection` form in case there are no credentials.

feat: allow create projects without warehouse credentials

---

packages/frontend/src/components/SettingsValidator/index.tsx

Closes:  #15380
I initially added a hard limit in the FE because the UI was a bit slow to load (also, there were some bugs on that page that made it worse, but they are fixed now). But now the customer wants to display all errors, and adding pagination is a bigger piece of work.
I tested again (with 1000 results) , and it seems better, it should work better on prod, without dev mode/scan.
[Screencast from 2025-06-30 09-44-53.webm](https://github.com/user-attachments/assets/95ef03bc-3d3c-45c4-b2bf-53bc9fe590e4)
Removed the 100-row limit in the SettingsValidator component. Previously, the validator table was artificially limited to display only the first 100 validation errors, with a note indicating the total count. This change allows the table to display all validation errors without …

fix: remove 100 row limit in validator table

---

packages/backend/src/services/CoderService/CoderService.ts
packages/common/src/types/coder.ts

Closes: #13844
Added support for `chartName` property in dashboard tiles. This property is now included in the type definitions for dashboard tiles and is properly handled in the `CoderService` when processing chart tiles.
1. Create chart
2. Add chart to dashboard
3. Run `lightdash download --language-map`
4. Check dashboard language map
**Before**
```yaml
dashboard:
dashboard-with-dashboard-charts:
name: Dashboard with dashboard charts
tiles:
- type: saved_chart
properties:
title: ''
chartName: ''
```
**After**
```yaml
dashboard:
dashboard-with-dashboard-charts:
name: Dashboard with dashboard charts
tiles:
- type: saved_chart
properties:
title: ''
chartName: '[Saved in dashboard] How much revenue do we have per payment method?'
```

fix: chartName in language maps

---

packages/backend/src/App.ts
packages/backend/src/SchedulerApp.ts

Closes: #N/A
Before
After
Register OAuth refresh strategies in the SchedulerApp to ensure proper authentication token refreshing when running the scheduler in production mode. This adds the necessary configuration for Google and Snowflake OAuth strategies to work correctly in the scheduler context, similar to how they're already registered in the main App.

fix: register refresh strategies in SchedulerApp

---

packages/frontend/src/ee/features/aiCopilot/hooks/useOrganizationAiAgents.ts

Closes: N/A
Removed the `onSuccess` callback from the `useUpdatePromptFeedbackMutation` hook that was invalidating queries. This eliminates the automatic refresh of thread data after submitting feedback.

fix: do not invalidate on human score change

---

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AiChartVisualization.tsx

Render filters based on metric query instead of ai_prompt.filtersOutput. This ensures that changes to AI Tool schema don't affect the filters UI

fix: render filters based on metric query instead of ai_prompt.filtersOutput

---

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatBubbles.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatDisplay.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AiChartVisualization.tsx

Related to: #15432
Fixes scroll-to-bottom behavior when loading threads w/ charts
- Sets a fixed height for all visualizations
- Makes tables scrollable
- Removes the unnecessary metricQuery check for visualization rendering
Demo (throttled 4g):
[CleanShot 2025-07-01 at 17.41.52.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/SRLEqMEevAzoFwvhnfeq/851c7dec-fd83-46d3-8c8a-58752cbc5306.mp4" />](https://app.graphite.dev/media/video/SRLEqMEevAzoFwvhnfeq/851c7dec-fd83-46d3-8c8a-58752cbc5306.mp4)

fix: scroll-to-bottom behavior when loading charts

---

packages/backend/src/ee/services/CommercialCacheService.ts

Closes: https://github.com/lightdash/lightdash/issues/15585
Added a buffer time to prevent cache expiration during pagination requests. The PR introduces a 10-minute buffer when checking if a cache is valid, ensuring that results don't expire while being actively fetched or paginated through.
This change helps prevent scenarios where a user might start paginating through results, only to have the cache expire midway through their session.
**Cache Buffer Logic:**
We use a dynamic buffer system to prevent cache expiration during pagination:
- For cache stale times > 40 minutes: Use a fixed 10-minute buffer
- For cache stale times ≤ 40 minutes: Use 25% of the stale time as buffer
This approach ensures that even short cache times remain usable while maintaining a safety margin for pagination …

fix: return cache hit when there's cache valid within 10 min buffer

---

packages/common/src/utils/i18n/chartAsCode.test.ts
packages/common/src/utils/i18n/chartAsCode.ts

Closes: [#15647](https://github.com/lightdash/lightdash/issues/15647)
Reproduction steps in main ticket.
Added support for custom chart type in the ChartAsCodeInternalization utility and made xAxis/yAxis name fields optional in the chartAsCodeSchema. This allows the internationalization system to properly handle custom charts and cartesian charts with empty axis configurations.
The PR includes comprehensive tests for various chart types including cartesian charts with empty yAxis entries, pie charts, funnel charts, big number charts, table charts, and custom charts to ensure proper handling of all chart configurations.

feat: add support for custom charts in i18n and make axis names optional

---

.github/CONTRIBUTING.md
.gitignore
dockerfile
dockerfile-prs
flake.nix
packages/backend/package.json
pnpm-lock.yaml

This PR removes unnecessary Cairo, Pango, and librsvg dependencies from our Docker images and development environment. It also:
1. Upgrades the canvas package from v2.11.2 to v3.1.2, which no longer requires these native dependencies
2. Adds support for Nix development environment via a new flake.nix file
3. Updates .gitignore to include Nix and direnv related files
4. Adds automatic setup of multiple dbt versions in the Nix environment
This change will make our development environment setup simpler and more consistent across platforms.

chore: add Nix flake for development environment

---

packages/backend/src/ee/controllers/aiAgentController.ts
packages/backend/src/ee/database/entities/ai.ts
packages/backend/src/ee/database/migrations/20250625151529_add_saved_chart_uuid_to_prompt.ts
packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/ee/AiAgent/index.ts
packages/frontend/src/components/common/modal/ChartCreateModal/SaveToSpaceOrDashboard.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AiChartQuickOptions.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AiChartVisualization.tsx
packages/frontend/src/ee/features/aiCopilot/hooks/useOrganizationAiAgents.ts

Closes: #15552, #15452
Added the ability to associate saved charts with AI agent messages. When a user saves a chart from an AI agent response, the saved chart UUID is now stored in the database and linked to the message. 
This way, users can see which charts have been saved and provides a direct link to view the saved chart.

feat: Link saved charts to ai prompts

---

packages/backend/src/auth/lightdashJwt.test.ts
packages/backend/src/auth/lightdashJwt.ts
packages/backend/src/ee/controllers/embedController.ts
packages/common/src/ee/embed/index.ts

Closes: #N/A
This PR improves JWT token validation for embedded dashboards by:
1. Updating the schema to properly handle `null` values for `allowedFilters` in dashboard filter interactivity options, which is needed for Python clients that serialize `None` to `null`.
2. Enhancing error handling in `decodeLightdashJwt` to log schema validation errors instead of throwing exceptions, reverting back to previous behavior. 
3. Improving error messages to be more specific about token schema validation errors.
4. Adding tests to verify that `null` values for `allowedFilters` are properly handled and that invalid payload structures are logged without throwing exceptions.

fix: allow schema validation errors for jwts again

---

packages/frontend/src/hooks/dashboard/useDashboard.ts

Closes: #15679 
Reproduction steps in the ticket.
Note: wasn't able to reproduce locally, perhaps because it doesn't block `localhost` urls.
Enhanced the CSV export functionality for dashboards by implementing a direct download mechanism instead of opening in a new tab. The exported file is now automatically downloaded with a filename that includes the dashboard name and current date.
This improves the user experience by eliminating the need to manually save the file from a new browser tab and provides a more intuitive download flow.

fix: export dashboard CSV without opening a new tab

---

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatBubbles.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatInput.tsx
packages/frontend/src/ee/pages/AiAgents/AgentPage.tsx
packages/frontend/src/hooks/useTimeAgo.ts

This PR makes three UI improvements:
1. Removes the `borderStartEndRadius: '0px'` style from the UserBubble component, allowing for consistent border radius styling.
2. Hides the "New thread" button when user's already on "New Thread" screen
3. Improves the time ago formatting by switching from `formatDistanceToNowStrict` to `formatDistanceToNow`, which provides more natural relative time descriptions (e.g., "about 2 hours ago" instead of "2 hours ago").

fix: improve chat UI and time formatting

---

packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
packages/frontend/src/hooks/useDelayedHover.ts

Closes: #15654
Added a new `useDelayedHover` hook that introduces a configurable delay before triggering hover state changes. This hook is used in the TileBase component to prevent the chart area from being blocked by the edit menu when hovering over the tile, while still allowing interaction with both chart and menu items.
[Screen Recording 2025-07-02 at 19.06.54.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/HorFj8gm8QUuuIDE2vgk/3c392a81-7393-444a-bc56-23a9abf5447d.mov" />](https://app.graphite.dev/media/video/HorFj8gm8QUuuIDE2vgk/3c392a81-7393-444a-bc56-23a9abf5447d.mov)

fix: Legend scroll arrows don't work when chart title is hidden on a dashboard

---

packages/backend/src/ee/controllers/aiAgentController.ts
packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/frontend/src/ee/features/aiCopilot/components/DefaultAgentButton/DefaultAgentButton.tsx
packages/frontend/src/ee/features/aiCopilot/hooks/useUserAgentPreferences.ts

This PR makes the default agent setting nullable, allowing users to unset their default agent. Previously, once a default agent was set, users couldn't remove it. Now:
1. The `default_agent_uuid` field in the database schema is modified to accept null values
2. A new migration is added to support this change
3. The DefaultAgentButton component is updated to toggle between setting and unsetting the default agent
4. API types are updated to support null values for default agent UUID

feat: allow toggling default agent

---

packages/backend/src/clients/Aws/S3CacheClient.ts
packages/backend/src/clients/ResultsFileStorageClients/S3ResultsFileStorageClient.ts
packages/backend/src/config/parseConfig.test.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/ee/services/CommercialCacheService.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.test.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/backend/src/services/CacheService/ICacheService.ts
packages/backend/src/utils/QueryBuilder/queryBuilder.mock.ts
packages/common/src/compiler/exploreCompiler.mock.ts
packages/common/src/types/queryHistory.ts
packages/common/src/types/warehouse.ts
packages/common/src/utils/convertCustomDimensionsToYaml.ts
packages/common/src/utils/virtualView.ts
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
packages/warehouses/src/warehouseClients/WarehouseBaseClient.ts

Closes: #15699
- Makes S3 storage optional for queries running in snowflake warehouses
**Query code paths:**
- **Cache disabled:**
- **S3 enabled:** No change, S3 results file is created and we paginate on top of the result file for all warehouses
- **S3 disabled:**
- **Snowflake:** Trigger async query in the warehouse and paginate results directly from there.
- **Other warehouses:** Throws error when trying to paginate. Method not implemented.
- **Cache enabled:**
- **S3 enabled:** No change, cache still works the same way using the results files.
- **S3 disabled:** Errors for all warehouses. 
test-frontend

feat: make s3 optional for snowflake

---

packages/backend/src/App.ts
packages/backend/src/ee/index.ts
packages/backend/src/services/InstanceConfigurationService/InstanceConfigurationService.ts
packages/backend/src/services/OrganizationService/OrganizationService.test.ts
packages/backend/src/services/OrganizationService/OrganizationService.ts
packages/backend/src/services/ServiceRepository.ts

Closes: #
Initial setup was added initially to the organization service, we had to add a few extra dependencies for this to work,  when we added ServiceModel (in ee) we had to initialize also on the EE services, which makes everything more confusing. 
This approach is cleaner.
Soon we'll be adding a new method `updateInstance`  to this service too.
Related: https://github.com/lightdash/lightdash/pull/15464
Without license (silent error) 
WIth license but no ENV config  (skip)
With license and ENV config but with existing org/users  (skip)
WIth license and ENV config and no orgs/users (apply initial setup) 
Created a dedicated `InstanceConfigurationService` to handle instance initialization, moving this functionality out of the `OrganizationService`. This improves separation of concerns …

chore: migrate instance initialization to new InstanceConfigurationService 

---

packages/backend/package.json
packages/backend/src/@types/passport-slack-oauth2.d.ts
packages/backend/src/App.ts
packages/backend/src/clients/Slack/SlackOptions.ts
packages/backend/src/controllers/authentication/strategies/slackStrategy.ts
packages/backend/src/controllers/slackController.ts
packages/backend/src/database/entities/openIdIdentities.ts
packages/backend/src/database/migrations/20250703090429_add_openid_team.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/OpenIdIdentitiesModel.ts
packages/backend/src/models/UserModel.ts
packages/backend/src/routers/apiV1Router.ts
packages/backend/src/services/UserService.ts
packages/common/src/types/openIdIdentity.ts
packages/common/src/types/user.ts
packages/frontend/src/components/UserSettings/SocialLoginsPanel/index.tsx
packages/frontend/src/features/users/components/LoginLanding.tsx
pnpm-lock.yaml

Closes: #XXXX
- open a browser on `/api/v1/auth/slack` to start authentication
- poll `/api/v1/slack/is-authenticated` with user credentials until this returns 200 (returns 404 when not authenticated)
- openid_identities will contain a `user_id` and `slack id` (subject) 
We need to add a new extra callback to the slack app, for this flow to work. 
Slack app > oauth & permissions > redirect URLs
https://api.slack.com/apps/A04EJP8LZPD/oauth
[Screencast from 2025-07-03 09-25-30.webm](https://github.com/user-attachments/assets/3d875dbf-af74-485b-8ca0-c33f9b263e1a)
On slack settings you can see who have logged in, and revoke access if we need to. 
https://lightdash.slack.com/marketplace/A04EJP8LZPD-lightdash-share-local?next_id=0&tab=settings
Also added team to the database
In the future, we …

feat: add Slack OAuth integration

---

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatInput.module.css
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatInput.tsx

Closes: #N/A
Updated the AI Copilot chat interface styling by changing the color scheme from violet to gray/dark. The focus border color now uses gray-5 instead of violet-5, and the send button uses dark.5 instead of violet. 
- fixed the conditional rendering logic for the disabled message to only show when both disabled is true and a disabledReason exists.

style: remove backdrop if not disabled

---

packages/backend/src/utils/QueryBuilder/queryBuilder.ts

Closes: #15725 
There was an issue with fanout handling that included custom dimensions (see the linked ticket). This fixes that issue, and probably some similar issues as well. 
We were getting the wrong opperator precedence when comparing dimension aliases and joining the clauses together. This fixes it by **wrapping each condition for a single dimension in parentheses before joining them with `AND`**.
So, we had
```
ON 
cte_unaffected."payments_payment_method" = cte_metrics_orders."payments_payment_method"
OR (
cte_unaffected."payments_payment_method" IS NULL 
AND cte_metrics_orders."payments_payment_method" IS NULL
)
AND cte_unaffected."amount_range" = cte_metrics_orders."amount_range"
OR (
cte_unaffected."amount_range" IS NULL 
AND cte_metrics_orders."amount_range" IS NULL
)
```
And …

fix: opperator precedence in final fanout join

---

packages/backend/src/auth/lightdashJwt.ts
packages/backend/src/ee/controllers/embedController.ts
packages/backend/src/ee/models/EmbedModel.ts
packages/backend/src/ee/services/EmbedService/EmbedService.ts
packages/backend/src/middlewares/jwtAuthMiddleware/hydrateEmbeddedAccount.ts
packages/backend/src/middlewares/jwtAuthMiddleware/index.ts
packages/backend/src/middlewares/jwtAuthMiddleware/jwtAuthMiddleware.test.ts
packages/backend/src/middlewares/jwtAuthMiddleware/jwtAuthMiddleware.ts
packages/backend/src/models/UserModel.ts
packages/common/src/authorization/index.ts
packages/common/src/authorization/scopeAbility.test.ts
packages/common/src/authorization/scopeAbility.ts
packages/common/src/authorization/types.ts
packages/common/src/ee/embed/index.ts
packages/common/src/types/auth.ts
packages/common/src/types/user.ts
packages/e2e/cypress/e2e/app/space.cy.ts
packages/frontend/src/testing/__mocks__/api/userResponse.mock.ts

Closes: #15580
Refactors the JWT authentication middleware to improve embedded dashboard functionality. This PR:
- Introduces a new `hydrateEmbeddedAccount` utility to properly populate user session data and abilities
- Adds CASL ability rules for embedded users with proper scoping
- Replaces `EmbedJwt` with `CreateEmbedJwt` type in relevant places due to zod and tsoa not being on friendly terms
- Enhances the embed model to include organization name
- Extracts dashboard UUID resolution logic to a dedicated method
- Adds comprehensive test coverage for embedded user abilities
- Slight refactor to CASL verbs and subjects so their sorted for easier reading
This change improves the security model for embedded dashboards by properly scoping user permissions based on the JWT token contents.

feat: hydate req.account in jwt middleware

---

packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Snowflake client was never throwing any errors when there was a network error.
This sets explicit retry limits so that it does.
1. Deploy snowflake project
2. Disable S3 (you can unset `S3_ENDPOINT` env variable)
3. Turn of wi-fi
4. Run query (can be explore)
**Before**
Queries were hanging forever
**After**

fix: set snowflake timeout values for login

---

packages/backend/src/ee/services/ai/visualizations/vizTimeSeries.ts
packages/common/src/ee/AiAgent/schemas/tools/toolTimeSeriesArgs.ts
packages/common/src/ee/AiAgent/schemas/visualizations/timeSeriesViz.ts
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AiChartVisualization.tsx
packages/frontend/src/ee/features/aiCopilot/utils/echarts.ts

Closes: #15453
Added support for x-axis and y-axis labels in time series visualizations. The schema now includes optional `xAxisLabel` and `yAxisLabel` fields that allow users to provide helpful descriptions for each axis. These labels are properly rendered in the ECharts configuration when present.
Before:
After:

feat: add x and y axis labels to time series visualization

---

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AiChartVisualization.tsx

Fixed duplicate `fieldsMap` props in AiChartVisualization component by removing redundant props and placing the single `fieldsMap` prop in the correct location.

fix: remove duplicate fieldsMap props and move to correct component

---

dockerfile
dockerfile-prs

Closes: 
Split the DBT installation commands in the Dockerfile to separate RUN instructions. This change improves build caching by separating the installation of DBT 1.9 and DBT 1.10 into distinct layers, which can help with more efficient rebuilds during development.

fix: split dbt installation into separate RUN commands

---

packages/backend/src/ee/services/ai/tools/generateTableVizConfig.ts

Closes: https://github.com/lightdash/lightdash/issues/15783
Reordered the progress update and result handling in the `generateTableVizConfig` tool:
1. Added "Done" progress update before checking if the result is a single row
2. Moved the single row result handling before the Slack-specific logic
3. This ensures proper progress updates are shown regardless of the result type and improves the flow of the code

fix: update progress message and reorder single row result handling

---

dockerfile
dockerfile-prs
packages/backend/package.json
pnpm-lock.yaml

Add Cairo, Pango, and RSVG development libraries to Docker images and downgrade canvas package from 3.1.2 to 2.11.2. These changes ensure proper support for rendering SVG and other graphics in the application.

fix: missing font by adding Cairo, Pango, and RSVG dependencies and downgrade canvas package

---

packages/common/src/types/filterGrammar.ts
packages/frontend/src/ee/features/embed/EmbedDashboard/components/EmbedDashboard.tsx

Closes:  #15779
Dashboard:
Before
After
Added tab support to embedded dashboards, allowing users to navigate between different dashboard tabs in embedded views. The implementation includes:
- Tab navigation UI with proper styling and active tab highlighting
- Filtering dashboard tiles based on the selected tab
- Handling legacy tiles (without tab assignment) by showing them on the first tab
- Empty tab state with appropriate messaging
- Automatic selection of the first tab when loading the dashboard
This enhancement ensures embedded dashboards maintain the same tab functionality as regular dashboards, providing a consistent user experience across both interfaces.

feat: add tab support to embedded dashboards

---

packages/backend/src/database/entities/slackAuthentication.ts
packages/backend/src/database/migrations/20250707073534_slack_installation_ai_thread_consent.ts
packages/backend/src/models/SlackAuthenticationModel.ts

Added a new boolean column `ai_thread_access_consent` to the `slack_auth_tokens` table with a default value of `false`. This column will track whether users have consented to AI access for their Slack threads.
- Creating a new migration for the column in the open-source version
- Updating the existing EE migration to check if the column exists before creating it
Internal thread: https://lightdash.slack.com/archives/C02GQKJK84Q/p1751639371093159

feat: add AI thread access column to Slack installations

---

packages/backend/src/database/entities/slackAuthentication.ts
packages/backend/src/database/migrations/20250707075311_slack_setting_ai_require_oauth.ts
packages/backend/src/ee/clients/Slack/SlackClient.ts
packages/backend/src/ee/index.ts
packages/backend/src/ee/models/CommercialSlackAuthenticationModel.ts
packages/backend/src/ee/services/CommercialSlackIntegrationService.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/OpenIdIdentitiesModel.ts
packages/backend/src/models/SlackAuthenticationModel.ts
packages/common/src/types/slack.ts
packages/common/src/types/slackSettings.ts
packages/frontend/src/components/UserSettings/SlackSettingsPanel/index.tsx

Closes: #15172
This PR adds a new setting for Slack integration that requires users to authenticate with OAuth before using AI Agent features.
- A new `ai_require_oauth` column in the `slack_auth_tokens` table
- Authentication handling in the Slack bot to verify user identity before processing AI requests
- UI controls in the Slack settings panel to toggle this requirement
- Integration with the OpenID identity system to verify user authentication
When enabled, users who haven't connected their Slack account to Lightdash will receive a message prompting them to authenticate before using AI features.
[CleanShot 2025-07-04 at 19.28.39.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" …

feat: add OAuth requirement option for Slack AI Agent

---

packages/backend/src/ee/clients/Slack/SlackClient.ts

Added 'groups:history' to the required Slack scopes in the CommercialSlackClient class to ensure proper access to private channel history.

feat: add groups:history to required Slack scopes for EE

---

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatAssistantBubble.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/AiChartToolCalls.tsx

Tool calls were mismatched between streaming and persisted states.

fix: tool calls mismatched on messages

---

packages/backend/src/controllers/projectController.ts
packages/backend/src/services/CoderService/CoderService.ts
packages/cli/src/handlers/download.ts
packages/cli/src/index.ts

Closes:  https://github.com/lightdash/lightdash/issues/13368
Before:
After:
Added a new `--skip-space-create` flag to the CLI upload command that prevents automatic space creation when uploading charts and dashboards. This allows users to upload resources only to existing spaces, avoiding unintended space creation.
The implementation:
1. Added a `skipSpaceCreate` parameter to the chart and dashboard upsert endpoints
2. Modified the CoderService to check this flag before creating a space
3. Updated the CLI to pass this flag through the upload command chain
4. Added appropriate error handling to skip resources when their spaces don't exist
This feature is useful for CI/CD pipelines where you want to ensure resources are only uploaded to pre-defined spaces.

feat: add skip-space-create option to CLI upload command

---

examples/full-jaffle-shop-demo/dbt/models/payments.yml
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/utils/QueryBuilder/utils.test.ts
packages/backend/src/utils/QueryBuilder/utils.ts
packages/common/src/dbt/schemas/lightdashMetadata.json
packages/common/src/schemas/json/lightdash-dbt-2.0.json
packages/common/src/types/explore.ts

Closes: [#15810](https://github.com/lightdash/lightdash/issues/15810)
To reproduce, modified payments joins:
```
joins:
- join: orders
sql_on: ${orders.order_id} = ${payments.order_id}
relationship: one-to-one
- join: customers
sql_on: ${customers.customer_id} = ${orders.customer_id}
relationship: many-to-many
```
Example: all tables have CTEs to deduplicate rows
Added support for many-to-many join relationships in the data model. This enhancement allows users to properly define many-to-many relationships between tables, which is particularly useful for junction tables that connect entities with many-to-many relationships.
- Added 'many-to-many' as a valid join relationship type in the schema definitions
- Updated the metric inflation detection logic to …

feat: add support for many-to-many join relationships

---

packages/backend/src/utils/QueryBuilder/queryBuilder.ts

Closes: [#15811](https://github.com/lightdash/lightdash/issues/15811)
Query working in Lightdash
Same query working in snowflake
Fixed SQL query generation in MetricQueryBuilder by properly quoting table names in primary key references. This ensures compatibility with databases that require table names to be quoted, especially when they contain special characters or reserved keywords.

fix: properly quote table names in SQL query builder

---

.env.development
.github/CONTRIBUTING.md
docker/docker-compose.dev.yml
docker/ssh-server-configs/sshd_config

Add SSH tunnel testing capability to local development environment
This PR adds the ability to test SSH tunnels locally during development by:
1. Adding an OpenSSH server container to the development Docker Compose setup
2. Creating a configuration for the SSH server that allows TCP forwarding
3. Adding a `DEV_SSH_PUBLIC_KEY` environment variable to store the developer's public key
4. Providing detailed documentation on how to set up and test SSH tunnels locally
Developers can now generate SSH key pairs through the Lightdash UI and use them to test database connections through SSH tunnels in their local development environment.

chore: add development ssh tunnel and instructions for testing in docker

---

packages/backend/src/scheduler/SchedulerTask.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.test.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/common/src/types/scheduler.ts

Closes: #15793
Refactored the async warehouse query execution to use a dedicated method in AsyncQueryService instead of duplicating the implementation in SchedulerTask. This change:
1. Extracts the query execution logic into a public `runAsyncWarehouseQuery` method in AsyncQueryService
2. Simplifies the SchedulerTask implementation to delegate to this method
3. Adds proper type definitions for the query execution parameters
4. Enables the worker-based query execution by uncommenting the scheduler task code
5. Improves credential handling by fetching them only when needed
6. Fetches warehouse credentials in `runAsyncWarehouseQuery` rather than passing them as an argument

fix: scheduler task to run queries should run asyncQueryService function

---

packages/backend/src/queryCompiler.test.ts
packages/backend/src/queryCompiler.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/utils/QueryBuilder/queryBuilder.test.ts
packages/backend/src/utils/QueryBuilder/queryBuilder.ts
packages/backend/src/utils/QueryBuilder/utils.test.ts
packages/backend/src/utils/QueryBuilder/utils.ts
packages/common/src/dbt/DbtSchemaEditor/DbtSchemaEditor.ts
packages/common/src/utils/convertCustomDimensionsToYaml.ts
packages/common/src/utils/customDimensions.ts

Closes: #15794 
Refactored the query compilation process to use a dedicated `WarehouseSqlBuilder` interface instead of the full `WarehouseClient`. This change decouples SQL generation from the warehouse connection, allowing for more efficient query building without requiring an active database connection.
This allows us to remove the need for a full `warehouseClient` in `prepareMetricQueryAsyncQueryArgs`
The main changes include:
- Replaced `warehouseClient` parameter with `warehouseSqlBuilder` in query compilation functions
- Updated all SQL generation utilities to use the builder interface
- Removed unnecessary SSH tunnel connections that were being created and immediately disconnected

chore: refactor prepareMetricQueryAsyncQueryArgs to use a warehouseSqlBuilder instead of warehouseClient

---

packages/frontend/src/components/CustomVisualization/index.tsx
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationConfig.tsx
packages/frontend/src/components/common/CollapsableCard/CollapsableCard.tsx
packages/frontend/src/components/common/CollapsableCard/constants.ts

Closes: https://github.com/lightdash/lightdash/issues/8787
Improves the CustomVisualization component by:
- Adding resize observation using Mantine's `useResizeObserver` hook
- Fixing the loading state display with proper centering
- Enhancing the visualization container with explicit width and height based on the observed dimensions
- Updating the autosize configuration from `fit` to `fit-x` for better horizontal scaling
- Adding overflow handling to prevent content from spilling outside the containe
video:
[CleanShot 2025-07-11 at 11.30.46.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/cOL6QbQzyaUdOs5psinD/2114362e-444d-4b44-bf14-ac6c98e3b7da.mp4" …

fix: improve custom visualization resizing with useResizeObserver

---

packages/backend/package.json
packages/backend/src/config/aiConfigSchema.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/ee/services/ai/models/index.ts
packages/backend/src/ee/services/ai/models/openrouter.ts
pnpm-lock.yaml

Add OpenRouter as an AI provider option for Lightdash AI Agent
- Adds OpenRouter as a new provider option alongside OpenAI, Azure, and Anthropic
- Supports configuration via environment variables:
- OPENROUTER_API_KEY
- OPENROUTER_MODEL_NAME
- OPENROUTER_SORT_ORDER
- OPENROUTER_ALLOWED_PROVIDERS

feat: add OpenRouter as AI provider option

---

packages/backend/src/ee/index.ts
packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/GroupsModel.ts
packages/common/src/ee/AiAgent/index.ts
packages/frontend/src/components/NavBar/AiAgentsButton.tsx
packages/frontend/src/ee/features/aiCopilot/hooks/useOrganizationAiAgents.ts
packages/frontend/src/ee/features/aiCopilot/hooks/useProjectAiAgents.ts
packages/frontend/src/ee/pages/AiAgents/ProjectAiAgentEditPage.tsx

Relates to: #15385
This PR adds group-based access control for AI Agents, allowing administrators to restrict agent access to specific user groups. 
Key changes:
- Added a `groupAccess` field to AI Agents that stores which groups can access an agent
- Implemented permission checks throughout the AI Agent service to verify user access
- Added UI components in the agent creation/edit form to select which groups can access an agent
- Improved error handling for permission-related errors in the frontend
- Added database schema and model methods to support group-based access control
When no groups are specified for an agent, it remains accessible to all users(non-viewers) in the organization. When groups are specified, only users in those groups (or users with admin/developer permissions) can …

feat: add group access to ai agents

---

packages/frontend/src/ee/features/embed/EmbedDashboard/components/EmbedDashboard.tsx

Closes: #[issue number]
Before:
After
Fixed positioning issues in the embedded dashboard by adding relative positioning to tab elements and wrapping the dashboard grid in a Group component with relative positioning. This ensures proper layout and respects the position constraints within the embedded context.

fix: add position styling to embedded dashboard tabs

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/errors.ts
packages/frontend/src/components/UserSettings/MyWarehouseConnectionsPanel/WarehouseFormInputs.tsx
packages/frontend/src/hooks/toaster/ApiErrorDisplay.tsx
packages/frontend/src/hooks/toaster/MultipleToastBody.tsx
packages/frontend/src/hooks/toaster/useToaster.tsx

Closes: https://github.com/lightdash/lightdash/issues/15803
[Screencast from 2025-07-10 16-22-51.webm](https://github.com/user-attachments/assets/331e32f8-a537-4601-aa39-7317b37d06d3)
Improved error handling for Snowflake SSO token refresh by adding a specific `SnowflakeTokenError` class that triggers a re-authentication UI in the frontend. When a Snowflake token refresh fails, users will now see a prompt to re-authenticate instead of a generic error message.
The implementation:
1. Adds try/catch block around Snowflake token refresh
2. Creates a new `SnowflakeTokenError` class in common error types
3. Enhances the API error display component to show a Snowflake login form when this specific error occurs
4. Exports the `SnowflakeFormInput` component for reuse in the error display

fix: add Snowflake token refresh error handling with reauthentication UI

---

packages/backend/src/database/entities/queryHistory.ts
packages/backend/src/ee/database/migrations/20250713101551_add_query_history_account.ts
packages/backend/src/models/QueryHistoryModel/QueryHistoryModel.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.test.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/common/src/types/queryHistory.ts

Closes: #15847
Added support for tracking queries by account in query history. `account` encapsulates identity that is not userUuid—which would include an external ID. 
These changes are needed so that embedded users can make async queries and have query history associated to their external ID. 
This change:
- Added a new `created_by_account` column to the query history table
- Created a migration to add the column and appropriate indexes
- Updated the QueryHistoryModel to support filtering by account instead of user UUID
- Modified method signatures in AsyncQueryService to accommodate the new account parameter
- Updated type definitions to include the new field
This enhancement allows queries to be associated with either a user UUID or an account identifier, enabling better tracking of …

feat: add create_by_account to query_history

---

.github/workflows/cli-tests.yml

Fix CLI tests failing due to dbt relation conflicts by adding `--full-refresh` flag to `dbt run` command.
CLI tests were failing with:
```
Database Error in model stg_customers (models/staging/stg_customers.sql)
relation "stg_customers" already exists
Database Error in model stg_orders (models/staging/stg_orders.sql)
relation "stg_orders" already exists
Database Error in model stg_payments (models/staging/stg_payments.sql)
relation "stg_payments" already exists
```
Example: https://github.com/lightdash/lightdash/runs/45986599501
Example of `--full-refresh` https://github.com/lightdash/lightdash/blob/207bbd4999473f8ca693fa5e43c72e2d7d102fb7/examples/full-jaffle-shop-demo/renderDeployHook.sh#L7

fix: add --full-refresh flag to dbt run command in CLI tests

---

packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/ee/services/ai/prompts/system.ts
packages/backend/src/ee/services/ai/tools/findExplores.ts
packages/backend/src/ee/services/ai/tools/findFields.ts
packages/backend/src/ee/services/ai/types/aiAgentExploreSummary.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/explore.ts

Closes: #15335
Added support for AI hints in explores and fields. These hints are now passed to the AI agent and take precedence over field descriptions when generating responses. The system prompt has been updated to instruct the AI to prioritize hints over descriptions when interpreting field usage.

feat: use AI hint fields from dbt schema in Agent prompts/tools

---

packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

Closes: #15865
- Fixed error handling in SQL Runner to properly display query execution errors
- Updated Redux state management to handle different error types (SerializedError, Error, ApiErrorDetail)
- Ensures users see meaningful error messages when SQL queries fail instead of silent failures
When SQL queries failed with execution errors (e.g., "Unrecognized name: f0\_ at [2:1]"), the errors were being swallowed and not displayed to users. The Redux store was only handling `ApiErrorDetail` errors from the payload

fix: improve SQL runner error handling

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/ee/analytics/index.ts
packages/backend/src/ee/services/EmbedService/EmbedService.ts
packages/common/src/types/user.ts

Closes: #15547
Added a new `trackAccount` method to `LightdashAnalytics` class to centralize tracking events from an account. This method automatically extracts common properties like `userId`, `anonymousId`, `externalId`, and `organizationId` from the account object, reducing code duplication.
Updated embed analytics to use this new method, simplifying the tracking code in `EmbedService` by removing redundant properties that are now handled automatically.

feat: add trackAccount to LightdashAnalytics

---

packages/backend/src/services/GroupService.ts
packages/backend/src/services/ServiceRepository.ts
packages/frontend/src/components/ProjectAccess/ProjectAccess.tsx
packages/frontend/src/components/ProjectAccess/index.tsx
packages/frontend/src/components/UserSettings/UserAttributesPanel/UserAttributeModal.tsx
packages/frontend/src/components/UserSettings/UserAttributesPanel/index.tsx
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/GroupsView.tsx
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/UsersView.tsx
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/index.tsx
packages/frontend/src/features/projectGroupAccess/components/ProjectGroupAccess.tsx
packages/frontend/src/hooks/useOrganizationGroups.ts
packages/frontend/src/pages/Settings.tsx

Added a feature flag to enable/disable the Group service functionality. This PR introduces a check in all Group service methods to verify if the service is enabled before proceeding with operations. If the service is disabled, a ForbiddenError is thrown with the message "Group service is not enabled".

feat: add group service enablement check with config integration

---

packages/backend/src/config/parseConfig.ts
packages/backend/src/services/InstanceConfigurationService/InstanceConfigurationService.test.ts
packages/backend/src/services/InstanceConfigurationService/InstanceConfigurationService.ts

Closes: https://github.com/lightdash/lightdash-internal-work/issues/3579
Before
After
`export LD_SETUP_ORGANIZATION_DEFAULT_ROLE=editor`
Added support for configuring the default role for new organization members through environment variables. This allows administrators to set a custom default role (e.g., VIEWER, EDITOR, ADMIN) for users joining via allowed email domains by setting the `LD_SETUP_ORGANIZATION_DEFAULT_ROLE` environment variable.
The PR includes:
- Added `defaultRole` to the organization configuration schema
- Updated the instance configuration service to apply the default role when creating or updating allowed email domains
- Added a new method to update the default role for existing organizations

feat: add organization default role configuration

---

packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/ValidationService/ValidationService.ts

Closes: #15903
Get compiled explores + virtual views with new method so that these can be merged and checked when validating with the CLI
How to test:
- Go to SQL runner and create a virtual view
- Validate project with the CLI (see cli/README)
- See that `compiledExplores` has no virtual views, so we add them

fix: get virtual views when cli-validate project

---

packages/backend/src/ee/services/ai/tools/generateBarVizConfig.ts
packages/backend/src/ee/services/ai/tools/generateTableVizConfig.ts
packages/backend/src/ee/services/ai/tools/generateTimeSeriesVizConfig.ts

Closes: #15919
Added field validation to AI visualization tools to ensure that selected fields exist in the explore before generating visualizations. This validation is now implemented across bar, table, and time series visualization configurations, preventing errors from non-existent fields.
Tool call with a wrong field name:
Response:

fix: validate field existence in visualization tools

---

flake.nix

Updated development dependencies in flake.nix to support new packages and changed Node.js version:
- Downgraded from Node.js 22 to Node.js 20 <<<<<<< we are using node 20 in our image builds, just matching that.
- Replaced pnpm with corepack
- Added libraries required for @databricks/sql: lz4
- Added libraries needed for node-canvas: pixman, cairo, pango, libjpeg, libpng, librsvg, and giflib

chore: update dependencies for databricks/sql and node-canvas support

---

packages/backend/src/ee/index.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.test.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/backend/src/services/CsvService/CsvService.test.ts
packages/backend/src/services/CsvService/CsvService.ts
packages/backend/src/services/PivotTableService/PivotTableService.ts
packages/backend/src/services/ServiceRepository.ts

Async query service had a dependency on CSV service just to download pivoted tables. This remove that dependency by moving pivot csv generation to its own service. 
This was necessary as a pre-req for having CSV service use the AsyncQuery service in the future.

chore: remove asyc query service dependency on csv service

---

.github/workflows/cli-tests.yml
packages/e2e/cypress/cli/commands.cy.ts
packages/e2e/cypress/cli/dbt/cli.cy.ts

There is no point on running non dbt specific CLI commands against multiple dbt vresions (eg: download/upload) 
I am planning to add more non dbt tests , eg: oauthLogin 
Split CLI tests into two separate jobs: one for basic CLI commands without dbt dependencies, and another for dbt-specific tests. This separation allows faster testing of basic CLI functionality without requiring dbt setup.
Also added basic CLI command tests to verify help and version commands work correctly.
test-cli

feat: split CLI tests into dbt and non-dbt workflows

---

packages/backend/src/config/parseConfig.ts
packages/backend/src/services/OAuthService/OAuthService.test.ts
packages/backend/src/services/OAuthService/OAuthService.ts
packages/cli/package.json
packages/cli/src/handlers/oauthLogin.ts
packages/common/package.json
packages/common/src/utils/oauth.ts
pnpm-lock.yaml

Closes: #N/A
3 changes: 
- Add configurable OAuth token lifetimes 
- use openid-client to authenticate with oauth in the client 
- extract html rendering into common package, and use handlebars
Same functionality. 
Add configurable OAuth token lifetimes and improve CLI OAuth flow
This PR adds configuration options for OAuth access and refresh token lifetimes through environment variables:
- `AUTH_OAUTH_SERVER_ACCESS_TOKEN_LIFETIME` (default: 1 hour)
- `AUTH_OAUTH_SERVER_REFRESH_TOKEN_LIFETIME` (default: 2 weeks)
The CLI OAuth login flow has been completely refactored to use the `openid-client` library for better security and standards compliance. The authentication UI has been improved with better error handling and templated responses using Handlebars to prevent XSS issues.

feat: use openid-client on CLI and build HTML with handlebards

---

packages/backend/src/ee/services/ai/tools/generateTableVizConfig.ts
packages/common/src/ee/AiAgent/schemas/visualizations/tableViz.ts

Removes the nullable option from the dimensions array in the table visualization configuration schema. This change ensures that dimensions are always treated as an array, eliminating the need for null checks when accessing dimensions in the code.

fix: remove nullable (can be an empty array) from tableVizConfigSchema dimensions

---

packages/backend/src/auth/lightdashJwt.ts
packages/backend/src/middlewares/jwtAuthMiddleware/jwtAuthMiddleware.test.ts
packages/backend/src/middlewares/jwtAuthMiddleware/jwtAuthMiddleware.ts
packages/common/src/authorization/index.ts
packages/frontend/src/api.ts
packages/frontend/src/ee/features/embed/EmbedDashboard/api.ts
packages/frontend/src/ee/features/embed/EmbedDashboard/hooks.ts
packages/frontend/src/ee/providers/Embed/EmbedProvider.tsx
packages/frontend/src/ee/providers/Embed/types.ts
packages/frontend/src/hooks/dashboard/useDashboard.ts
packages/frontend/src/hooks/useCalculateTotal.ts
packages/frontend/src/utils/inMemoryStorage.ts

Closes: 
This PR refactors how embed tokens are handled in the application to improve the embedding experience. The key changes include:
1. Moving the `JWT_HEADER_NAME` constant from backend to common package for better sharing
2. Storing embed tokens in in-memory in a dedicated module that can be accessed from the UI API
3. Refactoring the API client to automatically include embed tokens in requests
4. Improving project UUID handling by supporting it as a query parameter
These changes simplify the embedding flow and make it more robust, particularly when navigating between pages in an embedded dashboard.

feat: add JWT header to all UI network requests if present

---

packages/backend/src/controllers/CLAUDE.md
packages/backend/src/controllers/userController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/index.ts
packages/common/src/types/account.ts

Closes: #XXXX
Added a new `/user/account` endpoint to fetch account information without the user's ability rules. This endpoint returns a serialized account object that excludes the ability property from the user object.
Also implemented a new `useAccount` hook in the frontend to fetch account data, and updated the `useOrganization` hook to support embed tokens and project UUIDs. The EmbedExplore component now uses the account hook to ensure proper loading state.
We'll use this hook to get user abilities for the JWT user.

feat: add account endpoint

---

packages/backend/src/database/entities/catalog.ts
packages/backend/src/database/migrations/20250722164009_add_yaml_tags_to_catalog_search.ts
packages/backend/src/database/migrations/20250722164436_add_index_on_yaml_tags_of_catalog_search.ts
packages/backend/src/models/CatalogModel/CLAUDE.md
packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/models/CatalogModel/utils/index.ts
packages/backend/src/services/CatalogService/CatalogService.ts

Add YAML tags support to catalog search for AI feature visibility control
This PR adds a new `yaml_tags` column to the catalog search table to store tags defined in dbt YAML files. It implements a sophisticated filtering mechanism that controls which catalog items (explores, tables, and fields) are visible based on tag configuration:
- When no tags are configured, everything is visible by default
- When tags are configured, visibility follows these rules:
- If an explore has a matching tag, all fields in that explore are visible
- If specific fields have matching tags, only those fields are visible
- If both an explore and some fields have matching tags, only those tagged fields are visible
- If no matching tags exist, nothing is visible
The implementation includes database migrations to …

feat: add yaml_tags to catalog search for AI visibility filtering

---

docker/CLAUDE.md
docker/docker-compose.dev.yml

Adds `lightdash-query-worker` service to isolate warehouse query execution from the main backend bringing it closer to a production setup.
- New Service: lightdash-query-worker runs scheduler with only `runAsyncWarehouseQuery` tasks
- Main Backend: lightdash-dev excludes `runAsyncWarehouseQuery` via `SCHEDULER_EXCLUDE_TASKS`
- Deduplication: Added YAML anchors (x-lightdash-*) to eliminate ~90% config duplication
- Dependencies: Query worker depends on main service and auto-restarts on failure
```yaml
lightdash-dev:
SCHEDULER_EXCLUDE_TASKS: runAsyncWarehouseQuery  # API only
lightdash-query-worker:
SCHEDULER_INCLUDE_TASKS: runAsyncWarehouseQuery  # Queries only
restart: unless-stopped
```

chore: add separate query worker for dev environments

---

packages/backend/src/projectAdapters/dbtBaseProjectAdapter.test.ts
packages/cli/src/lightdash-config/lightdash-config.test.ts
packages/common/src/schemas/json/lightdash-project-config-1.0.json
packages/common/src/utils/loadLightdashProjectConfig.ts

Closes: 
Made the `spotlight` field required in the Lightdash project config schema and improved the config loading process by properly merging default values with user-provided configuration. This ensures that even if a user doesn't explicitly define spotlight settings, the default configuration will be applied consistently.
Update `examples/full-jaffle-shop-demo/dbt/lightdash.config.yml` to only have parameters:
```
parameters:
subscription_status:
label: "Subscription Status"
description: "Filter subscriptions by their current status"
default: "all"
options:
- "all"
- "Current"
- "Expired"
- "Cancelled"
```
Run deploy
```
pnpm cli-build
node ./packages/cli/dist/index.js login http://localhost:3000
node ./packages/cli/dist/index.js deploy --project-dir …
```

fix: make spotlight required and merge with default config

---

packages/backend/src/config/aiConfigSchema.ts
packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/ee/index.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/ee/services/ai/agents/agent.ts
packages/backend/src/ee/services/ai/agents/tests/testUtils.ts
packages/backend/src/ee/services/ai/tools/newFindFields.ts
packages/backend/src/ee/services/ai/types/aiAgent.ts
packages/backend/src/ee/services/ai/types/aiAgentDependencies.ts
packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/services/CatalogService/CatalogService.ts
packages/common/src/ee/AiAgent/schemas/fieldSearchQuery.ts
packages/common/src/ee/AiAgent/schemas/index.ts
packages/common/src/ee/AiAgent/schemas/tools/index.ts
packages/common/src/ee/AiAgent/schemas/tools/toolFindFieldsArgs.ts
packages/common/src/ee/AiAgent/schemas/tools/toolNewFindFieldsArgs.ts
packages/common/src/index.ts
packages/common/src/utils/explore.ts
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/AiChartToolCalls.tsx

Closes: #
Implements field search functionality for AI agents, allowing them to search for relevant fields across all available explores. This replaces the previous approach where agents had to first find explores and then search for fields within them.
Key changes:
- Added a new `findFields` function that uses the catalog service to find fields matching search queries
- Updated the `findFields` tool to accept search queries instead of explore names
- Added user attributes support to ensure proper access control for field searches
- Enhanced field search results with detailed metadata including descriptions, tags, and AI hints
- Updated the UI to display search terms instead of explore names in tool call descriptions
This change improves the AI agent's ability to find relevant fields …

feat: implement field search for AI agent with user attributes and ai tags

---

docker/docker-compose.dev.yml
packages/backend/package.json

Closes: 
Expose port 9229 in the development Docker environment and set `LIGHTDASH_MODE=development` and `HEADLESS=true` for the debug script to ensure consistent environment variables between development and debugging modes.

chore: fix debug command for dev and add debug port to service

---

packages/frontend/src/api.test.ts
packages/frontend/src/api.ts
packages/frontend/src/utils/inMemoryStorage.ts

Closes: #N/A
Prevents duplicate JWT headers in API requests by adding a safety check before adding embed tokens. This ensures that if an explicit JWT header is already provided, the system won't add another one from the embed token.
Added a new `isSafeToAddEmbedHeader` function that checks if JWT headers already exist before adding the embed token header.
Also added a `clearInMemoryStorage` utility function and created a test case to verify the prevention of duplicate token headers.

feat: do not duplicate embed headers

---

packages/backend/src/auth/account/account.test.ts
packages/backend/src/auth/account/account.ts
packages/backend/src/controllers/exploreController.ts
packages/backend/src/controllers/projectController.ts
packages/backend/src/controllers/runQueryController.ts
packages/backend/src/controllers/savedChartController.ts
packages/backend/src/controllers/sqlRunnerController.ts
packages/backend/src/controllers/v2/QueryController.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/ee/services/AiService/AiService.ts
packages/backend/src/ee/services/SupportService/SupportService.ts
packages/backend/src/models/QueryHistoryModel/QueryHistoryModel.ts
packages/backend/src/routers/dashboardRouter.ts
packages/backend/src/routers/savedChartRouter.ts
packages/backend/src/scheduler/SchedulerTask.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.test.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/backend/src/services/AsyncQueryService/types.ts
packages/backend/src/services/CsvService/CsvService.ts
packages/backend/src/services/MetricsExplorerService/MetricsExplorerService.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/authorization/jwtAbility.ts
packages/common/src/types/auth.ts
packages/common/src/types/queryHistory.ts
packages/common/src/types/scheduler.ts
packages/e2e/cypress/e2e/api/async-query.cy.ts
packages/e2e/cypress/e2e/app/explore.cy.ts
packages/e2e/cypress/support/commands.ts

This reverts commit 9356f4e354880d168139cc63e57ed2b3475580eb.
Closes: 
Reverting the revert from yesterday. 
1. The original PR (#15893) refactored AsyncQuery and Project services to use req.account instead of req.user for async query endpoints needed for embedded Explores. 
2. @almeidabbm [found a bug](https://lightdash.slack.com/archives/C02GQKJK84Q/p1753376104001839) I'd overlooked where we need Personal Access Token auth to be available
3. We reverted 1️⃣ (#16007)
4. Updated API Token and Service Account auth to create req.account (#16016)
5. Now we can reverse the reversal/revert the revert
Only changes from the original diff handled a merge conflict from the PR in 4️⃣ (#16016). Other than that, it's the same.

fix: Revert "fix: Revert "feat: refactor AsyncQuery and Project service to use account where needed for Embedded Explores (#15893)" (#16007)"

---

packages/backend/src/ee/clients/Slack/SlackClient.ts
packages/backend/src/ee/services/AiAgentService.ts

Closes: #15981
This PR fixes a bug where users couldn't up/downvote slack messages bc of an empty user id property
Key changes:
- Added user ID and organization UUID parameters to `updateHumanScoreForSlackPrompt`
- Properly passing user ID and organization data to analytics tracking

fix: handle empty analytics track of slack vote

---

examples/api/embedding.http
packages/backend/src/auth/CLAUDE.md
packages/backend/src/auth/account/account.ts
packages/common/src/authorization/buildAccountHelpers.ts
packages/common/src/authorization/index.ts
packages/common/src/authorization/parseAccount.ts
packages/common/src/types/auth.ts
packages/frontend/src/ee/providers/Embed/EmbedProvider.tsx
packages/frontend/src/hooks/user/useAccount.ts

Closes: #N/A
Foundational work for allowing abilities to power new embedded features. This gives us a hook to fetch the account and then use that entity to hydrate abilities using AbilityContext via the EmbedProvider. This works for both embed URLs and SDK. 
Enhances the embedding API example with a more comprehensive payload that includes user information and content permissions. Adds detailed documentation for the authentication module in a new CLAUDE.md file, explaining how to use session-based and JWT-based authentication.
Implements a new `buildAccountHelpers` utility in the common package to standardize account helper methods across the codebase. Creates a new `useAccount` hook in the frontend to fetch and properly construct account objects with abilities.
Updates the EmbedProvider …

feat: add useAccount hook

---

packages/backend/src/auth/lightdashJwt.test.ts
packages/backend/src/auth/lightdashJwt.ts
packages/backend/src/middlewares/jwtAuthMiddleware/jwtAuthMiddleware.test.ts
packages/backend/src/middlewares/jwtAuthMiddleware/jwtAuthMiddleware.ts
packages/frontend/sdk/index.tsx
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx
packages/frontend/src/components/Explorer/ResultsCard/ResultsCard.tsx
packages/frontend/src/components/Explorer/index.tsx
packages/frontend/src/ee/features/embed/EmbedDashboard/components/EmbedDashboard.tsx
packages/frontend/src/ee/features/embed/EmbedDashboard/components/EmbedDashboardChartTile.tsx
packages/frontend/src/ee/features/embed/EmbedDashboard/hooks.ts
packages/frontend/src/ee/features/embed/EmbedExplore/components/EmbedExplore.tsx
packages/frontend/src/ee/pages/EmbedExplore.tsx
packages/frontend/src/ee/providers/Embed/EmbedProvider.tsx
packages/frontend/src/ee/providers/Embed/context.ts
packages/frontend/src/ee/providers/Embed/types.ts
packages/frontend/src/ee/providers/Embed/useEmbed.ts
packages/frontend/src/hooks/useExplore.tsx
packages/frontend/src/hooks/useFieldValues.ts
packages/frontend/src/hooks/useProjectUuid.ts
packages/frontend/src/hooks/useProjects.ts
packages/frontend/src/hooks/useQueryResults.ts
packages/frontend/src/providers/Explorer/ExplorerProvider.tsx
packages/sdk-next-test-app/next.config.ts
packages/sdk-next-test-app/src/app/dashboard/yourCustomDashboardOne.tsx
packages/sdk-test-app/src/App.tsx

Closes: #15540
This PR adds the ability to explore charts from embedded dashboards. When a user clicks "Explore from here" on a chart in an embedded dashboard, they can now navigate to an embedded explore view for that chart. 
For now, this is enabled just for the React SDK, but we can easily enable this with an additional field in the JWT payload. 
- Added an `Explore` component to the SDK that can be used alongside the existing `Dashboard` component
- Added an `onExplore` callback to the Dashboard component that gets triggered when a user clicks "Explore from here"
- Moved the `JWT_HEADER_NAME` constant from backend to common package for better sharing
- Updated the Explorer components to work with project UUIDs from the embed context using `useEmbed`. 
- Added example implementations …

feat: use JWT token in explores for React SDK

---

packages/frontend/src/components/common/Filters/FilterInputs/FilterStringAutoComplete.tsx

Added error handling to `FilterStringAutoComplete`. When a field value query fails, the component now displays a red alert icon with a tooltip showing the error message.
Related to #16000

feat: improve UX for unavailable filters in dashboards

---

packages/e2e/cypress/e2e/api/catalog.cy.ts
packages/e2e/cypress/e2e/app/createProjects.cy.ts

This PR makes the E2E tests more resilient by replacing hardcoded expectations with dynamic checks:
1. In the catalog API test, replaced the expectation for exactly 21 tables with a check that there is at least 1 table
2. In the project creation test, updated the model count validation to use a regex pattern that accepts any number of models instead of expecting exactly 21 models
These changes will prevent test failures when the number of models in the test project changes.
test-frontend
test-backend

fix(test): make model number assertions generic

---

packages/frontend/src/ee/pages/AiAgents/ProjectAiAgentEditPage.tsx

Closes: #
Added an info tooltip to the Tags field in the AI Agent edit page. The tooltip explains that tags can be used to control which metrics and dimensions the AI agent can access, with a link to the documentation for more details.

chore: add helpful text on ai agent tags' input

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/savedCharts.ts

Relates to: #15996
Added support for parameters in subtotal calculations. This enhancement allows passing parameters to the `calculateSubtotals` endpoint, enabling parameter-based filtering in pivot tables with subtotals.
- Adding a `parameters` field to the `CalculateSubtotalsFromQuery` type
- Updating the ProjectService to handle parameters in subtotal calculations
- Passing parameters through the API routes and service methods

feat: support subtotals with parameters in backend

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationConfigTable.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/LightdashVisualization/types.ts
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AiChartVisualization.tsx
packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
packages/frontend/src/hooks/useCalculateTotal.ts
packages/frontend/src/hooks/useColumns.tsx
packages/frontend/src/pages/MinimalSavedExplorer.tsx

Relates to: #15996
Pass parameters to table visualization components to ensure proper calculation of totals in tables. This fix ensures that parameters are correctly propagated from dashboard contexts, chart visualizations, and explorer views to the underlying table calculation hooks.
The changes add a `parameters` prop to various visualization components and pass it through to the `useCalculateTotal` hook, which now includes these parameters in API requests for total calculations.

feat: support totals with parameters on the FE

---

examples/full-jaffle-shop-demo/dbt/lightdash.config.yml
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/schemas/json/lightdash-project-config-1.0.json
packages/common/src/types/lightdashProjectConfig.ts
packages/frontend/src/features/parameters/components/ParameterInput.tsx

Closes: #15995
Added support for custom values in project parameters by introducing the `allow_custom_values` property. This allows users to input values beyond the predefined options in parameter dropdowns.
Key changes:
- Added `allow_custom_values` flag to parameter schema in project config
- Updated parameter input components to support custom value entry when enabled
- Ensured both single-select and multi-select parameters support custom values
- Added proper UI for creating new parameter values with a consistent "Add [value]" label
- Updated the Jaffle Shop demo config to demonstrate this functionality
With options (multiple=false)
https://github.com/user-attachments/assets/2dadb778-3c9f-4dc7-9d19-a0988b956b96
With options (multiple=true) …

feat: add custom values support for parameter inputs

---

packages/frontend/src/hooks/useCalculateSubtotals.ts

Closes: 
Refactored `useCalculateSubtotals` hook to use the `useProjectUuid` hook instead of directly using `useParams` from react-router.  This created problems with the SDK because that component doesn't have route params for react-router to parse. We get the projectUuid via props—which are then saved and propagated via EmbedContext. 
[Slack context](https://lightdash.slack.com/archives/C097A5L6MV2/p1753788076866199?thread_ts=1753429757.377389&cid=C097A5L6MV2)

fix: use useProjectUuid for subtotals

---

packages/frontend/src/mantine8Theme.ts

Makes border radius consistent for `TextInput` with `Select` and other mantine 8 components.

fix: border style on TextInput mantine 8

---

packages/backend/src/database/entities/dashboards.ts
packages/backend/src/database/migrations/20250728131510_add-parameters-to-dashboards.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/DashboardModel/DashboardModel.mock.ts
packages/backend/src/models/DashboardModel/DashboardModel.ts
packages/common/src/types/dashboard.ts
packages/common/src/types/parameters.ts

Relates to: #16021 
Adds the ability to save parameter values with dashboards. This adds a dashboard parameters type and a column to the `dashboard_views` table to follow the pattern we have with filters.

chore: add parameters to dashboard creation

---

packages/backend/src/ee/services/AiAgentService.ts

Refactored the AiAgentService to reuse the existing `getExplore` method instead of duplicating explore filtering logic. This simplifies the `findExplore` function by leveraging the already implemented filtering functionality, improving code maintainability and reducing redundancy.

chore: reuse getExplore method in AiAgentService

---

packages/backend/src/services/CatalogService/CatalogService.ts
packages/backend/src/vitest.setup.integration.ts

Removed the unused `embedderFn` parameter from the `indexCatalog` method in the `CatalogService` class. Also added catalog indexing during integration test setup to ensure the catalog is properly indexed for tests.

chore: index catalog on integration test setup

---

packages/backend/src/utils/QueryBuilder/queryBuilder.test.ts
packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts
packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
packages/warehouses/src/warehouseClients/TrinoWarehouseClient.ts

Removed unnecessary escaping of special characters like `%`, `_` in SQL string escaping functions across all warehouse clients (PostgreSQL, BigQuery, Databricks, Snowflake, and Trino). These characters should not be escaped in regular SQL queries as they are only special in LIKE patterns.
Added tests to verify that regular characters are not escaped in PostgreSQL, ensuring that strings like "credit_card" remain unchanged when used in queries.
test-frontend
test-backend

fix: stop escaping SQL LIKE wildcards in string values

---

packages/frontend/src/components/AboutFooter.tsx

one more test of the `STYLE_GUIDE.md` on a more custom component
One-shot was mid successful:
Component prop name changes (position -> justify, spacing -> gap)
- It thought that underline wasn't needed (but mantine anchors only underline on hover)
- The docs button component had a darker grey background - are the greys between mantine 6 and the new theme different? I had to manually change it to a transparent background on the docs button - since that is how it looked before.
- Should it have used CSS modules here? There's lots of inline styling

chore: migrate AboutFooter to mantine 8

---

packages/frontend/sdk/package.json

Closes: #15541
Bumps the version of `@lightdash/sdk` from `0.1818.0` to `0.1855.1`.

feat: bump sdk version to match latest release

---

packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
packages/frontend/src/components/LightdashVisualization/index.tsx
packages/frontend/src/components/common/EmptyState/index.tsx

This PR fixes error handling in the Explorer by displaying errors from both the query and queryResults contexts. Previously, errors from queryResults were not being shown to users. Additionally, it removes the default value for the "subscription_status" parameter in the Jaffle Shop demo configuration.
The changes ensure that users will see appropriate error messages when either the query execution or the results processing encounters an issue, improving the overall error visibility in the Explorer interface.
**Before**
**After**

fix: error states in explorer

---

packages/e2e/cypress/e2e/app/dates.cy.ts
packages/frontend/src/components/AutoFetchResultsButton.tsx
packages/frontend/src/components/Explorer/ExplorerHeader/index.tsx
packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx
packages/frontend/src/components/Explorer/ResultsCard/CellContextMenu.tsx
packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx
packages/frontend/src/components/common/Filters/FilterRuleForm.tsx
packages/frontend/src/components/common/Filters/index.tsx
packages/frontend/src/ee/features/embed/EmbedExplore/components/EmbedExplore.tsx
packages/frontend/src/hooks/useExplorerRoute.ts
packages/frontend/src/hooks/useFilters.ts
packages/frontend/src/pages/ChartHistory.tsx
packages/frontend/src/pages/MinimalSavedExplorer.tsx
packages/frontend/src/pages/SavedExplorer.tsx
packages/frontend/src/providers/Explorer/ExplorerProvider.test.tsx
packages/frontend/src/providers/Explorer/ExplorerProvider.tsx
packages/frontend/src/providers/Explorer/defaultState.ts
packages/frontend/src/providers/Explorer/types.ts

Closes: #10080
Added an auto-fetch toggle button that allows users to enable/disable automatic query execution when making changes to the explorer. This gives users more control over when queries are run, especially useful for complex or resource-intensive queries.
The auto-fetch button appears in the Explorer header, with a tooltip indicating the current status. When enabled (default), queries run automatically as before. When disabled, users must manually click the refresh button to execute queries.
Auto fetch results setting is saved in the local storage.
Complete removed `shouldFetchResults` boolean from `exploreProvider`

feat: add auto run results setting in explore

---

packages/frontend/src/hooks/dashboard/useDashboardChartReadyQuery.ts

Closes: #15992 
Only reload relevant charts when a param changes. 
This works well. I thought there was an issue, but the issue was in the SQL definitions. One thing that is a little strange is that when react query has the old values cached, the charts update, but there is no spinner. I'm not sure if it's worth doing much about that.

feat: only reload relevant charts on param change

---

packages/backend/src/models/DashboardModel/DashboardModel.test.ts
packages/backend/src/models/DashboardModel/DashboardModel.ts

Closes: #16139
Added sortBy for `[y, x]` columns to preserve the order, which was otherwise randomised for the customer.

feat: add orderBy for dashboard tiles for consistent order & update test

---

packages/backend/src/controllers/exploreController.ts
packages/backend/src/controllers/organizationController.ts
packages/backend/src/controllers/projectController.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/routers/projectRouter.ts
packages/backend/src/services/GdriveService/GdriveService.ts
packages/backend/src/services/OrganizationService/OrganizationService.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts

Closes: #N/A
Pulled out of the [PR](https://github.com/lightdash/lightdash/pull/16118) for enabling explores in embedded iframes 
Refactored authentication to use `req.account` instead of `req.user` in organization and project controllers. 
test-frontend
test-backend

feat: refactor Project and Organaization services to enable iframe explores

---

packages/backend/src/database/migrations/20250728120551_add_index_on_yaml_tags_in_catalog_search.ts

Added a GIN index on the `yaml_tags` column in the `catalog_search` table to improve query performance when filtering by tags. This migration creates the index in the `up` function and removes it in the `down` function for rollback capability.

feat: add GIN index on yaml_tags in catalog_search table

---

packages/backend/src/config/aiConfigSchema.ts
packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/ee/services/AiAgentService.ts

Closes: #16162
We were using `LIGHTDASH_QUERY_MAX_LIMIT` in agents as maxlimit for queries, but we have a different limit `AI_DEFAULT_MAX_QUERY_LIMIT` for viz queries validations. These two were different (10k for ld max limit, 1k  for ai max query) causing errors.
This PR unifies this and introduces a new maxQuery config at config schema level.

fix: agent generates queries with limits > 1000

---

packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts

Fix BigQuery client initialization by handling empty location strings. When the `location` credential is an empty string, it's now treated as `undefined` to avoid invalid value errors from the BigQuery client.

fix: handle empty string location in BigQuery client config

---

packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/ee/services/ai/agents/agent.ts
packages/backend/src/ee/services/ai/tools/findExplores.ts
packages/backend/src/ee/services/ai/tools/findFields.ts
packages/backend/src/ee/services/ai/types/aiAgent.ts
packages/backend/src/ee/services/ai/types/aiAgentDependencies.ts

Refactored AI agent configuration to use explicit parameters instead of hardcoded values. This change:
- Added configurable parameters for search result sizes in AI agent tools
- Created proper type definitions for AI agent arguments and dependencies
- Replaced hardcoded values with configurable parameters for:
- Field search sizes
- Page sizes for explore and field searches
- Maximum description length
- Query limits
This makes the AI agent behavior more configurable and removes TODOs that were previously in the code.

feat: refactor AI agent with configurable search parameters

---

packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/ee/services/ai/agents/agent.ts
packages/backend/src/ee/services/ai/prompts/system.ts
packages/backend/src/ee/services/ai/tools/findExplores.ts
packages/backend/src/ee/services/ai/types/aiAgent.ts
packages/backend/src/ee/services/ai/types/aiAgentDependencies.ts

Enhances the AI agent system by adding available explores to the system prompt. This allows the agent to be aware of all available data sources from the start of the conversation.
Key changes:
- Added `includeFields` parameter to control whether field details are fetched with explores
- Made field search parameters optional when fields aren't needed
- Added validation to ensure required parameters are provided when fields are requested
- Implemented a new parameter `availableExploresPageSize` to control how many explores are loaded for the system prompt
- Modified the system prompt to include a list of all available explores
- Updated the agent initialization to fetch available explores before generating responses
This improvement helps the AI agent provide more accurate and contextual …

feat: include available explores in the system prompt

---

packages/backend/src/ee/services/ai/tools/findFields.ts
packages/common/src/ee/AiAgent/schemas/fieldType.ts
packages/common/src/ee/AiAgent/schemas/filters/booleanFilters.ts
packages/common/src/ee/AiAgent/schemas/filters/dateFilters.ts
packages/common/src/ee/AiAgent/schemas/filters/index.ts
packages/common/src/ee/AiAgent/schemas/filters/numberFilters.ts
packages/common/src/ee/AiAgent/schemas/filters/stringFilters.ts
packages/common/src/types/catalog.ts
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentVisualizationFilters.tsx

Refactored filter schemas to include type information directly in the schema objects rather than in a separate target object. This simplifies the filter rule structure by:
1. Adding a `type` field to each filter schema (boolean, date, number, string)
2. Flattening the filter rule structure by removing the nested `target` and `rule` objects
3. Moving `fieldId` to the top level of the filter rule
4. Restructuring the schema transformation to match the new flattened structure
This change makes the filter schemas more consistent and easier to work with while maintaining the same validation capabilities.

refactor: restructure filter schemas with type literals for better validation

---

packages/backend/src/ee/services/ai/utils/validators.ts
packages/common/src/ee/AiAgent/schemas/filters/index.ts

Closes: #16188
Enhanced filter validation in AI services by implementing type-specific validation for filter rules. The PR adds validation logic for boolean, date, timestamp, number, and string filter types, ensuring that filter rules match the expected field type before attempting to render SQL. Additionally, exports filter schema objects from the common package to make them accessible for validation purposes.

feat: validate filter type against field type

---

examples/full-jaffle-shop-demo/dbt/lightdash.config.yml
examples/full-jaffle-shop-demo/dbt/models/subscriptions.yml

Update Subscriptions model with params that have `multiple` and `allow_custom_values` props. We supported these, but they weren't in the demo data. So this if for testing and using those features.
Not that there is currently a bug where one of these doesn't show up: #16191

chore: update subscriptions with multiple and custom params

---

packages/backend/src/ee/services/ai/utils/validators.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/ee/AiAgent/schemas/filters/index.ts
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentVisualizationFilters.tsx

Added `fieldFilterType` to the AI agent filter rule schema to properly handle filter types in agent visualizations. This ensures that filter rules created by AI agents include the necessary filter type information, allowing the UI to correctly display and process these filters without having to derive the filter type from the field type.

fix: add fieldFilterType to AiFilterRule for improved filtering

---

packages/backend/src/services/GitIntegrationService/GitIntegrationService.ts

Fixed error handling in `GitIntegrationService`, now throws specific error types instead of generic ones. Users get clearer error messages, like when they need to compile before writing custom fields back to their project.

fix: improve error handling in git integration

---

packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/common/src/compiler/filtersCompiler.mock.ts
packages/common/src/compiler/filtersCompiler.test.ts
packages/common/src/compiler/filtersCompiler.ts
packages/frontend/src/components/common/Filters/FilterRuleForm.tsx

Closes: #16043, #7083
Improved handling of empty filter values in SQL generation. 
1. String filters with empty values now return `true` instead of generating invalid SQL
2. String filters with mixed empty and non-empty values properly filter out the empty strings
3. Number filters with empty or insufficient values (e.g., only one value for IN_BETWEEN) now return `true`
~~todo: Validate correct usage of `''` strings, as it can be a valid filter~~ We don't support filter by empty strings atm
| Before | After |
|--------|--------|
| ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/HorFj8gm8QUuuIDE2vgk/50060d71-220c-4be6-a902-f7c33f66e5e9.png) | ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/HorFj8gm8QUuuIDE2vgk/e4ebdc92-07dc-4e15-820f-8e6f923 …

fix: Empty filters apply placeholder values

---

packages/frontend/src/components/common/Filters/FilterInputs/FilterNumberRangeInput.tsx

Closes: #16043
Improved `FilterNumberRangeInput` validation. The component now validates that both min and max values are provided in addition to the current min/max validation.
I've also improved how the error message is rendered
<details><summary> screenshots 📸 </summary>
<p>
</p>
</details>

fix: range input filter properly indicates missing values

---

packages/frontend/src/providers/Explorer/ExplorerProvider.tsx

Closes: #16205
Prevents auto-fetching in edit mode until the first query is run. This change adds a check for `query.isFetched` in the condition that determines whether to run a query automatically, ensuring that auto-fetching only starts after the user has manually run a query at least once.
**With auto-fetch: true (only auto fetches after running query)**
https://github.com/user-attachments/assets/7411a24c-4940-4f0b-ad21-efcff14df864
**With auto-fetch: false (no change)**
https://github.com/user-attachments/assets/34d9331c-3e67-44b4-93da-580f8f084d1e

fix: only run query after first run even if auto-fetch is enabled

---

packages/frontend/src/App.tsx
packages/frontend/src/features/dateZoom/components/DateZoom.module.css
packages/frontend/src/features/dateZoom/components/DateZoom.tsx
packages/frontend/src/index.tsx

Upgrades the date zoom component to mantine 8. Why now? It's next to the new parameter component which uses mantine 8. Here's how it looks now:
Before
Edit mode before/after

chore: upgrade date zoom component to mantine 8

---

packages/backend/src/ee/services/ai/tools/findExplores.ts
packages/backend/src/ee/services/ai/types/aiAgentDependencies.ts

related to: https://github.com/lightdash/lightdash/issues/16232
This PR optimizes the `findExplores` AI tool to only fetch fields when a specific explore is requested. It updates the tool to:
1. Make fields optional in the response type
2. Only include fields in the response when an explore name is provided
3. Only render the Fields section in the response when dimensions and metrics are available
4. Update the tool description to better reflect its behavior
This change improves performance by avoiding unnecessary field fetching when browsing the list of available explores.
CONTEXT: https://lightdash.slack.com/archives/C08S88JT17W/p1754465077895719

feat: only show metrics/dimensions overview when focusing on explore

---

packages/backend/src/ee/database/entities/aiAgent.ts
packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/vitest.setup.integration.ts
packages/common/src/ee/AiAgent/index.ts
packages/frontend/src/components/ProjectAccess/ProjectAccess.tsx
packages/frontend/src/components/ProjectAccess/ProjectAccessRow.tsx
packages/frontend/src/components/ProjectAccess/RemoveProjectAccessModal.tsx
packages/frontend/src/ee/pages/AiAgents/ProjectAiAgentEditPage.tsx
packages/frontend/src/hooks/useProjectUsersWithRoles.ts

Closes: #10245
This PR adds user-level access control for AI Agents, allowing specific users to be granted access to an agent regardless of their group membership. The implementation includes:
1. Updated the AI Agent model to include user access in queries and CRUD operations
2. Enhanced the access check logic in `AiAgentService` to verify user access alongside group access
3. Updated the frontend to allow selecting specific users when creating or editing an AI agent
> [!NOTE]
> Created a reusable hook to get the _final_ role a user has. For example, a user might be org editor but downgraded to project viewer - the highest role is respected!
This provides more granular control over who can access AI agents, especially useful for giving access to specific users who may not be in groups …

feat: enable ai agent user access

---

packages/backend/src/ee/index.ts
packages/backend/src/ee/services/McpService/McpService.ts
packages/backend/src/ee/services/ai/tools/findExplores.ts
packages/backend/src/models/CatalogModel/CatalogModel.ts

Related to: #16199
Adds support for the `find_explores` tool to the Model Context Protocol (MCP) service. This tool allows MCP clients to search for explores and their fields in Lightdash projects.
The implementation:
- Adds necessary dependencies to the McpService constructor
- Implements the `setupHandlers` method to register the find_explores tool
- Creates a `getFindExploresFunction` method that leverages the catalog service to search for tables and fields
- Adds a new `MCP` context type to the CatalogSearchContext enum

feat: add find_explores tool to MCP service

---

packages/backend/src/ee/services/McpService/McpService.ts
packages/backend/src/ee/services/ai/tools/findFields.ts

Closes: #16199
Added a new MCP tool for finding fields in explores. This implementation registers a `FIND_FIELDS` tool in the MCP service that allows users to search for fields (metrics and dimensions) within explores. The tool includes functionality to search by field name, filter by table, and supports pagination of results.
- New `FIND_FIELDS` enum in McpToolName
- Registration of the tool with proper schema validation
- Implementation of the `getFindFieldsFunction` to handle field search requests
- Reuse of existing field search functionality from the catalog service

feat: add findFields tool to MCP service

---

packages/backend/src/ee/index.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/ee/services/ai/agents/agent.ts
packages/backend/src/ee/services/ai/prompts/system.ts
packages/backend/src/ee/services/ai/tools/findDashboards.ts
packages/backend/src/ee/services/ai/types/aiAgent.ts
packages/backend/src/ee/services/ai/types/aiAgentDependencies.ts
packages/backend/src/models/SearchModel/index.ts
packages/common/src/ee/AiAgent/schemas/index.ts
packages/common/src/ee/AiAgent/schemas/tools/index.ts
packages/common/src/ee/AiAgent/schemas/tools/toolFindDashboardsArgs.ts
packages/common/src/ee/AiAgent/schemas/visualizations/index.ts
packages/common/src/types/search.ts
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatAssistantBubble.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/AiChartToolCalls.tsx

Closes: #16217
Added dashboard search capability to the AI Copilot, allowing users to find existing dashboards through natural language queries. The AI assistant can now search for dashboards by name or description and return results with clickable links.
Key changes:
- Created a new `findDashboards` tool that searches for dashboards using the SearchModel
- Updated system prompts to guide the AI in handling dashboard search requests
- Added proper rendering of dashboard links in the chat interface
- Enhanced the AI's decision-making to determine when to search for dashboards vs. create new visualizations
- Implemented pagination for dashboard search results
demo convo:

feat: add find_dashboards tool

---

packages/backend/src/controllers/CLAUDE.md
packages/backend/src/controllers/v2/QueryController.ts
packages/backend/src/generated/swagger.json

Closes:
Standardized API documentation format across controllers by:
1. Simplified controller documentation in CLAUDE.md by removing redundant example code
2. Added requirement for JSDoc comments with `@summary` and `@description` tags
3. Reformatted all QueryController endpoint documentation to follow the new standard:
- Concise `@summary` (2-3 words)
- Brief `@description` that explains the endpoint's purpose
These changes make the API documentation more consistent and easier to maintain while improving the generated Swagger documentation.

docs: standardize API endpoint JSDoc comments with @summary

---

examples/full-jaffle-shop-demo/dbt/models/payments.yml
packages/backend/package.json
packages/backend/src/ee/services/ai/agents/tests/agent.integration.test.ts
packages/backend/src/vitest.setup.integration.ts

Added integration tests for agent relevancy and factuality evaluations. The tests verify that the agent can find relevant information from the correct explore and provide factual answers to user questions. Two test cases are included:
1. A query about order amounts broken down by completion status month over month
2. A query about revenue for credit card payments in the last 3 months
The tests use LLM-based evaluation metrics to assess context relevancy and answer factuality. Also fixed a user ID inconsistency in the test setup by using the userUuid instead of a hardcoded ID.

feat: add agent integration tests for query relevancy evaluation

---

packages/backend/src/utils/QueryBuilder/SqlQueryBuilder.mocks.ts
packages/backend/src/utils/QueryBuilder/SqlQueryBuilder.test.ts
packages/backend/src/utils/QueryBuilder/SqlQueryBuilder.ts
packages/backend/src/utils/QueryBuilder/utils.ts

Closes: #12574
Brings back functionality from https://github.com/lightdash/lightdash/pull/12647 which fixed https://github.com/lightdash/lightdash/issues/12574 and was removed in https://github.com/lightdash/lightdash/pull/15986
- Extracts and handles LIMIT/OFFSET clauses from subqueries
- Preserves OFFSET values when present in subqueries
- Uses the minimum value when both the subquery and outer query specify LIMIT values
- Includes comprehensive test cases for various LIMIT/OFFSET scenarios
**Sql Runner Sql**
```sql
SELECT * FROM "SNOWFLAKE_LEARNING_DB"."PUBLIC"."TRACKS_RAW" LIMIT 3;
```
**Before**
```sql
SELECT
"USER_ID" AS "USER_ID",
"EVENT_ID" AS "EVENT_ID",
"EVENT_NAME" AS "EVENT_NAME",
"EVENT_TIMESTAMP" AS "EVENT_TIMESTAMP"
FROM (
SELECT * FROM …
```

fix: extract limit clause from subquery and add it at the end of the sql

---

packages/backend/src/ee/index.ts
packages/backend/src/ee/services/McpService/McpService.ts
packages/backend/src/ee/services/ai/tools/findDashboards.ts

Closes: #16243
Added a new MCP tool for finding dashboards. This tool allows users to search for dashboards by name or description within a project. The implementation includes:
- Added a new `FIND_DASHBOARDS` enum to the McpToolName
- Registered the new dashboard search tool with the MCP server
- Implemented the `getFindDashboardsFunction` to handle dashboard search requests
- Ensured proper access control by filtering results based on user permissions

feat: add find_dashboards tool to MCP service

---

packages/common/src/types/parameters.ts
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/pages/Dashboard.tsx
packages/frontend/src/providers/Dashboard/DashboardProvider.tsx
packages/frontend/src/providers/Dashboard/types.ts

Closes: #16233 
Show the parameter label (instead of key) on dashboard tiles.

feat: show parameter label on tiles

---

packages/backend/src/scheduler/SchedulerClient.ts
packages/backend/src/scheduler/SchedulerWorker.ts
packages/common/src/types/errors.ts

Closes: #16251
Improves the reliability of scheduled jobs by:
1. Adding a new method to delete overlapping scheduled jobs before creating new ones, preventing duplicates if the `generateDailyJobs` task runs multiple times or retries
2. Enhancing error handling in the scheduler worker to:
- Continue processing other schedulers even if one fails
- Log detailed error information for each failed scheduler
- Only throw an exception if all schedulers fail
3. Creating a new `GenerateDailySchedulerJobError` class to provide better error context
This change makes the scheduler more resilient by ensuring jobs aren't duplicated and allowing partial success when some schedulers encounter issues.
Sample error when it fails:

fix: duplicate scheduler jobs when there are errors generating daily jobs

---

packages/backend/src/ee/services/ai/tools/generateTableVizConfig.ts

Closes: #N/A
Reordered the logic in `generateTableVizConfig.ts` to ensure CSV files are always sent to Slack when it's a Slack prompt, regardless of row count. Previously, the single row check would return early before the Slack file sending logic could execute.
This fix ensures that Slack users will receive the CSV file attachment for all query results that require a table

fix: unlock csv file attachment

---

packages/frontend/src/features/preview/components/PreviewAndCustomizeScreenshot.tsx
packages/frontend/src/features/scheduler/components/SchedulerPreview.tsx

Closes: #16322
Added the ability to display the current preview in the Scheduler Preview component. The component now maintains the current preview URL in its state and passes it to the child components, enabling users to see their scheduled dashboard preview.
- Added state to track the current preview URL
- Updated the preview click handler to store the returned URL
- Passed the current preview URL to child components for display
To test here: 
> [!NOTE]
> Added top right button to show full screen mode. user can still click anywhere on the image to do the same

fix: get screenshot on preview and size tab

---

packages/frontend/sdk/index.tsx
packages/frontend/sdk/package.json
packages/frontend/src/components/DashboardTiles/DashboardMarkdownTile.tsx
packages/frontend/src/index.tsx
packages/sdk-next-test-app/package.json
packages/sdk-next-test-app/postcss.config.json
packages/sdk-next-test-app/src/app/dashboard/yourCustomDashboardOne.tsx
packages/sdk-test-app/src/App.tsx
pnpm-lock.yaml

Closes: 
Updates the SDK package.json exports configuration to include a default export and properly expose CSS styles through a dedicated path. Moves Mantine 8 styles import to the main SDK index file. Updates the SDK test app to import styles from the new SDK CSS path.

refactor: update SDK package exports and CSS imports

---

packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.test.ts
packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.test.ts
packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts

Closes: #16257
Closes: #16362
BigQuery and Databricks SQL builders were incorrectly treating `#` symbols in string values as SQL comments and removing them. This caused issues when column names or data values legitimately contained `#` characters (e.g., hashtags, identifiers, etc.).
test-cli
test-backend
test-frontend

fix: remove escape of #... in databricks and bigquery

---

packages/backend/src/ee/controllers/aiAgentController.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/ee/AiAgent/index.ts
packages/frontend/src/ee/features/aiCopilot/hooks/useUserAgentPreferences.ts
packages/frontend/src/ee/pages/AiAgents/AiExploreAccessTree.tsx
packages/frontend/src/ee/pages/AiAgents/ProjectAiAgentEditPage.tsx

Closes: #16314
This PR adds a new endpoint and UI for AI agents to view explore access summaries. It allows users to see which explores, dimensions, and metrics an AI agent can access based on selected tags.
- New API endpoint `/explore-access-summary` to retrieve explore access information
- New React component `AiExploreAccessTree` to display the explore data in a tree view
- Integration with the agent edit page to show available explores based on selected tags
- Collapsible UI to show detailed metrics and dimensions for each explore

feat: add explore access summary for AI agents

---

packages/frontend/src/ee/pages/AiAgents/ProjectAiAgentEditPage.tsx

Closes: N/A
Reorganized the AI Agent edit page by creating a dedicated "Access control" section with a lock icon. Moved user/group selection controls and tags input into this new section to improve the UI organization and make access management more intuitive.
The change separates configuration concerns, placing access control settings in their own distinct paper component rather than mixing them with general agent settings.

refactor: move access controls to separate section in AI agent edit page

---

packages/frontend/src/components/RenderedSql.tsx

Closes: #16371 
Formatting fails with invalid (not normal) SQL. One way to cause this is to have a Parameter in your query. We are also seeing it in user reports. This just catches the error on formatting and returns the original error. 
To test
- Select Subscriptions model
- Select 'Filtered Subscriptions'
- Open SQL card
- On main it will error

fix: catch error in sql formatter

---

packages/backend/src/@types/knex-tables.d.ts
packages/backend/src/database/entities/roles.ts
packages/backend/src/database/migrations/20250807212731_add_custom_roles.ts
packages/common/src/index.ts
packages/common/src/types/roles.ts

Closes: #16280 (The parent issue has the related sub-issues that will be a part of this stack)
Adds database schema for custom roles and permissions system with three new tables:
1. `roles` - Stores organization-specific roles with name and description
2. `scopes` - Defines available permissions (resource + action combinations)
3. `scoped_roles` - Join table linking roles to their granted permissions
The migration initializes the system with common permission scopes for organization management, projects, dashboards, charts, spaces, exports, and AI agents.
This is the first go at adding roles. We'll have a subsequent migration as well to add more roles, as well as an update to the seed the database correctly for e2e tests. 
I move scope definitions out to a separate PR: …

feat: add migration for custom roles

---

.github/workflows/release-on-merge.yml
package.json
packages/frontend/package.json
release.config.js

Closes: 
Tested semantic release in Alpha branch https://github.com/lightdash/lightdash/pull/16358
Add frontend SDK to the release process by including it in the build and release scripts. The changes include:
1. Adding a comment in the release workflow to indicate that configuration is in release.config.js
2. Updating the build-published-packages script to also build the frontend SDK
3. Adding the frontend package to the release-packages script
4. Creating a release script in the frontend package.json for SDK publishing
5. Including the frontend SDK package.json in the release configuration
These changes ensure that the frontend SDK is properly built and published as part of the release process.

fix: add frontend SDK to release process

---

packages/frontend/sdk/index.tsx
packages/frontend/src/index.tsx
packages/frontend/src/providers/MantineProvider.tsx

Moved the Mantine CSS import from the MantineProvider component to the entry points of the application. This ensures that the styles are loaded at the root level in both the main application and the SDK.

fix: move Mantine styles import to entry points

---

packages/frontend/src/ee/features/embed/EmbedDashboard/components/EmbedDashboard.tsx

Closes: #16384
Removed `Group` wrapper around `EmbedDashboardGrid` component in the embedded dashboard view. The comment indicated the wrapper was for respecting position inside the Embed SDK, but it appears to have been causing width calculation problems with the Grid component. 
The first tab rendered would be collapsed without any width. After switching tabs, we'd get a wider canvas, but still narrower than it should be.

fix: remove Group from embedded tabbed dashboard

---

CLAUDE.md
packages/backend/src/ee/services/ai/tools/findCharts.ts
packages/backend/src/ee/services/ai/tools/findDashboards.ts
packages/backend/src/models/SearchModel/index.ts
packages/common/src/types/search.ts

Closes: #16313
Enhances AI tools with richer chart and dashboard metadata
1. Updates `findCharts` and `findDashboards` to include additional metadata:
- View counts
- First viewed date
- Last modified date
- Creator information
- For dashboards: embedded chart details

feat: add metadata to chart/dashboard search results

---

packages/common/src/authorization/jwtAbility.test.ts
packages/common/src/authorization/jwtAbility.ts
packages/common/src/types/auth.ts
packages/e2e/cypress/e2e/app/embed.cy.ts
packages/frontend/sdk/index.tsx
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/DashboardTiles/UnderlyingDataMenuItem.tsx
packages/frontend/src/ee/features/embed/EmbedDashboard/api.ts
packages/frontend/src/ee/features/embed/EmbedDashboard/components/EmbedDashboardChartTile.tsx
packages/frontend/src/ee/features/embed/EmbedDashboard/hooks.ts
packages/frontend/src/ee/features/embed/SettingsEmbed/EmbedCodeSnippet.tsx
packages/frontend/src/ee/features/embed/SettingsEmbed/EmbedUrlForm.tsx
packages/frontend/src/ee/providers/Embed/EmbedProvider.tsx
packages/frontend/src/hooks/dashboard/useDashboardChartReadyQuery.ts
packages/frontend/src/hooks/useUnderlyingDataResults.ts

Closes: #9605
This PR enables "View underlying data" for SDK and iframe embeds. It begins the process of moving Dashboards to use async-queries rather than embed endpoints for querying data.
1. Create a new JWT with the claim
2. Startup the SDK test app
3. Use the token
4. Change localizations
1. Create the JWT with the claim
2. Test in preview mode
3. Test with generating a URL in a separate window to not use session cookies

feat: enable 'viewUnderlyingData' for iframe and SDK embeds

---

packages/backend/src/ee/services/ai/tools/findDashboards.ts
packages/backend/src/models/SearchModel/index.ts
packages/common/src/types/search.ts

Added chart UUIDs and URLs to dashboard search results to improve AI assistant functionality.
1. Added the chart UUID to the dashboard search results data structure
2. Modified the SQL queries to include the saved_query_uuid in chart results
3. Enhanced the dashboard text representation to include chart URLs with proper linking to the project and chart view

feat: add chart URLs to dashboard search results

---

packages/frontend/CLAUDE.md
packages/frontend/STYLE_GUIDE.md
packages/frontend/sdk/index.tsx
packages/frontend/src/App.tsx
packages/frontend/src/components/AboutFooter.tsx
packages/frontend/src/components/Explorer/ParametersCard/ParametersCard.tsx
packages/frontend/src/components/PinnedParameters.tsx
packages/frontend/src/components/ProjectParameters/ProjectParameters.tsx
packages/frontend/src/components/RefreshButton.tsx
packages/frontend/src/components/SqlRunner/RunSqlQueryButton.tsx
packages/frontend/src/components/UserSettings/ProfilePanel/index.tsx
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/InvitesModal.tsx
packages/frontend/src/components/common/Tree/Tree.tsx
packages/frontend/src/components/common/Tree/TreeItem.tsx
packages/frontend/src/ee/CommercialRoutes.tsx
packages/frontend/src/features/dateZoom/components/DateZoom.tsx
packages/frontend/src/features/parameters/components/Parameters.tsx
packages/frontend/src/features/scheduler/components/SchedulerParameters.tsx
packages/frontend/src/pages/Dashboard.tsx
packages/frontend/src/providers/Mantine8Provider.tsx

Centralized Mantine v8 theme provider implementation by creating a global `Mantine8Provider` component that wraps the application. This eliminates the need to wrap individual components with `MantineProvider` and pass the theme override in multiple places.
Key changes:
- Created a new `Mantine8Provider` component that uses the global theme from `getMantine8ThemeOverride()`
- Added the provider to the main App and SDK entry points
- Removed redundant `MantineProvider` wrappers from individual components
- Updated style guide documentation to remove the requirement for wrapping components with `MantineProvider`
This change improves code maintainability by centralizing theme management and reduces boilerplate code throughout the application.

feat: add global Mantine8Provider to simplify component theming

---

packages/common/src/types/timezone.ts
packages/e2e/cypress/e2e/app/dates.cy.ts
packages/frontend/src/components/Explorer/SaveChartButton/index.tsx
packages/frontend/src/components/RefreshDbtButton/index.tsx
packages/frontend/src/components/common/ShareShortLinkButton/index.tsx
packages/frontend/src/components/common/TimeZonePicker/index.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx
packages/frontend/src/features/sync/components/SyncModalForm.tsx
packages/frontend/src/providers/Explorer/ExplorerProvider.tsx
packages/frontend/src/providers/Explorer/types.ts

Closes: 
Migrated several components to use Mantine 8 by:
- Updated imports from `@mantine/core` to `@mantine-8/core`
- Added `MantineProvider` with theme override to components
- Changed `leftIcon` prop to `leftSection`
- Replaced `sx` prop with `style` prop
- Updated styling syntax to match Mantine 8 requirements
**Before**
**After**

chore: migrate explore header buttons to mantine 8

---

packages/backend/src/ee/services/EmbedService/EmbedService.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/ProjectService/parameters.ts

This PR adds support for explore-specific default parameter values. Now when combining parameters, the system considers values from multiple sources in order of priority:
1. Request parameters (highest priority)
2. Saved chart/dashboard parameters
3. Default explore parameters values
4. Default project parameters values (lowest priority)
The `combineParameters` method now accepts an optional `explore` parameter, which is used to extract default parameter values from the explore's tables. This ensures that explore-specific parameter defaults are properly applied when executing queries.
**Before**
**After**

fix: add explore to combine parameters

---

packages/backend/src/services/GdriveService/GdriveService.ts
packages/backend/src/services/SchedulerService/SchedulerService.ts
packages/common/src/authorization/organizationMemberAbility.ts
packages/common/src/authorization/projectMemberAbility.ts
packages/common/src/authorization/scopes.ts
packages/common/src/authorization/types.ts
packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/features/export/components/ExportToGoogleSheet.tsx

Closes: #XXXX
Added permission checks for Google Sheets integration to ensure only authorized users can access this feature. This PR introduces a new 'GoogleSheets' subject in the authorization system with 'manage' permissions that are granted to organization members and project members.
- Added permission checks in GdriveService to verify user can manage Google Sheets
- Added permission validation in SchedulerService for Google Sheets format
- Created new 'manage:GoogleSheets' scope in the authorization system
- Updated organization and project member abilities to include Google Sheets permissions
- Added UI checks to hide Google Sheets export options for unauthorized users

fix: add Google Sheets permission controls

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/authorization/scopeAbilityBuilder.test.ts
packages/common/src/authorization/scopes.ts
packages/frontend/src/components/Explorer/ExplorePanel/index.tsx

Closes: 
We added 2 new scopes : create and delete virtualviews
Existing old roles will keep using manage:virtualView, so they will be able to create or delete virtual views
Tested updating old roles:
With create only (but not delete):
With manage: 
Added two new authorization scopes for virtual views: `create:VirtualView` and `delete:VirtualView`. These granular permissions will allow for more fine-grained access control when working with virtual views, complementing the existing `manage:VirtualView` scope.

fix: add create and delete scopes for VirtualView

---

packages/backend/src/clients/EmailClient/EmailClient.mock.ts
packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/ee/services/EmbedService/EmbedService.ts
packages/backend/src/models/FeatureFlagModel/FeatureFlagModel.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/utils/QueryBuilder/MetricQueryBuilder.test.ts
packages/backend/src/utils/QueryBuilder/MetricQueryBuilder.ts
packages/common/src/types/featureFlags.ts
packages/frontend/src/components/Explorer/ExplorerHeader/index.tsx

Closes: [#16473](https://github.com/lightdash/lightdash/issues/16473)
Closes: [#16471](https://github.com/lightdash/lightdash/issues/16471)
Removes the experimental `showQueryWarnings` feature flag and makes metric deduplication with CTEs the default behavior. This change:
1. Removes the `showQueryWarnings` configuration option from the LightdashConfig
2. Removes the `ShowQueryWarnings` feature flag
3. Makes the CTE-based metric deduplication approach the default in MetricQueryBuilder
4. Updates the query building process to always check for and display query warnings
5. Removes the conditional display of query warnings in the Explorer UI
This change improves query accuracy by default by preventing metric inflation due to join relationships.
**Also fixes the issue with wrong totals in …

refactor: remove showQueryWarnings feature flag and enable metric deduplication by default

---

packages/common/src/compiler/exploreCompiler.ts
packages/common/src/compiler/parameters.test.ts
packages/common/src/compiler/parameters.ts
packages/common/src/utils/loadLightdashProjectConfig.ts

Enhances parameter name validation to reject more invalid characters beyond just dots. Parameter names must now match the pattern `/^[a-zA-Z0-9_-]+$/`, allowing only alphanumeric characters, underscores, and hyphens.
The PR:
- Updates the validation logic in `validateParameterNames()` to use a regex pattern
- Adds comprehensive tests for parameter name validation
- Updates error messages to be more generic (removes specific mention of dots)
This change helps prevent issues with parameter names that could cause problems in queries or UI rendering.

chore: improve parameter name validation

---

packages/backend/src/ee/database/entities/aiArtifacts.ts
packages/backend/src/ee/models/AiAgentModel.ts
packages/common/src/ee/AiAgent/index.ts

Adds AI artifact management functionality to support chart artifacts. This PR:
- Restricts `artifact_type` to only accept 'chart' value in the database schema
- Implements CRUD operations for AI artifacts in the `AiAgentModel` class:
- `createArtifact`: Creates a new artifact with its first version
- `createArtifactVersion`: Adds a new version to an existing artifact
- `createOrUpdateArtifact`: Creates or updates an artifact based on thread UUID
- `getArtifact`: Retrieves an artifact by UUID
- `getArtifactByPromptUuid`: Retrieves an artifact by prompt UUID
- `getArtifactByThreadUuid`: Retrieves an artifact by thread UUID
- `findArtifactByThreadUuid`: Safely finds an artifact by thread UUID (returns null if not found)
- Defines the `AiArtifact` type in the common package to be used across …

feat: add AI artifacts model

---

examples/api/ai-agents.http
packages/backend/src/ee/controllers/aiAgentController.ts
packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/ee/services/ai/agents/agent.ts
packages/backend/src/ee/services/ai/tools/generateBarVizConfig.ts
packages/backend/src/ee/services/ai/tools/generateTableVizConfig.ts
packages/backend/src/ee/services/ai/tools/generateTimeSeriesVizConfig.ts
packages/backend/src/ee/services/ai/types/aiAgent.ts
packages/backend/src/ee/services/ai/types/aiAgentDependencies.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/ee/AiAgent/index.ts
packages/frontend/src/ee/features/aiCopilot/hooks/useOrganizationAiAgents.ts

This PR adds support for AI agent artifacts, allowing charts generated by AI to be stored and retrieved. It introduces a new endpoint `/api/v1/projects/:projectUuid/aiAgents/:agentUuid/artifacts/:artifactUuid` to fetch artifacts by UUID
The implementation updates the chart generation tools (bar, table, time series) to create artifacts when generating visualizations, storing metadata like title, description, and visualization configuration. This enables persistent storage of AI-generated charts that can be accessed independently of the conversation thread.
⚠️ Change is backwards-compatible so can be tested out from the existing UI

feat: add artifact creation to Agent tools, route to retrieve an artifact

---

packages/frontend/src/features/scheduler/components/SchedulerFilters.tsx

Fix scheduled delivery filter revert for 'any value' filters. Scheduler filters with 'any value' weren't reverting properly since the UI in Scheduled deliveries doesn't include enable/disable. 
This makes it so that if a fitler that requires values has no values, it gets set to disabled. 
To see the original issue:
- Add a filter with 'any value' to a dashboard
- Create a scheduled delivery and go to the filters tab
- Give the filter a value
- Revert it
- It gets set to no value, but not 'any value'
**Bug:**
The fitler is now in a state of being enabled with no values. This fix enables and disables the filters based on values and operator. 
**Fixed:**

fix: scheduled delivery filter revert state

---

packages/frontend/src/components/UserCompletionModal/UserCompletionModal.tsx

Closes: #16527
Removed the `organizationName` parameter from the user completion mutation in the UserCompletionModal component. This parameter is no longer needed when completing the user setup process.
Before:
https://github.com/user-attachments/assets/a28fcb82-9caa-48f0-9c2a-3ca57989bce8
After:
https://github.com/user-attachments/assets/e7e0d336-16e3-4e30-bea3-1473cad1952a

fix: remove organizationName from user completion mutation

---

packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx

Closes: #14734
Changed `getVisibleCells()` to `getAllCells()` in TableBody component to ensure all cells are available for conditional formatting, even if they're not currently visible in the UI.

fix: use getAllCells instead of getVisibleCells for conditional formatting

---

packages/common/src/authorization/roleToScopeParity.test.ts

Closes: 
Fixed import `getScopesForRole` to `getAllScopesForRole` in the role to scope parity test.

fix: incorrect import

---

packages/common/src/compiler/translator.ts

Closes: #16405
Adds support for handling `CompileError` in the explore conversion process. Now, both `ParseError` and `CompileError` will be properly categorized as `METADATA_PARSE_ERROR` type when encountered during explore conversion.
before:
after:

fix: lightdash validate command shows success despite compilation errors

---

examples/api/roles.http
packages/backend/src/controllers/OrganizationRolesController.ts
packages/backend/src/controllers/ProjectRolesController.ts
packages/backend/src/ee/controllers/CustomRolesController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/authorization/roleToScopeParity.test.ts
packages/e2e/cypress/e2e/api/roles.cy.ts

Closes: 
One more API migration before we start with the UI
The diff is unreviewable, because the changes don't match.
- move system/oss endpoints from OrganizationCOntroller to OSS
- keep custom role specific endpoints on CustomRoleController in EE
- Remove RoleController, and move those endpoints under organization namespace.

fix: move new role system endpoints to oss

---

packages/backend/src/clients/EmailClient/EmailClient.ts

Fixed email attachment file extension handling in the EmailClient. Now the code properly appends the correct file extension (.xlsx or .csv) to attachment filenames when they don't already have the appropriate extension, ensuring that recipients can open the files with the correct applications.

fix: add file extension to file name

---

packages/backend/src/auth/account/warnAccountExists.ts
packages/backend/src/controllers/authentication/middlewares.ts
packages/backend/src/ee/authentication/middlewares.ts
packages/backend/src/middlewares/accountMiddleware/sessionAccountMiddleware.ts
packages/backend/src/middlewares/jwtAuthMiddleware/jwtAuthMiddleware.ts
packages/common/src/types/auth.ts

Closes: #N/A
Part of a series of follow-ups to the [Embedded AuthZ Incident ](https://www.notion.so/lightdash/Authorization-error-on-embedded-dashboards-255a63207a7a80a59b70ef3075833b48)
Prevents multiple authentication methods from overriding each other by adding checks to ensure an account is not already authenticated before setting a new authentication method. Added warning logs when an account is already authenticated via OAuth, API key, service account, or session to help debug authentication issues.

chore: add logging for account edges

---

packages/frontend/src/components/AboutFooter.tsx

Closes: #16180
The PR fixes the documentation icon visibility issue in the footer, where the book icon was only visible on hover due to poor contrast.
File: `packages/frontend/src/components/AboutFooter.tsx`: Updated icon color and button variants
change: Removed custom hover styles in favor of consistent light variant behavior
| Before | After |
|--------|-------|
| <img width="480" height="100" alt="Before" src="https://github.com/user-attachments/assets/e057bce0-2aea-4f99-8607-01b662adb794" /> | <img width="480" height="100" alt="After" src="https://github.com/user-attachments/assets/59b0df47-64ab-4d00-bc7b-73c1441f046c" /> |

fix: document icon in settings not visible until hover 

---

packages/cli/package.json
packages/cli/src/handlers/createProject.ts
packages/cli/src/handlers/dbt/apiClient.ts
packages/cli/src/index.ts
pnpm-lock.yaml

Closes: https://github.com/lightdash/lightdash/issues/16572
Added permission checks to the CLI project creation flow to prevent users from creating projects when they don't have the required permissions. This implements the same CASL-based permission system used in the backend to validate if a user can create projects of a specific type before attempting the operation.
The PR adds:
- Permission validation before project creation attempts
- Improved error handling with helpful messages for permission-related errors
- User-friendly guidance when permission errors occur, directing users to contact their Lightdash administrator
- does not have access to create preview project:
- does not have access to create default project
has access to create project

feat: add permission check for CLI project creation

---

packages/backend/src/App.ts
packages/backend/src/routers/oauthRouter.ts

Related to: https://github.com/lightdash/lightdash/issues/16604
Added a new OAuth endpoint `/.well-known/oauth-protected-resource/api/v1/mcp` for MCP server protected resource discovery. This endpoint is required by some MCP clients to properly discover the protected resource.
error from cursor logs:
2025-08-27 17:27:36.484 [error] Failed to complete OAuth exchange Unexpected token '<', "\<!DOCTYPE "... is not valid JSON
call to the route in logs - it is 200 because it redirects to home page:

feat: add MCP server protected resource discovery endpoint

---

packages/backend/src/controllers/OrganizationRolesController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/RolesModel.ts
packages/backend/src/services/HealthService/HealthService.ts
packages/backend/src/services/RolesService/RolesService.ts
packages/frontend/src/ee/features/customRoles/CustomRolesCreateModal.tsx
packages/frontend/src/ee/features/customRoles/CustomRolesDeleteModal.tsx
packages/frontend/src/ee/features/customRoles/CustomRolesEditModal.tsx
packages/frontend/src/ee/features/customRoles/CustomRolesTable.tsx
packages/frontend/src/ee/features/customRoles/useCustomRoles.ts
packages/frontend/src/ee/pages/CustomRoles.tsx
packages/frontend/src/pages/Settings.tsx

Closes: #1234
This adds just the first iteration of custom roles. We have role management without handling scopes just yet. From here, we'll can iteratively add more capabilities.
We can:
- Create new custom role (just name + description)
- Edit the role
- Delete the role
- View all roles

feat: add custom roles admin page

---

packages/backend/src/utils/QueryBuilder/PivotQueryBuilder.test.ts
packages/backend/src/utils/QueryBuilder/PivotQueryBuilder.ts

Refactored the pivot query total columns calculation to use a more efficient and accurate approach. Instead of counting from the filtered rows, the new implementation uses a dedicated `getTotalColumnsSQL` method that counts distinct combinations from the source data.
The new approach is more warehouse-agnostic and provides a cleaner separation of concerns by extracting the total columns logic into its own method with proper documentation.
**Note:** Multiple index columns are already supported
```
{
indexColumn: [
{ reference: 'customers_first_name', type: 'category' },
{ reference: 'customers_last_name', type: 'category' }
],
valuesColumns: [
{ reference: 'orders_completion_percentage', aggregation: 'any' },
{ reference: 'orders_unique_order_count', aggregation: 'any' }
],
groupByColumns: …
```

fix: allow multiple groupByColumns in pivot configuration

---

.github/workflows/cli-tests.yml
packages/e2e/cypress/cli/dbt/cli.cy.ts

Added run id specific schemas to remove concurrency issues + cleanup job after
This change will help prevent test failures due to using the same db when multiple workflows are triggered at the same time.
test-cli

chore: add and clean run specific schemas for e2e CLI

---

packages/backend/src/auth/account/account.mock.ts
packages/backend/src/auth/account/account.test.ts
packages/backend/src/auth/account/account.ts
packages/backend/src/middlewares/jwtAuthMiddleware/jwtAuthMiddleware.ts
packages/common/src/authorization/jwtAbility.test.ts
packages/common/src/authorization/jwtAbility.ts
packages/common/src/ee/embed/index.ts
packages/common/src/types/auth.ts

Closes: #N/A
Part of follow-ups to the [Embedded AuthZ Incident](https://www.notion.so/lightdash/Authorization-error-on-embedded-dashboards-255a63207a7a80a59b70ef3075833b48)
@ZeRego suggested that customers may not be sending a proper JWT with all the claims we expect. This seems correct. I made an assumption that `projectUuid` would always be a claim in the JWT, but we don't enforce the JWT schema for embeds. The theory is that customers that were affected do not mint tokens with `projectUuid`.
We use `projectUuid` when applying CASL abilities. This would then make sense because we have authenticated users that get 403 Forbidden errors when accessing resources we expect to be available.
The error occurred because "View Underlying Data" moved embedded dashboards to use endpoints outside …

feat: use projectUuid in embed for JWT abilities

---

packages/frontend/src/components/DashboardTabs/gridUtils.ts
packages/frontend/src/components/DashboardTabs/index.tsx
packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
packages/frontend/src/ee/features/embed/EmbedDashboard/components/EmbedDashboard.tsx
packages/frontend/src/pages/MinimalDashboard.tsx

Relates to: #4161
Implemented responsive grid layouts for dashboards to properly scale tiles across different screen sizes. The changes include:
1. Enhanced `getReactGridLayoutConfig` to scale tile dimensions based on the number of columns in the current breakpoint
2. Added support for medium and small breakpoints in dashboard layouts
3. Created a TypeScript type for `ResponsiveGridLayoutProps` to improve type safety
4. Optimized grid layout configuration by reusing the same grid props instance
5. Applied responsive layouts to all dashboard views (standard, minimal, and embedded)
This ensures dashboard tiles maintain proper proportions when viewed on different devices, providing a better user experience across various screen sizes.
**Before**
**After**

fix: dashboard responsive layout depending on columns

---

packages/backend/src/database/migrations/20250821071500_add_title_to_ai_thread.ts
packages/backend/src/ee/controllers/aiAgentController.ts
packages/backend/src/ee/database/entities/ai.ts
packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/ee/services/ai/agents/titleGenerator.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/ee/AiAgent/index.ts
packages/common/src/index.ts
packages/frontend/src/ee/features/aiCopilot/components/ConversationsList.tsx
packages/frontend/src/ee/features/aiCopilot/hooks/useOrganizationAiAgents.ts
packages/frontend/src/ee/pages/AiAgents/AgentPage.tsx
packages/frontend/src/ee/pages/AiAgents/AgentThreadPage.tsx

Closes: #15317
Add thread title generation for AI conversations
This PR adds the ability to automatically generate titles for AI agent conversation threads. It includes:
1. A database migration to add `title` and `title_generated_at` columns to the `ai_thread` table
2. A new title generator service that creates concise, descriptive titles (max 60 chars) based on conversation content
3. A new API endpoint to generate titles for existing threads
4. Automatic title generation when creating new threads or adding messages
5. Updated UI to display titles in the conversation list and thread navigation
The titles make it easier for users to identify and navigate between their AI conversations.

feat: generate title for ai agent threads

---

packages/cli/src/handlers/createProject.ts

Temporarily disables the project creation permission check in the CLI to work around an issue with the permission check. The back-end permission check is still working as expected. Added a TODO comment to re-enable this check once the issue is fixed.

fix(cli): temporarily disable permissions warning for project creation

---

packages/backend/src/utils/QueryBuilder/PivotQueryBuilder.test.ts
packages/backend/src/utils/QueryBuilder/PivotQueryBuilder.ts
packages/common/src/pivot/derivePivotConfigFromChart.ts

Improved the PivotQueryBuilder to handle sorting more consistently and accurately:
1. Fixed column sorting in pivot queries by explicitly adding ASC direction to column_index ordering default
2. Refactored the ORDER BY clause generation to only include columns that are explicitly specified in sortBy
3. Added helper methods to handle field name generation for value columns with aggregations
4. Enhanced sort field handling to properly support sorting by value columns with aggregations
5. Updated the derivePivotConfigFromChart function to include value columns in sortBy configuration
This ensures that pivot tables correctly respect the specified sort directions and only apply sorting to columns that are explicitly included in the sort configuration.

fix: take into account all user defined sorts for row_index and column_index

---

packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/backend/src/utils/QueryBuilder/PivotQueryBuilder.ts
packages/common/src/visualizations/types/index.ts

Closes: 
Made `getValueColumnFieldName` method in `PivotQueryBuilder` public and refactored the `AsyncQueryService` to use this method when constructing value column references. This ensures consistent naming of value columns throughout the codebase and fixes an issue where the transformed row was using a different field name pattern than what was being set.
Adds `columnIndex` to values columns and sorts by column index before returning to the frontend

fix: respect column_index when transforming rows

---

packages/backend/src/clients/github/Github.ts
packages/backend/src/clients/gitlab/Gitlab.ts
packages/backend/src/projectAdapters/dbtGitProjectAdapter.ts
packages/backend/src/services/GitIntegrationService/GitIntegrationService.test.ts
packages/backend/src/services/GitIntegrationService/GitIntegrationService.ts
packages/frontend/src/components/Explorer/WriteBackModal/CreatedPullRequestModalContent.tsx
packages/frontend/src/components/Explorer/WriteBackModal/hooks.ts
packages/frontend/src/components/Explorer/WriteBackModal/index.tsx
packages/frontend/src/features/sqlRunner/components/Header/HeaderCreate.tsx
packages/frontend/src/features/sqlRunner/components/WriteBackToDbtModal.tsx

Closes:  #16636
This works with gitlab personall acccess token, Oauth is not required for this functionallity to work.
Extend "Write back to dbt" feature to support GitLab projects in addition to GitHub. This PR adds GitLab integration using personal access tokens, allowing users to create merge requests directly from Lightdash.
Key changes:
- Created a new GitLab client to interact with GitLab API
- Extended the GitIntegrationService to support both GitHub and GitLab
- Updated frontend components to recognize GitLab projects
- Updated UI messaging to reference "Git" instead of "GitHub" specifically
- Maintained backward compatibility with existing GitHub functionality
This implementation allows GitLab users to create merge requests for custom metrics, custom dimensions, and from SQL …

feat: extend "Write back to dbt" to support GitLab projects

---

packages/frontend/src/components/DashboardTabs/gridUtils.ts
packages/frontend/src/pages/MinimalDashboard.tsx

Closes: #16665
We recently updated dashboards to scale tiles based on the grid columns, but it's not working right in mobile dashboards. In mobile dashboards, we override the number of grid columns with `stackVerticallyOnSmallestBreakpoint`. 
This removes the column scaling for the smallest size (mobile) minimal dashboards. 
1. Make a dashboard with a row of 3 - 4 tiles
2. Size it very narrow
3. Reload so you get the mobile version
4. All tiles should be there, stacked.

fix: mobile dashbaord layout

---

packages/backend/src/ee/controllers/aiAgentController.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/ee/services/McpService/McpService.ts
packages/backend/src/ee/services/ai/prompts/system.ts
packages/backend/src/ee/services/ai/tools/generateBarVizConfig.ts
packages/backend/src/ee/services/ai/tools/generateTableVizConfig.ts
packages/backend/src/ee/services/ai/tools/generateTimeSeriesVizConfig.ts
packages/backend/src/ee/services/ai/tools/runMetricQuery.ts
packages/backend/src/ee/services/ai/utils/populateCustomMetricsSQL.ts
packages/backend/src/ee/services/ai/utils/validators.ts
packages/backend/src/ee/services/ai/visualizations/vizTable.ts
packages/backend/src/ee/services/ai/visualizations/vizTimeSeries.ts
packages/backend/src/ee/services/ai/visualizations/vizVerticalBar.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/ee/AiAgent/schemas/customMetrics.ts
packages/common/src/ee/AiAgent/schemas/index.ts
packages/common/src/ee/AiAgent/schemas/tools/toolTableVizArgs.ts
packages/common/src/ee/AiAgent/schemas/tools/toolTimeSeriesArgs.ts
packages/common/src/ee/AiAgent/schemas/tools/toolVerticalBarArgs.ts
packages/common/src/ee/AiAgent/schemas/visualizations/tableViz.ts
packages/common/src/ee/AiAgent/schemas/visualizations/timeSeriesViz.ts
packages/common/src/ee/AiAgent/schemas/visualizations/verticalBarViz.ts
packages/common/src/ee/AiAgent/types.ts
packages/common/src/ee/AiAgent/utils.ts
packages/common/src/utils/additionalMetrics.ts
packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNodeActions.tsx
packages/frontend/src/ee/features/aiCopilot/utils/echarts.ts

Relates to: #16586
This PR adds support for custom metrics in AI agent queries. Now when users request metrics that don't exist in the data model, the AI agent can create them on-the-fly using the new `additionalMetrics` field.
Key changes:
- Updated the `validateSelectedFieldsExistence` function to check for fields in both the explore **and** additional metrics
- Added `additionalMetrics` to the `AiMetricQuery` type and related schemas
- Enhanced the table visualization tool with documentation on how to create custom metrics
This enables more flexible AI-powered analytics by allowing the creation of custom aggregations based on user requests, even when those metrics aren't predefined in the data model.

feat: allow creating custom metrics on table and viz tool calls

---

packages/frontend/src/hooks/dashboard/useDashboardChartDownload.ts
packages/frontend/src/hooks/dashboard/useDashboardChartReadyQuery.ts
packages/frontend/src/hooks/usePivotDimensions.ts
packages/frontend/src/hooks/useQueryResults.ts
packages/frontend/src/providers/Explorer/ExplorerProvider.tsx

Closes: 
Refactored feature flag usage by replacing `useFeatureFlagEnabled` with `useFeatureFlag` across multiple dashboard and query-related hooks. This change improves how we access feature flag data by using the full response object and explicitly checking the `enabled` property instead of directly using the boolean return value.
The update affects chart downloads, dashboard queries, pivot dimensions, and query results, ensuring consistent feature flag handling throughout the application.
`useFeatureFlagEnabled` only checks Posthog
`useFeatureFlag` checks posthog + env var

refactor: replace useFeatureFlagEnabled with useFeatureFlag hook

---

examples/api/roles.http
packages/backend/src/controllers/OrganizationRolesController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/RolesService/RolesService.mock.ts
packages/backend/src/services/RolesService/RolesService.test.ts
packages/backend/src/services/RolesService/RolesService.ts
packages/e2e/cypress/e2e/api/roles.cy.ts
packages/frontend/src/ee/features/customRoles/DuplicateRoleModal.tsx
packages/frontend/src/ee/features/customRoles/components/RoleBuilder/RoleBuilder.tsx
packages/frontend/src/ee/features/customRoles/useCustomRoles.ts
packages/frontend/src/ee/features/customRoles/utils/roleValidation.ts
packages/frontend/src/ee/pages/customRoles/CustomRoles.tsx

Closes: #16603
This PR adds a new API endpoint and UI to duplicate roles. Users can now duplicate both system roles and custom roles, preserving all their scopes. The duplicated role will be created with a new name (either user-provided or automatically generated as "Copy of: [original name]").
- New `duplicateRole` endpoint in `OrganizationRolesController`
- Corresponding service method in `RolesService`
- Comprehensive test coverage for the new functionality
- Type definitions for the API response

feat: add duplicate role endpoint

---

packages/frontend/src/MobileRoutes.tsx
packages/frontend/src/components/NavBar/AiAgentsButton.tsx
packages/frontend/src/ee/CommercialRoutes.tsx
packages/frontend/src/ee/features/aiCopilot/components/AiAgentPageLayout/AiAgentPageLayout.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AiChartVisualization.tsx
packages/frontend/src/ee/features/aiCopilot/hooks/useAiAgentsButtonVisibility.ts
packages/frontend/src/ee/pages/AiAgents/AiAgentsRootLayout.tsx

Closes: N/A
Add AI Agents support to mobile view by:
- Adding an "Ask AI" navigation link in the mobile navigation bar
- Creating a shared hook `useAiAgentButtonVisibility` to determine when to show AI-related buttons
- Adding mobile-specific UI adaptations for AI agent components
- Creating a responsive `AiAgentsRootLayout` that uses the appropriate navigation bar based on screen size
- Adapting the AI chart visualization to hide certain controls on mobile
- Using a bottom drawer for artifact panels on mobile instead of the desktop side panel

feat: add ai agents mobile view

---

packages/common/src/pivot/pivotQueryResults.mock.ts
packages/common/src/pivot/pivotQueryResults.test.ts
packages/common/src/pivot/pivotQueryResults.ts
packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
packages/frontend/src/hooks/useQueryResults.ts

Closes: https://github.com/lightdash/lightdash/issues/16534 
Util function that converts SQL pivoted results to `pivotData` which is the expected format for the table viz component. 
Needs to be tested locally with ```export USE_SQL_PIVOT_RESULTS=true```
To be fixed in separate PRs:
- Subtotals to be fixed in [#16663](https://github.com/lightdash/lightdash/issues/16663)
- Fix hidden columns for SQL pivoted results [#16671](https://github.com/lightdash/lightdash/issues/16671)

chore: add support for SQL-pivoted results conversion to PivotData format

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.mock.ts
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
packages/frontend/src/hooks/cartesianChartConfig/utils.ts
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts
packages/frontend/src/hooks/plottedData/getPlottedData.ts

This PR refactors the chart data handling to support pre-pivoted data from the backend. Instead of passing just the `rows` property to chart configuration functions, we now pass the entire `resultsData` object which may contain `pivotDetails` with pre-calculated pivot information.
Key changes:
- Modified `getExpectedSeriesMap` to use `resultsData` instead of just `rows`
- Added new functions to handle pre-pivoted data: `getPivotedDataFromPivotDetails` and `getEchartsSeriesFromPivotedData`
- Added support for pivot value column mapping to properly format values
- Updated value formatters to handle pivot column references
- Implemented conditional logic to use the new implementation when `pivotDetails` are available
This change improves performance for pivoted charts by leveraging …

feat: add new cartesian chart util to handle backend pivoted data

---

packages/backend/src/config/parseConfig.ts
packages/backend/src/services/InstanceConfigurationService/InstanceConfigurationService.ts

Closes: https://github.com/lightdash/lightdash/issues/16700
Added support for configuring Databricks personal access token through environment variables. This allows users to set up Databricks authentication using the `PERSONAL_ACCESS_TOKEN` environment variable alongside the existing HTTP path configuration option.

feat: add PAT support for instance update setup

---

packages/backend/src/utils/QueryBuilder/PivotQueryBuilder.test.ts
packages/backend/src/utils/QueryBuilder/PivotQueryBuilder.ts
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Layout/index.tsx

Closes: [#16703](https://github.com/lightdash/lightdash/issues/16703)
Prevents users from selecting the same field for both index and group by columns in pivot tables, which would lead to invalid queries. This PR adds validation in the backend to throw a clear error message when this happens, and updates the frontend to disable fields in the group by dropdown that are already used as index columns.
Example:
Disabled options
New error message (shouldn't be possible to reach this state now)

fix: prevent overlapping columns between group by and index in pivot queries

---

packages/e2e/cypress/e2e/app/tableCalculation.cy.ts

Closes: #N/A
Reordered the table calculation test steps to match the actual UI flow. The test now first enters the calculation formula in the editor, selects the data type if needed, and then enters the calculation name before clicking create. This better reflects how users interact with the table calculation dialog.

chore: reorder table calculation input fields in e2e tests

---

examples/api/ai-agents.http
packages/backend/src/ee/controllers/AiAgentAdminController.ts
packages/backend/src/ee/index.ts
packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/ee/services/AiAgentAdminService.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/ServiceRepository.ts
packages/common/src/ee/AiAgent/adminTypes.ts
packages/common/src/ee/AiAgent/index.ts

Relates to: #16675
Added an admin API endpoint for AI agent conversation analytics. This new endpoint allows organization admins to retrieve and analyze all AI agent conversations across the organization with comprehensive filtering options.
Key features:
- New `/api/v1/aiAgents/admin/threads` endpoint for organization-wide conversation analysis
- Robust filtering capabilities including:
- Project and agent filtering
- User-specific filtering
- Source filtering (Slack vs Web App)
- Human feedback filtering (thumbs up/down)
- Date range filtering
- Pagination and sorting options
- Feedback aggregation for training loop analysis
- Comprehensive HTTP examples for API usage
This endpoint will enable admins to analyze AI agent performance, identify patterns in user feedback, and improve agent …

chore: add ai agent admin controller

---

packages/backend/src/ee/controllers/AiAgentAdminController.ts
packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/ee/AiAgent/adminTypes.ts
packages/common/src/index.ts
packages/frontend/src/ee/CommercialRoutes.tsx
packages/frontend/src/ee/features/aiCopilot/components/Admin/AiAgentAdminThreadsTable.tsx
packages/frontend/src/ee/features/aiCopilot/components/Admin/AiAgentsAdminLayout.tsx
packages/frontend/src/ee/features/aiCopilot/hooks/useAiAgentAdmin.ts
packages/frontend/src/ee/pages/AiAgents/Admin/AiAgentsAdminPage.tsx

Relates to: #16675
Adds an AI Agents Admin Panel that allows organization admins to view and manage AI Agent threads. The panel includes a table with thread details such as title, agent, project, user, source, feedback, and creation date. The table supports sorting, searching by title, and infinite scrolling.
- New admin route at `/ai-agents/admin`
- Admin threads table with "created at" sorting. More filters and sorts soon!
- Permission checks to ensure only organization admins can access the panel
- Backend API integration for fetching thread data

feat: display ai agent admin panel for all threads

---

packages/frontend/src/ee/features/aiCopilot/components/Admin/AiAgentAdminThreadsTable.tsx
packages/frontend/src/ee/features/aiCopilot/components/Admin/AiAgentsAdminLayout.module.css
packages/frontend/src/ee/features/aiCopilot/components/Admin/AiAgentsAdminLayout.tsx
packages/frontend/src/ee/features/aiCopilot/components/Admin/ThreadPreviewSidebar.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatAssistantBubble.tsx
packages/frontend/src/ee/features/aiCopilot/providers/AiLayoutProvider.tsx
packages/frontend/src/ee/pages/AiAgents/Admin/AiAgentsAdminPage.tsx

Closes: #16675
Added a thread preview sidebar to the AI Agents Admin Panel that allows admins to view thread content without leaving the admin page. The sidebar implementation includes:
- A resizable panel layout with a thread list and preview panel
- Thread selection functionality that highlights the selected thread
- A preview sidebar that displays the full conversation thread
- Navigation options to open the full thread in a new tab
- Proper loading states and error handling
The admin panel now provides a more efficient workflow for reviewing AI agent conversations, allowing admins to quickly scan through threads while maintaining context.
=== FOLDED ===
Added artifact viewing capability to the Thread Preview Sidebar in the AI Copilot admin interface. Users can now view artifacts …

feat: show thread preview on click of row

---

packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationWarning.tsx

Closes: [#16686](https://github.com/lightdash/lightdash/issues/16686)
Added a new visualization warning component that alerts users when their chart configuration might lead to incorrect results. The warning appears in two scenarios:
1. When dimensions in the query are not used in the chart configuration (x-axis, y-axis, or group by)
2. When there's a mismatch between configured pivot dimensions and the ones used to compute the results
The warning badge displays "Results may be incorrect" with a tooltip explaining the specific issues and recommended actions.

feat: add visualization warning for incorrect chart configurations

---

packages/frontend/src/pages/Settings.tsx

Closes: #16754
Added a new "AI Agents" navigation link in the Settings page for users with the appropriate permissions. The link directs to "/ai-agents/admin" and uses the IconBrain icon.

chore: add AI Agents link to settings page

---

packages/backend/src/config/aiConfigSchema.ts
packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/ee/models/CommercialFeatureFlagModel.ts

Closes: #16748
Adds a new configuration option `askAiButtonEnabled` to control the visibility of the Ask AI button. This can be set via the `ASK_AI_BUTTON_ENABLED` environment variable. When enabled, the Ask AI button will be shown regardless of feature flag settings.
The configuration follows the same pattern as other AI Copilot settings, integrating with the existing configuration schema and commercial feature flag model.

feat: add askAiButtonEnabled configuration option

---

packages/backend/src/models/UserModel.ts
packages/frontend/src/components/UserCompletionModal/UserCompletionModal.tsx

Closes: #16747
Skip user setup completion modal when analytics tracking is disabled. This change automatically marks users as having completed setup when Rudder analytics is not configured, eliminating the need for users to go through the setup completion process in environments where tracking is disabled.
The PR:
1. Automatically sets `is_setup_complete` to true during user creation when Rudder write key is not present
2. Removes the effect hook that was previously handling this scenario in the frontend

fix: skip user setup when analytics tracking is disabled

---

packages/frontend/src/features/comments/components/CommentForm.tsx
packages/frontend/src/features/comments/components/CommentWithMentions/LazyCommentWithMentions.tsx

Related to: #13587
Lazy load the CommentWithMentions component to reduce initial bundle size. This implementation:
- Creates a new LazyCommentWithMentions component that uses React.lazy to defer loading
- Adds a loading skeleton while the component is being loaded
- Avoids importing heavy prosemirror dependencies via @tiptap and @mantine/tiptap at the top level
- Updates the CommentForm to use the lazy-loaded version
This change should improve initial load performance by deferring the loading of these heavy dependencies until they're actually needed.

fix: lazy load CommentWithMentions component to reduce bundle size

---

packages/backend/src/ee/services/ai/prompts/system.ts
packages/backend/src/ee/services/ai/tools/generateBarVizConfig.ts
packages/backend/src/ee/services/ai/tools/generateTableVizConfig.ts
packages/backend/src/ee/services/ai/tools/generateTimeSeriesVizConfig.ts
packages/backend/src/ee/services/ai/tools/runMetricQuery.ts
packages/backend/src/ee/services/ai/utils/validators.ts
packages/common/src/ee/AiAgent/schemas/index.ts
packages/common/src/ee/AiAgent/schemas/sortField.ts

Closes: #16684
Added validation to ensure sort fields are selected in dimensions or metrics. This prevents agents from sorting by fields that aren't included in the query.
The new `validateSortFieldsAreSelected` function checks that all sort fields are present in either the selected dimensions, metrics, or custom metrics. If a sort field isn't selected, it throws a descriptive error message to guide users.
This validation has been implemented across all visualization tools (bar, table, time series) and MCP.

fix: validate sort fields in agent tool calls are selected in metrics/dimensions

---

packages/cli/src/handlers/diagnostics.ts

Added a warning message in the diagnostics output when the `LIGHTDASH_API_KEY` environment variable is set, informing users that it will override credentials in the config file. This helps users troubleshoot authentication issues by making them aware of environment variables that might affect their configuration.

chore(cli): add warning when LIGHTDASH_API_KEY environment variable is set

---

packages/backend/src/utils/QueryBuilder/PivotQueryBuilder.test.ts
packages/backend/src/utils/QueryBuilder/PivotQueryBuilder.ts

Closes: #16761
Fixed inconsistent quoting in PivotQueryBuilder by ensuring all index columns in select references are properly quoted. This ensures consistent behavior across all column references in the query.

fix: quote index columns in pivot query builder

---

packages/backend/src/utils/QueryBuilder/PivotQueryBuilder.test.ts
packages/backend/src/utils/QueryBuilder/PivotQueryBuilder.ts
packages/backend/src/utils/QueryBuilder/utils.ts

Closes: [#16739](https://github.com/lightdash/lightdash/issues/16739)
Improved the PivotQueryBuilder to properly handle SQL comments and LIMIT clauses in the base query. The builder now correctly removes comments and LIMIT statements from the original SQL when constructing the pivot query, ensuring that these elements don't interfere with the pivot operation.
Added a new test case that verifies comments and LIMIT clauses are properly removed from the base SQL in the original_query CTE. This ensures that pivot visualizations work correctly regardless of comments or LIMIT statements in the underlying SQL.

feat: apply limit after pivoting/grouping

---

packages/common/src/pivot/derivePivotConfigFromChart.ts
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Layout/index.tsx
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.test.ts
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
packages/frontend/src/hooks/plottedData/getPlottedData.ts
packages/frontend/src/hooks/usePivotDimensions.ts

Closes: #5432
Improves pivot configuration validation to prevent invalid pivot configurations. This PR:
1. Filters out pivot columns that are not in the metric query dimensions
2. Adds a validation function to check if a pivot configuration is valid
3. Ensures pivot columns don't overlap with index columns
4. Shows an error message for invalid pivot references in the UI
5. Prevents automatic fallback to pivot dimensions when using SQL pivot results
These changes make the pivot functionality more robust by ensuring only valid configurations are used, preventing potential errors when dimensions are removed from a query but still referenced in pivot settings.
**TLDR** This PR is a mix of fixes so the FE doesn't generate invalid pivot configuration and has better fallbacks. 
Before, we would …

fix: validate pivot configuration and prevent invalid pivot dimensions

---

packages/frontend/src/components/Explorer/SqlCard/SqlCard.tsx
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationConfig.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/index.tsx

Closes: #[issue number]
Implemented lazy loading for heavy components that import the Monaco editor to improve initial load performance. This includes:
1. Lazy loaded `RenderedSql` component in `SqlCard` with a skeleton loading state
2. Lazy loaded `CustomVisConfig` in `VisualizationConfig` with a loader fallback
3. Lazy loaded `TooltipConfig` in the Legend component with a loader fallback
These changes will reduce the initial bundle size and improve page load times by only loading the Monaco editor when these specific components are actually needed.
Improvement: 20%
Before
```
sdk/dist/sdk.css 492.91 kB │ gzip: 51.69 kB
sdk/dist/sdk.cjs.js 0.31 kB │ gzip: 0.24 kB │ map: 0.09 kB
sdk/dist/IconAlignRight-BolwD1bi.js 0.50 kB │ gzip: 0.26 kB │ map: 1.74 kB …
```

chore: lazy load  @monaco-editor/react imports in explore

---

packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/ee/services/ai/utils/getSlackBlocks.ts
packages/common/src/ee/AiAgent/followUpTools.ts
packages/common/src/ee/AiAgent/schemas/tools/toolTableVizArgs.ts
packages/common/src/ee/AiAgent/schemas/tools/toolTimeSeriesArgs.ts
packages/common/src/ee/AiAgent/schemas/tools/toolVerticalBarArgs.ts
packages/common/src/ee/AiAgent/types.ts

Refactored AI agent follow-up tools to use the `AiResultType` enum instead of the separate `FollowUpTools` enum. This consolidates the visualization types into a single enum, improving code consistency and maintainability.
The PR updates the follow-up tool references in multiple files, including the Slack blocks generation, tool schemas for different visualization types (table, time series, vertical bar), and the AI agent service.
Additionally, removed the unused `ONE_LINE_RESULT` type from the `AiResultType` enum and updated the follow-up tool descriptions to be more accurate.

refactor: replace FollowUpTools enum with AiResultType

---

packages/common/src/pivot/derivePivotConfigFromChart.ts

Closes: 
Fixed pivot configuration validation by adding a check for empty values columns. Also added filtering to ensure that only valid references (those included in metricQuery dimensions or metrics) are used in valuesColumns for both table and cartesian pivot configurations.
before
https://github.com/user-attachments/assets/81334933-19a5-4e38-9022-d5c3d917b3a6
after:
https://github.com/user-attachments/assets/c098c122-dccd-4b83-9ead-16a7a0dd2dec

fix: filter invalid references in pivot configuration and validate value columns

---

packages/frontend/src/pages/Dashboard.tsx
packages/frontend/src/providers/Dashboard/DashboardProvider.tsx
packages/frontend/src/providers/Dashboard/types.ts

Closes: #16734
When there were multiple tabs on a dashboard with parameters, the parameter inputs never finished loading because we were waiting for all charts and we don't load the charts from hidden tabs. 
This moves the tab state to the provider, then only counts charts on the active tab for loading the paramters.
The parameters input will add new parameters if more are added when more tabs load. 
I'll put a demo below, but the tests steps are:
- Create two charts with two different parameters
- Put them on the same dashboard on different tabs
- Whichever tab you start on, the parameters input should populate 
- When you switch tabs, you should get those extra parameters

fix: parameters only wait for active tab

---

packages/frontend/src/providers/Explorer/ExplorerProvider.tsx
packages/frontend/src/providers/Explorer/utils.ts

Closes: #16780
Fixed chart comparison logic to properly detect changes between saved and unsaved chart versions. Added a `cleanConfig` utility function to remove the `isFilteredOut` property from chart series data before comparison, ensuring that UI-specific properties don't trigger false change detection. Also included parameters in the comparison to ensure all relevant chart properties are considered.
https://github.com/user-attachments/assets/b6c89a98-1eb7-483b-9b6b-c34840a699cb
https://github.com/user-attachments/assets/d630aaed-81ea-4c53-9f1c-cbd860ed9e36

fix: improve chart comparison by cleaning config and including parameters

---

packages/frontend/src/hooks/useSavedQuery.ts

Closes: #16803
Invalidate dashboard chart queries when a saved query is updated or a new version is added. This ensures that charts on dashboards are refreshed with the latest data after changes are made to the underlying queries.
The PR adds query invalidation logic in two places:
1. In the `useUpdateMutation` hook when a chart is saved
2. In the `useAddVersionMutation` hook when a chart version is updated
This change improves the user experience by automatically refreshing dashboard charts without requiring a manual refresh.
[fix-invalidation.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/user-attachments/thumbnails/9d9f58f4-0216-4085-b2f4-767c2bbccf98.mov" …

fix: invalidate dashboard chart on chart edit

---

packages/backend/src/database/migrations/20250912162343_remove_tags_unique_constraint_name_project_uuid.ts

Closes: #16878
Fixes: LIGHTDASH-BACKEND-490
This PR removes the unique constraint on `project_uuid` and `name` columns in the `tags` table and adds an index on the `name` column instead. The previous constraint was too restrictive as it prevented tags with the same name from being created within the same project.
The migration includes both up and down functions to properly handle the schema changes, fixing a bug that was introduced in a previous migration (`20241104105903_add-project-tags-table.ts`).

fix: remove unique project uuid name constraint from tags

---

packages/frontend/src/ee/features/aiCopilot/components/Admin/AgentsFilter.tsx
packages/frontend/src/ee/features/aiCopilot/components/Admin/AiAgentAdminThreadsTable.tsx
packages/frontend/src/ee/features/aiCopilot/components/Admin/AiAgentAdminTopToolbar.tsx
packages/frontend/src/ee/features/aiCopilot/components/Admin/FeedbackFilter.tsx
packages/frontend/src/ee/features/aiCopilot/components/Admin/ProjectsFilter.tsx
packages/frontend/src/ee/features/aiCopilot/components/Admin/SearchFilter.tsx
packages/frontend/src/ee/features/aiCopilot/components/Admin/SourceFilter.tsx
packages/frontend/src/ee/features/aiCopilot/hooks/useAiAgentAdminFilters.ts

Closes: #N/A
Refactored AI Agent Admin filters to use URL persistence, allowing users to share and bookmark specific filter states. Created a new `useAiAgentAdminFilters` hook that centralizes filter management and synchronizes filter state with URL parameters.
Key improvements:
- Added URL persistence for all filter parameters (search, projects, agents, source, feedback, sorting)
- Implemented a "Clear all filters" button to reset filters to default state
- Refactored filter components to use the new hook through prop drilling
- Improved type safety by using TypeScript's Pick utility for component props
- Fixed sorting implementation to properly update URL parameters
This change makes the AI Agent Admin interface more user-friendly by preserving filter state across page refreshes and …

feat: set filters in url when interacting with ai admin threads

---

packages/frontend/src/ee/pages/AiAgents/ProjectAiAgentEditPage.tsx

Fixed user access filtering in the AI Agent edit page by ensuring that only valid users from the available options are displayed in the form. Also simplified the form schema by removing unnecessary type annotations.

fix: filter invalid users from AI agent userAccess list

---

packages/frontend/src/components/Explorer/index.tsx
packages/frontend/src/providers/Explorer/ExplorerProvider.tsx

Closes: #16855
Auto-fetch results for charts with pivot configurations when loaded from dashboards or as saved charts. This ensures that charts requiring backend pivot processing are properly rendered without requiring manual user interaction.
- Renamed `explore` to `exploreData` to avoid naming conflicts
- Added detection for charts with pivot configurations that need backend processing
- Enhanced the auto-fetch logic to consider pivot configuration requirements
- Added safeguards to wait for explore data when backend pivot processing is needed
- Improved dependency tracking in the useEffect hook for more reliable fetching
https://github.com/user-attachments/assets/0b899958-b600-4f39-bcf8-d6fd743c0c23
This addresses only the sorting, I haven't been able to reproduce …

fix: explore from here consistency

---

packages/common/src/pivot/pivotQueryResults.ts

Filter out hidden metrics from pivot table results to ensure they don't appear in the visualization. This change modifies the `convertSqlPivotedRowsToPivotData` function to respect the `hiddenMetricFieldIds` parameter by filtering the `valuesColumns` before processing the pivot data.
**Before**
https://github.com/user-attachments/assets/5ae65ea5-8ef5-4e62-9771-70f7515c6aec
**After**
https://github.com/user-attachments/assets/2703df30-675a-455d-bd32-0ccbb5a5ef74

fix: hidding values columns

---

packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/ee/AiAgent/index.ts
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatAssistantBubble.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ArtifactButton/AiArtifactButton.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ScrollToBottom.tsx
packages/frontend/src/ee/features/aiCopilot/hooks/useAiAgentThreadArtifact.ts
packages/frontend/src/ee/features/aiCopilot/hooks/useProjectAiAgents.ts

The reason for this change is that when the user would ask for multiple charts, there was a bug that couldn't properly handle it.
This PR refactors the AI agent artifact handling to support multiple artifacts per message. Instead of a single `artifact` property, messages now have an `artifacts` array that can contain multiple chart or dashboard artifacts.
Key changes:
- Changed the data model from a single `artifact` property to an `artifacts` array
- Optimized database queries by separating artifact fetching from prompt fetching
- Updated the UI to display multiple artifacts when available
- Fixed potential duplicate artifacts issue by using separate queries
This change improves the AI agent's ability to generate and display multiple visualizations in a single response, enhancing the …

fix: support multiple artifacts per AI agent message

---

packages/backend/src/scheduler/SchedulerTask.ts
packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/backend/src/services/CsvService/CsvService.ts
packages/backend/src/services/ExcelService/ExcelService.ts
packages/backend/src/services/PivotTableService/PivotTableService.ts
packages/common/src/pivot/pivotQueryResults.ts

Closes: [#16866](https://github.com/lightdash/lightdash/issues/16866)
Refactored pivot table functionality to support SQL-pivoted results in exports. Added a utility method `getPivotDetailsFromQueryHistory` to extract pivot details from query history, and updated the `pivotResultsAsCsv` function to handle both traditional and backend pivoted data. This ensures consistent pivot table behavior across all export formats (CSV, Excel) when using the new query execution path.
The changes maintain backward compatibility by adding `pivotDetails: null` comments in places where the old query execution path is still being used, marking them for future updates.
**Before**
**Steps to Reproduce the Bug or Issue**
1. Enable `USE_SQL_PIVOT_RESULTS` 
2. Go to explore
3. Add 2 dimensions and 1 metric
4. …

fix: downloading pivoted tables

---

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatInput.tsx
packages/frontend/src/ee/pages/AiAgents/AgentThreadPage.tsx

Added a warning message in the agent chat input when the thread exceeds 15 messages, informing users that agent performance degrades with long threads. The warning includes a link to start a new thread, which navigates to the threads page for that agent.

fix: add thread length warning with new thread link in agent chat

---

packages/backend/src/database/migrations/20250916155604_change_validation_columns_to_text.ts

Changes the data type of `chart_name`, `field_name`, and `model_name` columns in the `validations` table from `string` to `text`. This allows these columns to store longer values without truncation.

fix: change validation columns from string to text

---

packages/frontend/src/ee/pages/AiAgents/ProjectAiAgentEditPage.tsx

Removed an extra backslash character from `ProjectAiAgentEditPage`

fix: remove backslash agent settings

---

CLAUDE.md
packages/backend/src/database/migrations/20250917082048_change_user_attribute_value_to_text.ts

Closes: https://github.com/lightdash/lightdash/issues/16929
This PR adds a database migration to change the `value` column in the `organization_member_user_attributes` table from VARCHAR(255) to TEXT type, allowing for longer attribute values to be stored.
Additionally, I've updated the CLAUDE.md documentation to include commands for database migrations, making it easier for developers to create, run, and rollback migrations.

feat: add database migration commands to documentation and change user attribute value to text

---

packages/backend/src/@types/knex-tables.d.ts
packages/backend/src/ee/database/entities/aiEvals.ts
packages/backend/src/ee/database/migrations/20250917134049_ai_eval_tables.ts

Adds database schema for AI evaluation functionality. This includes:
- New tables for AI evaluations, prompts, runs, and results
- Database migration script to create these tables with proper relationships
- Type definitions for database entities
The schema supports creating evaluations for agents, storing evaluation prompts, tracking evaluation runs, and recording results with status tracking.

feat: add AI Agent eval database schema and migrations

---

packages/backend/src/ee/controllers/aiAgentController.ts
packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/ee/AiAgent/index.ts
packages/common/src/ee/AiAgent/requestTypes.ts

Renamed `cloneWebAppThread` to `cloneThread` to better reflect its functionality, as it now supports cloning threads from various sources, not just web apps. This includes renaming the method in the controller, service, and model, as well as updating related type definitions.

feat: support AI Agent evals for slack based threads

---

packages/backend/src/services/GitIntegrationService/GitIntegrationService.mock.ts
packages/backend/src/services/GitIntegrationService/GitIntegrationService.ts
packages/common/src/dbt/DbtSchemaEditor/DbtSchemaEditor.mock.ts
packages/common/src/dbt/DbtSchemaEditor/DbtSchemaEditor.test.ts
packages/common/src/dbt/DbtSchemaEditor/DbtSchemaEditor.ts

Closes:  https://github.com/lightdash/lightdash/issues/16790
This PR adds support for dbt v1.10+ compatibility in the schema editor. In dbt v1.10+, custom metrics and dimensions need to be placed under `config.meta` instead of directly under `meta`. 
- Added a method to detect if the dbt version is 1.10 or higher
- Modified the schema editor to place custom metrics and dimensions in the correct location based on dbt version
- Added comprehensive tests to verify the correct behavior for different dbt versions
- Updated the GitIntegrationService to pass the project's dbt version to the schema editor
These changes ensure that Lightdash can properly generate YAML files that are compatible with both older dbt versions and the newer v1.10+ format.

feat: add dbt version compatibility for schema editor

---

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatInput.module.css

Enhanced the focus state of the agent chat input by styling double border

fix: enhance agent chat input focus styling

---

packages/backend/src/ee/services/AiAgentService.ts

The problem with the original regex:
- `^.*?(<@U\d+\w*?>)` matches from the start of the string (^) up to and including the first Slack mention
- For `"Hello @bot test"`​, it would match "Hello <@U123456>" and remove that entire portion
- This left only "test"
The fixed regex:
- `<@U\d+\w*?>` matches only the Slack user mention tags (like `<@U123456>`)
- For `"Hello @bot￼ test"`​, it removes just the <@U123456> part
- This leaves "Hello test" as intended

fix: update Slack tag regex pattern

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
packages/common/src/pivot/pivotQueryResults.ts
packages/common/src/visualizations/types/index.ts

Closes: #17031
Fixes and issue where the FE formatting for dates in pivot table headers didn't match the formatting from the BE. This manifested itself in the headers showing local, tz-adjusted values, while table cells showed UTC. This adds a `formatted` version of the pivot column headers to the payload returned from the BE which is calculated the same way the formatted versions of the cell values are, so they should always match. 
```
{
"aggregation": "any",
"columnIndex": "1",
"pivotValues": [
{
"value": "2025-01-01T00:00:00Z",
"formatted": "2025", // added
"referenceField": "orders_order_date_year"
}
],
"referenceField": "orders_total_order_amount",
"pivotColumnName": "orders_total_order_amount_any_2025-01-01T00:00:00Z"
},
```
Note: I tested this a fair amount, but I didn't work on …

fix: return formatted pivot column headers

---

packages/backend/src/ee/controllers/aiAgentController.ts
packages/backend/src/ee/services/AiAgentService.ts

Added `projectUuid` parameter to all AI agent evaluation methods to ensure proper access control. This change ensures that agents are retrieved with the correct project context, preventing unauthorized access to evaluations across different projects.

fix: add projectUuid parameter to AI agent evaluation methods

---

packages/backend/src/ee/models/AiAgentModel.ts
packages/frontend/src/ee/features/aiCopilot/components/Evals/EvalRunDetails.tsx
packages/frontend/src/ee/features/aiCopilot/components/Evals/EvalRuns.tsx
packages/frontend/src/ee/features/aiCopilot/hooks/useAiAgentEvaluations.ts

Enables viewing pending evaluation threads by making pending evaluation runs clickable in the UI. Previously, only completed runs could be viewed. The PR also adds polling for evaluation run details to automatically update the UI when a run's status changes, and increases the polling interval from 2 to 4 seconds to reduce server load.
[CleanShot 2025-09-24 at 10.01.41.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/user-attachments/thumbnails/1ab06c4c-05bc-40c8-af1a-7854859e547f.mp4" />](https://app.graphite.dev/user-attachments/video/1ab06c4c-05bc-40c8-af1a-7854859e547f.mp4)

fix: allow viewing pending eval and improve polling

---

packages/frontend/src/App.tsx
packages/frontend/src/index.tsx
packages/frontend/src/providers/ReactQuery/ReactQueryProvider.tsx
packages/frontend/vite-env.d.ts
packages/frontend/vite.config.ts

This PR makes React Query DevTools and React Scan conditionally available in development mode based on environment variables. It moves the ReactQueryDevtools from App.tsx to the ReactQueryProvider component and adds environment flags (REACT_SCAN_ENABLED and REACT_QUERY_DEVTOOLS_ENABLED) to control their activation. This allows developers to disable these tools when not needed while keeping them available by default in development mode.

chore: make React devtools configurable via environment variables

---

packages/frontend/src/pages/Settings.tsx

Closes: #17084
Added a feature flag check for AI Agents in the Settings page. The AI Agents navigation link will now only be displayed when both the AiCopilot feature flag is enabled and the user has the appropriate permissions to manage AI Agents.

fix: AI Agent link shows in settings without FF

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/ee/services/ai/agents/agent.ts
packages/backend/src/ee/services/ai/types/aiAgentDependencies.ts

Closes: N/A
Added tracking for AI agent tool calls with `AiAgentToolCallEvent` 
- tracking details such as the organization, project, agent, tool name, and thread information.

chore: track ai agent tool calling

---

packages/frontend/src/components/Explorer/ParametersCard/ParametersCard.tsx
packages/frontend/src/features/explorer/store/explorerSlice.ts
packages/frontend/src/features/explorer/store/selectors.ts
packages/frontend/src/features/parameters/components/ParameterInput.tsx
packages/frontend/src/hooks/useCompiledSql.ts
packages/frontend/src/providers/Explorer/ExplorerProvider.tsx

Closes: #17115
This PR migrates the Parameters Card component to use Redux selectors and actions instead of the Explorer Context. Key changes include:
1. Added new Redux selectors for parameters:
- `selectParameters`
- `selectParameterDefinitions`
- `selectTableName`
2. Added new Redux actions:
- `clearAllParameters`
- `setParameterDefinitions`
3. Updated ParametersCard to use Redux selectors while maintaining backward compatibility with Context for computed state (missingRequiredParameters)
4. Added synchronization between Context and Redux state for parameters to ensure proper transitions during migration
5. Fixed parameter handling in ParameterInput to avoid Redux immutability issues by creating copies of arrays
6. Added an effect to trigger query updates when parameters change
7. …

feat: migrate ParametersCard to Redux store

---

packages/backend/src/models/UserWarehouseCredentials/UserWarehouseCredentialsModel.ts
packages/backend/src/services/UserService.ts

Closes:  https://github.com/lightdash/lightdash/issues/17134
Before
After
Added a method to delete all warehouse credentials for a user by warehouse type and implemented it in the Snowflake authentication flow to prevent duplicate credentials. The new `deleteAllByUserAndWarehouseType` method is called before creating new Snowflake credentials during authentication, ensuring users don't accumulate multiple sets of credentials for the same warehouse type.

fix: duplicate snowflake warehouse credentials

---

packages/common/src/types/dbt.ts

Closes: #17152
Renamed `getCompiledModels` to `getFilteredModels` to better reflect its purpose, and removed the `model.compiled` filter condition. This function now only filters models by their IDs when provided, otherwise it returns all models without additional filtering.
This allows the users to use `lightdash deploy --no-warehouse-credentials` after running `dbt parse` instead of `compile`. After dbt 1.5, `dbt parse` generates a `manifest.json` which is only what we need to deploy.
1. Run `dbt parse`
2. Run `lightdash deploy --no-warehouse-credentials`
3. The models should be deployed and we should be able to query it.

feat: allow deploy command to work with just manifest.json

---

packages/backend/src/@types/knex-tables.d.ts
packages/backend/src/controllers/ChangesetController.ts
packages/backend/src/database/entities/changesets.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/ChangesetModel.ts
packages/backend/src/models/ModelRepository.ts
packages/backend/src/services/ChangesetService.ts
packages/backend/src/services/ServiceRepository.ts
packages/common/src/index.ts
packages/common/src/types/changeset.ts

Closes: N/A
Added database entity types for changesets and changes to support version control functionality. This includes:
- Created new `changesets.ts` file with type definitions for the changesets and changes tables
- Defined database schema types for both tables including required fields and relationships
- Added the new table types to the Knex type declarations to ensure proper type checking
These changes lay the groundwork for implementing version control features that will allow tracking changes to tables, dimensions, and metrics within projects.

chore: add db types for changes and changesets

---

packages/backend/package.json
packages/backend/src/database/entities/changesets.ts
packages/backend/src/database/seeds/development/01_initial_user.ts
packages/backend/src/models/ModelRepository.ts
packages/backend/src/models/ProjectModel/ProjectModel.test.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/common/src/types/changeset.ts
pnpm-lock.yaml

Closes: N/A
Adds JSON Patch–based application of active changesets to cached explores (dimensions/metrics), integrates ChangesetModel into ProjectModel and repo, and tightens change payload typing.
---
> [!NOTE]
> Adds JSON Patch–based application of active changesets to cached explores (dimensions/metrics), integrates ChangesetModel into ProjectModel and repo, and tightens change payload typing.
> - **Backend**
>     - **ProjectModel**:
>         - Apply active changesets to explores via new `applyChangeset` and `applyChange` (supports `create/update/delete` for `dimensions/metrics` using `fast-json-patch`).
>         - Integrate changeset application into `findExploresFromCache`.
>         - Import `Change`, use stricter error handling (`ForbiddenError`, `NotExistsError`).
>     - …

feat: implement changeset application for explore dimensions and metrics

---

packages/e2e/cypress/e2e/app/customDimensions.cy.ts
packages/frontend/src/components/Explorer/CustomMetricModal/utils/index.ts

Closes: #17159 
**The bug:**
Creating a table calculation from a custom metric based on a custom dimension was failing. The real issue here was that custom metrics based on custom dimensions were being created with the wrong (bad) id. Dimensions have a `name` and a `label`, while custom dimensions have a `name` and an `id`, but the name is really the label. 
**The fix:**
Create custom metrics based on custom dimensions using the custom dimension ID instead of the name.
**A custom dimension before (bug)**
```
{
"uuid": "58a8e89a-7ac9-4565-bb62-ee73f93f9f90",
"table": "orders",
...
"label": "Count of A custom dimension",
"name": "A custom dimension_count_of_a_custom_dimension" // this is wrong
}
```
**The same custom dimension now**
```
{
"uuid": "9b754d9f-aed6-4191-b6ef-86237f310443", …
```

fix: custom metrics are created with the wrong id

---

packages/backend/src/services/CoderService/CoderService.ts
packages/common/src/types/coder.ts

Closes: #17160
Added support for matching dashboard tiles by `tileSlug` in addition to `chartSlug` when converting dashboard filters from code to database format. This fixes an issue where filters weren't properly associated with tiles that changed slug.
This would effectively remove the tile target from the filter.
- Created a new type `DashboardTileWithSlug` that extends `DashboardTile` with a `tileSlug` property
- Updated the filter matching logic to check both `tileSlug` and `chartSlug` when finding the corresponding tile
- Updated return types in relevant functions to use the new type
1. Download a dashboard with filters
2. Update tile target `tileSlug` and tile `tileSlug` but keep `chartSlug` the same.
3. Run `lightdash upload --force` …

fix: find tile targets first by tileSlug

---

packages/backend/src/ee/services/ai/agents/agent.ts
packages/backend/src/ee/services/ai/prompts/system.ts
packages/backend/src/ee/services/ai/tools/findFields.ts
packages/common/src/ee/AiAgent/schemas/tools/toolProposeChange.ts

Add support for self-improvement capabilities to AI agents, allowing them to propose changes to the semantic layer. This includes:
- Added `enableSelfImprovement` flag to agent messages and system prompt
- Enhanced system prompt with guidelines for proposing semantic layer changes
- Updated field description format in `findFields.ts` to use consistent `<description>` tags
- Improved documentation in the propose change tool schema to emphasize preserving existing content

fix: improve prompt for propose change tool

---

packages/backend/src/models/ProjectModel/ProjectModel.ts

Refactored the `applyChangeset` method in `ProjectModel` to improve how changes are applied to explores. The key improvements include:
1. Removed the unused `projectUuid` parameter from `applyChangeset`
2. Restructured the change application logic to process changes by explore rather than by change
3. Enhanced the `applyChange` method to support more entity types (CompiledTable and Explore)
4. Improved error handling for unsupported operations
5. Fixed the patch application logic to properly handle different entity types and change operations
This refactoring makes the changeset application more robust and maintainable while preserving the same functionality.

fix: changeset application logic

---

packages/common/src/types/changeset.ts
packages/frontend/src/features/changesets/components/ProjectChangesets.tsx
packages/frontend/src/features/changesets/hooks/index.ts
packages/frontend/src/features/changesets/hooks/useActiveChangesets.ts
packages/frontend/src/pages/ProjectSettings.tsx
packages/frontend/src/pages/Settings.tsx

Closes: #N/A
Adds a new Changesets UI to the project settings page, allowing users to track changes to their project over time. The implementation includes:
- A new `ProjectChangesets` component that displays a table of changes with details like entity name, change type, and creator
- Integration with the existing changesets API
- A new "Changesets" tab in the project settings navigation
- Support for viewing different change types (create, update, delete) with appropriate styling
- Tooltips showing additional information like table names and timestamps
The UI shows changes in an organized table format with proper handling for loading, error, and empty states.

feat: add initial project changesets table in settings

---

packages/common/src/ee/AiAgent/schemas/tools/toolProposeChange.ts
packages/frontend/.storybook/preview.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatAssistantBubble.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/AiChartToolCalls.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/AiProposeChangeToolCall/ChangeRenderer.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/AiProposeChangeToolCall/OperationRenderer.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/AiProposeChangeToolCall/SupportElements.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/AiProposeChangeToolCall/index.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/AiProposeChangeToolCall/types.ts
packages/frontend/src/stories/AiProposeChangeToolCall.stories.tsx

This PR adds a UI component to display proposed changes tool calls in the UI.
- Created a new `AiProposeChangeToolCall` component to render proposed changes
- Implemented renderers for different entity types (table, dimension, metric)
- Added support for displaying field operations (currently only 'replace')
- Added storybook `stories` file to test multiple variants of the component without the need to prompt ai

feat: introduce propose change tool template

---

packages/frontend/src/components/UserSettings/MyWarehouseConnectionsPanel/index.tsx

Closes: #17193
Added an informational callout to the Personal Warehouse Connections panel explaining that these credentials are only used for projects requiring user credentials. The callout includes a "learn more" link to the documentation. The callout appears both when credentials exist and when no credentials have been added yet.
test-frontend

chore: add callout to personal connections page

---

examples/full-jaffle-shop-demo/dbt/dbt_project.yml
packages/cli/src/dbt/context.test.ts
packages/cli/src/dbt/context.ts

Closes:  https://github.com/lightdash/lightdash/issues/17165
> target-path: "{{ env_var('DBT_ENV__TARGET_FOLDER', 'target') }}"
> export DBT_ENV__TARGET_FOLDER='new_target'

fix: process env_var in project yml

---

packages/backend/src/database/entities/changesets.ts
packages/backend/src/ee/index.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/ee/services/ai/agents/agent.ts
packages/backend/src/ee/services/ai/tools/proposeChange.test.ts
packages/backend/src/ee/services/ai/tools/proposeChange.ts
packages/backend/src/ee/services/ai/types/aiAgent.ts
packages/backend/src/ee/services/ai/types/aiAgentDependencies.ts
packages/backend/src/ee/services/ai/utils/populateCustomMetricsSQL.ts
packages/backend/src/ee/services/ai/utils/validators.ts
packages/common/src/ee/AiAgent/schemas/customMetrics.ts
packages/common/src/ee/AiAgent/schemas/tools/toolProposeChange.ts
packages/common/src/types/changeset.ts
packages/common/src/utils/changeset.ts

This PR adds support for creating metrics via the AI agent's proposeChange tool. The implementation includes:
1. Updated the DbChangeSchema to support a new payload type for metric creation
2. Enhanced the proposeChange tool to handle metric creation requests
3. Added the ExploreCompiler dependency to the AiAgentService to compile SQL for new metrics
4. Created a utility function to populate custom metric SQL from explore fields
5. Updated the changesets utility to properly handle metric creation changes
This allows users to request the AI agent to create new metrics in the semantic layer, which will be proposed as changes that can be reviewed and approved.

feat: add support for creating metrics via AI agent

---

.gitignore
packages/cli/entitlements.plist
packages/cli/package.json
packages/cli/pkg.config.json
packages/cli/scripts/build-binaries.sh
pnpm-lock.yaml

**How to review**
The .sh script is mostly an example and not the core contribution. The package commands, and configuration are what need reviewing. We we eventually formalise the binary building with a github action. The .sh script is mostly for dev testing and to show roughly the process for building.
This adds 
- a build script for building the Lightdash CLI
- signing and notorizing it for Apple
- and then zipping and creating checksums for github releases
it doesn't _yet_ add any automation or github actions to do this continuously.
I already added mac binaries here: https://github.com/lightdash/lightdash/releases/tag/0.2031.0
And updated our homebrew tap https://github.com/lightdash/homebrew-lightdash
You can test this by running the build script script locally (although you will …

chore: add script to generate cli mac binary

---

packages/backend/src/ee/controllers/aiAgentController.ts
packages/backend/src/ee/database/entities/ai.ts
packages/backend/src/ee/models/AiAgentModel.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/ee/services/ai/tools/proposeChange.ts
packages/backend/src/ee/services/ai/types/aiAgentDependencies.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/ChangesetModel.ts
packages/common/src/ee/AiAgent/index.ts
packages/common/src/ee/AiAgent/schemas/tools/toolProposeChange.ts

Adds the ability to revert changes proposed by the AI agent. This PR implements a new endpoint to revert changes and updates the metadata tracking to record when users reject proposed changes.
Key changes:
- Added a new `revertChange` endpoint in the AI agent controller
- Enhanced the tool result metadata schema to track user feedback (accepted/rejected)
- Updated the `ToolProposeChangeOutput` schema to include change UUID and user feedback
- Implemented the ability to update tool result metadata when changes are reverted
- Modified the message rendering to show when a proposed change has been rejected

feat: add ability to revert AI agent proposed changes

---

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatAssistantBubble.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/AiProposeChangeToolCall/index.tsx
packages/frontend/src/ee/features/aiCopilot/hooks/useProjectAiAgents.ts

Added the ability to reject AI-proposed changes in the chat interface. This feature allows users to revert changes made by the AI assistant directly from the chat bubble. The implementation includes:
- Added a "Reject" button to the AI propose change tool call component
- Connected the button to a new revert change mutation
- Added necessary props to pass project, agent, thread, and prompt UUIDs to the component
- Implemented state handling to show when a change has been rejected
- Added visual feedback during the rejection process

feat: add reject functionality for AI proposed changes frontend

---

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/AiProposeChangeToolCall/index.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/ToolCallPaper.tsx
packages/frontend/src/stories/AiProposeChangeToolCall.stories.tsx

Added a "View Changeset" button to the AI propose change tool call component that links to the project's changeset page.

feat: add view changeset button in propose change tool ui

---

packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/services/CatalogService/CatalogService.ts
packages/common/src/types/changeset.ts

Closes: N/A
Adds support for creating metrics through changesets. This PR:
- Implements the `create` change type for metrics in the `CatalogModel`
- Adds the metric schema definition in the `ChangeSchema` to validate metric payloads
- Passes the explore cache map to catalog search functions to ensure metrics have access to their associated explore data
- Updates the catalog service to load explore data from cache when processing metrics
This enables users to create metrics through the changeset workflow, with proper validation and integration into the catalog system.

feat: handle ai metric creation on catalog_search index

---

packages/backend/src/database/entities/savedCharts.ts
packages/backend/src/database/migrations/20250925130222_saved_chart_table_calculation_templates.ts
packages/backend/src/ee/services/AiService/utils/prepareData.ts
packages/backend/src/generated/routes.ts
packages/backend/src/models/SavedChartModel.ts
packages/backend/src/queryCompiler.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/backend/src/services/RenameService/rename.test.ts
packages/backend/src/services/RenameService/rename.ts
packages/backend/src/services/ValidationService/ValidationService.test.ts
packages/backend/src/services/ValidationService/ValidationService.ts
packages/backend/src/utils/QueryBuilder/MetricQueryBuilder.mock.ts
packages/common/src/compiler/exploreCompiler.mock.ts
packages/common/src/types/field.ts
packages/common/src/types/warehouse.ts
packages/common/src/utils/convertCustomDimensionsToYaml.ts
packages/common/src/utils/virtualView.ts
packages/frontend/src/components/Explorer/ResultsCard/QuickCalculations.tsx
packages/frontend/src/components/Explorer/ResultsCard/tableCalculationTemplateGenerator.ts
packages/frontend/src/features/tableCalculation/components/TableCalculationModal.tsx
packages/frontend/src/features/tableCalculation/components/TemplateViewer/TemplateViewer.tsx
packages/frontend/src/features/tableCalculation/utils/templateFormatting.ts
packages/frontend/src/providers/Explorer/ExplorerProvider.test.tsx
packages/frontend/src/providers/Explorer/ExplorerProvider.tsx
packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
packages/warehouses/src/warehouseClients/TrinoWarehouseClient.ts
packages/warehouses/src/warehouseClients/WarehouseBaseClient.ts
packages/warehouses/src/warehouseClients/WarehouseBaseSqlBuilder.ts

This PR adds support for table calculation templates, allowing users to create calculations using predefined formulas instead of writing raw SQL. The implementation includes:
- Added a new `template` field to the `saved_queries_version_table_calculations` table
- Created a `TableCalculationTemplate` type with support for 5 template types:
- Percent change from previous
- Percent of previous value
- Percent of column total
- Rank in column
- Running total
- Updated the Quick Calculations menu to use templates instead of generating SQL
- Added a template viewer in the table calculation modal
- Implemented SQL generation from templates at query compilation time
- Updated validation and rename services to handle template-based calculations
This makes it easier for users to create common …

feat: add table calculation templates

---

packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/ee/services/McpService/McpSchemaCompatLayer.test.ts
packages/backend/src/ee/services/ai/tools/generateBarVizConfig.ts
packages/backend/src/ee/services/ai/tools/generateTableVizConfig.ts
packages/backend/src/ee/services/ai/tools/generateTimeSeriesVizConfig.ts
packages/backend/src/ee/services/ai/tools/runMetricQuery.ts
packages/backend/src/ee/services/ai/utils/validateBarVizConfig.ts
packages/backend/src/ee/services/ai/utils/validateTableVizConfig.ts
packages/backend/src/ee/services/ai/utils/validateTimeSeriesVizConfig.ts
packages/backend/src/ee/services/ai/utils/validators.ts
packages/common/src/ee/AiAgent/schemas/index.ts
packages/common/src/ee/AiAgent/schemas/tableCalcs/tableCalcBaseSchemas.ts
packages/common/src/ee/AiAgent/schemas/tableCalcs/tableCalcPercentChangeFromPrevious.ts
packages/common/src/ee/AiAgent/schemas/tableCalcs/tableCalcPercentOfColumnTotal.ts
packages/common/src/ee/AiAgent/schemas/tableCalcs/tableCalcPercentOfPreviousValue.ts
packages/common/src/ee/AiAgent/schemas/tableCalcs/tableCalcRankInColumn.ts
packages/common/src/ee/AiAgent/schemas/tableCalcs/tableCalcRunningTotal.ts
packages/common/src/ee/AiAgent/schemas/tableCalcs/tableCalcs.test.ts
packages/common/src/ee/AiAgent/schemas/tableCalcs/tableCalcs.ts
packages/common/src/ee/AiAgent/schemas/tools/toolDashboardArgs.ts
packages/common/src/ee/AiAgent/schemas/tools/toolRunMetricQueryArgs.ts
packages/common/src/ee/AiAgent/schemas/tools/toolTableVizArgs.ts
packages/common/src/ee/AiAgent/schemas/tools/toolTimeSeriesArgs.ts
packages/common/src/ee/AiAgent/schemas/tools/toolVerticalBarArgs.ts
packages/common/src/ee/AiAgent/schemas/visualizations/tableViz.ts
packages/common/src/ee/AiAgent/schemas/visualizations/timeSeriesViz.ts
packages/common/src/ee/AiAgent/schemas/visualizations/verticalBarViz.ts
packages/common/src/ee/AiAgent/types.ts
packages/common/src/ee/AiAgent/utils.ts
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AiVisualizationRenderer.tsx

Add table calculations support to AI agent visualizations
This PR adds support for table calculations in AI-generated visualizations. Table calculations allow users to perform operations like percent change, running totals, and rankings across rows without collapsing data.
Key changes:
- Created schemas for different table calculation types (percent change, running total, etc.)
- Added validation for table calculations to ensure they reference valid metrics
- Implemented conversion from AI table calculation schema to Lightdash table calculation format
- Integrated table calculations into visualization tools (bar, table, time series)
- Removed TODO comments for table calculations that are now implemented
- Updated column ordering in visualization renderer to include table calculation …

feat: add table calculations support for AI agent visualizations

---

packages/backend/src/ee/services/ai/agents/agent.ts
packages/backend/src/ee/services/ai/tools/generateBarVizConfig.ts
packages/backend/src/ee/services/ai/tools/generateTableVizConfig.ts
packages/backend/src/ee/services/ai/tools/generateTimeSeriesVizConfig.ts

Closes: N/A
Added self-improvement capability to visualization tools. When custom metrics are created during visualization generation, the AI agent can now suggest creating these metrics in the semantic layer if `enableSelfImprovement` is enabled.
This enhancement was implemented across bar, table, and time series visualization tools, allowing the agent to provide follow-up suggestions when it identifies opportunities to improve the semantic layer with newly created metrics.

feat: ask user to create metric from custom metric after ai artifact

---

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/AiProposeChangeToolCall/ChangeRenderer.tsx
packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/AiProposeChangeToolCall/types.ts
packages/frontend/src/stories/AiProposeChangeToolCall.stories.tsx

Added a new `CreateMetric` component to render metric creation in proposed changes.
_before_
_after_

feat: display metric creation in Propose Change tool ui

---

packages/backend/src/ee/services/ai/models/openai-gpt.ts

Disabled parallel tool calls for OpenAI GPT models by setting `parallelToolCalls: false` in the provider options. This ensures that tool calls are processed sequentially rather than in parallel, which can help with certain execution patterns or prevent race conditions.

feat: disable parallel tool calls for OpenAI GPT model

---

packages/frontend/src/components/common/Dashboard/DashboardRefreshButton.tsx

Closes: #17229
Auto-refresh was confusing with cache enabled. It just said `Auto-refresh` next to the cache-refresh time. This changes the text to make it clear that it's only while viewing the dashboard. 
Also fixes the tooltip opening behind the menu

fix: improve auto-refresh UI

---

packages/backend/package.json
packages/backend/src/clients/Slack/SlackClient.ts
pnpm-lock.yaml

Adds support for OAuth flow in Slack socket mode by integrating the `@slack/oauth` package. This implementation creates an `InstallProvider` to handle OAuth callbacks and registers a route at `/api/v1/slack/oauth_redirect` to properly manage the Slack OAuth flow. The code also improves error handling when starting the Slack app and refactors the initialization process to reduce code duplication.
So the app works in `socketMode` we need to change the manifest to include: `"socket_mode_enabled": true`

fix: slack app in socket mode

---

packages/backend/src/controllers/ChangesetController.ts
packages/backend/src/ee/services/AiAgentService.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/ChangesetModel.ts
packages/backend/src/services/ChangesetService.ts
packages/backend/src/services/ServiceRepository.ts

Added API endpoints to revert changes in the changeset system. This PR introduces two new endpoints:
1. `/changes/{changeUuid}/revert` - Reverts a specific change by its UUID
2. `/revert-all` - Reverts all changes in the active changeset for a project

feat: add API endpoints to revert changes in changesets

---

packages/frontend/src/features/changesets/components/ProjectChangesets.tsx
packages/frontend/src/features/changesets/hooks/index.ts
packages/frontend/src/features/changesets/hooks/useActiveChangesets.ts
packages/frontend/src/features/changesets/hooks/useRevertAllChanges.ts
packages/frontend/src/features/changesets/hooks/useRevertChange.ts

Added the ability to revert changes in the Project Changesets UI. Users can now:
- Revert individual changes by clicking the new "Revert" button in the last row
- Revert all changes at once using the new "Revert All" button
- Confirmation modals prevent accidental reverts
- Success/error toasts provide feedback on revert operations
This implementation includes two new hooks:
- `useRevertChange` for reverting a single change
- `useRevertAllChanges` for reverting all changes at once

feat: add ability to revert changes in project changesets

---

packages/backend/src/clients/EmailClient/EmailClient.ts
packages/backend/src/scheduler/SchedulerTask.ts

Closes: #7961
Added email notifications for scheduled delivery failures. When a scheduled delivery fails, the system now sends an email to the scheduler creator with details about the error and a link to the scheduler settings. This helps users quickly identify and fix issues with their scheduled deliveries.
- A new `sendScheduledDeliveryFailureEmail` method in the EmailClient
- Error handling in the SchedulerTask to capture failures and trigger the notification
- Proper URL construction to direct users to the relevant scheduler settings
You can test this by adding this to `UnfurlService`
`throw new Error('Testing notification error');`

feat: send email notification when schedule fails

---

packages/backend/src/ee/services/AiAgentService.ts

Reply with message when an AI agent is not found for a Slack channel instead of no response

feat: display slack message when AI Agent is not found for channel

---

packages/backend/src/ee/services/ai/tools/proposeChange.ts
packages/backend/src/ee/services/ai/tools/runMetricQuery.ts
packages/backend/src/ee/services/ai/utils/validateBarVizConfig.ts
packages/backend/src/ee/services/ai/utils/validateTableVizConfig.ts
packages/backend/src/ee/services/ai/utils/validateTimeSeriesVizConfig.ts

Closes: https://github.com/lightdash/lightdash/issues/17273
Improves field validation in AI tools by using more specific validation functions. This PR replaces generic field existence checks with type-specific validation (`validateFieldEntityType`) to ensure dimensions and metrics are used correctly in their respective contexts. The changes affect multiple visualization tools (table, bar, time series) and the propose change functionality.
The main improvement is that we now validate that fields are of the correct type (dimension or metric) rather than just checking if they exist, which prevents misuse of fields in inappropriate contexts.

feat: validate field entity types in AI visualization tools

---

packages/cli/src/dbt/models.ts

Closes:
Fixes a bug in `lightdash generate` where column metadata was being double-wrapped with `meta`, causing:
```
- dbt 1.9: Generated YAMLs with meta: { meta: { dimension: ... } } instead of meta: { dimension: ... }
- dbt 1.10: Generated YAMLs with config: { meta: { meta: { dimension: ... } } } instead of config: { meta: { dimension: ... } }
```
This caused errors when deploying metrics that referenced these incorrectly nested fields.
:bulb: Used this: `node ./packages/cli/dist/index.js generate -s orders --project-dir ./examples/full-jaffle-shop-demo/dbt --profiles-dir ./examples/full-jaffle-shop-demo/profiles`​
In `/packages/cli/src/dbt/models.ts`, the `generateModelYml` function was passing an extra meta wrapper to the `wrapInConfig` helper:
```
wrapInConfig(dbtVersion, {
meta: { …
```

fix: wrap in config and do not duplicate meta

---

packages/backend/src/ee/services/ai/tools/generateDashboard.ts

Reordered the artifact creation logic in the dashboard generation process to ensure it only occurs after successful validation. This change moves the `createOrUpdateArtifact` call after the error handling logic, preventing artifacts from being created when there are validation errors.

fix: move artifact creation after error handling in dashboard generation

---

packages/frontend/src/providers/Explorer/ExplorerProvider.tsx

Fixes a bug where editing a chart, then cancelling keeps the edited unsavedChartVersion
To repro:
- Save a chart
- Edit it, make changes
- Cancel
- Edit again
- You will see the previously edited version
Note on implementation: I added the redux reset to the context instead of bringing redux into the Saved Chart Header. I did it this was because the header doesn't use redux yet. We could put the redux reset in the header instead, but it seems a little more prone to getting out of sync. Probably we should just migrate the header component to use all redux soon.

fix: cancelling a chart edit should reset editing

---

packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/common/src/types/projects.ts

Add support for duplicating AI agents when creating project previews. This includes copying:
- AI agent base records
- Instruction versions
- Group access permissions
- User access permissions
The implementation maps original AI agent UUIDs to new ones in the preview project, ensuring all relationships are maintained correctly. This mapping is stored in the `preview_content` table for reference.
Note: AI Agent integrations (including Slack) are intentionally skipped for preview projects due to organization-wide constraints such as one agent per Slack channel.

feat: duplicate AI agents when creating project previews

---

packages/frontend/src/providers/Explorer/ExplorerProvider.tsx

Closes: #17300
Removing a field from a saved chart causes an error when the chart is sorted by that field. This used to fall back to the default sort instead.
**Repro:**
Create a chart with a sort by dimension
Remove that dimension
Error
**Bug**
**Fixed**

fix: removing a sorted field causes a query error

---

packages/frontend/src/ee/features/aiCopilot/components/ChatElements/ToolCalls/AiProposeChangeToolCall/ChangeRenderer.tsx

Enhanced the display of metric information in the AI Copilot's ChangeRenderer component by adding the base dimension name to the metric type label. This provides users with more context about the metric being created or modified.

fix: display base dimension name in proposed metric label

---

packages/frontend/src/components/SchedulersView/LogsTable.tsx
packages/frontend/src/components/SchedulersView/SchedulersTable.tsx

Closes: #N/A
Improves the table height consistency in the Schedulers view by setting both the LogsTable and SchedulersTable to use the same dynamic height calculation (`calc(100dvh - 420px)`). This replaces the previous fixed height of 600px for the SchedulersTable and adjusts the LogsTable from `-500px` to `-420px`, ensuring a more consistent UI experience.

style: uniform schedule & logs table heights

---

packages/backend/src/config/aiConfigSchema.ts

Closes: 
Updated the default Anthropic model name from `claude-4-sonnet-20250514` to `claude-sonnet-4-20250514` to match the correct naming convention.

fix: claude sonnet default name fix

---

packages/common/src/ee/AiAgent/schemas/customMetrics.ts

Added a new `description` field to the custom metric base schema. This field allows users to provide a brief explanation of what the metric represents, how it's calculated, and why it matters. The description includes an example to guide users: "Calculates the total revenue by summing all transaction amounts in the sales table."

feat: add description field to custom metric schema

---

packages/common/src/pivot/derivePivotConfigFromChart.mock.ts
packages/common/src/pivot/derivePivotConfigFromChart.test.ts
packages/common/src/pivot/derivePivotConfigFromChart.ts
packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx
packages/frontend/src/features/explorer/store/selectors.ts
packages/frontend/src/hooks/explorer/buildQueryArgs.ts
packages/frontend/src/hooks/useExplorerQuery.ts
packages/frontend/src/hooks/useExplorerQueryManager.ts

Closes: #17018
Refactored pivot configuration logic by extracting the `getIndexColumn` function to reduce code duplication between table and cartesian pivot configurations. This improves maintainability and ensures consistent behavior when determining index columns for different chart types.
The PR also removes an unused import (`VizIndexType`) and simplifies the cartesian pivot configuration by using the same index column determination logic as tables.
**Before**
**After**
1. Create chart with group by
2. Sort by a column not included in either the X axis or group by
3. Sort should be respected

fix: include non grouped dimensions in index
