lightdash/lightdash

- packages/e2e/cypress/e2e/dates.cy.ts
Closes: 
This weekend (!?) we changed to winter time (no dailight saving) so some timezone tests are breaking
> test: fix  dailight saving timezone test

- packages/cli/src/dbt/schema.ts
- packages/cli/src/handlers/generate.ts
Closes: #3581 
Keeps all comments and empty lines at the top of the existing file
https://user-images.githubusercontent.com/9117144/198684264-04a1d920-2907-4a24-9037-f48e79d5a7d1.mp4
> feat: keep head comments on generate command

- packages/frontend/package.json
- packages/frontend/src/components/RefreshButton.tsx
- packages/frontend/src/hooks/useQueryResults.tsx
- packages/frontend/src/providers/ExplorerProvider.tsx
- yarn.lock
Closes: https://github.com/lightdash/lightdash/issues/733
disable button if query does not contain any changes
https://user-images.githubusercontent.com/962095/198999993-841729d8-83b8-47ec-837b-ea8b7d082e5c.mp4
> feat: disable run query button if query does not contain any changes

- packages/cli/src/dbt/context.ts
- packages/cli/src/globalState.ts
- packages/cli/src/handlers/compile.ts
- packages/cli/src/handlers/createProject.ts
- packages/cli/src/handlers/dbt/apiClient.ts
- packages/cli/src/handlers/dbt/compile.ts
- packages/cli/src/handlers/dbt/refresh.ts
- packages/cli/src/handlers/dbt/run.ts
- packages/cli/src/handlers/deploy.ts
- packages/cli/src/handlers/generate.ts
- packages/cli/src/handlers/login.ts
- packages/cli/src/handlers/preview.ts
- packages/cli/src/handlers/setProject.ts
- packages/cli/src/index.ts
- packages/cli/src/styles.ts
- Save verbose mode in global state instead of prop drilling
- Use global state to record debug logs
- Debug logs are grey to distinguish from normal logs
> chore: verbose and debug logs in  global state

- packages/cli/src/dbt/models.ts
- packages/cli/src/globalState.ts
- packages/cli/src/handlers/dbt/refresh.ts
- packages/cli/src/handlers/deploy.ts
- packages/cli/src/handlers/generate.ts
- packages/cli/src/handlers/preview.ts
Create and access spinners from the global state instead of prop drilling.
> chore: create spinners in global state

- packages/common/src/compiler/exploreCompiler.ts
- packages/common/src/compiler/filtersCompiler.ts
- packages/common/src/compiler/translator.ts
- packages/common/src/index.ts
- packages/common/src/utils/assertUnreachable.ts
- packages/frontend/src/components/UserSettings/UserManagementPanel/InviteSuccess.tsx
fixes few annoying linter warnings.
> chore: fix annoying eslint warnings

- packages/e2e/cypress/e2e/createProjects.cy.ts
- packages/e2e/cypress/e2e/dates.cy.ts
> test: fix date tokyo test and increase timeout to results 

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/Explorer/SaveChartButton/index.tsx
- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
- packages/frontend/src/hooks/useSavedQuery.ts
Closes:  #1208
[Screencast from 02-11-22 14:37:11.webm](https://user-images.githubusercontent.com/1983672/199503863-4b2fb963-87a7-4528-a082-b0df6eecd90d.webm)
> feat: edit chart redirect back to dashboard

- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/SimpleTable/index.tsx
- packages/frontend/src/components/TableConfigPanel/index.tsx
- packages/frontend/src/components/common/Table/TableProvider.tsx
- packages/frontend/src/components/common/Table/index.tsx
- packages/frontend/src/hooks/tableVisualization/getDataAndColumns.tsx
- packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
Closes: #3295
[Screencast from 03-11-22 09:40:17.webm](https://user-images.githubusercontent.com/1983672/199678980-5ecdb4db-0666-446b-be25-f7c4c829b9f1.webm)
> feat: hide row numbers

- docs/docs/guides/cli/how-to-use-lightdash-preview.mdx
- docs/docs/guides/exploring-your-content.mdx
- docs/docs/guides/visualizing-your-results.mdx
- docs/docs/references/dimensions.mdx
- docs/docs/references/joins.md
- docs/docs/references/metrics.mdx
Closes: 
#3535 
#3548 
Updates docs to include information on URLs relying on other column values, personal access token links in setting up preview github action.
> docs: update docs with new features

- packages/frontend/src/components/Home/LatestDashboards/index.tsx
- packages/frontend/src/components/Home/LatestSavedCharts/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/3683
fixes view permission for view all button for recent dashboards/charts
> fix: view permision for view all button for recent dashboards/charts

- packages/frontend/src/components/UnderlyingData/UnderlyingDataProvider.tsx
Closes: #3671
[Screencast from 04-11-22 09:21:56.webm](https://user-images.githubusercontent.com/1983672/199926561-6d7f70e3-3d30-435b-8f99-93250673a3ad.webm)
> fix: underlying data query on close

- packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectManually/ConnectManuallyStep1.tsx
- packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectUsingCLI.tsx
- packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ProjectConnectFlow.styles.tsx
- packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/UnsupportedWarehouse.tsx
- packages/frontend/src/pages/CreateProject.styles.tsx
Closes: https://github.com/lightdash/lightdash/issues/3688
https://user-images.githubusercontent.com/962095/200011546-c2a7d103-2bf7-46ef-aabd-f2653cf49f34.mp4
> style: fixed position for onboarding cards

- packages/frontend/src/components/common/ResourceList/ResourceEmptyState.styles.ts
Closes: https://github.com/lightdash/lightdash/issues/3691
> style: update empty state icon color

- packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/CustomMetricButtons.tsx
- packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/FieldButtons.tsx
Closes: https://github.com/lightdash/lightdash/issues/3692
> fix: popover position for metrics/dimensions

- packages/frontend/src/components/SimpleTable/DashboardCellContextMenu.tsx
Closes: #3672 
Changes:
- suggest filter for each pivot value
- apply all pivot values and dashboard filters when seeing underlying data
Note that there is a separate issue to fix case where unsaved dashboard filters aren't applied to underlying data #3685
> fix: dashboard table cell context menu options

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/SimpleTable/DashboardCellContextMenu.tsx
- packages/frontend/src/hooks/dashboard/useDashboardFiltersForExplore.ts
> fix: underlying data with unsaved dashboard filter

- packages/frontend/src/components/common/Filters/FilterInputs/AutoComplete/MultiAutoComplete.tsx
Closes:  #3653
[Screencast from 03-11-22 17:04:36.webm](https://user-images.githubusercontent.com/1983672/199773769-67052452-ca82-4bab-9f31-f2780b936771.webm)
> fix: filter autocomplete click bug

- packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
- packages/frontend/src/providers/ExplorerProvider.tsx
Closes:#3142
Before:
After:
After adding custom metric
> feat: remove magic metrics

- packages/frontend/src/components/Explorer/SpaceBrowser/AddResourceToSpaceModal.style.tsx
- packages/frontend/src/components/Explorer/SpaceBrowser/AddResourceToSpaceModal.tsx
Closes: https://github.com/lightdash/lightdash/issues/3269
> fix: add proper disabled styles for add to space item

- packages/frontend/src/pages/Settings.styles.tsx
- packages/frontend/src/pages/Settings.tsx
Closes: https://github.com/lightdash/lightdash/issues/3713
> feat: remove collapsable menus in settings

- packages/common/src/utils/assertUnreachable.ts
- packages/frontend/src/components/Explorer/SpaceBrowser/AddResourceToSpaceModal.tsx
- packages/frontend/src/components/Explorer/SpaceBrowser/CreateResourceToSpace.tsx
- packages/frontend/src/components/common/ResourceList/index.tsx
- packages/frontend/src/components/common/SpaceActionModal/index.tsx
- packages/frontend/src/providers/ExplorerProvider.tsx
- packages/frontend/src/utils/sortUtils.ts
- packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts
Closes: #3731 
Changes:
- require error message in assertUnreachable
- fallback unexpected databricks column type to string
> fix: databricks column type fallback

- packages/frontend/src/components/common/Page/PageWithSidebar.tsx
- packages/frontend/src/pages/Settings.tsx
Closes: https://github.com/lightdash/lightdash/issues/3742
> fix: settings page vertical alignment

- packages/e2e/cypress/e2e/dates.cy.ts
- packages/frontend/src/components/common/YearInput.tsx
Closes:  #3753
Before
[Screencast from 10-11-22 16:03:27.webm](https://user-images.githubusercontent.com/1983672/201136753-9e7ac3e5-e04a-4454-baca-28e3f756ed6c.webm)
Now
[Screencast from 10-11-22 16:29:34.webm](https://user-images.githubusercontent.com/1983672/201136780-1043575e-e273-4f77-8b7a-85ba1d2277a5.webm)
> fix: fix wrong year on year input change

- packages/common/src/types/savedCharts.ts
- packages/frontend/jest.config.ts
- packages/frontend/src/components/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
- packages/frontend/src/components/ChartConfigPanel/Series/SingleSeriesConfiguration.tsx
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/SimpleChart/index.tsx
- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes: #1652
[![180bc9c3abac4454a5b9c6be32aab166-with-play](https://user-images.githubusercontent.com/9117144/200864882-72201aab-a0a2-4e7d-ac14-8ed8c48ae2ec.gif)](https://www.loom.com/share/180bc9c3abac4454a5b9c6be32aab166)
> feat: stack totals

- packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
> fix: validate filter string values

- packages/common/src/index.ts
- packages/e2e/cypress/e2e/dates.cy.ts
> fix: change date when changing date operator

- packages/frontend/src/components/ChartConfigPanel/Grid/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/3670
updates inputs to have unit switcher:
https://user-images.githubusercontent.com/962095/201704201-ee8bbbe5-dbff-491e-a1cc-3c001be37e21.mp4
> chore: update inputs for margin config

- docs/package.json
- docs/yarn.lock
> chore(deps): bump docs dependencies

- packages/frontend/src/components/UnderlyingData/UnderlyingDataModalContent.tsx
> fix: show underlying data errors

- packages/frontend/src/components/CSVExporter/index.tsx
- packages/frontend/src/components/ChartDownload.tsx
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/DownloadCsvButton/index.tsx
- packages/frontend/src/components/DownloadCsvPopup/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/3721
- updated button styles
- removed card wrapper which created an unwanted border
- wrapped radio groups in form group for better UI
before:
after:
> feat: export as csv style consistency

- packages/frontend/src/components/common/Table/BodyCell.tsx
- yarn.lock
Closes: https://github.com/lightdash/lightdash/issues/3750
⚠️ I'm changing from not rendering a popover when the cell is not selected to `lazy` popover again. let's watch out if it has a significant performance hit.
https://user-images.githubusercontent.com/962095/201629227-6c874e9c-c06d-4f67-a7db-24fd000e91e4.mp4
> fix: select and copy value from table cell

- packages/backend/src/models/SpaceModel.ts
- packages/backend/src/services/SpaceService/SpaceService.ts
Closes: 
Fix bug when change space private state when there is another user on it. 
[Screencast from 22-11-22 15:13:03.webm](https://user-images.githubusercontent.com/1983672/203335964-9bd3c23f-624b-4b0e-853f-342456bf72a1.webm)
> fix: fix remove previous admin

- packages/frontend/src/components/SpacePanel/index.tsx
> style: change space edit button

- scripts/install.sh
I've added some code to the "install.sh" file so that arch users can install and use it.
> feat: arch linux installation update

- packages/frontend/src/components/DownloadCsvPopup/index.tsx
- packages/frontend/src/components/common/Table/BodyCell.tsx
- packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
- packages/frontend/src/components/common/Table/ScrollableTable/index.tsx
- packages/frontend/src/components/common/Table/Table.styles.ts
- packages/frontend/src/components/common/Table/TableProvider.tsx
Closes: https://github.com/lightdash/lightdash/issues/3781
add `mod+c` for table cells
⚠️ notice the animation
https://user-images.githubusercontent.com/962095/203594786-e23a909b-c564-4301-b60f-dafd8abc4a29.mp4
> feat: cell copy to clipboard

- packages/e2e/cypress/e2e/sqlrunner.cy.ts
- packages/frontend/src/components/common/Table/Table.styles.ts
- packages/frontend/src/components/common/Table/TablePagination/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/3802
updates style/copy for results table count label
> style: table total number

- packages/backend/src/database/entities/spaces.ts
- packages/backend/src/database/migrations/20221123161521_space_owner.ts
- packages/backend/src/models/SpaceModel.ts
- packages/backend/src/services/SpaceService/SpaceService.ts
- packages/frontend/src/components/common/ShareSpaceModal/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/3818
+  created by
> feat: space created_by_user_id and hide users when space is public

- docs/docs/references/metrics.mdx
> docs: update keywords for dbt metrics

- docs/docs/references/metrics.mdx
> docs: Update metrics.mdx

- packages/frontend/src/components/common/Page/Page.styles.ts
Closes: https://github.com/lightdash/lightdash/issues/3811
https://user-images.githubusercontent.com/962095/204540398-d6ad8dac-4be6-40ef-91c6-12eaf41917d6.mp4
> fix: explore container overflow

- README.md
- docs/docs/get-started/setup-lightdash/install-lightdash.mdx
updates waitlist → signup links
> docs: update signup links

- packages/backend/src/database/seeds/development/03_saved_dashboards.ts
- packages/backend/src/models/DashboardModel/DashboardModel.mock.ts
- packages/backend/src/services/DashboardService/DashboardService.mock.ts
- packages/common/src/types/dashboard.ts
- packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx
Closes: https://github.com/lightdash/lightdash/issues/3898
https://user-images.githubusercontent.com/962095/205580566-76977e46-ca27-45cc-bbfe-2f75d144226b.mp4
> fix: dashboard filters missing tile titles

- packages/backend/src/models/SearchModel/index.ts
- packages/backend/src/services/SearchService/SearchService.ts
- packages/backend/src/services/services.ts
- packages/common/src/types/search.ts
> feat: filter charts, dashboards and spaces on global search

- .github/CONTRIBUTING.md
Closes: no related issue
Added extra steps to the dockerless dev set up to make it clearer
> fix: contributing documentation for dockerless dev set up

- packages/frontend/src/pages/Login.tsx
- packages/frontend/src/pages/Register.tsx
- packages/frontend/src/pages/Settings.tsx
- packages/frontend/src/pages/Signup.tsx
Closes: #3933 
Pages that **now** have custom titles:
```
Login / Sign up
Saved Dashboards / Specific Dashboard
Tables / Specific Table
SQL Runner
Saved Charts / Specific Chart
Settings
Project settings
```
> feat: update window titles

- dockerfile
Closes: #1558
Pin `psycopg2-binary==2.8.6` on dockerfile
> fix: fix scrap authentication error psycopg2

- packages/e2e/cypress/e2e/createProjects.cy.ts
- packages/e2e/cypress/e2e/projectPermission.cy.ts
- packages/frontend/src/components/NavBar/ExploreMenu/ExploreMenu.styles.tsx
- packages/frontend/src/components/NavBar/ExploreMenu/index.tsx
Closes: #3915
[Screencast from 08-12-22 11:49:07.webm](https://user-images.githubusercontent.com/1983672/206428274-3447bb6b-a7b0-4742-bf33-d485725fab6e.webm)
With view permissions:
> feat: new explore menu

- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
- packages/frontend/src/components/ChartConfigPanel/Legend/Legend.styles.tsx
- packages/frontend/src/components/ChartConfigPanel/Legend/ReferenceLines.tsx
- packages/frontend/src/components/ChartConfigPanel/Legend/index.tsx
- packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
Closes: #3380
[Screencast from 09-12-22 11:56:50.webm](https://user-images.githubusercontent.com/1983672/206688028-8e2f34db-a72c-4979-a123-a32a74318913.webm)
> feat: reference lines

- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/common/src/utils/filters.ts
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/TileFilterConfiguration.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
- packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx
- packages/frontend/src/hooks/dashboard/useDashboard.tsx
Closes: https://github.com/lightdash/lightdash/issues/3945
Closes: https://github.com/lightdash/lightdash/issues/3938
Closes: https://github.com/lightdash/lightdash/issues/3947
with permissions:
without permissions:
> fix: available filters permissions and fetching

- packages/frontend/src/hooks/dashboard/useDashboardFiltersForExplore.ts
Closes: https://github.com/lightdash/lightdash/issues/3981
testing video:
https://user-images.githubusercontent.com/962095/208123265-cdd08fb8-ae90-497d-8e3d-2fae2fc8b9e5.mp4
> fix: dashboard tile filter is not being removed

- packages/frontend/src/components/Explorer/index.tsx
- packages/frontend/src/components/MetricQueryData/DrillDownMenuItem.tsx
- packages/frontend/src/components/MetricQueryData/DrillDownModal.tsx
- packages/frontend/src/components/MetricQueryData/MetricQueryDataProvider.tsx
- packages/frontend/src/components/MetricQueryData/UnderlyingDataModalContent.tsx
- packages/frontend/src/pages/Dashboard.tsx
Following work from https://github.com/lightdash/lightdash/pull/3967
Changes:
- move logic from menu items to a modal
- add auto-complete field to select dimension
> feat: drill by modal

- packages/frontend/src/components/AboutFooter.tsx
- packages/frontend/src/components/ProjectConnection/ProjectConnection.styles.tsx
- packages/frontend/src/components/ProjectConnection/index.tsx
- packages/frontend/src/components/common/Page/Sidebar.tsx
Closes: https://github.com/lightdash/lightdash/issues/3746
https://user-images.githubusercontent.com/962095/206716008-97dd2105-09d3-4478-ad1d-6d35a55bdc78.mp4
> style: floating test and compile button for project settings

- docs/docs/get-started/setup-lightdash/install-lightdash.mdx
> fix: docs missing link to project creation

- packages/cli/src/handlers/compile.ts
> fix: show warning on validation errors on CLI

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/clients/Slack/Slackbot.ts
- packages/backend/src/services/UnfurlService/UnfurlService.ts
Closes: #4019
[Screencast from 21-12-22 13:23:09.webm](https://user-images.githubusercontent.com/1983672/208905519-033e4ad6-33c5-4c28-9332-ad5720c4b524.webm)
> feat: dynamic slack unfurl

- packages/common/src/types/field.ts
Another typescript error I was getting locally. It makes sense but nobody else is getting these?
> fix: remove undefined error from friendlyName

- packages/frontend/src/components/ChartConfigPanel/Legend/ReferenceLines.tsx
Closes: #4042
[Screencast from 22-12-22 14:16:37.webm](https://user-images.githubusercontent.com/1983672/209142722-942d6630-0f17-4e5b-849c-67fad482709a.webm)
> fix: disable markline toggle

- packages/backend/src/database/seeds/development/03_saved_dashboards.ts
- packages/common/src/openapi/schemas/DashboardFilterRule.json
- packages/common/src/openapibundle.json
- packages/common/src/types/filter.ts
- packages/common/src/utils/filters.ts
- packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilter.tsx
- packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterSettings.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
- packages/frontend/src/components/DashboardFilter/FilterSearch/index.tsx
- packages/frontend/src/components/DashboardFilter/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/3658
adds label for dashboard filters
https://user-images.githubusercontent.com/962095/208946492-e77d5576-8ad3-485c-8b7e-2c7726b11352.mp4
> feat: dashboard filter labels

- docs/docs/guides/cli/cli-authentication.mdx
> docs: amend cli login example

- render.yaml
Prevent PR envs to run out of memory. 
Error we were getting before
> chore: increase render envs plan

- packages/common/src/compiler/filtersCompiler.mock.ts
- packages/common/src/compiler/filtersCompiler.test.ts
- packages/common/src/compiler/filtersCompiler.ts
- packages/common/src/types/filter.ts
- packages/common/src/utils/filters.ts
- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/UnitOfTimeAutoComplete.tsx
- packages/frontend/src/components/common/Filters/configs.ts
Closes: #3832 
<a href="https://www.loom.com/share/b2c754c77fc34bf399ad33ebce3f957f">
<p>Lightdash - in the current filters - Watch Video</p>
</a>
> feat: "in the current" date filters

- packages/frontend/src/components/ProjectConnection/index.tsx
Bug: Can't create new project
Problem: 
The user was redirected to the last created/updated project settings page since the active job was a success. 
When a project is created or updated we set the "active job" but in the create project form we weren't checking if that job was the correct one. 
Changes:
Save the job id when the user submits the form and check if the active job id matches the saved job id.
<a href="https://www.loom.com/share/9c32fc2969104b44a61f177d256cea1c">
<p>Lightdash - create project after updating existing project - Watch Video</p>
</a>
> fix: create project after updating existing project

- packages/common/src/types/filter.ts
- packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilter.tsx
- packages/frontend/src/components/common/Filters/configs.ts
- packages/frontend/src/hooks/dashboard/useDashboard.tsx
- packages/frontend/src/providers/DashboardProvider.tsx
Closes: https://github.com/lightdash/lightdash/issues/3660
shows multiple tables
> feat: add tooltip to show multiple tables for dashboard filters

- packages/common/src/compiler/filtersCompiler.mock.ts
- packages/common/src/compiler/filtersCompiler.test.ts
- packages/common/src/compiler/filtersCompiler.ts
- packages/common/src/types/filter.ts
- packages/common/src/utils/filters.ts
- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
- packages/frontend/src/components/common/Filters/configs.ts
> feat: "in the next" date filters

- packages/common/src/types/errors.ts
- packages/frontend/src/components/AppRoute.tsx
- packages/frontend/src/components/MetricQueryData/UnderlyingDataModalContent.tsx
- packages/frontend/src/components/ProjectRoute.tsx
- packages/frontend/src/components/common/Error/index.tsx
- packages/frontend/src/components/common/ErrorState/index.tsx
- packages/frontend/src/pages/Dashboard.tsx
- packages/frontend/src/pages/Home.tsx
- packages/frontend/src/pages/PasswordReset.tsx
- packages/frontend/src/pages/ProjectSettings.tsx
- packages/frontend/src/pages/Projects.tsx
- packages/frontend/src/pages/SavedExplorer.tsx
- packages/frontend/src/pages/Settings.tsx
- packages/frontend/src/pages/Space.tsx
Closes: #3835 
Changes:
- improve default message for Forbidden and Authorization errors
- create a generic component that handles all types of Lightdash errors
Error on space page
Error on chart page
Error on dashboard page
> chore: standard error state and message

- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/ChartConfigPanel/Legend/ReferenceLines.tsx
> feat: color reference line

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/Explorer/ResultsCard/CellContextMenu.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/SeriesContextMenu.tsx
- packages/frontend/src/components/SimpleStatistic/BigNumberContextMenu.tsx
- packages/frontend/src/components/SimpleTable/CellContextMenu.tsx
- packages/frontend/src/components/SimpleTable/DashboardCellContextMenu.tsx
- packages/frontend/src/components/common/Table/TableProvider.tsx
Closes: https://github.com/lightdash/lightdash/issues/4069
https://user-images.githubusercontent.com/962095/211276956-bc8194a2-beff-49b3-b60c-d06d108ebfb7.mp4
> feat: add copy value to all context menus

- packages/cli/src/handlers/compile.ts
> fix: only get catalog for compiled models

- packages/frontend/src/components/MetricQueryData/DrillDownModal.tsx
- packages/frontend/src/components/common/Filters/FieldAutoComplete.tsx
Closes: https://github.com/lightdash/lightdash/issues/2773
https://user-images.githubusercontent.com/962095/211298868-57cf84ba-f36d-4af5-843b-b397418b63ff.mp4
> feat: field autocomplete - sort labels alphabetically

- packages/cli/src/dbt/validation.ts
- packages/cli/src/handlers/compile.ts
Closes: #3877 
Closes: #3135
Before: 
After:
> fix: skip non-compiled models

- packages/cli/src/handlers/compile.ts
- packages/common/src/compiler/exploreCompiler.ts
> fix: show error for invalid show_underlying_values

- docs/docs/snippets/automatically-deploy-your-changes-using-github-action.mdx
Closes: 
Updating docs since we just renamed the template to something less generic.
> docs: update github action template url

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
Closes: https://github.com/lightdash/lightdash/issues/4137
fixes problem with navigation but the problem with large payloads and keeping the state in the URL params is still an issue
> fix: explore from here navigation

- packages/backend/src/index.ts
- packages/backend/src/queryBuilder.ts
- packages/common/src/types/errors.ts
> chore: sentry ignore field reference errors

- packages/frontend/src/components/common/Filters/configs.ts
> fix: "in the current" filter summary

- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/FilterInputs.styles.tsx
Closes: https://github.com/lightdash/lightdash/issues/4147
> fix: date range input wrapper styles

- packages/cli/src/handlers/compile.ts
- packages/e2e/cypress/cli/cli.cy.ts
Closes: #4111 
Related github action template: https://github.com/lightdash/cli-actions/pull/10
Docs update coming next.
> feat: exit process when project fails to compile

- packages/frontend/src/hooks/echarts/useEcharts.ts
> fix: fix echarts axis test failing

- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
Closes: #4162 
2 PR's were merged at the same time and one of them renamed a variable that the first one was using.
> fix: filterRule is not defined

- packages/common/src/utils/conditionalFormatting.ts
- packages/frontend/src/components/ChartConfigPanel/Legend/index.tsx
- packages/frontend/src/components/TableConfigPanel/ConditionalFormatting.styles.ts
- packages/frontend/src/components/TableConfigPanel/ConditionalFormatting.tsx
- packages/frontend/src/components/TableConfigPanel/ConditionalFormattingList.tsx
- packages/frontend/src/components/TableConfigPanel/index.tsx
- packages/frontend/src/components/common/Filters/FieldAutoComplete.tsx
- packages/frontend/src/components/common/Filters/renderFilterItem.tsx
Closes: https://github.com/lightdash/lightdash/issues/3932
https://user-images.githubusercontent.com/962095/212127900-76362706-c3c9-4ed5-aa06-6c6f0d535bf6.mp4
> feat: conditional formatting multiple rules

- packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/NumericInput.styles.tsx
Closes: https://github.com/lightdash/lightdash/issues/4153
Closes: https://github.com/lightdash/lightdash/issues/4179
> fix: numeric input should allow negative values

- packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
- packages/frontend/src/components/DashboardTiles/TileForms/TileModal.tsx
> fix: rename 'edit tile' menu option

- packages/frontend/src/components/TableConfigPanel/ConditionalFormatting.styles.ts
- packages/frontend/src/components/TableConfigPanel/ConditionalFormatting.tsx
- packages/frontend/src/components/TableConfigPanel/ConditionalFormattingList.tsx
- packages/frontend/src/components/TableConfigPanel/ConditionalFormattingRule.tsx
Closes: https://github.com/lightdash/lightdash/issues/3934
https://user-images.githubusercontent.com/962095/212620489-731c4d40-54e4-432e-84de-d0ba4a914d6b.mp4
> feat: conditional formatting multiple conditions

- packages/backend/src/index.ts
- Stops tracing requests from GCP ingress health checks
- Adds user email context
> fix: update sentry config

- packages/common/src/utils/conditionalFormatting.ts
- packages/frontend/src/components/TableConfigPanel/ConditionalFormattingList.tsx
- packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
Closes: https://github.com/lightdash/lightdash/issues/4152
> feat: conditional formatting support all numeric fields

- packages/backend/src/index.ts
- packages/frontend/src/hooks/thirdPartyServices/useSentry.ts
- packages/frontend/src/providers/AppProvider.tsx
Adds user details to frontend sentry events
> chore: add user to sentry frontend

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/models/OrganizationModel.ts
- packages/backend/src/routers/organizationRouter.ts
- packages/backend/src/services/OrganizationService/OrganizationService.test.ts
- packages/backend/src/services/OrganizationService/OrganizationService.ts
- packages/backend/src/services/services.ts
- packages/frontend/config/jest/react-markdown.js
- packages/frontend/config/jest/rehype.js
- packages/frontend/src/components/UserSettings/DeleteOrganisationPanel/DeleteOrganisationPanel.styles.ts
- packages/frontend/src/components/UserSettings/DeleteOrganisationPanel/index.tsx
- packages/frontend/src/hooks/organisation/useOrganisation.ts
- packages/frontend/src/hooks/organisation/useOrganisationDeleteMultation.ts
- packages/frontend/src/pages/Settings.tsx
Closes: #2989
Before deletion
After deletion
Now I'm able to register again with the same email.
[Screencast from 16-01-23 12:28:10.webm](https://user-images.githubusercontent.com/1983672/212668209-61f4100a-7e75-422c-a19f-ade071829813.webm)
> feat: delete organisation

- packages/backend/src/models/SpaceModel.ts
- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
> feat: add chart type to spaces request

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/services/DashboardService/DashboardService.ts
- packages/backend/src/services/SavedChartsService/SavedChartService.ts
> feat: track chart/dashboard views on  rudderstack

- packages/backend/src/models/PinnedListModel.ts
- packages/common/src/index.ts
> fix: pinning common export

- packages/backend/src/database/entities/passwordLogins.ts
- packages/backend/src/models/UserModel.ts
- packages/backend/src/overrideUserPassword.ts
- packages/backend/src/routers/userRouter.ts
- packages/backend/src/services/UserService.ts
- packages/frontend/src/components/UserSettings/PasswordPanel/index.tsx
- packages/frontend/src/hooks/user/usePassword.ts
- packages/frontend/src/pages/Settings.tsx
Closes: #3745 
Changes:
- refactor create and update function from entity file to user model
- expose endpoint to the FE if the user has a password or not
- fix form to set password for first time
https://www.loom.com/share/26fce68fd7ee45dbb6db6faf7b1a6e0d
https://user-images.githubusercontent.com/9117144/214018467-2945b0fe-0957-4c8a-8707-0190a839228d.mp4
> fix: set password for first time

- packages/frontend/src/components/DbtCloudSettings/index.tsx
- packages/frontend/src/components/ProjectAccess/index.tsx
- packages/frontend/src/pages/ProjectSettings.styles.tsx
Resolves https://github.com/lightdash/lightdash/issues/3896
> fix: Remove headings under the Project Settings tabs

- packages/common/src/compiler/translator.ts
> fix: join label

- packages/frontend/src/components/ChartConfigPanel/ChartConfigPanel.styles.ts
Closes:  [#4127](https://github.com/lightdash/lightdash/issues/4127)
> fix: adding max-height and inner-scroll to chart config panel

- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes:  #4248
This should address both issues in  #4248 . Both had table calculations
First case : reference line on table calculation
Second case: multiple axes, metric and table calculation
> fix: fix miN/max for table calculation on reference lines

- packages/frontend/package.json
- packages/frontend/src/components/Explorer/ExploreTree/index.tsx
- yarn.lock
- Remove unused component
- Remove unneeded large dependency (it was a 1mb vendor file!)
Closes:
> fix: remove highlight js

- packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.test.ts
- packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
Closes: #4263
Request columns for a specific database+schema+table instead of all the columns in that user account.
> fix: get snowflake catalog for specific tables

- docs/docs/references/joins.md
Docs to support #4277 and #4236
> docs: add docs for join aliases

- packages/cli/src/handlers/compile.ts
- packages/cli/src/handlers/dbt/getDbtVersion.ts
Closes:  #4211
with invalid version 
with valid version
> feat: cli check dbt version

- packages/common/src/index.ts
- packages/frontend/src/components/ProjectConnection/DbtForms/DbtNoneForm.tsx
- packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx
- packages/frontend/src/components/RefreshDbtButton/index.tsx
> feat: enable dbt connection CLI option

- packages/backend/src/queryBuilder.mock.ts
- packages/backend/src/queryCompiler.ts
- packages/common/src/compiler/exploreCompiler.mock.ts
- packages/common/src/compiler/exploreCompiler.test.ts
- packages/common/src/compiler/exploreCompiler.ts
- packages/common/src/compiler/translator.ts
- packages/common/src/types/warehouse.ts
- packages/warehouses/src/utils/sql.ts
- packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
- packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts
- packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
- packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
- packages/warehouses/src/warehouseClients/TrinoWarehouseClient.ts
Closes: #4233
Changes:
- move metric SQL logic to each warehouse client
- convert explore compiler functions into a class ( this is going to be hard to review since the entire file shows as changed, but the unit tests and mocks are pretty much unchanged )
> chore: explore compiler class

- packages/frontend/src/components/NavBar/ExploreMenu/index.tsx
- packages/frontend/src/components/common/modal/DashboardCreateModal.tsx
- packages/frontend/src/pages/SavedDashboards.tsx
Closes: #4316
[Screencast from 30-01-23 11:07:08.webm](https://user-images.githubusercontent.com/1983672/215447955-4a9a474b-d8db-4329-b75c-4ab5c124d39b.webm)
> fix: fix create dashboard from menu

- packages/frontend/src/index.tsx
- packages/frontend/tsconfig.json
Closes: 
Fixing type errors in preparation for https://github.com/lightdash/lightdash/issues/4215
> chore: vite types

- packages/frontend/package.json
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx
- packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
- packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx
- packages/frontend/src/components/SimpleStatistic/index.tsx
- packages/frontend/src/components/SimpleTable/DashboardCellContextMenu.tsx
- packages/frontend/src/components/TableConfigPanel/ConditionalFormatting.tsx
- packages/frontend/src/components/TableConfigPanel/ConditionalFormattingRule.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
- packages/frontend/src/components/common/Page/Page.styles.ts
- packages/frontend/src/components/common/Table/BodyCell.tsx
- packages/frontend/src/hooks/toaster/useToaster.tsx
- packages/frontend/src/hooks/useProjectCatalogTree.ts
- packages/frontend/src/pages/Dashboard.tsx
- packages/frontend/src/pages/SqlRunner.styles.ts
- packages/frontend/src/pages/SqlRunner.tsx
- packages/frontend/tsconfig.build.json
Closes: #4215 
Changes:
- import blueprint types properly
- add missing properties and values
- add specific tsconfig for building + run type check on frontend build
- force `any` type for ambiguous blueprint type ( [open issue](https://github.com/palantir/blueprint/issues/5889) )
> chore: frontend type validation

- docs/docs/references/metrics.mdx
- packages/common/src/compiler/filtersCompiler.ts
- packages/common/src/schemas/json/lightdash-dbt-2.0.json
- packages/common/src/types/field.ts
- packages/common/src/utils/filters.ts
- packages/common/src/utils/formatting.ts
- packages/common/src/utils/item.ts
- packages/e2e/cypress.config.ts
- packages/e2e/cypress/e2e/createProjects.cy.ts
- packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/FieldButtons.tsx
- packages/frontend/src/hooks/echarts/useEcharts.ts
- packages/frontend/src/utils/sortUtils.ts
- packages/warehouses/src/utils/sql.ts
- packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
- packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts
- packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
- packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
- packages/warehouses/src/warehouseClients/TrinoWarehouseClient.ts
Closes: #4250
https://deploy-preview-4333--peaceful-bassi-cbf284.netlify.app/references/metrics#median
> feat: median metric type

- packages/cli/src/handlers/deploy.ts
- packages/cli/src/handlers/preview.ts
Closes #4217
Loom is broken - sorry for the `.mov` files!
https://user-images.githubusercontent.com/11660098/216014491-2acab398-98b0-4c6a-9e1a-b492b9a7c710.mov
https://user-images.githubusercontent.com/11660098/216015549-2bbfd13a-cb96-4277-9c5d-c5cf30dad3ea.mov
> fix: catch errors in cli onboarding before create

- docs/docs/references/usage-analytics.mdx
- packages/backend/src/models/SearchModel/index.ts
- packages/backend/src/services/SearchService/SearchService.ts
- packages/common/src/types/search.ts
- packages/frontend/src/components/NavBar/GlobalSearch/hooks.ts
- packages/frontend/src/providers/TrackingProvider.tsx
Closes:  #4262
[Screencast from 01-02-23 08:57:12.webm](https://user-images.githubusercontent.com/1983672/215986027-2a8a203a-c243-43bd-9336-0cc8d3d5f394.webm)
> feat: User activity global search

- docs/docs/references/metrics.mdx
Closes: 
Wrap condition in quotes since some charts have special meaning in YML and throws error during compile
> docs: amend metric filter examples

- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
Closes: #4330
[Screencast from 01-02-23 12:26:28.webm](https://user-images.githubusercontent.com/1983672/216031370-0ea0ac90-24d4-4440-9187-18dae5480c30.webm)
> fix: date range bug

- packages/common/src/types/field.ts
- packages/common/src/utils/filters.ts
- packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilter.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterSettings.tsx
- packages/frontend/src/components/common/Filters/FilterRuleForm.tsx
- packages/frontend/src/components/common/Filters/configs.ts
- packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
Closes: https://github.com/lightdash/lightdash/issues/4315
fixes types around FilterableField and enables conditional formatting tooltips for table calculations
https://user-images.githubusercontent.com/962095/216095353-a0a9b29d-bb83-4aa1-9c3c-90318fd97643.mp4
> fix: conditional formatting tooltip for table calculations

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/ExploreFromHereButton/ExploreFromHere.styles.tsx
- packages/frontend/src/components/ExploreFromHereButton/index.tsx
- packages/frontend/src/components/MetricQueryData/UnderlyingDataModalContent.tsx
- packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectUsingCLI.tsx
- packages/frontend/src/components/common/LinkButton.tsx
- packages/frontend/src/components/common/LinkMenuItem.tsx
Closes: https://github.com/lightdash/lightdash/issues/4226
https://user-images.githubusercontent.com/962095/216352023-cfb8a73a-097c-410c-87f4-a5e05f3c4cb0.mp4
> fix: explore from here open in a new tab

- packages/e2e/cypress/e2e/createProjects.cy.ts
> chore: disable databricks e2e test

- packages/backend/src/queryBuilder.ts
- packages/common/src/compiler/exploreCompiler.ts
- packages/common/src/compiler/filtersCompiler.mock.ts
- packages/common/src/compiler/filtersCompiler.test.ts
- packages/common/src/compiler/filtersCompiler.ts
- packages/common/src/index.ts
- packages/common/src/utils/time.ts
Closes: #4337 
https://user-images.githubusercontent.com/9117144/216030516-b310b16a-0115-4654-98b2-bfa333491245.mp4
> fix: complete week filters with custom start of week

- packages/frontend/src/components/UserSettings/CreateTokenPanel/CreateTokens.styles.tsx
- packages/frontend/src/components/UserSettings/CreateTokenPanel/index.tsx
Closes: #4365
A better user experience for access token copy to cli command
> fix: access token copy to cli command

- docs/docs/references/metrics.mdx
> docs: update metrics reference with derived metrics

- packages/frontend/package.json
- packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
- packages/frontend/src/components/common/Table/ScrollableTable/index.tsx
- packages/frontend/src/components/common/Table/Table.styles.ts
- yarn.lock
Closes: 
Lib docs: https://react-virtual-v2.tanstack.com/docs/api
Note: The column's width changes since it is relative to the cell's content. There is a ticket to allow the manual resize of the columns that would force us to have fixed widths instead of relative ones and would also fix this issue.
Preview:
https://user-images.githubusercontent.com/9117144/217539451-8bce7387-ba0c-45bd-9c2c-da6e535234d3.mp4
> feat: virtualize table rows

- packages/frontend/src/components/common/Filters/FilterInputs/AutoComplete/AutoComplete.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/AutoComplete/MultiAutoComplete.tsx
> fix: sort autocomplete results case-insensitive

- packages/frontend/src/components/TableConfigPanel/GeneralSettings.tsx
Closes: #4403 
refactor: changed section title copy group - Pivot column
> fix: changed section title  copy group - Pivot column

- packages/backend/src/scheduler/SchedulerClient.ts
> fix: graphile migration

- packages/frontend/src/components/AutoFitText/index.tsx
- packages/frontend/src/components/SimpleStatistic/SimpleStatistics.styles.tsx
- packages/frontend/src/components/SimpleStatistic/index.tsx
> feat: AutoFitText component to handle big number responsiveness

- packages/backend/package.json
- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/scheduler/SchedulerClient.ts
- packages/backend/src/scheduler/SchedulerTask.ts
- packages/backend/src/scheduler/SchedulerWorker.ts
- packages/backend/src/services/DashboardService/DashboardService.ts
- packages/backend/src/services/SavedChartsService/SavedChartService.ts
- packages/backend/src/services/SchedulerService/SchedulerService.ts
- packages/common/src/types/scheduler.ts
- yarn.lock
Closes: #4114 
New events for the scheduler: 
- 'scheduler.created'
- 'scheduler.updated'
- 'scheduler.deleted'
**-- Edit: --**
The create and update events now have a `cron expression` and `cron string` properties/values that aren't in the screenshots bellow.
New events for the scheduler jobs:
- 'scheduler_job.created'
- 'scheduler_job.deleted'
- 'scheduler_job.started'
- 'scheduler_job.completed'
- 'scheduler_job.failed';
> chore: scheduler events

- packages/frontend/src/components/MetricQueryData/DrillDownMenuItem.tsx
- packages/frontend/src/components/MetricQueryData/DrillDownModal.tsx
Closes: #4438
[Screencast from 13-02-23 11:16:02.webm](https://user-images.githubusercontent.com/1983672/218431552-c8e24e80-f8e8-4e2f-8c86-c95426341287.webm)
> fix: grouped drill into

- packages/backend/src/index.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/backend/src/services/ProjectService/formatRows.js
- packages/backend/src/utils.ts
- packages/common/src/index.ts
Closes: #4390
Before the api was locked when doing `formatRows` now it is not locked because it runs on a different thread
> chore: format rows worker

- packages/frontend/src/components/ChartDownload.tsx
> feat: csv exports for table charts have full options (limit and format)

- packages/cli/src/dbt/context.ts
- packages/cli/src/handlers/compile.ts
- packages/cli/src/handlers/dbt/run.ts
- packages/cli/src/handlers/preview.ts
- packages/e2e/cypress/cli/cli.cy.ts
follow brand guidelines of dbt (just spotted this while updating some warning messages in the CLI)
> fix: lowercase dbt nouns

- packages/cli/src/handlers/compile.ts
- packages/cli/src/handlers/dbt/getDbtVersion.ts
Blocked by: #4467 
Closes: #4466
> fix: suppress 1.4.1 warnings

- docs/docs/references/syncing_your_dbt_changes.mdx
> docs: document supported dbt versions

- packages/frontend/src/components/Explorer/ExploreTree/TableTree/CollapsibleTableTree.tsx
- packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
- packages/frontend/src/components/PinnedItemsPanel/index.tsx
- packages/frontend/src/components/common/ResourceList/ResourceIcon.tsx
- packages/frontend/src/pages/SavedDashboards.tsx
- packages/frontend/src/pages/SavedQueries.tsx
- packages/frontend/src/pages/Spaces.tsx
> fix: updating icons in explore view

- packages/backend/src/queryBuilder.ts
- packages/backend/src/routers/projectRouter.ts
Closes: #4443
Before:
[Screencast from 14-02-23 09:54:57.webm](https://user-images.githubusercontent.com/1983672/218689413-e6255243-0af0-45bb-a802-3d83ef3df83a.webm)
Now:
[Screencast from 14-02-23 10:04:07.webm](https://user-images.githubusercontent.com/1983672/218689426-b96b0a5d-4814-4611-8b28-12de1a852c01.webm)
> feat: fix select sql metric

- packages/backend/src/config/parseConfig.ts
- packages/backend/src/models/ProjectModel/ProjectModel.mock.ts
- packages/backend/src/services/HealthService/HealthService.ts
- packages/common/src/index.ts
- packages/frontend/package.json
- packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
- packages/frontend/src/components/ReactHookForm/PasswordInput.tsx
- packages/frontend/src/components/UserSettings/CreateTokenPanel/index.tsx
- packages/frontend/src/components/UserSettings/UserManagementPanel/InviteSuccess.tsx
- packages/frontend/src/components/common/Table/index.tsx
- packages/frontend/src/hooks/thirdPartyServices/useFullstory.ts
- packages/frontend/src/pages/SqlRunner.tsx
- packages/frontend/src/providers/AppProvider.tsx
- yarn.lock
Adds the option to integrate with fullstory
> chore: add fullstory

- packages/frontend/src/components/Explorer/SpaceBrowser/AddResourceToSpaceMenu.styles.ts
- packages/frontend/src/components/Explorer/SpaceBrowser/AddResourceToSpaceMenu.tsx
- packages/frontend/src/components/SpacePanel/index.tsx
> feat: when user has no charts or dashboards add existing button is hidden

- packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.styles.tsx
- packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx
> fix: updating results table header icon

- packages/frontend/src/components/NavBar/BrowseMenu/index.tsx
- packages/frontend/src/components/NavBar/ExploreMenu/index.tsx
- packages/frontend/src/components/NavBar/HelpMenu/HelpMenu.styles.tsx
- packages/frontend/src/components/NavBar/HelpMenu/index.tsx
- packages/frontend/src/components/NavBar/SettingsMenu/index.tsx
Closes: #4508 
Replace all navbar icons with new tabler icons
https://user-images.githubusercontent.com/67699259/219679990-c72ce408-69ee-43d5-8ca9-a3e560d817e7.mov
https://user-images.githubusercontent.com/67699259/219680007-67c3dedd-ace8-4040-a240-bd005912e25e.mov
> feat: updating navbar icons

- packages/frontend/src/pages/UserActivity.tsx
> fix: user activity dashboard header styling

- packages/frontend/package.json
- packages/frontend/src/components/ReactHookForm/CronInput/CronInput.styles.ts
- packages/frontend/src/components/ReactHookForm/CronInput/CustomInputs.tsx
- packages/frontend/src/components/ReactHookForm/CronInput/DailyInputs.tsx
- packages/frontend/src/components/ReactHookForm/CronInput/FrequencySelect.tsx
- packages/frontend/src/components/ReactHookForm/CronInput/HourlyInputs.tsx
- packages/frontend/src/components/ReactHookForm/CronInput/MonthlyInputs.tsx
- packages/frontend/src/components/ReactHookForm/CronInput/WeekDaySelect.tsx
- packages/frontend/src/components/ReactHookForm/CronInput/WeeklyInputs.tsx
- packages/frontend/src/components/ReactHookForm/CronInput/cronInputUtils.ts
- packages/frontend/src/components/ReactHookForm/CronInput/index.tsx
- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulerForm.tsx
- packages/frontend/src/utils/fieldValidators.ts
Closes: #4113 
Note: we made small styling changes after recording this image/video
https://user-images.githubusercontent.com/9117144/219055436-fbba0a6c-dc77-4ae3-b317-ed93e0a1d890.mp4
> feat: scheduler frequency inputs

- packages/backend/package.json
- packages/backend/src/clients/Aws/s3.ts
- packages/backend/src/config/parseConfig.ts
- yarn.lock
Closes: #4522 
Debug log with signed url for the CSV:
> chore: update aws sdk packages

- packages/frontend/src/components/Home/RecentlyUpdatedPanel/index.tsx
- packages/frontend/src/components/common/ResourceView/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/4513
unblocks: https://github.com/lightdash/lightdash/issues/4186
adds tabs (without designs to ResourceView components)
https://user-images.githubusercontent.com/962095/220145701-c830c714-fcb8-42c6-9764-145c0c6ead9b.mp4
> feat: resource sorting tabs

- packages/frontend/src/components/PinnedItemsPanel/index.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/ResourceViewGridItem.styles.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/index.tsx
- packages/frontend/src/components/common/ResourceView/index.tsx
- packages/frontend/src/components/common/ResourceView/resourceUtils.ts
- packages/frontend/src/components/common/Table/ScrollableTable/TableHeader.tsx
- packages/frontend/src/components/common/Table/Table.styles.ts
Closes: https://github.com/lightdash/lightdash/issues/4491
⚠️ this feature will be enabled after https://github.com/lightdash/lightdash/issues/4442
> feat: resource groups

- packages/frontend/src/components/Home/RecentlyUpdatedPanel/index.tsx
- packages/frontend/src/components/common/ResourceView/ResourceView.styles.ts
- packages/frontend/src/components/common/ResourceView/index.tsx
Closes: #4186 
https://user-images.githubusercontent.com/67699259/220367600-e987d84c-aba9-4816-9315-5bcbc89ad12d.mov
> feat: most popular tab

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/services/SpaceService/SpaceService.ts
Closes: #4297 
New properties added:
```
isPrivate: boolean;
userAccessCount: number;
```
> chore: add space access to space events

- packages/backend/src/routers/projectRouter.ts
- packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
- packages/frontend/src/hooks/useDownloadCsv.tsx
- packages/frontend/src/pages/SqlRunner.tsx
Closes: #4435 
https://user-images.githubusercontent.com/67699259/220326694-374398d4-e5f8-4827-9fc8-de4d64d9230d.mov
> fix: exporting csv from SQL runner fails

- packages/frontend/src/components/ProjectConnection/index.tsx
> fix: typo test and compile button

- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/services/CsvService/CsvService.ts
- packages/frontend/src/components/ChartDownload.tsx
> fix: unify csv code 

- packages/frontend/package.json
- packages/frontend/src/components/common/Table/ScrollableTable/index.tsx
- packages/frontend/src/components/common/Table/Table.styles.ts
- packages/frontend/src/hooks/tableVisualization/getPivotDataAndColumns.ts
- yarn.lock
Closes: https://github.com/lightdash/lightdash/issues/4346
viz and results table:
pivots:
underlying data:
in dashboard tile:
with conditional formatting:
⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ 
@PriPatel stuff that I don't like now and maybe we can deal with later?:
1. frozen columns are divided by a shadow (does not feet our design needs). I think we need to elevate with using darker bg colour and add a bit lighter shadow
2. borders are missing from the top
3. borders are off with total.
for issues described above see this pictures below:
> style: update table component colours

- packages/frontend/src/components/NavBar/SettingsMenu/index.tsx
Closes: #4504 
https://user-images.githubusercontent.com/67699259/220601353-a7f749a5-faa7-4b8b-ad60-9a25abba9f88.mov
> feat: open settings page(s) in new tab

- packages/backend/src/clients/Aws/s3.ts
> fix: scheduler url expire time

- packages/frontend/src/components/DownloadCsvButton/index.tsx
- packages/frontend/src/components/ExportCSV/index.tsx
Closes: #4561
[Screencast from 23-02-23 15:17:48.webm](https://user-images.githubusercontent.com/1983672/220934250-62ef826e-bdf2-4d08-92f2-8415cf8d5f86.webm)
> fix: csv error handling

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/Explorer/ResultsCard/CellContextMenu.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/SeriesContextMenu.tsx
- packages/frontend/src/components/Explorer/index.tsx
- packages/frontend/src/components/MetricQueryData/DrillDownMenuItem.tsx
- packages/frontend/src/components/MetricQueryData/DrillDownModal.tsx
- packages/frontend/src/components/SimpleStatistic/BigNumberContextMenu.tsx
- packages/frontend/src/components/SimpleTable/CellContextMenu.tsx
- packages/frontend/src/components/SimpleTable/DashboardCellContextMenu.tsx
- packages/frontend/src/pages/Dashboard.tsx
- packages/frontend/src/providers/TrackingProvider.tsx
- packages/frontend/src/types/Events.ts
> feat: add a click event for `Drill by`

- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/services/CsvService/CsvService.ts
- packages/backend/src/services/CsvService/convertApiToCsv.js
- packages/backend/src/services/CsvService/convertSqlToCsv.js
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/backend/src/utils.ts
Closes: https://github.com/lightdash/lightdash-cloud/issues/32
With worker thread:
> fix: format csv on worker thread

- packages/backend/src/services/UnfurlService/UnfurlService.ts
Closes: #4572
Some quick improvements to headless browser method to make it more stable
> chore: make headless browser more stable (2)

- packages/backend/src/queryBuilder.mock.ts
- packages/backend/src/queryBuilder.test.ts
- packages/backend/src/queryBuilder.ts
> fix: empty where clause

- packages/backend/src/clients/Slack/SlackMessageBlocks.ts
> fix: empty description on slack unfurl

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/Explorer/ResultsCard/CellContextMenu.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/SeriesContextMenu.tsx
- packages/frontend/src/components/Explorer/index.tsx
- packages/frontend/src/components/MetricQueryData/DrillDownModal.tsx
- packages/frontend/src/components/MetricQueryData/UnderlyingDataModal.tsx
- packages/frontend/src/components/SimpleStatistic/BigNumberContextMenu.tsx
- packages/frontend/src/components/SimpleTable/CellContextMenu.tsx
- packages/frontend/src/components/SimpleTable/DashboardCellContextMenu.tsx
- packages/frontend/src/pages/Dashboard.tsx
- packages/frontend/src/providers/TrackingProvider.tsx
- packages/frontend/src/types/Events.ts
> feat: add a click event for `View underlying data`

- packages/cli/src/index.ts
> fix: start of week validation

- packages/backend/src/models/OrganizationModel.ts
- packages/backend/src/services/OrganizationService/OrganizationService.ts
- packages/common/src/authorization/organizationMemberAbility.test.ts
- packages/common/src/authorization/types.ts
- packages/common/src/index.ts
- packages/common/src/types/organization.ts
- packages/common/src/types/projects.ts
Type changes only
- type fix in OrganizationService using the wrong type
- move project / organization types to a separate type file
> chore: improve types for organization

- packages/backend/src/controllers/organizationController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/routers/organizationRouter.ts
- packages/backend/src/services/UserService.ts
- packages/common/src/types/organizationMemberProfile.ts
Close #4612 first
--- 
Updates routes for organization members to use tsoa
> feat: use tsoa for org member routes

- packages/backend/src/controllers/organizationController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/models/OrganizationModel.ts
- packages/backend/src/routers/organizationRouter.ts
- packages/backend/src/services/OrganizationService/OrganizationService.ts
- packages/backend/src/services/UserService.ts
- packages/common/src/authorization/organizationMemberAbility.test.ts
- packages/common/src/authorization/types.ts
- packages/common/src/index.ts
- packages/common/src/types/api/success.ts
- packages/common/src/types/organization.ts
- packages/common/src/types/organizationMemberProfile.ts
- packages/common/src/types/projects.ts
- packages/frontend/src/components/ProjectConnection/index.tsx
Merge #4611 first
---
Covers basic CRUD routes for orgs
> feat: use tsoa for org routes

- packages/backend/src/controllers/organizationController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/routers/organizationRouter.ts
- packages/backend/src/services/UserService.ts
- packages/common/src/index.ts
- packages/common/src/types/api/success.ts
- packages/common/src/types/organizationMemberProfile.ts
- packages/frontend/src/components/ProjectConnection/index.tsx
Merge #4607 first
---
Adds missing param on project creation via the UI
> chore: add tsoa to org endpoints

- packages/frontend/src/components/ReactHookForm/CronInput/CronInput.styles.ts
- packages/frontend/src/components/ReactHookForm/CronInput/index.tsx
- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulerForm.tsx
- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulerModalBase.styles.ts
- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulerModalContent.tsx
- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulersList.tsx
- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/index.tsx
Closes: #4581 
before
after
https://user-images.githubusercontent.com/67699259/221644198-578104ba-6201-4da5-bf79-cb2437949b31.mov
> fix: styling changes to scheduled deliveries

- packages/frontend/src/components/NavBar/GlobalSearch/SearchIcon.tsx
- packages/frontend/src/components/NavBar/GlobalSearch/hooks.ts
- packages/frontend/src/components/NavBar/GlobalSearch/index.tsx
- packages/frontend/src/components/common/Filters/FieldIcon.tsx
Closes: #4622 
https://user-images.githubusercontent.com/67699259/221905848-92f54b83-79b8-4f86-bc55-c3293c16567f.mov
> fix: updating global search icons

- packages/frontend/src/components/Home/RecentlyUpdatedPanel/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/4615
> feat: swap tabs

- packages/backend/src/services/CsvService/CsvService.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
> fix: all results in scheduled delivery CSV

- packages/backend/src/scheduler/SchedulerClient.ts
- packages/backend/src/scheduler/SchedulerWorker.ts
Closes: #4584 
Use connection uri if available.
> fix: scheduler database connection override

- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/services/CsvService/CsvService.ts
- packages/backend/src/services/CsvService/convertApiToCsv.js
- packages/backend/src/services/CsvService/convertSqlToCsv.js
- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/ChartDownload.tsx
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/Explorer/ResultsCard/ResultsCard.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
- packages/frontend/src/components/MetricQueryData/UnderlyingDataModalContent.tsx
- packages/frontend/src/hooks/useDownloadCsv.tsx
- packages/frontend/src/pages/SqlRunner.tsx
Closes: #4629 
Fix CSV headers in:
- chart section
- dashboard tile
- scheduled deliveries
> fix: custom labels in CSV export

- packages/frontend/package.json
- packages/frontend/src/App.tsx
- packages/frontend/src/components/CreateUserForm/CreateUserForm.styles.ts
- packages/frontend/src/components/CreateUserForm/VerifyEmailForm.tsx
- packages/frontend/src/pages/EmailVerification.tsx
- packages/frontend/src/pages/SignUp.styles.tsx
> feat: page for entering otp

- packages/backend/src/scheduler/SchedulerTask.ts
- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulerForm.tsx
Closes: 
Fix issue where the limit was being set the string "custom" instead of the number.
Also fix issue where we don't cascade the error so the job can retry.
> fix: scheduler custom limit

- packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
- packages/frontend/src/components/common/Table/Table.styles.ts
fixes table interactivity in #4652 
https://user-images.githubusercontent.com/13311268/222597942-1b5d156b-c20f-4c67-8a55-f92900eaa182.mov
> fix: make placeholder table row non interactive

- packages/frontend/src/components/UserSettings/AppearancePanel/index.tsx
- packages/frontend/src/hooks/organisation/useOrganisationUpdateMutation.ts
Closes: #4673 
Frontend was passing too much data to the backend and thus getting a validation error
https://user-images.githubusercontent.com/13311268/222781654-a1feff40-2518-49e6-8f79-21ccda3f16e8.mov
> fix: error when updating color palette

- packages/frontend/src/App.tsx
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/DashboardTiles/TileBase/TileBase.styles.tsx
- packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
- packages/frontend/src/hooks/dashboard/useSavedQueryWithDashboardFilters.ts
- packages/frontend/src/pages/MinimalDashboard.tsx
- packages/frontend/src/pages/MinimalSavedExplorer.tsx
Closes: https://github.com/lightdash/lightdash/issues/4599
> feat: minimal dashboard page

- packages/backend/src/clients/Slack/Slackbot.ts
- packages/backend/src/scheduler/SchedulerTask.ts
- packages/backend/src/services/UnfurlService/UnfurlService.ts
Closes: #4675
Depends on  #4674
Big number 
Chart
Table
Explore (unchanged, has no minimal pages, it works as before) 
Dashboard
> feat: take screenshots from minimal pages

- packages/backend/src/clients/EmailClient/templates/invitation.html
> chore: fix template format

- packages/backend/src/clients/EmailClient/templates/projectAccess.html
> feat: updating project access email layout

- packages/backend/src/clients/EmailClient/templates/recoverPassword.html
> feat: updating password recovery email layout

- packages/frontend/src/components/common/Table/Table.styles.ts
Closes: #4320 
https://user-images.githubusercontent.com/962095/223071540-017bdae8-4047-45a3-824c-4da21eee8cf6.mp4
> fix: conditional formatting interactions

- render.yaml
Closes: #4702 
- Set static env vars in Render instead of in the yml. 
- The current yml is creating a new env var group per each PR instead of reusing the same env var group across all PRs.
> chore: update render env group

- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
Closes: #4641 
Before:
https://user-images.githubusercontent.com/9117144/223400601-a671fec7-c596-4a42-9bd8-66aad1154312.mp4
After:
https://user-images.githubusercontent.com/9117144/223400583-acb6b386-42bd-4c76-931e-06ee98148285.mp4
> fix: in between timezone

- packages/backend/package.json
- packages/backend/src/database/migrations/20230308100040_remove_org_allowed_email_domains.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/models/OrganizationModel.ts
- packages/backend/src/services/OrganizationService/OrganizationService.mock.ts
- packages/backend/src/services/UserService.ts
- packages/common/src/types/organization.ts
- packages/frontend/src/components/UserSettings/OrganisationPanel/index.tsx
Closes: #4713 
Removing existing feature in preparation for the new feature around allowed domains https://github.com/lightdash/lightdash/milestone/61
> feat: remove organisation allowed email domains

- packages/e2e/cypress/e2e/settings/invites.cy.ts
- packages/e2e/cypress/support/commands.ts
> chore: update all user emails in e2e tests

- docs/docs/references/roles.md
- packages/common/src/authorization/organizationMemberAbility.test.ts
- packages/common/src/authorization/organizationMemberAbility.ts
Closes: #4714 
Admin vs Editor - User management page
Editor - Project page
> feat: only org admins can invite users

- packages/backend/src/models/UserModel.ts
- packages/backend/src/routers/apiV1Router.ts
- packages/backend/src/services/AnalyticsService/AnalyticsService.ts
- packages/backend/src/services/DashboardService/DashboardService.mock.ts
- packages/backend/src/services/DashboardService/DashboardService.ts
- packages/backend/src/services/OrganizationService/OrganizationService.ts
- packages/backend/src/services/ProjectService/ProjectService.mock.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/backend/src/services/SavedChartsService/SavedChartService.ts
- packages/backend/src/services/SchedulerService/SchedulerService.ts
- packages/backend/src/services/ShareService/ShareService.ts
- packages/backend/src/services/UserService.ts
- packages/common/src/authorization/index.mock.ts
- packages/common/src/authorization/index.test.ts
- packages/common/src/authorization/index.ts
- packages/common/src/authorization/organizationMemberAbility.ts
- packages/common/src/types/user.ts
- packages/frontend/src/components/Intercom.tsx
Closes: #4506 
Work in preparation for https://github.com/lightdash/lightdash/issues/3646
Added the service and model methods but they are not being used at the moment.(only used for testing)
> feat: allow create users without org

- packages/backend/src/routers/slackRouter.ts
> fix: fix slack image crashing

- .github/workflows/test-easy-install.yml
- docker-compose.yml
- scripts/install.sh
Closes: 
https://github.com/lightdash/lightdash/actions/runs/4372642251/jobs/7649813179
> test: test easy install script periodically

- packages/frontend/src/components/common/ResourceView/ResourceEmptyState.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/ResourceViewGridSpaceItem.tsx
> feat: minor home page improvements

- packages/frontend/src/components/DashboardTiles/EmptyStateNoTiles/index.tsx
- packages/frontend/src/pages/Dashboard.tsx
Closes: #4423
disallow adding a tile in view mode
> fix: disallow adding a tile in view mode

- .github/workflows/cli-test.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/timezone-tests.yml
> chore: don't skip external pr tests

- packages/common/src/index.ts
- packages/frontend/src/components/UserSettings/AllowedDomainsPanel/index.tsx
- packages/frontend/src/hooks/organisation/useAllowedDomains.ts
- packages/frontend/src/pages/Settings.styles.tsx
- packages/frontend/src/pages/Settings.tsx
Closes: #4716 
https://www.loom.com/share/71562da3426d4b16bb8545a0403065ed
https://user-images.githubusercontent.com/9117144/224478134-bdfe5305-0abe-47ca-9f5d-75315e94a4e2.mp4
> feat: organisation settings allowed email domains panel

- packages/frontend/src/components/ExportCSV/index.tsx
- packages/frontend/src/hooks/toaster/useToaster.tsx
Closes: #4631 
https://user-images.githubusercontent.com/13311268/222930748-03209a42-c083-40a1-acdb-10382a4e583c.mov
> fix: maintain loading state on table export

- examples/api/org-allowed-email-domains.http
- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/controllers/organizationController.ts
- packages/backend/src/controllers/userController.ts
- packages/backend/src/database/entities/organizations.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/models/OrganizationModel.ts
- packages/backend/src/models/UserModel.ts
- packages/backend/src/routers/apiV1Router.ts
- packages/backend/src/services/OrganizationService/OrganizationService.ts
- packages/backend/src/services/UserService.ts
- packages/backend/src/services/services.ts
- packages/common/src/index.ts
- packages/common/src/types/organization.ts
- packages/common/src/types/user.ts
- packages/frontend/src/App.tsx
- packages/frontend/src/components/PrivateRoute.tsx
- packages/frontend/src/hooks/organisation/useOrganisationCreateMutation.ts
- packages/frontend/src/hooks/user/useAllowedOrganizations.ts
- packages/frontend/src/hooks/user/useJoinOrganizationMutation.ts
- packages/frontend/src/pages/JoinOrganization.tsx
- packages/frontend/src/types/Events.ts
Closes: #3646 
Note that email verification for email+password is not enabled in PR envs so it's **not possible to test this in the PR env**.
Preview: 
https://www.loom.com/share/1d7de651d0ae47da85756809a3d3fc45
https://user-images.githubusercontent.com/9117144/224475586-3b58b0b9-84db-401f-a0b3-4d146e91e023.mp4
https://www.loom.com/share/33846e40cf80486eb2e263a2206d7029
https://user-images.githubusercontent.com/9117144/224475595-6453a9fe-cdcc-4d3e-9e45-5aeb1e92d542.mp4
https://www.loom.com/share/8465892f1f3b446f923e95056e629197
https://user-images.githubusercontent.com/9117144/224475599-11414101-5067-4deb-824c-39840c836968.mp4
https://www.loom.com/share/600daecc5e02479c9ad63e42e72f5337
https://user-images.githubusercontent.com/9117144/224475602-4f5b0879-3abc-450c-95b9-34886e6fa794.mp4
> feat: users join existing org

- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/services/CsvService/CsvService.ts
- packages/backend/src/services/CsvService/convertApiToCsv.js
- packages/frontend/src/components/ChartDownload.tsx
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/Explorer/ResultsCard/ResultsCard.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
- packages/frontend/src/components/MetricQueryData/UnderlyingDataModalContent.tsx
- packages/frontend/src/hooks/useDownloadCsv.tsx
Closes: #4750
- Download CSV from results on explore
- Download CSV from table chart on explore
- Download CSV from table chart on dashboard
- Download CSV from table chart on SQL runner
> fix: keep order on csv column export

- packages/backend/src/scheduler/SchedulerTask.ts
> fix: slack notification image prefix

- packages/backend/src/config/parseConfig.ts
- packages/backend/src/models/ProjectModel/ProjectModel.mock.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
Closes: 
Cloud PR https://github.com/lightdash/lightdash-cloud/pull/36
> feat: add new env cells limit

- packages/frontend/src/components/ExportCSV/index.tsx
> fix: csv export modal styles

- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulerForm.tsx
- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulerModalError.tsx
- packages/frontend/src/pages/Settings.tsx
> feat: update settings sidebar

- packages/backend/src/routers/projectRouter.ts
> fix: fix backend empty columnorder request

- packages/backend/src/clients/EmailClient/EmailClient.ts
- packages/backend/src/clients/EmailClient/templates/chartCsvNotification.html
- packages/backend/src/clients/EmailClient/templates/dashboardCsvNotification.html
- packages/backend/src/clients/EmailClient/templates/imageNotification.html
- packages/backend/src/scheduler/SchedulerTask.ts
https://user-images.githubusercontent.com/67699259/224796596-25269220-8baf-4e0e-9634-4d5304315a1d.mov
https://user-images.githubusercontent.com/67699259/224796600-7634141c-f27c-4269-b6e3-0a8317249ff4.mov
> feat: add scheduled deliveries link to emails

- packages/frontend/src/components/Home/LandingPanel/LandingPanel.styles.tsx
- packages/frontend/src/components/SpacePanel/index.tsx
- packages/frontend/src/components/common/Page/Page.styles.ts
- packages/frontend/src/components/common/ResourceView/ResourceIcon.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/ResourceViewGridChartItem.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/ResourceViewGridDashboardItem.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/ResourceViewGridSpaceItem.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewList/index.tsx
- packages/frontend/src/components/common/ResourceView/index.tsx
> style: homepage improvements

- packages/backend/src/services/DashboardService/DashboardService.ts
should capture exception that right now is happening with one of our customer.
> fix: capture space permission exception

- packages/backend/src/index.ts
Closes: #4790 
Previously would crash now we see this error message:
> fix: catch errors in passport deserialize

- packages/backend/src/controllers/organizationController.ts
> fix: remove promisify on delete org

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/models/EmailModel.ts
- packages/backend/src/services/UserService.ts
> chore: add verify event

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/services/OrganizationService/OrganizationService.ts
> chore: add org allowed email domains event

- docs/docs/references/joins.md
Just a small correction that seems to be a typo. I stumbled on it, while reading the docs
> docs: correct possible typo

- packages/backend/package.json
- packages/backend/src/services/UserService.ts
- packages/common/src/index.ts
- packages/e2e/cypress/e2e/settings/invites.cy.ts
- packages/e2e/cypress/support/commands.ts
- packages/frontend/src/components/PrivateRoute.tsx
- packages/frontend/src/pages/JoinOrganization.tsx
Closes: #4783 
changes:
- add development mode 
- set verification code to 000000 when in development mode or PR mode
- remove logic from FE
- update tests to verify email
> chore: set hardcoded verification code for development environments

- packages/backend/src/clients/Aws/s3.ts
- packages/backend/src/routers/dashboardRouter.ts
- packages/backend/src/services/UnfurlService/UnfurlService.ts
- packages/common/src/index.ts
- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
- packages/frontend/src/hooks/dashboard/useDashboard.tsx
- packages/frontend/src/pages/Dashboard.tsx
Closes: #2895 
https://user-images.githubusercontent.com/67699259/225087734-2cb3e0f5-3335-40d5-b7d1-e10ed4a2dd50.mov
> feat: dashboards can be exported

- packages/backend/src/database/entities/spaces.ts
- packages/backend/src/database/seeds/development/01_initial_user.ts
- packages/backend/src/database/seeds/development/02_saved_queries.ts
- packages/backend/src/database/seeds/development/03_saved_dashboards.ts
- packages/backend/src/models/SavedChartModel.ts
- packages/backend/src/services/DashboardService/DashboardService.test.ts
- packages/backend/src/services/DashboardService/DashboardService.ts
- packages/backend/src/services/SavedChartsService/SavedChartService.ts
- packages/frontend/src/components/SpacePanel/index.tsx
- packages/frontend/src/components/common/modal/DashboardCreateModal.tsx
closes: https://github.com/lightdash/lightdash/issues/4809
please read the issue for more context.
basically when we are creating dashboard it was defaulting first available space within the project.
if user A changes first space permission to private
and user B has no access to that space
when user B starts to create a dashboard it will try to default to that first space that userB has no permission to 💥 
this one also fixes UI bug where we were not assigning spaceUuid when we were creating a dashboard from space page
> fix: space permission on dashboard create

- packages/backend/src/services/OrganizationService/OrganizationService.ts
Closes: #4824
Before:
[Screencast from 16-03-23 16:06:06.webm](https://user-images.githubusercontent.com/1983672/225660173-83a4988d-e541-445e-af1c-484d2bac660a.webm)
After:
[Screencast from 16-03-23 16:06:48.webm](https://user-images.githubusercontent.com/1983672/225660192-ba890fea-883e-49a1-b13d-1a98875c3acb.webm)
> fix: create and join on multiorg

- docs/docs/get-started/exploring-data/sharing-insights.mdx
- docs/docs/guides/enable-cloud-storage.mdx
- docs/docs/guides/enable-slack-selfhost.mdx
- docs/docs/guides/how-to-create-scheduled-deliveries.mdx
- docs/docs/guides/spaces.mdx
- docs/docs/intro.md
Closes: #4694
Closes: #4693
https://deploy-preview-4841--peaceful-bassi-cbf284.netlify.app/guides/enable-cloud-storage
> docs: s3 docs

- packages/frontend/src/pages/SavedDashboards.tsx
- packages/frontend/src/pages/SavedQueries.tsx
- packages/frontend/src/pages/Spaces.tsx
> feat: updating all content pages breadcrumbs

- packages/backend/src/database/entities/spaces.ts
- packages/backend/src/models/DashboardModel/DashboardModel.mock.ts
- packages/backend/src/models/DashboardModel/DashboardModel.test.ts
- packages/backend/src/models/DashboardModel/DashboardModel.ts
- packages/backend/src/models/SavedChartModel.ts
- packages/backend/src/models/SpaceModel.ts
- packages/backend/src/services/DashboardService/DashboardService.mock.ts
- packages/backend/src/services/ProjectService/ProjectService.mock.ts
- packages/common/src/openapibundle.json
- packages/common/src/types/dashboard.ts
- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
- packages/frontend/src/components/common/PageHeader/ViewInfo.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/ResourceViewGridChartItem.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/ResourceViewGridDashboardItem.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewList/index.tsx
- packages/frontend/src/components/common/ResourceView/resourceUtils.ts
- packages/frontend/src/pages/Dashboard.tsx
Closes: #4386 
adds view "since when" tooltips to:
- resource list view
- resource grid view
- chart/dashboard headers
screenshots:
> feat: views but since when

- packages/frontend/src/components/common/ResourceView/index.tsx
Closes: #4832 
Added width to the resource view header group so the actions can auto align to the right.
> fix: resource view header actions position

- packages/backend/src/clients/Aws/s3.ts
> fix: s3 permissions and mimetypes

- packages/frontend/src/components/common/MantineIcon/index.tsx
Closes: [#4815](https://github.com/lightdash/lightdash/issues/4815)
> style: mantine icon

- packages/frontend/src/components/SimpleStatistic/index.tsx
related to: #4872 
set initial container width if Resizer does not fire.
> fix: setting initial element size width

- packages/frontend/src/providers/MantineProvider.tsx
part of: [Check how custom mantine spacing and font size works #4785](https://github.com/lightdash/lightdash/issues/4785)
> style: mantine spacing

- packages/backend/src/routers/projectRouter.ts
- packages/frontend/src/hooks/useQueryResults.tsx
> feat: run dashboard tile query

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/DashboardTiles/TileBase/TileBase.styles.tsx
- packages/frontend/src/components/LightdashVisualization/index.tsx
- packages/frontend/src/components/SimpleStatistic/SimpleStatistics.styles.tsx
- packages/frontend/src/components/SimpleStatistic/index.tsx
Closes: #4779 
https://user-images.githubusercontent.com/962095/227583556-fa6b6596-08d5-4214-a986-a6a2cbc274df.mp4
> style: bignumber spaces

- packages/frontend/src/components/Home/OnboardingPanel/index.tsx
- packages/frontend/src/pages/Invite.tsx
- packages/frontend/src/pages/Login.tsx
- packages/frontend/src/pages/Register.tsx
- packages/frontend/src/providers/MantineProvider.tsx
Closes: https://github.com/lightdash/lightdash/issues/4785
> style: mantine spacing extras

- packages/frontend/src/providers/ExplorerProvider.tsx
Closes: #4911
Automatically run query on table calculation create and update
[Screencast from 27-03-23 12:03:03.webm](https://user-images.githubusercontent.com/1983672/227910817-e084ba1b-035c-4d83-a09b-dac57a267093.webm)
> feat: run query on table calculation changes

- packages/backend/src/database/migrations/20230322102401_add_interactive_viewer_role.ts
- packages/backend/src/database/migrations/20230328152604_update_interactive_viewers.ts
> fix: interactive viewer migration

- docs/docs/references/roles.mdx
- packages/backend/src/clients/EmailClient/EmailClient.ts
- packages/backend/src/controllers/authenticationRoles.ts
- packages/backend/src/database/migrations/20230327070336_add_developer_role.ts
- packages/backend/src/database/migrations/20230328160259_update_developer.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/models/AnalyticsModel.ts
- packages/common/src/authorization/organizationMemberAbility.mock.ts
- packages/common/src/authorization/organizationMemberAbility.test.ts
- packages/common/src/authorization/organizationMemberAbility.ts
- packages/common/src/authorization/projectMemberAbility.mock.ts
- packages/common/src/authorization/projectMemberAbility.test.ts
- packages/common/src/authorization/projectMemberAbility.ts
- packages/common/src/types/organizationMemberProfile.ts
- packages/common/src/types/projectMemberProfile.ts
- packages/e2e/cypress/e2e/api/projectPermissions.cy.ts
- packages/frontend/src/components/ProjectAccess/ProjectAccess.tsx
- packages/frontend/src/pages/SqlRunner.tsx
Closes: #3111
Editor: 
Developer:
> feat: developer role

- packages/e2e/cypress/e2e/createProjects.cy.ts
- packages/frontend/src/components/PinnedItemsPanel/index.tsx
- packages/frontend/src/pages/Home.tsx
Closes: #4077 
https://user-images.githubusercontent.com/67699259/228231786-1bffb232-c59c-4f05-861c-cbe640520193.mov
> feat: space panel removed and pinned items empty state added

- docs/docs/guides/enable-cloud-storage.mdx
- packages/backend/src/clients/Aws/s3.ts
- packages/backend/src/config/parseConfig.ts
Break out expiration time to an environment variable
> feat: break out s3 image expiration time to env variable

- docs/docs/references/tables.md
> docs: fix order by docs

- packages/backend/package.json
- packages/backend/src/clients/Slack/SlackClient.ts
- yarn.lock
Closes: #4880
Testing with 100 users at a time
> feat: slack pagination

- packages/frontend/src/components/RegisterForms/VerifyEmailForm.tsx
- packages/frontend/src/pages/JoinOrganization.tsx
> feat: updating Join Workspace screen

- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/routers/slackRouter.ts
> feat: link docs when files are missing 

- packages/frontend/src/components/SimpleTable/DashboardCellContextMenu.tsx
Closes: #4976
Fixed this particular issue, but note this option is only available if `filters.length > 0` for some reason...
> fix: revert dashboard filter permission

- packages/backend/src/services/CsvService/CsvService.ts
> fix: s3 file stream

- packages/frontend/src/components/ExportCSV/index.tsx
> fix: fix downloading csv twice

- packages/backend/src/services/CsvService/CsvService.ts
> fix: fix s3 upload on scheduler too

- packages/e2e/cypress/e2e/savedDashboards.cy.ts
- packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx
> fix: delete action copy updated

- packages/frontend/src/components/SimpleTable/index.tsx
- packages/frontend/src/components/common/PivotTable/index.tsx
- packages/frontend/src/components/common/PivotTable/tableStyles.tsx
Closes: https://github.com/lightdash/lightdash/issues/5001
https://user-images.githubusercontent.com/962095/229561889-4ea06b5c-3da8-434f-8ee5-317b104d09eb.mp4
> feat: pivot table row numbers

- packages/common/src/types/pivot.ts
- packages/frontend/src/hooks/pivotTable/pivotQueryResults.ts
- packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
> fix: custom order of pivot metrics + index

- packages/backend/src/services/SchedulerService/SchedulerService.ts
- packages/common/src/authorization/organizationMemberAbility.ts
- packages/common/src/authorization/types.ts
> fix: grant permissions to csv result to members

- packages/frontend/src/components/ChartDownload.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
- packages/frontend/src/pages/SqlRunner.tsx
Fixes error where button to export csv was not showing in the explorer for users with project-specific permissions.
> fix: check project abilities for export csv

- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
Closes: #4825 
https://user-images.githubusercontent.com/67699259/228542530-908224e6-7124-42f4-9e78-5ed51f66d9c5.mov
> fix: timestamp selection for is between filter

- packages/backend/package.json
- packages/backend/src/clients/Aws/s3.ts
- yarn.lock
> fix: use s3 managed uploads

- packages/backend/src/services/CsvService/CsvService.ts
> fix: use pipe for csv transform

- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/ResourceViewGridSpaceItem.tsx
Closes: #5006 
https://user-images.githubusercontent.com/67699259/229799917-1860b16a-f7d8-4a43-8b8f-45085e2a1108.mov
> fix: space action menu shouldnt shrink the title

- packages/frontend/src/components/SimpleTable/index.tsx
- packages/frontend/src/components/TableConfigPanel/ColumnConfiguration.tsx
- packages/frontend/src/components/common/PivotTable/HeaderCell.tsx
- packages/frontend/src/components/common/PivotTable/TitleCell.tsx
- packages/frontend/src/components/common/PivotTable/index.tsx
- packages/frontend/src/hooks/tableVisualization/getDataAndColumns.tsx
- packages/frontend/src/hooks/tableVisualization/getPivotDataAndColumns.ts
- packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
> feat: new pivot table - rename columns

- packages/common/src/types/job.ts
- packages/frontend/src/components/JobDetailsDrawer/index.tsx
> fix: use log_version 2 for dbt json logs

- packages/cli/src/handlers/compile.ts
- packages/cli/src/handlers/dbt/getDbtVersion.ts
> fix: check stdout on getDbtVersion

- packages/warehouses/package.json
- yarn.lock
Security patches + removes AWS-SDK error when using the CLI
> chore: snowflake-sdk 1.6.20

- .gitignore
- packages/backend/src/clients/Aws/s3.ts
- packages/backend/src/routers/projectRouter.ts
- packages/e2e/cypress/e2e/downloadCsv.cy.ts
- packages/frontend/src/components/DownloadCsvButton/index.tsx
- packages/frontend/src/components/DownloadSqlCsvButton/index.tsx
- packages/frontend/src/components/ExportCSV/index.tsx
> fix: contentDisposition headers for csv downloads

- packages/backend/src/clients/EmailClient/EmailClient.ts
Closes: #4799
I was only able to replicate on gmail, it was ok on postmark 
Before:
Now:
> fix: scheduled delivery dashboard csv template

- packages/backend/src/clients/Slack/Slackbot.ts
- packages/backend/src/services/UnfurlService/UnfurlService.ts
- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
Closes: #4994
This will copy the location href of the dashboard (with filters) into the clipboard
Unfurling will be fixed here https://github.com/lightdash/lightdash/issues/5064
> feat: copy full url on dashboard

- packages/backend/src/services/CsvService/CsvService.ts
Closes:  #5059
I added an (empty) flag to the empty csv and no link, instead of removing the file from the list...
> fix: no results dashboard csv

- packages/frontend/src/components/PinnedItemsPanel/index.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewGrid/index.tsx
- packages/frontend/src/components/common/ResourceView/index.tsx
Closes:
Ready
```
- Drag and drop boilerplate
- Making the drag and drop optional and disabled by default
```
To do
```
- Link to the BE with a hook
```
> feat: Reorder pinned items (FE POC)

- packages/common/src/types/pivot.ts
- packages/frontend/src/components/common/PivotTable/HeaderCell.tsx
- packages/frontend/src/components/common/PivotTable/IndexCell.tsx
- packages/frontend/src/components/common/PivotTable/TitleCell.tsx
- packages/frontend/src/components/common/PivotTable/ValueCell.tsx
- packages/frontend/src/components/common/PivotTable/ValueCellMenu.tsx
- packages/frontend/src/components/common/PivotTable/index.tsx
- packages/frontend/src/components/common/PivotTable/tableStyles.tsx
- packages/frontend/src/hooks/pivotTable/pivotQueryResults.test.ts
- packages/frontend/src/hooks/pivotTable/pivotQueryResults.ts
- packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
> feat: pivot table interactivity tooltips

- packages/frontend/src/components/ProjectConnection/index.tsx
> fix: update dbt version in project form

- packages/common/src/utils/item.ts
- packages/e2e/cypress/e2e/dashboard.cy.ts
- packages/frontend/src/components/DashboardFilter/FilterSearch/index.tsx
- packages/frontend/src/components/common/Filters/FieldAutoComplete.tsx
- packages/frontend/src/components/common/Filters/FieldIcon.tsx
- packages/frontend/src/components/common/Filters/renderFilterItem.tsx
- packages/frontend/src/components/common/Filters/renderFilterList.tsx
Closes: #4375 
Changes
```
- Added hasGrouping prop to FieldAutoComplete component
- hasGrouping activates renderListItem prop to group
- hasGrouping renders items without table names (dimension only)
```
Need help @IrakliJani 
```
- Making titles sticky? tried sticky css didn't stick 😓 
```
https://user-images.githubusercontent.com/67699259/231510420-1ecc3df1-77dc-4388-948f-37d4973c4e5f.mov
> fix: added grouping to dashboard dimensions dropdown

- packages/frontend/src/components/common/Filters/renderFilterList.tsx
adds stickiness to group headers inside dashboard filter dropdown:
https://user-images.githubusercontent.com/962095/231859679-c340f7e5-dd6b-48e6-9800-1198628f51eb.mp4
> feat: add dashboard filter dropdown group header stickiness

- packages/backend/src/models/UserModel.ts
Closes: 
A customer had a conflict on login , perhaps he's accepting an invitation twice, or a race condition (I don't know how to replicate) but this upsert should fix any related issue
> fix: already has password

- packages/backend/src/services/UnfurlService/UnfurlService.ts
- packages/common/src/types/filter.ts
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/hooks/dashboard/useDashboardFiltersForExplore.ts
- packages/frontend/src/pages/MinimalDashboard.tsx
- packages/frontend/src/providers/DashboardProvider.tsx
Closes: #5064
WIth filters minimal page 
Without filters unfurl
With filters unfurl
> fix: minimal dashboard filters

- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/routers/slackRouter.ts
> fix: add extra security to file endpoints

- packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
Closes: #4219 
https://user-images.githubusercontent.com/67699259/232092724-a070893c-83bb-4a0e-90ba-ddb4eee40a4d.mov
> fix: filter tag input does not allow duplicate values

- docs/docs/references/roles.mdx
> docs: update roles and permissions docs with scheduled deliveries

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
Closes:  https://github.com/lightdash/lightdash/issues/4488
- Add warehouse type to project error event
> chore: add warehouse type to project error event

- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
- packages/frontend/src/components/common/modal/ChartUpdateModal.tsx
- packages/frontend/src/hooks/useSavedQuery.ts
Closes: #4056 
before
https://user-images.githubusercontent.com/67699259/232087477-681db02a-0c65-464a-a231-74c5cb183d36.mov
after
https://user-images.githubusercontent.com/67699259/232087500-a3be4ea2-3cf9-4814-a375-11b9d98d08fb.mov
> fix: adding open dashboard button to update chart success toast

- packages/common/src/types/pivot.ts
- packages/frontend/src/components/SimpleTable/index.tsx
- packages/frontend/src/components/TableConfigPanel/ColumnConfiguration.styles.ts
- packages/frontend/src/components/TableConfigPanel/ColumnConfiguration.tsx
- packages/frontend/src/components/common/PivotTable/index.tsx
- packages/frontend/src/hooks/pivotTable/pivotQueryResults.ts
- packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
Closes: #5031 
error boundary if you are hiding all metrics (0 rows = no data)
> feat: pivot table hide columns

- packages/backend/src/scheduler/SchedulerTask.ts
> fix: csv error slack

- packages/frontend/src/hooks/useCompiledSql.tsx
- packages/frontend/src/hooks/useDownloadCsv.tsx
- packages/frontend/src/hooks/useQueryResults.tsx
- packages/frontend/src/utils/dateFilter.ts
Closes: https://github.com/lightdash/lightdash/issues/5111
> fix: date dashboard filter

- packages/backend/src/controllers/pinnedItemsController.ts
- packages/backend/src/controllers/pinningController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/services/PinningService/PinningService.ts
- packages/backend/src/services/services.ts
- packages/common/src/types/pinning.ts
Closes: 
Req
```
pinnedListUuid
```
Res
```
{
dashboards: [
{
data: {},
order: 0
},
...
],
charts: [
{
data: {},
order: 0
},
...
],
spaces: [
{
data: {},
order: 0
},
...
],
}
```
> feat: pinned items API

- packages/frontend/src/components/common/SpaceActionModal/index.tsx
- packages/frontend/src/components/common/modal/ChartDeleteModal.tsx
- packages/frontend/src/components/common/modal/DashboardDeleteModal.tsx
- packages/frontend/src/hooks/dashboard/useDashboard.tsx
- packages/frontend/src/hooks/useSavedQuery.ts
- packages/frontend/src/hooks/useSpaces.ts
- packages/frontend/src/pages/Dashboard.tsx
Relates to: https://github.com/lightdash/lightdash/issues/5139
Rename other delete-mutation names to provide more detail and further avoid wrong imports. 
Discussed on: https://github.com/lightdash/lightdash/pull/5144#issuecomment-1514571489, thanks @IrakliJani !
> chore: rename other delete mutation hooks

- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/Explorer/ResultsCard/CellContextMenu.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/SeriesContextMenu.tsx
- packages/frontend/src/components/MetricQueryData/DrillDownMenuItem.tsx
- packages/frontend/src/components/MetricQueryData/DrillDownModal.tsx
- packages/frontend/src/components/MetricQueryData/MetricQueryDataProvider.tsx
- packages/frontend/src/components/MetricQueryData/UnderlyingDataModalContent.tsx
- packages/frontend/src/components/SimpleStatistic/BigNumberContextMenu.tsx
- packages/frontend/src/components/SimpleTable/CellContextMenu.tsx
- packages/frontend/src/components/SimpleTable/DashboardCellContextMenu.tsx
- packages/frontend/src/components/common/PivotTable/ValueCell.tsx
- packages/frontend/src/components/common/PivotTable/ValueCellMenu.tsx
- packages/frontend/src/components/common/PivotTable/index.tsx
- packages/frontend/src/components/common/PivotTable/tableStyles.tsx
- packages/frontend/src/hooks/pivotTable/pivotQueryResults.test.ts
- packages/frontend/src/hooks/pivotTable/pivotQueryResults.ts
Closes: #4933 
adds drill into and underlying data to metrics as rows
video demo:
https://cln.sh/8FDh5TL7
> feat: pivot table underlying data drill into

- packages/backend/src/controllers/pinningController.ts
- packages/common/src/index.ts
- packages/common/src/types/pinning.ts
- packages/frontend/src/components/PinnedItemsPanel/index.tsx
- packages/frontend/src/hooks/pinning/usePinnedItems.ts
- packages/frontend/src/pages/Home.tsx
> feat: use new pinnedItems API on the FE

- .github/workflows/count-blueprint.yml
- packages/frontend/src/hooks/dashboard/useDashboard.tsx
- scripts/count-blueprint-imports.ts
> chore: add github action for blueprint progress

- packages/frontend/src/pages/PasswordRecovery.styles.tsx
- packages/frontend/src/pages/PasswordRecovery.tsx
- packages/frontend/src/pages/PasswordRecoveryForm.tsx
Closes: #4923 
Before:
After: 
Before:
After:
> feat: migrate forgot password form to mantine

- packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
Closes: #5104
Before:
[Screencast from 03-05-23 10:39:45.webm](https://user-images.githubusercontent.com/1983672/235869492-6145251f-40bb-41ef-8371-5d1faf443143.webm)
Now:
[Screencast from 03-05-23 10:39:14.webm](https://user-images.githubusercontent.com/1983672/235869551-554dba2e-75e1-4b7e-96bb-91d11cf60c82.webm)
> fix: multiple series reference lines

- scripts/count-blueprint-imports.ts
sorted stats for blueprint burndown script
> chore: sort blueprint burndown counts

- packages/frontend/src/components/UserSettings/ProfilePanel/index.tsx
Closes: #5313 
Email verified
before: 
after:
Email not verified
before: 
after:
> feat: migrate profile settings to mantine

- packages/frontend/src/components/UserSettings/PasswordPanel/index.tsx
> feat: migrate password settings to mantine

- docker-compose.yml
Closes: 
This is to simplify self-hosting and make it easier to debug
> fix: remove scheduler from docker-compose by default

- packages/backend/src/controllers/projectController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/common/src/types/space.ts
- packages/e2e/cypress/e2e/api/README.md
- packages/e2e/cypress/e2e/api/api.cy.ts
- packages/e2e/cypress/e2e/api/organizationPermissions.cy.ts
- packages/e2e/cypress/e2e/api/pinning.cy.ts
- packages/e2e/cypress/e2e/api/projectPermissions.cy.ts
- packages/e2e/cypress/e2e/api/scheduler.cy.ts
- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
- packages/frontend/src/components/NavBar/BrowseMenu.tsx
- packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx
- packages/frontend/src/hooks/useSpaces.ts
> feat: add faster spaces endpoint

- packages/backend/src/models/AnalyticsModel.ts
- packages/backend/src/models/AnalyticsModelSql.ts
- packages/common/src/types/analytics.ts
Closes: #5076
We now show users who have never run a query
> fix: no queries analytics

- packages/backend/src/models/AnalyticsModelSql.ts
- packages/frontend/src/pages/UserActivity.tsx
Closes:  #5398
New users will show the days since the account was created (it can be < 90)
> fix: days usage analytics

- packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts
Closes: 
Set option to run the query asynchronously.
[Databricks docs](https://docs.databricks.com/dev-tools/nodejs-sql-driver.html#id15) don't provide much more information about this option
> fix: run databrick query async

- packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
[TypeError](https://lightdash.sentry.io/issues/4171880663/?referrer=slack)
Cannot read properties of undefined (reading 'reduce')
> fix: snowflake fields streaming

- packages/backend/src/clients/Slack/SlackClient.ts
> fix: increase slack channels request

- packages/backend/src/models/SavedChartModel.ts
- packages/backend/src/scheduler/SchedulerTask.ts
- packages/backend/src/services/SavedChartsService/SavedChartService.ts
- packages/backend/src/services/SchedulerService/SchedulerService.ts
- packages/backend/src/services/UnfurlService/UnfurlService.ts
- packages/common/src/types/savedCharts.ts
Closes: #5438 
- add a new method to get the chart summary
- replace `get()` with `getSummary()` where possible
> fix: optimize chart queries

- packages/frontend/src/components/UserSettings/PasswordPanel/index.tsx
- packages/frontend/src/hooks/user/usePassword.ts
Quick refactoring opportunity to move `useUserUpdatePasswordMutation` to the hooks file for passwords
> refactor: extract password hooks to single file

- packages/backend/src/models/AnalyticsModelSql.ts
Closes: #5486
New user 
User created > 90 days
> fix: remove new users from analytics

- packages/backend/src/models/ValidationModel/ValidationModel.ts
only pass property `lastUpdatedBy` if `first_name` is truthy
> fix: only pass property if first name

- packages/frontend/src/components/AboutFooter.tsx
> chore: hide update badge in development and cloud environments

- packages/backend/src/analytics/LightdashAnalytics.ts
> chore: add site url to server events

- packages/frontend/src/components/SettingsValidator/index.tsx
- packages/frontend/src/hooks/styles/useTableStyles.tsx
Closes: #5504
Add vertical scrolling to table if > 6 validation errors 
6 rows + adjusting height
https://github.com/lightdash/lightdash/assets/7611706/f907bf10-9da6-4004-952d-497682f0f78e
more than 6 rows
https://github.com/lightdash/lightdash/assets/7611706/cb6ed29c-d7d5-438c-8a2c-d65d8ebfca79
See comment below for latest screen recording: https://github.com/lightdash/lightdash/pull/5506#issuecomment-1549901980
> feat: add scroll if > 6 validation errors

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/scheduler/SchedulerTask.ts
- packages/backend/src/services/CsvService/CsvService.ts
- packages/backend/src/services/DashboardService/DashboardService.ts
- packages/backend/src/services/SavedChartsService/SavedChartService.ts
- packages/backend/src/services/SchedulerService/SchedulerService.ts
- packages/common/src/types/scheduler.ts
- packages/e2e/cypress/e2e/api/scheduler.cy.ts
- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulerForm.tsx
> chore: add format to scheduler events

- packages/backend/src/controllers/schedulerController.ts
- packages/backend/src/controllers/validationController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/models/SchedulerModel/index.ts
- packages/backend/src/scheduler/SchedulerClient.ts
- packages/backend/src/scheduler/SchedulerTask.ts
- packages/backend/src/scheduler/SchedulerWorker.ts
- packages/backend/src/services/SchedulerService/SchedulerService.ts
- packages/backend/src/services/ValidationService/ValidationService.test.ts
- packages/backend/src/services/ValidationService/ValidationService.ts
- packages/common/src/index.ts
- packages/common/src/types/scheduler.ts
- packages/common/src/types/validation.ts
- packages/e2e/cypress/e2e/api/api.cy.ts
- packages/frontend/src/components/SettingsValidator/index.tsx
- packages/frontend/src/hooks/scheduler/useScheduler.ts
- packages/frontend/src/hooks/validation/useValidation.ts
- packages/frontend/src/pages/ProjectSettings.tsx
Closes: #5508
[Screencast from 17-05-23 09:46:27.webm](https://github.com/lightdash/lightdash/assets/1983672/127cb888-0f1f-4703-977d-11988c93462d)
> feat: move generate validation to scheduler

- packages/e2e/cypress/e2e/api/api.cy.ts
- packages/e2e/cypress/e2e/api/organizationPermissions.cy.ts
- packages/e2e/cypress/e2e/api/pinning.cy.ts
- packages/e2e/cypress/e2e/api/projectPermissions.cy.ts
Closes: 
E2e tests can fail when there are multiple spaces (we create now private spaces in another e2e test)
> test: fix spaces-and-content e2e tests

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/clients/Slack/Slackbot.ts
- packages/backend/src/routers/slackRouter.ts
- packages/backend/src/services/UnfurlService/UnfurlService.ts
- packages/backend/src/services/services.ts
- packages/e2e/cypress/e2e/api/api.cy.ts
- packages/e2e/cypress/e2e/api/organizationPermissions.cy.ts
- packages/e2e/cypress/e2e/api/pinning.cy.ts
- packages/e2e/cypress/e2e/api/projectPermissions.cy.ts
> chore: add organization_id to slack unfurl events and rename old organizationUuid properties

- packages/frontend/src/components/NavBar/HeadwayMenuItem.tsx
Relates to: #5324 
Add tooltip "what's new?" to headway button
https://github.com/lightdash/lightdash/assets/7611706/4bf515a2-41e5-4f44-8905-4015a5e121b0
> feat: add tooltip to headway menu item

- packages/frontend/src/components/ChartConfigPanel/ChartConfigPanel.styles.ts
Closes: #5531
Stop forcing scroll bars.
Before:
After:
> fix: chart config scroll

- packages/cli/src/dbt/templating.test.ts
- packages/cli/src/dbt/templating.ts
> fix: env_var() default value

- docs/docs/references/roles.mdx
updates the roles docs to include admin access to all content
> docs: updates roles doc to include admin access

- packages/frontend/src/components/common/Filters/FilterInputs/AutoComplete/MultiAutoComplete.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/AutoComplete/autoCompleteUtils.ts
Closes:  
https://github.com/lightdash/lightdash/issues/5201
https://github.com/lightdash/lightdash/issues/5551
- Remove lowercase conversion while merge and do lowercase conversion only for unique checking
> fix: Copying a list of IDs into filters makes it lowercase

- packages/backend/src/services/ValidationService/ValidationService.mock.ts
- packages/backend/src/services/ValidationService/ValidationService.ts
> feat: remove NO_DIMENSIONS_FOUND from validation

- packages/frontend/src/components/UserSettings/AppearancePanel/index.tsx
- packages/frontend/src/components/common/PivotTable/ValueCell.tsx
- packages/frontend/src/components/common/PivotTable/tableStyles.tsx
- packages/frontend/src/utils/colorUtils.ts
Closes: #5569 
Change: 
- add util function to validate hex code colour
- check if color is valid before using it in external libraries methods
> fix: conditional formatting with empty color

- packages/backend/src/database/migrations/20230322102401_add_interactive_viewer_role.ts
- packages/backend/src/database/migrations/20230327070336_add_developer_role.ts
> fix: fix rollback role migration

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/database/entities/projects.ts
- packages/backend/src/database/migrations/20230522085619_preview_content.ts
- packages/backend/src/models/ProjectModel/ProjectModel.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/cli/src/handlers/createProject.ts
- packages/cli/src/handlers/preview.ts
- packages/common/src/index.ts
- packages/common/src/types/projects.ts
Closes:  #5228
[Screencast from 22-05-23 16:35:22.webm](https://github.com/lightdash/lightdash/assets/1983672/2e5da71f-4446-43b9-a7be-25fdcd0a6021)
Validation on prod 
Validation on preview after I change a dimension 
Stored mapping sample: 
``` {
"charts": [{
"id": 1,
"newId": 157
}, {
"id": 2,
"newId": 158
}, {
"id": 3,
"newId": 159
}, {
"id": 4,
"newId": 160
}, {
"id": 5,
"newId": 161
}, {
"id": 6,
"newId": 162
}],
"spaces": [{
"id": 1,
"newId": 54
}],
"dashboards": [{
"id": 1,
"newId": 19
}],
"chartVersions": [{
"id": 1,
"newId": 133
}, {
"id": 2,
"newId": 134
}, {
"id": 3,
"newId": 135
}, {
"id": 4,
"newId": 136
}, {
"id": 5,
"newId": 137
}, {
"id": 6,
"newId": 138
}],
"dashboardVersions": [{
"id": 1,
"newId": 19
}]
}
```
> feat: copy content preview

- packages/backend/src/services/ProjectService/ProjectService.ts
> fix: add try-catch to copy content

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/controllers/validationController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/scheduler/SchedulerTask.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/backend/src/services/ValidationService/ValidationService.ts
- packages/common/src/types/scheduler.ts
- packages/frontend/src/components/NavBar/NotificationsMenu/index.tsx
- packages/frontend/src/components/SettingsValidator/index.tsx
- packages/frontend/src/hooks/validation/useValidation.ts
> feat: add analytics to validation

- packages/backend/src/models/ProjectModel/ProjectModel.ts
> fix: fix additional metric copy typo

- packages/backend/src/models/ValidationModel/ValidationModel.ts
After merging: https://github.com/lightdash/lightdash/pull/5586, another issue came up with dashboards and charts and tables having duplicate errors.
> fix: distinct on validation error

- packages/backend/src/database/entities/validation.ts
- packages/backend/src/models/DashboardModel/DashboardModel.mock.ts
- packages/backend/src/models/DashboardModel/DashboardModel.test.ts
- packages/backend/src/models/DashboardModel/DashboardModel.ts
- packages/common/src/types/dashboard.ts
Related to: #5593 
Add validation errors to dashboards in model. 
Can confirm that it returns ok, and ready to re-open #5570 after this
> feat: add validation errors to dashboards in model

- packages/backend/src/services/ValidationService/ValidationService.ts
Closes: #5567
Closes: #5572
Before: 
AFter:
> fix: fix validation sorting false positives

- packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx
- packages/frontend/src/components/Explorer/ExploreTree/index.tsx
Closes: #5541 
https://github.com/lightdash/lightdash/assets/67699259/3fcf5881-eaa6-49e7-8641-619f35617c58
> fix: show custom metrics when at least 1 is defined

- packages/frontend/src/components/NavBar/HelpMenu.tsx
Closes: #5625 
https://github.com/lightdash/lightdash/assets/67699259/8b88c23b-f521-4999-900e-0efcf642e5a3
> fix: help menu links are broken

- packages/frontend/src/components/NavBar/index.tsx
Closes: #5626 
Using 'blue.6' instead of purple after @PriPatel & @TuringLovesDeathMetal's feedback.
https://github.com/lightdash/lightdash/assets/7611706/ae921898-fa1f-4976-ab66-6803e4e36c8f
> feat: add preview banner for preview projects

- packages/frontend/src/components/TableConfigPanel/ColumnConfiguration.styles.ts
- packages/frontend/src/components/TableConfigPanel/ColumnConfiguration.tsx
- packages/frontend/src/components/TableConfigPanel/DroppableItemsList.tsx
- packages/frontend/src/components/TableConfigPanel/GeneralSettings.tsx
- packages/frontend/src/components/TableConfigPanel/TableConfig.styles.ts
Closes: #4879 
Note: Only introduced a couple of simple mantine components to avoid a big refactor and make it really different from the rest of the chart config.
Without pivot:
With pivot:
> feat: table configuration with drag and drop 

- packages/backend/src/database/entities/savedCharts.ts
- packages/backend/src/models/ValidationModel/ValidationModel.ts
- packages/common/src/types/validation.ts
- packages/frontend/src/components/SettingsValidator/ValidatorTable.tsx
- packages/frontend/src/components/common/ResourceView/ResourceIcon.tsx
- packages/frontend/src/hooks/styles/useTableStyles.tsx
Closes: #5640 
Screenshots:
https://github.com/lightdash/lightdash/assets/7611706/c7d8b70d-caeb-4d7f-9318-4abb369fb18c
> feat: add correct icon for charts in validator table

- packages/backend/src/services/SpaceService/SpaceService.ts
> feat: admins can access private space

- .github/workflows/release-on-merge.yml
Closes: 
tested on alpha https://github.com/lightdash/lightdash/actions/runs/5110248608/jobs/9185931066
> fix: release on merge

- packages/e2e/cypress/e2e/settings/invites.cy.ts
- packages/frontend/src/components/DbtCloudSettings/index.tsx
- packages/frontend/src/components/ProjectAccess/ProjectAccess.styles.ts
- packages/frontend/src/components/ProjectAccess/ProjectAccess.tsx
- packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectManually/ConnectManuallyStep1.tsx
- packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectManually/index.tsx
- packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectSuccess.tsx
- packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectUsingCLI.tsx
- packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ProjectConnectFlow.styles.tsx
- packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/SelectWarehouse.tsx
- packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/UnsupportedWarehouse.tsx
- packages/frontend/src/components/ProjectConnection/ProjectConnection.styles.tsx
- packages/frontend/src/components/ProjectConnection/index.tsx
- packages/frontend/src/components/ProjectTablesConfiguration/ProjectTablesConfiguration.styles.tsx
- packages/frontend/src/components/ProjectTablesConfiguration/ProjectTablesConfiguration.tsx
- packages/frontend/src/components/SettingsScheduledDeliveries/index.tsx
- packages/frontend/src/components/SettingsUsageAnalytics/SettingsUsageAnalytics.styles.ts
- packages/frontend/src/components/SettingsUsageAnalytics/index.tsx
- packages/frontend/src/components/SettingsValidator/index.tsx
- packages/frontend/src/components/UserSettings/InvitesPanel/index.tsx
- packages/frontend/src/components/UserSettings/ProjectManagementPanel/ProjectManagementPanel.styles.ts
- packages/frontend/src/components/UserSettings/ProjectManagementPanel/index.tsx
- packages/frontend/src/components/UserSettings/UserManagementPanel/UserManagementPanel.styles.ts
- packages/frontend/src/components/UserSettings/UserManagementPanel/index.tsx
- packages/frontend/src/components/common/Settings/SettingsCard.tsx
- packages/frontend/src/pages/Settings.styles.tsx
- packages/frontend/src/pages/Settings.tsx
Closes: #5408 
Upgraded BlueprintJS Cards to MantineJS
> style: Migrate Settings Bluprint Card to Mantine

- packages/frontend/src/pages/Space.tsx
Closes:  https://github.com/lightdash/lightdash/issues/5601
- Make dashboard the default tab
> feat: Dashboards should be listed in a space first, by default

- packages/backend/src/services/ProjectService/ProjectService.ts
> fix: check copy project access

- packages/cli/src/handlers/dbt/validate.ts
fixes typo in lightdash validate command help.
> fix: fixes typo in start-preview

- packages/backend/src/otel.ts
> feat: make otlp endpoint configurable

- packages/common/src/compiler/filtersCompiler.mock.ts
- packages/common/src/compiler/filtersCompiler.ts
Closes: #4593
My results: (I had to set to NULL some values on db for testing) 
Before the fix 
After the fix
> fix: is not equal return null values

- packages/backend/src/services/ProjectService/ProjectService.test.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/backend/src/services/services.ts
- packages/common/src/types/projects.ts
- packages/warehouses/package.json
- packages/warehouses/src/index.ts
- packages/warehouses/src/ssh/sshTunnel.ts
- yarn.lock
Stacked PR3 for #2650 (for details see https://github.com/lightdash/lightdash/pull/5612)
Adds `SshTunnel` and uses throughout the project service.
> feat: add ssh tunnel (stacked 3)

- docs/docs/guides/cli/how-to-use-lightdash-validate.mdx
- packages/cli/src/config.ts
- packages/cli/src/handlers/deploy.ts
- packages/cli/src/handlers/preview.ts
- packages/cli/src/handlers/setProject.ts
- packages/cli/src/handlers/validate.ts
- packages/cli/src/index.ts
> feat: default project on validate

- packages/common/src/types/pivot.ts
- packages/frontend/src/components/SimpleTable/index.tsx
- packages/frontend/src/components/common/PivotTable/index.tsx
- packages/frontend/src/hooks/pivotTable/pivotQueryResults.test.ts
- packages/frontend/src/hooks/pivotTable/pivotQueryResults.ts
Closes: #5679 
TODO: 
https://github.com/lightdash/lightdash/assets/9117144/16a26ae1-9738-4b2e-86dd-1edc16439209
> feat: pivot table virtual rows

- packages/frontend/src/components/SettingsValidator/ValidatorTable.tsx
- packages/frontend/src/components/UserSettings/AccessTokensPanel/TokensTable.tsx
- packages/frontend/src/components/common/ResourceView/ResourceViewList/index.tsx
- packages/frontend/src/hooks/styles/useTableStyles.tsx
Closes: https://github.com/lightdash/lightdash/issues/5697
settings:
homepage:
> style: settings page table header

- packages/frontend/package.json
- packages/frontend/src/components/common/PivotTable/index.tsx
- packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
- yarn.lock
Fixes edge case where the virtual table doesn't recognize the latest `ref` value and doesn't render more rows.
More details on this issue from the library github https://github.com/TanStack/virtual/issues/263#issuecomment-1040073538
Updating to the latest version solves the issue since it now has a callback to fetch the latest `ref` value.
https://github.com/lightdash/lightdash/assets/9117144/ff55961f-0428-4bc4-aae0-0a18fed87970
> fix: virtual table with empty ref

- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes: https://github.com/lightdash/lightdash/issues/4617
Only sort results for chart, if the date is selected as xAxis dimension and date is not sorted by default.
> fix: default sort date chart

- packages/backend/src/controllers/csvController.ts
- packages/backend/src/controllers/dbtCloudIntegrationController.ts
- packages/backend/src/controllers/groupsController.ts
- packages/backend/src/controllers/organizationController.ts
- packages/backend/src/controllers/pinningController.ts
- packages/backend/src/controllers/projectController.ts
- packages/backend/src/controllers/runQueryController.ts
- packages/backend/src/controllers/savedChartController.ts
- packages/backend/src/controllers/schedulerController.ts
- packages/backend/src/controllers/shareController.ts
- packages/backend/src/controllers/slackController.ts
- packages/backend/src/controllers/sshController.ts
- packages/backend/src/controllers/userController.ts
- packages/backend/src/controllers/validationController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/tsoa.json
Towards #5666
Adds tags, improved descriptions, and names for controllers so that api docs are easier to browse. 
Docs: https://lightdash-pr-5708.onrender.com/api/docs
> docs: improve descriptions for openapi spec (stacked 1)

- packages/backend/src/models/ProjectModel/ProjectModel.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
> fix: fix missing project to copy, foreign key error

- packages/backend/src/controllers/sshController.ts
- packages/common/src/index.ts
- packages/frontend/src/components/ProjectConnection/WarehouseForms/PostgresForm.tsx
- packages/frontend/src/components/ProjectConnection/WarehouseForms/RedshiftForm.tsx
- packages/frontend/src/components/ProjectConnection/WarehouseForms/sshHooks.ts
- packages/frontend/src/components/ReactHookForm/Input.tsx
Final stacked PR for #2650 (for details see https://github.com/lightdash/lightdash/pull/5612)
Closes: #2650 
Showing new fields - error handling on generating a key - copying a key
> feat: add ssh tunnel to project config form

- packages/backend/src/otel.ts
Kill process on Open telemetry shutdown.
> fix: exit process on otel shutdown

- docs/docs/self-host/customize-deployment/configure-standalone-scheduled-worker.md
> docs: how to run standalone scheduler worker

- packages/backend/src/generated/swagger.json
> fix: regenerate tsoa spec-and-routes

- .husky/pre-commit
> fix: revert generating openapi in husky hook

- packages/frontend/src/pages/Settings.tsx
Closes: https://github.com/lightdash/lightdash/issues/5734
im leaving second word lowercased to match with existing menu items
> feat: rename project settings

- packages/backend/src/generated/swagger.json
- packages/common/src/authorization/organizationMemberAbility.ts
- packages/common/src/authorization/projectMemberAbility.ts
- packages/e2e/cypress/e2e/api/projectPermissions.cy.ts
Closes: #5761
I'm a developer
Before:
After:
> fix: cli deploy permissions

- packages/backend/src/config/parseConfig.ts
noticed in our logs that the default now doesn't include http logs but it used to!
> fix: default to http level logs

- packages/frontend/src/components/common/Table/Table.styles.ts
Closes: #5495 
Closes: https://github.com/lightdash/lightdash/pull/5778
Added top border for tables
> fix: add top border for table header

- packages/frontend/src/components/TableConfigPanel/GeneralSettings.tsx
Updates copy on the chart config button from `show results total` to `show number of results`.
> chore: updates copy on show results total 

- docs/docs/references/dimensions.mdx
- docs/docs/references/filters.md
- docs/docs/references/joins.md
- docs/docs/references/metrics.mdx
- docs/docs/references/tables.md
- docs/sidebars.js
updates reference docs titles and moves things around in the sidebar
> docs: updates reference docs titles

- packages/frontend/src/components/SchedulersView/LogsView.tsx
- packages/frontend/src/components/SchedulersView/SchedulersView.tsx
- packages/frontend/src/components/SchedulersView/SchedulersViewUtils.tsx
Closes: #5800 
before
https://github.com/lightdash/lightdash/assets/67699259/c06b3657-c45a-4c76-af9a-2504ec42c8f2
after
> fix: scheduled deliveries dash edge case, no destinations

- packages/frontend/src/components/ErrorLogsDrawer.tsx
- packages/frontend/src/components/NavBar/index.tsx
- packages/frontend/src/providers/ErrorLogsProvider.tsx
Closes: #5748 
https://github.com/lightdash/lightdash/assets/67699259/ebe97f68-67e6-4652-a552-ed6a7a851a62
> fix: remove show error logs button from navbar

- packages/frontend/src/components/SimpleTable/index.tsx
- packages/frontend/src/components/common/PivotTable/index.tsx
- packages/frontend/src/components/common/PivotTable/tableStyles.tsx
closes: #5771 
https://github.com/lightdash/lightdash/assets/962095/f8d6f3ac-7e71-45b4-8b9f-607a657ed603
> feat: pin column totals in pivot table

- packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
> fix: exclude dimensions from summable metric field ids

- packages/backend/src/models/SavedChartModel.ts
- packages/backend/src/services/UnfurlService/UnfurlService.ts
- packages/common/src/types/savedCharts.ts
> fix: big number size in Slack and E-mail

- .github/CONTRIBUTING.md
Update instructions of using new `.env.development.local` based on `with docker-compose` from #5787 to `without docker instructions`
> docs: adjust instructions to use new .env.development file

- packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
Closes: #5810 
https://github.com/lightdash/lightdash/assets/962095/4b4a12b7-12ed-42ad-82e4-24ce773c5033
> fix: pivot table hide table calculations

- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/common/src/types/warehouse.ts
- packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
- packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts
- packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
- packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
- packages/warehouses/src/warehouseClients/TrinoWarehouseClient.ts
Closes: #3379
Example of labels persisting on biquery job (fetched using `bq` cli)
Appends to sql
> feat: add query tags

- packages/frontend/src/components/SchedulersView/LogsView.tsx
Closes: #5823
https://github.com/lightdash/lightdash/assets/67699259/6982a208-ea5c-4372-836b-9aaf1f5157c7
> fix: all jobs shouldn't open all at once

- docs/docs/references/metrics.mdx
- packages/common/src/compiler/filtersCompiler.mock.ts
- packages/common/src/compiler/filtersCompiler.test.ts
- packages/common/src/compiler/filtersCompiler.ts
- packages/common/src/types/conditionalRule.ts
- packages/common/src/types/filterGrammar.test.ts
- packages/common/src/types/filterGrammar.ts
- packages/common/src/utils/conditionalFormatting.ts
- packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
- packages/frontend/src/components/common/Filters/configs.ts
Closes:  https://github.com/lightdash/lightdash/issues/5387
- Add ends with filter
- Similar to starts with, can multi-select items to filter
> feat: "Ends with" option for filtering

- packages/backend/package.json
- packages/warehouses/package.json
- yarn.lock
Update snowflake sdk since there is a new security patch
> fix: update snowflake sdk

- docs/docs/guides/how-to-create-scheduled-deliveries.mdx
> docs: updates scheduled deliveries doc to include 3 day expiry

- docs/docs/guides/adding-tables-to-lightdash.mdx
- docs/docs/snippets/how-to-create-dimensions.mdx
- docs/docs/snippets/how-to-create-metrics.mdx
> fix: docs typo "commnd" -> "command"

- packages/backend/src/controllers/spaceController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
Fixes: https://github.com/lightdash/lightdash/pull/5849
I made a mistake to name the method to revoke a space-level access.
> fix: correct the method name to revoke space-level access

- packages/frontend/src/components/common/PivotTable/index.tsx
- packages/frontend/src/components/common/PivotTable/tableStyles.tsx
Closes: https://github.com/lightdash/lightdash/issues/5825
https://github.com/lightdash/lightdash/assets/962095/7c45e488-0db6-4e0c-a75b-d81f4ddb985d
> feat: pivot table freeze headers

- packages/frontend/src/components/common/PivotTable/Cell.tsx
- packages/frontend/src/components/common/PivotTable/ValueCell.tsx
- packages/frontend/src/components/common/PivotTable/tableStyles.tsx
Closes: #5854 
https://github.com/lightdash/lightdash/assets/962095/3a9898f1-f607-4989-8958-7843e798d121
> feat: pivot table truncate large texts

- packages/backend/src/controllers/validationController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
Closes: https://github.com/lightdash/lightdash/issues/5951
We are adding the required parameter `projectUuid` to `DeleteValidationDismiss`.
> fix: add the path parameter projectUuid to  DeleteValidationDismiss

- packages/frontend/src/components/DashboardTiles/TileBase/TileBase.styles.tsx
- packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/4982
Closes: https://github.com/lightdash/lightdash/issues/5102
https://github.com/lightdash/lightdash/assets/962095/a6d3db8d-05bf-4e53-8b80-67fa884447bc
> fix: tile name on hover not appearing

- packages/frontend/src/components/NavBar/ProjectSwitcher.tsx
Closes: https://github.com/lightdash/lightdash/issues/5366
https://github.com/lightdash/lightdash/assets/962095/ebd03874-33e6-43c9-ad54-22ab1a541747
> fix: project switcher dropdown overflow

- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
> fix: date inputs max date

- packages/backend/.eslintrc.js
- packages/backend/package.json
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
Closes: #5930
https://eslint.org/docs/latest/use/configure/ignore
Before:
Now:
> chore: Skip generated lint files (swagger and routes) 

- packages/frontend/src/pages/UserActivity.tsx
User was confused by the current copy: https://lightdash.slack.com/archives/C03QX09JLCU/p1687166630933769?thread_ts=1680776369.414679&cid=C03QX09JLCU
Is my interpretation here correct?
Closes:
> docs: update labels on activity dashboard

- packages/backend/src/controllers/organizationController.ts
- packages/backend/src/generated/swagger.json
> chore: change order middleware

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
Closes: #5937
Added the following property: 
`tableCalculationsPercentFormatCount`
> chore: track table calculations percent format count

- packages/backend/src/scheduler/SchedulerTask.ts
Closes: #5945 
Read ticket for description ^ 
I believe this is where it needs to be done 👍
> fix: assert unreachable scheduled delivery format

- packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx
> feat: migrate `Add charts to dashboard` modal and multiselect

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/database/migrations/20230620204726_add_pie_to_chart_type.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/services/SavedChartsService/SavedChartService.ts
- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/Explorer/VisualizationCard/VisualizationConfigPanel.tsx
- packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
- packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
- packages/frontend/src/components/LightdashVisualization/index.tsx
- packages/frontend/src/components/common/ResourceIcon/index.tsx
- packages/frontend/src/components/common/ResourceView/resourceUtils.ts
- packages/frontend/src/hooks/usePieChartConfig.ts
- packages/frontend/src/providers/ExplorerProvider.tsx
closes: https://github.com/lightdash/lightdash/issues/6002
> feat: pie charts - add chart type and dropdown item

- packages/frontend/src/providers/DashboardProvider.tsx
Closes: #5817 
- found a syntax bug, setting values to the wrong state
- we were overriding the filters on dashboard load with dash saved filters
> fix: dashboard URL should update with filter values

- packages/backend/src/controllers/organizationController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/models/OrganizationAllowedEmailDomainsModel.ts
- packages/common/src/types/organization.ts
- packages/frontend/src/components/UserSettings/AllowedDomainsPanel/index.tsx
Closes: #5507 
Note: not adding developer and admin as that options since they have high level of permissions and access. Setting these roles as default role by mistake could cause security issues for that org. We can reconsider this in the future.
> feat: add editor and interactive viewer to default role options

- .github/CONTRIBUTING.md
Closes: 
NA
Environment variable is not created without the export keyword
> docs: Fix environment variable instructions

- packages/frontend/src/components/common/ResourceView/index.tsx
Reverts lightdash/lightdash#5931
Check if this is upping the CPU utilisation within app
> fix: revert #5931

- packages/backend/src/models/SavedChartModel.ts
- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx
Reverts lightdash/lightdash#6037
Check if this is upping the CPU utilisation within app
> fix: revert #6037

- packages/e2e/cypress/e2e/downloadCsv.cy.ts
- packages/frontend/src/components/BigNumberConfig/BigNumberConfigTabs.tsx
- packages/frontend/src/components/BigNumberConfig/index.tsx
- packages/frontend/src/components/ChartConfigPanel/ChartConfigPanel.styles.ts
- packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
- packages/frontend/src/components/ChartConfigPanel/index.tsx
- packages/frontend/src/components/ChartDownload.tsx
- packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
- packages/frontend/src/components/TableConfigPanel/TableConfig.styles.ts
- packages/frontend/src/components/TableConfigPanel/index.tsx
- packages/frontend/src/components/common/CollapsableCard.tsx
> fix: revert changes to chart config mantine refactor

- docs/docs/guides/table-calculations/adding-table-calculations.mdx
removes currency formatting example
> docs: Update adding-table-calculations.mdx

- packages/e2e/cypress/e2e/dates.cy.ts
- packages/e2e/cypress/e2e/downloadCsv.cy.ts
- packages/e2e/cypress/e2e/explore.cy.ts
- packages/frontend/src/components/AddColumnButton.tsx
- packages/frontend/src/components/BigNumberConfig/BigNumberConfigTabs.tsx
- packages/frontend/src/components/BigNumberConfig/index.tsx
- packages/frontend/src/components/ChartConfigPanel/index.tsx
- packages/frontend/src/components/ChartDownload.tsx
- packages/frontend/src/components/DownloadSqlCsvButton/index.tsx
- packages/frontend/src/components/Explorer/ResultsCard/ResultsCard.tsx
- packages/frontend/src/components/Explorer/SqlCard/OpenInSqlRunnerButton.tsx
- packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
- packages/frontend/src/components/PieChartConfig/index.tsx
- packages/frontend/src/components/TableConfigPanel/index.tsx
- packages/frontend/src/components/common/CollapsableCard.style.ts
- packages/frontend/src/components/common/CollapsableCard.tsx
> feat: explore card action item styles

- packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx
Closes #6075, closes #6074
Make `MultiSelect` `separator` sticky
Change styling of `separator label`
screen-recording: 
https://github.com/lightdash/lightdash/assets/7611706/18bb4707-d9de-4b14-a87b-02da67df0bd5
> style: pin separator and change font style of separator label in multiselect

- packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx
- packages/frontend/src/components/LimitButton/LimitBadge.tsx
- packages/frontend/src/components/SortButton/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/6060
> feat: explore card sort and limit pill styles

- packages/frontend/src/components/SimpleChart/index.tsx
- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes: #5081 
Adjust chart totals based on legends selected
https://github.com/lightdash/lightdash/assets/55316723/407d9b13-fe30-481e-a822-a11c1628812b
> fix: adjust chart totals based on legends selected

- packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
- packages/frontend/src/components/LightdashVisualization/index.tsx
- packages/frontend/src/components/PieChartConfig/PieChartLayoutConfig.tsx
- packages/frontend/src/components/SimplePieChart/index.tsx
- packages/frontend/src/hooks/echarts/useEchartsPieChart.ts
- packages/frontend/src/hooks/usePieChartConfig.ts
- yarn.lock
Closes: https://github.com/lightdash/lightdash/issues/6005
https://github.com/lightdash/lightdash/assets/962095/bc6d5b89-f620-4673-b4f1-2f6d53f3ff55
> feat: pie charts echarts visualization

- packages/frontend/src/components/PieChartConfig/PieChartLayoutConfig.tsx
- packages/frontend/src/hooks/echarts/useEchartsPieChart.ts
- yarn.lock
Closes: https://github.com/lightdash/lightdash/issues/6004
> feat: pie charts donut option

- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes: #6125 
https://github.com/lightdash/lightdash/assets/55316723/0eed4c27-7627-4232-bdaf-ff1b067cd321
> fix: working chart on legend checkbox toggle

- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/PieChartConfig/PieChartLayoutConfig.tsx
- packages/frontend/src/components/PieChartConfig/PieChartSeriesConfig.tsx
- packages/frontend/src/components/PieChartConfig/index.tsx
- packages/frontend/src/hooks/echarts/useEchartsPieChart.ts
- packages/frontend/src/hooks/usePieChartConfig.ts
Closes: https://github.com/lightdash/lightdash/issues/6006
outside:
inside:
hidden:
donut:
options:
> feat: pie charts value label options

- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/PieChartConfig/PieChartDisplayConfig.tsx
- packages/frontend/src/components/PieChartConfig/index.tsx
- packages/frontend/src/hooks/echarts/useEchartsPieChart.ts
- packages/frontend/src/hooks/usePieChartConfig.ts
Closes: https://github.com/lightdash/lightdash/issues/6008
https://github.com/lightdash/lightdash/assets/962095/466ae7be-c836-42d0-bc07-924e8b0c3bc0
> feat: pie charts hide legend option

- packages/common/src/compiler/filtersCompiler.mock.ts
- packages/common/src/compiler/filtersCompiler.ts
- packages/common/src/types/conditionalRule.ts
- packages/common/src/utils/conditionalFormatting.ts
- packages/common/src/utils/filters.ts
- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
- packages/frontend/src/components/common/Filters/configs.ts
> feat: not in the last filter

- scripts/count-blueprint-imports.ts
adds total number of imports from mantine
> chore: add mantine import counter

- packages/frontend/src/components/UserSettings/UserManagementPanel/index.tsx
Closes: #5994
Before: 
As editor: 
As admin:
> fix: fix user management permission table

- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/PieChartConfig/PieChartSeriesConfig.tsx
- packages/frontend/src/hooks/echarts/useEchartsPieChart.ts
- packages/frontend/src/hooks/usePieChartConfig.ts
⚠️ run this in browser console `localStorage.setItem('enablePieCharts', true)` and refresh page to enable pie chart menu item
Closes: #6009 
https://github.com/lightdash/lightdash/assets/962095/c213483b-20e8-48d5-9ba3-244c8756adc3
> feat: pie charts colour and value labels

- packages/backend/src/services/SpaceService/SpaceService.ts
> feat: allow admins to update/delete private spaces

- package.json
- packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
- packages/frontend/src/components/PieChartConfig/PieChartLayoutConfig.tsx
- packages/frontend/src/components/PieChartConfig/PieChartSeriesConfig.tsx
- packages/frontend/src/hooks/echarts/useEchartsPieChart.ts
- packages/frontend/src/hooks/usePieChartConfig.ts
- packages/frontend/tsconfig.json
- yarn.lock
Closes: https://github.com/lightdash/lightdash/issues/6151
https://github.com/lightdash/lightdash/assets/962095/2f28b63f-6dc7-4ed8-b3e2-0429a405ee0e
https://github.com/lightdash/lightdash/assets/962095/d6fce4b7-18ce-4d80-b38d-178fb5aab2ab
> feat: pie charts tweaks

- docs/docs/references/filters.md
adds `not in the last` to filters docs
> docs: Update filters.md

- packages/frontend/src/pages/UserActivity.tsx
- swaps the colours of the bar and line chart in the user query activity in the usage analytics dashboard (the contrast made it hard to see the line chart)
> chore: swaps colours on usage analytics chart

- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes: #5395
[Screencast from 07-07-23 09:15:44.webm](https://github.com/lightdash/lightdash/assets/1983672/adaf86eb-24fa-4ffc-a833-57fe769c581e)
> feat: echarts show tooltip only on hovered lines/bars

- packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
Closes: #6081 
Adds some space above charts in the chart editor
> style: add space above charts in editor

- packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
Closes: #6200 
https://github.com/lightdash/lightdash/assets/962095/38bb9177-910c-477c-911b-6184c4ae6b9e
> fix: pie charts with unselected custom metrics

- packages/frontend/src/components/ChartConfigPanel/Series/Series.styles.ts
> fix: grouped series padding

- packages/backend/src/models/SavedChartModel.ts
- packages/backend/src/services/CsvService/CsvService.mock.ts
- packages/common/src/dbt/schemas/lightdashMetadata.json
- packages/common/src/dbt/schemas/lightdashV8.json
- packages/common/src/dbt/schemas/lightdashV9.json
- packages/common/src/dbt/validation.mock.ts
- packages/common/src/dbt/validation.test.ts
- packages/common/src/types/dbt.ts
- packages/common/src/types/field.ts
- packages/common/src/types/metricQuery.ts
- packages/common/src/utils/formatting.test.ts
- packages/common/src/utils/formatting.ts
- packages/frontend/src/hooks/useBigNumberConfig.ts
Closes: [#5418](https://github.com/lightdash/lightdash/issues/5418)
We weren't validating the columns meta. 
Changes:
- validate columns meta
- update schema to check all meta properties
- improve format typing
- add unit tests
> fix: manifest validation

- .github/workflows/cli-tests.yml
- packages/cli/src/dbt/manifest.ts
- packages/cli/src/handlers/compile.ts
- packages/cli/src/handlers/dbt/getDbtVersion.ts
- packages/common/src/dbt/schemas/lightdashV7.json
- packages/common/src/dbt/schemas/manifestV7.json
- packages/common/src/dbt/validation.ts
- packages/common/src/types/dbt.ts
Closes: https://github.com/lightdash/lightdash/issues/6226
> feat: bring back support dbt 1.3 in the CLI

- packages/frontend/src/components/TableCalculationModals/TableCalculationModal.styles.ts
- packages/frontend/src/components/TableCalculationModals/TableCalculationModal.tsx
Closes: #6252
Before:
[Screencast from 11-07-23 17:11:49.webm](https://github.com/lightdash/lightdash/assets/1983672/688e0b04-3785-4ca8-88fa-7fdfd4005e15)
Now:
[Screencast from 11-07-23 17:39:56.webm](https://github.com/lightdash/lightdash/assets/1983672/18678430-6d43-4289-a176-9464a1299342)
> fix: fix table calculation fullscreen

- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/PieChartConfig/PieChartSeriesConfig.tsx
- packages/frontend/src/hooks/echarts/useEchartsPieChart.ts
- packages/frontend/src/hooks/usePieChartConfig.ts
Closes: #6152 
https://github.com/lightdash/lightdash/assets/962095/bfe947db-e7bf-423e-87ca-ba2ddfd28e3e
https://github.com/lightdash/lightdash/assets/962095/e5af3350-ab12-46db-aeb7-a15b4bee2a68
> feat: pie charts drag and drop series

- packages/backend/src/dbt/dbtCliClient.ts
> fix: explore dbt errors for all versions

- examples/api/organization-members.http
- packages/backend/src/controllers/organizationController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/models/OrganizationMemberProfileModel.ts
- packages/backend/src/services/OrganizationService/OrganizationService.ts
- packages/common/src/index.ts
- packages/common/src/types/api/uuid.ts
- packages/common/src/types/organizationMemberProfile.ts
> feat: api to get organization members

- packages/frontend/src/components/VisualizationConfigs/BigNumberConfig/BigNumberConfigTabs.tsx
- packages/frontend/src/components/VisualizationConfigs/BigNumberConfig/index.tsx
- packages/frontend/src/hooks/useBigNumberConfig.ts
Closes: #6250 
Migrates the big number config panel to Mantine
> feat: big number config panel using mantine

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
Closes: #6630 
Changes:
- expose query error in UI
Before: 
After fix:
(When trying export csv)
> fix: show chart tile error

- packages/backend/src/services/CsvService/CsvService.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
> feat: trace runMetricQuery and add generated sql

- packages/backend/src/database/seeds/development/03_saved_dashboards.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/models/DashboardModel/DashboardModel.test.ts
- packages/backend/src/models/DashboardModel/DashboardModel.ts
- packages/backend/src/models/SavedChartModel.ts
- packages/backend/src/services/DashboardService/DashboardService.test.ts
- packages/backend/src/services/DashboardService/DashboardService.ts
- packages/common/src/types/dashboard.ts
- packages/e2e/cypress/e2e/api/api.cy.ts
- packages/e2e/cypress/e2e/api/dashboard.cy.ts
- packages/e2e/cypress/support/commands.ts
Closes: **1/? of** [#6133](https://github.com/lightdash/lightdash/issues/6133) 
Changes:
- allow a chart to be created when creating/updating a dashboard
- add unit tests
- update API docs
> feat: create chart at tile creation

- packages/backend/src/queryBuilder.ts
Closes: #6389
<pending PR preview for screenshot>
> fix: deduplicate metric sql from filters

- packages/backend/src/models/ResourceViewItemModel.ts
Closes: #6182
- Change reference to chart_count field in query result
> fix: I can't see the number of charts in a Pinned Space when I hover over it 

- packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeProvider.tsx
Closes: #6202 
Allows searching by `groupLabel` in explore
Added `group_label` to 2 dimensions in our demo yml (`events.yml`)
https://github.com/lightdash/lightdash/assets/7611706/7a9d9a1b-6c3b-44a4-a253-d9c046ed7368
> feat: allow filtering by group_label

- docs/docs/guides/limiting-data-using-filters.mdx
- docs/docs/references/tables.mdx
Closes #6409 
https://deploy-preview-6410--peaceful-bassi-cbf284.netlify.app/guides/limiting-data-using-filters
https://deploy-preview-6410--peaceful-bassi-cbf284.netlify.app/references/tables#sql-filter
> docs: add docs for sql_filter

- packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ColumnConfiguration.tsx
- packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingList.tsx
- packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/DroppableItemsList.tsx
- packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/GeneralSettings.tsx
Closes: #6255 
Migrates the table column/pivot config to Mantine.
> feat: update table column config to use mantine

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/services/SavedChartsService/SavedChartService.ts
Closes: https://github.com/lightdash/lightdash/issues/6420
events are sent per conditional formatting rule:
```js
[
{
event: 'conditional_formatting_rule.saved',
userId: 'b264d83a-9000-426a-85ec-3f9c20f368ce',
properties: {
projectId: '3675b69e-8324-4110-bdca-059031aa8da3',
organizationId: '172a2270-000f-42be-9c68-c4752c23ae51',
savedQueryId: '2a229b98-5db8-441c-858d-46ad08ebc229',
type: 'single color',
numConditions: 2
}
},
{
event: 'conditional_formatting_rule.saved',
userId: 'b264d83a-9000-426a-85ec-3f9c20f368ce',
properties: {
projectId: '3675b69e-8324-4110-bdca-059031aa8da3',
organizationId: '172a2270-000f-42be-9c68-c4752c23ae51',
savedQueryId: '2a229b98-5db8-441c-858d-46ad08ebc229',
type: 'color range',
numConditions: 1
}
}
]
```
> feat: conditional formatting analytics events

- packages/frontend/package.json
- packages/frontend/src/components/SimplePieChart/PieChartContextMenu.tsx
- packages/frontend/src/components/SimplePieChart/index.tsx
- packages/frontend/src/hooks/echarts/useEchartsPieChart.ts
- packages/frontend/src/hooks/usePieChartConfig.ts
- yarn.lock
related to: https://github.com/lightdash/lightdash/issues/6154
all todos will be removed in follow-up PRs
https://github.com/lightdash/lightdash/assets/962095/ae24c93e-f693-4f4a-be63-6670e3cc05be
> feat: pie charts menu with copy

- packages/frontend/src/components/common/Filters/renderFilterItem.tsx
- packages/frontend/src/components/common/Filters/renderFilterList.tsx
Closes: #6299
Re-adds: https://github.com/lightdash/lightdash/pull/6077
But also reduces duplicate code through abstraction; 
Also, add a `500`ms delay to tooltip
Dashboard filters
https://github.com/lightdash/lightdash/assets/7611706/1c163b10-a85a-4be9-9598-b8ee0473fc0b
Chart filters
https://github.com/lightdash/lightdash/assets/7611706/ef34d27e-a6dd-4a1b-ae28-d944e572e4d1
> feat: show tooltip on hover of fields in filter list

- packages/frontend/src/components/NavBar/index.tsx
- packages/frontend/src/pages/SavedExplorer.tsx
Closes: #6243 
https://github.com/lightdash/lightdash/assets/9117144/ec91fb41-c1c5-471a-9d14-7d0b22df457f
> feat: show dashboard banner when editing chart that belongs to dashboard

- packages/frontend/src/components/NavBar/ProjectSwitcher.tsx
Closes: https://github.com/lightdash/lightdash/issues/5802
> fix: onboarding project switcher

- docs/docs/self-host/customize-deployment/configure-lightdash-to-use-external-object-storage.mdx
It took me some time to understand timeouts in s3 signed urls, so just adding couple of lines that might save someone time in the future 🙌
Related slack [thread](https://lightdash-community.slack.com/archives/C03MG2VTR08/p1690268551008219).
> docs: Add clarification to docs

- packages/backend/src/database/seeds/development/03_saved_dashboards.ts
Closes: #6552 
Changes:
- use correct tile type
- add specific chart to the dashboard
- remove `title` property since it is now optional and fallbacks to chart name
> chore: seed dashboard with correct charts

- packages/frontend/src/components/DashboardTiles/AddTileButton.tsx
- packages/frontend/src/pages/Dashboard.tsx
- packages/frontend/src/providers/DashboardProvider.tsx
Closes: #6508 
https://github.com/lightdash/lightdash/assets/67699259/9846a75a-2125-4e3c-ae03-0776e3289fa3
> fix: keep unsaved filters when creating a chart in dash

- packages/common/src/utils/conditionalFormatting.ts
Closes: N/A
remove unused `isMetric` import
> chore: remove isMetric reference

- .env.development
Closes: [#6561](https://github.com/lightdash/lightdash/issues/6561)
> chore: set rudderstack development env vars

- packages/backend/src/index.ts
- packages/backend/src/nodeMetrics.ts
- packages/backend/src/otel.ts
- packages/backend/src/scheduler/SchedulerWorker.ts
- improve description on `worker.task.duration` histogram
- add event loop metric
- add `envDetector` to otel node sdk
> feat: add event loop delay otel metric

- packages/common/src/compiler/exploreCompiler.test.ts
- packages/common/src/compiler/exploreCompiler.ts
Closes:  #6589
Setup 
Before: 
After:
> fix: fix lightdash variable prefix

- packages/frontend/package.json
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterSettings.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
- packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLine.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/UnitOfTimeAutoComplete.tsx
- packages/frontend/src/components/common/MonthAndYearInput.tsx
- packages/frontend/src/components/common/WeekPicker.tsx
- packages/frontend/src/components/common/YearInput.tsx
- yarn.lock
> fix: ability to have empty values in date inputs

- packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterSettings.tsx
Closes: #6379 
https://github.com/lightdash/lightdash/assets/7611706/a2f20b01-b8e2-4256-a567-13046f68f2a6
> feat: update label behaviour on dashboard filters

- packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterSettings.tsx
Closes: #6606 
wrap `Switch` in `div` so that tooltip works: https://github.com/mantinedev/mantine/issues/3518
https://github.com/lightdash/lightdash/assets/7611706/e44a2a35-cfa2-4b83-89f9-ad1f89e63b2a
> feat: add tooltip to switch on dashboard filter

- docs/docs/references/joins.md
- docs/docs/references/sql-variables.mdx
- docs/docs/references/tables.mdx
- docs/docs/references/user-attributes.mdx
- docs/sidebars.js
> docs: add user attributes reference

- packages/e2e/cypress/e2e/dashboard.cy.ts
- packages/frontend/src/components/DashboardTiles/AddTileButton.tsx
Closes: [#6505](https://github.com/lightdash/lightdash/issues/6505)
Changes:
- remove feature flag, so everyone can create charts in dashboards
- update e2e test to create chart in dashboard
> feat: allow charts to be created in dashboards

- packages/frontend/src/hooks/useSavedQuery.ts
- packages/frontend/src/pages/Dashboard.tsx
Closes: [#6591](https://github.com/lightdash/lightdash/issues/6591) 
https://github.com/lightdash/lightdash/assets/9117144/f3119317-e42f-4dd5-8929-a9a0583cb382
> fix: delete orphan charts on dashboard cancel

- render.yaml
Closes: 
Render has been having issues with the Oregon region for the past week. Changing region to see if this unblock us and we can run e2e tests for our PRs
https://status.render.com/
> chore: change render region for database and services

- docs/docs/references/filters.md
- docs/docs/references/metrics.mdx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterSettings.tsx
- packages/frontend/src/components/common/Filters/configs.ts
Closes: #6372
Replace component with mantine's `Select`
Change Filter label copy: 
* `is equal to` -> `is`
* `is not equal to` -> `is not`
https://github.com/lightdash/lightdash/assets/7611706/81cd7d19-70df-408c-be1a-8399abf53b0a
> feat: update filter operator dropdown

- packages/frontend/src/components/LightdashVisualization/index.tsx
- packages/frontend/src/components/SimplePieChart/PieChartContextMenu.tsx
- packages/frontend/src/components/SimpleStatistic/BigNumberContextMenu.tsx
- packages/frontend/src/components/SimpleStatistic/BigNumberDashboardContextMenu.tsx
- packages/frontend/src/components/SimpleStatistic/index.tsx
Closes: #6396 
:warning: if you just wanna review dashboard filter logic and skip mantine menu - then have a look to this commit only
[fix: big number + underlying values + dashboard filters](https://github.com/lightdash/lightdash/pull/6659/commits/48b711137e1a5f10d7dee8e1e423a3976c36711e)
https://github.com/lightdash/lightdash/assets/962095/83a11417-3988-4584-94e2-92b2805c1224
> fix: big number dashboard filters + underlying data

- packages/e2e/cypress/e2e/userAttributes.cy.ts
Closes: #6653
[Screencast from 11-08-23 11:22:15.webm](https://github.com/lightdash/lightdash/assets/1983672/96c21c76-4b59-4a82-999f-c99641252e28)
> test: add e2e test for column level security

- packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterSettings.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
Closes: #6718 
Style improvements to Dashboard filters
> feat: dashboard filter style updates

- packages/backend/src/models/ProjectModel/ProjectModel.ts
> fix: stringify additional metrics filters on copy

- packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilter.tsx
Closes: #6687 
Adds some spacing to the filter button list
> fix: filter button spacing

- packages/frontend/src/components/MetricQueryData/DrillDownMenuItem.tsx
- packages/frontend/src/components/MetricQueryData/MetricQueryDataProvider.tsx
- packages/frontend/src/components/SimplePieChart/PieChartContextMenu.tsx
- packages/frontend/src/components/SimpleStatistic/BigNumberContextMenu.tsx
- packages/frontend/src/components/common/PivotTable/ValueCellMenu.tsx
Closes: N/A
Fix typo in `openDrillDownModal`
> chore: fix drill down modal typo

- packages/backend/src/clients/Google/GoogleDriveClient.ts
Closes: https://github.com/lightdash/lightdash/issues/6757
Combines all diffferent PRs and apply typescript library and fix some typing bugs
> fix: google sheet typescript

- packages/frontend/src/components/common/modal/MoveChartThatBelongsToDashboardModal.tsx
Closes: N/A
Make UI layout changes when moving a chart that was created withing a dashboard to a space
Before
After
> style: make changes to move chart that belongs to dashboard modal

- packages/frontend/src/components/ProjectConnection/index.tsx
Closes: #6774
Get DBT version from form selected input when creating a new connection.
> fix: get dbtVersion when creating new connection

- packages/frontend/src/components/ProjectConnection/index.tsx
This PR closes one task (i.e general settings) defined in the issue #5402
> feat: Migrate general settings forms to use Mantine

- packages/frontend/src/components/DashboardFilter/FilterConfiguration/TileFilterConfiguration.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
Closes: #6772 
These borders were a little too light because they were a little too thin. Radius was also a little small.
> fix: fix filter input border style

- docs/docs/self-host/customize-deployment/use-sso-login-for-self-hosted-lightdash.mdx
Updates docs based on @rephus recent changes to auth env vars
> docs: document new google env vars

- packages/cli/src/dbt/models.ts
- packages/cli/src/handlers/dbt/compile.ts
- packages/cli/src/handlers/generate.ts
- packages/cli/src/index.ts
- packages/e2e/cypress/cli/cli.cy.ts
🔍 exploring 🔍 
Closes: https://github.com/lightdash/lightdash/issues/6655
delegating --select and --explore to dbt instead of figuring out model dependencies ourselves
> feat: generate with dbt compatible --select and --exclude

- packages/frontend/src/components/SchedulersView/SchedulersView.tsx
- packages/frontend/src/components/SchedulersView/SchedulersViewUtils.tsx
> feat: gsheet on scheduler dashboard

- packages/frontend/src/components/DashboardFilter/FilterConfiguration/TileFilterConfiguration.tsx
- packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
Closes: #6789
Closes: #6788
select all/deselect state was not syncing with actual draft state
while `useListState` is a great tool to manage list states - in this case it was just mirroring already existing state inside dashboard context
see a bug videos in the issues linked above
here's a fixed version
https://github.com/lightdash/lightdash/assets/962095/1c9a5e44-9373-41b9-af54-5b0835dcd157
> fix: dashboard filters tile settings select all

- packages/backend/package.json
- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/clients/Google/GoogleDriveClient.ts
- packages/backend/src/scheduler/README.md
- packages/backend/src/scheduler/SchedulerClient.ts
- packages/backend/src/scheduler/SchedulerTask.ts
- packages/backend/src/scheduler/SchedulerWorker.ts
- packages/backend/src/services/CsvService/CsvService.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/common/src/types/scheduler.ts
> fix: upload gsheet content from rows instead of csv

- packages/backend/src/services/ProjectService/ProjectService.ts
> fix: compile correct project settings on project update

- packages/backend/src/clients/Google/GoogleDriveClient.ts
- packages/backend/src/scheduler/SchedulerTask.ts
Closes: #6765
On charts
On dashboards
> feat: metadata tab

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/controllers/userAttributesController.ts
- packages/backend/src/services/UserAttributesService/UserAttributesService.ts
Closes: #6819 
```
organization_id
user_id
```
timestamp
```
user_id - user who created the attribute
organization_id
attribute_id - unique ID for the user attribute (unique across all orgs)
name - name of the attribute
description - description of the attribute
values -this is a json blob which has {user_id: [user_1, user_2, user_3, etc.], value: [value_for_user_1, value_for_user_2, etc.]}
```
```
user_id - user who updated the attribute
attribute_id - unique ID for the user attribute (unique across all orgs)
organization_id
name - name of the attribute
description - description of the attribute
values -this is a json blob which has {user_id: [user_1, user_2, user_3, etc.], value: [value_for_user_1, value_for_user_2, etc.]}
```
```
user_id - user who deleted the attribute
attribute_id - …
```
> chore: user attribute analytic events

- docs/package.json
- docs/yarn.lock
Related to: #6621
Updated all possible dependencies for the docs website.
> chore: update docs dependencies

- packages/frontend/src/components/DashboardFilter/Filter.tsx
Closes: #6851 
This PR fixes the uneven spacing between actual filters and add filters button.
PFA screenshot.
> fix: uneven spacing between add filters and filters in dashboard

- .gitpod.Dockerfile
- .gitpod.yml
- scripts/reset-db.sh
adds a gitpod config to enable dev environments with gitpod
You can launch a new workspace for this branch here: https://gitpod.io/projects/lightdash/prebuilds
(ask me for invite)
> chore: add gitpod configuration

- packages/backend/src/database/entities/savedCharts.ts
- packages/backend/src/database/migrations/20230829123133_add_additional_metrics_percentile_column.ts
- packages/backend/src/models/SavedChartModel.ts
- packages/frontend/src/components/Explorer/CustomMetricModal/index.tsx
Closes: #6904 
https://github.com/lightdash/lightdash/assets/962095/ca0334f0-68a5-4cc4-bc42-0a119d03cf0a
> fix: custom metrics percentile

- packages/frontend/src/components/SchedulersView/SchedulersViewUtils.tsx
Closes: https://github.com/lightdash/lightdash/issues/6849
- Change scheduler time format to 12 H
- Using dayjs as https://github.com/lightdash/lightdash/issues/6129 is already open
> fix: change scheduler time format to 12H and use dayjs

- packages/frontend/src/components/ReactHookForm/CronInput/CronInput.styles.ts
- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulerForm.tsx
Relates to: #6864 
Ahead of the work on #6864 , remove google sheets first from scheduled deliveries, and then create separate modal & interactions for `Sync` feature with Google Sheets Integration. 
Most of the code will be reused in the new component, so this will be used as a reference soon
Feature and reused code in: #6938
> chore: remove google sheets from scheduled deliveries

- docs/docs/references/roles.mdx
Relates to: #6945 & #6946
Update roles section
> docs: add new points for google-sheets-related actions

- packages/frontend/src/hooks/scheduler/useSchedulersDeleteMutation.ts
Closes: N/A
small copy typo when deleting scheduled deliveries
> chore: fix small copy typo

- .github/workflows/cli-tests.yml
- dockerfile
- dockerfile-prs
- packages/backend/src/dbt/dbtCliClient.ts
- packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts
- packages/cli/src/dbt/manifest.ts
- packages/cli/src/handlers/compile.ts
- packages/cli/src/handlers/dbt/getDbtVersion.ts
- packages/common/src/dbt/schemas/lightdashV10.json
- packages/common/src/dbt/schemas/manifestV10.json
- packages/common/src/dbt/validation.ts
- packages/common/src/types/dbt.ts
- packages/common/src/types/projects.ts
Closes: #6925
Changes:
- update docker to install dbt 1.6
- add support for dbt 1.6 + manifest v10 when compiling project via CLI or the APP
- this PR doesn't provide support for metricflow so we are ignore the metrics from the manifest
- update cli tests
> feat: dbt 1.6

- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
- packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx
Closes: #6951 
As part of this PR, have changed few icons that were described in the issue. Have attached screenshots as well.
> fix: update tabler icons for add to dashboard and unpin from homepage

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/scheduler/SchedulerTask.ts
- packages/backend/src/services/GdriveService/GdriveService.ts
- packages/common/src/types/gdrive.ts
Closes: #6812 
Add `download_results.x` events when a user exports with google sheets
> chore: add analytics events for export to google sheets results

- docs/docs/references/metrics.mdx
Updates metric filter docs to include the fact that filters can't be used with non-aggregate metrics
> docs: updates filters docs for non-aggregate metrics

- packages/e2e/cypress/e2e/login.cy.ts
Closes: N/A
Merge 2 tests in `login.cy.ts` into one and remove unnecessary commented out test
> chore: merge 2 login tests into one

- packages/frontend/src/features/sync/components/SyncModalView.tsx
Closes: N/A
Improve empty-state copy for Syncs Modal view
> chore: improve syncs empty state copy

- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes:  #6947
Before:
[Screencast from 04-09-23 09:09:38.webm](https://github.com/lightdash/lightdash/assets/1983672/3033a427-aaad-4f55-b285-97789a80d8ec)
AFter:
[Screencast from 04-09-23 09:09:07.webm](https://github.com/lightdash/lightdash/assets/1983672/a9c5b6c9-ffe8-499e-aaa5-876a738e4e6c)
> fix: fix total right axis

- packages/e2e/cypress/e2e/dashboard.cy.ts
- packages/frontend/src/components/DashboardTiles/AddTileButton.tsx
Re-enables charts in dashboards. It's in better shape now.
> fix: remove feature flag for charts in dashboards

- packages/backend/src/routers/dashboardRouter.ts
- packages/backend/src/services/UnfurlService/UnfurlService.ts
- packages/frontend/src/hooks/dashboard/useDashboard.tsx
- packages/frontend/src/pages/Dashboard.tsx
Closes: #6906
Closes: #6546
Before
[Screencast from 01-09-23 17:51:24.webm](https://github.com/lightdash/lightdash/assets/1983672/6fd3c2de-c215-41de-9ccb-a5541ac1326d)
After:
[Screencast from 01-09-23 17:52:18.webm](https://github.com/lightdash/lightdash/assets/1983672/5df9e020-7867-48d2-a279-53e2284cb1e2)
> fix: export dashboard with temporary filters

- packages/frontend/src/components/SettingsValidator/ValidatorTable/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/6981
removes unnecessary anchor inside first td
> fix: validator item opens two tabs

- packages/cli/src/analytics/analytics.ts
- packages/cli/src/handlers/compile.ts
Closes: #6916 
Help us understand how many users are using dbt metrics and what version they are using.
> chore: add dbt version and dbt metrics count to compile events

- packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx
Closes: https://github.com/lightdash/lightdash/issues/6996
- if there are admin visible spaces <img width="617" alt="CleanShot 2023-09-04 at 16 55 35@2x" src="https://github.com/lightdash/lightdash/assets/962095/13a8473d-79b3-4306-bc4d-ca1bd5c7eb0f">
- if there are no admin visible spaces
> feat: resource view move to space sections

- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/common/src/compiler/filtersCompiler.ts
- packages/common/src/index.ts
- packages/common/src/types/dbt.ts
- packages/common/src/types/field.ts
- packages/common/src/types/metricQuery.ts
- packages/common/src/types/timeFrames.ts
- packages/common/src/utils/additionalMetrics.ts
- packages/common/src/utils/filters.ts
- packages/common/src/utils/formatting.ts
- packages/frontend/src/components/Explorer/CustomMetricModal/index.tsx
- packages/frontend/src/components/Explorer/CustomMetricModal/utils/index.ts
- packages/frontend/src/components/common/Filters/FieldIcon.tsx
- packages/frontend/src/hooks/echarts/useEcharts.ts
- packages/frontend/src/utils/sortUtils.ts
- packages/warehouses/src/utils/sql.ts
Closes: https://github.com/lightdash/lightdash/issues/6843
respect date formatting of the base dimension in additional metrics.
> fix: additional metric date formatting

- packages/frontend/package.json
- packages/frontend/src/features/metricFlow/components/MetricFlowSqlCard.tsx
- packages/frontend/src/features/metricFlow/components/MetricFlowSqlCode.tsx
- packages/frontend/src/pages/MetricFlow.tsx
- yarn.lock
Changes:
Add SQL card so people can inspect the generated SQL and be able to open the SQL runner page so they can edit the SQL.
Add a beta badge so users are aware this feature is unstable.
> feat: show MetricFlow SQL

- packages/frontend/src/components/Explorer/ExportGsheets/index.tsx
- packages/frontend/src/features/sync/components/SelectGoogleSheetButton.tsx
- packages/frontend/src/hooks/gdrive/useGdrive.ts
Closes: N/A
Move auth logic, and refetching of the access token to `useGDriveAccessToken` hook.
> refactor: handle google auth and access token in useGDriveAccessToken hook

- packages/backend/src/generated/swagger.json
- packages/backend/src/routers/apiV1Router.ts
> feat: change gdrive scope

- packages/backend/src/clients/Google/GoogleDriveClient.ts
> fix: fix gsheet add tab error

- packages/backend/src/controllers/projectController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/models/ProjectModel/ProjectModel.ts
- packages/e2e/cypress/e2e/api/projectPermissions.cy.ts
Closes: https://github.com/lightdash/lightdash/issues/7107
Changes:
- fix path
- fix sql filter
- add API tests
> fix(api): get project member access

- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulerForm.tsx
Closes: #6678
UI for choosing to send a PDF in a scheduled delivery. Backend is already checked in. 
I followed the existing pattern in this form, but I don't really like the way we are integrating with useForm. We could make this better.
> feat: UI for pdf image delivery option

- docker-compose.yml
- docker/docker-compose.dev.yml
Closes: https://github.com/lightdash/lightdash/issues/7101
Let's fix this before more users complain about this (install is currently broken)
> fix: pin postgres 15.4 version on docker-compose

- docs/docs/self-host/customize-deployment/configure-logging-for-lightdash.mdx
- docs/docs/self-host/customize-deployment/environment-variables.mdx
> docs: amend typo for LIGHTDASH_LOG_LEVEL env

- docs/docs/references/joins.md
Updates joins docs to include a reference to the `fields` parameter in the main example
> docs: updates joins docs to include fields reference

- packages/frontend/src/components/SettingsValidator/ValidatorTable/ErrorMessage.tsx
- packages/frontend/src/components/SettingsValidator/ValidatorTable/index.tsx
- packages/frontend/src/components/SettingsValidator/index.tsx
- packages/frontend/src/hooks/styles/useTableStyles.tsx
Closes: #6995 
Fixed validator table UI issues
@IrakliJani Can you please explain the 3rd pointer, how is the content not proportional, and what is the desired ui? I'll make the changes to fix that issue and push it
> fix: validator table ui issues

- packages/backend/src/models/SavedChartModel.ts
Related to: #7058 
Executes the following queries in parallel when getting a Saved Chart:
* Fields
* Sorts
* Table Calculations
* Additional Metrics
> chore: use promiseAll for some queries in saved chart get

- packages/backend/src/services/UnfurlService/UnfurlService.ts
Closes: #7137
Thread: https://lightdash.slack.com/archives/C05RPGL10F2/p1695149317578389
Before:
[slack-image-notification-3cNFcfiJHYuNuT0EA7lQF.pdf](https://github.com/lightdash/lightdash/files/12670813/slack-image-notification-3cNFcfiJHYuNuT0EA7lQF.pdf)
Now (with wider charts):
[slack-image-notification-p079bd4iVpToPisAH0ZAd.pdf](https://github.com/lightdash/lightdash/files/12670819/slack-image-notification-p079bd4iVpToPisAH0ZAd.pdf)
> fix: fix pdf attachment resolution

- packages/backend/package.json
- packages/backend/src/services/UnfurlService/UnfurlService.ts
- packages/frontend/src/components/SimpleChart/index.tsx
- packages/frontend/src/components/SimplePieChart/index.tsx
- yarn.lock
Closes: #6932
:point_up: this PR might not close the issue, because we can't replicate, but it will fix one possible cause. We'll have to wait until we can replicate this again, and see the stats on grafana.
Before:
After:
> fix: wait until all charts finish loading before taking screenshot

- packages/frontend/src/components/ProjectConnection/WarehouseForms/DatabricksForm.tsx
Closes: This PR closes one task from Warehouse connection (i.e Databricks) defined in the issue #5402
Updating Databricks defined in WarehouseConnection inside Project Settings
> feat: migrate Databricks settings forms to use Mantine

- packages/backend/src/models/ProjectModel/ProjectModel.ts
Closes: #7040 
Main project
Preview
> fix: copy dashboard filters to preview

- packages/backend/src/controllers/organizationController.ts
- packages/backend/src/controllers/userController.ts
- packages/backend/src/generated/swagger.json
Closes: #7183 
Enables api-key auth for deleting users.
Tested with Postman:
> feat: enable api-key auth for deleting users

- packages/frontend/src/components/SimpleChart/index.tsx
- packages/frontend/src/components/SimplePieChart/index.tsx
Closes: N/A
Rename `Loading simple chart` spinner to `Loading chart`
> chore: rename loading chart title

- .github/CONTRIBUTING.md
> docs: how to run headless browser locally

- packages/backend/package.json
- packages/backend/src/index.ts
- packages/frontend/package.json
- packages/frontend/vite.config.ts
- yarn.lock
Closes: #7097 
Duplicate of #7188
> chore: compress vite assets and serve them

- packages/backend/package.json
- packages/backend/src/index.ts
- packages/frontend/package.json
- packages/frontend/vite.config.ts
- yarn.lock
Closes: #7097 
tested on `alpha`, #7188 - ready to merge
> fix: compress static assets and serve

- .github/stale.yml
> chore: increase days until stale

- packages/e2e/cypress/e2e/app/createProjects.cy.ts
- packages/e2e/cypress/support/commands.ts
- packages/frontend/src/components/ProjectConnection/DbtForms/GithubForm.tsx
- packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx
Closes: This PR closes one task from dbt connection (i.e Github) defined in the issue #5402 
Updating Github form defined in dbt connection inside Project Settings
> feat: migrate dbt connection Github forms to use mantine

- packages/frontend/src/components/ProjectConnection/DbtForms/GitlabForm.tsx
Closes: This PR closes one task from dbt connection (i.e Gitlab) defined in the issue #5402 
Updating Gitlab form defined in dbt connection inside Project Settings
> feat: migrate Gitlab forms to use mantine

- packages/frontend/src/components/ProjectConnection/DbtForms/BitBucketForm.tsx
Closes: This PR closes one task from dbt connection (i.e BitBucket) defined in the issue #5402 
Updating BitBucket form defined in dbt connection inside Project Settings
> feat: migrate Bitbucket forms to use mantine

- packages/backend/src/index.ts
remove `setHeaders` call and verify
> fix: add last implementation of express-static-gzip

- packages/backend/src/models/SavedChartModel.ts
Closes: N/A
There was a `limit` applied to this query so it was only getting the `availableFilters` for one chart in a dashboard. 
This now fixes it and subqueries the latest version per chart 
Fixes broken change introduced in: https://github.com/lightdash/lightdash/pull/7132/files#r1337073050
> fix: remove limit and get all available filters per chart

- packages/cli/package.json
- packages/cli/src/handlers/preview.ts
- yarn.lock
Closes: #7235 
fixes typo ^^ in the above ticket 
uses https://www.npmjs.com/package/@actions/core package
> feat: cli to use github actions core package

- packages/frontend/src/components/ProjectConnection/DbtForms/AzureDevOpsForm.tsx
Closes: This PR closes one task from dbt connection (i.e AzureDevOps) defined in the issue #5402 
Updating AzureDevOps form defined in dbt connection inside Project Settings
> feat: migrate AzureDevOps forms to use mantine

- packages/frontend/src/components/ProjectConnection/DbtForms/DbtNoneForm.tsx
Closes: #5402 
Updating CLI form defined in dbt connection inside Project Settings
> feat: migrate CLI to use mantine

- packages/frontend/src/components/common/Filters/FilterInputs/BooleanFilterInputs.tsx
Closes:  #6727
Migrate Boolean Filter input to Mantine
https://github.com/lightdash/lightdash/assets/113882904/4163fa79-a181-4500-9203-9997162b7e54
> feat: Migrate Boolean Filter input to Mantine

- packages/backend/src/models/UserAttributesModel.mock.ts
- packages/backend/src/models/UserAttributesModel.test.ts
- packages/backend/src/models/UserAttributesModel.ts
- packages/backend/src/queryBuilder.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/backend/src/services/UserAttributesService/UserAttributeUtils.ts
- packages/common/src/types/userAttributes.ts
Follow up from https://github.com/lightdash/lightdash/pull/7232 review.
Changes:
- improve typing
- improve logic
- add unit test
> chore: improve typing, test coverage, performance of org member attributes values

- docs/docs/references/dimensions.mdx
Updates dimension reference doc to include .yml snippets for each configuration block.
> docs: Update dimensions.mdx

- packages/backend/src/clients/dbtCloud/DbtCloudGraphqlClient.ts
> fix: update semantic layer API hostname

- packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulerForm.tsx
> chore: change to 'customize body message'

- packages/backend/src/controllers/savedChartController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/models/SavedChartModel.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/backend/src/services/SavedChartsService/SavedChartService.ts
- packages/common/src/index.ts
- packages/common/src/types/savedCharts.ts
- packages/frontend/src/Routes.tsx
- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
- packages/frontend/src/components/Explorer/index.tsx
- packages/frontend/src/hooks/useQueryResults.tsx
- packages/frontend/src/hooks/useSavedQuery.ts
- packages/frontend/src/pages/ChartHistory.tsx
- packages/frontend/src/providers/ExplorerProvider.tsx
- packages/frontend/src/types/Events.ts
Closes: #7271 
Changes
- Add 3 endpoints
- get chart history
- get chart version
- get query results for chart version
- Add /history page that uses the new endpoints
Following PR:
- add analytics
- rollback option
Preview:
https://github.com/lightdash/lightdash/assets/9117144/624f65e7-82e5-4676-8e7b-900a15782e23
> feat: chart history

- packages/frontend/src/components/ProjectConnection/ProjectStatusCallout.tsx
- packages/frontend/src/hooks/toaster/useToaster.tsx
> style: fix toaster styling

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/controllers/savedChartController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/models/SavedChartModel.ts
- packages/backend/src/services/SavedChartsService/SavedChartService.ts
- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
- packages/frontend/src/hooks/useSavedQuery.ts
- packages/frontend/src/pages/ChartHistory.tsx
Closes: 
Changes:
- add endpoint to rollback ( service creates a new version as if the user was updating the chart in the UI )
- add current label
- add options menu with rollback option + modal
https://github.com/lightdash/lightdash/assets/9117144/f9cac8c2-8bec-4ed9-b9d2-36f180e115fb
> feat: chart rollback

- docs/docs/self-host/lightdash-cloud-vs-self-hosted.mdx
Closes: 
(no bug filed)
Minor typo in the word "translate".  👍
> docs: fixes typo in docs

- packages/backend/src/services/CsvService/CsvService.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/common/src/utils/filters.ts
- packages/frontend/src/hooks/dashboard/useSavedQueryWithDashboardFilters.ts
Closes: https://github.com/lightdash/lightdash/issues/7246
extracts filter combinators to common/filter/utils and reuses them in fe/be
> chore: reuse combine filters

- packages/frontend/src/components/SimpleChart/index.tsx
- packages/frontend/src/hooks/echarts/useEcharts.ts
Closes: #6547 #6283
This PR changes the following: 
- on hover of a highlighted item, change `tooltip` `trigger` from `axis` to `item`, getting a focused view of the data
- move the non-null values to the top of the tooltip list
https://github.com/lightdash/lightdash/assets/7611706/31412ffc-8f7a-43a5-91cb-d94fb97ddcd7
> fix: change series tooltip and improve ux

- packages/e2e/cypress/e2e/app/savedDashboards.cy.ts
- packages/frontend/src/components/NavBar/ExploreMenu.tsx
- packages/frontend/src/components/common/modal/DashboardCreateModal.tsx
- packages/frontend/src/pages/SavedDashboards.tsx
- packages/frontend/src/pages/Space.tsx
Closes: N/A
Migrate modal to mantine
https://github.com/lightdash/lightdash/assets/7611706/83c4853f-b01c-4ec3-8e17-bfdb299d5b82
> feat: migrate create dashboard modal to mantine

- packages/warehouses/package.json
- yarn.lock
Closes: N/A
Fixes snowflake query failures after node 20 upgrade. 
Relevant GitHub issue: https://github.com/snowflakedb/snowflake-connector-nodejs/issues/588
Same error seen on our pods ^
> fix: upgrade snowflake-sdk to 1.9.0

- packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNodeActions.tsx
Closes: #7281 
Create submenu for custom metrics options instead of a long list
https://github.com/lightdash/lightdash/assets/7611706/a80b2fb7-8cbb-45dc-a3f7-c6aba51fdfd6
> feat: create submenu for custom metrics options

- packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx
Closes: #7310 
Add overflow Y `auto` and max height to nested menu when `moving to space`
Screen recording with duplicate data
https://github.com/lightdash/lightdash/assets/7611706/b0676d64-0137-4ab1-80a6-6b063793d240
> fix: add overflowY auto and max height

- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/common/src/types/space.ts
- packages/frontend/src/components/common/SpaceActionModal/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/7299
We pass an array of user UUIDs. We drop the parameters about project roles, first names and last names of users.
> fix: Improve the `access` parameter of `CreateSpaceInProject`

- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/UnitOfTimeAutoComplete.tsx
Closes: #7312 
Closes: https://github.com/lightdash/lightdash/issues/7315
> feat: unit of time inputs to mantine

- packages/warehouses/src/ssh/sshTunnel.ts
Improve observability for SSH connections for a user who is experiencing Lightdash connecting to random ports on their bastion host.
> fix: improve logging on ssh tunnel connections

- packages/frontend/src/features/metricFlow/hooks/useMetricFlowVisualization.ts
- packages/frontend/src/pages/MetricFlow.tsx
Closes: https://github.com/lightdash/lightdash/issues/7368
You can test it here: https://lightdash-pr-7367.onrender.com/projects/3675b69e-8324-4110-bdca-059031aa8da3/dbtsemanticlayer
> feat: enable big value viz on dbt semantic layer

- packages/frontend/src/components/RefreshButton.tsx
- packages/frontend/src/components/SqlRunner/RunSqlQueryButton.tsx
> fix: Migrate blueprint <KeyCombo> to mantine

- packages/backend/src/config/parseConfig.ts
- packages/backend/src/models/ProjectModel/ProjectModel.mock.ts
- packages/backend/src/services/HealthService/HealthService.mock.ts
- packages/backend/src/services/HealthService/HealthService.ts
- packages/common/src/index.ts
- packages/frontend/package.json
- packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
- packages/frontend/src/components/NavBar/UserMenu.tsx
- packages/frontend/src/components/NavBar/index.tsx
- packages/frontend/src/components/ReactHookForm/PasswordInput.tsx
- packages/frontend/src/components/UserSettings/AccessTokensPanel/CreateTokenModal.tsx
- packages/frontend/src/components/UserSettings/UserManagementPanel/InviteSuccess.tsx
- packages/frontend/src/components/common/Table/index.tsx
- packages/frontend/src/hooks/user/useUserLogoutMutation.ts
- packages/frontend/src/pages/MetricFlow.tsx
- packages/frontend/src/pages/MinimalSavedExplorer.tsx
- packages/frontend/src/pages/SqlRunner.tsx
- packages/frontend/src/providers/ThirdPartyServicesProvider.tsx
- yarn.lock
Features:
- don't identify opt-out users
- events are anonymous before signin/register
- anonymous events before sign-in are attributed to user after sign-in
- new session begins with new anonymous user after sign-out
- sensitive components masked
- users are assigned to groups
- use react library for posthog provider
- use react library for feature flags
Also see issue: https://github.com/lightdash/lightdash-internal-work/issues/961
> feat: add posthog

- packages/backend/src/database/seeds/development/02_saved_queries.ts
Closes: 
I coded 2 new sample charts for pivot tables and pie charts.
> chore: new chart type samples

- packages/backend/src/models/SpaceModel.ts
> chore: name join function

- packages/frontend/src/components/DbtCloudSettings/index.tsx
- packages/frontend/src/pages/Settings.tsx
Closes: #7398
Changes:
- update sidebar menu
- disable inputs and buttons
- replace labels and descriptions
> fix: disable dbt semantic layer settings page

- packages/common/src/types/scheduler.ts
- packages/frontend/src/features/scheduler/components/SchedulerForm2.tsx
Closes: #7388 
Add validation to scheduled deliveries form. There might be more we can do here, but these are what is clearly needed. 
- Require name
- Require custom limit when limit is chosen
- Enforce custom limit is an integer
- Enforce emails are emails
> chore: scheduled deliveries form validation

- packages/cli/src/handlers/preview.ts
Closes: #7113 
Straightforward. Seems to me this is only required for `lightdash preview`, thus the local scope of changes.
Let me know if this works :)
> fix: delete preview project on SIGINT

- packages/backend/src/models/AnalyticsModel.ts
- packages/backend/src/models/AnalyticsModelSql.ts
- packages/common/src/types/analytics.ts
- packages/frontend/src/pages/UserActivity.styles.ts
- packages/frontend/src/pages/UserActivity.tsx
- packages/frontend/src/providers/ThirdPartyServicesProvider.tsx
> feat: add new user activity charts

- packages/backend/src/models/SavedChartModel.ts
Closes: #7306
Before:
With fix:
( still filters older versions )
> fix: always show current version in chart history

- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
- packages/frontend/src/providers/ThirdPartyServicesProvider.tsx
Closes: #7309 
- Add button to chart version history
- Only show if feature flag is true
> feat: chat history feature flag

- packages/frontend/src/components/RenderedSql.tsx
> fix: migrate SQL runner from blueprint to mantine

- packages/frontend/src/components/common/Filters/index.tsx
Closes: #7465 
https://github.com/lightdash/lightdash/assets/962095/890a7d5a-b74f-41a6-8efe-7e1d66960fe1
> fix: explore filters field select x button alignment

- packages/backend/src/scheduler/SchedulerClient.ts
- packages/common/src/types/scheduler.ts
> fix: google sheet delivery type error

- packages/frontend/src/components/common/Filters/SimplifiedFilterGroupForm.tsx
- packages/frontend/src/components/common/Filters/index.tsx
Relates to: #6337
- [✅] I have manually tested the changes in the preview environment
- [✅] I have reviewed the code
- [✅] I understand that "request changes" will block this PR from merging
> fix: Replace Tooltip2 with Mantine

- packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.styles.tsx
- packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx
- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
- packages/frontend/src/features/scheduler/components/SchedulersListItem.tsx
> fix: Replace Popover2 with Mantine (Column Header & scheduler)

- packages/backend/src/controllers/authentication.ts
- packages/backend/src/routers/apiV1Router.ts
- packages/frontend/src/components/common/ThirdPartySignInButton/index.tsx
Closes: #7404
It also works with redirection urls with many query arguments
[Screencast from 17-10-23 09:27:20.webm](https://github.com/lightdash/lightdash/assets/1983672/c249ff83-bc09-4ed4-999d-1f45aaeaa0ff)
> fix: google sso redirection

- packages/backend/src/services/ProjectService/ProjectService.ts
Closes: 
test-cli test-frontend test-backend
> fix: revert adapter destroy on finally

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/ProjectAccess/ProjectAccess.styles.ts
- packages/frontend/src/components/ProjectAccess/ProjectAccess.tsx
- packages/frontend/src/components/RefreshButton.tsx
- packages/frontend/src/components/SqlRunner/RunSqlQueryButton.tsx
- packages/frontend/src/components/SqlRunner/SqlRunnerInput.tsx
- packages/frontend/src/pages/SqlRunner.tsx
Relates to: https://github.com/lightdash/lightdash/issues/6337
> fix: Replace Tooltip2 with Mantine (not in tables)

- packages/frontend/src/components/DashboardTiles/AddTileButton.tsx
- packages/frontend/src/components/DashboardTiles/EmptyStateNoTiles/index.tsx
- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
Relates to: https://github.com/lightdash/lightdash/issues/6340
> fix: Replace Popover2 with Mantine (save chart header & Add tile button)

- packages/frontend/src/components/common/TagInput/TagInput.tsx
- packages/frontend/src/features/scheduler/components/SchedulerForm2.tsx
Closes: #7517 
Uses the new TagInput for emails in scheduled deliveries. Emails are validated and split on space and comma. I tested pasting in a comma separated list as well.
> chore: use TagInput for scheduled deliveries emails

- packages/backend/src/models/SavedChartModel.ts
> chore: name where function

- packages/frontend/src/features/scheduler/components/SchedulerModals.tsx
Switch to posthog feature flag for new scheduled deliveries
> chore: use posthog feature flag for scheduler

- docs/docs/guides/how-to-create-syncs.mdx
- packages/frontend/src/features/sync/components/SyncModalView.tsx
Closes: #7534 
Add Policy popover to Sync with Google Sheets modal
Add this same policy disclosure to our docs
https://github.com/lightdash/lightdash/assets/7611706/46fc7455-82e5-443c-b761-e09c5c1711e9
> feat: add google disclosure

- packages/backend/src/services/ProjectService/ProjectService.ts
> chore: wrap sentry transaction around both format rows functions

- packages/frontend/src/components/NavBar/index.tsx
- packages/frontend/src/providers/ThirdPartyServicesProvider.tsx
Closes: N/A
Remove Posthog banner now that we're all familiar with using Posthog + React
> chore: remove posthog test banner

- packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx
Closes: #7588
Can edit Custom Dimension on Results table:
> feat: can edit custom dimension on results table

- packages/common/src/types/metricQuery.ts
- packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLine.tsx
Closes: https://github.com/lightdash/lightdash/issues/7625
> fix: reference line undefined custom dimension

- packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx
Closes: N/A
Allow deleting a custom dimension on results table;
https://github.com/lightdash/lightdash/assets/7611706/f8612a9a-b73b-4019-a651-89de32376e33
> feat: allow deletion of custom dimension in results table

- docs/docs/self-host/self-host-lightdash-docker-compose.mdx
The existing `docker-compose` command in the docs fails.
Fix is to change the order in the command.
> docs: set correct order in `docker-compose` command

- packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/FieldLayoutOptions.tsx
Fixes an incorrect tooltip position.
> fix: incorrect tooltip position in config

- docs/docs/guides/version-history.mdx
- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
- packages/frontend/src/mantineTheme.ts
- packages/frontend/src/pages/ChartHistory.tsx
- packages/frontend/src/providers/ThirdPartyServicesProvider.tsx
> feat: chart version history

- packages/frontend/src/components/UserSettings/ProfilePanel/index.tsx
- packages/frontend/src/hooks/toaster/useToaster.tsx
- packages/frontend/src/providers/ErrorLogsProvider.tsx
duplicate: https://github.com/lightdash/lightdash/pull/7637
Closes: https://github.com/lightdash/lightdash/issues/7628
Thanks @iMac7 for the contribution ❤️  just made 2 small changes where we were overriding the error timeout.
> fix: increase error alert timeout to 1 minute

- packages/frontend/src/components/Explorer/CustomDimensionModal/index.tsx
> fix: error custom dimension start number

- .husky/pre-commit
- packages/backend/package.json
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/warehouses/package.json
- packages/warehouses/src/ssh/sshTunnel.ts
- packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
- yarn.lock
Closes: #7617
TL;DR it seems trying to run a postgres query with an active ssh connection while this is trying to reconnect, it is failing. 
I also upgraded pg libs
Original error: 
I fixed this by removing `reconnect` property from ssh 
Now we get the following (not server -killing error) : 
I think I also fixed one issue about PG :  capturing `connection terminated unexpectedly` from pg. This seems harder to replicate,so I'm not 100% I fixed this.
Related issues: https://github.com/brianc/node-postgres/issues/2283
I was killing my ssh periodically 
> while true; do sleep 3; sudo pkill ssh ; sudo service sshd restart ; sudo service ssh restart;  done
I was running queries periodically from terminal
> while true; do sleep 1 ; curl …
> fix: ssh reconnect

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/backend/src/services/SavedChartsService/SavedChartService.ts
- packages/common/src/types/metricQuery.ts
> chore: add analytics to custom dimensions

- packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNodeActions.tsx
- packages/frontend/src/providers/TrackingProvider.tsx
- packages/frontend/src/types/Events.ts
Closes:  #7675
[Screencast from 26-10-23 15:07:45.webm](https://github.com/lightdash/lightdash/assets/1983672/b8ea4d27-d56f-421c-bc1d-2142ac77ab44)
> fix: remove custom dimension submenu

- packages/common/src/dbt/schemas/manifestV10.json
Closes: 
Update outdated dbt json schema v10 from https://schemas.getdbt.com/
> fix: update outdated dbt json schema v10

- packages/backend/src/clients/Aws/s3.ts
Closes: N/A
Add endpoint log to s3 failed upload
> chore: add more logging info to s3 failed upload

- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/services/CsvService/CsvService.ts
> feat: add custom dimension to csv export

- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
- packages/frontend/src/components/common/Filters/FilterInputs/DateTimePicker.tsx
> feat: filter inputs - date time picker input to mantine

- packages/backend/src/clients/Aws/s3.ts
- packages/backend/src/clients/clients.ts
- packages/backend/src/config/parseConfig.ts
- packages/backend/src/scheduler/SchedulerTask.ts
- packages/backend/src/services/CsvService/CsvService.test.ts
- packages/backend/src/services/ProjectService/ProjectService.test.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/backend/src/services/services.ts
Closes: #7620 
Initial results cache work. Still in an experimental phase.
> feat: add results cache

- packages/backend/src/queryBuilder.test.ts
- packages/backend/src/queryBuilder.ts
> fix:  round float custom dimension

- packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
Fixes #7660 
The columns hidden in the UI were not used before to check for the columns to send to the api, which create the CSV. I have added the checks in the VisualizationCard.tsx itself and not in its state provider and I am not sure if this is the correct approach.
I have added the checks in the arguments provided to the downloadCSV() function to successfully download a CSV. 
Having a sort field that is not supposed to be present in the CSV breaks the downloading process, which makes me think there might be more edge cases involved. Please let me know if I missed some.
> fix: hidden columns in table appearing in downloaded csv

- packages/backend/src/clients/Aws/s3.ts
- packages/backend/src/clients/clients.ts
- packages/backend/src/scheduler/SchedulerTask.ts
- packages/backend/src/services/CsvService/CsvService.test.ts
- packages/backend/src/services/CsvService/CsvService.ts
- packages/backend/src/services/GdriveService/GdriveService.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/backend/src/services/UnfurlService/UnfurlService.ts
- packages/backend/src/services/services.ts
Closes: #7720 
Replace all mentions from S3Service to S3Client.
No logic change.
> chore: remove s3Service references

- packages/backend/src/services/DashboardService/DashboardService.ts
> fix: duplicated dashboard with filters

- packages/frontend/src/hooks/gdrive/useGdrive.ts
Closes: #7685
This PR fixes when I open the Google authentication window and then close it, I am unable to open it again
Video demo:
https://github.com/lightdash/lightdash/assets/97773130/1638d67d-3f1a-4b15-95ed-0409406094ce
> fix: reopen google sheet auth issue

- packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/FieldLayoutOptions.tsx
- packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/GeneralSettings.tsx
- packages/frontend/src/hooks/pivotTable/pivotQueryResults.ts
- packages/frontend/src/hooks/usePivotDimensions.ts
> feat: pivot table with custom dimensions

- packages/frontend/src/components/common/Filters/FilterGroupForm.tsx
Closes: https://github.com/lightdash/lightdash/issues/7725
Renamed Add filter to Add group rule
> fix: Update button copy on nested filters #7725

- packages/backend/src/clients/Aws/S3CacheClient.ts
- packages/backend/src/clients/Aws/s3.ts
- packages/backend/src/clients/clients.ts
- packages/backend/src/config/parseConfig.ts
- packages/backend/src/models/ProjectModel/ProjectModel.mock.ts
- packages/backend/src/services/ProjectService/ProjectService.test.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/backend/src/services/services.ts
Closes: #7710 
Changes:
- support separate S3 credentials for cache bucket
- move s3 cache log to separate client
> feat: cache s3 credentials

- packages/backend/src/queryBuilder.test.ts
- packages/backend/src/queryBuilder.ts
- packages/e2e/cypress/e2e/app/createProjects.cy.ts
- packages/e2e/cypress/e2e/app/customDimensions.cy.ts
- packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx
- packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderSortMenuOptions.tsx
- packages/frontend/src/components/common/Table/types.ts
- packages/frontend/src/utils/sortUtils.ts
Closes:  #7594
Also for width: 
Custom range will be ipmlemented after it gets merged
> fix: custom dimension order

- packages/common/src/types/metricQuery.ts
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/Explorer/ResultsCard/CellContextMenu.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/SeriesContextMenu.tsx
- packages/frontend/src/components/SimplePieChart/PieChartContextMenu.tsx
- packages/frontend/src/components/SimpleStatistic/BigNumberContextMenu.tsx
- packages/frontend/src/components/SimpleTable/CellContextMenu.tsx
- packages/frontend/src/components/SimpleTable/DashboardCellContextMenu.tsx
- packages/frontend/src/components/common/PivotTable/ValueCellMenu.tsx
> fix: disable underlying data custom dimension

- packages/backend/src/database/entities/savedCharts.ts
- packages/backend/src/database/migrations/20231030080302_custom_dimensions_custom_range.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/models/SavedChartModel.ts
- packages/backend/src/queryBuilder.ts
- packages/common/src/types/field.ts
- packages/frontend/src/components/Explorer/CustomDimensionModal/index.tsx
> feat: custom dimension custom range

- packages/backend/src/models/SavedChartModel.ts
> fix: custom dimension table order and visualization

- packages/common/src/compiler/exploreCompiler.ts
Closes: https://github.com/lightdash/lightdash/issues/7678
Before
After
> fix: joined tables hidden fields

- packages/e2e/cypress/e2e/app/downloadCsv.cy.ts
- packages/e2e/cypress/e2e/app/explore.cy.ts
- packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
- packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
- packages/frontend/src/components/ExportCSV/index.tsx
- packages/frontend/src/components/ExportSelector/index.tsx
Closes: #7693 
Removes the chart config feature flag and changes the tests to use the sidebar
> feat: remove old chart config

- packages/frontend/src/hooks/useProject.ts
Closes: N/A
Update error message when user is updating project
> chore: change update project error message

- packages/frontend/src/components/common/Filters/FieldLabel.tsx
related to: https://github.com/lightdash/lightdash/issues/7746
before:
after:
> fix: field labels not showing

- packages/e2e/cypress/e2e/app/customDimensions.cy.ts
- packages/frontend/src/components/Explorer/CustomDimensionModal/index.tsx
Closes: N/A
Small copy changes; 
Display base dimension label on the modal title
> feat: make small UI changes to custom dimensions modal

- packages/backend/src/index.ts
- packages/backend/src/models/SpaceModel.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/backend/src/utils.ts
> chore: add more open telemetry events for chart results endpoint

- packages/frontend/src/components/common/Filters/FieldLabel.tsx
- packages/frontend/src/features/scheduler/components/SchedulerFilters.tsx
- packages/frontend/src/features/scheduler/components/SchedulerForm.tsx
- packages/frontend/src/features/scheduler/components/SchedulerModalContent.tsx
Closes: https://github.com/lightdash/lightdash/issues/4425
filter list:
loading state
empty state:
> feat: scheduled deliveries filter UI

- packages/frontend/src/features/scheduler/components/SchedulerForm.tsx
- packages/frontend/src/features/scheduler/components/SchedulerModalFooter.tsx
Closes: #7789 
Fix z-index issues in scheduled deliveries. 
- csv/image control was overflowing fotter
- Slack input was being cutoff by dialog
> fix: z-index issues in scheduled deliveries

- packages/backend/src/controllers/savedChartController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/scheduler/SchedulerTask.ts
- packages/backend/src/services/CsvService/CsvService.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
- packages/frontend/src/hooks/useQueryResults.tsx
- packages/frontend/src/providers/DashboardProvider.tsx
Closes: #7718 
This is a proof of concept for clearing the results cache with the refresh button. This doesn't have:
- a good way to turn caching back on
> feat: refresh button clears results cache

- packages/backend/src/models/UserModel.ts
> fix: multiple oauth accounts

- packages/warehouses/package.json
- packages/warehouses/src/ssh/sshTunnel.ts
- packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
- yarn.lock
> feat: add ssh tunnel beta

- packages/warehouses/src/warehouseClients/PostgresWarehouseClient.test.ts
- packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
> fix: postgres ssh connection errors

- packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx
- packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNodeActions.tsx
> chore: disable custom dimension feature flag

- packages/common/src/compiler/filtersCompiler.mock.ts
- packages/common/src/compiler/filtersCompiler.ts
Closes: https://github.com/lightdash/lightdash/issues/7565
> fix: custom metric or filter

- packages/common/src/types/resourceViewItem.ts
- packages/frontend/src/App.tsx
- packages/frontend/src/MobileRoutes.tsx
- packages/frontend/src/components/Mobile/index.tsx
- packages/frontend/src/pages/Login.tsx
- packages/frontend/src/pages/MobileCharts.tsx
- packages/frontend/src/pages/MobileDashboards.tsx
- packages/frontend/src/pages/MobileHome.tsx
- packages/frontend/src/pages/MobileSpace.tsx
- packages/frontend/src/pages/MobileSpaces.tsx
Closes: #4736 
Goals:
Changes:
- create new minimal pages: home, spaces, space, dashboards, chart ( they are pretty much all the same )
- use the existing minimal dashboard and chart page
- redirect chart and dashboard routes to minimal route
- enable tracking for minimal routes when on mobile
- show an "error" page when the user access a route that is not supported on mobile
> feat: mobile routes

- packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
Closes:  https://github.com/lightdash/lightdash/issues/7672
Before
After:
> feat: chart move to private space

- packages/frontend/src/components/Explorer/ExploreTree/index.tsx
Closes: https://github.com/lightdash/lightdash/issues/7489
> fix: sort join by label explore

- packages/frontend/src/features/scheduler/components/SchedulerFilters.tsx
- packages/frontend/src/features/scheduler/components/SchedulerForm.tsx
Related to: https://github.com/lightdash/lightdash/issues/4425
adds state management to scheduled delivery filters
> feat: scheduled deliveries filter state

- .github/workflows/main.yml
Closes: https://github.com/lightdash/lightdash/issues/4286
This PR adds arm64 build to the Github Actions
> feat: Implement multi-arch Docker builds in the CI

- packages/backend/src/clients/Google/GoogleDriveClient.ts
> fix: google sheet array field

- packages/backend/src/queryBuilder.ts
Closes: https://github.com/lightdash/lightdash/issues/7834
> fix: custom range sorting

- packages/frontend/src/components/DashboardFilter/index.tsx
Closes: N/A
We believe we don't need to fetch explores anymore;
Testing in Render
> fix: remove unnecessary usage of useExplores

- packages/backend/src/database/migrations/20231107174707_add-index-space-id-to-dashboards.ts
Closes: N/A
Add `space_id` index to `dashboards` table
> fix: add space_id index to dashboards table

- packages/frontend/src/components/common/modal/ChartCreateModal.tsx
Use mantine's form manager for create chart. This enables create on 'enter'.
> chore: use mantine form for saved charts

- packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNodeActions.tsx
Closes: #7859
[Screencast from 08-11-23 11:43:30.webm](https://github.com/lightdash/lightdash/assets/1983672/4720ad17-61d5-40cd-9648-d08f096d98db)
> fix: custom metric submenu

- packages/frontend/src/components/common/Filters/FilterInputs/FilterStringAutoComplete.tsx
Closes: https://github.com/lightdash/lightdash/issues/7857
https://github.com/lightdash/lightdash/assets/962095/0179a7a1-9f85-438d-a5d4-0f9df70ce41d
> feat: pin add option to the bottom of the string autocomplete list

- packages/backend/src/controllers/savedChartController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
Closes: 
There is an issue where the dashboard filters have the wrong format and it's causing the API to fail. 
While we are investigating the root cause we are disabling the validation for now.
> fix: disable dashboard filter validation

- release.config.js
> fix: do not skip ci on release

- packages/frontend/src/App.tsx
- packages/frontend/src/components/DbtCloudSettings/index.tsx
- packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectUsingCLI.tsx
- packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx
- packages/frontend/src/components/common/modal/ChartCreateModal.tsx
- packages/frontend/src/components/common/modal/DashboardCreateModal.tsx
- packages/frontend/src/hooks/gdrive/useGdrive.ts
- packages/frontend/src/hooks/useFieldValues.ts
- packages/frontend/src/hooks/useRefreshServer.tsx
- packages/frontend/src/hooks/validation/useValidation.ts
This change will make sure there are no duplicate requests within 30 seconds. This will make all pages faster to load.
Hooks that use `onSuccess` need to have staleTime: 0 
Before:
Notice duplicate requests for /health /org /user /projects
After:
> fix: remove duplicate requests on page load

- .github/workflows/build-docker.yml
`+` is not supported use `format()` instead
> fix: docker build syntax

- .github/workflows/build-docker.yml
> fix: typo in docker build action

- packages/frontend/src/components/Explorer/ExplorerHeader/index.tsx
Closes: #7883 
readd this button
> fix: readd share short link button to edit mode

- packages/backend/src/routers/projectRouter.ts
- packages/backend/src/services/CsvService/CsvService.ts
- packages/common/src/types/csv.ts
- packages/common/src/types/savedCharts.ts
- packages/common/src/types/scheduler.ts
- packages/frontend/src/api/csv.ts
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
Closes: #7702
Google sheet will be fixed on a separate issue : https://github.com/lightdash/lightdash/issues/7870
> fix: hide columns on csv

- packages/frontend/package.json
- yarn.lock
> feat: upgrade posthog to 1.88.3

- packages/e2e/cypress/e2e/app/dashboard.cy.ts
- packages/frontend/src/components/common/modal/ChartCreateModal.tsx
- packages/frontend/src/pages/Dashboard.tsx
- packages/frontend/src/providers/ThirdPartyServicesProvider.tsx
Closes: #7892
https://github.com/lightdash/lightdash/assets/9117144/6f624e33-8da4-463c-a59c-8ab084902f41
> feat: lazy load dashboard tiles

- packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
Closes: https://github.com/lightdash/lightdash/issues/7887
> fix: filter inputs timestamp input parsing and formatting

- packages/warehouses/package.json
- packages/warehouses/src/ssh/sshTunnel.ts
- yarn.lock
deploys the beta sshtunnel to all users
> feat: remove ssh2 promise

- packages/frontend/src/components/SqlRunner/RunSqlQueryButton.tsx
- packages/frontend/src/pages/SqlRunner.tsx
Closes: https://github.com/lightdash/lightdash/issues/7896
- before ![CleanShot 2023-11-09 at 13 23 03@2x](https://github.com/lightdash/lightdash/assets/962095/416004dd-ae25-4474-9b5e-14be66452fbd)
- after ![CleanShot 2023-11-09 at 13 21 53@2x](https://github.com/lightdash/lightdash/assets/962095/01c609fc-741d-4cae-aad9-bc76770bdab0)
> fix: sql runner run button styles

- packages/frontend/src/components/CustomVisualization/index.tsx
fixes explore with no result values.
bug introduced in custom viz
> fix: custom viz empty rows

- packages/frontend/src/pages/Dashboard.tsx
Closes: N/A
If some tiles aren't in view yet, prefetch them sequentially by referencing a sorted list of tiles based on the `dashboardTiles`.
> feat: prefetch tiles sequentially

- packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNodeActions.tsx
Closes:  #7859
Thread: https://lightdash.slack.com/archives/C02NPFHF4F6/p1699606259592799
> fix: remove custom metric submenu

- packages/warehouses/src/ssh/sshTunnel.ts
> fix: increase timeout sshTunnel.ts

- packages/frontend/src/Routes.tsx
> fix: fix tracking on minimal pages

- packages/warehouses/src/ssh/sshTunnel.ts
> fix: increase ssh timeout to 5mins

- packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNodeActions.tsx
- packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx
- packages/frontend/src/providers/ExplorerProvider.tsx
> fix: remove custom dimension sort

- packages/frontend/src/components/VisualizationConfigs/PieChartConfig/PieChartLayoutConfig.tsx
Closes: #7591 
Added the logic for checking whether a dimension is custom or not in a pie chart
[Screencast from 13-11-23 15:08:08.webm](https://github.com/lightdash/lightdash/assets/76876702/9715a362-d010-4d3a-9f7c-7f13bf913c84)
> fix: make custom dimensions selectable in pie charts

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
> fix: generic error on dashboard

- packages/e2e/cypress/e2e/app/minimal.cy.ts
- packages/frontend/src/components/VisualizationConfigs/PieChartConfig/PieChartLayoutConfig.tsx
Closes: https://github.com/lightdash/lightdash/issues/7924
> test: minimal e2e tests

- packages/backend/package.json
- packages/backend/src/controllers/csvController.ts
- packages/backend/src/controllers/dbtCloudIntegrationController.ts
- packages/backend/src/controllers/googleDriveController.ts
- packages/backend/src/controllers/groupsController.ts
- packages/backend/src/controllers/metricFlowController.ts
- packages/backend/src/controllers/organizationController.ts
- packages/backend/src/controllers/pinningController.ts
- packages/backend/src/controllers/projectController.ts
- packages/backend/src/controllers/runQueryController.ts
- packages/backend/src/controllers/savedChartController.ts
- packages/backend/src/controllers/schedulerController.ts
- packages/backend/src/controllers/shareController.ts
- packages/backend/src/controllers/slackController.ts
- packages/backend/src/controllers/spaceController.ts
- packages/backend/src/controllers/sshController.ts
- packages/backend/src/controllers/userAttributesController.ts
- packages/backend/src/controllers/userController.ts
- packages/backend/src/controllers/validationController.ts
- packages/backend/src/errors.ts
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- yarn.lock
> fix: upgrade zlib and merge dependencies

- packages/frontend/src/components/VisualizationConfigs/PieChartConfig/PieChartSeriesConfig.tsx
Closes: #7855 
[Screencast from 15-11-23 09:22:38.webm](https://github.com/lightdash/lightdash/assets/76876702/cd47c5dd-e1d1-425e-9680-1c44ce305c40)
> fix: drag and drop offset when reordering pie chart series

- packages/frontend/src/components/Explorer/ResultsCard/ExplorerResultsNonIdealStates.tsx
- packages/frontend/src/components/common/PageBreadcrumbs.tsx
gets rid of annoying console warnings
> chore: removes random console warnings

- packages/frontend/src/components/RegisterForms/VerifyEmailForm.tsx
Closes: #7994 
Adds a message to alert the user to resend an email. Previously a user was stuck on the screen and didn't know their passcode had expired
> fix: improve ui for expired otp on VerifyEmailForm.tsx

- packages/backend/src/controllers/savedChartController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/frontend/src/components/SimpleTable/DashboardHeaderContextMenu.tsx
- packages/frontend/src/components/SimpleTable/index.tsx
- packages/frontend/src/hooks/dashboard/useDashboardChart.ts
- packages/frontend/src/hooks/useQueryResults.tsx
- packages/frontend/src/providers/DashboardProvider.tsx
Closes: #6315
[Screencast from 15-11-23 10:06:04.webm](https://github.com/lightdash/lightdash/assets/1983672/ed9627c4-329f-4adf-955c-4d0db73020b6)
> feat: sort dashboard table

- packages/backend/src/services/ProjectService/ProjectService.ts
> fix: dashboard sorting line charts

- packages/backend/src/queryBuilder.ts
> fix: fix custom dimension with width bin and table calculation

- packages/frontend/src/components/common/Filters/FilterInputs/FilterStringAutoComplete.tsx
Closes: #7958 
[Screencast from 15-11-23 07:11:51.webm](https://github.com/lightdash/lightdash/assets/76876702/d973e830-85e2-4df1-9ed4-8030eb6711da)
> fix: enter adds incomplete filter value

- packages/backend/src/models/SpaceModel.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
Closes: N/A
Before we were checking space access for each saved chart, regardless of them sharing the same space Uuid. 
Now, with this change, we are:
* Getting all spaces for the dashboard charts in batch - and only querying the necessary tables and columns
* Running this query in parallel with the explores. 
* Checking space access on the `filterPromises`, without duplicating queries to get a space. 
Sentry link: https://lightdash.sentry.io/performance/lightdash:c6f373b04b2146f691051182bd6cc0ba/?breakdown=none&project=5959292&query=&showTransactions=p95&sort=-timestamp&statsPeriod=24h&transaction=POST+%2Fapi%2Fv1%2Fdashboards%2FavailableFilters so you can see why this change is necessary - look at the breakdown on find spaces queries
Trigger all e2e tests:
test-cli
test-backend …
> fix: get space access in batches along with explores on availableFilters

- packages/frontend/src/features/scheduler/components/SchedulerFilters.tsx
- packages/frontend/src/providers/DashboardProvider.tsx
Closes: #8017 
Can revert dashboard scheduled delivery filters
https://github.com/lightdash/lightdash/assets/7611706/c41becf6-4964-4629-a02e-0d03f909a8c0
> feat: can revert filters on dashboard scheduled delivery

- packages/frontend/src/pages/PasswordRecoveryForm.tsx
Closes: 
- validate email format
- make sure it doesn't allow white spaces
> fix: validate email in recover password form

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/controllers/projectController.ts
- packages/backend/src/controllers/runQueryController.ts
- packages/backend/src/controllers/savedChartController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/common/src/index.ts
- packages/common/src/types/metricQuery.ts
- packages/common/src/types/savedCharts.ts
- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
- packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
- packages/frontend/src/hooks/dashboard/useDashboardFiltersForTile.ts
- packages/frontend/src/hooks/tableVisualization/getDataAndColumns.tsx
- packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
- packages/frontend/src/hooks/useCalculateTotal.ts
- packages/frontend/src/hooks/useTotalCalculation.ts
- packages/frontend/src/pages/MinimalSavedExplorer.tsx
Closes:  https://github.com/lightdash/lightdash/issues/5790
[Screencast from 20-11-23 17:29:12.webm](https://github.com/lightdash/lightdash/assets/1983672/ac7e3bb4-2c9f-4359-9f88-636b44492abf)
> feat: total metrics

- packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
- packages/frontend/src/hooks/useCalculateTotal.ts
- packages/frontend/src/hooks/useColumns.tsx
> feat: show total column on results table

- packages/frontend/src/components/SimpleTable/DashboardHeaderContextMenu.tsx
- packages/frontend/src/utils/sortUtils.ts
Closes: [#8012](https://github.com/lightdash/lightdash/issues/8012)
[Screencast from 22-11-23 09:05:13.webm](https://github.com/lightdash/lightdash/assets/1983672/3f9a5e30-fca5-400a-a9f4-360f40661134)
> feat: improve sort ui

- packages/frontend/src/hooks/useCalculateTotal.ts
> fix: remove calculate total feature flag

- packages/frontend/src/features/dateZoom/components/DateZoom.tsx
- packages/frontend/src/features/dateZoom/index.ts
- packages/frontend/src/pages/Dashboard.tsx
Relates to: #8036
Adds `DateZoom` component behind a feature flag;
Adds `DateZoom` component with options for a timeFrame. 
https://github.com/lightdash/lightdash/assets/7611706/098309da-a11c-4efa-96ba-559ccfad794e
> feat: add date zoom component

- docs/docs/guides/limiting-data-using-filters.mdx
Closes: N/A
Set out clearer rules on sharing dashboards and specifics on temporary/saved filters + edit/view mode
> docs: clarify rules on dashboard filters overrides

- packages/backend/package.json
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- yarn.lock
Closes: N/A
Fix the following error when generating `spec-and-routes` with `tsoa`: 
Trigger all e2e tests:
test-cli
test-backend
test-frontend
> fix: upgrade tsoa to 6.0.0-rc.5

- packages/backend/package.json
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- yarn.lock
This reverts commit f43a3279f64acba916bdb36b04f996b9388773bf.
Revert `tsoa` upgrade in #8072 .
2 errors:
* incorrect type generation on user attributes ("Could not match the intersection against every type. Issues: [{\"body.attributeDefault\":{\"message\":\"invalid string value\",\"value\":null}}]")
* incorrect type generation on explores/
internal slack [ref]( https://lightdash.slack.com/archives/C02GQKJK84Q/p1700824660455259?thread_ts=1700816405.761219&cid=C02GQKJK84Q)
> fix: revert "fix: upgrade tsoa to 6.0.0-rc.5 (#8072)"

- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/common/src/types/scheduler.ts
Closes: N/A
After reverting #8072  (because of a few errors on route validation), improved now the type for `SchedulerFilterRule` 
Trigger all e2e tests:  
test-cli  
test-backend  
test-frontend
> fix: tsoa types generation with scheduler filter Omit

- docs/docs/self-host/customize-deployment/google-sheets-integration.mdx
> docs: add required apis for google sheets integration

- packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
Closes: #8034 
ignore client_session_keep_alive
> fix: ignore client_session_keep_alive

- packages/backend/src/services/ProjectService/ProjectService.test.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/backend/src/services/services.ts
Closes: #8067 
https://github.com/lightdash/lightdash/assets/9117144/c2c9bf29-46d6-4152-8a65-8e79f3e6697a
> fix: count chart views in dashboard page

- packages/frontend/src/components/RegisterForms/CreateUserForm.tsx
- packages/frontend/src/pages/Login.tsx
Closes: #8090 
Added **Sign Up** and **Sign in** links for easy navigation on **Sign in** and **Sign up** pages respectively.
> feat: add login and register links

- packages/backend/src/analytics/LightdashAnalytics.ts
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/frontend/src/features/dateZoom/components/DateZoom.tsx
- packages/frontend/src/providers/TrackingProvider.tsx
- packages/frontend/src/types/Events.ts
> chore: date zoom analytic events

- packages/frontend/src/components/common/Filters/FilterInputs/FilterDateTimeRangePicker.tsx
> fix: allow to edit seconds in time range picker

- packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
- packages/frontend/src/components/ExportCSV/ExportCSVModal.tsx
Export CSV modal in mantine. Just the modal, not the content. Content will be a follow up.
> chore: export csv modal in mantine

- packages/backend/src/services/HealthService/HealthService.mock.ts
- packages/backend/src/services/HealthService/HealthService.ts
- packages/common/src/index.ts
- packages/frontend/src/components/NavBar/ExploreMenu.tsx
> feat: add navigation to dbt semantic layer page

- packages/backend/src/services/ProjectService/ProjectService.ts
> fix: table calculation dimension

- packages/backend/src/controllers/savedChartController.ts
- packages/backend/src/generated/routes.ts
- packages/backend/src/generated/swagger.json
- packages/backend/src/services/ProjectService/ProjectService.ts
- packages/e2e/cypress/e2e/api/projectPermissions.cy.ts
- packages/frontend/src/hooks/dashboard/useDashboardChart.ts
- packages/frontend/src/hooks/useQueryResults.tsx
Closes: #6826
- require dashboard uuid
- update other params to be required
> feat: add dashboard uuid to query tags

- packages/backend/src/models/ProjectModel/ProjectModel.ts
Closes: https://github.com/lightdash/lightdash/issues/7965
`base_table` does not exist in the json blob. we have `baseTable`
> fix: base table match when finding explore by table name

- packages/frontend/src/features/scheduler/components/SchedulerForm.tsx
Closes: N/A
Remove feature flag check now that we can roll out to all customers
> chore: remove feature flag check for dashboard scheduler filters
