lightdash/lightdash

README.md
packages/backend/src/index.ts
packages/frontend/src/queryBuilder.ts

Fix postgres quotes

---

CHANGELOG.md
package.json
packages/backend/package.json
packages/common/package.json
packages/frontend/package.json

* This is just to test out PR previews tbh

bump version to 0.1.3

---

packages/backend/src/apiV1.ts
packages/backend/src/lightdash.ts
packages/common/src/index.ts
packages/frontend/package.json
packages/frontend/src/App.tsx
packages/frontend/src/components/ChartConfigPanel.tsx
packages/frontend/src/components/Explorer.tsx
packages/frontend/src/components/RefreshButton.tsx
packages/frontend/src/components/ResultsTable.tsx
packages/frontend/src/components/SimpleChart.tsx
packages/frontend/src/hooks/useChartConfig.tsx
packages/frontend/src/hooks/useExploreConfig.tsx
packages/frontend/src/hooks/useQueryResults.tsx
yarn.lock

Add chart settings space

---

CHANGELOG.md
docs/docusaurus-rudderstack-plugin/index.js
docs/docusaurus.config.js
packages/frontend/package.json
packages/frontend/public/index.html
packages/frontend/src/App.tsx
packages/frontend/src/components/Analytics.ts
packages/frontend/src/components/RefreshButton.tsx
render.yaml
yarn.lock

add rudderstack to app

---

CHANGELOG.md
dockerfile
package.json
packages/backend/package.json
packages/backend/src/dbt/translator.ts
packages/common/package.json
packages/common/src/index.ts
packages/frontend/package.json
packages/frontend/src/components/Analytics.ts
packages/frontend/src/components/ExploreSideBar.tsx
packages/frontend/src/components/Explorer.tsx
packages/frontend/src/components/LineageButton.tsx
packages/frontend/src/components/ShowDagButton.tsx

Closes #63 
--
Also minor fix to docker file for #87 
Not sure this worked correctly for demo.lightdash.com - seems to be working for docs.lightdash.com

63 users can see the lineage of a model

---

packages/frontend/src/components/ExploreSideBar.tsx

Suport scrolling in sidebar

---

packages/frontend/src/components/LineageButton.tsx

I thought that if you don't know what a lineage graph is, this description might be a bit confusing? (since it's a bit of a recursive definition)
Not sure what you think @owlas, but thought it might be worth changing?

updates info text of lineage button

---

packages/frontend/src/components/LineageButton.tsx

remove debugging statement

---

CHANGELOG.md
packages/frontend/src/components/ChartConfigPanel.tsx
packages/frontend/src/components/Explorer.tsx
packages/frontend/src/components/SimpleChart.tsx
packages/frontend/src/hooks/useChartConfig.tsx

Closes #76 
- Small change in the hook to assert seriesLayout.yMetrics is not an empty array
- Add message when chart has no data
- Disable chart buttons when chart has no data
- Small typing improvements
Preview:

add empty chart message

---

CHANGELOG.md
packages/backend/jest.config.js
packages/backend/package.json
packages/backend/src/dbt/translator.ts
packages/backend/src/errors.ts
packages/backend/src/exploreCompiler.mock.ts
packages/backend/src/exploreCompiler.test.ts
packages/backend/src/exploreCompiler.ts
packages/backend/src/queryBuilder.ts
packages/common/src/index.ts
packages/frontend/src/components/ExploreTree.tsx
yarn.lock

Catch invalid dimension references in config

---

CHANGELOG.md
README.md
packages/frontend/src/components/ExploreTree.tsx

Input get OFF focus on focus + few tweaks
-------------------------------

UI Fix - Input get OFF focus on focus

---

CHANGELOG.md
packages/backend/package.json
packages/backend/src/dbt/translator.ts
packages/backend/src/exploreCompiler.mock.ts
packages/common/src/index.ts
packages/frontend/package.json
packages/frontend/src/components/ExploreTree.tsx
yarn.lock

Closes: #65 
Preview:
<a href="https://www.loom.com/share/be2f243cb2894ec194d3c24c9941bc1f"> <p>Lightdash - Source Dialog</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/be2f243cb2894ec194d3c24c9941bc1f-with-play.gif"> </a>
Notes:
- [BE] code can be simplified and optimised once we refactor the translator file into classes. We could also memoize the yml files since they are the same across multiple models.
- [FE] we could use the context menu but we most likely need to stop using the <Tree/> component

Add source details

---

CHANGELOG.md
docs/docs/guides/how-to-update-docker-image.md
packages/backend/jest.config.js
packages/backend/package.json
packages/backend/setupJest.ts
packages/backend/src/apiV1.ts
packages/backend/src/health.mock.ts
packages/backend/src/health.test.ts
packages/backend/src/health.ts
packages/backend/tsconfig.json
packages/common/src/index.ts
packages/frontend/src/components/AboutFooter.tsx
packages/frontend/src/components/ExploreSideBar.tsx
yarn.lock

Closes: #127 
Preview:
[<img class="mt:small" src="https://cdn.loom.com/sessions/thumbnails/f586775f7aa744e18de18be205871209-with-play.gif">](https://www.loom.com/share/f586775f7aa744e18de18be205871209)
Notes:
- excluded test files when building BE

Lightdash 127

---

CHANGELOG.md
packages/backend/src/dbt/translator.ts

fix metric description

---

packages/frontend/src/components/ExploreTree.tsx

add source path label

---

packages/backend/src/dbt/translator.ts
packages/common/src/index.ts
packages/frontend/src/components/ExploreTree.tsx

Closes: #167 
Preview:
[<img src="https://cdn.loom.com/sessions/thumbnails/2dfe0343b7064683b1e12f81213aa737-with-play.gif" />](https://www.loom.com/share/2dfe0343b7064683b1e12f81213aa737)

fix metric source

---

CHANGELOG.md
packages/backend/src/dbt/dbtRpcClient.ts

handle missing GCP credentials error

---

CHANGELOG.md
packages/backend/src/dbt/dbtChildProcess.mock.ts
packages/backend/src/dbt/dbtChildProcess.test.ts
packages/backend/src/dbt/dbtChildProcess.ts

fix dbt child process event handler

---

.gitignore
CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/components/ChartDownload.tsx
packages/frontend/src/components/Explorer.tsx
packages/frontend/src/components/SimpleChart.tsx
yarn.lock

Closes: #74 
@owlas FYI: I had to switch the chart renderer from `canvas` to `svg`, otherwise we couldn't have the SVG option. Shouldn't have any impact but we can keep an eye on it. 
Preview:
[<img src="https://cdn.loom.com/sessions/thumbnails/1513d3603d2c447e9af784f4bb745227-with-play.gif" />](https://www.loom.com/share/1513d3603d2c447e9af784f4bb745227)

allow users to download chart

---

CHANGELOG.md
packages/backend/src/queryBuilder.ts

Fix error when getting quote strings from dbt adapter

---

CHANGELOG.md
packages/frontend/src/components/AboutFooter.tsx

add help button

---

README.md

Happy to adjust text as requested but currently links are broken and 404.

update broken links + add ref to new dbtCloud tutorial

---

CHANGELOG.md
dockerfile
dockerfile-demo
packages/backend/src/apiV1.ts
packages/backend/src/config/parseConfig.mock.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/database/entities/emails.ts
packages/backend/src/database/entities/organizations.ts
packages/backend/src/database/entities/passwordLogins.ts
packages/backend/src/database/entities/users.ts
packages/backend/src/health.test.ts
packages/backend/src/health.ts
packages/backend/src/index.ts
packages/backend/src/jsonSchemas/lightdashConfig/v1.json
packages/backend/src/models/Org.ts
packages/backend/src/models/User.ts
packages/common/src/index.ts
packages/frontend/src/api.ts
packages/frontend/src/components/AppBar.tsx
packages/frontend/src/components/PasswordInput.tsx
packages/frontend/src/components/UserSettingsModal/OrganizationPanel.tsx
packages/frontend/src/components/UserSettingsModal/PasswordPanel.tsx
packages/frontend/src/components/UserSettingsModal/ProfilePanel.tsx
packages/frontend/src/components/UserSettingsModal/UserSettingsModal.css
packages/frontend/src/components/UserSettingsModal/UserSettingsModal.tsx
packages/frontend/src/pages/login.tsx
packages/frontend/src/pages/register.tsx
packages/frontend/src/providers/AppProvider.tsx

Closes: #231 
Preview:
https://www.loom.com/share/7f2379bd37de4f4996f81193aeec68b4

add user settings modal

---

README.md

Update community channels in README

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/apiV1.ts
packages/backend/src/models/User.ts

closes #232

---

CHANGELOG.md
packages/backend/src/dbt/dbtRpcClientBase.ts

show database errors in ui

---

packages/backend/src/apiV1.ts
packages/backend/src/database/entities/savedQueries.ts
packages/backend/src/models/savedQueries.ts
packages/frontend/src/api.ts
packages/frontend/src/hooks/useSavedQuery.ts
packages/frontend/src/pages/Saved.tsx

allow user to delete saved queries

---

packages/backend/src/apiV1.ts
packages/backend/src/database/entities/savedQueries.ts
packages/backend/src/models/savedQueries.ts
packages/common/src/index.ts
packages/frontend/src/components/AppBar.tsx
packages/frontend/src/components/NavLink.tsx
packages/frontend/src/components/SaveQueryModal.tsx
packages/frontend/src/hooks/useSavedQuery.ts
packages/frontend/src/pages/Saved.tsx

allow user to rename saved query

---

packages/frontend/src/components/AppBar.tsx
packages/frontend/src/components/Explorer.tsx
packages/frontend/src/hooks/useSavedQuery.ts
packages/frontend/src/pages/Saved.tsx

rename saved queries to saved charts + loading state

---

CHANGELOG.md
packages/backend/src/dbt/translator.ts
packages/common/src/index.ts

patch_path can be null

---

packages/frontend/src/pages/Saved.tsx

changes 'edit' copy to 'rename' in saved charts

---

CHANGELOG.md
packages/backend/src/dbt/dbtCloudV2RpcClient.ts
packages/frontend/package.json
packages/frontend/src/components/AppBar.tsx
packages/frontend/src/components/ErrorLogsDrawer.tsx
packages/frontend/src/components/ExploreSideBar.tsx
packages/frontend/src/components/SaveQueryModal.tsx
packages/frontend/src/components/ShowErrorsButton.tsx
packages/frontend/src/components/UserSettingsModal/OrganizationPanel.tsx
packages/frontend/src/components/UserSettingsModal/PasswordPanel.tsx
packages/frontend/src/components/UserSettingsModal/ProfilePanel.tsx
packages/frontend/src/hooks/useErrorLogs.ts
packages/frontend/src/hooks/useExplorerRoute.ts
packages/frontend/src/hooks/useRefreshServer.tsx
packages/frontend/src/hooks/useSavedQuery.ts
packages/frontend/src/providers/AppProvider.tsx
yarn.lock

* Move errors to an error log drawer component
* Persist errors in the error log (Closes #313)
* Fix sidebar loading and empty states
* Fix error and sidebar update on refresh (Closes #309)
* Support clickable links via markdown in errors (Closes #286)
* Duplicated error messages are shown as "unread" (Closes #315)

Improve error messages in UI

---

CHANGELOG.md
packages/common/src/index.ts
packages/frontend/src/components/ExploreSideBar.tsx
packages/frontend/src/components/ExploreTree.tsx
packages/frontend/src/components/UserSettingsModal/OrganizationPanel.tsx
packages/frontend/src/components/UserSettingsModal/PasswordPanel.tsx
packages/frontend/src/components/UserSettingsModal/ProfilePanel.tsx
packages/frontend/src/filters/DateFilterForm.tsx
packages/frontend/src/filters/FilterRow.tsx
packages/frontend/src/filters/FiltersForm.tsx
packages/frontend/src/filters/NumberFilterForm.tsx
packages/frontend/src/filters/StringFilterForm.tsx
packages/frontend/src/hooks/useCompiledSql.tsx
packages/frontend/src/hooks/useErrorLogs.ts
packages/frontend/src/hooks/useQueryResults.tsx
packages/frontend/src/hooks/useRefreshServer.tsx
packages/frontend/src/hooks/useServerStatus.tsx
packages/frontend/src/hooks/useTable.tsx
packages/frontend/src/hooks/useTables.tsx
packages/frontend/src/providers/AppProvider.tsx

260 fix filter behaviour

---

CHANGELOG.md
packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/api/inviteLinksRouter.ts
packages/backend/src/models/InviteLinkModel.ts
packages/backend/src/services/UserService.ts
packages/common/src/openapi/paths/inviteLinks.json
packages/common/src/openapi/responses/SuccessResponse.json
packages/common/src/openapibundle.json
packages/frontend/src/components/UserSettingsModal/OrganizationPanel.tsx
packages/frontend/src/hooks/useInviteLink.tsx

Improvement of #316 
Preview: 
<a href="https://www.loom.com/share/d1df41cbf8404ce1b58df7b77316fc8c">
</a>

Revoke invite links

---

CHANGELOG.md
packages/backend/src/@types/knex-tables.d.ts
packages/backend/src/api/apiV1.ts
packages/backend/src/api/inviteLinksRouter.ts
packages/backend/src/api/userRouter.ts
packages/backend/src/database/entities/emails.ts
packages/backend/src/models/InviteLinkModel.ts
packages/backend/src/models/User.ts
packages/backend/src/models/UserModel.ts
packages/backend/src/services/UserService.ts
packages/backend/src/services/services.ts
packages/backend/src/utils.ts
packages/common/src/index.ts
packages/common/src/openapi/openapi.json
packages/common/src/openapi/paths/inviteLink.json
packages/common/src/openapi/paths/user.json
packages/common/src/openapi/schemas/CreateUser.json
packages/common/src/openapi/schemas/LightdashUser.json
packages/common/src/openapibundle.json
packages/frontend/src/App.tsx
packages/frontend/src/components/CreateUserForm.tsx
packages/frontend/src/components/UserSettingsModal/OrganizationPanel.tsx
packages/frontend/src/hooks/useInviteLink.tsx
packages/frontend/src/pages/Signup.tsx
packages/frontend/src/pages/register.tsx

Accept invite

---

CHANGELOG.md
packages/frontend/src/hooks/useChartConfig.tsx
packages/frontend/src/hooks/useColumns.tsx

PR to fix issues #184 and #185.

Data parsing fixes

---

CHANGELOG.md
packages/backend/src/@types/knex-tables.d.ts
packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/api/organizationRouter.ts
packages/backend/src/database/entities/sessions.ts
packages/backend/src/models/SessionModel.ts
packages/backend/src/models/UserModel.ts
packages/backend/src/services/UserService.ts
packages/backend/src/services/services.ts
packages/common/src/openapi/openapi.json
packages/common/src/openapi/paths/organizationUser.json
packages/common/src/openapibundle.json
packages/frontend/src/components/UserSettingsModal/UserManagementPanel.tsx
packages/frontend/src/hooks/useOrganizationUsers.ts

delete organization user

---

packages/frontend/src/components/UserSettingsModal/InvitesPanel.tsx
packages/frontend/src/components/UserSettingsModal/OrganizationPanel.tsx
packages/frontend/src/components/UserSettingsModal/UserSettingsModal.tsx
packages/frontend/src/types/Events.ts

add dedicated panel for invites

---

CHANGELOG.md
packages/frontend/src/components/ExploreSideBar.tsx
packages/frontend/src/components/ExploreTree.tsx

fix: order tables, metrics and dimensions alphabetically.

---

docs/docs/get-started/setup-the-demo-project.md

I got this error when setting up the demo locally. 
Hope this helps more people.

add docker error information

---

packages/backend/src/queryBuilder.mock.ts
packages/backend/src/queryCompiler.mock.ts
packages/common/src/index.ts
packages/frontend/src/components/ExploreSideBar.tsx
packages/frontend/src/components/ExploreTree.tsx
packages/frontend/src/components/RenderedSql.tsx
packages/frontend/src/components/ResultsTable.tsx
packages/frontend/src/components/TableCaculationsTree.tsx
packages/frontend/src/components/TableCalculationModal.tsx
packages/frontend/src/components/TableTree.tsx
packages/frontend/src/hooks/useColumns.tsx
packages/frontend/src/hooks/useCompiledSql.tsx
packages/frontend/src/hooks/useExplorerRoute.ts
packages/frontend/src/hooks/useQueryResults.tsx
packages/frontend/src/pages/SavedExplorer.tsx
packages/frontend/src/providers/ExplorerProvider.tsx
packages/frontend/src/types/react-table-config.d.ts

Closes: #376 
Changes:
- add table calculation to explore context
- sql compiler shows error inline instead of in drawer
- split explore tree into multiple files

table calculations

---

CHANGELOG.md
packages/frontend/src/components/SimpleChart.tsx

fix chart label from being cropped

---

CHANGELOG.md
packages/backend/src/dbt/translator.ts
packages/backend/src/exploreCompiler.mock.ts
packages/backend/src/exploreCompiler.ts
packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts
packages/backend/src/queryBuilder.mock.ts
packages/backend/src/queryBuilder.ts
packages/common/src/index.ts

Removes hack to determine quote string and begin implementing target-specific sql builders

Fix sql quote strings with adapter type

---

CHANGELOG.md
packages/backend/src/config/parseConfig.test.ts
packages/backend/src/config/parseConfig.ts
packages/e2e/cypress/integration/explore.spec.ts

fix(#434): support optional project configs via env

---

packages/backend/src/jsonSchemas/lightdashConfig/v1.json
packages/common/src/index.ts
packages/frontend/src/components/CreateUserForm.tsx

Form for cloud beta users:
Default form:

add cloud beta mode

---

packages/backend/src/@types/rudder-sdk-node.d.ts
packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/api/apiV1.ts
packages/backend/src/errors.ts
packages/backend/src/index.ts
packages/backend/src/lightdash.ts

Closes: #367 
3 new events:
```
type ProjectEvent = BaseTrack & {
event: 'project.compiled';
userId?: string;
anonymousId?: string;
properties: {
projectType: ProjectType;
};
};
type ProjectErrorEvent = BaseTrack & {
event: 'project.error';
userId?: string;
anonymousId?: string;
properties: {
name: string;
statusCode: number;
projectType: ProjectType;
};
};
type ApiErrorEvent = BaseTrack & {
event: 'api.error';
userId?: string;
anonymousId?: string;
properties: {
name: string;
statusCode: number;
route: string;
method: string;
};
};
```

track compile success and errors

---

CHANGELOG.md
packages/backend/src/config/parseConfig.ts
packages/backend/src/jsonSchemas/lightdashConfig/v1.json
packages/backend/src/projectAdapters/dbtGitProjectAdapter.ts
packages/backend/src/projectAdapters/dbtGitlabProjectAdapter.ts
packages/backend/src/projectAdapters/projectAdapter.ts

Add gitlab adapter

---

docker/.env.dev
docker/docker-compose.dev.yml
packages/backend/package.json
packages/backend/src/index.ts
yarn.lock

Add sentry

---

CHANGELOG.md
packages/backend/src/api/apiV1.ts
packages/backend/src/dbt/translator.ts
packages/backend/src/exploreCompiler.ts
packages/backend/src/lightdash.ts
packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts
packages/backend/src/projectAdapters/dbtCloudIdeProjectAdapter.ts
packages/backend/src/projectAdapters/dbtRemoteProjectAdapter.ts
packages/backend/src/services/ProjectService.ts
packages/backend/src/types.ts
packages/common/src/index.ts
packages/frontend/src/components/ExploreMenuItem.tsx
packages/frontend/src/components/ExploreSideBar.tsx
packages/frontend/src/components/LineageButton.tsx
packages/frontend/src/components/ProjectStatusCallout.tsx
packages/frontend/src/components/ResultsTable.tsx
packages/frontend/src/filters/FiltersForm.tsx
packages/frontend/src/hooks/useChartConfig.tsx
packages/frontend/src/hooks/useColumns.tsx
packages/frontend/src/hooks/useCompiledSql.tsx
packages/frontend/src/hooks/useExplore.tsx
packages/frontend/src/hooks/useExplorerAceEditorCompleter.tsx
packages/frontend/src/hooks/useExplores.tsx
packages/frontend/src/hooks/useQueryResults.tsx

Closes #449 
https://www.loom.com/share/4616ff4de8de4c41aadbbe3420a25fe6

Partial compilation

---

CHANGELOG.md
packages/backend/src/api/projectRouter.ts
packages/backend/src/queryBuilder.ts

Fix error with determining correct quote character for database

---

CHANGELOG.md
package.json
packages/backend/package.json
packages/common/package.json
packages/e2e/package.json
packages/frontend/package.json

release 0.7.0

---

CHANGELOG.md
packages/frontend/src/hooks/useExplorerRoute.ts

Closes: #416 
Preview: 
<a href="https://www.loom.com/share/1ad07934b9ef414aad377e481812b48b">
</a>

fix(#416): explore menu button reset explore state

---

CHANGELOG.md
packages/frontend/src/hooks/useCompiledSql.tsx

fix(#483): fix compiledSQL request path

---

CHANGELOG.md
packages/e2e/cypress/support/commands.ts
packages/frontend/src/hooks/useChartConfig.tsx

Closes: #490 #82 
Preview:
<a href="https://www.loom.com/share/ef6ffae32b0b4f799d15075e7f97c034">
</a>

fix(#490): dont reset chart config after run query

---

CHANGELOG.md
packages/frontend/src/components/RefreshButton.tsx
packages/frontend/src/hooks/useDefaultSortField.tsx
packages/frontend/src/providers/ExplorerProvider.tsx

Closes: #183 
Preview:
<a href="https://www.loom.com/share/f534a570acd14fd688c5ab794184c1d6">
</a>

fix(#183): add default sort

---

CHANGELOG.md
packages/common/src/index.ts
packages/frontend/src/components/ReactHookForm/Textarea.tsx
packages/frontend/src/components/ResultsTable.tsx
packages/frontend/src/components/TableCalculationModal.tsx
packages/frontend/src/hooks/useColumns.tsx

Add function in common package to test whether column name has specials characters.
```
export const hasSpecialCharacters = (text: string) => /[^a-zA-Z ]/g.test(text);
```
Add toast error if
- special character is found
- column name already exists

Fix: Special characters in table calculation column name

---

packages/backend/src/services/warehouseClients/PostgresWarehouseClient.ts

We were reusing the pg connection client, which raises an error. The warehouse client now holds a pool, which releases individual connections for each query.
—

Fix: use pg connection pool not reuse connection

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/dbt/dbtRpcClientBase.ts
packages/backend/src/errors.ts
packages/backend/src/models/ProjectModel/ProjectModel.mock.ts
packages/backend/src/models/ProjectModel/ProjectModel.test.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/models/models.ts
packages/backend/src/projectAdapters/projectAdapter.ts
packages/backend/src/services/OrganizationService.ts
packages/backend/src/services/ProjectService.ts
packages/common/src/index.ts
packages/frontend/src/components/ProjectConnection/DbtForms/DbtCloudForm.tsx
packages/frontend/src/components/ProjectConnection/index.tsx

Closes: #636 
Existing users with projects with no warehouse credentials will see this error. 
**Bonus change!** Display friendly error when dbt cloud IDE is not running + info callout in form.

feat(#636): require all projects to have warehouse credentials

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/api/projectRouter.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/services.ts
packages/common/src/index.ts
packages/common/src/openapi/openapi.json
packages/common/src/openapi/paths/projectSqlQuery.json
packages/common/src/openapibundle.json

feat: add endpoint to run sql

---

packages/frontend/src/components/Explorer.tsx
packages/frontend/src/components/ExplorerResults.tsx
packages/frontend/src/components/ResultsTable/ResultsTable.tsx
packages/frontend/src/components/ResultsTable/States.tsx

refactor(#704): extract results table into generic component

---

packages/frontend/src/components/ChartDownload.tsx

feat(#654): add option to download chart as echart json

---

packages/backend/src/api/projectRouter.ts
packages/backend/src/dbt/translator.ts
packages/backend/src/exploreCompiler.mock.ts
packages/backend/src/queryBuilder.mock.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/index.ts
packages/common/src/openapi/openapi.json
packages/common/src/openapi/paths/projectCatalog.json
packages/common/src/openapi/schemas/ProjectCatalog.json
packages/common/src/openapibundle.json

feat: add project catalog endpoint

---

docs/docs/get-started/setup-lightdash/connect-project.mdx
packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx

feat: removed dbt cloud from connection options

---

CHANGELOG.md
package.json
packages/backend/package.json
packages/common/package.json
packages/e2e/package.json
packages/frontend/package.json

build: release 0.9.4

---

packages/frontend/src/components/Explorer.tsx

Closes: #775 
Preview:
When title is to long it shows in multiple lines:

style: bigger chart title

---

packages/frontend/src/components/ExploreSideBar.tsx
packages/frontend/src/hooks/useExplorerRoute.ts

fix: update url when user selects table

---

packages/frontend/src/pages/Explorer.tsx

fix: fix sidebar width in explorer

---

packages/frontend/src/components/ResultsTable/ResultsTable.tsx
packages/frontend/src/pages/SqlRunner.tsx

The container flex box grows outside the screen unless I place a `min-width: 0` property: https://stackoverflow.com/questions/36247140/why-dont-flex-items-shrink-past-content-size

fix: add horizontal scroll to wide tables in sql runner

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx

feat: add link to explore chart from dashboard tile

---

lightdash-pr.yml
lightdash.yml
packages/backend/src/config/parseConfig.mock.ts
packages/backend/src/config/parseConfig.test.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/jsonSchemas/lightdashConfig/v1.json

fix: support lightdash.yml with no projects

---

lightdash-pr.yml
packages/backend/src/database/seeds/development/02_project.ts
packages/backend/src/health.test.ts
packages/backend/src/health.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/common/src/index.ts

BREAKING CHANGE: this change is not backwards compatible

refactor!: remove support for projects in lightdash.yml

---

packages/e2e/cypress/integration/settings/profile.spec.ts
packages/frontend/src/components/ProjectConnection/ProjectStatusCallout.tsx
packages/frontend/src/components/UserSettingsModal/OrganizationPanel.tsx
packages/frontend/src/components/UserSettingsModal/ProfilePanel.tsx
packages/frontend/src/hooks/dashboard/useDashboard.tsx
packages/frontend/src/hooks/useInviteLink.tsx
packages/frontend/src/hooks/useOrganizationUsers.ts
packages/frontend/src/hooks/useProject.ts
packages/frontend/src/hooks/useSavedQuery.ts

Hey @lightdash/engineering looking for opinions on new style for toast messages

feat: update copy in toast messages

---

packages/e2e/cypress/integration/settings/profile.spec.ts
packages/frontend/src/components/AppBar.tsx
packages/frontend/src/components/Avatar.tsx

feat: simplify user settings on app bar

---

packages/frontend/src/components/ResultsTable/ResultsTable.tsx

fix: make results table full width

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/api/projectRouter.ts
packages/backend/src/database/entities/projects.ts
packages/backend/src/database/migrations/20211110150258_add_project_table_selection_columns.ts
packages/backend/src/models/ProjectModel/ProjectModel.mock.ts
packages/backend/src/models/ProjectModel/ProjectModel.test.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/index.ts
packages/common/src/openapi/openapi.json
packages/common/src/openapi/paths/projectTablesConfiguration.json
packages/common/src/openapi/schemas/ProjectTablesConfiguration.json
packages/common/src/openapibundle.json

feat: add get/update endpoints for project tables configuration

---

packages/backend/src/api/projectRouter.ts
packages/backend/src/dbt/translator.mock.ts
packages/backend/src/dbt/translator.ts
packages/backend/src/exploreCompiler.mock.ts
packages/backend/src/exploreCompiler.ts
packages/backend/src/queryBuilder.mock.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/common/src/index.ts

feat: return explores with tags

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/frontend/src/App.tsx
packages/frontend/src/components/ProjectConnection/index.tsx
packages/frontend/src/components/ProjectTablesConfiguration/ProjectTablesConfiguration.tsx
packages/frontend/src/pages/CreateProjectSettings.tsx
packages/frontend/src/types/Events.ts

Closes: #768 
Preview:
<a href="https://www.loom.com/share/5f4a2f6197824c3198bee36d8d0edb5d">
</a>

feat: add tables configuration to onboarding

---

packages/backend/jest.config.js

chore: ignore dist folder when running tests

---

packages/backend/src/dbt/profiles.ts
packages/backend/src/exploreCompiler.ts
packages/frontend/src/filters/boolean-filter/BooleanFilterForm.tsx
packages/frontend/src/filters/filter-group/AddFilterGroup.tsx
packages/frontend/src/filters/filter-group/FilterGroupForm.tsx
packages/frontend/src/filters/number-filter/NumberFilterForm.tsx
packages/frontend/src/filters/string-filter/StringFilterForm.tsx
packages/frontend/src/hooks/useColumns.tsx

chore: clean disabled eslint rules

---

packages/frontend/src/components/common/ActionCard.tsx

fix: left align text in action cards

---

packages/frontend/src/hooks/useSavedQuery.ts

fix: dont redirect after deleting saved chart

---

packages/frontend/src/components/common/Page/Sidebar.tsx

fix: add scroll to sql runner sidebar

---

packages/frontend/src/hooks/useProject.ts

fix: refetch tables and results after project update

---

packages/frontend/src/components/RenderedSql.tsx

fix: show scroll when sql overflow

---

packages/frontend/src/components/ExploreTree.tsx

fix: show base table at the top

---

packages/frontend/src/filters/common/FilterRow.tsx

fix: show filter logical operator

---

packages/frontend/src/components/ProjectConnection/index.tsx

During project creation/update we can have collapsed fields with errors and isn't obvious why the submit isn't working.
Preview fix:

fix: show project form errors

---

packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/hooks/dashboard/useDashboard.tsx
packages/frontend/src/pages/Dashboard.tsx
packages/frontend/src/pages/SavedDashboards.tsx
packages/frontend/src/types/Events.ts

Closes: #744 
Preview:
<a href="https://www.loom.com/share/b2d3f4a1182c4e319bafd7eb384a72c0">
</a>

feat: editable name in dashboard page

---

README.md
docs/docs/best-practice/lightdash-way.md
docs/docs/get-started/setup-a-github-project.md
docs/docs/intro.md

- updates docs intro page to match readme
- fixes Looker in readme
- updates The Lightdash Way: Data Access

Updates docs

---

packages/common/src/index.ts
packages/frontend/src/components/Explorer.tsx
packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx
packages/frontend/src/components/SavedDashboards/CreateSavedDashboardModal.tsx
packages/frontend/src/components/SavedDashboards/DashboardForm.tsx
packages/frontend/src/hooks/dashboard/useDashboard.tsx
packages/frontend/src/hooks/dashboard/useDashboards.tsx
packages/frontend/src/pages/Dashboard.tsx

Closes #679 
Preview: 
<a href="https://www.loom.com/share/ef913c24b7724ebbb79fa47789fd4387">
</a>

feat: add chart to dashboard from explore

---

packages/frontend/src/App.tsx
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/DashboardTiles/DashboardLoomTile.tsx
packages/frontend/src/components/DashboardTiles/DashboardMarkdownTile.tsx
packages/frontend/src/components/DashboardTiles/TileBase.tsx
packages/frontend/src/components/common/ActionCard.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/components/common/modal/ModalActionButtons.tsx
packages/frontend/src/pages/Dashboard.tsx
packages/frontend/src/pages/SavedDashboards.tsx
packages/frontend/src/styles/react-grid.css

Closes: #742 
Preview:
<a href="https://www.loom.com/share/675c55e87d7d449a97d5eb42cb4c7b19">
</a>

feat: add dashboard view mode

---

packages/frontend/src/components/AppRoute.tsx
packages/frontend/src/pages/login.tsx

fix: redirect user from login page if already authenticated

---

packages/frontend/src/hooks/useQueryResults.tsx

fix: only run valid queries

---

packages/frontend/package.json
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/hooks/useTimeAgo.ts

feat: display time when dashboard page was loaded

---

packages/frontend/src/components/ReactHookForm/SqlInput.tsx
packages/frontend/src/components/SqlRunner/SqlRunnerInput.tsx

fix: import and set Ace mode and theme

---

packages/backend/src/errors.ts
packages/backend/src/projectAdapters/dbtGitProjectAdapter.ts

fix: improve error messages when connection to git

---

packages/backend/src/database/database.ts
packages/backend/src/database/knexfile.ts
packages/backend/src/errors.ts
packages/backend/src/health.test.ts
packages/backend/src/health.ts

fix: return error when database hasnt been migrated

---

packages/frontend/src/App.tsx
packages/frontend/src/components/OnboardingSteps.tsx
packages/frontend/src/hooks/useOnboardingStatus.ts
packages/frontend/src/pages/Home.tsx
packages/frontend/src/types/Events.ts

feat: add onboarding steps page

---

packages/frontend/src/components/AppBar.tsx
packages/frontend/src/components/DashboardTiles/TileForms/ChartTileForm.tsx
packages/frontend/src/components/Home/LatestCard.tsx
packages/frontend/src/components/Home/LatestDashboards.tsx
packages/frontend/src/components/Home/LatestSavedCharts.tsx
packages/frontend/src/components/Home/SuccessfulOnboarding.tsx
packages/frontend/src/hooks/useProjects.ts
packages/frontend/src/hooks/useSpaces.ts
packages/frontend/src/pages/Home.tsx
packages/frontend/src/pages/SavedQueries.tsx

feat: add latest dashboards and saved charts in home page

---

.gitignore
packages/backend/package.json
packages/backend/src/api/projectRouter.ts
packages/backend/src/index.ts
packages/backend/src/logger.ts
packages/backend/src/morganMiddleware.ts
packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts
packages/backend/src/projectAdapters/dbtGitProjectAdapter.ts
packages/backend/src/projectAdapters/projectAdapter.ts
packages/backend/src/services/warehouseClients/warehouseClientFromCredentials.ts
yarn.lock

chore: add logger

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Github setup: create pull request template

---

packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseSettingsForm.tsx
packages/frontend/src/components/ProjectConnection/index.tsx
packages/frontend/src/components/ProjectTablesConfiguration/ProjectTablesConfiguration.tsx
packages/frontend/src/components/ReactHookForm/Form.tsx
packages/frontend/src/components/TableCalculationModal.tsx
packages/frontend/src/components/common/modal/BaseModal.tsx
packages/frontend/src/pages/Welcome.tsx
packages/frontend/src/pages/login.tsx
packages/frontend/src/providers/TrackingProvider.tsx
packages/frontend/src/types/Events.ts

n/a
- Add events to initial setup process
- Add events to forms ( only the ones using useForm )
- Refactor project form to not re-render so much. 
n/a

chore: add setup events

---

.env.fast-install
install.sh

#714
<*Add a description of the changes proposed in the pull request.*>
<*insert your gif/screenshot/loom recording here*>

fix: add env file for fast install script

---

packages/frontend/src/pages/CreateProjectSettings.tsx

#950
<*Add a description of the changes proposed in the pull request.*>
<*insert your gif/screenshot/loom recording here*>

fix: amend typo

---

packages/frontend/src/components/SqlRunner/SqlRunnerResultsTable.tsx

fix: add correct state when sql errored

---

packages/frontend/src/components/Explorer.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/components/common/EditableHeader.tsx
packages/frontend/src/components/common/EditableText.tsx
packages/frontend/src/hooks/useSavedQuery.ts
packages/frontend/src/pages/SavedExplorer.tsx

Closes: #909 
Edit saved chart name from explore page
<a href="https://www.loom.com/share/b98ca39f603541cc856a7402b01126db">
<p>Lightdash - Edit saved chart name from explore page - Watch Video</p>
</a>

feat: edit saved chart name from explore page

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/discussion.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature-request.md

n/a
- replace comments and note styling 
n/a

chore: replace comment and note styling

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/discussion.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature-request.md

n/a
- amend issue template metadata
n/a

chore: amend template metadata

---

packages/frontend/src/components/common/Page/Page.tsx
packages/frontend/src/pages/Dashboard.tsx

Closes: 
Fix regression bug that made dashboard page not full width

fix: make dashboard page full width

---

packages/frontend/package.json
packages/frontend/src/components/ExploreSideBar.tsx
packages/frontend/src/components/RefreshButton.tsx
packages/frontend/src/hooks/useProject.ts
packages/frontend/src/hooks/useRefreshServer.tsx
packages/frontend/src/hooks/useServerStatus.tsx
yarn.lock

Closes: #904 
Table navigation wasn't refreshing properly after a dbt refresh.
<a href="https://www.loom.com/share/2d04444e0fa944ac9c0f542d95f6d3fc">
<p>Lightdash - fix dbt refresh - Watch Video</p>
</a>

fix: refresh explore after project compiles

---

packages/backend/src/overrideUserPassword.ts

Closes: #1003 
Script to override user password.
This is a temporary solution.

feat: script to override user password

---

.github/CONTRIBUTING.md
packages/backend/package.json
packages/backend/src/config/parseConfig.ts
packages/backend/src/database/migrations/20211217101654_add_bitbucket.ts
packages/backend/src/projectAdapters/dbtBitBucketProjectAdapter.ts
packages/backend/src/projectAdapters/projectAdapter.ts
packages/common/src/index.ts
packages/frontend/src/components/ProjectConnection/DbtForms/BitBucketForm.tsx
packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx

Closes: #1004
Add BitBucket support

feat: add support for BitBucket

---

packages/backend/setupJest.ts
packages/backend/src/analytics/LightdashAnalytics.ts

feat: add lightdashMode to event context

---

packages/backend/src/api/projectRouter.ts
packages/backend/src/services/ProjectService/ProjectService.ts

Closes: #963 
Amend the caching mechanism so it doesn't compile multiple times.

fix: stop multiple project compiles

---

README.md
docs/docs/help-and-contact/contact/contact_info.md
docs/docs/help-and-contact/faqs/faqs.md

related to issue https://github.com/lightdash/lightdash-internal-work/issues/56
Directs users to github discussions for FAQs + contact.

docs: removes faqs and adds discussions to contact

---

packages/backend/package.json
packages/backend/tsconfig.json

fix: copy amazon certificate after build

---

dockerfile
dockerfile-prs
packages/backend/src/dbt/profiles.ts
packages/backend/src/dbt/translator.ts
packages/backend/src/queryBuilder.ts
packages/common/src/index.ts

fix: use databricks adapter instead of spark adapter

---

README.md

#966 
Adds tree planting for each GitHub star to readme.

Docs: adds tree planting to readme

---

README.md

Fixes header separation in readme

Docs: fixes header separation in readme

---

docs/docs/references/dimensions.md
docs/docs/references/metrics.md

Adds label property to metrics + dimensions docs.

Docs: Add labels to docs

---

docker/.env
dockerfile-prs
packages/backend/src/config/parseConfig.ts
packages/backend/src/health.ts
packages/backend/src/models/InviteLinkModel.ts
packages/backend/src/models/ProjectModel/ProjectModel.mock.ts
packages/backend/src/services/UserService.ts
packages/common/src/index.ts
packages/common/src/openapi/schemas/InviteLink.json
packages/common/src/openapibundle.json
packages/frontend/src/components/UserSettingsModal/InvitesPanel.tsx
packages/frontend/src/hooks/useInviteLink.tsx

Closes: 
Adds the `SITE_URL` parameter used to configure all links in the app.
Defaults to localhost but users will be warned not to use this in production

feat: add site url configuration

---

packages/frontend/src/components/common/AnchorLink/index.tsx
packages/frontend/src/pages/Login.tsx
packages/frontend/src/pages/PasswordRecovery.tsx
packages/frontend/src/pages/PasswordReset.tsx

Closes: 
This PR updates the style to mirror designs on the password recovery flow

Feat: password recovery ux

---

packages/frontend/src/pages/CreateProject.tsx

style: add page description and link to demo page

---

packages/backend/src/services/warehouseClients/SnowflakeWarehouseClient.test.ts
packages/backend/src/services/warehouseClients/SnowflakeWarehouseClient.ts

fix(#1127): fix variable type parsing in snowflake

---

packages/backend/src/dbt/translator.ts

fix: apply custom labels to time interval dimensions

---

packages/frontend/src/components/ProjectConnection/DbtForms/BitBucketForm.tsx
packages/frontend/src/components/ProjectConnection/DbtForms/DbtCloudForm.tsx
packages/frontend/src/components/ProjectConnection/DbtForms/DbtLocalForm.tsx
packages/frontend/src/components/ProjectConnection/DbtForms/GithubForm.tsx
packages/frontend/src/components/ProjectConnection/DbtForms/GitlabForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/BigQueryForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/DatabricksForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/PostgresForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/RedshiftForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/SnowflakeForm.tsx
packages/frontend/src/utils/fieldValidators.ts

fix: add field validation to project form

---

packages/frontend/src/pages/Home.tsx

fix(#1106): update copy on home page primary action

---

packages/backend/setupJest.ts
packages/backend/src/config/parseConfig.test.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/database/knexfile.ts
packages/backend/src/models/ProjectModel/ProjectModel.mock.ts

feat: customise pg pool size

---

packages/backend/src/index.ts
packages/common/src/openapi/openapi.json
packages/common/src/openapi/paths/login.json
packages/common/src/openapi/paths/organizationUsers.json
packages/common/src/openapi/schemas/LightdashUser.json
packages/common/src/openapi/schemas/Login.json
packages/common/src/openapibundle.json

fix(#619): add openapi validation in development mode

---

docker/docker-compose.dev.yml

chore: dont sync node modules in docker compose

---

packages/frontend/src/components/ProjectConnection/index.tsx

feat: show message that dbt project must be compatible with v1

---

.gitignore
package.json

chore: build common package on yarn dev

---

docs/docs/get-started/setup-lightdash/install-lightdash.mdx
install.sh
packages/frontend/src/components/ProjectConnection/DbtForms/DbtLocalForm.tsx
packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx

feat: remove project directory + improve docs

---

packages/backend/src/config/parseConfig.ts

chore: remove site url warning in dev

---

docs/docs/get-started/setup-lightdash/connect-project.mdx
docs/docs/get-started/setup-lightdash/install-lightdash.mdx
packages/frontend/src/components/ProjectConnection/DbtForms/DbtLocalForm.tsx

docs: improve docs for local dbt option

---

packages/frontend/src/pages/Login.tsx

fix: skip login on demo app

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/models/OpenIdIdentitiesModel.ts
packages/backend/src/routers/userRouter.ts
packages/backend/src/services/UserService.ts
packages/common/src/index.ts
packages/frontend/src/components/UserSettingsModal/SocialLoginsPanel.tsx
packages/frontend/src/hooks/user/useDeleteOpenIdentityMutation.ts

feat: revoke social auths

---

README.md
docs/docs/intro.md
docs/docs/references/environmentVariables.md
docs/docs/references/explores.md
docs/docs/references/syncing_your_dbt_changes.md

Closes: #1249 
Adds Explore reference page (and removes references of the product roadmap)

Docs: removes product roadmap and adds explores reference

---

packages/backend/src/routers/apiV1Router.ts
packages/backend/src/routers/savedChartRouter.ts

refactor: move saved charts api to router

---

docker/docker-compose.dev.yml
packages/backend/src/projectAdapters/projectAdapter.ts
packages/common/src/index.ts

fix: set default path to local dbt project

---

docs/docs/references/explores.md

Fixes subheading in the explores reference doc

Docs: update explores.md

---

packages/backend/src/queryBuilder.ts

fix: add missing parentheses in string equals filter

---

packages/frontend/src/components/Explorer.tsx

fix: remove primary colour from save chart buttons

---

CHANGELOG.md
package.json
packages/backend/package.json
packages/common/package.json
packages/e2e/package.json
packages/frontend/package.json

build: release 0.12.1

---

packages/backend/src/queryBuilder.mock.ts
packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts
packages/common/package.json
packages/common/src/index.ts
packages/common/src/types/filter.ts
packages/frontend/src/components/Explorer.tsx
packages/frontend/src/components/TableTree.tsx
packages/frontend/src/components/common/Filters/FieldAutoComplete.tsx
packages/frontend/src/components/common/Filters/FilterGroupForm.styles.tsx
packages/frontend/src/components/common/Filters/FilterGroupForm.tsx
packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
packages/frontend/src/components/common/Filters/FilterRuleForm.tsx
packages/frontend/src/components/common/Filters/SimplifiedFilterGroupForm.tsx
packages/frontend/src/components/common/Filters/configs.ts
packages/frontend/src/components/common/Filters/index.tsx
packages/frontend/src/hooks/useFilters.ts

Closes: #186 
- add metric filter
- add metric filter from sidebar

feat(#186): add metric filters

---

packages/frontend/src/components/UserSettingsModal/InvitesPanel/index.tsx

Updates the revoke invitation action text.

fix: updates revoke invites text

---

.github/CONTRIBUTING.md

fixes broken link to community in contributions.md

Docs: update CONTRIBUTING.md

---

.github/workflows/validate-pr-title.yml

Related: https://github.com/lightdash/lightdash/pull/1292
Adds a check to validate that the title of the PR conforms to [Conventional Commits standard](https://www.conventionalcommits.org/en/v1.0.0/).

ci: Validate that the PR title conforms to Conventional Commits standard. 

---

packages/frontend/src/components/SimpleStatistic/index.tsx
packages/frontend/src/components/SimpleTable/index.tsx
packages/frontend/src/utils/bigNumberConfig.ts

Closes: #1296 
This PR fixes error on big numbers assuming that data is always present.

fix: fatal error when results are empty

---

.github/workflows/release-on-merge.yml
release.config.js

Follow up to https://github.com/lightdash/lightdash/pull/1306, where semantic-release was not updating "common" dependency version. 
https://github.com/lightdash/lightdash/actions/runs/1813759283
https://github.com/lightdash/lightdash/commit/981e7ce1d72ca565b311dcb9e3142cba9b2a8fba:

ci(semantic-release): increment common version in package.jsons

---

packages/backend/src/queryBuilder.mock.ts
packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts
packages/common/src/index.ts
packages/common/src/types/filter.ts
packages/frontend/src/components/common/Filters/FilterGroupForm.tsx
packages/frontend/src/components/common/Filters/SimplifiedFilterGroupForm.tsx
packages/frontend/src/components/common/Filters/index.tsx

Closes: #188 
<a href="https://www.loom.com/share/5b9db953edca40bf95643ae4a0afb01b">
<p>Lightdash - OR filter operator - Watch Video</p>
</a>
Tooltip message:

feat: add filter operator OR

---

packages/backend/src/queryBuilder.ts
packages/common/src/types/filter.ts
packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
packages/frontend/src/components/common/Filters/FilterInputs/UnitOfTimeAutoComplete.tsx
packages/frontend/src/components/common/Filters/configs.ts

Closes: #572
<a href="https://www.loom.com/share/b84cae7743d847c983b5677346734a42">
<p>Lightdash - completed date in filter - Watch Video</p>
</a>

feat: completed unit of time in filter

---

packages/backend/src/database/entities/savedQueries.ts
packages/backend/src/database/seeds/development/02_saved_queries.ts
packages/backend/src/routers/savedChartRouter.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/services.ts
packages/common/src/index.ts
packages/common/src/openapi/openapi.json
packages/common/src/openapi/paths/savedChart.json
packages/common/src/openapi/paths/savedChartFilters.json
packages/common/src/openapi/schemas/ChartConfig.json
packages/common/src/openapi/schemas/Field.json
packages/common/src/openapi/schemas/Fields.json
packages/common/src/openapi/schemas/SavedChart.json
packages/common/src/openapibundle.json
packages/frontend/src/hooks/dashboard/useDashboard.tsx

feat: add endpoint to fetch available filters [skip ci]

---

packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
packages/frontend/src/components/common/MonthAndYearInput.tsx
packages/frontend/src/components/common/YearInput.tsx

Closes: [#1219](https://github.com/lightdash/lightdash/issues/1219)
<a href="https://www.loom.com/share/5b74cd099a6a4abb96aeffa7121543bc">
<p>Loom Message - 9 February 2022 - Watch Video</p>
</a>

feat(filters): add month and year picker

---

packages/backend/src/routers/apiV1Router.ts

feat(api): add liveness endpoint

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/index.ts
packages/common/src/types/filter.ts
packages/frontend/src/App.tsx
packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilters.styles.ts
packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
packages/frontend/src/components/DashboardFilter/DashboardFilter.styles.tsx
packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterConfiguration.styled.tsx
packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
packages/frontend/src/components/DashboardFilter/FilterSearch/FilterSearch.styles.tsx
packages/frontend/src/components/DashboardFilter/FilterSearch/index.tsx
packages/frontend/src/components/DashboardFilter/index.tsx
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/UserSettingsModal/OrganisationPanel/index.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.styles.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/components/common/Filters/FieldAutoComplete.tsx
packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
packages/frontend/src/components/common/Filters/FilterInputs/FilterInputs.styles.tsx
packages/frontend/src/components/common/Filters/configs.ts
packages/frontend/src/hooks/dashboard/useDashboard.tsx
packages/frontend/src/hooks/useQueryResults.tsx
packages/frontend/src/pages/Dashboard.tsx
packages/frontend/src/providers/DashboardProvider.tsx

Closes: #1273 #1274 
This PR adds part of the UI for the dashboard filters
And allows the possibility to edit them from the active filters tags
https://www.loom.com/share/030d99aa39cb4f3d8f4eb8420c18b580

feat(dashboards): add dashboard filters

---

packages/backend/src/morganMiddleware.ts

fix: show http logs in production envs

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer.tsx
packages/frontend/src/components/LightdashVisualization/index.tsx

Closes: #1320
The explore page was using a useChartConfig hook an the chart component was using another useChartConfig hook. So the changes from the explore page weren't affecting the chart.
<a href="https://www.loom.com/share/e095777b192b45c99325ba217f6dcac9">
<a href="https://www.loom.com/share/e095777b192b45c99325ba217f6dcac9">
<p>Lightdash - 10 February 2022 - Watch Video</p>
</a>

fix(charts): amend chart configuration

---

packages/frontend/src/providers/DashboardProvider.tsx

Closes: #1330
<a href="https://www.loom.com/share/49c7157fc8f44f3a91b696cfbe291b29">
<p>Notification Centre - Notification Center - 10 February 2022 - Watch Video</p>
</a>

feat(dashboards): store filters in dashboard url [skip ci]

---

packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterConfiguration.styled.tsx
packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx

Closes: #1331 
This PR fixes the styling when there are multiple fields in the filter config modal.

style: Bad styling in dashboard filters for month filter

---

packages/backend/jest.config.js
packages/backend/package.json
packages/backend/src/queryBuilder.mock.ts
packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts
yarn.lock

Closes: #1316
If I want to see daily active users for the past 5 years and I run this query on the 4th July 2022.
You expect to see a time series: starting from 4th July 2017 -> 4th July 2022 (5 years of data)

fix(filters): dont format in the last date by default

---

packages/backend/src/index.ts
packages/backend/src/services/warehouseClients/BigqueryWarehouseClient.ts

chore: add logs when fecthing bigquery catalog and improve error messages

---

packages/backend/src/projectAdapters/dbtGitProjectAdapter.ts

fix: remove sparse checkout

---

packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilter.tsx
packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
packages/frontend/src/utils/resultFormatter.tsx

Closes: #1332
Show filter label with the correct:
- operator label
- formatted values

fix(dashboards): amend filter label

---

docs/docs/get-started/setup-lightdash/add-metrics.mdx
docs/docs/get-started/setup-lightdash/connect-project.mdx
docs/docs/get-started/setup-lightdash/install-lightdash.mdx
docs/docs/get-started/setup-lightdash/new-to-dbt.mdx
install.sh

docs: improve self-host instructions

---

dockerfile
packages/backend/src/projectAdapters/dbtGitProjectAdapter.ts

Fix: revert docker changes

---

packages/backend/src/projectAdapters/dbtGitProjectAdapter.ts

fix: update error message

---

docs/docs/best-practice/lightdash-way.md
docs/docs/best-practice/planning-your-dashboard.md

Fixes formatting for sidebar positioning in the tutorials docs

docs: fix tutorials formatting

---

packages/frontend/src/components/UserSettingsModal/OrganisationPanel/index.tsx

fix(settings): amend allowed email domains input

---

packages/frontend/src/App.tsx
packages/frontend/src/components/NavBar/BrowseMenu/index.tsx
packages/frontend/src/components/NavBar/ExploreMenu/index.tsx
packages/frontend/src/components/NavBar/HelpMenu/HelpMenu.styles.tsx
packages/frontend/src/components/NavBar/HelpMenu/index.tsx
packages/frontend/src/components/NavBar/NavBar.styles.tsx
packages/frontend/src/components/NavBar/index.tsx

Closes: #1351 
This PR adds a help menu in the nav bar, it also refactors a bit the component to extract each of the menus into their own directory. and migrates each component to styled components.

feat: add help button in nav bar

---

docker-compose.yml

Make it harder to unintentionally destroy the db
- tooling/docs (I guess?)

build: add named db volume to the docker-compose

---

packages/frontend/src/components/AboutFooter.tsx

Closes: 
The URL Link for how to update Lightdash was for a deprecated page. Updated

fix: update URL link in app to update Lightdash version

---

docs/docs/get-started/setup-lightdash/connect-project.mdx
packages/backend/src/dbt/profiles.ts
packages/common/src/index.ts
packages/frontend/src/components/ProjectConnection/WarehouseForms/RedshiftForm.tsx

feat: add ra3 node option to redshift dbt profiles

---

docs/docs/get-started/setup-lightdash/connect-project.mdx
packages/backend/src/config/parseConfig.ts
packages/backend/src/database/migrations/20220216151820_add_azure_devops.ts
packages/backend/src/projectAdapters/dbtAzureDevOpsProjectAdapter.ts
packages/backend/src/projectAdapters/dbtGitProjectAdapter.ts
packages/backend/src/projectAdapters/projectAdapter.ts
packages/common/src/index.ts
packages/frontend/src/components/ProjectConnection/DbtForms/AzureDevOpsForm.tsx
packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx

feat: add azure devops option for dbt projects

---

packages/backend/src/config/parseConfig.ts
packages/backend/src/projectAdapters/dbtGithubProjectAdapter.ts
packages/backend/src/projectAdapters/projectAdapter.ts
packages/common/src/index.ts
packages/frontend/src/components/ProjectConnection/DbtForms/GithubForm.tsx

feat: add host domain for github enterprise connections

---

packages/backend/package.json
packages/backend/src/index.ts
packages/backend/src/routers/projectRouter.ts
packages/common/src/openapi/paths/projectCatalog.json
packages/common/src/openapi/paths/projectSqlQuery.json
packages/common/src/openapi/schemas/ChartConfig.json
packages/common/src/openapi/schemas/CreateDashboard.json
packages/common/src/openapi/schemas/CreateDashboardTile.json
packages/common/src/openapi/schemas/Dashboard.json
packages/common/src/openapi/schemas/DashboardFilterRule.json
packages/common/src/openapi/schemas/DashboardFilters.json
packages/common/src/openapi/schemas/DashboardListItem.json
packages/common/src/openapi/schemas/LightdashUser.json
packages/common/src/openapi/schemas/LoomTileProperties.json
packages/common/src/openapi/schemas/MarkdownTileProperties.json
packages/common/src/openapi/schemas/SavedChart.json
packages/common/src/openapi/schemas/UpdateDashboard.json
packages/common/src/openapibundle.json
packages/frontend/src/hooks/dashboard/useDashboard.tsx
packages/frontend/src/pages/SavedDashboards.tsx
yarn.lock

Closes: 
- enable open api validation
- throws errors if request body isn't valid
- logs warning when response body isn't valid ( so it isn't a blocker for developers and we can incrementally fix them ) 
- only validates documented endpoints

chore: enable open api validation

---

packages/common/src/index.ts
packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilter.tsx
packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilters.styles.ts
packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
packages/frontend/src/components/DashboardFilter/DashboardFilter.styles.tsx
packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterConfiguration.styled.tsx
packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
packages/frontend/src/components/DashboardFilter/index.tsx
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.styles.tsx
packages/frontend/src/components/common/Filters/configs.ts

style: ui/ux improvements in dashboard page

---

packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx

fix: dashboard filter error causing blank page

---

dockerfile
dockerfile-prs

fix: bump dbt version

---

packages/frontend/src/components/DashboardFilter/index.tsx
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer.tsx
packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
packages/frontend/src/components/common/Filters/FilterInputs/StringAutoComplete.tsx
packages/frontend/src/components/common/Filters/FiltersProvider.tsx
packages/frontend/src/components/common/Filters/index.tsx
packages/frontend/src/hooks/dashboard/useDashboard.tsx
packages/frontend/src/providers/DashboardProvider.tsx

Closes: #920 
Add suggestions to filters in the explore.
Add suggestions to dashboard filters.
<a href="https://www.loom.com/share/17619f02ddc5473eac624729f4df0a9c">
<p>Lightdash - filter suggestions - Watch Video</p>
</a>
<a href="https://www.loom.com/share/b0afbdc1837d47c8b88b11fa829c655d">
<p>Lightdash - suggestions in dashboard filters - Watch Video</p>
</a>

feat(filters): add suggestions for string filters

---

packages/backend/src/database/entities/savedQueries.ts
packages/backend/src/database/migrations/20220127154726_add_chart_type_for_table.ts
packages/backend/src/database/migrations/20220131144706_add_big_number_chart_type.ts
packages/backend/src/database/migrations/20220222155435_alter_chart_configuration.ts

* Migrations ✅ 
* Read saved chart ✅ 
* Write saved chart ✅ 
Closes: #1434
Closes: #1441

refactor: update how we store chart config [skip ci]

---

packages/frontend/src/components/ResultsTable/ResultsTable.styles.tsx
packages/frontend/src/components/ResultsTable/ResultsTable.tsx

Closes: 
- set row number column with fixed width
- add bottom border
- align elements inside header

style(results): change header alignment + add missing border

---

packages/frontend/src/components/AddColumnButton.tsx
packages/frontend/src/components/DownloadCsvButton/index.tsx
packages/frontend/src/components/Explorer.tsx
packages/frontend/src/components/Explorer/ExplorerResults.tsx
packages/frontend/src/components/LimitButton/LimitButton.styles.ts
packages/frontend/src/components/LimitButton/index.tsx
packages/frontend/src/components/ResultsTable/ResultsTable.styles.tsx
packages/frontend/src/components/ResultsTable/ResultsTable.tsx
packages/frontend/src/components/common/SimpleButton.tsx
packages/frontend/src/providers/ExplorerProvider.tsx

Resolves #1439, resolves #1437, resolves #1396, resolves #1447
<a href="https://www.loom.com/share/0fc4ac8376414649a83aa0984dfa1272">
<p>Lightdash - 25 February 2022 - Watch Video</p>
</a>

feat(results): scroll all results + ux improvements

---

.all-contributorsrc

chore: all contributors commits should skip ci

---

packages/frontend/src/components/Explorer/ExplorerResults.tsx
packages/frontend/src/components/ResultsTable/ResultsTable.styles.tsx
packages/frontend/src/components/ResultsTable/ResultsTable.tsx

Closes: #1451 
Change table component so it doesn't depend on the explorer provider.

fix(sql_runner): amend missing provider

---

.github/CONTRIBUTING.md

docs: correct typos 

---

packages/common/src/index.ts
packages/frontend/src/components/ResultsTable/CellContextMenu.tsx

Closes: #1457 
<a href="https://www.loom.com/share/e9e18e2ac53d4422be4cafac0cd4d712">
<p>Lightdash 🔊 - 25 February 2022 - Watch Video</p>
</a>

fix(filters): filter by null

---

packages/backend/src/dbt/dbtCliClient.ts

fix: use dbt target-path value

---

packages/common/src/openapi/schemas/CreateUser.json
packages/common/src/openapibundle.json
packages/frontend/src/components/NavBar/index.tsx
packages/frontend/src/components/UserSettingsModal/index.tsx

feat: add invite user action to avatar

---

dockerfile
dockerfile-prs

Continuation of https://github.com/lightdash/lightdash/pull/1361 and https://github.com/lightdash/lightdash/pull/1370
Adds python into the runtime OS. 
Fixes this issue: where /usr/bin/entrypoint.sh (from jaffle fails to execute).

refactor: dockerfile optimized for smaller build

---

packages/frontend/src/components/Explorer/ExplorePanel/ExplorePanel.styles.ts
packages/frontend/src/components/Explorer/ExplorePanel/index.tsx

style: adjust title padding on explorer sidebar

---

packages/common/src/openapi/schemas/SavedChart/ChartConfig/ChartAxis.json
packages/common/src/openapi/schemas/SavedChart/ChartConfig/ChartConfigCartesian.json
packages/common/src/types/savedCharts.ts
packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
packages/frontend/src/hooks/useCartesianChartConfig.ts
packages/frontend/src/hooks/useEcharts.ts

feat(charts): option to rename chart axes

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/models/DashboardModel/DashboardModel.test.ts
packages/backend/src/models/DashboardModel/DashboardModel.ts
packages/backend/src/services/DashboardService/DashboardService.test.ts
packages/backend/src/services/DashboardService/DashboardService.ts
packages/backend/src/services/SavedChartsService/SavedChartService.ts

chore: improve dashboard and saved chart events

---

packages/frontend/src/hooks/useEcharts.ts

fix(charts): get axis type from valid field key

---

packages/frontend/src/hooks/useEcharts.ts

Closes: 
- Set correct type when field is a table calculation 
- Set correct axis types when axis are flipped

fix: set correct axis type

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/pages/Dashboard.tsx
packages/frontend/src/types/Events.ts

This PR adds tracking to the filters that added from clicking on the bars in a chart.

chore: add section tracking wrapper to dashboard tiles

---

packages/common/src/index.ts
packages/frontend/src/components/ChartConfigPanel/ChartConfigPanel.styles.ts
packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
packages/frontend/src/components/ChartConfigPanel/FieldLayoutOptions.tsx
packages/frontend/src/components/ChartConfigPanel/SeriesColorPicker.tsx
packages/frontend/src/components/ChartConfigPanel/index.tsx
packages/frontend/src/components/common/Filters/FieldAutoComplete.tsx
packages/frontend/src/hooks/useCartesianChartConfig.ts
packages/frontend/src/hooks/useEcharts.ts

Closes: [#1510](https://github.com/lightdash/lightdash/issues/1510)
Marking this PR as `fix` instead of `style` since it is quite a big change in the UI/UX.
<a href="https://www.loom.com/share/54bf6f75e5284ed78f314a957f892663">
<p>Lightdash - 7 March 2022 - Watch Video</p>
</a>

fix(charts): redesign chart configuration panel

---

packages/frontend/src/components/UserSettingsModal/OrganisationPanel/index.tsx
packages/frontend/src/utils/fieldValidators.ts

Closes: #1506 
<a href="https://www.loom.com/share/979c1167072e4f98a3056e7d54c20ae4">
<p>Lightdash - 8 March 2022 - Watch Video</p>
</a>

fix: add validation to email domains input field

---

packages/backend/src/index.ts

Closes: #280, closes: #1248 
https://github.com/expressjs/session#rolling

fix: refresh cookie expire date on user interaction

---

packages/frontend/src/hooks/useEcharts.ts

fix(charts): allow value/value axis for charts that are not bars

---

packages/backend/src/dbt/translator.ts

fix: add column details to missing column error

---

packages/frontend/package.json
packages/frontend/src/components/DashboardTiles/TileForms/MarkdownTileForm.tsx
yarn.lock

Closes: #1446 
<a href="https://www.loom.com/share/8179392d4c5b46d0bc9da2eb1df4f909">
<p>Lightdash - 9 March 2022 - Watch Video</p>
</a>

fix(dashboards): fix scroll after adding markdown tile

---

.github/ISSUE_TEMPLATE/feature-request.md

Removes some of the questions in the issue template to make it shorter.

chore: update issue template

---

docs/docs/references/dimensions.md
docs/docs/references/metrics.md

#1541 
Adds docs on hidden parameter for metrics + dimensions.

docs: adds hidden label

---

packages/frontend/src/hooks/useEcharts.ts

fix(charts): pivot by date

---

packages/backend/src/config/parseConfig.mock.ts
packages/backend/src/config/parseConfig.test.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/models/ProjectModel/ProjectModel.mock.ts
packages/backend/src/services/HealthService/HealthService.mock.ts

refactor: remove project definitions from lightdash.yml

---

packages/backend/src/dbt/translator.ts

fix: error message for wrong dimension type

---

packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/frontend/src/components/ProjectConnection/DbtForms/AzureDevOpsForm.tsx
packages/frontend/src/components/ProjectConnection/DbtForms/BitBucketForm.tsx
packages/frontend/src/components/ProjectConnection/DbtForms/DbtCloudForm.tsx
packages/frontend/src/components/ProjectConnection/DbtForms/GithubForm.tsx
packages/frontend/src/components/ProjectConnection/DbtForms/GitlabForm.tsx
packages/frontend/src/components/ProjectConnection/ProjectFormProvider.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/BigQueryForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/DatabricksForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/PostgresForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/RedshiftForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/SnowflakeForm.tsx
packages/frontend/src/components/ProjectConnection/index.tsx
packages/frontend/src/components/ReactHookForm/FileInput.tsx
packages/frontend/src/hooks/useProject.ts

Closes: [#623](https://github.com/lightdash/lightdash/issues/623)

fix: dont require project secrets on edit

---

packages/frontend/src/components/Home/LatestDashboards/index.tsx
packages/frontend/src/components/Home/LatestSavedCharts/index.tsx

fix: add missing key to homepage

---

packages/backend/src/projectAdapters/dbtAzureDevOpsProjectAdapter.ts
packages/backend/src/projectAdapters/dbtBitBucketProjectAdapter.ts
packages/backend/src/projectAdapters/dbtGitProjectAdapter.ts
packages/backend/src/projectAdapters/dbtGithubProjectAdapter.ts
packages/backend/src/projectAdapters/dbtGitlabProjectAdapter.ts
packages/backend/src/projectAdapters/dbtLocalCredentialsProjectAdapter.ts
packages/backend/src/projectAdapters/projectAdapter.ts
packages/common/src/index.ts
packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx
packages/frontend/src/components/ReactHookForm/MultiKeyValuePairsInput.styles.ts
packages/frontend/src/components/ReactHookForm/MultiKeyValuePairsInput.tsx

Closes: #801 
Closes: #1421  
**Todo**

feat: add configurable environment variables for dbt project

---

packages/frontend/src/components/UserSettingsModal/ProjectManagementPanel/index.tsx
packages/frontend/src/hooks/useProjects.ts

Closes:#1561
Add frontend wrappers to delete projects

feat: add delete project frontend

---

packages/frontend/src/components/ChartConfigPanel/ChartConfigPanel.styles.ts
packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
packages/frontend/src/components/ChartConfigPanel/Series/BasicSeriesConfiguration.tsx
packages/frontend/src/components/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
packages/frontend/src/components/ChartConfigPanel/Series/Series.styles.ts
packages/frontend/src/components/ChartConfigPanel/Series/SeriesColorPicker.tsx
packages/frontend/src/components/ChartConfigPanel/Series/SingleSeriesConfiguration.tsx
packages/frontend/src/components/ChartConfigPanel/SeriesColorPicker.tsx
packages/frontend/src/hooks/useCartesianChartConfig.ts

Closes: #1565
<a href="https://www.loom.com/share/b5daf832859c46988b2376d9e4919a8c">
<p>Gather - lightdash | Gather - 25 March 2022 - Watch Video</p>
</a>

feat(charts): configure grouped series

---

packages/common/src/index.ts
packages/common/src/types/savedCharts.ts
packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
packages/frontend/src/components/ChartConfigPanel/Series/BasicSeriesConfiguration.tsx
packages/frontend/src/components/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
packages/frontend/src/components/ChartConfigPanel/Series/SingleSeriesConfiguration.tsx
packages/frontend/src/hooks/useCartesianChartConfig.ts
packages/frontend/src/hooks/useEcharts.ts

Closes: #81 
<a href="https://www.loom.com/share/d127b97093614b75a77c809032481046">
<p>Lightdash - multiple y axis - Watch Video</p>
</a>

feat(charts): support multiple y axis

---

packages/frontend/src/components/ChartConfigPanel/ChartConfigPanel.styles.ts
packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
packages/frontend/src/components/ChartConfigPanel/FieldLayoutOptions.tsx
packages/frontend/src/components/ChartConfigPanel/Series/BasicSeriesConfiguration.tsx
packages/frontend/src/components/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
packages/frontend/src/components/ChartConfigPanel/Series/Series.styles.ts
packages/frontend/src/components/ChartConfigPanel/Series/SingleSeriesConfiguration.tsx
packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
packages/frontend/src/hooks/useCartesianChartConfig.ts
packages/frontend/src/hooks/useEcharts.ts

Closes: #819 
<a href="https://www.loom.com/share/2a6e48c0ccda4039a14b02f22817d3ad">
<p>Lightdash - multiple chart types - Watch Video</p>
</a>

feat(charts): support multiple chart types

---

packages/frontend/src/hooks/useEcharts.ts

fix: top axis name

---

packages/frontend/src/components/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
packages/frontend/src/hooks/useEcharts.ts

fix(charts): default label for single grouped metric

---

packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx

Fixes a bug on chart, when selecting the color, it was not changing, overrided by the organization chart colors

fix: fix series color picker on charts

---

.github/docs/Tracking.md

docs: add tracking docs

---

packages/frontend/src/hooks/useEcharts.ts

fix: remove double label from horizontal charts

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/services/ProjectService/ProjectService.ts

Closes: https://github.com/lightdash/lightdash-internal-work/issues/240
Add formattedFieldsCount to ligthdash analytics

feat: add analytics for formatted fields

---

packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
packages/frontend/src/components/ChartConfigPanel/Series/BasicSeriesConfiguration.tsx
packages/frontend/src/components/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
packages/frontend/src/components/ChartConfigPanel/Series/SingleSeriesConfiguration.tsx

fix: automatically collapse series UI when expanding another

---

packages/common/src/types/savedCharts.ts
packages/frontend/src/components/ChartConfigPanel/Series/Series.styles.ts
packages/frontend/src/components/ChartConfigPanel/Series/SingleSeriesConfiguration.tsx
packages/frontend/src/hooks/useEcharts.ts

Closes: #1620
Hide series on chart config

feat: add hide series on chart config

---

packages/frontend/src/components/Explorer.tsx
packages/frontend/src/hooks/dashboard/useDashboards.tsx

Closes: #1631
Add frontend with warning

feat: warn dashboards on chart deletion

---

packages/frontend/src/components/Explorer.tsx

Closes: #1703
Save changes also on filter changes / column sort, etc

fix: allow saving changes when filters or table config happens

---

packages/common/src/index.ts

feat: add eur to formatter

---

packages/frontend/src/App.styles.tsx
packages/frontend/src/App.tsx

fix: make sql autocomplete box wider

---

packages/frontend/src/components/Explorer.tsx

Closes: #1699
Link to dashboard

feat: link to dashboard on remove popup

---

dockerfile-prs
examples/full-jaffle-shop-demo/renderDeployHook.sh
render.yaml

build: move init script to render deploy hook for PR previews

---

packages/frontend/src/hooks/useBigNumberConfig.ts

Closes: #1731
Fixes a white screen that happened when adding a filter returned no results 
The error
My fix

fix: fix dashboard crash filter

---

packages/frontend/src/pages/CreateProject.tsx

fix: correct typo on the create project page

---

packages/frontend/src/components/NavBar/HelpMenu/HelpMenu.styles.tsx
packages/frontend/src/components/NavBar/HelpMenu/index.tsx
packages/frontend/src/providers/AppProvider.tsx

Closes: https://github.com/lightdash/lightdash-internal-work/issues/264
Add headway widget to header

feat: headway widget

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/services/ProjectService/ProjectService.ts

Closes: [](https://github.com/lightdash/lightdash-internal-work/issues/258)
add project name in project_compiled analytics event

feat: add projectName to project compiled analytics

---

packages/frontend/src/hooks/useBigNumberConfig.ts

Closes: #1789
Remove frinedlyname from bignumber value

fix: remove friendlyname from bignumber value

---

packages/e2e/cypress.json
packages/e2e/cypress/integration/explore.spec.ts
packages/e2e/cypress/support/commands.ts

test: add e2e save chart test

---

packages/e2e/cypress.json
packages/e2e/cypress/integration/login.spec.ts
packages/e2e/cypress/integration/savedDashboards.spec.ts

Fix broken savedashboard e2e tests

test: fix e2e savedashboards test

---

packages/frontend/src/components/TableTree.tsx

Closes: #1807
remove add metric link

feat: remove add metric link

---

docs/docs/references/dimensions.md

docs: update dimensions.md code snippet

---

packages/backend/src/database/seeds/development/03_saved_dashboards.ts
packages/backend/src/models/DashboardModel/DashboardModel.ts
packages/common/src/types/dashboard.ts

fix: format UUID in seed

---

packages/frontend/src/components/NavBar/HelpMenu/index.tsx

Closes: #1812 
This PR makes sure window has loaded before initialising Headway

fix: make sure window has mounted before initilizing Headway

---

packages/backend/src/database/seeds/development/02_saved_queries.ts
packages/common/src/index.ts

fix: handle table calcs in results formatter

---

packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
packages/frontend/src/components/TableTree.tsx

fix: make field search more strict with fuse options

---

packages/frontend/src/components/Explorer.tsx
packages/frontend/src/components/Explorer/ExplorerResults.tsx
packages/frontend/src/components/RefreshButton.tsx
packages/frontend/src/hooks/useQueryResults.tsx
packages/frontend/src/providers/ExplorerProvider.tsx

Closes: 
- move query results to explorer provider
- change from useQuery too useMutation

refactor: query results hook

---

docs/docs/get-started/setup-lightdash/connect-project.mdx

docs: update docs on bigquery permissions

---

packages/frontend/src/components/Explorer.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/hooks/useCartesianChartConfig.ts
packages/frontend/src/providers/ExplorerProvider.tsx

Closes: 
- move pivot state into provider
- move chart type and config into provider

refactor: move states into explorer provider

---

packages/frontend/src/hooks/useCartesianChartConfig.ts

chore: remove artifact

---

docs/docs/get-started/setup-lightdash/connect-project.mdx

Updates warehouse connection docs with the best descriptions from all the docs for similar fields!

docs: updates connection docs

---

docs/docs/get-started/setup-lightdash/connect-project.mdx

#1842 #1841 #1840 
Updates dbt project connection docs.

docs: updates dbt project connection docs

---

packages/backend/src/database/entities/savedCharts.ts
packages/backend/src/database/migrations/20220420124003_add_description_to_saved_chart.ts
packages/backend/src/database/seeds/development/02_saved_queries.ts
packages/backend/src/models/DashboardModel/DashboardModel.mock.ts
packages/backend/src/models/SavedChartModel.ts
packages/common/src/openapi/schemas/SavedChart/CreateSavedChart.json
packages/common/src/openapi/schemas/SavedChart/SavedChart.json
packages/common/src/openapibundle.json
packages/common/src/types/savedCharts.ts
packages/frontend/src/components/SavedQueries/CreateSavedQueryModal.tsx
packages/frontend/src/components/SavedQueries/SavedQueries.style.tsx
packages/frontend/src/hooks/useCartesianChartConfig.ts

Closes: #1679 
This PR adds a description field to the create chart modal.

feat: add description field to create chart modal

---

packages/frontend/src/components/Explorer.tsx
packages/frontend/src/hooks/useCompiledSql.tsx
packages/frontend/src/hooks/useExplorerRoute.ts
packages/frontend/src/hooks/useQueryResults.tsx
packages/frontend/src/pages/SavedExplorer.tsx
packages/frontend/src/providers/ExplorerProvider.tsx

Closes: 
- remove redundant property. All existing table calculations are "selected"

refactor: remove selected table calculations property

---

packages/backend/src/database/entities/projects.ts
packages/backend/src/database/migrations/20220420075732_cache_compiled_project.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/index.ts

feat: cache explores in db

---

packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
packages/frontend/src/components/RefreshButton.tsx

Closes: #1822 
This PR allows for Lightdash to keep on being functional while a refresh dbt is happening
[](https://www.loom.com/share/91f67fad921742f2b3cd7ca8d1cfae9f)

feat: allow user to keep using lightdash while it is refreshing

---

packages/frontend/src/components/common/ActionCard.tsx
packages/frontend/src/hooks/useSavedQuery.ts
packages/frontend/src/hooks/useTimeAgo.ts

Closes: #1818
Removes delay on moment

fix: updated chart delay

---

packages/common/src/openapi/openapi.json
packages/common/src/openapi/paths/job.json
packages/common/src/openapi/schemas/Job.json
packages/common/src/openapi/schemas/Step.json
packages/common/src/openapibundle.json

Closes:  #1872
API design for compile jobs

feat: add openapi docs

---

packages/frontend/src/components/RefreshButton.tsx
packages/frontend/src/hooks/useDefaultSortField.tsx
packages/frontend/src/providers/ExplorerProvider.tsx

refactor: move default sorting to provider

---

docs/docs/get-started/setup-lightdash/connect-project.mdx

fixes description on data location

updates data location docs

---

packages/frontend/src/hooks/user/useUserCompleteMutation.ts

Closes: #1333
<a href="https://www.loom.com/share/3947e170ab98421fa2a68e9efcfab183">
<p>Gather - lightdash | Gather - 26 April 2022 - Watch Video</p>
</a>

fix: refresh user permissions after register

---

packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx

Closes: 
Table visualization was displaying pivoted results when pivoting is only supported on charts for now.

fix: table visualization pivot

---

packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx

fix: revert change to pivotDimensions

---

packages/backend/src/@types/knex-tables.d.ts
packages/backend/src/database/entities/projects.ts
packages/backend/src/database/migrations/20220425072608_cache_warehouse.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/projectAdapters/dbtAzureDevOpsProjectAdapter.ts
packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts
packages/backend/src/projectAdapters/dbtBitBucketProjectAdapter.ts
packages/backend/src/projectAdapters/dbtCloudIdeProjectAdapter.ts
packages/backend/src/projectAdapters/dbtGitProjectAdapter.ts
packages/backend/src/projectAdapters/dbtGithubProjectAdapter.ts
packages/backend/src/projectAdapters/dbtGitlabProjectAdapter.ts
packages/backend/src/projectAdapters/dbtLocalCredentialsProjectAdapter.ts
packages/backend/src/projectAdapters/dbtLocalProjectAdapter.ts
packages/backend/src/projectAdapters/projectAdapter.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/types.ts

Closes: #1803
Cache entire data warehouse schema

feat: cache warehouse

---

packages/frontend/src/components/TableTree.tsx
packages/frontend/src/providers/ExplorerProvider.tsx
packages/frontend/src/providers/TrackingProvider.tsx
packages/frontend/src/types/Events.ts

Closes: 
<a href="https://www.loom.com/share/c61ede221d22404cbeafddd4492aef8e">
<p>Lightdash - remove custom metric - Watch Video</p>
</a>

feat: remove custom metric option

---

packages/backend/src/queryBuilder.ts
packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx
packages/frontend/src/hooks/useExplorerAceEditorCompleter.tsx

feat: use custom metric in filters and table calculations

---

docker/.env
packages/backend/src/index.ts

Closes: https://github.com/lightdash/lightdash-internal-work/issues/305

chore: limit sentry errors

---

packages/frontend/src/components/ResultsTable/ColumnHeaderContextMenu.tsx
packages/frontend/src/components/TableTree.tsx

feat: deselect columns on results

---

packages/backend/src/@types/knex-tables.d.ts
packages/backend/src/database/entities/jobs.ts
packages/backend/src/database/entities/projects.ts
packages/backend/src/database/migrations/20220428071116_job_steps.ts
packages/backend/src/models/JobModel/JobModel.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/models/models.ts
packages/backend/src/routers/organizationRouter.ts
packages/backend/src/routers/projectRouter.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/services.ts
packages/common/src/types/job.ts

Closes: #1918
Add steps to Jobs, Migrates job methods into JobModel
DB updates 
new /job steps

feat: job steps

---

packages/frontend/src/components/ShowErrorsButton.tsx

style: show errors button

---

packages/frontend/src/components/Intercom.tsx

chore: dont identify demo app user in intercom

---

packages/frontend/src/components/ExploreTree.tsx
packages/frontend/src/components/TableTree.tsx

Closes: #1888
Hide tree structure on single tables 
Single table (also hides redundant table name) 
Multiple tables (no changes)

style: hide tree single tables

---

packages/frontend/src/components/common/ActionCardList/index.tsx

Closes: #1956 
Update placeholder on search bar for saved charts

fix: update placeholder

---

packages/common/src/openapi/schemas/SavedChart/UpdateSavedChart.json
packages/common/src/openapibundle.json
packages/common/src/types/savedCharts.ts
packages/frontend/src/components/Explorer/ExploreHeader/ExploreHeader.styles.ts
packages/frontend/src/components/Explorer/ExploreHeader/ExploreHeader.tsx
packages/frontend/src/components/SavedQueries/RenameSavedChartModal.tsx
packages/frontend/src/hooks/useSavedQuery.ts

feat: update saved chart name and description in explore page

---

packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx
packages/frontend/src/components/ReactHookForm/MultiKeyValuePairsInput.tsx

docs: update dbt docs

---

docs/docs/get-started/setup-lightdash/connect-project.mdx
packages/frontend/src/components/ProjectConnection/DbtForms/BitBucketForm.tsx
packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx

Closes:  #1783
Update onboarding form and update documentation for bitbucket

fix: Update onboarding form and update documentation for bitbucket

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/index.ts
packages/frontend/src/components/TableTree.tsx
packages/frontend/src/hooks/useEcharts.ts

Closes: #1924 
Works in explorer + chart. Still not formatting tooltips in charts (see #1727)

fix: round custom average metrics

---

docs/docs/get-started/setup-lightdash/install-lightdash.mdx

docs: fix manual command

---

packages/frontend/src/App.tsx
packages/frontend/src/components/Intercom.tsx

fix: hide intercom launcher in most pages

---

packages/frontend/src/components/DocumentationHelpButton.tsx
packages/frontend/src/components/ExploreTree.tsx
packages/frontend/src/components/TableTree.styles.ts
packages/frontend/src/components/TableTree.tsx

style: improve table tree tooltips

---

packages/frontend/src/pages/Dashboard.tsx

fix: only show leave warning on edit mode

---

packages/frontend/src/hooks/useExplorerRoute.ts
packages/frontend/src/pages/SavedExplorer.tsx
packages/frontend/src/providers/ExplorerProvider.tsx

chore: remove redundant property from explorer context

---

packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
packages/frontend/src/components/common/SideBarLoadingState.tsx

Closes: #1932 
This PR removes the hello placeholders that are seen in the sidebar when a project is loading

fix: remove hello placeholders

---

packages/backend/src/clients/DockerHub/DockerHub.mock.ts
packages/backend/src/clients/DockerHub/DockerHub.test.ts
packages/backend/src/clients/DockerHub/DockerHub.ts
packages/backend/src/services/HealthService/HealthService.mock.ts
packages/backend/src/services/HealthService/HealthService.test.ts

test: amend health and docker hub tests

---

packages/frontend/src/components/Explorer/SqlCard/SqlCard.styles.ts

style: align sql title

---

packages/backend/src/dbt/translator.test.ts
packages/backend/src/dbt/translator.ts
packages/common/src/index.ts
packages/common/src/types/metricQuery.ts
packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
packages/frontend/src/providers/ExplorerProvider.tsx

Closes: #1993 
<a href="https://www.loom.com/share/1f7e981e8bc5428a996f863076677d89">
<p>Lightdash - magic metrics - Watch Video</p>
</a>

feat: magic metrics

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/SimpleTable/index.tsx
packages/frontend/src/utils/tableData.ts

Closes:#1548
Allow table chart sorting

fix: sort table chart

---

packages/frontend/src/hooks/useEcharts.ts

Closes: #1727
Format and round numbers in tooltips

feat: format and round echart tooltip

---

packages/backend/src/dbt/translator.ts

fix: use custom sql for date truncate fields

---

packages/backend/src/dbt/translator.ts

fix: prettier

---

packages/frontend/src/components/ResultsTable/ResultsTable.styles.tsx
packages/frontend/src/components/ResultsTable/ResultsTable.tsx
packages/frontend/src/components/SimpleTable/SimpleTable.styles.tsx
packages/frontend/src/components/SimpleTable/index.tsx
packages/frontend/src/utils/tableData.ts

Closes: #2040
Align numbers to the right, everything else stays on the left

feat: align numbers on table

---

packages/frontend/src/hooks/useColumns.tsx
packages/frontend/src/utils/resultFormatter.tsx

Closes: 
data is already formatted, we don't need to format the cell value

chore: remove cell formatting

---

packages/backend/src/dbt/translator.mock.ts
packages/common/src/types/metricQuery.ts

fix: regex lookahead

---

packages/frontend/src/utils/tableData.ts

fix: check null

---

packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/common/src/utils/formatting.ts

Closes: #2029 
Formats numbers across the site

feat: add currency function

---

packages/common/src/index.ts
packages/frontend/src/hooks/useColumns.tsx

Closes: 
Format table calculation values so it handles null and undefined.

fix: format table calculation values

---

packages/frontend/src/components/BigNumberConfig/index.tsx
packages/frontend/src/components/SimpleStatistic/index.tsx
packages/frontend/src/hooks/useBigNumberConfig.ts

Closes: #2019
Fix bignumber label on change

fix: fix bignumber label change

---

docs/docs/references/syncing_your_dbt_changes.md

Fixes reference doc on `refresh dbt`

docs: updates refresh dbt docs

---

packages/e2e/cypress/integration/sqlrunner.spec.ts

Closes: 
Add new sqlrunner e2e tests

test: sqlrunner e2e tests

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/index.ts
packages/common/src/utils/formatting.ts
packages/frontend/src/components/SimpleTable/index.tsx
packages/frontend/src/hooks/useEcharts.ts

Closes: 
Add formatting to table calculation values in table, charts and results table.

fix: format table calculation numbers with commas

---

packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/common/src/utils/formatting.ts
packages/frontend/src/hooks/useBigNumberConfig.ts

fix: format min and max dates

---

packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.styles.ts
packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx

feat: active filters tooltip

---

packages/frontend/src/components/Explorer/ExplorePanel/ExplorePanel.styles.ts
packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
packages/frontend/src/components/Explorer/ExploreTree/ExploreTree.styles.tsx
packages/frontend/src/components/Explorer/ExploreTree/index.tsx
packages/frontend/src/index.css
packages/frontend/src/pages/SavedExplorer.tsx

Closes: #1709  #2092 
This PR updates the UI of the side bar on the explorer

fix: updates ui of explorer side bar

---

packages/backend/src/routers/organizationRouter.ts
packages/backend/src/services/HealthService/HealthService.mock.ts
packages/backend/src/services/HealthService/HealthService.test.ts
packages/backend/src/services/HealthService/HealthService.ts
packages/backend/src/services/OrganizationService/OrganizationService.mock.ts
packages/backend/src/services/OrganizationService/OrganizationService.test.ts
packages/backend/src/services/OrganizationService/OrganizationService.ts
packages/common/src/index.ts
packages/frontend/src/components/AppRoute.tsx
packages/frontend/src/components/ProjectConnection/index.tsx
packages/frontend/src/components/UserSettingsModal/index.tsx
packages/frontend/src/pages/Welcome.tsx
packages/frontend/src/providers/AppProvider.tsx

Closes: #2093
move needsproject from /health to /org

refactor: move needsproject from /health to /org

---

packages/frontend/src/components/TableTree.tsx

Closes: https://github.com/lightdash/lightdash/issues/2102
Fixes typo from `you` --> `your`

fix: fixes typo in sidebar

---

packages/common/src/index.test.ts
packages/common/src/utils/formatting.ts

fix: rounding numbers with 4 or more digits

---

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/components/ShareLinkButton/ShareLinkButton.styles.tsx
packages/frontend/src/components/ShareLinkButton/index.tsx

Closes: #2076 
This PR creates the share link button, i have not added it yet to the header as the size of this button is different to the current ones, once the [new header](#2100 ) is merged  this button will be added to it.
https://www.loom.com/share/bd7b663d339942a0892de85d3f4a6c45

feat: add share link button

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx

fix: edit chart url

---

packages/frontend/src/hooks/useBigNumberConfig.ts

Closes: #2095 
Round big number when style is applied.

feat: round styled big numbers

---

packages/e2e/cypress/integration/explore.spec.ts
packages/frontend/src/hooks/useSavedQuery.ts

fix: show view mode after saving chart

---

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/components/ShareLinkButton/index.tsx

fix: show chart options in edit mode

---

packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/hooks/useExplorerRoute.ts
packages/frontend/src/providers/ExplorerProvider.tsx

Closes: #2123 
<a href="https://www.loom.com/share/e6d85143995a4fa3b148e665797ae584">
<p>Gather - lightdash | Gather - 16 May 2022 - Watch Video</p>
</a>

fix: cancel unsaved chart

---

release.config.js

fix: semantic release for warehouse version bump

---

packages/backend/src/projectAdapters/dbtGitProjectAdapter.ts

fix: strip secrets from git errors

---

packages/frontend/src/pages/Explorer.styles.ts

Closes: #2135 
This PR fixes the sidebar not being sticky when the content is too long in the explorer

fix: sidebar not being sticky on explorer

---

docs/docs/intro.md

Updates intro doc to new format structure

docs: change intro doc

---

packages/frontend/src/components/DashboardTiles/AddTileButton.tsx
packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx
packages/frontend/src/components/ReactHookForm/MultiSelect.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/pages/Dashboard.tsx

Closes: #1418 
Closes: #1355
- change multi select component to support array of value/label 
- change dashboard code to add multiple tiles at the same time
- add new modal
<a href="https://www.loom.com/share/e0bfc66e56f04b1490e7beaa6d6096e4">
<p>Lightdash - add multiple chart tiles - Watch Video</p>
</a>

feat: add multiple chart tiles

---

packages/backend/src/database/entities/jobs.ts
packages/backend/src/database/migrations/20220516074540_add_user_to_jobs.ts
packages/backend/src/models/JobModel/JobModel.ts
packages/backend/src/routers/jobsRouter.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/authorization/organizationMemberAbility.test.ts
packages/common/src/authorization/organizationMemberAbility.ts
packages/common/src/types/job.ts

Closes: #2107
Add permissions for Jobs resource

feat: Add permissions for Jobs resource

---

packages/frontend/src/index.css

Closes: #2052 
This PR removes the hover state from metrics/dimensions in the sidebar.

fix: remove hover state from metrics/dimensions label

---

packages/common/package.json
packages/warehouses/package.json
release.config.js

fix: publish common packages

---

release.config.js

fix: release cli on merge

---

packages/backend/src/dbt/translator.mock.ts
packages/backend/src/dbt/translator.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/projectAdapters/dbtAzureDevOpsProjectAdapter.ts
packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts
packages/backend/src/projectAdapters/dbtBitBucketProjectAdapter.ts
packages/backend/src/projectAdapters/dbtCloudIdeProjectAdapter.ts
packages/backend/src/projectAdapters/dbtGitProjectAdapter.ts
packages/backend/src/projectAdapters/dbtGithubProjectAdapter.ts
packages/backend/src/projectAdapters/dbtGitlabProjectAdapter.ts
packages/backend/src/projectAdapters/dbtLocalCredentialsProjectAdapter.ts
packages/backend/src/projectAdapters/dbtLocalProjectAdapter.ts
packages/backend/src/types.ts
packages/warehouses/src/types.ts
packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts
packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
packages/warehouses/src/warehouseClients/WarehouseClient.mock.ts

fix: remove column filters from catalog

---

packages/cli/package.json
packages/common/package.json
packages/warehouses/package.json

fix: add dist to packages

---

packages/cli/package.json
packages/common/package.json
packages/warehouses/package.json

fix: build before npm publish

---

docs/docs/guides/visualizing-your-results.mdx

Updates column chart to bar chart in a few places.

docs: changes column chart to bar chart

---

docs/docs/get-started/setup-lightdash/connect-project.mdx

Closes: #2153 
Adds docs for dbt cloud project connections.

docs: updates project connection dbt cloud

---

packages/frontend/src/hooks/useEcharts.ts

Closes: #2157 
Update default Echart colors

fix: update default echarts colors

---

packages/backend/src/services/UserService.ts

Closes: 
Allow multi org on google . If `allowMultiOrgs` is disabled, it will throw an exception on `registerNewUserWithOrg`

fix: multi org google register

---

dockerfile
dockerfile-prs

feat: upgrade dbt to 1.1.0

---

packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx

Closes: #1050
Fixes datetime filter issue. In my case, every datetime was the day/month/year before 
Before
After
Now I can filter !

fix: timezone filter

---

packages/cli/package.json

fix: manually fix cli dependency versions

---

packages/backend/src/dbt/translator.ts
packages/cli/src/dbt/models.ts
packages/cli/src/index.ts
packages/common/package.json
packages/common/src/index.ts
packages/common/src/types/dbt.ts

Closes #2187 
```
➜  dbt git:(main) lightdash generate -s +pages 
Generated .yml files:
✔   base_landing_page_pages ➡️  models/base/base_landing_page_pages.yml
✔   base_documentation_pages ➡️  models/base/base_documentation_pages.yml
✔   base_demo_pages ➡️  models/base/base_demo_pages.yml
✔   pages ➡️  models/prod/pages.yml
```
—

feat: add graph selectors to cli

---

packages/cli/src/dbt/models.ts

fix: type error

---

packages/backend/src/dbt/translator.ts

fix: table lineage typo

---

packages/frontend/src/hooks/useExplorerRoute.ts
packages/frontend/src/hooks/useSqlQueryVisualization.ts
packages/frontend/src/hooks/useSqlRunnerRoute.ts
packages/frontend/src/pages/SqlRunner.tsx
packages/frontend/src/providers/ExplorerProvider.tsx

Closes: #2193 
<a href="https://www.loom.com/share/f0cb409dd1544f1295579ea38854aa18">
<p>Lightdash - share sql runner chart - Watch Video</p>
</a>

feat: share sql runner chart

---

packages/e2e/cypress/integration/settings/invites.spec.ts
packages/frontend/src/components/NavBar/index.tsx
packages/frontend/src/components/UserSettingsModal/InvitesPanel/InvitesPanel.styles.ts
packages/frontend/src/components/UserSettingsModal/InvitesPanel/index.tsx
packages/frontend/src/components/UserSettingsModal/UserManagementPanel/UserManagementPanel.styles.ts
packages/frontend/src/components/UserSettingsModal/UserManagementPanel/index.tsx
packages/frontend/src/components/UserSettingsModal/index.tsx

Closes: #2199 
<a href="https://www.loom.com/share/23683c5421144ba39640259bab591c2f">
<p>Lightdash - move invite creation to user management - Watch Video</p>
</a>

feat: move invite creation to user management

---

packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Make columns lowercase in catalog queries
Closes:

fix: lowercase names in catalog query

---

packages/warehouses/src/warehouseClients/WarehouseClient.mock.ts

fix: snowflake catalog test

---

packages/backend/src/database/entities/inviteLinks.ts
packages/backend/src/database/migrations/20220524095230_add_email_column_to_invites.ts
packages/backend/src/models/InviteLinkModel.ts
packages/backend/src/models/UserModel.ts
packages/backend/src/services/UserService.ts
packages/common/src/index.ts
packages/e2e/cypress/integration/settings/invites.spec.ts
packages/frontend/src/components/CreateUserForm.tsx
packages/frontend/src/components/ReactHookForm/InputWrapper.tsx
packages/frontend/src/components/UserSettingsModal/InvitesPanel/InvitesPanel.styles.ts
packages/frontend/src/components/UserSettingsModal/InvitesPanel/index.tsx
packages/frontend/src/hooks/useInviteLink.tsx
packages/frontend/src/pages/Signup.tsx

feat: invite single email

---

packages/cli/src/dbt/context.ts
packages/common/src/utils/formatting.ts

Closes: #2233
Fix formatting on strings

fix: formatting strings

---

packages/cli/src/dbt/context.ts
packages/cli/src/dbt/manifest.ts
packages/cli/src/dbt/profile.ts
packages/cli/src/dbt/targets/bigquery.ts
packages/cli/src/handlers/dbt/run.ts

Closes: #2204
cli should find dbt_project.yml if I'm in a subdirectory
By recursively checking its parent until / 
if can't find it
Too many logs ? I could only show it once...

feat: find dbtproject subdirectory

---

packages/cli/src/dbt/models.ts
packages/common/src/types/dbt.ts

Closes: #2214
Skip ephemeral models for lightdash generate
Before:
After:

feat: Skip ephemeral models for lightdash generate

---

packages/cli/src/dbt/context.ts
packages/common/src/types/metricQuery.ts
packages/frontend/src/components/SimpleTable/index.tsx

Closes: #2231
Table viz show custom field labels

fix: table column label

---

packages/backend/src/database/entities/inviteLinks.ts
packages/backend/src/database/entities/users.ts
packages/backend/src/database/migrations/20220525150736_add-pending-users.ts
packages/backend/src/models/DashboardModel/DashboardModel.mock.ts
packages/backend/src/models/InviteLinkModel.ts
packages/backend/src/models/OrganizationMemberProfileModel.ts
packages/backend/src/models/UserModel.ts
packages/backend/src/routers/inviteLinksRouter.ts
packages/backend/src/routers/userRouter.ts
packages/backend/src/services/DashboardService/DashboardService.mock.ts
packages/backend/src/services/OrganizationService/OrganizationService.mock.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/backend/src/services/UserService.ts
packages/common/src/index.ts
packages/common/src/types/user.ts
packages/frontend/src/components/ReactHookForm/Select.tsx
packages/frontend/src/components/UserSettingsModal/InvitesPanel/InvitesPanel.styles.ts
packages/frontend/src/components/UserSettingsModal/InvitesPanel/index.tsx
packages/frontend/src/hooks/useInviteLink.tsx

feat: invite user with specific role

---

packages/backend/src/database/seeds/development/01_initial_user.ts
packages/backend/src/models/OrganizationMemberProfileModel.ts
packages/common/src/authorization/organizationMemberAbility.mock.ts
packages/common/src/index.ts
packages/common/src/types/organizationMemberProfile.ts
packages/frontend/src/components/UserSettingsModal/InvitesPanel/index.tsx
packages/frontend/src/components/UserSettingsModal/UserManagementPanel/UserManagementPanel.styles.ts
packages/frontend/src/components/UserSettingsModal/UserManagementPanel/index.tsx
packages/frontend/src/hooks/useInviteLink.tsx
packages/frontend/src/hooks/useOrganizationUsers.ts

Closes: #2184
Closes: #2211
I have left the font with the color it comes from blueprint as the white font with the warning color is not very readable.

feat: show pending users

---

packages/frontend/src/hooks/useRefreshServer.tsx

Closes: #2196
Sidebar / list of tables, dimensions, metrics doesn't update after refresh

fix: refresh tables on refresh dbt

---

packages/cli/src/index.ts

Closes: #2188 
Example:
```
(venv) ➜  jaffle_shop git:(demo) ✗ lightdash generate 
? Are you sure you want to generate .yml for all models in project? Yes
Generated .yml files:
✖   Failed to generate payments.yml
Couldn't parse existing yaml file at /Users/oliverlaslett/code/jaffle_shop/models/payments.yml:
REQUIRED must have required property 'join'
> 1 | {"version":2,"models":[{"name":"payments","meta":{"joins":[{"sql_on":"'{{ does_not_exist }}'"}]},"columns":[{"name":"payment_id","description":""},{"name":"order_id","description":""},{"name":"payment_method","description":""},{"name":"amount","description":""}]}]}
|                                                            ^ ☹️  join is missing here!
Error: Couldn't parse existing yaml file at …
```

docs: add GitHub link to cli

---

packages/backend/src/clients/EmailClient/EmailClient.test.ts
packages/backend/src/clients/EmailClient/templates/invite.html
packages/backend/src/clients/EmailClient/templates/recoverPassword.html

fix: prettier code backend invite on main

---

packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilter.tsx

Closes: [#2263](https://github.com/lightdash/lightdash/issues/2263)

fix: tooltip dashboard filter

---

packages/e2e/cypress/integration/dashboard.spec.ts

test: e2e dashboard tiles

---

packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx
packages/frontend/src/hooks/dashboard/useDashboard.tsx
packages/frontend/src/pages/Dashboard.tsx

feat: reorder new dashboard tiles to bottom

---

packages/backend/package.json
packages/backend/tsconfig.json

fix: add email template to dist

---

packages/backend/src/services/ProjectService/ProjectService.test.ts

fix: view job test role

---

packages/frontend/src/components/TableTree.tsx

Minor fix for the Custom Metrics info link.

fix: custom metrics link

---

packages/frontend/src/components/UserSettingsModal/ProfilePanel/index.tsx

Closes: #2303 
Reset user permissions after update

fix: user permissions after update

---

packages/cli/src/dbt/models.ts
packages/cli/src/dbt/schema.ts

feat: add dimension types to yml

---

packages/frontend/src/hooks/usePlottedData.ts

Closes: #2258
Keep `rows` initial sorting

fix: sort pivoted chart

---

packages/cli/track.sh

fix: do not track CLI install on CI 

---

.github/workflows/security.yml

chore: add github action for security check

---

packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/DatabricksForm.tsx

fix: databricks schema create project

---

packages/backend/src/services/UserService.ts

fix: validate invite email domain against organization allowed domains

---

packages/common/src/authorization/organizationMemberAbility.test.ts
packages/common/src/authorization/organizationMemberAbility.ts
packages/frontend/src/components/NavBar/index.tsx
packages/frontend/src/components/UserSettingsModal/UserManagementPanel/index.tsx
packages/frontend/src/components/UserSettingsModal/index.tsx

Closes: #2293
consistent invitelink permissions for inviteLink

fix: consistent invitelink permissions only for admin

---

.github/workflows/security.yml

chore: skip security check

---

packages/e2e/cypress/integration/api.spec.ts
packages/e2e/cypress/integration/login.spec.ts
packages/e2e/cypress/integration/settings/invites.spec.ts

test: fix e2e tests

---

packages/frontend/src/components/NavBar/index.tsx
packages/frontend/src/hooks/useProjects.ts
packages/frontend/src/pages/Projects.tsx

Closes: #1929
default last project using localstorage

feat: default last project using localstorage

---

packages/common/src/compiler/translator.mock.ts
packages/common/src/compiler/translator.test.ts
packages/common/src/compiler/translator.ts

fix: throw error when metric and dimension have same name

---

packages/frontend/src/hooks/useColumns.tsx

Closes: #1205 
Before: 
Fixed:

fix: table calculation table header

---

packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilters.styles.ts
packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
packages/frontend/src/components/DashboardFilter/index.tsx

fix: allow to remove invalid filters

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer/ExplorerHeader/index.tsx
packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/components/SavedDashboards/CreateSavedDashboardModal.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/components/common/modal/ModalActionButtons.tsx
packages/frontend/src/pages/SavedDashboards.tsx

fix: disable edit buttons with view permissions

---

packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.styles.ts
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
packages/frontend/src/components/SimpleTable/SimpleTable.styles.tsx

fix: table scroll

---

packages/frontend/src/App.styles.tsx
packages/frontend/src/providers/AppProvider.tsx

fix: hide refresh dbt toast close button

---

packages/frontend/src/components/Home/LatestDashboards/index.tsx
packages/frontend/src/pages/SavedDashboards.tsx

fix: hide create dashboard demo

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.styles.tsx
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/DashboardTiles/TileBase/TileBase.styles.tsx
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.styles.ts
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
packages/frontend/src/components/SimpleChart/index.tsx
packages/frontend/src/components/SimpleTable/SimpleTable.styles.tsx
packages/frontend/src/pages/SqlRunner.styles.ts

fix: dashboard tile scroll

---

packages/backend/src/dbt/dbtCliClient.ts

fix: dont expose env vars to dbt process

---

packages/common/src/compiler/translator.ts

feat: add formatting options for dbt metrics

---

packages/e2e/cypress/integration/createProjects.spec.ts
packages/e2e/cypress/integration/settings/invites.spec.ts
packages/e2e/cypress/integration/sqlrunner.spec.ts
packages/frontend/src/components/SqlRunner/SqlRunnerResultsTable.tsx
packages/frontend/src/hooks/useSqlQueryVisualization.ts
packages/frontend/src/hooks/useSqlRunnerColumns.ts
packages/frontend/src/pages/SqlRunner.tsx

Closes: #2405 
New sql runner hook that calculates totals and columns.

fix: sql runner column labels

---

packages/frontend/src/components/ProjectConnection/index.tsx

docs: update dbt project version requirements in ui

---

packages/frontend/src/pages/Dashboard.tsx

fix: dashboard page check reload view

---

.github/workflows/e2e-tests.yml
packages/e2e/cypress/e2e/api.cy.ts
packages/e2e/cypress/e2e/createProjects.cy.ts
packages/e2e/cypress/e2e/dashboard.cy.ts
packages/e2e/cypress/e2e/explore.cy.ts
packages/e2e/cypress/e2e/savedDashboards.cy.ts
packages/e2e/cypress/e2e/sqlrunner.cy.ts
packages/e2e/cypress/support/commands.ts
packages/e2e/cypress/support/e2e.ts

Closes: 
- fix video artifacts from github action
- fix shaky e2e test
- remove redundant pre compile project command

chore: improvements + fixes to e2e tests

---

packages/cli/src/handlers/dbt/run.ts
packages/cli/src/handlers/generate.ts
packages/cli/src/index.ts

feat: add models alias

---

packages/cli/src/dbt/models.ts

Closes: #2371
Don't overwrite dimension types in lightdash generate

bug: dont overwrite dimension types

---

packages/cli/src/handlers/generate.ts
packages/cli/src/index.ts

a little quality of life bonus
Closes:

feat: add cli yes flag

---

packages/backend/src/routers/projectRouter.ts
packages/backend/src/services/ProjectService/ProjectService.ts

Closes: 
Allows the CLI to push compiled projects to Lightdash
Quite basic for now and doesn't include validation, so if somebody used the API directly they could push invalid metrics

feat: api to update explores

---

packages/cli/src/handlers/dbt/run.ts

fix: add missing option for generate handler

---

packages/backend/src/services/UserService.ts
packages/common/src/index.ts
packages/frontend/src/components/UserSettingsModal/InvitesPanel/InvitesPanel.styles.ts
packages/frontend/src/components/UserSettingsModal/InvitesPanel/index.tsx

fix: invite role permission

---

docs/docs/references/roles.mdx

Closes: 
A docs update creating a draft page to describe roles and permissions. 
Provided as a guide for adding project-level permissions

docs: add draft roles and permissions docs

---

packages/frontend/src/components/UserSettingsModal/SocialLoginsPanel/SocialLoginsPanel.styles.tsx
packages/frontend/src/components/UserSettingsModal/SocialLoginsPanel/index.tsx
packages/frontend/src/components/common/GoogleLoginButton/GoogleLoginButton.styles.tsx
packages/frontend/src/components/common/GoogleLoginButton/index.tsx

…s component
Closes: #2412 
This pr fixes the broken google login button and migrates social logins component to styled components

fix: social login buttons

---

README.md

Closes: 
Adds a button to deploy a Lightdash instance to render.com

docs: add deploy to render button

---

packages/frontend/src/components/ProjectConnection/WarehouseSettingsForm.tsx
packages/frontend/src/components/ProjectConnection/index.tsx
packages/frontend/src/pages/CreateProject.tsx
packages/frontend/src/pages/ProjectSettings.styles.tsx
packages/frontend/src/pages/ProjectSettings.tsx

Closes: #2416 
This PR adds back the dropdown to choose a warehouse type on project update

fix: add back dropdown to choose warehouse on project update

---

packages/backend/src/database/migrations/20220615070629_add_member_role.ts
packages/backend/src/services/OrganizationService/OrganizationService.ts
packages/backend/src/services/UserService.ts
packages/common/src/authorization/organizationMemberAbility.mock.ts
packages/common/src/authorization/organizationMemberAbility.test.ts
packages/common/src/authorization/organizationMemberAbility.ts
packages/common/src/types/organizationMemberProfile.ts
packages/frontend/src/App.tsx
packages/frontend/src/components/ForbiddenPanel.tsx
packages/frontend/src/components/NavBar/index.tsx
packages/frontend/src/hooks/useQueryError.ts
packages/frontend/src/hooks/useSpaces.ts
packages/frontend/src/pages/Explorer.tsx
packages/frontend/src/pages/Home.tsx
packages/frontend/src/pages/Projects.tsx
packages/frontend/src/pages/SavedQueries.tsx
packages/frontend/src/pages/SqlRunner.tsx
packages/frontend/src/types/Events.ts

Closes: #2178
If they land on a project, via URL :

feat: add member role, update permissions

---

packages/backend/src/clients/EmailClient/EmailClient.ts
packages/backend/src/services/UserService.ts
packages/common/src/types/errors.ts
packages/e2e/cypress/e2e/settings/invites.cy.ts
packages/frontend/src/pages/SignUp.styles.tsx
packages/frontend/src/pages/Signup.tsx

Closes: #2182 
This PR sends the user to a welcome page when the user copy pastes the invite link, or directly to a sing up page when the user access the link through the received email, it also updates the card when the invite has expired.

feat: add UI for responding to invite codes

---

packages/backend/src/models/UserModel.mock.ts
packages/backend/src/models/UserModel.test.ts
packages/backend/src/models/UserModel.ts
packages/common/src/authorization/projectMemberAbility.mock.ts
packages/common/src/authorization/projectMemberAbility.test.ts
packages/common/src/authorization/projectMemberAbility.ts
packages/common/src/types/projectMemberProfile.ts
packages/common/src/types/user.ts

Closes: #2437
Project permissions 
Org and project permissions combined

feat: define abilities for project roles

---

docs/docs/references/personal_tokens.md
docs/docs/references/roles.md

https://deploy-preview-2453--peaceful-bassi-cbf284.netlify.app/references/personal_tokens

docs: personal access tokens

---

packages/common/src/compiler/translator.mock.ts
packages/common/src/compiler/translator.test.ts
packages/common/src/compiler/translator.ts

Closes: #2445 
Fixes aggregation error with snowflake aggregations due to `TIMESTAMP_TZ` allowing varying timezones at the record-level

fix: handle timezones in date trunc for snowflake

---

packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
packages/frontend/src/components/ChartConfigPanel/FieldLayoutOptions.tsx
packages/frontend/src/components/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/hooks/echarts/useEcharts.ts
packages/frontend/src/hooks/useCartesianChartConfig.ts
packages/frontend/src/hooks/usePivotDimensions.ts
packages/frontend/src/hooks/usePlottedData.ts

Closes: #2419 
Note that dimension series always show at the top and bellow all the grouped series.

feat: restrict pivot configuration

---

packages/backend/src/models/UserModel.mock.ts
packages/backend/src/models/UserModel.ts
packages/common/src/index.ts

fix: project member common imports

---

packages/frontend/src/components/ResultsTable/ResultsTable.tsx

fix: table header tooltip position

---

packages/backend/package.json
packages/backend/src/index.ts

chore: hide launch message when running in headless mode

---

packages/frontend/src/components/SimpleChart/index.tsx

feat: cross-filter on left-click

---

packages/frontend/src/components/ProjectConnection/ProjectConnection.styles.tsx
packages/frontend/src/components/ProjectConnection/index.tsx
packages/frontend/src/pages/ProjectSettings.styles.tsx
packages/frontend/src/pages/ProjectSettings.tsx

Closes: #2403 
this PR fixes the run project button not being sticky at the bottom of the page on very large screens

fix: button bar not sticking to the bottom

---

packages/frontend/src/pages/CreateProjectSettings.tsx

fix: redirect after create first project

---

packages/cli/src/handlers/setProject.ts

fix: typo url to project after cli login

---

packages/backend/src/clients/EmailClient/EmailClient.ts
packages/backend/src/clients/EmailClient/templates/projectAccess.html
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/services.ts

Closes:#2444
Sending the email seems a bit slow, is there any way to make it faster ? (without removing await) , I don't think the email should block this endpoint .

feat: send email on project access

---

packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Closes: #2475 
[Snowflake sdk was returning a custom date object that returns a string in the wrong format.](https://github.com/snowflakedb/snowflake-connector-nodejs/issues/317)

fix: snowflake date object

---

.github/workflows/e2e-tests.yml
packages/e2e/cypress/e2e/createProjects.cy.ts

test: databricks e2e tests

---

.github/workflows/e2e-tests.yml
packages/e2e/cypress/e2e/createProjects.cy.ts
packages/e2e/cypress/e2e/projectPermission.cy.ts

test: snowflake e2e tests

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/index.ts
packages/frontend/src/components/ProjectAccess/ProjectAccessCreation/ProjectAccessCreation.ts
packages/frontend/src/components/ProjectAccess/ProjectAccessCreation/index.tsx

feat: invite users from project view

---

packages/frontend/src/components/CreateUserForm/index.tsx
packages/frontend/src/components/UserSettings/ProfilePanel/index.tsx

Closes: #2522 
This PR updates the placeholders on the sign up forms from David Attenborough to first name/ last name.

fix: update forms placeholder

---

packages/cli/src/handlers/createProject.ts

fix: update create project endpoint in cli

---

packages/cli/src/config.ts

fix: handle missing cli config dir

---

packages/frontend/src/components/ProjectConnection/WarehouseForms/BigQueryForm.tsx

Closes: #2513 
Fixes bigquery docs link

fix: update wrong bigQuery link

---

packages/frontend/src/components/TableTree.styles.ts

Updates indentation in the explorer sidebar 
https://user-images.githubusercontent.com/31137824/175525597-9eed65b4-cf2d-4c5e-aa5c-d8f653da9838.mov

style: update indentation in the sidebar levels

---

packages/common/src/openapi/schemas/SavedChart/UpdateSavedChart.json
packages/common/src/openapibundle.json

fix: openapi update chart description optional

---

packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/authorization/organizationMemberAbility.test.ts
packages/common/src/authorization/organizationMemberAbility.ts
packages/common/src/authorization/projectMemberAbility.test.ts
packages/common/src/authorization/projectMemberAbility.ts
packages/common/src/authorization/types.ts
packages/e2e/cypress/e2e/api/projectPermissions.cy.ts
packages/frontend/src/components/NavBar/ExploreMenu/index.tsx

feat: disable sql runner for viewers

---

docs/docs/references/roles.md

docs: remove toles and permissions caution message

---

packages/frontend/src/hooks/echarts/useEcharts.ts

fix: y axis range

---

packages/cli/src/config.ts
packages/cli/src/handlers/login.ts
packages/cli/src/handlers/preview.ts
packages/cli/src/handlers/setProject.ts

feat: allow user to auth with env vars on cli

---

packages/cli/README.md

docs: cli readme

---

packages/backend/src/config/parseConfig.ts
packages/backend/src/index.ts
packages/backend/src/models/ProjectModel/ProjectModel.mock.ts

feat: allow server payload configuration

---

packages/cli/src/handlers/preview.ts

fix: teardown cli previews on error

---

packages/frontend/src/hooks/useCartesianChartConfig.ts

fix: keep area chart stacked when axis change

---

packages/cli/src/handlers/dbt/apiClient.ts
packages/cli/src/handlers/deploy.ts
packages/cli/src/handlers/preview.ts
packages/cli/src/index.ts

fix: improve auth error messages on cli

---

packages/cli/README.md
packages/cli/src/dbt/models.ts

fix: doc block quotes

---

docs/docs/get-started/setup-lightdash/lightdash-cli.mdx

docs: add documentation for upgrading cli

---

packages/cli/src/handlers/compile.ts

fix: ignore missing types during compile

---

docs/docs/get-started/setup-lightdash/lightdash-cli.mdx
packages/cli/src/index.ts

Closes: #2584 
https://deploy-preview-2585--peaceful-bassi-cbf284.netlify.app/get-started/setup-lightdash/lightdash-cli

docs: cli environment variables

---

packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
packages/frontend/src/components/TableTree.tsx

fix: use field labels in search

---

docs/docs/references/roles.md
packages/common/src/authorization/organizationMemberAbility.ts
packages/frontend/src/components/ProjectAccess/ProjectAccess.tsx

fix: editor project permissions

---

packages/frontend/src/providers/ExplorerProvider.tsx

Closes:  https://github.com/lightdash/lightdash/issues/2506
- Fix to enable save chart button: check to see if query is valid

fix: save chart button enable condition when nothing to save

---

docs/docs/get-started/develop-in-lightdash/intro.mdx
docs/docs/get-started/intro.mdx
docs/docs/get-started/setup-lightdash/add-metrics.mdx
docs/docs/get-started/setup-lightdash/lightdash-cli.mdx
docs/docs/guides/how-to-create-dimensions.md
docs/docs/guides/how-to-create-metrics.mdx
docs/docs/intro.md
docs/sidebars.js

Adds a developer "getting started" tutorial to the docs

docs: add developer tutorial

---

packages/frontend/src/components/TableTree.tsx

We were sorting by name instead of label

fix: field sorting

---

packages/warehouses/src/warehouseClients/PostgresWarehouseClient.test.ts
packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts

fix: catalog error when dbt is empty

---

packages/cli/src/handlers/compile.ts
packages/cli/src/handlers/dbt/compile.ts
packages/cli/src/handlers/deploy.ts
packages/cli/src/handlers/preview.ts
packages/cli/src/index.ts

feat: compile dbt project before compile, deploy and preview commands

---

packages/common/src/types/savedCharts.ts
packages/frontend/package.json
packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
packages/frontend/src/components/ChartConfigPanel/Grid/Grid.styles.tsx
packages/frontend/src/components/ChartConfigPanel/Grid/index.tsx
packages/frontend/src/components/ChartConfigPanel/Legend/Legend.styles.tsx
packages/frontend/src/components/ChartConfigPanel/Legend/index.tsx
packages/frontend/src/hooks/echarts/useEcharts.ts
packages/frontend/src/hooks/useCartesianChartConfig.ts

feat: legend and grid configuration

---

packages/common/src/types/savedCharts.ts
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/SimpleTable/index.tsx
packages/frontend/src/components/TableConfigPanel/TableConfig.styles.ts
packages/frontend/src/components/TableConfigPanel/index.tsx
packages/frontend/src/hooks/useTableConfig.ts
packages/frontend/src/providers/ExplorerProvider.tsx

feat: new table config and show table names property

---

packages/frontend/src/components/ProjectConnection/index.tsx

fix: update callout to show dbt 1.1.0 required

---

packages/warehouses/src/warehouseClients/RedshiftWarehouseClient.ts

fix: encode uri components in redshift connection string

---

packages/common/src/types/savedCharts.ts
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/SimpleTable/index.tsx
packages/frontend/src/components/TableConfigPanel/ColumnConfiguration.styles.ts
packages/frontend/src/components/TableConfigPanel/ColumnConfiguration.tsx
packages/frontend/src/components/TableConfigPanel/index.tsx
packages/frontend/src/hooks/useTableConfig.ts

feat: hide columns table charts

---

packages/common/src/compiler/translator.mock.ts
packages/common/src/compiler/translator.ts

fix: strip timezone from truncated snowflake fields

---

packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx

Closes: #2457 
<a href="https://www.loom.com/share/c95460318f084039b543cd3450d2966a">
<p>Lightdash - fix date picker - Watch Video</p>
</a>

fix: date picker timezone conversion

---

packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx
packages/frontend/src/components/ProjectConnection/index.tsx

fix: reset dbt.host_domain field

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx

feat: download csv on table charts from dashboards

---

CHANGELOG.md
docs/docs/guides/visualizing-your-results.mdx
packages/e2e/cypress/e2e/explore.cy.ts
packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx

Closes: https://github.com/lightdash/lightdash/issues/1520#issuecomment-1160582194

style: Rename big number

---

packages/common/src/types/savedCharts.ts
packages/frontend/src/components/BigNumberConfig/index.tsx
packages/frontend/src/hooks/useBigNumberConfig.ts

feat: bignumber field select

---

packages/backend/package.json
packages/frontend/package.json

Closes: https://github.com/lightdash/lightdash-internal-work/issues/373

chore: upgrade rudderstack 113

---

packages/e2e/cypress/e2e/dashboard.cy.ts
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.styles.ts
packages/frontend/src/components/LightdashVisualization/index.tsx
packages/frontend/src/components/SimpleTable/SimpleTable.styles.tsx
packages/frontend/src/components/SimpleTable/index.tsx
packages/frontend/src/components/SqlRunner/SqlRunnerResultsTable.tsx
packages/frontend/src/components/TableConfigPanel/ColumnConfiguration.tsx
packages/frontend/src/components/common/Table/TablePagination/index.tsx
packages/frontend/src/components/common/Table/TableProvider.tsx
packages/frontend/src/hooks/useColumnTotals.ts
packages/frontend/src/hooks/useColumns.tsx
packages/frontend/src/hooks/useSqlRunnerColumns.ts
packages/frontend/src/hooks/useTableConfig.ts

feat: table viz improvements

---

packages/cli/src/dbt/targets/bigquery.ts

Closes: #2614
Minor change to support oauth
https://github.com/lightdash/lightdash/issues/2614#issuecomment-1180501170

feat: support bigquery oauth

---

packages/frontend/src/components/ChartConfigPanel/FieldLayoutOptions.tsx
packages/frontend/src/hooks/echarts/useEcharts.ts

feat: can stack mixed series

---

packages/common/src/utils/formatting.ts
packages/e2e/cypress/e2e/explore.cy.ts
packages/frontend/src/hooks/echarts/useEcharts.ts

fix: legend time format

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/SimpleChart/index.tsx

feat: filter by pivot on dashboards

---

packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx

fix: edit table calculation

---

packages/common/src/types/savedCharts.ts
packages/frontend/src/hooks/useCartesianChartConfig.ts

fix: keep cartesian type in sync

---

packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTree.tsx

fix: sort dates on explore

---

packages/frontend/src/hooks/echarts/useEcharts.ts

fix: hideoverlap on labels

---

packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.mock.ts
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.test.ts
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts

feat: sort date dimensions on X axis

---

packages/cli/src/dbt/profile.ts
packages/cli/src/dbt/targets/redshift.ts

feat: support redshift on CLI

---

packages/frontend/src/hooks/echarts/useEcharts.ts

fix: do not force remove stack on area charts

---

packages/frontend/src/components/NavBar/HelpMenu/index.tsx

Closes: #2597 
Updates the "join the discussion" to "join the community" with the relevant link.
Adds another dropdown option to create a bug report or feature request.

fix: update help dropdown

---

docs/docs/get-started/setup-lightdash/connect-project.mdx

docs: add bitbucket app password

---

packages/backend/src/models/DashboardModel/DashboardModel.mock.ts
packages/backend/src/models/DashboardModel/DashboardModel.test.ts
packages/backend/src/models/DashboardModel/DashboardModel.ts
packages/backend/src/models/SavedChartModel.ts
packages/backend/src/services/DashboardService/DashboardService.mock.ts
packages/common/src/openapi/schemas/Dashboard.json
packages/common/src/openapi/schemas/SavedChart/SavedChart.json
packages/common/src/openapibundle.json
packages/common/src/types/dashboard.ts
packages/common/src/types/savedCharts.ts
packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/components/common/ActionCardList/index.tsx
packages/frontend/src/components/common/modal/ActionModal.tsx
packages/frontend/src/components/common/modal/ModalActionButtons.tsx
packages/frontend/src/components/common/modal/MoveToSpaceModal.tsx
packages/frontend/src/hooks/useSavedQuery.ts
packages/frontend/src/hooks/useSpaces.ts

feat: move items spaces

---

packages/frontend/src/components/NavBar/BrowseMenu/index.tsx

feat: navigate-spaces-navbar

---

packages/frontend/src/components/RefreshDbtButton/index.tsx

Closes: #2766
Now it matches the permission on the backend : 
https://github.com/lightdash/lightdash/blob/main/packages/backend/src/services/ProjectService/ProjectService.ts#L680

fix: remove refreshdbt button for editors

---

packages/backend/src/models/ProjectModel/ProjectModel.ts

chore: rename default space

---

docs/docs/guides/cli/how-to-use-lightdash-deploy.md

docs: lightdash deploy typo

---

packages/cli/src/dbt/context.ts

Closes: #2783
New Parsing error
Wrong dbt folder (same error)

fix: show yaml parsing errors on CLI

---

packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts

fix: default chart for 2+ dimensions 1 metric

---

packages/backend/src/models/SavedChartModel.ts
packages/backend/src/services/DashboardService/DashboardService.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/frontend/src/components/Home/LandingPanel/index.tsx
packages/frontend/src/components/NavBar/BrowseMenu/index.tsx
packages/frontend/src/components/SavedQueries/CreateSavedQueryModal.tsx
packages/frontend/src/components/SavedQueries/SavedQueries.style.tsx
packages/frontend/src/components/SpacePanel/index.tsx
packages/frontend/src/components/common/modal/ModalActionButtons.tsx
packages/frontend/src/hooks/useSpaces.ts

Closes: #2667
All existing SPACE features are behind a localstorage flag now, to enable just do `localStorage.setItem('spaceFeature', true) ` on console and refresh the page

feat: select space on save chart

---

packages/backend/src/dbt/dbtCliClient.ts

Closes: #2770
Closes: #2754
With this line in my `dbt_project.yml`
```yaml
target-path: "{{ var('yo', 'target') }}"
```
**Before**
**After**

fix: handle custom targets in dbt compile

---

packages/frontend/src/components/Explorer/SpaceBrowser/DeleteSpaceModal.tsx
packages/frontend/src/components/Home/LandingPanel/index.tsx

feat: warn about deleted chats and dashboards on space deletion

---

packages/backend/src/services/DashboardService/DashboardService.ts
packages/frontend/src/components/Home/LandingPanel/index.tsx
packages/frontend/src/components/NavBar/BrowseMenu/index.tsx
packages/frontend/src/components/SavedQueries/CreateSavedQueryModal.tsx
packages/frontend/src/components/common/modal/ModalActionButtons.tsx
packages/frontend/src/hooks/dashboard/useDashboard.tsx
packages/frontend/src/hooks/useSavedQuery.ts
packages/frontend/src/pages/SavedDashboards.tsx

feat: enable spaces

---

packages/backend/src/models/SpaceModel.ts

fix: fix organization_id on filter

---

packages/frontend/src/components/NavBar/NavBar.styles.tsx
packages/frontend/src/components/UserSettings/ProjectManagementPanel/ProjectManagementPanel.styles.ts
packages/frontend/src/components/UserSettings/ProjectManagementPanel/index.tsx

fix: truncate project name

---

packages/frontend/src/hooks/echarts/useEcharts.ts

fix: fix axes formatter

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/models/SearchModel/index.ts
packages/backend/src/models/models.ts
packages/backend/src/routers/projectRouter.ts
packages/backend/src/services/SearchService/SearchService.ts
packages/backend/src/services/services.ts
packages/common/src/index.ts
packages/common/src/types/search.ts
packages/e2e/cypress/e2e/dashboard.cy.ts
packages/e2e/cypress/e2e/globalSearch.cy.ts
packages/frontend/src/App.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTree.tsx
packages/frontend/src/components/NavBar/GlobalSearch/globalSearch.styles.ts
packages/frontend/src/components/NavBar/GlobalSearch/hooks.ts
packages/frontend/src/components/NavBar/GlobalSearch/index.tsx
packages/frontend/src/components/NavBar/index.tsx
packages/frontend/src/hooks/globalSearch/useGlobalSearch.ts
packages/frontend/src/providers/TrackingProvider.tsx
packages/frontend/src/types/Events.ts

feat: global search

---

packages/frontend/package.json
packages/frontend/src/components/SpacePanel/SpacePanel.styles.ts
packages/frontend/src/components/SpacePanel/index.tsx
yarn.lock

feat: add breacrumbs to space

---

packages/frontend/src/components/Home/LatestDashboards/index.tsx
packages/frontend/src/components/Home/LatestSavedCharts/index.tsx

style: update copy recently updated charts/dashboards

---

packages/frontend/src/components/NavBar/GlobalSearch/index.tsx

style: update global search copy

---

packages/frontend/src/components/SavedQueries/SavedQueriesContent.tsx
packages/frontend/src/components/SpacePanel/index.tsx
packages/frontend/src/pages/SavedDashboards.tsx
packages/frontend/src/pages/SavedQueries.tsx

style: update dashboards and saved charts pages copy

---

packages/backend/src/database/entities/spaces.ts
packages/backend/src/models/DashboardModel/DashboardModel.mock.ts
packages/backend/src/models/DashboardModel/DashboardModel.test.ts
packages/backend/src/models/DashboardModel/DashboardModel.ts
packages/backend/src/models/SavedChartModel.ts
packages/backend/src/services/DashboardService/DashboardService.mock.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/common/src/openapi/schemas/Dashboard.json
packages/common/src/openapi/schemas/SavedChart/SavedChart.json
packages/common/src/openapibundle.json
packages/common/src/types/dashboard.ts
packages/common/src/types/savedCharts.ts
packages/frontend/src/components/SavedQueries/CreateSavedQueryModal.tsx
packages/frontend/src/hooks/dashboard/useDashboard.tsx
packages/frontend/src/hooks/useMoveToSpace.ts
packages/frontend/src/hooks/useSavedQuery.ts

Closes: #2813 
Had a talk with Priyanka about dropping the old space name from the message since it would require big changes.

fix: move success message

---

packages/frontend/src/hooks/echarts/useEcharts.ts

Closes: #2795 
- improve typing
- add reduce initial value

fix: reduce missing initial value

---

packages/common/src/compiler/translator.mock.ts
packages/common/src/compiler/translator.test.ts
packages/common/src/compiler/translator.ts
packages/common/src/types/dbt.ts
packages/common/src/types/errors.ts

fix: handle non compiled models

---

docs/docs/guides/formatting-your-fields.mdx

Updates the groups docs missing `meta` and `metrics`

docs: Update groups

---

packages/frontend/src/components/SpacePanel/SpacePanel.styles.ts
packages/frontend/src/components/SpacePanel/index.tsx

style: Update breadcrumbs style

---

packages/frontend/src/components/SpacePanel/index.tsx

style: space spage copy

---

packages/frontend/src/components/ProjectConnection/DbtForms/GithubForm.tsx

docs: update github docs link

---

docs/docs/references/environmentVariables.md
packages/backend/package.json
packages/backend/src/@types/passport-openidconnect.d.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/controllers/authentication.ts
packages/backend/src/database/entities/openIdIdentities.ts
packages/backend/src/database/migrations/20220727122405_drop_issuer_fk.ts
packages/backend/src/index.ts
packages/backend/src/models/OpenIdIdentitiesModel.ts
packages/backend/src/models/ProjectModel/ProjectModel.mock.ts
packages/backend/src/models/UserModel.ts
packages/backend/src/routers/apiV1Router.ts
packages/backend/src/services/HealthService/HealthService.mock.ts
packages/backend/src/services/HealthService/HealthService.ts
packages/backend/src/services/UserService.ts
packages/common/src/index.ts
packages/common/src/types/user.ts
packages/frontend/src/components/UserSettings/SocialLoginsPanel/index.tsx
packages/frontend/src/components/common/GoogleLoginButton/index.tsx
packages/frontend/src/pages/Login.tsx
packages/frontend/src/pages/Register.tsx
packages/frontend/src/pages/Settings.tsx
packages/frontend/src/pages/Signup.tsx
yarn.lock

Closes #2757
Closes #2283 
Adds Okta as a provider for Lightdash login. Uses OpenID Connect for auth flow same as the Google flow.
Todo:
- remove restriction on issuers to handle any okta domain
- add sign in UI components
- Get name autofilled from okta
-

feat: add okta sso

---

packages/frontend/src/hooks/echarts/useEcharts.ts

fix: fix color shuffle on hidden series

---

packages/frontend/src/components/Explorer/SavedChartsHeader/SavedChartsHeader.styles.tsx
packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx

feat: move chart to space on edit mode

---

packages/frontend/src/hooks/echarts/useEcharts.ts

Closes: #2790 
Changes:
- only force type 'category' for horizontal bar chart
- apply correct type on each axis top/bottom/left/right

fix: both axis with continuous values

---

packages/frontend/src/components/ReactHookForm/MultiSelect.tsx
packages/frontend/src/components/common/modal/AddToSpaceModal.style.tsx
packages/frontend/src/components/common/modal/AddToSpaceModal.tsx
packages/frontend/src/index.css

feat: show current space on multiselect add chart/dashboard

---

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/components/common/modal/ModalActionButtons.tsx

style: add tick to selected space submenu

---

packages/e2e/cypress/e2e/globalSearch.cy.ts
packages/frontend/src/components/NavBar/GlobalSearch/globalSearch.styles.ts
packages/frontend/src/components/NavBar/GlobalSearch/hooks.ts
packages/frontend/src/components/NavBar/GlobalSearch/index.tsx
packages/frontend/src/components/common/HighlightedText/index.tsx

Closes: #2838 
@PriPatel note that I have used the table icon already used in the nav bar instead of the 'database' icon used in figma. Database icon is misleading and we stopped using it some time ago.

style: global search

---

packages/frontend/src/components/ProjectConnection/DbtForms/AzureDevOpsForm.tsx
packages/frontend/src/components/ProjectConnection/DbtForms/GitlabForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/BigQueryForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/DatabricksForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/PostgresForm.tsx

fix: warehouse doc urls

---

docs/docs/guides/table-calculations/table-calculation-sql-templates/running-total.mdx

updates running total SQL template

docs: update running total

---

docs/docs/get-started/setup-lightdash/connect-project.mdx

removes dbt cloud reference in dbt project connection

docs: fix dbt cloud in connection docs

---

docs/docs/references/environmentVariables.md

docs: update env vars in docs

---

packages/backend/src/models/SpaceModel.ts
packages/frontend/src/components/Explorer/SpaceBrowser/SpaceBrowserMenu.tsx
packages/frontend/src/components/Explorer/SpaceBrowser/index.tsx
packages/frontend/src/components/SpacePanel/SpacePanel.styles.ts
packages/frontend/src/components/SpacePanel/index.tsx
packages/frontend/src/hooks/useSpaces.ts

feat: rename and delete in space page

---

packages/frontend/src/components/Explorer/SpaceBrowser/SpaceBrowser.styles.tsx
packages/frontend/src/components/Explorer/SpaceBrowser/index.tsx

style: space items count

---

docs/docs/get-started/setup-lightdash/connect-project.mdx

docs: update IP address

---

packages/backend/src/services/UserService.ts

feat: add email to invite error message

---

packages/frontend/src/components/Explorer/SpaceBrowser/SpaceBrowserMenu.tsx
packages/frontend/src/components/Explorer/SpaceBrowser/index.tsx
packages/frontend/src/components/SpacePanel/index.tsx

Closes: #2879 
Had to pull the dialogs out of the space button. Basically rolling back some of the refactor from the previous PR

fix: rename space in homepage

---

packages/frontend/src/components/common/modal/AddToSpaceModal.tsx

feat: add new chart modal on spaces

---

packages/backend/src/services/UserService.ts

fix: match invite email case insensitive

---

packages/common/src/types/savedCharts.ts
packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx
packages/frontend/src/components/SimpleTable/index.tsx
packages/frontend/src/components/SqlRunner/SqlRunnerResultsTable.tsx
packages/frontend/src/components/TableConfigPanel/index.tsx
packages/frontend/src/components/common/Table/ScrollableTable/TableFooter.tsx
packages/frontend/src/components/common/Table/ScrollableTable/index.tsx
packages/frontend/src/components/common/Table/Table.styles.ts
packages/frontend/src/components/common/Table/TableProvider.tsx
packages/frontend/src/hooks/useTableConfig.ts

Closes: #2772 
Note that all existing saved charts will have their footer hidden.

feat: show or hide column calculation in table viz

---

docs/docs/get-started/setup-lightdash/add-metrics.mdx
docs/docs/guides/cli/how-to-install-the-lightdash-cli.mdx
docs/docs/guides/how-to-create-dimensions.md
packages/cli/src/handlers/login.ts
packages/cli/src/index.ts

feat: user can login to the cli with a token

---

packages/frontend/src/components/UserCompletionModal/index.tsx

Closes: #2865 
Added randomising to a dropdown list for a role selector

feat: randomze job titles in the job title selector

---

packages/frontend/src/components/ChartDownload.tsx

Closes: #2672 
Table viz CSV export used plot data
OLD
NEW

fix: csv export used plot data instead of raw

---

packages/frontend/src/hooks/useFilters.ts

feat: open filters panel on add filter

---

packages/common/src/types/savedCharts.ts
packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
packages/frontend/src/hooks/echarts/useEcharts.ts

feat: inverse X axis values

---

packages/backend/src/routers/dashboardRouter.ts
packages/backend/src/routers/inviteLinksRouter.ts
packages/backend/src/routers/organizationRouter.ts
packages/backend/src/routers/projectRouter.ts
packages/backend/src/routers/savedChartRouter.ts

- spaces
- charts
- dashboards
- users
- invite links
Closes:

feat: read and create users/spaces/dashboards/charts with personal access token

---

packages/frontend/src/hooks/useColumnTotals.ts

feat: remove average and percent from table totals

---

packages/frontend/src/components/Explorer/SpaceBrowser/CreateSpaceModal.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/hooks/useSpaces.ts
packages/frontend/src/pages/Dashboard.tsx

Closes: #2072
adds dashboard header actions. see the video below:
https://user-images.githubusercontent.com/962095/184621563-1418dfaa-fee8-4529-855a-6a5192a7463c.mp4

feat: add dashboard header actions

---

packages/common/src/compiler/translator.mock.ts
packages/common/src/compiler/translator.ts
packages/e2e/cypress/e2e/createProjects.cy.ts

fix: do not convert timezones for dates

---

packages/frontend/src/components/Explorer/ExploreTree/TableTree/CollapsibleTableTree.tsx

style: dont truncate table items count

---

packages/backend/src/queryBuilder.mock.ts
packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts

feat: nested filters SQL

---

packages/frontend/src/components/Explorer/VisualizationCard/ShowTotalsToggle.styles.ts
packages/frontend/src/components/Explorer/VisualizationCard/ShowTotalsToggle.tsx
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx

feat: show column total on chart view mode

---

packages/backend/src/queryBuilder.ts

fix: fix empty filter

---

packages/backend/src/queryBuilder.mock.ts
packages/backend/src/queryBuilder.test.ts
packages/e2e/cypress/e2e/dashboard.cy.ts

Closes: #2985
Before the fix, SQl had `WHERE ()` , and charts where not showing on dashboard

test: query builder filters empty test

---

packages/frontend/src/components/Explorer/ResultsCard/CellContextMenu.tsx
packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx
packages/frontend/src/components/common/Table/ScrollableTable/RichBodyCell.tsx
packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
packages/frontend/src/components/common/Table/ScrollableTable/index.tsx
packages/frontend/src/components/common/Table/Table.styles.ts
packages/frontend/src/components/common/Table/TableProvider.tsx
packages/frontend/src/components/common/Table/index.tsx
packages/frontend/src/components/common/Table/types.ts
packages/frontend/src/providers/TrackingProvider.tsx
packages/frontend/src/types/Events.ts

Closes: #2785 
https://user-images.githubusercontent.com/962095/185170305-7ffddff4-a95f-45ab-a5c2-adad3a31f79d.mp4

feat: table interactions

---

packages/frontend/src/components/SimpleTable/CellContextMenu.tsx
packages/frontend/src/components/SimpleTable/index.tsx

Closes: #3001 
fix: for broken table viz rows
feat: new left click context menu instead of right-click
https://www.loom.com/share/7b2df514414244539d82937ba26857a3

fix: table viz context menu

---

packages/cli/src/dbt/models.ts
packages/cli/src/dbt/schema.ts
packages/cli/src/handlers/dbt/run.ts
packages/cli/src/handlers/generate.ts
packages/cli/src/index.ts

feat: toggle generating dimension types

---

packages/frontend/src/components/SimpleTable/CellContextMenu.tsx
packages/frontend/src/components/common/Table/types.ts
packages/frontend/src/hooks/tableVisualization/getPivotDataAndColumns.ts

fix: view underlying data of pivot table

---

packages/frontend/src/components/BigNumberConfig/index.tsx
packages/frontend/src/components/ChartConfigPanel/Series/SeriesColorPicker.tsx
packages/frontend/src/components/ChartDownload.tsx
packages/frontend/src/components/DashboardFilter/ActiveFilters/ActiveFilter.tsx
packages/frontend/src/components/DashboardFilter/index.tsx
packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
packages/frontend/src/components/LimitButton/index.tsx
packages/frontend/src/components/TableConfigPanel/index.tsx

Related to https://github.com/lightdash/lightdash/issues/2997

chore: lazy load chart config modals

---

packages/frontend/src/components/UnderlyingData/UnderlyingDataResultsTable.tsx
packages/frontend/src/hooks/useUnderlyingDataColumns.ts

feat: underlying data table format

---

packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/SimpleStatistic/index.tsx
packages/frontend/src/components/SimpleTable/index.tsx

Closes: #3035
Disabled context menus for tables and bignumbers

fix: fix underyling data on sql runner

---

packages/frontend/src/components/UnderlyingData/UnderlyingDataModal.tsx
packages/frontend/src/components/UnderlyingData/UnderlyingDataProvider.tsx
packages/frontend/src/components/UnderlyingData/UnderlyingDataResultsTable.tsx
packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
packages/frontend/src/hooks/useColumns.tsx

Closes: #2909
On underlying data:

feat: only show table names if there are joins (explore)

---

packages/cli/src/analytics/analytics.ts
packages/cli/src/handlers/compile.ts
packages/cli/src/handlers/deploy.ts
packages/cli/src/handlers/preview.ts

feat: add new analytics for cli preview and compile

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/services/SpaceService/SpaceService.ts

Closes: #2973
From rudderstack:

feat: add project id to space analytics

---

packages/frontend/src/components/common/Table/ScrollableTable/TableHeader.tsx

add missing key on table headers.

fix: table header keys

---

packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx

fix: fix empty column order on explore from here for underlying data

---

docs/docs/guides/how-to-create-metrics.mdx

docs: update metrics to include reference sheet

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/providers/TrackingProvider.tsx
packages/frontend/src/types/Events.ts

feat: analytics cross filter applied click on dashboards

---

packages/cli/src/index.ts
packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectionOptions.tsx
packages/frontend/src/components/ProjectConnection/index.tsx

fixes links in buttons in onboarding

fix: update docs links

---

README.md

docs: Add link to Slack Community in README header

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/services/ProjectService/ProjectService.ts

feat: analytics project preview

---

docs/docs/guides/cli/cli-authentication.mdx

docs: update cli token docs

---

docs/docs/guides/how-to-create-metrics.mdx

docs: fixes doc link for metrics

---

packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeProvider.tsx
packages/frontend/src/components/Explorer/ExploreTree/index.tsx

feat: hide empty groups when searching on explore

---

docs/docs/references/environmentVariables.md
packages/backend/src/config/parseConfig.ts
packages/backend/src/controllers/authentication.ts
packages/backend/src/models/ProjectModel/ProjectModel.mock.ts

Closes: #2886 
- Adds an optional config key and corresponding environment variable for for the Okta `authorizationServerId`
- By default this value is blank, which enables support for the "Single Sign-On to Okta" authorization method [described in the docs](https://developer.okta.com/docs/reference/api/oidc/#composing-your-base-url)
- Custom authorization servers are still supported by passing a value for `AUTH_OKTA_AUTHORIZATION_SERVER_ID`—either `default` for the Okta-provided custom authorization server of the UUID of the custom authorization server your org created
- Note that this is a breaking change: users relying on the current behavior of setting the `default` custom authorization server will need to set a new environment variable (see example below). However, the breaking …

feat: enable Okta org auth server

---

packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts

fix: do not pivot on sql runner

---

docs/docs/references/update-lightdash.md

docs: fix wrong look for heroku upgrades

---

packages/frontend/src/components/DashboardTiles/DashboardMarkdownTile.styles.ts

fix: fix markdown color black

---

packages/e2e/cypress/e2e/savedDashboards.cy.ts
packages/frontend/src/components/NavBar/BrowseMenu/index.tsx
packages/frontend/src/components/NavBar/ExploreMenu/index.tsx
packages/frontend/src/components/NavBar/NavBar.styles.tsx
packages/frontend/src/components/NavLink.tsx

fixes menu styles broken by this PR: https://github.com/lightdash/lightdash/pull/3095

fix: navigation menu styles

---

packages/cli/src/index.ts

Closes: #2612
argument overrides ENV variable

feat: support DBT_PROJECT_DIR and DBT_PROFILES_DIR env variable on CLI

---

packages/common/src/index.ts
packages/frontend/src/components/common/Filters/FilterRuleForm.tsx

fix: fix filter default value on operator change

---

packages/frontend/src/components/ProjectConnection/DbtForms/AzureDevOpsForm.tsx
packages/frontend/src/components/ProjectConnection/DbtForms/BitBucketForm.tsx
packages/frontend/src/components/ProjectConnection/DbtForms/GithubForm.tsx
packages/frontend/src/components/ProjectConnection/DbtForms/GitlabForm.tsx
packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/BigQueryForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/PostgresForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/RedshiftForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/SnowflakeForm.tsx
packages/frontend/src/components/ReactHookForm/FromGroup.styles.ts
packages/frontend/src/components/ReactHookForm/InputWrapper.tsx
packages/frontend/src/components/ReactHookForm/MultiKeyValuePairsInput.tsx

feat: add onboarding instructions on helptext

---

docs/docs/references/roles.md

updates the actions in the roles table

docs: update roles.md

---

packages/frontend/src/components/ReactHookForm/FileInput.tsx

Closes:  https://github.com/lightdash/lightdash/issues/3003
- Add feedback card on successful upload
<details>
<summary>Screenshot</summary>
<br />
</details>

feat: add feedback card on upload success

---

packages/frontend/src/components/common/Table/BodyCell.tsx
packages/frontend/src/components/common/Table/Table.styles.ts

Closes: #3137 
fixes z-index problem with table headers

fix: filter tab appears behind table header

---

.github/workflows/manual-trigger-e2e-tests.yml

fix: manual e2e github action

---

packages/frontend/src/components/CreateUserForm/index.tsx
packages/frontend/src/pages/Login.tsx
packages/frontend/src/pages/PasswordRecovery.tsx

Closes: #3129 
- updated copy for login forms
- also updated forgot email form and signup forms

fix: login form copy

---

packages/backend/src/models/SpaceModel.ts

Closes: #3157 
- fixes backend: space list with dashboards did not fetch updatedAt correctly

fix: missing updatedAt date on space/dashboards

---

packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx
packages/frontend/src/components/common/Table/ScrollableTable/TableHeader.tsx
packages/frontend/src/hooks/useColumns.tsx

Closes: #3152 
show context menu with remove menuitem when field is invalid

fix: remove invalid field item

---

packages/cli/src/dbt/schema.ts

Closes: #3131 
Don't throw error when the model file is empty.

fix: generate yml when file is empty

---

packages/frontend/src/components/SimpleStatistic/BigNumberContextMenu.tsx
packages/frontend/src/components/SimpleStatistic/SimpleStatistics.styles.tsx
packages/frontend/src/components/SimpleStatistic/index.tsx

Closes: https://github.com/lightdash/lightdash/issues/3054
change bignumber context menu to open on left click instead of right click

feat: change bignumber context menu to open on left-click

---

packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTree.styles.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeGroupNode.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeNodes.tsx

Closes: #3155 
alphabet sort for tree node items

feat: table field list sort

---

packages/frontend/src/components/Explorer/SpaceBrowser/SpaceBrowser.styles.tsx
packages/frontend/src/components/Explorer/SpaceBrowser/SpaceItem.tsx
packages/frontend/src/components/Explorer/SpaceBrowser/index.tsx

Closes: #2898 
- extract SpaceItem component
- update margins
- change icon

style: update spaces component

---

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx

Closes: #2971 
adds links to dashboard and chart headers
https://user-images.githubusercontent.com/962095/188824887-5f7af447-9e9d-418a-98cd-e3b6d4fefae8.mp4

feat: add space links to chart and dashboard headers

---

packages/backend/src/dbt/profiles.ts
packages/backend/src/projectAdapters/dbtLocalCredentialsProjectAdapter.ts
packages/cli/src/dbt/targets/snowflake.ts
packages/common/src/index.ts
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Closes: #3132 
Snowflake docs:
https://docs.snowflake.com/en/user-guide/nodejs-driver-use.html#label-nodejs-key-pair-authentication

feat: snowflake key pair authentication in cli

---

packages/backend/src/services/SpaceService/SpaceService.ts
packages/common/src/authorization/organizationMemberAbility.test.ts
packages/common/src/authorization/organizationMemberAbility.ts
packages/common/src/authorization/projectMemberAbility.test.ts
packages/common/src/authorization/projectMemberAbility.ts
packages/common/src/authorization/types.ts
packages/frontend/src/components/Explorer/SpaceBrowser/SpaceItem.tsx
packages/frontend/src/components/Explorer/SpaceBrowser/index.tsx
packages/frontend/src/components/SpacePanel/index.tsx

Closes: #3134
Changes:
- add `Space` subject to our permissions matrix
- hide create/edit/delete buttons when user doesn't have permission
- amend backend space permissions

fix: space permissions

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/services/SpaceService/SpaceService.ts

Closes:  https://github.com/lightdash/lightdash/issues/3101
- Add `spaceId` to createSpace, updateSpace, deleteSpace events

chore: add spaceId to space track events

---

packages/common/src/compiler/translator.ts
packages/common/src/utils/formatting.ts

feat: quarter date formatting

---

packages/frontend/src/components/SortButton/index.tsx
packages/frontend/src/providers/ExplorerProvider.tsx

Closes: https://github.com/lightdash/lightdash/issues/3204
move item instead of swap
https://user-images.githubusercontent.com/962095/189317381-3f7fe9ee-4c0b-422c-b9c9-690eb1873445.mp4

fix: table multisort should reorder instead of swap

---

packages/common/src/index.ts

fix: table viz shows all custom metrics

---

packages/frontend/src/components/JobDetailsDrawer/JobDetailsDrawer.styles.tsx

Closes: #2064
Before:
After:
Set with and word wrap with auto hyphens

fix: wrap errors dbt compile

---

packages/backend/src/queryBuilder.ts
packages/backend/src/routers/projectRouter.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/frontend/src/components/DashboardFilter/index.tsx
packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx
packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
packages/frontend/src/components/common/Filters/FilterInputs/StringAutoComplete.tsx
packages/frontend/src/components/common/Filters/FiltersProvider.tsx
packages/frontend/src/hooks/useFieldValues.ts

Closes: #1660 
Add filter autocomplete:
- Autocomplete only available for string dimensions since it covers the majority of the use cases. We might extend this feature to other types later on.
- Autocomplete available in explore page and dashboard page
- Each search fetches 10 results 
- We don't cache values in our Database

feat: filter autocomplete

---

packages/frontend/src/components/SimpleChart/SimpleChart.styles.ts

Closes: #3199
This PR will not fix the cropped axis label 
This might affect charts on explore too, but I couldn't find any issues. 
[Screencast from 12-09-22 11:06:25.webm](https://user-images.githubusercontent.com/1983672/189615621-dc950cbb-8060-4619-8ee4-eb8c94fab7ac.webm)

fix: auto height for chart tile 

---

packages/cli/src/handlers/login.ts

fix: do not error when login in without projects

---

packages/cli/src/handlers/createProject.ts
packages/cli/src/handlers/deploy.ts
packages/cli/src/handlers/preview.ts
packages/cli/src/index.ts
packages/common/src/index.ts

Closes: #3077
[Screencast from 13-09-22 09:38:51.webm](https://user-images.githubusercontent.com/1983672/189840850-44e4b08b-fef9-4851-a64d-ae6a32fb4b24.webm)

feat: cli deploy create new project

---

packages/frontend/src/components/TableConfigPanel/index.tsx

fix: only disable table config when there are no results

---

packages/cli/src/analytics/analytics.ts
packages/cli/src/handlers/deploy.ts
packages/common/src/index.ts

fix: amend project type and add analytics to deploy create

---

packages/cli/package.json
packages/cli/src/handlers/preview.ts

Closes: #2534
[Screencast from 14-09-22 16:13:28.webm](https://user-images.githubusercontent.com/1983672/190179706-642a27bc-8911-4bdb-b065-7ca433fc34e1.webm)

feat: CLI preview reloads on DBT manifest file change

---

packages/cli/src/analytics/analytics.ts
packages/cli/src/handlers/preview.ts
packages/cli/src/index.ts

feat: start-preview and stop-preview CLI commands

---

packages/cli/src/dbt/targets/snowflake.ts
packages/common/src/index.ts
packages/frontend/src/components/ProjectConnection/WarehouseForms/SnowflakeForm.tsx

fix: snowflake role optional

---

packages/e2e/cypress/e2e/dashboard.cy.ts
packages/e2e/cypress/e2e/savedDashboards.cy.ts
packages/frontend/src/components/SpacePanel/index.tsx
packages/frontend/src/components/common/ResourceList/ResourceList.styles.ts
packages/frontend/src/components/common/ResourceList/ResourceTable/ResourceTable.styles.ts
packages/frontend/src/components/common/ResourceList/ResourceTable/index.tsx

removes react-table from resource lists
fixes flaky e2e test

feat: resource table without react-table

---

packages/frontend/src/components/Explorer/ExplorerHeader/ExplorerHeader.styles.tsx
packages/frontend/src/components/Explorer/ExplorerHeader/index.tsx
packages/frontend/src/components/RefreshDbtButton/index.tsx
packages/frontend/src/pages/ProjectSettings.styles.tsx
packages/frontend/src/pages/ProjectSettings.tsx
packages/frontend/src/pages/SqlRunner.styles.ts
packages/frontend/src/pages/SqlRunner.tsx

feat: move refresh dbt button to project settings page

---

packages/frontend/src/hooks/tableVisualization/getPivotDataAndColumns.ts

Closes: #3117
I didn't see any impact on performance, works as expected

feat: increase pivot limit to 60

---

docs/docusaurus.config.js
docs/package.json
docs/yarn.lock

Closes: #3153 
Note that this just makes the existing openapi schema available in our docs website. 
We still need to improve the openapi schema to have better descriptions, authentications, etc.

docs: openapi

---

packages/common/src/utils/formatting.ts
packages/frontend/src/hooks/useBigNumberConfig.ts

Closes: #3180 
Changes:
- show style config for custom metric and table calculations
- don't show style config if value isn't a number

fix: big number style config

---

docs/docs/guides/exploring-your-content.mdx
docs/docs/references/dimensions.mdx
docs/docs/references/metrics.md

Adds docs related to `show underlying values` in the .yml files
#3275

docs: adds underlying values limitation docs

---

packages/frontend/src/components/UnderlyingData/CellContextMenu.tsx
packages/frontend/src/components/UnderlyingData/UnderlyingDataResultsTable.tsx

fix: show cell menu in underlying data

---

packages/cli/src/config.ts
packages/cli/src/dbt/context.ts
packages/cli/src/handlers/compile.ts
packages/cli/src/handlers/createProject.ts
packages/cli/src/handlers/dbt/apiClient.ts
packages/cli/src/handlers/dbt/compile.ts
packages/cli/src/handlers/dbt/run.ts
packages/cli/src/handlers/deploy.ts
packages/cli/src/handlers/generate.ts
packages/cli/src/handlers/login.ts
packages/cli/src/handlers/preview.ts
packages/cli/src/handlers/setProject.ts
packages/cli/src/index.ts

Closes: #3110
Added verbose to all commands and a few new `console.errors` when it is enabled. 
Feel free to suggest new additions or remove some of the ones I added. 
Before:
After:

feat: add verbose flag to CLI

---

packages/backend/src/queryBuilder.mock.ts
packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts

Closes: #3249
Fixes bigquery `in the past`  filter for dates

fix: fix bigquery date filter in the past

---

packages/cli/src/handlers/dbt/apiClient.ts
packages/cli/src/handlers/deploy.ts
packages/cli/src/handlers/generate.ts
packages/cli/src/handlers/login.ts
packages/cli/src/handlers/preview.ts

feat: warn when cli and lightdash have different versions

---

packages/frontend/src/components/common/ResourceList/ResourceLastEdited/index.tsx
packages/frontend/src/components/common/ResourceList/ResourceTable/ResourceTable.styles.ts
packages/frontend/src/components/common/ResourceList/ResourceTable/index.tsx

- disables multisort
- remove absolute full-width link and replace with onClick
- add last edited at tooltip
https://user-images.githubusercontent.com/962095/191916455-bf9e6765-a885-4ee2-ab4f-529efcbaeddb.mp4

fix: resource table improvements

---

packages/cli/src/dbt/targets/Bigquery/oauth.ts

Closes: 
Allow using CLI with service credentials like:
Before:
After:

feat: cli supports bigquery oauth service credentials

---

packages/backend/src/queryBuilder.mock.ts
packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts

fix: fix in the last non completed dates and add tests

---

docs/docs/references/joins.md

docs: typo in joins doc

---

docs/docs/guides/how-to-create-dimensions.mdx
docs/docs/guides/how-to-create-metrics.mdx

- simplifies the content on the how to create dimensions docs
- includes instructions on how to manually define dimensions (in case the user isn't using the CLI)

docs: updates how to create dimensions docs

---

packages/backend/src/routers/userRouter.ts
packages/cli/src/handlers/login.ts
packages/cli/src/index.ts

Closes: #3328
I changed the way login with token worked. I also fixed the /user endpoint.
Before: token was just a boolean flag, interactive
After: token has a string with the token on it 
On invalid tokens

feat: change login with token

---

packages/frontend/src/components/Explorer/ExplorerHeader/ExplorerHeader.styles.tsx
packages/frontend/src/components/Explorer/ExplorerHeader/index.tsx
packages/frontend/src/components/RefreshDbtButton/index.tsx
packages/frontend/src/pages/ProjectSettings.styles.tsx
packages/frontend/src/pages/ProjectSettings.tsx
packages/frontend/src/pages/SqlRunner.styles.ts
packages/frontend/src/pages/SqlRunner.tsx

Closes: #3310
Reverts lightdash/lightdash#3260

fix: Revert "feat: move refresh dbt button to project settings page"

---

packages/backend/src/services/OrganizationService/OrganizationService.ts
packages/cli/src/handlers/dbt/apiClient.ts
packages/cli/src/handlers/login.ts
packages/e2e/cypress/e2e/api/projectPermissions.cy.ts
packages/e2e/cypress/e2e/projectPermission.cy.ts

fix: set empty project after login on CLI

---

packages/frontend/src/components/Explorer/ResultsCard/CellContextMenu.tsx
packages/frontend/src/components/common/Table/BodyCell.tsx
packages/frontend/src/components/common/Table/ScrollableTable/index.tsx
packages/frontend/src/components/common/Table/Table.styles.ts
packages/frontend/src/components/common/Table/TableProvider.tsx

Closes: #3324 
- disabling scroll when context menu is open
- disabling overflow container for context menu
- fix 0 value appearing in context menu

fix: cell context menu table overflow

---

packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts

Closes: #3366 
Apply the same fix we did for redshift here https://github.com/lightdash/lightdash/pull/2625

fix: postgres password with special chars

---

docs/docs/references/dimensions.mdx

docs: Using special characters on your column names

---

packages/frontend/src/components/SimpleChart/SimpleChart.styles.ts

Closes:#3349
Also tested again charts in explore
[Screencast from 03-10-22 08:33:51.webm](https://user-images.githubusercontent.com/1983672/193515101-39ec0550-c5cc-4df6-95df-94c8d7c0f9ab.webm)

feat: big charts on dashboards

---

packages/frontend/src/hooks/echarts/useEcharts.ts

Closes: #3360 
Example with simulated timezone in Sao Paulo

fix: axis label timezone

---

docs/docs/get-started/setup-lightdash/connect-project.mdx

fixes list of instructions for project connection updates

docs: updates instructions fo project connection settings

---

packages/cli/src/handlers/dbt/run.ts

fix: fix verbose flag on dbt commands

---

packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectManually.tsx
packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectSuccess.tsx
packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectUsingCLI.tsx
packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/InviteExpertFooter.tsx
packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ProjectConnectFlow.styles.tsx
packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/WareHouseConnectCard.tsx.tsx

Closes: https://github.com/lightdash/lightdash/issues/3372

feat: create project screen updates

---

packages/cli/src/handlers/login.ts

feat: warn when cloud server is not valid

---

packages/cli/src/handlers/compile.ts
packages/cli/src/handlers/dbt/run.ts
packages/cli/src/handlers/deploy.ts
packages/cli/src/handlers/generate.ts
packages/cli/src/handlers/preview.ts

fix: await cli error events

---

packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectUsingCLI.tsx

Updates copy on CLI onboarding to tell users to run command in their dbt project.

chore: updates copy on CLI tool onboarding

---

docs/docs/get-started/setup-lightdash/get-project-lightdash-ready.mdx
docs/docs/guides/limiting-data-using-filters.mdx

- adds info for dbt cloud users in onboarding
- adds error for not being in dbt project when executing CLI commands
- updates filters logic docs

docs: updates filters + onboarding docs

---

packages/cli/src/dbt/targets/Bigquery/oauth.ts
packages/cli/src/handlers/createProject.ts
packages/cli/src/handlers/deploy.ts

feat: warning if credentials project id does not match

---

packages/common/package.json
packages/common/src/types/filterGrammar.test.ts
yarn.lock

- import instead of require
- add ts types

chore: pegjs import

---

packages/common/src/compiler/translator.ts

Closes:  #3311
https://stackoverflow.com/a/13340151

fix: fix sql.replaceAll method on expression

---

packages/common/src/types/filter.ts
packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
packages/frontend/src/components/common/Filters/FilterInputs/UnitOfTimeAutoComplete.tsx

fix: date filter without time

---

packages/cli/src/handlers/preview.ts

Closes: #3400
[Screencast from 06-10-22 09:15:30.webm](https://user-images.githubusercontent.com/1983672/194244527-8a6f7014-5552-4501-848b-5e9a288a7735.webm)

fix: update copy shutdown preview cli

---

docs/docs/guides/cli/how-to-use-lightdash-preview.mdx

docs: fix close preview link

---

packages/cli/src/analytics/analytics.ts

Closes: 
Don't check env since users can login with token

fix: user uuid missing from events

---

packages/cli/src/handlers/preview.ts

Closes: 
When running in the CI ( github action ) set the url as an output
github action docs on how to set output https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-setting-a-value

feat: CLI start-preview output url

---

packages/frontend/src/components/NavBar/GlobalSearch/hooks.ts

Closes: #3338
[Screencast from 07-10-22 12:29:08.webm](https://user-images.githubusercontent.com/1983672/194533477-05c37978-8313-4708-ab04-d9a27941b56c.webm)

fix: fix global search no results when filtering

---

packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectManually/ConnectManuallyStep2.tsx
packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectUsingCLI.tsx
packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ProjectConnectFlow.styles.tsx
packages/frontend/src/providers/TrackingProvider.tsx
packages/frontend/src/types/Events.ts

reintroduces demo project link to cli onboarding screen

feat: add try demo project link

---

packages/e2e/cypress/e2e/createProjects.cy.ts
packages/frontend/src/components/ProjectTablesConfiguration/ProjectTablesConfiguration.tsx

chore: change table selection button text

---

docs/docs/guides/formatting-your-fields.mdx

fix: docs typo

---

packages/frontend/src/pages/ProjectSettings.tsx

Fix a typo on the Project Setttings > Table Configuration page.

style: fix typo

---

packages/frontend/src/pages/CreateProjectSettings.tsx
packages/frontend/src/pages/ProjectSettings.tsx

Closes: https://github.com/lightdash/lightdash/issues/3336
fixes typos

fix: typos in project settings

---

packages/e2e/cypress/e2e/projectPermission.cy.ts
packages/frontend/src/App.tsx
packages/frontend/src/components/NavBar/index.tsx
packages/frontend/src/components/ProjectRoute.tsx
packages/frontend/src/components/UserSettings/ProjectManagementPanel/index.tsx
packages/frontend/src/hooks/useProjects.ts
packages/frontend/src/pages/Projects.tsx

Closes: https://github.com/lightdash/lightdash/issues/3226
- invalidate projects on delete
- reset projects on 404
- icon updates
- fix bug with localstorage saved project UUID when project gets deleted
https://user-images.githubusercontent.com/962095/194526440-fe17c6ad-a7d1-4aba-9720-cc7701bcdbea.mp4

fix: projects invalidation and data resetting on 404

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx

feat: include dashboard filters when exploring from chart

---

packages/frontend/src/components/ProjectConnection/WarehouseForms/BigQueryForm.tsx

Closes: #3446
changes link on keyfile for BigQuery to link to our docs

chore: updates link to json key file docs

---

packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx

Closes:  #3471
Copied most of the logic from `CreateSavedQueryModal`
[Screencast from 12-10-22 17:11:27.webm](https://user-images.githubusercontent.com/1983672/195381394-365a543a-1642-48dd-be71-761113ccd19b.webm)

feat: create new dashboard and space from saved chart

---

packages/frontend/src/components/common/Filters/FieldAutoComplete.tsx

feat: show dimension icons on filter fields

---

packages/backend/src/database/migrations/20221013070147_dbt_connection_type_none.ts
packages/backend/src/projectAdapters/dbtNoneCredentialsProjectAdapter.ts
packages/backend/src/projectAdapters/projectAdapter.ts
packages/cli/src/handlers/createProject.ts
packages/common/src/index.ts
packages/frontend/src/components/ProjectConnection/DbtForms/DbtNoneForm.tsx
packages/frontend/src/components/ProjectConnection/DbtSettingsForm.tsx
packages/frontend/src/components/RefreshDbtButton/RefreshDbtbutton.styles.tsx
packages/frontend/src/components/RefreshDbtButton/index.tsx

feat: disable refresh dbt on dbt project type None

---

packages/frontend/src/components/common/Filters/FilterInputs/AutoComplete/AutoComplete.tsx
packages/frontend/src/components/common/Filters/FilterInputs/AutoComplete/MultiAutoComplete.tsx
packages/frontend/src/components/common/Filters/FilterInputs/AutoComplete/autoCompleteUtils.ts

Closes: https://github.com/lightdash/lightdash/issues/3302
ℹ️ intentionally slowed down loading for this demo video
https://user-images.githubusercontent.com/962095/195636155-95a0491b-4b90-4add-8c3f-e7dddfbc552d.mp4

fix: show spinner on initial load for autocompletes

---

packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectUsingCLI.tsx
packages/frontend/src/pages/CreateProject.tsx

Show command to install the CLI version that matches the server

fix: create project with specific CLI version

---

packages/common/src/index.mock.ts
packages/common/src/index.test.ts
packages/common/src/index.ts
packages/frontend/src/App.tsx
packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx

Closes:  #3481
Ok, this one was tricky,and it was caused by a different set of timezone issues. Added comments to the code.
Before: 
[Screencast from 14-10-22 11:21:01.webm](https://user-images.githubusercontent.com/1983672/195818477-b656aa8d-b18c-4e51-b240-960a25985ba9.webm)
After:
[Screencast from 14-10-22 02:43:37.webm](https://user-images.githubusercontent.com/1983672/195818529-0cbb12ab-94e4-4dc3-a2ba-51323aeb38f8.webm)

fix: timezone filter issues

---

packages/frontend/src/components/UnderlyingData/UnderlyingDataModalContent.tsx

Closes:  #3490
Normal underlying data (no fields, 1 filter) 
[Screencast from 14-10-22 15:39:32.webm](https://user-images.githubusercontent.com/1983672/195862414-25a62882-b1d6-49e6-960d-58c60bb501a8.webm)
Metric with `show_underlying_values` (order_date field , 1 filter) 
[Screencast from 14-10-22 15:40:58.webm](https://user-images.githubusercontent.com/1983672/195862363-bc57299c-52b5-4c9e-9346-34043509417a.webm)
Bonus: Metric with `show_underlying_values` and metric filters (customer_id field, 3 filters) 
[Screencast from 14-10-22 15:39:50.webm](https://user-images.githubusercontent.com/1983672/195862399-aa085c0b-a944-4ddf-a6bc-30b8432ee487.webm)

feat: remove selected fields from underlying data explore from here

---

.github/CONTRIBUTING.md

Closes: 
- Added missing step in dev-setup

chore: add missing step in dev-setup

---

docs/docs/guides/dbt-semantic-layer.mdx

docs: fix images path

---

packages/common/src/index.ts
packages/e2e/cypress/e2e/explore.cy.ts
packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
packages/frontend/src/components/common/MonthAndYearInput.tsx
packages/frontend/src/components/common/WeekPicker.tsx
packages/frontend/src/components/common/YearInput.tsx

Closes:#3521
I fixed a couple of UTC / non UTC date (most of them were affecting component visualization, not the actual filter or SQL). Some changes might not be required, but it currently works. 
[Screencast from 19-10-22 01:22:20.webm](https://user-images.githubusercontent.com/1983672/196665252-15320389-665e-4d1c-8119-a648beb62e44.webm)
[Screencast from 19-10-22 13:40:33.webm](https://user-images.githubusercontent.com/1983672/196685568-52a52532-fc35-43de-87b9-a616a2bbaa99.webm)

fix: filter dates from table and dimensions timezone issue

---

packages/frontend/.eslintrc.js
packages/frontend/src/components/Explorer/ResultsCard/UrlMenuItems.tsx
packages/frontend/src/components/JobDetailsDrawer/index.tsx
packages/frontend/src/components/ProjectTablesConfiguration/ProjectTablesConfiguration.tsx
packages/frontend/src/components/TableConfigPanel/ColumnConfiguration.tsx
packages/frontend/src/components/UserSettings/SocialLoginsPanel/index.tsx
packages/frontend/src/components/common/modal/DeleteActionModal.tsx

enable eslint error if react key is missing from required places and add missing keys

chore: enable eslint jsx-key error

---

packages/frontend/src/components/common/Filters/FilterInputs/AutoComplete/MultiAutoComplete.tsx
packages/frontend/src/components/common/Filters/FilterInputs/AutoComplete/autoCompleteUtils.ts

Closes: https://github.com/lightdash/lightdash/issues/3500
implements adding item on blur for `MultiAutoComplete`.
I read `MultiSelect`/`MultiSelect2`/`TagInput` source code and unfortunately `MultiSelect`/`MultiSelect2` does not support receiving onBlurs from `TagInput`. Created Blueprint issue here https://github.com/palantir/blueprint/issues/5683
https://user-images.githubusercontent.com/962095/196809715-3b4b44fc-848c-4903-8e03-a4d2ceaa4e0e.mp4

feat: MultiAutoComplete add item on blur

---

packages/cli/src/dbt/models.ts

Closes:  #3505
- Add alias
- DBT run 
- lightdash generate
- lightdash preview

fix: CLI alias on DBT

---

.github/workflows/cli-test.yml

test: upgrade dbt 1.3 on cli test

---

packages/e2e/cypress/e2e/formats.cy.ts

Closes: https://github.com/lightdash/lightdash/issues/3027

test: update jaffle_shop dbt with format and rounds, add e2e tests

---

packages/frontend/src/components/UnderlyingData/UnderlyingDataModalContent.tsx
packages/frontend/src/components/UnderlyingData/UnderlyingDataResultsTable.tsx

Closes: https://github.com/lightdash/lightdash/issues/3545

feat: sort results table columns by show_underlying_values

---

packages/frontend/src/components/TableConfigPanel/ColumnConfiguration.tsx
packages/frontend/src/components/TableConfigPanel/TableConfig.styles.ts
packages/frontend/src/components/TableConfigPanel/index.tsx
packages/frontend/src/hooks/plottedData/usePlottedData.mock.ts
packages/frontend/src/hooks/plottedData/usePlottedData.test.ts
packages/frontend/src/hooks/plottedData/usePlottedData.ts
packages/frontend/src/hooks/tableVisualization/getPivotDataAndColumns.ts
packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
packages/frontend/src/hooks/usePivotDimensions.ts

feat: support multiple pivots in table visualisations 

---

docs/docs/get-started/setup-lightdash/get-project-lightdash-ready.mdx
docs/docs/guides/cli/how-to-install-the-lightdash-cli.mdx
docs/docs/snippets/how-to-install-the-lightdash-cli.mdx

Closes: https://github.com/lightdash/lightdash/issues/3526
Closes: https://github.com/lightdash/lightdash/issues/3525
- adds instruction on how to install NodeJS using NVM
- reference to alternative installation instructions using preferred package manager
- reference to the guide on how to resolve EACCES permission error.
❓❓❓ question
how can I extract markdown fragment and include it in different pages?
Didn't want to reference from one page to another and I had to copy paste the same instructions in two different places.

docs: nodejs setup guide

---

docs/docs/snippets/how-to-install-the-lightdash-cli.mdx

forgot to commit latest changes (copy approved)

docs: append forgotten changes to nodejs setup guide

---

packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/OrganizationService/OrganizationService.ts
packages/cli/src/handlers/login.ts
packages/cli/src/handlers/setProject.ts
packages/e2e/cypress/e2e/api/api.cy.ts
packages/e2e/cypress/e2e/api/organizationPermissions.cy.ts
packages/e2e/cypress/e2e/api/projectPermissions.cy.ts
packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectUsingCLI.tsx
packages/frontend/src/components/UserSettings/ProjectManagementPanel/index.tsx
packages/frontend/src/hooks/useProjects.ts

from conversation in the slack https://lightdash.slack.com/archives/C02GQKJK84Q/p1666627831455609

fix: projects 404

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/UnderlyingData/UnderlyingDataModalContent.tsx
packages/frontend/src/components/UnderlyingData/UnderlyingDataProvider.tsx

Closes: #3547
[Screencast from 24-10-22 14:02:10.webm](https://user-images.githubusercontent.com/1983672/197522082-dba6909a-4b29-46f7-9126-d6aa4758739e.webm)

fix: fix filter for underlying data on dashboard

---

packages/backend/src/queryBuilder.mock.ts
packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts
packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx

Closes:  https://github.com/lightdash/lightdash/issues/3509
- Added support to input multi-values for includes, notIncludes & startsWith filter

feat: support multiple values on filters: includes, not includes and starts with

---

packages/e2e/cypress/e2e/createProjects.cy.ts
packages/e2e/cypress/e2e/projectPermission.cy.ts
packages/e2e/cypress/e2e/settings/invites.cy.ts
packages/e2e/cypress/e2e/settings/profile.cy.ts
packages/frontend/src/components/Avatar.tsx
packages/frontend/src/components/NavBar/SettingsMenu/index.tsx
packages/frontend/src/components/NavBar/UserMenu/index.tsx
packages/frontend/src/components/NavBar/index.tsx
packages/frontend/src/hooks/useProject.ts
packages/frontend/src/hooks/user/useUserLogoutMutation.ts

Closes: https://github.com/lightdash/lightdash/issues/3426
- menu for owners:
- menu for admins:
- gear icon hides for members/viewers
- added user settings menu item

feat: settings menu

---

packages/common/src/index.test.ts
packages/common/src/index.ts
packages/common/src/utils/formatting.ts
packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx

Closes: #3583
Dropping some date conversions, converting to string to avoid timezone issues 
Before:
[Screencast from 26-10-22 09:06:13.webm](https://user-images.githubusercontent.com/1983672/197959008-5f1ec369-cc36-4123-912a-dc06a58f0602.webm)
After:
[Screencast from 26-10-22 09:13:28.webm](https://user-images.githubusercontent.com/1983672/197959154-2ffc9f18-cab9-4ecf-9162-7d3e82e80993.webm)

fix: select filter date (again)

---

packages/common/src/index.ts
packages/common/src/types/savedCharts.ts
packages/frontend/src/components/ChartConfigPanel/FieldLayoutOptions.tsx
packages/frontend/src/components/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
packages/frontend/src/components/Explorer/VisualizationCard/SeriesContextMenu.tsx
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCardBody.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/SimpleChart/index.tsx
packages/frontend/src/components/TableConfigPanel/index.tsx
packages/frontend/src/components/UnderlyingData/UnderlyingDataProvider.tsx
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.mock.ts
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.test.ts
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
packages/frontend/src/hooks/cartesianChartConfig/utils.ts
packages/frontend/src/hooks/echarts/useEcharts.ts
packages/frontend/src/hooks/plottedData/usePlottedData.ts

feat: multi pivot chart

---

packages/frontend/src/components/ProjectAccess/ProjectAccessCreation/ProjectAccessCreation.ts
packages/frontend/src/components/ProjectAccess/ProjectAccessCreation/index.tsx
packages/frontend/src/components/UserSettings/InvitesPanel/InvitesPanel.styles.ts
packages/frontend/src/components/UserSettings/InvitesPanel/index.tsx
packages/frontend/src/components/UserSettings/UserManagementPanel/InviteSuccess.styles.ts
packages/frontend/src/components/UserSettings/UserManagementPanel/InviteSuccess.tsx
packages/frontend/src/components/UserSettings/UserManagementPanel/UserManagementPanel.styles.ts
packages/frontend/src/components/UserSettings/UserManagementPanel/index.tsx
packages/frontend/src/hooks/useInviteLink.tsx

Closes: #2935 
This PR:
- combines all the invite success messages into 1
- reuse component on 3 places
https://user-images.githubusercontent.com/9117144/198075155-86304339-1ef2-4570-90ad-396c62f39ab3.mp4

fix: invite success message

---

packages/backend/src/models/DashboardModel/DashboardModel.mock.ts
packages/backend/src/models/UserModel.ts
packages/backend/src/services/DashboardService/DashboardService.mock.ts
packages/backend/src/services/OrganizationService/OrganizationService.mock.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/backend/src/services/ShareService/ShareService.mock.ts
packages/common/src/openapi/schemas/Dashboard.json
packages/common/src/openapi/schemas/LightdashUser.json
packages/common/src/openapibundle.json
packages/common/src/types/user.ts
packages/frontend/src/components/Intercom.tsx

Closes: #3586 
Send organization created date to intercom.

chore: update intercom event with org created date

---

.github/workflows/cli-test.yml
packages/e2e/cypress/cli/cli.cy.ts

chore: disable prod analytics on cli tests

---

packages/warehouses/package.json
packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts
yarn.lock

upgrades databricks package to 1.0.0

chore: upgrade databricks package

---

packages/frontend/src/components/UnderlyingData/UnderlyingDataProvider.tsx

fix: cannot read pivotReference from undefined

---

packages/frontend/src/components/common/MonthAndYearInput.tsx
packages/frontend/src/components/common/WeekPicker.tsx
packages/frontend/src/components/common/YearInput.tsx

Closes: 
Fix current timezone e2e errors on main

fix: timezone e2e tests

---

packages/frontend/src/components/DownloadCsvPopup/index.tsx
packages/frontend/src/components/Explorer/ResultsCard/ResultsCard.tsx

Closes: https://github.com/lightdash/lightdash/issues/3590
[Screencast from 27-10-22 12:12:08.webm](https://user-images.githubusercontent.com/1983672/198258435-f43eacc5-56cc-40c6-93ae-af5a57daf1f9.webm)

feat: unformatted csv download option on popup

---

packages/frontend/src/components/NavBar/SettingsMenu/index.tsx
packages/frontend/src/pages/ProjectSettings.tsx
packages/frontend/src/pages/Settings.tsx

Closes: https://github.com/lightdash/lightdash/issues/3610
changed from manage to view permissions for projects as users are still able to see read-only version of project settings page/organization settings.

fix: view project permissions in the UI
