packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer/VisualizationCard/SeriesContextMenu.tsx

blueprint portal uses legacy context. replacing it with mantine is a simple change which also gets rid of annoying console warnings like this:

chore: get rid of blueprint portals

---

packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
packages/frontend/src/components/DashboardFilter/Filter.tsx
packages/frontend/src/components/DashboardFilter/index.tsx
packages/frontend/src/components/DashboardTiles/AddTileButton.tsx
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx
packages/frontend/src/components/SimpleTable/DashboardCellContextMenu.tsx
packages/frontend/src/components/common/Dashboard/DashboardRefreshButton.tsx
packages/frontend/src/features/scheduler/components/SchedulerFilters.tsx
packages/frontend/src/hooks/dashboard/useDashboardChart.ts
packages/frontend/src/hooks/dashboard/useDashboardFiltersForExplore.ts
packages/frontend/src/hooks/dashboard/useDashboardFiltersForTile.ts
packages/frontend/src/pages/Dashboard.tsx
packages/frontend/src/providers/DashboardProvider.tsx

- adding `use-context-selector` to dashboard context
- we use this library for explore contexts → see `useExplorerContext`

chore: dashboard provider use context selector

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx

this actually has a significant performance impact (positive) and regression was recently introduced
toggling between edit/view mode now is 0.5 sec instead of 3 sec 🎉

fix: dashboard chart tile perf by caching results

---

packages/frontend/src/features/sync/components/SyncModalView.tsx

Closes: #6968 
Makes the dialog footer sticky on the google sync dialog. 
I did this with css cause we were struggling with the ScrollArea. I don't love the negative margin but it's what we have been generally doing to get these footers right. We should consider adding a dialog footer.

fix: keep google sync dialog footer in view

---

packages/backend/src/generated/swagger.json
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/index.ts
packages/common/src/types/dashboard.ts
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/hooks/dashboard/useDashboard.tsx
packages/frontend/src/providers/DashboardProvider.tsx

Closes: #7946
**Improving `/availableFilters` payload by reducing its size:**
Currently, we store **all** available filterable fields per tile in a massive object, like so: 
```
{
[chartUuid]: [{...field1}, {...field2}]
}
```
This can be extremely big if the table the chart belongs to contains many fields + joined tables
With this change, we are: 
* caching explores in memory - reducing the call of `getExplore` if charts in a dashboard share the same `tableName`
* getting all filterable fields
* and an indexed map per tile
* Sending extra info to the body of the request, by sending an array of objects that contains both the tileUuid and the savedChartUuid
like so (from render)
**Note^**
Now the Uuids are the tile Uuids and not the saved query Uuids - these don't need to be computed on the …

fix: improve available filters and metric query suggestions

---

packages/e2e/cypress/e2e/app/createProjects.cy.ts

Expect 10 models in the tests
Trigger all e2e tests:
test-cli
test-backend
test-frontend

chore: expect 10 models in tests

---

packages/frontend/src/features/scheduler/components/SchedulersList.tsx

Closes: #7977 
Filter google sheets syncs out of the scheduled deliveries modal list. They show up in the google sync modal.

fix: don't show gsheets sync in schedulers list

---

packages/frontend/src/components/Explorer/ExplorerHeader/index.tsx

Closes: #7910 
When the refresh dbt button doesn't show, it returns null. This puts it in a box so the layout doesn't break when that button isn't there.

fix: run query stays on the right

---

packages/frontend/src/components/common/modal/ChartCreateModal.tsx

Closes: #7988 
Charts were getting created in spaces instead of in dashboards because we weren't sending a dashboard Id. I fixed that and added better types. I guess we need to be very careful with mantine form types. 
I'll think about how else we could have caught this.

fix: charts dashboards saved to the wrong place

---

packages/frontend/src/components/common/FieldSelect/index.tsx

Closes: #7927 
Added a delay on tooltip popups
[Screencast from 13-11-23 23:35:39.webm](https://github.com/lightdash/lightdash/assets/76876702/a1494d03-e013-458e-8f14-932f13d9f101)

fix: delay on tooltips in dashboard filter results

---

packages/frontend/src/pages/Dashboard.tsx

Adds a user error when charts in dashboards fail to parse

feat: add user error on chart parse failure

---

packages/frontend/src/pages/Dashboard.tsx

Closes: #8006 
There was a race condition when returning from creating a chart in a dashboard that cause the new chart to sometimes not be saved. The useEffect that adds the live charts to the dashboard was setting the charts in the dashboard unsafely. It was setting the set of charts when a new chart was added, but sometimes then setting the charts back to the saved charts from the server. This makes sure we only set to the saved charts in the server when there are no other charts.

fix: charts sometimes dont save to dashboards

---

packages/frontend/src/hooks/useSavedQuery.ts

Closes: #7937 
I tried invalidating manually with the react-query devtools but only resetting that query works. Chart config was also not changing in the cache but it is now.
[Screencast from 15-11-23 19:11:41.webm](https://github.com/lightdash/lightdash/assets/76876702/84ba927b-d529-4c24-8550-20bc57317f5a)

fix: changing chart data requires dashboard refresh

---

packages/common/src/types/scheduler.ts
packages/frontend/src/features/scheduler/components/SchedulerFilters.tsx
packages/frontend/src/features/scheduler/components/SchedulerForm.tsx
packages/frontend/src/hooks/useSavedDashboardFiltersOverrides.tsx
packages/frontend/src/pages/MinimalDashboard.tsx
packages/frontend/src/providers/DashboardProvider.tsx

Relates to: #4425
Adds the ability to save `filters` into a scheduler
Overrides dashboard filters on Minimal page aka scheduler page for it to take a screenshot of. 
**note**: This doesn't work with `Send now` feature yet

feat: dashboard filters with image format

---

packages/backend/src/scheduler/SchedulerTask.ts
packages/backend/src/services/CsvService/CsvService.ts
packages/common/src/types/filter.ts
packages/frontend/src/hooks/useSavedDashboardFiltersOverrides.tsx
packages/frontend/src/providers/DashboardProvider.tsx

Relates to: #4425
Passes `schedulerFilters` to `csvService` so that the charts are pulled with the dashboard filters + overrides (whatever the user changes on the scheduler
Moves util `applyDimensionOverrides` so that it can be reused across the stack.

feat: enable dashboard scheduled delivery filters for csv export

---

packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
packages/frontend/src/providers/DashboardProvider.tsx

Closes: #8001 
Fixes an issue with changing filters while editing them. We were deleting filters in a draft state when they were changed. This patch makes two changes: 1) only add overrides to filters that have been saved to the DB, 2) When overrides are applied, include the draft filters in the set that gets updated.

fix: changing an unsaved filter won't delete it

---

packages/backend/src/scheduler/SchedulerTask.ts
packages/frontend/src/pages/MinimalDashboard.tsx

Closes: #8025 
Note: this was already working with CSV exports
With the `Send Now` feature for scheduled deliveries, we want to be able to include the filters to the minimal URL (like we do with the exporting of a dashboard (with saved filter overrides) 
I was looking at different ways to avoid using the URL search param: 
* reuse the `schedulerUuid` search param, but the `send now` feature does not create one 
* set a cookie - didn't work as expected. Even when set properly, the screenshot wouldn't work properly
* set localstorage - this didn't work at all
So, instead, we set a searchParam `sendNowSchedulerFilters` that has the same format as `SchedulerFilterRule[]` and get that or the other (from the scheduler with the `schedulerUuid`), depending on what's present.

feat: add send now scheduler filters to URL

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/DashboardTiles/EditChartMenuItem.tsx

Closes: #8016 
We were not showing the chart editing controls when a chart errored out. This adds the edit button to a tile with errors. 
Writing this made me want to clean up the tile hierarchy more. There are a lot of wrappers that probably don't all need to be in there.

fix: enable editing charts with errors

---

packages/backend/src/models/ProjectModel/ProjectModel.ts

Closes: #7965 
Field search behaviour was different depending on which explore cache we hit. This makes the behaviour the same.
note that this function still has the same limitations of the previous version (finding a field_id is not always reliable depending on explore and alias names)

fix: explore search by fieldId to prioritise base table match over joined tables

---

packages/frontend/src/providers/ExplorerProvider.tsx

Closes: #7991 
editing a custom metric now changes affected columns. I removed the `TOGGLE-METRIC` dispatch because it resets the custom metric's sort field which I don't think is necessary for an edit.
[Screencast from 17-11-23 10:18:37.webm](https://github.com/lightdash/lightdash/assets/76876702/8fc0aa58-40ec-4996-991d-de43df5d7f43)

fix: change custom metric sorting with custom metric name

---

packages/frontend/src/hooks/useSavedDashboardFiltersOverrides.tsx

Closes: N/A
Now that Filters can have `tableCalculations`, let's ensure that the overrides types also include that, by syncing the state's types with `DashboardFilter` keys

fix: sync override type with the dashboard filter one

---

packages/frontend/src/features/scheduler/components/SchedulerFilters.tsx

Relates to: #4425
Display `dashboard filter`'s label if it exists, but always fallback to the field label when viewing scheduled delivery filters

chore: show dashboard filter label if exists in scheduler filters

---

packages/frontend/src/features/dateZoom/components/DateZoom.tsx
packages/frontend/src/pages/Dashboard.tsx

Relates to: #8036
Disables Menu when editing a dashboard. 
Once user leaves edit mode, then reset the date zoom.
https://github.com/lightdash/lightdash/assets/7611706/64daeb38-f493-4936-b6b2-805d4ae97fd7

feat: disable and clear date zoom on edit mode

---

packages/e2e/cypress/e2e/app/customDimensions.cy.ts
packages/e2e/cypress/e2e/app/downloadCsv.cy.ts
packages/e2e/cypress/e2e/app/explore.cy.ts
packages/frontend/src/components/Explorer/ExploreTree/TableTree/index.tsx
packages/frontend/src/components/Explorer/ExploreTree/index.tsx

Closes: #3201 
https://github.com/lightdash/lightdash/assets/9117144/85e2a8c9-e2a6-4e9c-b8cf-3875a701dac0

feat: collapse join tables by default

---

packages/frontend/src/features/dateZoom/components/DateZoom.tsx
packages/frontend/src/features/dateZoom/constants/index.ts
packages/frontend/src/features/dateZoom/index.ts
packages/frontend/src/providers/DashboardProvider.tsx

Relates to: https://github.com/lightdash/lightdash/issues/8036
`DashboardProvider` should store current date zoom granularity to it can be used by a chart tile when user changes its value. 
Also, moved the options to `dateZoom`/`constants` folder.

chore: store date zoom granularity in dashboard provider

---

packages/frontend/src/features/dateZoom/components/DateZoom.tsx

Closes: N/A
After some merges, forgot to replace the function call `setDateGranularity` with the correct one: `setDateZoomGranularity`

fix: replace wrong function name call

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/types/metricQuery.ts

Closes: N/A
There's a missing `tableCalculations` property that `MetricQueryRequest` could take in the `filters` property. 
I think this came from work on table calculations + filters, but yea, all good now
Error before: 
```ts 
{
"status": "error",
"error": {
"statusCode": 422,
"name": "ValidateError",
"message": "",
"data": {
"body.filters": {
"message": "\"tableCalculations\" is an excess property and therefore is not allowed",
"value": {
"tableCalculations": {
"id": "c8cb4287-c5a1-4c8d-baf3-e84a1288e461",
"and": []
}
}
}
}
}
}
```
You can test by: 
* adding a saved filter to a dashboard
* applying a filter that affects a chart
* `Explore from here` on that chart that has a dsahboard filter applied

fix: add missing tableCalculations type property

---

package.json
packages/backend/README.md
packages/backend/src/generated/swagger.json

Closes: 
There were some problems when rebasing where generating the API docs without compiling the common package where most types are.
The new command builds common + generates API + formats generated files

chore: improve command to generate API docs

---

packages/backend/src/controllers/savedChartController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/ProjectService/ProjectService.ts
packages/e2e/cypress/e2e/api/projectPermissions.cy.ts
packages/frontend/src/hooks/dashboard/useDashboardChart.ts
packages/frontend/src/hooks/useQueryResults.tsx

Closes: 
The `/results` endpoint was being used for the dashboard page and the chart page in view mode.
This was causing a few issues:
- increasing logic and params to handle both scenarios 
- since we stopped fetching the chart separately on the dashboard page, we stopped counting chart views (#8067)
- this will be fixed in following PR 
Now we have
`/results` used by chart page in view mode
`/chart-and-results` used by dashboard page
Even though most of the service code is similar, it is now simpler and easier to keep diverging logic between them. eg: count for chart view in `/chart-and-results`

refactor: split chart results endpoint

---

packages/backend/package.json
packages/backend/src/analytics/client.ts
packages/backend/src/index.ts
packages/backend/src/postHog.ts
yarn.lock

Closes: N/A
Adds `node-posthog` (followed this: https://posthog.com/docs/libraries/node)
Instantiates new PostHog client on the server; 
Identifies the user and group (same way we do in: https://github.com/lightdash/lightdash/blob/chore/enable-posthog-usage-on-backend/packages/frontend/src/providers/ThirdPartyServicesProvider.tsx#L12)
Shuts down `onExit`
Example: 
```ts
const isFeatureEnabled = await postHogClient.isFeatureEnabled(
'date-zoom',
user.userId.toString(),
);
```

chore: enable posthog on backend

---

packages/backend/src/analytics/client.ts
packages/backend/src/postHog.ts

Closes: N/A
Allow PostHog client to be undefined if no `projectApiKey` provided. No need to check for `apiHost` because it's got a default of: `'https://app.posthog.com'`

fix: add undefined value to posthog if no key

---

packages/frontend/src/components/DashboardTiles/AddTileButton.tsx
packages/frontend/src/components/DownloadCsvButton/index.tsx
packages/frontend/src/components/MetricQueryData/UnderlyingDataModalContent.tsx
packages/frontend/src/components/common/LinkButton.tsx

Small mantine migrations:
- Remove unused PopoverPosition
- Move the underlying data modal buttons to mantine. Make them not primary. 
Buttons before
Buttons after

chore: move some dashboard buttons to mantine

---

packages/frontend/src/components/ToastSpinner/index.ts
packages/frontend/src/providers/ActiveJobProvider.tsx

Remove ToastSpinner and replace it's usage with Mantine. Refreshing dbt is a good way to test this. It appears in the toast. 
Before (blueprint)
After 🎉

chore: remove ToastSpinner

---

packages/frontend/src/features/scheduler/components/SchedulerFilters.tsx

Closes: N/A
As suggested in: #8059, add copy next to the field label when: 
* filter is `disabled`/accepts any value 
and
* there's been no changes 
https://github.com/lightdash/lightdash/assets/7611706/0126b09f-e85f-41f2-84e6-996967dc216f

feat: display filter summary if not overridden

---

docs/docs/guides/cli/how-to-use-lightdash-preview.mdx

Closes: N/A
Add import to `GithubSecrets` snippet. It wasn't showing before in https://docs.lightdash.com/guides/cli/how-to-use-lightdash-preview#step-1-add-the-credentials-to-github-secrets after `If you haven't already set up a GitHub action for Lightdash, you'll need to add some secrets to GitHub. If you already have a GitHub action for Lightdash, then you can use the same Lightdash secrets you created for your other action.`
Now, it is rendered:

docs: add missing import paths to gh secrets

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/services/DashboardService/DashboardService.ts
packages/backend/src/services/SavedChartsService/SavedChartService.ts
packages/backend/src/services/SchedulerService/SchedulerService.ts

Closes: #7397
Add `filtersUpdatedNum` to: 
* `scheduler.created`
* `scheduler.updated`
Also, type event data objects with the already created types.

feat: add filter data to scheduler events

---

packages/backend/src/services/ProjectService/ProjectService.ts

Closes: [#8104](https://github.com/lightdash/lightdash/issues/8104)
Create a chat with a date on table calculation, like this 
```
SUM(${orders.unique_order_count})
OVER(ORDER BY ${orders.order_date_day})
```
Then add it to the filter and change the time zoom
This should also work with missing frames (eg: quarter)

fix: date zoom on table calcs

---

packages/frontend/src/hooks/useSqlRunnerColumns.ts

When a column name in the SQL runner contains a dot, the front end crashes. This fixes the crash by catching the error and logging the error. We could do more to handle this case, but I wasn't sure the best approach to fixing the underlying problem and fixing the crash is necessary anyway. With this change a field that has an error will show the string 'Error' in the table and log in the console. I hadn't put 'Error' in the results at first, but almost anything else could be misleading -- I wan't to make sure they know they aren't seeing data. 
The real problem here is that when there is a `.` in a field name, we use a fieldId to reference the column, which removes the dot. But the data still has the original field ID, so when the table tries to reference it, it fails. I'm not sure the …

fix: dont crash when column name contains a dot

---

.github/workflows/cli-tests.yml
dockerfile
dockerfile-prs
packages/backend/src/dbt/dbtCliClient.ts
packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts
packages/cli/src/dbt/manifest.ts
packages/cli/src/handlers/compile.ts
packages/cli/src/handlers/dbt/getDbtVersion.ts
packages/common/src/dbt/schemas/lightdashV11.json
packages/common/src/dbt/schemas/manifestV11.json
packages/common/src/dbt/validation.ts
packages/common/src/types/dbt.ts
packages/common/src/types/projects.ts

Closes: #7797 
Note: to test with the jaffle shop project you must delete `examples/full-jaffle-shop-demo/dbt/models/metrics.yml` otherwise is going to complain it doesn't support the old dbt metric syntax.

feat: support dbt 1.7

---

packages/frontend/src/components/common/Filters/FilterInputs/FilterStringAutoComplete.tsx

Closes: #7835
changes:
- memo dropdown component
- don't clear search after selecting one value
https://github.com/lightdash/lightdash/assets/9117144/a254d38e-f194-4a86-a411-e84d3a26e7f3

fix: filter autocomplete scroll

---

packages/backend/src/services/ValidationService/ValidationService.ts

Closes: https://github.com/lightdash/lightdash/issues/8125
custom dimension ids were not in the all available field ids

fix: custom dimension sort validation

---

packages/frontend/src/components/DashboardTiles/TileBase/index.tsx

Closes: N/A
Dashboards don't load when there's 2 tooltips (one nested) and when one is `disabled` when the other isn't.
Removing the extra tooltip that was to fix this: https://github.com/lightdash/lightdash/pull/8144#issuecomment-1831969506 
But will work on a different solution on another PR.
error for reference:

fix: remove extra tooltip on dashboard title

---

packages/cli/src/handlers/compile.ts
packages/cli/src/handlers/dbt/compile.ts
packages/cli/src/handlers/deploy.ts
packages/cli/src/index.ts

Closes: [7194](https://github.com/lightdash/lightdash/issues/7194).
This PR allows running `lightdash deploy` `lightdash validate`, `lightdash preview` and `lightdash start-preview` with the `--skip-dbt-compile` flag to perform the command without running `dbt compile` first, instead expecting an existing `./target/manifest.json` from which to build the Lightdash explores. 
This can be handy for teams running complex CI/CD workflows with dbt, to take advantage of already created artifacts.

feat: --skip-dbt-compile

---

packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx

Closes: https://github.com/lightdash/lightdash/issues/7466

fix: explore filter showing value with is null operator

---

packages/frontend/src/hooks/useBigNumberConfig.ts

Closes: #8157 
raw comparison
with percentage
with percentage inverse sort

fix: bignumber comparison negative percent values

---

packages/backend/src/scheduler/SchedulerClient.ts
packages/common/src/types/scheduler.ts

Closes: https://github.com/lightdash/lightdash/issues/7960
resolve the scheduler uuid before generating the notification job payload. 
tested locally

fix: fix broken link in email for saved schedule delivery

---

packages/backend/src/clients/Google/GoogleDriveClient.ts
packages/backend/src/services/CsvService/CsvService.mock.ts
packages/backend/src/services/CsvService/CsvService.ts
packages/backend/src/services/ProjectService/formatRows.ts
packages/common/src/index.ts
packages/common/src/types/field.ts
packages/common/src/utils/conditionalFormatting.ts
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/MetricQueryData/MetricQueryDataProvider.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/AxesOptions.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/ChartConfigTabs.tsx
packages/frontend/src/components/common/PivotTable/ValueCellMenu.tsx
packages/frontend/src/components/common/PivotTable/index.tsx
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts
packages/frontend/src/hooks/tableVisualization/getDataAndColumns.tsx
packages/frontend/src/hooks/useBigNumberConfig.ts
packages/frontend/src/hooks/useCalculateTotal.ts
packages/frontend/src/hooks/useColumnTotals.ts
packages/frontend/src/hooks/useColumns.tsx
packages/frontend/src/types/table-core.d.ts

Relates to: #8153 (first PR on cartesian config, will do more per config and remove unnecessary stuff as I progress)
Adds `ItemsMap` type
We don't use `explore` anymore in `useEchartsCartesianConfig.ts`. Instead, we use `itemsMap` which includes all we need.
THe `itemsMap` is now initialised on the `VisualizationProvider`

refactor: expose items map in cartesian visualization

---

packages/backend/src/config/parseConfig.ts
packages/backend/src/routers/headlessBrowser.ts
packages/backend/src/services/UnfurlService/UnfurlService.ts

closes: https://github.com/lightdash/lightdash/issues/6932
introduces new env variable `SCHEDULER_SCREENSHOT_TIMEOUT` to delay taking a screenshot for instances with heavy dashboards. this is a temporary workaround for https://github.com/lightdash/lightdash/issues/6932

feat: scheduled delivery screenshot timeout

---

packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
packages/frontend/src/components/Explorer/ExplorerHeader/index.tsx
packages/frontend/src/components/Explorer/index.tsx
packages/frontend/src/components/LimitButton/LimitForm.tsx
packages/frontend/src/components/LimitButton/index.tsx
packages/frontend/src/components/RefreshButton.tsx

Closes: 
Based on user feedback we moved the run query button back to the top and made the limit warning much smaller.

feat: move run query button back to the top of the page

---

packages/common/src/index.ts
packages/frontend/src/components/LightdashVisualization/VisualizationConfigPie.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/VisualizationConfigs/PieChartConfig/PieChartLayoutConfig.tsx
packages/frontend/src/hooks/echarts/useEchartsPieConfig.ts
packages/frontend/src/hooks/usePieChartConfig.ts

Relates to: https://github.com/lightdash/lightdash/issues/8153
Generate all `dimensions` and all `metrics` with `itemsMap` and utilise it where possible on Pie Charts. Now we don't do unnecessary loops for non-pie charts because that's been moved to the viz provider just for Pie charts.

refactor: use itemsMap on visualisation provider pie chart

---

packages/frontend/src/components/UserSettings/UserManagementPanel/index.tsx

Closes: #8208 
The previous invite was sticking around when the user invite modal was closed and re-opened. This clears the modal state when it is closed.

fix: clear previous invite from add user modal

---

packages/backend/src/models/SavedChartModel.mock.ts
packages/backend/src/models/SavedChartModel.test.ts
packages/backend/src/models/SavedChartModel.ts

Closes: #8227
After:
With Old version
New versions override old version

fix: chat history returns at least 1 old version

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer/ResultsCard/CellContextMenu.tsx
packages/frontend/src/components/Explorer/ResultsCard/UrlMenuItems.tsx
packages/frontend/src/components/Explorer/VisualizationCard/SeriesContextMenu.tsx
packages/frontend/src/components/MetricQueryData/CellContextMenu.tsx
packages/frontend/src/components/MetricQueryData/DrillDownMenuItem.tsx
packages/frontend/src/components/SimplePieChart/PieChartContextMenu.tsx
packages/frontend/src/components/SimpleStatistic/BigNumberContextMenu.tsx
packages/frontend/src/components/SimpleTable/CellContextMenu.tsx
packages/frontend/src/components/SimpleTable/DashboardCellContextMenu.tsx
packages/frontend/src/components/common/PivotTable/TotalCellMenu.tsx
packages/frontend/src/components/common/PivotTable/ValueCellMenu.tsx
packages/frontend/src/components/common/Table/BodyCell.tsx
packages/frontend/src/components/common/Table/ScrollableTable/index.tsx
packages/frontend/src/components/common/Table/Table.styles.ts
scripts/count-blueprint-imports.ts

migrates viz context menus to mantine (table + charts)

feat: visualization context menus to mantine

---

packages/frontend/src/hooks/useBigNumberConfig.ts

Closes: 
Before: 
Big number defaults to the first field available.
Now:
Big number defaults to metric > table calculation > dimensions.

fix: default big number field to metric

---

packages/backend/src/database/seeds/development/02_saved_queries.ts
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationConfigCartesian.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationConfigPie.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationConfigTable.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/SimpleTable/DashboardCellContextMenu.tsx
packages/frontend/src/components/SimpleTable/index.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/ChartConfigTabs.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/index.tsx
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.test.ts
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
packages/frontend/src/hooks/cartesianChartConfig/utils.ts
packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
packages/frontend/src/hooks/usePieChartConfig.ts
packages/frontend/src/hooks/useSqlQueryVisualization.ts
packages/frontend/src/pages/MetricFlow.tsx
packages/frontend/src/pages/MinimalSavedExplorer.tsx
packages/frontend/src/pages/SqlRunner.tsx

Closes: #8153
Main changes:
- remove explore from VisualizationProvider props
- remove explore, metrics, custom metrics, table calculation, explore name from the VisualizationProvider context
- refactor some stuff that was missed in the previous PRs
- in some cases we just need to remove the explore code
- in some cases we need to replace the explore with itemsMap
Tested: explore, saved chart, SQL runner, minimal dashboard, minimal chart

refactor: remove explore from visualization provider

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/compiler/exploreCompiler.ts

Closes: 
When overriding a dimension with a selected granularity, also try to get its base dimension's `type`. If that's `date` then set it as date. If not, then `timestamp`. 
This ensures that users don't see these `unformatted` x axis labels:
To reproduce (with jaffle shop) 
* create a chart with dimension : customers created date week + metric unique customer count
Date zoom to `Month`
in `/charts-and-results` `fields` property, the value `type` of the dimension (with the different SQL) should be: `date` and not `timestamp` - this was happening because we were getting the `type` from the `baseTimeDimension`, which was `timestamp`

fix: get base dimension type when date zooming

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/hooks/useExplorerRoute.ts

Closes: #8257 
Remove `dateZoom` from `explore from here` URL, meaning that users won't see the date zoom value applied when `explore from here` from a dashboard tile

fix: remove granularity from explore from here

---

packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
packages/frontend/src/components/DashboardFilter/FilterConfiguration/utils/index.ts
packages/frontend/src/features/scheduler/components/SchedulerFilters.tsx
packages/frontend/src/providers/DashboardProvider.tsx

Closes: #8267
To reproduce: 
1. Add **saved filter**, type string for example: payment method is bank transfer
2. On scheduler
3. Override payment method filter, but first: remove `bank transfer`, and then add `card` -> the `disabled: true` attribute was added when removing the initial value, and then wouldn't be inverted when readding values. 
This PR now checks if that should be actually `disabled`. 
Also, renames some utils to make them more generic so it's easier to share across different parts of the app 👍

fix: recheck if scheduler filter should be disabled

---

packages/frontend/src/components/UserSettings/DeleteOrganizationPanel/DeleteOrganizationPanel.styles.ts
packages/frontend/src/pages/Settings.tsx

Closes: N/A
Small `Description` SC component
Before
After

chore: remove description styled component

---

packages/e2e/cypress/e2e/app/downloadCsv.cy.ts
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/DashboardTiles/EditChartMenuItem.tsx
packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
packages/frontend/src/components/common/LinkMenuItem.tsx
packages/frontend/src/features/export/components/ExportToGoogleSheet.tsx

migrates tile menus to mantine

feat: tile menus (mantine migrations part 2)

---

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/components/common/ResourceView/ResourceActionHandlers.tsx
packages/frontend/src/components/common/modal/ChartDeleteModal.tsx

Relates to: https://github.com/lightdash/lightdash/issues/8301
Before
After

chore: mantine-fy chart delete modal

---

packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/components/common/ResourceView/ResourceActionHandlers.tsx
packages/frontend/src/components/common/modal/DashboardUpdateModal.tsx

Relates to: #8301 
dashboard update modal
before
after

chore: mantine-fy dashboard update modal

---

packages/cli/src/dbt/targets/Bigquery/index.ts
packages/frontend/src/components/ProjectConnection/WarehouseForms/BigQueryForm.tsx

Closes: #8306 
We were setting location to the empty string when it wasn't set in the big query form. This keeps it as undefined, which I believe is the desired behavior, but I'm not sure how to make sure this works for the customer case.

fix: empty location in BigQuery causes an error

---

packages/frontend/src/components/common/Table/ScrollableTable/TableHeader.tsx
packages/frontend/src/hooks/useColumns.tsx

restore https://github.com/lightdash/lightdash/pull/8258
this disappeared somehow either from a revert or a bad merge

feat: mantine tooltips in table headers

---

docs/docs/references/dimensions.mdx
docs/docs/references/user-attributes.mdx

Adds `required_attributes` to the user attributes doc (before it was only in the `dimensions` reference doc, which made it hard to find when users were reading about user attributes from the `user attributes` page).

docs: adds required attributes to user attributes doc

---

packages/frontend/src/components/UserCompletionModal/index.tsx

Closes: #8334 
Only send `organizationName` if it didn't exist in the first place. 
User has to set it if there's no org set up

fix: only send org name if it didn't exist

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer/index.tsx
packages/frontend/src/components/MetricQueryData/MetricQueryDataProvider.tsx

Closes: 
In the dashboard page, use explore from chart results for the MetricQueryDataProvider.

refactor: dont request explore in dashboard page

---

packages/frontend/src/components/DashboardTiles/AddTileButton.tsx
packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
packages/frontend/src/components/DashboardTiles/TileForms/MarkdownTileForm.tsx
packages/frontend/src/components/DashboardTiles/TileForms/TileAddModal.tsx
packages/frontend/src/components/DashboardTiles/TileForms/TileUpdateModal.tsx

Closes: #8301 
More modals...
On dashboard tiles:
* create
* update
https://github.com/lightdash/lightdash/assets/7611706/cd7e3974-a1b0-456d-9b13-97bc47f00f05
**note**
we had references to `chart` modal form `TileUpdateModal.tsx` and `TileAddModal.tsx` but it would never be reached (because we were rendering separately the markdown+loom vs charts)

chore: mantine-fy tile-related modals

---

packages/frontend/src/hooks/dashboard/useDashboards.tsx

Closes: #8318 
Added missing query param to "getDashboardsContainingChart" endpoint.  
How to replicate the issue fixed in this PR:
1. User **X** (e.g: developer) from the organization creates a Private Space **Y**
2. User **X** creates a new dashboard **W** in Private Space **Y**
3. Admin user **Z** from organization adds a chart from a public space into dashboard **W**

fix: added missing param to 'getDashboardsContainingChart' endpoint

---

packages/frontend/src/components/DashboardTiles/TileBase/index.tsx

fix: dashboard tile menu zindex

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/SavedChartModel.ts
packages/backend/src/services/DashboardService/DashboardService.mock.ts
packages/backend/src/services/ValidationService/ValidationService.mock.ts
packages/common/src/types/savedCharts.ts
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationConfigPie.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLine.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/SingleSeriesConfiguration.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/index.tsx
packages/frontend/src/components/VisualizationConfigs/ColorSelector.tsx
packages/frontend/src/components/VisualizationConfigs/PieChartConfig/PieChartSeriesConfig.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormatting.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingList.tsx
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts
packages/frontend/src/hooks/usePieChartConfig.ts
packages/frontend/src/pages/MetricFlow.tsx
packages/frontend/src/pages/MinimalSavedExplorer.tsx
packages/frontend/src/pages/SqlRunner.tsx

Closes: 
Stop requesting the organization color palette inside visualization components. This data is now available in the visualization provider.
We now return the color palette when fetching a chart.
There are 3 places where still need to fetch the org since we don't have a saved chart:
- dbt semantic layer (aka metricflow)
- SQL runner
- explore page
Affected features:
- cartesian charts - series colors + reference lines
- pie chart - series colors
- table chart - conditional formatting

refactor: return color palette with chart

---

packages/frontend/src/features/dateZoom/components/DateZoom.tsx

Closes: #8343 
Date zoom dropdown was staying open when interacting with other things. This makes the drowdown state uncontrolled and just changes the icon when the menu is open.

fix: close datezoom dropdown on click outside

---

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx

Remove blueprint from saved charts header. The main thing that changes is this popup:
OLD:
NEW:

chore: remove blueprint from SavedChartsHeader

---

packages/frontend/src/components/NavBar/ProjectSwitcher.tsx

Fix text showing up instead of icon
Before:
After:

chore: fix 'tick' text as icon

---

packages/frontend/src/components/common/Filters/FilterInputs/FilterStringAutoComplete.tsx

Closes: N/A
To reproduce: 
* click on saved filter which is a `FilterStringAutoComplete`
* click on dropdown
* click outside to close dropdown
* click outside again to close main popover 
tldr; `onDropdownClose` and `onDropdownOpen` were being passed but then overridden 
https://github.com/lightdash/lightdash/assets/7611706/e3a873ca-137e-4553-a324-130be8508ef5

fix: call subpopover handlers on close of autocomplete

---

packages/frontend/src/components/ReactHookForm/FromGroup.styles.ts
packages/frontend/src/components/ReactHookForm/Input.tsx
packages/frontend/src/components/ReactHookForm/InputWrapper.tsx
packages/frontend/src/components/ReactHookForm/MultiKeyValuePairsInput.tsx
packages/frontend/src/components/ReactHookForm/PasswordInput.tsx

Remove blueprint from ReactHookForm directory. This one is a bit confusing. The good news is there components are barely used. The bad news is you can't really test the DBT Cloud form. But it's deprecated and I did test it.

chore: remove blueprint from react hook form directory

---

packages/backend/src/controllers/schedulerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/SchedulerService/SchedulerService.ts
packages/common/src/index.ts
packages/common/src/types/scheduler.ts
packages/frontend/src/features/scheduler/components/SchedulerForm.tsx
packages/frontend/src/features/scheduler/components/SchedulerModalContent.tsx
packages/frontend/src/features/scheduler/components/SchedulerModalFooter.tsx
packages/frontend/src/features/scheduler/hooks/useScheduler.ts

Closes: #8358 
Disable `Send now` if no targets (email or slack)
Add Loading Overlay if processing `Send Now`
Display notifications when:
* Job Started
* When Scheduled delivery is being processed
* Send success and error notifications for each job status (`COMPLETED` `ERROR`)
Improve types and API responses
https://github.com/lightdash/lightdash/assets/7611706/f1e23db9-c503-4ed6-9f9e-51399af9e625

fix: add polling to send now messaging

---

packages/frontend/src/components/common/modal/ChartUpdateModal.tsx

Closes: #8385
Fix `descrition` typo so the form text input for `chart description` can get populated on load if that data exists

fix: add correct string for chart update modal

---

packages/frontend/src/components/common/ShareShortLinkButton/index.tsx

Closes: #8353 
Quick style fix. The icon button is still a little different from the others because of a mantine default, but it's better. 
Old:
New:

fix: disabled style on explores link button

---

packages/frontend/src/components/RenderedSql.tsx

Closes: #8289 
Luckily, Mantine has an inbuilt prop `withLineNumbers` that displays the line numbers in a `Prism`.
Before:
After:

feat: add line numbers to sql panel

---

packages/common/src/compiler/filtersCompiler.ts

Closes: #8285
This issue was only affecting table calculation filters with a `number` format . 
Before:
After:

fix: table calculation filter number

---

packages/frontend/src/components/common/ThirdPartySignInButton/index.tsx

Azure AD is mostly an internal name and the product has also been renamed. "Sign in with Microsoft" is more recognisable to end users

feat: change copy on sign-in-with-microsoft button

---

dockerfile

Closes: 
curl@7.74.0-1.3 -> 7.88
https://www.cve.org/CVERecord?id=CVE-2023-23914
zlib has not released any version to fix this issue https://github.com/madler/zlib/issues/868

fix: upgrade package libcurl4 to fix CVE-2023-23914

---

packages/frontend/src/components/DashboardTiles/TileBase/TileBase.styles.tsx

Closes: #8383 
Just had to change the flex styles for the `HeaderContainer` that wrapped the icons.
1) Align items: center fixes the vertical alignment
Before:
After:
2) Justify content: space-between makes sure the icons are on two ends of the tile.
Final Result (with missing title):

fix: alignment fix for date zoom icon

---

packages/backend/package.json
packages/backend/src/clients/Slack/Slackbot.ts
packages/backend/src/routers/dashboardRouter.ts
packages/backend/src/scheduler/SchedulerTask.ts
packages/backend/src/services/UnfurlService/UnfurlService.ts
packages/frontend/src/components/common/modal/DashboardExportModal.tsx
packages/frontend/src/hooks/dashboard/useDashboard.tsx
packages/frontend/src/pages/Dashboard.tsx
yarn.lock

Consequence of investigation: #8276 
Feature: 
* Allow dashboard `export now` - default behaviour
* Provide customisation section. Users can: change the width + preview what their dashboard would look like
**Demo (most recent):**
https://github.com/lightdash/lightdash/assets/7611706/8cf98155-f5b1-4ae9-8dd1-52fb612ae725
**Demo (outdated):**
https://github.com/lightdash/lightdash/assets/7611706/b1470203-2d27-4511-9e53-478603281009
Added a loading spinner to the notification for `exporting in progress` 
Notes:
* upgrade `puppeteer`
* convert some long-args-methods to one single object
* use `page.screenshot` instead - worked great on `dashboards` and `charts` exports

feat: customise width and preview dashboard exports

---

packages/frontend/src/components/UserSettings/UserManagementPanel/index.tsx
packages/frontend/src/hooks/useOrganizationUsers.ts

Closes: #8413 
Can search now by: 
* first name
* last name
* email
* role
with fuse.js (same way we do for explores)
Ideally we want the `users` query to accept a query param but this works as a v1 for now (we would like as well to support pagination which can be done on a separate ticket)
Demo:
https://github.com/lightdash/lightdash/assets/7611706/4fc2c5dd-0ef7-4fe5-801c-3400382429f1

feat: add search to user management table

---

packages/frontend/src/components/UserSettings/InvitesModal/index.tsx

Closes: #8195
The issue seemed to be because of the flex-end here.
https://github.com/lightdash/lightdash/blob/78633f90cf541f84b81480c65913f2eff328295d/packages/frontend/src/components/UserSettings/InvitesModal/index.tsx#L76
When we have an email error message, it increases the height of `TextInput`. Subsequently, the height of the Group also increases and it aligns itself to the end of it vertically. So a conditional bottom padding to the Group fixes this.
_Note: This may cause an extra padding at the bottom if we don't have all the inputs in the same line (but this shouldn't happen ideally)._ 
We don't need this fix in the `ProjectAccess` section as we are using a `Select` for the email there.
Before:
After:
Without Error -
With Error -

fix: sort alignment on email error message

---

packages/frontend/src/components/UserSettings/UserManagementPanel/index.tsx
packages/frontend/src/hooks/useOrganizationGroups.ts
packages/frontend/src/pages/Settings.tsx

Closes: #8418 
Add a group management tab to the users page. Behind a feature flag. For now it only lists groups. CRUD to come. 
Here's what it looks like with the flag ON:
And with the flag OFF (groups disabled)

chore: group management page

---

packages/frontend/src/hooks/health/useHealth.tsx

Health endpoint errors were showing with the wrong text color. This fixes the color. 
Before (BUG)
After (fixed)

fix: styles for errors on health endpoint

---

packages/frontend/src/pages/Settings.tsx

Closes: N/A
Only admins should be able to view `/userManagement` in settings. 
Currently, non-admins (or < admin role) can view the page. They shouldn't be able to.

fix: user management permission issue

---

packages/backend/src/controllers/organizationController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/models/GroupsModel.ts
packages/backend/src/services/OrganizationService/OrganizationService.ts
packages/common/src/types/groups.ts

Closes: 
for UI purposes to display user avatars https://mantine.dev/core/avatar/#avatargroup
this does not include pagination as it does not make sense with multiple groups.

feat: organization groups with members api

---

packages/backend/src/generated/routes.ts
packages/backend/src/services/OrganizationService/OrganizationService.ts
packages/common/src/types/groups.ts

Closes: 
use from the frontend:
```ts
const { mutateAsync, isLoading } = useGroupCreateMutation();
const handleSubmit = async (data: CreateGroup) => {
await mutateAsync({
...data,
// optional members property
members: [
{ userUuid: 'b264d83a-9000-426a-85ec-3f9c20f368ce' },
{ userUuid: '57cd4548-cbe3-42b3-aa13-97821713e307' },
{ userUuid: '4d242922-a402-427b-bd6d-74f9bddf90cd' },
],
});
}
```

feat: organization group creation with members

---

packages/backend/src/database/entities/scheduler.ts
packages/backend/src/database/migrations/20231229105147_add-custom-viewport-width-to-scheduler-table.ts
packages/backend/src/models/SchedulerModel/index.ts
packages/backend/src/scheduler/SchedulerTask.ts
packages/common/src/types/scheduler.ts
packages/frontend/src/components/common/modal/DashboardExportModal.tsx
packages/frontend/src/features/preview/components/PreviewAndCustomizeScreenshot.tsx
packages/frontend/src/features/preview/index.ts
packages/frontend/src/features/scheduler/components/SchedulerForm.tsx
packages/frontend/src/features/scheduler/components/SchedulerPreview.tsx
packages/frontend/src/features/scheduler/constants/index.ts

Relates to: #8276
Add `<SchedulerPreview />` component
Add new column to `scheduler` DB table: `custom_viewport_width`
Allow users to preview their scheduled deliveries for dashboard in image format in 3 sizes
Allow users to set their selection (if `Medium`, then that's the default value) -> Subsequent deliveries will respect the width selection
Create shared component `PreviewAndCustomizeScreenshot` that is shared by the Dashboard Export feature and the Scheduler Preview feature
> [!NOTE]
> This doesn't work yet with `Send Now` feature. 
Demo: 
https://github.com/lightdash/lightdash/assets/7611706/e0aa440b-14aa-4462-b762-e473964d4848
Scheduled delivery with Large setting: 
Scheduled delivery with Small setting (see the 2nd markdown tile from above ^ being moved randomly to another row …

feat: add preview choice to dashboard scheduled deliveries

---

packages/frontend/src/components/DashboardFilter/Filter.tsx

Closes: [Dashboard filter tooltip shows plural tables for a single table](https://github.com/lightdash/lightdash/issues/8448)
Fixes the issue where a dashboard filter for a single table shows the plural `Tables` in the tooltip. Also fixes the possibility of a tooltip showing if `filterRuleTables` is undefined or empty.
_Before:_
_After:_
_Notes:_
I have simplified the ternary for readability, since `filterRuleTables?.join(', ')` produces the same result as `filterRuleTables[0]` for an array of strings with a single item.

fix: formatting of tooltip on dashboard filter

---

packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/CreateGroupModal.tsx
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/GroupsView.tsx
packages/frontend/src/hooks/useOrganizationGroups.ts

Closes: #8442 
Adds a user select when creating a group so users can be added in the UI. Also shows the group members in the group list. This enables the functionality, but there more style work to be done. For now the users are listed in a scrolling box, but we probably want to change that. 
Create group with users:
Group list including users:

chore: groups can be created with users

---

packages/backend/package.json
packages/backend/src/models/ProjectModel/ProjectModel.mock.ts
packages/backend/src/models/ProjectModel/ProjectModel.test.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts

Closes: #8066 
In this PR I'm avoiding this error by discarding/ignoring models with duplicate names. It will only use the first model for each name.
This fix is focused on not throwing an error to unblock users that deploy their project via the UI which deploys all their models. We can open a new ticket to support multiple models with the same name but that hasn't been requested by users.

fix: discard explores with duplicate name

---

packages/backend/src/database/seeds/development/03_saved_dashboards.ts

Tests are failing because there is a dashboard filter that filters out data before 2019. This changes the filter to look back 10 years instead of 5. 
test-frontend
test-cli
test-backend

chore: change seeded filter timerange

---

packages/backend/src/controllers/organizationController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/OrganizationMemberProfileModel.ts
packages/backend/src/services/OrganizationService/OrganizationService.ts
packages/common/src/types/organizationMemberProfile.ts

Closes: N/A
Allows `includeGroups` in query for `/org/users`;
Gets users and the groups they belong to;
> [!NOTE]
> Should we do extra checks on permissions?
Example

feat: add option to query members and their groups

---

docs/docs/guides/how-to-embed-content.mdx
docs/docs/references/joins.md
docs/sidebars.js

Closes: https://github.com/lightdash/lightdash/issues/8118
Adds docs for how to manage hidden joined tables using tags so that they are still compiled, but don't appear in the sidebar. 
Also adds embedding docs to the sidebar

docs: adds hidden joins table management instructions

---

packages/backend/src/queryBuilder.ts
packages/backend/src/services/UserAttributesService/UserAttributeUtils.ts
packages/common/src/types/dbt.ts
packages/common/src/types/field.ts
packages/common/src/types/search.ts

Closes: #8464 
Updated `required_attributes` types to `Record<string, string | string[]>` to support string arrays and corresponding code that searches for the required_attributes.
Example:
```
name: first_name
description: Customer's first name
meta:
dimension:
...
required_attributes:
group: ["a","b"]
```
Group attribute settings - 
User 1 with group a -
User 2 with group b -
User 3 with group c -
User 4 without group attribute -
I had tested the existing string only required_attributes after the change and it worked fine as well.

feat: multiple values in required attributes

---

dockerfile

fix: update libcurl3-gnutls on bullseye-backports dependency

---

packages/backend/src/services/UnfurlService/UnfurlService.ts

Closes: N/A
Some dashboard screenshots are being cropped because we were targeting the page.screenshot when we should continue targetting the `element`. 
PR that introduced this change was: https://github.com/lightdash/lightdash/pull/8389/files#diff-9b86624a0467c9253f755c66928390e96818008cdd1df400c3509984ce4d1071L473-L475

fix: get screenshot from element instead

---

packages/frontend/src/features/scheduler/constants/index.ts

Relates to: #8276
Adds another option for Dashboard exports and Dashboard Scheduled delivery `Preview and customization`
From render:

feat: extra large option to export and scheduler

---

packages/e2e/cypress/e2e/app/userAttributes.cy.ts
packages/frontend/src/components/UserSettings/UserAttributesPanel/UserAttributeModal.tsx
packages/frontend/src/components/UserSettings/UserAttributesPanel/index.tsx
packages/frontend/src/hooks/useOrganizationGroups.ts
packages/frontend/src/pages/Settings.tsx

Relates to: #5444 
Add placeholder UI to then assign user attributes to Groups
Update copy for Settings tab label
Fix copy for user attributes: missing link, typos, etc
Change buttons to `edit` and `delete` user attributes by replacing them with `ActionIcon`s. 
Small style changes
Demo (will be complete once BE work is done)
https://github.com/lightdash/lightdash/assets/7611706/665bc1eb-9ca6-4e14-a8f2-a1e75cd1d445
Demo with the feature flag turned off
https://github.com/lightdash/lightdash/assets/7611706/c53c8926-bb30-4ac3-8bbc-db171e8f252e

feat: add placeholder UI to add user attributes to groups

---

packages/frontend/src/components/UserCompletionModal/index.tsx

Closes: [On the first onboarding screen, the 'Organization Name' input disappears when I try to fill it out](https://github.com/lightdash/lightdash/issues/8450)
Fixed the issue where the Organisation input disappears. It also fixes an unreported issue where the checkbox to allow users with a valid domain disappears in the same circumstances.
_BEFORE:_
_AFTER:_
_NOTES:_
I believe the intention was to check the existence of an existing organisation name and use it to show/hide these form elements. But the check was accidentally made against the form state.  Updated to check against the value loaded from the context instead.

fix: Remedy for disappearing Organisation input issue 8450

---

packages/frontend/src/hooks/useOrganizationUsers.ts

Small thing I noticed while doing group work. This query key wasn't right. I dont think it's causing any noticeable problems, but we might as well add this.

fix: incorrect query key in useOrganizationUsers

---

packages/frontend/src/components/UserSettings/SocialLoginsPanel/index.tsx
packages/frontend/src/components/common/ThirdPartySignInButton/index.tsx
packages/frontend/src/pages/Invite.tsx
packages/frontend/src/pages/Login.tsx
packages/frontend/src/pages/Register.tsx

Closes: 
Quick fix with duplication. We need to extract the authentication form to a separate component since is duplicated across all these pages.
Before: we show a toast each time the sso button rerenders
After: renders once

fix: show SSO authentication error once

---

packages/common/src/utils/timeFrames.ts

Closes: #8447 
The extra spacing was just due to how TO_CHAR works in postgres.
We can use the FM option to suppress these.
Documentation link - https://www.postgresql.org/docs/9.2/functions-formatting.html#FUNCTIONS-FORMATTING-NUMERICMOD-TABLE
After updating the code, query becomes - 
Output -
Run e2e tests:
test-frontend

fix: spaces in date part names

---

packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
packages/frontend/src/components/DashboardFilter/InvalidFilter.tsx
packages/frontend/src/features/scheduler/components/SchedulerFilters.tsx

Closes: #8488 
Fixes 2 issues when there are invalid dashboard filters:
- updating & removing valid filters would affect a different filter
- creating & updating scheduled deliveries would crash page
View mode
View mode + tooltip
Edit mode
Schedule delivery filter

fix: show invalid dashboard filters

---

packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/GroupsView.tsx
packages/frontend/src/hooks/useOrganizationGroups.ts

Some group fetches include members, and some don't. We weren't using the member count as part of the query key, so it wasn't being refetched. That caused an error. This fixes that by including member count in the query key.

fix: error when using groups with members

---

packages/frontend/src/components/DashboardTiles/TileBase/index.tsx

Related to PR #8407 
Refer to comments in above mentioned PR.
For Charts created within dashboard, added an `edit tile content` button disabled with a tooltip explaining that `charts from dashboards aren't editable`
Example Output: Chart created within dashboard
On Hover:

feat: add disabled edit tile content option

---

packages/backend/src/@types/knex-tables.d.ts
packages/backend/src/database/entities/userAttributes.ts
packages/backend/src/database/migrations/20240108152115_group_attributes.ts

Add table mapping groups to user attributes. 
Note that the groups table references the same user attributes table, `user_attributes` as the user attributes.
We could potentially clean up some of the names here.

chore: add table for group attribute mappings

---

packages/backend/src/generated/swagger.json
packages/common/src/types/groups.ts
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/CreateGroupModal.tsx
packages/frontend/src/hooks/useOrganizationGroups.ts

Fix a validation error when updating groups. The types got out of sync with the generated API. This removes the uuid from the update payload and regenerates the endpoints.

fix: update groups validation error

---

packages/backend/src/models/UserAttributesModel.mock.ts
packages/backend/src/models/UserAttributesModel.test.ts
packages/backend/src/models/UserAttributesModel.ts
packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts
packages/backend/src/services/UserAttributesService/UserAttributeUtil.test.ts
packages/backend/src/services/UserAttributesService/UserAttributeUtils.ts
packages/common/src/types/userAttributes.ts

Closes: #8500 
This PR does not improve query performance for user attributes. To be done in separate PR.
Needs to be tested locally since we can't edit group attributes in the UI( needs to be changed directly in DB ).
Row filtering eg
```
models:
- name: events
meta:
sql_filter: ${TABLE}.event = ${lightdash.attributes.event}
```
Column filtering eg
```
- name: event
meta:
dimension:
required_attributes:
is_admin: "true"
```

feat: filter rows and columns based on group attributes

---

packages/backend/package.json
packages/backend/src/@types/express-session.d.ts
packages/backend/src/controllers/authentication.ts
packages/backend/src/index.ts
packages/backend/src/models/GroupsModel.ts
packages/backend/src/routers/apiV1Router.ts
packages/backend/src/services/UserService.ts
packages/backend/src/services/services.ts
packages/common/src/types/user.ts
yarn.lock

Closes: #8498
Change Okta Sign up/in flow by using `node-openid-client`: https://github.com/panva/node-openid-client, so that we can get `groups` when requesting `user info`. 
With the previous implementation (using `passport-openidconnect`), the package wouldn't send back `groups` even if they were available: https://github.com/jaredhanson/passport-openidconnect/blob/master/lib/profile.js and relevant issue here: https://github.com/jaredhanson/passport-openidconnect/issues/100
Now, we get the `groups`, create the openId user, and then we add the user to the groups where the Okta group `name` === the `name` of the group in Lightdash. 
Most code on the `OpenIDClientOktaStrategy.authenticate` (which is only used for Okta atm), comes from the readme here: …

feat: update groups when users sign up and in (okta)

---

packages/e2e/cypress/e2e/app/settings/invites.cy.ts

The invites tests fail when re-run because too many users get added to the list and the one being searched is out of view. This scrolls it into view, which should help.

test: fix invite test when there are many users

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/DashboardTiles/EditChartMenuItem.tsx
packages/frontend/src/components/DashboardTiles/TileBase/index.tsx

Closes: #8518
While the chart is loading, we show:
* title (if exists) -user can click on title to view chart
* 3-dot menu `Edit chart` option to edit the chart without having to wait for the `/chart-and-results` endpoint to settle
More info on the ticket ^
Admin experience
https://github.com/lightdash/lightdash/assets/7611706/8ff1321f-c5d3-4d92-8b73-d4d7414fe531
Member experience
https://github.com/lightdash/lightdash/assets/7611706/e2dd1027-834f-4bc9-842b-081082bf8d48

feat: allow chart edit when loading in dashboard

---

packages/frontend/src/components/UserSettings/UserAttributesPanel/UserAttributeModal.tsx

Improve attribute dialog:
- Sticky footer so buttons don't scroll away
- Header underline
- Higher on the page with more space by default (matches other large dialogs)
Before:
After:

feat: improve attributes dialog UI

---

packages/common/src/types/organizationMemberProfile.ts
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/UsersView.tsx
packages/frontend/src/hooks/useOrganizationUsers.ts

Closes: #8535 
Shows basic group info in the users list. The number of groups is in the list and the groups are shown on hover.

feat: show group info in users list

---

examples/full-jaffle-shop-demo/dbt/models/generated_a.yml
packages/backend/src/services/ProjectService/ProjectService.ts

Adding OTEL events so we can track how slow it is to filter explore dimensions.
I haven't seen a big impact when filtering dimensions.
Tests requesting an explore with 20 joins and 1000 dimensions (from top to bottom):
- explore with column filter and user attribute
- explore with column filter and no user attribute
- explore without column filter
Traces when filtering

chore: add otel events to explore filtering

---

packages/frontend/src/hooks/useOrganizationGroups.ts

Refetch users when groups change. Without this the user's list gets out of date when groups are changed.

fix: update users when groups change

---

packages/frontend/src/features/projectGroupAccess/components/AddProjectGroupAccessModal.tsx
packages/frontend/src/features/projectGroupAccess/components/EditProjectGroupAccessModal.tsx
packages/frontend/src/features/projectGroupAccess/components/ProjectGroupAccess.tsx
packages/frontend/src/features/projectGroupAccess/components/ProjectGroupAccessItem.tsx

fix: project group access list does not exclude already assigned groups

---

packages/backend/src/services/UnfurlService/UnfurlService.ts

Closes: N/A
Related to Dashboard Screenshots / Scheduled deliveries logging. 
When we introduced the `/chart-and-results`, we didn't update the regex that is used to match and then log warnings/errors to grafana.

fix: get correct regex for chart-and-results endpoint

---

packages/backend/src/controllers/authentication.ts

Closes: N/A
Related to: #8498 
users were getting: 
```
{"status":"error","error":{"statusCode":500,"name":"UnexpectedServerError","message":"OPError: expected 200 OK, got: 401 Unauthorized","data":{}}}
```
when signing in with okta because it the `authorizationUrl` had `/default` by default. Some Okta apps might not have that Authorization Id (even though it's added by default and can be later disabled - ref: https://developer.okta.com/docs/concepts/auth-servers/#default-custom-authorization-server).
This ensures we append that only when it's available from the configuration. 
Also, remove unused `generateOktaUrl` function - not needed anymore because the package generates the other URLs for us.

fix: only append authorizationServerId if exists

---

packages/common/src/index.ts
packages/common/src/utils/email.ts
packages/e2e/cypress/e2e/app/login.cy.ts
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/InvitesModal.tsx
packages/frontend/src/pages/Login.tsx
packages/frontend/src/pages/PasswordRecoveryForm.tsx

Closes: #8198 
- Updated `getEmailSchema` and `validateEmail` to check for whitespaces in emails.
- Utilised zodResolver to validate emails.
- Updated login e2e tests to check for whitespaces
- Project Access contain a Select for user email so it shouldn't be an issue here.
- The Profile section handles this automatically by built-in validation. If needed, we can add the logic for text in showToastError.
Some Examples:
Login:
Signup:
Invite User:

fix: validate email inputs to not allow whitespaces

---

packages/backend/src/queryBuilder.mock.ts
packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts

Closes: #8274 
Use ctes for table calculation filters instead of nested select statements.
Added mock and tests for the same.
Before:
```
WITH metrics AS (
SELECT
DATE_TRUNC('WEEK', "orders".order_date) AS "orders_order_date_week",
"orders".status AS "orders_status",
(SUM("orders".amount))-(SUM(CASE WHEN (("orders".is_completed) = true) THEN ("orders".amount) ELSE NULL END)) AS "orders_total_non_completed_order_amount",
SUM("orders".amount) AS "orders_total_order_amount",
AVG("orders".amount) AS "orders_average_order_size"
FROM "postgres"."jaffle"."orders" AS "orders"
WHERE ((
("orders".customer_id) < (11)
))
GROUP BY 1,2
)
SELECT * FROM (SELECT
*,
"orders_total_order_amount" / 
LAG("orders_total_order_amount") OVER(
ORDER BY 
"orders_order_date_week",
"orders_status"
) AS "test"
FROM …
```

feat: CTE for table calculation filters instead of nested select

---

packages/common/src/compiler/exploreCompiler.mock.ts
packages/common/src/compiler/exploreCompiler.test.ts
packages/common/src/compiler/exploreCompiler.ts

Closes: #8305 
The table alias was not considered when `requiredDimensionsForJoin` were calculated.
Changed `join.table` to  `joinTableName`.
Added tests for the same.
Example Schema:
```
name: customers
meta:
joins:
- join: membership
alias: membership_alias
sql_on: ${customers.customer_id } = ${membership_alias.customer_id}
fields: [plan_id]
```
Before:
After:

fix: omitting field in joins in tables with alias

---

examples/full-jaffle-shop-demo/dbt/models/lightdash_exposures.yml
packages/backend/src/controllers/projectController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/DashboardModel/DashboardModel.ts
packages/backend/src/models/SavedChartModel.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/services.ts
packages/cli/src/analytics/analytics.ts
packages/cli/src/handlers/generateExposures.ts
packages/cli/src/index.ts
packages/common/src/index.ts
packages/common/src/types/dbt.ts

Closes: #4062 
Add experimental command to generate exposures.
**Note 1:** At the moment, it generates a yml file in `models/lightdash_exposures.yml` and replaces the existing file.
**Note 2:** only the active project and its dashboard and charts are generated.
**Note 3:** the owner is the last user whom updated the chart.
**Note 4:** charts depend on all possible joined tables
Command:
```lightdash generate-exposures```
Dbt docs
Lineage

feat(cli): command to generate exposures

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/features/export/components/ExportToGoogleSheet.tsx

Closes: #8576
`closeMenuOnClick` set to `false` so the request doesn't get canceled

fix: keep menu open while exporting google sheets

---

packages/frontend/src/components/common/Filters/FilterInputs/FilterDateTimeRangePicker.tsx

Closes: #8511 
Changed **day** to **second** in `maxDate` and `minDate` in `FilterDateTimeRangePicker` to allow same day range filter.
I have also added the logic to prevent the user from selecting an invalid date.
_There is an alternative to handling this. We can also allow the user to select any date and as per the selection, can modify the other date._
_For example - If a user selects a Start Date that is after the End Date, we can change the End Date to (Start Date + 1 hour) and vice versa._
Here is the output:
We can also add a red error state on the input if the time range is invalid.

fix: filter between two times in the same day

---

packages/cli/src/handlers/generateExposures.ts
packages/cli/src/index.ts

Closes: NA
If I should open an issue for the pull request ahead, please let me know.
It would be useful to provide an option to determine the output path of the exposures YAML file.
We assume if we deploy multiple Lightdash projects from a dbt project by switching dbt selectors. We might want to separate the exposures YAML files corresponding to Lightdash projects respectively. 
I don't completely understand the behavior of the CLI command. But, here is what I'm thinking. 
```
lightdash deploy --selector project1
LIGHTDASH_PROJECT="xxxx-for-project1" lightdash generate-exposures --output ./models/exposures/project1.yml 
lightdash deploy --selector project2
LIGHTDASH_PROJECT="xxxx-for-project2" lightdash generate-exposures --output ./models/exposures/project2.yml
```

feat: parameterize the output path of `generate-exposures`

---

packages/frontend/src/components/VisualizationConfigs/BigNumberConfig/BigNumberConfigTabs.tsx
packages/frontend/src/hooks/useBigNumberConfig.ts

Closes: #8065 
Added separate style for comparisons in big value charts.
Output -
Layout Tab -
Comparison Tab -
Example with different formats for big number and comparison -

feat: format comparison differently in big value charts

---

packages/common/src/utils/item.ts

Closes:  #8269
Fix date zoom on timestamps 
Tips PR does not add new zoom types
[Screencast from 16-01-24 11:16:18.webm](https://github.com/lightdash/lightdash/assets/1983672/533e9254-81f1-4c3f-b358-3a2d01f9af63)
This common date function was also used on reference lines, which I tested
This common method was used to return `hasADateDimension` on metadata, so the frontend knows which charts need to reload on date zoom changes

fix: date zoom timestamp

---

packages/backend/src/models/DashboardModel/DashboardModel.ts
packages/backend/src/services/ProjectService/ProjectService.ts

Closes: #8604 
Changes:
- Amend SQL to ignore any possible null values and handle when dashboard doesn't have any charts
- Amend SQL to only return one row per dashboard instead of 1 row per dashboard version

fix(cli): generate exposures for dashboards

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/GroupsModel.ts
packages/common/src/types/groups.ts

related to: https://github.com/lightdash/lightdash/issues/8545
this is for two reasons:
- for UI to count total users in a group
- show inherited user role from groups in the UI
> why do we have `includeMembers=5`?
to display avatar groups like this: https://mantine.dev/core/avatar/#avatargroup

feat: group api with member uuids

---

packages/cli/src/analytics/analytics.ts
packages/cli/src/handlers/compile.ts
packages/cli/src/handlers/dbt/refresh.ts
packages/cli/src/handlers/deploy.ts
packages/cli/src/handlers/generate.ts
packages/cli/src/handlers/generateExposures.ts
packages/cli/src/handlers/preview.ts

Closes: 
Add a `executionId` to most CLI events so they can be related. 
This will help us find how long a command execution took. eg: 'compile.started' -> 'compile.completed' or 'compile.error'
Changes:
- add `executionId` to most events
- generate uuid at the beginning of command handlers and pass down to other functions if needed
- refactor `preview.completed` to be recorded when the preview is ready instead when the preview is stopped/deleted
- add `preview.stopped` event to know when a preview is stopped/deleted

chore(cli): add execution ID to command events

---

packages/frontend/src/components/UserSettings/UserAttributesPanel/index.tsx

A small thing I noticed: users and groups count pluralization was wrong for the 0 case in the attributes list.

fix: incorrect pluralization in attributes list

---

packages/common/src/types/filter.ts
packages/frontend/src/providers/ExplorerProvider.tsx

Closes: #8061 
Added the logic for updating filters when custom metrics are edited.
As our filter structure can be nested as well, so I have updated the custom metric names recursively.
Initial filters:
On renaming:

fix: rename a custom metric with filter

---

packages/common/src/types/savedCharts.ts
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/AxesOptions.tsx
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: #6327 
Enables label rotation for the x-axis (non-flipped). We can add this for the other axes if necessary. I did some of the setup, but wanted to see if we found this the right approach. And if we add it fro the other labels we probably should think about the UI differently; here it is just a single number input. 
A couple notes:
- This moves the axis name in a way that *usually* looks good, but can end up pushing the name offscreen if the fields are long. We could either add field truncation (I played with this and have some ideas) or allow them to place the name. 
- When there are *a lot* of labels, some still get hidden. Theres an echarts bug about this. 
The code in the config file is a little tangled -- I think I made reasonable tradeoffs 😅, but I'm happy to make changes. I …

feat: chart x-axis label rotation

---

dockerfile
dockerfile-prs

current issues:
test-frontend test-backend test-cli

chore(wip): use bookworm-slim for docker base image

---

docs/docs/references/groups.mdx
docs/docs/self-host/customize-deployment/environment-variables.mdx
docs/docs/self-host/customize-deployment/use-sso-login-for-self-hosted-lightdash.mdx
packages/backend/src/config/parseConfig.ts
packages/backend/src/controllers/authentication.ts
packages/backend/src/models/ProjectModel/ProjectModel.mock.ts
packages/backend/src/models/SavedChartModel.mock.ts

Closes: #8610
Recap:
1. if `AUTH_OKTA_AUTHORIZATION_SERVER_ID` is set:
we use that and the `AUTH_OKTA_DOMAIN`  + `AUTH_OKTA_AUTHORIZATION_SERVER_ID` to construct the issuer URI
Okta-side config:
we expect the user to turn on the `claims` to get groups on the Okta Admin panel for the Authorization Server
2. if `AUTH_OKTA_AUTHORIZATION_SERVER_ID` is  not set:
we just use the AUTH_OKTA_DOMAIN to construct the issuer URI
⚠️ introduced on this PR: we pass the `groups` scope by adding this scope as `AUTH_OKTA_EXTRA_SCOPES`.
Okta-side config:
we expect the user to turn on the `claim` `groups` on the `sign on` section of the Okta App configuration
With the new env var `AUTH_OKTA_EXTRA_SCOPES`, this should be set as a space-delimited string of scopes, e.g. "groups scope1 scope2"

fix: add extra scopes env var for okta groups

---

packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/components/common/modal/ChartCreateModal.tsx
packages/frontend/src/components/common/modal/ChartUpdateModal.tsx
packages/frontend/src/components/common/modal/DashboardCreateModal.tsx
packages/frontend/src/components/common/modal/DashboardUpdateModal.tsx

Closes: #7819 
Changed TextInput to Textarea to support multiple rows and scroll in our chart and dashboard descriptions.
I have added maxRows of 3 so the box will expand until 3 rows and will scroll from there on.
Example - Update Dashboard

feat: expand description box in charts and dashboards

---

docs/docs/references/embedding.mdx

switch embedding link from typeform+zapier to direct calendly booking.

docs: switch embedding interest link to calendly

---

packages/frontend/src/components/Explorer/CustomMetricModal/index.tsx

Relates to: #8688
- Add `custom-metrics-format` feature flag checking
- Show format modal when creating a numeric custom metric

feat: add accordion to format custom metrics

---

docs/docs/references/dimensions.mdx
examples/full-jaffle-shop-demo/dbt/models/events.yml
packages/common/src/schemas/json/lightdash-dbt-2.0.json
packages/common/src/types/timeFrames.ts
packages/common/src/utils/timeFrames.ts
packages/e2e/cypress/e2e/app/createProjects.cy.ts

Closes: #8139 
Added granular date options - `hour_of_day` and `minute_of_hour` date options to existing time frames.
Example - 
Table field view -
Output -
1) Results -
2) SQL -
Another Example output with Filters -

feat: granular date part options for date dimensions

---

packages/frontend/src/hooks/useSpaces.ts

Refetch pinned items on space mutation. Changing names wasn't causing an update.

fix: refetch pinned items on space mutation

---

packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: #8674
I'm not sure if there is a better fix for it, I spent an hour on this and I couldn't find a better solution. getAxisLabelFormatter on timeframes will not work here, we could add a new function, but that seems a bit too much for this edge case. 
I think the underlying issue is that echarts by default formats some numbers into floats (perhaps this depends on the `axis type` (time/value/category) ) 
If this is true, I guess it is affecting more types , but this PR is only fixing week_num to avoid introducing some new bugs. I am going to also look a some date bugs in tooltips, so I might reuse some of this code. 
Before:
After:

fix: week num chart float

---

packages/frontend/src/hooks/toaster/useToaster.tsx

Closes: #8658 
As our openedKeys did not keep track of the toast keys shown, our update/show notification logic was not working which caused the issue.
Updated code to add key on notification method `show`.
Toast shown on job done -
Before:
After:

fix: show success toast on refresh dbt complete

---

packages/cli/src/dbt/models.ts
packages/cli/src/handlers/generate.ts

Closes: NA
When I tried to use `lightdash generate` at `0.946.0`, I got the subsequent error. It seems that it doesn't pass the dbt vars to `getCompiledModels`. So, I want to enable passing it to the function.
```
$ lightdash generate --profiles-dir . --vars "$(cat ./vars.yml)" --verbose
> Making HTTP query to: https://xxx.lightdash.cloud/api/v1/health
> HTTP request returned status: 200
> HTTP request returned status: ok
> Making HTTP query to: https://xxx.lightdash.cloud/api/v1/user
> HTTP request returned status: 200
> HTTP request returned status: ok
> Loading dbt_project.yml file from: /Users/[username]/local/src/xxx/dwh-dbt
> dbt target directory: target
> Loading profiles from directory: /Users/[username]/local/src/xxx/dwh-dbt
> Loaded target from profiles: bigquery
> Loading dbt …
```

fix: pass dbt vars to getCompiledModels

---

docs/docs/references/metrics.mdx
examples/full-jaffle-shop-demo/dbt/models/schema.yml
packages/common/src/types/filterGrammar.test.ts
packages/common/src/types/filterGrammar.ts

Closes: #5048
Closes: #5485
Allows metric filters to specify an array of values to include (should it also take the inverse?? 🤔 I feel like I've way underestimated how complex this might get 😅  )

feat: Include multiple values in metric filter

---

packages/cli/src/dbt/models.ts
packages/cli/src/handlers/generate.ts

User requested to generate the metrics in a package they important into their dbt project (i.e. they live in `packages.yml` and `dbt_packages`). 
`lightdash generate` could find the model but was outputting them into the main project instead of `dbt_packages`

feat: use lightdash generate for dbt deps packages

---

docs/docs/references/embedding.mdx

Moves embedding info to a pill to make it more obvious

docs: moves embedding info about cloud + beta to info pill

---

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/AxesOptions.tsx
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes:  https://github.com/lightdash/lightdash/issues/8748
The issue: 
Line / scatter charts have a `min` function, (not a string) , so the filtering was wrong. 
Before:
After:

fix: empty line chart axis range

---

packages/frontend/src/features/scheduler/components/SchedulerForm.tsx

Closes: #8736 
To add spacing b/w label and field in TextInput, we cannot use mt or mb as these props are typically used for setting margin on the component as a whole, not for internal elements like labels.
So I have added a marginBottom of 0.25rem to the label. Considering other inputs have a margin of xxs which is equal to rem(4) in our mantine styles. Hence in rem it is, 4/16 = 0.25rem.
Reference - https://mantine.dev/styles/rem/
Before:
After:

fix: inconsistent spacing in scheduler form

---

packages/frontend/src/components/common/Table/ScrollableTable/TableHeader.tsx

Fixes the occasional empty tooltip, particularly if using table calculations as part of a result, when looking at result table header fields. This behavior applies to anything that isn't a field.
Before:
Now: 
(No tooltip is displayed)

fix: TableHeader empty tooltip on results

---

docs/docs/references/user-attributes.mdx
packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts

Closes: #8536 
Developers should have access to all attribute values, independently if they are set at the user level, group level, or default value. This matches the behaviour we have for Table and Column filtering. 
- https://deploy-preview-8769--peaceful-bassi-cbf284.netlify.app/references/user-attributes#row-filtering-with-sql_filter
- https://deploy-preview-8769--peaceful-bassi-cbf284.netlify.app/references/user-attributes#row-filtering
---
**Current behaviour**
```sql_filter: ${TABLE}.sales_region = ${lightdash.attributes.sales_region}```
That would convert to
```sales.sales_region = 'USA'```
**New behaviour**
```sql_filter: ${TABLE}.sales_region = ${lightdash.attributes.sales_region}```
That would convert to
```sales.sales_region = 'USA'```
Note that is it backwards compatible.
--- …

feat: access all attribute values when filtering rows

---

packages/backend/src/services/ProjectService/ProjectService.ts

- Includes support for a new `new-table-calculations-engine` feature flag
- When enabled, includes a new span attribute for `ProjectService.runMetricQuery`:
- `tableCalculationsNum`: number of table calculations for this query
The goal is to measure the impact of upcoming table calculation changes on metrics queries. The span attribute will be moved outside the feature flag condition in a follow-up PR, to allow comparison testing (with/without new table calculations changes).

feat: Add additional attribute for # of table calculations in `ProjectService.runMetricQuery` trace

---

packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx

Closes: 
show explanation tooltip when button is disabled not the opposite.

fix: filter configuration apply tooltip

---

packages/backend/src/database/migrations/20240130125623_add-custom-metrics-format-options.ts

Closes: N/A
Edit missed `dropColumn` in down function for `format_options` -> custom metrics formatting

fix: dropColumn format_options on down in migration

---

examples/full-jaffle-shop-demo/dbt/models/schema.yml
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/types/field.ts
packages/common/src/utils/filters.ts
packages/common/src/utils/formatting.test.ts
packages/common/src/utils/formatting.ts
packages/e2e/cypress/e2e/app/formats.cy.ts
packages/frontend/src/components/Explorer/FormatForm/index.tsx
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts
packages/frontend/src/hooks/useBigNumberConfig.ts

Closes: #8767 
- Unifies the legacy formatting functions used for Metrics and Dimensions with the TableCalculation ones adhering to CustomFormat type
- Adds a convert function from legacy Format to CustomFormat
- Standardises rounding so that when round is undefined, then up to 3 decimal places are kept
- Adds support for negative rounding to Metrics and Dimensions. Previously it was just available for TableCalculations
- Fixes the tests

feat: unify legacy Format with CustomFormat functions

---

packages/frontend/src/components/common/modal/DashboardCreateModal.tsx

Opening the Create Dashboard modal causes a console error about nesting that can be annoying. Wrapping the modal title in a Box seems to fix the error.

chore: fix dom nesting warning in create dashboard

---

packages/e2e/cypress/e2e/api/api.cy.ts

Closes: https://github.com/lightdash/lightdash-internal-work/issues/1435
Not sure why they were disabled, probably we added `.only` for testing, and merged by mistake.

chore: reenable api e2e tests

---

packages/frontend/src/App.tsx
packages/frontend/src/components/VersionAutoUpdater/VersionAutoUpdater.tsx
packages/frontend/src/hooks/health/useHealth.tsx

Closes: #8806
Every 10 minutes the FE checks the server version.
If there is a new version and the user is creating/editing a chart/dashboard it shows a toast otherwise it refreshes the page.
Auto refresh page when version updates:
https://github.com/lightdash/lightdash/assets/9117144/e3faeedb-5fc4-44fc-b628-6e379ce75d89
Shows toast when version updates:
https://github.com/lightdash/lightdash/assets/9117144/fb3988ca-32cc-4762-ab1d-da339c7226ca

feat: version auto updater

---

packages/backend/package.json
packages/backend/src/services/UnfurlService/UnfurlService.ts
yarn.lock

Closes: N/A
Add 2 approaches here with Feature Flags for `element.screenshot`
1. `puppeteer-scroll-element-into-view`  - scroll into view of `element`. https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/api/ElementHandle.ts#L1239 
There was a _hidden_ feature on `element.screenshot()` - we can pass a `scrollIntoView` of element which will attempt a second `getBoundingBox` call if the element isn't _ready_. This is related to the `node has 0 height` error.
2. `puppeteer-set-viewport-dinamically` - https://github.com/puppeteer/puppeteer/issues/2423#issuecomment-590738707 Now this is another where screenshots don't work as expected. Could be a case where the element is not visible yet. This approach will: 
- Get the viewport size of the full page after charts are …

fix: experiment with 2 approaches when taking screenshot of dashboard

---

packages/common/src/types/featureFlags.ts
packages/frontend/src/components/LightdashVisualization/VisualizationConfigCartesian.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts

Taken from the method comment:
```ts
/**
* Given the org's color palette, and a dimension identifier, return the color
* in the palette assigned to that identifier.
*
* This works by hashing the identifier into an integer value, and then projecting
* that value into the org's color space - effectivelly getting a number from 0 to
* <number of colors in palette>.
*
* This is a straight-forward way to handle hashing dimensions into colors, with
* two major caveats:
*
* - We're no longer cycling over colors in the palette, potentially not following
*   an intentionally-designed best-neighbor-color approach.
* - We have no guarantee different dimensions won't be assigned the same color due
*   to the narrow color space - we can fix this by shifting colors aside when
*   compiling the chart …
```

feat: add shared chart color support under feature flag

---

packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx

Partially closes: #8873 
This issue was also coming up in case of `greater than` as it was related to our `FilterNumberInput`
The check for the input value - `values: newValue ? [newValue] : []` evaluated to false for 0 and hence did not set the values correctly.
Before:
After:

fix: using zero in conditional formatting

---

packages/common/src/utils/formatting.test.ts
packages/common/src/utils/formatting.ts

Closes: #8855 
The issue was due to the `maximumSignificantDigits` that we had set for case `round <= 0.`
When `round = 0`, `maximumSignificantDigits` was set to 1. This worked fine for numbers greater than 1.
But for cases like 0.001, the only significant digit ie. 1 is being taken into account and we get 0.001 as output even if round was set to 0.
Fixed by removing the = from the if condition. Added a test for the same.

fix: round with no decimals in table calculations

---

packages/common/src/utils/formatting.test.ts
packages/common/src/utils/formatting.ts

Closes: #8869
Cast numbers as strings when their `type` is set as `string`.
Where this was happening before: https://github.com/lightdash/lightdash/pull/8807#discussion_r1484326210

fix: return correct cast when type string

---

packages/frontend/src/pages/SqlRunner.tsx

chore: clean up sql runner sidebar

---

packages/frontend/src/components/MetricQueryData/DrillDownModal.tsx

Closes:  #8868
The drill menus will now have table names as headers.
Passing the `hasGrouping` prop to `FieldSection` component has made this possible.

feat: drill menus table names as headers

---

.github/workflows/cli-tests.yml
packages/cli/src/index.ts

Closes: #8773 
- Set -`-use-dbt-list` option true as default in cli
- Allow the user to use `--use-dbt-list=false` in case they need to use dbt compile
- Setting it to any value other than `true` or `false` would set it back to true
Example - 
The following commands will consider --use-dbt-list to true.
```
node <index.js path> deploy --create --profiles-dir .
node <index.js path> deploy --create --profiles-dir . --use-dbt-list
node <index.js path> deploy --create --profiles-dir . --use-dbt-list=true
node <index.js path> deploy --create --profiles-dir . --use-dbt-list true
```
Output - 
For setting it to false, we can use -
```
node <index.js path> deploy --create --profiles-dir . --use-dbt-list=false
node <index.js path> deploy --create --profiles-dir . --use-dbt-list false
```
Output -

feat: set --use-dbt-list as default in cli

---

docs/docs/references/filters.md
docs/docs/references/metrics.mdx
packages/common/src/compiler/filtersCompiler.ts

Closes: #8728
This may be intentionally designed as such, so apologies if so!!
But we were attempting to filter by "!true" and came across this, in a column that was brought in from a join onto our base table in such a way that true, false, null were all available, and we explicitly want [false, null].
Filtering as a list of values also fails as it casts them to string if that's preferable to fix?

feat: Render not equals SQL for boolean filter

---

packages/frontend/src/App.tsx
packages/frontend/src/components/NavBar/index.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/pages/Dashboard.tsx
packages/frontend/src/providers/AppProvider.tsx
packages/frontend/src/testing/__mocks__/providers/AppProvider.mock.tsx

- closes: #3195 
- Adds a TV/Fullscreen mode for dashboards:
- Hides navbar when in fullscreen mode:
Additionally, correctly handles browser-native fullscreen controls (e.g if the user exits fullscreen manually, we also disable TV mode in Lightdash).

feat: TV/Fullscreen mode for dashboards

---

packages/frontend/src/components/SqlRunner/SqlEditorActions.tsx
packages/frontend/src/components/SqlRunner/SqlRunnerInput.tsx
packages/frontend/src/features/tableCalculation/components/SqlForm.tsx
packages/frontend/src/features/tableCalculation/components/TableCalculationModal.tsx

- Fixes an error on the table calculations modal where the modal title was an `h5` inside the Mantine-default `h2` title (which is not valid html, and throws an error)
- Made `SqlEditorActions` a shared component across `SqlRunnerInput` and `SqlForm`, with both editors now supporting soft wrapping and copying to clipboard:

feat: standardize editor actions across SqlForm and SqlRunnerInput

---

packages/e2e/cypress/e2e/app/sqlrunner.cy.ts
packages/frontend/src/components/ChartDownload.tsx

Closes: #8906 
- Set `png` as the default export option in charts
- Allow the toggling of background transparency in `png` - set transparent by default
- I have added select options `Transparent` and `Opaque` for png exports. We can change the values to whatever feels suitable. Can also create an enum for the transparency options similar to how its done for download type if need be.
Output - 
`bg-transparency option in png` - 
Transparent PNG -
Opaque PNG -

feat: export png by default

---

packages/frontend/src/components/SqlRunner/SqlRunnerInput.tsx
packages/frontend/src/features/tableCalculation/components/SqlForm.tsx

Follow-up to: #8771 
- Enables soft-wrapping by default
- Saves the user's selection locally using local storage
Note: this implementation tracks sql runner and the table calculations sql form separately; there's likely a good case for reusing the same state between both, but given the different dimensions & context for either, there's potentially good reasoning for keeping them separate, too.

feat: enable soft-wrapping by default, store user choice locally

---

packages/backend/src/queryBuilder.mock.ts
packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts

Closes: https://github.com/lightdash/lightdash-commercial/issues/73
(See ticket from commercial on how to replicate ^)
When users set a `sql_filter` that is similar to this expression: 
```
${TABLE}.status = ${lightdash.attributes.order_status} or ${lightdash.attributes.order_status} = 'ALL'
```
And if the following statement is true: `${TABLE}.status = ${lightdash.attributes.order_status}`, then if the user sets extra filters on a chart, these will be ignored because there's a `( )` wrap missing. 
This will then affect charts and their generated SQL + where they're being used (dashboards, embedded dashboards)
This will then wrap the `replacedUserAttributesSQL` with a `()`
Question: should this be done somewhere else? I'm not sure...

fix: wrap sql_filter with ()

---

packages/common/src/types/featureFlags.ts
packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/PostgresForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/RedshiftForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/SnowflakeForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/TrinoForm.tsx
packages/frontend/src/hooks/useFeatureFlagEnabled.ts
packages/frontend/src/pages/Settings.tsx

Follow-up on #8795
- Adds a new `useFeatureFlagEnabled` hook that shadows posthog's, with stricter typing to require a member of the `FeatureFlags` enum
- Update existing uses of posthog's `useFeatureFlagEnabled` to use this new hook.
Note: intentionally avoided any type-level trickery (e.g overriding the external type definition for posthog's hook); technically would be a lower surface area, but could introduce maintainability issues down the road.

fix: add new useFeatureFlagEnabled hook, migrate existing frontend feature flags

---

packages/cli/src/handlers/dbt/compile.ts

Relates to: #8928 
`dbt ls` supports the `--quiet` flag for dbt `1.5.5` but fails for other patch versions like: `1.5.4`. For `1.6.x`, `dbt ls` doesn't support this flag for >`1.6.0` and <`1.6.6`
Instead of providing a very explicit range of versions before pushing arg `--quiet` in:
```ts
if (!version.startsWith('1.3.') && !version.startsWith('1.4.')) {
args.push('--quiet');
}
```
Let's add a workaround and more detailed error message to our users when logging the error, to: 
* advise on upgrading to latest patch version of `dbt`
* provide a potential alternative to the command they're using (that uses `dbt ls`) to disable it by setting `--use-dbt-list=false`

chore: update dbt compile error message

---

packages/frontend/src/components/ChartDownload.tsx

Closes: #8914 
Disabled chart download for custom viz. https://github.com/lightdash/lightdash/issues/8914#issuecomment-1941869268

fix: disable chart download in custom viz

---

packages/backend/src/models/SearchModel/index.ts
packages/e2e/cypress/e2e/app/globalSearch.cy.ts
packages/frontend/src/components/NavBar/GlobalSearch/index.tsx
render.yaml

Closes: #8926 
- Makes sure that the filtering of results is done in the backend (for dashboards for now)
- Removes all default mantine filtering
Before:
After:

fix: remove mantine default filtering

---

packages/backend/src/database/entities/savedCharts.ts
packages/backend/src/database/migrations/20240214160420_add_search_vector_to_charts.ts
packages/backend/src/models/DashboardModel/DashboardModel.mock.ts
packages/backend/src/models/SearchModel/index.ts
packages/backend/src/models/SearchModel/utils/fullTextSearch.ts

Related to: #5631
- Adds full text search to charts
- Makes search rank calc raw sql reusable

feat: add full text search to charts

---

packages/cli/src/dbt/models.ts

some dbt configurations are not listing out models in packages for example:
```
dbt ls -s other_package.model_in_other
dbt ls -s model_in_other
```
In the first case `dbt` fails. In the second case `lightdash fails`. This fixes the second case, by checking for the `package_name` on the model metadata instead of relying on the `patch_path` to determine it (it seems sometimes the `patch_path` is missing)
Slack thread: https://lightdash.slack.com/archives/C0699FEJCR0/p1708003529824679?thread_ts=1705415250.660129&cid=C0699FEJCR0

fix: use dbt model package_name for lightdash generate

---

packages/backend/src/dbt/DbtMetadataApiClient.ts

Fix to handle `model.alias` on the new MetadataApiAdapter

fix: use dbt model alias from discovery api

---

packages/common/src/types/organization.ts
packages/common/src/utils/email.ts
packages/frontend/package.json
packages/frontend/src/components/ProjectTablesConfiguration/ProjectTablesConfiguration.tsx
packages/frontend/src/components/UserSettings/AllowedDomainsPanel/index.tsx
packages/frontend/src/components/UserSettings/DefaultProjectPanel/index.tsx
packages/frontend/src/components/UserSettings/OrganizationPanel/index.tsx
packages/frontend/src/components/UserSettings/PasswordPanel/index.tsx
packages/frontend/src/components/UserSettings/ProfilePanel/index.tsx
packages/frontend/src/features/scheduler/components/SchedulerForm.tsx
packages/frontend/src/hooks/user/useUserUpdateMutation.ts
packages/frontend/src/utils/fieldValidators.ts
yarn.lock

Closes: #8738 
Added code to keep save/update buttons inactive until a change is made. Also includes cancel button to revert back to original state.
Areas of impact in the form settings
Just wanted to check on the `Organizations - Embedding configuration form`.
I do see it in the docs - https://docs.lightdash.com/references/embedding/. Is the code for this closed-source for now?
Output:
Profile Form -
Before:
On Change:
Table Configuration Form-
Before:
On Change:
General Form-
Before:
On Change:

feat: button inactive until change

---

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx

The chart move to space menu was clickable where it shouldnt be and also showed an incorrect popup about charts in dashboards when clicked. This makes it so:
- You can't click disabled items in the sub menu
- You can't click the "move to space menu header"
Before:
After (fixed)

fix: move to space menu click handling

---

packages/backend/src/database/migrations/20240207133121_add-english-dictionary-with-custom-stop-words.ts
packages/backend/src/database/migrations/20240207133122_add_search_vector_to_dashboards.ts
packages/backend/src/database/migrations/20240214160420_add_search_vector_to_charts.ts
packages/backend/src/database/migrations/20240215091924_add_search_vector_to_spaces.ts
packages/backend/src/models/SearchModel/utils/fullTextSearch.ts

Relates to: [#5631](https://github.com/lightdash/lightdash/issues/5631)
Default dictionary uses stop words which would impact our search results, this removes those stop words.
Before:
After:

fix: add and use dictionary with no stop-words

---

packages/backend/src/services/GitIntegrationService/GitIntegrationService.ts

Hide the add custom metric to project button. I did this the quick way but commenting out the UI for now. We should put it behind a feature flag

fix: hide dbt metric button

---

packages/frontend/src/features/scheduler/components/SchedulerForm.tsx

Closes: #8944 
Allow using decimal values in alerts.
I tested this a few ways and it all seems to work. There is one oddity with this component that 1.5 gets saved as 1,5 regardless of the system number format. We should fix that in the component, not here.

fix: floating point values in alerts

---

packages/common/src/types/filter.test.ts
packages/common/src/types/filter.ts
packages/frontend/src/providers/ExplorerProvider.tsx

Closes: #8629 
Added logic for updating filters when custom metrics are removed.
Example -
Before:
On removing:

fix: remove a custom metric with filter

---

packages/frontend/src/features/scheduler/components/SchedulerForm.tsx

Closes: #8945 
This just makes the field for alerting required. I thought there would be other validation that made sense, but I think this is sufficient for now.

fix: require threshold field in alerts

---

.github/workflows/duplicate-external-pr.yml

Adds `Duplicate External PR` by commenting on PR with `/duplicate-external-pr`
Before doing so, it checks if user belongs to `lightdash/engineering` team

chore: add duplicate-external-PR GH action

---

examples/full-jaffle-shop-demo/dbt/models/customers.sql
examples/full-jaffle-shop-demo/dbt/models/schema.yml
packages/common/src/compiler/translator.mock.ts
packages/common/src/compiler/translator.ts

Closes: #8963
dbt models have the table name under `alias` property. This property is also populated when the developer didn't set a alias in the yml.
Before: all dimensions are marked as strings
After: dimensions have correct type

fix: support model alias

---

.github/workflows/duplicate-external-pr.yml

Closes: N/A
Utilises `GITHUB_CI_TOKEN` to check if user is part of lightdash engineering team

fix: use GITHUB_CI_TOKEN to check team in org

---

packages/frontend/src/components/common/Filters/FilterInputs/FilterStringAutoComplete.tsx

Attempts to fix #8840 
Opts-out of Mantine's multi-select condition for `shouldCreate`, which hides the option under some conditions:
- Missing query - which I tweaked to also exclude fully empty strings
- value exists in list of items even if casing doesn't match)
- There's some existing uniqueness logic in Lightdash's filter string autocomplete component that was causing some weirdness when paired with Mantine's condition.

fix: prevent filter autocomplete from disallowing adding custom values

---

packages/backend/src/database/migrations/20240220102923_add-weight-to-spaces-vector.ts

Closes: 
- Adds name weight to `spaces` search vector, it was giving wrong ranks

fix: adds spaces search_vector weighted by name

---

packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/UserSettings/AppearanceSettingsPanel/index.tsx
packages/frontend/src/hooks/useChartColorConfig.ts

Closes: #8978 
Skips the shared color assignment logic for non-group series, instead using the default behavior that applies color from the palette in order.

feat: Do not apply shared colors to non-group series

---

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/features/scheduler/components/SchedulerModal.tsx

Closes: #8980
This PR changes name from `Threshold Alerts` to `Alerts` in Chart Context Menus and also for the Threshold Alert Modal as shown in the following screenshots.
Please let me know if there are any other changes to be made, I will be happy to make them as desired :)

fix: change name to 'Alerts' in chart context menus

---

packages/backend/src/services/CsvService/CsvService.ts
packages/backend/src/services/GitIntegrationService/GitIntegrationService.ts
packages/backend/src/services/UnfurlService/UnfurlService.ts

If the SITE_URL variable ends with a `/` we generate invalid URLs. Example:
> Cannot POST //api/v1/headless-browser/login/ff2a9f1d-08bd-49df-8ce5-540e8a06197f
Change updates all the cases where we were concatenating the SITE_URL to use [URL constructor](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL).
This should also fix any security issues related to path traversing.

fix: generate valid urls based on site url

---

examples/full-jaffle-shop-demo/dbt/models/customers.sql
examples/full-jaffle-shop-demo/dbt/models/schema.yml

Closes: 
E2E tests are failing because it expects a new table in the staging warehouses that doesn't exist. 
I reverted the jaffle project to not use the table alias anymore, restoring it as it was before.
test-frontend

chore: revert customers table alias

---

.github/workflows/duplicate-external-pr.yml

Closes:N/A
Related to `duplicate-external-pr` github action
output should be set as `GITHUB_OUTPUT`
fixes typo where I had `GITHUB_ENV` 
team affiliation check works: https://github.com/lightdash/lightdash/actions/runs/7987560280

chore: fix typo with step output

---

packages/frontend/src/components/common/Filters/FilterInputs/FilterStringAutoComplete.tsx

Tightens the logic around filter matching/value creation by hiding the option for exact matches. Fixes failing e2e test.

fix: do not show create option for exact matches on filter input

---

packages/backend/src/models/SearchModel/index.ts
packages/backend/src/routers/projectRouter.ts
packages/backend/src/services/SearchService/SearchService.ts
packages/common/src/types/search.ts

Relates to: #5266 
- Adds backend to allow for entity type filter in global search. The types supported are:
- charts
- dashboards
- tables
- fields
- spaces
Examples:
- search for `jaffle`
- with no filter: `http://localhost:3000/api/v1/projects/3675b69e-8324-4110-bdca-059031aa8da3/search/jaffle`
```json
{"status":"ok","results":{"spaces":[{"uuid":"156de9a5-9db6-4c71-8bf2-aa7fe981cfeb","name":"Jaffle shop","search_rank":0.6079271}],"dashboards":[{"uuid":"fb03a6dd-66b2-4445-9d4e-a4b4f039259e","name":"Jaffle dashboard","description":null,"spaceUuid":"156de9a5-9db6-4c71-8bf2-aa7fe981cfeb","search_rank":0.6079271,"validationErrors":[]}],"savedCharts":[],"tables":[],"fields":[],"pages":[]}}
```
- with type dashboards filter: `http://localhost:3000/api/v1/projects/3675b69e-8324-4110-bdca-059031 …

feat: add entity type filter backend for global search

---

packages/backend/src/database/migrations/20240220173325_remove-share-user-id-cascade-deletion.ts

Closes: #8981 
- When a user is deleted, the `current_user_id` in share URLs is set to null. Currently we have the `ON DELETE CASCADE` for the foreign key `current_user_id` in the `shares` table. Due to this, when a user is deleted, any share URL created by him are broken. 
- Added a migration file to update this to `ON DELETE SET NULL` instead (also removed the `NOT NULL` constraint). Verified the changes in postgres database as well. (also checked the rollback command)
Share URL initially - 
When a user is deleted :
Before: 
After:

feat: set user id to null in share URL when user deleted

---

packages/backend/src/models/SearchModel/index.ts

- Search filter for pages wasn't being applied so it always returned pages

fix: search type filter for page wasn't being applied

---

examples/full-jaffle-shop-demo/dbt/models/docs.md
packages/frontend/src/components/Explorer/ExploreTree/TableTree/ItemDetailContext.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNode.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNodeActions.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/index.tsx
packages/frontend/src/utils/markdownUtils.ts

Closes: #1174 
Adds an improved UX for viewing dbt field descriptions:

feat: show longer dbt descriptions for fields, including markdown support

---

packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNode.tsx

Fixes a flake e2e test on custom dimensions.
- Explicitly close description popover when opening item menu
- Tweak popover offset when field is filtered to avoid the menu option being covered by it

fix: explicitly close description popover when menu clicked, tweak offset

---

packages/backend/src/models/SearchModel/index.ts
packages/backend/src/models/SearchModel/utils/filters.ts
packages/backend/src/routers/projectRouter.ts
packages/common/src/types/search.ts
packages/frontend/src/features/omnibar/components/OmnibarFilters.tsx

Closes: [#5266](https://github.com/lightdash/lightdash/issues/5266)
- Adds created by filter to omnibar
https://github.com/lightdash/lightdash/assets/22939015/04a41759-01a5-4588-9f6a-d9982015eef9
Notes: `dashboards` and `saved_charts` are versioned entities but there's a difference, `saved_charts` has `last_version_updated_by_user_uuid` column which means we don't need to join with any other table to apply the filter. `dashboards` on the other hand are not, so we need to join with `dashboard_versions` to get the user UUID of who created the latest version. See: `packages/backend/src/models/SearchModel/utils/filters.ts` - `filterByCreatedByUuid` function and its usage in `packages/backend/src/models/SearchModel/index.ts`

feat: add search createdBy filter

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx

Closes: #9097 
Export CSV option is now available to VIEWERS and for all chart types.
Exporting chart images and exporting to google sheet not included in this ticket. We can create a ticket if users ask for it.

fix: allow viewers to export csv from dashboard

---

packages/backend/src/database/entities/scheduler.ts
packages/backend/src/database/migrations/20240222164421_add_notification_frequency_to_alerts.ts
packages/backend/src/models/SchedulerModel/index.ts
packages/backend/src/scheduler/SchedulerTask.ts
packages/common/src/types/scheduler.ts
packages/frontend/src/features/scheduler/components/SchedulerForm.tsx

Closes: #9026 
Note that this is a draft at the moment. It seems to work, but I'd like to test it more rigorously. 
Adds a checkbox to send scheduled alerts just once. This does this by disabling the alert once it's been sent. I added some helper text when the box is turned off. Should we add some text when it is on as well.
Send once state:
Send always state:

feat: send once option for threshold alerts

---

packages/backend/src/models/SearchModel/index.ts
packages/backend/src/models/SearchModel/utils/fullTextSearch.ts

- Always use `search_rank`, do not depend on argument value

fix: always use same name for search_rank, do not depend on arg

---

packages/backend/src/models/SearchModel/index.ts
packages/backend/src/models/SearchModel/utils/filters.ts
packages/backend/src/models/SearchModel/utils/fullTextSearch.ts

- Sets the `search_rank` alias in the query rather than in raw sql
- Uses named bindings for search rank raw sql
- Uses named bindings for created at filter raw sql

fix: use hardcoded search_rank alias

---

packages/frontend/src/features/metricFlow/hooks/useMetricFlowQueryResults.ts

Closes: 
Context: we need to first create a query and then use the query ID to fetch the results. 
Problem: `@tanstack/react-query` useQuery was caching the query ID so we were trying to fetch the results from an expired query ID.
Before:
https://github.com/lightdash/lightdash/assets/9117144/8925fa5e-b16e-42f7-965f-7dcb0fda4068
After:
https://github.com/lightdash/lightdash/assets/9117144/94bee1cf-8458-496b-840b-35c43d5ba21b

fix: semantic layer expired query

---

packages/backend/src/postHog.ts
packages/backend/src/projectAdapters/projectAdapter.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/UnfurlService/UnfurlService.ts
packages/common/src/types/featureFlags.ts

Unblocks (part of?) the query experience during Posthog outage: https://status.posthog.com/
Temporarily removes `UseInMemoryTableCalculations` feature flag check.

fix: remove posthog check for UseInMemoryTableCalculations

---

packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx

Closes: #9062 
Moved `filterLabel` state from `FilterSettings` to `FilterConfiguration` to use it in `FieldLabel`.
Example - 
Set field label of `Order Date Year` to `Year of order date`
Before:
After:

fix: dashboard filter label inside modal

---

packages/cli/src/dbt/models.ts
packages/cli/src/handlers/generate.ts

Closes: #9107 
Updated the `findAndUpdateModelYaml` and `askOverwriteDescription` to assume yes if `-y` or `--assume-yes` flag used with generate command.
For testing - added a column to `deletedColumnNames` so that change is needed in column list.
Commands : assume-yes
```
node ./packages/cli/dist/index.js generate -y
node ./packages/cli/dist/index.js generate --assume-yes
```
Before:
After:

fix: assume yes in cli generate command

---

packages/frontend/src/features/metricFlow/hooks/useMetricFlowQueryResults.ts

Closes: 
Context: Some metrics require a dimension to be selected. 
Problem: At the moment there isn't a direct way for us to know that before running the query. 
Solution: Show a nicer error message
Before:
After:

fix: semantic layer required dimension message

---

packages/backend/src/models/SchedulerModel/index.ts

Closes: #9053 
`charts` created in `dashboards` were not showing up because they don't belong to a `space` and therefore have `space_id` column set to `NULL`
Since those `charts` belong to a `dashboard` the fix is to join that table in the query to get access to the `space_id` column

fix: dashboard chart schedulers not appearing

---

examples/full-jaffle-shop-demo/dbt/models/schema.yml
packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
packages/frontend/src/components/Explorer/ExploreSideBar/ExploreNavLink.tsx
packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/ItemDetailPreview.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNode.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/index.tsx

Follow-up to #1174 
Ticket: #9148 
Extends markdown/longer description support to the Explore sidebar's models list
- Removes tooltip from breadcrumb for simplicity for now, will re-introduce it with markdown support on a follow-up if deemed necessary, but requires more work to ensure it works well across different breadcrumb uses.
- Adds support for markdown descriptions on models
- Reshuffles some code around to remove duplication around model descriptions + minor cleanup

feat: Add support for markdown descriptions for models, in the Explore sidebar models list

---

packages/backend/src/postHog.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/UnfurlService/UnfurlService.ts
packages/common/src/types/featureFlags.ts

Closes: #9165 
Follow-up to: #9154 
- Slightly increases the timeout value for the Posthog feature flag check, and adds an escape hatch via an env var to control the timeout value.
- Migrates `PuppeteerScrollElementIntoView` and `PuppeteerSetViewportDynamically` to the `FeatureFlags` enum, and re-adds the checks for these flags using the `isFeatureFlag` enabled helper
- Re-enables the feature flag check for `UseInMemoryTableCalculations`

chore: Revert posthog-outage related changes, migrate feature flags to `isFeatureFlagEnabled` helper

---

packages/frontend/src/components/VersionAutoUpdater/VersionAutoUpdater.tsx

Closes: #9162 
- Removes auto refresh on lightdash version update in favor of showing toast.

fix: always show toast on version update

---

packages/frontend/src/features/comments/components/CommentWithMentions/SuggestionList.tsx

Closes: N/A
Introducing the `Menu` in here: https://github.com/lightdash/lightdash/issues/9135 meant that suggestions could be easily keyboard-navigatable but search functionality ended up not working. 
This brings back the Card + list approach and that is fine. 
Tested: 
- keyboard only
- mouse
- searching valid usernames and searching with no results

fix: allow search of tagged people again

---

packages/frontend/src/features/comments/components/CommentDetail.tsx
packages/frontend/src/features/comments/components/CommentForm.tsx
packages/frontend/src/features/comments/components/CommentWithMentions/index.tsx
packages/frontend/src/features/comments/components/DashboardCommentAndReplies.tsx
packages/frontend/src/features/comments/components/DashboardTileComments.tsx

Closes: N/A
Instead of creating a `tiptap` instance for each comment, let's just use a `Box` component where we set its html to the output html from tiptap (`comment.textHtml`)
Other bits that weren't properly managed from merge conflicts:  https://github.com/lightdash/lightdash/commit/630408ee18eb297ddfe22e02442b845c15aefeff
And a clarification/fix of a confusing variable name: https://github.com/lightdash/lightdash/commit/e9c1555d255912075acb0e889d3fbc7551c023b3
Additionally, I have adjusted the popover width for the comments list to be more constrained, addressing an issue where an excessively long comment could expand the list's width. The width and maximum width have now been set to 400 in packages/frontend/src/features/comments/components/DashboardTileComments.tsx, ensuring a …

chore: improve performance of comment details

---

packages/backend/src/controllers/baseController.ts
packages/backend/src/controllers/commentsController.ts
packages/backend/src/controllers/csvController.ts
packages/backend/src/controllers/dbtCloudIntegrationController.ts
packages/backend/src/controllers/exploreController.ts
packages/backend/src/controllers/gitIntegrationController.ts
packages/backend/src/controllers/githubController.ts
packages/backend/src/controllers/googleDriveController.ts
packages/backend/src/controllers/groupsController.ts
packages/backend/src/controllers/notificationsController.ts
packages/backend/src/controllers/organizationController.ts
packages/backend/src/controllers/pinningController.ts
packages/backend/src/controllers/projectController.ts
packages/backend/src/controllers/runQueryController.ts
packages/backend/src/controllers/savedChartController.ts
packages/backend/src/controllers/schedulerController.ts
packages/backend/src/controllers/shareController.ts
packages/backend/src/controllers/spaceController.ts
packages/backend/src/controllers/sshController.ts
packages/backend/src/controllers/userAttributesController.ts
packages/backend/src/controllers/userController.ts
packages/backend/src/controllers/validationController.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/ServiceRepository.ts
packages/backend/src/services/services.ts
packages/backend/src/services/tsoaServiceContainer.ts

**See #9232 for the full context.**
This PR is a follow-up to #9233, and will be rebased once that (and its parent) are merged.
Closes: #9169
Implements part of #9151 
Updates all controllers to use the injected `ServiceRepository` to access services, instead of relying on the singleton export from `./services`.
This is functionally the same as before, since we're ultimately using our singleton services as part of the `ServiceRepository` setup, but this allows us to later move forward to proper dependency injection.

chore: update controllers to use injected `ServiceRepository` for service access

---

packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/UsersView.tsx

Closes: #9191 
A user reported they couldnt delete users they had searched for. This is a tiny fix. I don't know why the code was like this, but I everything seems to work well now. 
You can test by searching for a user. If there was only one search result, the delete button was being disabled. Now they should be deletable.

fix: dont disable delete on user search

---

packages/backend/src/App.ts
packages/backend/src/routers/analyticsRouter.ts
packages/backend/src/routers/apiV1Router.ts
packages/backend/src/routers/dashboardRouter.ts
packages/backend/src/routers/headlessBrowser.ts
packages/backend/src/routers/inviteLinksRouter.ts
packages/backend/src/routers/jobsRouter.ts
packages/backend/src/routers/organizationRouter.ts
packages/backend/src/routers/passwordResetLinksRouter.ts
packages/backend/src/routers/projectRouter.ts
packages/backend/src/routers/savedChartRouter.ts
packages/backend/src/routers/slackRouter.ts
packages/backend/src/routers/userRouter.ts

Closes: #9151 
Follow-up to other PRs included in the related ticket above. Expands the service repository support to express routers under `routers/`.
This is, for now at least, done via a middleware that injects `ServiceRepository` under `req.services` - the same singleton `ServiceRepository` used for controllers.

chore: migrate routes to use ServiceRepository

---

packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
packages/frontend/src/components/DashboardTiles/TileForms/ChartUpdateModal.tsx

Closes: #9240 
- Allows to hide the title of a chart belonging to a dashboard
- Hides the select to replace chart if tile is a dashboard chart
https://github.com/lightdash/lightdash/assets/22939015/bf84592c-d81d-424e-8c1b-37966771e0ec

feat: enable hiding dashboard chart title

---

packages/frontend/src/features/comments/components/CommentForm.tsx
packages/frontend/src/features/comments/components/CommentWithMentions/SuggestionList.tsx
packages/frontend/src/features/comments/types/index.ts

Closes: #9219 
Display tooltip and make button disabled when the user I'm trying to tag  doesn't have access to the dashboard's space.
There's also a performance issue that is reported in a TODO in `userNames`
https://github.com/lightdash/lightdash/assets/7611706/38c3bf38-4fd3-4e18-aadd-d623471c9b5f

fix: only tag users with dashboard access

---

packages/frontend/src/hooks/tableVisualization/useTableConfig.ts

Closes: #9027 
I have utilized `cloneDeep` to create a fully independent copy of the `columnProperties` object, avoiding the direct mutation of state. 
Also each property is checked for configurability before deletion, to prevent deletion of non-configurable properties.
Had to create a test object to reproduce the issue,
Test code :
```
let properties = {};
Object.defineProperties(properties, {
__1: {
value: { visible: true, name: 'Column 1', frozen: false },
configurable: false,
enumerable: true,
},
column2: {
value: { visible: true, name: 'Column 2', frozen: false },
configurable: true, 
enumerable: true,
},
});
Object.keys(properties).forEach((field) => {
try {
console.log(`Attempting to delete property '${field}'`);
delete properties[field]; // Attempt to delete - error here …
```

fix: delete property of columnProperties object

---

packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: #8857 
- This issue was previously reported in the `echarts` repository: https://github.com/apache/echarts/issues/19178
- Implements suggestion to use `symbolSize: 0` to hide the symbol but still display the labels for `line` and `area` charts
NOTE: This is a frontend only implementation that depending on the `showSymbol` value for `line` and `area` charts we either set `symbolSize` to `0` or `4` (default size: https://echarts.apache.org/en/option.html#series-line.symbolSize). We could also add this value to be saved on the database, but I didn't find a good enough reason to do it as we can simply infer the `symbolSize` value from the `showSymbol` value for display purposes.
Before:
After:

fix: use symbolSize to hide the symbol but display the labels

---

packages/backend/package.json
packages/backend/src/App.ts
yarn.lock

The `body-parser` package is deprecated for use with express `4.16` onwards, and replaced with methods included as part of the `express` object:
https://expressjs.com/en/api.html#express.json
https://expressjs.com/en/api.html#express.urlencoded
This PR removes `body-parser` and uses the equivalent methods instead, which are really just the same methods as included in `body-parser`: https://github.com/expressjs/express/blob/master/lib/express.js#L78

chore: remove deprecated body-parser use

---

packages/backend/src/scheduler/SchedulerWorker.ts

Closes: 
Context: 
We refactored the standalone scheduler to be inside a class. 
In this class we create a SchedulerWorker and `await worker.run()`. 
The problem is that this promise is never resolved.

fix: scheduler worker health endpoints

---

packages/frontend/src/hooks/tableVisualization/useTableConfig.ts

Closes: 
There is an infinite loop when the table has custom labels or other customization for the columns. 
Before:
https://github.com/lightdash/lightdash/assets/9117144/1768d7ab-2d42-4c42-88f5-fad1bb1a70fb
after:
https://github.com/lightdash/lightdash/assets/9117144/1b6ac224-ba77-47ea-8167-8c7adea929b2

fix: table infinite loop

---

packages/frontend/src/features/comments/components/DashboardTileComments.tsx
packages/frontend/src/features/comments/hooks/useScrollToDashboardCommentViaSearchParam.ts
packages/frontend/src/features/notifications/components/DashboardCommentsNotifications.tsx

Closes: #9048
Uses `scrollTo` with refs and then animates the icon for a few seconds. 
Scrolling only happens when dashboard and comments data has been settled.
Note:
I tried to use Mantine's hook `useScrollIntoView` but it wouldn't work as expected: 
- ref would be identified successfully 
- scrolling would work great
- **but**, the grid wouldn't render - I think `react-grid-layout` might have some CSS visibility in place that ignores whatever Mantine is using for scrolling. I guess it's good that with vanilla JS we achieve what we want
https://github.com/lightdash/lightdash/assets/7611706/3f9530ac-cd36-4c80-a27e-f7583073e3e7

feat: scroll to comment when notification clicked

---

packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx

Closes: #9029 
Allow viewers to set filters that were 'any value' to null or not null.

fix: allow interactive viewers setting filter operator to isNull and not null

---

packages/backend/src/services/ServiceRepository.ts
packages/backend/src/services/services.ts

Closes: #9248
Expands `ServiceRepository` to support:
- Memoizing services
- Accepting service providers to override service instantiation
Nothing actually changes as far as how things work with this change, it just allows us to complete the last remaining steps of the milestone.

chore: Add service override support, OperationContext, service memoization

---

packages/frontend/src/components/DashboardTiles/TileBase/index.tsx

- Fixes charts belonging to dashboard not wrapping the title
- Fixes hiding and showing again the title caused not expanding on hover
https://github.com/lightdash/lightdash/assets/22939015/b486b5e5-ffb6-4a20-ae13-1c00207cf7cd

fix: fixes title wrapper hover for charts in dashboards

---

packages/backend/src/models/ProjectModel/ProjectModel.ts

Closes:  https://github.com/lightdash/lightdash/issues/9273
Fixes: 
>     2024-03-07 10:51:31 [Lightdash] error: Unable to copy content on preview error: insert into "spaces" ("created_at", "created_by_user_id", "is_private", "name", "project_id", "search_vector") values ($1, $2, $3, $4, $5, $6) returning * - cannot insert a non-DEFAULT value into column "search_vector"

fix: duplicate preview vector issue

---

packages/backend/src/models/CommentModel/CommentModel.ts
packages/backend/src/models/NotificationsModel/NotificationsModel.ts
packages/backend/src/services/CommentService/CommentService.ts

Closes: #8998
Users who have also commented in a tile should also be notified when there's a new comment.
If, on the newest comment, there's a tag to user X, don't send an extra notification to user X (just the tag one will be sufficient).
There are now 2 types of messages for comments notifications: 
- tagged
- non-tagged (interacted?)

feat: notify people in thread without mentions as well

---

packages/backend/src/App.ts
packages/backend/src/SchedulerApp.ts
packages/backend/src/controllers/authentication.ts
packages/backend/src/database/seeds/development/01_initial_user.ts
packages/backend/src/services/services.ts
packages/backend/src/services/tsoaServiceContainer.ts

Closes: #9247 
Based on #9304, will rebase after merge.
Moves further along the process of introducing `ServiceRepository` + removing direct references to service singleton instances.
- Updates `App` to instantiate `ServiceRepository`
- Updates `SchedulerApp` to instantiate `ServiceRepository`
- Uses the App's own instance across `express`, `passport`, and `tsoa`
- `passport` and `tsoa` access the shared instance via the express request (`req.services`) or via factory functions
- Deprecates the `serviceRepository` singleton, which is currently used only from within a knex seed file.
Keyword to force frontend e2e tests:
test-frontend

chore: share `ServiceRepository` instance from `App`/`SchedulerApp`

---

packages/common/src/utils/filters.ts
packages/common/src/utils/formatting.ts
packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx

Closes: #8942
This ensures that `value` depends on `valueFormat` 
Also changed the `moment` usage with `dayjs` 
When `valueFormat` is processed, then `value` is assigned to its value but parsed 
Tested when locally I'm in San Francisco - this is related to the issue reported, where the value of the input wasn't matching the day selected on the date calendar input + the time input below
Then in London

fix: ensure date time picker inputs are all in sync

---

packages/common/src/types/filter.ts
packages/common/src/utils/filters.ts
packages/frontend/src/components/DashboardFilter/FilterDashboardTo.tsx
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/SimpleTable/DashboardCellContextMenu.tsx

Closes: #9179 
- Uses table name and field name in `FilterDashboardTo` component

fix: use table and field names for FilterDashboardTo component

---

packages/backend/src/App.ts
packages/backend/src/SchedulerApp.ts
packages/backend/src/services/ServiceRepository.ts

Allows configuring service providers within `ServiceRepository` when creating an `App` or `SchedulerApp` instance.

chore: allow passing serviceProviders during App/SchedulerApp instancing

---

packages/frontend/src/components/ProjectConnection/DbtForms/AzureDevOpsForm.tsx

The Branch and Path names would be set to the same value. This is now fixed and addresses issue #9133
Closes: #9133 
This commit changes the property used for the input field from ```branch``` to ```project_sub_path``` enabling the correct creation of new projects as well as the update of existing ones with Azure DevOps.

fix: AzureDevOpsForm when creating new projects

---

packages/e2e/cypress/e2e/app/settings/profile.cy.ts

Closes: 
Profile e2e test was flaky since the form was only populated once we were typing the new values.
Example where it has a mix of David and Kevin.
We also had a warning about chaining clearing and typing methods.
I added an instruction to make sure the form is populated and split clearing and typing instructions.

chore: stabilize profile e2e test

---

packages/frontend/src/mantineTheme.ts

Closes: #9321
The default `font-family` for the editor is `'Monaco', 'Menlo', 'Ubuntu Mono', 'Consolas', 'source-code-pro', monospace`.
Monaco font causes cursor to be off the current character.
- Removes 'Monaco' from the editor `font-family`
Before:
https://github.com/lightdash/lightdash/assets/22939015/d9fdffec-e25a-4222-aaf2-e208605b289b
After:
https://github.com/lightdash/lightdash/assets/22939015/706b8f26-94e4-45ea-ae47-e185457a3443

fix: remove Monaco from font-family for ace-editor

---

packages/backend/src/models/SpaceModel.ts
packages/backend/src/services/CommentService/CommentService.ts
packages/backend/src/services/DashboardService/DashboardService.test.ts
packages/backend/src/services/DashboardService/DashboardService.ts
packages/backend/src/services/GitIntegrationService/GitIntegrationService.ts
packages/backend/src/services/PinningService/PinningService.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/SavedChartsService/SavedChartService.ts
packages/backend/src/services/SchedulerService/SchedulerService.ts
packages/backend/src/services/SearchService/SearchService.ts
packages/backend/src/services/SpaceService/SpaceService.ts
packages/backend/src/services/ValidationService/ValidationService.ts

Closes: 
We were fetching all the org users when checking the user space access. The more users an org has the slower the query was. Since we checked the space access in most endpoints, it was slowing down the entire app.
Changes:
- filter query by user uuid
- move user table join to be first to optimize query filtering + fix sequencial scans in following joins
- removed logic that removes user access on get
- remove space access call in scheduler
The only places where we still fetch all the org members access are for:
- get space endpoint
- deprecated endpoint `/spaces-and-content` 
Force frontend e2e test:
test-frontend

fix: user space access query

---

packages/frontend/src/components/common/Filters/FilterInputs/FilterStringAutoComplete.tsx

Closes: https://github.com/lightdash/lightdash/issues/9278
This is an easy fix as it's a built in Mantine prop. Also, I added a gap between options because it looked ugly if two or more options were selected under each other.
Before:
After:

fix: clear search on option select

---

packages/backend/src/analytics/LightdashAnalytics.ts

Closes: 
Goal: allow to have other events but not allow to override existing events.
Example of a new event that is not part of this repo
```
type BananaEvent = BaseTrack & {
event: 'banana.deleted';
userId: string;
properties: {
organizationId: string;
bananaId: string;
};
};
this.analytics.track<BananaEvent>({
userId: user.userUuid,
event: 'banana.deleted',
properties: {
organizationId: user.userUuid,
bananaId: userUuid,
},
});
```
Example of a new event that tries to override an event in this repo. It throws an error.
```
type BadUserUpdatedEvent = BaseTrack & {
event: 'user.updated';
userId: string;
properties: {
organizationId: string;
bananaId: string;
};
};
this.analytics.track({
userId: user.userUuid,
event: 'user.updated',
properties: {
organizationId: user.userUuid,
bananaId: …
```

chore: analytics untyped events

---

packages/common/package.json
packages/common/src/index.ts
packages/common/src/utils/sanitizeHtml.test.ts
packages/common/src/utils/sanitizeHtml.ts
yarn.lock

- Introduces a new helper under `common` to sanitize user-provided HTML input/output, with a set of sane defaults.
- Adds a minimal set of sanity unit tests

feat: add sanitizeHtml utility

---

packages/common/package.json
packages/frontend/package.json

Explicitly includes `eslint-plugin-unused-imports` in the packages that depend on it.

fix: include eslint-plugin-unused-imports as dev dep in frontend, common

---

packages/backend/src/controllers/projectController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/SpaceModel.ts
packages/backend/src/routers/projectRouter.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/SpaceService/SpaceService.ts
packages/common/src/types/savedCharts.ts
packages/e2e/cypress/e2e/api/README.md
packages/e2e/cypress/e2e/api/api.cy.ts
packages/e2e/cypress/e2e/api/dashboard.cy.ts
packages/e2e/cypress/e2e/api/organizationPermissions.cy.ts
packages/e2e/cypress/e2e/api/pinning.cy.ts
packages/e2e/cypress/e2e/api/projectPermissions.cy.ts
packages/e2e/cypress/e2e/api/scheduler.cy.ts
packages/e2e/cypress/e2e/api/spacePermissions.cy.ts
packages/e2e/cypress/e2e/app/minimal.cy.ts
packages/frontend/src/hooks/useChartSummaries.ts
packages/frontend/src/hooks/useCharts.ts
packages/frontend/src/hooks/useSpaces.ts
packages/frontend/src/pages/MobileCharts.tsx
packages/frontend/src/pages/SavedQueries.tsx

Closes: 
Problem: 
The deprecated/spaces-and-content endpoint fetches all the spaces, all the charts and all the dashboards. With our changes to the space permissions, this involves more heavy queries to the database.
Changes:
- remove /spaces-and-content endpoint
- add a new endpoint `/charts` and rename the existing one to `/chart-summaries`. 
- amend all e2e tests to use /spaces or /charts or /dashboards endpoints instead

fix: remove /spaces-and-content endpoint

---

packages/common/src/compiler/translator.test.ts
packages/common/src/types/metricQuery.ts

removing metric query code which is only used in tests

chore: remove unused metric code with tests

---

packages/cli/.eslintrc.js
packages/cli/src/analytics/analytics.ts
packages/cli/src/analytics/rudder-sdk-node.d.ts
packages/cli/src/dbt/context.ts
packages/cli/src/dbt/targets/Bigquery/index.ts
packages/cli/src/dbt/targets/Bigquery/oauth.ts
packages/cli/src/dbt/templating.ts
packages/cli/src/dbt/types.ts
packages/cli/src/handlers/dbt/run.ts

Related: https://github.com/lightdash/lightdash/issues/3790
Part II of converting `any` to `unknown` in the CLI. With this PR the CLI package is now free from all `any` except one in `handlers/dbt/run.ts` which I couldn't find a proper type for. Also, the `@typescript-eslint/no-explicit-any` rule is configured to throw an error from now on.

refactor: any => unknown in CLI (Part II.)

---

packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/VisualizationConfigs/PieChartConfig/PieChartSeriesConfig.tsx
packages/frontend/src/hooks/echarts/useEchartsPieConfig.ts
packages/frontend/src/hooks/useChartColorConfig.tsx

Closes: #9297 
Changes consistent color assignment to provide higher quality mapping, via grouped+sequential assignment.
In short: colors are assigned to series respecting the order of the color palette, instead of through a hash of the identifier string.
- Null, empty strings, etc are always assigned a gray color.
- Colors are no longer assigned based on a hash of the group or identifier
- Colors are assigned following the order defined in the color palette
- If the same color has already been assigned to a group or identifier, we reuse that assignment across different charts in a dashboard
- Assignments are tracked through sub-groups, based on their underlying table/model or other grouping mechanism. This allows multiple unrelated charts to cycle through available colors in parallel.
- …

feat: consistent color mapping via sequential assignment

---

packages/cli/track.sh

Closes: #9314 
Inform macOS users on `xcrun` requirement on pre-install of lightdash CLI
Error message:

chore: inform macos requirement of xcrun

---

packages/backend/src/controllers/organizationController.ts
packages/backend/src/controllers/userController.ts
packages/backend/src/database/seeds/development/01_initial_user.ts
packages/backend/src/database/seeds/development/02_saved_queries.ts
packages/backend/src/overrideUserPassword.ts
packages/backend/src/routers/headlessBrowser.ts
packages/backend/src/services/CsvService/CsvService.test.ts
packages/backend/src/services/DashboardService/DashboardService.test.ts
packages/backend/src/services/HealthService/HealthService.test.ts
packages/backend/src/services/OrganizationService/OrganizationService.test.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ShareService/ShareService.test.ts
packages/backend/src/services/UserService.test.ts
packages/backend/src/services/ValidationService/ValidationService.test.ts

Closes: 
Stop importing from `models/models.ts`as we are moving the models initialization to the App class.
The only import I haven't moved in this PR is in `slackRouter` as I need to create a new service. 
Changes:
- refactored controllers/routes to use the user service instead of the user model
- create model instances inside seed files
- create model instance inside the 'overrideUserPassword.ts' script
- amended test mocks 
Following PRs:
- refactor `slackRouter` to use a service instead of a model
- move model initialization to App class

refactor: stop importing models directly

---

packages/cli/src/dbt/targets/Bigquery/index.ts
packages/cli/src/dbt/targets/snowflake.ts

Closes: #9427
- Allows `bigquery` profiles to have `schema` instead of `dataset` for CLI by passing it as `dataset` in `convertBigquerySchema`

fix: allow schema in profiles.yml for bigquery

---

docs/docs/references/roles.mdx
docs/src/css/custom.css
packages/backend/src/services/ProjectService/ProjectService.ts
packages/cli/src/handlers/createProject.ts
packages/cli/src/handlers/deploy.ts
packages/cli/src/handlers/preview.ts
packages/common/src/index.ts

Closes: #9378
- Updates the docs on who can create project previews.
- Adds info panel about project previews' content to docs
- Displays CLI warning when content wasn't copied
Before with `editor`, `developer`, `interactive viewer`
CLI:
Backend:
After with `editor`, `developer`, `interactive viewer`
CLI:

fix: show warning on content not copied on dev previews

---

packages/frontend/src/components/NavBar/DashboardExplorerBanner.tsx
packages/frontend/src/components/NavBar/MainNavBarContent.tsx
packages/frontend/src/components/NavBar/PreviewBanner.tsx
packages/frontend/src/components/NavBar/index.tsx
packages/frontend/src/components/common/Page/Page.tsx
packages/frontend/src/pages/Explorer.tsx

Closes: #7531 #8364
When users were editing charts from dashboards, they would see an issue with the Page layout where the Explorer sidebar and the whole `Page` seemed cropped. 
The reason why this is happening currently if because: 
- the main nav bar behaves one way, has specific height, styling, etc
- the blue banner that we render when `editing charts from dashboards` is a different component, with less of the styling we apply to the main nav bar
Instead of replacing the `Navbar` completely when that's the case, we can just render different content inside the same component.
What was done: 
- Created separate components for: `main nav bar content`, `dashboard explorer banner`, and the `preview banner`
- On the `index.tsx` of `NavBar`, we have now a Nav bar chooser hook, that controls …

fix: navbar layout issues

---

.gitignore
dangerfile.ts

Follow-up to: #9428 
- Allows for repo or local dangerfiles just by creating `dangerfile.repo.ts` or `dangerfile.development.ts` files in the root of the repo.
- `dangerfile.development.ts` is excluded via `.gitignore`

chore: add support for local/repo dangerfile checks

---

dangerfile.ts

Allows checks to access the dangerfile `danger` global without importing the `danger` module (which is not possible to do from within repo or development dangerfiles).

chore: pass danger utils to danger checks

---

packages/common/src/utils/email.ts

Closes: 
I was just testing account invite/signup flow and noticed that icloud is not in the common email domains list.
that list is not ideal and I hope new auth flow fixes the issue associated with "claiming a brand domain name" problem

fix: add icloud to email provider list

---

packages/e2e/cypress/e2e/api/dashboard.cy.ts

Closes: 
These tests sometimes fail because we save all the dashboard tiles in parallel so we shouldn't rely on the order of the tiles array. 
Updated the test to find the correct tile instead.

chore: fix race condition in dashboard test

---

examples/full-jaffle-shop-demo/dbt/models/events.yml
packages/common/src/index.mock.ts
packages/common/src/index.test.ts
packages/common/src/index.ts

Closes: #9298 
After this: https://github.com/lightdash/lightdash/issues/8094, we've removed the `date granularity` from the date group labels on the x axis, but we don't respect the `label` set on the yml.
This PR uses proposal 2, which originally was: 
`Use date label only (e.g. Order created) - and if no label specified, then just generate the friendly name` in https://github.com/lightdash/lightdash/issues/9298#issuecomment-2003813784. 
What this PR does is: 
- if it's in a `group`, then check its `timeInterval`, and display the `label` without the `time interval`
- if the `time interval` - for any reason - is invalid, then use the friendly name
I'm open to suggestions on doing this differently... 
This is an example `axisItem`:
```json
{
"sql": "DATE_TRUNC('DAY', …
```

fix: display label and if so remove time interval

---

packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.test.ts
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: #9368 #9379 
There were a few bugs around reference lines when multiple series were involved. If you had a reference line on the **first** series in your chart, and that line was outside of the range of the data in that series, we were setting the entire chart's range to that reference line (either min or max). Any other series' values above or below the range wouldn't show. 
This fix changes `getMinAndMaxReferenceLines` to take an array of series to find the min and max values across all of the series, not just the first one. There's a note in the review about the core problem. The rest of the code here is just supporting the notion of checking the range of all of the series. 
I'll list the repro steps here, but the main thing to test is that charts aren't broken. Try multi …

fix: reference lines breaking axis ranges

---

packages/e2e/cypress/e2e/app/settings/profile.cy.ts
packages/frontend/src/components/UserSettings/ProfilePanel/index.tsx

this is something I observed recently and confirmed flakyness locally...
main changes are:
- tests waits for the input boxes to be enabled - they are in disabled state when loading the data
- how form handles setting and resetting default (initial) form state
other changes are cosmetic and using some of the [best practices from cypress 
](https://docs.cypress.io/guides/references/best-practices)

fix: flaky e2e profile test

---

packages/backend/src/routers/projectRouter.ts
packages/backend/src/services/DashboardService/DashboardService.ts
packages/backend/src/services/SavedChartsService/SavedChartService.ts
packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/components/common/ResourceView/ResourceActionHandlers.tsx
packages/frontend/src/components/common/modal/ChartDuplicateModal.tsx
packages/frontend/src/components/common/modal/DashboardDuplicateModal.tsx
packages/frontend/src/hooks/dashboard/useDashboard.ts
packages/frontend/src/hooks/useSavedQuery.ts
packages/frontend/src/pages/Dashboard.tsx

Closes: https://github.com/lightdash/lightdash/issues/9280
Added a modal for charts and dashboards to be able to edit the `name` and `description` before duplicating. For this I had to modify the backend serivices too (`SavedChartService`, `DashboardService`) and the corresponding hooks since they did not take the necessary parameters on the request. Tested manually.
[Screencast from 2024-03-12 22-01-05.webm](https://github.com/lightdash/lightdash/assets/30611343/a37d9854-520c-4769-b7c9-be74c315640e)

feat: show modal before chart, dashboard duplication

---

packages/frontend/src/components/Explorer/ExplorerHeader/index.tsx
packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/components/Explorer/index.tsx

Closes: #9435 
Move CTAs to Chart header when on view mode
https://github.com/lightdash/lightdash/assets/7611706/5cbfa9bd-64c6-40f1-8dbb-17ac417777cf

feat: move ctas in view mode saved chart

---

packages/frontend/src/features/users/components/LoginLanding.tsx

Closes: #9501 
In the case where the user is know and they are automatically re-directed, we were not showing loading spinners while waiting for the redirect. Also, the button text was changing and it shouldn't

fix: missing spinner when automatically logged in

---

packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/BasicSeriesConfiguration.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/SingleSeriesConfiguration.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/index.tsx
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts
packages/frontend/src/hooks/useChartColorConfig.tsx

- Cleans up temporary code introduced during the color mapping changes
- Makes color fallback behavior more reliable, and fixes some edge cases around sorting, removing and re-adding series.
Note that this change is not directly related to color mapping (though it uses some of the same code).
- Ensures re-ordering series preserves the "original" color (as well as manually set colors as before)
- Ensures removing and re-adding a series works, and picks up the correct fallback color (this fixes an issue where colors were sticky, and removing a series and re-adding it would re-add it with the old color, which may no longer be in the correct position)
- Works across different chart types

fix: improve behavior when ordering non-grouped series, cleanup temporary color assignment code 

---

packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNode.tsx

Closes: #9408
Uses `HoverCard` instead of Popover and adds a small `openDelay`
https://github.com/lightdash/lightdash/assets/7611706/30ee295b-c41d-4325-a838-8a288a20db66

feat: use hovercard instead of popover

---

packages/frontend/src/components/SimpleStatistic/index.tsx

fix: bignumber context menu position

---

packages/backend/src/models/DashboardModel/DashboardModel.ts
packages/common/src/utils/sanitizeHtml.test.ts
packages/common/src/utils/sanitizeHtml.ts
packages/frontend/src/components/DashboardTiles/TileForms/MarkdownTileForm.tsx
packages/frontend/src/components/DashboardTiles/TileForms/TileAddModal.tsx
packages/frontend/src/components/DashboardTiles/TileForms/TileUpdateModal.tsx

- Extends `sanitizeHtml` to support a ruleset as an argument
- Adds a new ruleset specifically for markdown tiles (which supports iframes and a subset of attributes)
- Updates the dashboards router (backend) and the tile forms (frontend) to pre-process input

fix: preprocess markdown tile content (backend/frontend)

---

packages/frontend/src/components/ChartDownload.tsx
packages/frontend/src/components/DownloadSqlCsvButton/index.tsx
packages/frontend/src/components/Explorer/ResultsCard/ResultsCard.tsx
packages/frontend/src/components/common/CollapsableCard.tsx

Closes: #9430 
Uses `ActionIcon` and creates a new var for Action Icon props, since the `size` has to be `md`, instead of `xs`.
Before
After

style: reduce export chart results icon size

---

packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceUserList.tsx

Closes: #9553 
Before a space admin could not edit another space admin access.
Now it can
(inherited admins still can't be changed)
If we try to edit a org/project admin to another role we should throw an error.

fix: space admins can update other space admins access

---

packages/backend/src/services/SpaceService/SpaceService.ts

Closes: #9555 
Before we show an error when we try to remove the last user with direct access from a space. Even though there are org/project admins with inherited access.
Now we can remove them. We don't need this check as there will always be an org admin with access.

fix: can remove all users access from space

---

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx

Closes: #9549 
Show "explore from here" button to interactive viewers.
Before:
After:

fix: show explore from here button to interactive viewers

---

packages/frontend/src/components/Explorer/ExploreTree/index.tsx
packages/frontend/src/mantineTheme.ts

Closes: #9551
Fixed by overriding the `viewport`'s child element `display` value from `table` to `block`. Couldn't find a selector with higher specificity than the inline styling that radix x Mantine apply to the `viewport`'s child
https://github.com/lightdash/lightdash/assets/7611706/05a144cd-f58c-49fb-84cd-799c7e451877

fix: apply viewport child block display

---

packages/backend/src/database/migrations/20240329095412_modify_user_uuid_fk_in_dashboard_tile_comments.ts

Closes: N/A
Some users would get this error when deleting another user that had left dashboard comments
```
error: delete from "users" where "user_uuid" = $1 - update or
delete on table "users" violates foreign key constraint
"dashboard_tile_comments_user_uuid_foreign" on table
"dashboard_tile_comments"
```
There's a missing on delete cascade in the `user_uuid` column.
Added a migration that drops current foreign constraint and re-adds it with the on delete
Verified with `psql`
```sql
"dashboard_tile_comments_user_uuid_foreign" FOREIGN KEY (user_uuid) REFERENCES users(user_uuid) ON DELETE CASCADE
```
bug
https://github.com/lightdash/lightdash/assets/7611706/7681ecdd-b37d-480b-a7eb-c53a7d561b30
fix
https://github.com/lightdash/lightdash/assets/7611706/ea2a964d-7104-43fe-8856-07527cf1db5a

fix: add migration to add delete cascade

---

packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationSidebar.tsx

Closes: N/A
Now that the saved chart header is shorter, we should also fix the offset height of the visualization Drawer
This also refines the logic and utilizes constants where possible.
Tested this with every possible scenario
1. preview-edit-chart-within-dashboard
2. preview-create-chart-within-dashboard
3. preview-saved-chart
4. preview-query-from-tables
5. edit-chart-within-dashboard
6. create-chart-within-dashboard
7. query-from-tables
8. saved-chart

style: fix vertical offset vis sidebar

---

packages/frontend/src/components/Explorer/CustomMetricModal/index.tsx
packages/frontend/src/components/Explorer/CustomMetricModal/utils/index.ts

Closes: https://github.com/lightdash/lightdash/issues/7759
This PR fixes the issue with custom metrics, where they are too long , 
this fix should be backwards compatible and straightforward, we are just making a shorter name for the custom metric. 
it doesn't fix the max column name on dbt, that will require a bigger fix
I'm using 64 as the max limit because that's the lowest limit (from postgres) , other database have higher limits.  
Before and after

fix: custom metric long name

---

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLine.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLines.tsx

Closes: N/A
Use `index` instead of referenceLine's `data.value` to fix this issue: https://lightdash.sentry.io/issues/5131175770/?project=5959292&referrer=slack
`Accordion.Item`s will break if their `value` attribute value is not correct.

fix: reference line accordion item index

---

packages/frontend/src/hooks/usePieChartConfig.ts

Closes: #9613 
Steps to reproduce:
1. Create a pie chart with a custom metric
2. Remove the metric from the results table
3. Click run query

fix: return empty data if metric doesn't exist in results for pie chart

---

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/BasicSeriesConfiguration.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/SingleSeriesConfiguration.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/common/EditableText.tsx

Relates to: #9528 
- Spacing on `Series`- see `Show symbol` checkbox that had a missing margin left
- `EditableText` - show placeholder if no value set - it goes back to default value on the chart visualisation so let's keep that.

feat: address remaining bits on chart config ui changes

---

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Axes/AxisMinMax.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Axes/index.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Layout/index.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLines.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/index.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/BasicSeriesConfiguration.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/common/Config.tsx

Closes: N/A
From discussion here: https://github.com/lightdash/lightdash/pull/9528#discussion_r1546580576
Rework the `Config` component to have its _sub-components_ with clearer namings
```
Config.Section - was Config.Group before
Config.Heading - was Label before
Config.Group - was GroupLabel before
Config.Label - was SubLabel before
```

refactor: rework Config component

---

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx

Fix a small issue with return to dashboard tooltip
Before
After

fix: return to dashboard tooltip overflow

---

packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx

Closes: N/A
To reproduce: 
- Go to a dashboard ([internal dashboard](https://analytics.lightdash.cloud/projects/21eef0b9-5bae-40f3-851e-9554588e71a6/dashboards/7fa4c980-f9ad-43ca-9a7c-31ef15ae8c49/view))
- Click on `disabled` filter
- Search for a result (has to be a long list, that goes above the max limit - currently 100 for us) 
**Now use your keyboard**
- Select value with `Enter` key
- Press `Escape`
- Click `Apply`
- Filter does not get _enabled_
This PR uses the `hasFilterValueSet` util to check if a filter has a value set depending on its operator & type.
How I replicated this locally: 
seeded `raw_payments.csv`
```csv
130,99,cash,901
131,97,mobile_payment,455
132,92,mobile_payment,1543
133,98,cash,1985
134,97,mobile_payment,232
135,94,cash,1046
136,93,check,1266
137,99,check,1295 …
```

fix: handle disabled filter change correctly

---

packages/backend/src/services/CsvService/CsvService.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/featureFlags.ts
packages/common/src/types/filter.ts
packages/common/src/utils/filters.mock.ts
packages/common/src/utils/filters.test.ts
packages/common/src/utils/filters.ts

Relates to: #7268
Introduces a feature flag to let dashboard filters override the chart filter if they have the same target field. 
https://github.com/lightdash/lightdash/assets/9117144/0a89e223-4ba0-4536-9621-ecb15d3fd779

feat: override chart filters with dashboard filters

---

.github/workflows/test-and-build.yml
package.json

Prevents issues around missing github tokens. `pull_request_target` is a better way to achieve this, but this way is easier if we want to reuse the existing project setup.
Checks if `GITHUB_TOKEN` is set when running `danger-ci-lint`

chore: run dangerjs for internal PRs only

---

packages/backend/src/config/parseConfig.test.ts
packages/backend/src/config/parseConfig.ts

- Allows any configuration value to be (optionally) represented as `base64`, using a new utility
- Adds a minimal helper for `private_key_jwt` certificates, to use `base64` encoding for any string that doesn't look like a plain text certificate.

feat: add support for base64-encoded secrets/configuration values

---

packages/frontend/src/components/Explorer/VisualizationCard/VisualizationSidebar.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/TableConfigTabs.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/index.tsx

Closes: #9568 
Focuses on `Tabs` for table config chart
Moves `mantineTheme` to the root vis folder

feat: table chart config - tabs (1/3)

---

packages/frontend/src/components/Explorer/VisualizationCard/VisualizationSidebar.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ColumnConfiguration.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/DroppableItemsList.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/GeneralSettings.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/TableConfigTabs.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/index.tsx

Relates to: #9568 
Table config changes to `General Settings` tab
- Inputs are smaller
- Lighter droppable areas - their text inputs have a placeholder if you leave the input empty (default label)
- Grouped checkboxes by intent

feat: table chart config - general settings (2/3)

---

packages/frontend/src/components/Explorer/VisualizationCard/VisualizationSidebar.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLines.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ColumnConfiguration.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingItem.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingList.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingRule.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/DroppableItemsList.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/GeneralSettings.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/TableConfigTabs.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/index.tsx
packages/frontend/src/components/VisualizationConfigs/common/hooks/useControlledAccordion.tsx

Relates to: #9568 
Table config changes to `Conditional Formatting` tab
Single colour
Range
- Inputs are smaller
- Color selects are different depending on mode
- It's an accordion now
- Different UI when adding more and more conditions

feat: table chart config - conditional formatting (3/3)

---

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Layout/index.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLine.tsx

Relates to: #9409
Adds `hasGrouping` to `FieldSelect`s in cartesian chart config

feat: enable field grouping in cartesian chart config

---

packages/frontend/src/components/VisualizationConfigs/PieChartConfig/PieChartLayoutConfig.tsx

Relates to: #9409
Adds `hasGrouping` to `FieldSelect`s in pie chart config

feat: enable field grouping in pie chart config

---

packages/frontend/src/components/VisualizationConfigs/BigNumberConfig/BigNumberLayout.tsx

Relates to: #9409
Adds `hasGrouping` to `FieldSelect`s in big number chart config

feat: enable grouping on field select in big number config

---

packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingItem.tsx

Closes: #9409
Adds `hasGrouping` to `FieldSelect`s in table config

feat: enable grouping on field select in table config

---

packages/frontend/src/components/Explorer/ExploreTree/TableTree/ItemDetailPreview.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNode.tsx
packages/frontend/src/mantineTheme.ts
packages/frontend/vite.config.ts

Closes: #9502 
Makes markdown preview popovers look more like regular tooltips.

feat: make markdown previews look more like standard tooltips

---

packages/common/src/compiler/exploreCompiler.ts

Closes: #9691
Fixes table alias resolution so that it behaves consistently across contexts, particularly when resolving aliased joins.
This is achieved by allowing table name references to be resolved via `name` or `originalName` fields for aliased references.

fix: table alias not always correctly resolved during compile

---

packages/backend/src/models/UserModel.ts
packages/backend/src/services/UserService.test.ts
packages/backend/src/services/UserService.ts

Closes: 
Question: Is it possible to have 2 existing open_id types linked to the same primary email ? if so we should do the filter in the getOPenIdIssuer model method, or return all (instead of first) and filter them later

fix: only use enabled openid issuers

---

packages/common/src/types/featureFlags.ts
packages/frontend/src/pages/Dashboard.tsx
packages/frontend/src/pages/MinimalDashboard.tsx

Closes: #9655
- Introduces a new feature flag (`DashboardMobileVerticalStack`)
- Refactors `getResponsiveGridLayoutProps` to accept options based on the feature flag above
- If the feature flag is enabled, stacks tiles vertically (single column) on the smallest (mobile) breakpoint.
Before:
After (same dashboard):

fix: force chart tiles into a vertical stack in mobile minimal view

---

packages/frontend/src/components/Explorer/ResultsCard/QuickCalculations.tsx

Closes: #9703
Follow the same convention for sorted field IDs on the BE by wrapping the `fieldId` in the quick calculation `sorts` with the fieldquotechar - dependant on warehouse

fix: quick calculation order bys quote char

---

packages/common/src/utils/filters.ts
packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx
packages/frontend/src/components/common/Filters/FilterRuleForm.tsx
packages/frontend/src/components/common/Filters/index.tsx

Closes: #9667
The issue: 
- When _invalid_ filters (no longer available) are in `Filters` card, we display a message `tried to reference...` 
- This doesn't apply when there's a Filter group - the component doesn't handle it at the moment (see `FilterGroupForm`)
The solution for this is to: 
- Get valid and invalid filter rules in the parent: `FiltersForm` (see Filters/index.ts)
- Improve: `getFilterRulesByFieldType` to return also invalid filters
- Use the invalid filters and render the same component in `FiltersForm` - the parent of  `FilterRuleForm`
Demo: 
https://github.com/lightdash/lightdash/assets/7611706/e815e51f-11d9-4df4-89c9-1bf116ead35a

fix: get invalid filters and allow deletion even in groups

---

docs/package.json
docs/yarn.lock

Closes:  https://github.com/lightdash/lightdash-internal-work/issues/1644
Upgrade trim on docs package to 1.0.1, This package is a dependency from docusaurus, 
Tested locally and in https://deploy-preview-9708--peaceful-bassi-cbf284.netlify.app/ It all looks good

fix: upgrade trim package docs

---

packages/common/src/utils/formatting.test.ts
packages/common/src/utils/formatting.ts

Closes: #4707 #9536
Apply string formatting to `YEAR_NUM` dimension type.
Happy to discuss other ways of improving this (or call it in `formatNumberValue` but that requires passing new arg `item`)
Before:
see screenshots from issues ⬆️ 
After:

fix: treat YEAR_NUM formatting as string

---

docs/docs/references/joins.mdx
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/queryBuilder.ts
packages/common/src/compiler/exploreCompiler.mock.ts
packages/common/src/compiler/exploreCompiler.test.ts
packages/common/src/compiler/exploreCompiler.ts
packages/common/src/compiler/translator.ts
packages/common/src/dbt/schemas/lightdashMetadata.json
packages/common/src/schemas/json/lightdash-dbt-2.0.json
packages/common/src/types/dbt.ts
packages/common/src/types/explore.ts

Closes: [#6693](https://github.com/lightdash/lightdash/issues/6693)
- Adds `always` field to `yaml` joins
- Always join the table when `always` is `true`
**Before**
**After**
- With `always: true`
- With `always: false`
https://github.com/lightdash/lightdash/assets/22939015/5a8d3059-812e-4939-b3ec-cebdabd10a32

feat: allow to always join a table

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/featureFlags.ts
packages/common/src/types/projects.ts
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Closes: #7459 
Sets `QUOTED_IDENTIFIERS_IGNORE_CASE` for Snowflake based on a feature flag. The goal is to roll this over to be true by default, but the feature flag gives us some room to deal with possible unintended consequences.
See the linked ticket for more context.

feat: Set `QUOTED_IDENTIFIERS_IGNORE_CASE = FALSE` for Snowflake via feature flag

---

packages/frontend/src/hooks/useChartColorConfig.tsx

Closes: #9710
- Color mapping groups are now suffixed with its number of groups if >1 (e.g `order_status_n2.shipped`) to improve serial color assignment when switching chart groups, by preventing different combinations of groups from taking colors from a single color pool.
- All pivot values are considered when building color mapping identifiers, so all permutations of groups are assigned a unique color (e.g `[shipped - <some other metric>]` is no longer the same color as just `[shipped]`)

fix: improve color assignment for charts with multiple groups

---

packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx

Closes: #9734
pass `withinPortal: true` to `FiltersProvider` in `FilterCard` - we do that in Dashboard filters as well - was just missing here
before
https://github.com/lightdash/lightdash/assets/7611706/9b7db2c2-15d3-494b-a54d-09fe885319e1
after
https://github.com/lightdash/lightdash/assets/7611706/52cca399-6e2d-49a8-b64d-cefaf1b7aed8

fix: add withinPortal to FiltersProvider in card

---

.github/ISSUE_TEMPLATE/bug_report.yml

On the issue report form, makes the description field a textarea (like remaining fields) instead of a single line input. The single line input is awkward to write in (particularly since most useful descriptions will be a couple of lines, or at least a longer single line), and doesn't currently show the full placeholder text.
Field in question as it is now (and the second field is what it'll look like instead):

chore: make bug report description field a textarea

---

packages/backend/src/clients/Google/GoogleDriveClient.ts
packages/backend/src/scheduler/SchedulerTask.ts

Closes: [9682](https://github.com/lightdash/lightdash/issues/9682)
Adds report URL to meta tab for Charts' google sheets syncs

feat: add report URL to charts' google syncs

---

docs/docs/references/sql-variables.mdx
docs/docs/references/user-attributes.mdx
packages/backend/src/queryBuilder.mock.ts
packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/user.ts

Closes: [#6955](https://github.com/lightdash/lightdash/issues/6955)
- Allows to reference  user intrinsic attributes in `filters` and `join` on clauses via `${lightdash.user.<attribute>}`
- Available attributes are - `email`, `first_name`, `last_name`
- join `sql_on`
- models `sql_filter`

feat: allow intrinsic user attributes

---

packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx

Filters lost their max width and now grow infinitely. This adds a max width.

fix: add max width on dashboard filters

---

packages/common/src/types/featureFlags.ts
packages/frontend/src/pages/MinimalDashboard.tsx

Removes feature flag code for `DashboardMobileVerticalStack`, which is no longer necessary.

chore: Remove feature flag code for DashboardMobileVerticalStack

---

packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
packages/frontend/src/components/DashboardTiles/TileForms/MoveTileToTabModal.tsx

Closes: #9827
Closes: #9657 
Changes:
- Only show option to move tab when there are multiple tabs available.
- Don't show current tab as an option.
- Disable button until they select a tab

fix: only show option to move tab when there are multiple tabs available

---

packages/common/package.json
packages/common/src/index.ts
packages/common/src/transformers/README.md
packages/common/src/transformers/ResultTransformers/AbstractResultTransformer.ts
packages/common/src/transformers/ResultTransformers/ExplorerResultsTransformer.ts
packages/common/src/transformers/ResultTransformers/index.ts
packages/common/src/transformers/VizConfigTransformers/AbstractVizConfigTransformer.ts
packages/common/src/transformers/VizConfigTransformers/Cartisean/AbstractCartiseanConfigTransformer.ts
packages/common/src/transformers/VizConfigTransformers/Cartisean/BarConfigTransformer.ts
packages/common/src/transformers/VizConfigTransformers/Table/TableConfigTransformer.ts
packages/common/src/transformers/VizConfigTransformers/VizConfigTransformerFactory.ts
packages/common/src/transformers/VizConfigTransformers/index.ts
packages/common/src/transformers/VizLibTransformers/AbstractVizLibTransformer.ts
packages/common/src/transformers/VizLibTransformers/LibTransformer.mock.ts
packages/common/src/transformers/VizLibTransformers/Table/TableTransformer.test.ts
packages/common/src/transformers/VizLibTransformers/Table/TableTransformer.ts
packages/common/src/transformers/VizLibTransformers/Vega/VegaTransformer.test.ts
packages/common/src/transformers/VizLibTransformers/Vega/VegaTransformer.ts
packages/common/src/transformers/VizLibTransformers/VizLibTransformerFactory.ts
packages/common/src/transformers/VizLibTransformers/index.ts
packages/common/src/transformers/index.ts
packages/frontend/package.json
yarn.lock

Closes: 
Transformer classes + docs
This directory contains classes that are used to transform the data between each layer of the application.
At the moment there are 3 types of transformers:
-   **Results**: Transforms data related the query and results
-   **Viz configuration**: Validates, manages and transforms the viz configuration
-   **Viz library**: Transforms the viz configuration into a viz library specific configuration
The viz configuration and viz library transformers instances should **ONLY** be created via their factory.
To render a visualisation, you need to chain all the transformers together. Here is an example of how to do it:
```typescript
const results = {}; // this would be the data from the backend after running a query (explore/sql runner/semanticlayer)
// Create a …
```

chore: transformers

---

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/hooks/pinning/useChartPinningMutation.ts
packages/frontend/src/hooks/pinning/useDashboardPinningMutation.ts
packages/frontend/src/pages/Dashboard.tsx
packages/frontend/src/pages/SavedExplorer.tsx

Closes: [#9782](https://github.com/lightdash/lightdash/issues/9782)
- Allows pinning dashboard from the dashboard page
- Allows pinning chart from the chart page, doesn't display this option for dashboard charts
https://github.com/lightdash/lightdash/assets/22939015/21bd5d3c-c4f0-46ca-8cad-13f7086dd13c

feat: allow pinning from chart and dashboard pages

---

packages/backend/src/models/ResourceViewItemModel.ts

This started happening after https://github.com/lightdash/lightdash/pull/9418/files#diff-97f739a09ecb82dabeb72908a35fe8e622e4d81c213616bc90df3a38d065e23f got merged. we stopped returning `chartType` as `chartKind` in the queries + handling of the frontend icons now used `chartKind` which this endpoint didn't return.
Before:
After:

fix: wrong chart icon in pinned list

---

packages/backend/src/queryCompiler.ts
packages/common/src/compiler/exploreCompiler.ts
packages/common/src/compiler/translator.ts
packages/common/src/types/explore.ts

Closes:  https://github.com/lightdash/lightdash/issues/9726
Generate a mapping with all the joins tables and aliases so we can evaluate the alias in the dimension reference method 
This PR is only fixing the specified issue with nested joins , alias and sql metric. There are other scenarios that are not covered on this PR , like dimensions, user attributes, etc. THe approach should be similar to this fix though. 
Before
After:

fix: fix joined table with aliases in metric

---

packages/frontend/src/components/DashboardTabs/index.tsx

Closes: 
[9832](https://github.com/lightdash/lightdash/issues/9832)
fix: 
- update all tiles with default tile uuid when first time creating tabs.
- rename "Remove Tab" to "Remove Tabs Component" when only one tab exists.
- delete tab directly instead of opening a modal when deleting last tab.

fix: Delete last tab should not delete tiles

---

packages/common/src/compiler/filtersCompiler.ts
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: #9885 
For table calculations return numeric type as the default

fix: incorrect default table calc type

---

packages/frontend/src/components/DashboardTabs/index.tsx

Closes: 
issue:
this error would happen when delete last tab:
and that's happening because the tab uuid referenced in the tiles is gone.

fix: fix foreign key constraint error when delete last tab

---

packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx

Closes: 
steps to reproduce:
1.  create a saved chart - c1
2. create a dashboard and add tabs to dashboard - d1
3. click "add to dashboard"  from saved chart
4. then you get the error

fix: fix foreign constraint error when add chart to dashboard

---

packages/cli/src/handlers/deploy.ts

Closes: 
Makes sure the Project Name passed in the CLI is trimmed, avoiding any whitespace in the project name that can cause trouble with managing the project.

fix: trim project name whitespace on CreateProject

---

packages/common/src/utils/filters.ts

Closes: #9840 
- Keeps filter settings when overriding chart filter
Date filter value was being overridden but the settings weren't. Because of this the chart filter's `unitOfTime` was kept the same and wasn't overridden with the dashboard filter one
**Before**
https://github.com/lightdash/lightdash/assets/22939015/c09105e0-3a96-4fb9-922a-9d157c2fe61a
**After**
https://github.com/lightdash/lightdash/assets/22939015/51d47f10-93eb-4acd-b41a-1489c6780964

fix: keep identical filter settings if they exist when overriding

---

.github/workflows/create-sentry-release.yml
.github/workflows/release-on-merge.yml

Closes: #9918 
When `release-on-merge` is successful, and when there's a new version created, then trigger a new workflow: `Create Sentry release` to: 
- build frontend assets
- create Sentry release with `getsentry/action-release@v1` https://github.com/marketplace/actions/sentry-release
- push sourcemaps to that release

feat: create sentry release and publish sourcemaps

---

examples/full-jaffle-shop-demo/dbt/models/schema.yml
packages/common/src/types/field.ts

Closes: #9779, 
Formatting was getting skipped for some metrics defined in yml because they were being treated as table calculations. Our isTableCalculation check is pretty fragile, but I made it a little better to fix this. I added a check for displayName, which is only on table calculations for now. But if someone adds that field to another Item type this could break. Ideally we'd have a fieldType field on all of these types, but it's missing on TableCalculation. I tried adding it there to fix this, but it's not backwards compatible -- any existing table calculations won't have it. So I checked displayName for now. 
I added a model-level metric to test this. 
1. Create a chart
2. add orders.completion_percentage. If it's displayed as a percent this should be working.

fix: missing formatting in model level metrics

---

.github/workflows/release-on-merge.yml

Relates to: #9932 
After fixing that step, got an issue with dispatching the workflow here: 
https://github.com/lightdash/lightdash/actions/runs/8895669590/job/24426516663
error
```
Run curl -X POST \
curl -X POST \
-H "Authorization: token ***" \
-H "Accept: application/vnd.github.v3+json" \
-d '{"event_type": "sentry-release", "client_payload": {"version": "0.1079.[2](https://github.com/lightdash/lightdash/actions/runs/8895669590/job/24426516663#step:9:2)", "environment": "production"}}' \
https://api.github.com/repos/lightdash/lightdash/actions/workflows/create-sentry-release.yml/dispatches
shell: /usr/bin/bash -e {0}
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 …
```

fix: use github ci token

---

.github/workflows/create-sentry-release.yml
.github/workflows/release-on-merge.yml

Relates to: #9918 
After this error: https://github.com/lightdash/lightdash/actions/runs/8897910487/job/24433880988
```
Run curl -X POST \
curl -X POST \
-H "Authorization: token ***" \
-H "Accept: application/vnd.github.v3+json" \
-d '{"event_type": "sentry-release", "client_payload": {"version": "0.1081.1", "environment": "production"}}' \
https://api.github.com/repos/lightdash/lightdash/actions/workflows/create-sentry-release.yml/dispatches
shell: /usr/bin/bash -e {0}
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   334  100   [2](https://github.com/lightdash/lightdash/actions/runs/8897910487/job/24433880988#step:9:2)30  100   104 …
```

fix: use correct dispatch params to trigger sentry release workflow

---

.github/workflows/create-sentry-release.yml
.github/workflows/release-on-merge.yml

Relates to: #9918 
Uses `gh` cli to help with posting the workflow dispatch. Tested this locally and was able to trigger this run: https://github.com/lightdash/lightdash/actions/runs/8907197505/job/24460632498 - with this error I found that we should also build `common` before building `frontend`.
Use this as reference: https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event
and this: https://josh-ops.com/posts/gh-auth-login-in-actions/

fix: use gh cli and build common before frontend

---

packages/backend/src/services/DashboardService/DashboardService.ts

Closes: 
issue:
steps to reproduce:
1. created a tabbed dashboard
2. create a new tab
3. create a 'new chart' tile in the new tab
4. duplicate the dashboard

fix: fix tile insert error when duplicate tabbed dashboard

---

packages/backend/src/services/UnfurlService/UnfurlService.ts
packages/common/src/types/featureFlags.ts

Closes: #9962
See ticket description for more detail
Adds feature flag `puppeteer-disconnect-browser`
Closes `page` and disconnects from `browser` instead of closing the browser if that FF is enabled.

fix: disconnect browser instead of closing (feature flag)

---

packages/backend/src/services/CsvService/CsvService.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/featureFlags.ts
packages/common/src/utils/filters.mock.ts
packages/common/src/utils/filters.test.ts
packages/common/src/utils/filters.ts

Closes: https://github.com/lightdash/lightdash-internal-work/issues/1680
Applying breaking change that was announced it here:
https://changelog.lightdash.com/breaking-change-dashboard-filters-will-now-apply-to-all-matching-tiles-by-default-274972
This breaking change as been active in cloud but not for self hosted users. This PR is the final work to remove the old behaviour.

feat: dashboard override chart filters

---

packages/cli/src/dbt/targets/Bigquery/serviceAccount.ts

Closes: 
Some users experiencing errors `Error: error:1E08010C:DECODER routines::unsupported` when using env vars in their dbt profile.
This thread explains why this may happen and how to fix it. 
https://stackoverflow.com/questions/74131595/error-error1e08010cdecoder-routinesunsupported-with-google-auth-library

fix: replace escaped newlines in credentials values

---

packages/frontend/src/components/common/modal/ChartCreateModal/SaveToSpaceOrDashboard.tsx

Closes: 
issue:
steps to reproduce:
1. created a tabbed dashboard
2. go back to home page and click "Run Query"
3. create a chart 
4. click "save chart"
5. choose tabbed dashboard

fix: fix add saved chart to tabbed dashbord from explore view error out

---

packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Closes: #8480
If user provides `password` then the `authenticator` method is `SNOWFLAKE` - the default
If the user provides a `decodedPrivateKey`, then it should use `SNOWFLAKE_JWT`

fix: use snowflake user and password if provided

---

packages/common/src/utils/filters.test.ts
packages/common/src/utils/filters.ts
packages/common/src/utils/item.ts

Closes:  #9965
Have a chart with a date ìs` filter
IF I try to override on the dashboard: 
Before: (it creates 2 filters) 
After:

fix: override operator dashboard filter

---

packages/backend/src/App.ts

Closes: N/A
Initialise Sentry before any other express handlers/middleware
```
The Sentry request handler middleware must be added before any other handlers
app.use(Sentry.Handlers.requestHandler());
```
From the guide here: https://docs.sentry.io/platforms/javascript/guides/express/

fix: init sentry before express handlers

---

packages/common/src/utils/timeFrames.ts
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: #3621 
The goal of this is to make data line up with the axis labels and ticks better when looking at WEEK timeframe data. 
To do this, I made the week-timeframe use a categorical axis, which gives much more control over axis styles and such. The downside of the categorical axis is it's not continuous -- it doesn't fill holes where there is no data. To handle this, I found the min and max weeks and made the x-axis always a continuous range between them. 
This does a good job of lining up the bars with the ticks, but more could still be done about overlapping labels. 
This is what a week-based chart (with gaps in the data) looked like before:
And here's what it looks like with this change

feat: align x-axis ticks with data

---

packages/backend/src/models/SchedulerModel/index.ts
packages/backend/src/scheduler/SchedulerClient.ts

Closes:  https://github.com/lightdash/lightdash/issues/9994
We were creating the job, but didn't add the `scheduled` job status , so if the scheduler was busy, we were trying to fetch a missing job log from the job id
This PR ensures we create the `scheduled` job log on `send now`
Before:
After:

fix: fix missing scheduled job error

---

packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/services/HealthService/HealthService.mock.ts
packages/backend/src/services/HealthService/HealthService.test.ts
packages/backend/src/services/HealthService/HealthService.ts
packages/common/src/index.ts
packages/frontend/src/components/NavBar/HelpMenu.tsx
packages/frontend/src/providers/ThirdPartyServicesProvider.tsx
packages/frontend/src/testing/__mocks__/api/healthResponse.mock.ts

Closes: https://github.com/lightdash/lightdash-internal-work/issues/1651 
Changes:
- add new env vars
- pass app id and verification hash to frontend
- init pylon if needed
- show pylon chat instead of intercom if initialized
Note:
- We still show intercom chat if pylon chat is not available
- Keep intercom in login and verification pages as Pylon doesn't support chat when user is not authenticated.
How to test:
1. pull branch locally
2. update `HelpMenu.tsx` to have `{isCloudCustomer || true && (`
3. set env vars

feat: pylon chat

---

packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: #10003 
Fixes adding an extra week at the end when filling gaps in the week axis. 
Oops. 
Repro:
- Make a chart with weeks on the x-axis. There will be a repeated week at the end.

fix: extra week added in week chart axis

---

packages/common/src/types/field.ts
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: #9967 
Apply formatters to table calculations. We were skipping formatting because they aren't considered fields. I think these days they are more like fields and we *could* clean up some of these checks. But I think this is the right fix for this bug.

fix: apply formatting to table calculations in axes

---

packages/common/src/utils/filters.ts
packages/frontend/src/components/common/Filters/index.tsx

Closes: #10008
The simplified filters form update function was always de-structuring the root filter groups into the new filters.
Since root filters can now be OR type, it would mean that we could end up with a root filter group having both `and` and `or`. The fix was to remove the de-structuring and just add the rules for the simplified form in a AND group - note: the simplified form only shows when theres only 1 filter rule or there's no subgroups, so it can always be AND in that case.
Before:
https://github.com/lightdash/lightdash/assets/22939015/412dcdf4-e8fc-46b7-8f0e-311c337761b5
After:
https://github.com/lightdash/lightdash/assets/22939015/0b2436bd-bf34-4ca6-a6a7-327162c1f533

fix: don't destructure root filter groups as they can be 'any' now

---

packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
packages/frontend/src/components/NavBar/BrowseMenu.tsx
packages/frontend/src/components/NavBar/ExploreMenu.tsx

Closes: #9974 
There were some z-Index issues on dashboard while charts were loading. Here is a before and after
**Before**
**After***

fix: zIndex issues on dashboard while loading

---

packages/frontend/src/hooks/useBigNumberConfig.ts

Closes: #10018
new table calculations now have types, but existing table calculations has type as undefined. For undefined table calculations, we assume they are strings (for backwards compatibility) but this assumption is not correct on bignumber.
Before:
After:
For strings: 
(new check type) For table calculation with `string` type:

fix: fix undefiled type table calculation on bignumber

---

packages/frontend/src/components/MetricQueryData/UnderlyingDataModalContent.tsx

Closes: #10006 
Apply dashboard filters to view underlying query. 
We were leaving out filters on fields that weren't part of the chart display. 
To test:
- Apply a new filter to a dashboard
- View underlying data on a chart in the dashboard that is affected by the filter
- Make sure the new filter is reflected in the underlying data query

fix: apply dashboard filters to underlying data query

---

packages/frontend/src/components/DashboardFilter/FilterConfiguration/TileFilterConfiguration.tsx

Closes: 
This should revert the select all logic for no tabs, and fix the e2e test

fix: add select all if no tabs

---

packages/backend/src/services/CsvService/CsvService.ts
packages/backend/src/services/ProjectService/ProjectService.ts

Closes: 
Amend csv download and total calculation endpoints to check custom SQL dimension permission.

fix: sql dimension permission on csv download and total calculation

---

packages/common/src/utils/formatting.ts
packages/common/src/utils/item.ts
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: 
Results table and viz where not recognising the custom dimension type.
before:
after:
before:
after:

fix: custom dimension value type

---

packages/common/src/utils/sanitizeHtml.test.ts
packages/common/src/utils/sanitizeHtml.ts

Closes: #9976
Adds support for common text styling/formatting CSS properties, with basic value validations, as part of the `sanitize-html` configuration. This is applied only for sanitization with the markdown tile rule-set.
Updates the existing `sanitizeHtml` utility test suite to match!

feat: allow common properties for text styling in markdown tile html tags

---

packages/frontend/src/pages/Dashboard.tsx

Closes: #10039
- Saving a dashboard chart from "Explore from here" was overwriting the current tiles in the dashboard
**Before**
https://github.com/lightdash/lightdash/assets/22939015/60779288-2a8c-45e6-aa35-f719ae65cdb5
**After**
https://github.com/lightdash/lightdash/assets/22939015/0efb879f-149c-455f-b1b3-7b274956bfc4

fix: dashboard chart from explore from here deleted all current dashboard tiles

---

packages/backend/src/queryBuilder.mock.ts
packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts

Closes: 
Add quotes to the custom dimension alias so the warehouses (usually snowflake) don't return column as uppercase in the results. 
Before:
```
(month("users".user_created_at)) AS month,
```
After
```
(month("users".user_created_at)) AS "month",
```

fix: custom sql dimension alias

---

packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts

Closes: 
adds "include errors" arg and specs to `getAllExploresSummary`

feat: add "include errors" arg to all explores summaries

---

packages/frontend/src/pages/Dashboard.tsx

Reverts lightdash/lightdash#10058
Kicking off this revert so it's ready to roll out if we dont have a better answer.

fix: Revert "fix: dashboard chart from explore from here deleted all current dashboard tiles"

---

packages/frontend/src/components/ExploreFromHereButton/index.tsx

Closes: #10039
Steps:
- Click on chart from dashboard in dashboard
- Click explore from here
- Should not see banner (you are creating/editing/viewing chart from dashboard)
Before this change, users were seeing that banner when exploring from here on chart within a dashboard.

fix: clear dashboard storage before explore from here

---

packages/frontend/src/components/common/modal/ChartCreateModal/index.tsx

Closes: #10084
We lost the functionality here: https://github.com/lightdash/lightdash/pull/5669 with all the changes to mantine + `history` pushes. The search param would get discarded so it wouldn't be defined when the user opened the chart creation modal
Demo of this working: 
https://github.com/lightdash/lightdash/assets/7611706/3a51db57-c5ff-487a-ab49-0613e2023b9a

feat: show space in select if adding to space

---

packages/frontend/src/components/DashboardTiles/TileBase/index.tsx

Disables the explore link in dashboard tile titles when editing a dashboard. When linking out we can't keep dashboard state and it's easy to lose dashboard changes. This makes it so users have to finish editing to explore.

fix: disable chart link while editing dashboard

---

packages/common/src/compiler/exploreCompiler.ts
packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeProvider.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNode.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/index.tsx
packages/frontend/src/components/Explorer/ExploreTree/index.tsx

Closes: #10066 
https://github.com/lightdash/lightdash/assets/22939015/9206e91f-ac3f-4bba-9ffa-b3f323e466db

fix: display missing custom metrics and dimensions

---

packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: #9983 
while trying to debug found out that filter function was causing the issue removed it and it is working fine. 
**Before**
**After**

fix: tooltip fix for horizontal bar

---

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLine.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLines.tsx

Closes: #10060 
Treats un-typed table calculations as numeric for the purposes of reference lines. 
We could consider having the check within isNumericItem, but we have to clean filters up to handle that correctly.

fix: reference lines break for tables calculations with no type

---

packages/frontend/src/components/NavBar/NotificationsMenu/index.tsx
packages/frontend/src/components/SettingsValidator/index.tsx
packages/frontend/src/hooks/validation/useValidation.ts

Closes: (https://github.com/lightdash/lightdash/issues/9327)
Fix the project validation details request if the user does not have permission to do so. I've figured out how it's validated on the Backend. Based on this. I've validate the user on the Frontend before making the validation request.

fix: avoid requesting validation endpoint when no permission

---

packages/common/src/types/featureFlags.ts
packages/frontend/src/components/DashboardTabs/index.tsx
packages/frontend/src/pages/Dashboard.tsx
packages/frontend/src/providers/ThirdPartyServicesProvider.tsx

Reverts changes added in: https://github.com/lightdash/lightdash/pull/7876
Removes feature flag check for `lazy-load-dashboard-tiles`.
Removes lazy loading from dashboard tiles
Re-ran a dashboard and all is OK

chore: remove lazy loading from dashboard tiles

---

packages/common/src/utils/filters.ts
packages/common/src/utils/item.ts
packages/frontend/src/components/Explorer/ResultsCard/CellContextMenu.tsx
packages/frontend/src/components/SimpleTable/DashboardCellContextMenu.tsx

Closes: #10096
Steps to reproduce: 
- have empty dates on a csv for the seed data
- try to filter to/by on an explore or on a dashboard
- it breaks the explore (see ticket with the Sentry replay)
Fix for a chart
https://github.com/lightdash/lightdash/assets/7611706/dd1a4a23-ab5b-48e3-b70f-76c7e132230c
Fix for a dashboard
https://github.com/lightdash/lightdash/assets/7611706/51bbbdfc-6d29-4892-8e39-681a2aa85ec3

fix: handle filter bys for invalid dates/empty

---

packages/frontend/src/components/Explorer/CustomDimensionModal/CustomBinDimensionModel.tsx

Closes: #10124 
Removed `and under` from first line range since it will be `< x`, not `<= x`

fix: remove and under from first custom dim range

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/CatalogService/CatalogService.ts
packages/common/src/types/catalog.ts
packages/frontend/src/features/catalog/components/CatalogGroup.tsx
packages/frontend/src/features/catalog/components/CatalogPanel.tsx

Makes:
- Catalog page show tables by default
- Api return table groups
- Scrolling within page height

chore: default catalog page to tables, add groups

---

docs/docs/guides/dbt-semantic-layer.mdx

Removes "self-hosted" section in dbt semantic layer docs since we don't offer dbt semantic layer to self-hosted users. 
This confused some users.

docs: removes dbt semantic layer from self-hosted docs

---

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx

Closes: #10128
Treats time-based field values in the chart series config as UTC. There was an issue where the series config display wasn't matching the chart formatted values. 
The semantics here aren't great--the variable set to 'true' is called convertToUTC, and this it more treating them as utc, but it solves the problem. 
Before
After

fix: use utc time display in series config

---

packages/frontend/src/components/DashboardTabs/index.tsx
packages/frontend/src/components/DashboardTiles/AddTileButton.tsx
packages/frontend/src/components/DashboardTiles/EmptyStateNoTiles/index.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/hooks/dashboard/useDashboardStorage.tsx
packages/frontend/src/pages/Dashboard.tsx

Closes: 
issue:
when creating a tab without save it and then create a "dashboard chart" for this tab, it will be redirected to chart creation page and when the process finished and navigate back to the dashboard page, previously created tab would gone.
https://github.com/lightdash/lightdash/assets/101873365/2e034dca-6b58-419b-9bb0-7a9b0637cc0e

fix: save temp dashboard tabs to session storage when creating new chart

---

packages/frontend/src/components/Explorer/CustomDimensionModal/CustomSqlDimensionModal.tsx
packages/frontend/src/features/tableCalculation/components/TableCalculationModal.tsx

Closes: #10107
This also checks TCs when creating/editing a custom SQL dimension. Followed the issue's steps to replicate it.
Fix:
https://github.com/lightdash/lightdash/assets/7611706/e3fee4fd-7134-4827-bfe5-d35b243a5c98
Side note:
I also looked at `CustomBinDimensionModal` but the code below wouldn't cause an issue unless the TC was named with the same name and prefixed with the base table for the custom Bin dimension. 
Leaving this here if we want to add it in the future. I believe this is unrelated to the issue that the ticket raised though.
```ts
const customDimensionName = sanitizeId(
label,
isEditing && isCustomDimension(item)
? item.dimensionId
: item.name,
);
if (
isEditing &&
isCustomDimension(item) &&
customDimensionName === item.id
) {
return null;
}
const tableCalculationsIds …
```

fix: check against tcs when creating custom sql dim

---

packages/frontend/src/components/DashboardTiles/TileBase/index.tsx

Closes: 
issue:
"move to another tab" option is not available for the chart that only belongs to dashboard
fix:
https://github.com/lightdash/lightdash/assets/101873365/9d40af28-e572-4851-a711-422e9610fe42

fix: allow new charts to be moved around tabs

---

packages/frontend/src/components/Explorer/CustomDimensionModal/CustomSqlDimensionModal.tsx
packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/index.tsx
packages/frontend/src/components/Explorer/ExploreTree/index.tsx
packages/frontend/src/providers/ExplorerProvider.tsx

Closes: [#10108](https://github.com/lightdash/lightdash/issues/10108)
Gets `tables` in `explore` to check if there's a missing custom dimension (and also additional metric)
Followed the steps to replicate this. 
Also tried the following: 
- Create 2 custom dims (one in orders, the other one in payments)
- Edited one at a time, just the name. Edit again (you should edit it 2x!)
- Saw false missing fields in one, where there was an issue with the editing of custom sql dimensions. That is fixed now - to do with the `edit_custom_metric` action and the value received by the payload
When getting the **missing** custom dimensions, I did the calculation on the `ExplorePanel` to utilise a previous computation for `missingFields` - that way we avoid adding more loops. 
Now, the structure for …

fix: check correctly missing custom dimensions against explore's tables

---

packages/common/src/types/featureFlags.ts
packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx

Closes: [#10057](https://github.com/lightdash/lightdash/issues/10057)
Removes feature flag `CustomSqlDimensions` `custom-sql-dimensions`
Adds small tooltip on hover of `+ Add`

chore: remove custom dimension sql feature flag

---

docs/docs/guides/how-to-create-custom-fields.mdx

splits out the way to create custom dimensions in the custom dimensions doc (since binning and custom SQL are created differently)

docs: split out `how to create custom dimensions` 

---

docs/docs/get-started/setup-lightdash/connect-project.mdx

Updates trino connection docs to include information about how we only support LDAP authentication. Also adds more detail on the required fields for setup.

docs: update Trino connection docs

---

packages/frontend/src/components/common/ShareShortLinkButton/index.tsx
packages/frontend/src/hooks/useAsyncClipboard.tsx

Closes: [#10148](https://github.com/lightdash/lightdash/issues/10148)
When dealing with async operations to retrieve text to then copy to clipboard, Safari blocks this operation because it doesn't consider it a direct user action: on click -> API call -> copy to clipboard. Since there's an API in the middle of the process, that is then blocked by Safari. 
Found this blog post that explained it nicely: https://wolfgangrittner.dev/how-to-use-clipboard-api-in-firefox/
And also it mentions this safari thread with the solution: https://developer.apple.com/forums/thread/691873
Also added a custom hook `useAsyncClipboard` which covers both major browsers: Chrome Firefox and Safari. 
> [!NOTE]  
> I checked other places in the code where we use `useClipboard` - and these are only used for …

fix: allow safari to copy to clipboard on async values

---

packages/frontend/vite.config.ts

- Fixes slack `request_url` verification when in `dev` mode

fix: route slack/events to backend

---

packages/common/src/index.ts
packages/common/src/types/savedCharts.ts
packages/frontend/src/components/Explorer/FiltersCard/useFieldsWithSuggestions.ts
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Axes/AxisMinMax.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Axes/index.tsx
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: #9814
https://github.com/lightdash/lightdash/assets/7611706/49a88ceb-dab1-431f-b259-3076cb56afad
Requirements: 
- Only for x axis
- Only for bar charts, **not** horizontal
- Only for visualizations of type `value` on the x axis (basically, a numeric value like 0, 1, 2)
Adds `minOffset` and `maxOffset` to type `Axis`
User can set this offset when setting x-axis range to manual. 
The value set by default is `0.5` (-0.5 on the left and +0.5 on the right)
When the inputs (for max or min) are set to empty, then we apply the data min and data max from the `rows` data. If the user overrides to their own, the calculations are applied.
To replicate:
Locally:
- Go to `Tracks` table
- Select Timestamp month
- Select Event count
- Create table calculation, with this: ` …

fix: allow setting offset to avoid bars overlapping/falling outside of range

---

packages/frontend/src/components/common/Page/Page.tsx
packages/frontend/src/components/common/Page/Sidebar.tsx
packages/frontend/src/hooks/useSidebarResize.ts

Relates to: #10130 
Adds `rightSidebar` to `Page`
Allows `Sidebar` to take a position - can be `right` or `left`
Ensures that the `useSidebarResize` hook can take a `position` arg so resizing works well. 
Adds a temporary example in `Catalog` to showcase how this works. 
https://github.com/lightdash/lightdash/assets/7611706/29ec9957-e9f5-4361-9440-edc1c544c869

feat: add right sidebar to page component

---

packages/frontend/src/components/CustomVisualization/index.tsx

Closes: #10199 
Turns off the actions menu in custom visualizations. It's possible there should be an option to turn it back on, but the main request is to turn it off and it's not clear it adds value at the moment.
This removes this button/menu:

feat: disable custom viz actions

---

packages/common/src/types/catalog.ts
packages/frontend/src/features/catalog/components/CatalogFieldListItem.tsx
packages/frontend/src/features/catalog/components/CatalogMetadata.tsx
packages/frontend/src/features/catalog/components/CatalogPanel.tsx
packages/frontend/src/features/catalog/components/CatalogTree.tsx

Closes: #10210
Makes fields selectable and fixed up keyboard navigation to move across groups and tables. @rephus suggested this should make the same metadata requests as the containing table, so that's what it does. For now it doesn't display any field metadata specifically, just highlights the field in the table metadata. We can update the metadata view to show field data. 
**Note:** one main limitation here is that with keyboard navigation, selections do not scroll into view. I played with it some and I the scroll setup seems like it will sufficiently complex that we should add this once we have that finalized more.

chore: make fields selectable

---

packages/frontend/src/features/catalog/components/CatalogMetadata.tsx
packages/frontend/src/features/catalog/components/CatalogPanel.tsx
packages/frontend/src/features/catalog/context/CatalogProvider.tsx
packages/frontend/src/features/catalog/hooks/useCatalogAnalytics.ts
packages/frontend/src/features/catalog/hooks/useCatalogMetadata.ts
packages/frontend/src/pages/Catalog.tsx

Closes: #10130 
Finalises the work on the right sidebar POC by adding the `CatalogMetadata` as the `rightsidebar` of `Page` component. 
This also introduces a `CatalogProvider` to help with the content display of a sidebar when interacting with the `CatalogPanel`.
When there's a table selected, it will store its value in the provider, along with its analytics
**NOTE**: I still need to check more usecases on scrolling behaviour, but that should be only assessed after the UI polish work incoming for the table.
https://github.com/lightdash/lightdash/assets/7611706/36802d1c-aa39-4eb7-b5e9-de1aaac155da

feat: add metadata to right sidebar

---

packages/backend/src/services/UserService.mock.ts
packages/backend/src/services/UserService.test.ts
packages/backend/src/services/UserService.ts

Closes: 
How to replicate: 
- set env var `ALLOW_MULTIPLE_ORGS=false` 
- register new user with email X
- see error "Cannot register user in a new organization. ..." and do **NOT** click to cancel registration
- login with demo user
- invite user with email X
Before: 
They would get the error:
After:
user is invited
Added unit tests to cover invite logic:
- should create user and send invite when email is not found
- should send invite when email belongs to user without org
- should send invite when email belongs to inactive user in same org
- should throw error when email belongs to user in different org
- should throw error when email belongs to an active user in same org

fix: invite user without org

---

packages/backend/src/models/SavedChartModel.ts
packages/backend/src/services/ValidationService/ValidationService.mock.ts
packages/backend/src/services/ValidationService/ValidationService.test.ts
packages/backend/src/services/ValidationService/ValidationService.ts

Before: 
| Step  | Queries | Real example - 426 charts and 106 dashboards |
| ------------- | ------------- |------------- |
| Get explores  | 1  | 1 |
| get tables configuration  | 1  | 1 |
| get chart summaries  | 1  | 1 |
| get chart (n = number of charts)  | 7 * n  | 2982 |
| get dashboard summaries  | 1  | 1 |
| get dashboard (n = number of dashboards)  | 4 * n  | 424 |
|  |  | 3411 |
Now: 
| Step  | Queries | Real example - 426 charts and 106 dashboards |
| ------------- | ------------- |------------- |
| Get explores  | 1  | 1 |
| get tables configuration  | 1  | 1 |
| get charts  | 1  | 1 |
| get dashboard summaries  | 1  | 1 |
| get dashboard (n = number of dashboards)  | 4 * n  | 424 |
|  |  | 428 |
This PR is only fixing the charts queries by stop fetching all the chart data …

fix: reduce amount on queries needed to validate charts

---

packages/backend/src/models/CatalogModel/utils/parser.ts
packages/backend/src/services/CatalogService/CatalogService.ts
packages/common/src/types/catalog.ts
packages/e2e/cypress/e2e/api/catalog.cy.ts

Closes: #10200
We apply the same filtering logic from explores?filtered=true
I filtered on table selection `generated_b` but not `generated_a`
Table
Search table 
Filter fields from generated_b on search

fix: filter table selection

---

packages/frontend/src/components/DashboardTabs/index.tsx

Closes: 
issue:
when switching tab previously temp filter value is gone, later when sharing the link temp filter value is not copied to the link which would be miss leading.
https://github.com/lightdash/lightdash/assets/101873365/8361b367-9c98-4701-81c8-de9f37d59f9f

fix: add search params when switching tab

---

packages/frontend/src/components/common/Page/Page.tsx
packages/frontend/src/components/common/Page/Sidebar.tsx
packages/frontend/src/hooks/useSidebarResize.ts
packages/frontend/src/pages/Catalog.tsx

Relates to: https://github.com/lightdash/lightdash/issues/10193
adds `withFitContent` to `Catalog` Page
Ensures the siderbar resize respects `mainWidth` and stops it from increasing if we've reached the min width of `main` (600 atm)
Applies a wider page width on the panel when there's a `withRightSidebar`
Demo:
https://github.com/lightdash/lightdash/assets/7611706/913d5adc-a857-4a37-aebc-165b341681e1

style: improve right sidebar resize and fit page

---

packages/frontend/src/features/catalog/components/CatalogAnalyticCharts.tsx

Closes: N/A
Before we were separating charts and charts within dashboards on the analytics tab
Now we render them on the same list, but we keep the sorting that was applied before. This probably needs revisiting. 
Question: 
Do we want to sort charts first by space, then inside by type?
- chart 1 (space A)
- chart 2 (space A)
- chart 3 (space A) (dashboard X)
- chart 4 (space B) (dashboard Y)
- chart 5 (space C)
- chart 6 (space C) (dashboard Z)
Before: 
After:

fix: merge charts in analytics and display breadcrumb if within dashboard

---

docs/docs/references/dimensions.mdx

Removes `group_label` from `dimensions reference` doc and adds `groups` instead

docs: Update dimensions.mdx to include `groups` instead of `group_label`

---

packages/frontend/src/features/catalog/components/CatalogFieldListItem.tsx
packages/frontend/src/features/catalog/components/CatalogTableListItem.tsx
packages/frontend/src/features/catalog/components/CatalogTree.tsx

Relates to: https://github.com/lightdash/lightdash/issues/10193
Made the `CatalogFieldListItem` an  `unstyled` button
Added a transparent border to it regardless of it being selected or not - helps with content jumping when selecting/de-selecting
Added some spacings necessary for making it look nicer
Added temporary styles/icons to fields that are dimensions or metrics. This will change soon once I get @PriPatel 's new assets. 
Before
After

style: initial catalog field styling

---

packages/frontend/src/features/catalog/components/CatalogGroup.tsx
packages/frontend/src/features/catalog/components/CatalogMetadata.tsx
packages/frontend/src/features/catalog/components/CatalogPanel.tsx
packages/frontend/src/features/catalog/components/CatalogTableListItem.tsx
packages/frontend/src/features/catalog/hooks/useCatalogMetadata.ts
packages/frontend/src/pages/Catalog.tsx

Closes: N/A
Instructions to review this PR: 
- Go to: https://www.notion.so/lightdash/To-do-batch-1-8e64d5610dc9408ea02aecd32d8f7b30
- Follow each step and there's a commit attached to each comment (except for the last [chore: re-style close button](https://github.com/lightdash/lightdash/commit/bd21f8fab6d0301f726c878ebe8c6589ca7b294b)) which is fix after the changes applied
If the commits aren't sufficient I'm happy to go through each step together/split into smaller PRs
One **NOTE**
- [style: add close button to CatalogMetadata](https://github.com/lightdash/lightdash/commit/47b07c42f1119634851c4b0e3b9a354c9237bf11)
See changes here ^ I'm positive we should only handle the **close event** which will set the `selection` to `undefined`, close the sidebar, and reset the `metadata`. LMK what …

style: address styling catalog feedback

---

packages/frontend/src/components/MetricQueryData/MetricQueryDataProvider.tsx

Closes: #10221 
For `null` values we pass the formatted value since echarts won't render them correctly otherwise. See more about bug here: https://github.com/apache/echarts/issues/15821
So when handling the echarts event we change it back to `null`.
https://github.com/lightdash/lightdash/assets/9117144/df263424-324e-4bfd-8d68-4b93b43ef176

fix: underlying data with null filter

---

packages/frontend/src/features/catalog/components/CatalogMetadata.tsx
packages/frontend/src/features/catalog/components/CatalogPanel.tsx

Closes: N/A
We could start opening the sidebar before waiting for the data to be returned. 
Added a temporary loading overlay (I'm sure this is being worked on a separate ticket)
This uses `useTransition` and we apply it to: 
- when we store the metadata
This unblocks the UI thread while the processing is happening 
Displays a loading indicator on the usage analytics + on the whole metadata sidebar
Demo: 
https://github.com/lightdash/lightdash/assets/7611706/46010d77-2c53-43d0-94a4-fea078aa595b

fix: defer state when opening metadata sidebar

---

packages/backend/src/models/DashboardModel/DashboardModel.ts
packages/backend/src/services/ValidationService/ValidationService.mock.ts
packages/backend/src/services/ValidationService/ValidationService.test.ts
packages/backend/src/services/ValidationService/ValidationService.ts

Continuing optimizations to our validation process. First one was https://github.com/lightdash/lightdash/pull/10226
**Note** there is bug validating charts that belong to a dashboard: https://github.com/lightdash/lightdash/issues/10253
Before: 
| Step  | Queries | Real example - 426 charts and 106 dashboards |
| ------------- | ------------- |------------- |
| Get explores  | 1  | 1 |
| get tables configuration  | 1  | 1 |
| get charts  | 1  | 1 |
| get dashboard summaries  | 1  | 1 |
| get dashboard (n = number of dashboards)  | 4 * n  | 424 |
|  |  | 428 | 
Now: 
| Step  | Queries | Real example - 426 charts and 106 dashboards |
| ------------- | ------------- |------------- |
| Get explores  | 1  | 1 |
| get tables configuration  | 1  | 1 |
| get charts  | 1  | 1 |
| get dashboards  | …

fix: reduce amount of queries necessary to validate dashboards

---

packages/frontend/src/components/common/Filters/FilterGroupForm.tsx

Closes: #10132 
We now create a group with the opposite operation of the parent group. This avoid the group from being flatten automatically.
https://github.com/lightdash/lightdash/assets/9117144/bfbd91ae-74e2-4cc9-b10d-ac2e5c120867

fix: create new group with opposite operator

---

packages/backend/src/App.ts
packages/frontend/src/hooks/thirdPartyServices/useSentry.ts

Closes:[ #1764](https://github.com/lightdash/lightdash-internal-work/issues/1764)
Sets `tag` `organization` for Sentry requests on BE and FE
On BE I triggered an exception and it includes the tags: 
```
[backend]   tags: {
[backend]     transaction: 'GET /api/v1/health',
[backend]     organization: '172a2270-000f-42be-9c68-c4752c23ae51'
[backend]   },
```
On FE I can see that being set on the network tab
```
{"conte...
....
"tags":{"organization":"172a2270-000f-42be-9c68-c4752c23ae51","effectiveConnectionType":"4g","deviceMemory":"8 GB","hardwareConcurrency":"10"},"
...
```

feat: pass organization tag to sentry events

---

packages/frontend/src/features/catalog/components/CatalogTree.tsx
packages/frontend/src/pages/Catalog.tsx

Relates to: #10243 
Removed overflow-y `scroll` on `CatalogTree` wrapper
Applies it to the `Catalog`, only when the sidebar is open
Fixes first TODO in issue #10243
https://github.com/lightdash/lightdash/assets/7611706/ec180a10-1b34-414a-9054-f3759f4699ad

fix: enable overflowY scroll if sidebar open

---

packages/backend/src/App.ts
packages/backend/src/models/MigrationModel/MigrationModel.ts
packages/backend/src/services/HealthService/HealthService.ts

Closes: [#10290](https://github.com/lightdash/lightdash/issues/10290)
Triggered `Database has not been migrated yet` error. See the `after` where the event is discarded
Before 
After

chore: don't throw error for out of sync migrations

---

packages/backend/src/App.ts
packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/config/parseConfig.test.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/services/HealthService/HealthService.mock.ts
packages/backend/src/services/HealthService/HealthService.ts
packages/common/src/index.ts
packages/frontend/src/hooks/thirdPartyServices/useSentry.ts
packages/frontend/src/testing/__mocks__/api/healthResponse.mock.ts

Relates to: [#10296](https://github.com/lightdash/lightdash/issues/10296)
Closes: [#10296](https://github.com/lightdash/lightdash/issues/10296)
initially, the ticket mentioned to only allow traces sampling rate to be configurable, but I figured we would want the same for profiling in the backend.
Reads: 
```
SENTRY_TRACES_SAMPLE_RATE
SENTRY_PROFILES_SAMPLE_RATE
```
and parses them into: 
```
tracesSampleRate
profilesSampleRate
```

chore: make sentry traces and profiles sample rate configurable

---

packages/frontend/src/hooks/dashboard/useDashboardStorage.tsx

Closes: #10305 #10301
`dashboardTabs` was being set to string `"undefined"` - that's why it was throwing the toast error. This checks if there are tabs and their length is > 0 before storing them. 
with these changes:
https://github.com/lightdash/lightdash/assets/7611706/41bbd4c1-dae1-41f1-8fc5-9c8ce0c1e876

chore: check dashboardTabs before setting them in storage

---

packages/backend/package.json
packages/backend/src/scheduler/SchedulerClient.ts
yarn.lock

Closes: N/A
Increases `maxAttempts` for dashboard + image screenshot + schedulers by `1` so it's `2` now. 
Also, upgrades `puppeteer` to latest, because it includes these fixes: 
https://github.com/puppeteer/puppeteer/pull/12352
https://github.com/puppeteer/puppeteer/pull/12225
This is based on the errors we would get from logs: 
ProtocolError
`Requesting main frame too early!`

feat: increase max retries for dashboard image schedulers

---

package.json
packages/common/package.json
yarn.lock

Closes: N/A
tsx ~4... shows a faster dev mode when making changes to the `backend` and `common` packages.
Changes to `common`/`backend` are almost instant when using these with Docker. 
test-cli test-frontend test-backend

chore: upgrade tsx to 4.11.0 and use tsx for `common`

---

packages/backend/src/@types/knex-tables.d.ts
packages/backend/src/clients/Slack/SlackClient.ts
packages/backend/src/clients/Slack/Slackbot.ts
packages/backend/src/controllers/slackController.ts
packages/backend/src/database/entities/slackAuthentication.ts
packages/backend/src/database/migrations/20240606085700_add-custom-fields-to-slack-installation.ts
packages/backend/src/database/migrations/20240606085700_add-profile-photo-to-slack-installation.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/SlackAuthenticationModel.ts
packages/backend/src/services/SlackIntegrationService/SlackIntegrationService.ts
packages/common/src/types/slack.ts
packages/common/src/types/slackSettings.ts
packages/frontend/src/components/UserSettings/SlackSettingsPanel/index.tsx
packages/frontend/src/hooks/slack/useSlack.ts

Closes: [Allow customisation of bot appearance per organization](https://github.com/lightdash/lightdash-commercial/issues/229)
- Allows to change the photo used by the bot when calling PostMessage

feat: allow slack bot customization

---

packages/backend/src/models/SpaceModel.ts
packages/backend/src/services/CatalogService/CatalogService.ts
packages/backend/src/services/DashboardService/DashboardService.test.ts
packages/backend/src/services/DashboardService/DashboardService.ts
packages/backend/src/services/PinningService/PinningService.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/SearchService/SearchService.ts
packages/backend/src/services/ValidationService/ValidationService.ts

Closes: [#10347](https://github.com/lightdash/lightdash/issues/10347)
Changes:
- update query to fetch multiple spaces
- fix services to use new method
Routes fixed:
- POST /api/v1/dashboards/availableFilters
- GET /api/v1/projects/{project}/spaces
- GET /api/v1/projects/{project}/chart-summaries
- GET /api/v1/projects/{project}/charts
- GET /api/v1/projects/{project}/dashboards
- GET /api/v1/projects/{project}/pinned-lists/{list}/items
- GET /api/v1/projects/{project}/search/:query
- GET /api/v1/projects/{project}/dataCatalog/{table}/analytics
- GET /api/v1/projects/{project}/dataCatalog/{table}/analytics/{field}
- GET /api/v1/projects/{project}/validate

fix: remove n+1 query by fetching user access from multiple spaces

---

packages/frontend/package.json
packages/frontend/src/api.ts
packages/frontend/src/features/errorBoundary/components/ErrorBoundary.tsx
packages/frontend/src/hooks/thirdPartyServices/useSentry.ts
yarn.lock

Relates to: #10334 
Upgrades `@sentry/react` to v8
Removes deprecated usage of `getActiveTransaction` and uses recommended version: `startSpan` https://github.com/getsentry/sentry-javascript/blob/master/MIGRATION.md#deprecate-scopegettransaction-and-getactivetransaction uses `spanToTraceHeader(s);` instead of `span.toTraceparent(`  https://github.com/getsentry/sentry-javascript/blob/master/MIGRATION.md#deprecated-fields-on-span-and-transaction
Screenshot of API and distributed tracing enabled: 
Relevant event: https://lightdash.sentry.io/performance/trace/32b9434735144a9d85766572b02b634e/?fov=0%2C4513.7001953125&node=txn-002ffc37fe5b47d0adeb630bddd1616a&statsPeriod=30m&timestamp=1718026417
Here ⬆️  you can verify that: 
- Distributed tracing is on (you can see references to express …

chore: upgrade sentry react to v8 on frontend

---

packages/backend/package.json
packages/backend/src/otel.ts
yarn.lock

Measures event loop utilization in production.
Example locally with `OTEL_METRICS_EXPORTER=console`
```
{
descriptor: {
name: 'nodejs.event_loop.utilization',
type: 'OBSERVABLE_GAUGE',
description: 'Event loop utilization',
unit: '1',
valueType: 1
},
dataPointType: 2,
dataPoints: [
{
attributes: {},
startTime: [Array],
endTime: [Array],
value: 0.006861551882104955
}
]
}
```

feat: add node runtime ELU metric

---

packages/backend/src/services/UnfurlService/UnfurlService.ts

Closes: N/A
Get the correct selector for charts' screenshots: should be `body` instead of `[data-testid="visualization"]`
Introduced here: https://github.com/lightdash/lightdash/commit/43eb5ba11d0c51390334000e2d8be6601fc4c4fd
See how these are set in: `UnfurlService` > `parseUrl`
```
const chartUrl = new RegExp(`/projects/${uuid}/saved/${uuid}`); // will be CHART
const exploreUrl = new RegExp(`/projects/${uuid}/tables/`); // will be EXPLORE
```

fix: get body selector for playwright chart screenshots

---

packages/backend/src/App.ts
packages/backend/src/config/parseConfig.ts

Changes:
- add domain list of third party libraries/services
- support custom domains via env var
- support https iframes in markdown
- support https images in markdown
- support Lightdash to be embedded in other https websites
- support script-src eval
- support script-src-elem unsafe-inline
- support worker-src blob

fix: adjust content security policy directives

---

packages/backend/src/services/UnfurlService/UnfurlService.ts

Closes: N/A
Playwright's default timeout for `waitForResponse` is 30s - https://playwright.dev/docs/api/class-page#page-wait-for-response
Increased to 60s - some charts might take longer
Re-added the `.loading_chart` `wait`s that we already have in puppeteer - thought I didn't need this, but it increases reliability.
How to test:
1. add this to the browser connection
```ts
browser = await playwright.chromium.connectOverCDP(
browserWSEndpoint,
{
logger: {
isEnabled: (name, severity) => true,
log: (name, severity, message, args) =>
console.log(
`PLAYWRIGHT: ${name} ${message}`,
),
},
},
);
```
2. Add a delay to the `getChartsAndResults` in `ProjectService` before the return:
```ts
const delay = (ms: number | undefined) =>
new Promise((resolve) => setTimeout(resolve, ms));
if (
chartUuid === …
```

fix: increase timeout to wait for charts to 60s (playwright)

---

packages/frontend/src/hooks/useExplorerRoute.ts

Closes: #10371 
1. Click "Run a query"
2. Select a table and then some dimensions / metrics
3. Click "Run query"
4. Copy the URL from the browser
5. Paste the URL in another tab and remove the **LAST** `%7D` from the URL
**Before**
**After**

fix: handle error thrown when parsing explore params

---

packages/backend/src/services/DashboardService/DashboardService.ts
packages/backend/src/services/SavedChartsService/SavedChartService.ts
packages/common/src/index.ts
packages/common/src/types/pinning.ts
packages/e2e/cypress/e2e/api/pinning.cy.ts
packages/frontend/src/hooks/pinning/useChartPinningMutation.ts
packages/frontend/src/hooks/pinning/useDashboardPinningMutation.ts

Relates to: #10321
While pinning either a dashboard or a particular chart to the homepage, the view count increases because:
1. `getById()` method in `DashboardService.ts` and
2. `get()` method in `SavedChartService.ts`
call the following block of code, that is used to increase the views count:
```
await this.analyticsModel.addDashboardViewEvent(
dashboard.uuid,
user.userUuid,
);
```
To avoid this view count increase on `pinning/unpinning to homepage`, having a boolean value which tells whether the chart/dashboard is being pinned to homepage or not ( `isPinning` value ) helps in this case. This value will be `true` only when pinning occurs and hence will not increase the view count, the default value will be `false` if not provided otherwise. …

fix: chart and dashboard view count increase on pinning to homepage

---

packages/backend/src/services/UnfurlService/UnfurlService.ts
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts
packages/frontend/src/hooks/echarts/useEchartsPieConfig.ts

Closes: N/A
- Takes a full page screenshot for charts (to prevent a screenshot clip - DM me for an example of an internal chart that didn't work as expected)
- Removes `animation` for all `minimal` echarts 
- Forces viewport size setting on all types

fix: more playwright improvements

---

packages/frontend/src/features/users/components/LoginLanding.tsx

Closes: 
Fixes keyboard navigation in the login page. Now when email is entered and the PW box shows, the pw box will be focussed. 
Before:
After:

fix: focus password input in login page

---

packages/backend/src/database/entities/dashboards.ts
packages/backend/src/models/DashboardModel/DashboardModel.test.ts
packages/backend/src/models/DashboardModel/DashboardModel.ts
packages/common/src/types/dashboard.ts

Remove 6 n+1 queries when creating/updating a dashboard.
Changes:
- moved the loops inside the insert method to insert multiple rows in the same query.
- pre generate tile uuid to simplify queries + updated typing to require uuid.
- fix saved chart id typing to allow `null`

fix: remove n+1 queries when creating and updating a dashboard

---

packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts

Closes: 
Query all explores in 1 query (removes n+1 query)
There is a separate [tech debt ticket](https://github.com/lightdash/lightdash/issues/10384) to replace all the old model methods with the new one.
test-frontend

fix: get all explores in one query for dashboard available filters

---

packages/backend/src/models/SavedChartModel.ts
packages/backend/src/services/PromoteService/PromoteService.ts
packages/frontend/src/features/promotion/components/PromotionConfirmDialog.tsx

Closes:  https://github.com/lightdash/lightdash/issues/10370
Chart promote with space name change but no new chart version
Dashboard promote without chart changes 
No changes on chart promote 
- Dashboard don't have updated_at so we assume they are always updated (existing behaviour) 
- We only promote for charts if promotedChart.updatedAt > upstreamChart.updatedAt or name/description changes.

fix: check no_changes on promote content

---

packages/common/src/compiler/translator.ts
packages/common/src/types/field.ts

Closes: https://github.com/lightdash/lightdash/issues/10348
1. without groups
---
2. using groups and custom label
---
3. deprecated group label - 2 separate groups
---
4. one in a group - one without a group
---

fix: date dimension groups

---

packages/backend/src/clients/Slack/SlackClient.ts
packages/common/src/types/slackSettings.ts

Closes: [#257](https://github.com/lightdash/lightdash-commercial/issues/257)
Information about the new scope: https://api.slack.com/scopes/groups:read
- Allows slack app to notify and list private channels that it has been added to

fix: list private channels that the app has joined

---

packages/backend/src/App.ts
packages/backend/src/models/SavedChartModel.ts

Remove n+1 queries when saving chart.
test-frontend

fix: remove n+1 queries when saving chart

---

packages/backend/src/scheduler/SchedulerClient.ts

Closes:  #10429
Now we automatically disable some schedulers that are throwing non retriable , so we're throwing more errors of this type.
Before:
Now:
``

fix: do not add daily jobs for disabled schedulers

---

packages/backend/src/scheduler/SchedulerTask.mock.ts
packages/backend/src/scheduler/SchedulerTask.test.ts
packages/backend/src/scheduler/SchedulerTask.ts

Scheduler job errors when threshold condition doesn't have results.
Changes:
- add condition to check amount of rows and thresholds
- handle possible undefined second row
- add test

fix: undefined error when threshold doesnt have enough results

---

packages/frontend/src/components/ProjectConnection/WarehouseForms/Inputs/StartOfWeekSelect.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/SnowflakeForm.tsx

Closes: [#8465](https://github.com/lightdash/lightdash/issues/8465)
Changes:
- add alert in project settings about required CLI option.
- don't show alert for snowflake as it doesn't need it

fix: show start of the week CLI option in project settings

---

packages/backend/src/knexfile.ts

Closes: #9952 
Knex sporadically errors when getting a connection.
> Connection terminated unexpectedly
Found this related thread https://github.com/knex/knex/issues/3523
Knex [docs](https://knexjs.org/guide/#pool) recommend setting min pool connection to 0.
> Note that the default value of min is 2 only for historical reasons. It can result in problems with stale connections, despite tarn's default idle connection timeout of 30 seconds, which is only applied when there are more than min active connections. It is recommended to set min: 0 so all idle connections can be terminated.

fix: minimum knex connections

---

packages/backend/src/services/UnfurlService/UnfurlService.ts

Closes: N/A
This solution addresses errors like this: 
```
{"error": "locator.waitFor: Error: strict mode violation: locator('.loading_chart') resolved to 3 elements:\n    1) <div class=\"mantine-Stack-root loading_chart mantine-…>…</div> aka locator('.mantine-Stack-root').first()\n    2) <div class=\"mantine-Stack-root loading_chart mantine-…>…</div> aka locator('div:nth-child(20) > .mantine-Paper-root > .sc-dJjYzT > .mantine-wsk78d > div > .mantine-Stack-root')\n    3) <div class=\"mantine-Stack-root loading_chart mantine-…>…</div> aka locator('div:nth-child(21) > .mantine-Paper-root > .sc-dJjYzT > .mantine-wsk78d > div > .mantine-Stack-root')\n\nCall log:\n  - waiting for locator('.loading_chart') to be hidden\n"}
```
When getting all remaining `.loading_chart`s, we should use the …

fix: wait for all chart spinners before playwright screenshot

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/types/field.ts
packages/common/src/utils/formatting.mock.ts
packages/common/src/utils/formatting.test.ts
packages/common/src/utils/formatting.ts
packages/frontend/src/components/Explorer/CustomMetricModal/utils/index.ts

Closes: https://github.com/lightdash/lightdash/issues/10358
> ideally - it should keep the min/max format of the metric but still use the value formatting of date.
Keep `max` type on the custom metric, and add a new `date/timestamp` custom format .
There are a couple of unexpected side effects when keeping this a `max` . We could create separate issues for these.

fix: custom metric date max format

---

packages/backend/src/config/parseConfig.ts
packages/backend/src/services/UnfurlService/UnfurlService.ts

Closes: #9024
We experimented using `playwright` to save screenshots and that has been quite reliable at getting them for scheduled deliveries and working with `browserless`. 
Besides these changes, we also:
- Added retries #10028 
- Increase `maxAttempts` of dashboard + image scheduled deliveries to 2 (#10313)
- Increased the replica count of some instances (see cloud)
- Reduced max number of concurrent jobs slightly for instances that heavily use scheduled deliveries (see cloud)
This PR removes: 
- usage of env var: `SCHEDULER_SCREENSHOT_WITH_PLAYWRIGHT`
- removes the puppeteer `saveScreenshot` util and replaces it with its playwright-equivalent
> [!NOTE]
> This doesn't remove `puppeteer` completely because I see some references in `headlessBrowser` and that should be handled in another …

chore: use playwright to saves creenshots by default

---

packages/backend/src/prometheus.ts

Closes: 
Event loop utilization [docs](https://nodejs.org/api/perf_hooks.html#performanceeventlooputilizationutilization1-utilization2)

chore: add eventloop utilization Prometheus metric

---

packages/backend/src/App.ts
packages/backend/src/SchedulerApp.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/prometheus.ts
packages/backend/src/scheduler/SchedulerClient.ts

Closes:  https://github.com/lightdash/lightdash-cloud/issues/403
We could add a group by on task and add the task as an extra argument to the gauge, but this will probably slow down the request, so not doing it for now.

fix: add queue size prometheus

---

docs/docs/self-host/customize-deployment/environment-variables.mdx
packages/backend/src/App.ts
packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/config/parseConfig.ts

Closes: [#10356](https://github.com/lightdash/lightdash/issues/10356)
Changes:
- Allow to configure "report only" via env var. Default is report only
- Allow to set report URI
- Document CSP env vars
- Amend allowed list to support all monaco editor files

feat: CSP report only configuration

---

packages/backend/src/services/UnfurlService/UnfurlService.ts

Closes: https://github.com/lightdash/lightdash/issues/10479
In here: https://github.com/lightdash/lightdash/pull/10451 we waited for all charts to load on dashboard scheduled deliveries. We should actually wait for `CHART` and `EXPLORE` scheduled deliveries as well.

fix: wait for `.loading_chart` regardless of scheduled delivery

---

packages/backend/src/services/UnfurlService/UnfurlService.ts

Closes: #10462 
See Sentry issue in ticket ⬆️ 
- Waits for `/runQuery` instead of `/results` when sharing an unsaved chart link so it works with Slack image unfurling.

fix: get correct response pattern for explore screenshots

---

packages/backend/src/scheduler/SchedulerClient.ts

Closes: https://github.com/lightdash/lightdash-cloud/issues/433
set LIGHTDASH_SCHEDULER: False
Tried downloading a CSV, the gauge increased
Scheduled some deliveries in the future, the gauge didn't increase
I also tried doing this: 
> add metric queue_concurrency_utilization where it filters rows by is_locked (as it is an indicator that is being processed) and divide by concurrency config to find the %.
However , when the jobs are `in progress` they are removed from the `jobs` table. so we can't track thoes jobs using SQL. We could do some manual tracking using `runner.events.on`

fix: queue monitoring sql

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/models/CatalogModel/utils/parser.ts
packages/common/src/types/catalog.ts
packages/e2e/cypress/e2e/api/catalog.cy.ts
packages/frontend/src/features/catalog/components/CatalogFieldListItem.tsx
packages/frontend/src/features/catalog/components/CatalogMetadata.tsx
packages/frontend/src/features/catalog/components/CatalogMetadataFieldsTable.tsx
packages/frontend/src/features/catalog/components/CatalogPanel.tsx

Closes: [#10328](https://github.com/lightdash/lightdash/issues/10328)
- Display field labels on the panel **and** on the metadata sidebar table
- Created a separate component for the fields table as a lil refactor
- Added `tableLabel` to the CatalogTree so when we're searching we don't get _empty_ table labels

feat: display field labels in catalog metadata

---

packages/backend/src/services/CatalogService/CatalogService.ts
packages/frontend/src/features/catalog/components/CatalogMetadata.tsx
packages/frontend/src/features/catalog/components/CatalogPanel.tsx
packages/frontend/src/features/catalog/components/CatalogTableListItem.tsx
packages/frontend/src/features/catalog/context/CatalogProvider.tsx

Closes: #10489
Hide explore errors in Catalog if they have `NO_DIMENSIONS_FOUND` error - we do the same in the validator.
Reduce opacity of errors table list item (this will be revisited a bit more when we deal with the removal of this grouping)
Display tooltip if the error is truncated, but don't open the sidebar with the full error anymore
**note**: I see that the keyboard navigation could be handled differently. I believe this can be done on a separate PR, but lmk if pressing
To test, I changed this locally in `schema.yml`
before
after
https://github.com/lightdash/lightdash/assets/7611706/2393cd12-1f54-4b62-9246-6daaea421eae
And now we don't see the errors group and we don't handle if there are errors in the explore because they don't get added to the payload

feat: hide explore errors in catalog

---

packages/backend/src/App.ts

Closes: https://github.com/lightdash/lightdash-internal-work/issues/1833
Apply child-src fallback for safari older than 15.5 as worker-src wasn't supported before that version.

fix: safari child src fallback

---

packages/backend/src/models/CatalogModel/utils/index.ts
packages/backend/src/models/CatalogModel/utils/parser.ts

Closes: #10309
Hide `hidden` fields when:
- Searching ( see `...between...` field)
before
after
- Viewing metadata ( see `...between...` field)
before
after

feat: hide hidden catalog fields

---

packages/backend/src/services/CatalogService/CatalogService.ts
packages/common/src/types/catalog.ts
packages/frontend/src/features/catalog/components/CatalogMetadata.tsx

Closes: N/A
Missed one bit in: https://github.com/lightdash/lightdash/pull/10485
Before
After

fix: get correct table label and label on metadata

---

docs/docs/references/filters.md

Closes: https://github.com/lightdash/lightdash-internal-work/issues/1840
@TuringLovesDeathMetal
This is the section that got updated: https://deploy-preview-10522–peaceful-bassi-cbf284.netlify.app/references/filters#date-filters.
I started by adding the “not in the current” filter, but I noticed that some of the filters were missing, examples were incorrect, or names were wrong. So, I went through all of them within this PR.

docs: update date filters section

---

packages/frontend/src/features/catalog/components/CatalogFieldListItem.tsx

Closes: [#10492](https://github.com/lightdash/lightdash/issues/10492)
Use a `Grid` to display the 3 elements of a field item row: `icon` - `label` - `description`
This approach is very similar to `CatalogTableListItem`

feat: display field descriptions

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/models/CatalogModel/utils/index.ts
packages/backend/src/models/CatalogModel/utils/parser.ts
packages/common/src/types/catalog.ts
packages/frontend/src/features/catalog/components/CatalogFieldListItem.tsx
packages/frontend/src/features/catalog/components/CatalogMetadata.tsx
packages/frontend/src/hooks/useExplorerRoute.ts

Closes: [#10150](https://github.com/lightdash/lightdash/issues/10150)
- Allows field selection when searching it (on hover) and also when viewing its metadata
Demo:
https://github.com/lightdash/lightdash/assets/7611706/4a653f98-8434-4784-8b55-d0b5c1203265
**NOTE**: this also filters out dimensions that have `isIntervalBase`: `true` - for example, we have a `Timestamp` dimension that has many granularities. Currently, we display its base dimension, but that isn't explorable. Instead, we should just filter them out from the catalog fields that we can search. If we want to bring back this functionality in the future, we should remove this filtering but handle these fields differently on the Catalog - we should have a tree basically.

feat: allow select field to explore in catalog

---

packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/GroupsView.tsx

Closes: #10536 
Increase the number of members returned when viewing group membership. This is a partial/temporary fix. We should also make this a paginated list on the FE.

fix: increase limit on number of members shown per group

---

packages/backend/src/queryBuilder.mock.ts
packages/common/src/compiler/exploreCompiler.mock.ts
packages/common/src/types/warehouse.ts
packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.mock.ts
packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.test.ts
packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts
packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
packages/warehouses/src/warehouseClients/TrinoWarehouseClient.ts
packages/warehouses/src/warehouseClients/WarehouseBaseClient.ts

Closes: [#10537](https://github.com/lightdash/lightdash/issues/10537)
Expose new WarehouseClient method `streamQuery` and deprecate `runQuery`.
Note that we are still using `runQuery` and all rows loaded in memory. We will incrementally refactor our code to use the new streaming method.
test-api test-backend test-frontend

feat: expose WarehouseClient method to stream results

---

packages/backend/src/controllers/catalogController.ts
packages/backend/src/database/migrations/20240625163709_add_field_type_to_catalog_search.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/CatalogService/CatalogService.ts
packages/common/src/types/catalog.ts
packages/frontend/src/features/catalog/components/CatalogFilterSearch.tsx
packages/frontend/src/features/catalog/components/CatalogPanel.tsx
packages/frontend/src/features/catalog/hooks/useCatalog.ts

Closes: [#10326](https://github.com/lightdash/lightdash/issues/10326)
- Enables searching just for `tables` or `metrics` or `dimensions`
- These are only enabled when search value is > 2
Overall changes
- Added migration file that includes `field_type` column to `catalog_search` - this is useful for filtering out fields by type: `dimension` or `metric`. These are added when the user compiles the project
- Search accepts `type` and `filter` which will take that into account when searching 
- if the filter is `table` then it will search only by the table type
- if the filter is `dimension` or `metric`, it will only search by fields **and** by `field_type`
- Removed previous filter logic on the FE because we changed a few things in its behaviour
- we only accept one filter at a time
- we …

feat: enable searching catalog with filters (including search index)

---

packages/frontend/src/Routes.tsx
packages/frontend/src/features/sqlRunner/components/Sidebar.tsx
packages/frontend/src/features/sqlRunner/components/Tables.tsx
packages/frontend/src/features/sqlRunner/hooks/useTables.tsx
packages/frontend/src/features/sqlRunner/index.ts
packages/frontend/src/pages/SqlRunnerNew.tsx

Relates to: #10551 
- Adds new route `/sqlRunnerNew`
- Adds Sidebar (can be open and closed) - another PR will be open to handle the mount/unmount. We shouldn't do this and the `Transition` applied to the main Sidebar component should be replaced with a raw implementation 
- Gets `tables` from `useTables` hook and renders grouped by `schema`
NOTE: another PR will be open to handle the fields for each table
DEMO:
https://github.com/lightdash/lightdash/assets/7611706/88fc355f-6e5e-4e5b-93d2-3a89904a3580

feat: add new sql runner page with tables

---

packages/frontend/package.json
packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx
packages/frontend/src/components/DashboardFilter/FilterConfiguration/utils/index.ts
packages/frontend/src/components/DashboardTiles/TileForms/TileUpdateModal.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/index.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingItem.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingList.tsx
packages/frontend/src/components/common/ResourceView/ResourceViewGrid/index.tsx
packages/frontend/src/providers/ExplorerProvider.tsx
yarn.lock

Closes: N/A
Relates to: #10515 
Upgrades `immer` to latest before introducing `redux-toolkit`.
Have a look at the breaking changes
https://github.com/immerjs/immer/releases/tag/v10.0.0
Changes are
- named import `{ produce }`
- ensure every value passed to `produce(...)` is not a promise

chore: upgrade immer to latest

---

packages/backend/src/models/SpaceModel.ts

Closes: #10165 
- Returns user space access instead of group access when user has `space_user_access`, only return the highest group access when user doesn't have explicit user access
Before:
https://github.com/lightdash/lightdash/assets/22939015/8098a8db-a223-4e8f-8d63-4efd2bfe43bc
After:
https://github.com/lightdash/lightdash/assets/22939015/9f4dc14c-e85b-4391-b24f-edd4ee809b6e

fix: allow downgrade of individual user space permissions when in group

---

packages/frontend/src/features/sqlRunner/components/Sidebar.tsx
packages/frontend/src/features/sqlRunner/components/TableFields.tsx
packages/frontend/src/features/sqlRunner/components/Tables.tsx

Closes: N/A
- Computes height of `ResizableBox` and substracts that from the `Tables`' height.
- Some overflow scrolls
- Changed `Sidebar` height from `100vh` to `100%`
demo:
https://github.com/lightdash/lightdash/assets/7611706/2d78c9ae-e505-4be0-b4a5-f81221d9e5d7

fix: handle resize height and apply correct overflows

---

packages/frontend/src/features/scheduler/hooks/useScheduler.ts
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/hooks/useSqlQueryRun.tsx

Closes: [#10552](https://github.com/lightdash/lightdash/issues/10552)
- Creates hook `useSqlQueryRun` hook that does the following: 
- schedules run query job
- polls a query job status until it's complete or errors
- after a successful job it reads the streamed results, processes them into a `ResultRow[]` format
The component `ContentPanel` will keep track of what the user types on the `sql` + it will set the button as loading until the job settles. 
You can try with this: 
```sql
SELECT *
FROM "postgres"."jaffle"."users" LIMIT 25
```
Demo:
https://github.com/lightdash/lightdash/assets/7611706/80735faa-eacc-4533-860a-fe846e9c2f8b

feat: stream data to sql runner page

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx

Closes: #[10611](https://github.com/lightdash/lightdash/issues/10611)
- Shows disabled button with tooltip in dashboard tile options when user cannot edit chart
1. Create a new user
2. Share `Jaffle shop` space with the user using `can view` permissions
3. Create a new space
4. Share space with the new user using `can edit` permissions
5. Add a new chart to the created space
6. Add a new dashboard to the created space (should contain the new chart in this space + a chart in jaffle shop)
7. Go to dashboard
8. Click on the "three dots" menu of each chart to see the options

fix: show edit button tooltip when user doesn't have permission to edit

---

packages/common/src/compiler/exploreCompiler.ts

Closes: [#10534](https://github.com/lightdash/lightdash/issues/10534)
- Fixes joining twice with on the same table picking the wrong table join. Previously it was finding the first that matched the original name which could result in the incorrect join being picked up.
Before:
https://github.com/lightdash/lightdash/assets/22939015/b1b7946f-b9b7-41c3-ab13-bb2167649531
After:
https://github.com/lightdash/lightdash/assets/22939015/5a2bfe09-2b99-4482-ad3e-dd5e4c327678

fix: alias join on the same table

---

packages/frontend/src/features/sqlRunner/components/TableFields.tsx

Closes: https://github.com/lightdash/lightdash/issues/10612
switches the icon with a `CopyButton` on hover of a table field. 
happy to go over other suggestions (for example, on top of `type`?) 
Another thing I tried was to display this icon next to the name, but not sure if it would be annoying to have the icon appear on different places on the x axis.
demo: 
https://github.com/lightdash/lightdash/assets/7611706/8e9eba27-c85f-44f2-b2b7-d065e2ce1f1c

feat: sql runner fields copy to clipboard

---

packages/frontend/src/components/VisualizationConfigs/common/EditableText.tsx

solves issue #10618
Closes: 
#10618 
https://github.com/lightdash/lightdash/assets/143312648/f132126b-31e3-4144-af2d-d1e09a69cb01

fix: focus on editable text on pencil icon click

---

packages/warehouses/src/warehouseClients/TrinoWarehouseClient.ts

- Checks if results data is `undefined` and passes empty array in that case
Before https://github.com/lightdash/lightdash/commit/a2847ca36d643593aa87781f760c94eae1ef0258 it already included the check: https://github.com/lightdash/lightdash/blob/c33ecc12d7578fdf0fa5030844443e2ddcf5ab41/packages/warehouses/src/warehouseClients/TrinoWarehouseClient.ts#L199

fix: pass empty array when null or undefined to resultHandler

---

packages/common/src/transformers/ResultTransformers/SqlRunnerResultsTransformer.ts
packages/common/src/transformers/ResultTransformers/index.ts
packages/common/src/types/sqlRunner.ts

Closes: #10636 
Adds `SqlRunnerResultsTransformer` that exposes two methods
- getRows
- getColumns
Added type `SqlRunnerResults`
Usage in `ContentPanel` would look something like: 
```tsx
const {
mutate: runSqlQuery,
data: queryResults,
isLoading,
} = useSqlQueryRun();
// But without the `undefined`
const tableTest = queryResults
? new SqlRunnerResultsTransformer({ data: queryResults })
: undefined;
```

chore: add SqlRunnerResultsTransformer class

---

docs/docs/references/embedding.mdx

Fix embedding guide link which was broken

fix: embedding guide link

---

packages/frontend/src/features/sqlRunner/components/Header.tsx
packages/frontend/src/features/sqlRunner/components/SaveSqlChartModal.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

Closes: #10677 
- Adds `modals` state to store as well as a `toggleModal` action
- Displays placeholder modal for saving a SQL chart
demo: 
https://github.com/lightdash/lightdash/assets/7611706/c7ae45d0-aa47-4176-9dbc-381621950dd6

chore: add placeholder modal to save sql chart

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/visualizations/Table.tsx
packages/frontend/src/features/sqlRunner/transformers/useTableDataTransformer.ts
packages/frontend/src/pages/SqlRunnerNew.tsx

Closes: https://github.com/lightdash/lightdash/issues/10679
Adds wrapper with the proper `flex` styling
Uses containers' `h`s and `w`s to apply correct overflow
Removes usage of `TableScrollableWrapper` - needed to add one more style: `flex: 1` but also used Mantine's `Flex` component to make less changes and avoid using Styled Components.
Demo: 
https://github.com/lightdash/lightdash/assets/7611706/5be70408-3251-41de-8e0c-441d66db1f64

style: fix content panel width and height on large column table results

---

dockerfile
packages/backend/src/SchedulerApp.ts

Closes: https://github.com/lightdash/lightdash-cloud/issues/400
- `yarn workspace ...` as the docker command does not handle SIGTERM
- `node scheduler.js` handles SIGTERM but won't kill the container
- `dumb-init node scheduler.js` handles SIGTERM
Also updated logging on the shutdown for the scheduler.
https://github.com/lightdash/lightdash/assets/11660098/063bb6f0-d748-4ee9-865d-7a2d52a53242
@ZeRego not sure if you still need changes for your docker-compose setup to work? I noticed you made a change on #10482

fix: handle SIGTERM gracefully on scheduler

---

packages/frontend/src/features/sqlRunner/components/Tables.tsx
packages/frontend/src/features/sqlRunner/hooks/useTables.tsx

Closes #10687, closes #10686
- Memoizes `TableItem` (now when we click on a table we're not rendering all table items again) - this is done by passing the `isActive` prop instead of computing that on the component-level.
- Adds `ScrollArea`, only vertical ,and with variant primary to mimick what we have for `TableFields`
- On hover, we let the user copy to clipboard, the database+schema+table so that it can just be referenced easily on the SQL editor.
demo on truncation:
https://github.com/lightdash/lightdash/assets/7611706/2d7f6f67-6498-4311-8dc9-1cc0e6a84ca9
demo on copying: 
https://github.com/lightdash/lightdash/assets/7611706/4624f207-1f16-4684-80b3-86592901041b

feat: truncate tables and allow copying table reference

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/visualizations/Table.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts
packages/frontend/src/features/sqlRunner/transformers/TableDataTransformer.ts
packages/frontend/src/features/sqlRunner/transformers/useTableDataTransformer.ts

Closes: #10711
Add tabs for 'Chart' and 'Results'. The results tab will always show a static, non-configurable table showing all results. The chart tab can be any viz.

chore: add results and chart tabs

---

packages/backend/src/models/UserModel.ts
packages/backend/src/services/UserService.test.ts
packages/backend/src/services/UserService.ts

Closes:  https://github.com/lightdash/lightdash-internal-work/issues/1889
So, what's happening: 
- users on the org are not joining via invitation
- org has a whitelisted domain, so the user joins automatically the org
- however, when we check for groups, the user hasn't joined the group yet
- on /joinOrg we don't have information about the group
How this fixes it.
- Targeted fix: if `  !createdUser.organizationUuid && !inviteCode &&  hasGroups &&  allowedOrgs.length === 1`
- Join the org
- Then apply group

fix: auto join org to apply okta group

---

packages/common/src/types/sqlRunner.ts
packages/frontend/src/features/sqlRunner/components/Header.tsx
packages/frontend/src/features/sqlRunner/components/RightSidebar.tsx
packages/frontend/src/features/sqlRunner/components/SaveSqlChartModal.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

Closes: #10726 
- Makes it possible to update the SQL runner name in place. 
- That name then gets used in the modal.
- Makes it possible to enter a description when saving
- Note that the description is currently not displayed anywhere. 
Note that once save, these can't be updated. We dont have them in the versioned types. I wasn't sure whether to add them or not -- the way that types are set up it looks intentional. Is there any reason these should be kept out of versioning? If so that's fine, but we have to change some things to plumb updated to name and description through.

chore: make sql runner name and description updatable

---

packages/frontend/src/features/sqlRunner/components/Tables.tsx

Closes: N/A
Use `background` instead of `backgroundColor`. 
demo: 
https://github.com/user-attachments/assets/33cdd2c7-c80e-4360-93bc-ae420ca69f37

style: change bg color if active table

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/SqlEditor.tsx

Closes: https://github.com/lightdash/lightdash/issues/10738
allows to run a query with cmd+enter outside and inside the sql editor
Followed this suggestion to get to a working solution: https://github.com/suren-atoyan/monaco-react/issues/328#issuecomment-1079967898
demo:
https://github.com/user-attachments/assets/18fc4a0f-1756-4f2b-8b7b-3a69f2a0a5d3

feat: run query on cmd+enter

---

packages/frontend/src/components/NavBar/ProjectSwitcher.tsx

Closes: <-- reference the related issue e.g. #10702  -->
closes issue #10702 
was asked to make the badges be on the right side so that projects which dont have the preview badges also would look uniform with the ones that do && change the style of badge to outline & color to 🍊 . I did. see below video.
<-- Even better add a screenshot / gif / loom -->
https://github.com/user-attachments/assets/da3c091d-7153-4310-8d22-b933d107b14c

style: update preview project badge and layout

---

packages/backend/src/models/DashboardModel/DashboardModel.ts
packages/common/src/index.ts
packages/frontend/src/api.ts
packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx
packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx
packages/frontend/src/features/sqlRunner/hooks/useSqlChartAndResults.tsx
packages/frontend/src/hooks/useChartSummariesV2.ts

Closes: #10744
Allows adding tiles to a dashboard that are SQL charts
Uses the new v2 endpoint: `useChartSummariesV2` and allows `lightdashApi` to have a different prefix.
I've also added a chart icon to each select item when adding chart tiles to the dashboard
Improved loading state of `useSqlChartAndResults` hook and when setting the `chart` data if the job is cached.
Demo
https://github.com/user-attachments/assets/86030e9e-75a8-4c40-80cb-6e54790951d8

feat: allow adding sql charts to dashboard

---

packages/frontend/src/features/sqlRunner/components/Tables.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts
packages/frontend/src/pages/SqlRunnerNew.tsx

Related: https://github.com/lightdash/lightdash/issues/10616
-  add default SQL. eg SELECT * FROM lightdash-analytics.prod.github_daily LIMIT 25
-  Add quoting when coping a table (e.g. when I click pages it should copy `database.table.pages`
[Screencast from 19-07-24 10:06:09.webm](https://github.com/user-attachments/assets/f9b2c24b-71ca-4916-abc1-5bdba9d2b2e6)

chore: load sample sql if empty with warehouse quotes

---

packages/backend/src/SchedulerApp.ts

Related to: https://github.com/lightdash/lightdash-cloud/pull/473
- From the `terminus` docs, they recommend adding `useExit0` to signal kubernetes that the container exited gracefully: https://github.com/godaddy/terminus?tab=readme-ov-file#how-to-set-terminus-up-with-kubernetes
Similar issue on `terminus` repo: https://github.com/godaddy/terminus/issues/209
PR that fixed it by adding `useExit0`: https://github.com/godaddy/terminus/pull/212
The following videos show how our worker and backend pods are terminated - grace period is set to default of 30 and we're not using init containers from https://github.com/lightdash/lightdash-cloud/pull/473, this is our CURRENT setup
For the backend one, you'll be able to see that right after a pod starts and has both containers running, the `old` pod …

chore: use exit 0 on terminus shutdown to signal kubernetes

---

packages/frontend/src/features/sqlRunner/components/Header.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

Closes: https://github.com/lightdash/lightdash/issues/10783
Specify saved chart space `name` and `uuid` 
user can click on it to go the space it belongs to
Small rename from `savedChartUuid` to `savedSqlUuid` to match the original type
Screenshot:

feat: add space breadcrumb before saved chart

---

packages/frontend/src/styles/react-grid.css

It turns out that the `react-resizable` package, introduced recently, is the same package that the `react-grid-layout` package uses underneath to resize tiles.
The `react-resizable` CSS import is conflicting with our own modified `react-grid.css`.
Regression change: https://github.com/lightdash/lightdash/commit/2ddd7567dc32d720ebffb95ca49744dbf7b9d20c#diff-e4f4c3d05237e4dfb5e48d715e10af4beed2cbec2f93f6b7d5d9e68e6666b2b7R17
https://github.com/user-attachments/assets/2d3a6ae8-e1f6-4677-a80b-a4d4567abac1
https://github.com/user-attachments/assets/e19b5360-3898-4d4c-81ef-daedbdda8831

fix: dashboard tile resize handler visibility

---

packages/backend/src/queryBuilder.mock.ts
packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts

Closes:  https://github.com/lightdash/lightdash/issues/10793
CTE with month name sort

fix: bigquery month name sort

---

packages/backend/src/scheduler/SchedulerTask.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/index.ts
packages/common/src/types/sqlRunner.ts
packages/frontend/src/features/scheduler/hooks/useScheduler.ts
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/visualizations/BarChart.tsx
packages/frontend/src/features/sqlRunner/components/visualizations/Table.tsx
packages/frontend/src/features/sqlRunner/hooks/useSqlQueryRun.tsx
packages/frontend/src/features/sqlRunner/transformers/TableDataTransformer.ts
packages/frontend/src/features/sqlRunner/transformers/useBarChartDataTransformer.ts
packages/frontend/src/features/sqlRunner/transformers/useTableDataTransformer.ts

Closes: N/A
Why we need this:
https://github.com/lightdash/lightdash/pull/10801#discussion_r1688383916
So that we can apply dimensionType-specific logic to each config layout option
- Adds `columns` to sql runner job task
- Improves types and allows `logWrapper` to accept a generic (it will help with different response types for different jobs)
- Add `columns` on `select` of `useSqlQueryRun`
- Updated the transformers to reference `ResultRow[]` instead of the return type of the hook (initially I thought the hook type would be beneficial, but it's not that reliable)
Screenshot:

chore: return column types on sql runner results job

---

packages/frontend/src/features/tableCalculation/components/TableCalculationModal.tsx
packages/frontend/src/providers/ExplorerProvider.tsx

Closes: #10505 
- prevent user from creating a table caluclation with empty sql
-  allow user to remove the erroneous column
[Screencast from 2024-07-24 22-31-52.webm](https://github.com/user-attachments/assets/2c339e4d-e6fd-4d15-bbd8-727a66d12a48)

fix: table calculation empty sql formula

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/controllers/savedChartController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/scheduler/SchedulerTask.ts
packages/backend/src/services/CsvService/CsvService.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/frontend/src/components/common/Dashboard/DashboardRefreshButton.tsx
packages/frontend/src/hooks/dashboard/useDashboardChart.ts
packages/frontend/src/hooks/useQueryResults.tsx
packages/frontend/src/providers/DashboardProvider.tsx

Partially Closes:  #10773
> No changes were done on the sql runner
SQL runner queries trigger the lightdash_server.sql.executed event
New sql runner also run `lightdash_server.sql.executed` with an extra `streaming` flag 
Triggered on SchedulerTask -> handleScheduledDelivery, added `scheduledChart` context to query query.executed
Triggered on SchedulerTask -> handleScheduledDelivery, added `scheduledDashboard` context to query.executed
Kept `gsheets` context for uploading results to gsheets
Added `scheduledGsheetsChart` and `scheduledGsheetsDashboard` for scheduled gsheets
Added `autorefreshedDashboard` context to queries triggered from autorefresh (this was harder to implement that it seems) 
No autorefresh:

chore: add context analytic events

---

packages/backend/src/controllers/sqlRunnerController.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/SavedSqlService/SavedSqlService.ts
packages/backend/src/services/ServiceRepository.ts
packages/e2e/cypress/e2e/api/sqlRunner.cy.ts

Closes: 
Problem: Only users that could manage CustomSQL could view the saved charts. 
Changes:
- Amend permission check when requesting results 
- Reuse permission check logic
Note: Not updating e2e tests in this PR. We need to seed a SQL chart to simplify e2e tests and cover these scenarios.

fix: viewers can see saved SQL chart 

---

packages/e2e/cypress/e2e/app/space.cy.ts

Closes: 
What the issue is:
We have request happening in the modal to get the spaces, when the request finishes, the input is reset. 
On render the request takes longer than expected, and the typing is quick, which means some parts of the text gets deleted. 
See video: 
[Screencast from 25-07-24 16:48:33.webm](https://github.com/user-attachments/assets/858937e3-f6f5-4a3c-8493-0b95171d6b32)
This PR fixes this issue by waiting for some text to appear before typing.

fix: space e2e test

---

packages/backend/src/database/pagination/index.ts
packages/backend/src/models/ContentModel/ContentConfigurations/DashboardContentConfiguration.ts
packages/backend/src/models/ContentModel/ContentModel.ts
packages/e2e/cypress/e2e/api/content.cy.ts

Closes: [#10809](https://github.com/lightdash/lightdash/issues/10809)
Closes: [#10761](https://github.com/lightdash/lightdash/issues/10761)
- complete dashboard content query to include first/last version
- add hardcoded orderby `last_updated_at`
- added new e2e test
Before:
After:

fix: sort v2 content by last_updated_at

---

packages/e2e/cypress/e2e/app/dates.cy.ts

Closes:  https://github.com/lightdash/lightdash/issues/10839
What was happening: 
The explore page does a reload (posthog?) so some of the actions were lost (adding a filter) 
How I fixed it: 
Wait until some of the content is loaded before doing any action.

chore: fix timezone tests

---

packages/common/src/types/sqlRunner.ts
packages/frontend/src/features/sqlRunner/hooks/useSqlQueryRun.tsx

Closes: #10844
Show SQL errors on the FE. Since the polling request returns successfully, we werent treating it as an error, even when it contained error details about the job. This shows the error details when they are there. 
🤔 Should we restructure the API to return this as an error (non-200)?

chore: show SQL errors in SQL runner

---

packages/backend/src/services/SavedSqlService/SavedSqlService.ts
packages/common/src/types/featureFlags.ts
packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx
packages/frontend/src/components/NavBar/ExploreMenu.tsx

Closes: [#10845](https://github.com/lightdash/lightdash/issues/10845) 
Changes:
- saved SQL chart endpoints throw error if user doesn't have feature flag
- app navigation points to /sql-runner-new if feature flag is enabled
- fix URL from dashboard tile to SQL runner page
Note that e2e should still pass as they access to current SQL runner page via the URL instead the UI.

feat: save sql chart feature flag

---

packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts

Closes: N/A
Handle `Int8`s and `NUMERIC`s in Postgres by parsing them to JS `Number`s 
How to verify this
**Before this change**
Go to `customers` with the SQL runner (old/new)
Query `customers` and see the value of `customer_lifetime_value`
It returns as a string 
**After this change**
A number is returned

feat: parse postgres numerics & int8s to JS numbers

---

packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/visualizations/BarChart.tsx
packages/frontend/src/features/sqlRunner/transformers/useBarChart.ts

Closes: #10856
Adds loading state + merge transitions
https://github.com/user-attachments/assets/6227cd79-4f88-4f20-b0a6-defbd8029b98
https://github.com/user-attachments/assets/d8364648-5264-4fd9-9f98-dc915f84bc29

fix: bar chart loading state

---

packages/common/src/schemas/json/lightdash-dbt-2.0.json

Closes: xxx
I didn't create an issue for the pull request. Please let me know, if I should create one.
I have changed `lightdash-dbt-2.0.json` to prohibit null values of some properties in dimensions and metrics. For instance, null value of the `label` property for a dimension is allowed. So, we can add constraints to check if it isn't null using `"minLength": 1`.
```
columns:
- name: revenue_gbp_total_est
description: 'Total estimated revenue in GBP based on forecasting done by the finance team.'
meta:
dimension:
type: string
label: 
```

chore: Prohibit null of some properties in `lightdash-dbt-2.0.json`

---

packages/frontend/src/components/common/modal/ChartCreateModal/SaveToDashboard.tsx

Closes: #10865
With this fix, we've introduced a new edge case:
If the user is editing a dashboard and deletes all the tiles , without saving, then edit or create a chart iwthin dashboard. Then after saving that chart within dashboard, it will get all the `saved` tiles instead of the `unsaved tiles` because unsavedTiles.length === 0 
I think this is a rare edge case and it good trade off. 
Before:
[Screencast from 29-07-24 09:19:19.webm](https://github.com/user-attachments/assets/b55a765a-6aac-4d56-8f92-3752dcbb1e4e)
After:
[Screencast from 29-07-24 09:26:39.webm](https://github.com/user-attachments/assets/23f19f8d-6683-4199-955c-266c8da8154a)

fix: saving chat within dashboard as save as overrides dashboard

---

packages/frontend/src/features/sqlRunner/components/Header.tsx
packages/frontend/src/features/sqlRunner/components/HeaderViewMode.tsx
packages/frontend/src/features/sqlRunner/store/barChartSlice.ts
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts
packages/frontend/src/features/sqlRunner/store/tableVisSlice.ts
packages/frontend/src/pages/SqlRunnerNew.tsx
packages/frontend/src/pages/ViewSqlChart.tsx

Closes: 
We need to store the entire saved SQL chart in the redux state as we need most (if not all) information for different parts of the page. The `savedSqlChart` property should be treated as "read only".
The properties that are editable(name, SQL, config) should also be stored as separate properties in the redux state as treated as the "unsaved/dirty" state.

chore: refactor sql runner redux state to have entire sql chart data

---

packages/frontend/src/features/sqlRunner/components/BarChartFieldConfiguration.tsx

Closes: N/A
When the `group by` is cleared, return `null` on `value` so that it disappears. Mantine takes `undefined` as a "show me previous" 
Demo
https://github.com/user-attachments/assets/b8b60efa-8160-410b-95be-fb19f1b91b52

fix: group by clear bar chart sql

---

packages/frontend/src/features/tableCalculation/components/SqlForm.tsx
packages/frontend/src/features/tableCalculation/components/TableCalculationModal.tsx

Closes: #10884 
Hello,
Today, When we open the Table Calculation Modal, save and cancel button appears only when scrolled.
I added a wrapper element that has `position:sticky` as seen in the file:
packages/frontend/src/features/tableCalculation/components/TableCalculationModal.tsx
Additionally, there is one change done in the file:  
packages/frontend/src/features/tableCalculation/components/SqlForm.tsx
The ace editor's left grey bar was overlapping on the Modals footer (Element with sticky position) as we scrolled down. So I had to adjust the z-index here in SQLForm.tsx
Current UI/UX:
New Behaviour:
cc: @TuringLovesDeathMetal @ZeRego

fix: Table Calculation Modal (save and cancel) buttons

---

packages/common/src/utils/filters.ts
packages/frontend/src/components/common/Filters/FilterRuleForm.tsx

Closes: [#10748](https://github.com/lightdash/lightdash/issues/10748)
- Format the date in the values taking into account the timeframe when changing date filters
**Before:**
https://github.com/user-attachments/assets/c434e7d6-a528-410c-b4e9-934d0081bcc4
**After:**
https://github.com/user-attachments/assets/dee58dd4-992a-4f10-8875-fd7cd8655e34

fix: format date values with the new interval when changing date field

---

packages/frontend/src/features/sqlRunner/components/Header/HeaderEdit.tsx
packages/frontend/src/features/sqlRunner/components/SaveSqlChartModal.tsx
packages/frontend/src/features/sqlRunner/store/selectors.ts

Closes: 
Add a selectors file with a compound selector. This makes it so you can get the current chart config without know which it is like 
`const config = useAppSelector((state) => selectCurrentChartConfig(state));`

chore: add a selector for the current chart config

---

packages/frontend/src/components/VisualizationConfigs/common/Config.tsx
packages/frontend/src/features/sqlRunner/components/BarChartAggregationConfig.tsx
packages/frontend/src/features/sqlRunner/components/BarChartFieldConfiguration.tsx
packages/frontend/src/features/sqlRunner/store/barChartSlice.ts

Closes: #10863 
- Can add/edit/remove to the y axis
- Can edit its aggregation
- When there's more than one, it turns into a show/hide stack of bar series
- doesn't work with other types **yet**
- Aggregation config changes from a segmented control to a better styled Select
- 
DEMO:
https://github.com/user-attachments/assets/fd984b33-f75a-48a7-a06d-8e2d66371cfb
> [!NOTE]
> I want to split the components in the configuration component a bit better - but shall be done when we prioritise more the UI refactoring.
> [!NOTE]
> I can't yet change the colour and label of the series - I want to do this on a separate PR (https://github.com/lightdash/lightdash/issues/10947) after this PR's review

feat: allow adding series

---

packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx
packages/frontend/src/features/sqlRunner/hooks/useSqlChartAndResults.tsx

Closes: [#10936](https://github.com/lightdash/lightdash/issues/10936) 
Changes:
- check `isFetched` and `isFetching` to catch when query is not enabled ( aka, savedSqlChartUuid is null )
- check if any of the queries returned an error
- update tile props 
Before: we would show the loading state if something was wrong
After: when saved chart no longer exists
After: when there is an error fetching chart and results

fix: dashboard SQL chart tile error state

---

packages/frontend/src/features/sqlRunner/components/BarChartFieldConfiguration.tsx
packages/frontend/src/features/sqlRunner/store/barChartSlice.ts

Closes: N/A
Before we were relying on `reference` but a 2 series can have the same reference. This won't work as expected when changing a series' aggregation. So this relies on the `index` as the other actions for y axis fields.
Demo:
https://github.com/user-attachments/assets/36d540ef-ea98-45a1-aee8-2edb275f19da

fix: change y axis aggregation based on index instead of reference

---

docs/docs/guides/limiting-data-using-filters.mdx

Closes: 
here
https://docs.lightdash.com/guides/limiting-data-using-filters/
linking to table sql filters:
was broken.

docs: fix broken sql filter link

---

packages/frontend/src/features/sqlRunner/components/Sidebar.tsx

Closes: 
avoids using `ConditionalVisibility` (because it messes up with the hierarchy + react resizable) It should be a ConditionalDisplay instead - I wanted to add a new component but this should be a quick fix
Before
https://github.com/user-attachments/assets/fd9449f0-9386-4e90-a807-b6f0decaf356
After
https://github.com/user-attachments/assets/af02c5ca-1ecd-4433-a863-e5d5731190ed

fix: dont use conditional visibility for table overflows

---

packages/frontend/src/components/common/Page/Sidebar.tsx

Closes: [#10935](https://github.com/lightdash/lightdash/issues/10935)
Make sure the sidebar component has a higher z-index than the main content so the drag and drop is available.
Before:
After:

fix: page sidebar above center main section

---

packages/frontend/src/pages/SqlRunnerNew.tsx

Closes: [#10990](https://github.com/lightdash/lightdash/issues/10990)
We now show a page error, as we have for other pages, in case it can't load the saved SQL chart

fix: show SQL chart page error

---

packages/backend/src/database/entities/catalog.ts
packages/backend/src/models/CatalogModel/utils/index.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts

Closes: https://github.com/lightdash/lightdash/issues/10921
cleaned up indexCatalog function as well since adding `field_type` would not require to return both converted explore catalog and inserted
ℹ️ this is going to break commercial build so I gotta update types in there as well

chore: improve typing for db catalog

---

packages/frontend/src/components/common/Filters/FilterInputs/FilterMultiStringInput.tsx
packages/frontend/src/components/common/Filters/FilterInputs/FilterStringAutoComplete.tsx
packages/frontend/src/components/common/Filters/FilterInputs/MultiValuePastePopover.tsx

When pasting a value into a filter our default behavior was to always add it as multiple values when the clipboard contents had commas.
This PR makes it so that when pasting a comma separated value we ask for user input on how the value should be treated
- Shows a popover when pasting to filters if the clipboard values has comma separated values
**chart filters**
https://github.com/user-attachments/assets/245d04d9-6a15-462a-99c7-dfb192a23d41
**dashboard filters**

fix: show popover on paste

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx

Closes: N/A
Use `useDeferredValue` to deal with this exact issue: when the user scrolls up and down the results panel it should affect the bar chart's height, but it shouldn't block the UI thread
demo: 
https://github.com/user-attachments/assets/04815c97-83b5-4413-891f-185b1bd90b79

chore: replace useDebouncedValue with useDeferredValue

---

packages/frontend/src/features/sqlRunner/components/Header/HeaderCreate.tsx
packages/frontend/src/features/sqlRunner/components/SaveSqlChartModal.tsx
packages/frontend/src/features/sqlRunner/store/selectors.ts

Closes: #10974 
Makes it possible to save an SQL runner without viewing the chart.  This will choose a table viz by default. This is least likely to break and most likely to match what they see if they haven't looked at the charts.

fix: can save sql without viewing chart

---

packages/cli/package.json
packages/cli/src/dbt/manifest.ts
packages/cli/src/handlers/compile.ts
packages/cli/src/handlers/dbt/compile.ts

Closes: #4748
- Runs `dbt parse` to generate a manifest before compiling all the models and their joins (looks recursively and takes into account `--select` and `--exclude` opts)
https://github.com/user-attachments/assets/5f91ca85-161e-497f-98cf-40a49d35877e
test-cli

fix: cli join compile

---

packages/warehouses/package.json
yarn.lock

Closes: #11021
- Snowflake introduced `determineConnectionDomain` on v1.12.0 which is being installed in @lightdash/warehouses package. This is causing the following error whenever trying to connect to snowflake: `Snowflake error: this.determineConnectionDomain is not a function`

chore: pin snowflake-sdk version to only accept patches

---

packages/backend/src/controllers/gitIntegrationController.ts
packages/backend/src/controllers/savedChartController.ts
packages/backend/src/generated/swagger.json

Closes: xxx
I didn't open an issue for the pull request due to the minor changes. Please let me know, if I should open one.
It seems that there are few duplicated operation IDs in controllers. So, I encountered the errors on a OpenAPI schema validator with `swagger.json`.
https://editor.swagger.io/
```
Semantic error at paths./api/v1/projects/{projectUuid}/git-integration/pull-requests/custom-metrics.post.operationId
Operations must have unique operationIds.
Jump to line 10103
Semantic error at paths./api/v1/saved/{chartUuid}/chart-and-results.post.operationId
Operations must have unique operationIds.
Jump to line 12528
Semantic error at paths./api/v1/saved/{chartUuid}/version/{versionUuid}.get.operationId
Operations must have unique operationIds.
Jump to line 12644
```

chore: Correct operation IDs in controllers

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/SavedSqlModel.ts
packages/backend/src/services/SavedSqlService/SavedSqlService.ts
packages/common/src/types/sqlRunner.ts
packages/frontend/src/features/sqlRunner/components/Header/HeaderView.tsx

Closes: [#10937](https://github.com/lightdash/lightdash/issues/10937)
Changes:
- SQL chart type now contains more properties from SpaceSummary: isPrivate, userAccess
- update FE to use space properties to check access
Before: non-admin users could not see the edit and delete button for SQL charts in private spaces
(right side: page from developer user)
After: user can see the edit and delete button for SQL charts in private spaces
Note: non-developers, independently of their space access, cannot see the edit button as they lack access to SQL runner.
(right side: page from developer user)

fix: SQL chart access in private spaces

---

packages/frontend/src/features/sync/components/SelectGoogleSheetButton.tsx
packages/frontend/src/hooks/gdrive/useGdrive.ts

Closes: https://github.com/lightdash/lightdash/issues/10914
At least on Firefox (popup blocker?) , the `window.close` api always returns true, which doesn't correspond what the documentation says (Related issue: https://stackoverflow.com/questions/5972164/window-open-returns-always-closed-in-true) . This was causing firefox to reopen inifnite popups. 
This was mainly to `reopen` the modal automatically if someone closed the popup. Because once it was closed, it was not possible to reopen the modal again. 
WHen clicking on the `Select Google Sheet via Google drive`, I `force` close the modal, this opens a new modal. 
Before:
[Screencast from 05-08-24 12:11:29.webm](https://github.com/user-attachments/assets/f04733f1-6f22-47c3-bdde-4a67bfde0514)
After:
[Screencast from 05-08-24 …

fix: infinite google login popup

---

packages/backend/src/clients/Slack/SlackClient.ts
packages/backend/src/clients/Slack/Slackbot.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/SlackAuthenticationModel.ts
packages/backend/src/scheduler/SchedulerTask.ts
packages/backend/src/services/SlackIntegrationService/SlackIntegrationService.ts
packages/common/src/index.ts
packages/common/src/types/errors.ts
packages/common/src/types/slack.ts
packages/common/src/types/slackSettings.ts
packages/frontend/src/components/SchedulersView/SchedulersView.tsx
packages/frontend/src/components/UserSettings/SlackSettingsPanel/index.tsx
packages/frontend/src/features/scheduler/components/SchedulerForm.tsx
packages/frontend/src/hooks/slack/useSlack.ts

Closes: https://github.com/lightdash/lightdash/issues/10473
Closes: https://github.com/lightdash/lightdash/pull/10716
if organization does not have a slack integration it throws an error when visiting integrations page and returns error 500
two routes were affected by this:
`/api/v1/slack/`
`/api/v1/slack/channels`
you can see whole bunch of sentry events here:
https://lightdash.sentry.io/issues/4521767626/events/?project=5959292&sort=-url
THIS PR IS BASED on contributions from @maxdiplogit -> https://github.com/lightdash/lightdash/pull/10716
> This PR deals with improving developer productivity by not relying on network errors on the Frontend and also not requesting /slack/channels endpoint if slack is not enabled.

fix: slack auth model throwing an error

---

packages/e2e/cypress/e2e/app/dashboard.cy.ts
packages/frontend/src/components/DashboardFilter/FilterConfiguration/index.tsx

Closes: 
A new checkbox was introduced in the filter configuration. https://github.com/lightdash/lightdash/pull/9505
Tabs are both mounted so the e2e selector was picking up that checkbox as well.
I added a test id to that tab and improved the e2e selector. Didn't want to change the tabs to have `keepMounted=false` because they store useful state when creating/editing a filter.

chore: update dashboard e2e test selectors

---

packages/cli/src/dbt/profile.ts
packages/cli/src/dbt/profiles.test.ts
packages/cli/src/dbt/templating.test.ts
packages/cli/src/dbt/templating.ts
packages/cli/src/index.ts

Closes: #10649 and #10674  
Lightdash now checks for profile.yml file in parallel logic to how dbt finds profile.yml file using following precedence.
1. `--profiles-dir` option.
2. `DBT_PROFILES_DIR` environment variable.
3. Current working directory using `process.cwd()` which gives directory from which Lightdash process is started. 
4. `~/.dbt/` directory.
note: 
`yarn link` cannot be used to do manually testing of cwd feature as using `yarn lightdash dbt run`  will change the cwd to directory in which package.json is present hence cwd feature will not work. 
`[object object]` error was occurring due to conversion of obejct to string inside `packages/cli/src/dbt/templating.ts`
Now Nunjucks template handles object and insures output is of always of expected type. 
Now `default` keyword …

feat: update profile.yml directory logic and nunjucks template

---

packages/frontend/src/components/NavBar/BrowseMenu.tsx

Closes: #10607
adds scrolling area to spaces' menu items
used this to create a mock number of spaces: 
` const mockSpaces = Array.from({ length: 40 }, () => spaces?.[0]);`
before
https://github.com/user-attachments/assets/20949a84-f128-4ae0-9f59-2769f0c52edc
after
https://github.com/user-attachments/assets/55aaf53f-f12d-4d7d-b4d1-0377fd4627f3

style: add scrollarea to spaces menu items

---

examples/full-jaffle-shop-demo/dbt/models/plan.yml
packages/cli/src/dbt/manifest.ts
packages/cli/src/handlers/compile.ts
packages/cli/src/handlers/dbt/compile.ts
packages/common/src/types/dbt.ts

Closes: #4748
- Previous implementation didn't take into account recursively joined models and also selecting/excluding models via tags instead of names.
This PR fixes that by keeping track of the visited models and by running `compile` with the passed arguments instead of `parse` this way we make sure that we get the initially compiled models at the expense of having to compile twice.
The following diff creates recursively joined models `customer -> plan -> customer` and can be used for testing
```diff
diff --git a/examples/full-jaffle-shop-demo/dbt/models/plan.yml b/examples/full-jaffle-shop-demo/dbt/models/plan.yml
index 14ae531a0..871a6cc42 100755
--- a/examples/full-jaffle-shop-demo/dbt/models/plan.yml
+++ b/examples/full-jaffle-shop-demo/dbt/models/plan.yml
@@ -4,6 +4,9 @@ models: …
```

fix: cli compile joined models

---

packages/frontend/src/components/SqlRunner/RunSqlQueryButton.tsx
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/SqlEditor.tsx
packages/frontend/src/features/sqlRunner/components/visualizations/Table.tsx

Closes: #10987 
Some sql runner style fixes:
- Disable run button when there is no query
- Fix drag handle z-index so it doesn't sit on top of modal overlay
- Center sql editor loading spinner
- Fix validation error for table header -- needed a <tr>

fix: sql runner style fixes

---

packages/common/src/types/sqlRunner.ts
packages/common/src/visualizations/CartesianChartDataTransformer.ts
packages/common/src/visualizations/PieChartDataTransformer.ts
packages/common/src/visualizations/ResultsTransformerBase.ts
packages/common/src/visualizations/SqlRunnerResultsTransformer.ts
packages/frontend/src/features/sqlRunner/components/CartesianChartFieldConfiguration.tsx
packages/frontend/src/features/sqlRunner/components/visualizations/SqlRunnerChart.tsx
packages/frontend/src/features/sqlRunner/store/barChartSlice.ts
packages/frontend/src/features/sqlRunner/store/cartesianChartBaseSlice.ts
packages/frontend/src/features/sqlRunner/store/lineChartSlice.ts
packages/frontend/src/features/sqlRunner/store/pieChartSlice.ts

Closes: #11013, #11014, #10985 
Better error handling for changing SQL queries in the SQL runner:
- First, move data merging logic to the transformer instead of the slice
- When the query is changed and there are no matching fields, reset the chart config. We're making the assumption that NO matching fields means they are making an all new query
- When the query is changed and there **are** matching fields, we will no longer reset the config. This is probably a common scenario when building real-world queries. The error messages tell the user to pick different fields and the chart gets fixed.

fix: better error handling for missing fields

---

packages/common/src/types/sqlRunner.ts
packages/common/src/visualizations/CartesianChartDataTransformer.ts
packages/common/src/visualizations/PieChartDataTransformer.ts
packages/common/src/visualizations/ResultsTransformerBase.ts
packages/common/src/visualizations/SqlRunnerResultsTransformer.ts
packages/frontend/src/features/sqlRunner/components/CartesianChartFieldConfiguration.tsx
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/visualizations/SqlRunnerChart.tsx
packages/frontend/src/features/sqlRunner/store/barChartSlice.ts
packages/frontend/src/features/sqlRunner/store/cartesianChartBaseSlice.ts
packages/frontend/src/features/sqlRunner/store/lineChartSlice.ts
packages/frontend/src/features/sqlRunner/store/pieChartSlice.ts
packages/frontend/src/features/sqlRunner/store/selectors.ts

Closes: #10983
Keeps charts mounted so it is instant switching between them. 
I can't tell, but there might be a bit of a perf problem on initial load. Is it ok? What should we do about it?

chore: sql runner - dont unmount charts

---

packages/frontend/src/components/Explorer/CustomDimensionModal/CustomBinDimensionModal.tsx
packages/frontend/src/providers/ExplorerProvider.tsx

Closes: #11057
- Fixes custom dimension id match when updating explore context
**Before**
https://github.com/user-attachments/assets/bf50607f-8de7-491b-a00d-49973892654b
**After**
https://github.com/user-attachments/assets/6bc0e6b8-8077-42ee-a681-95d57103f4de

fix: custom dimension edit not persisting

---

packages/cli/src/handlers/dbt/run.ts
packages/cli/src/index.ts

Closes: #10831
- When users run `lightdash dbt run`, `assumeYes` is currently turned on by default. So all doc finds will overwrite the existing description for a dimension/metric.
- This adds the ability to pass `--assume-yes` and if not passed, it asks the user through a prompt if they want to replace the description field with a doc block. 
Demo:
https://github.com/user-attachments/assets/e10031b5-9f5f-4d0b-a338-0c1407e33829

feat: allow for lightdash dbt run --assume-yes flag

---

packages/frontend/src/features/sqlRunner/components/CartesianChartConfiguration.tsx
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/hooks/useSavedSqlCharts.tsx

Closes: #10986, #10963 
A few small fixes for SQL runner:
- After saving a chart, the back button goes back to SQL runner
- Clear toasts on Run Query
- Style section open by default
- Margin changes

fix: sql runner fixes - back button, toasts, styles

---

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx

Closes: (https://github.com/lightdash/lightdash/issues/10819)
If we are editing chats from any dashboard, the history will include parameters like fromDashboard={dashboardId}. If we are editing chats from space, it will be null. I check if the search parameter is not null; 
If it isn’t, I redirect to the dashboard, Otherwise I redirect to the home page.
https://www.loom.com/share/2c58db6dba4647deaf8bb95685f40b1e?sid=a5f8d6a7-6f18-4caa-8c97-f16d4a82391d

fix: If a chart is deleted, It should be redirected to the dashboard

---

packages/cli/src/handlers/preview.ts
packages/cli/src/index.ts

Closes: https://github.com/lightdash/lightdash/issues/11044
Similar to `deploy` command, the preview commands will now fail if there are compile errors. 
To keep the existing behaviour, you can use the option `--ignore-errors`
Example:
```lightdash preview --ignore-errors```

feat: preview commands fail if there are compile errors

---

packages/backend/src/clients/ClientRepository.ts
packages/backend/src/clients/cube/CubeClient.ts
packages/backend/src/clients/cube/transformer.ts
packages/backend/src/clients/dbtCloud/DbtCloudGraphqlClient.ts
packages/backend/src/clients/dbtCloud/transformer.ts
packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/controllers/metricFlowController.ts
packages/backend/src/controllers/v2/SemanticLayerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/HealthService/HealthService.ts
packages/backend/src/services/SemanticLayerService/SemanticLayerService.ts
packages/common/src/types/dbtSemanticLayer.ts
packages/common/src/types/semanticLayer.ts
packages/frontend/src/features/semanticViewer/components/FieldIcon.tsx
packages/frontend/src/features/semanticViewer/components/SidebarViewFields.tsx
packages/frontend/src/features/semanticViewer/components/SqlViewer.tsx
packages/frontend/src/features/semanticViewer/store/semanticViewerSlice.ts

Closes: #11027 
- Instantiates the `DbtCloudGraphqlClient` with `lightdashConfig` and makes necessary changes so that current `dbt semantic layer` works
- Moves transformer usage into `semantic layer clients` so that we don't have to deal with returned types right now - see: [Move transformer usage out of the clients and into the service layer](https://github.com/lightdash/lightdash/issues/11082)
- Select client type depending on config
- Make adjustments to `DbtCloudGraphqlClient` so that it can be used in the service

feat: add dbt semantic layer to service

---

packages/cli/src/handlers/compile.ts
packages/cli/src/handlers/dbt/compile.ts
packages/cli/src/handlers/deploy.ts

Closes: [#4748](https://github.com/lightdash/lightdash/issues/4748) 
Reopened the ticket because it **only** worked when using "--use-dbt-list false". 
Logs when creating a preview without "--use-dbt-list false"
```
lightdash preview --project-dir ./examples/full-jaffle-shop-demo/dbt --profiles-dir ./examples/full-jaffle-shop-demo/profiles -s customers
⠴   Setting up preview environmentoptions.useDbtList true
⠼   Setting up preview environment
⠙   Setting up preview environment
- ERROR> customers : Failed to compile explore "customers". Tried to join table "membership" to "customers" but cannot find table with name "membership"
Compiled 1 explores, SUCCESS=0 ERRORS=1
⠼   Setting up preview environment
Deploying project with 1 errors
✔   Developer preview "crimson takin" ready at: …
```

fix: auto join models

---

packages/frontend/src/features/sqlRunner/hooks/useSqlQueryRun.tsx

Closes: [#11109](https://github.com/lightdash/lightdash/issues/11109)
Display error toast message by removing the invalid error message reference.

fix: display error toast on no sql runner results

---

packages/backend/src/clients/cube/CubeClient.ts
packages/backend/src/clients/cube/transformer.ts
packages/backend/src/clients/dbtCloud/DbtCloudGraphqlClient.ts
packages/backend/src/clients/dbtCloud/transformer.ts
packages/backend/src/controllers/v2/SemanticLayerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/SemanticLayerService/SemanticLayerService.ts
packages/common/src/types/semanticLayer.ts
packages/frontend/src/features/semanticViewer/api/hooks.ts
packages/frontend/src/features/semanticViewer/api/requests.ts
packages/frontend/src/features/semanticViewer/components/Content.tsx
packages/frontend/src/features/semanticViewer/components/ResultsViewer.tsx
packages/frontend/src/features/semanticViewer/components/SidebarViewFields.tsx
packages/frontend/src/features/semanticViewer/store/semanticViewerSlice.ts

Relates to: #11125 
- Adds `availableGranularities` to fields
- Uses the selected granularity when fetching results

feat: add semantic layer time granularities backend

---

packages/backend/src/clients/cube/transformer.ts
packages/backend/src/clients/dbtCloud/transformer.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/types/semanticLayer.ts
packages/frontend/src/features/semanticViewer/components/ResultsViewer.tsx
packages/frontend/src/features/semanticViewer/components/SqlViewer.tsx
packages/frontend/src/features/semanticViewer/store/semanticViewerSlice.ts

Relates to: #11033 
- Creates `SemanticLayerSortBy` type and handles it in the transformers for each semantic layer

feat: semantic layer sorting backend

---

packages/backend/src/clients/dbtCloud/DbtCloudGraphqlClient.ts
packages/backend/src/clients/dbtCloud/transformer.ts
packages/backend/src/services/SemanticLayerService/SemanticLayerService.ts
packages/common/src/types/semanticLayer.ts

Relates to: #11125 
- Pass `grain` as `null` to `GraphQL` query
- Transform `granularity` into `grain` in query

fix: pass granularity as null to graphql query

---

packages/common/src/schemas/json/lightdash-dbt-2.0.json

Closes: #11146
Related to PR: https://github.com/lightdash/lightdash/pull/11090
"groups" was defined in the wrong place in the schema causing AVJ to throw an error.
How to reproduce: 
- add groups to a dimension in orders model
```
meta:
dimension:
groups:
- product_details
```
- compile that model ```node ./packages/cli/dist/index.js generate --project-dir ./examples/full-jaffle-shop-demo/dbt --profiles-dir ./examples/full-jaffle-shop-demo/profiles -s orders```

fix: move groups property to valid structure

---

packages/backend/src/services/ProjectService/ProjectService.ts

Closes: 
We were ignoring limit passed to streamSqlQueryIntoFile. This puts back the limit wrapper.

fix: sql runner limit

---

packages/backend/src/models/SavedChartModel.ts

Closes: [#1978](https://github.com/lightdash/lightdash-internal-work/issues/1978) 
Problem occurs when a chart is updated to use a different explore has each version can have a distinct explore value. This can happen when promoting or via the API.
How to replicate:
- edit chart
- go to database and edit the first version to have the explore "banana"
- load embed dashboard / run `lightdash generate-exposures` 
You can see that this query returns 2 rows because we are grouping by explore name in the join CTE.
Fix when filtering by last version instead of a CTE in the join logic.
Problem in embed filters:
After:
Problem when generating exposures, `depends_on` is empty:
```
cd examples/full-jaffle-shop-demo/dbt
node ../../../packages/cli/dist/index.js generate-exposures
```
After:

fix: chart queries to get last version

---

packages/frontend/src/features/users/components/LoginLanding.tsx

Closes: [#11118](https://github.com/lightdash/lightdash/issues/11118) 
We were calling okta login multiple times and creating a different code/state for each call.
To test this locally run in production mode, otherwise react hooks run multiple times.
`NODE_ENV=production yarn dev`
Problem:
Fix:

fix: okta state mismatch

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/SavedSqlModel.ts
packages/common/src/types/sqlRunner.ts
packages/common/src/visualizations/CartesianChartDataTransformer.ts
packages/common/src/visualizations/PieChartDataTransformer.ts
packages/frontend/src/features/semanticViewer/transformers/useSqlChart.ts
packages/frontend/src/features/sqlRunner/components/visualizations/SqlRunnerChart.tsx
packages/frontend/src/features/sqlRunner/transformers/useSqlChart.ts

Closes: N/A
We were triggering a duck db query on any config/display change. 
We should **only** trigger a new change when the `fieldConfig` changes.
Any stylistic (`display`) changes should just mutate the echarts spec/config. 
This PR improves chart styling changes UX.
Try interacting with any input in `Styling`

perf: improve sql chart display changes

---

packages/backend/src/queryBuilder.mock.ts
packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts

Closes: https://github.com/lightdash/lightdash/issues/11070
Here in `backend/src/queryBuilder.ts`, sorting in descending order (DESC) is not implemented for `sortMonthName` and `sortDayOfWeekName`. So, I implemented DESC by checking if `sort.descending` is `true` and adding 'DESC' to the query. I also wrote test cases to verify this DESC functionality.
https://www.loom.com/share/3addfb9d5997498fb33f4fbc25b03b73?sid=8ad9bc20-2f54-4116-92f6-5f72f15e2edb

fix: day of week does not work with desc sorts

---

packages/frontend/src/components/DataViz/config/CartesianChartStyling.tsx

Closes: N/A
- removed `defaultValue` usage now that `display` changes don't trigger a new query
- if the label is `undefined` then we swap its value with the reference of the field used.
Demo: 
https://github.com/user-attachments/assets/2b73845c-19d1-4bd8-90ae-b852563dcd8f

fix: update x y labels if undefined

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

Related to: [#11047](https://github.com/lightdash/lightdash/issues/11047)
We currently generate the data for all configs when the user hits run query. 
This gives a better experience between selecting different chart types, but slows down the initial load. 
This PR tracks the active chart config and _marks it as active_ so next time the user selects that same type, it won't re-mount.
Demo
https://github.com/user-attachments/assets/293aa5f8-5837-45ec-af4d-9736e9aec1d5

perf: track active configs and render on selection

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/SqlEditor.tsx

Closes: N/A
Debounce `onChange` on SQL change.
The Monaco editor maintains its own internal state, which is always up-to-date, so we can safely debounce to improve UX

perf: debounce on sql change

---

packages/backend/src/clients/cube/CubeClient.ts
packages/backend/src/clients/dbtCloud/DbtCloudGraphqlClient.ts
packages/backend/src/controllers/v2/SemanticLayerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/SemanticLayerService/SemanticLayerService.ts
packages/common/src/types/semanticLayer.ts

- Simplifies default limit logic by extracting to a function and default it only when needed instead of trying to default in multiple places

feat: simplify limit logic and add endpoint to get the client max query limit

---

scripts/install.sh

Hello! When I executed `./scripts/install.sh`, the following error occurred.
There are two ways to run Docker on Mac: 'Docker Desktop' and 'OrbStack'.
In my environment, I use 'OrbStack'.
I think that's why the following error occurred.
> Starting Docker ...
> Unable to find application named 'Docker'
> 🔴 The containers didn't seem to start correctly. Please run the following command to check containers that may have errored out:
Modified the `scripts/install.sh` script so that it can be used by 'OrbStack' users.

fix: Unable to find application named 'Docker'

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx

Closes: #11064 
Adds a `Transition` to move from `table` view and `other charts` view
Keeps charts mounted
> [!NOTE]
> There's a table layout shift when selecting its config view. I'm aware of this but don't think it's pressing for now.

feat: hide results table when viewing table chart

---

packages/backend/src/clients/Slack/SlackMessageBlocks.ts

Closes: https://github.com/lightdash/lightdash/issues/11262
fields: [] can't be empty or ` ""` , but `" "` works.

fix: empty description on slack unfurl

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/SqlEditor.tsx

Closes: N/A
Bring back logic in `onMount` from here: https://github.com/lightdash/lightdash/pull/10740/files
To test: 
Click on Sql Editor 
use `Cmd`+`Enter` shortcut
See query run 
THis also works when the sql editor isn't focused.
demo:
https://github.com/user-attachments/assets/1dd89540-08c0-43ae-98ed-2b7616f4037c

fix: allow cmd+enter when focusing sql editor

---

packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

Closes: #11294 
Non-bar charts were not showing during editing. This adds the save chart type to the active chart types. 
Before:
After:

fix: non-bar charts not showing on edit

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/visualizations/CartesianChartDataModel.ts
packages/common/src/visualizations/TableDataModel.ts
packages/common/src/visualizations/types/index.ts
packages/frontend/src/components/DataViz/transformers/ResultsRunner.ts
packages/frontend/src/components/DataViz/transformers/useChart.ts
packages/frontend/src/components/DataViz/visualizations/ChartView.tsx
packages/frontend/src/components/DataViz/visualizations/Table.tsx
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/hooks/useChartResultsTableConfig.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

Relates to: [#11233](https://github.com/lightdash/lightdash/issues/11233)
- Removed `limit` override in button
- Allows for charts to have their own `results` table 
> [!NOTE]
> Don't have the `Allow fine-tuning the limit on the visualization` - this will be in a separate PR
Demo: 
https://github.com/user-attachments/assets/4d11f70a-11ba-40e0-9698-0935a58213e9

feat: remove limit and display chart results in chart viz

---

packages/backend/src/database/entities/analytics.ts
packages/backend/src/database/entities/savedSql.ts
packages/backend/src/database/migrations/20240829112616_add_last_viewed_sql_chart.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/AnalyticsModel.ts
packages/backend/src/models/SavedSqlModel.ts
packages/backend/src/services/SavedSqlService/SavedSqlService.ts
packages/backend/src/services/ServiceRepository.ts
packages/common/src/types/sqlRunner.ts
packages/frontend/src/features/sqlRunner/components/Header/HeaderEdit.tsx
packages/frontend/src/features/sqlRunner/components/Header/HeaderView.tsx

Closes:  https://github.com/lightdash/lightdash/issues/10829
Track when a user views an SQL chart and when the first view was.
Track user views on separatate table for usage analytics

feat: track views sql runner chart

---

packages/backend/src/controllers/sqlRunnerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/SavedSqlService/SavedSqlService.ts
packages/common/src/types/sqlRunner.ts
packages/common/src/visualizations/CartesianChartDataModel.ts
packages/common/src/visualizations/types/IResultsRunner.ts
packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx
packages/frontend/src/components/DataViz/transformers/useChart.ts
packages/frontend/src/components/DataViz/visualizations/ChartView.tsx
packages/frontend/src/features/sqlRunner/components/Header/HeaderView.tsx
packages/frontend/src/features/sqlRunner/runners/SqlRunnerResultsRunner.ts
packages/frontend/src/pages/ViewSqlChart.tsx

Closes: N/A
Can view saved sql charts:
Cannot edit saved sql chart in dashboard:
Can view saved sql charts:
Cannot edit saved sql chart in dashboard:

fix: viewers+ can view sql runner charts 

---

packages/common/src/visualizations/CartesianChartDataModel.ts
packages/common/src/visualizations/PieChartDataModel.ts
packages/common/src/visualizations/TableDataModel.ts
packages/common/src/visualizations/types/IChartDataModel.ts
packages/frontend/src/components/DataViz/transformers/getChartConfigAndOptions.ts
packages/frontend/src/components/DataViz/transformers/useChart.ts

Closes: N/A
`...DataModel`s should have a `fieldConfig` in the constructor but no `display`. the `display` should be passed to the `mergeConfig` so that we don't trigger a new query every time it changes.

perf: only trigger query when config.type/config.fieldConfig changes

---

packages/common/src/index.ts
packages/frontend/src/components/DataViz/transformers/useChart.ts
packages/frontend/src/components/DataViz/visualizations/ChartView.tsx

Closes: N/A
Now that we get the pivot results through an API endpoint, we should get the error's `message` correctly to display under the `ChartView` `SuboptimalState`
How to test: 
- Select * any table
- Run query
- Select * another table
- See error states in chart configuration + `error generating chart` with a description from the Api error.
Similar screenshot:

fix: display error message if failed

---

packages/backend/src/clients/cube/transformer.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/SemanticLayerService/Pivoting.ts
packages/backend/src/services/SemanticLayerService/SemanticLayerService.ts
packages/common/src/types/semanticLayer.ts
packages/frontend/src/features/semanticViewer/runners/SemanticViewerResultsRunner.ts

Closes: 
removes unnecessary group by and pivot with aggregations from semantic viewer pivoting functionality

fix: remove semantic viewer aggregation functions

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/visualizations/types/index.ts
packages/frontend/src/components/DataViz/config/DataVizAggregationConfig.tsx

Relates to: [#11329](https://github.com/lightdash/lightdash/issues/11329)
Removes this option. We should replace it with `ANY_VALUE` in a separate PR
https://docs.snowflake.com/en/sql-reference/functions/any_value
https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#any_value
https://www.postgresql.org/docs/16/release-16.html

chore: remove first aggregation option

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

Closes: [#11305](https://github.com/lightdash/lightdash/issues/11305)
Allows setting sql limit for visualizations. This will be shared across all visualizations **except tables** because the main sql query results will remain the same. 
demo:
https://github.com/user-attachments/assets/9be3b34a-5914-4681-b3b6-818246dd86f8

feat: allow fine tuning query limits for non-table visualizations

---

packages/frontend/src/features/semanticViewer/components/SidebarViewFields.tsx
packages/frontend/src/features/semanticViewer/components/SidebarViewFieldsGroupItem.tsx

A couple small fixes for semantic viewer:
- Search wasnt working 
- We had buttons nested in buttons, which isnt allowed and breaks accessibility

chore: fix search and dom error in semantic viewer

---

packages/common/src/visualizations/CartesianChartDataModel.ts
packages/frontend/src/components/DataViz/config/CartesianChartSeries.tsx
packages/frontend/src/components/DataViz/config/CartesianChartStyling.tsx
packages/frontend/src/components/DataViz/store/cartesianChartBaseSlice.ts

Closes: [#11345](https://github.com/lightdash/lightdash/issues/11345)
Gets `label` and `color` by checking the `yAxisIndex` - more reliable. Since these objects are usually very small, I don't see performance issues with this
Demo: 
https://github.com/user-attachments/assets/4008e3cf-5449-458a-81a6-58046cb60076

fix: allow setting labels and colours to series

---

packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx
packages/frontend/src/pages/ViewSqlChart.tsx

Closes: N/A
Before
After
Before
After

fix: pass limit to saved chart & tile

---

packages/frontend/src/components/DataViz/config/CartesianChartFieldConfiguration.tsx

Closes: https://github.com/lightdash/lightdash/issues/11326
Allow clearing the `groupBy` select when there's an error + no options to group by
The `clearable` prop only works if there's data, so if the user clicks, it will clear. 
> [!IMPORTANT]
> there should be a better way to merge configs. Currently, `mergeConfig` doesn't influence the RTK state when we edit the query/config. Therefore, the result of this should change the state `onResults`. Look into `ResultsRunner`, where it should have clear steps on how to handle this - for example, if the `groupBy`'s references aren't valid, then unset this property (to `undefined`). Since it required a wider change + `useEffect` dependencies considerations, it would mean a bigger PR. that can be handled later.
demo: …

fix: allow clearing the groupby if no options

---

packages/frontend/src/pages/ViewSqlChart.tsx

Closes: N/A
wait for `sql` before trying to display `ChartView` on `ViewSqlChart`. 
To replicate the issue **without the fix**
(keep cache, don't disable it)
- Go to chart A
- Click on breadcrumb to Space
- Go back to chart
Because the SQL was empty.
This is in between states and store initialisations. Since `ChartView`'s prop `sql` is intentionally optional, it led to this error.
Now all is well.

fix: wait for sql before viewing sql chart

---

packages/frontend/src/features/semanticViewer/components/Content.tsx
packages/frontend/src/features/semanticViewer/components/SqlViewer.tsx

Fix some visual bugs in semantic viewer:
1. Don't show 'sort by' when there is nothing to sort by
2. Change loader zIndex to avoid this:

chore: fix semantic viewer zIndex and empty sort

---

packages/frontend/src/features/sqlRunner/components/Header/HeaderEdit.tsx

Closes: N/A
Adds loading state to this save button:
Moves `onClick` to the ActionIcon instead of the icons

chore: add loading state when saving  chart changes

---

packages/backend/src/services/SemanticLayerService/Pivoting.ts
packages/common/src/types/semanticLayer.ts
packages/common/src/visualizations/TableDataModel.ts
packages/common/src/visualizations/types/IResultsRunner.ts
packages/frontend/src/components/DataViz/transformers/ResultsRunner.ts
packages/frontend/src/components/DataViz/transformers/useTableDataModel.ts
packages/frontend/src/features/semanticViewer/runners/SemanticViewerResultsRunner.ts

Closes: 
This PR fixes 2 issues:
- Depending on the warehouse, the column names might not match the field name casing, so we need to match the column names to field names to avoid this
- We removed aggregations, so we cannot use the same query to fetch results for the visualizations, this is because it might contain more columns than the fields selected in the chart config and therefore it would brake the viz.
**Before**
Notice the lack of x-axis label
**After**

fix: result cols mapping and query when fetching pivoted results

---

packages/frontend/src/features/semanticViewer/components/Content.tsx

Updates the copy on the empty state for the semantic viewer

chore: update copy on empty state

---

packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.mock.ts
packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.test.ts
packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts

Related: [#11312](https://github.com/lightdash/lightdash/issues/11312)
Use the same Bigquery client with the same credentials and configuration.
Dataset/table references can still be configured to point to a different database(aka project).
This is in preparation for #11312.
SQL runner queries and sidebar working as expected.

chore: reuse Bigquery client

---

packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx

Closes: [](https://github.com/lightdash/lightdash/issues/11426)
Uses `LinkMenuItem` to open in new tab

feat: open edit sql chart in new tab - dashboard

---

packages/common/src/visualizations/CartesianChartDataModel.ts
packages/frontend/src/components/DataViz/config/CartesianChartSeries.tsx
packages/frontend/src/components/DataViz/store/cartesianChartBaseSlice.ts

Closes: #11425
- Hide legend if only on y axis fieldConfig
- When from 1 series to 2, then clear to default on series 1
- When only 1 series + when setting a label for `y` axis, then that will change the series label as well 
recording:
https://github.com/user-attachments/assets/f79fc029-130a-44c7-94c7-d91baee8a13f

fix: set series labels depending on field config `y`

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/visualizations/types/index.ts
packages/frontend/src/components/DataViz/visualizations/Table.tsx

Closes: N/A
Allow saving table viz config.
To replicate: 
- Run a query
- Go to `Chart`
- Choose Table viz type
- Hide some tables etc
- Save
Should see that reflected on the saved chart. 
> [!NOTE]
> I know there's an issue with the table rendering when it doesn't have many columns visible. Tracking here: https://github.com/lightdash/lightdash/issues/11458

fix: allow saving columns config on save

---

packages/frontend/src/features/semanticViewer/components/Content.tsx

Makes the semantic layer sort buttons gray. This is probably not their final form, but we are making them more subtle for the demo.

chore: make semantic layer sort buttons gray

---

packages/backend/src/models/WarehouseAvailableTablesModel/WarehouseAvailableTablesModel.ts

Closes: #11383
Knex throws on empty insert rows: https://github.com/lightdash/lightdash/issues/11434
**Updated wiki**: https://www.notion.so/lightdash/Knex-6a3615a169044daeaa7a54465c631960
User complained about receiving this error, which is a combination of this bug and https://github.com/lightdash/lightdash/issues/11434

fix: check for empty rows when updating warehouse available tables

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/SqlEditor.tsx

Closes: [#11270](https://github.com/lightdash/lightdash/issues/11270)
Increased padding top for sql editor & subtle highlight on line

style: highlight on sql editor line and up padding top

---

packages/frontend/src/components/DataViz/hooks/useChartViz.ts
packages/frontend/src/features/semanticViewer/components/ContentCharts.tsx

Fixes the loading state when interacting with charts. Use isFetching instead of isLoading on updated chart queries.

chore: fix chart loading in semantic viewer

---

packages/backend/src/services/PromoteService/PromoteService.mock.ts
packages/backend/src/services/PromoteService/PromoteService.test.ts
packages/backend/src/services/PromoteService/PromoteService.ts

Closes: [#11469](https://github.com/lightdash/lightdash/issues/11469) 
Testing promoting with user that has access in downstream project but not upstream project

feat: copy access when promoting new private space

---

packages/frontend/src/components/DataViz/visualizations/Table.tsx
packages/frontend/src/components/common/Page/Page.tsx
packages/frontend/src/components/common/Page/Sidebar.tsx
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/Sidebar.tsx
packages/frontend/src/features/sqlRunner/components/TablesPanel.tsx
packages/frontend/src/pages/SqlRunnerNew.tsx

Closes: [#11273](https://github.com/lightdash/lightdash/issues/11273)
Header groups (table column names) are now `13px`
Resize handlers are shorter + have a grip icon
`Page` can now take `sidebarProps` which is basically being passed, for now, as the `cardProps` - no other place in the app was using this prop so I rewrote that. 
Screenshot: 
https://github.com/user-attachments/assets/999c6dc9-f2fa-4355-9b25-5d34dfcfa49a

style: improve resize handlers design & spacings

---

packages/frontend/src/features/sqlRunner/components/Sidebar.tsx

Closes: N/A
Relates to: https://github.com/lightdash/lightdash/pull/11481
Adds `px` to viz config panel
before: 
after:

style: add px to viz panel

---

packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx
packages/frontend/src/components/common/ResourceView/ResourceActionHandlers.tsx
packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx
packages/frontend/src/features/sqlRunner/components/Header/HeaderView.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

Closes:  https://github.com/lightdash/lightdash/issues/11390
[Screencast from 10-09-24 09:30:26.webm](https://github.com/user-attachments/assets/36533b59-8acf-4257-acc3-025cd5ec209d)

feat: add sql chart to dashboard

---

packages/frontend/src/components/DataViz/hooks/useChartViz.ts
packages/frontend/src/features/semanticViewer/components/ContentCharts.tsx

Closes: #11490 
- Refetch chart data on sort and query change. This updates query keys based on fitler and sort updates. Note that the hook itself doesn't get the sorts or filters directly, but now exposes a cache key that can be updated. This is because the useChartViz can be used in multiple places and shouldnt rely on page-specific types
This handles charts and and I'm posting it so we could use it for the demo. More to do:
- Tables don't go through this useQuery so don't get updated with this cache key. To update them, the query needs to be run again
- Filters get updated too often, it should only be on apply. I'm working on this.

chore: refetch data on sort or filter in semantic viewer

---

packages/frontend/src/pages/ViewSqlChart.tsx

Closes: #11210 
Display pivoted table for non-table sql charts in view mode

feat: show pivoted results for non-table sql chart view

---

packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx
packages/frontend/src/features/sqlRunner/hooks/useDashboardSqlChart.tsx
packages/frontend/src/features/sqlRunner/hooks/useResultsFromStreamWorker.tsx
packages/frontend/src/features/sqlRunner/hooks/useSqlChartResults.ts
packages/frontend/src/features/sqlRunner/hooks/useSqlQueryRun.tsx

Closes: #11494
Runs `getResultsFromStream` in a worker 
Virtualises Table rows in Dashboard SQL tiles

perf: use web workers to get results from stream

---

packages/frontend/src/features/semanticViewer/components/FiltersModal/index.tsx
packages/frontend/src/features/semanticViewer/store/semanticViewerSlice.ts

Closes: #11490 
In the semantic layer, don't apply filters until the Apply button is clicked

chore: dont update filters until apply on semantic viewer

---

packages/frontend/src/components/Explorer/ResultsCard/UrlMenuItems.tsx
packages/frontend/src/components/SimpleTable/MinimalCellContextMenu.tsx
packages/frontend/src/components/SimpleTable/index.tsx
packages/frontend/src/components/common/Table/ScrollableTable/BodyCell.tsx
packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx

Closes: [#11292](https://github.com/lightdash/lightdash/issues/11292) 
Show minimal table cell context for mobile page and embed. 
Mobile (load the Lightdash home page in a small browser window and then navigate to a dashboard):
Embed: ( FYI: you can't test this in this repo but also uses `minimal=true`)

fix: show minimal table cell context menu

---

packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/CreateGroupModal.tsx

Closes: #11495 
This pull request addresses an issue where the MultiSelect dropdown for `Group Members` would cover the save button, leading to a poor user experience. Users were often confused and accidentally clicked the 'X' button instead of saving their changes.

fix: changed dropdown position to top

---

packages/frontend/src/components/common/Filters/index.tsx

Closes: #11298 
This PR introduces a new "Clear All" button next to the existing "Add Filter" button in the filters section. The button allows users to clear all active filters with a single click, improving the overall user experience by simplifying the filter reset process.
Currently, users must remove filters one by one, which can be cumbersome. This new feature streamlines that workflow by adding a convenient option to clear all filters at once.
The filters section does not have an option to clear all filters, requiring users to manually remove each filter individually.
With the "Clear All" button, users can clear all active filters with one click, making the process faster and more efficient.
https://github.com/user-attachments/assets/d9d3094e-a091-4e08-b086-ff092d6c6113

feat: added clear all filters button

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/visualizations/CartesianChartDataModel.ts
packages/frontend/src/components/DataViz/config/CartesianChartStyling.tsx
packages/frontend/src/components/DataViz/store/cartesianChartBaseSlice.ts

Prevents x-axis from returning to `CATEGORY` type when updating the xaxis label

fix: fix xAxisLabel setter, not set axis type

---

packages/frontend/src/components/common/Filters/FilterGroupForm.tsx
packages/frontend/src/components/common/Filters/index.tsx

Closes: 
For more advanced filter logic, users need multiple levels of groups.
Example:
```
in the last 30 days 
AND (
(
day IN (1, 30)
AND value > X
)
OR day NOT IN (1, 30)
)
```
We only allowed for 1 level which was a blocker for such logic. 
We are now allowing 2 levels as it solves most of the use cases and doesn't break the UI.

feat: allow for two levels of filter groups

---

packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/pages/ViewSqlChart.tsx

Closes: N/A
Now that we `keepPreviousData`, we should track the loading state with `isFetching`
https://github.com/user-attachments/assets/00b7b654-188e-4f29-8d1a-e30a307a4cd0

fix: use isFetching to display loading state

---

packages/backend/src/controllers/sqlRunnerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/index.ts
packages/common/src/types/featureFlags.ts
packages/common/src/types/sqlRunner.ts
packages/common/src/utils/customExplore.ts
packages/frontend/src/features/sqlRunner/components/Header/HeaderCreate.tsx
packages/frontend/src/features/sqlRunner/components/SaveCustomExploreModal.tsx
packages/frontend/src/features/sqlRunner/hooks/useCustomExplore.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

Closes: #11557
- Hides this feature behind a feature flag
- Allows users to save sql runner queries as explores to be used when querying from tables
- Can go to explore and query dimensions, create custom metrics, and also save charts!
Limitations
- Can't edit 
- When clicking `refresh dbt`, it clears the saved explores
- Missing some core features
> [!IMPORTANT]
> This doesn't cover **everything** on the issue, but this is for demo purposes. The scope has been verified by @owlas.
Demo: 
https://github.com/user-attachments/assets/4d245988-7b78-4191-b0e8-518b18260c42

feat: enable saving sql runner model

---

packages/frontend/src/components/DataViz/store/actions/commonChartActions.ts
packages/frontend/src/components/DataViz/store/barChartSlice.ts
packages/frontend/src/components/DataViz/store/lineChartSlice.ts
packages/frontend/src/components/DataViz/store/pieChartSlice.ts
packages/frontend/src/components/DataViz/store/tableVisSlice.ts
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts
packages/frontend/src/pages/SqlRunnerNew.tsx
packages/frontend/src/pages/ViewSqlChart.tsx

Closes: N/A
Reset chart-related slices on unmount. The current `resetState` doesn't reset chart-related slices on `unmount`

fix: reset chart configs on unmount of create and view

---

packages/backend/src/database/pagination/index.ts

Closes:  #11496
By removing select and group, we are not filtering out duplicated data on the results, so the count can be innacurate. The worst thing is that this bug is hard to catch, and it will depend on the `query` que pass as parameter. We need a solution that is consistent and error-proneless
Replace the count custom query with a CTE that simply counts all the results in the original subquery. Hopefully, this is more generic and less hacky. 
This is virtually running the same query twice, one just for counting results. However, this is not different to what we had previosly anyway...
An alternative option is to get all the results from the query, count and filter on javascript, this is potentially more memory heavy and not a big improvement...

fix: total count pagination bug

---

packages/common/src/visualizations/CartesianChartDataModel.ts
packages/common/src/visualizations/PieChartDataModel.ts
packages/common/src/visualizations/types/IResultsRunner.ts
packages/common/src/visualizations/types/index.ts
packages/frontend/src/components/DataViz/config/CartesianChartFieldConfiguration.tsx
packages/frontend/src/components/DataViz/config/PieChartConfiguration.tsx
packages/frontend/src/components/DataViz/store/actions/commonChartActions.ts
packages/frontend/src/components/DataViz/store/barChartSlice.ts
packages/frontend/src/components/DataViz/store/cartesianChartBaseSlice.ts
packages/frontend/src/components/DataViz/store/lineChartSlice.ts
packages/frontend/src/components/DataViz/store/pieChartSlice.ts
packages/frontend/src/components/DataViz/store/selectors.ts
packages/frontend/src/components/DataViz/transformers/ResultsRunner.ts
packages/frontend/src/components/DataViz/transformers/getChartConfigAndOptions.ts
packages/frontend/src/features/sqlRunner/components/ChartErrorsAlert.tsx
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/Header/HeaderCreate.tsx
packages/frontend/src/features/sqlRunner/components/Header/HeaderEdit.tsx
packages/frontend/src/features/sqlRunner/components/Header/HeaderView.tsx
packages/frontend/src/features/sqlRunner/components/SaveSqlChartModal.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

Relates to: https://github.com/lightdash/lightdash/issues/11486
Keeps track of errors in chart config (specifically for bar, line, and pie)
Alerts the user that the chart is invalid and tells them to fix them before saving, preventing the saving of invalid chart configs. With this, I've also improved the error tracking on the form. We generate/check for errors every time there's a new query/sql.
**Create action**
https://github.com/user-attachments/assets/4fac5dc1-71ab-42d4-a09a-7741c6173ebd
**Edit action**
https://github.com/user-attachments/assets/e70d17d2-e7be-4642-ab41-251ec936c674

feat: display chart errors on save/edit if invalid

---

packages/backend/src/models/DashboardModel/DashboardModel.test.ts
packages/backend/src/models/DashboardModel/DashboardModel.ts
packages/backend/src/models/SavedChartModel.ts
packages/backend/src/models/SavedSemanticViewerChartModel.ts
packages/backend/src/models/SavedSqlModel.ts
packages/backend/src/models/SpaceModel.ts
packages/backend/src/utils/SlugUtils.ts

Closes: #11616
Now saving a chat/space/dashboard with the same name doesn't generate a duplicated slug 
Before
[Screencast from 20-09-24 15:40:08.webm](https://github.com/user-attachments/assets/01a75a82-68df-4e2a-8cfa-5f99a9e83f34)
After
[Screencast from 20-09-24 15:43:12.webm](https://github.com/user-attachments/assets/050d3c75-ba5e-4bfe-b971-48ce69a14021)
[Screencast from 20-09-24 15:46:50.webm](https://github.com/user-attachments/assets/8d0959ce-8e38-48d4-945d-9b930aa342cf)
[Screencast from 20-09-24 15:48:34.webm](https://github.com/user-attachments/assets/cd3afc42-6166-401d-bcee-827afe053bd2)
Also, as expected, when creating a preview project and copying content, we copy the same slug, this is required for promotion to work correctly.

fix: avoid duplicating slugs on all charts, dashboards and spaces

---

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx

Closes:  #11617
> Since we don't delete orphan charts within dashboards anymore, it is impossible to delete a chart that was removed from a dashboard.
This is particularly annoying if this chart has validation errors

fix: allow deletion of charts within dashboards

---

packages/frontend/src/components/Explorer/ResultsCard/QuickCalculations.tsx

Closes:  #11586
I tried replicating on snowflake, bigquery and postgres, and I couldn't, even when using INT
It is possible this is only affecting redshift, or some specific versions. In any case, I added a casting for all warehouses. 
[Screencast from 19-09-24 15:50:56.webm](https://github.com/user-attachments/assets/2c9546d0-204e-49ad-9898-80e1f58f45bf)
I don't think we need to update the docs , having this feature.

fix: cast float on quick table calculations

---

packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx

Closes: https://github.com/lightdash/lightdash/issues/11629
Add query keys to `useChartViz` dashboard sql tiles: uuid & slug
Add query keys to `useChartViz` to Content panel charts: `sql` 
This ensures we don't return cached data for different charts, by applying unique query keys.

fix: add additional query key to dashboard sql tile

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/SqlEditor.tsx

Closes: [#11282](https://github.com/lightdash/lightdash/issues/11282)
When CMD + Enter was pressed fast enough when writing a query, the previous value (before debounce) was sent. 
This has been fixed by directly passing the current value only when CMD + Enter is pressed, since it should not wait for debounce.

fix: cmd + enter in sql-runner submits correct values if pressed before debounce

---

packages/frontend/src/components/DataViz/store/tableVisSlice.ts
packages/frontend/src/features/semanticViewer/components/Content.tsx
packages/frontend/src/features/semanticViewer/components/SaveChart/SemanticViewerSaveChartContent.tsx
packages/frontend/src/features/semanticViewer/components/SaveChart/SemanticViewerSaveChartModal.tsx
packages/frontend/src/features/semanticViewer/store/semanticViewerSlice.ts

Closes: #11455 
- Allows selected chart kind to be `undefined` (this reflects a bit better when a user hasn't clicked the chart tab)
- If chart kind is undefined when saving, use table chart kind

feat: save table when viz tab hasn't been clicked

---

packages/frontend/src/components/DashboardFilter/FilterConfiguration/TileFilterConfiguration.tsx

Adds a "Select all" checkbox to the filter "Chart tiles" dropdown/dialog when using tabbed dashboards. Non-tabbed dashboards already have this checkbox.
**All selected**
**All de-selected**
**Mixed selected**
**FYI, indentation formatting changed many lines. Before formatting:**

feat: select all for tabbed dashboard filters

---

.github/CONTRIBUTING.md
.github/workflows/test-easy-install.yml
docs/docs/self-host/self-host-lightdash-docker-compose.mdx
scripts/install.sh

Closes: #11532 
This PR updates the Docker setup script to replace the deprecated `docker-compose` command with the `docker compose` syntax, as `docker-compose` is no longer supported in newer versions of Docker. Additional changes include the removal of the old Docker Compose installation step and a check_docker_version
This ensures that the installation process is aligned with the current Docker architecture and reduces issues for users running the latest versions of Docker.

fix: updated install scripts to docker compose

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/types/savedCharts.ts
packages/common/src/visualizations/CartesianChartDataModel.ts
packages/frontend/src/components/DataViz/config/CartesianChartFieldConfiguration.tsx
packages/frontend/src/components/DataViz/config/CartesianChartSeries.tsx
packages/frontend/src/components/DataViz/config/CartesianChartStyling.tsx
packages/frontend/src/components/DataViz/config/CartesianChartTypeConfig.tsx
packages/frontend/src/components/DataViz/store/cartesianChartBaseSlice.ts
packages/frontend/src/features/sqlRunner/components/Sidebar.tsx

Closes: [#11638](https://github.com/lightdash/lightdash/issues/11638)
- Can change the chart type of each series
- It's quick 
- When you have 2 series and then delete one, it resets the chosen chart type to ensure the visualization matches. The user can just switch the base chart type as they wish. 
Demo:
https://github.com/user-attachments/assets/70e699ce-3ccb-4222-a25d-5a1ea3e9c88a

feat: allow changing the chart type of each series

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/Download/ResultsDownload.tsx
packages/frontend/src/features/sqlRunner/hooks/useDownloadResults.tsx

Closes: https://github.com/lightdash/lightdash/issues/11643
When on the SQL tab or when visualising a Table, users can: 
- Apply a custom limit to their query so that they can download the results as csv
Recording:
https://github.com/user-attachments/assets/400bc98d-4c6b-4044-a2bf-2124387421da

feat: allow setting custom sql on results download

---

packages/frontend/src/features/sqlRunner/components/SqlEditor.tsx
packages/frontend/src/features/sqlRunner/store/history.ts
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts
packages/frontend/src/pages/SqlRunnerNew.tsx

Closes: #11677
Stores warehouse connection in sql runner slice.
Passes the warehouse connection to `sql-formatter`'s `format.language`
If there's a format error, it doesn't normalise/format the sql, leaving it up to the user to fix the query (they will see an error from the error toast if they run an invalid sql query anyway)
Screenshots with different warehouse connections (tested when creating and also editing a chart)
go to this render env without this change: https://lightdash-pr-11676.onrender.com/projects/85ef7207-b1d4-4d0c-82c7-edb93bded560 and in the snowflake project, paste this: 
```sql
SELECT * FROM "SNOWFLAKE_DATABASE_STAGING"."JAFFLE"."CUSTOMERS"
WHERE customer_id = 'C123'
AND (
SELECT COUNT(*) FROM "SNOWFLAKE_DATABASE_STAGING"."JAFFLE"."ORDERS"
WHERE customer_id = …
```

fix: get correct language and not throw error if format fails

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx

Closes: N/A
Removes `sql` from `useChartViz`'s queryKey when in `ContentPanel` - this was leading to a new query run on every sql change

fix: remove query key sql from useChartViz

---

packages/backend/src/scheduler/SchedulerTask.test.ts
packages/backend/src/scheduler/SchedulerTask.ts

Closes: #11229 
This PR improves error messaging for threshold alerts when queries return insufficient results. It explicitly distinguishes between cases where the query returns zero rows or just one row (when more are required). This helps users understand why an alert failed and guides them to adjust their queries accordingly.

fix: clarify threshold alerts errors when it doesn't have enough results

---

packages/backend/src/models/SpaceModel.ts

Relates to: #11367
Fixes the `uuid` column reference so users can add charts to dashboards from the resource actions (which get `uuid` and not the `slug`)
Before
https://github.com/user-attachments/assets/80e28361-432b-46e8-a0fd-82812cef2ae1
After
https://github.com/user-attachments/assets/b7939b04-5701-409b-a8a5-91b89f677e64

fix: get correct uuid column for resource actions

---

packages/backend/src/services/SavedSemanticViewerChartService/SavedSemanticViewerChartService.ts
packages/backend/src/services/SearchService/SearchService.ts
packages/backend/src/services/SemanticLayerService/SemanticLayerService.ts
packages/common/src/authorization/organizationMemberAbility.test.ts
packages/common/src/authorization/organizationMemberAbility.ts
packages/common/src/authorization/projectMemberAbility.test.ts
packages/common/src/authorization/projectMemberAbility.ts
packages/common/src/authorization/types.ts
packages/frontend/src/components/DashboardTiles/DashboardSemanticViewerChartTile.tsx
packages/frontend/src/features/semanticViewer/components/Header/HeaderView.tsx
packages/frontend/src/features/semanticViewer/components/Sidebar.tsx
packages/frontend/src/pages/SemanticViewerEdit.tsx

Closes: #11592
- Adds permissions for `Semantic Viewer` access
**Acceptance criteria**
**interactive viewer with editor access to chart space**
**interactive viewer**

feat: add semantic viewer permissions

---

packages/frontend/src/components/Explorer/SqlCard/OpenInSqlRunnerButton.tsx
packages/frontend/src/features/metricFlow/components/MetricFlowSqlCard.tsx
packages/frontend/src/pages/SqlRunnerNew.tsx

Closes: #11628
- when "Open in SQL runner" is clicked in an Explore chart it now goes to the new runner, passing the sql to it

feat: redirect sql runner to new runner

---

packages/common/src/types/pivot.ts
packages/frontend/src/components/SimpleTable/index.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/GeneralSettings.tsx
packages/frontend/src/components/common/LightTable/index.tsx
packages/frontend/src/components/common/PivotTable/ValueCellMenu.tsx
packages/frontend/src/components/common/PivotTable/index.tsx
packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
packages/frontend/src/hooks/pivotTable/pivotQueryResults.test.ts
packages/frontend/src/hooks/pivotTable/pivotQueryResults.ts
packages/frontend/src/hooks/tableVisualization/getDataAndColumns.tsx
packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
packages/frontend/src/types/table-core.d.ts

Closes: https://github.com/lightdash/lightdash/issues/10267
Adds row grouping and subtotal functionality to Pivot Tables. Pivot Table and non-Pivot Table components have distinct implementations, and ideally we'd like to combine them. This code does not do that. Instead, it keeps them separate. The underlying Pivot Table data structures have been "retrofitted" rather than rewritten at this time. I think that task is better done in the future when combining the two components, to avoid too much wasted effort.

feat: pivot table row grouping and subtotals

---

packages/backend/src/services/UserService.test.ts
packages/backend/src/services/UserService.ts

Closes:  #11708
How to replicate: 
- with `export ALLOW_MULTIPLE_ORGS=false` 
- create a new account using /register
- You will get an error (no other orgs can be created) , this is expected
- Now invite this user to your org.
- You will not see the invite in your users page, and no org will be created :fire: 
Before: 
[Screencast from 30-09-24 09:14:15.webm](https://github.com/user-attachments/assets/efe91454-0f7a-44ef-ac3a-70ed6508137e)
After:
[Screencast from 30-09-24 09:23:11.webm](https://github.com/user-attachments/assets/8e245dac-8058-4d73-83fc-691333706963)

fix: invite user with no org

---

packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/common/src/types/projects.ts

Closes: #11627
- Saved sql-runner charts now properly get duplicated in to the preview environment.

fix: copy sql runner content with preview env

---

.github/workflows/e2e-tests.yml
packages/backend/src/models/DashboardModel/DashboardModel.mock.ts
packages/backend/src/models/DashboardModel/DashboardModel.test.ts
packages/backend/src/models/DashboardModel/DashboardModel.ts
packages/backend/src/services/DashboardService/DashboardService.ts
packages/common/src/types/dashboard.ts
packages/e2e/cypress.config.ts
packages/e2e/cypress/e2e/app/sqlRunnerNew.cy.ts
packages/e2e/dockerfile
packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx
packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx
packages/frontend/src/components/common/ResourceIcon/index.tsx
packages/frontend/src/hooks/dashboard/useDashboard.ts
packages/frontend/src/hooks/dashboard/useDashboards.tsx

Closes: #11726 
- Disables dashboard select items when dashboard has tiles from a different semantic layer (adding charts via chart view/list menus)
- Disables chart select items when dashboard has tiles from a different semantic layer (adding charts from dashboard view)

feat: show disabled items when diff semantic layers

---

docs/docs/references/chart-types.mdx

removes sentence saying that subtotals don't work on pivot tables.

docs: Update chart-types.mdx

---

packages/frontend/src/components/SettingsSemanticLayer/DbtSemanticLayerForm.tsx
packages/frontend/src/components/SettingsSemanticLayer/index.tsx

Closes: 
https://github.com/user-attachments/assets/3c9b0789-9844-4c4f-9e15-b0f9ea33b5fb

feat: semantic layer config loading and success states

---

packages/e2e/cypress/e2e/app/explore.cy.ts

Closes: N/A
Gets sql from explore and from the new sql runner and then compares them
test-cli  
test-frontend  
test-backend

test: fix sql runner redirect in `explore.cy.ts`

---

packages/common/src/utils/email.test.ts
packages/common/src/utils/email.ts

Closes: https://github.com/lightdash/lightdash-internal-work/issues/2099
This fixes a security vulnerability where malicious users could sign up with an account which could be classed as another organisations email, therefore joining that organization if the "let users with this domain" setting is enabled. As emails can contain more than one emails an email such as `"@organization.com@"@gmail.com` would with the old code be classed as organization.com
This bug hasn't been tested as I don't have a spare email server but in theory looking at this code there is no reason why this wouldn't work.
https://stackoverflow.com/questions/12355858/how-many-symbol-can-be-in-an-email-address

fix: Improve domain check in emails 

---

packages/backend/src/controllers/exploreController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/ProjectModel/ProjectModel.test.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/models/SearchModel/index.ts
packages/backend/src/services/CatalogService/CatalogService.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/ValidationService/ValidationService.ts
packages/common/src/types/explore.ts
packages/common/src/utils/customExplore.ts
packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
packages/frontend/src/components/ProjectTablesConfiguration/ProjectTablesConfiguration.tsx
packages/frontend/src/features/sqlRunner/components/CreateVirtualViewModal.tsx
yarn.lock

Closes: [#11749](https://github.com/lightdash/lightdash/issues/11749)
This PR allows the persistence of `virtual views`/`custom explores` when the user refreshes dbt.
It also moved these below all _default_ explores

fix: persist virtual views when refreshing dbt

---

packages/backend/src/controllers/exploreController.ts
packages/backend/src/controllers/sqlRunnerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/sqlRunner.ts
packages/common/src/utils/virtualView.ts
packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/Header/HeaderVirtualView.tsx
packages/frontend/src/features/sqlRunner/components/Header/index.tsx
packages/frontend/src/features/sqlRunner/components/SqlQueryBeforeSaveAlert.tsx
packages/frontend/src/features/sqlRunner/hooks/useVirtualView.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts
packages/frontend/src/pages/SqlRunnerNew.tsx

Closes: [#11794](https://github.com/lightdash/lightdash/issues/11794)
This PR: 
- Adds a new endpoint (`virtual-view/name`) to update a virtual view
- Updates it in the new explores-related tables
- Opens a modal and lazy loads Sql Runner in the Explore panel
- Alerts the user if there are unsaved changes and to confirm the closing of the modal - this can be refined later
- **doesn't** allow editing the name - that can be done later IMO
- Hides some components in the sql runner, depending on the `mode` - default or virtual view
- If the user has `unrunChanges`, then it will run a query with limit 1 just to get the schema correctly from the warehouse.
- It doesn't have proper error handling yet, tickets below will cover what's remaining: 
on broken content: …

feat: allow editing a virtual view in explore view

---

packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
packages/frontend/src/features/sqlRunner/components/EditVirtualViewModal.tsx

Closes: #11830 
Refactored modal to listen to modal step changes (now there's 3)
Center modals that provide warnings
Clear unsaved chart version if the user wants to discard them and continue editing the virtual view
Demo:
https://github.com/user-attachments/assets/5a0f94fb-5ebd-4630-a9fa-c575a1dcad5c

feat: warn users that changes will be discarded before editing

---

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Grid/index.tsx

Closes: #11850
Before:
After:
Note: this makes the padding of fixed instead of %, which means that when a chart tile is bigger the padding will be the same, previously it got bigger

fix: add 25px padding to grid instead of 5%

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/authorization/organizationMemberAbility.ts
packages/common/src/authorization/projectMemberAbility.ts
packages/common/src/authorization/types.ts
packages/frontend/src/components/Explorer/ExplorePanel/index.tsx

Closes: N/A
Manage permissions by adding a new ability 
`>= developers can manage virtual views`

fix: hide edit/delete virtual view if no permission to

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/authorization/projectMemberAbility.ts

Closes: #11876 
From the docs page, a project admin should be able to create project previews: https://docs.lightdash.com/references/roles/#organization-roles
**Before**
**After**
1. Create a user that has `member` role at the org level and `admin` at the project level
2. Run `lightdash preview` with that user

fix: project admin can create preview projects

---

packages/warehouses/src/warehouseClients/PostgresWarehouseClient.test.ts
packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts

Closes: https://github.com/lightdash/lightdash/issues/11885
Previously we were querying `pg_catalog.pg_matviews` without checking first for the PG version.
`pg_matviews` is only available from PostgreSQL >= 12: https://www.postgresql.org/docs/current/view-pg-matviews.html
Logs added for debug purposes:
**PG 11 (doesn't support matviews)**
**PG 15 (supports matviews)**

fix: check for pgversion before querying for matviews

---

packages/frontend/src/hooks/useExplorerRoute.ts

Closes: https://github.com/lightdash/lightdash/issues/11710
What was happening: adding pivots was causing a really long metricquery, and we were adding all the series config into the URL 
What's new: We check the URL, if it is bigger than `3000` chars (just on queyr parameters) (limit seems to be ~4000 , including the host+path) then we remove the `series from the metric query config`
Expected side effect: CUstom configuration on series (eg: color, value labels, mixed chart types...) will be lost after refreshing. 
Alternative solutions: If we don't want to lose information (custom serie config), we will have to store it somewhere, perhaps in local storage, or save a draft in the backend . I don't think this needs to be done, the side effect is very small. 
How to test: 
- go to an …

fix: reduce url on explore

---

packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts

Closes: #11867 
When we remove `project` from `profiles.yml` the BigQuery client will authenticate using the default project set in the config, the way that this is done is that the `projectId` property of `BigQuery` client is supposed to be interpolated and therefore it is `{{ projectId }}` when there's no explicit project to initialize the client with.
When we create the `Dataset` we already pass an explicit `projectId` which comes from the compiled model so we don't need to try and pick up the `projectId` from `BigQuery` client but can instead pick it from the `dataset`
1. Set your `profiles.yml` to use BigQuery with `oauth`
2. Set your default gcloud project using `gcloud config set project <project_id>`
3. Remove `project` from `profiles.yml` so that it uses …

fix: set metadata project from the Dataset instead of BigQuery client

---

packages/backend/src/models/ProjectModel/ProjectModel.ts

Closes: [#11904](https://github.com/lightdash/lightdash/issues/11904)
Now removes the explore correctly - query was incorrect.
To test: 
- create virtual view
- delete it
- should return back to `/tables` with the virtual view deleted

fix: improve query for removing specific explore from cached_explores

---

packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
packages/frontend/src/features/virtualView/components/EditVirtualViewModal.tsx
packages/frontend/src/features/virtualView/components/HeaderVirtualView.tsx

Closes: #11908
Clears the `are you sure...` modal and disallows closing the modal on click outside and on close button. 
Brings back `unrunChanges` boolean just to deal with the enabling/disabling of the save button.
Demo:
https://github.com/user-attachments/assets/0210aa14-2347-415a-84be-421616bab69d

feat: polish save changes flow in virtual view modal

---

packages/e2e/cypress/e2e/app/downloadCsv.cy.ts

Closes: N/A
After this merge: https://github.com/lightdash/lightdash/pull/11873/files#diff-911ad724a0c3e0f6738ce95dbf521028bdeefb7c83eeb0fb188b92ac87e3158a 
The test to download a chart tile csv in a dashboard broke bc the endpoint is slightly different.
test-frontent
test-backend

test: use correct endpoint for download csv chart in dashboard

---

packages/frontend/src/hooks/useExplorerRoute.ts

Closes: [#11913](https://github.com/lightdash/lightdash/issues/11913)
1. Click on "Query from tables"
2. Select a table and some fields (don't click "Run Query")
3. Copy the link at the top, when opened it should have the same state

fix: update explore when metric query changes instead of on success

---

packages/frontend/src/features/sqlRunner/components/SqlEditor.tsx

Closes: #11325
> [!NOTE]
> We only _worry_ about a new sql query, bc when the user wants to edit a sql chart, the tab that is enabled on page load is the Chart/vis, not the sql editor.
Before
https://github.com/user-attachments/assets/670d5628-d788-4b98-bcef-fb7cedc896ec
After
https://github.com/user-attachments/assets/a35a97c8-d3f6-429d-86a5-0e9511e859f9

chore: focus on mount of sql editor

---

packages/frontend/src/features/virtualView/components/EditVirtualViewModal.tsx
packages/frontend/src/pages/SqlRunnerNew.tsx

Closes: N/A
Fix boolean check introduced in #11611  - messed this up but it's fixed now and included on-mount-related-code in that `useOnMount`
Fixed a perf issue when switching between modals when editing a virtual view. Suspense loads the chart correctly and caches it after closing the modal and reopening it! 
Before
see chart opening and screen freezing while loading the sql runner component async
https://github.com/user-attachments/assets/0dff6698-4c34-43b9-8a6f-0f0c3f2030ff
After
both issues fixed - opens sql and there's no freeze between modal body states.
https://github.com/user-attachments/assets/febe0521-6349-4160-9f45-ce6a17ba3cd1

fix: apply correct boolean check when editing virtual view

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/ProjectService/ProjectService.ts

Closes: #11960 
> [!NOTE]
> I'm doing the `saved_chart_created` and `saved_chart_updated` on a separate PR since it demands a wider change
**virtual_view_created - this event should be triggered when a virtual view is first created.**
**virtual_view_updated - this event should be triggered when a virtual view is updated.**
**virtual_view_deleted - this event should be triggered when a virtual view is deleted.**
**query_executed --> add a parameter called virtual_view_id which is empty if the query was executed from a regular explore or the SQL runner, but is non-empty if the query was executed from a virtual view.**

chore: add CUD virtual views & query_executed analytics events

---

packages/common/src/compiler/translator.ts
packages/common/src/schemas/json/lightdash-dbt-2.0.json
packages/common/src/types/dbt.ts

Closes: #11716 
After this PR `additional_dimensions` now support `time_intervals`!
It follows the same logic of `dimensions` where:
- if `time_intervals` is not specified, it uses the default
- if `time_intervals` is specified, it uses those intervals
- if `time_intervals` are "OFF", the value is raw
```yaml
- name: event
description: ""
meta:
dimension:
type: string
groups: ["events"]
additional_dimensions:
timestamp_est:
type: timestamp
group_label: "Timestamp test"
sql: ${TABLE}.timestamp_ltz
time_intervals: ["YEAR"]
```

fix: fix additional_dimensions allowing time_intervals

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/SavedSqlService/SavedSqlService.ts
packages/common/src/types/sqlRunner.ts
packages/frontend/src/features/queryRunner/sqlRunnerPivotQueries.ts
packages/frontend/src/features/sqlRunner/hooks/useSavedSqlChartResults.tsx
packages/frontend/src/features/sqlRunner/runners/SqlRunnerResultsRunnerFrontend.ts
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

Closes: #11995 
1. Create a chart using the `Sql Runner` & save
2. Create a new user with `editor` role
3. Open the saved chart using the `editor` user
Note: `viewers` & `interactive_viewers` should also be able to see the saved chart, as this should have the same permissions as normal charts

fix: check for saved chart view access when running pivot query

---

packages/frontend/src/components/Explorer/CustomDimensionModal/CustomBinDimensionModal.tsx

Closes: https://github.com/lightdash/lightdash/issues/11859
mantine 7 offers the option to have floats in the number input. but mantine 6 does not. changed to text input instead of number input and I also added a zod schema

feat: custom dimensions custom range float values

---

packages/frontend/src/components/DataViz/config/TableVisConfiguration.tsx

Closes: #11869
- When someone hides a field in the table chart, it should appear to be disabled
- The cursor pointer is set to be `not-allowed`
- [✅] I have manually tested the changes in the preview environment
- [✅] I have reviewed the code
- [✅] I understand that "request changes" will block this PR from merging

fix: style hidden column as read-only

---

packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts
packages/frontend/src/features/virtualView/components/HeaderVirtualView.tsx

Closes: N/A
Found this issue when the user types a SQL query, runs it, but can't save its edit. 
Only they can type the sql and click save. 
reuses a compare sql function. 
**before**
https://github.com/user-attachments/assets/35ee226e-dde9-4cd9-9882-f97d9e56d2d3
**after**
https://github.com/user-attachments/assets/8ac2574f-9fbb-483e-aadc-7da76bfe7a3e

fix: compare sqls on change to edit virtual view

---

package.json
packages/backend/tsconfig.json
packages/cli/tsconfig.json
packages/common/tsconfig.json
packages/warehouses/tsconfig.json
yarn.lock

Closes: 
- smaller build
- synchronized config between backend/warehouses/common/cli
- modern-ish builds (supported by node 20)
- it supposed to have a performance impact since it's now using fewer polyfills and native async/await!
tsconfig values:
```json
{
"target": "ES2020",
"module": "CommonJS",
"lib": [
"ESNext"
],
"allowJs": false,
"importHelpers": true,
"moduleResolution": "Node",
"esModuleInterop": true,
}
```

chore: modern-ish backend build

---

packages/cli/src/handlers/preview.ts

Closes: https://github.com/lightdash/lightdash/issues/12034 
To reproduce bug run:
```
CI=true LIGHTDASH_API_KEY=af38f1f28d1d4d5ccc4a5c94781f70e1 LIGHTDASH_PROJECT=3675b69e-8324-4110-bdca-059031aa8da3 LIGHTDASH_URL=http://localhost:3000 node ./packages/cli/dist/index.js start-preview --project-dir ./examples/full-jaffle-shop-demo/dbt --profiles-dir ./examples/full-jaffle-shop-demo/profiles --name 'banana'
CI=true LIGHTDASH_API_KEY=af38f1f28d1d4d5ccc4a5c94781f70e1 LIGHTDASH_PROJECT=3675b69e-8324-4110-bdca-059031aa8da3 LIGHTDASH_URL=http://localhost:3000 node ./packages/cli/dist/index.js validate --preview --project-dir ./examples/full-jaffle-shop-demo/dbt --profiles-dir ./examples/full-jaffle-shop-demo/profiles
rm ~./.config/lightdash/config.yaml
CI=true …
```

fix(cli): set preview project in config when preview is updated

---

packages/frontend/src/components/NavBar/ProjectSwitcher.tsx

Closes: 
Now there is always at least 1 `menu item` : creat preview 
[Screencast from 24-10-24 13:11:52.webm](https://github.com/user-attachments/assets/4df404ee-32c7-44da-ad75-6de6b006494a)

fix: single project create preview

---

packages/frontend/src/hooks/dashboard/useDashboard.ts

Closes: #12004 
Increase time for 'open dashboard' toast from 5 seconds to 10 seconds.  To see it: add a chart to a dashboard from the explores page.
This one

fix: increase notification time for chart added to dashboard

---

packages/e2e/cypress/e2e/app/createProjects.cy.ts
packages/frontend/src/components/ProjectConnection/index.tsx

Amend the button label when updating project settings so it is obvious that the project will be deployed.

fix: amend button label when updating project settings

---

packages/backend/src/services/ProjectService/ProjectService.ts

Closes: 
At the moment, when there is an unexpected error while compiling all explores we don't capture the original error message. 
This PR makes sure we capture the original error in Sentry and our logs for debug purposes. The message returned to the user is still the same as we can't expose an internal error message.
Example forcing an error:
To reproduce add the following code inside the try catch
```throw new Error('force error');```

chore: capture unexpected error when compiling all explores

---

packages/backend/src/models/OrganizationMemberProfileModel.ts
packages/backend/src/models/UserModel.ts
packages/common/src/index.ts
packages/common/src/types/organizationMemberProfile.ts
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/UsersView.tsx

- Modifies the userUpdate method in UserModel to accept isActive argument (used when an external service like SCIM will create a user)
- Adds a visual indicator in the user management window that an account is marked as not active
- Limit or block usage of the blocked account 
- Does not create UI controls for making a user active/inactive
This video shows the separation of invite logic working as expected along with the "inactive" state:
https://github.com/user-attachments/assets/b6e01933-2d93-4592-a644-0594a81e814d

feat: methods to activate/deactivate user

---

packages/frontend/src/components/DataViz/store/barChartSlice.ts
packages/frontend/src/components/DataViz/store/lineChartSlice.ts
packages/frontend/src/components/DataViz/store/pieChartSlice.ts
packages/frontend/src/features/sqlRunner/store/sqlRunnerListeners.ts

Closes: #11842 
Fixes keeping old results around when a new SQL query is run. This does 2 things:
1. Always reset the chart config when a new query is run. We had been trying to keep some of it around, but that wasn't working right anyway, so I think just updating it is fine. It seems like the way the UI is set up, it won't be common for people to work on a chart, change the SQL, then work on the chart again. 
2. Remove the old results from the store when an error occurs. They were sticking around and it was confusing.

fix: update chart when sql changes

---

packages/frontend/src/Routes.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx
packages/frontend/src/features/metricsCatalog/index.ts
packages/frontend/src/pages/MetricsCatalog.tsx
packages/frontend/src/types/Events.ts

Relates to: #12104
small placeholder in new route

feat: create `/metrics` route with placeholder

---

packages/e2e/cypress/e2e/app/sqlRunnerNew.cy.ts
packages/frontend/src/components/DataViz/FieldReferenceSelect.tsx
packages/frontend/src/components/DataViz/config/CartesianChartFieldConfiguration.tsx
packages/frontend/src/components/DataViz/config/DataVizAggregationConfig.tsx
packages/frontend/src/components/DataViz/config/DataVizSortConfig.tsx
packages/frontend/src/components/DataViz/hooks/usePillSelectStyles.tsx
packages/frontend/src/components/DataViz/store/cartesianChartBaseSlice.ts

Closes: https://github.com/lightdash/lightdash/issues/11470
See main ticket and request figma link
THis PR: 
- Introduces `usePillSelectStyles` - allows us to create PillSelect's with Mantine hooks
- Allows the user to update the sort and aggregation inside the fieldReferenceSelect
- Replaces the `+ add ` button with an action icon
- Replaces the `clearable` prop with a different approach (with the - action icon)
- Refactors the `setSortBy` action.

style: apply new designs to field configuration (x, y)

---

packages/backend/src/controllers/catalogController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/services/CatalogService/CatalogService.ts
packages/common/src/types/catalog.ts

Closes: [#12129](https://github.com/lightdash/lightdash/issues/12129)
Endpoint: `/api/v1/projects/${UUID}/dataCatalog/metrics`
Example response:
```json
{"status": "ok", "results": [{"name":"unique_payment_count","label":"Unique payment count","description":"count of all payments","tableLabel":"Payments","tableName":"payments","fieldType":"metric","basicType":"number","type":"field","tags":[],"analytics":{"charts":[{"name":"Which customers have not recently ordered an item?","uuid":"0e6a25c8-a026-4420-93ba-a5d07ec9bb4e","spaceUuid":"0d96ca58-19e7-4b86-aa7b-c0d30f0797ef","spaceName":"Jaffle shop","dashboardName":null,"dashboardUuid":null}]}
```
test-frontend

feat: add metrics catalog endpoint

---

examples/full-jaffle-shop-demo/dbt/models/tracks.yml
packages/frontend/package.json
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
packages/frontend/src/features/metricsCatalog/hooks/useMetricsCatalog.tsx
yarn.lock

Adds package: `mantine-react-table`
Adds simple `useMetricsCatalog` hook 
Displays a very simple table (used this PR as a base: https://github.com/lightdash/lightdash/pull/12124)
> [!NOTE]
> This doesn't include work on infinite scroll/querying -  awaiting BE work

feat: show catalog metrics in table

---

packages/frontend/package.json
packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
packages/frontend/src/components/DashboardFilter/Filter.tsx
yarn.lock

Closes: https://github.com/lightdash/lightdash/issues/6705
When editing a dashboard, filters may be reordered by dragging. Blue indicator denotes drop location.
Please note:
1. Using `dnd-kit` as it supports dragging of components that wrap to multiple lines.
2. The blue "drop zone" indicator only occupies the existing space between filters because trying to expand it causes glitches when filters wrap on multiple lines. This is also the reason the 6-dot drag handle appears on all filters when in edit mode rather than only on mouseover.
3. While dragging, filter is slightly translucent to help see what's under it. Lmk if you'd like to change that.
4. A dragged filter appears under filters to its right. I looked into fixing this, and the code changes are considerable. Since this is sort of …

feat: reorderable dashboard filters

---

packages/backend/src/database/entities/users.ts
packages/backend/src/database/migrations/20241028143602_add_updated_at_to_users_table.ts
packages/backend/src/models/OrganizationMemberProfileModel.ts
packages/backend/src/models/UserModel.ts

Commercial PR: https://github.com/lightdash/lightdash-commercial/pull/327 
- This adds updated_at to the users table. Used for SCIM to show the oldest updated users first
- this also adds logic to update update_at when a user is updated, joins an org, or activates

feat: updated_at added to users table

---

packages/backend/src/controllers/projectController.ts
packages/backend/src/database/seeds/development/03_saved_dashboards.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/SavedChartModel.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/e2e/cypress/e2e/api/chartSummaries.cy.ts
packages/frontend/src/hooks/useChartSummaries.ts

Closes: [#12113](https://github.com/lightdash/lightdash/issues/12113)
Changes:
- updated SQL to make sure we only list charts that are used in the latest version of the dashboards
- added a new dashboard in seed data
- added API test
- added a new URL param `excludeChartsSavedInDashboard` to exclude charts saved in dashboards

feat(api): include charts saved in dashboards in charts summary list by default

---

examples/full-jaffle-shop-demo/dbt/models/schema.yml
packages/backend/src/controllers/catalogController.ts
packages/backend/src/database/entities/catalog.ts
packages/backend/src/database/migrations/20241028170155_add-required-attributes-to-catalog-search.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/models/CatalogModel/utils/index.ts
packages/backend/src/models/CatalogModel/utils/parser.ts
packages/backend/src/services/CatalogService/CatalogService.ts
packages/e2e/cypress/e2e/api/catalog.cy.ts

Closes: #12135 
- introduces `required_attributes` column to `catalog_search` (`null` by default, and then user has to refresh dbt / compile project for all to be populated for each field and table - this is handled on the db query)
- this also ensures that the filtering around required_attributes (or user attributes) and table access (like model selection, tag selection) is happening on the the db query instead of post-db-query
test-frontend

feat: add pagination to /dataCatalog/metrics endpoint

---

packages/frontend/src/features/metricsCatalog/components/MetricChartsUsageModal.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
packages/frontend/src/features/metricsCatalog/store/metricsCatalogSlice.ts
packages/frontend/src/features/sqlRunner/store/index.ts
packages/frontend/src/pages/MetricsCatalog.tsx

Adds new slice `metricsCatalog` 
Adds modal, and it's controlled by the setting of active metric name - we might want to do this differently in the future, but it works fine
https://github.com/user-attachments/assets/f045cebd-685d-463c-80ae-8932771919ac

feat: open usage chart in modal and let user open chart

---

packages/frontend/src/hooks/useColumnTotals.ts

Closes:  https://github.com/lightdash/lightdash/issues/12047
Related: https://github.com/lightdash/lightdash/issues/9981
https://github.com/lightdash/lightdash/issues/9981#issuecomment-2443881249
For context, we don't calculate totals on pivot tables for metric type `number`, because the `sum` of numbers is not a correct total. 
Let's take this example: 
I have a metric which is a type:number calculated from `sums`
```
- name: amount
description: Total amount (AUD) of the individual payment
meta:
metrics:
total_revenue:
type: sum
description: Sum of all payments
total_cost:
type: number
sql: ${total_revenue} - 10
total_percent_profit: 
type: number
sql: 100 * ${total_revenue}/${total_cost}
```
WHen I calculate totals in a non-pivot table, the result is correct, we calculate this on a …

fix: remove number metric total calculation on pivot

---

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
packages/frontend/src/hooks/useExplorerRoute.ts

> [!NOTE]
> I have a subsequent PR that refactors this component into smaller ones
When the user clicks on `use metric`, they are redirected to an explore where they can preview their metric - it gets a date dimension - if it can't find it in the base table, and if there are other joined tables, it will try to find it again. 
demo:
https://github.com/user-attachments/assets/04ac1b8b-9010-4f24-ab21-04c116bb91ff

feat: open metric preview on click of metric in table

---

packages/backend/src/controllers/catalogController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/services/CatalogService/CatalogService.ts
packages/common/src/index.ts
packages/common/src/types/api/sort.ts
packages/common/src/types/catalog.ts

Closes: [#12168](https://github.com/lightdash/lightdash/issues/12168)
New query params added:
- `sort`: name of the column to sort by
- `order`: either `asc`, `desc` or `undefined`

feat: add sorting to dataCatalog/metrics endpoint

---

packages/frontend/src/features/tableCalculation/components/TableCalculationModal.tsx
packages/frontend/src/hooks/toaster/useToaster.tsx
packages/frontend/src/hooks/useQueryError.ts

Closes: #11198 
Makes it possible to add errors to a list instead of each in it's own toast. That list is collapsable and the errors can be dismissed individually. 
Note that there is a new method `addToastError` that will add to the list and I kept the old `showToastError` for now. This way we can keep the existing behavior in some places, but use error lists in others. For now I have only updated a few places where multiple errors were most problematic to use the error list, primarily the API error reporting. 
The collapsed errors now look like:
And the expanded list looks like:
One consistent way to test this is to add a table calculation with invalid columns or no sql, then do it again. The first toast will be the same as always, the second one will add to the list.

feat: stacking error list

---

packages/backend/src/App.ts
packages/backend/src/SchedulerApp.ts
packages/backend/src/controllers/catalogController.ts
packages/backend/src/database/entities/catalog.ts
packages/backend/src/database/migrations/20241030141715_add_chart_usage_to_catalog_search.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/models/CatalogModel/utils/index.ts
packages/backend/src/models/CatalogModel/utils/parser.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/models/SavedChartModel.ts
packages/backend/src/scheduler/SchedulerClient.ts
packages/backend/src/scheduler/SchedulerTask.ts
packages/backend/src/scheduler/SchedulerWorker.ts
packages/backend/src/services/CatalogService/CatalogService.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/catalog.ts
packages/common/src/types/scheduler.ts
packages/e2e/cypress/e2e/api/catalog.cy.ts

Closes: https://github.com/lightdash/lightdash/issues/12175
- Adds `chart_usage` column to `catalog_search`
- After the catalog is indexed, a new task will be scheduled to calculate the chart usage per each field in the catalog with the charts where this field is used
- Then, the column `chart_usage` will be updated with the new count
> [!NOTE]
> A separate PR will be created to update this counter on chart creation/update/deletion. 
test-frontend

feat: get a field's chart usage and store in catalog

---

packages/backend/src/controllers/organizationController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/GroupsModel.ts
packages/backend/src/services/GroupService.ts
packages/backend/src/services/OrganizationService/OrganizationService.ts
packages/common/src/types/groups.ts
packages/frontend/src/hooks/useOrganizationGroups.ts

Closes: 
Remove loop that adds members on group creation. Prevent issues with database pool max out.
Should have no impact on existing behaviour.

fix: add group members in a single insert

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/CatalogService/CatalogService.ts
packages/common/src/types/catalog.ts
packages/frontend/src/features/metricsCatalog/components/MetricChartsUsageModal.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
packages/frontend/src/features/metricsCatalog/store/metricsCatalogSlice.ts

Closes: https://github.com/lightdash/lightdash/issues/12104
> [!NOTE]
> Will get the charts per field endpoint working on a separate PR

chore: get chart usage from api response

---

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
packages/frontend/src/features/metricsCatalog/hooks/useMetricsCatalog.tsx

Relates to: #12104 
Can sort by popularity/chart usage and it's sorted DESC by default
demo
https://github.com/user-attachments/assets/60065f91-dee2-47ab-b1f9-77f5732d8138

feat: allow sorting by popularity and by default

---

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Layout/index.tsx

Closes: #8701 
Allow stacking in ungrouped bar charts. It seems like mostly we were hiding the control for this. It seems to work well with the control available.

fix: allow stacking in ungrouped bar charts

---

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx

Relates to: https://github.com/lightdash/lightdash/issues/12167
-  update copy 'use metric'  to 'explore'
-  remove row numbers' column 
-  remove shadow from paper container
-  remove box shadow from table head row 
-  disable filter modes like fuzzy
-  open search by default and align to left 
demo: 
https://github.com/user-attachments/assets/ee77b2ad-5839-4592-9c1f-80b11610290e

style: apply small ui/ux improvements (part 2)

---

docs/docs/references/roles.mdx
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/authorization/organizationMemberAbility.test.ts
packages/common/src/authorization/organizationMemberAbility.ts
packages/common/src/authorization/projectMemberAbility.test.ts
packages/common/src/authorization/projectMemberAbility.ts
packages/e2e/cypress/e2e/api/organizationPermissions.cy.ts
packages/frontend/src/components/NavBar/ProjectSwitcher.tsx
packages/frontend/src/hooks/useProjectPreview.ts

Closes: https://github.com/lightdash/lightdash/issues/8307
test-frontend
test-backend
test-cli
internal discussion: https://lightdash.slack.com/archives/C07TP0EN8PP/p1730197569059179
developer:
member:
member able to access preview via url:

feat: project list no previews for members and below

---

packages/backend/src/models/OrganizationMemberProfileModel.ts

Commercial PR: https://github.com/lightdash/lightdash-commercial/pull/347
- Added function inside of OrganizationMemberProfileModel to assign users to organizations via the user uuid and org uuid

feat: added function to assign a user to an org via uuids

---

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx

Closes: #12167
AC: 
> [!IMPORTANT]
> I couldn't hide the drag handle, but made the width smaller - is this acceptable?
demo:
https://github.com/user-attachments/assets/4949ed8f-4f53-45a1-8f9f-e03a6da56561

style: apply small ui/ux improvements (part 3)

---

packages/frontend/src/pages/MetricsCatalog.tsx

Closes: #12194
overrides the main font family to `inter` just in Metrics Catalog for now 
Added a TODO to address this override and enable it globally if no issues are found.

style: use font `Inter` in MetricsCatalog

---

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/features/scheduler/components/SchedulerModalContent.tsx
packages/frontend/src/features/scheduler/utils/index.ts

Closes: #9075 
Description:
Checked Schedule Delivery model is getting open when we pass scheduler_uuid as query parameter in the URL
and replicated the same for threshold_uuid. please check the below video
https://github.com/user-attachments/assets/7fb3ba24-f2d7-414a-a0d4-07da54ca0e17

fix: open threshold edit modal on click of link

---

packages/backend/src/services/CsvService/CsvService.ts

Closes: 
issue: export dashboard failed for csv option.
steps to reproduce:
1. open any dashboard.
2. create a chart tile with zero returned data.
3. export dashboard.
then it will throw this issue in the backend:
```
[backend] ArchiverError: file filepath argument must be a non-empty string value
[backend]     at Archiver.file (/usr/app/node_modules/archiver/lib/core.js:707:24)
[backend]     at <anonymous> (/usr/app/packages/backend/src/services/CsvService/CsvService.ts:1185:29)
[backend]     at Array.forEach (<anonymous>)
[backend]     at <anonymous> (/usr/app/packages/backend/src/services/CsvService/CsvService.ts:1184:23)
[backend]     at new Promise (<anonymous>)
[backend]     at writeZipFile (/usr/app/packages/backend/src/services/CsvService/CsvService.ts:1169:13)
[backend]     at …
```

fix: export to CSV failing for some dashboards

---

examples/full-jaffle-shop-demo/dbt/data/raw_orders.csv
packages/common/src/index.ts

Closes: #12201 
This fixes an issue where clicking 'view underlying data' with a null date caused an error in the dialog (see video). The fix is small and a seems a little unrelated from the bug, but it makes our date handling more correct. The fix is to return null when a date field is null; before were were trying to parse null as a date and returning 'Invalid date' as a date. The underlying data dialog was then trying to use 'Invalid date' as a filter value, causing the error. 
This fix will change the way null dates are returned from runQuery. I don't know if there are other places that were relying on the old (broken) behavior. This is definitely more correct though. 
To test:
- use the orders model and choose oder date day as one of the fields
- filter such that orders date day …

fix: view underlying data with a null date

---

packages/frontend/src/features/comments/hooks/useDashboardCommentsCheck.ts

Closes: 
Thread: https://lightdash.slack.com/archives/C03MCQ08UKS/p1730729911553919?thread_ts=1730715499.115549&cid=C03MCQ08UKS
If posthog is not used, `useFeatureFlagEnabledPosthog(FeatureFlags.DashboardComments)` returns `undefined`

fix: comments feature enable by default for self-host

---

packages/backend/src/database/migrations/20241104104713_reset_users_active_status.ts
packages/backend/src/models/OrganizationMemberProfileModel.ts
packages/backend/src/models/UserModel.ts
packages/backend/src/services/UserService.mock.ts
packages/backend/src/services/UserService.test.ts
packages/backend/src/services/UserService.ts
packages/common/src/types/organizationMemberProfile.ts
packages/common/src/types/user.ts
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/UsersView.tsx
packages/frontend/src/features/comments/components/CommentForm.tsx

Related to: https://github.com/lightdash/lightdash-commercial/issues/324
We want user accounts marked with isActive = false to not have access to Lightdash. 
At the moment, is_active is being used to track what users were invited but haven't logged in yet aka don't have an authentication method.
The variable/value is used in these places:
https://github.com/lightdash/lightdash/blob/547ad8083fc47a848b33110ea6a09f440c7b160f/packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/UsersView.tsx#L65
https://github.com/lightdash/lightdash/blob/1dd45b035b9485c6f646f68a4a4a5520eca15010/packages/frontend/src/features/comments/components/CommentForm.tsx#L51
https://github.com/lightdash/lightdash/blob/fa0c44aff40c8a86a5dd1ae0dda91a58be09c8a1/packages/backend/src/services/UserService.ts#L369 …

feat: change user 'isActive' definition

---

packages/frontend/src/features/metricsCatalog/components/ExploreMetricButton.tsx
packages/frontend/src/features/metricsCatalog/components/MetricChartUsageButton.tsx
packages/frontend/src/features/metricsCatalog/components/MetricChartUsageModal.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx

Relates to: #10330
**NOTE**
`MetricsCatalogColumns` returns an array but each element's `Cell` is basically a component so I'm keeping it PascalCased

refactor: split metrics table components into multiple

---

packages/cli/src/handlers/dbt/apiClient.ts

Closes: NA
When I seldom encountered errors when executing a `lightdash stop-preview` command today. Resulting logs of a command didn't provide meaningful information about the error. First, I want to show the HTTP method to call a Lightdash API. Then, I want to improve the error message `Something went wrong.` after identifying which endpoint raise the error.
```
$ lightdash stop-preview
...
> Making HTTP query to: https://xxx.lightdash.cloud/api/v1/health
> HTTP request returned status: 200
> HTTP request returned status: ok
> Making HTTP query to: https://xxx.lightdash.cloud/api/v1/org/projects/
> HTTP request returned status: 200
> HTTP request returned status: ok
> Making HTTP query to: https://xxx.lightdash.cloud/api/v1/user
> HTTP request returned status: 200
> HTTP request …
```

feat: Show HTTP method in `lightdashApi`

---

packages/backend/src/controllers/catalogController.ts
packages/backend/src/database/entities/catalog.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/services/CatalogService/CatalogService.ts
packages/common/src/types/catalog.ts

Closes: #12261 
- Adds `catalogTags` query parameter to allow filtering by tag uuids in `/metrics` endpoint
- Supports array values by passing N times, e.g. `catalogTags=3715c854-a5e6-4ad3-996b-81d4b2372ef1&catalogTags=d963896a-8180-4a37-bf6f-a27877b883d8`

feat: allow to filter by catalog tags

---

packages/backend/src/controllers/authentication/middlewares.ts
packages/backend/src/models/SchedulerModel/index.ts
packages/backend/src/services/UserService.ts
packages/common/src/types/errors.ts
packages/frontend/src/api.ts

Related to: https://github.com/lightdash/lightdash-commercial/issues/324
We want user accounts marked with isActive = false to not have access to Lightdash. The experience should be:
- if they aren’t signed in: they see an error trying to sign in
- if they are signed in: on the next action they are signed out and redirected to /login
Note: we need to change the value in the DB to test.
Fail with password
https://github.com/user-attachments/assets/e54afa0f-9007-42e3-8db2-851f23beb1d7
Fail with oauth
https://github.com/user-attachments/assets/767316e1-3725-40c8-b4f4-4b30b6166af5
Session destroyed & redirect to /login page ( the error message might show for a brief moment depending on the error handling in the page. Depriotized this as it is an edge case and haven't found of a solution that …

feat: block deactivated users from accessing Lightdash

---

packages/common/src/types/filter.ts
packages/frontend/src/features/scheduler/components/SchedulerFilters.tsx

Closes: #12204 
Fixes an issue where some filters on scheduled deliveries not overriding dashboard filters. The SD filters were being set as disabled. This fixes that by using the DB setting for disabled. 
To repro the issue:
1. Add a fitler to a dashboard for something like 'date is after...'
2. Set up a scheduled delivery with a filter for a different 'date is after...'
3. Send now. You will get data filtered by the dashboard filter.

fix: time-based filters in scheduled deliveries 

---

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar.tsx
packages/frontend/src/features/metricsCatalog/hooks/useMetricsCatalog.tsx
packages/frontend/src/features/metricsCatalog/store/metricsCatalogSlice.ts

Closes: [#10330](https://github.com/lightdash/lightdash/issues/10330)
Custom TopToolbar component that contains the search input and the tags
Makes a clear distinction between the selected tags vs the stored ones in the filter (because the user has to get out of the popover to confirm changes
Can filter the catalog by tag
https://github.com/user-attachments/assets/a1d85ee2-ce52-43f0-850f-988c328149d0

feat: enable catalog filtering by tag/category

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/frontend/src/features/metricsCatalog/components/ExploreMetricButton.tsx
packages/frontend/src/features/metricsCatalog/components/MetricChartUsageButton.tsx
packages/frontend/src/features/metricsCatalog/components/MetricChartUsageModal.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogPanel.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogTagForm.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsTableTopToolbar.tsx
packages/frontend/src/features/metricsCatalog/store/metricsCatalogSlice.ts
packages/frontend/src/providers/TrackingProvider.tsx
packages/frontend/src/types/Events.ts
yarn.lock

Closes: #12260
> [!NOTE]
> Added as well project id and org id to all metrics-catalog-related events

chore: add catalog-category-related events

---

packages/backend/src/models/GroupsModel.ts

Closes: https://github.com/lightdash/lightdash-commercial/issues/373
- Adds check in group update if newMembers matches membersToAdd, throws error if not. Previously the error thrown by having an empty array for newMembers was not helpful

fix: added check and throw error in group update if newMembers does not match expected

---

packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNode.tsx

Closes:  #12289
- we keep add metric in ... menu
-  if there’s already a filter applied, then clicking on the filter doesn’t do anything

fix: filter metric on sidebar icon

---

packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
packages/frontend/src/components/DataViz/config/CartesianChartStyling.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/SingleSeriesConfiguration.tsx

Fixes a couple react errors. 
- React started warning about defaultProps, so I removed them:
```
Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
```
- There was a warning about control/uncontrolled components for the axis names in SQL runner

fix: react default prop and controlled component errors

---

packages/frontend/src/features/metricsCatalog/components/MetricCatalogCategoryFormItem.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogCategoryForm.tsx
packages/frontend/src/features/metricsCatalog/hooks/useCatalogCategories.tsx
packages/frontend/src/features/metricsCatalog/hooks/useProjectTags.tsx

Closes: #12308 
Adds optimistic updates to `metrics-catalog` and `project-tags` queries. 
- Creating a category (which will also category the metric)
1. optimistically update the list of categories in the form 
2. update the tagInput value array
3. as well as the cell array
- uncategorising a metric
1. update the tagInput value array
1. as well as the cell array
1. list of categories in the form **remains the same**
- deleting a **tag** project
1. update the tagInput value array (if category is there)
1. as well as the cell array
1. list of categories in the form updates
- updating a **tag** the project
1. update the tagInput value array (if category is there)
1. as well as the cell array
1. list of categories in the form updates

feat: optimistically update categories

---

packages/backend/src/database/migrations/20241108145015_group-names-unique.ts
packages/backend/src/models/GroupsModel.ts

Closes: https://github.com/lightdash/lightdash-commercial/issues/362
- Creates a unique constraint on the groups table by (name, organization_id) but first changes any identically named groups in an org to "$NAME", "$NAME 2", "$NAME...
- On group update and delete it checks for a Postgres unique violation error and throws an appropriate Lightdash error

feat: force unique group names at the db level

---

packages/frontend/src/features/scheduler/components/SchedulerFilters.tsx
packages/frontend/src/pages/MinimalDashboard.tsx

…isabled on creation
Closes: #12204 
The SD filters were being set as disabled. This fixes that by using the existing fitler setting for disabled.
Also, send now wasn't using the Scheduled delivery filters because of a typo in URL parsing. This was adding to confusing about whether SD filters worked at all. Also fixed here. 
To repro the issue:
Add a fitler to a dashboard for something like 'date is after...'
Set up a scheduled delivery with a filter for a different 'date is after...'
Send now. You will get data filtered by the dashboard filter.

fix: send now filters weren't working for images, some filters 

---

packages/frontend/package.json
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumnName.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx
packages/frontend/src/svgs/metrics-catalog-metric-icon.svg
yarn.lock

Close: #12344 
Adds `emoji-picker-react`
Creates shared emoji picker (one for all cells with `Portal`) 
DEMO: 
https://github.com/user-attachments/assets/92e49064-65be-48b4-afb8-9aac07694ba0
> [!NOTE]
> If we had a popover with the picker for each cell, that would lead to a very slow ux because the emoji picker would be mounted on every open. If we kept the popover mounted, it would lead to a nr_of_cells X pickers on the UI which is a no-no. So keeping a shared instance and moving the position as requested is an easier experience.

chore: introduce shared emoji picker and metric icon

---

packages/common/src/compiler/translator.ts
packages/common/src/dbt/schemas/lightdashMetadata.json
packages/common/src/types/dbt.ts
packages/common/src/types/field.ts

Closes: https://github.com/lightdash/lightdash/issues/12258
test-backend
test-frontend
test-cli
column level dimension tagging:
column level metric tagging:
model level metric tagging:

feat: field tagging in yml

---

packages/frontend/src/features/metricsCatalog/components/MetricChartUsageModal.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumns.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
packages/frontend/src/pages/MetricsCatalog.tsx

Closes: [#12298](https://github.com/lightdash/lightdash/issues/12298)
- Fixes table scroll bar to show only on the body
- Makes chart usage scroll bar use a scroll area: 
Note: scroll bar still hides behind the header, this seems to be a limitation on mantine

fix: metrics catalog scroll bars

---

packages/frontend/src/features/metricsCatalog/components/MetricsCatalogColumnName.tsx
packages/frontend/src/svgs/metrics-catalog-metric-icon.svg

Closes: [#12363](https://github.com/lightdash/lightdash/issues/12363)
This PR: 
- adds the ability to remove an icon from a metric
- applies styles to the metric icon as requested by @PriPatel

feat: allow deleting a metric icon

---

packages/warehouses/package.json

Closes: https://github.com/lightdash/lightdash/issues/12387
This is a tentative solution to build Lightdash CLI to quickly avoid the `ERR_REQUIRE_ESM` error. 
The Lithdash CLI can't be built with `trino-js-client` [v0.2.4](https://github.com/trinodb/trino-js-client/releases/tag/v0.2.4). I am doubting changes from trino-js-client v0.2.3 to v0.2.4. It seems that "type": "module" was added to the package.json` of trino-js-client. We have to change something to handle it.
According to my research, I was able to build the Lightdash CLI with trino-client v0.2.3. Meanwhile, I could reproduce the error with trino-client v0.2.4.
- (Succeeded) Build with trino-client v0.2.3: https://github.com/yu-iskw/lightdash/pull/1#issuecomment-2472414181
- (Failed) Build with trino-client …

fix: Pin the version of `trino-client` at v0.2.3

---

packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/components/common/modal/DashboardFiltersWarningModal.tsx
packages/frontend/src/hooks/useSavedDashboardFiltersOverrides.tsx
packages/frontend/src/pages/Dashboard.tsx
packages/frontend/src/providers/DashboardProvider.tsx

Closes: #11642 
Adds a warning modal when editing a dashboard with filters changed:
If the user clicks yes, we clear the filters and go into edit mode. If they click cancel, cancel editing. 
To repro: either update a saved filter on a dashboard, or add a temp fitler. Then try to edit.

feat: add warning about default filter override
