packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/types/metricQuery.ts

fix: metadata runquery

---

packages/frontend/src/providers/DashboardProvider.tsx

feat: share date zoom url

---

packages/backend/src/queryBuilder.ts
packages/common/src/compiler/filtersCompiler.ts

Closes: https://github.com/lightdash/lightdash/issues/8141
frontend-test backend-test
test-backend test-frontend

fix: table calculation filter field quotes

---

examples/full-jaffle-shop-demo/dbt/data/raw_plan.csv
examples/full-jaffle-shop-demo/dbt/dbt_project.yml
examples/full-jaffle-shop-demo/dbt/models/plan.yml
packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/compiler/translator.mock.ts
packages/common/src/compiler/translator.test.ts
packages/common/src/compiler/translator.ts
packages/common/src/dbt/schemas/lightdashMetadata.json
packages/common/src/types/dbt.ts
packages/common/src/types/field.ts

Closes: #3232
Documentation PR: https://github.com/lightdash/lightdash/pull/8167
Main changes:
Example data:
```
id,plan_name,metadata
1,free,{"created_by":"John Miller"}
2,silver,{"created_by":"Elliot Stone"}
3,gold,{"created_by":"John Miller"}
4,platinum,{"created_by":"Elliot Stone"}
5,diamond,{"created_by":"John Miller"}
```
Example yml:
```
version: 2
models:
- name: plan
columns:
- name: id
- name: plan_name
- name: metadata
meta:
dimension:
hidden: true
additional_dimensions:
created_by:
type: string
sql: ${plan.metadata}->>'created_by'
created_by_first_name:
type: string
sql: SPLIT_PART(${created_by}, ' ', 1)
created_by_last_name:
type: string
sql: SPLIT_PART(${created_by}, ' ', 2)
metrics:
creator_count:
type: count
sql: ${created_by}
```

feat: support multiple dimensions from same column

---

packages/e2e/cypress/e2e/app/dateZoom.cy.ts

fix: unify date zoom test

---

packages/frontend/src/hooks/useExplorerRoute.ts
packages/frontend/src/pages/MinimalDashboard.tsx
packages/frontend/src/providers/DashboardProvider.tsx

Partially Closes:  #8038
- Only exports JPG
- CSV will be done on a separate PR 
[Screencast from 30-11-23 11:46:32.webm](https://github.com/lightdash/lightdash/assets/1983672/d6c695d3-391f-476a-a301-0738e01dc46c)

feat: minimal dashboard zoom

---

packages/backend/src/services/ValidationService/ValidationService.ts

fix: table calculation filter validation

---

examples/full-jaffle-shop-demo/dbt/models/plan.yml
packages/backend/src/clients/Google/GoogleDriveClient.ts

fix: json google sheets

---

packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes:  #7527
This fixes the inconsistency between axis and tooltip. 
But not the date-only tooltip issue https://lightdash.slack.com/archives/C04KD95TF0U/p1701792355904829?thread_ts=1697561010.794869&cid=C04KD95TF0U (this will be fixed in a separate PR) 
Before:
After:

fix: apply date formatter to axispointer

---

packages/frontend/src/components/LightdashVisualization/VisualizationConfigTable.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormattingList.tsx
packages/frontend/src/components/common/PivotTable/index.tsx
packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
packages/frontend/src/hooks/useCalculateTotal.ts

refactor: use itemsMap instead of explorer in table config

---

packages/frontend/src/components/UserSettings/PasswordPanel/index.tsx
packages/frontend/src/hooks/user/usePassword.ts

Closes: https://github.com/lightdash/lightdash/issues/8201
https://github.com/lightdash/lightdash/assets/962095/19c5a5a0-ed63-4e07-b061-cadaf86ad7b5

fix: set password for users who signed up using social login

---

packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.mock.ts
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
packages/frontend/src/hooks/cartesianChartConfig/utils.ts

Closes: #7923
Before:
[Screencast from 06-12-23 15:17:29.webm](https://github.com/lightdash/lightdash/assets/1983672/652c063c-1c7b-4722-b0ee-7159c07e3bbf)
after:

fix: apply label on new chart series

---

packages/frontend/src/components/LightdashVisualization/VisualizationBigNumberConfig.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/SimpleStatistic/BigNumberContextMenu.tsx
packages/frontend/src/components/VisualizationConfigs/BigNumberConfig/BigNumberConfigTabs.tsx
packages/frontend/src/hooks/useBigNumberConfig.ts

Relates to: https://github.com/lightdash/lightdash/issues/8153
use `itemsMap` instead of `explore` on big number

refactor: use items map in big number viz

---

packages/backend/src/clients/Google/GoogleDriveClient.test.ts
packages/backend/src/clients/Google/GoogleDriveClient.ts

fix: google sheet date export

---

packages/frontend/src/hooks/useBigNumberConfig.ts

fix: comparison value on table calculation

---

packages/frontend/src/hooks/useSavedQuery.ts

Closes: #8223
Before:
[Screencast from 07-12-23 08:53:22.webm](https://github.com/lightdash/lightdash/assets/1983672/d380d11b-cb2c-4c1d-aa06-c7440d8519cd)
After:
[Screencast from 07-12-23 09:38:13.webm](https://github.com/lightdash/lightdash/assets/1983672/ad1a125b-e7a2-4a8c-bd6f-b0bc5d667e48)

fix: remove deleted chart frontend cache on dashboards

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/LightdashVisualization/index.tsx

fix: add dashboard filter from table viz

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer/ResultsCard/CellContextMenu.tsx
packages/frontend/src/components/Explorer/ResultsCard/UrlMenuItems.tsx
packages/frontend/src/components/Explorer/VisualizationCard/SeriesContextMenu.tsx
packages/frontend/src/components/MetricQueryData/CellContextMenu.tsx
packages/frontend/src/components/MetricQueryData/DrillDownMenuItem.tsx
packages/frontend/src/components/SimplePieChart/PieChartContextMenu.tsx
packages/frontend/src/components/SimpleStatistic/BigNumberContextMenu.tsx
packages/frontend/src/components/SimpleTable/CellContextMenu.tsx
packages/frontend/src/components/SimpleTable/DashboardCellContextMenu.tsx
packages/frontend/src/components/common/PivotTable/TotalCellMenu.tsx
packages/frontend/src/components/common/PivotTable/ValueCellMenu.tsx
packages/frontend/src/components/common/Table/BodyCell.tsx
packages/frontend/src/components/common/Table/ScrollableTable/index.tsx
packages/frontend/src/components/common/Table/Table.styles.ts

This reverts commit 94f3a98520e5c57eb00bbf839040d47b8e53456c.
Reverts: https://github.com/lightdash/lightdash/pull/8230
Work done on https://github.com/lightdash/lightdash/pull/8230 to be re-added once some performance issues are addressed: 
* Going from view -> edit mode saw an increase in render time
* Clicking on a table cell to `view underlying data` or `filter dashboard to` took too long and UI _hangs_

fix: revert "feat: visualization context menus to mantine (#8230)"

---

packages/frontend/src/hooks/useQueryResults.tsx
packages/frontend/src/pages/Dashboard.tsx

Closes: N/A
Remove feature flag `date-zoom` now that's enabled for everyone

chore: remove feature flag date-zoom

---

packages/frontend/src/components/common/Table/ScrollableTable/TableHeader.tsx
packages/frontend/src/hooks/useColumns.tsx

feat: tooltip migrations to mantine (mantine migrations part 3) 

---

packages/cli/src/dbt/targets/Bigquery/index.ts
packages/frontend/src/components/ProjectConnection/WarehouseForms/BigQueryForm.tsx

Closes:  #6635
I created a local project using biguqery staging settings with no location via CLI and UI

fix: allow empty bigquery location

---

packages/frontend/src/components/common/ResourceView/ResourceActionHandlers.tsx
packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx
packages/frontend/src/components/common/ResourceView/index.tsx
packages/frontend/src/components/common/modal/DashboardCreateModal.tsx

Closes: N/A
remove unnecessary console.logs

chore: remove unnecessary console.logs

---

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/AxesOptions.tsx
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes:  #2943
This issue https://github.com/apache/echarts/issues/16984#issuecomment-1849116907 is still affecting these charts.

feat: limit x-axis range

---

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/AxesOptions.tsx
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

This reverts commit df2207749623a42621ef7fb8260b9708db6a7113.
Closes: 
Thread: https://lightdash.slack.com/archives/C03MCQ08UKS/p1702465035304209?thread_ts=1702464470.452429&cid=C03MCQ08UKS

revert: "feat: limit x-axis range (#8261)"

---

packages/frontend/src/components/RegisterForms/ProjectConnectFlow.styles.tsx
packages/frontend/src/pages/VerifyEmail.tsx

Closes: N/A
Before
After
https://github.com/lightdash/lightdash/assets/7611706/a18c74ce-134d-41d0-a447-898f3d8d199f

chore: mantine-fy verify email success icon

---

packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/components/common/ResourceView/ResourceActionHandlers.tsx
packages/frontend/src/components/common/modal/ChartUpdateModal.tsx

Relates to: #8301 
Before
after

chore: mantine-fy chart update modal

---

packages/frontend/src/components/common/BigButton.tsx

Closes: N/A
Issue on `main` branch

fix: remove unused big button

---

packages/backend/src/generated/swagger.json
packages/backend/src/services/ProjectService/ProjectService.ts
packages/cli/src/dbt/models.ts
packages/cli/src/handlers/compile.ts
packages/common/src/compiler/exploreCompiler.mock.ts
packages/common/src/compiler/exploreCompiler.ts
packages/common/src/compiler/translator.ts
packages/common/src/types/dbt.ts
packages/common/src/types/dbtFromSchema.ts
packages/common/src/types/explore.ts
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

This reverts commit 12c03bd47ba7b3aadd90c3250fa692579f650afd.
Closes:

fix: revert "feat: snowflake warehouse connection (#8255)"

---

packages/backend/src/clients/dbtCloud/DbtCloudGraphqlClient.ts
packages/backend/src/controllers/metricFlowController.ts
packages/backend/src/services/HealthService/HealthService.ts

Closes: #8316 
Ability to set env var if user has dbt cloud in a different region or single tenancy or multi-cell ( new architecture )

feat(dbt-semantinc-layer): support all dbt regions

---

packages/frontend/src/features/metricFlow/utils/convertFieldMapToTableColumns.ts
packages/frontend/src/features/metricFlow/utils/convertMetricFlowQueryResultsToResultsData.mock.ts
packages/frontend/src/features/metricFlow/utils/convertMetricFlowQueryResultsToResultsData.ts
packages/frontend/src/pages/MetricFlow.tsx

After refactoring the visualization provider a bug was introduced in the dbt semantic layer page. We weren't passing the correct data (fields) which are required to configure and display the viz.

fix(dbt-semantic-layer): visualization fields

---

packages/backend/src/generated/swagger.json
packages/backend/src/services/ProjectService/ProjectService.ts
packages/cli/src/dbt/models.ts
packages/cli/src/handlers/compile.ts
packages/common/src/compiler/exploreCompiler.mock.ts
packages/common/src/compiler/exploreCompiler.ts
packages/common/src/compiler/translator.ts
packages/common/src/types/dbt.ts
packages/common/src/types/dbtFromSchema.ts
packages/common/src/types/explore.ts
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

fix: Reapply snowflake warehouse (revert + fix credentials)

---

packages/frontend/src/components/ProjectConnection/DbtForms/DbtCloudForm.tsx
packages/frontend/src/components/ProjectConnection/DbtForms/DbtLocalForm.tsx
packages/frontend/src/components/ProjectConnection/DbtForms/DbtNoneForm.tsx
packages/frontend/src/components/ProjectConnection/ProjectStatusCallout.tsx
packages/frontend/src/components/ProjectConnection/index.tsx

feat: callouts in mantine

---

packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceAccessType.tsx
packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceModal.style.ts
packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceUserList.tsx
packages/frontend/src/components/common/ShareSpaceModal/index.tsx

Relates to: #8301 
Space share modal
screenshots incoming
one thing not done yet: add user to space

chore: mantine-fy space share modal

---

packages/frontend/src/components/ChartDownload.tsx

Closes: N/A
https://github.com/lightdash/lightdash/assets/7611706/00cc387d-8dd3-448f-be67-f0dfc01dfa57

chore: mantine-fy chart download

---

packages/frontend/src/components/PageSpinner/PageSpinner.styles.tsx
packages/frontend/src/components/PageSpinner/index.tsx
packages/frontend/src/components/UserSettings/AppearancePanel/index.tsx
packages/frontend/src/components/common/SuboptimalState/SuboptimalState.tsx
packages/frontend/src/features/export/hooks/useExportToGoogleSheet.tsx
packages/frontend/src/pages/Dashboard.tsx

Closes: N/A
Update `Loader` styles (like the `PageSpinner`)

chore: mantine-fy loader styles

---

packages/frontend/src/pages/Dashboard.tsx

chore: mantine-fy dashboard alert

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/Explorer/index.tsx
packages/frontend/src/components/MetricQueryData/DrillDownModal.tsx

Relates to: #8301 
before
after
https://github.com/lightdash/lightdash/assets/7611706/74978c04-9471-4dc3-9373-3f29ded7f2d4

chore: mantine-fy drill down modal

---

.github/CONTRIBUTING.md

Update contributing docs to include DBT versions supported locally. Also better node version.

docs: include dbt versions in contributing docs

---

packages/backend/src/index.ts

Closes: #8373 
Tested:
✅  scheduled delivery

feat: strict same site cookies

---

examples/full-jaffle-shop-demo/dbt/models/events.yml
examples/full-jaffle-shop-demo/dbt/models/schema.yml
packages/common/src/types/filterGrammar.test.ts
packages/common/src/types/filterGrammar.ts
packages/e2e/cypress/e2e/api/api.cy.ts

fix: equal metric filter + e2e test

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx

chore: abstract dashboard chart tile component

---

packages/frontend/jest.config.ts
packages/frontend/package.json
packages/frontend/setupJest.ts
packages/frontend/src/api.test.ts
packages/frontend/src/api.ts
packages/frontend/src/setupTests.ts
yarn.lock

chore: support custom headers argument

---

packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
packages/frontend/src/components/common/Table/Table.styles.ts

Closes: https://github.com/lightdash/lightdash/issues/8402
https://github.com/lightdash/lightdash/assets/962095/35282385-5224-4dc5-a33c-c1635ac722e2

fix: table alternating row styles

---

packages/frontend/src/features/tableCalculation/components/SqlForm.tsx

Closes: #8395
Followed this comment: https://github.com/securingsincity/react-ace/issues/415#issuecomment-436623269
Demo:
https://github.com/lightdash/lightdash/assets/7611706/544f5026-338c-4787-b36d-fc6d7ebc3cfb

fix: alllow scrolling in react-ace table calc

---

packages/frontend/src/components/MetricQueryData/UnderlyingDataModal.tsx
packages/frontend/src/components/MetricQueryData/UnderlyingDataModalContent.tsx

related to: https://github.com/lightdash/lightdash/issues/8410
before: 
after:

fix: displaying error inside underlying data modal

---

packages/frontend/src/components/DashboardFilter/Filter.tsx
packages/frontend/src/components/DashboardFilter/index.tsx
packages/frontend/src/pages/Dashboard.tsx
packages/frontend/src/styles/react-grid.css

Closes: 
before:
---
after:
---
---
---
---
minimal view:

style: tidy up dashboard layout

---

packages/frontend/src/components/DashboardFilter/ActiveFilters/index.tsx
packages/frontend/src/components/DashboardFilter/Filter.tsx
packages/frontend/src/components/DashboardFilter/index.tsx

Closes: https://github.com/lightdash/lightdash/issues/7930
https://github.com/lightdash/lightdash/assets/962095/bae2740c-240e-4ab0-b60c-0fbfee077bbd

fix: dashboard filter popover state

---

packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/GroupsView.tsx
packages/frontend/src/hooks/useOrganizationGroups.ts

Closes: #8430 
Enable deleting groups from the UI.

chore: enable deleting groups

---

packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/UsersView.tsx

Adds a clear button and set width to user search, as requested by @PriPatel 
Now:

feat: add clear to user search

---

packages/frontend/src/components/ProjectAccess/ProjectAccessRow.tsx
packages/frontend/src/components/UserSettings/AccessTokensPanel/TokensTable.tsx
packages/frontend/src/components/UserSettings/DeleteOrganizationPanel/DeleteOrganizationModal.tsx
packages/frontend/src/components/UserSettings/UserAttributesPanel/index.tsx
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/UsersView.tsx
packages/frontend/src/components/common/modal/ChartDeleteModal.tsx
packages/frontend/src/components/common/modal/DashboardDeleteModal.tsx
packages/frontend/src/components/common/modal/DeleteChartTileThatBelongsToDashboardModal.tsx
packages/frontend/src/features/scheduler/components/SchedulerDeleteModal.tsx
packages/frontend/src/features/sync/components/SyncModalDelete.tsx
packages/frontend/src/features/tableCalculation/components/DeleteTableCalculationModal.tsx

Closes: N/A
Update `Cancel` button in delete modals to be `color="dark"`
Screenshots

style: change cancel button color to dark on delete modals

---

dockerfile

This PR consolidate the `RUN` statements by combine them together using `&&` operator in the Dockerfile. This change will reduce the total layers, for additional reference [see](https://docs.docker.com/develop/dev-best-practices/#how-to-keep-your-images-small)

chore: consolidate RUN instructions

---

docs/docs/references/user-attributes.mdx

Closes: #8468 
Adds docs for multiple values for user attributes (this PR that just closed: https://github.com/lightdash/lightdash/pull/8466)

docs: adds docs for multiple values for user attributes

---

packages/frontend/src/components/SimplePieChart/index.tsx

Closes: https://github.com/lightdash/lightdash-commercial/issues/46

fix: only show pie chart context menu if user is authenticated

---

packages/backend/src/services/ProjectService/ProjectService.ts

Closes: #8403 
On totals query:
- add the correct warehouse override for snowflake client
- add query tags

fix: add tags and warehouse to totals query

---

docs/docs/guides/cli/how-to-use-lightdash-preview.mdx

docs: how to use developer credentials in your preview project

---

packages/frontend/src/hooks/useOrganizationGroups.ts

Fix 'undefined' in update toast

fix: undefined group name in update toast

---

packages/backend/src/controllers/groupsController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/GroupsModel.ts
packages/backend/src/services/GroupService.ts
packages/common/src/types/projectGroupAccess.ts
packages/e2e/cypress/e2e/api/groups.cy.ts

backend for: https://github.com/lightdash/lightdash/issues/8543
adds backend to allow updating `role` for project group access
also adds e2e

feat: project group access update backend

---

packages/frontend/src/components/ProjectAccess/ProjectAccessRow.tsx
packages/frontend/src/components/ProjectAccess/index.tsx
packages/frontend/src/features/projectGroupAccess/components/ProjectGroupAccess.tsx
packages/frontend/src/features/projectGroupAccess/components/ProjectGroupAccessItem.tsx
packages/frontend/src/features/projectGroupAccess/components/RemoveProjectGroupAccessModal.tsx
packages/frontend/src/features/projectGroupAccess/components/RevokeProjectGroupAccessModal.tsx

feat: project group access list delete

---

packages/backend/src/controllers/authentication.ts

Closes:  #1304
[Screencast from 11-01-24 10:58:46.webm](https://github.com/lightdash/lightdash/assets/1983672/8e43fa7c-be2f-4812-9356-ff70f2905a8a)

fix: use pathname on sso redirection

---

packages/backend/src/routers/projectRouter.ts
packages/backend/src/routers/slackRouter.ts
packages/backend/src/services/CsvService/CsvService.test.ts
packages/backend/src/services/CsvService/CsvService.ts
packages/backend/src/services/UnfurlService/UnfurlService.test.ts
packages/backend/src/services/UnfurlService/UnfurlService.ts
packages/frontend/src/components/NavBar/SettingsMenu.tsx
packages/frontend/src/components/SettingsValidator/ValidatorTable/index.tsx
packages/frontend/src/pages/ProjectSettings.tsx

Closes: https://github.com/lightdash/lightdash-internal-work/issues/1297
Closes: https://github.com/lightdash/lightdash-internal-work/issues/1298

fix: improve csv name handling

---

packages/backend/src/models/ProjectModel/ProjectModel.ts

fix: copy custom dimensions on preview

---

dockerfile
dockerfile-prs

fix: upgrade docker bookworm

---

docs/docs/references/groups.mdx
docs/docs/references/user-attributes.mdx

- adds information about how user + group attribute values are handled

docs: adds docs about groups and user precedence in user attributes

---

docs/docs/references/roles.mdx

adds export results role capabilities for viewer to the docs

docs: adds export results to roles

---

packages/backend/src/services/UserService.ts

Closes: #8481
We already cover creating users using google sso with a differnt email : https://github.com/lightdash/lightdash/blob/main/packages/backend/src/services/UserService.ts#L161
This PR fixes the following use case: 
- a user already has an account and a separate org !
- he gets an invite with a different email
- the user accepts the invite using his other email using google SSO
- that makes him think he accepted the invitation
- now instead of logging the user in his existing account, we throw an error if the login happens via invitation

fix: invite wrong email

---

packages/common/src/index.ts
packages/frontend/src/components/LightdashVisualization/VisualizationConfigPie.tsx
packages/frontend/src/components/VisualizationConfigs/PieChartConfig/PieChartLayoutConfig.tsx
packages/frontend/src/hooks/usePieChartConfig.ts

Closes: https://github.com/lightdash/lightdash/issues/8497

feat: allow table calculations on pie metrics

---

.github/CONTRIBUTING.md

Since this whole section is a code block it's better to have that line marked as a comment too otherwise it cannot be copy-pasted without error.

chore: Update CONTRIBUTING.md docker-compose code snippet

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx

Closes: 
https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers
Short answer - de facto limit of 2000 characters
I thought about keeping the existing href functionality for links < 2000 chars, but links right now are  unlikely to be 2000 chars even for simple bignumber charts. 
[Screencast from 15-01-24 12:11:06.webm](https://github.com/lightdash/lightdash/assets/1983672/2b1a4dda-dd8f-4699-a7a0-5e2fca34af5f)
side effects: 
* Clicking `back` on explore does`t take you back to the dashboard (you need to click it twice) , this is because we do a redirection, we should fix it on a separate pr an do a replacement on history rather than a push. 
* You can't copy the link from the LinkButton anymore, this is because the shared link is generated on …

fix: explore from here long url

---

packages/frontend/src/components/DashboardTiles/TileForms/TileUpdateModal.tsx

chore: remove extra s in `cancels`

---

packages/frontend/src/components/UserCompletionModal/index.tsx

Closes: 
https://github.com/lightdash/lightdash/assets/962095/ccfed9f1-f2fd-4b04-b3fc-a5dce118ec19

fix: org signup domain whitelist

---

packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

fix: table calculation format tooltip

---

packages/backend/src/services/ProjectService/ProjectService.ts

fix: add query tags totals

---

packages/frontend/src/hooks/dashboard/useDashboardStorage.tsx
packages/frontend/src/hooks/toaster/useToaster.tsx
packages/frontend/src/pages/Dashboard.tsx
packages/frontend/src/providers/DashboardProvider.tsx

Closes: 
https://github.com/lightdash/lightdash/assets/962095/aa7a3a4b-feba-4c45-8ddc-a4808d40c0e6

fix: create chart from dashboard

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/models/GroupsModel.ts
packages/backend/src/services/GroupService.ts
packages/backend/src/services/OrganizationService/OrganizationService.ts
packages/backend/src/services/UserAttributesService/UserAttributesService.ts
packages/backend/src/services/UserService.ts

Closes: #8531 
Add events:
```
export type GroupCreateAndUpdateEvent = BaseTrack & {
event: 'group.created' | 'group.updated';
userId: string;
properties: {
organizationId: string;
groupId: string;
name: string;
countUsersInGroup: number;
viaSso: boolean;
};
};
export type GroupDeleteEvent = BaseTrack & {
event: 'group.deleted';
userId: string;
properties: {
organizationId: string;
groupId: string;
};
};
```
Updated : 
```
export type UserAttributeCreateAndUpdateEvent = BaseTrack & {
event: 'user_attribute.created' | 'user_attribute.updated';
userId: string;
properties: {
organizationId: string;
attributeId: string;
name: string;
description?: string;
values: {
userIds: string[];
values: string[];
groupIds: string[];
groupValues: string[];
};
defaultValue: string | null;
};
};
```

chore: group events

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/DashboardTiles/TileBase/index.tsx

Closes:  https://github.com/lightdash/lightdash/issues/8473
Removed unnecessary wrappers from header

fix: remove links from minimal charts

---

packages/backend/src/services/ValidationService/ValidationService.mock.ts
packages/backend/src/services/ValidationService/ValidationService.test.ts
packages/backend/src/services/ValidationService/ValidationService.ts
packages/common/src/types/validation.ts

feat: validate custom metrics missing dimensions

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx

fix: open explore from here new tab

---

packages/common/src/types/projectMemberRole.ts
packages/frontend/src/components/ProjectAccess/CreateProjectAccessModal.tsx
packages/frontend/src/components/ProjectAccess/ProjectAccess.tsx
packages/frontend/src/components/ProjectAccess/ProjectAccessRow.tsx
packages/frontend/src/components/ProjectAccess/RemoveProjectAccessModal.tsx
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/UsersView.tsx

Closes: https://github.com/lightdash/lightdash/issues/8512
Closes: https://github.com/lightdash/lightdash/issues/8499

feat: update role ux in projec access list

---

packages/backend/src/routers/projectRouter.ts
packages/backend/src/routers/slackRouter.ts

Thread: https://lightdash.slack.com/archives/C02GQKJK84Q/p1705925966746589
TEsted images on email

fix: normalize path

---

packages/frontend/src/pages/SqlRunner.tsx

Closes: #8679 
Wraps the "Refresh dbt" button in a box to preserve button alignment when "Refresh dbt" not relevant, consistent with other pages

fix: Button alignment in SQLRunner

---

packages/backend/src/@types/knex-tables.d.ts
packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/controllers/userController.ts
packages/backend/src/database/entities/userWarehouseCredentials.ts
packages/backend/src/database/entities/warehouseCredentials.ts
packages/backend/src/database/migrations/20240119163546_add_user_credentials_table.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/UserWarehouseCredentials/UserWarehouseCredentialsModel.ts
packages/backend/src/models/models.ts
packages/backend/src/services/UserService.ts
packages/backend/src/services/services.ts
packages/common/src/index.ts
packages/common/src/types/userWarehouseCredentials.ts
packages/e2e/cypress/e2e/api/userWarehouseCredentials.cy.ts

Relates to: #8611 
Endpoints to list/create/update/delete user warehouse credentials.

feat(API): user warehouse credentials

---

packages/common/src/index.ts

chore: remove unused import

---

packages/common/src/types/field.ts
packages/common/src/utils/item.ts
packages/frontend/src/components/Explorer/CustomMetricModal/index.tsx
packages/frontend/src/features/tableCalculation/components/FormatForm.tsx
packages/frontend/src/features/tableCalculation/components/TableCalculationModal.tsx

Relates to:  #8688
Add compatibility between 2 forms: Table calculation Modal and Custom metric modal

feat: add formatting inputs to custom metric accordion

---

packages/common/src/utils/conditionalFormatting.ts
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormatting.tsx

Closes: https://github.com/lightdash/lightdash/issues/8710
https://github.com/lightdash/lightdash/assets/962095/97e89feb-2a06-4186-9516-9bc656895647

fix: conditional formatting range with decimal numbers

---

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/AxesOptions.tsx
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: #2943
This PR is restoring an old commit that was reverted because the bars looked bad outside of the chart, this PR is also addressing that issue. 
Before:
After:.

feat: limit axis range 2

---

packages/backend/src/models/UserWarehouseCredentials/UserWarehouseCredentialsModel.ts
packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/services.ts
packages/backend/src/types.ts
packages/common/src/types/projects.ts
packages/frontend/src/components/ProjectConnection/WarehouseForms/PostgresForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/RedshiftForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/SnowflakeForm.tsx
packages/frontend/src/components/ProjectConnection/WarehouseForms/TrinoForm.tsx

Closes: #8630 
Changes:
- update warehouse form
- use user warehouse credential if required
- remove method that is tech debt 
https://github.com/lightdash/lightdash/assets/9117144/b2efce47-9e31-4e11-b012-0fb984a610b4
Note this feature is behind a feature flag for now.

feat: allow project to require users credentials

---

packages/frontend/src/components/UserCompletionModal/index.tsx

Closes: https://github.com/lightdash/lightdash/issues/8731
https://github.com/lightdash/lightdash/assets/962095/54fa99af-afe4-4630-85f3-5b7f76416cd8
https://github.com/lightdash/lightdash/assets/962095/a9f0e5ae-54d2-460b-9ff9-8fdc4ade6c2a

fix: onboarding enabled domain access for email providers

---

packages/backend/src/@types/knex-tables.d.ts
packages/backend/src/controllers/projectController.ts
packages/backend/src/database/entities/userWarehouseCredentials.ts
packages/backend/src/database/migrations/20240125152923_create_project_user_warehouse_credentials_preference_table.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/models/UserWarehouseCredentials/UserWarehouseCredentialsModel.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/index.ts
packages/common/src/types/organization.ts
packages/common/src/types/userWarehouseCredentials.ts
packages/e2e/cypress/e2e/api/userWarehouseCredentials.cy.ts

Relates to: #8633 
Changes:
- add endpoint to get project-preferred credentials
- add endpoint to update project-preferred credentials
- update project service logic to use preferred credentials 
- update org projects endpoint to return what is the project warehouse type and if they require user credentials
Note: UI in separate PR https://github.com/lightdash/lightdash/pull/8744

feat(API): project credentials preference

---

packages/backend/src/generated/swagger.json
packages/backend/src/models/UserWarehouseCredentials/UserWarehouseCredentialsModel.ts
packages/frontend/src/components/NavBar/UserCredentialsSwitcher.tsx
packages/frontend/src/components/NavBar/index.tsx
packages/frontend/src/components/UserSettings/MyWarehouseConnectionsPanel/CreateCredentialsModal.tsx
packages/frontend/src/hooks/userWarehouseCredentials/useProjectUserWarehouseCredentialsPreference.ts
packages/frontend/src/hooks/userWarehouseCredentials/useUserWarehouseCredentials.ts

Closes: #8633 
Changes
- add UI to switch preferred credentials
- add UI to create credentials for active project

feat: update project credentials preference

---

packages/backend/src/models/UserWarehouseCredentials/UserWarehouseCredentialsModel.ts
packages/frontend/src/components/NavBar/UserCredentialsSwitcher.tsx
packages/frontend/src/components/UserSettings/MyWarehouseConnectionsPanel/CreateCredentialsModal.tsx
packages/frontend/src/hooks/userWarehouseCredentials/useProjectUserWarehouseCredentialsPreference.ts

Closes: #8631 
https://github.com/lightdash/lightdash/assets/9117144/199b7607-95ac-4061-88cc-b30b36387938
Updated copy:

feat: automatically show modal to add user warehouse credentials

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/types/field.ts
packages/frontend/src/components/Explorer/CustomMetricModal/index.tsx

Closes: #8689 
Resets form on close of modal 
Populates values correctly when editing form 
Improve types in `CustomFormat`

feat: finalise editing of custom metric format

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/services/ProjectService/ProjectService.ts

Closes: #8685 
Add events for custom metrics formatting: 
```
additionalMetricsPercentFormatCount: number;
additionalMetricsCurrencyFormatCount: number;
additionalMetricsNumberFormatCount: number;
```

chore: add analytics events for custom metric formatting

---

packages/frontend/.eslintrc.js
packages/frontend/package.json
packages/frontend/src/components/UserCompletionModal/UserCompletionModal.test.tsx
packages/frontend/src/components/UserCompletionModal/UserCompletionModal.tsx
packages/frontend/src/providers/AppProvider.tsx
packages/frontend/src/testing/__mocks__/implementations/matchMedia.mock.ts
packages/frontend/src/testing/__mocks__/implementations/resizeObserver.mock.ts
packages/frontend/src/testing/__mocks__/providers/AppProvider.mock.tsx
packages/frontend/src/testing/testUtils.tsx
packages/frontend/src/testing/vitest.setup.ts
packages/frontend/vite.config.ts
yarn.lock

Closes: 
- adds jest-dom / react-testing-library eslint plugins/extensions
- improves mocks
- adds component tests for `UserCompletionModal`
- fixes bug in the component where signing up a new org member would enable domain auth
- ^^^ this is why we need these tests 🤷

test: user completion modal

---

packages/frontend/src/features/tableCalculation/components/SqlForm.tsx

Adds support for soft-wrapping while editing table calculation expressions.
Simply exposes the underlying ace editor feature, and should be straight-forward to include this behavior in an SqlRunner component follow-up.

feat: Support soft-wrapping in SqlEditor for table calculations

---

packages/backend/src/services/SearchService/SearchService.ts

Closes: https://github.com/lightdash/lightdash/issues/8752
Before:
After:

fix: search admin access

---

packages/frontend/src/components/Explorer/CustomMetricModal/index.tsx

Closes: #7344
Remove feature flag

feat: remove flag check for custom metrics formatting

---

packages/e2e/cypress/e2e/api/spacePermissions.cy.ts

chore: fix search permission test

---

packages/frontend/src/hooks/useQueryResults.tsx

fix: dont show duplicate error when running a query

---

packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/index.tsx
packages/frontend/src/components/Explorer/ExploreTree/index.tsx

Closes:  https://github.com/lightdash/lightdash/issues/7873
Removing a metric: 
[Screencast from 01-02-24 17:07:03.webm](https://github.com/lightdash/lightdash/assets/1983672/63e96b43-4547-4223-b5b4-60e6527a5969)
Removing a dimension: 
[Screencast from 01-02-24 17:07:59.webm](https://github.com/lightdash/lightdash/assets/1983672/45559489-2883-4d2f-9e5a-3bca9f4b5653)

fix: missing metrics and dimensions on charts

---

packages/frontend/src/pages/Projects.tsx

Closes: #8835 
https://github.com/lightdash/lightdash/assets/962095/7303f1cb-05cb-4a8e-88ab-f52b48a70526

fix: no project access redirect

---

packages/backend/src/controllers/exploreController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json

Closes:  https://github.com/lightdash/lightdash/issues/8831
tion:

fix: custom label csv export

---

packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
packages/frontend/src/components/Explorer/ExploreTree/index.tsx

fix: table calculation missing fields

---

packages/e2e/cypress/e2e/app/dates.cy.ts
packages/e2e/cypress/e2e/app/downloadCsv.cy.ts
packages/e2e/cypress/e2e/app/explore.cy.ts
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
packages/frontend/src/pages/SqlRunner.tsx

Closes: N/A
Rename `Charts` to `Chart` accordion

chore: rename Charts to Chart accordion title

---

packages/backend/src/database/entities/dashboards.ts
packages/backend/src/database/migrations/20240207133122_add_search_vector_to_dashboards.ts
packages/backend/src/models/SearchModel/index.ts

feat: fulltext search

---

packages/backend/src/models/SearchModel/index.ts

feat: order by cosine similarity

---

packages/backend/package.json
packages/backend/src/database/seeds/development/05_generate_fake_data.ts
packages/backend/src/models/SearchModel/index.ts
packages/backend/src/routers/dashboardRouter.ts
packages/backend/src/services/DashboardService/DashboardService.ts
yarn.lock

chore: faker + bakfill + search query

---

packages/frontend/src/features/scheduler/constants/index.ts

Closes: N/A
Added more human-readable copy to the scheduled deliveries preview options.

fix: update scheduled delivery preview copy to be more user-friendly

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/tsoa.yml

Closes: https://github.com/lightdash/lightdash/issues/8834
- Go to jaffle dashboard 
- explore from here on a chart
- show sql code 
- it should not fail now

fix: allow additional properties tsoa

---

packages/frontend/src/components/ProjectAccess/ProjectAccess.tsx
packages/frontend/src/components/UserSettings/UserAttributesPanel/UserAttributeModal.tsx
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/GroupsView.tsx
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/UsersView.tsx
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/index.tsx
packages/frontend/src/features/projectGroupAccess/components/ProjectGroupAccess.tsx
packages/frontend/src/hooks/useOrganizationGroups.ts

Closes: #8801 
- Add group search
- Move Add user and Add group buttons into table header

feat: group search and users-group styles

---

.gitignore

chore: add .envrc to .gitignore

---

dockerfile
dockerfile-prs

Closes: 
Upgrade packages with `fix available` 
- systemd/libsystemd0
- gnutls28/libgnutls30
- tar

fix: upgrade bookworm packages

---

packages/backend/src/services/UnfurlService/UnfurlService.ts

Closes: N/A
Add more span attributes to screenshot logger

chore: add more span attributes to screenshots

---

packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx

Removes restrictions around adding the same chart multiple times to the same dashboard.

feat: Allow adding the same chart to a dashboard more than once

---

packages/frontend/src/components/ProjectTablesConfiguration/ProjectTablesConfiguration.tsx

Closes: #8753 
Added ability to search in table configuration panel for both models as well as tags.
Tags search:
Models search:

feat: searchable table and tags in table config

---

packages/e2e/cypress/e2e/app/sqlrunner.cy.ts

fix: sqlrunner.cy.ts tests

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLine.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/BasicSeriesConfiguration.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/SingleSeriesConfiguration.tsx
packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Series/index.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/ConditionalFormatting.tsx
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts
packages/frontend/src/hooks/echarts/useEchartsPieConfig.ts
packages/frontend/src/hooks/useChartColorConfig.ts
packages/frontend/src/hooks/usePieChartConfig.ts

Follow-up to https://github.com/lightdash/lightdash/pull/8856, with additional improvements to how colors are assigned, support for pie charts, and to the underlying code.

feat: improvements to shared color assignment

---

packages/backend/src/database/entities/spaces.ts
packages/backend/src/database/migrations/20240207133122_add_search_vector_to_dashboards.ts
packages/backend/src/database/migrations/20240214160420_add_search_vector_to_charts.ts
packages/backend/src/database/migrations/20240215091924_add_search_vector_to_spaces.ts
packages/backend/src/models/DashboardModel/DashboardModel.mock.ts
packages/backend/src/models/SearchModel/index.ts
packages/backend/src/services/DashboardService/DashboardService.mock.ts

Related to: https://github.com/lightdash/lightdash/issues/5631
- Adds full text search to spaces
Note: waiting on https://github.com/lightdash/lightdash/pull/8933 to be merged so I can rebase and reuse the correct function name for the search rank raw sql

feat: add full text search to spaces

---

packages/backend/src/clients/EmailClient/EmailClient.ts
packages/backend/src/scheduler/SchedulerTask.ts
packages/frontend/src/features/scheduler/components/SchedulerForm.tsx

feat: send email on threshold alerts

---

packages/backend/src/database/seeds/development/05_generate_fake_data.ts

chore: search fake data

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/scheduler/SchedulerTask.ts
packages/frontend/src/features/scheduler/components/SchedulerForm.tsx

chore: add analytic events threshold alert

---

packages/backend/src/clients/Slack/SlackMessageBlocks.ts
packages/backend/src/scheduler/SchedulerTask.ts

feat: threshold alert slack add image

---

docs/docs/guides/cli/how-to-use-lightdash-preview.mdx

Closes: 
Docs on how to create preview projects when using dbt cloud IDE.

docs: how to use dbt cloud schema in your preview project

---

packages/backend/src/generated/swagger.json
packages/common/src/types/search.ts
packages/frontend/src/components/NavBar/GlobalSearch/hooks.ts
packages/frontend/src/hooks/globalSearch/useGlobalSearch.ts

Closes: 
- Orders all the search results by their rank agains the query

fix: order search results by rank

---

packages/backend/src/controllers/schedulerController.ts
packages/backend/src/database/entities/scheduler.ts
packages/backend/src/database/migrations/20240219150917_scheduler_active_flag.ts
packages/backend/src/database/migrations/20240219150917_scheduler_enabled_flag.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/SchedulerModel/index.ts
packages/backend/src/scheduler/SchedulerTask.ts
packages/backend/src/services/SchedulerService/SchedulerService.ts
packages/common/src/types/scheduler.ts
packages/frontend/src/features/scheduler/components/SchedulerForm.tsx
packages/frontend/src/features/scheduler/components/SchedulersListItem.tsx
packages/frontend/src/features/scheduler/hooks/useSchedulersUpdateMutation.ts
packages/frontend/src/features/sync/components/SyncModalForm.tsx

feat: scheduler active flag

---

packages/backend/src/clients/Slack/SlackMessageBlocks.ts
packages/backend/src/scheduler/SchedulerTask.ts
packages/common/src/types/scheduler.ts
packages/frontend/src/features/scheduler/components/SchedulerForm.tsx

fix: update copy threshold alerts

---

.github/workflows/duplicate-external-pr.yml

Closes: 
passes `GITHUB_CI_TOKEN` to the necessary steps, so we can utilise the `gh` CLI and also push

chore: fix PR creation with the correct token

---

packages/frontend/src/components/ExploreFromHereButton/index.tsx

Closes: #8825
Before:
https://github.com/lightdash/lightdash/assets/9117144/ad959a84-dbb0-403c-9080-e392b93879d3
After:
https://github.com/lightdash/lightdash/assets/9117144/b37446ee-3f3c-4f14-ba8b-c7df5d8935f3

fix: explore from chart with long url

---

packages/frontend/src/features/scheduler/components/SchedulersListItem.tsx

fix: scheduler enabled tooltip

---

packages/frontend/src/features/scheduler/components/SchedulerModal.tsx

fix: add docs panel

---

packages/common/src/types/featureFlags.ts
packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx

fix: remove feature flag alert

---

.github/CONTRIBUTING.md
docs/docs/self-host/customize-deployment/configure-lightdash-to-use-an-external-database.mdx

Closes: [#9036](https://github.com/lightdash/lightdash/issues/9036)
- Adds minimum PostgresSQL version of >=12 to docs

docs: add notes on postgres minimum version

---

.github/workflows/duplicate-external-pr.yml

Closes: N/A
Utilise `duplicate-external-pr` script as a reference.

chore: update duplicate external pr script in gh action

---

packages/backend/src/models/SearchModel/index.ts
packages/common/src/types/search.ts

Relates to: [#5266](https://github.com/lightdash/lightdash/issues/5266)
- Adds type filter for page
- Improves types for entity type filter

feat: add page type filter to global search

---

packages/backend/src/models/SearchModel/index.ts
packages/backend/src/routers/projectRouter.ts
packages/common/src/types/search.ts

Relates to: #5266 
- with no filters: http://localhost:3000/api/v1/projects/3675b69e-8324-4110-bdca-059031aa8da3/search/jaffle
```json
{"status":"ok","results":{"spaces":[{"uuid":"30b82864-de5d-4935-97c7-e4a40819a601","name":"Jaffle shop","search_rank":0.6079271}],"dashboards":[{"uuid":"9c22b362-9e22-4c5c-9927-3d6979fdf902","name":"Jaffle dashboard","description":null,"spaceUuid":"30b82864-de5d-4935-97c7-e4a40819a601","search_rank":0.6079271,"validationErrors":[]}],"savedCharts":[],"tables":[],"fields":[],"pages":[]}}
```
- with `fromDate` filter: http://localhost:3000/api/v1/projects/3675b69e-8324-4110-bdca-059031aa8da3/search/jaffle?fromDate=2024-02-21
```json
{"status":"ok","results":{"spaces":[{"uuid":"30b82864-de5d-4935-97c7-e4a40819a601","name":"Jaffle …
```

feat: add created at filter backend to global search

---

packages/e2e/cypress/e2e/app/dates.cy.ts

fix: e2e dates failing sporadically when trying to close the chart panel

---

packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: #9059
Before: total stays the same
https://github.com/lightdash/lightdash/assets/9117144/6758c7a0-6823-4a87-b382-6224b825d99c
After: total updates
https://github.com/lightdash/lightdash/assets/9117144/21ed2da7-37ff-4fce-9f18-9591bf037507

fix: stack totals when using custom series labels

---

packages/frontend/src/features/omnibar/api/search.ts
packages/frontend/src/features/omnibar/components/Omnibar.tsx
packages/frontend/src/features/omnibar/components/OmnibarFilters.tsx
packages/frontend/src/features/omnibar/components/OmnibarItemGroups.tsx
packages/frontend/src/features/omnibar/hooks/useSearch.ts
packages/frontend/src/features/omnibar/utils/getDateFilterLabel.ts

- Adds created at filter to omnibar

feat: add omnibar created at filter

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json

chore: generate api

---

docs/docs/references/metrics.mdx

Removes dbt metrics docs and replaces with reference to Semantic Layer.

docs: removes dbt metrics docs

---

packages/backend/src/inMemoryTableCalculations.ts

Closes: #9045 
Measures time spent building column vectors prior to loading data into duckdb.

chore: measure time spent building column vectors for in-memory table calcs.

---

packages/common/src/types/featureFlags.ts
packages/frontend/src/components/CustomSqlPanel/CustomSqlPanel.tsx
packages/frontend/src/pages/Settings.tsx

Puts custom SQL behind a feature flag

fix: feature flag custom sql

---

packages/frontend/src/features/omnibar/components/Omnibar.tsx
packages/frontend/src/features/omnibar/components/OmnibarFilters.tsx
packages/frontend/src/features/omnibar/components/OmnibarItem.tsx
packages/frontend/src/features/omnibar/components/OmnibarTarget.tsx
packages/frontend/src/features/omnibar/utils/getDateFilterLabel.ts

fix: search v2 UI

---

packages/frontend/src/features/omnibar/components/OmnibarFilters.tsx

Closes: [#9105](https://github.com/lightdash/lightdash/issues/9105)
- Shows button to clear all filters if there are any applied
https://github.com/lightdash/lightdash/assets/22939015/db961b6a-0e2b-4ad8-96c0-6425ebe9b103

feat: add clear filters button when there are filters applied

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json

chore: generate-api

---

packages/common/src/types/search.ts
packages/frontend/src/features/omnibar/components/Omnibar.tsx
packages/frontend/src/features/omnibar/components/OmnibarItem.tsx
packages/frontend/src/features/omnibar/components/OmnibarItemGroups.tsx
packages/frontend/src/features/omnibar/components/OmnibarKeyboardNav.tsx
packages/frontend/src/features/omnibar/types/searchItem.ts

Closes: #5256 
- Adds keyboard navigation to omnibar

feat: add omnibar keyboard navigation

---

packages/backend/setupJest.ts
packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/analytics/client.ts
packages/backend/src/clients/Google/GoogleDriveClient.ts
packages/backend/src/clients/clients.ts
packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/models/DashboardModel/DashboardModel.test.ts
packages/backend/src/models/InviteLinkModel.ts
packages/backend/src/models/UserModel.ts
packages/backend/src/models/models.ts
packages/backend/src/services/OrganizationService/OrganizationService.test.ts
packages/backend/src/services/OrganizationService/OrganizationService.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/UserService.ts
packages/backend/src/services/services.ts

Closes: #9147 
changes:
- remove `import {lightdashConfig}` where possible. Where not possible, created a bullet point in #9099
- convert static methods and properties that depend on lightdash config to be private
- amend test mocks

fix: inject lightdashConfig dependency

---

packages/frontend/src/components/NavBar/ProjectSwitcher.tsx

Closes: https://github.com/lightdash/lightdash/issues/9175
https://github.com/lightdash/lightdash/assets/962095/79e72c0f-eb3b-426b-af58-eaead8ca0ab6

fix: project switcher long list

---

packages/warehouses/package.json
yarn.lock

fix: upgrade databricks library to 1.8.1

---

packages/backend/src/models/NotificationsModel/NotificationsModel.ts
packages/common/src/index.ts
packages/common/src/types/notifications.ts
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/NavBar/NotificationsMenu/index.tsx
packages/frontend/src/features/comments/components/CommentWithMentions/index.tsx
packages/frontend/src/features/comments/components/DashboardTileComments.tsx
packages/frontend/src/features/comments/hooks/useDashboardCommentsCheck.ts
packages/frontend/src/features/notifications/components/DashboardCommentsNotifications.tsx
packages/frontend/src/features/notifications/hooks/useNotifications.tsx
packages/frontend/src/features/notifications/index.ts

Closes: #9122 
Adds UI for notifications for dashboard comments
Has `viewed`/`read` state
On click, it will direct the user to the dashboard

feat: display notification if user mentioned in comment

---

yarn.lock

- `yarn.lock` in `main` branch is out of date, just had to run `yarn install` on the root of the project

chore: run yarn for the repo

---

.github/CONTRIBUTING.md

Closes: 
These are not actual commands so they should be prepended with a # .

chore: Update CONTRIBUTING.md

---

packages/frontend/src/features/notifications/components/DashboardCommentsNotifications.tsx
packages/frontend/src/providers/TrackingProvider.tsx
packages/frontend/src/types/Events.ts

Closes: #9121 
On Notification Comment Item click

chore: add notification comments item click event

---

packages/frontend/src/features/comments/components/CommentDetail.tsx
packages/frontend/src/features/comments/components/CommentForm.tsx
packages/frontend/src/features/comments/components/CommentTimestamp.tsx
packages/frontend/src/features/comments/components/CommentWithMentions/SuggestionList.tsx
packages/frontend/src/features/comments/components/CommentWithMentions/index.tsx
packages/frontend/src/features/comments/components/DashboardCommentAndReplies.tsx
packages/frontend/src/features/comments/components/DashboardTileComments.tsx

Closes: #9135 
- Smaller comment timestamp tooltip
- Use `Menu` component to list user mentions
- Address width issues - fixed and popover doesn't increase width if the comment text is looooong
- Make icon to reply more subtle, but also make it less easy to delete a comment (under another menu)
- Add a top border to the main comment input
- Increase height of the comment list
- Bolder comment author names
- Scroll to the bottom every time there's a new comment added by the user - this does not apply to replies
- Only show the reply text input if I hit reply
- Less padding on the text input (mimics current text inputs)
- Suggestions list (users that I want to tag) can be scrollable with a maxheight as well
https://github.com/lightdash/lightdash/assets/7611706/84b201e2-57fb-4623-a5a1-38dc9f4 …

chore: apply ui improvements to dashboard comments

---

README.md
docs/docs/contact/contact_info.md
docs/docs/guides/dbt-semantic-layer.mdx
docs/docs/intro.md
docs/docusaurus.config.js
packages/frontend/src/components/NavBar/HelpMenu.tsx
scripts/install.sh

Closes: 
Found a broken Slack link and replaced all occurences with the one in the navbar on lightdash.com.
+1 broken link in the footer

docs: update broken links

---

docs/docs/references/roles.mdx

Closes: #9002
https://deploy-preview-9212--peaceful-bassi-cbf284.netlify.app/references/roles

chore: add comment docs

---

packages/backend/src/index.ts
packages/backend/src/scheduler.ts
packages/backend/src/scheduler/SchedulerTask.ts
packages/backend/src/scheduler/SchedulerWorker.ts
packages/backend/src/services/services.ts

Closes: #9173 
No business logic was changed.
Changes:
- created a SchedulerTask class
- moved all functions inside that class
- SchedulerWorker class now extends SchedulerTask class
- fixed functions to use class properties instead of importing services/clients

fix: scheduler dependency injection

---

packages/e2e/cypress/e2e/app/globalSearch.cy.ts
packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx

Closes: #9207 
Steps to reproduce:
1. Click on a chart
2. Click "Edit chart"
After:

fix: wraps components with provider rather than condition

---

packages/frontend/src/features/comments/components/CommentForm.tsx

fix: hide unregistered users

---

packages/backend/src/App.ts
packages/backend/src/index.ts

Closes: #9218 
Changes:
- create App class
- move all the server and clients initialization inside the class
- keep access to `process` outside the app class.
Following PRs will slowly improve the dependency injection in the App class and everything inside it.

fix: app class

---

docs/docs/guides/cli/how-to-use-lightdash-validate.mdx
packages/cli/src/handlers/validate.ts
packages/cli/src/index.ts

Closes: #9088
Without --preview 
with --preview

fix: validate preview cli

---

packages/backend/src/SchedulerApp.ts
packages/backend/src/scheduler.ts

Closes: #9225 
Context: the scheduler worker can run in the same container as the Lightdash server OR it can run in a separate container. This refactor impacts the later. 
Demo: Standalone scheduler app logs showing it compiled a project with success.
Changes:
- create scheduler app class
- move all the setup inside the class
- don't access `process` inside the clas
Needs to be tested locally as we don't run a standalone scheduler in our staging environemnts:
1. Add env var `SCHEDULER_ENABLED=false`
2. Run the standalone scheduler with one of the options:
- Run `yarn workspace backend scheduler-dev`
- Update docker compose to create the standalone scheduler container
```
scheduler:
build:
context: ..
dockerfile: dockerfile
target: dev
depends_on:
- db-dev
entrypoint: [ "yarn", …
```

fix: scheduler app class

---

packages/backend/src/controllers/commentsController.ts
packages/backend/src/controllers/csvController.ts
packages/backend/src/controllers/dbtCloudIntegrationController.ts
packages/backend/src/controllers/exploreController.ts
packages/backend/src/controllers/gitIntegrationController.ts
packages/backend/src/controllers/githubController.ts
packages/backend/src/controllers/googleDriveController.ts
packages/backend/src/controllers/groupsController.ts
packages/backend/src/controllers/metricFlowController.ts
packages/backend/src/controllers/notificationsController.ts
packages/backend/src/controllers/organizationController.ts
packages/backend/src/controllers/pinningController.ts
packages/backend/src/controllers/projectController.ts
packages/backend/src/controllers/runQueryController.ts
packages/backend/src/controllers/savedChartController.ts
packages/backend/src/controllers/schedulerController.ts
packages/backend/src/controllers/shareController.ts
packages/backend/src/controllers/slackController.ts
packages/backend/src/controllers/spaceController.ts
packages/backend/src/controllers/sshController.ts
packages/backend/src/controllers/userAttributesController.ts
packages/backend/src/controllers/userController.ts
packages/backend/src/controllers/validationController.ts

Follow-up to #9232 
_Will rebase before merging, once the above is merged._
Updates all controllers to use `BaseController`. This essentially does not change anything in the controllers' behavior, and depends on work that'll be part of a follow-up PR. See the related PR above for more context.

chore: update controllers to use new `BaseController`

---

docs/docs/guides/how-to-embed-content.mdx
docs/docs/references/embedding.mdx

docs: update embedding docs

---

packages/backend/src/App.ts

fix: add missing next() call

---

README.md
docs/docs/contact/contact_info.md

fix community link in readme and contact info

docs: fix community link in contact info

---

packages/frontend/src/components/SimpleChart/index.tsx
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: #9087
Before
[Screencast from 06-03-24 11:49:14.webm](https://github.com/lightdash/lightdash/assets/1983672/b035d6a3-7b43-4bcd-9727-23261a394a6a)
After
[Screencast from 06-03-24 11:49:37.webm](https://github.com/lightdash/lightdash/assets/1983672/f79589f7-0469-46a2-9219-36e298e1effa)
[Screencast from 06-03-24 11:52:30.webm](https://github.com/lightdash/lightdash/assets/1983672/52eb3b2a-4e86-447f-b0e4-e4ea2d55566d)
Related PR https://github.com/lightdash/lightdash/pull/7290

fix: date/number tooltip

---

packages/common/src/types/featureFlags.ts
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/components/DashboardTiles/DashboardLoomTile.tsx
packages/frontend/src/components/DashboardTiles/DashboardMarkdownTile.tsx
packages/frontend/src/components/NavBar/NotificationsMenu/index.tsx
packages/frontend/src/features/comments/hooks/useDashboardCommentsCheck.ts
packages/frontend/src/providers/DashboardProvider.tsx

Closes: N/A
Remove Feature Flag check for `dashboard-tile-comments`

chore: remove dashboard tile comments feature flag check

---

packages/backend/src/services/UnfurlService/UnfurlService.ts

Closes: https://github.com/lightdash/lightdash-internal-work/issues/1546
See ticket for more details

fix: set cookie directly without using headers on puppeteer

---

packages/frontend/src/features/sync/components/SelectGoogleSheetButton.tsx

fix: add google sheet link on sync

---

packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts

Closes: #9200
Changes:
- await query to close
- batch catalog queries in groups of 100
- throw original error instead of `close` error
To replicate the original error you need to override the requests to be 500 or more and change the DATABRICKS_QUERIES_BATCH_SIZE to be 500 ( basically, it creates a single batch of the promises ). 
```
requests = Array.from({ length: 500 }, () => ({
database: 'hive_metastore',
schema: 'default',
table: 'payments',
}));
```

fix: databricks catalog queries to run in batches

---

packages/backend/src/services/ServiceRepository.ts

Adds a stand-in for `EmbedService` in `ServiceRepository`, which must be configured explicitly during repository initialization.

feat: add ServiceRepository.getEmbedService stand-in

---

packages/frontend/src/components/DashboardTiles/TileBase/index.tsx

Closes: #8721
With title:
Without title:
Before:
After (on hover):

fix: hidden menu table chart

---

packages/backend/src/controllers/authentication.ts

Closes: #9336 
###To Reproduce
With lightdash running locally:
1. Run `yarn workspace @lightdash/cli build`
2. Go into `examples/full-jaffle-shop-demo/dbt`
3. Run `../../../packages/cli/dist/index.js login http://localhost:3000/`
4. Run` ../../../packages/cli/dist/index.js preview --profiles-dir=../profiles`

fix: await for loginWithPersonalAccessToken promise

---

packages/frontend/src/components/AboutFooter.tsx
packages/frontend/src/components/NavBar/HelpMenu.tsx
packages/frontend/src/components/NavBar/NotificationsMenu/index.tsx
packages/frontend/src/components/NavBar/SettingsMenu.tsx
packages/frontend/src/components/common/Page/Page.tsx
packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx

Closes: 
Added `aria-label`s for buttons, and some semantic elements.
Before: 
After:

fix: home page a11y issues

---

README.md
docs/docs/contact/contact_info.md
docs/docs/guides/dbt-semantic-layer.mdx
docs/docs/intro.md
packages/frontend/src/components/NavBar/HelpMenu.tsx
scripts/install.sh

Fixes join slack community link in all docs.

docs: fix join Slack community link

---

.github/workflows/build-docker.yml
.github/workflows/cli-tests.yml
.github/workflows/e2e-tests.yml
.github/workflows/release-on-merge.yml
.github/workflows/security.yml
.github/workflows/test-and-build.yml
.github/workflows/test-easy-install.yml
.github/workflows/validate-pr-title.yml

Related: https://github.com/lightdash/lightdash/issues/9028

chore: upgrade github workflows

---

packages/frontend/src/components/common/SqlRunner/CatalogTree.tsx
packages/frontend/src/pages/SqlRunner.tsx

Closes: #9198 
Uses the existing `TableItemDetailPreview` component to add rich markdown description support to tables in the SQL runner.

feat: Add markdown description support to tables list in SQL runner

---

docs/docs/guides/how-to-join-tables.md
docs/docs/references/tables.mdx

Fixes the failing docs build due to a broken reference to `joins.md` (now `joins.mdx`)

docs: fix broken references to `joins.mdx`

---

packages/backend/src/controllers/exploreController.ts
packages/backend/src/controllers/googleDriveController.ts
packages/backend/src/scheduler/SchedulerWorker.test.ts
packages/backend/src/services/CsvService/CsvService.test.ts
packages/backend/src/services/CsvService/CsvService.ts
packages/backend/src/services/DashboardService/DashboardService.test.ts
packages/backend/src/services/DashboardService/DashboardService.ts
packages/backend/src/services/GdriveService/GdriveService.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/SavedChartsService/SavedChartService.ts
packages/backend/src/services/SchedulerService/SchedulerService.ts
packages/backend/src/services/ServiceRepository.ts
packages/backend/src/services/ValidationService/ValidationService.test.ts
packages/backend/src/services/ValidationService/ValidationService.ts

Closes: 
First PR of multiple to inject clients / models / database.

refactor: client injection in services

---

docs/docs/references/dimensions.mdx

Closes: 
Update wrong typing in dimension docs

docs: update dimensions for wrong typing

---

packages/backend/src/App.ts
packages/backend/src/SchedulerApp.ts
packages/backend/src/clients/clients.ts
packages/backend/src/controllers/metricFlowController.ts
packages/backend/src/controllers/slackController.ts
packages/backend/src/schedulerMetrics.ts
packages/backend/src/services/CsvService/CsvService.test.ts
packages/backend/src/services/ServiceRepository.ts
packages/backend/src/services/UserService.test.ts
packages/backend/src/services/services.ts

Closes: 
Merge after https://github.com/lightdash/lightdash/pull/9382
Second PR of multiple to inject clients / models / database.

refactor: initialize clients in App class

---

packages/cli/src/index.ts

fix: use 3rd person singular for descriptions

---

packages/backend/src/App.ts
packages/backend/src/clients/Slack/Slackbot.ts
packages/backend/src/routers/slackRouter.ts
packages/backend/src/services/ServiceRepository.ts
packages/backend/src/services/SlackIntegrationService/SlackIntegrationService.ts

Closes: 
Following the work from https://github.com/lightdash/lightdash/pull/9420 this PR is meant to remove the `models/models.ts` import from the slack router.

refactor: slack integration service

---

packages/frontend/src/features/users/components/LoginLanding.tsx

Add fix from this ticket to the new login: https://github.com/lightdash/lightdash/pull/8486

fix: add flash messages to new login

---

packages/backend/src/controllers/authentication.ts

Closes:  #9333
Reference: https://medium.com/passportjs/pkce-support-for-oauth-2-0-e3a77013b278
Google oauth URL: 
- OpenIDConnectStrategy doesn't seem compatible with this challenge
- okta already has a challenge in place

chore: oauth challenge

---

.github/workflows/test-and-build.yml
dangerfile.ts
package.json
yarn.lock

- Adds [`dangerjs`](https://danger.systems/js/)
- Adds a basic `dangerfile.ts`, and basic harness for running checks
- Adds a step to run `danger` as part of the CI process, with comments + github check support
- Adds a `danger-local-lint` script to run dangerjs locally

chore: add dangerjs

---

packages/backend/src/database/database.ts
packages/backend/src/models/MigrationModel/MigrationModel.ts
packages/backend/src/models/ModelRepository.ts
packages/backend/src/services/HealthService/HealthService.test.ts
packages/backend/src/services/HealthService/HealthService.ts
packages/backend/src/services/ServiceRepository.ts

Closes: 
Refactor health service to depend on a modal rather than the `database` instance itself. The next PR is going to refactor the database.ts file and create the database instance in index.ts instead.

refactor: add migration model

---

packages/frontend/package.json
yarn.lock

Relates to: #8493
All unused packages on the FE are reviewed. 
last steps are in: https://github.com/lightdash/lightdash/issues/8493#issuecomment-2006712546

chore: remove unused postcss-normalize

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/compiler/exploreCompiler.mock.ts
packages/common/src/compiler/exploreCompiler.ts
packages/common/src/types/table.ts

Closes: #9231
My alias in join
Before fix: 
After fix:

fix: exposure join with alias

---

packages/backend/src/models/ModelRepository.ts

chore: add embed model placeholder

---

packages/backend/src/models/ModelRepository.ts

Closes: 
Add database to model provider arguments.

chore: add database to model provider arguments

---

docs/docs/guides/dbt-semantic-layer.mdx

updating the docs to clarify dbt semantic layer access

docs: clarify dbt semantic layer access

---

docs/docs/references/roles.mdx
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/ProjectService/ProjectService.ts

feat: clone preview without private spaces

---

packages/backend/src/models/SearchModel/index.ts

- Allows to search for dashboard charts

fix: join dashboards table to allow search on dashboard charts

---

packages/frontend/src/components/Explorer/ResultsCard/QuickCalculations.tsx

Closes: https://github.com/lightdash/lightdash/issues/9480
Before
After

fix: divide by zero in quick calculations

---

packages/frontend/src/components/Explorer/ExploreTree/index.tsx
packages/frontend/src/mantineTheme.ts
packages/frontend/src/pages/Settings.tsx

Closes: #9406 
Adds `primary` variant to `ScrollArea` component
Uses this new scroll component in: 
- ExploreTree sidebar
- Settings sidebar
Unfortunately, we can't add `defaultProps` to variants: https://github.com/orgs/mantinedev/discussions/5550
https://github.com/lightdash/lightdash/assets/7611706/a9825722-9703-48b7-8681-66b053bc7ca9

style: smaller scrollbar variant

---

packages/frontend/src/pages/Login.tsx

Closes: #9500 
Add a banner explaining new login.

feat: new login banner

---

packages/backend/src/controllers/exploreController.ts
packages/backend/src/services/CsvService/CsvService.ts
packages/common/src/types/csv.ts
packages/common/src/types/scheduler.ts
packages/frontend/src/api/csv.ts
packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx

Closes: #9481
Before: 
csv-payments-2024-03-22-09-56-40-0230.csv
AFter:
csv-how_much_revenue_do_we_have_per_payment_method_-2024-03-22-09-55-57-1410.csv

fix: download csv from dashboard with chart filename

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json

Closes: N/A
Ran `yarn generate-api`

chore: generate-routes

---

packages/frontend/src/features/omnibar/components/Omnibar.tsx

Closes: #9492
Before:
[Screencast from 26-03-24 08:49:33.webm](https://github.com/lightdash/lightdash/assets/1983672/a06f56ba-afd4-40e4-a806-81b4604045f3)
AFter:
[Screencast from 26-03-24 08:53:56.webm](https://github.com/lightdash/lightdash/assets/1983672/2b72b88f-5cde-464e-b85e-2cb1df7a4772)

fix: reset search on exit

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
packages/frontend/src/hooks/useSavedQuery.ts
packages/frontend/src/pages/Dashboard.tsx

Closes:  #7335
I can't get scrolling to work on the dashboard, I'd suggest to create a separate ticket for it 
[Screencast from 25-03-24 13:39:03.webm](https://github.com/lightdash/lightdash/assets/1983672/b7a1dd4b-7dcd-47ed-967c-c12698899e26)

feat: duplicate chart dashboard

---

packages/frontend/src/components/Explorer/SavedChartsHeader/TitleBreadcrumbs.tsx
packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/components/common/Page/PageHeader.tsx
packages/frontend/src/components/common/PageHeader/UpdatedInfo.tsx
packages/frontend/src/components/common/PageHeader/index.tsx
packages/frontend/src/components/common/ResourceInfoPopup/DashboardList.tsx
packages/frontend/src/components/common/ResourceInfoPopup/ResourceInfoPopup.tsx

Closes: #9414
See ticket ^ for ACs, but here's a summary either way: 
- Add Breadcrumbs to the Title: if it belongs to space, add space name, if it belongs to dashboard, also add it. Both of these are links. THey get truncated if longer than 160; Space name gets hidden when viewing chart within dashboard
- Made header smaller
- Re-styled `views information`
- Re-styled `last updated by...` to not have some parts bold
- Changed some spacings - minimal
- Removed unused SCs

feat: make save charts header changes

---

packages/frontend/src/components/ForbiddenPanel.tsx
packages/frontend/src/components/common/ErrorState/index.tsx
packages/frontend/src/components/common/SuboptimalState/SuboptimalState.tsx
packages/frontend/src/pages/MinimalSavedExplorer.tsx
packages/frontend/src/pages/ShareRedirect.tsx

Removes some of the remaining styled components. There are some more, but this is progress. These were a little hard to verify, but I think I tested all cases.

chore: remove some styled components

---

packages/frontend/src/components/common/LightTable/index.tsx
packages/frontend/src/components/common/LightTable/styles.ts
packages/frontend/src/components/common/PivotTable/index.tsx

Closes: #9448 
it now removes whitespace!
https://github.com/lightdash/lightdash/assets/962095/b88a3fb6-9e05-4dea-a8cc-c2948a5ed997
how it handles cells with large content:
https://github.com/lightdash/lightdash/assets/962095/05587bcd-8210-4015-b1ec-fd883289cf8a

fix: pivot table cell overflow

---

packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceUserList.tsx

Closes: #9530
Before we were showing an error when changing a viewer to be a space editor/admin. But this wouldn't cover when a project editor is set to be a space editor/admin and later changed to be a project viewer. 
The error wouldn't say how the user could fix the problem.
We now allow viewers to be set with any space role but we show an error icon + tooltip. The message now says that the user needs to be promoted to interactive viewer.

fix: error when project viewer has a higher space access

---

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Legend/ReferenceLines.tsx

Remove some debugging logs from reference lines

chore: remove debugging logs

---

packages/e2e/cypress/e2e/app/settings/profile.cy.ts
packages/e2e/package.json
packages/frontend/src/components/UserSettings/ProfilePanel/index.tsx
yarn.lock

Found some Stackoverflow threads where they recommended:
- use `.focus()` before clear
- assert input is empty after clear
- have the `.type()` in separate line

chore: amend profile e2e test to clear input before typing

---

docs/docs/self-host/customize-deployment/use-sso-login-for-self-hosted-lightdash.mdx

Adds generic OIDC configuration docs.

docs: add documentation for OIDC configuration

---

packages/backend/src/routers/apiV1Router.ts
packages/backend/src/services/HealthService/HealthService.mock.ts
packages/backend/src/services/HealthService/HealthService.test.ts
packages/backend/src/services/HealthService/HealthService.ts
packages/common/src/types/featureFlags.ts

Closes: https://github.com/lightdash/lightdash-internal-work/issues/1635 
Add a temporary Posthog feature flag for user groups.

chore: add user group posthog feature flag

---

packages/backend/src/database/seeds/development/01_initial_user.ts
packages/backend/src/models/GithubAppInstallations/GithubAppInstallationsModel.ts
packages/backend/src/models/ModelRepository.ts
packages/backend/src/models/ProjectModel/ProjectModel.mock.ts
packages/backend/src/models/ProjectModel/ProjectModel.test.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/models/SshKeyPairModel.ts
packages/backend/src/models/UserWarehouseCredentials/UserWarehouseCredentialsModel.ts
packages/backend/src/services/ServiceRepository.ts
packages/backend/src/services/UnfurlService/UnfurlService.ts
packages/backend/src/utils/EncryptionUtil/EncryptionUtil.test.ts
packages/backend/src/utils/EncryptionUtil/EncryptionUtil.ts

Closes: 
EncryptionService should not be a service class. I moved it to be a Util class instead.

chore: refactor encryption service to be a util class

---

packages/common/src/types/dashboard.ts

Relates to: [#122](https://github.com/lightdash/lightdash-commercial/issues/122)

chore: add audience to DashboardSummary type

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/bug_report.yml

Closes: 
Following
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms
Tested in lightdash-internal 
https://github.com/lightdash/lightdash-internal-work/issues/new?assignees=&labels=%F0%9F%90%9B+bug&projects=&template=bug_report.yml

chore: new bug report template

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/OpenIdIdentitiesModel.ts
packages/common/src/types/openIdIdentity.ts

Closes: 
Update open id identities queries to return the user uuid instead of the user id.
Unblocks work for #9692

chore: return user uuid in open id identities

---

packages/backend/src/models/OpenIdIdentitiesModel.ts
packages/backend/src/services/UserService.mock.ts
packages/backend/src/services/UserService.test.ts
packages/backend/src/services/UserService.ts

Closes: #9692 
Note: I'm adding unit tests to cover all the `loginWithOpenId` scenarios in the following PR.
https://github.com/lightdash/lightdash/assets/9117144/560d633e-760e-444f-b23d-30ea4b46fcf9

feat: link oauth accounts with same email

---

packages/backend/src/models/OpenIdIdentitiesModel.ts
packages/backend/src/services/UserService.mock.ts
packages/backend/src/services/UserService.test.ts
packages/backend/src/services/UserService.ts

Closes: 
Related to: https://github.com/lightdash/lightdash/pull/9706
Add more unit test to cover most scenarios during login with openid

chore: add unit tests for login with open id

---

packages/backend/src/queryBuilder.mock.ts
packages/backend/src/queryBuilder.ts
packages/backend/src/queryCompiler.ts
packages/common/src/compiler/exploreCompiler.mock.ts
packages/common/src/compiler/exploreCompiler.ts
packages/common/src/index.ts
packages/common/src/types/warehouse.ts
packages/common/src/utils/warehouse.ts
packages/frontend/src/components/Explorer/ResultsCard/QuickCalculations.tsx
packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts
packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
packages/warehouses/src/warehouseClients/TrinoWarehouseClient.ts
packages/warehouses/src/warehouseClients/WarehouseBaseClient.ts

Closes: #9711 
Creates `common/utils/warehouse.ts` and adds `getFieldQuoteChar`. 
Now this util is used across the FE and BE

refactor: expose warehouse utils in common

---

packages/frontend/package.json
packages/frontend/src/components/common/Table/getGroupedRowModelLightdash.ts
yarn.lock

Closes: #9713 
Upgrades `@tanstack/react-table` 
from `"@tanstack/react-table": "^8.5.11",` -> `"@tanstack/react-table": "^8.15.3",`

chore: upgrade @tanstack/react-table

---

docs/docs/self-host/customize-deployment/configure-lightdash-to-use-an-external-database.mdx

- Moves note above initial paragraph
- Reword sentence to make it clear Postgres is a requirement (and not just state a minimum PG version)
New copy:
Current version of same page:
https://docs.lightdash.com/self-host/customize-deployment/configure-lightdash-to-use-an-external-database

docs: state clearly that PG is a requirement, alongside the minimum version

---

packages/e2e/cypress/e2e/app/createProjects.cy.ts
packages/e2e/cypress/e2e/app/settings/profile.cy.ts

chore: fix e2e model test

---

packages/frontend/src/api/csv.ts

- Fixes `422` error when exporting csv: `"Could not match the intersection against every type. Issues: [{\"body.timezone\":{\"message\":\"invalid string value\",\"value\":null}}]"`
1. Open dashboard
2. Click to export csv in one of the tiles

fix: add timezone to csv export

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/frontend/src/api/csv.ts

Closes: https://github.com/lightdash/lightdash/issues/9757

chore: add timezone to query executed analytic event

---

packages/frontend/src/components/common/Dashboard/DashboardRefreshButton.tsx

fix: remove 1minute dashboard refresh interval

---

packages/backend/src/config/jwtKeySet.ts
packages/backend/src/controllers/authentication/strategies/azureStrategy.ts
packages/frontend/src/pages/Dashboard.tsx

Quick change to remove some ambiguity from recent comments I've written.

chore: fix a couple of comments for clarity (azureAdStrategy, Dashboard)

---

packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
packages/frontend/src/components/common/Table/Table.styles.ts
packages/frontend/src/hooks/useColumns.tsx

Closes: https://github.com/lightdash/lightdash/issues/9777
https://github.com/lightdash/lightdash/assets/962095/c67b9708-c687-4856-9da5-529130bed2ae

fix: results table font options

---

packages/backend/src/services/ValidationService/ValidationService.ts
packages/common/src/types/filter.ts

Closes: https://github.com/lightdash/lightdash/issues/9759

fix: validation filter tile

---

packages/frontend/src/components/DashboardFilter/FilterConfiguration/TileFilterConfiguration.tsx

Closes: #9759
Quick change to let users know the field is invalid (it took me a lot to debug, more info in the ticket)

fix: show invalid filter dashboard

---

packages/e2e/cypress/e2e/app/settings/profile.cy.ts

Closes: 
See previous video run , at some point it is mixing inputs 
https://github.com/lightdash/lightdash/assets/1983672/045caa1e-0331-4b5b-9e64-09bcc060bbcb

fix: fix unstable profile test

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Follow-up to #1504 
- Removes feature flag code
- Adds debug statement before session statement

fix: force QUOTED_IDENTIFIERS_IGNORE_CASE = FALSE for snowflake

---

docs/docs/references/joins.mdx

Fixes some of the joins documentation (makes things a bit more clear for intermediate joined models)

docs: Update joins.mdx

---

examples/full-jaffle-shop-demo/dbt/models/users.yml

- Adds an example of using an intrinsic user attribute to jaffle shop

chore: add intrinsic user attribute to jaffle shop users model

---

packages/frontend/src/components/Explorer/ExploreTree/TableTree/ItemDetailPreview.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNode.tsx
packages/frontend/src/mantineTheme.ts

Reverts lightdash/lightdash#9632
This PR was causing slow downs in the explore page

chore: revert "feat: make markdown previews look more like standard tooltips"

---

packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

fix: fix horizontal chart tooltip

---

packages/frontend/src/hooks/useCompiledSql.tsx

Closes: 
I thought I fixed this already...

fix: null timezone compilequery

---

README.md
packages/frontend/src/Routes.tsx
packages/frontend/src/components/DashboardTabs/index.tsx
packages/frontend/src/pages/Dashboard.tsx

Closes: #9658 
Creating unique URL for each tab in a Dashboard

feat: dashboard tabs url

---

docker/docker-compose.dev.yml
packages/backend/src/App.ts
packages/backend/src/clients/Slack/SlackClient.ts
packages/backend/src/clients/Slack/Slackbot.ts

Closes: 
Allow us to extend the slack bot class.

chore: support slack bot dependency injection

---

packages/frontend/src/hooks/useQueryError.ts
packages/frontend/src/hooks/useQueryResults.tsx

fix: toast was not showing for errors running query

---

packages/backend/src/App.ts
packages/backend/src/scheduler/SchedulerWorker.ts

chore: scheduler factory

---

packages/backend/src/models/ModelRepository.ts
packages/backend/src/services/ServiceRepository.ts

chore: expose clients in service context + ai model

---

docs/docs/get-started/setup-lightdash/connect-project.mdx

Adds requirement for project connection for GitLab based on user feedback

chore(docs): Update connect-project.mdx

---

packages/backend/src/clients/EmailClient/EmailClient.ts
packages/backend/src/clients/EmailClient/templates/chartCsvNotification.html
packages/backend/src/services/CsvService/CsvService.ts

Closes:  https://github.com/lightdash/lightdash/issues/9678
Before:
AFter:

fix: no results email

---

packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

fix: min max range on horizontal bar chart

---

examples/api/dashboard.http
packages/backend/src/models/DashboardModel/DashboardModel.ts

Closes:  https://github.com/lightdash/lightdash/issues/9863
Before:
After:

fix: fix tabs for create dashboard api

---

packages/common/src/transformers/VizConfigTransformers/Cartisean/AbstractCartiseanConfigTransformer.ts
packages/common/src/transformers/VizConfigTransformers/Cartisean/BarConfigTransformer.ts
packages/common/src/transformers/VizConfigTransformers/Table/TableConfigTransformer.ts
packages/common/src/transformers/VizLibTransformers/LibTransformer.mock.ts
packages/common/src/transformers/VizLibTransformers/Table/TableTransformer.test.ts

- adds descriptions to zod type definitions
- updates table column type def

chore: update transformer types and add descriptions

---

packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts
packages/common/src/index.ts

Closes: [#9845](https://github.com/lightdash/lightdash/issues/9845)
- Custom range:
- Fixed bins:
- Fixed width - was already working without any change:

fix: add NULL as an extra bin

---

packages/backend/src/database/entities/savedCharts.ts
packages/backend/src/database/migrations/20240423103748_add_type_table_calculation.ts
packages/backend/src/models/SavedChartModel.ts
packages/backend/src/queryBuilder.ts
packages/backend/src/services/CsvService/CsvService.mock.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/compiler/filtersCompiler.ts
packages/common/src/types/field.ts
packages/common/src/utils/filters.ts
packages/common/src/utils/formatting.mock.ts
packages/common/src/utils/formatting.ts
packages/frontend/src/components/Explorer/FiltersCard/useFieldsWithSuggestions.ts
packages/frontend/src/components/common/Filters/FieldIcon.tsx
packages/frontend/src/components/common/Filters/index.tsx
packages/frontend/src/components/common/Filters/utils/getPlaceholderByFilterTypeAndOperator.ts
packages/frontend/src/features/tableCalculation/components/TableCalculationModal.tsx
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts
packages/frontend/src/utils/sortUtils.ts

Closes: https://github.com/lightdash/lightdash/issues/9850
Closes: https://github.com/lightdash/lightdash/issues/9850
I tested everything I can think of, including chart filters, charst axis
Hopefully everything should be backwards compatible, and if no type is defined, default to our current behaviour
Before: 
After: 
- Now date table calculations work 
- You can specify the type of a tc and still apply formatting
- axis icons fixed 
- table calculation filters icons and sql fixed
- select table calculations on Filters on dashboards
- select table calculations on pivots

feat: select table calculation type

---

packages/backend/src/services/DashboardService/DashboardService.ts
packages/backend/src/services/SchedulerService/SchedulerService.ts

Related to: #9880 
Add logging for an issue with 'send now' permissions. Also, I had to add an await to a permissions check to see the right info, and it seems like there's a good chance that fixes the issue.

fix: add await to scheduler access calculation

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/cli/src/handlers/createProject.ts
packages/cli/src/handlers/preview.ts
packages/common/src/types/projects.ts

Closes:   #9854
Rename copiedFromProjectUuid
Places where I didn't replace: 
- analytics : ( we don't want to break the existing data) 
- dbProject: It needs to match the db column name 
test-frontend test-backend test-cli

chore: rename copied from project uuid field

---

packages/common/src/utils/filters.mock.ts
packages/common/src/utils/filters.test.ts
packages/common/src/utils/filters.ts

Closes: [#9840](https://github.com/lightdash/lightdash/issues/9840)
https://github.com/lightdash/lightdash/assets/22939015/f8230f60-9325-4353-80ae-2025228c069e

fix: remove duplicated rules

---

packages/frontend/src/components/DashboardTabs/index.tsx

Closes: 
[9871](https://github.com/lightdash/lightdash/issues/9871)

chore: Styling updates to the Tabs section

---

packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Closes: #9449 
Disabling snowflake info logs. 
Relevant [thread in snowflake repo](https://github.com/snowflakedb/snowflake-connector-nodejs/issues/794#issuecomment-1991736326)
To replicate, connect to a snowflake warehouse and run a query.

fix: exclude snowflake info logs

---

.github/workflows/release-on-merge.yml

Relates to: #9918 
Fixed indentation - format-on-save revert issue. 
action with error here: https://github.com/lightdash/lightdash/actions/runs/8895213747/job/24425076336

fix: correct indentation on sentry release dispatch

---

packages/frontend/src/hooks/thirdPartyServices/useSentry.ts

Relates to: #9907 
Enables tracking of INP: https://docs.sentry.io/product/performance/web-vitals/web-vitals-concepts/#interaction-to-next-paint-inp to further help on reviewing dashboard and charts experience.
> [Interaction to Next Paint (INP)](https://web.dev/articles/inp) measures the time from when a user interacts with a page (through a click, tap, or keyboard input) to when the next paint (rendering of content on the screen) occurs. INP aims to assess how quickly users see a response from the website after taking an action, which is crucial for providing a smooth and responsive user experience.

feat: enable inp in react sentry

---

packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: #9938 
Before:
https://github.com/lightdash/lightdash/assets/9117144/48404bc0-0710-4bed-812a-17f9a7ac802c
After:
https://github.com/lightdash/lightdash/assets/9117144/48f18215-9f2c-4136-89a5-6af8a24e1005

fix: only apply min/max for numeric axis

---

packages/frontend/src/components/MetricQueryData/UnderlyingDataModalContent.tsx

Closes: [#9537](https://github.com/lightdash/lightdash/issues/9537)
- Flattens root filter group
**Before**
https://github.com/lightdash/lightdash/assets/22939015/c81ab972-068b-4fe3-821b-1fb74efff690
**After**
https://github.com/lightdash/lightdash/assets/22939015/79443612-e7f9-4cba-94fc-0504fa51c6cc

fix: flatten root filter group

---

packages/backend/src/database/entities/dashboards.ts
packages/backend/src/database/entities/savedCharts.ts
packages/backend/src/database/entities/spaces.ts
packages/backend/src/database/migrations/20240424131157_add_slugs.ts
packages/backend/src/database/migrations/20240424131220_populate_slugs.ts
packages/backend/src/database/seeds/development/01_initial_user.ts
packages/backend/src/database/seeds/development/02_saved_queries.ts
packages/backend/src/database/seeds/development/03_saved_dashboards.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/DashboardModel/DashboardModel.mock.ts
packages/backend/src/models/DashboardModel/DashboardModel.test.ts
packages/backend/src/models/DashboardModel/DashboardModel.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/models/SavedChartModel.ts
packages/backend/src/models/SpaceModel.ts
packages/backend/src/services/DashboardService/DashboardService.mock.ts
packages/backend/src/services/DashboardService/DashboardService.test.ts
packages/backend/src/services/DashboardService/DashboardService.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/backend/src/services/SavedChartsService/SavedChartService.ts
packages/backend/src/services/SpaceService/SpaceService.ts
packages/backend/src/services/ValidationService/ValidationService.mock.ts
packages/common/src/index.ts
packages/common/src/slug.test.ts
packages/common/src/types/dashboard.ts
packages/common/src/types/savedCharts.ts
packages/common/src/types/space.ts
packages/common/src/utils/slugs.ts

Closes:  https://github.com/lightdash/lightdash/issues/9853
After migration: 
Adding new charts and spaces:

feat: new resource-slugs

---

packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts

Closes: [#9877](https://github.com/lightdash/lightdash/issues/9877)

fix: Postgres and Redshift average decimal values

---

packages/common/src/utils/item.ts

Closes:  https://github.com/lightdash/lightdash/issues/9902
test-fronted test-backend

fix: stack table calculation non-number

---

docker-compose.yml
docker/docker-compose.dev.yml

Closes: #9968
Enforces the lightdash docker image as described in the issue.

chore: enforce Lightdash Docker Image platform

---

packages/common/src/types/errors.ts
packages/frontend/src/components/common/ErrorState/index.tsx
packages/frontend/src/features/errorBoundary/components/ErrorBoundary.tsx
packages/frontend/src/features/tableCalculation/utils/index.ts
packages/frontend/src/hooks/toaster/useToaster.tsx

Closes: #9956
Changed the error messages.

feat: Error messages changed

---

packages/backend/src/services/UnfurlService/UnfurlService.ts
packages/common/src/types/featureFlags.ts

Closes: #9970 
Removes `puppeteer`-related feature flags but keeps logic as it hasn't affected screenshots negatively.

chore: remove feature flags and keep logic

---

packages/backend/src/clients/Aws/s3.ts
packages/backend/src/services/CsvService/CsvService.ts
packages/common/src/types/errors.ts

Closes: https://github.com/lightdash/lightdash/issues/10007
Before:
After:
if no cloud storage: 
with cloud storage: 
and timestamp

fix: fix error and sanitize csv error

---

packages/backend/src/services/UnfurlService/UnfurlService.ts

Closes: #9947 
Retries screenshot logic for a scheduled job when there's a `ProtocolError` or a `Timeout` error.
This will retry `saveScreenshot` recursively 3 times if the error is _retryable_
References: 
https://github.com/puppeteer/puppeteer/issues/10144#issuecomment-1918840262
And from `Test script` section in Browserless: https://www.browserless.io/blog/horizontally-scaling-chrome
To reproduce this retry/error: 
- Create a scheduled delivery for a dashboard
- Rename the `finalSelector` for dashboards from 
```ts
finalSelector = '.react-grid-layout';
```
to 
```ts
finalSelector = '.react-gri-layout';
```
- That will lead to a timeout error and you will see the retries happening.

fix: retry screenshot for protocol and timeout errors

---

packages/cli/src/dbt/targets/Bigquery/serviceAccount.ts
packages/cli/src/dbt/templating.ts

fix: multiline profile bigquery

---

packages/frontend/src/pages/Settings.tsx

Closes:  https://github.com/lightdash/lightdash/issues/10024

fix: empty integrations redirection

---

packages/frontend/src/components/DashboardTabs/index.tsx

Closes: 
issue:
https://github.com/lightdash/lightdash/assets/101873365/73a51a30-cd5c-4ab8-9f7c-64c63e8956e5

fix: switch tab clears temp filters state

---

packages/backend/package.json
packages/backend/src/App.ts
yarn.lock

Closes: N/A
Follows this guide: https://docs.sentry.io/platforms/javascript/guides/node/profiling/
Enables profiling of 20% of the samples.

feat: enable sentry backend profiling

---

packages/common/src/utils/conditionalFormatting.ts

Closes: https://github.com/lightdash/lightdash/issues/10052
Before
After

fix: conditional formatting table calculation

---

packages/backend/src/models/AnalyticsModelSql.ts

Closes: https://github.com/lightdash/lightdash/issues/10038
Before:
After:

fix: usage analytics groups

---

packages/frontend/src/components/SimpleChart/index.tsx

Closes: #9939
[fix type error or undefined param.encode.x](https://github.com/lightdash/lightdash/commit/89eed7ce81c9b4496d81efc21a1e0f23b5b51752)

fix: fix type error or undefined param.encode.x

---

packages/frontend/src/components/Explorer/CustomMetricModal/index.tsx
packages/frontend/src/components/Explorer/CustomMetricModal/utils/index.ts
packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNodeActions.tsx
packages/frontend/src/providers/ExplorerProvider.tsx

Closes: https://github.com/lightdash/lightdash/issues/9931
[Screencast from 15-05-24 09:40:51.webm](https://github.com/lightdash/lightdash/assets/1983672/b18f5412-1ae2-4e75-8d7c-14e85da6ef7c)

fix: add custom metric from custom dimension

---

packages/frontend/src/components/VisualizationConfigs/ChartConfigPanel/Layout/index.tsx
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts

Closes: #10051
Before:
After:
[Screencast from 14-05-24 10:15:20.webm](https://github.com/lightdash/lightdash/assets/1983672/19342739-4307-448a-b407-acc19f66424d)

fix: table calculation group stack

---

packages/backend/src/database/migrations/20240515151028_add_custom_dimension_to_selected_dimensions.ts
packages/backend/src/database/seeds/development/02_saved_queries.ts
packages/backend/src/queryBuilder.mock.ts
packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts
packages/backend/src/services/CsvService/CsvService.ts
packages/common/src/index.ts
packages/common/src/utils/fields.mock.ts
packages/common/src/utils/fields.test.ts
packages/common/src/utils/fields.ts
packages/e2e/cypress/e2e/app/createProjects.cy.ts
packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/VisualizationConfigs/TableConfigPanel/GeneralSettings.tsx
packages/frontend/src/hooks/cartesianChartConfig/useCartesianChartConfig.ts
packages/frontend/src/hooks/pivotTable/pivotQueryResults.ts
packages/frontend/src/hooks/usePivotDimensions.ts
packages/frontend/src/hooks/useQueryResults.tsx
packages/frontend/src/providers/ExplorerProvider.tsx

Closes: https://github.com/lightdash/lightdash/issues/10079
[Screencast from 15-05-24 16:58:03.webm](https://github.com/lightdash/lightdash/assets/1983672/8668f4a5-e45e-4eda-81e2-9bdbd0325d70)

fix: select custom dimensions

---

packages/backend/src/queryBuilder.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/compiler/filtersCompiler.ts
packages/common/src/types/field.ts
packages/common/src/utils/filters.mock.ts
packages/common/src/utils/filters.test.ts
packages/common/src/utils/filters.ts
packages/frontend/src/components/Explorer/CustomMetricModal/hooks/useDataForFiltersProvider.ts
packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNodeActions.tsx
packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx
packages/frontend/src/components/Explorer/FiltersCard/useFieldsWithSuggestions.ts
packages/frontend/src/components/Explorer/ResultsCard/CellContextMenu.tsx
packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx
packages/frontend/src/components/common/Filters/FilterGroupForm.tsx
packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
packages/frontend/src/components/common/Filters/FilterInputs/index.tsx

Closes: #7564 
Tested:
- Add filter from sidebar
- Add filter from table header
- Add filter from table cell
- Add filter from filter select
- Add filter for unselected custom dimension ( joins necessary table )
- Add multiple filters for different types of custom dimensions

feat: custom sql dimension filters

---

packages/e2e/cypress/e2e/app/space.cy.ts

chore: private space access e2e test

---

packages/e2e/cypress/e2e/app/customDimensions.cy.ts

Closes: 
[Screencast from 17-05-24 09:46:41.webm](https://github.com/lightdash/lightdash/assets/1983672/9bda987b-5286-4509-931c-3692371b8055)

chore: custom sql dimension e2e 

---

examples/full-jaffle-shop-demo/dbt/models/tracks.yml

Adds a column to our demo data which has an EST timezone.

chore: add EST time to demo

---

examples/full-jaffle-shop-demo/dbt/models/tracks.yml

Closes: 
Fixes quotes issue. Replace wrapping quotes to single quotes so they don't conflict with double quotes inside description.
test-frontend

chore: amend yml quotes

---

packages/e2e/cypress/e2e/app/tableCalculation.cy.ts

chore: add table calculation e2e

---

packages/backend/src/clients/EmailClient/EmailClient.mock.ts
packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/queryBuilder.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/package.json
packages/common/src/compiler/filtersCompiler.mock.ts
packages/common/src/compiler/filtersCompiler.test.ts
packages/common/src/compiler/filtersCompiler.ts
yarn.lock

Closes: https://github.com/lightdash/lightdash-internal-work/issues/1760
test-frontend

feat: add timezone handling to "in the current" filter

---

packages/e2e/cypress/e2e/app/dashboard.cy.ts

Amend e2e test to expand group that was recently added for staging tables

chore: amend e2e test to expand sidebar group

---

packages/backend/src/models/CatalogModel/CatalogModel.ts

The current catalog search only searches whole words. This adds the ability to search partial words as well as multiple words. Note that without the multi word search, things like `customer table` cause an error.

chore: add partial word and multi-word search to catalog search

---

packages/backend/src/@types/knex-tables.d.ts
packages/backend/src/database/entities/catalog.ts

fix: catalog table typo

---

packages/backend/src/database/entities/catalog.ts
packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/models/CatalogModel/utils/index.ts
packages/backend/src/models/ModelRepository.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/models/SearchModel/index.ts
packages/backend/src/models/SearchModel/utils/search.ts
packages/backend/src/services/CatalogService/CatalogService.ts

chore: updates to catalog search

---

packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/models/SearchModel/index.ts
packages/backend/src/models/SearchModel/utils/search.ts

chore: updates to catalog search 2

---

packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/models/SearchModel/utils/search.ts

fix: to tsquery

---

packages/backend/src/models/ProjectModel/ProjectModel.ts

Closes: #10182
Added sentry transactions
On error:
But deploy still works
test-frontend test-backend test-cli

fix: index catalog error

---

docs/docs/guides/how-to-create-custom-fields.mdx

Adds info that only developers or admins can use custom SQL dimensions.

docs: adds info about user access level. 

---

packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Closes: 
Remove snowflake warning logs.

chore: snowflake log level error

---

examples/api/catalog.http
packages/backend/src/controllers/catalogController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/models/CatalogModel/utils/parser.ts
packages/backend/src/services/CatalogService/CatalogService.ts
packages/common/src/index.ts
packages/common/src/types/catalog.ts
packages/frontend/src/features/catalog/components/CatalogListItem.tsx
packages/frontend/src/features/catalog/components/CatalogMetadata.tsx
packages/frontend/src/features/catalog/components/CatalogPanel.tsx
packages/frontend/src/features/catalog/hooks/useCatalog.ts
packages/frontend/src/features/catalog/hooks/useCatalogMetadata.ts

Closes: #10073
[Screencast from 24-05-24 10:29:02.webm](https://github.com/lightdash/lightdash/assets/1983672/5759561b-0f6f-43ba-822c-caf4a29abfd3)
[Screencast from 24-05-24 12:08:13.webm](https://github.com/lightdash/lightdash/assets/1983672/7fc65270-2583-4425-b3cd-3ddd47e65402)
[Sketch](https://www.figma.com/proto/rlqMIJ4pm3t8aAsiMd3CZJ/Lightdash-Product-New?node-id=2544-18430&t=eeMfJ6TrYhH4TyAU-0&scaling=min-zoom&page-id=2544%3A18282&starting-point-node-id=2550%3A115315) (use your right and left arrows to navigate it)
**If a table has been selected:**
**Navigation:**
**Other**
- This ticket covers testing the UX of navigating through different previews here, so it can be scrappy. I want to test out how wide the panels need to be and just how smooth the experience is. 
- **Out of …

feat: catalog metadata

---

packages/e2e/cypress/e2e/api/catalog.cy.ts

fix: e2e catalog metric

---

packages/backend/src/clients/Slack/SlackClient.ts
packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/models/SearchModel/utils/search.ts
packages/backend/src/services/CsvService/CsvService.ts
packages/common/src/types/slackSettings.ts
packages/e2e/cypress/e2e/api/catalog.cy.ts

chore: slack client, csv service and project model changes

---

packages/backend/src/scheduler/SchedulerClient.ts
packages/backend/src/scheduler/SchedulerTask.ts
packages/frontend/src/components/SettingsValidator/index.tsx
packages/frontend/src/features/scheduler/hooks/useScheduler.ts
packages/frontend/src/hooks/validation/useValidation.ts

Closes: 
This PR tackles 3 things:
- [chore] add more details to scheduled jobs for easier debug
- [fix] properly fail graphile job and log error in sentry by re-throwing error during validation
- [fix] show validation error in UI and stop loading spinner
Before:
After:

fix: show validation error

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/CatalogService/CatalogService.ts
packages/common/src/types/catalog.ts
packages/frontend/src/features/catalog/components/CatalogAnalyticCharts.tsx

feat: add catalog chart kind to analytics

---

packages/backend/src/models/SavedChartModel.ts

fix: duplicated versions chart analytics

---

examples/api/catalog.http
packages/backend/src/controllers/catalogController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/CatalogService/CatalogService.ts
packages/e2e/cypress/e2e/api/catalog.cy.ts
packages/frontend/src/features/catalog/components/CatalogMetadata.tsx
packages/frontend/src/features/catalog/components/CatalogPanel.tsx
packages/frontend/src/features/catalog/hooks/useCatalogAnalytics.ts

Closes: #10195
[Screencast from 29-05-24 09:28:17.webm](https://github.com/lightdash/lightdash/assets/1983672/c3d6442d-8cf5-43b4-8d43-c11bf5dd3bd6)

feat: catalog field analytics

---

packages/frontend/src/components/common/Page/Page.tsx
packages/frontend/src/components/common/Page/Sidebar.tsx
packages/frontend/src/features/catalog/components/CatalogAnalyticCharts.tsx
packages/frontend/src/features/catalog/components/CatalogMetadata.tsx
packages/frontend/src/pages/Catalog.tsx

Closes: #10194 
This PR covers the following: 
- Adds `SidebarWidthProps` to `Sidebar` to set the following styles: 
```ts
rightSidebarWidthProps={{
defaultWidth: 600,
minWidth: 600,
maxWidth: 800,
}}
```
- sets styles to the sidebar, according to the ticket mentioned above ^
Demo: 
https://github.com/lightdash/lightdash/assets/7611706/91d70f1f-ea9b-4c76-b27e-f5eec6783095

feat: polish metadata sidebar 

---

packages/frontend/src/features/catalog/components/CatalogPanel.tsx

Closes: https://github.com/lightdash/lightdash/issues/10241
[Screencast from 30-05-24 10:13:39.webm](https://github.com/lightdash/lightdash/assets/1983672/107ff743-ef14-4f29-ae74-67b1d00ce297)

fix: clear search catalog

---

packages/frontend/src/features/catalog/components/CatalogPanel.tsx

Relates to: #10193
Before
After

style: update catalog header styles

---

packages/frontend/src/features/catalog/components/CatalogMetadata.tsx

Closes:  https://github.com/lightdash/lightdash/issues/10218
[Screencast from 29-05-24 16:24:20.webm](https://github.com/lightdash/lightdash/assets/1983672/19fd5015-ada9-469d-b9b5-2affcea9adf3)

feat: select field in table

---

docs/docs/guides/formatting-your-fields.mdx

Closes: 
Update groups docs to mention max of 2 levels.
\+ move deprecation warning

docs: max groups in sidebar

---

packages/frontend/src/features/catalog/components/CatalogGroup.tsx
packages/frontend/src/features/catalog/components/CatalogPanel.tsx
packages/frontend/src/features/catalog/components/CatalogTableListItem.tsx
packages/frontend/src/features/catalog/components/CatalogTree.tsx

Relates to: https://github.com/lightdash/lightdash/issues/10193
Updates List and Group components' styles
Since we don't use CSS modules, we need to track if the a component is first or last of the list to render styles conditionally like: 
- border radius
- border bottom
Before
After
https://github.com/lightdash/lightdash/assets/7611706/8b5b45cf-3590-4f5c-93e1-ec6c7bf85b31

style: update catalog tree list and group styles

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/CatalogService/CatalogService.ts
packages/common/src/types/catalog.ts
packages/frontend/src/features/catalog/components/CatalogMetadata.tsx

Closes: N/A
Returns `joinedTables` from metadata endpoint;
Displays them:

feat: add joined tables to metadata sidebar

---

packages/backend/src/models/ValidationModel/ValidationModel.ts

Closes: 
Refactor code to do a bulk insert rather than one insert per row.

fix: refactor validation error insert

---

packages/frontend/src/features/catalog/components/CatalogPanel.tsx
packages/frontend/src/features/catalog/components/CatalogTree.tsx

Closes: N/A
Add loading states to when the catalog is loading and when the user is searching.
https://github.com/lightdash/lightdash/assets/7611706/8e7b67ca-5a51-47fe-a78d-6ad48cd5ed30

feat: add loading state when catalog is loading

---

packages/frontend/src/features/catalog/components/CatalogPanel.tsx

Closes: N/A
Controls visibility of `description` to avoid the UI shifting when displaying/hiding it
Demo: 
https://github.com/lightdash/lightdash/assets/7611706/d70bfc73-22bd-417f-917a-8312235f697c

style: fix search/filter button alignment

---

packages/frontend/src/features/catalog/components/CatalogMetadata.tsx
packages/frontend/src/features/catalog/components/CatalogPanel.tsx
packages/frontend/src/features/catalog/components/CatalogTableListItem.tsx
packages/frontend/src/features/catalog/context/CatalogProvider.tsx

Closes: N/A
Relates to: https://github.com/lightdash/lightdash/pull/10283#issuecomment-2144404234
Stores `metadataErrors` in `CatalogProvider`
And displays the error message if a table has an error on the Metadata sidebar
https://github.com/lightdash/lightdash/assets/7611706/b6269452-9dd2-4809-8aa9-edab2c4bac42

feat: display error message on metadata panel if open

---

packages/backend/src/App.ts
packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/config/parseConfig.ts

Closes: https://github.com/lightdash/lightdash/issues/10294
Sets tags for: 
```
podName
podNamespace
nodeName
lightdashCloudInstance
```
from envs: 
```
LIGHTDASH_CLOUD_INSTANCE
K8S_NODE_NAME
K8S_POD_NAME
K8S_POD_NAMESPACE
```
Triggered an error and saw the tags being passed (when they're not `undefined`):

feat: set k8s tags for sentry events

---

packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceAddUser.tsx

Closes: [#9539](https://github.com/lightdash/lightdash/issues/9539)
demo:
https://github.com/lightdash/lightdash/assets/101873365/8d795ded-15b5-4eab-945c-af1763e8b550

feat: add space role inheritance info tooltip

---

packages/backend/src/controllers/slackController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/types/slack.ts

Relates to: [Allow customisation of bot appearance per organization](https://github.com/lightdash/lightdash-commercial/issues/229)

fix: custom settings endpoint

---

packages/backend/src/services/UnfurlService/UnfurlService.ts

Closes: N/A
Gets all chart tile uuids for a dashboard and waits for `/chart-and-results/UUID` to settle before taking a screenshot.
Since this is a good indicator of waiting for the page to load, I've removed some extra selector awaits. 
HOW TO TEST:
Go to `ProjectService` > `getChartAndResults`, then before returning, add this
```ts
const delay = (ms: number | undefined) =>
new Promise((resolve) => setTimeout(resolve, ms));
if (chartUuid === 'GET_ID_FROM_ONE_OR_TWO_CHARTS') {
await delay(10000);
}
```
The screenshot function will wait for the 10s chart to load: 
Before
After
You can also test errors: 
Add this after the `delay` call:
```ts
throw new UnexpectedServerError('This is a test error');
```
Result:
waits for `{uuid}/results` to settle before taking a screenshot
HOW TO TEST …

fix: wait for all charts to settle with playwright screenshot

---

packages/backend/package.json
packages/backend/src/App.ts
packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/config/parseConfig.test.ts
packages/backend/src/config/parseConfig.ts
packages/common/src/index.ts
yarn.lock

Closes: [#8331](https://github.com/lightdash/lightdash/issues/8331)

feat: security headers

---

packages/backend/src/config/lightdashConfig.mock.ts

Closes: 
Fixed missing `security` in config mock:

chore: add security to config mock

---

packages/backend/src/App.ts

Closes: 
Allow lightdash to be embedded in other websites.

fix: remove x frame options header

---

packages/backend/src/App.ts

Closes: 
Add intercom and google domains to content security policy.

fix: add intercom and google domains to content security policy

---

packages/backend/src/models/SlackAuthenticationModel.ts
packages/backend/src/services/SlackIntegrationService/SlackIntegrationService.ts
packages/common/src/types/slack.ts
packages/common/src/types/slackSettings.ts
packages/frontend/src/components/UserSettings/SlackSettingsPanel/index.tsx

Relates to: https://github.com/lightdash/lightdash-commercial/issues/236
- Add new types
- Improve slack settings page styles ( this will help the other PR have more consistency )

chore: add slack project mapping types

---

packages/common/src/compiler/filtersCompiler.ts
packages/common/src/types/filter.ts

Closes: https://github.com/lightdash/lightdash/issues/10388
before:
after:

feat: improve cli error for operator to type error

---

packages/e2e/cypress/e2e/api/promotion.cy.ts
packages/e2e/cypress/support/commands.ts

Closes:  https://github.com/lightdash/lightdash/issues/10367
[Screencast from 12-06-24 14:03:19.webm](https://github.com/lightdash/lightdash/assets/1983672/b7e92cf3-274b-4f8d-941a-be36912fbd8b)

test: promotion api test

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json

chore: run yarn generate-api

---

packages/cli/src/handlers/preview.ts

Closes: #10391 
1. Run `lightdash login` and hit `ctrl + c` when it asks you to choose a project
2. Run `lightdash preview`

chore: warn the user that project is not set

---

packages/frontend/src/components/common/Page/Page.tsx
packages/frontend/src/pages/Login.tsx

Closes: https://github.com/lightdash/lightdash/issues/10284
before video: https://lightdash.slack.com/archives/C02GQKJK84Q/p1718181068735969
after: 
https://github.com/lightdash/lightdash/assets/962095/3e7bac97-b357-4a3f-88dc-127df763bf9a

fix: footer in page component

---

packages/frontend/src/providers/ExplorerProvider.tsx

Closes: https://github.com/lightdash/lightdash/issues/10205
https://github.com/lightdash/lightdash/assets/962095/46880058-7821-48df-9ada-342149b4ca87

fix: custom dimension edit re run query

---

packages/backend/src/models/SavedChartModel.ts

Closes: #10253 
https://github.com/lightdash/lightdash/assets/22939015/9d335ace-a24b-4fec-8bc4-b57a83a14289

fix: join dashboards when getting charts for validation

---

packages/backend/src/@types/knex-tables.d.ts
packages/backend/src/database/entities/dashboards.ts
packages/backend/src/models/ProjectModel/ProjectModel.ts

Closes: [#10396](https://github.com/lightdash/lightdash/issues/10396)
Copy dashboard tabs when copying project content.

fix: copy dashboard tabs

---

packages/frontend/src/api.ts

chore: improve API 500 error copy

---

packages/common/src/utils/filters.test.ts
packages/common/src/utils/filters.ts
packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx

Closes: https://github.com/lightdash/lightdash/issues/10427
sentry: https://lightdash.sentry.io/issues/5490564879/?project=4507168845529088&query=Cannot+assign+to+read+only+property&referrer=issue-stream&statsPeriod=14d&stream_index=0

fix: reset required filter rules mutation

---

packages/common/src/types/featureFlags.ts
packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx

chore: remove feature flag promotion

---

docs/docs/references/tables.mdx

Closes: #10416
Headway update incoming

docs: update required_filters docs

---

docs/docs/guides/how-to-create-alerts.mdx

Remove mentions of dashboards from alerting docs since it only works for saved charts

docs: update alert docs

---

packages/backend/src/sentry.ts

Closes: 
Update sentry config to ignore a few more errors.

chore: update sentry config to ignore more errors

---

packages/backend/src/scheduler/SchedulerClient.ts
packages/backend/src/scheduler/SchedulerTask.test.ts
packages/backend/src/scheduler/SchedulerTask.ts
packages/backend/src/sentry.ts
packages/common/src/types/errors.ts

fix: disable non retriable error on threshold alert and improve error handling

---

packages/backend/src/sentry.ts

chore: ignore token error sentry

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/compiler/filtersCompiler.mock.ts
packages/common/src/compiler/filtersCompiler.ts
packages/common/src/types/conditionalRule.ts
packages/common/src/utils/conditionalFormatting.ts
packages/common/src/utils/filters.ts
packages/frontend/src/components/DashboardFilter/FilterConfiguration/utils/index.ts
packages/frontend/src/components/common/Filters/FilterInputs/DateFilterInputs.tsx
packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
packages/frontend/src/components/common/Filters/FilterInputs/index.tsx
packages/frontend/src/components/common/Filters/utils/getPlaceholderByFilterTypeAndOperator.ts

feat: not in the current filter

---

docker/docker-compose.dev.yml
docs/docs/self-host/customize-deployment/environment-variables.mdx
packages/backend/package.json
packages/backend/src/App.ts
packages/backend/src/SchedulerApp.ts
packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/config/parseConfig.test.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/prometheus.ts
yarn.lock

Closes: https://github.com/lightdash/lightdash-cloud/issues/401
Add Prometheus metrics endpoint. 
| Variable                                    | Description                                                                     | Required? | Default                     |
| ------------------------------------------- | ------------------------------------------------------------------------------- | --------- | --------------------------- |
| `LIGHTDASH_PROMETHEUS_ENABLED`              | Enables/Disables Prometheus metrics endpoint                                    |           | `false`                     |
| `LIGHTDASH_PROMETHEUS_PORT`                 | Port for Prometheus metrics endpoint                                            |           | `9090`                      |
| …

feat: prometheus metrics

---

packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

fix: round 0 on chart label

---

packages/backend/src/database/migrations/20240619090032_add-funnel-chart-type.ts
packages/backend/src/services/SavedChartsService/SavedChartService.ts
packages/common/src/types/savedCharts.ts
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationConfigPanel.tsx
packages/frontend/src/components/Explorer/VisualizationCard/VisualizationSidebar.tsx
packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
packages/frontend/src/components/FunnelChart/FunnelChartContextMenu.tsx
packages/frontend/src/components/FunnelChart/index.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationConfigFunnel.tsx
packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
packages/frontend/src/components/LightdashVisualization/index.tsx
packages/frontend/src/components/VisualizationConfigs/FunnelChartConfig/FunnelChartConfigTabs.tsx
packages/frontend/src/components/VisualizationConfigs/FunnelChartConfig/index.tsx
packages/frontend/src/components/common/ResourceIcon/index.tsx
packages/frontend/src/components/common/ResourceView/resourceUtils.ts
packages/frontend/src/hooks/echarts/useEchartsFunnelConfig.ts
packages/frontend/src/hooks/useFunnelChartConfig.ts
packages/frontend/src/providers/ExplorerProvider.tsx

Closes: #2594 
Adds a funnel chart viz (from eCharts). This is a draft for now but it's not far from being ready. At the moment you can pick which column in the data to use for the steps. Customers requested also to be able to use a row. We can think about other options (colors?). 
Here's what it looks like for now.

feat: funnel chart

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/CatalogModel/utils/parser.ts
packages/backend/src/services/CatalogService/CatalogService.ts
packages/common/src/types/catalog.ts
packages/e2e/cypress/e2e/api/catalog.cy.ts
packages/frontend/src/features/catalog/components/CatalogMetadata.tsx
packages/frontend/src/features/catalog/components/CatalogTableListItem.tsx

Closes: [#10311](https://github.com/lightdash/lightdash/issues/10311)
- displays table label 
- when hovering on the metadata, we display the name
Demo: 
https://github.com/lightdash/lightdash/assets/7611706/d24fa3b0-3fcb-423e-b8e8-065295d35b6e

feat: display table labels in catalog

---

yarn.lock

adds missing yarn lock changes

chore: add missing yarn lock changes

---

docs/docs/guides/how-to-promote-content.md

Clarifying docs on promoting content since it wasn't clear promoting doesn't work in private spaces yet.

docs: update promoting content

---

packages/backend/src/App.ts

fix: log unexpected errors in backend

---

packages/common/src/types/savedCharts.ts
packages/frontend/src/components/VisualizationConfigs/FunnelChartConfig/FunnelChartConfigTabs.tsx
packages/frontend/src/hooks/echarts/useEchartsFunnelConfig.ts
packages/frontend/src/hooks/useFunnelChartConfig.ts

Closes: #10488 
Add label properties to funnel chart:
- placement
- show value (without hover)
- show percentage (without hover)
Chart with label: right, value and percentage:
Config:

feat: add label placement, value and percentage to funnel chart

---

packages/frontend/src/hooks/useFunnelChartConfig.ts

Funnel chart was caching the max value when fields were changed. 
Repro:
1. Make a funnel chart with 2 numeric fields. 
2. Use steps are ROWS
3. Switch between the two fields
4. Notice the percentages are wrong in the second field
This just calculated the max along with the data. I don't remember why I had a useRef. 😅

fix: don't cache max value when fields change in funnel chart

---

packages/frontend/src/features/catalog/components/CatalogPanel.tsx
packages/frontend/src/hooks/useRefreshServer.tsx

Closes: https://github.com/lightdash/lightdash/issues/10184
Add `RefreshDbtButton` that already handles permissions and flag checks for us. 
Invalidate `catalog...` if the job type is of type `COMPILE_PROJECT`
https://github.com/lightdash/lightdash/assets/7611706/523ecb5e-5dfb-4ab3-a3cd-bef85f2ccd00

feat: add refresh dbt button to catalog

---

.github/workflows/e2e-tests.yml
dockerfile
dockerfile-prs
examples/api/sqlRunner.http
packages/backend/src/controllers/sqlRunnerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/queryBuilder.mock.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/compiler/exploreCompiler.mock.ts
packages/common/src/types/warehouse.ts
packages/e2e/cypress.config.ts
packages/e2e/cypress/e2e/api/promotion.cy.ts
packages/e2e/cypress/e2e/api/sqlRunner.cy.ts
packages/e2e/cypress/support/commands.ts
packages/e2e/cypress/support/warehouses.ts
packages/e2e/tsconfig.json
packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts
packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
packages/warehouses/src/warehouseClients/TrinoWarehouseClient.ts
packages/warehouses/src/warehouseClients/WarehouseBaseClient.ts

Closes:  https://github.com/lightdash/lightdash/issues/10516 
[Screencast from 26-06-24 12:12:44.webm](https://github.com/lightdash/lightdash/assets/1983672/534d8b63-967c-4f9d-ac92-bdac7e9df0e9)

feat: sql runner tables and fields

---

packages/backend/src/App.ts

Closes: 
Sentry Issue: [LIGHTDASH-BACKEND-4DY](https://lightdash.sentry.io/issues/5541418091/?referrer=github_integration)

fix: CSP domains for pylon dependencies

---

packages/frontend/src/components/NavBar/BrowseMenu.tsx

- Shows private spaces that the user has access to in the browse menu

fix: pass boolean to see private spaces

---

packages/frontend/src/components/common/Page/Page.tsx
packages/frontend/src/pages/SqlRunnerNew.tsx

Before:
After:
New runner layout remains good:

fix: add optional flex content to page.tsx

---

packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/components/common/Dashboard/DashboardRefreshButton.tsx
packages/frontend/src/providers/TrackingProvider.tsx
packages/frontend/src/types/Events.ts

Closes: #10508 
- Adds `dashboard_auto_refresh.updated` event

chore: add tracking event for auto refresh update

---

packages/frontend/src/features/sqlRunner/components/Tables.tsx
packages/frontend/src/features/sqlRunner/hooks/useTables.tsx

Relates to: https://github.com/lightdash/lightdash/issues/10569 
- Implements search for tables (another PR incoming for table fields)
- Applies data transformation on `select`
- Uses `fuse` if there's a search string > 2 (do we want to increase/decrease this?)
Demo
https://github.com/lightdash/lightdash/assets/7611706/444f504c-4bf1-4370-a459-92c19f266a00

feat: allow searching tables sql runner

---

packages/frontend/src/features/sqlRunner/components/TableFields.tsx
packages/frontend/src/features/sqlRunner/components/Tables.tsx
packages/frontend/src/features/sqlRunner/hooks/useTableFields.tsx
packages/frontend/src/features/sqlRunner/hooks/useTables.tsx

Closes: https://github.com/lightdash/lightdash/issues/10569
Related to: #10586 
- Can search table fields (debounced)
- Highlights search
- Uses react-query's `select` to transform data
https://github.com/lightdash/lightdash/assets/7611706/9b0395da-e725-4871-bb8f-8911124791e9

feat: allow searching fields sql runner

---

packages/common/src/types/savedCharts.ts
packages/frontend/src/components/LightdashVisualization/VisualizationConfigFunnel.tsx
packages/frontend/src/components/VisualizationConfigs/FunnelChartConfig/FunnelChartConfigTabs.tsx
packages/frontend/src/components/VisualizationConfigs/FunnelChartConfig/StepConfig.tsx
packages/frontend/src/hooks/echarts/useEchartsFunnelConfig.ts
packages/frontend/src/hooks/useFunnelChartConfig.ts

Closes: #10484 
Adds settings for labels, colors and legend for funnel charts:
- Change label text
- Change step color
- Hide labels
- Legend position
- Hide legend

feat: color and label settings for funnel chart

---

packages/backend/src/clients/Aws/s3.ts
packages/backend/src/services/CsvService/CsvService.test.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/ServiceRepository.ts

Closes:  https://github.com/lightdash/lightdash/issues/10592
File in s3: https://lightdash-storage-local-test.storage.googleapis.com/l3lUws_M_oo50929fIJYu.jsonl?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=GOOG1EKMFNHMF3MMT4PHVEDYE232MLW7AVESE4ER3AIDY44ZM4FLF4RA76B4Y%2F20240703%2Feurope-west1%2Fs3%2Faws4_request&X-Amz-Date=20240703T150515Z&X-Amz-Expires=259200&X-Amz-Signature=5eaa6311b50e3af3245d520ba7df610ab4bd9520dba921ba21be90147d8f83ba&X-Amz-SignedHeaders=host&x-id=GetObject
https://console.cloud.google.com/storage/browser/lightdash-storage-local-test;tab=objects?forceOnBucketsSortingFiltering=true&authuser=0&project=lightdash-database-staging&prefix=&forceOnObjectsSortingFiltering=true

feat: s3 result streaming

---

docs/docs/guides/cli/how-to-use-lightdash-validate.mdx
docs/docs/references/dimensions.mdx
docs/docs/references/metrics.mdx
packages/backend/src/controllers/validationController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/scheduler/SchedulerTask.ts
packages/backend/src/services/ValidationService/ValidationService.test.ts
packages/backend/src/services/ValidationService/ValidationService.ts
packages/cli/src/handlers/validate.ts
packages/cli/src/index.ts
packages/common/src/types/scheduler.ts
packages/common/src/types/validation.ts

Closes: #10595
- Adds option to validate only tables to CLI
https://github.com/lightdash/lightdash/assets/22939015/fd717aa6-60e9-43c0-8fbc-d032c0b283fa

feat: add table only validation to cli

---

packages/common/src/index.ts
packages/frontend/src/components/common/Filters/FieldIcon.tsx
packages/frontend/src/features/sqlRunner/components/TableFields.tsx
packages/frontend/src/features/sqlRunner/hooks/useTableFields.tsx

Closes: [#10613](https://github.com/lightdash/lightdash/issues/10613) 
Changes:
- amend API response typing
- truncate long field names
- show type
Video:
https://github.com/lightdash/lightdash/assets/9117144/3f0975cf-c2e9-449c-997b-b9070dcad4f2

feat: show sql runner field type and truncate long names

---

docs/docs/snippets/allowed-email-domains.mdx
packages/frontend/src/components/VisualizationConfigs/common/EditableText.tsx

docs: changed the wrong email domain mentioned

---

packages/backend/src/clients/Aws/s3.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/downloadFile.ts

Closes:  https://github.com/lightdash/lightdash/issues/10647

fix: stream s3 sql runner results from backend

---

packages/frontend/src/components/common/LightTable/index.tsx
packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
packages/frontend/src/components/common/Table/Table.styles.ts
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/visualizations/Table.tsx
packages/frontend/src/features/sqlRunner/processors/TableDataProcessor.ts
packages/frontend/src/features/sqlRunner/transformers/TableDataTransformer.ts
packages/frontend/src/features/sqlRunner/transformers/useTableDataTransformer.ts

Closes: #10635
- Adds `TableDataTransformer`
- Adds `Table` component under `/visualizations`
- Gets style components already used in other tables' viz and applies these to the `Table` component
On `TableDataTransformer`
- Reads the results and provides all necessary methods to render a table
- Accounts for elements in the config (which will be done on a different issue) and will get columns depending on the config passed.
Demo:
https://github.com/lightdash/lightdash/assets/7611706/a582fef5-4485-426b-8a08-1f0c9d0aa514

chore: create table component and config

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/SpaceModel.ts
packages/common/src/types/space.ts
packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceUserList.tsx
packages/frontend/src/components/common/SpaceActionModal/CreateSpaceAddUser.tsx
packages/frontend/src/components/common/SpaceActionModal/CreateSpaceModalContent.tsx

fix: use project level role to show warning on frontend

---

packages/backend/src/services/DashboardService/DashboardService.ts
packages/backend/src/services/SavedChartsService/SavedChartService.ts
packages/backend/src/services/SchedulerService/SchedulerService.ts
packages/common/src/utils/scheduler.test.ts
packages/common/src/utils/scheduler.ts
packages/frontend/src/components/ReactHookForm/CronInput/CustomInputs.tsx
packages/frontend/src/components/ReactHookForm/CronInput/index.tsx
packages/frontend/src/utils/fieldValidators.ts

Closes:  https://github.com/lightdash/lightdash/issues/10432
Extra fix: 
Fixed cron max width on schedulers ( I didn't fix it on sync) 
Before:
After:

feat: limit schedulers hourly

---

.github/workflows/cli-tests.yml
dockerfile
dockerfile-prs

Closes:  https://github.com/lightdash/lightdash/issues/10673

feat: support dbt postgres 1.8

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/visualizations/Table.tsx
packages/frontend/src/features/sqlRunner/hooks/useSqlQueryRun.tsx
packages/frontend/src/features/sqlRunner/transformers/useTableDataTransformer.ts
packages/frontend/src/pages/SqlRunnerNew.tsx

Closes: https://github.com/lightdash/lightdash/issues/10683
On successful sql query result: open the results drawer/panel if it was originally closed. 
Demo: 
https://github.com/lightdash/lightdash/assets/7611706/66ebb8fc-5db0-4932-b901-16a637e11c1c

feat: open results on successful sql query

---

packages/frontend/src/features/sync/components/SyncModalView.tsx

Closes: https://github.com/lightdash/lightdash/issues/10318

feat: disable sync ui

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx

Closes: #10690 
Fixes SQL runner tooltips:
- keep tooltips from staying open
- don't allow multiple tooltips at once
- fix typo in config tooltip

chore: fix sql runner toolitps

---

packages/common/src/transformers/BarChartDataTransformer.ts
packages/common/src/types/visualizations.ts
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/RightSidebar.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts
packages/frontend/src/features/sqlRunner/transformers/useBarChartDataTransformer.ts

Closes: 
Adds config options for bar chart
- rename axes
- rename series
- also updates chart style

chore: add bar chart config

---

packages/common/src/transformers/BarChartDataTransformer.ts
packages/common/src/types/visualizations.ts
packages/frontend/src/features/sqlRunner/components/RightSidebar.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

After some discussion we went back to this:
- Separate series labels from axis labels
- Only one axis by default

chore: separate series names from axis names

---

dockerfile

fix: run backend from packages/backend directory

---

packages/backend/src/controllers/organizationController.ts
packages/backend/src/database/pagination/errors.ts
packages/backend/src/database/pagination/index.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/OrganizationMemberProfileModel.ts
packages/backend/src/models/SearchModel/utils/search.ts
packages/backend/src/services/OrganizationService/OrganizationService.ts
packages/common/src/index.ts
packages/common/src/types/errors.ts
packages/common/src/types/knex-paginate.ts
packages/common/src/types/organizationMemberProfile.ts
packages/e2e/cypress/e2e/app/settings/invites.cy.ts
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/UsersView.tsx
packages/frontend/src/hooks/useOrganizationUsers.ts

Closes: #10549 
- Adds pagination to user list
- Adds backend search (using regex matching) so that we're able to search paginated results instead of just results on each page
Note: tried using different libs that already implemented pagination but there was always some problem with typescript types coming from knex. Ended up deciding on our own pagination so that we can maintain it as we go and add functionality to it if needed
https://github.com/lightdash/lightdash/assets/22939015/251f428e-8e35-4d5e-831d-b80ea04be309

feat: user list pagination

---

packages/backend/src/services/UserService.ts

fix: add user to group on creation okta

---

packages/frontend/src/components/Explorer/SqlCard/OpenInSqlRunnerButton.tsx

Closes: N/A
Adds feature flag: `'databricks-notebook-button'` (purposedly not using the `featureflags.ts` file approach as this is a mock feature)
Styled demo:
https://github.com/user-attachments/assets/4d46d4bd-aab6-42fe-997e-f6a5032222f2

chore: add databricks sql runner option (mock)

---

packages/frontend/src/features/sqlRunner/hooks/useSavedSqlCharts.tsx

Closes: N/A
from `update` to `updated`

chore: fix small typo copy

---

packages/backend/src/controllers/sqlRunnerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/SavedSqlModel.ts
packages/backend/src/services/SavedSqlService/SavedSqlService.ts
packages/common/src/types/sqlRunner.ts
packages/e2e/cypress/e2e/api/sqlRunner.cy.ts
packages/frontend/src/Routes.tsx
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/hooks/useSavedSqlCharts.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts
packages/frontend/src/pages/SqlRunnerNew.tsx

Closes: [#10710](https://github.com/lightdash/lightdash/issues/10710) 
Route has a slug instead of a uuid.
On creation, we get all matching slugs and generate a new slug that doesn't exist. 
There is a small change of a race condition generating the same slug and the database returns an error.

feat: sql runner slug

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx

Closes: https://github.com/lightdash/lightdash/issues/10676
thread: https://lightdash.slack.com/archives/C05UPNC0LGP/p1720704503869989?thread_ts=1720543597.835129&cid=C05UPNC0LGP

fix: show warning custom dimension viewers

---

packages/frontend/src/components/Explorer/SqlCard/OpenInSqlRunnerButton.tsx

This reverts commit a120601a1259d7abf8d40f008341e4e277a43bc6.

chore: revert "chore: add databricks sql runner option (mock) (#10719)"

---

packages/backend/src/models/DashboardModel/DashboardModel.ts
packages/common/src/transformers/BarChartDataTransformer.ts
packages/common/src/types/dashboard.ts
packages/frontend/src/components/DashboardTabs/GridTile.tsx
packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx
packages/frontend/src/components/DashboardTiles/TileForms/TileUpdateModal.tsx
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/visualizations/BarChart.tsx
packages/frontend/src/pages/MinimalDashboard.tsx

Closes: https://github.com/lightdash/lightdash/issues/10640
Allows charts created by the SQL runner to render on a Dashboard. 
Updates and adds types to allow this
> [!IMPORTANT]  
> To fully test this, you can use the mocks below ⬇️  because we depend on: https://github.com/lightdash/lightdash/issues/10693 but this is basically preparing the FE to render SQL charts in a dashboard
demo with a bar chart
Adds component for SQL dashboard tiles with TODOs: 
- add hook to get results and config
- get loading and error states to display the necessary tile base
- use `sqlRunner`s Table to display the correct viz
You can try this with the following mock
<details>
<summary>Add the following to `useDashboardQuery`'s select in `DashboardProvider`:</summary>
```
return {
...d,
tiles: d.tiles.concat([ …
```

feat: allow dashboards to render SQL runner charts 

---

examples/api/dashboard.http
packages/backend/src/database/entities/dashboards.ts
packages/backend/src/database/migrations/20240716141621_add_saved_sql_tile_type.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/DashboardModel/DashboardModel.ts
packages/common/src/types/dashboard.ts

feat: save sql chart tile

---

packages/frontend/src/features/sqlRunner/components/Header.tsx
packages/frontend/src/features/sqlRunner/components/ShareSqlLinkButton.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts
packages/frontend/src/hooks/useShare.ts
packages/frontend/src/pages/ShareRedirect.tsx
packages/frontend/src/pages/SqlRunnerNew.tsx

Closes:  https://github.com/lightdash/lightdash/issues/10668
[Screencast from 17-07-24 16:57:28.webm](https://github.com/user-attachments/assets/8366c19d-be63-4f84-8585-21d38654dcec)

feat: Share sql chart url

---

packages/frontend/src/components/Explorer/SqlCard/SqlCard.tsx
packages/frontend/src/components/common/CollapsableCard.tsx

Closes: #10602
solves issue #10602 
https://github.com/user-attachments/assets/f981297e-3ce8-48b6-abe4-32c66b921461
-----
This Is WORKING now. It WILL copy the SQL too, unlike the last time😂. (#10717)

feat: added a copy sql button when card is closed

---

packages/backend/src/database/pagination/index.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/types/knex-paginate.ts
packages/common/src/types/sqlRunner.ts
packages/frontend/src/components/Explorer/SqlCard/SqlCard.tsx
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/UsersView.tsx
packages/frontend/src/hooks/useCompiledSql.tsx

Closes: 
Unblocks https://github.com/lightdash/lightdash/pull/10774 so that we can generate the API docs correctly with `redocusaurus`

chore: fixes paginate type

---

docs/docs/get-started/setup-lightdash/connect-project.mdx
docs/docs/references/roles.mdx
docs/docs/references/syncing_your_dbt_changes.mdx

Closes: #9392 , #10667 , #4711 
Update to say we support dbt v1.4+ closes https://github.com/lightdash/lightdash/issues/9392
Add Create and explore custom SQL dimensions to project role table with access for admin and devs only, closes https://github.com/lightdash/lightdash/issues/10667
Fix ip address link, closes https://github.com/lightdash/lightdash/issues/4711

docs: various quick fixes

---

packages/frontend/src/features/sqlRunner/components/SqlEditor.tsx

Closes: https://github.com/lightdash/lightdash/issues/10781
Needs design input

feat: add lightdash SQL theme

---

packages/frontend/src/features/sqlRunner/components/SqlEditor.tsx

Closes: https://github.com/lightdash/lightdash/issues/10789
Gets tables from server state (cached because the list on left side-bar is already loaded)
Generates quoted table autocompletion.
Demo:
https://github.com/user-attachments/assets/3c6f148f-c5b2-4907-b5a3-dee091cc7ebf

feat: add SQL editor autocompletion

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/ResourceViewItemModel.ts
packages/backend/src/models/SavedChartModel.ts
packages/backend/src/models/SpaceModel.ts
packages/backend/src/services/ProjectService/ProjectService.mock.ts
packages/backend/src/services/PromoteService/PromoteService.mock.ts
packages/common/src/types/resourceViewItem.ts
packages/common/src/types/savedCharts.ts
packages/frontend/src/components/common/ResourceView/resourceUtils.ts
packages/frontend/src/components/common/modal/ChartCreateModal/SaveToSpaceOrDashboard.tsx
packages/frontend/src/features/sqlRunner/components/SaveSqlChartModal.tsx

feat: Save sql chart in space and fix slug for sql charts

---

docs/docs/references/tables.mdx

docs: fixes typo

---

packages/frontend/src/components/RefreshButton.tsx

Closes: #9476
- Added **divider** between Run Query Button and Down arrow-head.
- Used Gray color and RGBA to add **transparent** effect, this makes divider clear and subtle.

style: add divider to Run Query Group Button

---

packages/e2e/cypress/e2e/api/catalog.cy.ts
packages/e2e/cypress/e2e/api/content.cy.ts
packages/e2e/cypress/e2e/api/dashboard.cy.ts
packages/e2e/cypress/e2e/api/promotion.cy.ts
packages/e2e/cypress/support/mocks.ts

Closes:  https://github.com/lightdash/lightdash/issues/10763

chore: api v2 integration tests

---

docs/docs/get-started/setup-lightdash/connect-project.mdx
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/types/projects.ts
packages/frontend/src/components/ProjectConnection/WarehouseForms/SnowflakeForm.tsx
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Closes:  https://github.com/lightdash/lightdash/issues/10714
Before:
After:

fix: Override snowflake warehouse

---

packages/backend/src/services/DashboardService/DashboardService.ts

Closes:  #10752
Before:
After:

fix: create unique slug for charts within dashboards

---

packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx

fix: duplicate chart on dashboard with different name

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/authorization/organizationMemberAbility.ts
packages/common/src/authorization/projectMemberAbility.ts
packages/common/src/authorization/types.ts
packages/frontend/src/components/RefreshDbtButton/index.tsx

Closes:  #10827
Editors: 
Devs and admins:

feat: new compile project ability

---

packages/backend/src/logging/winston.ts

Closes: [#411](https://github.com/lightdash/lightdash-cloud/issues/411)
**using default pretty format**
**using json format**
```
{"message":"Starting sentry transaction 9fcccc862b78793d \"Passport.deserializeUser\" with context: {}","level":"debug","sentryTraceId":"681071b92bc7e6d1996479b533e90d02","timestamp":"2024-07-25 14:05:24"}
{"message":"Starting sentry transaction 08a03d678a6f0c31 \"Passport.deserializeUser\" with context: {}","level":"debug","sentryTraceId":"95152c2faf5c0d60b710931ae14291f2","timestamp":"2024-07-25 14:05:24"}
{"message":"Starting sentry transaction c5193580e618398e \"Passport.deserializeUser\" with context: {}","level":"debug","sentryTraceId":"bb1a4d301529b29045f0c9d7e51c4d6b","timestamp":"2024-07-25 14:05:24"}
{"message":"Starting sentry transaction …
```

chore: add sentry trace id to winston formatters

---

docs/docs/self-host/customize-deployment/configure-a-slack-app-for-lightdash.mdx

changes slack manifest in docs. we've updated slack required scopes recently: https://github.com/lightdash/lightdash/blob/main/packages/common/src/types/slackSettings.ts
ℹ️ I've also updated an internal doc

docs: slack permission update

---

packages/frontend/src/features/sqlRunner/components/SaveSqlChartModal.tsx
packages/frontend/src/features/sqlRunner/components/ShareSqlLinkButton.tsx
packages/frontend/src/features/sqlRunner/hooks/useSavedSqlCharts.tsx

Fix some errors in SQL runner:
- Errors from missing form defaults in the save modal
- Fix forwarded ref error on link button
- Don't fetch saved SQL runner if the slug is undefined

chore: small sql runner fixes for console and network errors

---

examples/full-jaffle-shop-demo/dbt/models/schema.yml

Closes: 
Revert unused customer description to fix e2e tests

fix: revert customer yml description

---

packages/common/src/schemas/json/lightdash-dbt-2.0.json

Closes: xxx
I don't create an issue corresponding to the pull request due to the minor change. Please let me know, if I should create one.
dbt now provides the `unit_tests` property.
https://docs.getdbt.com/reference/resource-properties/unit-tests

chore: Add `unit_tests` property to `lightdash-dbt-2.0.json`

---

packages/backend/src/services/PromoteService/PromoteService.ts

Closes: https://github.com/lightdash/lightdash/issues/10743

fix: promotion upsert chart type

---

packages/frontend/src/features/sqlRunner/components/Tables.tsx

small QOL
https://github.com/user-attachments/assets/2af79c52-9274-4224-81df-6799eca74346

fix: sql autofill

---

packages/frontend/src/features/sqlRunner/components/RightSidebar.tsx
packages/frontend/src/features/sqlRunner/components/VisualizationSwitcher.tsx

Closes: N/A
Adds new visualization switcher
This is from work done with @PriPatel in the past
demo:
https://github.com/user-attachments/assets/f5fa3328-4db2-475f-9a32-785fe723e884

feat: introduce new visualization switcher

---

packages/frontend/src/Routes.tsx
packages/frontend/src/features/sqlRunner/components/Header.tsx
packages/frontend/src/features/sqlRunner/components/HeaderViewMode.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts
packages/frontend/src/pages/ViewSqlChart.tsx

Closes: [#10851](https://github.com/lightdash/lightdash/issues/10851)
Add page to view a saved SQL chart.
Admin:
https://github.com/user-attachments/assets/c561e6b0-2a72-45b5-bb0b-6bbc168250b1
Viewer:
https://github.com/user-attachments/assets/240cd447-f24c-40b8-97db-28c2c6ef881d

feat: view page for SQL chart

---

docs/docs/references/tables.mdx

docs: update tables doc indentation

docs: update tables doc indentation

---

.github/workflows/cli-tests.yml

fix: fix dbt 1.8 cli tests

---

packages/common/src/visualizations/SqlRunnerResultsTransformer.ts
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/visualizations/BarChart.tsx
packages/frontend/src/features/sqlRunner/store/barChartSlice.ts
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts
packages/frontend/src/features/sqlRunner/store/tableVisSlice.ts

Closes: #10854
Resets configuration to default if the state matches the previous chart default
https://github.com/user-attachments/assets/aeb2ef24-1464-421c-96ba-89be4c9f7e96

fix: improve bar chart defaults

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/DeleteSqlChartModal.tsx
packages/frontend/src/features/sqlRunner/components/Header.tsx
packages/frontend/src/features/sqlRunner/components/HeaderViewMode.tsx
packages/frontend/src/features/sqlRunner/hooks/useSavedSqlCharts.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

Closes: [#10898](https://github.com/lightdash/lightdash/issues/10898)
Add delete button in view/edit page.

feat: option to delete SQL chart

---

packages/common/src/visualizations/SqlRunnerResultsTransformer.ts
packages/frontend/src/features/sqlRunner/components/BarChartFieldConfiguration.tsx
packages/frontend/src/features/sqlRunner/store/barChartSlice.ts

feat: add pivot to bar charts

---

packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts

fix: databricks log on close error

---

packages/frontend/src/features/sqlRunner/components/BarChartFieldConfiguration.tsx

Partial for [#10862](https://github.com/lightdash/lightdash/issues/10862)
https://github.com/user-attachments/assets/1e5814a8-bc13-4b44-9451-950cf6beb506

feat: add validation to bar chart field config

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx

refactor: remove expand/collapse from sql runner

---

packages/frontend/src/components/common/modal/ChartCreateModal/SaveToSpaceOrDashboard.tsx
packages/frontend/src/features/sqlRunner/components/Header.tsx
packages/frontend/src/features/sqlRunner/components/UpdateSqlChartModal.tsx
packages/frontend/src/features/sqlRunner/hooks/useSavedSqlCharts.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

Closes: [#10902](https://github.com/lightdash/lightdash/issues/10902) 
https://github.com/user-attachments/assets/884ae926-7876-4bb7-a0df-7e44dc0a90b5

feat: allow to update SQL chart name, description, space

---

packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts
packages/frontend/src/pages/SqlRunnerNew.tsx
packages/frontend/src/pages/ViewSqlChart.tsx

Closes: [#10910](https://github.com/lightdash/lightdash/issues/10910)
Before:
https://github.com/user-attachments/assets/f671276f-7280-41a3-bb0f-c6c1082b17d0
After:
https://github.com/user-attachments/assets/c0ddbc66-3b57-4c7f-bd52-e96ebb75d5fd

fix: reset SQL runner redux state on page unmount

---

packages/common/src/schemas/json/lightdash-dbt-2.0.json

Closes: xxx
I didn't create an issue for the pull request. Please let me know, if I should create one.
> New data_tests: syntax
> Data tests were historically called "tests" in dbt as the only form of testing available. With the introduction of unit tests in v1.8, it was necessary to update our naming conventions and syntax.
> As of v1.8, tests: is still supported in your YML configuration files as an alias but will be deprecated in the future in favor of data_tests:.
https://docs.getdbt.com/docs/build/data-tests

chore: Support `data_tests` in `lightdash-dbt-2.0.json`

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
yarn.lock

Closes: N/A
(yarn lock changed because of this: https://github.com/lightdash/lightdash/pull/10875)
before 
after

style: reduce content panel headers padding

---

packages/common/src/visualizations/BarChartDataTransformer.ts
packages/common/src/visualizations/SqlRunnerResultsTransformer.ts
packages/frontend/src/features/sqlRunner/components/BarChartStyling.tsx
packages/frontend/src/features/sqlRunner/store/barChartSlice.ts

https://github.com/user-attachments/assets/5fae1e6a-2be3-4dc8-8d31-f5ce44880d6c

feat: change the position of bar y-axis

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx

Closes: N/A
Before
https://github.com/user-attachments/assets/cb4ea645-0062-4d48-9ecd-88759b0e2211
After
https://github.com/user-attachments/assets/9724241b-bf8e-4348-b06e-dbc9630467c5

style: add overflow auto to paper wrapper

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/visualizations/BarChart.tsx
packages/frontend/src/features/sqlRunner/hooks/useSqlQueryRun.tsx

Closes: #10923 
- keeps results while new results pending
- fixes loading state to watch for `isFetching` (`isLoading` is true from react query while data is undefined, even if not fetching)
- fixes loading state to include job status fetching (prevents blinking loading state)
- adds overlay to previous results on results fetching
- replaces bar chart loading state with same loading overlay
https://github.com/user-attachments/assets/415055ca-31c7-4c7e-a314-07e3a3e5cec9

feat: improved loading state for sql runner

---

packages/frontend/src/features/sqlRunner/components/visualizations/BarChart.tsx
packages/frontend/src/features/sqlRunner/components/visualizations/PieChart.tsx

Closses: https://github.com/lightdash/lightdash/issues/10931

fix: notMerge eCharts on barcharts

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/models/OpenIdIdentitiesModel.ts
packages/backend/src/services/UserService.ts

Closes: [#10886](https://github.com/lightdash/lightdash/issues/10886)
- Adds `issuerType` to analytics events

chore: add issuerType to analytics events

---

packages/common/src/visualizations/BarChartDataTransformer.ts
packages/common/src/visualizations/ResultsTransformerBase.ts
packages/common/src/visualizations/SqlRunnerResultsTransformer.ts
packages/frontend/src/features/sqlRunner/components/BarChartFieldConfiguration.tsx
packages/frontend/src/features/sqlRunner/store/barChartSlice.ts

Closes: https://github.com/lightdash/lightdash/issues/10942
https://github.com/user-attachments/assets/9a7eb96b-fd33-4aa6-a9f5-fbdfe92971cd

fix: use time axes on bar charts

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/models/SavedSqlModel.ts
packages/backend/src/services/DashboardService/DashboardService.ts
packages/backend/src/services/SavedSqlService/SavedSqlService.ts

Closes: [#10927](https://github.com/lightdash/lightdash/issues/10927)

chore: add SQL chart events

---

packages/frontend/src/features/sqlRunner/components/Header/HeaderEdit.tsx

Closes: 
Fix linting after merge conflict.

chore: fix import order

---

packages/frontend/src/features/sqlRunner/store/pieChartSlice.ts
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts
packages/frontend/src/pages/ViewSqlChart.tsx

Closes: #10939 
Pie chart wasnt loading it's data or being instantiate on the view page. This fixes that.
Note that this is based on a couple other reviews, this review will be cleaner when they merge.

chore: fix saving pie chart

---

packages/frontend/src/features/sqlRunner/components/BarChartStyling.tsx

Closes: N/A
From a `Select` to a `SegmentedControl`
demo
https://github.com/user-attachments/assets/516c006a-f034-424e-be34-c58f84119672

style: improve y axis position input

---

docs/docs/guides/how-to-embed-content.mdx
docs/docs/references/embedding.mdx

Adds known limitations to embedding docs, still waiting for more details from the team to make sure this is comprehensive.

docs: add embedding limitations

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Closes:  #10714
How to configure snowflake_warehouse,
eg: in events.sql add at the top.
```
{{
config(
materialized='table',
snowflake_warehouse='EXTRA_LARGE'
)
}}
```
Before: 
After:
The error I get at the beggining is because it is using an invalid schema.
[Screencast from 02-08-24 11:48:27.webm](https://github.com/user-attachments/assets/2d5bd95f-05db-4016-8bcb-5194d500f356)

fix: snowflake override warehouse

---

packages/frontend/src/features/tableCalculation/components/SqlForm.tsx
packages/frontend/src/features/tableCalculation/components/TableCalculationModal.tsx

After https://github.com/lightdash/lightdash/pull/10901 was merged, `tableCalculation.cy.ts` e2e test failed when trying to write in the sql editor
- reverts css changes of previous PR fixes conflicting z-index + scroll area height which was making the test fail
**after fix**
https://github.com/user-attachments/assets/3b104a29-14e7-439c-adc6-7114726679e8

fix: e2e test couldn't write to sql editor

---

packages/backend/src/clients/Slack/SlackMessageBlocks.ts
packages/backend/src/scheduler/SchedulerTask.ts
packages/common/src/types/scheduler.ts
packages/frontend/src/features/scheduler/components/SchedulerForm.tsx

Closes:  #10980
This is an icon, not a button like in the ticket because this doesn't have any clickable action. But I'm happy to other suggestions

fix: threshold alert copy and icon

---

packages/backend/src/scheduler/SchedulerTask.mock.ts
packages/backend/src/scheduler/SchedulerTask.test.ts
packages/backend/src/scheduler/SchedulerTask.ts

Closes:  https://github.com/lightdash/lightdash/issues/10979

fix: increase by and decreased by alert threshold

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx

Closes: #10988
Zindex issue
demo: 
https://github.com/user-attachments/assets/2dec133e-042a-492d-8370-0628355fcb05

style: hide loading overlay when closed - results table

---

packages/frontend/src/features/sqlRunner/components/CartesianChartFieldConfiguration.tsx
packages/frontend/src/features/sqlRunner/store/cartesianChartBaseSlice.ts

Closes: #10984
I believe this are the touch points
Ensures we set defaults on the slice

refactor: handle setX/YAxisReference defaults in slice

---

packages/frontend/src/components/DashboardFilter/FilterConfiguration/FilterSettings.tsx
packages/frontend/src/pages/Dashboard.tsx

Closes:  https://github.com/lightdash/lightdash/issues/10868
[Screencast from 02-08-24 09:42:25.webm](https://github.com/user-attachments/assets/8caf8d0d-9f28-4452-b894-f6d9e4ee53c6)

fix: temporary value on required filter

---

packages/backend/src/models/SchedulerModel/index.ts
packages/frontend/src/features/scheduler/components/SchedulersList.tsx
packages/frontend/src/features/scheduler/components/SchedulersListItem.tsx
packages/frontend/src/features/sync/components/SyncModalView.tsx

Closes: https://github.com/lightdash/lightdash/issues/10978
- fixes scheduler list order for charts
- fixes scheduler list order for dashboards
- fixes inconsistencies in the UI
⚠️ let me know if you think sorting by created_at is a better variant
https://github.com/user-attachments/assets/67904dee-b1d7-4591-a752-1cd53cec95aa

fix: sort scheduler list by name to avoid reorders

---

packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx
packages/frontend/src/features/sqlRunner/hooks/requestUtils.ts
packages/frontend/src/features/sqlRunner/hooks/useSqlChartAndResults.tsx
packages/frontend/src/features/sqlRunner/hooks/useSqlChartResults.ts

Closes: [#10960](https://github.com/lightdash/lightdash/issues/10960) 
Problems
- Hook with chained react queries were returning different objects on each rerender
- Fixed by using one react query. Fix mentioned here [#10969](https://github.com/lightdash/lightdash/issues/10969)
- a new object was created on each DashboardSqlChartTile render
- Fixed by memorizing the object
before:
after:

fix: SQL chart dashboard tile loading state

---

packages/frontend/src/components/Explorer/ResultsCard/QuickCalculations.tsx

fix: quick table calculation sorting

---

docs/docs/references/tables.mdx
packages/backend/src/queryBuilder.mock.ts
packages/backend/src/queryBuilder.ts
packages/common/src/compiler/exploreCompiler.mock.ts
packages/common/src/compiler/exploreCompiler.ts
packages/common/src/compiler/translator.test.ts
packages/common/src/types/explore.ts

Closes: https://github.com/lightdash/lightdash/issues/10828
test-frontend

fix: table `sql_filter` should join a referenced table

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/pages/ViewSqlChart.tsx

Closes: 
Changes:
https://github.com/user-attachments/assets/ba6395fd-dfb1-4106-8d0a-da80e8d6a26c

fix: SQL chart view page loading state and chart height

---

packages/frontend/src/features/sqlRunner/store/tableVisSlice.ts

Closes: #11011 
**The problem was:** when a new SQL query was run, the table viz kept it's old config which didn't match any of the new columns and the chart would render nonsense (empty table)
**Now:** when a new query is run, the columns get reset to the columns from the new query. This is the same behavior as the bar chart
**Note:** in the future we could try harder to merge the old columns with the new or show some kind of warning, but this should at least un-break the case of totally new queries
**Before**
**After**

fix: reset table config when columns change

---

packages/cli/src/dbt/manifest.ts
packages/cli/src/handlers/compile.ts
packages/cli/src/handlers/dbt/compile.ts

Reverts lightdash/lightdash#11019
Relates to: #4748

fix: revert "cli join compile"

---

packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx
packages/frontend/src/features/sqlRunner/hooks/useSqlChartAndResults.tsx
packages/frontend/src/features/sqlRunner/hooks/useSqlChartResults.ts
packages/frontend/src/pages/ViewSqlChart.tsx

fix: use columns from saved sql charts

---

docker/docker-compose.dev.yml
packages/backend/src/clients/dbtCloud/DbtCloudGraphqlClient.ts
packages/backend/src/controllers/metricFlowController.ts
packages/common/src/index.ts
packages/common/src/types/dbtSemanticLayer.ts

Relates to: #11027 
- Adds `getSql`, `runQuery`, `getMetrics`, `getMetricsForDimensions` and `getDimensions` functions to the graphql client
- types args and responses

feat: prepare graphql client with necessary functions

---

packages/common/src/schemas/json/lightdash-dbt-2.0.json

Closes: xxx
It might be good to define the accepted values of the `type` property for dimensions.
https://docs.lightdash.com/references/dimensions/#type

chore: enumerate data type of dimension in `lightdash-dbt-2.0.json`

---

packages/cli/README.md

Closes: N/A
Some formatting improvements and added small instructions on testing different dbt versions

docs: update cli development docs with example and caveat

---

docs/docs/references/tables.mdx

docs: sql filter join amendment

---

packages/e2e/cypress/e2e/api/semanticLayer.cy.ts

chore: add semantic layer integration test (placeholder)

---

docs/docs/get-started/develop-in-lightdash/intro.mdx
docs/docs/get-started/exploring-data/dashboards.mdx
docs/docs/get-started/intro.mdx
docs/docs/references/dimensions.mdx

Closes: #10841
A bunch of small docs updates I've had in my notes for a while 😸

docs: various minor updates

---

packages/frontend/src/features/semanticViewer/components/SidebarViewFields.tsx
packages/frontend/src/features/semanticViewer/components/SqlViewer.tsx
packages/frontend/src/features/semanticViewer/store/semanticViewerSlice.ts

- Tracks and sends `timeDimensions` in FE

fix: add timeDimensions to frontend

---

docker/docker-compose.dev.yml
packages/backend/src/clients/cube/CubeClient.ts
packages/backend/src/clients/cube/transformer.ts
packages/backend/src/clients/dbtCloud/DbtCloudGraphqlClient.ts
packages/backend/src/clients/dbtCloud/transformer.ts
packages/backend/src/controllers/v2/SemanticLayerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/SemanticLayerService/SemanticLayerService.ts
packages/common/src/types/semanticLayer.ts
packages/frontend/src/features/semanticViewer/api/hooks.ts
packages/frontend/src/features/semanticViewer/api/requests.ts
packages/frontend/src/features/semanticViewer/components/SidebarViewFields.tsx

Relates to: #11030 
- Set visibility of fields when selecting from sidebar
test-frontend
test-backend

feat: hide fields on toggle

---

packages/common/src/schemas/json/lightdash-dbt-2.0.json

Closes: xxx
The changes is to support groups in `lightdash-dbt-2.0.json`. 
https://docs.lightdash.com/references/dimensions/#groups
I have checked the JSON schema with [check-jsonschema](https://github.com/python-jsonschema/check-jsonschema) locally.
```
$ check-jsonschema --check-metaschema packages/common/src/schemas/json/lightdash-dbt-2.0.json -v
ok -- validation done
The following files were checked:
packages/common/src/schemas/json/lightdash-dbt-2.0.json
```

chore: support groups in `lightdash-dbt-2.0.json`

---

packages/backend/src/clients/cube/transformer.ts
packages/backend/src/clients/dbtCloud/DbtCloudGraphqlClient.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/types/semanticLayer.ts

chore: enforce visible property for semanticLayer view and field

---

packages/frontend/src/components/common/PivotTable/index.tsx

Closes: [#11108](https://github.com/lightdash/lightdash/issues/11108)
before:
after:

fix: ignore invalid color in condition formatting

---

packages/common/src/visualizations/CartesianChartDataTransformer.ts
packages/frontend/src/features/sqlRunner/components/CartesianChartStyling.tsx
packages/frontend/src/features/sqlRunner/store/cartesianChartBaseSlice.ts

Closes: #11061 
https://github.com/user-attachments/assets/452b1211-4b15-4204-8f99-c4210a596054

feat: allow stacking cartesian charts

---

packages/backend/src/clients/cube/CubeClient.ts
packages/backend/src/clients/cube/transformer.ts
packages/backend/src/clients/dbtCloud/DbtCloudGraphqlClient.ts
packages/backend/src/clients/dbtCloud/transformer.ts
packages/backend/src/controllers/v2/SemanticLayerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/SemanticLayerService/SemanticLayerService.ts
packages/common/src/types/semanticLayer.ts
packages/e2e/cypress/e2e/api/semanticLayer.cy.ts
packages/frontend/src/features/semanticViewer/api/hooks.ts
packages/frontend/src/features/semanticViewer/api/requests.ts
packages/frontend/src/features/semanticViewer/api/streamingResults.ts
packages/frontend/src/features/semanticViewer/components/Content.tsx
packages/frontend/src/features/semanticViewer/components/ResultsViewer.tsx
packages/frontend/src/features/semanticViewer/components/SidebarViewFieldItem.tsx
packages/frontend/src/features/semanticViewer/components/SidebarViewFields.tsx
packages/frontend/src/features/semanticViewer/components/SidebarViewFieldsGroup.tsx
packages/frontend/src/features/semanticViewer/components/SidebarViewFieldsGroupItem.tsx
packages/frontend/src/features/semanticViewer/components/SqlViewer.tsx
packages/frontend/src/features/semanticViewer/store/selectors.ts
packages/frontend/src/features/semanticViewer/store/semanticViewerSlice.ts

Closes: https://github.com/lightdash/lightdash/issues/11030
Closes: https://github.com/lightdash/lightdash/issues/11086

feat: semantic viewer layout and UI

---

packages/frontend/src/features/sqlRunner/components/Header/HeaderCreate.tsx
packages/frontend/src/features/sqlRunner/components/Header/HeaderEdit.tsx

Closes: https://github.com/lightdash/lightdash/issues/11147
There could be more to be done, like making it green when there are changes, but this is more explicit now.

style: change save sql chart to a button

---

packages/common/src/visualizations/CartesianChartDataTransformer.ts
packages/frontend/src/features/sqlRunner/components/CartesianChartFormatConfig.tsx
packages/frontend/src/features/sqlRunner/components/CartesianChartStyling.tsx
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/store/cartesianChartBaseSlice.ts

Closes: #11092 
Allows formatting of field by `percentage`
This is all done on the EchartsSpec.
https://github.com/user-attachments/assets/4cc41b9d-7582-4a5d-bf5a-ed3f05cf140c

feat: allow formatting by percentage

---

packages/backend/src/generated/swagger.json
packages/common/src/types/semanticLayer.ts
packages/frontend/src/features/semanticViewer/components/Content.tsx
packages/frontend/src/features/semanticViewer/components/ResultsViewer.tsx
packages/frontend/src/features/semanticViewer/components/Sidebar.tsx
packages/frontend/src/features/semanticViewer/components/SidebarViewFields.tsx
packages/frontend/src/features/semanticViewer/components/SidebarViewFieldsGroup.tsx
packages/frontend/src/features/semanticViewer/components/SidebarViewFieldsGroupItem.tsx
packages/frontend/src/features/semanticViewer/components/SqlViewer.tsx
packages/frontend/src/features/semanticViewer/components/TimeDimensionGranularityPicker.tsx
packages/frontend/src/features/semanticViewer/store/selectors.ts
packages/frontend/src/features/semanticViewer/store/semanticViewerSlice.ts

Closes: https://github.com/lightdash/lightdash/issues/11125

feat: semantic viewer field granularity selector

---

packages/frontend/src/features/sqlRunner/hooks/useSqlChartAndResults.tsx
packages/frontend/src/features/sqlRunner/hooks/useSqlChartResults.ts
packages/frontend/src/features/sqlRunner/hooks/useSqlQueryRun.tsx

Closes: [#10969](https://github.com/lightdash/lightdash/issues/10969)
`useSqlQueryRun` only uses one mutation and has a `keepPreviousData`-like logic similar to `useQuery`'s prop. 
improved documentation of other hooks to be clearer

refactor: simplify `useSqlQueryRun` hook

---

packages/backend/src/controllers/sqlRunnerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/ProjectService/ProjectService.ts
packages/frontend/src/features/sqlRunner/components/Sidebar.tsx
packages/frontend/src/features/sqlRunner/hooks/useTables.tsx

Closes: #11141 
Adds a manual refresh button for the tables list in SQL runner.

feat: add catalog refresh button

---

packages/backend/src/controllers/sqlRunnerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/ProjectService/ProjectService.ts
packages/frontend/src/features/sqlRunner/components/Sidebar.tsx
packages/frontend/src/features/sqlRunner/hooks/useTables.tsx
packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts

Closes: 
Filters out postgres system tables when getting the catalog

fix: filter out postgres tables

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx

Closes: N/A
Still need to fix the extra space up top, but this makes it possible to scroll a table vis. 
https://github.com/user-attachments/assets/5d99af64-3ff2-46bd-8a6a-fe37036f9207

style: pass overflow hidden if current vis is table

---

packages/common/src/types/sqlRunner.ts
packages/frontend/src/features/sqlRunner/hooks/requestUtils.ts
packages/frontend/src/features/sqlRunner/hooks/useSqlChartAndResults.tsx
packages/frontend/src/features/sqlRunner/hooks/useSqlChartResults.ts
packages/frontend/src/features/sqlRunner/hooks/useSqlQueryRun.tsx

Closes: 
`return`s instead of throwing the Api Error. 
Fixes types

fix: let query run hook handle error

---

packages/backend/src/controllers/sqlRunnerController.ts
packages/backend/src/queryBuilder.test.ts
packages/backend/src/queryBuilder.ts
packages/backend/src/services/ProjectService/ProjectService.ts

fix: strip trailing semicolon on sql runners

---

packages/frontend/src/features/sqlRunner/hooks/useSqlQueryRun.tsx

Relates to: #11176 
Modified sqlRunner to have a clearer message when error is thrown

fix: display a clearer message in sqlRunner when errors are thrown

---

packages/frontend/src/features/sqlRunner/components/SqlEditor.tsx

Closes: N/A
Amend callback after https://github.com/lightdash/lightdash/pull/11193

fix: amend debounce callback

---

docs/docs/guides/how-to-reset-your-password.md
docs/docs/self-host/customize-deployment/environment-variables.mdx
docs/docs/self-host/customize-deployment/use-sso-login-for-self-hosted-lightdash.mdx
docs/sidebars.js

this is one of many small changes I found with Hamzah when we reviewed things together last week

docs: remove forgot password doc

---

packages/frontend/src/features/sqlRunner/components/Tables.tsx
packages/frontend/src/features/sqlRunner/hooks/useTables.tsx

Closes: N/A
https://github.com/user-attachments/assets/bbe51b48-a530-4ac8-9ec1-6e7ea7db55f0

feat: allow toggling schemas

---

packages/frontend/src/components/DataOps/index.tsx

feat: preview projects as upstream project

---

packages/backend/src/@types/express-session.d.ts
packages/backend/src/controllers/authentication/middlewares.ts
packages/backend/src/routers/apiV1Router.ts
packages/backend/src/services/UserService.ts
packages/frontend/src/MobileRoutes.tsx
packages/frontend/src/Routes.tsx
packages/frontend/src/features/export/components/ExportToGoogleSheet.tsx
packages/frontend/src/features/sync/components/SelectGoogleSheetButton.tsx
packages/frontend/src/hooks/gdrive/useGdrive.ts
packages/frontend/src/pages/AuthPopupResult.tsx

Closes: [#11206](https://github.com/lightdash/lightdash/issues/11206) 
Videos in thread: https://lightdash.slack.com/archives/C02GQKJK84Q/p1724171905645509
Changes:
- popup success/failure page
- popup close automatically
- show error when auth is missing scopes
To test locally you should:
- setup env vars
```
export AUTH_GOOGLE_ENABLED=true
export AUTH_GOOGLE_OAUTH2_CLIENT_ID=
export AUTH_GOOGLE_OAUTH2_CLIENT_SECRET=
export GOOGLE_DRIVE_API_KEY=
```
- run in production mode
```NODE_ENV=production yarn dev```
- use a non lightdash gmail account

fix: google drive authentication

---

packages/backend/src/clients/Slack/SlackMessageBlocks.ts
packages/frontend/src/providers/ThirdPartyServicesProvider.tsx

Closes:  https://github.com/lightdash/lightdash-internal-work/issues/1945
On `health.data?.mode === LightdashMode.DEMO`

chore: add clarity demo

---

packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/models/UserModel.ts
packages/backend/src/overrideUserPassword.ts
packages/backend/src/services/UserService.test.ts
packages/backend/src/services/UserService.ts

feat: allow OIDC to link to account with same verified email

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/results.ts
packages/common/src/types/sqlRunner.ts
packages/common/src/visualizations/types/index.ts
packages/frontend/src/components/DataViz/Results.tsx
packages/frontend/src/components/DataViz/formatters/formatRowValueFromWarehouse.ts
packages/frontend/src/components/DataViz/transformers/ResultsTransformer.ts
packages/frontend/src/components/DataViz/visualizations/Table.tsx
packages/frontend/src/components/common/Table/ScrollableTable/BodyCell.tsx
packages/frontend/src/features/semanticViewer/components/RunSemanticQueryButton.tsx
packages/frontend/src/features/semanticViewer/components/visualizations/Table.tsx
packages/frontend/src/features/semanticViewer/store/semanticViewerSlice.ts
packages/frontend/src/features/semanticViewer/transformers/SemanticViewerResultsTransformer.ts
packages/frontend/src/features/semanticViewer/transformers/TableDataTransformer.ts
packages/frontend/src/features/semanticViewer/transformers/useTableDataTransformer.ts
packages/frontend/src/features/sqlRunner/hooks/useSqlChartAndResults.tsx
packages/frontend/src/features/sqlRunner/hooks/useSqlChartResults.ts
packages/frontend/src/features/sqlRunner/hooks/useSqlQueryRun.tsx
packages/frontend/src/features/sqlRunner/transformers/SqlRunnerResultsTransformer.ts
packages/frontend/src/features/sqlRunner/transformers/TableDataTransformer.ts
packages/frontend/src/features/sqlRunner/transformers/useTableDataTransformer.ts
packages/frontend/src/hooks/useColumns.tsx

Closes: [#11085](https://github.com/lightdash/lightdash/issues/11085)
Removes formatting of rows. Now, we don't access the row value by the `formatted` key, but with the direct value instead.

chore: remove formatted from rows

---

packages/backend/src/controllers/commentsController.ts
packages/backend/src/controllers/dashboardController.ts
packages/backend/src/controllers/savedChartController.ts

Closes: 
We don't want such actions to be available in the demo website.

chore: disable promotion and dashboard comments in demo

---

packages/e2e/cypress/e2e/api/sqlRunner.cy.ts

Closes: N/A
Fix `expect`s after #11268 
test-cli
test-frontend
test-backend

fix: amend expectactions on sql runner api test

---

packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx

Closes:  #11148
I didn't add the tooltip on disabled edit mode, to make the code more readable. Let me know if you think it is needed. 
[Screencast from 29-08-24 12:56:18.webm](https://github.com/user-attachments/assets/2b11c0f4-9059-4048-9306-ca8f31f2e7c5)

feat: edit sql chart from dashboard

---

packages/backend/src/controllers/sqlRunnerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/ProjectService/ProjectService.ts
packages/frontend/src/features/sqlRunner/components/TableFields.tsx
packages/frontend/src/features/sqlRunner/components/Tables.tsx
packages/frontend/src/features/sqlRunner/hooks/useTableFields.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

fix: sql runner fields on different schema

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/SemanticLayerService/Pivoting.ts
packages/common/src/types/semanticLayer.ts
packages/common/src/visualizations/types/index.ts
packages/frontend/src/components/DataViz/config/DataVizAggregationConfig.tsx

feat: avg aggregation sql runner

---

packages/frontend/src/pages/SqlRunner.tsx

chore: add old sql runner banner

---

packages/backend/src/services/ProjectService/ProjectService.ts

fix: use <= for row_index limit

---

packages/backend/src/controllers/sqlRunnerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/queryBuilder.mock.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/warehouse.ts
packages/e2e/cypress/e2e/api/sqlRunner.cy.ts
packages/frontend/src/features/sqlRunner/hooks/requestUtils.ts
packages/frontend/src/features/sqlRunner/hooks/useTableFields.tsx
packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts
packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
packages/warehouses/src/warehouseClients/TrinoWarehouseClient.ts
packages/warehouses/src/warehouseClients/WarehouseBaseClient.ts

Closes: #11134
see comments inline.
This was initially from an issue that said “pre-filled snowflake queries don’t work” but the root problem was worse and actually the schema browser and field browsers weren’t working correctly for snowflake users

fix: handle case sensitivity for SQL catalog for snowflake

---

packages/backend/src/services/DashboardService/DashboardService.ts
packages/backend/src/services/SavedChartsService/SavedChartService.ts
packages/common/src/types/pinning.ts
packages/common/src/types/resourceViewItem.ts
packages/frontend/src/hooks/dashboard/useDashboard.ts
packages/frontend/src/hooks/pinning/useChartPinningMutation.ts
packages/frontend/src/hooks/pinning/useDashboardPinningMutation.ts
packages/frontend/src/hooks/useSavedQuery.ts

fix: fixed delete dashboards from resources list

---

packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

fix: only push if not included

---

packages/common/src/types/sqlRunner.ts
packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx
packages/frontend/src/features/sqlRunner/hooks/useSqlChartAndResults.tsx
packages/frontend/src/features/sqlRunner/hooks/useSqlChartResults.ts
packages/frontend/src/pages/ViewSqlChart.tsx

Closes:  https://github.com/lightdash/lightdash/issues/11353
Before:
After:

fix: display sql runner error

---

packages/backend/src/models/UserModel.ts
packages/backend/src/overrideUserPassword.ts
packages/backend/src/services/UserService.ts

Changes:
- fetch user instead of user session (lighter method)
- amend method to update password to receive a user uuid instead of a user id.
- display errors nicely
Demo changing user password:
Error before:
Error after:

chore: handle script error + tech debt 

---

packages/frontend/src/features/sqlRunner/components/Tables.tsx

fix: allow clicking whole schema name to toggle

---

packages/frontend/src/components/common/ResourceView/ResourceActionHandlers.tsx
packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx
packages/frontend/src/features/sqlRunner/hooks/useSavedSqlCharts.tsx

Closes:  https://github.com/lightdash/lightdash/issues/11293
- rename : needs new modal component
- add to dashboard: needs modifying hooks on add to dashboard component
- pin : needs new endpoint
- promote: needs new endpoint

feat: allow move to space and delete for sql charts

---

packages/backend/src/services/SavedSqlService/SavedSqlService.ts
packages/common/src/types/featureFlags.ts
packages/frontend/src/components/NavBar/ExploreMenu.tsx

Closes: #11380
Clear feature flag `save-sql-chart`

chore: remove feature flag save-sql-chart

---

packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts

Fixes: https://github.com/lightdash/lightdash/issues/11388

fix: check for results and columns length

---

packages/backend/src/services/ProjectService/ProjectService.ts

Closes: 
SELECT * FROM "postgres"."jaffle"."orders" limit 3
Before:
After:

fix: write last row pivot worker

---

packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

chore: add debug log for snowflake catalog queries

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/SearchModel/index.ts
packages/backend/src/services/SearchService/SearchService.ts
packages/common/src/types/search.ts
packages/frontend/src/features/omnibar/components/OmnibarFilters.tsx
packages/frontend/src/features/omnibar/components/OmnibarItemIcon.tsx
packages/frontend/src/features/omnibar/types/searchItem.ts
packages/frontend/src/features/omnibar/utils/getSearchItemLabel.ts
packages/frontend/src/features/omnibar/utils/getSearchItemMap.ts
packages/frontend/src/providers/TrackingProvider.tsx

Related: #11392
I think I'm going to do the list all on a separate PR

feat: add sql runner charts to search

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/SpaceModel.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/savedCharts.ts

Closes:  https://github.com/lightdash/lightdash/issues/11392

feat: add sql runner to popular chart endpoint

---

packages/common/src/visualizations/types/index.ts
packages/frontend/src/components/DashboardTiles/DashboardSqlChartTile.tsx
packages/frontend/src/components/DataViz/hooks/useChartViz.ts
packages/frontend/src/components/DataViz/hooks/useDataVizTable.ts
packages/frontend/src/components/DataViz/hooks/useTableDataModel.ts
packages/frontend/src/components/DataViz/visualizations/ChartVizTransformedDataTable.tsx
packages/frontend/src/features/semanticViewer/components/ContentCharts.tsx
packages/frontend/src/features/semanticViewer/components/ContentResults.tsx
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/pages/ViewSqlChart.tsx

feat: sql runner pivot table

---

packages/common/src/compiler/filtersCompiler.ts

Closes: 
Throw a Compile error so it's not treated as an unhandled error and tracked by sentry. 
Sentry Issue: [LIGHTDASH-BACKEND-4A0](https://lightdash.sentry.io/issues/5490360141/?referrer=github_integration)

chore: throw Compile error when filter is invalid

---

packages/backend/src/dbt/profiles.ts
packages/cli/src/dbt/targets/Bigquery/index.ts
packages/cli/src/dbt/targets/Bigquery/serviceAccount.ts
packages/common/src/types/projects.ts
packages/frontend/src/components/ProjectConnection/WarehouseForms/BigQueryForm.tsx
packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.mock.ts
packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.test.ts
packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts

Closes: https://github.com/lightdash/lightdash/issues/11312
Changes:
- support `execution_project` from dbt profile
- add `execution project` input to Bigquery form, under advanced settings
- create Bigquery client with execution project, if available

feat: support Bigquery execution project

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx

Closes: N/A
Now works. 
Try to run a query for the first time and see the results panel opening on query successful. 
https://github.com/user-attachments/assets/96b30ece-5cac-483d-8541-87750b9e685f

fix: open results table on query

---

docs/docs/references/metrics.mdx

This example was confusing to a customer so I'm updating to clarify.

docs: update filter example in metrics ref

---

docs/docs/references/lightdash-cli.mdx

Clarify a few CLI reference items about dbt options

docs: update cli reference doc

---

packages/frontend/src/pages/ViewSqlChart.tsx

fix: sql runner view mode results table

---

packages/frontend/src/features/omnibar/components/Omnibar.tsx

https://lightdash.slack.com/archives/C075JNX28GG/p1725478268373689

fix: clear omnibar on clicking item

---

docs/docs/get-started/setup-lightdash/connect-project.mdx

document changes made in this PR https://github.com/lightdash/lightdash/pull/11374

docs: add BQ execution project

---

packages/backend/src/services/UnfurlService/UnfurlService.ts

Closes: https://github.com/lightdash/lightdash/issues/11430
Before
AFter

fix: screenshot wait for sql runner

---

packages/frontend/src/features/sqlRunner/components/Tables.tsx

Closes:  https://github.com/lightdash/lightdash/issues/11407
Before
[Screencast from 06-09-24 09:46:36.webm](https://github.com/user-attachments/assets/f8474ec1-30e9-4374-8b01-8e3c3db8eaf0)
After:
[Screencast from 06-09-24 09:40:08.webm](https://github.com/user-attachments/assets/c391847a-4d09-498e-a3fd-e7f15bb72327)

fix: duplicated table name sql runner

---

packages/backend/src/models/DashboardModel/DashboardModel.ts

Closes:  https://github.com/lightdash/lightdash/issues/11427
[Screencast from 06-09-24 11:01:08.webm](https://github.com/user-attachments/assets/e3edfbb8-ca58-4bce-bc95-a15562819b83)

fix: rename sql chart dashboard

---

packages/frontend/src/features/semanticViewer/components/ContentCharts.tsx

Closes: https://github.com/lightdash/lightdash/issues/11364

feat: semantic viewer pivot table

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/e2e/cypress/e2e/api/sqlRunner.cy.ts
packages/e2e/cypress/support/warehouses.ts

Closes:  #11424
Closes: https://github.com/lightdash/lightdash/issues/11417

chore: fix e2e sql runner tests

---

packages/common/src/types/field.ts
packages/common/src/visualizations/CartesianChartDataModel.ts

Closes:  https://github.com/lightdash/lightdash/issues/11344
After:

fix: do not remove special chars in tooltip

---

docs/docs/guides/how-to-promote-content.md
packages/backend/src/database/entities/spaces.ts
packages/backend/src/models/SpaceModel.ts
packages/backend/src/services/PromoteService/PromoteService.mock.ts
packages/backend/src/services/PromoteService/PromoteService.test.ts
packages/backend/src/services/PromoteService/PromoteService.ts

Closes: [#11264](https://github.com/lightdash/lightdash/issues/11264)
Create/update content in private spaces.
Note that we don't update space permissions (public/private).

feat: promote content from private spaces

---

packages/frontend/src/features/sqlRunner/components/Tables.tsx

style: fix fontsize sql runner sidebar

---

packages/frontend/src/components/DataViz/VisualizationConfigPanel.tsx

Closes: [#11272](https://github.com/lightdash/lightdash/issues/11272)
Removed copy:

chore: remove copy on viz switcher

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx

Closes: #11271
Some styling improvements reviewed with @PriPatel 
https://github.com/user-attachments/assets/8ff05f50-a146-42f3-9118-c3865ed54e96

style: improve segmented control for sql and chart

---

packages/frontend/src/features/sqlRunner/components/Sidebar.tsx
packages/frontend/src/features/sqlRunner/hooks/useTables.tsx

chore: lint some files

---

packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Closes: 
Allow to change the snowflake SDK traces to debug issues.

chore: add snowflake sdk log level env var

---

packages/backend/src/services/UnfurlService/UnfurlService.ts

fix: unfurl sql runner

---

packages/backend/src/services/ProjectService/ProjectService.ts

Closes: 
At the moment our logs contain the error message but no way to trace it to the code that triggered it.
before:
after:

chore: track error stack on project creation

---

packages/frontend/package.json
yarn.lock

Closes: N/A
Upgrade to latest `@tanstack/react-virtual`.
Tested that virtualization still worked by scrolling through rows on table sql charts

chore: upgrade @tanstack/react-virtual

---

packages/frontend/src/components/DataViz/config/CartesianChartConfiguration.tsx
packages/frontend/src/components/DataViz/config/CartesianChartFieldConfiguration.tsx

Closes: https://github.com/lightdash/lightdash/issues/11433
https://github.com/user-attachments/assets/5eb9e45a-2acd-4b9b-a33c-98e3680c0f31

style: use tabs for chart config

---

packages/backend/src/clients/cube/transformer.ts

Previously we were always passing time dimensions with granularity in both `dimensions` and `timeDimensions`.
Fix was to:
- Pass time dimensions **without** granularity in `dimensions` - this way they show up
- Pass time dimensions **with** granularity in `timeDimensions`
https://github.com/user-attachments/assets/d9cbf89b-e5b1-4aa5-bc23-6a900abd72de

fix: time dimension granularity

---

yarn.lock

fix: update yarn lock after #11525

---

packages/backend/src/generated/swagger.json
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/visualizations/types/index.ts
packages/e2e/cypress/e2e/api/sqlRunner.cy.ts
packages/frontend/src/features/semanticViewer/runners/SemanticViewerResultsRunner.ts
packages/frontend/src/features/sqlRunner/hooks/useSqlChartResults.ts
packages/frontend/src/features/sqlRunner/runners/SqlRunnerResultsRunner.ts
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts
packages/frontend/src/pages/ViewSqlChart.tsx

Closes: 
on a previous PR, I introduced `url` on pivot results, in order to make this more consistent with other endpoints and fix a e2e test , I am renaming this now to `fileUrl`

chore: rename fileUrl sql runner results

---

packages/frontend/src/features/semanticViewer/components/SaveChart/SemanticViewerSaveChartContent.tsx
packages/frontend/src/features/semanticViewer/components/SaveChart/SemanticViewerSaveChartModal.tsx
packages/frontend/src/features/semanticViewer/components/Sidebar.tsx

fix: semantic viewer save chart ux

---

packages/backend/src/services/SemanticLayerService/SemanticLayerService.ts
packages/frontend/src/components/DataViz/hooks/useChartViz.ts
packages/frontend/src/features/semanticViewer/runners/SemanticViewerResultsRunner.ts

Closes: https://github.com/lightdash/lightdash/issues/11560

fix: pivot data table not displaying aggregated columns

---

packages/backend/src/services/SemanticLayerService/Pivoting.ts
packages/frontend/src/features/semanticViewer/components/Content.tsx

fix: pivot on empty results throwing an error

---

packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/DownloadCsvButton.tsx
packages/frontend/src/features/sqlRunner/hooks/useDashboardSqlChart.tsx
packages/frontend/src/features/sqlRunner/hooks/useSqlQueryRun.tsx
packages/frontend/src/pages/ViewSqlChart.tsx

Closes:  https://github.com/lightdash/lightdash/issues/11553
[Screencast from 16-09-24 17:08:49.webm](https://github.com/user-attachments/assets/897be5b9-82d2-4c66-9bfe-7e92e027df8f)

feat: download csv results sql runner edit mode

---

packages/frontend/package.json
yarn.lock

Closes: https://github.com/lightdash/lightdash-internal-work/issues/2052

fix: upgrade posthog frontend

---

packages/frontend/src/features/semanticViewer/components/Content.tsx
packages/frontend/src/features/semanticViewer/components/ContentCharts.tsx
packages/frontend/src/features/semanticViewer/components/ContentResults.tsx
packages/frontend/src/features/semanticViewer/components/RunSemanticQueryButton.tsx
packages/frontend/src/features/semanticViewer/store/semanticViewerSlice.ts

Closes: https://github.com/lightdash/lightdash/issues/11503
Closes: https://github.com/lightdash/lightdash/issues/11504
Closes: https://github.com/lightdash/lightdash/issues/11506
Closes: https://github.com/lightdash/lightdash/issues/11507

fix: semantic viewer minor changes

---

packages/backend/src/models/DashboardModel/DashboardModel.ts
packages/frontend/src/components/DashboardTiles/DashboardSemanticViewerChartTile.tsx

Closes: https://github.com/lightdash/lightdash/issues/11555

fix: semantic viewer chart dashboard tile title

---

packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts

Closes: https://github.com/lightdash/lightdash/issues/11522
views: 
before:
after:

fix: fetch views from snowflake

---

packages/backend/package.json
yarn.lock

Closes: [#11601](https://github.com/lightdash/lightdash/issues/11601)
https://github.com/user-attachments/assets/a3bdf941-9994-42e3-94ea-e22f67b01076

fix: add ts-node as dev dependency for backend

---

packages/frontend/src/features/semanticViewer/components/SidebarViewFieldsGroupItem.tsx

Closes: https://github.com/lightdash/lightdash/issues/11502

feat: time granularity label and separate menu

---

packages/backend/src/controllers/sqlRunnerController.ts
packages/backend/src/database/entities/warehouseAvailableTables.ts
packages/backend/src/database/migrations/20240917083427_add_partition_column_warehouse_table.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/WarehouseAvailableTablesModel/WarehouseAvailableTablesModel.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/warehouse.ts
packages/frontend/src/features/sqlRunner/components/Tables.tsx
packages/frontend/src/features/sqlRunner/hooks/useTables.tsx
packages/warehouses/src/warehouseClients/BigqueryWarehouseClient.ts
packages/warehouses/src/warehouseClients/WarehouseBaseClient.ts

Closes: #11389
[Screencast from 17-09-24 11:24:37.webm](https://github.com/user-attachments/assets/dcb6e824-8690-4ed1-ad4a-9b3ff757c74c)

feat: add partitioning bigquery sql runner

---

packages/common/src/visualizations/types/index.ts
packages/frontend/src/components/DataViz/visualizations/Table.tsx
packages/frontend/src/features/semanticViewer/api/hooks.ts
packages/frontend/src/features/semanticViewer/components/Content.tsx
packages/frontend/src/features/semanticViewer/components/ContentCharts.tsx
packages/frontend/src/features/semanticViewer/components/ContentResults.tsx
packages/frontend/src/features/semanticViewer/components/RunSemanticQueryButton.tsx
packages/frontend/src/features/semanticViewer/runners/SemanticViewerResultsRunner.ts
packages/frontend/src/features/semanticViewer/store/selectors.ts
packages/frontend/src/features/semanticViewer/store/semanticViewerSlice.ts

Closes: #11498
https://github.com/user-attachments/assets/a20fd968-9370-4202-aeb2-c6a8ec187074

feat: sorts on table headers

---

packages/backend/src/models/UserModel.ts
packages/common/src/types/errors.ts
packages/frontend/src/features/users/hooks/useLogin.ts
packages/frontend/src/hooks/health/useHealth.tsx
packages/frontend/src/hooks/useQueryError.ts

fix: fix invalid user redirection

---

packages/frontend/src/components/common/ResourceView/ResourceActionHandlers.tsx

fix: move to new space

---

packages/backend/src/services/UserService.ts

Closes:  https://github.com/lightdash/lightdash-internal-work/issues/2071
Before:
AFter:

fix: delete users from orgs

---

packages/frontend/src/components/ChartDownload.tsx
packages/frontend/src/components/DataViz/visualizations/ChartView.tsx
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/Download/ChartDownload.tsx
packages/frontend/src/features/sqlRunner/components/Download/ResultsDownload.tsx
packages/frontend/src/features/sqlRunner/hooks/useDownloadResults.tsx
packages/frontend/src/pages/ViewSqlChart.tsx

Closes: [#11529](https://github.com/lightdash/lightdash/issues/11529)
Allows downloading charts as image,pdf,json.etc - uses the same component as the Explorer
Demo: 
https://github.com/user-attachments/assets/53d131c8-f5e2-4a4a-aab1-771f60dcd61b

feat: allow download charts as image,pdf

---

packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: #8627
- [✅] I have manually tested the changes in the preview environment
- [✅] I have reviewed the code
- [✅] I understand that "request changes" will block this PR from merging

fix: wait for valid echarts options before returning cartesian config

---

packages/backend/src/generated/swagger.json
packages/backend/src/models/SearchModel/index.ts
packages/backend/src/models/SpaceModel.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/search.ts
packages/frontend/src/components/common/ResourceView/resourceUtils.ts
packages/frontend/src/features/omnibar/components/OmnibarFilters.tsx
packages/frontend/src/features/omnibar/components/OmnibarItemIcon.tsx
packages/frontend/src/features/omnibar/utils/getSearchItemLabel.ts
packages/frontend/src/features/omnibar/utils/getSearchItemMap.ts
packages/frontend/src/providers/TrackingProvider.tsx

feat: show semantic viewer charts in search and chart lists

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/services/DashboardService/DashboardService.ts
packages/backend/src/services/SavedChartsService/SavedChartService.ts

chore: add name and description to analytic events

---

packages/backend/src/projectAdapters/dbtNoneCredentialsProjectAdapter.ts
packages/backend/src/scheduler/SchedulerTask.ts
packages/backend/src/services/CsvService/CsvService.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/warehouse.ts

Closes:  #10009
- [✅] I have manually tested the changes in the preview environment
- [✅] I have reviewed the code
- [✅] I understand that "request changes" will block this PR from merging

fix: Require query tags for all warehouse queries

---

packages/frontend/src/features/semanticViewer/components/Sidebar.tsx

fix: semantic viewer field select scroll overflow

---

packages/frontend/src/features/semanticViewer/components/FiltersModal/Filter/MultiStringFilter.tsx
packages/frontend/src/features/semanticViewer/components/FiltersModal/Filter/TimeFilter.tsx
packages/frontend/src/features/semanticViewer/components/FiltersModal/Filter/index.tsx

Closes: https://github.com/lightdash/lightdash/issues/11685
Closes: https://github.com/lightdash/lightdash/issues/11438
Bonus: fixed text alignment inconsistencies
fyi, this padding should be enough on all fonts/os variations I think:

fix: semantic viewer filter ui bugs

---

packages/backend/src/models/SpaceModel.ts
packages/backend/src/services/PromoteService/PromoteService.test.ts
packages/backend/src/services/PromoteService/PromoteService.ts

fix: force same slug on spaces in different project

---

packages/e2e/cypress/e2e/app/sqlRunnerNew.cy.ts
packages/frontend/src/components/DataViz/VisualizationSwitcher.tsx
packages/frontend/src/components/DataViz/visualizations/ChartView.tsx
packages/frontend/src/features/sqlRunner/components/Header/HeaderEdit.tsx
packages/frontend/src/features/sqlRunner/components/SqlQueryHistory.tsx

Closes: #11679 
1. Should verify that the query is autocompleted, run, and the results are displayed
- Checks autocomplete functionality
- Verifies query execution and result display
- Confirms query saving in draft history
- Tests query replacement with new table suggestion
2. Should verify that the chart is displayed
- Checks initial disabled state of Run query button
- Verifies query execution
- Tests chart configuration and display
- Validates adding new series to the chart
- Checks grouping functionality
- Verifies chart not displayed with incomplete configuration
3. Should verify that all chart types are displayed
- Tests display of various chart types:
- Table
- Line chart
- Pie chart
- Bar chart
4. Should save a chart
- Verifies chart saving process
- Checks view mode after saving …

test: add sql runner e2e tests [postgres warehouse only]

---

packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNodeActions.tsx

Closes: #11328
Added new options for duplicate metrics and dimension like 
Multiple Custom Dimensions and metrics added:

feat: Duplicate metrics dimensions

---

packages/backend/src/controllers/v2/SemanticLayerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/SavedSemanticViewerChartModel.ts
packages/backend/src/services/SavedSemanticViewerChartService/SavedSemanticViewerChartService.ts
packages/backend/src/services/SemanticLayerService/SemanticLayerService.ts
packages/common/src/types/errors.ts
packages/frontend/src/Routes.tsx
packages/frontend/src/components/DashboardTiles/DashboardSemanticViewerChartTile.tsx
packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx
packages/frontend/src/features/semanticViewer/api/hooks.ts
packages/frontend/src/features/semanticViewer/api/requests.ts
packages/frontend/src/features/semanticViewer/components/Header/HeaderView.tsx
packages/frontend/src/features/semanticViewer/components/SaveChart/SemanticViewerSaveChartModal.tsx
packages/frontend/src/features/semanticViewer/components/Sidebar.tsx
packages/frontend/src/pages/SemanticViewerEdit.tsx
packages/frontend/src/pages/SemanticViewerView.tsx

Missing feature from: #11659 
adds slug support for urls

feat: semantic viewer slug

---

packages/frontend/src/features/semanticViewer/store/semanticViewerSlice.ts

Closes: https://github.com/lightdash/lightdash/issues/11669

fix: semantic viewer remove sorted field

---

packages/frontend/src/features/semanticViewer/components/Content.tsx
packages/frontend/src/features/semanticViewer/components/Header/HeaderView.tsx
packages/frontend/src/features/semanticViewer/components/Modals/DeleteSemanticViewerChartModal.tsx
packages/frontend/src/features/semanticViewer/components/Modals/SaveSemanticViewerChartModal.tsx
packages/frontend/src/features/semanticViewer/components/Modals/index.ts
packages/frontend/src/features/semanticViewer/components/SaveChart/index.ts
packages/frontend/src/features/semanticViewer/components/SaveSemanticViewerChart.tsx
packages/frontend/src/features/semanticViewer/components/Sidebar.tsx

Closes: https://github.com/lightdash/lightdash/issues/11725

feat: semantic viewer should redirect to view mode after save

---

packages/frontend/src/components/DashboardTiles/AddTileButton.tsx
packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
packages/frontend/src/pages/Dashboard.tsx

Closes: https://github.com/lightdash/lightdash/issues/11649
view and edit mode screenshots:

feat: semantic viewer disable dashboard features

---

packages/frontend/src/components/SettingsSemanticLayer/DbtSemanticLayerForm.tsx

fix: deduplicate select domains

---

packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/SemanticLayerService/SemanticLayerService.ts
packages/common/src/types/semanticLayer.ts
packages/frontend/src/components/NavBar/ExploreMenu.tsx
packages/frontend/src/features/semanticViewer/api/hooks.ts
packages/frontend/src/pages/SemanticViewerEdit.tsx
packages/frontend/src/pages/Settings.tsx

Closes: https://github.com/lightdash/lightdash/issues/11735

feat: semantic viewer menu link based on connection status

---

packages/backend/src/controllers/sqlRunnerController.ts
packages/common/src/types/sqlRunner.ts
packages/frontend/src/features/sqlRunner/components/SaveCustomViewModal.tsx
packages/frontend/src/features/sqlRunner/hooks/useGithubDbtWriteBack.tsx

Closes: [#11720](https://github.com/lightdash/lightdash/issues/11720)
adds `useGithubDbtWriteBack`
makes small fix to snake case name on file creation preview
opens PR in new tab
https://github.com/user-attachments/assets/c0f1826c-6191-4e56-aaf5-59eedf1cdd3a

feat: allow creating PR on custom view modal

---

packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/controllers/githubController.ts

Closes: 
Removes hard coded lightdash app name

chore: env variable for github app name

---

packages/frontend/src/features/sqlRunner/components/Header/HeaderCreate.tsx

Closes: https://github.com/lightdash/lightdash/issues/11497

style: change header create button style

---

packages/frontend/src/components/SettingsSemanticLayer/index.tsx

Relates to: [#11743](https://github.com/lightdash/lightdash/issues/11743)

chore: add copy for semantic layer settings

---

packages/backend/src/clients/cube/CubeClient.ts
packages/backend/src/clients/dbtCloud/DbtCloudGraphqlClient.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/frontend/src/components/NavBar/ExploreMenu.tsx

feat: semantic viewer menu copy

---

packages/frontend/src/components/DataViz/visualizations/ChartView.tsx
packages/frontend/src/pages/SemanticViewerView.tsx

Closes: #11738 
error state:
chart load
https://github.com/user-attachments/assets/69541ec9-7883-4649-9d10-6cd4515a9589
table load
https://github.com/user-attachments/assets/79d23ca3-2262-455c-ba2b-6bc6a6b99bd2

feat: semantic layer view mode load and error states

---

packages/common/src/types/semanticLayer.ts
packages/frontend/src/features/semanticViewer/api/hooks.ts
packages/frontend/src/features/semanticViewer/store/semanticViewerSlice.ts
packages/frontend/src/pages/SemanticViewerEdit.tsx

fix: semantic viewer edit mode result initialization

---

packages/backend/src/controllers/projectController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/frontend/src/components/SettingsSemanticLayer/CubeSemanticLayerForm.tsx
packages/frontend/src/components/SettingsSemanticLayer/DbtSemanticLayerForm.tsx
packages/frontend/src/components/SettingsSemanticLayer/index.tsx
packages/frontend/src/hooks/useProject.ts

Closes: #11624 
- Adds form for semantic layer connection
- Adds delete button to remove a semantic layer connection

feat: add csl form

---

packages/backend/src/clients/github/Github.ts

fix: github base64 key

---

packages/backend/src/services/GitIntegrationService/GitIntegrationService.ts

fix: friendly name yml

---

packages/frontend/src/components/UserSettings/GithubSettingsPanel/index.tsx
packages/frontend/src/features/sqlRunner/components/CreateVirtualViewModal.tsx
packages/frontend/src/features/sqlRunner/hooks/useCustomExplore.tsx

chore: update copy when creating virtual view

---

packages/frontend/src/components/UserSettings/GithubSettingsPanel/index.tsx
packages/frontend/src/features/sqlRunner/components/Header/HeaderCreate.tsx

Closes: https://github.com/lightdash/lightdash/issues/11765
For testing, you can force this error by blocking the /list endpoint in dev tools.

fix: disable github button if not enabled

---

packages/backend/src/services/GitIntegrationService/GitIntegrationService.ts

Closes:  https://github.com/lightdash/lightdash/issues/11788

fix: write back GitHub path

---

packages/frontend/src/features/semanticViewer/components/RunSemanticQueryButton.tsx
packages/frontend/src/features/semanticViewer/store/semanticViewerSlice.ts

feat: show limit warning on button

---

packages/frontend/src/components/SettingsSemanticLayer/index.tsx

chore: add learn more link

---

packages/warehouses/package.json
packages/warehouses/src/warehouseClients/SnowflakeWarehouseClient.ts
yarn.lock

Closes: https://github.com/lightdash/lightdash-internal-work/issues/2098
test-cli
test-frontend
test-backend

fix: bump snowflake sdk to 14

---

packages/cli/tsconfig.json

Closes: 
internal thread: https://lightdash.slack.com/archives/C02GQKJK84Q/p1728035250733979

feat: cli modern build

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/config/parseConfig.ts

Closes:  https://github.com/lightdash/lightdash/issues/11598
Before:
Now:
No errors

chore: allow rudderstack key empty

---

packages/cli/src/handlers/deploy.ts

fix: remove double slashes CLI

---

packages/cli/package.json
yarn.lock

Closes: https://github.com/lightdash/lightdash/issues/11797

fix: lightdash cli erroring in github ci

---

packages/cli/package.json
yarn.lock

Related to: https://github.com/lightdash/lightdash/issues/11797
more context on why this happened: https://github.com/actions/toolkit/issues/1841

fix: pin github actions core version

---

packages/frontend/package.json
packages/frontend/src/features/sqlRunner/hooks/useDownloadResults.tsx
yarn.lock

Closes:  #11813
How to replicate 
> select customer_id, array_agg(order_id) FROM "postgres"."jaffle"."orders" group by customer_id
Before
After:

fix: sql runner csv comma stringify

---

packages/backend/src/controllers/sqlRunnerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/index.ts
packages/common/src/types/featureFlags.ts
packages/common/src/types/sqlRunner.ts
packages/common/src/utils/virtualView.ts
packages/frontend/src/features/sqlRunner/components/CreateVirtualViewModal.tsx
packages/frontend/src/features/sqlRunner/components/Header/HeaderCreate.tsx
packages/frontend/src/features/sqlRunner/hooks/useVirtualView.tsx

Closes: N/A
Replace references to custom explores with similar wording to `virtual views`

refactor: replace custom explore references with virtual view

---

packages/cli/package.json
yarn.lock

Closes: 
why, we pinned github actions to a certain version because of an ongoing bug which is fixed in the latest version now: https://github.com/actions/toolkit/issues/1841#issuecomment-2394724989

chore: github actions unpin version

---

packages/backend/src/controllers/githubController.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/GithubAppService/GithubAppService.ts
packages/frontend/src/components/UserSettings/GithubSettingsPanel/index.tsx

Closes: https://github.com/lightdash/lightdash/issues/11825

fix: show errors to github config page

---

packages/backend/src/controllers/githubController.ts
packages/backend/src/services/GithubAppService/GithubAppService.ts
packages/frontend/src/components/UserSettings/GithubSettingsPanel/index.tsx

Closes:  #11827
Now deleting and reinstalling, also deletes the installation Id on github, so you don't see `configure` anymore when installing it twice...

fix: improve git delete flow

---

packages/backend/src/clients/github/Github.ts
packages/backend/src/services/GitIntegrationService/GitIntegrationService.ts
packages/frontend/src/features/sqlRunner/hooks/useGithubDbtWriteBack.tsx

fix: check if file exists in github

---

packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
packages/frontend/src/features/sqlRunner/components/EditVirtualViewModal.tsx
packages/frontend/src/features/sqlRunner/components/Header/HeaderVirtualView.tsx
packages/frontend/src/features/sqlRunner/utils/compareColumns.ts
packages/frontend/src/pages/SqlRunnerNew.tsx

Closes: #11795
Alerts the user when there are changes to the schema when editing their virtual view
This PR also moves the modal to the features/sqlRunner to be easier to manage
Demo:
https://github.com/user-attachments/assets/4db061af-3aab-4695-a796-91e562654d78

feat: alert users on changes to virtual view

---

packages/frontend/src/features/sqlRunner/components/Header/HeaderCreate.tsx

fix: disable write back if project is not github

---

packages/backend/src/services/AnalyticsService/AnalyticsService.ts
packages/backend/src/services/OrganizationService/OrganizationService.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/SavedSqlService/SavedSqlService.ts
packages/backend/src/services/UserService.ts

Closes: https://github.com/lightdash/lightdash-internal-work/issues/2073

fix: add missing subject to casl methods

---

packages/backend/src/controllers/sqlRunnerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
packages/frontend/src/features/sqlRunner/components/DeleteVirtualViewModal.tsx
packages/frontend/src/features/sqlRunner/hooks/useVirtualView.tsx

Closes: #11847
Allows deletion of virtual views
This PR does not include the nice-to-haves which can be covered here: https://github.com/lightdash/lightdash/issues/11845
https://github.com/user-attachments/assets/1d3f085c-8e0c-43c7-acf1-1daea8e70717

feat: allow deleting virtual views

---

packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts

Closes: #11855 
**Before**
https://github.com/user-attachments/assets/e81a0da2-b9e2-4dd8-af33-0230d7dc21fc
**After**
https://github.com/user-attachments/assets/1ffe1c25-bfd3-4cbc-a90f-8b28fc48979b

fix: look for materialized view columns in pg_attribute and pg_matviews

---

packages/backend/src/controllers/sqlRunnerController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/utils/virtualView.ts
packages/frontend/src/features/sqlRunner/components/Header/HeaderVirtualView.tsx
packages/frontend/src/features/sqlRunner/hooks/useVirtualView.tsx

Closes:  https://github.com/lightdash/lightdash/issues/11796
[Screencast from 08-10-24 16:20:45.webm](https://github.com/user-attachments/assets/4e15ad35-a736-4c2d-b09c-05c846248daa)

feat: rename virtual explore

---

packages/backend/src/clients/cube/transformer.ts
packages/backend/src/clients/dbtCloud/DbtCloudGraphqlClient.ts
packages/backend/src/clients/dbtCloud/transformer.ts
packages/common/src/types/semanticLayer.ts
packages/frontend/src/features/semanticViewer/components/Content.tsx
packages/frontend/src/features/semanticViewer/components/ContentResults.tsx
packages/frontend/src/features/semanticViewer/components/SqlViewer.tsx

Closes: #11365 
https://github.com/user-attachments/assets/7a5a3024-ece3-4cda-bd46-5e863eda9560

fix: show semantic layer results and sql errors in suboptimal state

---

docker-compose.yml

chore: add posthog to compose

---

packages/backend/src/controllers/projectController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/ProjectModel/ProjectModel.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/common/src/types/projects.ts
packages/frontend/src/components/SettingsSemanticLayer/CubeSemanticLayerForm.tsx
packages/frontend/src/components/SettingsSemanticLayer/DbtSemanticLayerForm.tsx
packages/frontend/src/components/SettingsSemanticLayer/index.tsx
packages/frontend/src/hooks/useProject.ts

fix: make update accept partial

---

packages/backend/src/services/ValidationService/ValidationService.ts
packages/common/src/utils/virtualView.ts
packages/frontend/src/features/sqlRunner/components/Header/HeaderVirtualView.tsx
packages/frontend/src/hooks/validation/useValidation.ts

Closes: https://github.com/lightdash/lightdash/issues/11845
[Screencast from 09-10-24 14:10:21.webm](https://github.com/user-attachments/assets/8397883d-c91c-4bc1-a525-3e853b0fe9e7)

feat: validate before editing virtual view

---

packages/backend/src/services/AnalyticsService/AnalyticsService.ts

After https://github.com/lightdash/lightdash/pull/11804 user-activity dashboard fails with 403 forbidden error

chore: add organization to user-analytics dashboard

---

render.yaml

fix: add previewPlan to render yml

---

packages/warehouses/src/warehouseClients/PostgresWarehouseClient.test.ts
packages/warehouses/src/warehouseClients/PostgresWarehouseClient.ts

fix: do not use server_version_num

---

packages/frontend/src/features/virtualView/components/HeaderVirtualView.tsx

Closes: N/A
- Always runs query before getting validation
- Skips validation & column diffing if the user has already accepted/reviewing the changes that will happen if they edit the virtual view
recording:
https://github.com/user-attachments/assets/f6bc9dfd-a37e-48c8-876e-27139198d9f1

fix: always run query before validating diffs

---

docs/docs/references/dbt-semantic-layer.mdx
docs/docs/references/dimensions.mdx
docs/docs/references/user-attributes.mdx

Closes: [#11878](https://github.com/lightdash/lightdash/issues/11878)

chore: update docs column filtering

---

packages/backend/src/services/ProjectService/ProjectService.ts
packages/warehouses/src/warehouseClients/DatabricksWarehouseClient.ts

Closes: https://github.com/lightdash/lightdash/issues/11574
Before:
After:

fix: databricks sql runner catalog

---

packages/frontend/src/features/virtualView/components/EditVirtualViewModal.tsx
packages/frontend/src/features/virtualView/components/HeaderVirtualView.tsx
packages/frontend/src/pages/SqlRunnerNew.tsx

Closes: #11907
See loom video in ticket ⬆️  as a _before_
and after:
https://github.com/user-attachments/assets/29dc6c65-0e19-4409-923f-2724081d925f

fix: display label in text input when editing virtual view

---

packages/backend/src/services/UserService.ts

Closes:  #11793
Before:
After:

fix: delete user on cancel registration

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/clients/cube/CubeClient.ts
packages/backend/src/clients/dbtCloud/DbtCloudGraphqlClient.ts
packages/backend/src/generated/swagger.json
packages/backend/src/services/SemanticLayerService/SemanticLayerService.ts
packages/common/src/types/analytics.ts
packages/common/src/types/semanticLayer.ts

- Adds `query_executed` event with `semanticViewer` context

chore: add semantic viewer query_executed event

---

packages/warehouses/src/warehouseClients/TrinoWarehouseClient.ts

Closes:  https://github.com/lightdash/lightdash/issues/11865

fix: trino sql runner tables

---

packages/common/src/types/featureFlags.ts
packages/frontend/src/features/sqlRunner/components/Header/HeaderCreate.tsx

feat: remove feature flag save-custom-explore-from-sql-runner

---

packages/frontend/src/features/virtualView/components/EditVirtualViewModal.tsx

Closes: [#11905](https://github.com/lightdash/lightdash/issues/11905)
Demo in comment: 
https://github.com/lightdash/lightdash/issues/11905#issuecomment-2411535818
Changed copy & discard button color
To test:
- create virtual view
- start exploring (adding a dim)
- Click to edit a virtual view.

style: change copy and color button of edit virtual view modal

---

packages/backend/src/postHog.ts

chore: debug posthog client

---

docker/docker-compose.dev.yml
packages/backend/src/config/lightdashConfig.mock.ts
packages/backend/src/config/parseConfig.ts
packages/backend/src/controllers/githubController.ts

Closes:  https://github.com/lightdash/lightdash-internal-work/issues/2145
This is based on this nginx config (deployed on render)  https://github.com/lightdash/github-nginx-proxy/blob/master/nginx.conf
notice how the mapping allow us to configure different testing environments, while leaving the rest of the domains for lightdash.cloud
Demo in localhost with `export GITHUB_REDIRECT_DOMAIN='localhost'`
[Screencast from 16-10-24 09:46:37.webm](https://github.com/user-attachments/assets/9cda12d3-eb4f-47f8-9ffd-99ba7853bda9)

feat: github proxy callback

---

packages/backend/src/controllers/githubController.ts

Closes:  https://github.com/lightdash/lightdash-internal-work/issues/2149
With this nginx config
https://github.com/lightdash/github-nginx-proxy/blob/dev/nginx.conf

fix: add nanoid to state in github oauth

---

docs/docs/references/dbt-write-back.mdx
docs/docs/references/roles.mdx
docs/docs/references/sql-runner.mdx
docs/docs/references/virtual-views.mdx
packages/backend/src/services/CsvService/CsvService.test.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/ServiceRepository.ts
packages/common/src/authorization/organizationMemberAbility.test.ts
packages/common/src/authorization/organizationMemberAbility.ts
packages/common/src/authorization/projectMemberAbility.test.ts
packages/common/src/authorization/projectMemberAbility.ts
packages/e2e/cypress/e2e/api/organizationPermissions.cy.ts

Closes:  [11318](https://github.com/lightdash/lightdash/issues/11318)
Interactive viewers can't create projects but they can create preview projects
copied content
Copy same users / groups in the previevw project 
Because of that :point_up: we now can copy also private spaces, withouth letting the user access those
Can't create a default project as org editor/project developer: 
>         console.log('createWithoutCompile', organizationUuid, data.upstreamProjectUuid, data.type)

feat: interactive viewers can create previews

---

docs/sidebars.js

adds custom fields back into sidebar

docs: adds custom fields docs back into docs sidebar

---

packages/backend/src/services/CommentService/CommentService.ts
packages/common/src/types/featureFlags.ts
packages/frontend/src/features/comments/hooks/useDashboardCommentsCheck.ts
packages/frontend/src/pages/Dashboard.tsx

Closes: #11928 
adds feature flag to disable dashboard comments feature.
posthog dev: https://us.posthog.com/project/39172/feature_flags/76769
posthog prod: https://us.posthog.com/project/16377/feature_flags/76770

feat: feature flag for dashboard comments

---

packages/backend/src/clients/dbtCloud/DbtCloudGraphqlClient.ts
packages/frontend/src/features/semanticViewer/components/SidebarViewFields.tsx

To reproduce set the `environmentId` in the semantic layer connection settings to an incorrect environment

fix: fix field errors for semantic viewer

---

packages/frontend/src/components/SettingsSemanticLayer/DbtSemanticLayerForm.tsx

chore: update dbt service token tooltip

---

packages/e2e/cypress/e2e/api/sqlRunner.cy.ts
packages/e2e/cypress/support/warehouses.ts

Closes:  https://github.com/lightdash/lightdash-internal-work/issues/2138

chore: add databricks sql runner tests

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/controllers/githubController.ts
packages/backend/src/services/GitIntegrationService/GitIntegrationService.ts
packages/backend/src/services/GithubAppService/GithubAppService.ts
packages/backend/src/services/ServiceRepository.ts

chore: Analytic events write back + refactor

---

packages/backend/src/services/CommentService/CommentService.ts

Closes: https://github.com/lightdash/lightdash/issues/12000
sentry error: https://lightdash.sentry.io/issues/6002036953/?alert_rule_id=9333608&alert_type=issue&environment=cloud_beta&notification_uuid=b2f6601c-1303-4e0a-a82a-370414952373&project=5959292&referrer=issue_alert-slack

fix: comment service throwing

---

packages/frontend/src/components/DashboardTabs/AddTabModal.tsx

Closes: 
https://github.com/lightdash/lightdash/issues/11214
Updated the new tab modal to use the 'sm' size as suggested.

feat: change add tab modal to use a small size

---

packages/frontend/src/features/sqlRunner/components/Header/HeaderCreate.tsx

Closes:  #12013
Keep the flag for custom metrics and dimensions

fix: remove custom sql feature flag from write back

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/services/GithubAppService/GithubAppService.ts
packages/frontend/src/components/UserSettings/GithubSettingsPanel/index.tsx

Closes:  https://github.com/lightdash/lightdash/issues/11987
CLicking on pending approval takes it to the setup page, where they can cancel the request 
[Screencast from 21-10-24 10:57:41.webm](https://github.com/user-attachments/assets/713dfd7b-fae3-4d1a-963b-eb7f23cc028c)

fix: GitHub app admin install

---

packages/frontend/src/features/semanticViewer/components/SaveSemanticViewerChart.tsx
packages/frontend/src/pages/SemanticViewerEdit.tsx

Closes: https://github.com/lightdash/lightdash/issues/12017

fix: update saved semantic viewer

---

packages/backend/src/clients/Slack/SlackClient.ts

Closes:   #12023
Thread: https://lightdash.slack.com/archives/C0234T34WEQ/p1729527892538059?thread_ts=1729525337.587039&cid=C0234T34WEQ

chore: improve lightdash slack error type

---

docs/docs/guides/how-to-embed-content.mdx

docs: update embed documentation

---

packages/frontend/src/components/DashboardTiles/DashboardMinimalDownloadCsv.tsx

chore: update copy download csv

---

docs/docs/references/lightdash-cli.mdx

Add example to CLI docs thanks to customer feedback 
Example added to `lightdash generate-exposure` CLI reference doc

docs: add cli example

---

packages/frontend/src/components/CustomSqlPanel/CustomSqlPanel.tsx

Closes:   #12050
Refetches every time the user goes into this settings panel

fix: refetch on mount custom metrics

---

packages/common/src/visualizations/CartesianChartDataModel.ts

Closes: https://github.com/lightdash/lightdash/issues/11937
old:
new:

fix: timezone offsetting in the new chartviz tooltip

---

docker/docker-compose.dev.yml
packages/frontend/src/features/sync/components/SyncModal.tsx
packages/frontend/src/features/sync/components/SyncModalForm.tsx
packages/frontend/src/features/sync/components/SyncModalView.tsx

feat: add time zone to gsheets sync

---

packages/common/src/visualizations/TableDataModel.ts
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx
packages/frontend/src/features/sqlRunner/components/Download/ResultsDownloadFromData.tsx
packages/frontend/src/features/sqlRunner/components/Download/ResultsDownloadFromUrl.tsx
packages/frontend/src/features/sqlRunner/hooks/useDownloadResults.tsx
packages/frontend/src/pages/ViewSqlChart.tsx

Closes:  #12065
Kept existing behaviour for cartesian charts (with pivot url)

fix: download results from data for sql table chart

---

packages/backend/src/database/entities/scheduler.ts
packages/backend/src/models/SchedulerModel/index.ts

Closes: #12103 
To Reproduce:
1. Go to a dashboard
2. Create an alert using the project default time zone
3. Go to project settings
4. Change the time zone

fix: update only cron in bulk cron update

---

packages/frontend/src/components/NavBar/DashboardExplorerBanner.tsx

Closes: https://github.com/lightdash/lightdash/issues/12055
[Screencast from 25-10-24 11:23:07.webm](https://github.com/user-attachments/assets/8e4c389a-c6f7-423a-8592-d56e07a92d35)

fix: do not clear dashboard storage on cancel

---

packages/backend/src/models/ShareModel.ts

Closes: #12116 
Handle undefined row.

fix: handle error when share link does not exist

---

packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts

Closes: #12108 
`y` is possibly undefined so we need to check it before accessing the value inside

fix: check if y is defined

---

packages/backend/src/controllers/projectController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json

Closes: NA
I added `@Middlewares` to `updateSchedulerSettings` so that we can call the API.
When I tried the API with a curl command like below, I got the error message `Something went wrong`.
```shell
export LIGHTDASH_API_KEY="..."
export PROJECT_UUID="..."
curl -X PATCH \
"https://xxx.lightdash.cloud/api/v1/projects/${PROJECT_UUID}/schedulerSettings" \
-H "Authorization: ApiKey ${LIGHTDASH_API_KEY}" \
-H "Content-Type: application/json" \
-d '{"schedulerTimezone": "UTC"}'
{"status":"error","error":{"statusCode":500,"name":"UnexpectedServerError","message":"Something went wrong.","data":{},"id":"f9e47f3929e24bbc9888bfa419127e5e"}}
```

fix: Add `@Middlewares` to `updateSchedulerSettings`

---

packages/frontend/src/hooks/dashboard/useDashboardRefresh.ts

Closes: #12111 
Handle undefined queryKey.

fix: handle undefined queryKey

---

packages/backend/src/database/entities/savedSql.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/SavedSqlModel.ts
packages/common/src/types/semanticLayer.ts
packages/common/src/types/sqlRunner.ts
packages/common/src/visualizations/types/index.ts
packages/frontend/src/components/DataViz/transformers/getChartConfigAndOptions.ts

Quick cleanup I noticed in the new viz stack. Remove duplicate type.

chore: remove duplicate viz config type

---

packages/backend/src/models/UserModel.ts
packages/backend/src/services/UserService.test.ts
packages/backend/src/services/UserService.ts

Closes: https://github.com/lightdash/lightdash/issues/12097
Sometimes we allow user registering when they are in single org instances, and without invitations. We can detect these cases earlier on and avoid creating the user . 
This not only improves the overall UX for the user registering, but also, it reduces errosr in the long term. We recently discovered  some of these users were created some time ago (they got an error, and they forgot about it), and then, when they try to register again, their user is already taken. 
My fix is already taken into account special register cases like `whitelisted domains`, empty user/orgs, and enabled OIDC for SSO. 
Before:
[Screencast from 25-10-24 13:53:07.webm](https://github.com/user-attachments/assets/c3d3fa5a-6490-4669-aba3-4a7c84567f00)
After: …

fix: improve ux for registering users

---

packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceAddUser.tsx
packages/frontend/src/components/common/ShareSpaceModal/Utils.ts

Closes:  https://github.com/lightdash/lightdash/issues/12120
Before:
[Screencast from 28-10-24 09:58:26.webm](https://github.com/user-attachments/assets/061553ac-0643-4750-8871-6516495dc377)
Now:

fix: private space filter user email

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/services/DashboardService/DashboardService.ts
packages/backend/src/services/SavedChartsService/SavedChartService.ts

Closes:  https://github.com/lightdash/lightdash/issues/11972

fix: analytic event virtual view saved chart

---

packages/frontend/src/components/DataViz/visualizations/ChartDataTable.tsx
packages/frontend/src/components/DataViz/visualizations/ChartView.tsx
packages/frontend/src/components/DataViz/visualizations/Table.tsx
packages/frontend/src/features/sqlRunner/components/ContentPanel.tsx

Closes:  https://github.com/lightdash/lightdash-internal-work/issues/2167
Before:
After:
sql runner chart 
sql runner chart results 
sql runner chart as table

fix: add classnames to sql runner tables

---

packages/backend/src/controllers/catalogController.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/common/src/index.ts
packages/common/src/types/catalog.ts
packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
packages/frontend/src/features/metricsCatalog/hooks/useMetricsCatalog.tsx

- Allows infinite scroll of metrics in metrics table
- displays feedback to user.
https://github.com/user-attachments/assets/591a38d8-98ef-4979-abb5-e68007663a8e

feat: add infinite scroll to metrics table

---

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
packages/frontend/src/features/metricsCatalog/hooks/useMetricsCatalog.tsx

Allows searching the metrics table by description and/or name
Demo
https://github.com/user-attachments/assets/61734baa-e72d-4f91-9412-43da84ce1f0b

feat: allow searching metrics table

---

packages/backend/src/analytics/LightdashAnalytics.ts
packages/backend/src/models/SchedulerModel/index.ts
packages/backend/src/services/DashboardService/DashboardService.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/SavedChartsService/SavedChartService.ts
packages/backend/src/services/SchedulerService/SchedulerService.ts
packages/common/src/utils/scheduler.ts
packages/frontend/src/components/common/TimeZonePicker/index.tsx

Closes:  https://github.com/lightdash/lightdash/issues/12075

chore: add analytic events to scheduler timezone changes

---

packages/backend/src/controllers/organizationController.ts
packages/backend/src/database/entities/groups.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/GroupsModel.ts
packages/backend/src/services/OrganizationService/OrganizationService.ts
packages/common/src/index.ts
packages/common/src/types/groups.ts
packages/e2e/cypress/e2e/api/groups.cy.ts
packages/frontend/src/components/ProjectAccess/ProjectAccess.tsx
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/GroupsView.tsx
packages/frontend/src/components/UserSettings/UsersAndGroupsPanel/UsersView.tsx
packages/frontend/src/components/common/PaginateControl.tsx
packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceAddUser.tsx
packages/frontend/src/components/common/ShareSpaceModal/ShareSpaceUserList.tsx
packages/frontend/src/components/common/ShareSpaceModal/index.tsx
packages/frontend/src/components/common/Table/TablePagination/index.tsx
packages/frontend/src/features/projectGroupAccess/components/ProjectGroupAccess.tsx
packages/frontend/src/hooks/useOrganizationGroups.ts
packages/frontend/src/hooks/useOrganizationUsers.ts

Closes: [#12006](https://github.com/lightdash/lightdash/issues/12006)
To test, apply the following `diff` and re-run `sh ./scripts/seed-lightdash.sh` - this will add 10k users to the database
```diff
diff --git a/packages/backend/src/database/seeds/development/01_initial_user.ts b/packages/backend/src/database/seeds/development/01_initial_user.ts
index 395333e8b..16b97cbc5 100644
--- a/packages/backend/src/database/seeds/development/01_initial_user.ts
+++ b/packages/backend/src/database/seeds/development/01_initial_user.ts
@@ -20,6 +20,7 @@ import {
import bcrypt from 'bcrypt';
import { Knex } from 'knex';
import path from 'path';
+import { v4 } from 'uuid';
import { lightdashConfig } from '../../../config/lightdashConfig';
import { ProjectModel } from …
```

fix: paginate space share

---

packages/frontend/src/types/@tanstack-react-table.d.ts
yarn.lock

fix: building with tanstack react table type

---

packages/backend/src/services/OrganizationService/OrganizationService.ts

fix: group members map unsafe access

---

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
packages/frontend/src/features/metricsCatalog/hooks/useMetricsCatalog.tsx

Can sort by: 
`name`
by `asc`, `desc`, and no order at all
demo:
https://github.com/user-attachments/assets/8a7eb0b6-8203-4a94-8251-7686c6f94935

feat: allow sorting by name in metrics catalog

---

packages/frontend/src/features/sqlRunner/components/Header/HeaderCreate.tsx
packages/frontend/src/features/sqlRunner/store/sqlRunnerSlice.ts
packages/frontend/src/pages/SqlRunnerNew.tsx

…reate.tsx
Closes:   [#12092](https://github.com/lightdash/lightdash/issues/12092)
[Screencast from 30-10-24 16:27:05.webm](https://github.com/user-attachments/assets/d3075431-82d4-47f8-bc17-b5d8ef1373af)

feat: share url in sql runner

---

packages/frontend/src/features/metricsCatalog/components/MetricChartsUsageModal.tsx
packages/frontend/src/features/metricsCatalog/hooks/useMetricChartAnalytics.tsx

Closes: N/A
After #12175 , we now request the charts that use a field on button click
https://github.com/user-attachments/assets/80dbe887-c149-4bb7-a786-94fb21f98d46

feat: get field analytics on button click

---

packages/frontend/src/components/NavBar/ExploreMenu.tsx

Closes: #12156 12156
If already on the SQL runner page, open New > Query using SQL runner in a new browser tab.

feat: open sql runner in a new tab if already on sql runner

---

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx

Relates to: https://github.com/lightdash/lightdash/issues/12167
Covers: 
1. Open metric' should open the explorer in a new tab.
2.  Is it easy to make tooltips stand out more? Either with a dropshadow or dark mode? Basically, it gets lost in the table and is hard to read.
3.  Copy change directory to table
demo:
https://github.com/user-attachments/assets/1710652d-c491-4667-96c7-db5f2c148abb

style: apply small ui/ux improvements (part 1)

---

packages/backend/src/App.ts

Commercial PR: https://github.com/lightdash/lightdash-commercial/pull/347
- adds ability to pass custom middleware functions to be used in express
- this will be used for the commercial repo to pass custom SCIM middleware

feat: added ability to pass custom middlewares to express

---

packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx

Closes: https://github.com/lightdash/lightdash/issues/12214
Uses table's state to track search and highlight accordingly
Demo
https://github.com/user-attachments/assets/933158da-a947-45d4-b45e-e9b5356ad0e2

style: enable highlighting on search

---

packages/frontend/src/features/metricsCatalog/components/MetricChartsUsageModal.tsx
packages/frontend/src/features/metricsCatalog/components/MetricsTable.tsx
packages/frontend/src/providers/TrackingProvider.tsx
packages/frontend/src/types/Events.ts

Closes: https://github.com/lightdash/lightdash/issues/12106

chore: track clicks on metrics actions

---

packages/frontend/src/components/DashboardTabs/Tab.tsx
packages/frontend/src/components/DashboardTabs/index.tsx
packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
packages/frontend/src/pages/Dashboard.tsx
packages/frontend/src/styles/droppable.css

Closes: 
https://github.com/lightdash/lightdash/issues/11213
Updated tabs according to the specs described in the issue. Appearance remains unchanged when tabs are not in use.

feat: updated dashboard tab appearance

---

packages/backend/src/scheduler/SchedulerWorker.ts

Closes: N/A
Wraps `setCatalogChartUsagesJob` with `tryJobOrTimeout`

chore: wrap setCatalogChartUsagesJob with tryJobOrTimeout

---

packages/frontend/src/components/DashboardTiles/TileForms/AddChartTilesModal.tsx

Closes: #12048
Description: Disable Add Button untill a Chart is Selected

feat: disable 'Add' button until a chart is selected

---

docs/docs/references/dimensions.mdx
examples/full-jaffle-shop-demo/dbt/models/events.yml
packages/common/src/schemas/json/lightdash-dbt-2.0.json
packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeProvider.tsx

Closes:  https://github.com/lightdash/lightdash/issues/11316

fix: allow multiple nested groups

---

packages/common/src/schemas/json/lightdash-dbt-2.0.json

fix: cli schema validation failure and e2e

---

packages/frontend/src/components/common/TagInput/TagInput.tsx

Closes:  https://github.com/lightdash/lightdash/issues/12211
Fix columns/rows paste from excel (libreoffice) and google sheets

fix: fix paste numbers from excel

---

examples/api/catalog.http
packages/backend/src/@types/knex-tables.d.ts
packages/backend/src/controllers/catalogController.ts
packages/backend/src/controllers/projectController.ts
packages/backend/src/database/entities/catalog.ts
packages/backend/src/database/entities/tags.ts
packages/backend/src/database/migrations/20241104105903_add-project-tags-table.ts
packages/backend/src/generated/routes.ts
packages/backend/src/generated/swagger.json
packages/backend/src/models/CatalogModel/CatalogModel.ts
packages/backend/src/models/CatalogModel/utils/parser.ts
packages/backend/src/models/ModelRepository.ts
packages/backend/src/models/TagsModel.ts
packages/backend/src/services/CatalogService/CatalogService.ts
packages/backend/src/services/CsvService/CsvService.test.ts
packages/backend/src/services/ProjectService/ProjectService.test.ts
packages/backend/src/services/ProjectService/ProjectService.ts
packages/backend/src/services/ServiceRepository.ts
packages/common/src/authorization/organizationMemberAbility.ts
packages/common/src/authorization/projectMemberAbility.ts
packages/common/src/authorization/types.ts
packages/common/src/index.ts
packages/common/src/types/catalog.ts
packages/common/src/types/tags.ts
packages/e2e/cypress/e2e/api/catalog.cy.ts

Closes: [#12232](https://github.com/lightdash/lightdash/issues/12232)
Adds endpoint to create/delete/list project tags.
- GET `{project_uuid}/tags`
- POST `{project_uuid}/tags`
- DELETE `{project_uuid}/tags/{tag_uuid}`
Adds endpoint to tag and untag catalog item:
- POST `{catalog_search_uuid}/tags`
- DELETE `{catalog_search_uuid}/tags/{tag_uuid}`

feat: add metric tags
